### ISSUE TITLE
Drag gray knob in modulation mode

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1004]
@mkruselj suggests some gesture (RMB, shift-mouse - lets see what's bound) to drag the gray knob in modulation mode. And we agree.

**Comment by mkruselj** [comment]
We can't drag the base parameter in modulation assign mode, buuuut we can set the new parameter value through typeins, so for the time being that is sufficient. I suppose this is as good as it's gonna get without an awful lot of complications with mouse interaction, so we might as well close this one?
