### ISSUE TITLE
VST3 Context Menus

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#101]
looks like the `vst3-contextmenu` ( https://github.com/kurasu/surge/tree/vst3-contextmenu ) is one commit ahead of the master branch. Which contextmenu was this fixing, @kurasu ?

here's a link to the commit https://github.com/kurasu/surge/commit/89d215f6ad7eef54971232435053301871f927cf

if anyone is moving towards building a vst3, maybe this commit is of use? @kzantow @JurekR @jsakkine @whydoubt @baconpaul

**Comment by kurasu** [comment]
This branch is about adding support for a VST3 specific feature for context menus. Essentially the plug-in can ask the host application to populate the context menu when the user right-clicks on a parameter in the plug-in GUI.

**Comment by esaruoho** [comment]
@kurasu now that the vst3sdk or vstgui or some upgrade is in, is this branch something that should be looked at, or was it like a grab of certain features in vst3sdk/vstgui? 

i have no idea :) @baconpaul any ideas?

**Comment by baconpaul** [comment]
Other than 'boy does that branch need rebasing' nothing comes to mind.

From the diff in the commit looks like vst3 has an API by which a plugin can ask a host for extra context menus, and that's what this does. That also matches what @kurasu said on Dec 18 I just realized!

So "nice to merge this in one day".

I guess we would test it by running surge in such a host. Wonder if nitwit 2.4.3 is such a host?

I'd leave this open.

**Comment by baconpaul** [comment]
Reviving this one. Evil says reaper supports it. That branch gives an idea of how the code would work. So lets give it a whirl, but probably by re-writing not by merging.

**Comment by baconpaul** [comment]
https://steinbergmedia.github.io/vst3_doc/vstinterfaces/classSteinberg_1_1Vst_1_1IComponentHandler3.html#details
