### ISSUE TITLE
Various statuses on display

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1021]
The synth is getting more internal state (like MPE, Tuning, etc...)

![image](https://user-images.githubusercontent.com/13387561/62940226-1b7be700-bda1-11e9-8b8c-157dd349e833.png)

We can put little tags here to show those.

**Comment by mortfell** [comment]
Thats a great idea

**Comment by baconpaul** [comment]
<img width="694" alt="Screen Shot 2019-08-16 at 9 25 53 PM" src="https://user-images.githubusercontent.com/13387561/63205051-a9d7bd80-c06c-11e9-8d0d-b40972db7ef2.png">

current wip for feedback

**Comment by baconpaul** [comment]
Implemented in #1038
