### ISSUE TITLE
Ctrl(Cmd) snap function on modulation assignments.

### ISSUE THREAD

**Issue by mortfell** [surge-synthesizer/surge#1024]
Noticed another small nerdy detail that could make things nicer for designing presets:
The Mousewheel and click+drag have modifiers shift (for fine control) and Ctrl(cmd) (for stepped control) on sliders. This is a great feature of the Surge interface for quickly entering fine a coarse values.

**Issue:**
When assigning a modulation source to a slider with the mouse-wheel or click+drag  "shift for fine control" works, but "ctrl(cmd) for stepped control" does not.
**Request:**
Being able to use the "stepped" control when making modulation assignments would be useful for a couple reasons:

**reasons it would be useful**

1. The interface doesn't allow assigning a modulation source to octave switches, so if you want to make a macro or modulator shift something in exact semitones or octaves it's pretty fiddley. The Stepseq gives you the option to set steps mapped to exact semitones, but it would be really useful for FM modulation stuff to have controls/modulation sources be able to quickly set stepped/exact pitch mod amounts.

2. On a lot of the parameters the "stepped" parameter option switches things between all the way off or all the way on... which is EXACTLY what you want a lot of the time when setting modulation amounts. Being able to hold ctrl(cmd) and quickly turn modulation sources all the way up or down with the mousewheel/trackpad would feel really cool I think. 

If this is easy enough to implement I think it would be a really nice workflow improvement for people who like making presets!

**Comment by baconpaul** [comment]
I was gonna ask what “steps” are for these continuous controllers with no particular internal physical representation. They are basically a 0-1 float representation of 0-127 int.

“0, half way, and 1” are good steps though. Easy enough to make that the default. Sound reasonable?

**Comment by baconpaul** [comment]
Oh and it is 5 lines to implement if we just agree on what we are implementing :). Lemme know if the 3-stop sounds right to you and I will bang it in sometime next few days.

**Comment by baconpaul** [comment]
Oh sigh for an annoying reason this is not 5 lines to implement, and is actually a bit annoying. May not be super duper easy.

**Comment by baconpaul** [comment]
Ha off that. Step one of every great change is to give up in defeat. I see how to do it and why these controls are different now. Not that hard.

**Comment by mortfell** [comment]
Haha cool.
I think the way the the control the step modifier works already (when moving sliders not when assigning sources) is perfect. Some have integer steps, some are on/off, some are -100, 0, +100.

So if there is a way to use those same increments in the modulation assign that would be ideal.

**Comment by baconpaul** [comment]
Ha double off that. No this is exactly as aggravating as I thought. May be a bit.

**Comment by mortfell** [comment]
oh dang, maybe not worth it.

**Comment by baconpaul** [comment]
Yeah
I could do it with control-doubleclick super easily though if that helps.

**Comment by mortfell** [comment]
Do you mean if you control-doubleclick a parameter you are mapping to a modulator  it would snap to the nearest stepped value?

**Comment by baconpaul** [comment]
Yeah exactly.

**Comment by mortfell** [comment]
yeah that would still be helpful for sure! The main problem was just the fidely mapping to pitch controls for me.

**Comment by mkruselj** [comment]
@mortfell We now have typing in direct values for modulation in nightlies.

@baconpaul Would still be nice to do bound_value on modulation sliders - what exactly makes this aggravating? Code hints requested. :)

**Comment by baconpaul** [comment]
Same thing as units really. Need to have the parameter know how to bind itself and then call in the right spot. I'll do it binding to .1 for all params then let you take it from there, sound good? Tagging this into 1.7 so I remember

**Comment by baconpaul** [comment]
Pushing a diff this morning.
This diff does two things, but leaves some stuff undone

1. Puts in place a quantization hook in Parameter, snapped to 0.05
2. Uses it for modulation on the slider when appropriate button pressed

There's some things we still need to do

1. Snap-jump the slider (it is continuous graphcis with quantized value)
2. Handle different type based modulation

The general plan with these things is that I will have to do #1 since there's a few tricky bits, and @mkruselj can do #2 now there's a clean API point, as shown in the diff above.

**Comment by mkruselj** [comment]
#3875 sorted out LinearWithScale and Decibel display types. Remains AToTheBx and certain custom types (FM ratio etc)...

**Comment by baconpaul** [comment]
Just merged a "good enough" implementation but if you want to keep hacking on it, go ahead! If you are happy though please just close the issue.

**Comment by baconpaul** [comment]
@mkruselj we want to do any more here?

**Comment by mkruselj** [comment]
Ah, sorry, I totally forgot to check out what you did there. I _think_ I would kinda want the snapping on Cutoff based parameters be in semitones rather than how it's now (but unsure how to go about it). Envelope times and LFO rate are fine. FM3 osc ratio seems to be not done.

**Comment by baconpaul** [comment]
Semitones are just integer snaps in range val_min to val_max.

so basically floor( input * (val-max + val-min))/(val-max + val-min)

**Comment by mkruselj** [comment]
OK so after #4090 the only one that seems to remain (as far as I can tell) is `ct_fmratio`. Should snap in integer ratio units, cover extended and absolute etc.

EDIT: I have just noticed that the regular Ctrl+drag (`Parameter::bound_value()`) is wrong in extended mode for this ctype (it doesn't snap to integer units as one would expect).

**Comment by mkruselj** [comment]
Some questions for @baconpaul:

1.

![image](https://user-images.githubusercontent.com/2393720/111869755-1b7e9880-8981-11eb-9877-c5ea7c0724e0.png)

Unipolar modulation source, only shows 31 as maximum modulation amount range when FM3 Ratio is in extended mode. But we have a range of 1/32 to 1:32 so that seems wrong?

2.

Do this please:

1. FM3 extended mode, double-click to reset to 1/1
2. Ctrl+drag to alternate between C : 2, 1/1 and 1/2
3. make a MSEG that does the same thing (see pic)

![image](https://user-images.githubusercontent.com/2393720/111869796-4e289100-8981-11eb-8f2c-cd461e3c17ce.png)

4. assign modulation amount of 1.0 - doesn't sound the same, sounds like it goes way more than one step. and even at 0.5 it sounds wrong (there's some beating happening)

![image](https://user-images.githubusercontent.com/2393720/111869805-5680cc00-8981-11eb-8f52-fc65710adfe9.png)

Seems that in extended mode, where we have 32 steps on either half of the slider, I'd expect that 0.5 is exactly one ratio increment, but above pic shows otherwise. Why is this?

**Comment by baconpaul** [comment]
Oh on your first point @mkruselj : 31 is correct. The range of the slider is 0 -> 32, which is really from 1/32 -> 32 with the center at 1.  So from 1/1 -> 32/1 is actually a mod depth of 31.

Or thought of another way: The range of the slider *is* in fact +/- 31. 1/32->1/1 == a spread of 31; and 1/1 -> 32/1 is a spread of 31.

Will look at the rest today.

**Comment by baconpaul** [comment]
Oh, Your 4th point is the same. 1 + 31/32 = 1.968750

We can fix a lot of this by changing the modulation depth display to not be fractional but the math is correct internally (the stringification is not).

**Comment by mkruselj** [comment]
Does it make sense to then write it as C:31 or 1/31 perhaps? Or is that complicating things too much?

**Comment by mkruselj** [comment]
Oh also I only had 3 points but had neested numbering. Edited my post for clarity. :slightly_smiling_face:

**Comment by baconpaul** [comment]
Well it *is* c 32 as a value. The question is how we display differences 

so yes my rough plan is to show all the modulation depths in units of frequency span. So your 0.5 internal value would render as dC: 0.98675 in the ui or some such and if you typed in a modulation of 2 it would set it so to 2/31 or what not. Will work out the right thing

**Comment by mkruselj** [comment]
Lovely!
