### ISSUE TITLE
Some old presets simply don't load

### ISSUE THREAD

**Issue by koozin** [surge-synthesizer/surge#1026]
**Describe the bug**
I'm trying to load some old presets on surge and some of them load, some of them not. Surge doesn't . I've put all of 'em on Documents>Surge folder.
**Please let us know your surge version**

* Surge Version: Version 1.6.1.1
* Plugin type (VST2, 3 or AU) AU
* Bits (32/64) 64 bits

**Desktop (please complete the following information):**
 - OS: MacOSX 10.13.6
 - Host: Logic Pro 10.4.5

**Additional context**
It looks like the ones that doesn't load are very old presets. I'm not sure about that. I'm attaching 2 examples of some old presets that I have, one that loads and another that don't.

[Presets.zip](https://github.com/surge-synthesizer/surge/files/3503860/Presets.zip)

**Comment by baconpaul** [comment]
Thanks. I’m actually in that code now so can look. There’s been no change to this code since it was open sourcedz how old are these?

**Comment by baconpaul** [comment]
So your "this doesn't" isn't a surge patch it doesn't seem. The contents are just "sEDU" with a string of 0 binaries strung after it repeated over and over. An .fxp file contains a standard header and then if it is for surge contains the string `sub3` at position leading up to byte 0x100 when you do an od -c

Do you have others that don't load?

(The one that does load is indeed one version old - soon to be two versions old - probably from surge 1.5 or so from reading the source)

**Comment by koozin** [comment]
> So your "this doesn't" isn't a surge patch it doesn't seem. The contents are just "sEDU" with a string of 0 binaries strung after it repeated over and over. An .fxp file contains a standard header and then if it is for surge contains the string `sub3` at position leading up to byte 0x100 when you do an od -c
> 
> Do you have others that don't load?
> 
> (The one that does load is indeed one version old - soon to be two versions old - probably from surge 1.5 or so from reading the source)

Yeah, actually I looked through the codes too, although I don't fully understand them and I noticed that too. Strange thing is, I was using 1.5.3 version and they were working as expected.

New update: Probably files got some corrupted while copying files from the old folder to the new one. Fortunately I had a backup. Anyway, tks ur time.

**Comment by baconpaul** [comment]
OK thank you!
