### ISSUE TITLE
"Root" FM Routing configuration

### ISSUE THREAD

**Issue by mortfell** [surge-synthesizer/surge#1028]
With regards to conversations in the Surge Slack channel:
Letting OSC 3 modulate both 1 and 2 in root configuration rather than stacked would allow some more classic FM configurations:
1<3>2

This would require a small change to the GUI, but there is room in the FM routing area. @baconpaul said the DSP would be easy.

**Comment by baconpaul** [comment]
Yeah this one is pretty straight forward. I’m using it toninaugaurste the 1.6.3 milestone :)

**Comment by mkruselj** [comment]
And I'm inaugurating it to the 1.7.n milestone. Magic! :P

**Comment by mkruselj** [comment]
And also let's see if we can actually make it happen for 1.9. 😝

**Comment by mkruselj** [comment]
Closing this issue in favor of #1031!
