### ISSUE TITLE
Sin modulator could self modulate 

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1030]
You know those boxes that point to themselves on dx7 algos and their kin? They are tricky to do in general in surge. But the sin oscillator could add a parameter self-modulation which scaled that feedback loop on that osc.

**Comment by mortfell** [comment]
I am loving the weird sine shapes since you brought them up! Very unique sounds to be made with those. I am guessing strange stuff can happen when those weird since shapes feedback on them selves.

**Comment by baconpaul** [comment]
OK this one was too much fun to wait on. So I have added it. This issue will auto-close when I sweep the code.
