### ISSUE TITLE
Unison for the SIN oscillator

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1034]
No reason at all we can't have unison on this oscillator. Now it is getting FM-fun and weird shapes may be good to listen to.

**Comment by mkruselj** [comment]
Agreed, makes sense to have it!

**Comment by baconpaul** [comment]
So ere's how to do it if we are only doing it for non-legacy mode

1. osc_sine::init_ctrltypes add p[3] with name "Unison Detune" and p[4] with "Unison Voices" with types ct_oscspread and ct_osccount respectively. Immediately below initialize them with p[3].val.f = 0.2 and p[4].val.i = 1;

2. In Oscillator.h, copying from AbstractBlitoperator copy the proprtypes for prepare_unison, the float out_attenuation line to the osc_sine declaration around like 65. Also copy the panL and panR members

3. change phase to phase[MAX_UNISON] in the .h

4. copy SurgeSuperOscillator.cpp function AbstratctBlitOsc::prepare_nison to Oscillator.cpp and name it osc_sine::prepare_unison. (Later we should combine these but for now copy and paste)

Now you will get all sorts of compile errors that things aren't indexed properly. That's OK. Our job is to start putting in unison.

1. In osc_sine::init call prepare_unison at the top with oscdata->p[4].val.i (or whatever the count is) and store that count as a member

2. Change phase = 0 to for i=0; i<nunsion; ++i phase = 2.0 * M_PI * rand() / RAND_MAX

in process_block put an inner loop over unison appropriately. That is

for k=0 to block size
  for u = 0 to nunison
    auto p = phase[u] + lastvalue[u] <-- last value will have to be changed in the header too

most importantly you need to put the stereo handling inside there along with the attenuation. That is use the pan and attenuate you set in prepare unison to adjust the output

test!

**Comment by mkruselj** [comment]
Following those instructions (and some more hand-holding on Slack), I got pretty close to something workable!

It's all in my forked branch here: https://github.com/mkruselj/surge/tree/ed-sineosc-work
