### ISSUE TITLE
Support TUN files

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1042]
With #828 wrapped up we probably want to support .tun as well as .scl files

https://www.mark-henning.de/files/am/Tuning_File_V2_Doc.pdf

In 1.6.3 though

**Comment by baconpaul** [comment]
This is a way more ambitious and painful spec. So maybe we just won’t do it!

**Comment by MBYlt** [comment]
AnaMark Tuning Library (aka the .tun specification) is now on GitHub: https://github.com/zardini123/AnaMark-Tuning-Library

**Comment by baconpaul** [comment]
Oh interesting
Thank you

**Comment by baconpaul** [comment]
https://github.com/zardini123/AnaMark-Tuning-Library/issues/2 I dropped them a note to see if they want to collaborate with us.
