### ISSUE TITLE
Tuning “lock” rather than popup

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1044]
Right now in the tuning state diagram if you have a tuning applied and you load a patch which has a tuning persisted, you get a popup about whether you want to keep your current or apply the patch tuning. 

On slack folks pointed out that Serum and u-he implement this choice by a “lock” icon on tuning rather than a prompt. That’s probably a good idea if people end up using this a lot.

Recording this as I closes #828

**Comment by SeanArchibald** [comment]
As somebody who uses a lot of microtonal-capable synths, I can confirm from my view that this suggested feature is a significant quality of life improvement. Thanks baconpaul!

**Comment by baconpaul** [comment]
Oh thanks for the feedback!

Can you give the current nightly a try and see how our current implementation compares to other synths in your microtonal workflow? Feedback and testing would be super useful!

**Comment by SeanArchibald** [comment]
I can test this but I will struggle to get the nightly compiled - I'm not really set up for that or knowledgeable about that. Is there any way I can grab a Linux VST binary for testing?

**Comment by baconpaul** [comment]
Oh yeah we make a binary of the nightly available with every commit to master at https://surge-synthesizer.github.io/

**Comment by SeanArchibald** [comment]
I have installed the nightly build and quickly played about with it on my backup computer. So far so good! I'll need to get this installed on my main music computer some time to really put it through a good test session.

When I switch between preset patches the tuning does remain "locked" which is great. Is this the expected behaviour? Does the patch have to specify a tuning in order for the popup to appear?

**Comment by baconpaul** [comment]
Yeah here's the behavior

If a patch contains no tuning, don't change the tuning state (so stay locked)
If a patch contains a tuning, but you are currently in standard tuning, apply the tuning state
If a patch contains a tuning, but you are in non-standard tuning, pop up the question

To make a patch with tuning in it, set a tuning and store a patch, and when you store a patch, click the (new) "store tuning in patch" button. You can choose as a patch designer whether the tuning is integral to the patch or not. The default is no.

**Comment by baconpaul** [comment]
Oh and currently no factory or third party patches contain tunings

**Comment by mkruselj** [comment]
Resolve this issue (and remove the dialog that pops up when loading a patch with tuning over existing non-12TET tuning) with two menu options in Menu->Tuning:

```
On patch load > Keep current tuning
                Override with tuning stored in patch (if available)
```

Truth table for tuning load:

```
CT - current tuning
PT - patch tuning
OD - override tuning menu option yes/no
RES - 1 for executing loading tuning from patch

CT PT OD  RES
0  0  0   0
0  1  0   0
1  0  0   0
1  1  0   0
0  0  1   0
0  1  1   1
1  0  1   0
1  1  1   1
```

Have the same menu options for KBM, too, actually.

**Comment by mkruselj** [comment]
@baconpaul also suggested adding an option "Set to patch-embedded tuning" option to the Tuning menu, in case there is one. This would serve as a fallback in case the user set both tuning/mapping options to keep their current tuning.

![image](https://user-images.githubusercontent.com/2393720/145731794-ebf4eb57-d682-419e-b991-674b2c76c85b.png)

Add a separator after "Set to standard scale" and add the two options for patch-embedded tuning/mapping afterwards.
