### ISSUE TITLE
Support MIDI tuning standard

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1045]
There’s a midi tuning standard - we discussed it in #1025 and the document is there, even though what the user needed in that issue wasn’t full midi tuning.

I don’t know if I want to implement it in surge. But want an issue open so I remember the conversation. This one has no current milestone attached.

**Comment by mkruselj** [comment]
@baconpaul Closing this issue in favor of [the same issue opened for tuning-library](https://github.com/surge-synthesizer/tuning-library/issues/26). If tuning lib gets it, Surge gets it too.
