### ISSUE TITLE
Tuning with very short scales interacts oddly with oscillators

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1051]
With this tuning

1. DXEP is fine
2. The Wavetable Oscillator is off by several octaves
3. The sawtooth classic oscillator has a delay as you go down the keyboard

Why?

```
! 05-19.scl
!
5 out of 19-tET
 5
!
 252.63158
 505.26316
 757.89474
 1010.52632
 2/1
```

**Comment by VincyZed** [comment]
Seems like the more tones in the scale, the lesser the delay.

**Comment by baconpaul** [comment]
Yeah I think the delay is a function of the frequency shift so a short scale implies big shift 

Should be easy enough to debug. Really appreciate the testing!!

**Comment by baconpaul** [comment]
So the delay is a function of note onset only (obviously). If you are running the oscillator and toggle tuning with the tun button the note shifts but doesn't add the delay. I'm suspicious of the calculations using 8.175etc... as a constant in the oscillators.

**Comment by baconpaul** [comment]
Hey I found the problem with square and sawtooth at least. Potential fix for that coming.

**Comment by baconpaul** [comment]
s&h noise has the same problem by the way. Will fix that one too.

**Comment by VincyZed** [comment]
Awesome!

**Comment by baconpaul** [comment]
Got them all fixed. PR coming. This issue will close when it is swept.
