### ISSUE TITLE
Adjusting Master Volume: Causes master out to become non responsive  and quiet

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#1052]
This video captures what I am seeing well for steps:

This is in Cubase Pro 10 VST3. 

<img width="703" alt="Screen Shot 2019-08-18 at 5 03 33 PM" src="https://user-images.githubusercontent.com/11078351/63230948-263bdf00-c1da-11e9-89f2-02f9e31edd1d.png">

Repro Steps In Video Here

https://www.dropbox.com/s/lsfy7t9ctdpi1dy/master_volume.mp4?dl=0

I have to remove the Surge instance and then re-add it to get back to normal. Happens with the default patches too.

**Comment by baconpaul** [comment]
So alas with the VST3 in bitwig or the AU in logic I don't see this behavior.

Is Cubase recording any automation when you move the master volume? Master volume is supposed to be non-automated. I wonder if the VST3 is throwing some message you don't expect?

**Comment by itsmedavep** [comment]
Not recording anything via the GUI. 

If you look in the video along the upper edge, there are two buttons. One with R for read , and one with W for write. 

Neither is enabled, meaning read and write is disabled for GUI automation.

**Comment by baconpaul** [comment]
OK thanks! So clearly "something is afoot with the vst3 in cubase"

I'll figure out a time to download a demo and look!

**Comment by itsmedavep** [comment]
If there is anything I can help with please let me know. Happy to help out!

**Comment by baconpaul** [comment]
Oh shoot I'm getting a 404 on that video - is it still around?

**Comment by baconpaul** [comment]
Oh never mind. I can reproduce it in LE instantly.

**Comment by baconpaul** [comment]
And it does NOT happen in REAPER so this is a Cubase only oddity. Fun! I wonder what it will turn out to be?

**Comment by baconpaul** [comment]
FX return does the same thing. It's all about the remapping somehow confusing things.

**Comment by baconpaul** [comment]
And now I've found it! Yay!
