### ISSUE TITLE
Realtime Render: VST3 and Cubase had to realtime render to get GUI automation to render into audio

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#1054]
Build Surge with the latest from source (as of today)
Launch Cubase 10 Pro and add a Surge instance
Change OSC type to sine
Automate Surge via the GUI and record in Cubase
Export audio mixdown (24 bit 44,100 wave)

Notice your GUI automation is not rendered to audio. 

Do the same thing but use real time audio export and you now have the GUI automation rendered to audio.

**Comment by baconpaul** [comment]
OK this is either a Cubase or a VST3 issue. I set up a track in logic where I parameter automated the sine wave shape and rendered the audio non-realtime and got the control no problem.

Hmm. Dave - do you have another VST3 host you know well? If not I can test it in bitwig quickly but will need to learn some more bitwig to actually - you know - do the thing that took me 20 seconds in logic :)

**Comment by itsmedavep** [comment]
@baconpaul Im not really super familiar with other VST3 hosts BUT could likely get Reaper to try something out with.

What is it that you would like me to test out?

**Comment by baconpaul** [comment]
Yeah I can figure it out also. Just wondering if you had another one where doing that would take 20 seconds rather than 5 minutes.

**Comment by baconpaul** [comment]
OK confirmed that Reaper VST3 acts just like Logic AU, namely: does not require realtime.

So this is a cubase problem. Sigh.

**Comment by baconpaul** [comment]
Hey @itsmedavep if you could check this in a new nightly that would be super appreciated. Or let me know how I would test it since I don't know cubase well :)

Thanks

**Comment by itsmedavep** [comment]
Tested and this looks good~ TY!

**Comment by baconpaul** [comment]
Awesome
