### ISSUE TITLE
Copying and pasting wavetable oscillators sometimes does not work properly

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1060]
**Bug Description**
When pasting certain wavetables in an oscillator after copying them from another oscillator, the result is not the same as the first one.

* Surge Version: Latest Nightly
* Plugin type: VST3
* 64 bits

**To Reproduce**

1. Open an instance of Surge
2. Set the type of the first OSC to Wavetable
3. For example, select the wavetable "bells" under the "rhythmic" category
4. Morph through the wavetable to see expected result
5. Copy the first oscillator (right-click on the "1" button at the top of the display)
6. Paste it on OSC 2 (right-click on the "2" button at the top of the display)
7. Go on the second OSC and morph through the wavetable. It is not the same content as the first OSC.

**Expected behavior**
It should behave like the first OSC we copied the data from.

**Screenshots**

OSC 1 (the one we copied from)

![image](https://user-images.githubusercontent.com/50145178/63315999-561edb80-c2db-11e9-80fe-95ec9e2d6135.png)

OSC 2 (the one we pasted data from 1)

![image](https://user-images.githubusercontent.com/50145178/63316008-5dde8000-c2db-11e9-87bd-451d28300202.png)

**Desktop config:**
 - OS: Windows 10 x64
 - Host FL Studio 20.5.1

**Comment by baconpaul** [comment]
I've confirmed this is a bug in 1.6.1.1 as well; which is good. It means my .wav file changes didn't introduce it. But also is bad. It means I have more code to look at to figure it out :)

Thanks for the accurate bug report.

**Comment by baconpaul** [comment]
Oh geez - it's super clear in the code

SurgeStorage::clipboard_paste in the cp_osc block just ignores the wavetable on the clipboard. Should be an easy fix.

**Comment by baconpaul** [comment]
OK this bug was introduced between 1.6.0 beta-9 and 1.6.1.1 

Looking at the "copy" code I think it is that the "copy" code doesn't deal with dynamic wavetables properly.

**Comment by VincyZed** [comment]
Confirmed, it works now! 

The only thing is that the name of the selected wavetable from the copied OSC does not appear after pasting, instead it says the generic "(Patch Wavetable)" name.

**Comment by baconpaul** [comment]
Yeah that’s right; cloning makes an in memory copy and loses affiliation with the on-disk image. Just like if you save your state in the DAW and then re-open it. 

I’ve occasionally thought about fixing this (like store an ‘original name’) but that’s a bit deceptive. It is a wierd behavior though I agree.

**Comment by baconpaul** [comment]
(I think the fundamental reason for this - that surge stores the *contents* of the wavetable in the patch rather than the *reference* - is absolutely correct behavior. It’s just the display name issue)

**Comment by VincyZed** [comment]
OK, sounds good, not really important after all!

**Comment by VincyZed** [comment]
Copying and pasting oscillators now **always pastes OSC 1** to whatever destination you paste to. Probably a side-effect to the fix above.

**Comment by VincyZed** [comment]
Copying with modulation does seem to work fine though.

**Comment by baconpaul** [comment]
Huh the fix above wouldn’t do that but could easily be another bug! I’ll look

**Comment by baconpaul** [comment]
can reproduce though. Will look!

**Comment by baconpaul** [comment]
```
        char txt[256];
         sprintf(txt, "Osc %i", a + 1);
         contextMenu->addEntry(txt, eid++);
         contextMenu->addEntry("-", eid++);
         addCallbackMenu(contextMenu, "Copy",
                         [this]() { synth->storage.clipboard_copy(cp_osc, current_scene, 0); });
         eid++;

         addCallbackMenu(contextMenu, "Copy (with modulation)", [this, a]() {
            synth->storage.clipboard_copy(cp_oscmod, current_scene, a);
         });
         eid++;
```

Can you spot the bug? (I can!)

**Comment by baconpaul** [comment]
Anyway, pull request in
