### ISSUE TITLE
Should patch wavetable retain name if there?

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1065]
A wavetable has a source often and that source has a name.

If you copy it or stream and upstream it the name becomes patch-wavetable

The contents decision here is absolutely correct. Store the wavetable data in the patch, not by reference.

But I wonder if we want to perhaps also store the name of the original source so we could make a display something like "(patch - from 'bells')"

I don't know if I like this idea so just gonna drop it here as an unmilestoned issue, but it relates to #1060

**Comment by mkruselj** [comment]
I would love it for wavetable filename to be shown on the display even after loading the preset again.

**Comment by mkruselj** [comment]
As menitoned on Slack, wavetable filename should be displayed when drag&dropping a wavetable too, and also streamed!

**Comment by baconpaul** [comment]
When we do this export could use the name too by default

**Comment by baconpaul** [comment]
Since #1598 means I need to open up the patch format for 1.6.6 I might as well do this one also
