### ISSUE TITLE
Type-in for Parameter Values

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1071]
On Slack we were discussing a type in for a parameter change

Right now, we have on the RMB a "value 0.23" which is display only and does nothing. That menu item could launch an editor easily. So here's how you would do it

1. Write a VSTGUI popup which you could call. This is tedious but we can do it the same was as the store dialog basically.

2. Once that is done add to Parameter.h `bool can_parsestringvalue()` which has initial implementation of "return false". Add a method called `bool parsestringvalue( std::string & )` which has initial implementation of "return false"

3. In SurgeGUIEditor make that value 1.23 menu item check can_parsestringvalue and if so then get a string value and call parsestringvalue.

4. On a type-by-type basis implement parse_stringvalue and so on so.

```
can_parsestringvalue
  switch type
     case ct_percent:
         return true
  return false

parse_stringvalue
   switch type
       case ct_percent
          set value(atoll(s.c_str())
```

parse_stringvalue is essentially a type-by-type inversion of the format parameter code.

**Comment by baconpaul** [comment]
Oh presume you could do this for modulation values also just with a slightly different menu structure

**Comment by mortfell** [comment]
Ahh being able to do this with modulation would be a more elegant way to fix this issue If assigning pitch values with more precision in #1024

**Comment by mkruselj** [comment]
I'd kinda like to double-click on parameter name to type its value (because double-clicking on the slider is already reserved for defaulting the control). However, Ctrl+click on the slider is doing the same thing! So we have two mouse actions that do the same thing now.

I propose two menu options for this, mutually exclusive:

* Dbl-click reset to default, Ctrl+click type in value
* Dbl-click type in value, Ctrl+click reset to default

**Comment by baconpaul** [comment]
Yeah I spoke with @itsmedavep about this some too. I think if I get the experimental branch to work we need to have a sort of coherent thought session about the know and slider both - and I agree quick action to type in and jog is key.

**Comment by baconpaul** [comment]
Knob
Because we will get a knob post experimental too

**Comment by baconpaul** [comment]
OK @mkruselj when I merge #1831 we will be ready to start working. Here's what you want to do

- In the UI RMB/Value on something. If it pops up as unsupported now you have a job!
- Find out the ctrl_type by looking in SurgePatch for the variable. It will be ct_decible_whatzit or something
- In parameter.cpp look fro that ct_ and you can see how it goes from value -> string in getdisaplvalye
- so now we need to write the inverse of that and activate it
- so in Parameter::can_setvalue_from_string add the type to the list of supported types. As soon as you do this you will be included in the retests (more in a second on that)
- in Parmeter:;set_value_from_string undo the stringification. A few examples there. Basically turn it into a number then undo the math.
- Once you've done that compile. Does the UI basically work now?
- If so, then run the regtests by running surge-headless. This will test your inverse function on 100 or so random values
- if that all works, move onto the next control

**Comment by VincyZed** [comment]
Been testing this new features, and it works great! 
However I found the following bug:

After invoking the Type in value box, if the value is not changed, pressing enter won't close it (e.g. if it's set to 20.0%, you open the box and just press enter to close it, it won't close, or if you erase it and type 20.0% again, it won't close either) When writing 20.1% for instance, it will close.

**Comment by baconpaul** [comment]
yeah sorry like I said on slack: The GUI is absolute garbage and its just there so we can start writing the parameter inverters. This one - plus the terrible look and feel generally and the bad colors and fonts and so on - are all things we have to do.

But I wanted to get it into evil's hands so he could start writing string inverters for the other types.

**Comment by VincyZed** [comment]
No worries, just wanted to put it out there just in case :)

**Comment by baconpaul** [comment]
just fixed the more egregious of these problems. pushing now.

**Comment by baconpaul** [comment]
Edge cases I'd like to see somehow resolved (pointers welcome!):

right now typing -inf into the ct_amplitude types does work, but it would be super-nice if it also recognized -oo as the same as -inf
right now if you type a value lower than -192.00 dB for ct_amplitude it will clamp to the minimum value and show it in the context menu (instead of showing -inf). the main problem here is that it doesn't return false if you type a value below -192 dB, not sure why
Send FX levels are also using ct_amplitude type but they have a larger range (multiplied by 1.5874 in SurgePatch.cpp), which created some problems, I had to special handle the case when you type 12 dB because it didn't work (I assume float inaccuracies). it should've been a separate ctype, but not sure if adding a new type now would mess stuff up
it would be mega-awesome if we could parse k as a thousands multiplier when entering frequencies in Hz. i.e. 5.67k, 0.35k, 16k and so on

**Comment by baconpaul** [comment]
Above is from #1868

**Comment by mkruselj** [comment]
Would be nice if the user types in an invalid entry, that the text remains focused for reentry. Right now you need to reselect text manually to reenter.

**Comment by mkruselj** [comment]
Master Volume type in in top right corner is cut off beyond the UI frame. Same situation will likely happen when typein is added to Split Key parameter on the other side.

![image](https://user-images.githubusercontent.com/2393720/81702093-23b99d80-946b-11ea-98ed-8f980f7db9f3.png)

**Comment by mkruselj** [comment]
Also the text "Invalid entry" could be in a different color temporarily, perhaps?

**Comment by baconpaul** [comment]
- [ ] if you press enter in an invalid entry without having changed it it dismisses due to that vstgui focus handling on enter.

**Comment by baconpaul** [comment]
- [ ] can put range at bottom of type in a small font i bet.

**Comment by baconpaul** [comment]
- [ ] click away to dismiss

**Comment by mkruselj** [comment]
- [ ] Maybe additional method of calling up the typein without visiting the context menu, like middle mouse click?

**Comment by baconpaul** [comment]
- [ ] typein modulation values

**Comment by mkruselj** [comment]
> typein modulation values

...by adding a new entry in the context menu, only available when mod assign mode is active. Because the current typein still works to change the underlying parameter value, which is GREAT because we cannot do this with the mouse currently

**Comment by mkruselj** [comment]
- [ ] Recognize note name input on: Split Key, Keytrack Root, any Hz based control that also shows the closest note pitch.

**Comment by VincyZed** [comment]
Just found a small bug with the new Type-in for modulation amount:

We can type-in modulation amount values that go outside of the traditional limits when dragging the blue sliders to set mod amount. This creates arguably unwanted modulation behavior.

**Comment by mkruselj** [comment]
- [ ] Modulation amount typeins aren't being rescaled for extendable parameters

- [ ] When a mod amount typein is open, and that same mod amount slider is tweaked, shouldn't the value in the typein also update?

**Comment by mkruselj** [comment]
- [ ] Opening Store Patch dialog should close any open typeins

![image](https://user-images.githubusercontent.com/2393720/82734161-38bee800-9d19-11ea-98e5-53d2b8ef9fbb.png)

**Comment by mkruselj** [comment]
![image](https://user-images.githubusercontent.com/2393720/82740706-8eac8380-9d4b-11ea-8753-2bcccdf28100.png)

When the text is focused for input in the typein, the background of the selected text (in the above image it has the same color as the background of the typein rectangle), goes over the black borders of the rectangle.

**Comment by baconpaul** [comment]
that doesn't seem to happen on mac fwiw. lemme check lin.

**Comment by VincyZed** [comment]
I see this too. It does disappear when clicking outside this box (when the editing field is no longer in focus and text cursor disappears).

**Comment by baconpaul** [comment]
I shared a fix with @mkruselj last night that he is gonna push through with some other changes
