### ISSUE TITLE
Crash when instantiating a reverb preset on send 2

### ISSUE THREAD

**Issue by mortfell** [surge-synthesizer/surge#1076]
This isn't a great bug report, but I thought it would probably be wortf anyway.

Had the most recent Surge VST2 crash Ableton Live 10.1 on Mac OS Sierra when adding a reverb preset last night. Only bug I've experienced in the last couple days.....

I haven't been able to reproduce it so far, but I'll post here again if something similar occurs.
I had been working on that particular sound for around 40 minutes and had tried various configurations of effects and modulations.
Including the dump from Ableton Live in case there is any useful information to be gleaned!

[surge crash ableton live.txt](https://github.com/surge-synthesizer/surge/files/3535779/surge.crash.ableton.live.txt)

**Comment by baconpaul** [comment]
Oof crash in the idle thread. That’s not awesome. Very useful to have that info tho thanks.

Do you remember which reverb preset you tried?

**Comment by mortfell** [comment]
I am fairly certain the preset was "Long 2"

**Comment by baconpaul** [comment]
Thanks!

And yes stack traces always help!!

**Comment by baconpaul** [comment]
Hmm ... no luck reproducing this. Has it come back for you at all?

**Comment by baconpaul** [comment]
Gonna close this one; presume it has not reproduced for you yeah?

**Comment by mortfell** [comment]
nope
