### ISSUE TITLE
Incorrect ranges in "Set controller to..." menu

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1082]
![image](https://user-images.githubusercontent.com/2393720/63974380-03001200-caad-11e9-97c0-bca33fd73a33.png)

Should be:

0-19
20-29
30-39...

**Comment by esaruoho** [comment]
I remember fixing this stuff only for it to be wrecked by the ”no no no, wrong CC availability disable all we dont want” brigade.

**Comment by baconpaul** [comment]
Ahh yeah #552 

Well I was just gonna fix the off by one error here and close this one. The other issues are all still open. And hi! Long time hope all is well etc
