### ISSUE TITLE
Reaper Ubuntu 18.04 - Resize problem

### ISSUE THREAD

**Issue by EnGeeMoon** [surge-synthesizer/surge#1085]
**Describe the bug**
Changing the size making the extending size invisible.

**Please let us know your surge version**

* Surge Version: Surge-linux-x64-NIGHTLY-2019-08-29
* Plugin type (VST2, 3 or AU): VST2
* Bits (32/64): 64bit

**To Reproduce**
1. Insert a new Virtual Instrument in a new track
2. Choose VSTi Surge
3. Click on Menu/Zoom ... to any % other than 100
4. You get a cropped image of Surge

**Expected behavior**
A zoomed version of Surge

**Screenshots**
see Bellow:

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Host: Reaper 
 - Version 5.983

![Surge 125% Reaper 5 983 Ubuntu](https://user-images.githubusercontent.com/54669479/64055740-97b85c00-cbe2-11e9-97df-996a57019e29.png)

**Comment by baconpaul** [comment]
Hi.

Yes we know about this. I was unable to fix it, but the VST3 (which ships with the nightly) works with the latest reaper on linux just fine and also supports zoom. So I’m going to close this as a dump of #937 

If the VST3 doesn’t work for you please do let us know!
