### ISSUE TITLE
Wide mode should be routing set in default preset

### ISSUE THREAD

**Issue by mortfell** [surge-synthesizer/surge#1086]
This is a request related to ease of use. Especially for new users!
I think this could be good to include for 1.6.2 as the new features of Surge will surely attract some new users.

Currently the default filter routing on the default patch is S1 (Serial 1), there is four reasons I think width would be better as a default starting point for most users these days.

**REASONS:**
![Screen Shot 2019-08-31 at 11 39 58 AM](https://user-images.githubusercontent.com/4732794/64066828-44dfa400-cbe4-11e9-8406-e99ff523b42e.png)
 1. Enabling unison does not create a stereo signal in serial 1 mode. This is confusing for new users as this isn't how other software works.
2. You can't pan sounds using the mixer in Serial 1 mode. 
3. The feedback knob doesn't do anything in Serial 1 mode. I don't think the default layout of a synth should have non-functioning sliders. 
4. the width knob is non-existent  (see above)

**Describe alternatives you've considered**
I already use my own default starting preset, but this is mostly out of concern for new users. I had a bit of trouble understanding the filter block when I first used Surge.... and I'm a plugin enthusiast with lots of experience in software synthesizers. 

**Additional context**
In the manual it mentions that "Serial 1" is more CPU efficient because it doesn't have feedback enabled, but given the power of the average computer at this moment in time this is sort of a non-issue. 

It's a little confusing to have whether or not a sound is mono or stereo be determined in the filter routing section. I've seen multiple posts of people confused about why they can't pan sounds or why unison isn't in stereo.

The filter routing is really powerful, but you can only take advantage of the power once you understand it. For someone coming to this synth for the first time I think the Width mode is the filter block routing that makes the most sense right now.

If anyone disagrees or has any thoughts on this, would love to hear!

**Comment by baconpaul** [comment]
How do you pan using the mixer in wide mode?

I have no objection. If we do this then I will probably set up velocity sensitivity at not zero in the default patch at the same time

**Comment by mortfell** [comment]
Ah yes, I just noticed it the other day

In Wide mode it seems that all oscillators ALWAYS pass through both filters. Changing the little green switch underneath mute and solo either sends the oscillator all to the left or all to the right.
(the filter balance slider still changes the balance between the two filters)

Which now that think about it is another case where the interface doesn't properly reflect whats happening, because you still get a little tooltip saying "both" "filter 1" or "filter 2" when it's actually just changing left or right

**Comment by baconpaul** [comment]
I'm still pondering this, by the way. I would sort of rather have a better set of init templates and keep the current init in place, just from a code, manual, and user experience stability point of view. I agree the default patch is a bit wonky but something about changing this late in the 1.6.2 cycle makes me nervous in a way which isn't quite logical but ....

would you mind if I pushed this to 1.6.3?

**Comment by mkruselj** [comment]
A better solution to this would be to stereoize the filters, so that all the different filter routing modes still work the same way, just in stereo. Then the mixer filter routing would make sense too, instead of panning L/R in some modes and not in others.
