### ISSUE TITLE
Longer one-shots crashing VST3i and VSTi on Windows 10

### ISSUE THREAD

**Issue by mortfell** [surge-synthesizer/surge#1087]
I've tried loading one-shots in the past, and noticed there was a size limit. 
The other day I noticed that in a recent version of Surge we can now import longer Wavs as one-shots. Tried this on Mac and it worked fine.
Loading longer one-shots on Windows however.... crashes Reaper and Ableton Live .

One-shots of the size which previously worked is fine, but larger ones crash instantly.
As examples:
this still works fine on windows and mac:
[poor lil guy.zip](https://github.com/surge-synthesizer/surge/files/3562979/poor.lil.guy.zip)
this crashes on windows:
[Snare-VSCO.zip](https://github.com/surge-synthesizer/surge/files/3562978/Snare-VSCO.zip)

I'm using the latest nightly (Aug 29 2019) 
REAPER and Ableton Live
VSTi and VST3i
Windows 10 64 bit

I'm not getting any error or anything, instant crash
If there is anything else I can do to provide better info let me know!

**Comment by baconpaul** [comment]
Thanks - bet it will be easy to find. I’ll look this week

**Comment by baconpaul** [comment]
You know how I always say "good bug reports make good software"? Well I think I'll print that on a friggin mug after this one. The particular edge case here doesn't matter that much, except that it was only a small set of .wav files which would have caught it in quite the way you found here, and order of operation matters, and your case was a great reproduction.

Anyway the 17 character (!!) fix is making its way through the pull request and CI process now.

Thank you for this report.
