### ISSUE TITLE
Starting some Wikis for instruction articles on Surge.

### ISSUE THREAD

**Issue by mortfell** [surge-synthesizer/surge#1090]
Hey 
Just wanted to check in if It's ok if I start some Wiki pages on here!
It seems like the "markdown" format would be a pretty ideal way to make some brief instructional content, and it could also link to videos (if I get around to making them) and download links for session files etc.

Right now I'm specifically thinking of:
#1005 and #1078 
So making wikis on :
- Using Surge as an effect (and Vocoder)
- Creating Wavetables for Surge

I've done a lot of messing around with these two things as of late and now would be a good time for me detail some use cases.... especially since I will almost certainly forget how I'm using them and will need a reminder in the future myself 🤣

I was looking at the Github documentation... so If i was to do this, I just click "Wiki" and create a "New Page"? Then that creates a "pull request" which can be approved for inclusion ?
Let me know if this makes sense!

**Comment by baconpaul** [comment]
The github wikis had something odd about them that made us not use them - I forget what - something permissions based I think? Have you used them in the past?

I’d also be happy to make a directory and give you write access to the main website which is also all just markdown. That’s where much of our end user documentation has ended up.

Lemme know which works for you? I’m happy either way!

**Comment by baconpaul** [comment]
Or alternately we could use the wiki over at the website repo and then I can just give you merge access so you don’t need each edit approved. Sound good? If so I’ll set it up and explain it here

**Comment by mortfell** [comment]
Hmm I'm not sure what would be simpler. I've not used github wikis, other than as a reader.

Wiki style would be good because then other people will maybe want to add stuff if they see there is some already written. 

If it ends up being frustrating I can just port the stuff over to the website, either one would probably be a similar amount of messing around to figure out for me

**Comment by baconpaul** [comment]
OK Cool. 

Let’s use the wiki over in the documentation repo (https://github.com/surge-synthesizer/surge-synthesizer.github.io) and we can make a link to that from both the main webpage and the README here in the code and data repo. I can then give you write perms to the documentation repo so we don’t need people to approve your wikis. Just - you know - don’t blow up the website or anything like that :)

Sound good? I’ll adjust permissions now and start one.

**Comment by baconpaul** [comment]
Alright you should have an invite to join that repo and I started a wiki. It is very easy to add a link to the wiki from the main home page and the README. I’ll do that in the next day or two if the wiki editing works for you over there.

Thanks for your efforts to write these docs. Let me know if it works for you!

**Comment by mortfell** [comment]
Awesome! I'll try starting on this tonight :)

**Comment by baconpaul** [comment]
Cool. I’ll be online for a bit more if you need another permission change but you should be able to do anything you need except for invite or disinvite another user (I gave you write not admin)

**Comment by mortfell** [comment]
Seems to be ok so far, started work on a page!
Is there somewhere in the github where I can host images for the wiki? (gifs etc.)

**Comment by baconpaul** [comment]
When I’m editing markdown and stuff I just drag the image into the github editor and it uploads it to an “appropriate place” for me. Haven’t tried that in wikis. If that doesn’t work in wiki we can just make a directory in the surge synth website repo easily.

**Comment by mortfell** [comment]
Yeah, I've noticed you can do that it the comments too.... i
t doesn't work in the wiki editor seemingly

**Comment by baconpaul** [comment]
OK gimme 2 minutes... I think I have a solution

**Comment by baconpaul** [comment]
Alrighty here's how to do it

1. There's now a directory "assets/wiki" https://github.com/surge-synthesizer/surge-synthesizer.github.io/tree/master/assets/wiki
2. If you upload an image to there it is addressable as "https://surge-synthesizer.github.io/assets/wiki/imagename.png"
3. Then in your wiki you can just <img src" it
4. To test it I put an image in this unwritten wiki https://github.com/surge-synthesizer/surge-synthesizer.github.io/wiki/Why-do-I-get-high-frequency-distortion-from-some-wavetables%3F

You can just upload the images directly using the "upload" function on the GitHub site. To deploy to the web addressable form takes about 30 seconds. The GitHub-repo channel in slack will show you when it is deployed. Basically instant.

We can also, of course, store things like ableton or logic files (or zips thereof) in the same assets/wiki and have them be addressable using <a href. Nothing at all image specific.

**Comment by baconpaul** [comment]
So my thinking is if that works for you I can link to the ‘wiki’ from the top of the homepage and then we can just create articles as we need. We can use the current ‘home’ wiki as an index and then it’s all fine. I’ll add a wiki on adding an image to a wiki if you agree with this path, and then when you can do same and it works, we can close this issue.

Good stuff!

**Comment by mortfell** [comment]
seems fine to to me! 
I'll work on these when I can and try and and get these entries done by for 1.6.2

**Comment by baconpaul** [comment]
Great!

**Comment by baconpaul** [comment]
Alright I have a PR ready for this to add it to the website which I will merge coincident with the 1.6.2 release; and seems everything else is working. So closing this issue

**Comment by mortfell** [comment]
Thanks Paul, forgot about this one!
