### ISSUE TITLE
Vocoder goes unstable and never comes back at extrema of band frequency

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1094]
As described. Just try it with surge-fx in logic and you'll see.

**Comment by mortfell** [comment]
I assume you are already aware of this, but just making a comment in case.
I have also noticed this in the latest build of Surge the synth on both Windows and Mac.

**Comment by baconpaul** [comment]
Yup thanks; it’s all the same code. It would be way more worrying if they were different!!
