### ISSUE TITLE
LV2 menus bug in Ardour on linux

### ISSUE THREAD

**Issue by mortfell** [surge-synthesizer/surge#1100]
The menus on the LV2 version of Surge open, but they don't do anything when you click on them. For instance, open manual, open user folder etc. View Code, link to website

No response from system.... nothing happens
"About" works!

The menu options work fine in Carla. Open Manual opens the manual etc.
in Ardour nothing happens.

**To Reproduce**
just open LV2 Surge in Ardour and attempt to do anything with the menu in the bottom right corner. No actions occur.

**SYSTEM INFO**
The latest nightly, first version with LV2
I'm on the latest lubuntu 19.04 a lightweight Ubuntu distro.
UNAME printout:
5.0.0-13-generic #14-Ubuntu SMP Mon Apr 15 14:59:14 UTC 2019 x86_64 GNU/Linux
Latest stable Ardour.

Let me know if there is any other system info I can provide if you are unable to reproduce the bug.

**Comment by jpcima** [comment]
I haven't reproduced it on Ardour 5.12.
The menu action works. I tried opening manual, website, code, all have appeared to work.

(In fact, except "open user data folder", but probably because I didn't set it, and it tried opening the incomplete url "file://")

It needs the command `xdg-open` to run.
Does your machine have this installed ?

**Comment by mortfell** [comment]
I was using the "demo" version of Ardour, and it appears to be working now.
And I did have xdg-open installed. The menu was working correctly in Carla, which it would not be if that package was missing yes?

Anyway, I guess I'll close this as it seems like an issue with the Ardour demo versionl

**Comment by jpcima** [comment]
>The menu was working correctly in Carla, which it would not be if that package was missing yes?

It's true yes. It remains a mystery why Ardour "demo" would have anything to do with it.

**Comment by mortfell** [comment]
yeah totally. It's very strange. The Demo version was also 5.12.
Actually the Ardour demo ran poorly on this system. It was booting up and also loading plugins very slowly. It was also hanging on exiting frequently.

The same version ( 5.12 ) from the repository generally seems much more stable and snappy.
