### ISSUE TITLE
Can not select custom user folder on LV2 or VST in Linux

### ISSUE THREAD

**Issue by mortfell** [surge-synthesizer/surge#1102]
**Describe the bug**
The "zenity" dialogue which opens for selecting a custom user preset folder from the menu (if it opens at all) doesn't actually allow you to select a folder. If you press "ok" it just steps to the next directory level until it can't anymore.
![surgezenitybug](https://user-images.githubusercontent.com/4732794/64228283-efd5b380-ceab-11e9-8432-d72883676593.png)

This is on VST2/VST3/LV2 and all hosts. (REAPER, Ardour, Carla, Renoise)

SYSTEM INFO
The latest nightly, first version with LV2
I'm on the latest lubuntu 19.04 a lightweight Ubuntu distro.
UNAME printout:
5.0.0-13-generic #14-Ubuntu SMP Mon Apr 15 14:59:14 UTC 2019 x86_64 GNU/Linux
Latest stable Ardour, REAPER, RENOISE and Carla

Let me know if any other info would be helpful!

**Comment by baconpaul** [comment]
zenity command line is constructed in src/linux/UserInteractionsLinux.cpp if that helps folks

**Comment by mortfell** [comment]
This works for me now!
thanks

**Comment by mortfell** [comment]
this worked for me yesterday! but something broke the mouse support since then

**Comment by jpcima** [comment]
Can you explain in detail what is "broken mouse support in zenity" ?
Zenity is external software, it handles mouse in full independent way of what surge does, none of our code has to do with it.

**Comment by baconpaul** [comment]
@tank-trax reported the same. The mouse can't click on any of the zenity windows for some reason. 

Oh and I bet I know what it is

Our menu change probably isn't releasing mouse focus properly.

And zenity is only launched from menus.

**Comment by baconpaul** [comment]
I will hae to debug that for you. It's too tricky to debug if you don't know vstgui. I'll open a separate issue and look this weekend.

**Comment by baconpaul** [comment]
Moved it over to #1124

**Comment by mortfell** [comment]
ahh @jpcima  sorry for not being more specific.
The mouse just doesn't do anything at all in the zenity interface which Surge opens

**Comment by baconpaul** [comment]
i have a fix in flight @mortfell

**Comment by mortfell** [comment]
I will close this one since technically you can select it with the keyboard, and the other issue more accurately describes the problem
