### ISSUE TITLE
SurgeEffectBank 32 bit does not include vst3

### ISSUE THREAD

**Issue by mortfell** [surge-synthesizer/surge#1109]
The 32 bit version of the new Surge-fx renamed to SurgeEffectsBank doesn't include a vst3 when downloaded from:
https://github.com/surge-synthesizer/surge-fx/releases

**Comment by baconpaul** [comment]
Have a fix for this (but its in the other repo) so closing this now. Thanks for flagging it!

**Comment by mortfell** [comment]
no problem!
