### ISSUE TITLE
Want some feedback on preset organization

### ISSUE THREAD

**Issue by mortfell** [surge-synthesizer/surge#1122]
I'm almost done with a preset bank in Surge and I want to ask feedback/get approval from others on the project for formatting.
I know @mkruselj and @baconpaul will have thoughts on this. I'm trying to make a case for something.

The presets I've made fall into 3 categories: 
Drum sounds
Templates
and 
Synth

I know if it's good to avoid excessive sub-foldering but I'd like to organize them like this:
![Screen Shot 2019-09-05 at 2 28 13 PM](https://user-images.githubusercontent.com/4732794/64374996-91fbb580-cfea-11e9-8399-2d498a632541.png)

In my submitted presets I will ONLY have 3 folders though, Drums, Templates, Synths.
And ONE subdirectory

None of the other preset folder have this right now, but there is a handful of reasons I think this works really well:
1 . Surges preset store dialogue actually supports creating subfolder by default if you write a slash, for instance writing: "Emu/Drums/" as the category it will create a folder called Emu and a folder called Drums within it.
![Screen Shot 2019-09-05 at 2 29 23 PM](https://user-images.githubusercontent.com/4732794/64375440-8b217280-cfeb-11e9-91dc-353ccbe2ad60.png)

This will make my entry show up as ONE folder in the main menu with just a couple sub folders after.

2. Using Category for the name of the creator is redundant since Surge already has a space for the name of the creator to be stored..... I really don't wanna do that if It's ok.
In my opinion this:
![Screen Shot 2019-09-05 at 2 29 01 PM](https://user-images.githubusercontent.com/4732794/64375551-c02dc500-cfeb-11e9-9c7f-66e67117535a.png) 
makes much better use of Surge's current preset interface than:
![Screen Shot 2019-09-05 at 2 29 34 PM](https://user-images.githubusercontent.com/4732794/64375658-e3587480-cfeb-11e9-8b61-117ca3622e5a.png)
The creators name is referenced THREE TIMES and I still don't have the faintest clue what it sounds like.

3. The last reason is having sub folders is actually totally supported by the "category" buttons, it just steps through them sequentially, and ignores folders with nothing in them.

**Comment by mkruselj** [comment]
This is all good as far as I'm concerned. One little thing though, if you use plural for "Drums", also use plural for "Templates". That's all :)

**Comment by mortfell** [comment]
Ok thanks! Yeah good call

**Comment by mkruselj** [comment]
Actually, maybe when you're going with subfolders, you could subdivide them further. So DR patches go to Drums, PR go to Percussion, WT go to Wavetable?

**Comment by baconpaul** [comment]
The reason most other presets don’t use Su folders is sub folders didn’t work until 1.6 beta 8 when I added them :)

Your naming looks great to me with the templates fix. I don’t think you need multiple sub folders beyond that first level so the dr pr wt thing I’m not so sure on

**Comment by mortfell** [comment]
@mkruselj I actually tried doing that....
The problem with that is you start to get "Category" tags so long that it overlaps with some of the names and looks glitchy in the interface. The one subdirectory thing with short names seems to be the sweet spot for the stuff I've tested.

@baconpaul ohhhhhh that makes sense.

**Comment by mkruselj** [comment]
> @mkruselj I actually tried doing that....
> The problem with that is you start to get "Category" tags so long that it overlaps with some of the names and looks glitchy in the interface. 

That means there should be some clipping in that area so that it doesn't go over the preset names :) Paul?

**Comment by baconpaul** [comment]
Yeah I am sure that can happen. I like @mortfell solution to the problem. You know, doctor joke it away for 162

**Comment by mortfell** [comment]
ok I'll go ahead with more or less what I was planning! Thanks
