### ISSUE TITLE
zenity linux doesn't get mouse focus

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1124]
Reported by @tank-trax and @mortfell to @jpcima and me any of the zenity things like open sci no longer respond to mouse

I bet our menu changes mean a mouse event is getting mis-routed or mis-handled and vstgui is somehow confused about who has focus.

**Comment by baconpaul** [comment]
So here's the problem

It used to be a menu closed before a callback was called

With our never animate that is no longer the case

So the menu is still open and stealing the mouse

Basically the lack of animation in removeModalView gets things out of order.

**Comment by jpcima** [comment]
Oh right. What if the callback is rescheduled on the event loop to be done soon later?
eg. on a 0-delay timer

**Comment by baconpaul** [comment]
Yeah that's exactly the fix. I will get it in place now.

**Comment by tank-trax** [comment]
basically the whole screen becomes mouse inoperable... keyboard works though; happens on all versions LV2, VST2 and VST3

![surge-zenity 01](https://user-images.githubusercontent.com/41337033/64383222-ba43de00-d003-11e9-855b-809b44667983.gif)

**Comment by baconpaul** [comment]
Yeah I found the bug and have a fix. Just waiting for CI to finish and I'll merge it. Thanks!!

**Comment by baconpaul** [comment]
just pushed to master. If you build yourself and do a submodule update you should be good. Or wait for the deb in about 30 minutes.

**Comment by jpcima** [comment]
It confirm it as fixed after rebuilding master, following the submodule update.

**Comment by baconpaul** [comment]
Great!
