### ISSUE TITLE
Velocity 127 registers as 0 with VST3

### ISSUE THREAD

**Issue by mortfell** [surge-synthesizer/surge#1131]
I noticed there are no bugs related to Studio One anywere, and I also wasn't sure if anyone had tested Surge as an effect in Studio one (which I'm interested in for the wiki). Posted on the Studio One sub-reddit a few days ago, to see if anyone had tested Surge and got a useful bug report that it seems like no one has noticed yet!

from user @noisedroid on Reddit:
"Seems like there's a problem with MIDI notes with maximum velocity? With many of the presets a note at max velocity doesn't sound at all.

Or if I start with an init patch and route velocity to filter cutoff, the filter opens up as expected with increasing velocity but then is fully closed when velocity is 127.

It's as if 1 is being added to the 7-bit input velocity, but it's being processed internally as a byte with a 01111111 bit-mask, so at maximum velocity the high bit is simply discarded."

Upon further prompting about platform:
"VST3 on Studio One 4 / Windows 10"

I can confirm this bug exists on both Linux and MacOS VST3, in REAPER.
I tested some other midi inputs (channel pressure, Mod wheel) and none seem to have that problem.

AU,VST2 and LV2 don't have the issue. 
VST3 only.

**Comment by jpcima** [comment]
Oh, I'm betting it's this computation. The result of real-valued operation Is overflowing the `char` type.

```
char cVel = std::min((char)(e.noteOn.velocity * 128.0), (char)127);
```
