### ISSUE TITLE
"Set Custom User Data Folder" doesn't work correctly

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1136]
**Bug description**
"Set Custom User Data Folder" in the menu doesn't work correctly.

**Surge version**
* Surge Version: Latest Nightly
* Plugin type: VST3 64bit

**To Reproduce**
When I select the option for the first time, it opens the explorer window to select a folder and puts me in the root with all my drives (This PC) and selects C:\ by default instead of the current user data folder location. If I click Cancel, it will actually change it to there instead of cancelling. If I reopen it and click OK this time, it crashes the host, and does that every time I open an instance of Surge, until I manually change the location in SurgeUserDefaults.xml.

**Expected behavior**
The explorer window to select a folder should open at the current user data folder location.
Cancel should cancel the operation, and it should not crash when setting C:\ as the user data folder location. 

**Desktop config**
 - OS: Windows 10 x64
 - Host: FL Studio 20.5.1 (latest build)

**Comment by baconpaul** [comment]
Will be an easy fix. I’m ignoring the return code in that path Eu ght now!!! Sorry about that

**Comment by baconpaul** [comment]
OK Thanks @VincyZed I just pushed this to master.

Did two things

First: Actualy, you know, cancel when you cancel
But second I set the default directory choice to your current directory choice

Will take about 30 minutes to reflect in the nightly.

**Comment by VincyZed** [comment]
Awesome. Thank you!
