### ISSUE TITLE
Linux uninstall script does not remove Headless/VST3

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#1140]
building from source and installing locally using 
`./build-linux.sh  -l install`

places the contents in the following folders

VST2 = `~/.vst/`
VST3 =  `~/.vst3/Surge.vst3/Contents/x86_64-linux/`
LV2 = `~/.lv2/Surge.lv2/`
Headless = `~/bin/Surge-Headless/Surge/`
Data = `~/.local/share/Surge/`

running 

`./build-linux.sh  -l uninstall`

 removes everything except the Headless returning this error

`rm: cannot remove '/home/studio/bin/Surge-Headless': Is a directory`

**Comment by baconpaul** [comment]
Line 252 of build-linux.sh

I must be missing something. I can't spot the bug. Can you?

**Comment by tank-trax** [comment]
it's not removing VST3 either

it removes the LV2 folder and contents

the LV2 has this line `rmdir $lv2_dest_path/$lv2_bundle_name`

**Comment by baconpaul** [comment]
Oh it’s doing rm -vf not rm -rvf in the uninstall routine it looks like

**Comment by tank-trax** [comment]
for headless there is the extra Surge folder between Surge-Headless and executable Surge-Headless

**Comment by jpcima** [comment]
Note: I didn't remove recursively when I wrote LV2.
It's because I fear about variables not being quoted appropriately for whitespace. In this regard, rmdir will be safer.

For example a `rm -rf $foo`, which is unquoted with "foo=/home/Toto Tata/lv2"; the variable will be interpreted in two parts, and there exists a risk of deleting "/home/Toto" when this exists.
So, it's a safety measure, but for actual fixing, strings should be properly quoted.

**Comment by tank-trax** [comment]
bear in mind that if the install is not local it requires sudo and in this case I would have to agree with @jpcima

**Comment by baconpaul** [comment]
OK! I’m happy for you guys to change it to what you think is safest to be honest! No strong opinions here but agree with the quoting point. (Although I think the script quotes the names but I’m not sure (since I really only use build-OS X with any regularity :) ) )

**Comment by tank-trax** [comment]
this modification for line 242 to remove the VST3 


`rm -v $vst3_dest_path/Surge.vst3/Contents/x86_64-linux/$dest_plugin_name && rmdir -v $vst3_dest_path/Surge.vst3/Contents/x86_64-linux $vst3_dest_path/Surge.vst3/Contents $vst3_dest_path/Surge.vst3`

and line 252 to remove headless

`rm -vf $headless_dest_path/$dest_headless_name/Surge/$dest_headless_name && rmdir -v $headless_dest_path/$dest_headless_name/Surge $headless_dest_path/$dest_headless_name
`
```
sudo ./build-linux.sh  uninstall
removed '/usr/lib/vst/Surge.so'
removed '/usr/lib/vst3/Surge.vst3/Contents/x86_64-linux/Surge.so'
rmdir: removing directory, '/usr/lib/vst3/Surge.vst3/Contents/x86_64-linux'
rmdir: removing directory, '/usr/lib/vst3/Surge.vst3/Contents'
rmdir: removing directory, '/usr/lib/vst3/Surge.vst3'
removed '/usr/lib/lv2/Surge.lv2/Surge.so'
removed '/usr/lib/lv2/Surge.lv2/manifest.ttl'
removed '/usr/lib/lv2/Surge.lv2/Surge_dsp.ttl'
removed '/usr/lib/lv2/Surge.lv2/Surge_ui.ttl'
rmdir: removing directory, '/usr/lib/lv2/Surge.lv2'
removed '/usr/bin/Surge-Headless/Surge/Surge-Headless'
rmdir: removing directory, '/usr/bin/Surge-Headless/Surge'
rmdir: removing directory, '/usr/bin/Surge-Headless'

```

**Comment by baconpaul** [comment]
OK we can get this pushed into 1.6.2. One of us will be making another change in the next few days I’m sure and we can just sweep this into our PRs. Thanks!

**Comment by baconpaul** [comment]
Applying this quickly now. Will close issue once it's in.
