### ISSUE TITLE
LFO Magnitude bipolar, rename, reposition

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1146]
"Magnitude" is an extremely rarely used word when LFOs are concerned. Renaming this parameter to "Intensity" or "Amplitude" would be much better.

Also, after a bit of messing around, when you modulate LFO magnitude/amplitude/intensity with another LFO that is bipolar, Surge allows the modulation to overshoot the parameter range. So in case of bipolar LFO, it's going to eventually invert the amplitude of the modulated LFO. Which is COOL!

However, with that in mind, I think that LFO amplitude should be a bipolar slider, not a unipolar one like it is now. It would be more representative. Plus you would also be able to very easily create a reverse ramp LFO, for example.

Lastly, since this parameter is basically scaling the output of the LFO, I think it should swap places with the Deform slider, and be at the bottom there.

**Comment by sense-amr** [comment]
i second the motion..

**Comment by baconpaul** [comment]
OK these are all good ideas; but I’m going to leave them til post 1.6.2 - I’m in the mood to ship what we have!

**Comment by mkruselj** [comment]
Sure I didn't even mean to imply that it should be in 1.6.2 :)

**Comment by baconpaul** [comment]
Yeah but you know - I listen to your ideas man!
