### ISSUE TITLE
Sine osc: WaveShape > Shape

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1147]
I feel there shouldn't be random naming inconsistencies like these. Classic oscillator uses Shape, so why shouldn't the Sine oscillator use the same parameter name? :)

**Comment by baconpaul** [comment]
That is an excellent point and an easy change.

@VincyZed I’m gonna make this change for 1.6.2 in case that requires a quick mannual edit.

**Comment by VincyZed** [comment]
Yes, I agree, and it will be changed in the manual. Thanks for letting me know!
