### ISSUE TITLE
Make 32-bit macOS & Windows AU,VST,VST3 buildable, and create automated builds for them for the releasepage

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#115]
Objective: Provide automated 32-bit builds for macOS (AU,VST2,VST3) + Windows (VST2,VST3) automatically, by utilising the following information from @kurasu @kzantow @asimilon and @getdunne

`Premake5` -related info provided by @kurasu 
```
platforms { "x32", "x64" }
in premake
probably need to tweak some output dirs too, but i think that's it
```

VS-Projects related stuff posted by @asimilon at #97 
```
The VS projects need to be set up so that there 
are two "Configurations" for Win32 and x64, 
then on Azure just a matter of having two 
"Build Solutions" (this is using msbuild behind 
the scenes), with the appropriate "Configuration" 
and the "Platform" set to "Win32" or "x64" 
to correspond.
```

@getdunne's [surge-vst32proj.zip](https://github.com/surge-synthesizer/surge/files/2696528/surge-vst32proj.zip) for building a 32-bit windows build using VS2017, mirrored from ticket #14  - here's a segment of the readme: 

```
Create the VS2017 solution using premake5, 
as described in the main surge README on GitHub.

Open Surge.sln in VST2017, choose "Add project",
and add my surge-vst2.vcxproj.

Choose "x86" from the Visual Studio "solution platforms"
drop-down menu, and build the VST2 project.

Open a 32-bit VST2 host and select 
surge/target/vst2_32/Debug/Surge-Debug.dll
(or, if you do a Release build, 
surge/target/vst2_32/Release/Surge.dll).
```

but what i'd love to know is how the `surge-vst2.vcxproj` was made in the first place. anything specific you made @getdunne ? 

--
Anyway, that's what I have regards 32-bit, maybe @asimilon could talk about older versions of Xcode 

Anyway, are these automated builds possible with your azure voodoo, @kzantow?

**Comment by esaruoho** [comment]
as per people requesting a windows 32-bit on #24  - would be good to be able to bake 32-bit windows versions for vst2,vst3.

is this possible with your azure voodoo, @kzantow ?

**Comment by kzantow** [comment]
@esaruoho yes, I think so - it's using Xcode 9. I'm just trying to get windows building on Azure first, then will see about adding 32-bit to the mix

**Comment by esaruoho** [comment]
@kzantow cool! i agree, getting windows 64bit running first is pretty hot, then if we could get the 32bit packagers for vst2,vst3,au for macos and maybe 32bit for windows, too, then some magic person could work on linux builds :)

**Comment by baconpaul** [comment]
Which host requires a 32 bit au? Logic 9? I sort of want to move to auv3 rather than v2 one day and that will preclude 32 bit au.

**Comment by esaruoho** [comment]
@baconpaul if not 32bit au then at least 32bit vst2 :)

**Comment by esaruoho** [comment]
reopening since there is still a need for set of macos + windows 32-bit plugins. and #97 is doing well.

**Comment by esaruoho** [comment]
info provided by @kurasu 
```
platforms { "x32", "x64" }
in premake
probably need to tweak some output dirs too, but i think that's it
```

**Comment by esaruoho** [comment]
some stuff from @asimilon from #97 
```
The VS projects need to be set up so that there 
are two "Configurations" for Win32 and x64, 
then on Azure just a matter of having two 
"Build Solutions" (this is using msbuild behind 
the scenes), with the appropriate "Configuration" 
and the "Platform" set to "Win32" or "x64" 
to correspond.
```

**Comment by kzantow** [comment]
yeah, let's tackle this after I wrap up the first stab of the automated build script (I'm very close to having a PR; probably tonight)

**Comment by esaruoho** [comment]
@kzantow cool! just saw this issue is here, so will update with some extra data:

i saw @getdunne post his [surge-vst32proj.zip](https://github.com/surge-synthesizer/surge/files/2696528/surge-vst32proj.zip) for building a 32-bit windows build using VS2017, mirrored from ticket #14 : 

```
Create the VS2017 solution using premake5, 
as described in the main surge README on GitHub.

Open Surge.sln in VST2017, choose "Add project",
and add my surge-vst2.vcxproj.

Choose "x86" from the Visual Studio "solution platforms"
drop-down menu, and build the VST2 project.

Open a 32-bit VST2 host and select 
surge/target/vst2_32/Debug/Surge-Debug.dll
(or, if you do a Release build, 
surge/target/vst2_32/Release/Surge.dll).
```

but what i'd love to know is how the `surge-vst2.vcxproj` was made in the first place. anything specific you made @getdunne ?

**Comment by esaruoho** [comment]
There are some mentions of there being issues we will have with macOS Mojave (10.14) SDK not being capable of compiling 32-bit apps, so this would have to be some older version of Xcode running in a VM, right?
```
The macOS 10.14 SDK no longer contains support for 
compiling 32-bit applications. If developers need to 
compile for i386, Xcode 9.4 or earlier is required. (39858111)
```

**Comment by baconpaul** [comment]
32 bit windows now builds and works vst2/3 on windows 10 from the master branch after the merge I just pushed. 

I don't think we're ever doing mac32. So I am tempted to close this issue. What say you @esaruoho?

**Comment by esaruoho** [comment]
If mac32 is relatively painless to do, it would be good to have it. But i can change this ticket to be about win32 and make a separate mac32 ticket and we can close this. However, does this mean that @kzantow // website will have 32bit Windows packagers before long?

**Comment by baconpaul** [comment]
Mac32 is literally impossible for me to do. I have no software which can compile it.

**Comment by esaruoho** [comment]
so.. does windows 32 bit nowadays compile?

**Comment by baconpaul** [comment]
Yup compiles and works perfectly. It is now part of my regular!are tests

**Comment by esaruoho** [comment]
ok, closing ticket and opening a secondary ticket about macos 32bit :)
