### ISSUE TITLE
Sticky mod assign mode option

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1152]
When we're in mod assign mode (green blinking), selecting a different modulator disables the mod assign mode. This unnecessarily slows down workflow in a lot of cases, so I propose a change to this behavior. Maybe it could be an option in the Menu? But being able to stay in mod assign mode when changing which modulator is selected for assignment would definitely be a workflow booster IMHO.

**Comment by baconpaul** [comment]
I agree and have been irritated by this recently so will tag it for 1.6.6 just with the caveat that “we have to be super careful about the little orange arrow trick when we test”

**Comment by mkruselj** [comment]
Orange arrow is indeed problematic. I feel like there are cases where you want it to stick where it is, rather than follow which LFO you pressed.

Maybe if we Ctrl+click the orange arrow, it sticks there until we either normal-click it or normal-click another one? This would mean we would always see that particular LFO parameters, regardless of which other LFO we select for modulation. Maybe the orange arrow should then change color, too?

**Comment by baconpaul** [comment]
It’s not problematic - I mean it works now. Just we need to remember to test it. If you click on the orange arrow you are modulating foo; if you click on the label you have started modulating with foo (as opposed to now where the second is ‘you have selected foo and disabled modulation’)

**Comment by mkruselj** [comment]
On further thought, this need not be a mode. The best way of sorting this one out (IMHO) is to separate the down arrow physically from the rest of the control - giving it a larger hit area in the process, and decoupled behavior from the main mod tab through a modifier (either a keyboard modifier, or a different mouse button).

**Comment by mkruselj** [comment]
I FIGURED IT OUT!
