### ISSUE TITLE
Bipolar slider negative side end cut off

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1155]
![image](https://user-images.githubusercontent.com/2393720/64728635-bd473e80-d4db-11e9-9c12-6eb33edd4fc4.png)

Not sure what's the cause, but the positive side doesn't have the end cut off in the same way. Maybe the slope of the diagonal line is not symmetrical between right and left side of the slider?

**Comment by baconpaul** [comment]
Is that on windows at 125%?

**Comment by mkruselj** [comment]
You bet :)

**Comment by mkruselj** [comment]
This seems to be greatly improved now, so I assume @itsmedavep worked on the SVGs at some point. I'll close this as fixed!

**Comment by baconpaul** [comment]
could also be the 2x oversampling in the windows renderer now too. but glad it is fixed!
