### ISSUE TITLE
LV2 can't be loaded in Ardour 

### ISSUE THREAD

**Issue by 0x000FF4** [surge-synthesizer/surge#1157]
**Describe the bug**
After installing from the source ,manual installing form the ubuntu deb file and some personal testing I can't load surge 

**Please let us know your surge version**
Nightly build , deb 64 bit ubuntu file .

**To Reproduce**
Try to install surge I any way possible and load it in ardour 

**Expected behavior**
To find the plugin 

**Screenshots**
![Screenshot from 2019-09-11 23-01-45](https://user-images.githubusercontent.com/3662977/64730504-29c83a80-d4e8-11e9-927b-88ed3575aea8.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04

**Additional context**
I am sorry if I am causing too much of a mess. But it looks like that the trouble finds me :D .I have tried to reload ardour , to place the lv2 folder but still no luck

**Comment by jpcima** [comment]
I can give it a check when I install your OS version.
Was it recognized in other hosts?

**Comment by 0x000FF4** [comment]
I haven't tried

**Comment by trebmuh** [comment]
Anything in Ardour's message console maybe? Or maybe when started from the CLI?

**Comment by 0x000FF4** [comment]
nothing interesting

**Comment by baconpaul** [comment]
I can't figure out ardour to saye my life, but I've swept some more changes from the linux team and they seem to be able to load the LV2 in ardour with current master. Any luck if you try a new build at head or the latest nightly deb?

**Comment by tank-trax** [comment]
Debian 9.9 Stretch 
4.9.0-11-rt-amd64 #1 SMP PREEMPT RT Debian 4.9.189-3 (2019-09-02) x86_64 GNU/Linux
backports enabled

Ardour built from source (is debug, not sure how to build release)
Surge built from source

LV2 loads...

![surge lv2 ardour 5 12](https://user-images.githubusercontent.com/41337033/65463700-34f36280-de26-11e9-94be-dd3d3486b538.png)
