### ISSUE TITLE
Notarize the MacOS installer

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1166]
https://developer.apple.com/documentation/xcode/notarizing_your_app_before_distribution/customizing_the_notarization_workflow

This could be critical as Catalina rolls out. Placeholder issue

**Comment by baconpaul** [comment]
https://cutecoder.org/programming/notarize-disk-image-developer-id-distribution/

**Comment by aaylward** [comment]
this would be great for Big Sur users as well!

**Comment by baconpaul** [comment]
Unfortunately the macOS notarization service is surprisingly hard to navigate for open source projects with no entity. I’ve been talking to other devs about this some but this issue is still just a placeholder.

**Comment by aaylward** [comment]
Thanks for the response @baconpaul -- I'll build from source for now 👍 

What an awesome project :)

**Comment by baconpaul** [comment]
So I finally got around to doing this. The nightly from now on, and the next production version, should be signed and notarized so closing this.
