### ISSUE TITLE
Reaper Windows Shrinking VST2

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1178]
This is an issue impacting only reaper on windows; and only with the VST2. The workaround to this issue is to use the VST3 on windows.

<img width="1389" alt="Screen Shot 2019-09-17 at 8 35 49 AM" src="https://user-images.githubusercontent.com/13387561/65043020-1ffb6880-d928-11e9-93a4-a78b0f02a2bb.png">

On reaper windows when you shrink your VST2 below your initial size, scrollbars appear. This appears to be because we resize the contents, but the call to the (semi-supported) VST2 document `sizeWindow` does not resize the parent. The scroll region available is the scroll region of the original size, even though the content is shrunk.

I think reaper is probably not shrinking the parent component of the plugin when getting the resize message on windows; then asking the parent component for its size; realizing it is larger than the display area; and putting on scrollbars. But I don't have the reaper code.

As I suggested on slack, 

> maybe I’ll just disable the vst2 in reaper with a popup that says “it’s finally time to upgrade evil” - chuckle

but @mkruselj / EvilDragon thought that we should write it up so he can bring it over to the Reaper forums! Thanks for any help.

**Comment by baconpaul** [comment]
EvilDragon 9:02 AM
https://forum.cockos.com/showthread.php?t=165052

forum.cockos.comforum.cockos.com
Plugin resize, scrollbars - Cockos Incorporated Forums
Plugin resize, scrollbars REAPER Bug Reports
hmmm, maybe helps?
yeah I just tried FL, Live, Maschine, no downward resize issue there
baconpaul 9:08 AM
That is exacty the problem we are seeing
You should totally link that to your new thread
And it also means there is an order of operations which I could prbably figure out which doesn’t do it - which I bet arturia and group do - or that it is a vstgui bug
interacting with that reaper bug-like-feature
EvilDragon 9:08 AM
right
EvilDragon 10:23 AM
That is exacty the problem we are seeing
And it also means there is an order of operations which I could prbably figure out which doesn’t do it - which I bet arturia and group do - or that it is a vstgui bug
the guy does mention this in the thread:
I've identified the source of the issue.

    REAPER implements these scroll-bars while many hosts don't.
    They are sized based upon the size of the child window.
    REAPER polls this rather than accepting the size reported by the plugin.


This means that in order for REAPER to work correctly it requires the plugin to make any adjustments to its own client window before notifying REAPER of the resize.
(edited)
baconpaul 11:13 AM
Ahh I wonder if I call sizeWindow at the end of handleZoom that will fix it?
Let me look

**Comment by baconpaul** [comment]
But nope. If I move sizeWindow to after I resize the frame it doesn't work. Wonder if I have to do something risky and dumb like send a sizeWindow into the async queue so the frame can resize. Ugh. No way I'm trying that for 1.6.2 when the VST3 works and this VST2 zoom code has proven so hard to get even close to working.... so leave this one for post release.

**Comment by mkruselj** [comment]
This seems to happen only if you set your default zoom to something larger than 100%, then reduce zoom level.

**Comment by baconpaul** [comment]
At this point, “just use the VST3” is the answer for reaper users on windows. So closing this
