### ISSUE TITLE
Processing Audio Inputs does not seem to work in LV2

### ISSUE THREAD

**Issue by mortfell** [surge-synthesizer/surge#1194]
**Describe the bug**
Using the new stable (1.6.2) I've noticed the LV2 does not seem to work with audio inputs.
Such as:
using Surge as a Vocoder
using Surge as an effect

Tested in Ardour 5 on Ubuntu.
The settings below produce a Vocoder effect in VST2 but do nothing in LV2:

![noaudioinLv2](https://user-images.githubusercontent.com/4732794/65365305-fbc8b180-dbdd-11e9-88ed-da29d990eb79.png)

**Comment by baconpaul** [comment]
Thanks. Did this ever work? Just curious.

Adding @jpcima and @falkTX

**Comment by mortfell** [comment]
Not to my knowledge, tried it for the first time today though

**Comment by jpcima** [comment]
Hi. It's not implemented, but should be possible to handle it by using the `connectionOptional` property.
http://lv2plug.in/ns/lv2core/#connectionOptional

By this property, it should be able to check for a null data pointer, and this tells if port is connected or not. Now, it has to check if DAW support this feature in practice.

(ps. apologies for long absence over last days, as I deal with a health trouble.
I was told lv2 is to delay for a next release, and I think the choice is wise for now)

**Comment by baconpaul** [comment]
We ended up putting the LV2 in the release so we can get feedback but I think most LV2 users build from source anyway or use one of the distros where I have way less transparency. Vast majority of linux use is still vst2 I think.

Surge is actually a super powerful audio processor if you can get DAW audio into it, so supporting this would be lovely!

I’m sorry to hear about your health. Hope you recover! I’m taking a short break then am coming back online to do a bunch of branched experimental things which we are thinking about for a ‘surge 2’ - so if you want to continue to plug away at LV2 on the 1.6 branch there’s plenty of opportunity and time. The one bug 1.6 branch bug we know about - cubase pitchwheel with vst3 - is held up on me seeing if I can get a running copy of cubase!

**Comment by baconpaul** [comment]
@mortfell just FYI @jpcima pushed a change which means this should be fixed in Linux nightly - if you have a moment anytime to confirm that’d be great and we can close or expand this issue then. Thanks!

**Comment by mortfell** [comment]
oh ok great, I'll take a look

**Comment by mortfell** [comment]
yup seems to be working great!
I'll add this Ardour LV2 vocoder example to the Wiki as well:
[surgeArdourVocoderLV2.zip](https://github.com/surge-synthesizer/surge/files/3668195/surgeArdourVocoderLV2.zip)
