### ISSUE TITLE
WT menu entry nitpick renames

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1196]
![image](https://user-images.githubusercontent.com/2393720/65369237-bee6d400-dc4a-11e9-93dc-dba836c72b19.png)

That one should probably say "Open Wavetable From File...".
Also ellipsis should probably be added to Download Additional Content (since both these options open something else, ellipsis is kind of standard to use.

**Comment by baconpaul** [comment]
Thanks! Will sweep into the point release
