### ISSUE TITLE
Modulation Sources parameters as Modulation Destinations

### ISSUE THREAD

**Issue by alfonso73** [surge-synthesizer/surge#1198]
Hi!
While working on Surge sound design i'm often facing the limit of not having Mod Sources parameters as Mod Destinations. Mod Sources parameters are a good mean to make more expressive sounds! 
thx

**Comment by baconpaul** [comment]
Hi

Surge supports inter-mod-source routing - so one LFO can modulate another or keyboard velocity can modulate LFO rate. The UI is driven by the little arrow.

Here’s the manual

https://surge-synthesizer.github.io/manual/#inter-modsource-routing

Is this what you mean? If not could you clarify what’s missing with an example?

Thanks for the comment!

**Comment by alfonso73** [comment]
Oh thanks!! I totally missed this one even if i'm an owner of Surge since Claes times :-D (RTFM to myself when things are not self evident). Can we delete the Feature Request?

**Comment by baconpaul** [comment]
Yeah I can just close the issue no problem. 

One of the things we've been talking about is how some parts of the synth are not the easiest UX. This is one example. We are thinking quite a bit about expanding some of the UX gestures in a future release and this one is on my list to think about indeed. 

Thanks for submitting the suggestion though, even if it was already there :)

Best
