### ISSUE TITLE
Rename (S)LFO to ENV or SEQ when LFO mode is set to those

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1201]
I believe the summary in the title is quite self-explanatory. All instances of (S)LFO in the plugin should be affected - both the GUI tabs, and various mentions in dropdown menus.

This should make things easier to discern when dissecting the patches.

**Comment by mkruselj** [comment]
This is awesome! However, it has some niggles, @baconpaul and here they are.

- [ ] When setting an LFO to envelope or seq mode, then right-clicking its mod tab, it uses full name on the button. It also doesn't refresh the name of the modulator in that RMB context menu:

![image](https://user-images.githubusercontent.com/2393720/81871470-23f38f00-9578-11ea-92b7-2d284935458e.png)

- [ ] LFOs above 2 are clipped to showing 2, instead of using 3-6. `bool fnum = idx % 6` should be `int fnum = idx % 6` :)

- [ ] Updated modulator name is not used in modulation amount tooltips:

![image](https://user-images.githubusercontent.com/2393720/81871552-569d8780-9578-11ea-98af-656e5e22212d.png)

- [ ] (Optional) slider's RMB context menu should show full name of the modulator instead of shorthand, maybe?

**Comment by VincyZed** [comment]
Sorry to reopen again, noticed a bug:

The "Ctrl" parameters are now named by default instead of "-", which is a good change imo! However if those were named previously in a patch, and we load the patch, their names stay "Ctrl" instead of loading the previously given names that are saved in the patch.

**Comment by baconpaul** [comment]
Ahh shoot thank you I will revert that bit

**Comment by baconpaul** [comment]
Tomorrow

**Comment by mkruselj** [comment]
I do think it makes sense to call them Ctrl 1-8. Maybe even Macro 1-8?
