### ISSUE TITLE
"release-moved" tag usage stops GH notifications and easy return of version from git

### ISSUE THREAD

**Issue by mxmilkiib** [surge-synthesizer/surge#1202]
**Describe the bug**
The "release-moved" tag usage as seen on https://github.com/surge-synthesizer/surge/tags stops both GH notifications and the easy return of version info from git.

**Please let us know your surge version**

**To Reproduce**
```
% git describe --long --tags
release-moved-362-ge1997c8                   
```

**Expected behavior**
```
% git describe --long --tags
1.6.2-2-ge1997c8
```
(I believe that'd be the format)

**Comment by baconpaul** [comment]
Right - the 'release-moved' for the master releases is necessary but I think the solution here is for the non-master releases that we actually issue a new tag. @kzantow can we add that to the pipeline? I think it is just a matter of a git tag somewhere in the azure but I'm not sure.

@mxmilkb thank you!

**Comment by baconpaul** [comment]
Just an FYI @mxmilkb - @kzantow and I were chatting and I think the 1.6.2.1 release will still have this problem but then we'll take a pause and figure out how to restructure the pipelines.

We just need to see if more bugs show up this weekend and want to keep the machinery stable while we get these micro-changes swept.

**Comment by baconpaul** [comment]
Oh this was fixed forever ago it seems. Now we do releases in the release repo (and have forever) all the releases since 1.6.4 seem tagged ok

```
paul:~/dev/music/surge$ git checkout main
Already on 'main'
Your branch is up to date with 'origin/main'.
paul:~/dev/music/surge$ git log | head -5
commit c4a7ea3456ad1be31f2fe4c8d31f55959f1887b4
Author: Paul <baconpaul@users.noreply.github.com>
Date:   Sat Apr 10 21:59:58 2021 -0400

    SurgeXT: More chipping away (#4288)
paul:~/dev/music/surge$ git describe --long --tags
release_1.8.1-395-gc4a7ea34
paul:~/dev/music/surge$ git log release_1.8.1 | head -5
commit 9de93366e343e45e0da427b00a944d24d5b38304
Author: EvilDragon <mario.kruselj@gmail.com>
Date:   Wed Jan 27 10:03:57 2021 +0100

    Update Damon Armani author name in half of his patches (#3723)
```

So closing this
