### ISSUE TITLE
Aborted (core dumped) with LV2

### ISSUE THREAD

**Issue by fpesari** [surge-synthesizer/surge#1203]
I [made an openSUSE package](https://build.opensuse.org/package/show/home:geekositalia:daw/surge) for the LV2 version of Surge and tried on Ardour, it crashes the program.

I then tried with all backends of `jalv`, it keeps crashing with these errors:

GTK:
```
GLib-GObject:ERROR:gvaluetypes.c:455:_g_value_types_init: assertion failed: (type == G_TYPE_CHAR)
Aborted (core dumped)
```

Qt:
```
*** Error in `jalv.qt5': corrupted double-linked list: 0x0000558a2a86ea30 ***
Aborted (core dumped)
```

* Surge Version: 1.6.2
* LV2
* 64 bit

My setup:

 - OS: openSUSE Leap 15.1 (GNU/Linux, 64bit)
 - Host Ardour
 - Version 5.12.0

**Comment by baconpaul** [comment]
Tagging in @jpcima and @falkTX who worked on the LV2 port in this release.
Thanks for the clear bug report.

**Comment by falkTX** [comment]
are you able to get a gdb backtrace?

**Comment by fpesari** [comment]
> are you able to get a gdb backtrace?

yes, I will try compiling it with debug symbols and try

**Comment by fpesari** [comment]
Well, I actually forgot to copy files in /usr/share/Surge, my bad :laughing:

It was an extreme reaction to that, though! Maybe Surge should warn and exit more gracefully if data files aren't found.

**Comment by baconpaul** [comment]
Oh you had the same problem as #1199!

If /usr/share/Surge is missing it pops user dialog saying fix that. That user dialog uses zenity and prints to stderr.

If zenity wasn't installed, though, we core dumped

@falkTX  and I fixed that this morning - https://github.com/surge-synthesizer/surge/commit/77b9cb9301a307cf0fcd7dcc6d11eb686d8421ff

So you should be able to grab master, remove /usr/share/Surge/ and get a non-SEGV but non-crashing surge.

Can you confirm that for us?

**Comment by fpesari** [comment]
> Can you confirm that for us?

Confirmed. Much better now! Thank you, also for the speed with which you replied! :smile_cat:

**Comment by baconpaul** [comment]
Great! We will sweep this fix into a point release this week - closing he issue

Thanks for the report!
