### ISSUE TITLE
LV2 Build Windows and Mac

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1207]
@jpcima @falkTX just FYI had this as a request

I peeked at it. Seems there's a couple of things

1. deconditionalize the premake
2. macOS premake doesn't support targetdir
3. how we gonna run that python script on mac and windows? we need a parallel solution
4. when I do get to the point of a build on macOS, I get that lv2 is included with <> but it should be included with "" - that's probably a sysincludedirs thing

but just putting this issue here to hang off any efforts we may make.

would be super useful to know how do I even test an LV2 on osx!

**Comment by baconpaul** [comment]
I have a set of diffs that make this start to be close to working on mac. How do I test on mac though would be handy?! Thanks

**Comment by trebmuh** [comment]
you can probably use [Ardour](https://community.ardour.org/download) or [Carla](https://kx.studio/Applications:Carla) on a mac, you can get a free version of Ardour-mac which go silent every 10 mins IIRC

**Comment by baconpaul** [comment]
Yeah my Mac already has Carla installed I was just being a doofus not thinking of it - thanks!

**Comment by trebmuh** [comment]
yw

**Comment by baconpaul** [comment]
OK so working on mac is some effort, and I'm not going to tackle it now. But here's the notes for how far I got

1. the big diff is src/lv2/AllLV2.h needs to turn from angle bracket includes to double quote includes
2. the premake change is just bringing mac into the ifs properly
3. build-osx works for lv2 just fine with the obvious 4 or 5 lines.

and then you get started. That's not even worth committing though because we still need to assemble the bundle and put the resources in it and deal with the resource loading for configuration.xml and cscalablebitmap. That means copying the script scripts/macos/package-blah for an lv2 and doing the right thing as well as copying the python lv2 extractor, which should be simple.

So like I said not doing this now, but don't think it is that hard if you understand LV2 and have a mac. I'm half way there :)

**Comment by jpcima** [comment]
I don't think the Mac or Windows build is anything special compared to Linux.
It's mostly hope that UI is going to embed and work correctly for these platforms.

Bundle structure is identical. The python script should work, but if it's a problem to use it, there exists this program doing essentially the same thing.
https://github.com/falkTX/DPF/blob/master/utils/lv2-ttl-generator/lv2_ttl_generator.c

**Comment by baconpaul** [comment]
I made it build on mac optionally with the 1.7 release but couldn't test it. I don't think I ever will on windows - that python prerequisite and the dll load is going to be too annoying. So lemme close this as "done enough".
