### ISSUE TITLE
Oscillator panning.

### ISSUE THREAD

**Issue by Psiome** [surge-synthesizer/surge#1211]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

To create complex, textural sounds, an important role is played by the free panning of the oscillators. Can I make three separate pan controls in the synthesizer? These parameters can be modulated by the LFO.

**Describe alternatives you've considered**

**Additional context**

**Comment by baconpaul** [comment]
Thanks! This is actually a dup of #304 and sort of #1150 so I’m going to close this as a dup but please feel free to subscribe to those isssue for updates!

Best
