### ISSUE TITLE
wav and patch ordering uses path causing windows-specific sort differences

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1218]
Open the wavetable oscillator
Choose the last EMU wave (so voices / yoobee or what not)
Click "next" arrow

On Mac you get the correct behavior of "STAC French Horn" 

On Windows you skip the EMU VSCO and go straight to the first Layer

EMU VSCO are all .wav not .wt so something must be wrong in our sort and truncate on windows

**Comment by gnips** [comment]
Next arrow on "talk_yoobee", I get the "STAC French Horn".
Prev arrow goes back to "talk_yoobee", so no problem here.
Trunk, VS17 from source, Windows 7.

**Comment by baconpaul** [comment]
OK! In my windows 10 from source at master it did the avove and that matches what @mkruselj saw also. So even curiouser!

Thank you for the report. Super duper useful.

**Comment by gnips** [comment]
Double/tripple tested, + many other .wt dir. wraps, they all work as they should for me. 
Tested from Init or other start patch.

**Comment by baconpaul** [comment]
My theory (which is pretty pedestrian) is that the overall wt order sorting breaks on windows 10 with .wav files because of something in the utf8 conversion. So the category assignment is correct (hence the menu being right) but the jog button which traverses the total order goes wrong.

That’s consistent with windows 7 and mac working and windows 10 not

But I didn’t debug it beyond that. Having a host where I could easily see stdout from the plugin on windows would make my life way easier.  But I think the problem is in the sorting of the total order for wavetables

**Comment by gnips** [comment]
Hmm. I don't see any Utf8 char there that would need +8 bits...

**Comment by baconpaul** [comment]
Yeah didn’t say it was a great theory. Chuckle.
And my one test didn’t fix it
So it’s probably something else!

**Comment by baconpaul** [comment]
Anyway it's clearly a category-sort-order vs item-sort-order.

If I sit on the last waldorf and next, I get the first EMU VSCO; If I sit on the last EMU VSCO and next I get the first EMU; and if I sit on the last EMU I get the first Layzer

So the patch ordering is not matching the menu category display ordering on win 10.

Oh also if you build from source you may need to blow away and reinstall your %LOCALAPPDIR%/Surge. May not of course but just pointing out that a copy may not bring all the renames along.

**Comment by gnips** [comment]
Win10 is a can of worms...

I know %LOCALAPPDIR%, keeping updated, thanks.

**Comment by baconpaul** [comment]
Great. 

Anyway I'm taking a week or so break from surge dev but this one is sitting here. It's actually a nice issue for a win10 dev to look at if they want. The code is all in SurgeStorage.cpp and that wt_list data structure is just getting sorted differently on win10 than expected.  But sure we will get to it eventually too. Thanks for the reports on win7!

**Comment by gnips** [comment]
Another take: Could be localization problem, I'm in sweden.

**Comment by baconpaul** [comment]
Oh yeah! Thank you!

**Comment by gnips** [comment]
Yet another take: I have no spaces in my %LOCALAPPDIR%, or %APPDATA% path.

**Comment by mkruselj** [comment]
The space could be it. Sounds like you're not using the latest renaming of wavetables that I did, which converts any dashes and underlines with spaces. Please try it (1.6.2.1 build is live IIRC) and see if you get it too.

**Comment by gnips** [comment]
Yes, that is the difference. When updating with new names I see same thing.
"Emu VSCO" is sorted before "Emu" for some reason. 
So Next in "Emu VSCO" ...SUS Pic...  juimps to "Emu" ... Chippy

**Comment by gnips** [comment]
Path is in 1 string (in struct Patch), so with sub-dirs for wt's:

Windows:
"Surge\wavetables_3rdparty\Emu VSCO\Brass" < "Surge\wavetables_3rdparty\Emu\Voices And Animals"
Mac:
"Surge\wavetables_3rdparty\Emu VSCO\Brass" > "Surge\wavetables_3rdparty\Emu\Voices And Animals"

So obviously space " " sorts before dir separator "\" or "/" in Windows, but not on Mac. 
Should be easy to fix.

**Comment by baconpaul** [comment]
Oh what a clever observation.

**Comment by gnips** [comment]
Coming from embedded C, C++ is not my area, so I'll stay away from coding.
But there should be some smart std lib routine doing it right.

**Comment by baconpaul** [comment]
Yeah it will be easy to fix - I’ll get to it this month for sure!
