### ISSUE TITLE
Context sensitive "Help" option in context menus

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1222]
Since Surge can seem complicated to understand at first glance, we had the idea to implement a context sensitive "Help" option at the end of each context menu. This option would link to the specific section in the manual explaining this item.

For instance, right-clicking the **Patch Browser** and choosing "Help", or "Read in Manual" (or whatever we would end up calling it) would open up https://surge-synthesizer.github.io/manual/#patch-browser , and so on.

**Comment by baconpaul** [comment]
So the way to do this in Surge++ is as follows

1. Add a 'helpurl' URL to each layout. If you do "#patch-browser" it presumes the manual as a prefix
2. Add an interface ISupportsHelp in src/common/gui which just contains the `std::string getHelpURL() = 0` like normal
3. around line 1920 of SurgeGUIEditor we create the menu. So there we can do an

```
if( hc = dynamic_cast<ISupportsHelp>(control) )
  url = hc->getURL
  if( url starts with '#' )
    addMenu( UserInteractions::openURL( manualBase + postfix ) )
  else
    addMenu ( ... )
```

in gross pseudocode of course.

and then we can put the URLs in the xml and it will work at least for sliders and glyphs. (Other components create their own menus I think so we have to go hunt down that code).

**Comment by baconpaul** [comment]
Bumping this back into 1.7.0 after I had an idea about how to do it.

**Comment by baconpaul** [comment]
OK so @VincyZed here’s my design for #1222 I am working on
4:38
As discussed if there is help available for a param it will launch from the name which will be visually modified “somehow” (TBD)
4:38
The data has to come from somewhere though. So what I’ve done is created a new surge-wide XML file called “paramdocumentation.xml”
4:38
Here’s the version from my working system

EvilDragon  4:38 PM
oh oh oh I have an idea for the online manual

baconpaul  4:38 PM
paramdocumentation.xml 
<param-doc>
  <ctrl_group group="0" group_name="cg_GLOBAL" help_url=""/>
  <ctrl_group group="2" group_name="cg_OSC" help_url=""/>
  <ctrl_group group="3" group_name="cg_MIX" help_url=""/>
  <ctrl_group group="4" group_name="cg_FILTER" help_url=""/>
Click to expand inline (396 lines)



EvilDragon  4:38 PM
TOC should be always visible in a panel to the left

baconpaul  4:39 PM
OK so what happens is a param will look itself up first by skin name and oscilator or fx type; and if that fails by skin name; and if that fails by control group
4:39
So if you make, say, the ctrl_group mix there have a help_url and change nothing else, all the mix params will point at that URL
4:39
A blank url is equivalent to “no data”

EvilDragon  4:39 PM
that is highly comprehensive, Paul

baconpaul  4:39 PM
And all urls are relative to the manual. So will be surge-synth/manual/#help-url
4:40
this way we can document a group of things or pick out a single particular one
4:40
Makes sense yeah?

EvilDragon  4:40 PM
years of experience shining through. fallbacks of fallbacks of fallbacks. nice :smile:
4:40
like a house of cards
4:40
or rather dominoes

baconpaul  4:40 PM
yeah it’s basically a heirarchical index

EvilDragon  4:40 PM
well it makes sense

baconpaul  4:40 PM
“tell me about switch 3 for oscillator with type 2”.
4:40
“OK tell me about switch 3 for oscillators”
4:40
“OK tell me about oscillators”
4:40
“oh well. Thanks for playing”
