### ISSUE TITLE
Surge can't load to Waveform10

### ISSUE THREAD

**Issue by dacrhu** [surge-synthesizer/surge#1223]
**Describe the bug**
I tried with binary package and builded from source too, Waveform10 scan can't load Surge VST.

**Please let us know your surge version**

* Surge Version: 1.6.2.1 and development too
* Plugin type VST3
* 64bit

**To Reproduce**
1. in Waveform10 plugins page press scan button

**Desktop (please complete the following information):**
 - OS: Fedora 30
 - Host: Waveform10
 - Version: 10.3.1 (Built: 3 September 2019) (64-bit)

**Additional context**
I tested with pluginval:

pluginval v0.2.3 - JUCE v5.4.3
Started validating: /usr/lib64/vst/surge-vst.so
Random seed: 0x33fdfce
Validation started: 28 Sep 2019 8:56:39pm

Strictness level: 10
-----------------------------------------------------------------
Starting test: pluginval / Scan for known types: /usr/lib64/vst/surge-vst.so...
Num types found: 0
!!! Test 1 failed: No types found
FAILED!!  1 test failed, out of a total of 1

Finished validating: /usr/lib64/vst/surge-vst.so
*** FAILED: 1 TESTS
*** FAILED: 1 TESTS

LDD output:
# ldd surge-vst.so 
	linux-vdso.so.1 (0x00007ffdfde79000)
	libcairo.so.2 => /lib64/libcairo.so.2 (0x00007f7256ba8000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f7256b60000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f7256aa3000)
	libxkbcommon-x11.so.0 => /lib64/libxkbcommon-x11.so.0 (0x00007f7256a98000)
	libxkbcommon.so.0 => /lib64/libxkbcommon.so.0 (0x00007f7256a55000)
	libxcb-cursor.so.0 => /lib64/libxcb-cursor.so.0 (0x00007f7256a4c000)
	libxcb-keysyms.so.1 => /lib64/libxcb-keysyms.so.1 (0x00007f7256a45000)
	libxcb-xkb.so.1 => /lib64/libxcb-xkb.so.1 (0x00007f7256a26000)
	libxcb-util.so.1 => /lib64/libxcb-util.so.1 (0x00007f7256a1d000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f72569f2000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f72568ad000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f725688c000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f7256870000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f725686a000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f7256670000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f725652a000)
	libmvec.so.1 => /lib64/libmvec.so.1 (0x00007f72564fe000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f7256338000)
	libpixman-1.so.0 => /lib64/libpixman-1.so.0 (0x00007f725628e000)
	libpng16.so.16 => /lib64/libpng16.so.16 (0x00007f7256258000)
	libxcb-shm.so.0 => /lib64/libxcb-shm.so.0 (0x00007f7256253000)
	libxcb-render.so.0 => /lib64/libxcb-render.so.0 (0x00007f7256243000)
	libXrender.so.1 => /lib64/libXrender.so.1 (0x00007f7256236000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007f7256221000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f7256205000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f72561fb000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f72561cd000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f72561b9000)
	libxcb-render-util.so.0 => /lib64/libxcb-render-util.so.0 (0x00007f72561b2000)
	libxcb-image.so.0 => /lib64/libxcb-image.so.0 (0x00007f72561ac000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f72561a4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7257125000)

**Comment by dacrhu** [comment]
Hm. From https://copr.fedorainfracloud.org/coprs/ycollet/linuxmao working fine the Development version. But it is VST2.

**Comment by baconpaul** [comment]
Yeah the vst3 on Linux only works on reaper now. Let me link this to #514

**Comment by dacrhu** [comment]
Thank you!
