### ISSUE TITLE
Rename "Polymode" to "Play Mode"

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1229]
1. Makes more sense
2. Separates two words correctly

:)

**Comment by mkruselj** [comment]
@itsmedavep would you be willing to do the SVG change for the main background in both skins for v1.7?

**Comment by itsmedavep** [comment]
Oh sure! I can fix that up once I get time to work on the skins again.

**Comment by mkruselj** [comment]
Great, thanks!
