### ISSUE TITLE
Midi CC or Automation of LFO and OSC parameters doesn’t update LFO or OSC UI

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1232]
@itsmedavep reports in Cubase that if you learn an LFO parameter (like rate or deform or what not) with a midi controller then move the controller, the slider moves but the LFO display doesn’t repaint.

**Comment by baconpaul** [comment]
This is not just a cubase problem; and not just an LFO problem.

If you either DAW automate or MIDI CC learn and control the params in LFO or OSC, you get the slider moving and the sound changing, but you don't get a UI response in the drawn element.

**Comment by itsmedavep** [comment]
![LFO_Display_Doesnt_Update](https://user-images.githubusercontent.com/11078351/66209465-01fa6b80-e67d-11e9-94b8-07cbc797a502.gif)

Here's the video.

**Comment by baconpaul** [comment]
Yeah it's also not just a VST3 thing; it happens in the AU also. This is just a good old fashioned bug!

**Comment by baconpaul** [comment]
So around like 443 of SurgeGUI Editor in the if((j< block we want to do something like

- is this param one for the current OSC or LFO 
- if so invalidate oscdisplay if it is there and lfodisplay if it is there

basically

**Comment by itsmedavep** [comment]
Im using this:
<img width="909" alt="Screen Shot 2019-10-04 at 8 44 47 PM" src="https://user-images.githubusercontent.com/11078351/66248040-e11b3000-e6e7-11e9-85e3-b4429ea06ce9.png">

I still see this when automating LFO deform via MIDI learned CC.


![MIDI](https://user-images.githubusercontent.com/11078351/66248132-b9789780-e6e8-11e9-9ee3-cf467878b9ba.gif)

**Comment by baconpaul** [comment]
OK I’ll take a look! I had tested it in reaper and it seemed to work but I tested with phase so maybe deform is special somehow. And this is in cubase pro 10 right?

**Comment by itsmedavep** [comment]
Yup I’m on Cubase 10 Pro.

**Comment by itsmedavep** [comment]
Interesting about phase. Ill give other parameters a look too. I kinda just went for the jugular so to speak. I didn't check very broadly.

**Comment by baconpaul** [comment]
Alrightly here's what's happening at current master in reaper

1. If you automate with VST3 automation the slider moves and the graph repaints (LFO and OSC both)
2. If you learn midi and move it with a controller it doesn't

The second case comes through a different path which is "::channelController" which resets enough state to force a knob to move but not enough state to make the repaint happen it seems?

It also seems in REAPER at least that if you VST3 automate and midi control the VST3 automate always wins. Which makes sense since it is applied continuously.

**Comment by baconpaul** [comment]
Oh right; because ::channelControl sets refresh_ctrl_queue not refresh_param_queue at line 1038 or so of SurgeSynthesizer; so I need to do my respond-to-redraw in the place that handles that too I think. Should be an easy fix tomorrow sometime.

**Comment by baconpaul** [comment]
Not a VST3 bug; this is in all the host flavors.

**Comment by baconpaul** [comment]
Yup got it. PR coming in.

**Comment by itsmedavep** [comment]
Tested and looks good.

**Comment by baconpaul** [comment]
Great thanks!
