### ISSUE TITLE
Parameter value popups cover other sliders and are too long

### ISSUE THREAD

**Issue by cxbignekoc** [surge-synthesizer/surge#1245]
Want to suggest that the **value-preview-bar** for sliders should not be so long and dont cover other parameters...
A better position is maybe next to the sliders or a static preview

the issue
[https://www.screencast.com/t/4BZSi71YHK]

sugesstion
[https://www.screencast.com/t/b6XowJxo]

surge V.1.6.2.1 - 64bit - VST3
Bitwig 3.0.2
Win 7 64 bit

**Comment by baconpaul** [comment]
Thanks for the suggestion! I'm going to tag this one as "unscheduled" but I've been thinking a lot about that preview for the UI rewrite so we will leave it open and get to it over the next few months.

Best

**Comment by cxbignekoc** [comment]
Yeah it maybe in this process a "improve" as an error...we will see thx 4 rply...see ya on slack ;)

**Comment by mkruselj** [comment]
@baconpaul I think this issue might not be relevant anymore since we kinda complicated things with even bigger value popups in case showing modulation ranges and/or high-precision value displays options are enabled...? Instead of condensing we made it "worse". 😁

**Comment by baconpaul** [comment]
yeah I agree.
