### ISSUE TITLE
CritSection runaway with windows.wt missing on linux

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1249]
As reported by @codecollider in #1247 if you run surge on linux with the shared assets missing, you get a runaway in the critical section recursion. That's interesting and we should debug it one day, even though the proximate problem in #1247 was solved with better error reporting.

**Comment by mkruselj** [comment]
@mvf since CriticalSection is now removed and replaced with std::mutex, is this issue still relevant?

**Comment by baconpaul** [comment]
It is. In fact if this happens we will deadlock instead of run so we need to understand why it happened before 18 or change the mutex to recursive which sucks

**Comment by mvf** [comment]
Yeah, would love to get to the bottom of this. Spent quite some time already trying to reproduce this with the current version by deleting `windows.wt` with 8f4e694f697871f8fb6896e6aad90d7aaea7700a reverted, then trying to load "Window" into the oscillator. Couldn't get it to deadlock/recurse yet but will poke around some more.

If we can't figure this out, this old issue alone wouldn't be reason enough for me personally to consider recursive mutex. What was once a bad code path should now be barred, and to the user both an endless loop and a deadlock manifest as a hang. So even if this strikes again it's not really a regression IMHO.

**Comment by baconpaul** [comment]
I agree if we can't repro it we should go ahead
I also agree we should poke at it some more
I also agree we have time
So lets leave this open and we can poke at it some
:)

**Comment by mkruselj** [comment]
Here's a thought. Why don't we actually subsume windows.wt into the binary itself? Then it's always gonna be available, no way to deadlock in that case?

**Comment by baconpaul** [comment]
while that would solve the proximate problem
i want to understand why it recursed
in case it would in other failure cases

**Comment by baconpaul** [comment]
So I just tried for another half hour to make this happen again
I am unable to
I conclude that fixes we put in other parts of the codes to pthis runaway which was hard to reproduce anyway
So I'm going to close it.
