### ISSUE TITLE
Arrows Menus Linux

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#1250]
This is happening in Linux
OS: Debian 9 Stretch
Build: 

I just noticed that the up and down arrows only work on the bottom level menu

For example, from the Categories Bass to Zoozither it is not possible to use arrows to navigate up or down, only the mouse works

However the sub-menus with the patches it is possible to use the arrows to navigate, and press enter to select the preset

For Categories that have sub-categories such as

Giana Brothers
Kuniklo
Nick Moritz

it is only the patches that the arrows can navigate, not the sub-categories

this possibly started happening around #1186 

the same behavior happens on the FX menu and the Main menu

same behavior on VST3 and LV2

just noticed if the mouse is off the menu the arrows can work, however of moving back or up to the previous or upper level menu the arrows no longer respond and that item stays selected until the mouse over

for the arrows to work the menu has to be closed and reopened

**Comment by baconpaul** [comment]
Arrows you mean arrow keys?

**Comment by baconpaul** [comment]
Oh and if I had to guess I’d say the vstgui animation change may be a more likely culprit (that’s https://github.com/surge-synthesizer/surge/commit/69ea9cec44b997dd1d5713273ceea86882b940e7 and #1124 / #1125 ) but I haven’t looked closely. Backing up to before 69ea9cec, running a submodule update init recursive, and clean building would be the first thing I would try.

**Comment by tank-trax** [comment]
`git reset 69ea9ce`

`git log`
commit 69ea9cec44b997dd1d5713273ceea86882b940e7
Author: Paul <baconpaul@users.noreply.github.com>
Date:   Thu Sep 5 14:31:37 2019 -0400

    Move the VSTGUI.SURGE pointer for linux menus (#1118)
    
    This vstgui.surge turns off the buggy/ghosty/slow linux menu
    animation in vstgui
    
    Addresses #1101

still the same behavior

**Comment by tank-trax** [comment]
Ahhhh... prior to
I went back to a previous commit

`git reset 7052796`

`git log`

commit 7052796ea238b80e969aa1eaef832d35fb7886be
Author: JP Cimalando <jp-dev@inbox.ru>
Date:   Wed Sep 4 23:10:29 2019 +0200

    Linux file dialog (#1111)
    
    * On Linux, invoke the file callback only if Ok was clicked
    
    * Check the SCL file for basic validity
    
    * Move the SCL validation logic where appropriate

and up, down, left, right arrows and menu behavior is as it should be

**Comment by tank-trax** [comment]
you were correct, the changes to #1118 caused it

menus are good here ->

git log
commit c24561ab8a163f6b4036e6c3a54c667e65109f7f
Author: JP Cimalando <jp-dev@inbox.ru>
Date:   Thu Sep 5 15:50:15 2019 +0200

    Add xdg-open and zenity commands as Debian dependencies (#1115)

**Comment by baconpaul** [comment]
Yeah ok. Well that’s good to know! I think not crashing and not ghosting is better than arrow keys with ghosts and crashes but if I get some time
With a Linux vm I will look for 163

**Comment by baconpaul** [comment]
And thanks for confirming!

**Comment by baconpaul** [comment]
I found the problem. A misplaced ifdef.

Fix coming shortly. Would really appreciate some testing of course!

**Comment by tank-trax** [comment]
tested and working as it should, thanks!
