### ISSUE TITLE
Mouse Vanishing Mis-Behavior Windows

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1254]
As reported by KVR user dandruff in [this thread](https://www.kvraudio.com/forum/viewtopic.php?f=1&t=511922&p=7555192#top)

> Windows 8.1 Pro, REAPER 5.984 x64, Surge 1.6.3 VST2
> 
> Small bug:
>
> 1. click Cutoff fader and hold the mouse button
> 2. drag mouse down
> 3. release the mouse button
> 
> Result: Mouse pointer shown below the Cutoff fader
>
> Expected: Mouse pointer shown on the Cutoff fader

I bet the bug is somewhere in here

https://github.com/surge-synthesizer/surge/blob/0a624daa0c658aacca8ca98b6c921179b94095cc/src/common/gui/CCursorHidingControl.cpp#L101

**Comment by baconpaul** [comment]
On Slack, AJ Young pointed out that this was a problem at zoom != 100%; I bet that code I posted above uses logical coordinates in one point and zoom coordinates in another to determine the mouse position move.

**Comment by MD-78** [comment]
I'm running at 100% zoom.

**Comment by baconpaul** [comment]
@mkruselj is this the bug you fixed the other day?

**Comment by mkruselj** [comment]
Ha, looks like it is. :)
