### ISSUE TITLE
VST3 Expose the presets to the host

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1256]
After convo on slack with a user using surge through accesibility channels, it became clear this would be a useful feature. Let me tag it into an imagined small 1.6.4 milestone. AU is in #405 so this is just doing the VST3 implementation

**Comment by baconpaul** [comment]
https://steinbergmedia.github.io/vst3_doc/vstinterfaces/classSteinberg_1_1Vst_1_1IUnitInfo.html Is how you do it in vst3.

**Comment by baconpaul** [comment]
And #405 explains how to do this in the AU.

I’m sure there’s something in VST2 and LV2 but for now I’ll just do AU and VST3 unless the VST2 and LV2 APIs are super obvious.

**Comment by baconpaul** [comment]
sigh. this is of course complicated and ugly for a relatively simple thing

anyway here's a start before i gave up

[x.patch.txt](https://github.com/surge-synthesizer/surge/files/4603898/x.patch.txt)

**Comment by mkruselj** [comment]
It's also apparently not really working well in some hosts either (including Steinberg's own):

https://www.kvraudio.com/forum/viewtopic.php?p=7923054

**Comment by baconpaul** [comment]
<img width="889" alt="Screen Shot 2021-04-08 at 11 45 53 AM" src="https://user-images.githubusercontent.com/13387561/114286620-71010f00-9a2e-11eb-8045-0565fd2ee7c6.png">

The SurgeXT plugin at main today exposes the set. May not be the set we want or we may want to name it differently but no work required for the VST3 at this point. Closing this issue since XT release will fix it and already has demonstrated that.
