### ISSUE TITLE
Expose wavetable name as a parameter

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1257]
Conversation from slack w/Claudio Garanzini

> Hi all! My name is Claudio and I'm a totally blind new user of Surge! I simply love this synth; there's so much to do and to discover! One simple question: I'm using Surge in Reaper and use a plug-in that can read all the params in the synth. There isn't a way for us to load or brouse the waveforms when using the Waveform osc. Could you please insert a param so that we could at least search a waveform in the list? If you want to test what I'm talking about, the reaper plug-in for the blind people is called OSARA.

> hHi Baconpaul! Thanks for your answers! I can eqally use VST2 or 3, eather 32 or 64 bit versions; I use Windows 10 and NVDA as my screen reader of choice! The params of Surge are exposed in Osara without problems; they can be easily manipulated in it! It'ld be intresting to have a param for selecting the waveforms because, actually, we can't have this opportunity! But as I sad before, Surge is a Must for blind people because it has man other ways to create and manipulate sounds and the paramethers are so clearly exposed if you use NVDA and Osara, in my opinion! Thanks again for your help! Bye for now!

My response among other things

> OK wonderful. It’s actually pretty easy for me to add the waveform parameter “at the end” in the VST2 and maybe the VST3 I think. At the same time I’ll see if I can expose the preset list properly.

> Other things are harder ... but for another reason I’m planning a 1.6.4 release sometime in late Nov or early Dec and I will see if I can sneak this in.

> Oh but: if you actually modulate that control with your DAW at audio playback time you will be sadly disappointed I think! I know that’s not your use case but we will have to update the manual for sure. And because of a technical annoyance they will be the “last 6” parameters in the synth. And I may only be able to add them to the VST2 and AU (but can probably get them in the VST3 also)

**Comment by baconpaul** [comment]
Oooh I played with this and it is tricky and risky in a couple of ways. I want to stabilize 1.6.4 right now so, sadly, I'm going to bump this one

**Comment by per99** [comment]
@baconpaul Maybe this isn't the right thread (or whatever it's called). I'm not very familiar with GitHub.

But I wanted to ask you, dear Mr. baconpaul, if you have any additional information, regarding Bash and Python? I've been trying to create a wavetable file, for use in Surge, using the instructions in the wikis that J Riley Hill has written. I have tried for a week now, to transform a .wav file to a wavetable using Bash: python3 ~/Scripts/add-surge-metadata.py etcetera. If I use GitBash, for example, it says persmission denied. If I use Ubuntu, instead (or Windows Power Shell), it instaed claims that no such file (add-surge-metadata.py) or directory exists. But they do exist! J Riley Hill at the Surge FB-forum does not know how to solve this. May I ask if you have got any tips?

Best regards, per99

**Comment by baconpaul** [comment]
Hi @per99 

Hmm when you run gitbash and just type “python3 -v” what does it say? And when you run python are you in a directory with checked out surge code?

Probably easier if you hop on our slack to discuss this kind of debugging.

**Comment by per99** [comment]
@baconpaul  Yes, I remember Slack ... I think I created an account and password half a year ago ... But I'm on a new computer ... Can I just type www.slack.com as URL, or something? 

It says quite a lot when I use Ubuntu and type python -v. I attach a screenshot, but it's only the beginning (I have different versions of python in the same windows apps-folder - I downloaded one of them from Microsoft store) . If I use GitBash and do the same thing (or type python3 --version) it says permission denied.

![try_python](https://user-images.githubusercontent.com/32549962/72668024-93ba9880-3a22-11ea-9386-3da94e28a5ce.JPG)

**Comment by per99** [comment]
@baconpaul P.S. But if I use Ubuntu and type' Python3 --version' it simply says Python 3.6.7 (but I would have expected Python 3.7).

**Comment by baconpaul** [comment]
Any python past around 3.5 will work - so why not run the scripts in that Ubuntu python?

There’s a link on our website for getting on slack. Just use that and you should be good!

**Comment by per99** [comment]
@baconpaul Thanks! Well, I am logged in to Slack. Would the best thing be to start some kind of new thread and carefully describe the whole matter? (This has been going on for a week.)

**Comment by baconpaul** [comment]
Just hop into general and ask - one of us can offer some help I bet

**Comment by meckito** [comment]
I am also a blind user of Surge, or rather a potential user, because I really care about wavetable synthesis. Maybe there is another possibility for a blind person to have access to the wave selection? Maybe keyboard shortcuts? I must admit that I really care about wavetable synthesis and so far I do not know anything that would give such opportunities for free as Surge, the more that the project is open source, so theoretically anyone can do it. Unfortunately, I am not a programmer and I can only ask others to make it possible for me and other people like me to create at least one sensible synthesizer that would be fully available to us. Windows 10 has a built-in OCR that recognizes, among other things, the name of the currently loaded preset. I can click on it with a virtual mouse and thus have access to the list of presets. I don't know what this name looks like, but maybe knowing this, you could design an element with the name wave to be read as well. Or maybe it is possible to use keyboard shortcuts to select wave? Besides, I know that it is possible to pass any text directly to the screen reader. Such a tool can be e.g. https://github.com/dkager/tolk. I don't know if it will help, but I am asking for any help. Making music is one of the few professions in which a blind person can act professionally, but creating inaccessible effects and synthesizers doesn't make it any easier.

**Comment by baconpaul** [comment]
Oh @meckito that is super interesting that your OCR can read the patch name.  Can you tell me anything about how to read that built in OCR and how it guides you to test?

Our problem is that almost all the graphics elements are VSTGUI rendered, not windows controls, and so they don't participate with accessibility. This has upset me for nearly 2 years but it is quite hard to fix, although I do intend to take a swing at it. The state of play of accessibility in music software is just so low I find! Full accessibility is a pretty big project though.

But if your built in OCR can read the patch name and allow you to click and then navigate the preset menu, a potentially easy interim solution is to convert the wavetable name display from a rendered string on an opaque component to a label with the same contents. While this would not make surge accessible by any stretch, it might expose this hidden component, and some (but unfortunately not all) of the rest of the synth can be controlled by DAW automation. You could, say, load a patch and change a wavetable at least, and mute and unmute oscillators and change effects. You could not set up modulations though.

That is not as good as full blown accessibility though, which I do keep thinking about. But it might be simple.

Is there any resource you can point us to on how to use the built in OCR which allows you to read the patch? If I can run it myself I am glad to see if a change to the wave display works with it.

Thank you

**Comment by baconpaul** [comment]
And sorry for the pedestrian question abut windows OCR tools. I am a mac user predominantly, but do have a windows 10 VM I can use to test.

**Comment by RDMurray** [comment]
@baconpaul  Hi.  I am also a blind Reaper user and one of the OSARA developers.  I would love to see more accessibility in Surge.

OCR is only necessary to click on the preset control.  After that the pop-up menu is a standard windows menu.  Is it possible to add keyboard shortcuts in VSTGUI?  If it is then it would be really helpful to have shortcuts for any controls that use the same kind of menu.

**Comment by baconpaul** [comment]
We've avoided keyboard shortcuts since there's a load of ambiguity between whether they are DAW-targeted or Plugin-targeted. We found different DAWs behaved in different ways. That said, we could introduce them optionally for this use case.

I also spent some time last night playing with my vstgui branch which adopts proper accessibility apis (IAccessible and NSAccessible). It's not working but I have some hope.

I'm super interested in this topic but not that well versed on what "good" would look like. Any help on that would be greatly appreciated.

**Comment by mkruselj** [comment]
Keyboard shortcuts could be a toggle in the main menu, perhaps? Provided we can make the main menu accessible.

**Comment by baconpaul** [comment]
Yeah
Also I have the start of vstgui calling to a custom iaccessible  wrapper On win32 so maybe we just do the proper thing here in our fork...

**Comment by mkruselj** [comment]
IMHO the right way to solve this one is #2355!

**Comment by baconpaul** [comment]
Hi folks
This has been a long dormant issue but we have been porting surge to juce and with the next version of juce we can implement accessibility support. I have a pr in now which allows some basic screen reader manipulation including a show menu action for the wavetable (but no oscillator selector yet)

I am consolidating that work over in issue #4616 so I’m going to close this issue - mostly since we don’t want wavetable as a vst3 param foe a variety of reasons but the conversation which followed about screen readers is broader work which our next version of surge will start to support.

welcome any testing and contribution. We aren’t quite at the point of a testable synth for a visually impaired user yet but we are a lot closer than we were yesterday. Please follow the other issue for regular updates

Thank you
