### ISSUE TITLE
Resetting modulation amount of release velocity by double-clicking on a blue slider doesn't work correctly

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1272]
**Bug description**
Double-clicking to reset a blue slider (modulation amount) that is linked to release velocity doesn't actually reset the mod amount value.

**Surge Version**
Latest nightly, VST3 64 bits.

**Steps to reproduce the behavior**
1. Open stock patch of Surge.
2. Select Velocity in the routing bar.
3. Switch to release velocity
4. Engage routing mode
5. Drag OSC Pitch's blue slider all the way, for example. (increase AEG release to hear the effect)
6. Double-click on the blue slider to reset it to 0. On screen it goes back to center, but it is still being modulated.
7. Disengage, then re-engage routing mode. The slider will be back to where it was before.

**Expected behavior**
Double-clicking should reset the modulation amount to 0 correctly.

**Comment by baconpaul** [comment]
What's happening is the double-click is resetting the UI element (great!) and the velocity modulation (only half great). The only half great is because with release velocity selected you want to reset that modulation.

Excellent bug report. Should be able to squash it shortly.

**Comment by baconpaul** [comment]
Found and fixed it in literally 7 minutes with this bug report. Thanks! Sweep coming.
