### ISSUE TITLE
Option to link certain parameters between scenes

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1276]
**Context**
Sometimes, depending on the patch and the way we use the two scenes, this feature could be really useful. For example, if we use both scenes as layering purposes (both playing at the same time) and we want the same Amp Envelope to control both scenes, the user could link the 4 ADSR controls to both scenes to have a single Master Amp Envelope without doing it manually in the two separate scenes.

As an example, Harmor uses 2 parts, similar to the scene concept, and has implemented this feature like so (sorry, recording is pretty small):

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/50145178/68159930-bdcee500-ff20-11e9-9b68-20926bb1140d.gif)

**Solution, possible implementation and alternatives**
I thought of adding a main link button like in Harmor for instance, but I think a better way to do it could be with a context menu option on each parameter, or at least the ones that we judge could be "linkable" :  "Link with Scene B" if we're in Scene A, and "Link with Scene A" if we're in Scene B.

I don't know how hard would it be regarding automation and stuff like that though...

**Comment by baconpaul** [comment]
I think this is a clever idea

**Comment by mkruselj** [comment]
I guess certain parameters couldn't be linkable. For example, oscillator parameters could link only if you have exactly the same oscillator type across the two scenes. Ditto for FX.

**Comment by mkruselj** [comment]
Issue #1410 is a more generalized version of this one, so it's a superset of this request, hence closing this one in favor of the superset.
