### ISSUE TITLE
FreePiano host produces no sound with Surge on Windows

### ISSUE THREAD

**Issue by LoveBodhi** [surge-synthesizer/surge#1277]
http://freepiano.tiwb.com/ I just tested Surge with FreePiano, but it doesn't work properly.

**Comment by baconpaul** [comment]
Can you let us know a bit more like which os which version and flavor (vst2/3, 32 or 64) and what errors you got? Also does surge work in any other host on your system? 

Thanks

**Comment by LoveBodhi** [comment]
other hosts works fine, but with FreePiano, it doesn't produce any sound.

**Comment by baconpaul** [comment]
OK thanks. Tagged the issue as a windows host issue and clarified title a bit.
