### ISSUE TITLE
Integer Parameter right-click menu doesn't work

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1282]
**Bug description**
I think the title is pretty self explanatory.

**Version**
Latest nightly, VST3 x64, FL Studio 20.5.1 x64, Windows 10 x64.

**Comment by baconpaul** [comment]
Same for M2, sine shape, distortion wave shape, etc..

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/blob/72f037e83780c1f74de49308e6d697972ab5bb2d/src/common/gui/SurgeGUIEditor.cpp#L2027

**Comment by baconpaul** [comment]
Obvious fix is add another branch if button & kR && valtype == int just put in the titles bit; or share the code between float and titles and break out earlier if you are int only. Basically skip all the modulation stuff for non-float but not the name and value.

**Comment by baconpaul** [comment]
![RMBInts](https://user-images.githubusercontent.com/13387561/68551446-0a139c80-03db-11ea-8614-21a275b2abbb.gif)
There we go. Fix inbound.
