### ISSUE TITLE
Uni Spread "Absolute" mode doesn't work in Window and SH-Noise oscillators

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1284]
While playing notes on different octaves in these two OSC modes, they are still being de-tuned proportionally to the notes I play, where as in other OSC modes, in Absolute spreading, the higher the note, the less detuned the voices are from each other (as it should be).

VST3 x64, FL Studio 20.5.1 x64, Windows 10 x64.

I think that this is a pretty old bug, as it was present in a version from last June (and possibly before that as well).

**Comment by baconpaul** [comment]
Oh yeah. That’s a bug that her been there since I implemented absolute in the summer. When I added absolute mode I bet I didn’t add it to window and S&H just the other oscillators. thanks!

**Comment by baconpaul** [comment]
I'm going to push this out of 1.6.4 for now since I want 1.6.4 to be a bit smaller.

**Comment by baconpaul** [comment]
Turns out it is just the window oscillator; S&H is doing the right thing if you set it in correlation=1 mode (where the frequency not the noise shows the pitch).

**Comment by VincyZed** [comment]
Ah yes that's right, Absolute in S&H works fine, just tested as well. Awesome!
