### ISSUE TITLE
Stereo Phase Difference for Chorus

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1285]
@mkruselj and I were chatting on slack this morning about the chorus, and he noticed that the chorus modulation was the same phase in both L and R channel; which is true it is. That’s because there’s a single, and not a stereo, LFO.

So we decided the following

- independent L and R LFOs which default are the same
- Add a phase control to the modulation section which sets a different phase for each of the LFOs
- Maybe (but still TBD when I code it up and screw around with it) add a waveshape other than triangle which takes you into sine and square land. But we aren’t sure that’s useful.

**Comment by mkruselj** [comment]
Sine waveform is for sure useful, square not really. That's more for tremolo (and even then it'd be more trapezoid than square because you don't want those discontinuities modulating your output volume).

**Comment by baconpaul** [comment]
Yeah on slack I had said “tri -> sin -> sin^3 -> sin^9” type thing as what I described here as “square land”. Basically changing the shape of the LFO to be ‘faster’ or ‘time varying’ more interestingly. Obviously a hard square is a bad bad idea...

**Comment by baconpaul** [comment]
Hmm so right. This is unsurprisingly more complicated than I thought. A naive implementation of stereo channel phase shift seems to not work as I'd hoped.

I have squirreled away my code for another day in a branch. But don't think we will see big chorus upgrades today.

**Comment by baconpaul** [comment]
OK I just took a closer look at this one and I think the original spec is a bit wrong

Right now the chorus has 4 voices all of which are out of phase and spread across the stereo field. My diff above makes no sense. So there's not really much we want to do with stereo field and phase I don't think (the width parameter does M/S expansion already)

I can run those voices at drifting rate but that gives weird beating sounds

So I guess from looking at my abandoned silly change above and the current state of the code it's not clear to me what we want to change any more. What exact param against the 4 voices do we want to add? 

I can definitely make the chorus worse. Can't make it any better though.

**Comment by baconpaul** [comment]
Like: my original statement is false. There's not a single LFO. There are 4 of them spread across the field.

**Comment by mkruselj** [comment]
I see!

I suppose that parameter would then make it so that phases between left and right oriented LFOs are shifted more? I mean I don't know what the current LFO offsets are, but the idea is to go from all LFOs in phase, to all LFOs spread out in phase like it's now. Maybe?

**Comment by mkruselj** [comment]
So, the solution here is to just have a better chorus effect, like that BBD ensemble. Not gonna mess with the existing chorus (but it is kinda lame, sadly).

Closing issue.
