### ISSUE TITLE
LFO wave in LFO editor is drawn under the Min and Max lines

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1293]
**Describe the bug**
The LFO wave is drawn under the Minimum and Maximum lines in the LFO editor. 

Latest nightly, VST3 x64.

**Expected behavior**
LFO wave should be drawn over the Minimum and Maximum lines in the LFO editor so it doesn't appear thinner in these areas.

**Screenshots**
![lfo](https://user-images.githubusercontent.com/50145178/68954551-3ee47280-0792-11ea-8935-118762b3fff3.png)

**Comment by baconpaul** [comment]
This is just reordering the draw calls in COsicullatorDisplay.cpp. Super easy. Tagging for 1.6.4. Thanks for seeing it!

**Comment by baconpaul** [comment]
<img width="309" alt="Screen Shot 2019-11-20 at 10 12 23 AM" src="https://user-images.githubusercontent.com/13387561/69250952-9a41a680-0b7e-11ea-8636-2e50f33966b2.png">

There you go! PR in and headed to nightly now

**Comment by VincyZed** [comment]
Awesome, thank you!! :)
