### ISSUE TITLE
Feature: New static randomizing mode / waveform

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1317]
**The problem:**
Right now, if I want to send a randomized value each time a voice / scene is triggered, the best way to do this is to use the LFO with the S/H waveform and set it to the slowest rate possible (0.008 Hz).
The problem is that its value would change after a little more than 2 minutes, since it's at 0.008 Hz.

**Feature request:**
We were talking about that over on Slack, but there could be 2 ways to implement this:
1. Allowing the LFO speed to go down to 0 Hz. When set to S/H and using the existing "Random" trigger mode, this would behave like a randomizer. This wouldn't add any new mode / waveform.

2. Adding a new "Randomize" waveform or mode. This could lock the LFO rate to 0 Hz and remove the Rate slider (like the "Width" parameter is disabled when using certain types of filters), and lock the trigger mode to "Random". Magnitude could set the extremums of the randomizer. Deform could make it so the odds of hitting a bigger / smaller value than 0 are greater? Not sure what the Phase / Shuffle could do. This approach would be more explicit for the user and would allow for more customization of the LFO parameters in the context of a dedicated randomizer.

**Additional context**
This is really useful when routing the LFO to voice pitch for instance, where each time a note is triggered, the pitch of each voice would be slightly randomized, to give it a more analog feel.

**Comment by mkruselj** [comment]
If this comes to pass, I am voting for suggestion 2 here.

**Comment by mkruselj** [comment]
OK so Paul helped Vincy to implement LFO phase scrubbing, so this essentially allows Vincy to make LFOs do his bidding! Yay!

**Comment by VincyZed** [comment]
Yup, this has been done on #2135! :)
