### ISSUE TITLE
Preset: Adding custom preset to 3rdparty requires a restart for the newly added preset to be selectable

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#1324]
**Describe the bug**
1) Open Surge and click on menu --> data and patches --> open factory data folder
2) Create a custom folder in patches_3rdparty and copy the attached preset into your newly created folder
3) Do menu-->rescan all data folders
4) Notice you can now see your custom folder and it is populated with your preset as verified by clicking on the preset browser and checking the menu
5) Click on the patch browser and navigate to your preset and select
6) Notice nothing happens after you click it. Patch browser still shows Init. 

<img width="197" alt="Screen Shot 2019-11-21 at 7 59 55 AM" src="https://user-images.githubusercontent.com/11078351/69344496-15fe2a80-0c35-11ea-925d-b033e1491ed9.png">
<img width="500" alt="Screen Shot 2019-11-21 at 7 59 46 AM" src="https://user-images.githubusercontent.com/11078351/69344497-15fe2a80-0c35-11ea-850f-68cab97929e9.png">
<img width="1440" alt="Screen Shot 2019-11-21 at 7 59 40 AM" src="https://user-images.githubusercontent.com/11078351/69344499-15fe2a80-0c35-11ea-863e-1e8b5b6ec783.png">

[Scene Test.fxp.zip](https://github.com/surge-synthesizer/surge/files/3874986/Scene.Test.fxp.zip)

Expectation is that the patch loads and is available after the scan.

**Comment by itsmedavep** [comment]
![Preset Load](https://user-images.githubusercontent.com/11078351/69344679-65dcf180-0c35-11ea-8a0b-6f6dbb1ce9e9.gif)

**Comment by baconpaul** [comment]
Let me tag this 1.6.4.1 also in case it is a catalina specific thing. I can at least confirm if not fix it once I get a catalina installer running.

**Comment by baconpaul** [comment]
Hey @itsmedavep I can't reproduce this for the life of me, and now am on catalina.

Does it still happen for you reliably? Just cleaning up old issues as we head to 1.6.5

Thanks!

**Comment by itsmedavep** [comment]
Im still seeing this with the latest nightly build. It is reliable and presents the same way. Removing the plug instance and then readd and the preset shows up. 

Hmmm. Thats really odd.

**Comment by baconpaul** [comment]
OK! I will look for 1.6.6 then. Thanks!!

**Comment by itsmedavep** [comment]
<img width="588" alt="Screen Shot 2020-02-02 at 12 42 59 PM" src="https://user-images.githubusercontent.com/11078351/73613311-d26f5780-45b9-11ea-9f47-b23842a18ed1.png">
This is what the about shows for posterity.
