### ISSUE TITLE
No way to export wavetables from a patch 

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1341]
Pretty straight forward really. You load a patch and want the wt the synth makes it hard. You can copy and paste the osc but you can’t get it as a standalone

**Comment by mkruselj** [comment]
Would this be in WAV format, 2048 points per frmae (regardless of how many points the original WT had)?

**Comment by baconpaul** [comment]
No I was thinking you would export exactly what’s in the patch probably as a wav with surge tags

This is successful if loading a patch exporting the wav and then reloading the wav is a complete noop. 

We could add a feature “export as 2048 samples” and do the interpolation. But that’s not the default

I was also thinking - like you I suspect - of this being a good first issue

**Comment by baconpaul** [comment]
Oh and it is not at all obvious how to best make a 2048 version of a 128 sample wavetable. I actually coded this up in python and even good interpolations like Lanczos have problems and introduce ringing in some cases in the library.
