### ISSUE TITLE
Report that Installer doesn't install resources reliably on Catalina

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1344]
@itsmedavep has run on catalina but it seems the installer doesn't correctly install resources; a user with a fresh catalina report (Blaz Babnik on Surge) reports that /Library/Application Support/Surge was left empty-ish by our installer. 

Talking the user through git checkout and manual rsync worked; so this is really a matter of installer not pushing properly to the location.

**Comment by itsmedavep** [comment]
I can verify this. 

I upgraded to Catalina which meant that these directories still existed which in turn masked this problem. 

Once I moved /Library/Application Support/Surge/ and installed I saw this issue.

<img width="990" alt="Screen Shot 2019-11-25 at 8 34 01 AM" src="https://user-images.githubusercontent.com/11078351/69549383-d1d59780-0f5e-11ea-81f4-a51d61d1a556.png">

**Comment by baconpaul** [comment]
If I had to bet, I would bet that the resources installer which dumps assets in /tmp then copies them with a script is having that script not run on catalina - namely the post install script is failing for some reason unknown to me until I upgrade.

**Comment by baconpaul** [comment]
@itsmedavep confirms he has a /tmp/Surge which means the installer unpacked and didn't run the post install script.

**Comment by itsmedavep** [comment]
<img width="543" alt="Screen Shot 2019-11-25 at 9 28 37 AM" src="https://user-images.githubusercontent.com/11078351/69554288-2ed54b80-0f67-11ea-887e-039a22a6220f.png">

Here is the confirmation of the /tmp/surge dir after install.

**Comment by baconpaul** [comment]
Dave and I have both confirmed that this diff fixes the catalina installer.
