### ISSUE TITLE
Digital envelope release stage states 2 and 3 look the same

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1349]
...yet they don't sound the same.

![digienvrel](https://user-images.githubusercontent.com/2393720/69723558-2709d880-111a-11ea-98a0-f44f64373abf.gif)

(Zoom in the browser if you can't see!)

**Comment by baconpaul** [comment]
Just for reference, the three types are linear, quadratic, and cubic,so just make the third state appear “even faster” in the SVG

**Comment by baconpaul** [comment]
Seems this got fixed by @VincyZed in ef57a35e21edfb9461c36a40600731c29479ade3

Thanks @VincyZed !

![env](https://user-images.githubusercontent.com/13387561/74105475-11f2f200-4b2c-11ea-90bd-a7d7c6247a93.gif)

Closing
