### ISSUE TITLE
Migrate from premake5 to CMake

### ISSUE THREAD

**Issue by jsakkine** [surge-synthesizer/surge#137]
There are numerous reasons to migrate to CMake:

- CMake is a very mature build system where we can find ready made solution for almost anything we might ever encounter.
- CMake is designed for C++. Just to give you a glimpse, it provides things like defining the C++ standard version in the level that you can even specify separate standard versions for internal and outfacing interfaces. Most of the time you don't need to mess with the compiler flags.
- CMake has so called _packages_ for defining various dependencies. Right now we don't define dependencies at all, which can cause "silent" failures that cause either compilation or run-time errors.

Premake is a simple build system but it is some ways too simple, which makes defining more complex things chaotic.

**Comment by jsakkine** [comment]
Started writing build files. Try to get something out ASAP.

**Comment by jsakkine** [comment]
Here is also a motivational video about CMake and its merits: https://www.youtube.com/watch?v=rLopVhns4Zs

**Comment by baconpaul** [comment]
Very interested to see how this plays out. Thank you.

**Comment by jsakkine** [comment]
Enough of merry jolly ho ho ho for me. Had one blocker with this: we have multiple targets with the same filename, which cmake does not allow (you can enforce it though with an option but it is not really a good practice so lets not do that).  What you can do, however,  is to have different names for different targets (e.g. target for the AU plugin ought to be  `Surge-au`) and use a properties called `PREFIX` and `OUTPUT_NAME` to define the output binary.

Other than that the existing build file do not have anything special that cannot be easily mapped to cmake.

**Comment by jsakkine** [comment]
I'll do Linux and macOS targets and make the first PR. Does not matter if the Windows is not here because not going to make a commit that would remove `premake5.lua`.

**Comment by jsakkine** [comment]
One thing I'm doing differently other than the whole build system, is to use explicit list of source files. It removes one angle of unpredictable behavior when making builds. I consider wildcards in project files a harmful anti-pattern.

**Comment by jsakkine** [comment]
```
CMake Error at CMakeLists.txt:67 (add_library):
  The target name "vst3/Surge" is reserved or not valid for certain CMake
  features, such as generator expressions, and may result in undefined
  behavior.
```

i.e. the first option it is.

**Comment by esaruoho** [comment]
what's happening with this one? should the ticket be closed? are we premake5-less now?

**Comment by baconpaul** [comment]
The main fork at master can answer that! Still no cmakefile and still requires premake 

@jsakkine is working on it. Ticket should stay open 

Thanks

**Comment by jsakkine** [comment]
@esaruoho, check my latest comment in #171. Gives also background to this. To summarize, targeting this after the first stable release. No reason to close it.

**Comment by jsakkine** [comment]
Writing CMakeLists.txt that compiles the headless version on **all platforms**. The reason for doing this is that it can be easily tested with any sort of environment albeit I plan to use it at first for embedded testing (i.e. close the ARM intrinsics issue).

**Comment by baconpaul** [comment]
Great. Maybe we can super simplify the headless premake to just call cmake then; then our ci huilds can start to test this

**Comment by jsakkine** [comment]
I think we should close this now and then open an issue whenever we want to do CMake for GUI.
