### ISSUE TITLE
LFO 1 Step Seq trigger lane enhancement

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1385]
![image](https://user-images.githubusercontent.com/2393720/69922162-28c8f880-149a-11ea-94e8-c7a530b153a4.png)

**Comment by VincyZed** [comment]
Great idea!

**Comment by baconpaul** [comment]
Oh awesome this is also pretty easy to do

Right now the LFO has a bool called retrigger_EG which is set by the trig mask. That trig mask has values of 2^step but is stored in an int with some hairy values basically meaning which step is active.

But there's "room" in the trig mask for at least 2 more bits I think, which we can use for "A Only" and "E Only". So then the storage will be clear. So we should be free of not having any streaming changes.

Then change retrigger_EG from a bool to a state variable with values both, a, f, none.

and then bobs your uncle.

**Comment by baconpaul** [comment]
Oh of course we will have to make trig mask a 64 bit value since we have 3 states at 16 positions so need 48 bits.  To be most portable that's an "unsigned long long". That's not a problem in memory at all but it is a bit of a problem at the XML boundary. 

This is streamed as an int attribute into XML so is stored as text not binary. 

But it also will be a pain on 32 bit systems - and need checking carefully.

**Comment by baconpaul** [comment]
So just so I remember

Tinxml uses “int” as does SurgeStorage and these don’t have portable sizes

So the mask in SurgeStorage should go to a uint64_t and include stdint.h

Then we should truncate that and cast it to an int for backwards compatibility but also stringify it ourselves in SurgePatch using std::stoull and std::to_string and store that on mask_64 or some such

Then when we load a patch if mask 64 is there great. And if its not also great

So I’m now back at thinking this isn’t very hard again! :)

**Comment by baconpaul** [comment]
OK I have a first version of this coming as a Pull Request I think; I want to get it in alpha testers hands but it isn't quite done. Will see. A few things

1: Want some user feedback on the UI/UX
2: Have to go and test win32bit since I used that uint64_t although I think I got it right
3. Have to test linux to make sure drawing code works same both sides

**Comment by baconpaul** [comment]
Evil reports that windows skips the aeg
It’s because 1L << 32 is too small on windows
Use UINT64_C(1) << 32

**Comment by baconpaul** [comment]
loop start/end handles: #2A7BEA
darker steps: #9ABFE0
lighter steps: #A9D0EF
steps could be the same dark blue as in the matrix #123463

And the left right arrows need vectorizing 

And refactor the code so bitmap and vector call same path

**Comment by mkruselj** [comment]
Also maybe just make try same color for loop start/end handles as for steps #123463. Could look better than #2A7BEA, but I leave the final call to you.

**Comment by baconpaul** [comment]
Also also right click or shift click to toggle special

**Comment by baconpaul** [comment]
Also click-dragging on those squares makes them blink weirdly

**Comment by mkruselj** [comment]
On Windows at least FEG-only/AEG-only states seem inverted: blue square to the left triggers amp env only, when it should be filter env.

Also none of these triggers seem to work with FEG/AEG in Analog mode.

**Comment by baconpaul** [comment]
Also use bg rather than gray for divided items

**Comment by baconpaul** [comment]
Maybe I should just break down and vector draw the section too, then I can get F and A in there and stuff.

**Comment by baconpaul** [comment]
Sigh - on mac the blue square to the left triggers filter no problem. I'll have to debug that in a windows VM.

**Comment by mkruselj** [comment]
Maybe also try these colors for inactive steps:

darker: #E7AF67
brighter: #ECBF86

**Comment by baconpaul** [comment]
I noodled with this a bit and I think it makes it a bit too "invisible" against the background vs the gray. With the gray you retain the sense of a 'special region'. It's a test thing but I think I'm gonna stick with the gray and blue for now.

So I think this is all wrapped up! Let me close this issue now. Thanks for the idea!
