### ISSUE TITLE
Turn on tempo sync for LFO/SLFO all parameters at once.

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#1398]
There are a couple of cases here that may make sense to me at least. 

1) Enable tempo sync for an entire LFO/SLFO etc from a single user gesture. This would enable tempo sync on all available parameters at once. Nice and quick to get the tempo sync enabled and then the user could further adjust the individuals tempo as per needed.

****** Below here may just be crazy talk but still useful*****
These may be differing features entirely TBH. I think 1 above is the minimum case to be addressed. 2 would be useful to me as well. 3 may just be crazy IDK. 

2) Same as above but once enabled all of the sliders snap to the same note duration. AKA adjust one parameter to 1/4 notes and they all follow. 

3) For the sake of completeness, you could also treat this like grouping the faders and then have them all adjust relative to one another. ALA grouping faders on a mixer channels in your DAW.

**Comment by baconpaul** [comment]
I think I'll bounce 2 and 3 to a separate issue once I've done 1. I can do 1 for the 1.6.5 release tho. Not hard! and good idea!

**Comment by itsmedavep** [comment]
Cheers! It may advisable to consider something similar for the mixer in Surge as well. 

LOL. Ill stop the feature creep now! And just let me know if you want me to break these out into separate issue for you.

**Comment by baconpaul** [comment]
Yeah coupling is a nice s++ thing - I’ll break it out when I close this one it’s fine until then. Thanks!!

**Comment by baconpaul** [comment]
![TSAll](https://user-images.githubusercontent.com/13387561/70377443-83bb7f00-18e2-11ea-9929-7f7c7698f7ba.gif)

There you go. headed to master now if the builds all work.
