### ISSUE TITLE
Modulating the "Phase/Shuffle" parameter with another LFO does not work

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1414]
**Describe the bug**
Modulating the "Phase/Shuffle" LFO parameter with another LFO does not work.

**Surge version**
Latest nightly.

**Expected behavior**
"Phase/Shuffle" modulation should work.

**Additional context**
 Although "Random" mode can be used most of the time, there are times where precisely modulating the phase of an LFO can be useful instead of just randomizing it.

**Comment by VincyZed** [comment]
Modulating a voice LFO's phase from another voice LFO does not currently work.

**Please let us know your surge version**
Latest nightly, VST3 x64

**Expected behavior**
LFO Phase modulation from another LFO should normally work.

**Additional context**
This **only affects LFOs**. It does work when modulating an SLFO's phase with another SLFO, or with a note property modsource like Keytrack and such.

**Comment by baconpaul** [comment]
Just for completeness, an SLFO modulating an LFO phase start works also.
This is really just LFO->LFO
And it is probably an order of initialization problem in the voice 
Namely the modulating LFO hasn't "run" when the phases is snapped.
May not be easily solvable - in which case I'll split into a separate issue.

**Comment by baconpaul** [comment]
OK fixing this is too ugly for 1.6.5. I think I'll leave this partly broken and bump it, since the changes I'm looking at right now are pretty big, so either I don't get the problem, or the changes are big, and in either case, I shouldn't do that this late in a release cycle.

Will fix though. Tagging 1.6.6

**Comment by baconpaul** [comment]
There's a chance 29850683dbc3c13fab8d0491214e13aac4088c95 fixed this by accident.

**Comment by VincyZed** [comment]
Just tested, this has not been fixed yet.

**Comment by mkruselj** [comment]
I have tried modulating VLFO2 phase with VLFO1 and indeed it doesn't work. Unless I disable VLFO2 - then it works. Maybe a clue?

**Comment by baconpaul** [comment]
So the phase is snapped at attack and not read again unless rate is disabled 
And the vlfo attack in order
I’m no longer sure this is a fixable bug

**Comment by mkruselj** [comment]
How come SLFO -> VLFO Phase works then?

**Comment by baconpaul** [comment]
Because the slfo run outside of the voices. The vlfo creates new modulator instances per voice

**Comment by baconpaul** [comment]
That is: the slfo will not attack at (almost every) voice on but all vlfos will

**Comment by mkruselj** [comment]
Gotcha! Shall we close this one, then?

**Comment by baconpaul** [comment]
Yeah I think so
