### ISSUE TITLE
FL Studio crashes when copying LFOs two times

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1425]
**Describe the bug**
FL Studio crashes (simply closes unexpectedly without any error message) when doing the following:

**To Reproduce**
1. Open Surge.
2. Copy any LFO once.
3. Copy any LFO a second time.
4. FL Studio crashes.

**Surge version**
NIGHTLY-2019-12-16-aa75776
VST3 x64

**Desktop config:**
 - OS: Windows 10 x64
 - Host: FL Studio 20.6 x64

**Additional context**
Weird crash that _probably_ only happens since recently. Tested in 1.6.4.1 VST3 in the same environment and it works fine (the crash does not occur).

**Comment by baconpaul** [comment]
I didn’t even know you could copy an LFO! Will look.

**Comment by baconpaul** [comment]
Oh yeah I introduced this in the nightly with a half-completed thing which I realized I don't need anyway. Will fix this morning. Thanks!

**Comment by VincyZed** [comment]
Awesome. Thanks! :)

**Comment by baconpaul** [comment]
Yeah refactored that half finished code to (1) be less clumsy and (2) not crash anymore. Pull request in now. Should be in the nightly in an hour or so. Thanks - great catch!
