### ISSUE TITLE
FL20 VST3 Menus

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1434]
The FL20 VST3 Host menus give us entries like

```
-Automation
```

which when rendered in FL menus show up as headers; but which don't set the VST3 kGroupHeader item flag. 

So if( host == FL && name[0] == '-' ) do something clever

in the vst3 menus

Tagging @VincyZed

**Comment by mkruselj** [comment]
Actually we have a similar, but not the same, situation in Reaper.

![image](https://user-images.githubusercontent.com/2393720/71817083-0a4fb180-3085-11ea-9d09-5eb62c7695a4.png)

The bottom three entries are supposed to be in a submenu, apparently:

![image](https://user-images.githubusercontent.com/2393720/71817182-5bf83c00-3085-11ea-9467-f1811e0a81d3.png)

This menu becomes available (not greyed out) when you MIDI learn a plugin parameter.

**Comment by baconpaul** [comment]
OK I have a fix for this coming. One gotcha - the parent menu (default controller mappings) is disabled on reaper mac but vstgui doesn't let you disable parents. 

Should be in a nightly soon. Appreciate some testing of this (and of course of everything else).
