### ISSUE TITLE
Improve sensitivity of Split point parameter

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1436]
Currently, the Split point parameter is **extremely** sensitive to mouse movement. I can go from minimum to maximum key in just about 2 cm of mouse travel. Mouse Behavior in the menu doesn't seem to affect this.

Not only that, but apparently this slider responds to left-right movement. I'd kinda expect up/down. But maybe having it respond to both would be good, dunno...

And not only THAT, when we're in Channel Split mode, it actually responds slower to mouse changes than it does in Key Split mode (and yeah Paul said this is because of a dirty hack). :)

**Comment by mkruselj** [comment]
Also mousewheel is apparently supposed to work on this control but it doesn't when the slider is at min or max. Mousewheel doesn't budge.

Also, it goes to MIDI note 128 which doesn't exist (G#8), max is MIDI note 127 which is G8.

**Comment by baconpaul** [comment]
Wow yeah that is way too sensisite
And the mouse wheel just keeps on going into the stratosphere
So fix both of those problems this morning!
