### ISSUE TITLE
Sliders don't follow touches with Windows 10 touch sceen

### ISSUE THREAD

**Issue by nathankopp** [surge-synthesizer/surge#1443]
When using a touch screen in Windows 10 to control the sliders, they do not work as expected.  If you slide your finger a little to the left and then leave it stationary, the slider continues moving.  It's as if distance-from-center becomes velocity.  This makes touch-screen usage unworkable.

* Surge Version: 1.6.4.1
* Plugin type: VST3 Windows 10
* Bits (32/64): 64

**To Reproduce**
Use VST3 with Windows 10 on a PC with a touch screen. Touch a slider and move your finger just a few pixels in one of the slider's directions.  The slider will continue moving even if your finger is stationary.

**Expected behavior**
The slider should follow your finger 1:1.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Host Reaper
 - Version 6.0

**Comment by baconpaul** [comment]
Do you mind if I ask what type of physical device you are using for windows 10 touchscreen? Since step one is trying to simulate or get our hands on such a thing some details would help.

I’m a Mac user and vm user so not sure I will be able to repro easily unless a friend has (whatever device you have) or another member of our volunteer set does

Alternately if you are comfortable as a developer I can give some hints as to where I might look. Long shot I know but figured I’d ask

**Comment by nathankopp** [comment]
Lenovo Yoga 920.

Yes, I am a developer so I can take a look at the source code and see if anything sticks out.  Let me know where to start looking.

**Comment by baconpaul** [comment]
Excellent

The directions on the readme on the main page are pretty up to date about how to build. Someone tried them a few weeks ago and got a working vst3. We build every commit on windows using that approach too so step one obviously is check out the code, grab the tools, etc... For people developing for the first time who want to test if their build worked i usually tell em to look in src/common/gui/CAboutBox.cpp where the about text is. Just add something there like “THIS IS MY BUILD” or what not and make sure that menu/about shows it. If so you have reaper loading your dll. Great.

The slider code is all in src/common/gui/CSurgeSlider.cpp and there’s four methods in there that matter. OnMouseDown/MouseMove/MouseUp and onWheel. There’s a small chance your screen is sending a gesture which vstgui conflates with a wheel in which case onWheel will trigger but probably not.

You can see in the onMouseBlahs we are updating an internal value and then calling notifylistener. Not rocket science.  All right around here. https://github.com/surge-synthesizer/surge/blob/6109a95f24699600686f1204b8e68eb0d6bb48d7/src/common/gui/CSurgeSlider.cpp#L386

We would love and welcome more developers to the project! Just a heads up that I’m on a couple of week break from surge so will be less quick to respond than normal with questions and stuff - especially between christmas and new year. But there’s folks on our slack who can help too, and the directions for that are all on the readme also.

Best

**Comment by mkruselj** [comment]
I can test touchscreen behavior on my Surface Pro 4, just FYI.

**Comment by baconpaul** [comment]
Cool do you see the same as the original poster?

After holidays I will upgrade to catalina so then I can try the iPad sidecar thing on my Mac too.

**Comment by mkruselj** [comment]
>  Cool do you see the same as the original poster?

Yes, I do.

**Comment by nathankopp** [comment]
I've gotten Surge to build and I've found the offending code.  There's a section in line CCursorHidingControl.cpp, lines 64-75 that seems to be the cause of the problem. If this section is commented-out, and if mouse control is set to "exact", then touch controls work as expected.

However', I'm not sure what this "_isDetatched" flag is supposed to be used for, so commenting out this code might cause negative side effects in other situations.

#if WINDOWS
   if (_isDetatched)
   {
      double ddx = where.x - _detachPos.x;
      double ddy = where.y - _detachPos.y;
      double d = sqrt(ddx * ddx + ddy * ddy);
      if (d > 10 && SetCursorPos(_hideX, _hideY))
      {
         _lastPos = _detachPos;
      }
   }
#endif

**Comment by nathankopp** [comment]
Note: this issue is that _lastPos gets reset to _detachPos instead of tracking with the most recent x,y coordinates. That means that the delta computed during the next onMouseMoved event will be incorrect.

**Comment by baconpaul** [comment]
Ahh great debugging
That’s the code on windows which hides the mouse visible cursor then returns it to the starting spot when you drag with a mouse. It makes perfect sense that it would screw up a touch display 

Does windows have a way to know if a gesture is a touch gesture do you know?

**Comment by baconpaul** [comment]
Oh and one obvious (but not super awesome) idea if the answer is “no” or “not through vstgui” is to add a user pref for “touch screen” which is togglable in the menu after exact and stuff which basically comments out this code

**Comment by nathankopp** [comment]
It looks like VSTGUI might put too much of a barrier between Windows and Surge to determine if the event is from the mouse or a touch. I don't see any touch-related details in the data structures that are passed to onMouseMoved().  Also, I checked the VSTGUI source that is part of the Surge build, and it doesn't appear to register to receive touch-specific messages. Therefore, it looks like VSTGUI would need to be modified to be able to tell the difference between mouse and touch. I searched Google and found the following documentation for registering to receive touch events in Win32: https://docs.microsoft.com/en-us/windows/win32/wintouch/guide-multi-touch-input

I've tried running Surge both with and without that block of code, and the only difference I see in behavior occurs when the slider is near the edge of the screen.  With the code enabled, you can slide the handle the full range, including past the edge of the screen.  When the code is disabled, the hidden mouse cursor is constrained by the screen pixels, and therefore you sometimes can't move the slider it's full range. Because the scaling factor is usually less than 1.0, this means that the invisible mouse cursor hits the edge of the screen before the slider handle does, and the slider stops moving unexpectedly.

One possible compromise might be to disable this code when the scaling factor is equal to 1.0.  Thus, if the user chooses "exact", touch gestures will work as expected, and I think the only negative side-effect will be that the slider handles can't be moved past the edge of the screen (but will stop exactly at the edge, and not before).

**Comment by baconpaul** [comment]
Thank you for the research.  I really appreciate you diving in on this problem, especially as I don’t have an environment where I can debug it (since I’m a mac user).

Also I am unsurprised vstgui suppresses the message; and agree we shouldn’t fork it further.

But reading the documentation you shared it seems we may be able to detect whether our input device is a touch device. From that document this call

```
// test for touch
int value = GetSystemMetrics(SM_DIGITIZER);
if (value & NID_READY){ /* stack ready */}
if (value  & NID_MULTI_INPUT){
    /* digitizer is multitouch */ 
    MessageBoxW(hWnd, L"Multitouch found", L"IsMulti!", MB_OK);
}
if (value & NID_INTEGRATED_TOUCH){ /* Integrated touch. Probably message box here too */}
```

Lets us know if we have a touch device as the device for our primary input digitizer; and isn’t event dependent. 

Unfortunately I don’t have a windows touch event but I wonder if we stuck that code into the CCursorHidingControl and ran surge on your touch screen and then on a non touch screen if we would be able to detect the state. At that point, on a touch screen we can skip the hiding code as you’ve already found.

**Comment by nathankopp** [comment]
Ok... here's what I ended up with, which works on my Lenovo laptop.  I haven't tried it on a non-touch system, but it successfully detected touch capabilities of my screen.

It's too bad VSTGUI doesn't support touch events for Windows. In the latest code on github for the project, there's at lest some support for touch events in the context of iOS.  I also noticed that surge is using a fork of vstgui that's a bit out of date. Maybe a pull from vstgui's master branch is in order sometime?  Since it's already forked, adding true touch support might not be too complicated.

```
#if WINDOWS
   if (_isDetatched)
   {
      // test for touch
      int value = GetSystemMetrics(SM_DIGITIZER);
      bool hasTouch = (value & NID_READY)?true:false;

      if (!hasTouch)
      {
         double ddx = where.x - _detachPos.x;
         double ddy = where.y - _detachPos.y;
         double d = sqrt(ddx * ddx + ddy * ddy);
         if (d > 10 && SetCursorPos(_detachPos.x, _detachPos.y))
         {
            _lastPos = _detachPos;
         }
      }
   }
#endif
```

**Comment by baconpaul** [comment]
Wonderful thank you. I will merge this in for 1.6.5. Super appreciated.

Yeah the vstgui fork was a hard decision but the zoom and Linux implementation had showstopper bugs. We should upgrade one day but that’s definitely one of those activities which will be painful, hard, annoying, and if it works, nothing will change. So hasn’t exactly met my “fun hobby project” thresholds :)

**Comment by baconpaul** [comment]
Hey @nathankopp so I tried the patch and it triggered on my non-touch-screen, but I think it is super close. I committed it with the slightly modified 

```
      bool hasTouch = ( value & ( NID_INTEGRATED_TOUCH | NID_EXTERNAL_TOUCH ) ) ? true : false;
 ```

which didn't trigger for me. I'll push this to master (along with a change that addresses #1455) once our CI completes and if you could test that change I would appreciate it!

And thanks for all your help here.

**Comment by nathankopp** [comment]
@baconpaul , your modification still works properly on my touch screen. Looks great!

**Comment by baconpaul** [comment]
Wonderful. Thank so much for the help and the testing! I'll close this issue.
