### ISSUE TITLE
Delay effect buffer init shenanigan

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1444]
Please open the attached Reaper project (opens VST3):

[surge delay test.zip](https://github.com/surge-synthesizer/surge/files/3998937/surge.delay.test.zip)

Play from the beginning of the project. Notice the pitch warble on the very first note.

Now stop playback, let the delay tail go away, and play project from the beginning again. No pitch warble at all.

This only happens when opening the project, so smells like delay buffer init shenanigans!

**Comment by baconpaul** [comment]
Well the good news is I see it on Mac also! Thanks for the clear test case!

**Comment by baconpaul** [comment]
OK I now know what's happening but don't quite know a fix yet.

The problem is that the initialization of the delay is called when the system is unstreamed but at that point the temposync is true; but the temposyncratio is still 0. This may be an order-of-operations bug in our VST3. Close.

**Comment by baconpaul** [comment]
(Oh and combine that with the delay smoothly changing time; so the delay time jumps from 0 up to the temposync value the first time then stays there).

**Comment by baconpaul** [comment]
OK I have a preliminary fix. Cool find!

**Comment by baconpaul** [comment]
Will have to apply the same fix to the FreqShifter (but only the freqshifter and the delay will need it).
