### ISSUE TITLE
False positive on install for Win 10?

### ISSUE THREAD

**Issue by bill545** [surge-synthesizer/surge#1446]
**Describe the bug**
The first time I tried to install I got an error from Windows' "Smart Screen" saying this file was potentially harmful. I felt pretty confident it was safe, so I bypassed, then exited. When I ran the install file again, it doesn't come up (I'm guessing Smart Screen flagged as safe). May be nothing, but FYI/FWIW.

**Please let us know your surge version**

* Surge Version: 1.6.4.1
* Plugin type (VST2, 3 or AU)  VST2
* Bits (32/64)  64

**To Reproduce**
Double-click on install file.

**Expected behavior**
No Smart Screen error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10]  Windows 10 Home, Build 17763.rs5_release.180914 1434
 - Host [e.g. bitwig, logic]  Didn't get that far :) 
 - Version [e.g. 2.4]

**Additional context**
None

**Comment by baconpaul** [comment]
Thanks. Is "Smart Screen" something built into windows or something additional you installed?

**Comment by VincyZed** [comment]
Yes it does the same thing here. It's built-in and is part of Windows Defender. I think it flags it because it is now "commonly downloaded"

**Comment by baconpaul** [comment]
Any idea at all what we would do to avoid that message?

**Comment by baconpaul** [comment]
So reading the windows site, it seems we need to (1) sign with some Cert; (2) apply for a "windows logo" or (3) live with this.

For now I'm choosing (3) just like we are on Catalina. Appreciate the flag though - good to know this is happening.
