### ISSUE TITLE
Holding down shift and sliding above buttons with mouse pointer activates them without left-clicking

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1447]
**Description:**
Holding down shift and sliding across buttons with the mouse pointer activates them without left-clicking, which is probably not intended behavior.

**Version:**
Latest nightly, VST3 64 bits.

**Expected behavior:**
Pressing "Shift" should not affect buttons whatsoever.

**Additional context:**
It does this with Scene mode, FX Bypass / Character, Polymode, Filter type selectors, octave buttons, Waveshaper shape, the EG stage curve controls (orange rectangles), and maybe more. It **DOES NOT** do it with a row or column with 2 buttons or less (A|B, Digital/Analog mode for EGs, etc.) It also does not do it with OSC 1-2-3 buttons. After a quick peak in the code I haven't found anything yet. I might take a deeper look eventually, but this is (I hope) probably a very easy fix nonetheless.

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/blob/6109a95f24699600686f1204b8e68eb0d6bb48d7/src/common/gui/CHSwitch2.cpp#L79

I think that line should be something like

If( draggable && ( buttons.getButtonState() && ( buttons.getModifuer & kShift )  )

Rather than ||

But I’m still without a laptop for a day or two. I can look and fix this when I’m back if that doesn’t do it.

And great find!

**Comment by baconpaul** [comment]
Actually reading the code more closely it seems like shift without mouse is exactly the behavior that draggable creates. So while this is odd it may be expected. But perhaps we should turn it off anyway. The && change would mean that drag with regular mouse down wouldn’t work. If we want to eliminate the shift-without-mouse-down we just knock out the entire || so it would be draggable && buttons.getButtonState() alone. I think. Like I said I’m on an ipad not a computer right now.

**Comment by VincyZed** [comment]
I think I've already tried that, but I will do it once more to be sure. Thanks!

**Comment by VincyZed** [comment]
Ah yes you were right, I didn't remove that line properly before. This fixes it!
