### ISSUE TITLE
Mono mode + sustain pedal + notes retriggered on release

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1459]
Currently, when we are in monophonic play mode and sustain pedal is pressed, Surge sounds only the last pressed note, it doesn't retrigger back to any previously held notes, which is how it works when sustain pedal is **not** pressed.

To me this feels supremely unplayable when playing very fast monophonic (shred) lines under sustain pedal to retain constant legato at all times. It breaks playing fast trills as a consequence.

I propose a change of this behavior, either permanent or through a global option. These situations should produce the same result:

press and keep holding key 1 > press key 2 > release key 2 = goes back to key 1

press sustain pedal > press and keep holding key 1 > press key 2 > release key 2 = goes back to key 1

press and keep holding key 1 > press sustain pedal > press key 2 > release key 2 = goes back to key 1

**Comment by baconpaul** [comment]
Link to #1554

**Comment by baconpaul** [comment]
Hey @mkruselj can you retest this at your convenience with a nightly? I think the pedal fix i put in 1.6.6. may fix it. i put it in the 17 milestone so if not we can grab it for that.

**Comment by mkruselj** [comment]
Nope it's still the same behavior as before...

**Comment by mkruselj** [comment]
@baconpaul Let's try to see if this can be a mode added easily on right mouse click for 1.8!

**Comment by baconpaul** [comment]
The trick is https://github.com/surge-synthesizer/surge/blob/00e5ba4f0af4d51f3ee1da24019c01176ea5d694/src/common/SurgeSynthesizer.cpp#L668

Basically if we are in a mono mode, and the hold buffer has a note other than myself which is held, release myself other than push myself to the hold buffer.

I am going to write down the cases as way of a Reg test too
