### ISSUE TITLE
Mouse pointer does not reappear after renaming assignable controllers

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1465]
**Bug description**
The mouse pointer does not reappear after renaming one of the 8 assignable controllers (macros) mod sources.

**Please let us know your surge version**
Latest nightly.

**Surge Version** 
VST3 x64.
FL Studio 20.6 x64
Windows 10 x64

**To Reproduce**
1. Right-click -> Rename one of the assignable controllers.
2. Write the new name without moving the mouse. Notice how the mouse pointer disappears. 
3. After pressing "Enter", the mouse pointer does not reappear.
4. To make it reappear, you have to left-click somewhere.

**Expected behavior**
Either the mouse pointer should not disappear on the first place, or it should reappear automatically after the modsource has been renamed.

**Comment by baconpaul** [comment]
This is somewhere in src/common/gui/PopupEditorDialog.h and src/windows/surge.rc

**Comment by baconpaul** [comment]
Seems this and #846 are the same thing

**Comment by baconpaul** [comment]
So the FX doesn't do this; the Rename does
but the Rename is also a CursorHidingControl
So I bet ti is there somewhere

**Comment by baconpaul** [comment]
So it's not CCursorHidingControl or even the invalidation loop

I don't know what it is or what is different about rename vs MPE Pitch Bend which doesn't do this

But even if I hammer in a 'setCursor' after the miniEdit my cursor doesn't come back.

**Comment by baconpaul** [comment]
Over in #846 it is noted that the cursor doesn't break if you make the name *shorter* and I can confirm that is true. maddening but true.

**Comment by K0rrid0r** [comment]
I just tried. It does disappear but appears again if you manage to click the same assignable controller.

**Comment by baconpaul** [comment]
if you make the name shorter it didn't when i just tried; if you make the name longer it does

**Comment by K0rrid0r** [comment]
More hints: You can actually click any wear in surge to make the mouse appear again. And making the name shorter did like you said. 

More hint: If you rename the assignable controller and hold the mouse outside of surge when clicking enter for the name to appear, The mouse cursor does not disappear.

**Comment by baconpaul** [comment]
right
the 'make it shorter and it doesn't disappear' is really the thing i'm pondering like crazy
gives me an idea though

**Comment by VincyZed** [comment]
Actually on my side, if you move the mouse before pressing enter, it doesn't disappear no matter where it is. And if not, it does disappear no matter where it is. To bring it back, I have to click anywhere on the screen once.

**Comment by baconpaul** [comment]
I've figured it out

**Comment by mkruselj** [comment]
What was it? :O

**Comment by baconpaul** [comment]
modality. i was already modal when i called a modal modal thing
just add a Call:later([],1) thing and it properly cedes the ui thread so the mouse stuff can work
