### ISSUE TITLE
Touch screen implementation issue when using the mouse

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1470]
**Bug description:**
After implementing #1443 ( awesome stuff by the way! ), when dragging with the mouse on sliders, they seem to respond 1:1 to the pointer (way faster than usual) and Shift precision does not work anymore.

**Surge version:**
Latest nightly, VST3 x64

**Expected behavior**
Mouse behavior when not using a touch screen should not have changed.

**Config:**
 - OS: Windows 10 x64
 - Host: FL Studio 20.6 x64

**Additional context**
This leads me to believe that Surge thinks I'm using a touch screen when I'm actually using the mouse.

**Comment by nathankopp** [comment]
Interesting. I don't currently have a non-touch Windows machine to test.  On my touch-enabled Lenovo laptop, mouse events did not cause 1:1 motion and still responded to shift, but touch events caused the new behavior.  We may need to also include the checks for system hardware (i.e. GetSystemMetrics(SM_DIGITIZER)) in addition to the checks for WM_GESTURE.

**Comment by baconpaul** [comment]
Yeah that’s right; I think we need the check we had one ago plus your thing both.

**Comment by baconpaul** [comment]
Oh and tag this 1.6.5 since clearly we need to fix it before we finally ship.

**Comment by nathankopp** [comment]
I've pushed a change to the feature/win_touch branch in my forked repository which should fix this issue (and also uses WM_POINTER* instead of WM_GESTURE).  This *should* fix the problem.  The change only affects the VSTGUI code.  @VincyZed, can you test this and see if it fixes the issue you experienced.

**Comment by nathankopp** [comment]
Note: I don't think we actually need to call GetSystemMetrics() to determine hardware support... I think the proper initialization of the variable, along with using WM_POINTER instead of WM_GESTURE, will solve the issue.

**Comment by VincyZed** [comment]
Yes, happy to test. Will let you know! :)

**Comment by VincyZed** [comment]
@nathankopp OK just tested with your fix, and it seems to work great on my machine at least!
