### ISSUE TITLE
Modulated LFO parameters's blue sliders do not update until refreshed manually

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1477]
**Bug description**
Modulated LFO parameters's blue sliders do not update until refreshed manually. This only occurs when the modulated LFO is selected as the mod-source.

**Version**
Latest nightly, VST3 x64

**To Reproduce**
1. Modulate an LFO with another.
2. **Select the newly modulated LFO as mod source.**
3. Right-click the modulated parameter -> Clear modulation.
4. Blue slider remains until selecting another LFO, then selecting back the previous one.

**Additional context**
Maybe related to #1424 ?

**Comment by baconpaul** [comment]
Ooh thanks yeah I bet it is related. Will look

**Comment by baconpaul** [comment]
OK have confirmed. Lemme find that code and get a quick fix in. Thanks for the excellent report.

**Comment by baconpaul** [comment]
Fix inbound.
