### ISSUE TITLE
Channel split / dual mode swapped when selected

### ISSUE THREAD

**Issue by pauleye** [surge-synthesizer/surge#1485]
**Describe the bug**
When selecting channel split mode, dual mode shows as selected, and vice versa. Selecting any of the scene A/B, oscillator 1/2/3, or routing buttons updates the selection to the correct one. Any other buttons don't seem to update it.

In the upper part of this image I've selected channel split, and dual in the lower.

![surgemodebug](https://user-images.githubusercontent.com/59901371/72525397-bdca5a00-386c-11ea-9482-fa5e8eb6a642.png)

**Please let us know your surge version**
* Surge Version: latest nightly, aa92f27 as of now, but it's been going on for a while
* Plugin type (VST2, 3 or AU): VST2
* Bits (32/64): both

**Desktop (please complete the following information):**
- OS: Windows 10 x64 1909
- Host: REAPER (32-bit and 64-bit)
- Version: 6.03 (and a few earlier versions)
- Also tested in Jeskola Buzz (32-bit) out of interest, same behaviour

**Comment by baconpaul** [comment]
Thanks. There’s a tricky bit of code which makes the display order and the switch value swap around. I bet I missed a spot. Tagging this 1.6.5 so I can fix before we ship final.

To be clear this is a ui only problem. The synth does the right thing but displays the wrong state yeah?

Appreciate the clear bug report. Thank you

**Comment by pauleye** [comment]
Yep, it's just an UI bug, functionality is as expected :)

**Comment by baconpaul** [comment]
Super - thanks! Will definitely fix before 1.6.5. Appreciated!

**Comment by baconpaul** [comment]
So both the AU and VST3 on macOS in Logic and Reaper (respectively) do not do this.

I'm on a new laptop so I don't have a VST2 environment up and running yet, nor a windows environment, but do you have the ability to test the VST3 on windows and see if that works? (At this point, the VST3 is generally a better choice than the VST2 in all environments).

**Comment by baconpaul** [comment]
(We still have to fix it of course!)

**Comment by pauleye** [comment]
Yeah, the VST3 works as expected (tested the 64-bit version only, same nightly build)
I'm still a bit of a dinosaur who hasn't really moved to VST3 yet at all :D

**Comment by baconpaul** [comment]
OK cool but that helps me figure out how to debug

Step 1: Make it so I have any system anywhere that can run the surge vst2 :)

(Brief plug for VST3. In reaper the nightly VST3 has the cool new menu extension feature, by the way. If you RMB on a surge control you will get the reaper param menu right there in surge! Still a few things to work out but it's great. Also if you are on Reaper 6.02 or greater, and the Surge nightly, you get corrected side chain routing for audio processing with surge (which required a joint change to reaper and surge). But we still need to fix the VST2 of course!)

**Comment by pauleye** [comment]
Oh, good to know, thanks :)

**Comment by baconpaul** [comment]
Anyway in good news, Mac VST2 does exactly what you report and I can now run it in reaper. (Like I said I'm mid setting up my new laptop so some things take a bit longer. Got it all running).

Will debug and report back.

**Comment by pauleye** [comment]
Sure, take your time :)
Just tested the VST3 RMB menu, that's...a surprise, and certainly useful :D

**Comment by baconpaul** [comment]
Found and fixed this. Let me walk it through CI and stuff but should be corrected in the VST2 nightly soon.

I'm not that proud of my fix. but you know, VST2 is old. I'm OK hacking around it a bit.

**Comment by pauleye** [comment]
Works as expected now, thanks :)

**Comment by baconpaul** [comment]
Awesome. Thanks for the super clear report! And have fun making music with Surge!
