### ISSUE TITLE
Surge as a Physical Modeling Synthesizer

### ISSUE THREAD

**Issue by MaurerMusic** [surge-synthesizer/surge#1490]
[Serge_Presets_1.zip](https://github.com/surge-synthesizer/surge/files/4082085/Serge_Presets_1.zip)

While scrolling through the factory presets I noted that there were very few physical modeled presets (comb filter), only a few FM and most did not take advantage of the second layer.  

About half of these presets utilize physical modeling techniques while the rest are FM or VA.  The MW was programmed to make meaningful changes and AT has an assignment (vibrato/tremolo) in most cases.  The second layer has been added where appropriate.

**Comment by baconpaul** [comment]
Hey thank you for sharing!

@mkruselj has been making sure our library has consistent naming and capitalization and stuff. Let me tag him here so we can review. And I can’t wait to play with your sounds. I’ve been using some of the feedback / comb  techniques lately in my sound design.

Would you be OK if, after a peek and potential rename or two, we included these in the distro, and if so, how would you like your name to appear in the “Third Party” menu (RMB on the presets and you can see a ‘second group’ with names like Inigo Kennedy and Roger Linn and what not).

Best, and thanks again!

**Comment by MaurerMusic** [comment]
Consistency is a good thing so feel free to adjust as needed.  If you want to put initials on the patches that would be "DJM".  As far as name, "MaurerMusic" or "Dan Maurer" is fine.

It would be great if the filter tracked keyboard pitch a little better when using noise to drive the comb filter.  Using a sine wave in Osc1 solves the tuning issue but takes away a lot of the unpredictable magic.  

Would anyone be interested in making the wind preset Roli compatible? Easy to do in Equator but still working on it in Surge.

**Comment by baconpaul** [comment]
I think patches targeted to MPE are super interesting; and there’s very few of them in the factory set (there’s the MPE set and the Roger Linn set and that’s it). So anything you can do to expand the MPE examples would be great!

**Comment by mkruselj** [comment]
Sequence>Tube Rhythm patch has some pretty nasty clicking in it. Worth checking out what causes it.

**Comment by mkruselj** [comment]
Anyways, here's the slightly resorted folder with Dan's patches, and some small naming tweaks (nothing major).

[Dan Maurer Surge patches.zip](https://github.com/surge-synthesizer/surge/files/4083489/Dan.Maurer.Surge.patches.zip)

**Comment by MaurerMusic** [comment]
[Updated.zip](https://github.com/surge-synthesizer/surge/files/4083958/Updated.zip)

Thanks for looking these over.  Carolina Sequence was clicking because the Step Sequencer was being used as a VCA gate.  I switched this to the filter cutoff and adjusted the Phase a little bit to get better results.  Oboe... has been switched to Mono ST.

**Comment by baconpaul** [comment]
Thanks - I have house guests for the long weekend here in the states but I can test and merge all this tuesday night / weds morning so it is part of 1.6.5. Thank you very much!

**Comment by baconpaul** [comment]
Sorry for the delay in getting to this. These are great! I'm merging them this morning so they should be in the nightly today and in the 1.6.5 release also. Thank you very much!
