### ISSUE TITLE
LFO Freerun and Keytrigger incorrect in VST3 without transport running

### ISSUE THREAD

**Issue by Oberlai** [surge-synthesizer/surge#1491]
Copying chat from Slack (ED), for reference:

Scene LFOs are not per voice, yes? If so, then freerun LFO mode is wrong for SLFO. It always starts from phase defined by Phase parameter just like keytrigger mode.

It shouldn't start from random phase like Random mode does, it should in theory run all the time in the background, then when voice is triggered take the current phase value and go with it.

For voice LFOs, it should be like this: random: each voice gets a random phase - works correctly.

Keytrigger: each voice starts from phase defined by Phase parameter - works correctly.

Freerun: since we cannot run LFOs all the time in the background for voice LFOs, the first voice starting after complete silence should get random phase, any subsequent voices should pick up the current phase from first voice and run with it. This way you would get a sorta-global LFO for all voices when in freerun mode. That's how it's supposed to work.

**Comment by baconpaul** [comment]
As I mentioned on slack, this relates to transport state also

https://github.com/surge-synthesizer/surge/issues/146

so I wonder if that same trick needs to be done in the VST3 and the VST2 also?

**Comment by baconpaul** [comment]
Basically the ‘attack’ for all the modulators is called at the outset of a voice and you can see that keytrigger resets phase; random randomizes it; and freerun sets the phase based on the song position
8:20
This means if you back up your transport and run your synth the freerun will be at the same spot every time, which is what we want! But it means in live performance mode where songpos isn’t set there’s no difference between keytrigger and freerun

**Comment by baconpaul** [comment]
@mkruselj confirms that with transport running the vst3 behaves as expected; so this really is just the transport songpos missing bug from the au

**Comment by VincyZed** [comment]
Ohhh didn't know it was related to transport! That would then close #1002 as well :)

**Comment by baconpaul** [comment]
Fix for this in the VST3 inbound (so freerun will act reasonably if transport is not playing)
