### ISSUE TITLE
Show value units for more parameters

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1495]
Currently pitch-based parameters (Pitch, Formant, Sync, Cutoff modulation depth, and pitch-based parameter modulation depths) which are in semitones, aren't stating that they're in semitones. Which they should :)

Also Uni Count should probably say "voices" as unit.

Modulation amounts should all be in % (except for pitch and Hz based parameters) with two decimals (i.e. moving from -1.000000 ... 1.00000 to -100.00% ... 100.00%).

I'd also suggest that any current %-based parameter should move to showing two decimals for consistency.

**Comment by baconpaul** [comment]
As I commented on slack: need to be careful about which are in semitones and which are in notes; since notes != semitones with non-uniform tunings.

**Comment by baconpaul** [comment]
What I can do is make the display (if (is standard tuning) “st” : “scale notes” )

**Comment by mkruselj** [comment]
> What I can do is make the display (if (is standard tuning) “st” : “scale notes” )

Will be good enough. "st" vs "notes" is a fine (and short and to the point) distinction.

**Comment by baconpaul** [comment]
I’m going to push this out of 1.6.5; the st/note thing is too much engineering and some of the others require re-typing some params which is too much surgery this late in the game. Will keep it open of course just not in this release.

**Comment by mkruselj** [comment]
This is now closed after all the work on Ctrl+drag I did.

**Comment by mkruselj** [comment]
Actually it isn't because modulation amounts still don't use the relevant units based on the parameter they're modulating, sigh...

**Comment by mkruselj** [comment]
Successfully PRing #1991 will close this one too.
