### ISSUE TITLE
Feedback on Slider Bar Feature

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1499]
I just put a slider bar feature in to ship in 1.6.5

Feedback on it from nightly users here please!

![final](https://user-images.githubusercontent.com/13387561/72924439-eb0c8180-3d1e-11ea-95f5-7dc2b35ab2fd.gif)

**Comment by VincyZed** [comment]
Cool! Will test it.

**Comment by VincyZed** [comment]
3 things I noticed so far:
- Green line does not update by themselves when activating Unipolar when in routing mode. They only do after moving the slider.
- Vertical green lines have not been narrowed in the latest fix like the horizontal ones.
- Are envelopes always unipolar? if so, I guess it should be a unipolar green line as well, but I may be mistaken.

**Comment by baconpaul** [comment]
Oh darn it yea I knew about the first one; and the second is just sloppy. Than you.

Envelopes are always unipolar; but you can modulate an envelope parameter with a bipolar modulator. So when using the AEG or FEG modulator it should appear unipolar; but when modulating the AEG attack with an LFO it should appear bipolar.

**Comment by baconpaul** [comment]
Seems we ended up in a good place. Closing this one.
