### ISSUE TITLE
Snap to semitones on pitch modulation amount slider

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1501]
Currently, when tweaking oscillator Pitch parameter and holding Ctrl/Cmd, it snaps to semitones. However, this doesn't happen when tweaking the pitch modulation amount (regardless of modulator used).

It would be nice if it did happen, though!

**Comment by baconpaul** [comment]
So the only problem with this is right now Cltrl-Click when modulating clears the modulation and doesn't allow subsequent editing (try it!) 

It's pretty easy to do this, either by extending the editing or changing the binding. Will noodle.

**Comment by baconpaul** [comment]
So the east thing to do is

start dragging and press control - integerized
press control and start dragging - reset to zero then integerized

but I think the second is probably a "bad idea" since if you accidentally drag it will undo the clear of modulation from control click

`baconpaul/quantized-mod-1501` is how you would do it

Welcome thoughts here.

**Comment by mkruselj** [comment]
Can you make it so that reset to zero happens on mouse up rather than mouse down? Then we can start dragging and holding control, or holding control and start dragging, both would integerize, but if we keep control at mouseup then it resets to zero.

Too complicated?

**Comment by baconpaul** [comment]
Oh that’s a good idea.

**Comment by baconpaul** [comment]
Oh sigh; the short answer is: that's a good idea but it's not easy. Have to change the collaboration between SurgeGUIEditor and CSurgeSlider in a way which is a bit further reaching than I would like. So I'm going to push this one out of 1.6.5. Sorry!

**Comment by mkruselj** [comment]
@baconpaul I'd like to try tackling doing value quantizing on modulation amount sliders, since Ctrl+click doesn't do anything anymore (because we removed that when I did the Ctrl+drag quantizations of regular parameters). Baconsignal ahoy!

**Comment by baconpaul** [comment]
Yeah
this is the same as #1024 right? 
I'll put the stub in place and let you go from there, like i did with mod dipsplay
sometime next few days

**Comment by baconpaul** [comment]
I'm gonna close this as a dup of #1024 at this point.
