### ISSUE TITLE
Noise when certain AMP envelope shape used and sustain=0 and note held

### ISSUE THREAD

**Issue by williamfields** [surge-synthesizer/surge#1509]
**Describe the bug**
If sustain is set to 0, and the decay part of the AMP envelope shape is set in the middle (the default setting), and you trigger a note and hold it down, a low-level noise is generated. See attached for a demonstration.

![noise](https://user-images.githubusercontent.com/9380730/73124201-a2dfa000-3f66-11ea-9553-082fd09ee646.gif)

**Please let us know your surge version**
This information is all in the menu/about screen

* Surge Version: 1.6.2.1
* Plugin type (VST2, 3 or AU): VST2
* Bits (32/64): 32

**To Reproduce**
1. Set sustain to 0.
2. Make sure decay part of AMP envelope shape to the middle. (default setting)
3. Trigger a note and hold it down.

**Expected behavior**
Volume should go to 0. No noise.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Host: REAPER
 - Version: 6.03

**Additional context**

**Comment by baconpaul** [comment]
Thanks. For the upcoming 1.6.5 release I fixed quite a few things in the analog mode, including the sustain target being wrong. I'll give this a try, but it might also be fixed in the nightly already.

**Comment by baconpaul** [comment]
Oh sorry this is the digital envelope not the analog.

Well much easier to debug for sure. Will peek.

**Comment by baconpaul** [comment]
OK I now know *why* this happens but am not quite sure what to do

https://github.com/surge-synthesizer/surge/blob/d4e5017369a023ad54bda285bf2484b671a731b3/src/common/dsp/AdsrEnvelope.h#L275

that code which is the quadratic version of the decay in digital mode has the problem that when phase -> 0 lo = hi as opposed to lo and hi bracketing the sustain. I think the answer is to make the low have a - rate * rate but I am still debugging.

But yeah this is a real bug in the implementation when sustain is zero.

**Comment by baconpaul** [comment]
OK this is fixed. Will be corrected in 1.6.5 coming in the next few weeks; and should be fixed in the nightly on our website in an hour or so. Thanks for the super accurate report. Really helped me find the problem quickly.

**Comment by williamfields** [comment]
Amazing! Thank you!
