### ISSUE TITLE
Tooltips stay on screen after dragging with the mouse.

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1512]
**Description**
Tooltips stay on screen for about 2 seconds when dragging with the mouse. It seems to act as if the scroll wheel was used instead.

**Version**
Latest nightly, VST3 x64

**Steps to replicate**
1. Tweak any slider with the mouse wheel.
2. Before the tooltip disappears, use click and drag that same control.
3. This control's tooltip will now always stay for 2 seconds or so after being moved with click-drag when it shouldn't.

**Expected behavior**
The tooltip should disappear instantly when clicked and dragged.

**Setup**
Windows 10 x64, FL Studio 20.6.1 x64

Edit: This actually affects all parameters, not only Filter cutoff.

**Comment by baconpaul** [comment]
Got it. Yeah I know where this is. Thanks for the report! Fixing this morning.

**Comment by baconpaul** [comment]
Oh wow this is a bit annoyingly difficult to fix.

Basically VSTs assume that you call "begin edit" and "end edit" in an edit gesture

So when do you call "endEdit" for a mouse wheel gesture?

That's the fix I'm putting in.

The choice I'm making is: when you click or when you leave the control.

Will need some testing when I make this change though.

**Comment by VincyZed** [comment]
Awesome! Just tested, it works great. Thanks a lot! :)
