### ISSUE TITLE
Pitch Standard -> Setting A4 to frequencies other than 440

### ISSUE THREAD

**Issue by RCJacH** [surge-synthesizer/surge#1526]
**Is your feature request related to a problem? Please describe.**
Currently Surge has no way to change the pitch standard of notes. We can only achieve similar effect with pitch wheel.

**Describe the solution you'd like**
Add a setting to change the pitch standard, possibly a button beneath "tun" button at top-center of the screen under "Status" column, or even place it in Menu. Then replace the 440 with a variable in the frequency calculation in 440 * 2^((note-69)/12) for each note.

Consider this as a simplified version of #1209.

**Comment by baconpaul** [comment]
So in the current nightly the way I would do this is to use a simple KBM file which remaps the center note. Does that work for you?

I suppose I could add a menu option to add a "retune A to" that fakes up a KBM file for you too!

**Comment by RCJacH** [comment]
Oh sure, as long as it works. Although I don't really know what KBM file is. Is it like the .scl file?

**Comment by baconpaul** [comment]
Yeah if you are running the nightly in the tuning menu is an option like “tuning library” which has a bunch of kbm files that show you how to remap a keyboard. Basically an scl file is a scam and a kbm file is how that scale maps to midi notes (so contains things like the scale starts on this key, this key is the frequency reference at 440, etc)

**Comment by baconpaul** [comment]
But depending on how hard it is I might still add a tuning function called “tune a4 (midi #69) to...” tomorrow which will mean you don’t have to figure it out!

**Comment by baconpaul** [comment]
Hi!

Tonight's nightly will have this in the "tun" menu. There's a bug with toggling tuning on and off which I will fix tomorrow but you can retune A to any frequency you want with the feature. To restore to normal, though (just for now), retune A to 440, don't click "tun" and turn off tuning (which is the #1533 bug I need to fix).
