### ISSUE TITLE
LFO Beat-syncing is unpredictable in Latch mode

### ISSUE THREAD

**Issue by mortfell** [surge-synthesizer/surge#1532]
When using Surge as an audio effect in Latch mode we get some unpredictable behavior from beat synced LFO's. 

**Describe the solution you'd like**
How the latch is connected to the tempo of the DAW seems to be connected to the moment you actually "enable" latch mode. 

it's really finicky to get things locked to the tempo correctly. You'll have the correct tempo, but the phase of the LFO will be slightly off, and if you re-enable latch mode it the phase will be somewhere else.

**Describe alternatives you've considered**
If there is a way to force latch mode to lock to the actual bar position that would fix this issue.

**Comment by baconpaul** [comment]
If you switch the lfo to free run does it work properly?

**Comment by mortfell** [comment]
oh yes....
duh
thanks Paul!

**Comment by baconpaul** [comment]
Cool!
