### ISSUE TITLE
Improve automation param naming of FX units

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1540]
Currently (in 1.6.5 release) FX are just named 1-8 in the automation parameter list. It would make more sense to comply (or adapt) to nomenclature that Surge's GUI uses, which is:

A Insert 1
A Insert 2
B Insert 1
B Insert 2
Send FX 1
Send FX 2
Master 1
Master 2

This text shows here:

![image](https://user-images.githubusercontent.com/2393720/73555987-db8fe580-444e-11ea-865f-ade5d3eef145.png)

Even this is slightly inconsistent (only Send FX has "FX" in its name, haha), but here's how I would propose condensing the automation parameter names (and then update this text within Surge as well):

IFX A1 Param 1...x
IFX A2 Param 1...x
IFX B1 Param 1...x
IFX B2 Param 1...x
SFX 1 Param 1...x
SFX 2 Param 1...x
MFX 1 Param 1...x
MFX 2 Param 1...x

Note that this numbering is 1-based, currently it's 0-based for 1.6.5.

And then I would also suggest tweaking that text within Surge so that it's consistent:

A Insert FX 1
A Insert FX 2
B Insert FX 1
B Insert FX 2
Send FX 1
Send FX 2
Master FX 1
Master FX 2

**Comment by baconpaul** [comment]
https://forum.juce.com/t/vst3-parameter-name-changes-dont-work/28313/2

Just dropping that convo there. Vst3 and au have parameter name invalidation available and so we could avail ourselves of them perhaps and even make the name “afx 1 p1 delay time” or what not

**Comment by baconpaul** [comment]
Good idea. I chose a slightly different name for the DAW params ("FX A1", "FX A2" "FX S1" etc... ) to keep the list looking close to the current one. Changed the menu. Am pushing now.

Making the VST3 param name update work will make this powerful too. Will see how that works out.

Oh also no longer label params starting at 0 rather use 1.
