### ISSUE TITLE
Tuning appears to change global highpass settings

### ISSUE THREAD

**Issue by bit-101010** [surge-synthesizer/surge#1545]
Loading a .scl file appears to affect the global highpass filter. This is particularly noticeable with low notes on large scales.
Apparently, this involves the calc_omega function in the code.

Here's the scale I was working with- I changed the extension to .txt for Github upload but it's a .scl file.
[31edo.txt](https://github.com/surge-synthesizer/surge/files/4143464/31edo.txt)

Thank you for making this the best FOSS retunable synth out there!

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/blob/b4db5c24b606deb1a4e011c5085585bd20289389/src/common/dsp/BiquadFilter.h#L197

**Comment by baconpaul** [comment]
looking i bet it changes the effects also like the cutoff in delay and the bands in distortion, again incorrectly

**Comment by baconpaul** [comment]
Ha this is a somewhat bigger problem. Tuning also hits up things like delay time. I have a new API point and a basic test. Fix inbound later today.
