### ISSUE TITLE
Windows HiDPI support 

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1547]
Right now windows in display info always return a backing store density of 1. This means we render to a 96dpi pixel in cscalabalebitmap and some zooms are blurry

We could alternately support the hdpi api and set that scale factor then test in all the hosts and display configurations but I don’t know those apis don’t have those displays and don’t run those hosts! So adding a placeholder issue

**Comment by Kingston1** [comment]
One solution that I have done elsewhere in an unrelated project is initially scale and store all vector based bitmaps to relatively large internal size, thus ignoring the initial dpi issue entirely. Then always scale down. This works well but with slight increase in memory footprint.

**Comment by baconpaul** [comment]
Yeah in 17 we did exactly that with this implementation

https://github.com/surge-synthesizer/surge/blob/8369a6fbe6c7ba7969ee1b70c47b826ffaf7862d/src/windows/DisplayInfoWin.cpp#L34

**Comment by baconpaul** [comment]
So I think the correct implementation here would 

1: go frame -> hwnd
2: go hwnd -> resolution
3: scale resolution by 100 and return it

rather than simply "return 2"

I think a super-complete implementation would also hop into vstgui.surge/vstgui/lib/platform/windows and modify win32frame so that the WM_DPICHANGED message invalidated you but that's probably more trouble than its worth. So for now I think just a readonly access. Take a look at src/windows/DisplayInfoMac.cpp for an example!

**Comment by mkruselj** [comment]
JUCE, our savior, deliver us from the pain that is VSTGUI!

**Comment by baconpaul** [comment]
Yeah you should just try xt. The SVGs render perfectly in mac retina with none of my code for vstgui being used

**Comment by mkruselj** [comment]
Oh so it's using 1.0 backing store on non-HiDPI in XT now? I don't see anything changed there in `DisplayInfoWin`, but I bet it's a matter of finding the right JUCE API and hooking it up there.

**Comment by baconpaul** [comment]
The juce code path never calls backing store resolution

**Comment by mkruselj** [comment]
Oh!

**Comment by mkruselj** [comment]
So wait, is this one basically implemented and could be closed simply by virtue of having XT building fine across all platforms (even if it's not completed yet)?

**Comment by baconpaul** [comment]
Well does XT do the right thing on Windows HDPI?
It does on mac!

**Comment by mkruselj** [comment]
It seems to be using backing store 1.0 over here on non-HiDPI, but I suppose I should check on my Surface and report back 🙂

**Comment by mkruselj** [comment]
The answer is: yes, yes it does! So closing it ahead of schedule. 😁
