### ISSUE TITLE
Unison and sample rate in Absolute modes

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1548]
From KVR:

> I think Surge still has a bug regarding samplerate: The unison spread is dependent on the samplerate, but should not be. For example, try the "polysynth->megamega" patch. First listen in 48kHz, now switch to 96kHz. The unison spread sounds the stronger the high the samplerate is. So I guess the calculated pitch detune formula actually is samplerate dependent here, but this makes no sense.

**Comment by JurekR** [comment]
Thanks for filing. Also I am not too sure why the middle / neutral detune position is not 0 on the unison spead... Is this intended?
[0.2f seems to be the initial value](https://github.com/surge-synthesizer/surge/blob/master/src/common/dsp/SurgeSuperOscillator.cpp#L315), so seems to be alright then...? 

I think currently the unison spread is not adjusted to samplerate at all, at least a

`l_detune.newValue(limit_range(localcopy[id_detune].f, 0.f, 1.f));`

 is missing [here](https://github.com/surge-synthesizer/surge/blob/master/src/common/dsp/SurgeSuperOscillator.cpp#532). The other parameters are set to samplerate [here](https://github.com/surge-synthesizer/surge/blob/master/src/common/dsp/SurgeSuperOscillator.cpp#238). It is [not yet defined](https://github.com/surge-synthesizer/surge/blob/master/src/common/dsp/Oscillator.h#L211). But I guess you know that already :) Not sure what setRate actually does [https://github.com/surge-synthesizer/surge/blob/master/src/common/dsp/DspUtilities.h#125](here).

**Comment by baconpaul** [comment]
That code is setting the phase difference of the unison voices not the pitch difference, but it definitely needs to be tuning centered to deal with scl adjustments. 

The mega mega is a big patch - do you happen to see this effect in a smaller patch? I tried surge in logic with a simple count 2 width 100 and the tuning seemed sample rate invariant 

Thanks for helping us find this!!

**Comment by JurekR** [comment]
Try this patch: https://ufile.io/mdcg1exf
If I switch the samplerate 48/96kHz I can clearly hear that the detuning is much stronger at 96kHz. 11Hz @ 96kHz is almost like 16Hz @ 48kHz.

**Comment by baconpaul** [comment]
Oh yeah that is clear as day. Thank you.

We will definitely fix this in 1.6.6.

**Comment by baconpaul** [comment]
[srdep.zip](https://github.com/surge-synthesizer/surge/files/4156375/srdep.zip)

Here's a zip of that patch in case the link above expires.

**Comment by baconpaul** [comment]
Walking the blame is interesting

```
// double t = max(0.5,dsamplerate_os * (1/8.175798915) * note_to_pitch_inv(pitch + detune) *
221
      // 2);
222
      float t = note_to_pitch_inv(detune) * 2;
```

this is the code which was checked in the day it was open sourced. The change (to make that detune tuning centered properly) kept the behavior constant over the scl implementation but looking at it now I am wondering why those time shifts aren't samplerate dependent.

I think you're right the problem is near there; I think you might also be right that the problem has existed in all the 1.6 vintages.

This code is too hairy and I'm tired from doing the release today and stuff, but I'll make this top priority 1.6.5; and perhaps I'll do a 1.6.6 with this fixed and move 1.6.6 to 1.6.7 if I can find it in the next couple of weeks.

Thanks again!

**Comment by JurekR** [comment]
Nice to read, thanks for your efforts! I might checkout this project and try myself a bit, but still need to get friend with xcode.

**Comment by baconpaul** [comment]
Happy to help. If you get stuck you can hop on our slack and there's usually someone there who can help with build problems. I develop on mac so the toolchain is pretty well setup at this point once you get it working.

**Comment by JurekR** [comment]
Neat.

Oh here, this preset does not seem to be affected, still investigating why that is:
https://ufile.io/p2e0l5do

**Comment by baconpaul** [comment]
Oh do you have .scl in the mega mega patch?
There's a chance that SCL and timing are off. I fixed a bunch of those bugs in 1.6.5. 
Will take a look this week!

**Comment by JurekR** [comment]
No, I did not use/add any SCL. It is an old patch, so then this is not the cause? It was just spontanous idea about the cause, which seems to be wrong. I then have no idea, why the first preset doesn't work properly, but the second does. Could not find the missing link here. Can you?

**Comment by baconpaul** [comment]
I changed a lot for scl but it is all constant if you are Untuned. I think this one will just need digging to be honest! Happy to do that though

**Comment by Jurek-Raben** [comment]
This is a strange one. Again compared those two presets, and still have no idea where a difference is, why one is working properly and the other not. I also laoded SCL files and switched back to standard tuning, no change in the buggy behaviour...

**Comment by baconpaul** [comment]
Wonderful thank you.

I am in the middle of a different side project for the rest of the week but this is my next surge issue to turn to. Our regrets engine should let me make short order of it once I have the patches set up

**Comment by Jurek-Raben** [comment]
Maybe the patch "megamega" should be considered as faulty. Since I actually wasn't able to find any other patch so far, which shows the same problem with detuning. So the reason might be inside the patch. Maybe there is a orphaned parameter in the vstchunk of the preset, which still is affecting the synthesis, but is not changable in the gui at all anymore?

Were there such changes in the revisions of Surge?

**Comment by baconpaul** [comment]
Oh that is excellent bug hunting. And also explains why my tests in non-absolute mode didn’t find it! And yes it is absolutely that line - pitchmult_inv has a samplerate dependency. Great debugging! There’s probably a similar line in the wavetable oscillator too, by the way, and there’s a few other places with absolute frequency shifts.

It also means this is a smaller problem than we feared. Absolute mode is not all that widely used. Let me change the title. 

Now we just need to figure out what the sample rate independent version of that line is that is invariant in sound at (say) 48k.

**Comment by Jurek-Raben** [comment]
Ok, the above line simply needs to be the same as the line for not-absolute-mode.
`t = storage->note_to_pitch_inv_tuningctr(detune  + sync);`

Just tested, seems to be working then!

Btw. the slack invitation link seems to be outdated.

**Comment by baconpaul** [comment]
Yeah that will just ignore the absolute nature. Basically what absolute means is "convert the detune from pitch space (basically "detune is in log(frequency)") to frequency space (basically detune is in frequency). So think of setting it to "10hz" vs "10 cents"

Lemme look at the slack invite

**Comment by baconpaul** [comment]
https://join.slack.com/t/surgesynth/shared_invite/enQtNTE4OTg0MTU2NDY5LWZkMjllNDAzZjYzNTc4NjUzNjk2OGUxNDYzZTYyZTU3ZGU4OTY4MzhkNzcwZGE5ZDQyMzk5MjE1ODEzZTFmODI

that link shows as expired for you? Slack is telling me it won't expire. But I could regenerate it I think.

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/blob/b489fc16a62890fe1b67887bcc1875432078f3bd/src/headless/UnitTestsDSP.cpp#L60

there's the unit test for unison hz (which passes; but which doesn't test multiple sample rates)

**Comment by baconpaul** [comment]
Some more commentary here.

The unison absolute spread displays as "16 * spread.val.f" in absolute mode, but in my modified unit test, where I am looking, it is not that.

So it seems if you set the absolute unison spread to 15.0 HZ you get a unison spread which is actually "1.44745 * 15 * 44100 / samplerate"

Both sample rate dependent and off by a factor of 1.447 or so.

So step 1 is find the sample rate dependency in each of the oscillators and step 2 is find the 1.44745.

branch with the unit test is baconpaul/unison-absolute-sr-1548 and right now it prints rather than asserts so the whole test can run. Test case is "Unison at Sample Rates"
