### ISSUE TITLE
Showing parameter already on initial mouse down

### ISSUE THREAD

**Issue by Jurek-Raben** [surge-synthesizer/surge#1549]
**Is your feature request related to a problem? Please describe.**
If you hold LMB down a parameter, it will show the parameter value AFTER you start to move the handle.

**Describe the solution you'd like**
It should already show the value on mousedown, BEFORE moving.

**Describe alternatives you've considered**
Ultimative would be the additional usage of the big display above (patch browser), for displaying the value, as soon as you mouse-over a parameter. Just like Zebra. This would be much more convenient.

**Comment by baconpaul** [comment]
I think this is the same as #377 and, annoyingly, it is annoying to implement in vstgui

You can right mouse on any control and see the value, although I know that's not what you are asking for.

**Comment by JurekR** [comment]
Oh damn, VSTGUI again 🤡 Well, that idea of the huge display might be very helpful, too. What do you think about it? Zebra deluxe...

**Comment by baconpaul** [comment]
Ha - we are at a bit of a crossroads as to what to do with the ui. I’m still in a thinking mode. I have a pre alpha version of surge running with a skinning engine that might help but I’m not quite sure yet the path to release it... 

I also kinda dislike the non locality a lot of synth uis have (mouse here show there type things). But we have lots of room on the screen to show stuff up top so worth considering....

**Comment by Jurek-Raben** [comment]
Hi,

if you add a 
`if (listener)` 
`    listener->valueChanged(this);` 
[here](https://github.com/surge-synthesizer/surge/blob/master/src/common/gui/CSurgeSlider.cpp#L565), straight before the return, it seems to display the value then already on initial mousedown. Not sure if everything then still is correct though...

**Comment by baconpaul** [comment]
Yeah that might work indeed! 

We would want to bounceValue also when we do (take a look in onMouseMoveDelta) and also test it with the various other flavors (like shift and control drag). But sending a value change when we start a mouse action as opposed to when we micro drag should be OK, as long as it is after beginEdit

If we do this we should test the automation paths also of course.

Happy for you to try that and put a PR together and we can have folks test the nightly. I'm going to wait one or two more days of 1.6.5 being out there before I merge stuff but I think you are right that this would be safe

Thanks so much for looking at this!

**Comment by baconpaul** [comment]
if you add the bounceValue your diff as proposed works in every case I tested. So let me sweep that in this afternoon. Thanks!

**Comment by VincyZed** [comment]
Good stuff! Right now though, it also shows it when double-clicking to reset a slider value, which is probably not the correct behavior.

**Comment by baconpaul** [comment]
Oh sigh I get called twice, once for click a second time for double click. Harumph. Need to think about this one. I may just put a request-to-show into the idle queue but that is bigger surgery.

**Comment by Jurek-Raben** [comment]
Why it is a problem, if it is shown while a reset?

**Comment by VincyZed** [comment]
Well I think it's not a major problem. Just an annoyance.

**Comment by baconpaul** [comment]
And it would have to show both values if it stayed open and so on. Plus to do that we are in the idle loop anyway so might as well do the more correct thing. Not impossible but needs doing.

**Comment by Jurek-Raben** [comment]
Hm, maybe my idea about timeout is quite a nonsense. Might actually disturb a quick workflow using the mouse.

**Comment by baconpaul** [comment]
The timeout is what we do on mousewheel actually. So it is definitely not nonsense! Just a timeout to go away is the same code as a timeout to not appear in the first place, roughly, and I think the write answer in this case is the later.

**Comment by Jurek-Raben** [comment]
Yeah, but while very quick mouse actions, it might block other sliders in workflow...

**Comment by baconpaul** [comment]
Yeah I agree - we don’t want it to popup and stay when you double click. 

My point was you have four options

0: popup on mouse down (what code did earlier)
1: popup and dismiss immdiedately (what code does now)
2; popup and hang around with a timeout (your idea which you now call “nonsense”)
3: delay popup for 20ms on mouse down anticipating a mouse click (roughly the same code as above but not the same UI). I’m proposing we do this one.

**Comment by Jurek-Raben** [comment]
4: popup and disappear immediately on mousedown, and for a second click within a timeout interval, prevent a popup?

**Comment by baconpaul** [comment]
your “#4” is exactly what happens today. And it looks sloppy and bad when you double click.

**Comment by baconpaul** [comment]
I mean: I wrote the code that looks sloppy and bad. I’m not blaming you! Just we need a better solution that your number 4 which is exactly the number 1.

**Comment by Jurek-Raben** [comment]
but... it does not prevent the popop on the second click currently, or does it?

**Comment by VincyZed** [comment]
Yeah no it doesn't
