### ISSUE TITLE
Incorrect mouse behaviour with "Slow" setting

### ISSUE THREAD

**Issue by MD-78** [surge-synthesizer/surge#1550]
Surge Version: 1.6.5
Plugin type (VST2, 3 or AU): VST2
Bits (32/64): 64

1. set the mouse behaviour to "Slow"
2. drag Cutoff slider fully to the left (don't release the mouse button)
3. drag mouse even more to the left (say 200 pixels)
4. drag mouse to the right

Current behaviour: Cutoff slider doesn't move to the right immediately when dragging the mouse to the right. The 200 pixels in step 3 first have to be "compensated" - after that the slider will move.

Expected behavior: Cutoff slider immediately begins to move to the right when dragging the mouse to the right.

Note: This problem doesn't occur with the "Classic" mouse behaviour.

 - OS: Windows 8.1 Pro
 - Host: REAPER 6.03/x64

**Comment by baconpaul** [comment]
Thanks. Great report. We'll look for 1.6.6

**Comment by baconpaul** [comment]
The reason for this is because Medium and Slow are multiples of exact; and exact only moves when you are exactly over the slider.

I'm not saying this is correct, but that's the core difference in the implementation, whereas classic is differently set up.

The problem is in the bounceValue for classic. I think that should be boucneValue for not exact instead.

**Comment by baconpaul** [comment]
Yeah that's exactly it. Commit coming in.

**Comment by MD-78** [comment]
Fixed in 1.6.6 for "Slow" and "Medium".


But "Exact" mode still has the issue!

**Comment by baconpaul** [comment]
I purposefully left the issue in place in exact mode. Exact mode is designed to have the cursor under your mouse exactly so the desired behavior is indeed to ignore the overdrags

You may disagree and I may be wrong, but it wasn't an oversight! Happy to hear the other side.

**Comment by MD-78** [comment]
Ok.

What's the difference of "Slow" compared to "Classic"?

**Comment by baconpaul** [comment]
Slow is uniformly slow 
Classic has different speeds per slider
None of us are quite sure why but it is what classic surge did

**Comment by MD-78** [comment]
Ok, thanks!
