### ISSUE TITLE
Report of matching Virus Signature at virustotal.com with Surge-1.6.5-Setup.exe

### ISSUE THREAD

**Issue by josemic** [surge-synthesizer/surge#1551]
**Describe the bug**
I installed surge version Surge-1.6.5-Setup.exe from download page. 
I could not started it. Maybe it is only a plugin, not a standalone synthesizer.

Thus I ran it through virus total (virustotal.com). It complained of the following malware:
 Bkav reported W32.AIDetectVM.malware

Virus total fingerprint: 

3e60d9eecc26b4aba86f39a7d6359fcb114b4749fee01fddfc969bedf87513dc
Surge-1.6.5-Setup-x86.exe

Same for 

853bdc270660b489981461618dbdc48ec76e30ee87bd3d3d6cdabfae5ebf3f06
Surge-1.6.5-Setup.exe
 Bkav reported W32.AIDetectVM.malware

And for:

4f11d09f563f3c116f153db40020e2cdf6b4000c9ea8d1355f5cef42649d2211
Surge-NIGHTLY-2020-02-02-b489fc1-Setup.exe

Bkav reported W32.AIDetectVM.malware
an 
Qihoo-360 reported HEUR/QVM05.1.0A29.Malware.Gen

**Please let us know your surge version**
1.6.5 from download
* Surge Version: 
* Bits (32/64)
32 and 64 Bit

**To Reproduce**
1. Go to virustotal.com
2. Click on Choose file from download and scan

**Expected behavior**
No virus found.

**Desktop (please complete the following information):**
 - OS: windows 10

Hopefully it is not my PC causing this trouble.

**Comment by baconpaul** [comment]
Hi!

it is only a plugin and it doesn’t contain a virus; but I’m not sure what virus total is doing to detect a virus inside it. I’ll ask some of our other windows users to take a peek.

**Comment by mkruselj** [comment]
It's a false positive, VirusTotal's heuristics gone wild. Report to them that it's a legitimate binary and that they should whitelist it.

**Comment by baconpaul** [comment]
OK I’m going to close this issue then, especially since Windows Defender scans us clean. If OP would like to follow up with VirusTotal would be happy for them to do so.
