### ISSUE TITLE
Unison spread range

### ISSUE THREAD

**Issue by fiftysevendegreesofrad** [surge-synthesizer/surge#1552]
Hi this is a great synth!

I wonder if you'd consider increasing the range available on the "uni spread" parameter? The unison spread sounds great (which is not something you can say of many synths) but if you compare to e.g. Sylenth, greater amounts of spread are possible and desirable for those who like to stray further into inharmonic territory.

**Comment by baconpaul** [comment]
Thanks!

And that's a great idea. Some other controls (like pitch and the distortion FX) have an 'extended' mode where you RMB and choose 'extend range'. No reason we couldn't add that to uni spread also.

Let me tag this for 1.6.6

**Comment by mkruselj** [comment]
Very good suggestion!

**Comment by baconpaul** [comment]
Oh so right now Uni spread is up to 100 cents (in normal mode) or 16 hz (in absolute)
In an extended mode I'm thinking go to 1200 cents so multiply the range by 12; and then similarly that would take you to 192 Hz (16 * 12) in absolute mode.

We do have to make a choice. Absolute mode is just a multiple. We could, I suppose, choose a different absolute from normal mode multiple.

Barring any other feedback I'm going to choose 12 but will make it a constant in case there's disagreement.

**Comment by baconpaul** [comment]
Ha for a super cool reason, 12 is obviously the right answer

Take an oscillator, set uni count to 3, set unison to extended, and set it all the way up, and you get all three octaves sounding at once using only one oscillator. It's really pretty awesome.

Anyway have it all working, so will push extended with a factor of 12 now. Thanks for the suggestion!

**Comment by baconpaul** [comment]
OK this should be in the nightly on the website in about 20 minutes. Enjoy!

**Comment by fiftysevendegreesofrad** [comment]
Sweet! I look forward to trying it out :D
