### ISSUE TITLE
Notes "stuck" when using sustain pedal (MIDI CH 3 & 4)  Other midi channels have problem as well...

### ISSUE THREAD

**Issue by Sprolkyman** [surge-synthesizer/surge#1554]
Playing notes on external Keyboard on MIDI CH 3 & 4 (Maybe higher as well), and using sustain pedal, wont let go of the notes played. They will sound until the same notes are played again. 
Cycling Sustain pedal does not help!
Using MIDI CH 1 or 2 does not cause this problem.

**Please let us know your surge version**
This information is all in the menu/about screen

* Surge Version: (1.6.5 - 2020-02-04 )
* Plugin type (AU)
* Bits (64)

**To Reproduce**
1. Using any patch that can sustain (I Think)
2. Use Midi Channel 3 or 4 from controller to play note while holding down sustain pedal. 
3. Note Continues to play even if you let go of both pedal & Note
4. To Stop Note(s) sounding, press on the same notes that are sounding, and they will stop as they should.
5. No such problem when using MIDI Channel 1 or 2 !
I have not tried higher Channels than #4. ! (Due to my controller)

**Expected behavior**
Notes played should stop when letting go of key

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MAC OSX Catalina & High SIerra
 - Host LOGIC PRO X 
 - Version 10.4.8 (Latest)

**Additional context**

**Comment by baconpaul** [comment]
Are you in MPE mode?

But this might indeed be a legit bug; channels 3 and 4 are treated specially in surge to route between scenes if you are not in MPE mode. Sustain pedal should work of course but.

**Comment by Sprolkyman** [comment]
Not in MPE Mode!
I Enabled the MPE mode just now as you mentioned that mode; No different behavior ! 
Also, does not matter what notes / octaves are played.
/David.

**Comment by baconpaul** [comment]
OK thanks. I'll take a look.
The sustain pedal is a bit tricky.
Oh one question: Does your keyboard send the sustain pedal on channel 3/4 with your midi, or does it send it on channel 1?
Or alternately could you attach a logic file zipped up which shows the break with your setup?
but if not I'm sure I can replicate.
Appreciate the report.

**Comment by Sprolkyman** [comment]
In the control display in LPX, it says CH# (ex 4). 64 . 127, No matter what channel i play on!
Thanks! :)

**Comment by Sprolkyman** [comment]
So, if i play on Channel 4 it says Channel4, If playing on 2 it says 2!   
I saw my wording was unclear maybe.. :)

**Comment by baconpaul** [comment]
Cool thanks. Got it.

wonder what that purgeHoldBuffer around like 948 of SurgeSynthesizer.cpp is doing ... looks suspicious to me.

**Comment by baconpaul** [comment]
Oh yeah that's exactly where the bug is. Wow. That code is just weirdly wrong. I will need to think about and test it but thanks, should be able to fix it soon enough.

**Comment by Sprolkyman** [comment]
Sorry.. Thats ”Greek” to me! :)  I don’t know programming..  But I really admire all your work you guys put down on this amazing instrument!

**Comment by baconpaul** [comment]
Oh the "greek" means "jeez yeah you are exactly right, what's this weird bit of code sitting here that's been there forever even trying to do - that will kill sustain pedal releases on channel 3 and 4! Ahh well at least I know what to fix now"

Stay tuned to this issue, When I fix it there will be an update here and you can download a nightly with the fix.

**Comment by Sprolkyman** [comment]
Thanks Paul!  No Hurry for me & Good job! :)  /Thanks again.

**Comment by Sprolkyman** [comment]
ADDITIONAL SUSTAIN PROBLEM..!

All midi Channels!

I am playing around with Surge, checking out patches, and i get strange behavior  on other MIDI Channels as well:  This is an intermittent problem, but easy to replicate if you just keep on trying a couple of times.

1. Hold down sustain pedal and then play the notes / chords, Shifting the sustain on and off as one does when playing. All of a sudden, : Holding down the played notes the sound stops if you go from an activated sustain (Pedal Down) to a release of the sustain.  That is, still holding down the notes!!.

Expected is that if i one holds the notes down, they should hold their own sustain, so to say.. even if i let go of sustain.

 Its like the notes that are pressed at this moment lost the key down signal, and what’s heard is the sound created when the pedal was pressed and the notes played. But when sustain is released it goes silent! 

And its erratic!  I Have checked other instruments, and they behave as they should!

**Comment by baconpaul** [comment]
Yeah OK sustain is tricky beleive it or not, and we found and fixed some bugs in the MPE implementation with this release but didn’t do a full test.

For 1.6.6 I will add a comprehensive set of tests and get it working properly.

Appreciate your patience! Sorry for the bugs. The code is peculiarly hairy and I don;’t think it needs to be so I will probably just rejigger the whole sustain handling code.

**Comment by baconpaul** [comment]
Ahh OK here's the trick for the erratic state

Press and hold a key
Press the sustain pedal
Release the key and press and hold it again <-- At this point the voice is playing twice
Release the sustain pedal <-- At this point both the voices get killed

The reason is that press-while-sustained does't register as needing sustain to be held

if you press and hold a key without repeating it the sustain pedal works as it should.

Real bug. Looking.

**Comment by baconpaul** [comment]
OK I have a fix to both of these problems coming in. Stay tuned.

**Comment by baconpaul** [comment]
OK @Sprolkyman this should now be fixed in the nightly at surge-synthesizer.github.io. We plan on doing a 1.6.6 release pretty soon for a couple of reasons so if you had a chance to test and confirm it would be appreciated.

**Comment by Sprolkyman** [comment]
As a Charm!! ! :)  Thats how it works now! :)
You are the best Paul!
All you guys working hard to make this great synth even better every update are terrific!

Thanks! Love to ya all:)
David.

**Comment by baconpaul** [comment]
Super! Thanks!
