### ISSUE TITLE
Modulation “Peak Pin” mode

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1555]
Right now if you set a slider to 0.5 and modulate it 0.3 it does 0.5 +/- 0.3 or p2p of 0.2/0.8 with a bipolar modulator. If you then move the center to 0.6 it does 0.6 +/- 0.3 or p2p of 0.3/0.9

It would be interesting to add a ‘peak pin’ mode (or really mod pin mode). So if you have at 0.5 then modulate it 0.3 then ‘pin’ the modulation thought some UI gesture TBD, then it is 0.5 +/- 0.3 so p2p of 0.2/0.8 still, but if you then slide the center to 0.6 it becomes 0.6 +/- 0.2, or p2p of 0.4/0.8.

Similarly modulation by -0.3 from 0.5 (so p2p of 0.2/0.8 with 180 deg phase shift basically) and then sliding to 0.6 would make you 0.6 with mod of -0.4 or p2p of 0.2/1.0

Not entirely sure what the UI gesture is but something like “RMB on the blue handle, toggle peak pin mode, and then change the handle display” is the rough idea we had

**Comment by baconpaul** [comment]
Oh internally this could be a pretty gnarly change. Two possible ways

1. store the pair of ‘root and depth’ rather than just ‘dept’ in the modulation data structure
2. Have the widget send modulation depth changes as value changes on center changes in pin mode

Both have pluses and minuses. I think #2 is the way to go (then this really becomes a UI-only feature not an engine feature) but if/when we code this up we can decide

**Comment by mkruselj** [comment]
@baconpaul I think this FR is just bound to confuse pretty much everyone, we're probably better off axing it completely and not implementing it at all.

**Comment by baconpaul** [comment]
Concur.
