### ISSUE TITLE
Surge GUI gets scrambled when 2nd Instance of Surge is added to a Track

### ISSUE THREAD

**Issue by maxxatgit** [surge-synthesizer/surge#1557]
**Describe the bug**
When a 2nd plugin instance is added, the GUI of both instances becomes scrambled and unreadable. Closing the plugin list and re-opening it will *sometimes* display a clean Surge GUI, but usually crashes the VST2 host (Reaper).

**Please let us know your surge version**
Version 1.6.5 64 bit Linux vst2 Built Feb 4 2020

**To Reproduce**
In Reaper:
1) Open the FX (plugin list) window for a track
2) Click "Add"
3) Select Surge and click OK. Surge instance is added to the track's VST list, and the Surge GUI is normal
4) Repeat 2 & 3 above to add another Surge instance to the track
5) Both GUIs are now scrambled
6) Closing and then re-opening the FX window usually (but not always) causes Reaper to crash 

**Expected behavior**
At #5 above, the Surge GUI should be fully functional if I select either instance.

Closing and re-opening the FX window should not cause a crash

**Screenshots**
See screenshot of scrambled GUI

**Desktop:**
 - OS: Linux Ubuntu 18.04 with KDE desktop
 - Host Reaper native Linux
 - Version 6.03

**Additional context**
I ran Reaper from the command line to try to get some information when it crashes. This is what came up on the command line when Reaper crashed:

reaper: ../../../../src/cairo-xcb-screen.c:219: _get_screen_index: Assertion `!"reached"' failed.
Aborted (core dumped)

This is an edge case. I do this (add multiple instances of VSTs to a single track) to collect similar sounding presets on a single track, and save it as a track template. There are several Surge presets that I would like to save together like this. It works fine for other VSTs; Renoise Redux, OxeFM, Zebra2, etc. Probably not a high priority bug in itself, but it does indicate that there is something  going on in the GUI code.

Thank you for supporting this fine synth plugin!
![Screenshot_20200206_152556](https://user-images.githubusercontent.com/1574547/73977497-7b8aba80-48f8-11ea-9332-c05dc26a4005.png)

**Comment by baconpaul** [comment]
Wow thank you for the clear report and the kind words about the synth

If you open on two separate tracks in reaper no problem right?

That Cairo bug means something which has scrambled the world blows up vstgui. Wonder if the same scenario on Mac and win reaper die.
Oh also what process isolation mode are you using in reaper?

Also the Linux vst3 works well in reaper last I checked. If you have a moment curious if it does the same?

Thanks!

**Comment by baconpaul** [comment]
@mkruselj reports this is fine on win vst2 and 3 so linux issue it seems - will try Mac vst3 later on

**Comment by baconpaul** [comment]
Mac also fine so this is linux only it seems. I bet it is that tricky reparenting reaper does blowing up vstgui

**Comment by maxxatgit** [comment]
Wow, you people are fast!
- Two instances on two different tracks, no problem
- Isolation mode: default (I looked in preferences, and really didn't see any vst isolation parameters...
- VST3 version works fine! I had to tell Reaper to scan the /usr/lib/vst3 folder.

Thanks again!

**Comment by baconpaul** [comment]
OK cool thank you! Probably relatively low priority then especially since you have a workaround. For a variety of reasons we really want to move people to VST3 where possible (linux VST3 generally hard but linux VST3 reaper is not).

**Comment by maxxatgit** [comment]
I'm just really grateful. Surge is a powerful synth. Being able to choose a larger GUI (125%) makes editing accessible. The folks at Vember did a wonderful thing open-sourcing Surge.

Digging around to get good info to report here led me to getting Surge vst3 working... what a joy!

Have a great day!

**Comment by baconpaul** [comment]
They really did do something great by open sourcing surge, yes. I'm grateful for that regularly and wish more folks would do it. Thanks for your kind words, and have a great day too!
