### ISSUE TITLE
(voice) envs in the lfo section of surge are not working correctly.

### ISSUE THREAD

**Issue by bigtonesounddesign** [surge-synthesizer/surge#1560]
**Describe the bug**
when routing one of the lfos of surge to the wavetable morph slider, the env mode has an annoying glitch (a fast ramping) when set to fastest attack - in other words, the attack isn't instant. it's practically unusable for percussive sounds like basses.

**Please let us know your surge version**
Surge Version: 1.6.5
Plugin type (VST2, 3 or AU): both, vst 2&3, same behavior
Bits (32/64): x64

**To Reproduce**
select the "initialize to saw" preset. set osc1 to wavetable mode, route voice lfo1 to the wavetable morph slider of osc1 and set the depth to max. then set lfo1 to env mode and enable retrigger (max magnitude, max deform to the right). set delay and attack to min, decay to a mid ranged position (around 300/400 ms). play a note you'll hear a glitch at every beginning of the note (a ramping up - effectively a very fast run through the complete wavetable). very annoying.

**Expected behavior**
no glitch/ramp/fast run through the wavetable. when attack and delay are set to min, the envs attack should basically be absolutely instant, effectively playing the wavetable from the position the env depth is set to on the morph slider.

kind regards,
nico

**Comment by baconpaul** [comment]
Thanks. We can definitely look!

**Comment by baconpaul** [comment]
Clearly the intent is to do what you say

https://github.com/surge-synthesizer/surge/blob/b229283a8ede1612607ef0d44b6e621ee2d9c2bd/src/common/dsp/LfoModulationSource.cpp#L123

but seems still something is off. Definitely a bug and def something to look at for 1.6.6 (and attack with a clean unit test)

Thanks for the clear report.

**Comment by baconpaul** [comment]
(note to self: there is also a chance the LFO does the "right" thing and then we lipol it at the outset of modulation setup so we get the super rapid sweep; make sure initial modulations are hard set not change set).

**Comment by bigtonesounddesign** [comment]
[snip]
> Thanks for the clear report.

no problem. i like surge, so i'd love to use it to full extent - hence i thought i'd post it.

**Comment by bigtonesounddesign** [comment]
> (note to self: there is also a chance the LFO does the "right" thing and then we lipol it at the outset of modulation setup so we get the super rapid sweep; make sure initial modulations are hard set not change set).

yeah - could be an interpolation issue, too - now that you say it... you maybe just must not interpolate at note on or so...

**Comment by baconpaul** [comment]
So what is happening, it seems is ::update_lagvals is getting called once with a 0 then the up amounts; and so is going to the immediately interpolate from 0 to amount.

Here's the values on a key press in an FXP set up roughly as you describe

```
update_lagvals  localcopy[id_shape].f=0
update_lagvals  localcopy[id_shape].f=0.984448
update_lagvals  localcopy[id_shape].f=0.984448
update_lagvals  localcopy[id_shape].f=0.984448
update_lagvals  localcopy[id_shape].f=0.984448
```

so lemme figure out where that 0 comes from.

**Comment by baconpaul** [comment]
And the reason for this is that SurgeVoice calls osc[i]->init before any of the LFOs get attack. The update_lagvals<true> is the one with a 0 and the <false> is the one without.

**Comment by baconpaul** [comment]
And the reason for this was because we called calc_ctrldata<true> after switch_toggled() in SurgeVoice.

Changing that order fixes this problem. Lemme do a review but I think I have this corrected.

**Comment by baconpaul** [comment]
OK @bigtonesounddesign I have just pushed a fix to this (around 12:30 US Eastern time). It should be in the nightly any time after about 1:15 pm today. If you would like to grab the nightly from the website later this afternoon or tomorrow or what not and confirm that's great.

If it still doesn't work for you if you could attach a .fxp and an mp3 in a zip file here and reopen the issue that would be super. But I am really confident that I both isolated and fixed the problem you describe. 

Thanks

**Comment by baconpaul** [comment]
The fix is now included in our nightly. Your confirmation that the problem is resolved would be greatly appreciated. No rush - we aren’t releasing 1.6.6 until April or so is my guess. But checking when you have time would be wonderful.

Thanks again for a clear report.

**Comment by bigtonesounddesign** [comment]
> The fix is now included in our nightly. Your confirmation that the problem is resolved would be greatly appreciated. No rush - we aren’t releasing 1.6.6 until April or so is my guess. But checking when you have time would be wonderful.
> 
> Thanks again for a clear report.

hi baconpaul,
you're welcome, no problem.
that sounds great. i will check the nightly version at the weekend.

ps: now, if you could only implement the possibility to not only retrigger the oscs, but also give the user the possibility to set the retrigger phase for each osc independently (i've requested it on kvr under my nickname "brok landers"), that would be _it_. ;)

kind regards,
nico from bigtone sounddesign

**Comment by baconpaul** [comment]
If you can add your request to #867 which I think is the same or expand that issue that would be great.

For some internal technical reasons - we are out of parameter slots alas - your request is probably hard to implement in the current version

**Comment by baconpaul** [comment]
Hi @bigtonesounddesign 

for a couple of reasons, we would like to do a release pretty soon (like next week!) which includes this change. If you do get a chance to confirm it in the  nightly this weekend that would be greatly appreciated.

**Comment by bigtonesounddesign** [comment]
hi paul,

the nightly build fixed it for me. the envs of the lfo now trigger instantly, when attack and delay are at minimum.

kind regards,
nico from bigtone

**Comment by baconpaul** [comment]
Great!! Thanks
