### ISSUE TITLE
RegTest the FM changes

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1564]
With #1171 I made Window observe FM but I didn't add a retest with that commit just checked it by ear comparing Sin -> FM2 and Sin -> Window-Setup-As-Sin

Ideally we would check that the https://en.wikipedia.org/wiki/Pearson_correlation_coefficient correlation between the two patches I used was similar as we modify FM depth. Or perhaps do a spectrum analysis to make sure similar high frequency spectra arise. Or maybe this is just too tricky to regtest automatically and reliably vs the size of the change, but I don't like that answer.

**Comment by Jurek-Raben** [comment]
Hi, how about adding this for wavetable OSCs, too? Or let's say, making FM possible for any kind of OSC mode? What do you think about it?

**Comment by baconpaul** [comment]
Right now, FM works on FM2/3/Sin/Window in one consistent manner and on Classic and Wavetable in a second manner, consistent with each other, but not consistent with the first chunk. The second is #1253 which is in the 1.6.6 milestone but, while trying to address yesterday, i realized may not be possible; so we may end up with two “clusters” of FM.

But right now all the oscillators (except maybe S&H) support FM just with rather different interpretations of depth in the two clusters.
