### ISSUE TITLE
Maybe a VST3 CC issue?

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1571]
As @JackyLigon and I discussed on slack: (edited for clarity)

Jacky  5:25 PM
@baconpaul Probably need to dig a little deeper, but was attempting to map an Assignable Controller to a synth parameter using CC17, and I can see it - curiously - changing FX1 Return slider, which I have in no way assigned to anything. Need to look more closely though.

baconpaul  5:27 PM
VST2 or VST3?

Jacky  5:27 PM
VST3

baconpaul  5:27 PM
And latest nightly?

Jacky  5:28 PM
Surge-NIGHTLY-2020-02-12-48b6528-Setup

baconpaul  5:29 PM
OK there’s some hairy mapping which goes on in the VST3 to get CCs working properly. I had tested that pretty closely but the FX return is in the collection of params which is kinda in the ‘painful and too complicated’ range so if you find a clear example that woudl be very very very useful

Jacky  5:30 PM
As a step in trying to diagnose the MIDI mapping issue above, I've been using Reaper's JS MIDI Examiner to see CCs and values coming from the keyboard controller, just confirming CC17...

baconpaul  5:30 PM
CC17 and which channel would be useful too!

Jacky  5:34 PM
Happens actually that it was transmitting CC17 on CH 3 in this case.

baconpaul  5:34 PM
@Jacky OK I will poke at it. Lemme open an issue so I don’t forget

**Comment by bit-101010** [comment]
I've noticed this too, on VST2 as well. The parameter name for FX return 1 show up as C1:[whatever you named the first assignable controller]
Master volume and C3 are linked like this, too. If you use MIDI learn on Controller 3, it learns to the Master Volume slider. 

Also, if I automate the Master volume parameter in my DAW (Reaper), it moves Controller 3 instead.

**Comment by baconpaul** [comment]
Just making sure you are running 1.6.6? I fixed a bunch of these things between 1.6.3 and 1.6.6.

**Comment by baconpaul** [comment]
But may have not fixed them all of course. Just want to confirm

**Comment by baconpaul** [comment]
I tested the heck out of this with indirection and am sure it’s fixed for 18
