### ISSUE TITLE
Bitwig Linux VST3 GUI errors (vst2 crash resolved)

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#1572]
Linux Build Debian Buster 10.2 commit faed28

VST3 GUI now displays intermittently, when the GUI displays VST3 all sliders work, sliders affect sound changes, however Menus are inoperable, Menus will display and it's possible to scroll with mouse or arrows but clicking the left Mouse or pressing the Enter key will not produce a response

If the VST3 screen is closed and reopened the black screen appears again
double clicking Surge VST3 in the VST browser will redisplay the GUI again but lose whatever sound was loaded

VST2 will see presets if the Data folders are added to Sound Content Locations
however the browser does not see the presets when the VST3 is loaded

VST2 is now crashing if closed and reopened and will give this screen

![surge vst2 01](https://user-images.githubusercontent.com/41337033/74409869-b06da480-4e05-11ea-9053-55e7061b0ca0.png)

**Comment by baconpaul** [comment]
Wonder if the VST2 open close thing is that fix I put in place for that windows host in the last update where I change the VST2 open close path... will peek. 

Which bitwig linux version you running?

Thanks!

**Comment by tank-trax** [comment]
latest Bitiwg 3.1.2

**Comment by baconpaul** [comment]
So the VST problem was indeed the change I made for #1406. I have backed it out for linux and am pushing now.

**Comment by tank-trax** [comment]
here are a few [examples](https://www.youtube.com/watch?v=EK_4GVVARIo&feature=youtu.be) visualized

**Comment by baconpaul** [comment]
Thanks!

**Comment by hoergen** [comment]
I don't know if it is the same error, but I only get a black window when opening surge under the latest Bitwig/Linux (Kubuntu 19.10) and only the first standard sound is available. Is there anything i can try?

**Comment by baconpaul** [comment]
It’s the same error. More details are in #514 
We haven’t been able to get the linux VST3 working in bitwig yet, just reaper. It’s on our list an the team at Bitwig has been very helpful, but we just can’t quite get it and it is remarkably difficult.

For now we recommend using the VST2 in bitwig linux if you are able to.

**Comment by hoergen** [comment]
Thanks a lot. That helps. Just had to add `/usr/lib/vst` to locations in Bitwig and removed the files+directories in `/usr/lib/vst3` .

**Comment by baconpaul** [comment]
Great. Thanks for your patience and enjoy making music with Surge!

**Comment by baconpaul** [comment]
With the various updates we have pushed to head of surge, and with some updates to bitwig which will be 3.2 beta4 either this weekend or early next week, the surge vst3 finally works properly in bitwig. So I'm going to close this issue (although since beta4 isn't in full avail yet you may have to wait until next week to see the update)

**Comment by hoergen** [comment]
With  Bitwig version 3.2.1 there are still problems with VST3. It opens (mostly) but you can't use it or select a preset. I returned to use VST2 again.

**Comment by baconpaul** [comment]
Are you using the nightly or 1.6.6?
We have made many changes (both to bitwig and surge actually) to make the nightly work.

**Comment by tank-trax** [comment]
for the VST3 the presets cannot be accessed via Bitwig's preset browser (as is the case with the VST2) and can only be accessed via Surge's Preset Menu

other than that, could you tell us what exactly is not working?

**Comment by hoergen** [comment]
> Are you using the nightly or 1.6.6?
> We have made many changes (both to bitwig and surge actually) to make the nightly work.

I used the official 1.6.6 Release, when I was writing that comment. But i tried your suggestion and first impression is, that it is working great. Thank you 🌻👍

**Comment by baconpaul** [comment]
Super!
