### ISSUE TITLE
Stereo-by-default

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1575]
Right now the filter bank in surge pushes everything to mono. Doesn't have to, but it does. So we lose things like stereo unison in the Oscillators. It all gets re-stereofied in the effects though.

After talking with @JackyLigon @mkruselj and others on slack decided the following:

1. Add a button "Stereo" which is off for all current patches, on for a blank surge, and saves in the patch state
2. If stereo is on, make all the mono filter paths stereo; leave L<>R and Wide unchecking
3. If stereo is off, make all the filter paths mono as they are today

All pretty obvious how to do it. Bump the streaming version etc.... and so on.

Also "stereo" is not a DAW modulatable thing so we don't even need to burn a param slot.

**Comment by mkruselj** [comment]
This issue ties into #1150 and #1825, so let me link it to those, and also change milestone to after XT 1.0.

**Comment by mkruselj** [comment]
Actually #4355 replaces this issue pretty much entirely, so closing this one.
