### ISSUE TITLE
Microtuning affects oscillator display

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1590]
1. Load ED2-5 microtuning from factory tuning library
2. Pick one of the oscillators (click on a tab)
3. Osc waveform changes

Obviously waveform display is drawn by sending a MIDI note number then rendered by the resulting tone, but microtuning messes with this. I assume this is middle C (261 Hz in 12-TET 440 Hz). A number of microtunings mess this frequency up, so maybe there should be a way to force the waveform display to **always** draw at 261 Hz?

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/blob/2888e8e54ee097410389951db07267c4219b1eae/src/common/gui/COscillatorDisplay.cpp#L156

The code is in pitch space. 95.15-48+some goop is the pitch but that must imply a frequency so I can find that frequency or close to it in pitch space instead ... should be a smallish fix. Nice find!

**Comment by baconpaul** [comment]
OK I've confirmed the note being played is around note 42 but what we really want is "the note where the pitch is 11.414" (pitch is basically frequency / 8.16etc... and is the internal representation surge uses).

So the fix here is to, if in non-standard-tuning, find a pair of notes which bracket the ignored tuning. Not that hard but a bit tedious. Will fix before we ship 1.6.6
