### ISSUE TITLE
Save SCL and KBM microtuning data in patches

### ISSUE THREAD

**Issue by JackyLigon** [surge-synthesizer/surge#1598]
Surge-NIGHTLY-2020-02-21-8dc0cf8 | Windows 10 x64 | Reaper, Live | VST3i

Although something I would tend to rarely use, I'd been curious about the **Store Patch / Save Tuning In Patch** feature, so I made a test to see how it worked.

Worth mentioning, is that while I found that the SCL saved with a patch is reliably restored on reopening the patch and the Show Current Tuning data displays correctly, I noticed that any loaded KBM is not being stored with the patch, and upon reopening the preset, the KBM is lost.

**FWIW: I would suggest that it's a good idea to save/restore the KBM with patches as well.**

I'm imagining two scenarios where it would be useful to be able to Save/Restore both the SCL and KBM data associated with patches:

1. Live performance scenarios, where one might prefer to completely save and restore the patch state, with the complete tuning data, to eliminate having to load them in a performance setting.
2. Where one has designed custom patches on a per-composition basis (something I'm actually doing with increasing frequency), and wishes to restore the complete patch state with the SCL-KBM intonation data.

**Comment by baconpaul** [comment]
Thank you yes of course. I added kbm support after this feature and forgot to test it. Is ill delay 1.6.6 slightly and add it
