### ISSUE TITLE
Sending Program Change and Notes at the same time yields a short pluck instead of preset

### ISSUE THREAD

**Issue by hems** [surge-synthesizer/surge#1601]
**Describe the bug**
Sending Program Change on Ableton and Notes at the same time yields no sound, for instance:

![image](https://user-images.githubusercontent.com/27327/75102665-b1be7e80-5608-11ea-9a20-3d888633c548.png)

^ will make no sound

![image](https://user-images.githubusercontent.com/27327/75102669-be42d700-5608-11ea-984d-0ba88346b42e.png)

^ if i delay the notes by 1/16 @ 121bpm will change the preset then yield sound.

**Please let us know your surge version**

I'm using the AU, here is the version / build screenshot
![image](https://user-images.githubusercontent.com/27327/75102675-db77a580-5608-11ea-98f7-0e6f1962fa6c.png)

**To Reproduce**
Please look at bug description

**Expected behavior**
Change the preset and play the notes

**Screenshots**
please see description

**Desktop (please complete the following information):**

OSX 10.12.6, Abletn Live 10

**Comment by baconpaul** [comment]
Hi!

Let me tie this to #576. The way a program change will work is it will queue up a change so it is entirely possible that it comes out of order. Thank you for the report!

**Comment by mkruselj** [comment]
Considering a number of other virtual instruments that support changing programs via program changes behave similarly to Surge here (or they don't produce any sound at all), I am going to close this issue. Gotta have just a tiny little difference of a single MIDI tick or two after program change for things to work.

**Comment by mkruselj** [comment]
When we Get program change support working in the future (#576), we will test this, but we aren't fixing this code path, sorry.

**Comment by hems** [comment]
> When we get program change support working in the future (#576), we will test this, but we aren't fixing this code path, sorry. It will really depend on how JUCE implements this and how it schedules MIDI events internally. If behavior stays the same, well that's that then and nothing we can do about it, would need to be fixed on JUCE side (which is less likely to happen).

so you saying every plugin made with JUCE has the same bug? 

i find hard to think that would be the case? and if it's the case there must be some workaround documented JUCE forums / mailing list or something like that?

if there is not then we should fill a bug report on JUCE?

i honestly would like to help with with filling a bug or looking for the solution on the JUCE part ( surely someone has a solution for such basic issue ) but i'm not familiar enough with JUCE :(

**Comment by mkruselj** [comment]
Try other JUCE plugins, i.e. OB-Xd or Dexed and see if they exhibit the same behavior.

**Comment by hems** [comment]
> Try other JUCE plugins, i.e. OB-Xd or Dexed and see if they exhibit the same behavior.

just tried on Dexed it works perfectly as expected

**Comment by hems** [comment]
> No we aren’t saying that
> We ported to juce and haven’t supported their preset mechanism yet
> If this is fine in other juce plugins one day it will be in surge if we support their preset mechanism

makes sense!! i understand @mkruselj message now!
