### ISSUE TITLE
Display Bank / Sub / Program number for current preset?

### ISSUE THREAD

**Issue by hems** [surge-synthesizer/surge#1602]
**Is your feature request related to a problem? Please describe.**
During a live performance, it's important to keep the number of instances to a minimum so ideally changing programs should work as smooth as possible.

If i change the preset on the UI it's hard to know what Bank / Sub / Program i'm using so it's not straight forward to add this information on the midi clip.

**Describe the solution you'd like**
Be able to see the Program information on the UI.

**Additional context**
I'm Afraid adding presets to a preset folder will change/offset the Program  Number for a Program Change Message already baked into the life performance sequencer / DAW which means replaying the same midi messages would yield different sound.

Perhaps one must be able to select which preset will be allocated to each PGM message and that list of presets would be saved on the current state of the instance so adding presets to Surge won't mess previous sequences.

Does that make sense?

For example let's say i only have 3 presets:

 - Bass/Super Bass ( Program 1 )
 - Pads/Super Pad ( Program 2 )
 - Pads/Crap Pad ( Program 3 )

Then i go to my sequencer and sequence my PADS track so eventually it changes the preset from Super Pad to Crap Pad.

Later on in another project i create another Bass preset, now i would have 4 presets:

 - Bass/Crap Bass  ( Program 1 )
 - Bass/Super Bass  ( Program 2 )
 - Pads/Super Pad  ( Program 3 )
 - Pads/Crap Pad  ( Program 4 )

Therefore if i play my other project the Program Change Messages will be triggering the wrong presets.

Am i doing or understading something wrong? Any recommendations on how to work aruond that?

**Comment by baconpaul** [comment]
Hi!

I think this is a dup of #576 but with a clearer spec. 

The short version of an answer is: We don’t support program change in surge very well now at all. Basically we just run through the patches in random order but don’t crash. I’ll leave this open and tied to the #576 issue.

**Comment by mkruselj** [comment]
@baconpaul I would close this one because we're gonna do program change support differently across the board. As it stands, this FR is only valid for VST2, which we don't officially support anymore.
