### ISSUE TITLE
KBM button

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#1607]
Could it be possible to add a kbm button below mpe and tun to the right of the Patch Browser to allow for disabling/enabling keyboard mapping?

Thanks

**Comment by JackyLigon** [comment]
Take or leave as needed, but with the TUN button now labeled Tuning, it somewhat obviates the need to have discrete SCL and KBM buttons. Tuning should be sufficient and concise enough to use for drag-and-dropping SCL and KBM files onto the button to microtune and map Surge.
