### ISSUE TITLE
Aeg name doesn’t vary by scene in params

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1608]
shoukd be aeg a and b or some such
As reported on the big kvr thread

**Comment by mkruselj** [comment]
In fact ALL the synth parameters need the A/B designation for automation names, they are all duplicates now.

**Comment by baconpaul** [comment]
@mkruselj you have fixed this yes?

**Comment by mkruselj** [comment]
Indeed, this was fixed with #1899 but I forgot to adjust commit message to reference this issue :(
