### ISSUE TITLE
VST3 polyphonic aftertouch incorrect

### ISSUE THREAD

**Issue by jpcima** [surge-synthesizer/surge#1610]
**Describe the bug**
VST3 polyphonic aftertouch incorrect

**Please let us know your surge version**
Surge Git 44e2fed

I find a programming problem which seems to me rather evident with a look at source code.

The poly pressure from VST3 is documented as 0-1 float, and passed into an int argument expecting 0-127. I'm guessing the aftertouch also required the `value01ToMidi7Bit` treatment.

https://github.com/surge-synthesizer/surge/blob/44e2fedc335cd32984395e8243c85fd6a7d7b562/src/vst3/SurgeVst3Processor.cpp#L260-L262

**Comment by baconpaul** [comment]
Oh darn it I thiought we got all of those. You are correct this one needs the value01ToMidi7Bit application. 

Want to toss in a PR? If not I’ll do it when I’m next in the VST3.

Thanks!
