### ISSUE TITLE
Envelope Self Modulation

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1613]
ampeg can't modulate ampeg attack (or filteg attack for that matter) because of ModulationSource.h / canModulateModulators

So what bad thing happens if we lift that restriction? And how do we compensate for that thing?

Raised by slack user 'stamp'

**Comment by mkruselj** [comment]
@baconpaul I tested out lifting that restriction. Nothing terribly bad happens, but it doesn't seem to work properly either. So if I self-modulate filter EG attack with filter EG (digital mode for env, all stages linear), I don't hear any added curving in the envelope shapes, just the duration of the stage becomes longer or shorter depending on modulation amount.

The intention behind this FR is to be able to additionally shape the envelope curvature, this is how it was done in Access Virus for example. However, we don't need to do it like that, at all. The proper solution for this request is making attack/decay/release curve 3-position switches actual continuous controls that would reshape the curvature with more granularity (say, up to 10th power and 1/10th power in the other direction).

**Comment by mkruselj** [comment]
@baconpaul I think this is a "won't be done". This feature request is inspired by the method Access Virus uses to affect the slopes of envelope stages. We have a different method in place (digital with 3 curves per stage, or analog), and we have much more curve flexibility with MSEG now.

I guess another way of sorting this one out is adding a new FEG/AEG mode that would give a -1...1 numfield for ADR stages (like in Shortcircuit). But I'm kinda not a fan of that solution. I'd rather leave this sort of thing to MSEGs. So, fair to close by applying "Won't be Done" label?

**Comment by baconpaul** [comment]
yeah with mseg and (especially) with formula you can do literally what you want. agree.
