### ISSUE TITLE
Can Surge mimic wave sequencing?

### ISSUE THREAD

**Issue by MaurerMusic** [surge-synthesizer/surge#1614]
[Wave_Motion.zip](https://github.com/surge-synthesizer/surge/files/4297889/Wave_Motion.zip)

Here are 50 Presets inspired by a recently released wave sequencing synth.  Since the designs of Surge and the aforementioned hardware synth are so different, there were some limitations in recreating "that" sound.  However, Since Surge can do FM and Physical Modeling, there were also new opportunities to explore.

Play, have fun, enjoy...

**Comment by baconpaul** [comment]
Hey thanks! I’ll push these into the distribution and, since it will be a little while until we ship another release, also put them on our extra content page if that’s OK with you?

Appreciate the patches!

**Comment by bgins** [comment]
These are some awesome patches!

**Comment by MaurerMusic** [comment]
Thanks for the nice comments.  I was in the mood to try something new and this resulted.  

Putting these on the extra content page is fine with me.

**Comment by baconpaul** [comment]
OK I merged these into the repo so they will be in the nightly and in 1.7; and also put them on the additional content page so people can get them before 1.7 ships

I also played them. These are amazing patches. What a fascinating way to highlight the synth. Thank you very much!!

**Comment by MaurerMusic** [comment]
Maybe one of the users could make a video demoing a few of the patches.  Might generate additional interest in this project.
