### ISSUE TITLE
playing a mis installed surge after the warnings crashes

### ISSUE THREAD

**Issue by magnetophon** [surge-synthesizer/surge#1617]
**Describe the bug**
When I change the oscilator type to wavetable or window while playing notes, the plugin takes down Ardour.
 

**Please let us know your surge version**

* Surge Version: 1.6.6
* Plugin type LV2
* Bits 64

**To Reproduce**
1. play a sequence
2. Click CLASSIC
3. Click WAVETABLE
4. See crash

**Desktop (please complete the following information):**
 - OS: linux; NixOS
 - Host Ardour
 - Version 5.12

**Comment by baconpaul** [comment]
thanks. if you aren't playing does it crash? did you get a stack?

**Comment by baconpaul** [comment]
Just tried the AU on mac and it didn't exhibit this behavior, so this is either LV2, Linux, or Ardour related at a minimum.

**Comment by magnetophon** [comment]
@baconpaul When I'm not playing, there's no crash.
I didn't get any output, other then "segmentation fault".

**Comment by baconpaul** [comment]
Ok thanks!

**Comment by baconpaul** [comment]
If I had to speculate: The changes we made so that parameters re-broadcast their values when you change oscillator and effect type I bet are doing something which confuses either Ardour or the LV2 while playing. That's just  a note for me or others when we turn to this.

**Comment by magnetophon** [comment]
I finished up creating a package, and now Surge can find it's data (wavetables, presets, etc).
That also fixed the crash!

So the bug is: It'll crash when switching to wavetabe during playing, when there is no wavetable data.

**Comment by baconpaul** [comment]
Oh sure but it will also warn when it can’t find those. You should have gotten a zenity popup. Did you not?

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/blob/a7da44c8b8f48788af2c0c2dd88b6b032c42b6bd/src/linux/UserInteractionsLinux.cpp#L53

Yeah there you go. When the synth is improperly installed it will try and show a zenity error and put an error to stderr saying it won’t work.

If you have ideas about other things we could do in that error case I would love to hear them. We are hindered a bit by the fact that linux doesn’t have standard desktop os apis for things like message boxes.

**Comment by baconpaul** [comment]
(And I am presuming they you don’t have zenity installed and ardour didn’t show you stderr)

**Comment by magnetophon** [comment]
Yeah, I didn't have zenity.
I've added it to the dependencies of the pkg and will report back when it's done building.

**Comment by baconpaul** [comment]
Cool
Which package out of curiosity?
In installer-linux we have the prerequisites in the deb listed if that helps?

**Comment by magnetophon** [comment]
I'm making a pkg for NixOS.
I found all the deps by now, too late.  :)
Maybe put the full list in the readme, for the next chap...

As far as I can tell it's:
premake5, pkgconfig, cmake ,cairo, libxkbcommon, libxcb, xcb-util-cursor, xcbutilkeysyms, ncurses, which, getopt ,python, zenity

**Comment by baconpaul** [comment]
Thanks!

yeah that sounds about right. Also the lato font package. Happy for you to either drop a readme update here when you have it all or send in a PR to the README whichever works for you.

**Comment by magnetophon** [comment]
What do you mean by "drop a readme update here when you have it all"?

**Comment by baconpaul** [comment]
Oh “if you wish the readme had said xyz please let us know the xyz either in this issue or as a pull request to the readme.md in this repo” is all!

Thanks

**Comment by magnetophon** [comment]
OK, will do.  Thank *you* for such a great synth!

**Comment by baconpaul** [comment]
Thanks for helping make it available to more users!

**Comment by magnetophon** [comment]
NP.  Come to think of your PR proposal: I only know the names of the pkgs in NixOS, so maybe it'd be best if you take the above list, translate it to something more universal, ike Debian names, and put it in the readme yourself.

**Comment by baconpaul** [comment]
Ok cool will do next time I have the readme open 

(In fact what I’ll probably do is just have the readme link to the spot in our installer and ci pipeline where we set up the packages)

Thanks!

**Comment by tank-trax** [comment]
compiling on Debian gives specific errors so it's very easy to find what's needed

for example, on a recent installation of Debian Buster I had to install **rsync** and **premake5** on top of what was listed
