### ISSUE TITLE
Rename Ctl1 without zenity installed breaks the gui

### ISSUE THREAD

**Issue by magnetophon** [surge-synthesizer/surge#1618]
**Describe the bug**
When I click "rename Ctl1" the gui turns into this:
![screenshot_20200311_134455](https://user-images.githubusercontent.com/7645711/76419536-ca68bb80-63a0-11ea-8c4e-cfcb8d0cfba1.png)

Then I did something with Surge that crashed Ardour. I forgot what I did, sorry.
When I reopen Ardour, create a new track, add Surge and open the gui, it's still broken.

The name of the function I clicked  is from memory, as I don't have a working surge anymore.

**Please let us know your surge version**

* Surge Version: 1.6.6
* Plugin type: LV2
* Bits 64

**To Reproduce**
1. right click Ctl1
2. click "rename Ctl1"
3. See error

**Desktop (please complete the following information):**
 - OS: NixOS
 - Host: Ardour
 - Version: 5.12

**Comment by baconpaul** [comment]
that rename pops up zenity
i just tried it on ubuntu 18 with the lv2 in ardour and it worked fine
did you get a small window popping up when you clicked rename?

I am not sure why it would permanently blow up your surge. perhaps start a fresh ardour session?

**Comment by magnetophon** [comment]
When I open a new ardour session, the gui works again.
The other session still doesn't.
I ran Ardour from the cli, and got "zenity: command not found" when I tried to rename.
No broken gui this time.

I can attach the Ardour session if you want.

**Comment by baconpaul** [comment]
Nah no need

I bet the problem is here

https://github.com/surge-synthesizer/surge/blob/a7da44c8b8f48788af2c0c2dd88b6b032c42b6bd/src/common/gui/PopupEditorDialog.cpp#L156

when zenity isn't found we leave garbage in the buffer.

Both those return branches should add a c[0] = 0; before the return.
