### ISSUE TITLE
Add standard stereo controls for unison

### ISSUE THREAD

**Issue by kzantow** [surge-synthesizer/surge#162]
Currently unison [seems to be] implemented in mono. It would be much nicer to add stereo width and detune like most modern synths have. One question is where to put this in the UI, any suggestions welcome.

**Comment by esaruoho** [comment]
This could be tackled post-1.6.0 i guess :)

**Comment by kzantow** [comment]
NOTES:

@baconpaul found that there is already some code to deal with stereo unison; some links to the files are here:
https://github.com/surge-synthesizer/surge/blob/802cd1130ce228106ea4b2a8fa01d834363e069c/src/common/dsp/SurgeSuperOscillator.cpp#L41
https://github.com/surge-synthesizer/surge/blob/802cd1130ce228106ea4b2a8fa01d834363e069c/src/common/dsp/WavetableOscillator.cpp#L271

**Comment by Jurek-Raben** [comment]
The unison feature should provide a stereo amount, a stereo spread curve amount ranging from log to exp, and then also a pitch spread curve amount, too.

**Comment by mkruselj** [comment]
We already have that covered by #3150.
