### ISSUE TITLE
Skinned TempoSync Slider Markers are wrong

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1626]
Parameterize the space you have and so on.

**Comment by baconpaul** [comment]
I'm going to solve this one the same way I solved #1634. Absent an overlay glyph paint the current "TS" but if you provide an overlay glyph, then use that.

**Comment by baconpaul** [comment]
OK @itsmedavep I have fixed the little "TS" splattage problem.

I did that by introducing a couple of extra SVGs just like I did for the MPE button. Here's a diff I made to the dark-skin in #1642. I also introduced two new SVGs which are the size of one of the handle sprites and are painted over the appropriate sprite. In this case I just made it a little "TS" in your #202020 color and it looks fine but you may want a different glyph perhaps.

Like the other issues I'm not going to auto-close this one when I merge #1642 but if you look and decide that this solution looks OK we can close this one!

```
diff --git a/resources/data/skins/dark-mode.surge-skin/skin.xml b/resources/data/skins/dark-mode.surge-skin/skin.xml
index 78b2b8af..4195fa3e 100644
--- a/resources/data/skins/dark-mode.surge-skin/skin.xml
+++ b/resources/data/skins/dark-mode.surge-skin/skin.xml
@@ -3,6 +3,8 @@
     <!-- This means if there is a bmp00???.svg in this directory we use it over the built in for this skin -->
     <defaultimage directory="SVG/"/>
 
+    <image id="TEMPOSYNC_HORIZONTAL_OVERLAY" resource="SVG/temposync_horizontal_overlay.svg"/>
+    <image id="TEMPOSYNC_VERTICAL_OVERLAY" resource="SVG/temposync_vertical_overlay.svg"/>
     
     <color id="lfo.waveform.fill" value="#303030"/> 
     <color id="lfo.waveform.font" value="#FF9000"/>
```

**Comment by itsmedavep** [comment]
OH Snap. I didnt realize this was a thing. Ill look at this tomorrow.

**Comment by baconpaul** [comment]
OK since you used this successfully in the latest PR it seems it all works. Also I like the cool inner blue dot. Closing this.
