### ISSUE TITLE
Be smart about showing the DEV menu

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1627]
It's just for paul and skin developers. figure out how to turn it off for other folks. perhaps have it toggle in the ui menu?.

**Comment by itsmedavep** [comment]
Maybe a key combo when clicking on the menu ala macOS finder and the Go menu for showing library?

**Comment by mkruselj** [comment]
I would suggest instead of a key combo, a right click on Menu instead of left click should add dev features. Simpler and needs one hand only. The other hand can hold a beer mug.

**Comment by baconpaul** [comment]
@mkruselj closing this one since you got it. Thanks!

**Comment by mkruselj** [comment]
Now you can dev menu while you also beer mug! :)
