### ISSUE TITLE
Cursor hiding on Mac and Linux

### ISSUE THREAD

**Issue by hems** [surge-synthesizer/surge#1631]
**Describe the bug**
When clicking a slider and sliding on OSX the mouse starting moving on the screen ( As opposed to standing still and only the slider moving ).

This creates a problem because if the mouse reaches the left most or right most side of the screen you can't move the slider further, having to release the clicked slider, clicking again and starting dragging again.

For some reason this is also connected to "zooming the interface", so when zooming it to for instance 150% it seems the slider gets even less sensitive to the mouse movement, therefore even if you slide the entire screen the slider ends up sliding much slower.

**Please let us know your surge version**

![image](https://user-images.githubusercontent.com/27327/77002911-468c7180-6954-11ea-8afe-3a333bced274.png)

**To Reproduce**
click and drag a slider until the pointer reaches the left or right most side before the slider going to 0% or 100% value.

**Expected behavior**
1. the mouse could stay still and only the slider move
2. zooming on the UI would still have the same sensitivity as 100% zoom

**Desktop (please complete the following information):**
OS 10.12
Live 10

**Comment by baconpaul** [comment]
Thanks I'll definitely look

There are a couple of mouse modes in the UI menu (like exact, slow, medium, classic) which change this behavior. And we fixed a few edge cases between 1.6.4.1 and 1.6.6 (but not the case you report I don't think). Just in case that helps.

**Comment by hems** [comment]
interesting.. after fiddling with the mouse options it seems the bug went away..

i'm not entirely sure if i can reproduce it now.

anyway i believe the desired effect would b the mouse pointer to stick to the initial position and only the slider move?

that's show some other interfaces work?

For instance in ableton when i click a knob to drag my mouse disappears and only the knob value changes, once i release the button my pointer stays on the same place.

**Comment by baconpaul** [comment]
Yeah there's cursor hiding support on windows but not on mac or lin. Lemme change the title of this issue and will try and figure out why that isn't working. (I think it has never worked and the cursor hiding stuff on mac is just a no-op)

**Comment by baconpaul** [comment]
Gonna close this since

1: Mac and Win are done
2: The Linux APIs are more confusing and less uniform. If someone really wants to figure out how to get to xcb_warp_cursor through vstgui lets open another issue.
3: But the API responds cleanly whether you have or don't have it.
