### ISSUE TITLE
Skin: Add in colors for controlling LFO Step Sequence <> arrow buttons

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#1632]
If you hop on over to my branch

Surge-Color-Identifications and look at commit: 5b3bd5f

I added in the colors for the left and right arrow buttons

You can find those changes here:

<img width="663" alt="Screen Shot 2020-03-18 at 8 15 34 PM" src="https://user-images.githubusercontent.com/11078351/77021962-47be9e00-6956-11ea-9418-cb490123ad5a.png">

Would be nice to have. Alternatively, just specifying an image for those would be good too.

**Comment by baconpaul** [comment]
Man I can't believe I missed these first time round. See my comment on the other issue. I'll get to them later today I bet but the prescription to convert them in master is also super easy if you want to!

**Comment by itsmedavep** [comment]
Fixed this up. Opening a PR...

<img width="561" alt="Screen Shot 2020-03-20 at 7 29 37 AM" src="https://user-images.githubusercontent.com/11078351/77163694-9b2b0c00-6a7c-11ea-8521-42609326df59.png">
PR:
https://github.com/surge-synthesizer/surge/pull/1644
