### ISSUE TITLE
Skin: LFO Ruler ticks line and LFO label colors

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#1633]
I would love to be able to set the ruler ticks color in the xml. Additionally, Id love to be able to set the font color for the LFO label.

If you go to my Surge-Color-Identifications branch on this commit: be4bcf4

Searching for setFontColor will yield 6 results. That would point you at where I changed the font colors. 

<img width="838" alt="Screen Shot 2020-03-18 at 8 27 41 PM" src="https://user-images.githubusercontent.com/11078351/77022688-4db57e80-6958-11ea-94d3-b047aa760cc2.png">

This image gets at the places I changed the tick marks and stuff. Would be nice to have those in the skin colors as well.

**Comment by baconpaul** [comment]
Oh sorry I missed those!

Just so you know the change to make against master for putting LFO colors into the XML is to change lines like

```
dc->setFrameColor(VSTGUI::CColor(0xE0, 0x80, 0x00));
```

to

```
dc->setFrameColor( skin->getColor( "lfo.waveform.tickruler" ), VSTGUI::CColor( 0xE0, 0x80, 0x00 ) );
```

which will introduce a new dynamic color ("lfo.waveform.tickruler") which you can then set in the XML, defaulting it to the original color in case it isn't set.

I can make those changes this afternoon but if you want to make them this morning I'm also happy for you to do so!

**Comment by baconpaul** [comment]
Oh and that change works in general if I have hooked the skin engine up to the component which with most components I now have for slider, LFO, OSC, StatusPanel, Numberfield and a few others (look in the .h file to see if the class implements Surge::UI::SkinConsumingComponent or not).

**Comment by itsmedavep** [comment]
I got more of these last night. I was trying to track down the "minor" ruler ticks and where that color was being used (its orange now). Just leaving a note here for me to find and change that. It seemed like it was just using the waveform color. Ideally, Id like to separate it out to its own. 

Happy to do the work. Just leaving a reminder for myself.

**Comment by itsmedavep** [comment]
Got it. Pr incoming.

<img width="454" alt="Screen Shot 2020-03-21 at 2 25 01 PM" src="https://user-images.githubusercontent.com/11078351/77234899-d06c5280-6b7f-11ea-98c5-c747e6933c63.png">

**Comment by itsmedavep** [comment]
PR is merged closing now.
