### ISSUE TITLE
Skin: Status Buttons

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#1634]
I changed the radius of them in code. Ultimately though it would be sweet to just have them be an .svg. If you want to start exposing things like radius along with the colors which are already there you could do so by using this stuff:

I did change the radius on the selected state too. Again, not sure if it should be a graphic or not as the answer but here is some info.

CStatusPanel.cpp

<img width="1243" alt="Screen Shot 2020-03-18 at 8 41 08 PM" src="https://user-images.githubusercontent.com/11078351/77022969-efd56680-6958-11ea-9d9a-e90019ff1304.png">

**Comment by baconpaul** [comment]
Yeah I should just make these SVGs. They will also be useful since they will be the first example of a fully optional SVG (namely an SVG which appears in a skin but doesn't appear in master) which is something I want to be able to do anyway.

Don't suppose you happen to have a 2 state sprite for 'on-off' without text for the button you want handy do you? If so attaching it to this image or dm it to me on slack would be super handy.

**Comment by baconpaul** [comment]
OK @itsmedavep here's what I've done.

By default the button draws with current radii using the colors I put in your skin

You can override this by making a button background image. The button is size 31x11 so the SVG is a 31x22 SVG with the disabled state on top and the enabled on bottom. Put this SVG in your skin SVG/ directory with whatever name then add to your skin

```
  <image id="STATUS_BUTTON" resource="SVG/whateveryounamedit.svg"/>
```

and your skin will see the image and avoid the code to draw the background. You can then use the foreground colors in the skin already to set the various states.

Need to merge the PR linked above but will do that as soon as it builds.

Here's my dumb test skin showing it.

![dumbskin](https://user-images.githubusercontent.com/13387561/77087727-d4f70680-69d9-11ea-88be-c6e051d43887.gif)

**Comment by baconpaul** [comment]
OK I merged that PR. Why don't you see if that lets you use a glyph to accomplish this in the dark skin and if it does, fire over a PR to the dark skin which closes this one?

**Comment by itsmedavep** [comment]
![status_button](https://user-images.githubusercontent.com/11078351/77125743-ca0d9780-6a14-11ea-9a52-b47bd02a6222.gif)

Looks great. Closing.

**Comment by baconpaul** [comment]
Cool - look forward to the new asset pr! And thanks!
