### ISSUE TITLE
Skin: Change area behind LFO waveform color

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#1635]
It would be great to be able to control the bg color of the area the LFO waveform draws on.

**Comment by itsmedavep** [comment]
<img width="604" alt="Screen Shot 2020-03-18 at 8 44 11 PM" src="https://user-images.githubusercontent.com/11078351/77023065-404cc400-6959-11ea-868d-d1f467c02acd.png">

**Comment by baconpaul** [comment]
Note to self: right now we don't even fill the component in vector mode so just ride along with the background. Add a color test for it and do a fillrect.

**Comment by baconpaul** [comment]
Once I merge #1641 the color "lfo.waveform.fill" will do this. I also put it in the dark skin. If that works as you expect, please close this issue! Thanks!

**Comment by baconpaul** [comment]
Oh and from my dumb test skin, this is the part of the UI to which that color applies.

<img width="686" alt="Screen Shot 2020-03-19 at 3 47 00 PM" src="https://user-images.githubusercontent.com/13387561/77108616-e7cd0380-69f8-11ea-8c2a-8428285170c9.png">

**Comment by itsmedavep** [comment]
Color change looks good. I do seem to get a little drawing oddness.

<img width="469" alt="Screen Shot 2020-03-19 at 6 56 22 PM" src="https://user-images.githubusercontent.com/11078351/77125293-5d45cd80-6a13-11ea-9598-d575a3af321b.png">

I

**Comment by baconpaul** [comment]
Oh I bet that’s the attack envelope - I will look tomorrow

**Comment by itsmedavep** [comment]
Oh yeah! It totally was and I didnt realize I had touched it. Closing out now
