### ISSUE TITLE
VST3: Split Processor vs Controller?

### ISSUE THREAD

**Issue by whydoubt** [surge-synthesizer/surge#164]
SurgeVst3EditController is unused.  Either the processor and controller should be split properly into separate components, or this vestigial controller should go away.  Knowing the history of the VST3 code could be of value here.  FWIW, Steinberg discourages using the single-component pattern for VST3 plugins.

From messing with the code a bit, the main issue I run into with trying to split the components is that methods from both components access surgeInstance, and I don't know how to handle that.

**Comment by baconpaul** [comment]
I'm struggling with VST3 zoom #305 #357 and I think it's because of this split also. The API to indicate resize to a host is not clearly reachable from our single class to me. Not sure I am correct, but just linking the issues.

**Comment by baconpaul** [comment]
So I'm going to close this issue because I just opened #1208 which will subsume this. We need to do this for sure, but it's a big change which #1208 covers for all the host flavors.
