### ISSUE TITLE
Skin: Graphic artifacts when switching selected buttons

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#1646]
Not sure when this cropped up but I am seeing it on both the light and dark skins. 

![graphic_artifacts](https://user-images.githubusercontent.com/11078351/77203778-48267880-6abf-11ea-995a-ca593e010306.gif)

macOS Mojave. 150% zoom but visible at all zoom level except 100%.

Essentially when the graphics files touch the extents of the clipping area there are some parts of it the dont appear to be getting redrawn when selecting a differing control.

**Comment by baconpaul** [comment]
So I can confirm this booger both here and in the filter dialog per @mkruselj report on slack. Looking. Not exactly sure what it is yet.

**Comment by baconpaul** [comment]
and I can't for the life of me figure it out. Harumph. I thought it was the clip 0.01 shenanigans in CScalableBitmap but it isnt

**Comment by baconpaul** [comment]
The crazy thing with poly is the only one it sticks on is the one which is set when you do the rebuild.So like select MONO FP and your booger is (wherever) no do scene b scene a and there is no booger. Check POLY and the booger is now on MONO FP

So something about the *initial* draw is misaligned by a smidge. 

<img width="559" alt="Screen Shot 2020-04-10 at 10 13 18 AM" src="https://user-images.githubusercontent.com/13387561/78997085-ed0f0100-7b13-11ea-8b5b-ee9ac4dee059.png">

And if you zoom up you can see the smidge is exactly one pixel

So somewhere between the draw-at-rebuild and the redraw is a one pixel jiggle.

Double harumph. I will get this, but I won't get it today.

**Comment by baconpaul** [comment]
Interestingly you can see there that the selected one is also drawn off by one pixel just you don't notice because the leftover goobit is the almost black line. I wonder if the whole draw is shifting by one px between build and redraw.

(Why on earth would that happen).

**Comment by baconpaul** [comment]
OK so the draw when we rebuild has cliprect == viewrect
The draw when we hover or click without a rebuild has cliprect < viewrect by a smidge

```
VIEW (x=239,y=87)+(w=50,h=47)
CLIP (x=239.259,y=87)+(w=49.6296,h=47)
```

that's at 130% on my mac or some such.

**Comment by baconpaul** [comment]
sigh so i tried a call to makeIntegral inside cviewcontainer and that made the clip rectangle the right size but didn't kill the broken pixel :(

**Comment by baconpaul** [comment]
Sigh
This isn't a painting problem I don't think
it is an invalidation problem
that is: the widget invalidates too small a region when zoomed
probably due to some rounding error

**Comment by baconpaul** [comment]
yeah ha that's exactly it

If I do

```
void CView::invalidRect (const CRect& rect)
{
   CRect fr = rect;
   fr.extend(1,1);
	if (isAttached () && hasViewFlag (kVisible))
	{
		vstgui_assert (pImpl->parentView);
		pImpl->parentView->invalidRect (fr);
	}
}
``` 

then no edge boogers. I don't think that's the permanent solution but I'm suer close now.
