### ISSUE TITLE
Scrolling does not work for the LFO waveform selector

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1648]
**Describe the bug**
Scrolling does not work for the LFO waveform selector.

**Expected behavior**
Scrolling on that area should switch LFO waveforms, like it does on other button arrays like this one.

**Screenshots**
![image](https://user-images.githubusercontent.com/50145178/77216478-eda61000-6af0-11ea-8d10-322eeada586d.png)

**Additional context**
This has been there for as long as I remember, it's not a recently introduced bug or anything. Just a minor inconvenience :)

**Comment by baconpaul** [comment]
Yeah there's a particular reason this is annoying to add, but I can overcome it.

Also chatting with dave, I'll probably make the wheel support on switches a global UI option

**Comment by baconpaul** [comment]
Oh ha I added a wheel for the step sequencer and that wheel command can do this also. Just a note to myself.

**Comment by baconpaul** [comment]
Push coming to fix this this morning.
