### ISSUE TITLE
Skin: Supply svg for bg on LFO waveform/step seq

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#1657]
Im not sure if I can do this yet. Please close if you can but Id like to do something like:

<image id="LFO_BACKGROUND" resource="SVG/lfobgframe.svg"/>

Basically, the desire is to be able to draw the background frame around the LFO waveform as well as the step seq. Then you can have a stroke around that part. 

Alternatively, we could just add the ability to stroke the frame. BUT Id also like to control border radius and stuff so .svg seems a bit better approach.

**Comment by baconpaul** [comment]
Yeah that’s not hard now that I have the “optional” SVGs in place (like for the status button and tempo sync). I can add it tonight or tomorrow for you.

**Comment by baconpaul** [comment]
Oh @itsmedavep we don't need this

If you simply don't specify an "lfo.waveform.fill" color the LFO waveform won't fill. It just draws the wave. So then you can use your background for whatever you want

In my dumb skin background I put the word "DERP" on the background as a path and it shines through. I'll spare you the screenshot.

The step sequencer does something different though so I think we may need to think about step sequencer bounds and stuff. But can you try this by adjusting your background and see if that works?

**Comment by baconpaul** [comment]
Ignore me. My comment is correct but will splat when the lfo is movable. I’ll just add the svg!!!

**Comment by baconpaul** [comment]
id is LFO_WAVE_BACKGROUND
size is 280x85
The labels paint right up to the edge ... we may need to give ourselves a bit more room for the graphic but play with it and let me know (once it is merged)

here's the feature in use in my test skin.

<img width="578" alt="Screen Shot 2020-03-22 at 5 16 13 PM" src="https://user-images.githubusercontent.com/13387561/77260908-2d8c0500-6c61-11ea-8682-c8adc7961257.png">
