### ISSUE TITLE
LFO: Step seq trigger lane UX update

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#1659]
As I was playing around with the skin stuff I thought "You know it would be great to have the trigger lane steps activate as I drag across them all not only on mouseUp"

This video should show how it works now. Which may or may not be that useful now that Im thinking about it LOL. 

![step_seq](https://user-images.githubusercontent.com/11078351/77259004-5f46a100-6c4c-11ea-8198-ef012c84bd6c.gif)

**Comment by baconpaul** [comment]
Perfectly clear. May be annoying to fix but if it’s easy I can!

**Comment by itsmedavep** [comment]
Vincy mentioned something about an annoying flashing that was happening when the trigger lane was first introduced.  Perhaps thats something we can fix with skin colors now or something. IDK. just throwing that out there.

**Comment by baconpaul** [comment]
Yeah I saw that. I think it is just that each click toggles your to both a b or some such and the drag was walking through that. Knowing I am in a drag and applying starting point is the state management I will have to do

**Comment by baconpaul** [comment]
Oh i fixed the annoying flash. The drag still not there but the annoying flash bit the dust once i had the vector render correct

**Comment by VincyZed** [comment]
I agree, that's the best solution. Also, before implementing independent trigger lanes, that's exactly what happened. (Just tested in 1.6.3 for instance):

![drag](https://user-images.githubusercontent.com/50145178/83281094-93d35d80-a1a5-11ea-99e3-70cfb81f54ce.gif)

**Comment by VincyZed** [comment]
Would it be possible to delete the steps as we drag instead of only when releasing? Right now it updates as we drag for adding, but not deleting:
![seq](https://user-images.githubusercontent.com/50145178/83594434-320c4e00-a52d-11ea-8742-cec874ed6b76.gif)
I've looked at the code trying to do it myself but have trouble understanding.
Just going to reopen this instead of creating a new issue.
