### ISSUE TITLE
Increase unison-voices for all Surge oscillators to 16

### ISSUE THREAD

**Issue by JackyLigon** [surge-synthesizer/surge#1662]
In a discussion with Zero Green Fox over the weekend, the different unison-voice counts for the Surge oscillators came up:

**Uni Counts**
    Classic        16
    W Table      7
    Window     7
    SH-Noise   16

Just curious, why is it that WT and Window have only 7, while Classic and SH-Noise have 16?
Is it possible, or even desirable, to evolve them, such that they each have a uniform number of 16?

**Comment by baconpaul** [comment]
Notes to self

- the synth has all its data structures set to MAX_UNISON which is 16
- the parameter (ct_osccountWT) has a max of 7 in Parameter.cpp
- Not clear why
