### ISSUE TITLE
Store Patch/Save Tuning in Patch: Text should be gray to match the other text

### ISSUE THREAD

**Issue by JackyLigon** [surge-synthesizer/surge#1666]
Surge-NIGHTLY-2020-03-23-5edda34

![image](https://user-images.githubusercontent.com/59207606/77375569-428d9480-6d44-11ea-80ca-4f1b546ef0cc.png)

**Comment by baconpaul** [comment]
oh yeah thanks. I need to parameterize that.

**Comment by mkruselj** [comment]
I actually added that parameterization in #1788 but forgot to update the SVG for the patch dialog for the dark skin. This is in PR now and then issue can be closed.

**Comment by baconpaul** [comment]
Just merged it
