### ISSUE TITLE
Ardour crashes when loading the plugin, both VST and LV2 versions

### ISSUE THREAD

**Issue by REIS0** [surge-synthesizer/surge#1667]
When I try to load the plugin into Ardour it crashes the whole program, so far this is the only plugin that I get something like this.

* Version 1.6.6 (using the one from kxstudio repositories, since the gui does not load at all I can only use their website for this info)
* VST and LV2 versions
* 64 Bits

1. Open Ardour
2. Add new MIDI track
3. Load the plugin from the plugin manager
4. Ardour stops working

**Expected behavior**
Well to use the plugin without crashing.

**Screenshots**

![Screenshot from 2020-03-23 21-48-42](https://user-images.githubusercontent.com/38042161/77377125-20a70880-6d6a-11ea-84ed-e2666bd14fc4.png)

**Desktop (please complete the following information):**
 - OS: Pop_OS! 19.10
 - Ardour
 - Version 5.12

**Additional context**
I've searched for similar issues like #1157, #1577 and #1619 , but I could not find anything that helped me, since this is only plugin that I have problems in Ardour my guess that it will be related to surge.
Here's the log from Ardour when running from the terminal: https://pastebin.com/XHmgWWRR

**Comment by baconpaul** [comment]
I think surge lv2 and ardour just are not a reliable combo. The lv2 has bugs which I know @jpcima is looking at and unless those are fixed I don’t think it will be usable.

I’m surprised the vst crashes - but I haven’t used the kx version of surge so am not sure what libs are used to make the vst2.

Looking at the paste bin I don’t see it scanning vst just lv2; and there’s a lot of fontconfig errors. Are you sure that you can load the lato font and are you sure you tried to load the vst?

Thanks for the report

**Comment by REIS0** [comment]
I've forgot to put the log when loading the vst version, sorry.
About the font config, I'll check about this lato font, since font config errors are kind "normal" and I did not had any problems like this before, I tend to ignore them. (maybe I should start checking them now)

![image](https://user-images.githubusercontent.com/38042161/77457008-f9951900-6df3-11ea-941b-dcd9c2a071a7.png)

Here's the vst pastebin: https://pastebin.com/rbNBAXs6

**Comment by baconpaul** [comment]
Yeah the large number of font errors makes me wonder if that is the problem 

Here’s the code where we try to load fonts. 

https://github.com/surge-synthesizer/surge/blob/5edda34e7faf571c799e48c504eaeaec6c7c7788/src/linux/RuntimeFontLinux.cpp#L12

Maybe a few careful printfs in there could help find out the crash point? Are you able to build and mod code?

**Comment by REIS0** [comment]
Apparently it is, after trying the solution here https://discourse.ardour.org/t/font-changed-to-ugly-serif-mono/101832/10 the errors are gone and I can load the load plugin without any issues, I'll try to check if is a problem with ardour version from kx repos or ardour overall.

**Comment by baconpaul** [comment]
Ok that’s great! So the lv2 is still buggy but the vst2 I Hope will work for you - it does in other hosts

Have fun making music with surge!
