### ISSUE TITLE
Store patch text entry mangled

### ISSUE THREAD

**Issue by bgins** [surge-synthesizer/surge#1672]
**Describe the bug**
When I open the dialog to store a patch and enter text into any field, instead of text small rectangles appear and the cursor blinks violently. On attempting save the patch, I receive an invalid name error.

**Please let us know your surge version**
* Surge Version: Nightly at b642f3e
* Plugin type: VST2
* Bits: 64

**To Reproduce**
1. Click on the Store button
2. Start typing in any text input
3. Click on OK

**Expected behavior**
I expect to see the text I enter and to be able to save the patch.

**Screenshots**
![store](https://user-images.githubusercontent.com/7957636/77809907-1416fe80-704f-11ea-8e59-951879878e6b.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Host: Bitwig
 - Version: 3.1.3

**Comment by bgins** [comment]
After rebooting, text shows up for me, and I'm able to save. The cursor is still blinking rapidly.

**Comment by mkruselj** [comment]
OK since you have reported that subject issue isn't happening anymore, we'll be closing this one. Cursor blinking is inconsequential, plus it might be an OS-level setting?

**Comment by bgins** [comment]
Yeah, makes sense to close it. The cursor blinking didn't break anything, although I don't recall seeing it elsewhere.

If I see the small rectangles instead of font again, and I can give steps to reproduce, I'll re-open this.
