### ISSUE TITLE
Remember/Save CC mappings

### ISSUE THREAD

**Issue by bit-101010** [surge-synthesizer/surge#1678]
Surge clears out the CC mappings for parameters on reload. For anyone who sets up custom mappings to parameters, these must be re-set every time the synth reloads.

**Possible solutions**
Ideally, the synth should restore the CC mappings when it reloads, just like it restores modulation and parameter data.
Additionally, Surge could have a menu item for saving the current CC mappings that can be loaded into other instances of the synth.

These would be two separate but related features that would improve the synth's utility in a variety of production and performance settings.

**Comment by baconpaul** [comment]
I pushed user settings today also, so this is closed! Enjoy.
