### ISSUE TITLE
lfo.stepseq.disabledstepmarker color not implemented

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1682]
As per subject title :)

**Comment by baconpaul** [comment]
This will be part of my big push this week.

<img width="450" alt="Screen Shot 2020-04-09 at 9 01 11 AM" src="https://user-images.githubusercontent.com/13387561/78897807-bddb8f80-7a40-11ea-977c-bfe94bda815b.png">

<img width="484" alt="Screen Shot 2020-04-09 at 9 01 52 AM" src="https://user-images.githubusercontent.com/13387561/78897818-c633ca80-7a40-11ea-91df-9b45625ebd4f.png">

**Comment by baconpaul** [comment]
next nightly will support those colors.
