### ISSUE TITLE
binaries and plugins have executable stack by default

### ISSUE THREAD

**Issue by dvzrv** [surge-synthesizer/surge#1701]
**Describe the bug**
When building 1.6.6 as a package for Arch Linux I realized that created executables and plugins have [executable stack](https://en.wikipedia.org/wiki/Executable_space_protection). This can be circumvented by adding `-z,noexecstack` to `LDFLAGS`.

**Please let us know your surge version**

* Surge Version: 1.6.6
* Plugin type n/a
* Bits n/a

**To Reproduce**
1. Build the headless binary or plugins
2. Run [namcap](https://wiki.archlinux.org/index.php/Namcap) (Arch specific) on the resulting package or [execstack](https://linux.die.net/man/8/execstack) on the elf files

**Expected behavior**
Executables and plugins don't have executable stack.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Host n/a
 - Version n/a

**Comment by baconpaul** [comment]
So @dvzrv this is easy to add of course but a quick google leads me to understand that on some older architectures where this isn't hardware supported there can be some performance penalties. Am I mis-understanding? (that is entirely possible. It's been a decade or more since I worried about this sort of thing on unixes)

**Comment by dvzrv** [comment]
I think the performance penalty in relation to this is completely negliable.
I'm not even sure the processors in question would be able to reliably run surge (given that the total market share is probably around 0.01%).

**Comment by baconpaul** [comment]
```
paul@ubuntu:~/dev/music/surge-xt$ execstack  ~/.vst3/Surge.vst3/Contents/x86_64-linux/Surge.so 
X /home/paul/.vst3/Surge.vst3/Contents/x86_64-linux/Surge.so
paul@ubuntu:~/dev/music/surge-xt$ execstack ignore/avx/surge-xt_artefacts/Debug/VST3/Surge\ XT.vst3/Contents/x86_64-linux/Surge\ XT.so 
- ignore/avx/surge-xt_artefacts/Debug/VST3/Surge XT.vst3/Contents/x86_64-linux/Surge XT.so
```

next merge accomplishes that difference
