### ISSUE TITLE
Can the VST3 be VST2 drop in compatible?

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1702]
https://forum.cockos.com/showthread.php?p=2269396#post2269396

**Comment by mkruselj** [comment]
Relevant link from the above Reaper forum thread:

http://www.noelborthwick.com/2014/01/22/developer-notes-sonar-x3-vst3-internals/

**Comment by baconpaul** [comment]
yeah i had read that link
basically it says "when you first make your vst3 set the magic number this way"
it seems we didn't 
so i need to ponder if there's anything we can do about that. Perhaps we can have two registered ids for the vst3?

**Comment by mkruselj** [comment]
Hmmm if that wasn't done then it might be too late :( I think you can only have one registered ID per plugin. Buuuut maybe asking in KvR dev subforum might yield some hits?
