### ISSUE TITLE
REAPER hangs when loading Surge (wine)

### ISSUE THREAD

**Issue by The-Foilist** [surge-synthesizer/surge#1704]
**System Specs**
- OS: Ubuntu 19.10 running Wine 5.0 stable
- Host: REAPER (x64) Windows version running in wine
- Surge version 1.6.6, both VST2 and VST3, both 32 and 64-bit

**Describe the bug**
I installed Surge using wine, and everything appeared normal. However, trying to add Surge to a track in Reaper causes Reaper to hang. This happens with both the 32-bit and 64-bit versions, and with both the VST2 and VST3 versions. The Surge effects VST3 plugin works fine.

**To Reproduce**
1. Create a new wine prefix and install Reaper for Windows.
2. Install the Windows version of Surge using the same wine prefix.
3. Attempt to open the Surge plugin with Reaper.

**Additional context**
It works fine if I install the Linux versions and run Reaper in Linux natively, but I prefer to use the wine version of Reaper for compatibility with all of my other plugins. There isn't much info out there on Surge's compatibility with wine, but I did find this: [https://github.com/surge-synthesizer/surge/issues/862](https://github.com/surge-synthesizer/surge/issues/862). I'm wondering if it's a related issue.

**Comment by baconpaul** [comment]
I don't know if any of us even have an environment in which we can debug this. Are there any error messages anywhere (like the wine console?)

One thought, remembering I know nothing at all about wine: Surge looks for data in %PROGRAMDATA% and if it doesn't find it, tries to open a popup window. If your wine environment %PROGRAMDATA% doesn't contain the surge data, or if the installer installed to a %PROGRAMDAATA% different than your runtime, perhaps this could trip you up? But I have no idea how you would even check for that, again, because I've never run wine.

Hope that helps!

**Comment by The-Foilist** [comment]
[Here's the output](https://pastebin.com/V7fLWBdG) from the wine console after trying to load Surge. It looks to me like it could have something to do with Direct3D, though the console often shows similar messages for other programs with GUI that run normally. If so, that would make it wine's problem and not Surge's. I'll check with some wine forums and report back.

**Comment by The-Foilist** [comment]
Okay, I installed [DXVK](https://github.com/doitsujin/dxvk) to see if their implementation of Direct3D would fix it. While it did fix some of the GUI bugs in some of my other plugins, now attempting to run any version of Surge in Reaper results in an immediate crash with [this trace](https://pastebin.com/95DzMake). It's clear that this is on wine's end, since child window rendering doesn't seem to be implemented yet. Unless it's possible to rewrite Surge's GUI to not use child window rendering (or Direct2D in general), I guess I'm SOL.

**Comment by baconpaul** [comment]
We use vstgui which uses direct2d underneath all over the place, yeah. That’s definitely not changing anytime soon on my end (but of course you are welcome to write whatever code you want as long as you object GPL3 rules and we have separated the dsp from the UI for the rack implementation. So you could imagine writing a UI in something other than VSTGUI or a simpler UI for just preset playback like the surgefx module but just for patches. Both are tractable projects if you are really excited to undertake them, but neither is small).

**Comment by Ashvith** [comment]
On the other hand , why don't you try using an **experimental linux build** of REAPER?
[Download page](https://www.reaper.fm/download.php#linux_download)

Here , you can see that there is an "Experimental" Linux build , do try that , and please reply if it works :-)

**Comment by The-Foilist** [comment]
> On the other hand , why don't you try using an **experimental linux build** of REAPER?
> [Download page](https://www.reaper.fm/download.php#linux_download)
> 
> Here , you can see that there is an "Experimental" Linux build , do try that , and please reply if it works :-)

The Linux version of Reaper works fine with Surge. That's not the issue here. I need to use the wine version for compatibility with all my other plugins.

**Comment by Ashvith** [comment]
> > On the other hand , why don't you try using an **experimental linux build** of REAPER?
> > [Download page](https://www.reaper.fm/download.php#linux_download)
> > Here , you can see that there is an "Experimental" Linux build , do try that , and please reply if it works :-)
> 
> The Linux version of Reaper works fine with Surge. That's not the issue here. I need to use the wine version for compatibility with all my other plugins.

I am assuming the fact that you have installed LinVST... did you try these ?
[link here](https://github.com/osxmidi/LinVst#common-problemspossible-fixes)

**Comment by The-Foilist** [comment]
Of course I tried that. LinVST doesn't allow me to use the ARA2 protocol, as it doesn't support VST3 except by wrapping it as a VST2. It also doesn't work well with proprietary Windows VSTs that require external authentication.

**Comment by baconpaul** [comment]
Hi just a ping on this dead thread

We just released 1.9 and it still doesn't work with WINE, but we are working in a port to juce (surge-xt) and a user reported the pre-alpha version of that plugin comes up under wine so later this summer we may have a wine-targeted beta.

**Comment by jarkk0sakkinen** [comment]
Is that pre-alpha version available somewhere? I do have Linux version but this is for using FL Studio in Wine, which I use from time to time.

**Comment by baconpaul** [comment]
Sure! Just check out the branch xt-alpha or look at the repo here releases-xt if you want to grab a binary. Apply a squillion caveats. It is very early and I bet we are a month or two from anything like a beta
