### ISSUE TITLE
Add Stages parameter to Phaser

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1706]
Presently, the phaser in Surge has 4 stages per channel (so 8 total). I could totally see the use for Stages parameter, that would be an integer between 2 and 12, to change the number of allpass filters used by the effect. Of course that means 4-24 stages total, for full stereo.

**Comment by baconpaul** [comment]
This is still a cool idea but I’m gonna knock it out if 17 beta 1

**Comment by mkruselj** [comment]
With #3015 this issue is now finally put to rest. Thank you @amyfurniss for being awesome!
