### ISSUE TITLE
A Flanger

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1708]
PR #1707 pushed the shell and starting implementation of a flanger as we discussed on slack in April 2020.

This issue is for people to put feedback and bugs as they play with the beta I just pushed to the nightly.

- [x] All the 'unimpl' controls need implementation
- [x] the text "flanger" doesn't appear on the menu when you select a flanger
- [ ] saw and s+h modulation modes click because their transition is too harsh
- [x] move sin lfo to a table lookup
- [ ] All the params get attached to smoothers
- [ ] All the 'fixme' points in the code
- [x] auto gains 
   - [ ] doppler modes need a gain boost probably - maybe by a factor of 2?
   - [x] unison modes with high voices need a gain cut perhaps - maybe by 1/root(voices)?
- [x] better than linear delay interp? Reuse sinctable from storage perhaps?
- [x] pop on voice on. Doesn't reset delay lines in suspend maybe?
- [ ] high rate arpeggio pops at voice transition. Smooth the voices weights into lines for one.
- [ ] width in arpeggio mode does nothing
- [x] Feedback is too much. Scale or extend the slider
- [x] gain should be in decibels; and let you drive well into overdrive
- [x] I left mix turned off in the nightly
- [x] move mix to the output section
- [x] renames: Baiscs -> modulation; Voices -> Combs; voice 0 -> base pitch; FB LF Damp -> LF Damp, Stereo Width -> Width, Gain -> Saturation 
- [x] remove specious 'fp' from tooltip for voice 0
- [x] rename 'unison' to 'classic' in modes'
- [x] mode wave ordering: sin, tri, saw, s+h
- [x] chorus / flanger / phaser is order in configuration.xml (alpha)
- [x] some presets
- [x] Get it working in sfx (@tank-trax reports the move to 5.4.7 stops params saving)
- [ ] get it working in surge-rack (along with reverb2)

**Comment by mkruselj** [comment]
Also renames: FB LF Damp -> LF Damp, Stereo Width -> Width, Gain -> Saturation (maybe, not necessary, but it would convey that it's not just linear gain).

**Comment by mkruselj** [comment]
Some other things for the to-do list perhaps:

- [ ] Base Pitch slider should be able to quantize in semitones. Keyboard modifier?
- [ ] Fine-tune the scaling for Feedback slider - cube scaling right now means that there's little to no feedback for about half of the slider, which is not super-useful unfortunately
- [ ] Try to reduce volume as feedback goes up, to keep things under control
- [ ] Same thing for Saturation parameter - it should add gain without increasing the output volume by much, or at all
- [ ] Adding more than 1 comb/voice should not change the loudness at all
- [ ] Currently with all voices going, feedback at 80% or above, dropping the modulation rate actually _increases_ the feedback levels... pretty wild
- [ ] Feedback with just a single comb/voice is super-weak, it should not be. :)

**Comment by mkruselj** [comment]
Testing as of d9458ba:

- [ ] There's a weird glitch in the sound in Tuned modes when the Rate slider is between 0.050...0.300 Hz, you can easily hear this with FB around 75% and all voices and sweeping the Rate slider moderately fast
- [ ] Chords still don't give out any sense of pitch like they do in Flair
- [ ] Gain compensation when going from 1 to 4 voices, is still not as good as it could be because volume still rises as you add more voices. Volume should be consistent (equal power crossfades might help?) no matter how many voices are going
