### ISSUE TITLE
Please add FreeBSD as a system when Surge is available

### ISSUE THREAD

**Issue by yurivict** [surge-synthesizer/surge#1728]
On this page: https://surge-synthesizer.github.io/

The FreeBSD port is now available: https://www.freshports.org/audio/surge-synthesizer-lv2/

Users can install it with the command:
* ```pkg install surge-synthesizer-lv2``` (using a binary package)
* ```cd /usr/ports/audio/surge-synthesizer-lv2 && make install clean``` (build and install from source)

**Comment by baconpaul** [comment]
hey congratulations on getting it working!

We have a couple of places and we will add it yup. I think we should probably touch up https://github.com/surge-synthesizer/surge-synthesizer.github.io/wiki/(Draft)-How-to-install-Surge-on-Linux-from-various-distros, rename it from "Linux" to "Unixes", and make that be linked prominently on the home page with "What about Arch, FreeBSD, and other oses"

We also have a release checklist where we notify people. Is there anything you need other than for us to make a tag for each release?

Finally note there's a list of known bugs with the LV2. Some of your users may get crashes and problems. They are here as issues in the LV2 tag.

**Comment by yurivict** [comment]
Ok!

**Comment by baconpaul** [comment]
![Screen Shot 2020-04-15 at 6 34 48 PM](https://user-images.githubusercontent.com/13387561/79395534-d586ac80-7f47-11ea-8ef7-ea896a11bca2.png)

Home page now looks like that

https://github.com/surge-synthesizer/surge-synthesizer.github.io/wiki/Surge-on-various-unix-like-distributions

that's the document it links to

if you have edits please just reopen the issue.

Thanks!
