### ISSUE TITLE
package-vst3.sh breaks during out-of-source build

### ISSUE THREAD

**Issue by yurivict** [surge-synthesizer/surge#1730]
Here: https://github.com/surge-synthesizer/surge/blob/master/scripts/linux/package-vst3.sh#L18

it assumes that the build path is ```build/```, but it is different when cmake builds the project ```out-of-source```.

To prevent such issues you should always use the cmake's ```install``` instruction to install files.

**Comment by baconpaul** [comment]
Thanks. I'm literally doing that for macOS right now. I've been learning cmake and as I'm sure you see we are about 2 days into it. 

How does one build out of source so I can test? Definitely want to fix that use case.

Appreciated.

**Comment by baconpaul** [comment]
oh right just use a build directory outside your source tree. obvious. 

yeah cmake gives me a variable i should use. fill fix it today or tomorrow. thanks!

**Comment by baconpaul** [comment]
Just an FYI on workflow. I have a PR going in to address a couple of these. The issue will auto-close when it is merged into master if I think I have resolved it. Feel free to re-open if you think there's a problem.

Thanks

**Comment by yurivict** [comment]
Thanks for letting me know!

I'll look forward to the next release.

**Comment by baconpaul** [comment]
i just merged master

our next 'numbered' release will be 1.7 and will be this summer. 

thanks for all your comments. glad we were able to work together better this time.
