### ISSUE TITLE
std::filesystem vs std::experimental::filesystem in C++-17 FreeBSD clang (was: lots of warnings)

### ISSUE THREAD

**Issue by yurivict** [surge-synthesizer/surge#1731]
Here is a full build log: https://people.freebsd.org/~yuri/surge-synthesizer-lv2-build.log

Particularly, ```std::experimental::filesystem``` should be ```std::filesystem```. It can probably be detected with a cmake script if ```std::filesystem``` is available.

Overwritten vtables, missing ```override``` keywords, '&' within '|' - clang is pretty good at finding C++ issues.

**Comment by baconpaul** [comment]
thank you

that "this &&" has upset me since the day this was open sourced. We worked around it (since in 32 bit windows it can actually be null there and on linux it never is) but yeah we should kill that and a few of the others.

(I use clang on mac also and it is indeed great)

**Comment by baconpaul** [comment]
https://stackoverflow.com/questions/54290254/problem-adding-stdfilesystem-to-cmake-project

**Comment by yurivict** [comment]
Additionally, on FreeBSD ```stdc++fs``` isn't needed at all - it just works without it.

**Comment by baconpaul** [comment]
is there a way in cmake I can know if I am in freebsd vs linux? Thank you.

**Comment by yurivict** [comment]
Yes:
```if(${CMAKE_SYSTEM_NAME} MATCHES "FreeBSD|DragonFly")```

**Comment by baconpaul** [comment]
thanks

**Comment by baconpaul** [comment]
I just pushed a change to master which turns on these warnings on macos

```
-Werror=inconsistent-missing-override
-Werror=logical-op-parentheses
-Werror=dynamic-class-memaccess
-Werror=undefined-bool-conversion
```

and, with this compiler

```
paul:~/dev/music/surge$ clang --version
Apple clang version 11.0.3 (clang-1103.0.32.29)
Target: x86_64-apple-darwin19.4.0
```

everything builds on macOS. This should greatly reduce yours.

The std::filesystem thing is a bit more annoying so I'll leave this open and change the subject. Maybe I'll install FreeBSD 12 in parallels.

**Comment by baconpaul** [comment]
just a note to self here. macos10.15 has std::filesystem just like freebsd does in clang version; but since we build for macos older than that we still have to use our hand rolled version so need to be a bit careful when we tackle this last item
