### ISSUE TITLE
OSC FM and Filter Graphics: Cursor change while over clickable area of graphics

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#1739]
Per a Slack convo:

The OSC FM and Filter routing graphics are clickable. Right now though the cursor doesnt change whilst over that nor is there any hover or indications that the area is clickable. 

This is poor for discoverability and leads to folks just kinda stumbling into it finding that out. 

> So, instead of a SVG state based thing I was thinking that VSTGUI maybe provided a mechanism to switch from say cursor: normal to cursor: pointer (the hand) when over those invisible hit test.
No .svg change at all more like:
Cframe -> setCursor -> kCursorHand when over those  hit tests.
https://steinbergmedia.github.io/vst3_doc/vstgui/html/namespace_v_s_t_g_u_i.html#a1abab90c69fe188695d974d72708f609
https://steinbergmedia.github.io/vst3_doc/vstgui/html/class_v_s_t_g_u_i_1_1_c_frame.html#a3f7668c15f67ed4e7b9a27db9b95cb2b
Maybe on mouseEntered
https://steinbergmedia.github.io/vst3_doc/vstgui/html/class_v_s_t_g_u_i_1_1_c_frame.html#a1f4ce6bc02521efb056d04c427c77336

**Comment by itsmedavep** [comment]
![Affordance](https://user-images.githubusercontent.com/11078351/79688082-60e69300-8211-11ea-9c2a-78c31307861e.png)

**Comment by baconpaul** [comment]
Gonna close this as being subsumed by #1752
