### ISSUE TITLE
Surge 1.6.6 crashing FL Studio 20, preset name not showing when selected

### ISSUE THREAD

**Issue by duane2020davis** [surge-synthesizer/surge#1747]
In my case, perhaps this is not occurring with others, the current version Surge 1.6.6 several presets immediately crash FL Studio 20, such as presets within 'Percussion' but not limited to 'Percussion.'  Select the preset and the crash occurs, and in cases select the preset, play a few notes, then the DAW crashes and must be closed.  Also, if a preset is chosen the current preset name never shows in the UI, then select the next preset of different name and that current name does not show yet the previous preset name now shows.  Surge 1.6.6 is unusable in my case.

**Comment by baconpaul** [comment]
@VincyZed you use FL20 right? Do you see this?

@duane2020davis I presume you're on windows 10?

We load all patches in our regtests and I can play all these on my mac; so definitely something in your setup is giving you a different experience than what I have but happy to help find it

does 1.6.5 work differently? Is there any stack shown?

**Comment by duane2020davis** [comment]
Yes, windows 10...

**Comment by VincyZed** [comment]
Will take a look, I have basically the same setup.

**Comment by VincyZed** [comment]
@duane2020davis  As far as I can see, there is no preset called Percussion, but there is category of factory presets called Percussion. Unless I did not understand correctly, I went through the 8 presets under the percussion category and unfortunately did not encounter any crash or anything else mentioned above.

I am running the 64 bit version of FL 20.7 (Release Candidate 2) and Surge 1.6.6 x64 (VST3).

**Comment by baconpaul** [comment]
Is there any way to get a crash log or a stack from FL @VincyZed or @duane2020davis?

**Comment by baconpaul** [comment]
Oh and thanks for looking @VincyZed! Since I rebuild my MacBook I don’t have FL in any of my VMs. Appreciated.

**Comment by VincyZed** [comment]
I believe crash logs would be located at C:\Users\USERNAME\Documents\Image-Line\FL Studio\Support

**Comment by duane2020davis** [comment]
I thank you all for checking on this...Indeed Percussion is the category
and not a specific preset and I should have stated that.  Is it possible
that Comodo is causing issues, or perhaps something else during install
caused an issue?  I bought XO from XLN Audio and sometimes it loads and
sometimes it gives an error, and they are telling me they have never before
seen the error that is occurring. .I just bought Serum and am not having
any issues, nor am I with any other of my plugins other than 'The Riser'
and 'XO.'  All others are doing fine in FL...Since you all could not find
anything then that means it's on my end then, and who knows what could be
causing this...Kind Regards, Duane

**Comment by baconpaul** [comment]
If you have a crash log in the directory @VincyZed sees I'm happy to take a look. I'm not much of a windows person but could maybe at least tell you which component is blowing up? Maybe?

Sorry to not have a better answer

**Comment by duane2020davis** [comment]
Hi Vincent, my apologies for bugging you guys again...Well, I recently
bought Serum so I have been playing with that for a while now...I went
ahead and decided to try with Surge again and loaded it up and yet again
with the FL crashes...I have hundreds of plugins and not one has crashed FL
Studio like Surge does.  The thing is is that it's truly sad because Surge
would be one of my go to plugins if it worked.  Again, this is the only
plugin out of several hundred I have that is causing FL to crash in this
manner...It can be the loading of the first preset that crashes it, or it
can be two later.  And the current preset not showing in the window of the
Surge plugin is still occurring, where the preset name will always be the
previous one I choose.  So, from 'init' I choose 'attacky' and it will not
show anything other than 'init'...I then choose the next preset other than
'attacky' and it will show 'attacky'...As far as the log, I don't see
anything in there of significance, but I could send it so you can look at
it...Just makes zero sense to me why these things are occurring...Billions
Of Best Regards, Duane

**Comment by baconpaul** [comment]
Hi

I fixed a behavior in the plugin which interacted poorly with FL recently in the nightly which caused a display delay. If you are on fl20 and grab the VST3 nightly I suspect you will get a more stable performance. We know the 1.6.6 VST2 and FL are particularly susceptible to some of the fixes we made, although the behavior does vary from machine to machine. 

Since we've discontinued the VST2, though, and fixed the VST3 I think that both the nightly now and the upcoming 1.7 release may be far better for you.

  Paul

**Comment by baconpaul** [comment]
Commit 5d514b9657e93b2a88df507736cf0b5187da1a14 was the one which I think should do it.

**Comment by duane2020davis** [comment]
Hi Paul, great to hear from you again...I will give that a go and
definitely let you all know the results...Take care and thank you very
much...Centillions Of Best Regards, Duane

**Comment by duane2020davis** [comment]
Hi Paul, I installed the most recent nightly build...Looking great so far!
The current chosen preset is showing properly and no crashes thus
far...Take Care, Duane

**Comment by baconpaul** [comment]
Wonderful 
Let me close this then. Please do reopen it if you find more problems
