### ISSUE TITLE
Scene B LFO 2-6 are not fully mapped

### ISSUE THREAD

**Issue by bit-101010** [surge-synthesizer/surge#1748]
In Scene B, the parameters of LFO 2-6 **cannot** be controlled by Velocity, Aftertouch, (the rest of the top row of modulators as well), F. Env, A. Env, nor C1-C8.
All of those controls _can_ modulate LFO1 and the SLFOs. All of this also works correctly in Scene B.

The LFOs can properly modulate each other, and the SLFOs can modulate all LFOs correctly.

I encountered this working on on a rather special dual-scene patch. I want to use a Controller to automate LFO magnitude across multiple Scene B LFOs, but that's impossible in Surge 1.6.6.

**Comment by baconpaul** [comment]
Here's what I see with nightly

- Open init
- set OSC to sine (so you an see your scene)
- put key track in mod mode
- adjust lfo2 rate
- swap to scene b - key track will still be green
- modulate lfo2 deform works
- swap to polyAT
- activate polly at mod
- now you can't modulate 

so if you switch scenes with modulation active it works

also try this
- start surge
- switch to B
- click key track
- mod activate key track
- press LFO2 orange arrow
- you can modulate
- arm poly at for mod
- press LFO3 and modulate rate
- go back to keytrack
- arm keytrack
- you can no longer modulate lfo2

so some state is really wrong in the UI. I think something is not rebuilding properly when we change modulation sources.

**Comment by mkruselj** [comment]
Wow it's really not just a boundary issue, this does look trickier than what it initally sounded like!

**Comment by baconpaul** [comment]
anyway found it. There were a few places where the modulation assembly was using scene[0] vs scene[current_scene] so if you went down one of those rebuild paths you go the 'wrong' lfo.

**Comment by baconpaul** [comment]
OK so now Have it mostly working with the [0] -> [current_scene]. Just writing down my last broken case here (basically using GitHub as a notebook - sorry!)

- start a fresh surge
- change osc to sine
- arm keytrack
- modulate A LFO2 rate
- switch to B
- modulate B LFO 2 rate (works)
- arm poly
- modulate B LFO 3 rate (works)
- modulate B LFO 2 rate (works)
- arm key track - the B LFO2 doesn't show the modulate
- try to modulate B LFO 2 (fails)

So that makes me think that when I switch the modulation source it doesn't rebuild the LFO section in scene B.

**Comment by baconpaul** [comment]
OK and another fix and now an even simpler case

- start a fresh surge
- switch to b
- arm keytrack
- orange arrow LFO2 and modulate rate (works)
- arm poly AT *don't click orange button though*
- LFO2 is not modulatable. "orange-button" ness doesn't carry over
- orange button LFO 3 and you can modulate
- orange button LFO 2 back and now you an modulate there also
- arm key track and LFO2 is not modulatable but
- with key track armed orange button LFO 3 then orange button 2 and you see the 2 modulation

so swapping armed modulator in scene B while not re-orange-buttoning doesn't work
