### ISSUE TITLE
Finish Default Skin Hover Assets

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1752]
OK here's the places we need it still

- [x] 112 - filter config dark
- [x] 113 - AB light
- [x] 114 - key split light
- [x] 117 and 118 - octave dark
- [ ] 119 osc select (may need code)
- [x] 120 ws light
- [x] 121 link light
- [x] 122 osc select dark
- [x] 125 keytrigger
- [x] 126 retrigger
- [x] 132 solo
- [x] 140 link
- [x] 143 filter select
- [x] 144 fx send
- [x] 146 lfo trigger
- [x] 148 store
- [x] 149 jog
- [x] 151 fm
- [x] 152 unipolar
- [x] 160 filter type
- [x] menu
- [x] jog

(finish this list later)

**Comment by mkruselj** [comment]
Hands only show on slider handle, despite the fact that you can drag the slider from any point on it, even if it's not a handle.

I really wonder if this is required on sliders, tho. I know, consistency, but can't say I saw many plugins which change cursors on each and every parameter?

**Comment by baconpaul** [comment]
PW notes to self

light images
offset
553300 on ffeeaa in hov
000000 on ffffff in on

dark images
hoverOn has a gradient
hover alone has a different gradient
sigh
