### ISSUE TITLE
FX preset prev-next buttons don't fully wraparound

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1754]
1. Init patch
2. Immediately press next FX preset button -> first delay preset is loaded
3. Now press prev FX preset button -> nothing happens (expected: last available preset is loaded, which is Vocoder init preset currently - skip the "Off" preset since that's not super-useful)

Presets do wrap around if you load Vocoder init preset then press next FX preset button (it skips the "Off" preset and loads first Delay preset). I'd expect the same in the other direction.

**Comment by baconpaul** [comment]
oh hah you are right i don't back-wrap properly. thanks
