### ISSUE TITLE
Very loud noise produced by this patch

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1756]
**Describe the bug**
Playing a note of this patch makes a REALLY LOUD noise.

**Please let us know your surge version**
Latest nightly, VST3 x64.

**To Reproduce**
Basically what I remember doing is the following:
I added a Reverb2 in FX slot A1. Then, I copied it, pasted it in slot A2, and then removed A1. Everything fine so far. Then I copied A2 and pasted it back in A1 then removed A2. Now it makes this horrendous loud noise. Adding a second Reverb2 and/or removing the first one doesn't fix it.

Here's the patch in question: 
[Bugged patch (VERY LOUD).zip](https://github.com/surge-synthesizer/surge/files/4533891/Bugged.patch.VERY.LOUD.zip)

**Comment by baconpaul** [comment]
OK I can confirm the very loud noise yeah. Lemme look at the internal state!

**Comment by baconpaul** [comment]
Hmm I wonder how you wedged it but this is very useful. FYI the saved patch has totally corrupt values for the R2 params and that blows it up. So at least what I need to do is figure out how you got those bad values! Will look.

**Comment by baconpaul** [comment]
OK I have a fix, both to restoring corrupted patches not blowing the world up; and also copy and paste not allowing you to paste bad float values.
