### ISSUE TITLE
LV2 plug-in sets insert effect to 100% wet when stopping transport in Ardour

### ISSUE THREAD

**Issue by unfa** [surge-synthesizer/surge#1768]
Hi!

I've been reporting issues with the LV2 version of Surge a while back, I've been waiting to see if maybe the issues were ironed out. Seems like I can still reproduce them, so here's one:

Every time I stop tranport in Ardour the reverb I put on Stage Insert gets set to 100% wet.

**Here's a video demonstrating this phenomenon:**

https://youtu.be/ClWulLyfsQ4

Watch as whenever I stop the transport (not start, not move the playhead - only stop!) - the reverb goes back to 100% wet. (Sorry for the missing mouse cursor).

**Details of my environment:**

Manjaro Linux KDE
Ardour 5.12
Surge LV2 version 1.6.6 (64-bit Linux built Feb 27 2020 13:37:04) installed via `yay -S surge-synthesizer-bin` (as the `surge-synthesizer-git`version failes to build for me recently).

Maybe you've already got this sorted out in Git master, and I'm just lagging behind?

**Comment by baconpaul** [comment]
Hi!

The issues aren’t ironed out. @falkTX and @jpcima had a convo over on https://github.com/surge-synthesizer/surge/issues/1619 but the code was truncated there and I don’t know the contents of the solution. I’ve been pinging them - if you are in touch with either perhaps you could also?

That said: we have just gotten the VST3 working at head. With juce6 also building linux vst3s I think there’s a very good chance that it will become an important FOSS option (it is entirely GPL3 code). If you use the latest Carla and surge at master, for instance, we know it works.

**Comment by baconpaul** [comment]
(oh and for clarity: at head the particular issue you mention is fixed; but it is fixed in a way that causes a set of other problems and that's what jp and falk were chatting about)

**Comment by baconpaul** [comment]
Closing this issue, since #4030 is the place we are investing in LV2 going forward. If the JUCE/LV2 port works, it works, and the problems in our hand-port will be gone (or replaced with problems in the JUCE/LV2 port).
