### ISSUE TITLE
6 channel output for the AU

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1793]
Channel 1/2 is A + B
Channel 3/4 is A
Channel 5/6 is B

**Comment by baconpaul** [comment]
OK I just pushed this for the VST3. The AU is harder and the VST2 and LV2 I'm not gonna bother. (I may also not bother with the AU since I don't really think I would use this feature myself :) )

**Comment by baconpaul** [comment]
VST2/3 are in

**Comment by baconpaul** [comment]
Oh that last one is very useful.

**Comment by mkruselj** [comment]
Goodie!

He also said "It's pretty simple, most of the time it's about overriding the Property getters for AU".

But also "I feel the hardest part of anything AU related is documentation. The best way I found so far is to look at the SDKs." 😀

**Comment by baconpaul** [comment]
Ahh now I remember - i had gone down this route

I set the channels to 6 and I couldn't figure out what to set as a layout

So getting 6 channel as an option is fine
but getting it to advertise a layout that lets LPX make that is what I don't know

it is easy to respond to those properties (just implement GetAudioChannelLayout and GetChannelLayoutTags) but what to return from them is where I'm a bit flummoxed

I'm sure we will look in 1.9 tho.

**Comment by baconpaul** [comment]
[au.patch.txt](https://github.com/surge-synthesizer/surge/files/5771411/au.patch.txt)

Anyway that patch makes auval report a 6 channel output option but a layout which is only stereo, which is where I was stuck before, so Logic doesn't show any option other than Stereo

I think implement GetChannelLayoutTags "properly" in our aulayer would do it (right now we just don't do anything so it does the default which is the stereo out).

**Comment by baconpaul** [comment]
And reading the JUCE code it looks like

```
kAudioChannelLayoutTag_DiscreteInOrder | ch
```

is the value of that tag I want.

**Comment by baconpaul** [comment]
SurgeXT at head does this in the AU now. Confirmed in LPX. But I'm not quite sure how to test it - since I don't actually know how to route a 3 stereo output AU in Logic. So keeping this one open even though the plugin shows the right shape

**Comment by baconpaul** [comment]
And XT does this, once I realize how to set it up in logic. Thanks @mkruselj !
