### ISSUE TITLE
More Inputs

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1794]
We have 2 input side chain channels. VST3 lets you have more if you want (AU doesn't). If we had more we could do more audio processing with the VST3.

**Comment by hems** [comment]
you could use a "cross" or non-zero value as a re-trigger for an LFO for instance?

**Comment by baconpaul** [comment]
Yeah that's sort of over in #1795 where we talk about using audio for non-audio things. Agreed it could be interesting.

**Comment by mkruselj** [comment]
I would advise that if something cannot be done consistently across all the supported plugin formats (i.e. can't have the same number of inputs between AU/VST3) that it's better not to do it at all. Sort of punishes the users of the "lesser" plugin implementation, which ain't cool...
