### ISSUE TITLE
Step sequencer end marker < start marker edge case

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1796]
![image](https://user-images.githubusercontent.com/2393720/81115831-a353e380-8f24-11ea-89f9-6fa8b77f573d.png)

Currently Surge behaves weirdly when end marker is behind start marker. In the above image it plays first 3 steps then freezes on the first step AFTER the start marker (second marker).

In my mind, step seq should always play start -> end, so in the above situation it means it should play the part between the two markers in reverse. That is super useful to have, methinks!

**Comment by baconpaul** [comment]
So this is in LfoModulationSource.cpp around like 421. You can se where we go "step++" and "if step > ss->oop_end ) step = ss->loop start

I think what you want is to take that section of the code and make it look like

if( loop_start <= loop_end )
{
  step ++
  if( step > loop_end ) step = loop start
}
else
{
 step --
  if( step < loop_start ) step = loop_end
}

then move the shuffle_id stuff to after that if and you should be good. Test and voila

**Comment by mkruselj** [comment]
Yeah I decided against reverse loop. But I found this all and fixed it just fine! Also fixed some coloring bugs (env triggers would not have disabled step marker color outside of loop range etc.)

**Comment by mkruselj** [comment]
Fixed in PR #1800.
