### ISSUE TITLE
Old problem with latch function creates overtones in prolonged notes

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#1805]
**Describe the bug**
This is an old problem i already heard in 1.5.2 version of surge but it seems it still exist in 1.6.6.

When latching a oscillator so it just stays on it starts to create somekind of overtones after a while that just gets louder and louder as time goes. The only way to stop it is to midi re-trig surge, but the only thing that happends then is that this effect just begins all over again. 

This is hard to hear in a prolonged sawtooth or squarewave bur very easy to hear in FM2 and FM3 and also Sine. 

What is happening here? 

**Please let us know your surge version**
1.5.2
1.6.6
latest nightly build

**To Reproduce**
1. put on "latch"
2. listen to either fm2, fm3 or sine over a period of 8+ minutes and you will start to hear, downsampling?, overtones? i dont know what it is, but it's starting from high frequencies and goes down.

**Expected behavior**
to just sound the same all the time without this behaviour.

**Screenshots**
![edeft](https://user-images.githubusercontent.com/56724286/81154382-222c3900-8f84-11ea-83cc-cf1964eadb45.jpg)

just for visual description where the tones start.

**Desktop (please complete the following information):**
 - OS: [e.g. windows 8.1]
 - OS: [e.g. windows 7]
 - OS: [e.g. windows XP]

 - Host [e.g. FL Studio 5-20]
 - I have also heard this in ableton.

**Additional context**
this will affect anything that uses oscillators in latch mode, eventually it becomes louder and louder.

**SOUND EXAMPLE**
https://we.tl/t-qnvWSs3VJF

**Comment by mkruselj** [comment]
By the way, the shorter issue title the better ;)

**Comment by baconpaul** [comment]
@K0rrid0r are you using the vst3 for 166? I suspect it’s not in the plugin layer but just wanted to ask

**Comment by baconpaul** [comment]
Oh I bet I know what this is

The fm23 and sin oscillators have the form basically

Phase += diff
Output = sin(phase)

But never resets phase. After 8 minutes at 440hz your phase will have looped to 8*60*440 which is 211200. Since phase is a float it only has 8 sig figs so the phase shift gets quantized slowly towards a 0.1 shift making us basically bitcrush the sin and fm23

I bet an if phase > 2pi phase -= 2pi will do it

**Comment by baconpaul** [comment]
OK at head and in rack osc sine seems fine but osc_fm2/3 have this problem

![Screen Shot 2020-05-06 at 8 52 32 AM](https://user-images.githubusercontent.com/13387561/81179385-94e2e780-8f77-11ea-90fb-965c4666a415.png)

and i definitely think it is an overflow of phase from looking at th every simple code.

**Comment by baconpaul** [comment]
OK yeah I've confirmed it is indeed phase overflow and have a fix to the synth. (Rack will lag).

Push coming.

**Comment by baconpaul** [comment]
All fixed up! nightly soon.
