### ISSUE TITLE
Buttons offset

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#1812]
**Describe the bug** 
The buttons are not centered either vertically or horizontally 

This is the most recent build 

![Screenshot_20200506_201539](https://user-images.githubusercontent.com/41337033/81240967-f5edd800-8fd6-11ea-8a6a-8191d8085d59.png)

Here is an example from the last premake build

![Screenshot_20200506_201606](https://user-images.githubusercontent.com/41337033/81241009-1027b600-8fd7-11ea-8e79-6eae7284038b.png)

Also the current button has extra shadow around the corners 

![Screenshot_20200506_200917](https://user-images.githubusercontent.com/41337033/81241060-3d746400-8fd7-11ea-9916-50878ca2dcc2.png)

the previous button looked like

![Screenshot_20200506_201012](https://user-images.githubusercontent.com/41337033/81241101-5e3cb980-8fd7-11ea-8f28-27acf5491611.png)

**Comment by baconpaul** [comment]
bet it is the scalable piggies stuff.

**Comment by baconpaul** [comment]
and the cmake move

**Comment by tank-trax** [comment]
The hover will not appear until a mouse down event. After a mouse down or left click the hover will appear however it is also not aligned

![hover-offset](https://user-images.githubusercontent.com/41337033/81242252-a01b2f00-8fda-11ea-9d16-ca32f59a968c.gif)

**Comment by baconpaul** [comment]
yeah wow everything is just off by a few

**Comment by tank-trax** [comment]
git checkout d5491b46a9ad8495f158ee89bb7616967f7f8047
is OK

**Comment by baconpaul** [comment]
Yeah hover not working may be something else
But d5491b4 is fine and clean build at master is off? There’s literally nothing changed in the default skin in between there and master

**Comment by tank-trax** [comment]
just rebuilt master and it does the same thing, I think I have some clues and looks to be related to the issue https://github.com/surge-synthesizer/surge/issues/1811

When opening Surge on Master the Hover does not work. Clicking on the area for FX does not activate the GUI. Clicking in the Scene activates hover. Clicking in FX does not deactivate. Clicking in Patch Browser Status FX Bypass/Character will deactivate. It is also inconsistent. To get hover on Filter 2 to work it requires a click in it's area, ditto for Filter 1.

**Comment by baconpaul** [comment]
“Does the same thing” as in “misaligns images”? So something between d5491b4 and master is what breaks it?

**Comment by tank-trax** [comment]
it's before 8c375c9

**Comment by tank-trax** [comment]
it starts at fe5717

**Comment by baconpaul** [comment]
Oh damnit yeah i bet its the piggies
If we change the size of the svg we need to take a step and i bet the cmake does it wrong
I’ll look tomorrow. It’s not the fault of that commit - it’s that that commit changes the aboutbox svg size and that blows up with our build
There’s a way you can regenerate then by hand but now I know cmake better i bet i can fix it
Thanks for the hunt!
