### ISSUE TITLE
error: call of overloaded 'abs(float&)' is ambiguous

### ISSUE THREAD

**Issue by mickski56** [surge-synthesizer/surge#1814]
Latest git fails to build on my g++-5.5.0 linux system with the title error.
g++-5.5.0 mostly supports c++17 but abs(float) is defined in `<cmath>` not `<cstdlib>` as it is in later gcc versions.

Adding "#include `<cmath>`" to surge/src/common/dsp/Oscillator.cpp fixes the build for me, but I don't know whether this is the correct solution for surge as a whole.

abs(float) was introduced to surge/src/common/dsp/Oscillator.cpp in commit 1e0876e7bfbb6e087284b471e38361a22529ff12

Hope this helps somewhat.

**Comment by baconpaul** [comment]
Oh thanks yeah that’s the right solution
I’ll do it when I’m fixing another Linux but at head today

**Comment by baconpaul** [comment]
Pushed this include this morning. thanks!
