### ISSUE TITLE
Hover is intermittent - Linux VST3

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#1817]
Using Debian Buster Linux

- hover often requires a mouse down click to enable/activate
- for example, after a preset is selected from the Patch Browser, hover does not initiate

- after clicking down on the GUI hover appears when passing the mouse over those elements that hover

- sometimes it requires two clicks to get it working

here is an [example](https://www.youtube.com/watch?v=1ZfxJOvhru0)

Happens on VST3 in Carla and Bitwig
Does not happen in VST3 in Reaper
Does not happen in VST2 in Reaper, Carla or Bitwig

**Comment by tank-trax** [comment]
I've noticed a few patterns with regards to the hover intermittent behavior.

In the Modulation section when the mouse passes over the menu to select the Waveform LFO Shapes or Trigger mode it often displays an arrow whereas it should be a hand.

When the hand appears while hovering over the Waveform LFO Shapes menu it may have an arrow over the Trigger mode menu. Clicking elements within the Waveform LFO Shapes menu may return a hand when hovering over the Trigger mode menu, occasionally returning an arrow.

![hover-vst3 01](https://user-images.githubusercontent.com/41337033/82249362-a3d27e00-9917-11ea-8816-0192b487a320.gif)

In this animated gif the arrow will become a hand on a click down event, the Trigger mode menu has a hand hovering and the hover will work on the Waveshaper menu. However it appears to lose its focus once it hovers above the Filter option buttons.
![hover-vst3](https://user-images.githubusercontent.com/41337033/82250097-dd57b900-9918-11ea-9d0e-9ae2b5e2e912.gif)

**Comment by tank-trax** [comment]
In this instance the hover works over the Oscillator and Scene sections and loses focus when it passes over the Filter section.

Returning to Waveform LFO Shapes menu the Mouse is now an arrow and will change to a hand on a left click down. Returning to the Oscillator section though the mouse remains a hand. Clicking again on the Waveform LFO Shapes menu and when returning to the Oscillator section mouse appears as an arrow and the hover works, once again losing focus over the Filter section.


![hover-vst3 02](https://user-images.githubusercontent.com/41337033/82251751-c6669600-991b-11ea-8949-4b6702e3f34f.gif)

**Comment by baconpaul** [comment]
So the hands are just because I haven't fully backed out #1752 hand gesture yet. I'll do so.

The hover is more worrying and i see it too. It is, of course, most likely event loop related and we are just not getting the events.

**Comment by bgins** [comment]
I'm also seeing intermittent behavior on Ubuntu 18.04, Bitwig studio, nightly 823b1f2. The hover gets stuck after selecting something:

![hover-stuck](https://user-images.githubusercontent.com/7957636/86154099-769cf200-bab7-11ea-8e40-b1f047f3abf3.gif)

Either selecting another thing or clicking clicking somewhere else on the GUI clears the hover.

**Comment by baconpaul** [comment]
yeah the xcb hover delivery just hangs up on me and I can't figure out why. Forcing it by doing a click seems to start the events again. Do you happen to know a lot about xcb? If so I could definitely use some help. (If not I will keep plugging away at it of course).

**Comment by bgins** [comment]
I'm not familiar with xcb. If I were, I'd be happy to look into it.

**Comment by baconpaul** [comment]
Thanks! Figured it didn't hurt to ask

I think the problem is vstgui and xcb somewhere ... I keep getting close. But this is in the 170 milestone so I really do intend to fix it.

**Comment by baconpaul** [comment]
Just figured it out.

**Comment by bgins** [comment]
That fixed it. Thanks!
