### ISSUE TITLE
Surge should load Init Saw as default patch (+user preference for init patch)

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1824]
... and position the patch browser inside the Init folder, so that clicking prev/next traverses that folder, instead of Bass folder (which is current behavior).

if Init Saw patch is not found or is renamed, fallback to current behavior.

**Comment by baconpaul** [comment]
At  the end of SurgeSynthezier.cpp is a commented out loadPatch(0). that's where you want to make the change, but *don't call loadpatch*.

What you need to do is figure out the patch id for the init saw patch, then set the patchid_queue and call processthreadunsafeops. So you will write code that looks something like this

```
int pid = 0;
for( auto p : storage->patch_list )
{
  if( p->name == "Init Saw" && storage->patch_category[p->category].name == "Init" )
  {
      patchid_queue = pid;
      processThreadunsafeOperations();
     break;
  }
   pid++;
}
```

and that *shoudl* do it

**Comment by mkruselj** [comment]
Well, that was super easy! Also works if it doesn't find things, just falls back to current state. PR coming!

**Comment by mkruselj** [comment]
Reopening because it requires better implementation.

**Comment by baconpaul** [comment]
so calling the unsafe stuff was not the right thing - we just want to set the patched
but if we do that the regtests fail
so that's what i need to figure out

**Comment by baconpaul** [comment]
Lemme debug the regtests on this one today

**Comment by baconpaul** [comment]
The headless change has nothing to do with this change per-se but that the headless (and rack and surge-fx) run in a different threading model than the daws so the background thread reload just cored out.

Fix this by having the init saw selection only active in VST2/3/AU/LV2 compiles.

**Comment by baconpaul** [comment]
I'm gonna push this out of 1.7.0 for now and into 1.7.n

**Comment by mkruselj** [comment]
So actually this issue should be reformulated to: Surge should load Init Saw as default patch, but we should also have a user preference for choosing what should be the default patch Surge will load on init.
