### ISSUE TITLE
FMOscillator.cpp now also calls abs(float)

### ISSUE THREAD

**Issue by mickski56** [surge-synthesizer/surge#1826]
Same build error as in #1814 call of overloaded 'abs(float&)' is ambiguous with older gcc versions on linux.
Fix is the same "#include `<cmath>`" , possibly in Oscillator.h as two files now need it.

**Comment by baconpaul** [comment]
oh thanks!

**Comment by baconpaul** [comment]
Find at da80e8b

**Comment by baconpaul** [comment]
(oh and we are happy to fix these as you report them; but also happy for you to just fire in a pull request with a fix if you want)
