### ISSUE TITLE
Context menu dividers appear at the wrong place

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1835]
**Description:**
Context menu dividers appear at the wrong place.

**Version:**
Running the latest Surge nightly VST3 x64

**Screenshots**
![image](https://user-images.githubusercontent.com/50145178/81446992-cd3a1f80-9149-11ea-8d52-c2e56c3255bc.png)

**Desktop config:**
 - OS: Windows 10
 - Host FL Studio 20.7 pre-4 (x64)

Love the new menu entries and type in value btw :)

**Comment by baconpaul** [comment]
Oh ha that's an easy fix yeah I know exactly what it is
