### ISSUE TITLE
Hosts struggle loading two flavors of surge at once 

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#184]
macOS: Ableton Live 10 Suite behaviour:

1. Load Surge.AU
2. After that, load Surge.VST

Expected result:
You now have Surge.Au + Surge.VST

Current result:
Surge.vst refuses to load.

Then reverse. First load VST, then AU -> expected result is VST+AU, current result is VST loads, AU refuses to load.

After that, you can continue loading Surge.VST Surge.VST Surge.VST and they will load, or you can load Surge.AU Surge.AU Surge.AU and they will load.

**Comment by baconpaul** [comment]
Just checking: Does this work with another vst/au pair and not with surge?

**Comment by baconpaul** [comment]
I also note that bitwig studio on mac refuses to load both the vst2 and the vst3 at the same time (but will load both as long as the other isn't loaded). This is a feature which is unique to surge. I have vst3 and vst2 versions of arturia synths and bitwig is fine loading them both at the same time.

So clearly something actually done by surge here which makes the multi-load wonky.

**Comment by itsmedavep** [comment]
Some further discussion has taken place over in the slack channel. Per @baconpaul suggestion of renaming this issue "mixed plugin flavors in single host crash"


This is a condensed version of that conversation. 

In Cubase 9.5  this also happens but not with mixed technologies. Meaning, Cubase doesn't do AU only VST. 

It seems Cubase will only allow either all VST 2.x instances or all 3.x instances running. I will not allow for VST2 with an instance of VST3 plug in running along side. Same as the rest of the comments in the thread.

**Comment by Kingston1** [comment]
Just checked with Cubase 11 Pro. VST2 and VST3 instances work fine side by side.

**Comment by baconpaul** [comment]
i wonder if i accidentally fixed this one somewhere along the way. Lemme try reaper mac.

**Comment by Kingston1** [comment]
Now checked bitwig macOS, VST2 and VST3 instances work fine side by side also.

**Comment by baconpaul** [comment]
Is Cubase sandboxed?
In reaper I can load all 3 on my mac as I can both on bitwig; but if I turn off plugin sandboxing in bitwig and load the V3 I can then not load the V2. That is, one, not both, are loadable for me in a single process space.

**Comment by Kingston1** [comment]
Sorry for not being clear, this was Cubase 11 Windows. Didn't know about any sandboxing options in those macOS apps.

**Comment by baconpaul** [comment]
Right! Does Cubase win sandbox do you know?

**Comment by Kingston1** [comment]
There's no process level sandboxing available in windows like macOS.

To be perfectly clear, I can instantiate VST2 and VST3 surges in a single Cubase Windows process and attach a debugger with breakpoints. Both plugin instances will fire breakpoints from that same attached process.

**Comment by baconpaul** [comment]
Huh OK then it might just be a macOS thing. I wonder if both are doing that objective c anonymous class name collision thingy you know that i never quite understood.

But we can leave it be then! I'll just close this one.

**Comment by mkruselj** [comment]
Sandboxing on Windows (at least as far as DAWs are concerned) is just running the plugin in a separate process then using IPC to bridge it back to the host... Both Reaper and Bitwig do it on Win too. I think Reason also has something like that.
