### ISSUE TITLE
Add menu list of all existing preset folders to Patch Store

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#1840]
**Is your feature request related to a problem? Please describe.**
This is not really a problem, more like adding something back that existed in a earlier version of surge for ease of use when you maybe have forgotten what the name of your preset folder was and just need to save a preset fast to an already existing folder.

**Describe the solution you'd like**
A drop down menu for current preset folders that has this functionality, picture is 1.5.2. This window is also detached from surge which might be a good thing if you have a long list, I find it handy anyway to be able to move around the patch store window.
![3](https://user-images.githubusercontent.com/56724286/81460100-677a8180-91a3-11ea-9a8c-2cac831228ca.jpg)

Current patch store window is locked over the preset name also.
![6](https://user-images.githubusercontent.com/56724286/81460143-b88a7580-91a3-11ea-8c75-b9db54382cde.jpg)

Here is a solution to just lower the window down abit.
![2](https://user-images.githubusercontent.com/56724286/81460204-2b93ec00-91a4-11ea-9fed-faea3acfce0b.jpg)

**Additional context**
In my context i always took away all the factory presets and 3rd party presets to learn surge and really focus on my own sounds and unpredictability and as well always starting from a Init saw sound which didn't even have it's own folder so my patch store window would never show any name or category so that might be unique to how i worked. a drop down meny is good to have to remind you of your own folders because they might have strange names and are very many etc.

**Comment by baconpaul** [comment]
lowering it is an obvious thing - i can't believe none of us thought of that
the dropdown is a good idea too. like i mentioned on slack none of us have 1.5.2 so any other differences please do open issues.
i'm gonna tag this one 1.7 beta 1 but it may be tricky - have to see what vstgui offers me.

**Comment by baconpaul** [comment]
sigh. vstgui doesn't have a dropdown widget. will ponder.

**Comment by mkruselj** [comment]
It's called COptionMenu, @baconpaul.

https://steinbergmedia.github.io/vst3_doc/vstgui/html/class_v_s_t_g_u_i_1_1_c_option_menu.html

**Comment by baconpaul** [comment]
What is?

**Comment by mkruselj** [comment]
Dropdown menu in VSTGUI, it's COptionMenu, if I'm reading things correctly.

**Comment by baconpaul** [comment]
To help @mkruselj and future readers in this thread we are using the word “dropdown” colloquially to mean the widget that is more precisely called “combobox”. Which vstgui still doesn’t seem to have.

**Comment by mkruselj** [comment]
Yep, learned a lesson here!

**Comment by baconpaul** [comment]
I'm gonna push this out of 1.7.beta1. There's not enough kit in VSTGUi to make it easy. Will get to it in the 1.7 vintages but not at the first release. Sorry!

**Comment by tank-trax** [comment]
I like the idea of the drop down menu for Category and also think being able to move the Patch Store would be useful. I wonder if dumping VSTGUI for Patch Store and using the native browsers as is being done with the FX presets would not provide an easier solution, or one with less hurdles to surmount.

**Comment by K0rrid0r** [comment]
It really makes finding your folders and go directly into them efficient and fast. I had to leave this way of working with the new builds a bit, but i hope for a smart solution eventually since this just allow more fast access.

**Comment by baconpaul** [comment]
So an easy way to do this is have a typein like now but also have a button which shows you all the user categories you have which will fill it. A full combo box is hard but a ‘populate this please’ menu is pretty easy i think. (I think)

**Comment by mkruselj** [comment]
I kinda think that the patch browser will make this issue obsolete. Storing patches would just be done in the currently selected patch browser's folder.

**Comment by mkruselj** [comment]
And I still think that patch browser with all its possible interactions overrules this issue, so I'm closing it in favor of #2359!

**Comment by baconpaul** [comment]
I noodled with this a bit

https://forum.juce.com/t/type-ahead-dropdown-box/5600/8 has useful info

the juce combo box isn't styled enough so we either have to do something like above or some look and feel surgery

**Comment by mkruselj** [comment]
I still very much think that we don't need this at all. Once we have patch browser implemented, the currently opened folder in the tree would be the one in which user patch will be stored.

**Comment by baconpaul** [comment]
won't we still have the store dialog? I think we will!

**Comment by mkruselj** [comment]
Yeah we will, but we should also have the whole folder tree in the patch browser, and user would be able to select which folder to view, and last selected folder would be where the patch would be stored (except if factory folder was selected).

This is pretty straightforward, I think?

**Comment by baconpaul** [comment]
A combo box is not right agree. I was thinking the category would have typeahead completion which is basically what that juce fragment shows

what’s your imagined workflow for i load init sine and want to save in an existing category of mine? That’s the workflow typeahead would make easier

**Comment by mkruselj** [comment]
Yeah I guess that's the one singular case where it'd make sense. but I kinda think with full-blown tagging we don't need the Category field in patch store dialog - categories would be tags that get stored in the patch. New workflow.

**Comment by baconpaul** [comment]
ok i'll leave this undone for now but lets leave it in the milestone. we will probably want a similar typeahead for tags. also need to figure out exactly how much change to impose.

**Comment by mkruselj** [comment]
Tags should probably not be typed in (except when creating a new one), but use a tag cloud coupled with some drag&drop action. And/or a dropdown menu. But yeah patch browser - separate issue and discussion 🙂

**Comment by baconpaul** [comment]
or a typeahead widget :)

sounds like we might have added a bunch of clicks to save a patch. that's what we want to think about carefully (and i bet when we do we will want a widget 'like' this for some of the components)

**Comment by baconpaul** [comment]
![WithRealCats](https://user-images.githubusercontent.com/13387561/135629786-2c5b7217-8cb5-48e1-8f06-bcb0afd9dccd.gif)
