### ISSUE TITLE
Letter "-" on the qwerty keyboard is resizing surge untill it reaches 50% size

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#1841]
**Describe the bug**
I just noticed in Surge x64 VST3 Nightly 67e750f (and also the VST2) that the letter "-" is resizing the surge window to be smaller and smaller, you can click four times untill surge hits 50% in size.

**Please let us know your surge version**
Surge x64 VST3 Nightly 67e750f 

**To Reproduce**
probably just click "-"

**Expected behavior**
nothing except a qwerty midi note, like normal

**Screenshots**
at click 4 it reaches maximum small size of 50%
![7](https://user-images.githubusercontent.com/56724286/81460928-bd055d00-91a8-11ea-8fa8-179ff7c12897.jpg)

This buttom for clarification
![8](https://user-images.githubusercontent.com/56724286/81460980-1d949a00-91a9-11ea-9bcb-add30583608c.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. windows 8.1]
 - FL 20.6 (x64)

**Additional context**
Surge x64 VST3, is the only version that works with changing presets and qwerty in FL fully in VST3 mode therefore i found this.

**Comment by baconpaul** [comment]
oh ha yeah that's there on purpose but we took out most of the keyboard bindings for exactly this reason. i'll make this one an option you can turn off too.

**Comment by baconpaul** [comment]
any consolation: + will make it bigger again. chuckle.

**Comment by K0rrid0r** [comment]
Ah ok. i guess all my QWERTY playing is revealing new bugs lol.. 

letter "-" is corresponding to letter "p" in FL studio QWERTY, "p" is one octave higher then "-"

please have the function turned off at first so a user can choose to turn it on rather then having it on from begining. you are free to disagree :)

**Comment by baconpaul** [comment]
yeah sure. the keybindings cause us only problems.

**Comment by baconpaul** [comment]
i will probably just remove them tbh. they cause us only headaches.

**Comment by mkruselj** [comment]
> Ah ok. i guess all my QWERTY playing is revealing new bugs lol..

Yeah it's not a bug tho.
