### ISSUE TITLE
Ctrl+drag always starts from default value

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1844]
Regardless of where the slider actually is, it seems that Ctrl+drag always first executes Ctrl+click, which defaults the control. This can be quite inconvenient, for example if the volume slider was at a low value, and its default value is 0 dB.

We already have defaulting controls on double-click, so Ctrl+click should just do nothing here.

**Comment by mkruselj** [comment]
Here's another tidbit of info: this only happens if you hold Ctrl first, THEN press mouse and drag. If you press mouse to drag and then add Ctrl, it doesn't jump (I guess makes sense, since the drag has already started?).

**Comment by baconpaul** [comment]
Yeah makes sense because drag starts with click and if Ctrl-click centers then...

**Comment by mkruselj** [comment]
One-liner change to fix it, amazing!
