### ISSUE TITLE
Surge LV2 UI does not scale with the host

### ISSUE THREAD

**Issue by falkTX** [surge-synthesizer/surge#1846]
When an LV2 plugin host runs in a high-dpi screen or is set to render at a custom scale, Surge LV2 UI does not scale to match.
See https://github.com/falkTX/Carla/issues/1121

This happens in any surge version.
For LV2, there is a UI property to inform the plugin about the host GUI scale.
Surge should be reading this information and automatically set UI scale to match.

PS:
Not sure about VST2 or VST3, might be the same also happens there.
Focusing on LV2 first, then we can see the rest.
I will try to fix this myself, as a way to ensure Carla is implementing this properly too.
I have opened the ticket just to get some visibility on the topic, and I might need some help soon :)

**Comment by baconpaul** [comment]
The HDPI support is mostly in DisplayInfo/getBackingStore which is what upscales us. Don't know anything about linux apis to find out our density but you can see that plus the zoom handler in SurgeGUIEditor is basically where it is. You can see there's handling of physicalzoomfactor as well in surgeguieditor around like 3730 to help compensate for some vstgui bugs. that's probably where you want to read your property to increase zoom.

Note the LV2 still has loads of bugs with parameters and basically doesn't work in ardour. Those are still open! So just when you test don't expect consistent behavior of the plugin.

**Comment by falkTX** [comment]
Yeah I know of the other issues, sorry been a lot busy with work.
Today I thought to look into Carla UI issues, this one is relevant since I need an opensource plugin that can handle scaling and supports multiple formats. So surge is quite the nice fit.
I will look into the other LV2 issues another day, if that is okay.

Anyway, is there a way to force a specific UI scale before creating the UI? so it starts up with that?
I think if the host informs the plugin UI what scaling to use, the plugin should use that instead of trying to guess the desktop one (which sometimes is not correct, could be also that host is running at a custom scale set by the user)

**Comment by baconpaul** [comment]
Yeah what I would do if I had to was (presuming you have a function called “getExtraScale()” which returns 1, 2, etc...)

You can probably do it all in the zoom callback per host

https://github.com/surge-synthesizer/surge/blob/1aa548947e441364448812e7da984b7b53eb9254/src/lv2/SurgeLv2Ui.cpp#L150

If you need to intervene earlier than that, In surgeguieditor.cpp SetZoom with an #ifdef TARGET_LV2 could do it also

But i think the lv2 local one will let you do it

**Comment by baconpaul** [comment]
Specifically if you replace all the e->getZoomFactor() / 100 with fzf in that function; then scale fzf by your lv2ui scale; it all works.

**Comment by falkTX** [comment]
that seems to be what I need. will try that, thanks!
