### ISSUE TITLE
Change certain strings based on context

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1848]
For example, LFO Phase/Shuffle parameter - it should be just called Phase for all LFO modes except Step Seq, otherwise it should be called Shuffle.

Another thing, currently pitch-based parameters (Pitch, Sync, Formant) don't show any unit at all when it should be semitones, but this should change between "semitones" if microtuning is not loaded and "keys" or "pitches" (I'm more inclined towards the former) if microtuning is loaded.

In fact, it looks like those two things are the only of this sort which would need a context-sensitive update.

Also tightly related to #1201!

**Comment by baconpaul** [comment]
The primary problem @mkruselj ran into trying this first was that Parameter doesn’t have a reference to its associated storage (but does vice versa). Adding this in carefully and making sure it is set will let us do this. Or maybe doing some gross hack. But much bigger change than just an if alas.

**Comment by mkruselj** [comment]
Another thing to tuck into this issue is changing "semitones" unit in pitch-based parameters to "keys", based on microtuning being loaded or not.

**Comment by renatoviana12** [comment]
Hey, can I pick this up?

**Comment by baconpaul** [comment]
you mean pick up the issue to code? Or pick up the binary with the change?

This issue is a bit hairy as a first issue but happy to describe how to do it if you are a C++ dev looking to join the project!

**Comment by renatoviana12** [comment]
Pick up the issue, I would love to join the project :)

**Comment by baconpaul** [comment]
Cool! Welcome. You should also join our slack then if you want to hang with the team.

The basic problem is the data structure which knows if we are tuned (SurgeStorage) is "above" the data structure which makes the string (Parameter) in the hierarchy. So we need to get a reference to the storage object into the parameter function which makes the string.

There's a lot of ways to do it but I think the safest is this:

0. Make sure you can build and run the synth. A good test is to edit one of the strings in CAboutBox.cpp to be something funny, build, run in your DAW, do help/about, and see if you see it. Also check out doc/git-howto.md on how we use git. If you have this running so you can make and see changes in a cycle then:

1. src/common/Parameter.h add a forward decl of SurgeStorage. You can't include surge storage.h there it will cycle.
2. Parameter.h add a SurgeStorage *s = nullptr argument to get_display
3. src/common/Parameter.cpp include SurgeStorage.h and where there is semitones do an `if( s && ! s->isStandardTuning ) "keys" : "semitones"` at the right place
4. src/common/gui/SurgeGUIEditor.cpp find the places where we call get_display and add add the reference (and the defaults for external and ef I suppose also).
5. test, push, etc...

And welcome! Glad to have devs join.

**Comment by renatoviana12** [comment]
I'll get the proper tooling and get to it. I'm also joining the team slack rn

**Comment by baconpaul** [comment]
I went a different approach on this since it showed up more than once. Pushing the pattern today.
