### ISSUE TITLE
surge cant see/find .scl files in appropriate folder

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#1853]
**Describe the bug**
surge cant see or find the .scl files in the appropiate folder where they actually are. 

**Please let us know your surge version**
Surge-NIGHTLY-2020-05-09-9569d16

* Surge Version: 
* Plugin type (VST2, VST3)
* Bits (32/64)

**To Reproduce**
try to find .scl files via the meny.

**Expected behavior**
to find the .scl files in the folder 

**Screenshots**
![13](https://user-images.githubusercontent.com/56724286/81487907-a3c0e700-9262-11ea-8b5f-006578c824ee.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. windows 8.1]
 - Host (FL 20.6 and FL 10)

**Comment by baconpaul** [comment]
Almost Definitely https://github.com/surge-synthesizer/surge/commit/df54d24c890f15142abb8085494e53d1be52397a

@mkruselj just need to do a pr to revert that filter change

**Comment by baconpaul** [comment]
I think the temporary fix is to change

```
 ofn.lpstrFilter = filterSuffix.c_str();
```

back to 

```
 ofn.lpstrFilter = NULL;
```

while we figure out how to debug

**Comment by mkruselj** [comment]
[stackoverflow to the rescue!](https://stackoverflow.com/questions/34201213/c-lpstr-and-string-trouble-with-zero-terminated-strings)

Working on it!
