### ISSUE TITLE
The Mysterious DOT oscillator

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1854]
In 'src/todo' there was most of an oscillator called DOTWAVE

in branch "baconpaul/wtf-is-dot" I got it to compile even though it generates garbage still

Looks like it was written before the BitBlitOscillator was a base class, and before the sinctables were restructured

but I bet i can make it work.

So put this issue in so I remember.

@kurasu if you still read anything over here, any ideas on what the oscillator was supposed to be would help, beyond what i see in the source.

**Comment by mkruselj** [comment]
I am also extremely curious about this oscillator, count me in for wanting to hear more info about the DSP involved, @kurasu!

**Comment by baconpaul** [comment]
So my analysis is

1: There' two internal wavetables; a square-like and triangle-like one
2. There's some basic phase distortion to accelerate or decelerate
3. There's a prior version fo the formant shifts and convolution in the wavetable and super oscillator

so nothing that exciting. Glad I spent an hour or two looking but gonna close this.
