### ISSUE TITLE
Version numbers in nightly .deb package

### ISSUE THREAD

**Issue by elcalenx** [surge-synthesizer/surge#1859]
There is a very minor and mostly cosmetic issue with .deb releases that I've been noticing with the nightly builds for a while already: if I install a newer nightly version over a stable version, using dpkg, on Debian, it gives me a warning that I'm *downgrading* Surge. Which is obviously not the case. It still installs and works fine, it's merely a harmless but incorrect warning.

I don't have experience building .deb packages myself, and I have no idea how their versioning works, but it appears that for some reason it's interpreting the version of the nightly builds as beginning with 0. For instance, when I installed the latest nightly, I got the following output:

Preparing to unpack surge-linux-x64-NIGHTLY-2020-05-10-83299a7.deb ...
Unpacking surge (0.NIGHTLY-2020-05-10-83299a7) over (0.NIGHTLY-2020-05-09-5d514b9) ...

So if I were to install it over, say, version 1.6.6, it'd naturally assume that version 0 is older than version 1... Like I said, the warning is harmless, but I figured I ought to let you know in case you weren't aware of this...

**Comment by baconpaul** [comment]
Thanks

In #1771 I am slowly making our cmake implementation make more consistent version numbers for all our assets and points so let me link this here. We'll get this before we get 1.7 beta 1 out.
