### ISSUE TITLE
Improve UX with file open dialogs

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1864]
Currently SCL/KBM actions open in their associated factory folder, which is great for first-time microtuning users since it guarantees that something loadable will show up.

However for people with their own tuning libraries this might not be best. So it would be useful to actually remember last used path to load a valid SCL/KBM (or indeed wavetable) file. We can store these paths in user-configuration.xml, one entry for each file type, then when calling the dialog, first check if the path exists in user-configuration (or if it exists, is it still valid), otherwise fallback to factory folder.

Excerpt from Slack:

![image](https://user-images.githubusercontent.com/2393720/81584912-b0a12000-93b3-11ea-9d6e-16812979c87d.png)

**Comment by baconpaul** [comment]
I wanna replace this code path with the Juce file dialog. Pushing to XT.
