### ISSUE TITLE
RMB context menu tweaks

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1866]
![image](https://user-images.githubusercontent.com/2393720/81619759-9b93b380-93ea-11ea-8e08-519f456a73c3.png)

Vocoder menu should only show multiples of 4 here.

Any temposyncable parameter should show all the values in the context menu, preferably separated in submenus by normal, triplet and dotteds.

Right-clicking the keytrack root key, split key and poly shows huge menus. For keytrack and split key they should show submenus per octave, and poly limit should maybe be a special case where it's an integer parameter, but it gets a typein dialog anyways?

**Comment by baconpaul** [comment]
Type in for pb range also

**Comment by baconpaul** [comment]
i have a lot of this put together in `baconpaul/rmb-context` but @mkruselj it's got a good chance to conflict with your changes. i've resolved a scullion git conflicts in my life so i'm gonna hold until you push your stuff and then will do the merge and resolve after that.

**Comment by baconpaul** [comment]
Closing this since it's all in prod now.
