### ISSUE TITLE
No VST3 context menu options for assignable controls

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1867]
Pretty self-explanatory, I've wanted a couple of times to use the "Create Automation" option in FL on the assignable controls, but those have no VST3 context menus options:

![image](https://user-images.githubusercontent.com/50145178/81620557-31631a80-93ba-11ea-896e-453c5a1f1cb7.png)

**Comment by baconpaul** [comment]
bit of an annoying code restructure and interacts with the param id mapping to control id mapping nonsense so i'll leave it until after i remap all the ids for id expansion, but yeah easy to add in the 17 beta
