### ISSUE TITLE
Small bugs and enhancements with the mod amount white text box

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1873]
When modulation is applied and moving the blue slider of Unison Detune, it shows a relative value instead of an absolute value, like it does on other absolute controls, such as FM Depth (in dB):

![image](https://user-images.githubusercontent.com/50145178/81759542-ff71b700-9492-11ea-9a90-f6599cb8ddc7.png)

This should probably display something like 60 cents or so..

Also, for controls ranging from -1.00 to 1.00, maybe showing the mod amount in % instead of the direct multiplier applied would make more sense and would be easier to understand for the end user? Something like this:

![image](https://user-images.githubusercontent.com/50145178/81759675-58414f80-9493-11ea-90e0-fbed82ff50ff.png)

In the current nightly it shows 0.271 .

**Comment by mkruselj** [comment]
Yeah all the units and scaling of mod amounts needs an overhaul. #1071 is where we talk about all that.

**Comment by baconpaul** [comment]
![LICEcap](https://user-images.githubusercontent.com/13387561/81816345-32e72c80-94f9-11ea-84e6-f12ea0ad2b42.gif)

from @JackyLigon
