### ISSUE TITLE
Surge f2c096b VST3 is shuffling midi trigs

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#1874]
**Describe the bug**
When sending quantized un shuffled midi trigs to Surge f2c096b VST3 the midi messages are being shuffled (swing/shuffling effect)

**Please let us know your surge version**
Surge f2c096b VST3

* Surge Version: 
* Plugin type (VST3)
* Bits (32) <--------------- ONLY

**To Reproduce**
put notes after eachother like this.
![15](https://user-images.githubusercontent.com/56724286/81774238-666e8a80-94ea-11ea-8540-4802f5cb61b6.jpg)

**Expected behavior**
no shuffling to be heard

**Desktop (please complete the following information):**
heard in both of these:
FL Studio 20.6
FL Studio 10

**Sound Example**
https://we.tl/t-fCsiHXzO7E

![16](https://user-images.githubusercontent.com/56724286/81786036-6dec5e80-94ff-11ea-8bad-32314d953360.jpg)

**Comment by mkruselj** [comment]
Cannot confirm here in FL20.6 with VST3 or VST2.

**Comment by baconpaul** [comment]
@K0rrid0r I know you had some other problems this morning which went away on a restart. News on this one?

**Comment by VincyZed** [comment]
Cannot confirm in FL 20.7 VST3 either.

**Comment by K0rrid0r** [comment]
update on this problem from now.

FL 20.6 32 bit
VST3 32-bit Surge-NIGHTLY-2020-05-13-624fd37    shuffling, no glitch
VST3 64-bit Surge-NIGHTLY-2020-05-13-624fd37    shuffling, no glitch

FL 20.6 64 bit
VST3 32-bit cant be tested or opened, expected
VST3 64-bit Surge-NIGHTLY-2020-05-13-624fd37    shuffling, no glitch

FL 10 (32 bit only)
VST3 32-bit Surge-NIGHTLY-2020-05-13-624fd37    glitch only
VST3 64-bit Surge-NIGHTLY-2020-05-13-624fd37    works fine

**Comment by K0rrid0r** [comment]
this seems to be related to my computer and cache issues, maybe. will look into it asap

**Comment by K0rrid0r** [comment]
FL studio automaticly clicked on "use fixed size buffers" when opening VST3 plugins. THIS was the problem. I will close this issue now.

**Comment by baconpaul** [comment]
Ahh great! I’m really glad you found it
