### ISSUE TITLE
error message after loading .scl and you try to type in value on any slider

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#1875]
**Describe the bug**
First surge works fine and values can be typed in. But once i load in .scl files and try to type in a value on a slider i get two different error mesages.

**Please let us know your surge version**
This only appeard in FL Studio 10 and on VST2, but on the newest compiled Nightly f2c096b
Surge-NIGHTLY-2020-05-12-f2c096b-Setup-x86

* Surge Version: 
* Plugin type (VST2)
* Bits (32)

**Expected behavior**
no error message when typeing new values after loading in .scl

**Screenshots**
![error 2](https://user-images.githubusercontent.com/56724286/81775171-9028b100-94ec-11ea-98e9-e78e8d13a6e0.jpg)
![error](https://user-images.githubusercontent.com/56724286/81775172-9028b100-94ec-11ea-9683-9e31642ce623.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. windows 8.1]

**Comment by mkruselj** [comment]
I've seen this pop up at random times, not even after loading SCL, so there is no consistent reproduction case for this one...

**Comment by K0rrid0r** [comment]
i have never seen this message in surge ever untill this nightly. but also in this nightly was the first time type in numbers was added, so its a new problem i guess.

**Comment by baconpaul** [comment]
Oh man that’s basically a nasty internal bug reading a null. Means some internal state is wrong in the c++. Do you get any sort of crash log? On Mac when that happens I can click report and get a super useful (to me) crash reporr

**Comment by baconpaul** [comment]
Oh and yeah there’s all sorts of state management with typins that if I get it wrong will give exactly this error.

**Comment by K0rrid0r** [comment]
interesting! @baconpaul so im sure you will find it :) im going to try and reproduce the error now and se if i can geta  crash report, from somewear. not sure i will

**Comment by baconpaul** [comment]
one theory is: if you do something to the ui (like arm a modulator) with the typein visible I bet I end up in a wierd state. I didn’t test all those combinations fully yet.

**Comment by baconpaul** [comment]
Yeah this is exactly what I thought
If you do some action to rebuild the UI (like drag in a scl file) with the typein open, the next typein will crash. Can repro it on my mac too. Fix shortly. Nice find - thanks!

**Comment by baconpaul** [comment]
And found it. One line fix. Pushing now. Thanks!
