### ISSUE TITLE
Popup not wide enough for certain parameters and assignments

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1885]
![image](https://user-images.githubusercontent.com/2393720/81944707-6ca15b80-95fd-11ea-9438-e74718c44a85.png)

![image](https://user-images.githubusercontent.com/2393720/81944717-7034e280-95fd-11ea-9b52-5a41f2760517.png)

Would be great to make the popup dynamically sized, although that's tricky I suppose. If that's not happening, then just make it even wider, however uncool looking that might be?

**Comment by baconpaul** [comment]
It wasn't that hard to dynamically size the infowindow. Couldn't use the exact string width for a silly reason but used a good heuristic. Pushing soon if it builds in CI.

**Comment by mkruselj** [comment]
There are still some cases where this doesn't quite work well.

![image](https://user-images.githubusercontent.com/2393720/84954708-33757300-b0f6-11ea-9308-cef361fb47b6.png)

![image](https://user-images.githubusercontent.com/2393720/84954774-54d65f00-b0f6-11ea-8eea-d274e9fec2e1.png)

**Comment by baconpaul** [comment]
Right so it’s all a bit empirical because I don’t quite have string-width access when I set the box. I’ll up my factor by a smidge for that case
