### ISSUE TITLE
Step sequencer enhancements

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1887]
(edits by @baconpaul to keep everything up top)

- [x] Alt+drag in step seq should quantize to 1/scale degrees
- [x] Show the value. I don't think we need to show the parameter name in this popup, it should just be a small single line popup that says "Step x: <value>"
- [x] move to vector ui
- [ ] (maybe) rmb and typein a step value
- [x] give the gui a chance at idle time so we can do values on wheel
- [x] Hover states for prev/next triangle buttons
- [x] Antialiasing for prev/next triangles
- [x] perhaps draw the curve to show the line

Example from a Kontakt instrument I did:

![quant](https://user-images.githubusercontent.com/2393720/81947217-94de8980-9600-11ea-8dcd-cbed62246831.gif)

**Comment by K0rrid0r** [comment]
Ive been thinking about this as Shift is activating the step mode what is the purpose of Ctrl excpet for reset? The mouse can reset by right click so in that case activating the steps with Shift + Ctrl should do a slow scroll between the semitone steps as it is quite hard to set a chosen step with the mouse as of now. Thats what ive experienced.

And maybe also an "expert mode" should allow for 24 snapped steps hence the above slow scroll feature.

**Comment by baconpaul** [comment]
There was some key combo which set you to 1/(2 scale length) and since we wrote this issue it really is always (scale length) that is the divisor so the Alt thing is gone

**Comment by mkruselj** [comment]
Shift+Alt does 2x the scale length (so, 24 by default).

**Comment by K0rrid0r** [comment]
but how about a slow scroll function, its hard to fetch a certain snap with the mouse, one has to be really precise. or im missing something

**Comment by baconpaul** [comment]
I just pushed a version where mouse wheel and shift-mouse-wheel both work. Will have types soon.

**Comment by mkruselj** [comment]
- [ ] Vector step seq: mousewheel adjusting the step can overshoot the boundary:

![image](https://user-images.githubusercontent.com/2393720/82739808-22c61d00-9d43-11ea-9291-fd59b00bb590.png)

- [ ] Hover and pressed states for prev/next triangle buttons
