### ISSUE TITLE
Preset menu checkmark not present on init

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1896]
When you open Surge it loads its "init" state. When you now open the preset menu, you cannot see the checkmark on any category or preset (because there is no preset called just "init" - this seems closely related to issue #1814).

Now if you try to store a new patch, it does show its name in the menu, but doesn't add checkmark next to it, which makes no sense because the patch is already loaded.

BTW, the currently selected category doesn't get repositioned in the menu at all in this case either, so if you do this:

1. load Surge
2. save patch immediately under a different name
3. click prev/next preset

...instead of going prev/next from the place where you have just saved the patch, it goes back to Bass folder first preset, Attacky.

Obviously this should all be more predictable, which is why I think we should start with an already existing init preset, so that both checkmarks and category focus are correct.

**Comment by baconpaul** [comment]
This is related to #1824 also and we will have to fix both at the same time, so knocking this out of 1.7.b1 for now.

**Comment by baconpaul** [comment]
Oh I fixed this with my default push thingy last night also. Closing.
