### ISSUE TITLE
Default author

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1898]
We should be able to set who the default author is when storing patches. Get this in userconfig.xml and refer to that always when showing Store Patch dialog. User can of course override in the dialog, but the field would be autopopulated every time based on what's saved as author in userconfig.

**Comment by VincyZed** [comment]
That's a great idea!

**Comment by baconpaul** [comment]
Good idea! Also you could set the value based on the last value you used when you saved.

**Comment by mkruselj** [comment]
Maybe? Not sure I'm a fan of that, I'd rather it be explicitly set, with possibility to change on individual preset basis. I can certainly be overruled on this one, though :)

**Comment by baconpaul** [comment]
OK so here's how I would do it then

1. You need to add a menu *somewhere* that lets you set it. The lambda body looks something like this

```
std::string s = Surge::Storage::UserDefaults::getUserDefaultValue( this->synth->storage, "defaultPatchAuthor", "your name" );
char txt[256];
strncpy( txt, s.c_str(), 256 );
spawn_miniedit_text( txt, 256 );
Surge::Storage::UserDefaults::setUserValue( this->synth->storage, "defaultPatchAuthor", txt );
```

that's the bit inside the {} and in an addCallbackMenu

2. in the tag_store block of SurgeGuiEditor around line 3300 I would do this

```
   string s = Surge::Storage::UserDefaults::getUserDefaultValue( this->synth->storage, "defaultPatchAuthor", "your name" );
   string comm = p.comments;
   if( p.author != s )
      comm += std::string( " (original author " ) + p.author + ( " )" );
  patchCreator->setText( s.c_str() );
  patchComment->setText( comm.c_str() )
```

this means that if you load a patch by baconpaul and save it as you the comment gets the original author modified (which of course you can remove).
