### ISSUE TITLE
Make it so 1.6.6 and 1.7 can co-exist

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1904]
With #1777 closed some folks have asked to make it so the 1.7 VST3 and the 1.6.6 VST2 can co-exist on a system

The dlls are fine. To do this though we need to worry about the resource data.

I propose we make the `%PROGRAMDATA%/Surge` into `%PROGRAMDATA%/Surge_17` in the installer and search paths to do this.

I considered renaming the plugin also but don't want to break saved sessions which are using VST3 today.

**Comment by mkruselj** [comment]
So all the patches etc. would be duplicated? I'm not sure that particular thing (duplicating patches) is really necessary, though.

**Comment by baconpaul** [comment]
The problem is 17 will have patches and configuration that don’t load in 166. That’s kinda what I need to figure out how to solve for

**Comment by mkruselj** [comment]
Ah gotcha. Bummer, I guess. Seems like a needless waste of space but if there's no easier or clearer solution...

**Comment by baconpaul** [comment]
The way to do this, I suppose, would be to do a portable install of 1.7 on windows, so I'm gonna close it. Don't think mac and lin demand will be as high as win.
