### ISSUE TITLE
Access certain tuning options when custom tuning is loaded but disabled

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1905]
We should be able to access the "Set to standard tuning option" when custom tuning is loaded but is simply disabled. This is current behavior (Tuning file is loaded):

![image](https://user-images.githubusercontent.com/50145178/82246474-bbf3ce80-9912-11ea-9e81-eaf24494cb8f.png)

![image](https://user-images.githubusercontent.com/50145178/82246556-e5145f00-9912-11ea-822a-6dc8b13174ba.png)

Same thing applies for keyboard mapping.

From Paul on Slack:
In the code, change SurgeGUIEditor line 4320 to:
`! this->synth.isStandardTuning || tuningCacheForToggle.size() > 0`

Same for kbm, about 13 lines down.

**Comment by mkruselj** [comment]
Done over here. :)
