### ISSUE TITLE
Change behavior of Tuning button

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1907]
Currently the button does nothing by default when Surge is loaded.

It would make more sense to show the same menu that RMB on Tuning button shows in this scenario, then after that shift the functionality to the on/off tuning thing.

I thought it was as simple as this:

![image](https://user-images.githubusercontent.com/2393720/82266671-94c8eb80-996a-11ea-9947-a32bdd5ca83e.png)

But it's not because unhandled exception because the pointer to storage is null and is never set to actually point to the storage. So, raising the Baconbatsignal! :)

**Comment by baconpaul** [comment]
Oh @EvilDragon sorry I found 2 seconds to look before dinner
6:54
The answer is the CStatusPanel constructor doesn’t assign storage
6:54
after doingDrag=false at line27 of CStatusPanel.h add
6:54
this->storage = storage;
6:54
and you should be fine
6:55
In your mouse handler where it says if (box.inside && editor ) make it say if( box.inside && editor && storage ) if you reference storage inside the block, just to be safe

**Comment by mkruselj** [comment]
OK, thanks!

I found that this condition won't really work, though. Because basically, when you disable the Tuning button, ìsStandardTuning` goes back to 0 and also the SCL that is loaded seems to revert to the standard 12-TET SCL. So I am not sure how to create this query which should only pop up the context menu on LMB if you didn't load a microtuning or KBM that is different from the default...

**Comment by baconpaul** [comment]
I just put that condition on an issue for @VincyZed yesterday. There’s a cache which holds the toggled off scale you can check. Look over in #1905 (and those are members on the editor)

**Comment by mkruselj** [comment]
Doh, it was that simple! But I assume I should probably take KBM into account as well. Just a few more ||s then.

One thing I noticed is that with that condition, when you return back to standard tuning/mapping, it doesn't gray out those menu entries again. Maybe it should?

**Comment by baconpaul** [comment]
That’s what #1905 is all about yeah graying our the menus

**Comment by mkruselj** [comment]
Yep that graying out is done, but since the tuning/mapping cache was kept even after setting the tuning and/or mapping to default, the menu wouldn't gray out. Anyways explicitly doing that now after setting to defaults, and all is good! #1911 sorts it all out!
