### ISSUE TITLE
Expand sub-menus for FX and Menu on the left (Linux)

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#1909]
Currently when passing mouse or arrows over menus for Effects and the Menu the sub-menus expand on the right, which makes it tricky to navigate

![vlcsnap-2020-05-19-09h57m45s713](https://user-images.githubusercontent.com/41337033/82336352-77227300-99b8-11ea-89a7-f96388ad07a8.png)

Would it be possible to have it like this?
![vlcsnap-2020-05-19-09h58m00s913 a](https://user-images.githubusercontent.com/41337033/82336510-b05ae300-99b8-11ea-9800-5c8e8050ca4f.png)

For 
![vlcsnap-2020-05-19-09h58m14s618](https://user-images.githubusercontent.com/41337033/82336549-bea8ff00-99b8-11ea-8915-ccccdc58cd22.png)

to be like
![vlcsnap-2020-05-19-09h58m58s098 a](https://user-images.githubusercontent.com/41337033/82336583-c9fc2a80-99b8-11ea-9831-985ec0109537.png)

The Text or Arrows do not need to be altered. Just the call to expand these two menus leftward and keep the Patch browser as is.

Thanks

**Comment by baconpaul** [comment]
OK I have a start on this but want you to give it a whirl and it's a bit hard to commit unless I commit 

so 

[oddy.patch.txt](https://github.com/surge-synthesizer/surge/files/4651275/oddy.patch.txt)

1. Save that file into your surge/vstgui.surge directory as `oddy.patch.txt`
2. do a `cd vstgui.surge` then `git apply oddy.patch.txt`
3. do a `cd ..` and build surge

when you run it you should see the menus opening left if they don't collide
the problem is the sub-sub menus open right. so like go to the ui / mouse menu and you will see
I think I can thread through fixing that but before I do that work want to make sure the double-left is the behavior you expect.
Thanks!

**Comment by tank-trax** [comment]
That works very well at 100%. Although, as you noted a sub-menu of a sub-menu will expand on the right.

![menus-1](https://user-images.githubusercontent.com/41337033/82345803-b1ddd880-99c3-11ea-8c03-4afbe978781f.gif)

Here is how it looks at 150%

![menus-2](https://user-images.githubusercontent.com/41337033/82345930-d76ae200-99c3-11ea-9413-7f4f7a11a65e.gif)

Apart from the aesthetics of having the menus mapped properly at various zoom levels and to have sub-menus of a sub-menu expand left, these changes already make navigating these menus much more efficient.

**Comment by baconpaul** [comment]
Oh right I calculate width in logical space and apply it in physical - lemme clean that up

**Comment by baconpaul** [comment]
[oddy_zoom_left.patch.txt](https://github.com/surge-synthesizer/surge/files/4651924/oddy_zoom_left.patch.txt)

OK here's the prescription now. Save that as `vstgui.surge/oddy_zoom_left.patch.txt`

```
cd vstgui.surge
git reset origin/surge --hard
git apply oddy_zoom_left.patch.txt
```

and give it a build and test. You will get a couple of harmless training whitespace errors when you apply.

If that works then I'll clean up my debug print statements and do the various rigamarole to apply a patch to vstgui.surge.

**Comment by baconpaul** [comment]
The above patch not only fixes zoom, it means 'once you go left you always go left'

**Comment by tank-trax** [comment]
Works perfectly on the Menu menu but am wondering... did you apply that to the FX menu? FX is at is was after the first patch.

**Comment by tank-trax** [comment]
hmm. just did a git pull and now get this

```
git apply oddy_zoom_left.patch.txt
oddy_zoom_left.patch.txt:78: trailing whitespace.

oddy_zoom_left.patch.txt:97: trailing whitespace.

oddy_zoom_left.patch.txt:114: trailing whitespace.

warning: 3 lines add whitespace errors.
```

**Comment by tank-trax** [comment]
Menus expand perfectly at all resolutions.

**Comment by xard-dev** [comment]
The change to make menu button items open left works so much better than the previous approach drawing over the existing dialog. I get that this compromise probably comes from a limitation where built-in dialogs can't be drawn outside of the plugin window.

There would be even space to flip the arrow icons to left side to make it look cleaner.

**Comment by baconpaul** [comment]
that's exactly why yeah. 

I thought about flipping the arrows. The reason i didn't is because with the keyboard the right arrow still opens the submenu. your thoughts on that thought welcome.

**Comment by tank-trax** [comment]
I though about the arrows being placed on the left until I looked at standard behaviour on KDE and when menus expand on the left the arrows remain on the right. It may look cleaner cosmetically but could be tricky to code.

**Comment by tank-trax** [comment]
Here is an example. The right arrow still expands to the left and the left arrow closes the sub-menu. The current behavior of the Surge menus is the same as the standard behavior in KDE. I am OK with keeping the arrows as they are.

![vlcsnap-2020-05-21-10h14m04s339](https://user-images.githubusercontent.com/41337033/82567919-0ad87880-9b4c-11ea-809f-608e6ba8fbf3.png)

**Comment by xard-dev** [comment]
Fair enough, it's understandable still and I didn't take account the keyboard shortcut which the arrow  symbolizes as well.
