### ISSUE TITLE
Mod tabs area changes look after typein

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1923]
![typein mod area ui issue](https://user-images.githubusercontent.com/2393720/82604070-0051c980-9bb4-11ea-884a-d335f66a9841.gif)

This happens only once when opening Surge afresh and once every time you change the zoom level. Dark or default skin.

**Comment by mkruselj** [comment]
Additionally, same thing now happens with vectorized step sequencer, same situation: when loading Surge afresh and every time when you change the zoom level. This is first at 175% then 150% zoom:

![stepseqchange](https://user-images.githubusercontent.com/2393720/82739537-99ade680-9d40-11ea-9167-cde940b763c6.gif)

**Comment by baconpaul** [comment]
I think this is the same problem as #1646 - namely redraw off by a smidge of a pixel vs rebuild.

I worry about this bug a lot.
