### ISSUE TITLE
Nightly VST3 plugin doesn't show up on ableton

### ISSUE THREAD

**Issue by hems** [surge-synthesizer/surge#1940]
**Describe the bug**
VST3 version doesn't show up on Ableton, that's all that shows up on the VST3 folder.

![image](https://user-images.githubusercontent.com/27327/82743096-0be0f400-9d5e-11ea-99bd-9cadcfeb854e.png)

AU works as expected:

![image](https://user-images.githubusercontent.com/27327/82743097-13080200-9d5e-11ea-84c9-7edaf9061e4a.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Host Ableton
 - Version 10

**Comment by K0rrid0r** [comment]
![100647610_272636237452519_8144533791776440320_n](https://user-images.githubusercontent.com/56724286/82743109-b52be800-9d66-11ea-8801-f56b7102c46d.png)
earlier today i also got another report from another user about ableton.

**Comment by baconpaul** [comment]
Can you run it from the command line and see if there are errors in the console? 

I don’t have ableton. 

The au works ok?

**Comment by hems** [comment]
> The au works ok?

AU works as expected.

Running ableton from the command line does not show any message regarding Surge ( but does from other vets, max map, etcs )

**Comment by baconpaul** [comment]
Ok. Any problem just using the au? Like I said I don’t have live and the one time I ran the (now expired) demo to test something I found it super confusing s

**Comment by hems** [comment]
> Ok. Any problem just using the au? Like I said I don’t have live and the one time I ran the (now expired) demo to test something I found it super confusing s

AU seems fine, also i don't have another DAW to test at the moment.

i guess you test on bitwig?

**Comment by sourcebox** [comment]
> Ok. Any problem just using the au? Like I said I don’t have live and the one time I ran the (now expired) demo to test something I found it super confusing s

AFAIK you can always download and run the latest version of Ableton Live in demo mode. It will not expire, only the save and export functions are disabled. Plugins will show up and load without any problems.

**Comment by baconpaul** [comment]
Primary dev is with test hosts (like hosting au or juce audiopluginhost) and regular usage is reaper and logic. The folks who test also regular tests in bitwig, Carla, qtractor and fl. Just no Mac live users in the group

**Comment by baconpaul** [comment]
> > Ok. Any problem just using the au? Like I said I don’t have live and the one time I ran the (now expired) demo to test something I found it super confusing s
> 
> AFAIK you can always download and run the latest version of Ableton Live in demo mode. It will not expire, only the save and export functions are disabled. Plugins will show up and load without any problems.

Oh thanks I’ll look when I next have a minute

**Comment by baconpaul** [comment]
So downloaded Live 10.1.16 demo and indeed it doesn't load surge vst3. it does load our juce vst3s. it gives me no error message and no way to debug. and the surge vst3 passes the vst3 validator and loads in every other daw on my mac. So I conclude that

1. This is something wrong with live / VST3 interacting with surge
2. Unless we get someone on the team who has debugged things in live the answer will be to use the AU

I'm going to leave this open but not put it in a milestone. If you know a person who fits the profile of #2, would love help recruiting her/him/them.

**Comment by hems** [comment]
> I'm going to leave this open but not put it in a milestone. If you know a person who fits the profile of #2, would love help recruiting her/him/them.

If I'm not mistaken VST3 version used to work a couple versions before.

So in theory, if you test 1 or 2 stable versions before and try again you might be able to find the error either manually or with git bisect.. ( I know it's a boring task.. sorry! )

I mainly use the AU and avoid VST3 at all costs, but I thought it was good to report the VST3 problem.

And yes, probably something related to Ableton which is definitely can;t be trusted in this sort of situation.

**Comment by baconpaul** [comment]
Wonder if it is when we added the multiple outputs - does live support multi output vst3?

**Comment by baconpaul** [comment]
Well it is not. I backed down to d5491b46 and still no live.

so at that point, the bisection becomes actually tedious. especially if we have to back to before cmake port.

**Comment by hems** [comment]
> Wonder if it is when we added the multiple outputs - does live support multi output vst3?

honestly, I don't know, also I opened the `Surge Effect Bank` and it

# BLASTED  AN INCREDIBLE LOUD NOISE FOR A SPLIT SECOND AND ALMOST BLEW MY SPEAKERS AND MY EARS 😭

I would recommend not having VST3 being installed by default and have some sort of "I AGREE THIS THING CAN BLOW MY SPEAKERS IF I USE ABLETON" sort of message, or "Use with caution at your own risk".

Ableton Live 10.1.4 here
OSX 10.12 ( maybe that's part of the issue? the OSX version? )

**Comment by baconpaul** [comment]
Well punishing the users of all the daws that do work with vst3 (namely everyone except live) seems a bit extreme but adding a click through warning in the installer is a good idea. I’ll look into that

**Comment by baconpaul** [comment]
<img width="630" alt="Screen Shot 2020-05-24 at 11 36 09 AM" src="https://user-images.githubusercontent.com/13387561/82758149-da464800-9db2-11ea-9ad6-99b5387b12d2.png">

the installer will have this step as of the next nightly

**Comment by baconpaul** [comment]
oh also i just ran the 1.6.6 vst3 surge effects bank in ableton 10.1.14 and it worked no problem. But the build of the master installed locally didn't show up. Everything fine in Reaper ,Bitwig, Validator. 

So :shrug: seems like live mac has a lot of work left to do on the VST3. glad it loads AU!

**Comment by hems** [comment]
> Well punishing the users of all the daws that do work with vst3 (namely everyone except live) seems a bit extreme but adding a click through warning in the installer is a good idea. I’ll look into that

yes i agree.

also i must say it was very weird that the effect bank did a very loud noise, that never happened before with any other plugin..

**Comment by baconpaul** [comment]
yeah you had me checking right away; but in logic and reaper on my mac we were fine.
I think "mac live doesn't work well with VST3" is the punchline here.

**Comment by mkruselj** [comment]
This has since been fixed in 1.7.1, right, @baconpaul? We could close this one.

**Comment by baconpaul** [comment]
Yup I had to blank sign the vst3 and did so so all good now
