### ISSUE TITLE
New step sequencer GUI enhancements look weird in some situations (especially dark skin)

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1941]
Here's a GIF explaining what I mean:

![Step-Seq](https://user-images.githubusercontent.com/50145178/82743738-7fbed480-9d3d-11ea-9c85-8795312c681e.gif)

**Comment by baconpaul** [comment]
Oh yeah wow a paint bug when we click the header thank you. Great demo

**Comment by baconpaul** [comment]
yeah i had an if at the wrong spot. fix coming. thanks!
