### ISSUE TITLE
Conditioner effect sounds wrong, affects sound when put on when it shouldn't.

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#1945]
**Describe the bug**
Something has been added to the code recently that affects the Conditioner effect, it sounds like a comb filter is being put on when the sound should stay unaffected.

**Please let us know your surge version**
@baconpaul this did not exist in the VST2 that you finally fixed with that preset problem. but the last VST2 build actually has this effect and the latest VST3, 64 bit.

* Surge Version: 
* Plugin type VST2 32 bit (last build), VST3 64 bit (latest)

**To Reproduce**
Just put on the init Conditioner over a sawtooth or something, you will hear it.

**Expected behavior**
Conditioner should not change the sound when put on.

**Comment by baconpaul** [comment]
Zero change to this code in 2 years. Not sure what it could be. For the version where you think it is OK, can you tell me the git hash on the about screen so I can look at what’s changed in between? Also can anyone else repro this?

**Comment by baconpaul** [comment]
I guess the fixed VST2 you refer to is this commit https://github.com/surge-synthesizer/surge/commit/5d514b9657e93b2a88df507736cf0b5187da1a14

On a quick scan It looks like UI only changes between there and today. When I get a minute I’ll build head and that and see if I can see the diff, especially if other folks see it.

**Comment by K0rrid0r** [comment]
yeah that version was the one i tested before this issue, no problem, didnt have the name of it.

but dont you hear it? did you test?

**Comment by baconpaul** [comment]
I don't hear it

at master, mac au, if I take init patch play a saw

activate init conditioner in position A1 and set the gain to -11.5db or so

the sound is unchanged

and toggle it on and off it basically sounds transparent.

**Comment by K0rrid0r** [comment]
sometimes i just cant understand my computer, now it dissapeared... im closing this issue.
