### ISSUE TITLE
New Surge installer cannot replace existing SurgeEffectsBank.vst3 anymore

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1947]
Since the new changes to the installer, I get this error:

![image](https://user-images.githubusercontent.com/50145178/82776273-63dc3100-9e18-11ea-8003-3e040147729b.png)

For now I can just skip it as I don't use SurgeEffects.

Before NIGHTLY-2020-05-25-24e8464 it was installing without any issues.

**Comment by baconpaul** [comment]
Aww man juce6 made it a bundle ... remove the old one and it will work but I need to fix it too

**Comment by tank-trax** [comment]
I noticed that if I make a session in Reaper using a previous version of SurgeEffectsBank.vst3 and build a newer version the new SurgeEffectsBank.vst3 will not be recognized by the session. Rescanning will find the new SurgeEffectsBank.vst3 but it cannot be loaded in the place of the old SurgeEffectsBank.vst3 so any settings or prests are lost.

**Comment by mkruselj** [comment]
@tank-trax that is worth checking out in a few other DAWs and see if they behave the same or if they load the project correctly. If it's the latter then it's a Reaper issue..

**Comment by baconpaul** [comment]
@tank-trax also 'previous version' you mean hand built vst3? But can you bounce that to another issue. I want to close this one since it is about the windows installer and I have it fixed.
