### ISSUE TITLE
Investigate the VST3 Scale Factor API

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1951]
https://steinbergmedia.github.io/vst3_doc/base/classSteinberg_1_1IPlugViewContentScaleSupport.html

This could help us a lot with some of our windows off-by-one pixels boogers i bet if the DAWs support it.

Basically use a call to this API to modify the backing store size on windows and maybe on Linux too.

**Comment by baconpaul** [comment]
So I investigated briefly and alas reaper windows doesn't seem to call me, so push this out of 1.7 beta 1 until I feel like looking in more detail

**Comment by Kingston1** [comment]
Cubase 11 Pro reports this correctly but not quite as expected. The result from setContentScaleFactor on the first few calls that the host sends are 1.0. Eventually it calls with the correct scale factor.

**Comment by baconpaul** [comment]
Well that is certainly consistent with the bug we are seeing in that DAW.

Looks like an “if hostname == “Cubase”” is in our future in SurgeGUIEditor I guess :(

**Comment by Kingston1** [comment]
Well, scaleFactor at least is consistently broken. On opening the UI (both reopen and initial open) the scaleFactor will be 1.0 for the first few calls.

On the other hand SurgeGUIEditor::onSize(Steinberg::ViewRect* newSize) will be different on initial open vs. reopen.

**Comment by Kingston1** [comment]
Due to zoom stabilize across the board in https://github.com/surge-synthesizer/surge/pull/3210 this issue can probably be closed.

The scale factor that cubase reports is not really useful for anything and is not needed for even high DPI scenarios. Windows size simply works now, despite DPI setting.

**Comment by baconpaul** [comment]
Yeah we implement and understand this now. Can close. Thanks so much @Kingston1 !
