### ISSUE TITLE
Bitwig functions crash VST3

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#1952]
**Describe the bug**
Bitwig has additional options for Surge's VST3 instrument:

- Map to Controller or Key
- Add Automation Lane
- Set to Default Value

These options do not exist for the VST2.

When any of the following options is selected Surge will crash

![offset](https://user-images.githubusercontent.com/41337033/82939105-d3f5ce80-9f60-11ea-8d16-7d36532402cb.gif)

![auto](https://user-images.githubusercontent.com/41337033/82939111-d5bf9200-9f60-11ea-8704-50213ea41787.gif)

* Surge Version: commit 24f7676
* Plugin type: VST3
* Bits: 64
 - OS: Linux Debian Buster 10.3
 - Host: Bitwig 
 - Version: 3.2 beta 7

**Comment by mkruselj** [comment]
Doesn't happen on Windows, but BWS 3.1.2.

**Comment by tank-trax** [comment]
Happens on 3.1.2 also

**Comment by baconpaul** [comment]
OK I know why this is happening. The target I am remembering in the menu gets deleted so it is actually wrong on all platforms but crashes bitwig linux.

a "target->addRef()" in SurgeGUIEditor fixes the crash but adds a leak. So a tiny bit of work to do.

**Comment by baconpaul** [comment]
Seems this didn't fix it for @tank-trax so re-opening

**Comment by tank-trax** [comment]
I just built a clean folder with a new git pull and it has the commit at aba9b80
git pull now has the latest commit

**Comment by baconpaul** [comment]
and does it still crash?

**Comment by baconpaul** [comment]
@tank-trax reports

> it no longer crashes using commit aba980 however - Set to Default Value does not reset the value not sure if the functions are working

and I say

> Wonder if I have to retain something else?

**Comment by tank-trax** [comment]
no crashing, but not functional

**Comment by baconpaul** [comment]
https://github.com/ryukau/VSTPlugins have a working version it seems

**Comment by baconpaul** [comment]
So looking at that code they do

```
  IContextMenu *menu = handler->createContextMenu(this, &id);
  if (menu == nullptr) return kMouseEventNotHandled;

  menu->popup(where.x, where.y);
  menu->release();
```

which means they just show the bitwig menu directly, not merge it with their own menu which we can't do

but I bet that ->release() is what's getting us. I'm sure we have to do an addRef also on the handler to make it work in bitwig
