### ISSUE TITLE
Ring Modulator Effect

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1958]
Chatting with Korridor on Slack we discussed a RM effect with a built in carrier. I have most of the code in BaconMusic in a beta way so lets add this as an option.

**Comment by K0rrid0r** [comment]
Some desired functions of the ring modulator would be something in the style of this.

![ring](https://user-images.githubusercontent.com/56724286/83029481-03750b80-a033-11ea-88c0-50196f2d7ac8.jpg)
![22](https://user-images.githubusercontent.com/56724286/83028916-5601f800-a032-11ea-8bab-f43f9afc7012.gif)

This ring modulator may be old but has some unique features that world very well and gives an experimental sound. A surge effect can have a maximum of 15 sliders, so 15 functions could be applied which would be awesome.

1. Frequency from 0-20000 hertz and with extend range feature
2. Internal carrier oscillator with various waveforms, Sine, Triangle, Square, Sawtooth, Ramp and more.
1. Mix/Dry of the effect (Depth)

LFO features.
3. Internal LFO with various waveforms, Sine, Triangle, Square, Sawtooth, Ramp and more and with DAW tempo sync.
4. LFO to depth
5. LFO frequency from 0-20000 hertz and with extend range feature.
6. LFO to frequency 
7. LFO threshold. -inf, -50 db -0 db
8. LFO deform
9. LFO magnitude
10. LFO unipolar/bipolar
11. Slave sync slider that slaves the ring modulator carrier oscillator to oscillator frequency of scene A and B
12. Chose which oscillator to slave it to with these options. if you want
(OscA1), (OscA2), (OscA3), (OscB1), (OscB2), (OscB3), (OscA1+OscA2+OscA3), (OscA1+OscA2), (OscA1+OscA3), (OscA2+OscA3), (OscB1+OscB2+OscB3), (OscB1+OscB2), (OscB1+OscB3), (OscB2+OscB3), (All)
13. Chose which Surge LFO to slave the ring modulator LFO to, if you want
(Voice LFO1), (Voice LFO2), (Voice LFO3), (Voice LFO4), (Voice LFO5), (Voice LFO6), 
(Scene LFO7), (Scene LFO8), (Scene LFO9), (Scene LFO10), (Scene LFO11), (Scene LFO12)

Ideas for:
14. ?
15. ?

**Comment by baconpaul** [comment]
Thanks

So FX can't have voice level properties - they are scene level. So we can't couple to VLFO or a particular OSC if we drop it in the FX slot. And the built in modulation from SLFO will already work so I'm not sure why we want to slave things vs just use modulation. From your description it sounds like you don't want this as an effect but rather as a in-line RM.

So while we can make it an effect (in fact I have it running on my MacBook right now!) it sounds like what you really want is something more like "analog mode" for the RM section of the mixer perhaps?

I do have a basic analog RM running with an independent sin oscillator as an effect right now. And can do a bunch of stuff using built in modulation. 

Lemme put an mp3 on slack for you

**Comment by baconpaul** [comment]
ToDos here

- [ ] A bit more gain leveling
- [ ] Probably run it oversampled
- [ ] Add High Cut and Low Cut
- [ ] Consider moving the innards to SSE depending on a performance check
