### ISSUE TITLE
Analog ring modulation mode in the mixer

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1962]
Over in #1958 I am implementing  https://github.com/baconpaul/surge/pull/new/ringmod-1958 as a standalone FX

But no reason a version of that couldn't be analog mode for the 1x2 and 2x3 mixer stuf

Not for 1.7.0 though.

**Comment by mkruselj** [comment]
We can have this with the voice level insert FX envisioned by #4355. Closing this one in favor of it.
