### ISSUE TITLE
Bitwig VST3 Warning about handlers

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1968]
Running surge in 3.2 beta 7 the ~/.BitwigStudio/logs/engine.log contains this:

<img width="1082" alt="Screen Shot 2020-05-27 at 6 59 21 PM" src="https://user-images.githubusercontent.com/13387561/83080454-38da2300-a04c-11ea-8142-40a4c8619a89.png">

**Comment by baconpaul** [comment]
XT VST3 in Bitwig 3.3.7 linux no longer displays this

**Comment by mkruselj** [comment]
We can close then 🙂

**Comment by baconpaul** [comment]
Yeah didn’t I? Sheesh sorry
