### ISSUE TITLE
Scope for audio and modulation signals (was: Oscilloscope view for OSCs)

### ISSUE THREAD

**Issue by hems** [surge-synthesizer/surge#1970]
It would be great to have a mode on the OSC view to visualize the current waveform that is being played accounting with FM and other modulation sources.

Basically having the "static view" of the OSC, which shows the "original waveform", as it currently works but also having a "oscilloscope view" which reflects the waveform that is actually being played at the moment ( basically redrawing the waveform considering FM + all parameter modulations ).

This feature wouldn't change the sound of the synthesizer but could be used to further understand what the synth is doing and eventually come up with new ideas and sounds based on that.

Also, I can imagine in the future having an "OSC Editor" where the user could freely draw a waveshape and use it as LFO or as a Complex Oscillator depending on it's frequency?

**Comment by hems** [comment]
Here is a fun reference given by @k0rrid0r: https://www.desmos.com/calculator/uhbqb9yj1e?fbclid=IwAR0wXBqjjB7B6N8nmJhDEzq5Eq2uL1K6382x3VZVurXvIPiSkF5b-ApSEyQ

**Comment by baconpaul** [comment]
So we’ve chatted about this a couple of times. Our conclusions generally come down to

1. Writing a good scope is hard
2. Writing a good scope in vstgui is harder
3. There’s good scopes available as plugins so if you want to see something stick one of those downstream in your daw
4. So the work : compelling ratio on a scope isn’t that high

An editor is a separate thing. #982 talks about an MSEG; On an OSC editor, I think most folks would use a wavetable for that. I haven’t used https://synthtech.com/waveedit/ but I think it outputs files compatible with surge now. (If not we should fix that!)

**Comment by baconpaul** [comment]
So s(m)oscope the scope I generally use in quick and dirty AU situations is GPL3 and written in VSTGUI. I took a look at the code this afternoon to see if there are any tricks. There are not. It just collects and draws the wave. So VSTGUI - at least on mac - can scale to a scope view. Just dropping this comment in here for when I finally turn to this issue

**Comment by mx** [comment]
PR #6626 added a basic scope. Rather, it added the spectrum analyzer part of it. The waveform part is coming next.

**Comment by baconpaul** [comment]
Amazing

**Comment by hems** [comment]
Amazing! I think my favourite scope is by Melda Productions ( i love the specially the normalize feature and the auto sync ) !

sometimes i use the one from StillWell tough which is great as it can plot several waveforms at the same time with different colours

i think its worth having a look on both

**Comment by mx** [comment]
This is now complete and should be released with XT 1.2.
