### ISSUE TITLE
Fragments for the 1.7 Manual Upgrade

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1979]
Some features are trickier than others to document. As we code up bits and bobs add little hints for the manual here.

In addition to including these, we need to update the paramdocumetation.xml file to be complete.

**Comment by baconpaul** [comment]
Portable Mode on Windows

- Portable Mode allows you to store assets in the same directory as your surge.vst3 dll.
- If Surge.vst3 is installed in a folder and in that same folder is a directory called "SurgeData", Surge will use that for factory data rather than %PROGRAMDATA%\Surge
- If in that same folder is a directory called "SurgeUserData" Surge will use that for user data rather than %DOCUMENTS%\Surge
- Either none, one, or both of those folders can be there. Surge will fall back to the defaults if they are not present
- You can always see your data paths in the about screen

**Comment by baconpaul** [comment]
LFO and Step Sequencer UI updates

- as well as the general display improvements
- on step sequencer, quantized drag quantizes to scale length if you are in a non-standard tuning
- rmb and drag across the steps to set up a ramp from point to point. end your ramp in the step where you start to cancel

**Comment by mkruselj** [comment]
- Step seq: Shift+Alt (Shift+Opt on Mac, I suspect) does a drag that quantizes to twice the scale length
- Step seq: Quantization with Shift/Shift+Alt is also applied when doing the linear ramp with RMB drag

**Comment by mkruselj** [comment]
Check all of the parameter names and compare them to old ones, a LOT of them will need updating in the manual!

**Comment by mkruselj** [comment]
Current glide mode is constant time: it always takes the same time to glide between any two keys. In constant rate glide mode, the time to cover one octave is defined by the Portamento slider. From there on, each octave added duplicates that glide time, so if you play C1 then C3, and your glide time is 0.5s, it will glide 1s total.

Constant rate factor applied to glide time is: `1 / ((1 / 12) * glide_interval)`

**Comment by VincyZed** [comment]
So for the new **Constant glide rate** option for portamento:

Current glide mode is constant time: it always takes the same time to glide between any two keys.
In constant rate, the time to cover one octave is defined by the Portamento slider.
From there on, each octave added duplicates that glide time, so if you play C1 then C3, and your glide time is 0.5s, it will glide 1s

Formula is 1 / (1/ScaleLength * interval)

**Comment by baconpaul** [comment]
Portamento 'retrigger at scale degrees' will retire the AEG and FEG each time portamento crosses to a new pitch

**Comment by mkruselj** [comment]
Paul's phone autocorrect meant "retrigger" instead of "retire" ;)
