### ISSUE TITLE
wav file loading on mac and linux

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#198]
Right now, .wav file (in SurgeStorageLoadWav.cpp) is implemented for windows only. We should fix that I guess!

**Comment by esaruoho** [comment]
Aha!  So this is what the KVR ppl were talking about. When i asked for Details all i got was silence. Incredibly frustrating.

**Comment by baconpaul** [comment]
Yeah; this is separate from the drag-and-drop stuff (which is cross-platform disabled) but basically when you load_wt, you check if it is a .wt file, and then if you aren't mac you and you are a .wav you call load_wt_wav.

so this means behavior is

* windows: a .wav file loads
* mac: a .wav file doesn't load and nothing happens because you never call load_wt_wav in SurgeStorage
* linux: a .wav file doesn't load but you do get an fprintf to stderr, because you do call load_wt_wav in SurgeStorage, but you don't meet the `#if WINDOWS` gate.

I guess if someone were to attack this issue you'd just sort of need to either (1) like some external library for reading wav files or (2) replicate the stuff in the windows block to not use the windows specific mmioOpen API and use instead uhh I guess fread? or some mem mapped file read?

Looks like "actual unfun work" tbh.

**Comment by baconpaul** [comment]
For the person who does it on a mac, even if it ends up being me, I would use https://developer.apple.com/documentation/audiotoolbox/audio_file_services and then you can read basically anything and don't have to write all that code.

On linux I guess you could use libsndfile

**Comment by baconpaul** [comment]
baconpaul branch mac-wav-file-198 is a healthy start; it loads a wav file and reads the bits. It just can't seem to push the bits into the wavetable data structure yet. So plugging away here.

**Comment by baconpaul** [comment]
<img width="474" alt="screen shot 2019-01-05 at 11 40 51 am" src="https://user-images.githubusercontent.com/13387561/50726699-e1e24f80-10de-11e9-8c46-f2541c2ee591.png">

OK so I can read a wav file and create wavetables. I am not quite sure what the expected behavior is though so need to read some more code.

@esaruoho the users who complained about not being able to load wav? Did they provide a few sample wav files for us to try?

**Comment by esaruoho** [comment]
@baconpaul they just wrote that they were not able to drag a WAV in. Does the WAV (in your screenshot) that you dragged in play in the plugin? Can i try it?-)

**Comment by baconpaul** [comment]
@esaruoho it does play but you can’t drag it in; you need to put it in the application support wavetables directory. The thing is that way files imply loop segments which I haven’t implemented yet and contain multiple virtual tables as a result. So I was looking for someone who had a way file configured for surge that had (1) the loop settings set up and (2) a second file which was 32 bit float rather than 16  bit int along with a description about how those work with shape.

But if you want to try it

```
Git remote add baconpaul https://github.com/baconpaul/surge
Git fetch baconpaul
Git checkout baconpaul/mac-wav-file-198
```

Or thereabouts should let you do a build with my diffs.

**Comment by baconpaul** [comment]
This issue is still alive; and I just rebased my branch.
