### ISSUE TITLE
Integrate Nick Moritz skin

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1984]
As discussed in the slack design channel

The course of doing so will make me finish off the skin engine I bet

**Comment by baconpaul** [comment]
[NickMoritzAssets.zip](https://github.com/surge-synthesizer/surge/files/4712809/NickMoritzAssets.zip)

there's the file from nick so we have it

**Comment by baconpaul** [comment]
[Surge Assets - Merged - Simplified (01.07).zip](https://github.com/surge-synthesizer/surge/files/4858244/Surge.Assets.-.Merged.-.Simplified.01.07.zip)

https://xd.adobe.com/view/0da59dd5-1561-4595-bcbf-94de8e69dd3d-58f6/

**Comment by mkruselj** [comment]
Requirements to make it work as it's intended to look:

- [ ] resizeable complete GUI frame
- [ ] restoring bitmaps
- [ ] mod tabs skinnable
- [ ] LFO switcher skinnable
- [ ] XYWH for _everything_

**Comment by mkruselj** [comment]
For Nick:

- [ ] PNG dimensions for zoom levels:
100%: 940x564
125%: 1175x705
150%: 1410x846
175%: 1645x987
200%: 1880x1128
300%: 2820x1692
400%: 3760x2256
- [ ] Generate SVG for menu used in FX section for Airwindows/Distortion/Flanger effects (bmp00167) - normal and hover state
- [ ] Generate SVG for shorter menu used for filter type (bmp00168) - normal and hover state
- [ ] Generate SVG for vertically stacked filter icons (bmp00169) - normal and hover state

**Comment by mkruselj** [comment]
And we have done it, peeps!
