### ISSUE TITLE
Older linux gcc needs these to detect experimental::filesystem

### ISSUE THREAD

**Issue by mickski56** [surge-synthesizer/surge#1986]
**Describe the bug**
Older linux gcc needs these to detect experimental::filesystem

**Please let us know your surge version**
git latest

**To Reproduce**
1. Try to build surge with gcc 5.3

**Expected behavior**
surge builds

**Additional context**

```--- CMakeLists.txt-orig	2020-05-30 13:13:34.149811243 +0100
+++ CMakeLists.txt	2020-05-30 13:16:53.050629014 +0100
@@ -80,6 +80,8 @@
   set( FS_COMPILE_DEFINITIONS USE_STD_FILESYSTEM=1 )
   message( STATUS "Using std::filesystem" )
 else()
+  set (CMAKE_REQUIRED_FLAGS "-std=c++11")
+  set (CMAKE_REQUIRED_LIBRARIES "stdc++fs")
   CHECK_CXX_SYMBOL_EXISTS(std::experimental::filesystem::path::preferred_separator "experimental/filesystem" CXX_EXP_STD_FS)
   if( CXX_EXP_STD_FS )
     set( FS_COMPILE_DEFINITIONS USE_STD_EXPERIMENTAL_FILESYSTEM=1 )
```

**Comment by baconpaul** [comment]
is there any way to determine if I am in gcc 5 in cmake so I can just adjust for linux and older compilers?

**Comment by baconpaul** [comment]
Apparently CMAKE_CXX_COMPILER_VERSION is defined so lemme look there

**Comment by mickski56** [comment]
CMAKE_REQUIRED_FLAGS & CMAKE_REQUIRED_LIBRARIES are only required to pass the check for std::experimental::filesystem::path::preferred_separator, you can unset them immediately afterwords and surge will build just fine.

Also  -std=c++11 is the minimum, you could use anything after like -std=c++1z

**Comment by baconpaul** [comment]
Yup so I will just add that in an if(LINUX) and we should be good. Or maybe an if( LINUX AND (CMAKE_CXX_COMPILER_VERSION VERSION_LESS 6.0 ) )

I'll also activate an ubuntu 16 in our pipeline. Recently upgraded them to ubuntu 18 which is I'm guessing why I didn't see this.

Thanks!

**Comment by baconpaul** [comment]
OK I pushed this change conditioned on unix not apple; I also re-added an ubuntu 16 pipeline to CI which uses gcc 5.4; without the change it fails and with the change it builds.

All as of 69a273b

Thanks!
