### ISSUE TITLE
Changes made through host automation to the Assignable controllers are not reflected in export/render/bounce (VST3)

### ISSUE THREAD

**Issue by arjen-klar** [surge-synthesizer/surge#1999]
**Describe the bug**
Changes made to the _Assignable controllers_ through DAW automation are not reflected in non real time DAW export/render/bounce. This only is applicable for the VST3 version.

Tested with Studio One 4.5 and Cubase 10.5

**Please let us know your surge version**
1.6.6
VST3
x64

**To Reproduce**
1. Load _Init_ preset
2. Assign _Assignable controller 1_ (C1:) to OSC 1 pitch with a value of -7 on 100% 
3. Create a note and automation move in the host controlling _Assignable controller 1_ (C1:) from 0 to 100%
4. Export the result (not in real time)

**Expected behavior**
The exports reflects what the DAW plays back in real time (pitch going from 0 to -7 (0 to 100%)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Host Studio One 4.5, Cubase 10.5

**Comment by baconpaul** [comment]
Oh fascinating Thank you for the excellent report

**Comment by baconpaul** [comment]
@mkruselj looked in reaper and same thing there. This is more of the “cc vs FX1” mapping confusion. I’ll try and hunt it down.

Appreciate the report.

**Comment by mkruselj** [comment]
As a temporary workaround, you can use the MIDI CC assigned to the macro controller and it will work.

**Comment by baconpaul** [comment]
So confirmed. When I automate CC -> Pitch in the DAW it sounds but when I render it does not.

So let me find out what the difference is.

**Comment by baconpaul** [comment]
Found it. Far less scary than I thought. There are two entry points for automation and I had one of them skipping the metacontrollers

**Comment by baconpaul** [comment]
This will be fixed in the next surge nightly; and also in the upcoming 1.7 release later this summer.
