### ISSUE TITLE
LFO deform problem, cross LFOing

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2016]
**Describe the bug**
It is hard to locate what the cause of this problem is but when doing cross LFOing between for example two LFOs and involving deform surge sometimes breaks/stops/clips.

**Please let us know your surge version**
all versions from old to newest.

**To Reproduce**
Just take deform on LFO1 (SEQ 1) to over 50% and surge will break/stop/clip
[surge breaks LFO1 deform 50%.zip](https://github.com/surge-synthesizer/surge/files/4720356/surge.breaks.LFO1.deform.50.zip)

Just take deform on LFO1 (SEQ 1) to over 50% and surge will give a sound that indicates the problem but not break
[surge breaks LFO1 deform 50% 2.zip](https://github.com/surge-synthesizer/surge/files/4720357/surge.breaks.LFO1.deform.50.2.zip)

This one just breaks/stops/clips, directly when played.
[surge broke 2.zip](https://github.com/surge-synthesizer/surge/files/4720359/surge.broke.2.zip)

**Expected behavior**
No break/stop/clip, when doing cross LFOing in interesting ways.

**Comment by baconpaul** [comment]
Found it. What an amazingly good bug report. Thank you.
