### ISSUE TITLE
Hover State gets wrong coordinate message after UI Rebuild (was: Prev-next arrows hover state mixup)

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2020]
![hover mixup](https://user-images.githubusercontent.com/2393720/83605475-4295e600-a578-11ea-9ad6-79e7f58d364d.gif)

Should be self-explanatory. Left arrow works ok (sometimes showing a hover state is skipped tho), right arrow not.

**Comment by baconpaul** [comment]
oh ha it is because those hover based on 'value' and the value of those is probably not maintained properly. thanks.

**Comment by baconpaul** [comment]
nope it is for a more annoying reason
the patch change makes the ui rebuild
the ui rebuild means the new version of the switches don't have the hover state set because the mouse hasn't entered
so basically when i construct the ui from scratch i need to set hover state properly
ugh

**Comment by baconpaul** [comment]
OK this is even worse than the thing that is even worse

when frame does an onmouseup it sends a message mouse entered in untranslated coordinates
that puts my hover at the wrong spot
this is a vstgui bug with scaling and transforms when you make new components
but i am having a hard time finding it
this one is tough. even if i force the right call... it ends up doing the right thing then getting clobbered by the frame

`baconpaul/hover-2020` is as far as i got

**Comment by baconpaul** [comment]
at 100% zoom it should work perfectly. does on mac. would appreciate a test on win.

**Comment by mkruselj** [comment]
Tested your branch - works at 100% on Win!

**Comment by baconpaul** [comment]
Alright it looks now like onMouseEntered is not applying a transform and onMouseMoved is, and this is across the board.

If in CHSwitch2 I put prints and stacks here's what I see when I enter the patch widget. Note the different coordinates for the third call.

```
 where.x=339.77 where.y=55.625
-------- StackTrace (14 frames deep) --------
  [  1]: 1   Surge                               0x00000001158be6a5 _ZN9CHSwitch214onMouseEnteredERN6VSTGUI6CPointERKNS0_12CButtonStateE + 261
  [  2]: 2   Surge                               0x0000000115962003 _ZN6VSTGUI6CFrame15checkMouseViewsERKNS_6CPointERKNS_12CButtonStateE + 1219
  [  3]: 3   Surge                               0x000000011596357f _ZN6VSTGUI6CFrame12onMouseMovedERNS_6CPointERKNS_12CButtonStateE + 271
  [  4]: 4   Surge                               0x00000001159684ea _ZN6VSTGUI6CFrame20platformOnMouseMovedERNS_6CPointERKNS_12CButtonStateE + 90
 where.x=339.77 where.y=55.625 nhoverValue=1 hoverValue=-1 x=1 y=0 mouseableArea.top=41 mouseableArea.left=242 mouseableArea.getWidth()=37 mouseableArea.getHeight()=12
-------- StackTrace (15 frames deep) --------
  [  1]: 1   Surge                               0x00000001158be06f _ZN9CHSwitch219calculateHoverValueERKN6VSTGUI6CPointE + 1023
  [  2]: 2   Surge                               0x00000001158be6c3 _ZN9CHSwitch214onMouseEnteredERN6VSTGUI6CPointERKNS0_12CButtonStateE + 291
  [  3]: 3   Surge                               0x0000000115962003 _ZN6VSTGUI6CFrame15checkMouseViewsERKNS_6CPointERKNS_12CButtonStateE + 1219
  [  4]: 4   Surge                               0x000000011596357f _ZN6VSTGUI6CFrame12onMouseMovedERNS_6CPointERKNS_12CButtonStateE + 271
 where.x=251.681 where.y=41.2037 nhoverValue=0 hoverValue=1 x=0 y=0 mouseableArea.top=41 mouseableArea.left=242 mouseableArea.getWidth()=37 mouseableArea.getHeight()=12
-------- StackTrace (14 frames deep) --------
  [  1]: 1   Surge                               0x00000001158be06f _ZN9CHSwitch219calculateHoverValueERKN6VSTGUI6CPointE + 1023
  [  2]: 2   Surge                               0x00000001158bdc22 _ZN9CHSwitch212onMouseMovedERN6VSTGUI6CPointERKNS0_12CButtonStateE + 274
  [  3]: 3   Surge                               0x000000011596376e _ZN6VSTGUI6CFrame12onMouseMovedERNS_6CPointERKNS_12CButtonStateE + 766
  [  4]: 4   Surge                               0x00000001159684ea _ZN6VSTGUI6CFrame20platformOnMouseMovedERNS_6CPointERKNS_12CButtonStateE + 90
```
