### ISSUE TITLE
Editing step sequencer should hide/show cursor

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2025]
...just like when tweaking the sliders (if the global option is enabled, ofc!).

I have tried (so naively, I guess), to just try this on Windows by adding `showCursor(false/true)` in `::onMouseDown` and `::onMouseUp` but that just didn't work, and I don't know why - either cursor wouldn't hide, or it would remain permahidden...

(obviously I checked `rect_steps.pointInside` along with relevant button states but...)

**Comment by baconpaul** [comment]
i have a cleanup PR going; i'll knock this one out with it also
