### ISSUE TITLE
Truncated menu glyph on Linux

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2029]
genericoptionmenu draws the menu
when it truncates it scrolls all fine that's no problem
but there's no glyph indicating a truncated menu in either direction
add one, allowing us to close #617 and stick this in the 1.7 beta1 milestone along with the rest of the linux gfx improvements.

**Comment by tank-trax** [comment]
only the Patch Menu would require this feature (should it be added) as the FX and Main Menus do not exceed the boundaries

**Comment by baconpaul** [comment]
Yeah that's the one to test with.

**Comment by baconpaul** [comment]
<img width="999" alt="Screen Shot 2021-04-10 at 7 16 55 PM" src="https://user-images.githubusercontent.com/13387561/114286997-714ed980-9a31-11eb-97f2-33f42fa7ce82.png">

There's the linux JUCE menu. Works just like mac and windows. So no need to code in a glyph to vstgui so will close this as a 'wont do won't need juce has fixed'

I'm sure we will have lots of issues about menus in XT but they won't be linux specific any more :)

**Comment by baconpaul** [comment]
<img width="861" alt="Screen Shot 2021-04-10 at 7 19 21 PM" src="https://user-images.githubusercontent.com/13387561/114287019-aeb36700-9a31-11eb-8778-394cdd82dbe5.png">

Here's the exact same menu at head in mac. So cool menu non-uniformity gone. Closing this.
