### ISSUE TITLE
HF Damp in 'Reverb 1' can blow up/clip if reaching into negative values + modulation problem

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2034]
**Describe the bug**
As discussed briefly in slack the one-pole filter in HF Damp, Reverb 1 can blow up/clip if reaching into negative values.

Also modulation from surge LFOs, macro controllers and DAW host modulation can also blow up/clip (sometimes in an --extremely-- loud bang) HF Damp even if it dosen't reach into negative values.

This preset demonstrates the problem well. Just put on any of the two send reverbs and the preset will break within seconds. (USE LIMITER AFTER SURGE!)
[HF Damp reverb 1 issue preset - send reverbs 1+2.zip](https://github.com/surge-synthesizer/surge/files/4737711/HF.Damp.reverb.1.issue.preset.-.send.reverbs.1%2B2.zip)
Take away HF Damp modulations from both of the reverb 1 sends and the preset will run (just tried for 30 minutes, it went without clipping)

**Please let us know your surge version**
Exist in all surge versions from oldest to newest and is still an unsolved problem.

**Comment by baconpaul** [comment]
oh yeah thanks. i'll add this to the list. i know what the fix is.

**Comment by K0rrid0r** [comment]
I also checked Reverb 2 now and it can also blow up but in a slower way. check that also, HF Damp
