### ISSUE TITLE
Mod targets should be cleared in effects.

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2036]
I noticed now that mod targets are still on when you change effect. Mod targets should be cleared in effects.

Example
![30](https://user-images.githubusercontent.com/56724286/83919541-17c7af80-a77b-11ea-9f8a-3b9f9a8a1507.gif)

**Comment by baconpaul** [comment]
![clr2036](https://user-images.githubusercontent.com/13387561/84092095-6c11a000-a9c4-11ea-9404-5db174116049.gif)
