### ISSUE TITLE
Add Tempo Sync for all Filter and Amp EG controls (where logically applicable)

### ISSUE THREAD

**Issue by Jacky-Ligon** [surge-synthesizer/surge#2037]
Filter and Amp EG | Tempo Sync

In the LFO/SEQ section, one can right-click on a control and select from either Tempo Sync, or Enable Tempo Sync For All…

How complicated would it be to add the latter option to the Filter and Amp EGs, where it could be logically applied (obviously not on Sustain stage for example)? 

Enable Tempo Sync For All Controls?

**Comment by mkruselj** [comment]
@Jacky-Ligon It was quite simple to implement once you know where to look. 🙂

**Comment by Jacky-Ligon** [comment]
In quite a hilarious synchronicity, just minutes ago I was designing some attack-transient patch components, and was thinking specifically about this issue, and how it will really help to make these more quickly, then saw your GitHub transmission. 

Glad to know it's somewhat trivial to implement; was hoping that would be the case.

Have been thinking of the potential for using Surge to create a library of short attack-transient timbres, and another with sustaining timbres, from the seven oscillators, then use these in various combinations, kind of like the old Roland D-50...

So far, the initial test patches have been extremely promising, and Surge actually excels wonderfully at this sort of sound-design task, so looking forward to this enhancement, and thanks for looking into it at the code level.

**Comment by mkruselj** [comment]
Well, go off and have a nigthly, this is now implemented 🙂

**Comment by Jacky-Ligon** [comment]
Thanks much for the enhancement. Have been using it already, and very glad to have this in place for the Surge sound-design ahead.
