### ISSUE TITLE
Mousewheel on oscillator type menu

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2042]
We got mousewheel on LFO type menu for 1.7, may be worth to do the same for the oscillator menu, if achievable in a relatively easy way? That'd be superb!

**Comment by baconpaul** [comment]
This is closely related to #1896 so let me link them. if I do one of them I can do the other at the same time I think. but they are both annoying for an annoying reason.

**Comment by mkruselj** [comment]
I'm moving this one to 1.7.n in good faith. :)

**Comment by mkruselj** [comment]
Reopening in order to fix the issue where it takes way too many mousewheel clicks to go outside of Classic osc subfolder into the rest of the list.
