### ISSUE TITLE
Formula modulator tasks

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2048]
OK so PR #4527 gets something working with luajit which is pretty fun. I'm gonna hijack this issue as a book of work

- [ ] LUA Prelude
     - [ ] What do we want in here? 
     - [ ] Design some things but include probably an ADSR and a few other type envelopes
- [x] Low Level Fixes 
     - [ ] Clean up all functions at patch change (this is tricky because the scope of lua isn't the scope of patch)
     - [x] Regtest for vector output formula
- [ ] Tutorial Patches (rough sketch)
    - [ ] redo 6 and add 11
   
- [ ] UI and Behavior Small Things
    - [x] Skin Colors for the Debugger
    - [ ] When `use_envelope` is set to false, don't scale the LFO display in time

---------

This is the @baconpaul "lets have a scheme interpreter" joke, except real, and relates to a lot fo the other modulation issues based on conversations with @mkruselj and @K0rrid0r 

here's the idea

1. Introduce a new LFO type called "FORMULA"
2. when you go into formula mode all of the inputs - all of them - change name to Param A, Param B etc...
3. The waveform section gets replaced with a type area which looks like

```
float lfo_value( time, A, B, C, D, E )
{
    return ( time * 0.5 ) % 1 * 2 - 1;
} 
```

or some such

then you can code whatever modulation output you want. The ABCD are values of the sliders and so you can bind them toothed modulators.

Watch out for cycles!

**Comment by mkruselj** [comment]
Isn't this sort of similar to FUNs request (#868)? Except that request would require external inputs (any other modulator, or maybe even audio input)...

**Comment by baconpaul** [comment]
yeah same class of idea

**Comment by K0rrid0r** [comment]
Here is some inspiration into how FL handles formula expression.

FL Studio: Understanding Mapping Formulas
https://unaspectedstudios.wordpress.com/2016/03/09/fl-studio-understanding-mapping-formulas/2/

FL Studio: Mapping-Formula Research Thread
https://forum.image-line.com/viewtopic.php?t=203681

**Comment by mkruselj** [comment]
The waveform section should probably stay but be less tall, so that you can still see the result of your formula+slider positions, I think. Or, maybe better: envelope parameters could go away and replaced by the typing area, so the waveform display stays intact.

What say you?

**Comment by VincyZed** [comment]
Hmm... Having envelope parameters that affect the formula's result would be nice though

**Comment by mkruselj** [comment]
You could use the 5 sliders to the left do a mini envelope if need be... with weirder shapes and so on... I really think the important thing here is to be able to see the resulting waveform rather than wrapping it with an envelope. So: 5 sliders, waveform, typing area.

**Comment by sourcebox** [comment]
I wonder if making use of a scripting engine like MicroPython, Lua, etc. would be an option. Usually these engines provide support for evaluating all kind of maths and also allow control structures to be used. Scripting would be nice either ;-)

**Comment by baconpaul** [comment]
Yeah definitely. The idea originated with me threatening to put in a scheme interpreter 

Just need to pick carefully

**Comment by mkruselj** [comment]
So, after some mental excercises, I came to a conclusion that this implementation could actually totally cover issue #868. Since we could modulate the 5 sliders with other modulators... then throw that in a custom function... we basically get FUNs from VAST and then some.

However the formula interpreter should cover all those different functions available in FUNs (diode, warp, etc.), and also the y variable should be available (output from previous LFO value calculated, history). :)

**Comment by baconpaul** [comment]
Yeah. This is a really fun feature. I think I will write it for 1.7.1! But gotta finish 1.7.0 first.

**Comment by mkruselj** [comment]
Let me write up some things we should totally have in this formula modulator as part of formula parser (so, extra stuff apart from sliders A-E).

There are some mod sources you can use in Kurzweil VAST that we don't have easy access to in Surge for modulation, so let me explain. I'm thinking these could be special keywords that could be used as constant values (well, updated whenever their value changes of course) within the formula entered.

**Channel State**
Whether any notes are currently active on a given MIDI channel ("given" being MIDI channel used to play the sounding voice - relevant to MPE and also multitimbral use of Surge when scene A takes notes from channel 2, etc.). Channel State switches on whenever a note is started, and switches off when a Note Off has been received for each current note on that channel, even if notes are sustained.

**Sync State**
This unipolar control source responds to MIDI clock messages received from an external MIDI device. Sync State switches on (+1) at each clock start, and switches off (0) with each clock stop.

**A Clock**
This is a unipolar square wave that responds to MIDI clock messages. It switches to +1 and back to 0 with every clock beat. 

**B Clock**
This is similar to A Clock, but it’s bipolar - it switches from +1 to -1 with every clock beat.

**Global Phase**
These bipolar global control sources are both rising sawtooth waves that rise from -1 to +1 with each MIDI clock beat.

**Note State**
Note State can be used as a unipolar control source that responds to each note that’s played. It switches to +1 when the note starts, and stays on as long as the note is held on (by the sustain pedal, for example), or by holding down the trigger for that note. It switches to 0 when the note is no longer sustained by any means. For example, if you play a note, then hold it with the sustain pedal, its Note State is still on (+1), even if you’ve released the key that triggered the note. As soon as you release the sustain pedal, the note’s Note State switches to off (0), even if it has a long release and you can still hear the release section of the note.

**Key State**
This is a unipolar control source that responds to the motion of your MIDI controller's keys (or other note trigger). It switches to +1 when a key is pressed, and switches to 0 when the key is released. Its effect differs from Note State in that when the key that switched it on is released, it will switch off even if the note is sustained.

**Key Number**
This is a unipolar control source that generates its signal value based on the MIDI key number of each note triggered. That is, it generates a value of 0 in response to MIDI key number 0, a value of 64 in response to MIDI key number 64, and so on.

**Attack Velocity**
This unipolar control source responds to note on velocity values received. Velocity values of 0 cause it to generate a signal value of 0, while velocity values of 127 will generate a value of +1. All other velocity values will result in signal values proportionally scaled between 0 and +1.

**Attack State**
This unipolar control source switches to +1 and back to 0 very quickly with each note start, basically creating a very short pulse for every note played.

**Release State**
This unipolar control source switches to +1 when a note is released, and stays on until the note has completed its release (faded to silence), then it switches to 0. It will stay on if a note is sustained, even if its trigger is released.

**Global High Key, Global Low Key**
These control sources track the highest key currently held and the lowest key currently held respectively. By using one of these as the only source for pitch tracking, you can create monophonic-like layers within a polyphonic program. There are many other uses, too.

**Comment by baconpaul** [comment]
I think we won't use lua here, although we might, perhaps preferring faust.
but `baconpaul/19-integrate-luajit` branch shows us how we would integrate lua if we chose to
