### ISSUE TITLE
Sub/Harmonic pitch offset units for Sine oscillators

### ISSUE THREAD

**Issue by Jacky-Ligon** [surge-synthesizer/surge#2051]
Since the Sine oscillators are evolving towards functioning as operators in more complex FM algos (actually already possible with 3), such as the above TX81Z, is occurs that it would be very useful to have the option to work with entering harmonics and subharmonic units for making offsets to the oscillator pitch, as well as being able to detune away from precise sub/harmonics with at least two decimal places of accuracy.

As we know, now it's semicents (shorthand for semitones and cents) offsets, so offsetting a sine oscillator by harmonics - for example as in the below pictured 3/1 - the user must enter 19.02.

And to enter other higher harmonics:

Harmonics SemiCents
1	0.00
2	12.00
3	19.02
4	24.00
5	27.86
6	31.02
7	33.69
8	36.00
9	38.04
10	39.86
11	41.51
12	43.02
13	44.41
14	45.69
15	46.88
16   48.00

Semicents for expressing harmonics, can, for some users, be a bit non-intuitive.If this is possible, it might also be a good idea to when inputting harmonics or subharmonic offset values, for it to somehow override the Extend Range, so that wouldn't have to be set every time one needed to enter sub/harmonics greater than 3/1.

One question in such an implementation of sub/harmonic pitch offsets, is how we might deal with inputting detuning values away from the precise ratios, but I suppose if it were somehow switchable between semicents and sub/harmonic units, then it could be controlled by the sliders and typeins and stay close to the current functionality.

Anyhow, as we know, using ratios in FM algos is as old as the synthesis form itself, so it would be very useful enhancement as well in Surge. If memory serves, with the DX/TX Yamaha FM synths, it was possible to set sub/harmonics in the range of -/+ 64, and it would probably also be a good functional range for Surge as well.

[FYI/FWIW: A number of the U-He VIs have this ability, and theirs is switchable between semicents and harmonics (although, extremely oddly, ratios are displayed in the form of n-1, which has never made sense).]

![image](https://user-images.githubusercontent.com/66483816/83967408-01127d00-a88f-11ea-9e60-5ab92bc42112.png)

**Comment by Jacky-Ligon** [comment]
baconpaul

Great

And I think rmb/units is the way to go. Useful elsewhere too

Ooh so it’s interesting if tuned thought

Since pitch value is in keys

So 4==24 means if you do rmb / harmonics and enter 4 the pitch is set to 24 but if you are in ed2-19 note 24 is not what you mean note 38 is what you mean with 4

Jacky

VERY good point there.

So, the best way around this, is simply using ratios.

**Comment by Jacky-Ligon** [comment]
Jacky

Yes, on further reflection, I can see this would complicate things, when, for example one is using the SEQs for pitch-sequencing, where the requirement is to have the oscillator pitch in accord with the loaded SCL file.

If making ratio offsets and setting SCL tuning ranges are not compatible, it might be a good idea to just leave it as is.

**Comment by baconpaul** [comment]
yeah love this idea but as discussed on slack some subtlety. gonna keep this here in the 'unscheduled' milestone for now while we ponder. Thanks @Jacky-Ligon !

**Comment by Jacky-Ligon** [comment]
Let's close this one...

Upon deeper reflection, yes, I think it would be a good idea to just close #2051.

Anyone needing to create such offsets, can merely use typeins to achieve them.

I'm closing that one now. Thanks.
