### ISSUE TITLE
Host automating FM routing does not make FM Depth slider transparent when reaching NO FM.

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2056]
**Describe the bug**
Host automating FM routing does not make FM Depth slider transparent when reaching NO FM. Only manual mouse click does!

Here we can se that when the automation reach NO FM, the slider stays the same.
![43](https://user-images.githubusercontent.com/56724286/83978716-a9fdbe00-a909-11ea-8633-97757933d891.gif)

Windows 8.1

**Comment by K0rrid0r** [comment]
Same problem for the 'feedback' slider

**Comment by mkruselj** [comment]
I am not entirely sure how to fix it, so baconsignal to @baconpaul !

**Comment by K0rrid0r** [comment]
also related to this is that sometimes when i have clicked away surge and reopen it 'transparent' mode is only shown instead, when full color mode was shown before clicking surge away.

![45](https://user-images.githubusercontent.com/56724286/83979667-59d62a00-a910-11ea-904f-69f6b6a9563b.gif)

**Comment by baconpaul** [comment]
yeah that's the same problem. It will be 'whatever mode is in automation when you open the UI independent of automation. I'll get to it. It's non-mod-param silliness. Thanks for the clear report!

**Comment by tank-trax** [comment]
not getting this in Linux

**Comment by K0rrid0r** [comment]
**Another hint on this problem**

Automating the FM Routing and the click on any LFO will take the FM Depth slider to the state it should be in when either off or on.
![51](https://user-images.githubusercontent.com/56724286/84079102-48f1eb00-a9da-11ea-9040-cfe94ec02877.gif)

**Comment by baconpaul** [comment]
yes because swapping LFO forces a UI rebuild which means the slider will grab the state

The problem here is that the automation path doesn't do that (thankfully) but only impacts the param which is automated; but we now have a non-local automation graphics change we have to compensate for (that is, automation on param i changes widget i and j).
