### ISSUE TITLE
Envelope Type and External Automation

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#206]
After we fixed #160 which linked DAW parameter changes with GUI changes, only envelope type was left. envelope type is different from other params in that

1. It sets need_refresh=true in SurgeSynthesizer so skips the idle refresh
2. When using it in the GUI it also updates the picture of the ADSR envelope
3. Those things aren't obvious how to link when coming from parameters

So while almost every parameter works, this one bug remains. I'm going to drop this here as a low priority UI bug.

If you want to figure out how to fix it here's how to diagnose

1. bind your DAW to the scene a aeg filter mode. You can hear it changing but not see it.
2. Then click on digital and analog and you can see and hear it changing but you also see the envelope image changing
3. Then try setting needs_refresh=true in SurgeSytnehsizer like I did for solo and then the parameter works to change the switch
4. but then neither the parameter nor the switch change the display of the envelope

So I can get it in a state with two different bugs but not in a state with zero bugs.

**Comment by lunafreya** [comment]
Uh, @baconpaul, did you resolve the envelope type bug you said in this issue? I think this might have been fixed in the later versions of the synth.

**Comment by baconpaul** [comment]
Hey while working on #702 I found the solution to this one also.
