### ISSUE TITLE
Reverb2 lf

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2061]
@baconpaul

Jacky said 

Surge-NIGHTLY-2020-06-08-c88548a | Win-10, VST3i

Found during a sound-design session, that it seems the LF Damping in Reverb 2 isn't working.

Please confirm as time permits.

**Comment by mkruselj** [comment]
Seems to work just fine here.

**Comment by K0rrid0r** [comment]
I hear absolutely no difference in when i turn LF Damp on Reverb 2
![48](https://user-images.githubusercontent.com/56724286/84010233-aeab8c00-a974-11ea-9189-2c2f95290273.gif)

**Comment by K0rrid0r** [comment]
Listening to 47a55f0 

LF Damp on Reverb 2 still does nothing.

**Comment by baconpaul** [comment]
<img width="219" alt="Screen Shot 2020-06-09 at 8 11 40 AM" src="https://user-images.githubusercontent.com/13387561/84145976-dfe59400-aa28-11ea-8557-76c2faf9d349.png">

Really? I just tested it again

Take that setting for R2 with the init patch going into
then move LF damp to 100%
and you get a low cut
or at least I do

I can send you a patch that shows it if you want.

**Comment by K0rrid0r** [comment]
ok forget what i said, it did work, i just reloaded the plugin. wierd.
