### ISSUE TITLE
Right click does not work in transparent mode on Feedback, Width and FM Depth

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2063]
**Describe the bug**
Right click does not work on transparent mode on Feedback, Width and FM Depth

It makes planning stuff worse as you need to put it in a 'on' state to for example type in a value, if wanted. Which will potentially affect what you work on sound wise when you don't want to.

**Comment by K0rrid0r** [comment]
This is not fixed in  Surge-NIGHTLY-2020-06-08-7a5f33d  i just tried. Right click does not open a dialog window.

![49](https://user-images.githubusercontent.com/56724286/84033856-ce08e000-a999-11ea-9eae-32b1570297c7.gif)

Windows issue, maybe.

**Comment by K0rrid0r** [comment]
Double right click also has the function to put it back to init position (instead of dialog window)

![50](https://user-images.githubusercontent.com/56724286/84035981-df072080-a99c-11ea-8980-e6c79a287f92.gif)

**Comment by VincyZed** [comment]
Yup, can confirm.

**Comment by baconpaul** [comment]
OK will look

**Comment by baconpaul** [comment]
Oh sigh I tried it with Sine ones where it works and figured that was a fix; but there's another spot. Sorry bout that!

**Comment by baconpaul** [comment]
```
      if ((button & kRButton) && !(p->ctrltype == ct_lfoshape) &&
          !(ctrl != nullptr && ctrl->disabled == true)) // supress RMB on LFO Shape and hidden sliders, for LFO let CLFOGui handle it
 ```
oh the code explicitly disables it!
lemme take that out
