### ISSUE TITLE
Reverb 2 - consistent low/high cut filters

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2065]
Currently Reverb 2 is the only effect that has LF/HF Damp parameters rather than Low/High Cut that delay, chorus, sine osc have. Also the value reported is different (% vs Hz). It'd be nice to have this consistent in Surge.

**Comment by baconpaul** [comment]
As discussed in slack they are different things and are different algos so this would change the sound and cpu profile if we change the mechanism. Maybe a label change is poss

**Comment by mkruselj** [comment]
Actually scratch this one. I now see reverb 1 also has HF Damp parameter, which is different from low/high cut in the EQ section. Maybe we could just add "-ing" to make it sound a bit more human (LF/HF Damping), but that's it.
