### ISSUE TITLE
Required Binary Assets in the Binary of the Plugin (configxml etc)

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2071]
This would make it easier to test any changes in configuration.xml without needing to copy it to ProgramData or wherever else on other platforms.

**Comment by mkruselj** [comment]
The way to close this issue is by making config.xml paramconfig.xml and windows.wt all a part of the Surge binaries, rather than assets that install in ProgramData etc.

**Comment by baconpaul** [comment]
Labeleling this as juce-will-fix because it will do exactly the binary thing you describe @mkruselj and do it easily once we have cut off the pre-juce codebase

**Comment by baconpaul** [comment]
OK this all works now. Closing it!
