### ISSUE TITLE
Midi Learn on Controllers in at least the AU

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2072]
Midi Learn controller 1 or 2 or what not
Wiggle a knob
And you have learned param[1] or [2] so the FX balance moves

Related to #1999
in the family of #1994

**Comment by mkruselj** [comment]
Also happens in VST.

**Comment by baconpaul** [comment]
Cool thanks!

**Comment by baconpaul** [comment]
Huh this one was a smaller bug that had been there forever which is not related to #1999. Anyway have a fix. Will sweep.
