### ISSUE TITLE
Feature: Panic (kill) option

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#2081]
I think FL Studio can communicate with plugins to kill output sound from plugins (I know it does it with some 3rd party reverb VSTs for instance). To do this (in FL), press stop to stop playback, then press stop again to kill remaining audio from plugins. (or press Ctrl+H)
This halt "signal" is probably standard for VSTs (I suppose?)

I was wondering if there was a way to do this with Surge, to kill long remaining notes with long release.

**Comment by mkruselj** [comment]
Send CC123.

**Comment by K0rrid0r** [comment]
This STOP method worked with long remaining notes on VST2 and with VST3 it stopped working.

**Comment by baconpaul** [comment]
With the 1.6.6 or 1.7 VST2 it worked you mean? Or with the 1.5.2? (If it worked with an open source version it means I can look at the code - that's why I'm curious)

**Comment by K0rrid0r** [comment]
It worked with the last VST2 that was in the install aswel. All VST2 will stop the sound of long decay when clicking on STOP and surge VST3 does not stop the decay when doing so.

I guess it is a VST3 thing just like the QWERTY thing, a "feature".

**Comment by mkruselj** [comment]
I guess it depends what FL sends. In Reaper, Surge VST3 responds to the panic action ("send all notes off to all MIDI devices").

**Comment by baconpaul** [comment]
I do note that the suspend codepath in the VST2 and VST3 are a little different but if you call the VST3 suspend path with the right flags it should call all_processing false. Probably requires some investigation and also depends on the DAW indeed.

Anyway the work is all in SurgeVst3Processor::setProcessing - if that gets called with a state which is false, audio will shut off, just like if you cal Vst2PluginInstance::suspend

don't know what the DAWs are actually calling. Haven't looked

**Comment by VincyZed** [comment]
Oh hey it works now! Has this been tweaked with !?

**Comment by baconpaul** [comment]
Not this week

**Comment by VincyZed** [comment]
Oh well. Gonna close this I guess!
