### ISSUE TITLE
Sine oscillator waveforms cropped in display

### ISSUE THREAD

**Issue by Jacky-Ligon** [surge-synthesizer/surge#2085]
Surge-NIGHTLY-2020-06-09-47a55f0 | Win-10, VST3i

Also note in the below LICEcap, that some of the waveforms displayed at the top of the Sine oscillator control panel, have the graphical representation of the waveform extending above the frame.

Should the displayed waveforms ideally scale and fit within that frame during use?

Or is it expected behavior for them to be cropped out of the range of the display?

![LICEcap](https://user-images.githubusercontent.com/66483816/84161206-07def280-aa3d-11ea-9870-21e8331e826b.gif)

**Comment by baconpaul** [comment]
![whythetwo](https://user-images.githubusercontent.com/13387561/84165122-4ecee700-aa41-11ea-9bc0-50db03031ddf.gif)

here's why 2 is the right range

**Comment by baconpaul** [comment]
The answer here is: The oscillator display shows -0.9-0.9 and some waveforms do indeed clip it out. We've generally decided to not change this in the past. Auto-scaling seems dangerous. We could shrink all the waveforms but that seems not appropriate.

So my instinct is to close this issue but welcome feedback?

**Comment by Jacky-Ligon** [comment]
Seems a mostly insignificant issue that has no impact on the sound. 

Close it as needed, if there is no easy method for scaling the visual height of the waveform within the frame without compromising the sound of the oscillator....

Suppose the only concern is it being potentially confusing to new users after the 1.7 release.

**Comment by baconpaul** [comment]
yeah several settings of the waveform oscillator already do it; we've generally lived with it.

we could rescale based on max in the display. Or just make the display shorter. but there a bit of apples-and-apples and center-case stuff. lemme close this for now. Thanks!
