### ISSUE TITLE
cmake - make sure the VS default configuration is set to Release

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2092]
Instead of Debug.

**Comment by mkruselj** [comment]
Do we really really need the debug one? I recall you saying they're not really that useful, for some reason or another.

**Comment by mvf** [comment]
This can probably be closed.

Debug is a Visual Studio default, independent from CMake. It remembers the last-used solution configuration in its own (binary) `.suo` config file, which CMake doesn't generate. So indeed, the only way to make Visual Studio default to Release is removing the other build types. But with Debug builds starting to see some use lately, this doesn't seem feasible or even desirable anymore.

**Comment by baconpaul** [comment]
Agree
