### ISSUE TITLE
Add 'Copy with Modulation' option for SEQ LFO and FX

### ISSUE THREAD

**Issue by ghost** [surge-synthesizer/surge#2095]
From Slack discussion 20200610

Jacky  
Surge 1.7 beta Q:

When copying the settings of one modulation source (LFO, SEQ, etc.) to another modulation slot, if there are modulation assignments made to controls on the source being copied - i.e - LFOs/SEQs modulating each other's parameters, should those cross-modulation assignments - theoretically in practice - be a part of the copy?

FWIW, copying any modulation assignments from other sources, might be the ideal behavior for quickly setting up variant modulations from the copied source, thereby eliminating the need to have to reassign them after the copy. Your opinion? Any drawbacks to copying modulation assignments from other modulation sources that occur?

baconpaul  
So the way we did it with oscillators is we have “copy” and “copy with modulation” as two distinct things so the user picks. We should do the same with LFOs. Sometimes you want it sometimes you don’t basically.

Good observation that we lack the capability though (even though we have it on OSC). We should also add it to the copy/paste on FX which also is value only not value-and-mod.

Wanna toss in an issue and we can do it after 1.7.0!

**Comment by baconpaul** [comment]
While we are at it, we should add it to the FX too. Good observation!

**Comment by mkruselj** [comment]
Moreover, in FX menu we always see Copy and Paste options, whereas elsewhere Paste only shows up when there's something to copy. We should make it more consistent then for the FX menu, only show Copy and Copy with Modulation options, then once we have copied, show Paste the next time menu is opened.

**Comment by baconpaul** [comment]
As well as "Copy with modulation" we should have a "Copy Routings Only" option probably.

**Comment by mkruselj** [comment]
Yes, so that we can copy from LFO to velocity, and so on...
