### ISSUE TITLE
Restore skin engine PNG support

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2101]
Minimal feature set

- [x] Can load PNGs referenced by the skin engine
- [ ] PNG has a zoom structure in the filename somehow and enumerated zooms in the skin
- [ ] Results in fixed zooms being available
- [x] cleanly swappable between PNG and SVG skins
- [x] Support mixed PNG/SVG skins

**Comment by mkruselj** [comment]
Regarding zoom levels in PNG-based skins, here are my thoughts:

- [ ] Recognize how many zoom scales we have, either from available files in the skin folder, or via some definition in skin XML
- [ ] Options for dynamic zoom level in the menus need to be hidden for PNG-based skins, and only zoom levels which are recognized displayed
- [ ] Zoom level of PNG-based skins stored separately from dynamic zoom level of SVG-based skins
- [ ] When switching from SVG-based skin to PNG-based skin for the first time, zoom level defaults to closest zoom level of the SVG-based skin, if possible/exists. If not, load first lower zoom level available.
