### ISSUE TITLE
Resizing problem

### ISSUE THREAD

**Issue by akira242** [surge-synthesizer/surge#2103]
**Describe the bug**
Resizing doesn't work. 

![Surge](https://user-images.githubusercontent.com/66801138/84433949-68ce1c80-ac2f-11ea-85ab-131f7b2a94e2.png)

**Please let us know your surge version**

* Surge Version: 1.6.6
* Plugin type (VST2, 3 or AU)
vst2
* Bits (32/64)
64
**To Reproduce**
1. Go to 'menu'
2. Click on 'zoom'

**Expected behavior**
resizing !
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.04
4 - Host: Reaper 6.11
 - Version 6.11

**Additional context**

**Comment by baconpaul** [comment]
Does it work with the VST3?

**Comment by akira242** [comment]
surge vst3 doesn't appear, only vst2

in what folder is surge supposed to be ?

**Comment by K0rrid0r** [comment]
@akira242 your VST3 plugin appears in your default VST3 folder.

For Linux platform
On the Linux platform, the host application expects VST 3 Plug-ins to be located in:

Read here:
https://steinbergmedia.github.io/vst3_doc/vstinterfaces/vst3loc.html

**Comment by akira242** [comment]
vst2 are in /home/username/.vst

vst3 are located in the folder:
/home/username/.vst3
but there is no surge vst3 .. only my other vst3
surge must be installed in an other folder....but where?

**Comment by baconpaul** [comment]
how did you install surge?
I also wonder if 1.6.6 didn't include the VST3.
but it is probably in /usr/lib/vst3 if the .deb installed it and would be in /home/username/.vst3 if you built it with build-linux

As of surge 1.7 (and the current nightly) we no longer distribute a VST2 and we basically no longer support it. We've done a lot of work with the linux community to make our vst3 viable, though, and the nightly version and the 1.7 will be. If I remember, though, the 1.6.6 version also worked fine in linux reaper

**Comment by akira242** [comment]
I simply installed the paquet via surge.deb 
you're right .. it's where you said.../usr/lib/vst3   but reaper doesn't detect it
I tried to move it in /home/username/.vst3 but it doesn't work

**Comment by baconpaul** [comment]
have you set reaper's plugin scan path to look in either of those locations?
reaper also has an option to show 2 over 3, 3 over 2, or both, if I recall. Is that set properly?

**Comment by tank-trax** [comment]
OS: Linux Debian Buster 
Host: Reaper 5.11
Surge version: VST3 

When using Reaper 5.11 and Surge VST3 the resize/stretch works properly. 

OS: Linux Debian Buster 
Host: Reaper 5.11
Surge version: VST2 

For the VST2 there is no stretch feature and it's necessary to use the Zoom function. However in Reaper after resizing (with zoom), the FX: Track window needs to be closed and reopened for Surge to draw to it's correct zoom level. 

This issue looks like #845

**Comment by tank-trax** [comment]
the VST3 in system install should be in

`/usr/lib/vst3`

**Comment by tank-trax** [comment]
commit 9586c2d

There is an issue with the VST2. Now I have to resize, set zoom level to default, delete plugin and then reload for it to draw properly. VST3 works perfectly.

**Comment by tank-trax** [comment]
Now, it's working for zoom smaller but zoom bigger needs Reaper's FX Browser to be resized to match it. 

Zoom down to 150, 125 and 100 work

Zoom up to 125 is OK. Up to 150 requires resizing of outer window.

I got it. If I start Surge VST2 at 160% as its default any resizing works from 100% to 160%. Anything above 160 will be 

![Screenshot_20200611_214002](https://user-images.githubusercontent.com/41337033/84455765-248d4d00-ac2c-11ea-9466-342e9b57ef01.png)

**Comment by baconpaul** [comment]
oh yeah i remember something like that with the vst2 not being able to grow beyond its original size in reaper, vaguely. I think the fix stumped me back when I was working on VST2.

**Comment by akira242** [comment]
> have you set reaper's plugin scan path to look in either of those locations?
> reaper also has an option to show 2 over 3, 3 over 2, or both, if I recall. Is that set properly?

done ! and it solves the problem...I can use surge vst3 with resizing :) Thanks a lot Guys ! (same resizing problem with TAL vst2 by the way)
it's not the topic but an other problem is I can only move really slowly the faders. If I try to move them fast, it's not smooth...very buggy...maybe it's a known problem ?
Anyway, this is one of my favorites synths (top 3 with Tyrell and Diva)... I love its sound, the presets are awesome !! Thanks for your work on it !

**Comment by baconpaul** [comment]
We have fixed the slow sliders in the nightly and the general linux graphics performance is about 10x better there. You can run the nightly from our website - it is getting pretty stable - or wait until we ship it as 1.7 later this summer. So I’m going to close this issue, not because you are wrong, but rather because I think we got to it already!

Thanks!

**Comment by baconpaul** [comment]
Oh and glad you enjoy the synth! Thanks for the nice words
