### ISSUE TITLE
"Apply .scl file tuning" does nothing

### ISSUE THREAD

**Issue by barudaret** [surge-synthesizer/surge#2107]
**Describe the bug**
In the manual, it says if you want to change the tuning scheme, you right-click the "tun" button (or go through the menu on the bottom right) and click "Apply .scl file tuning".  However, I have tried the menu and the tun button, and after I click the "Apply .scl file tuning" menu option, nothing happens.  It doesn't prompt me to locate the file or anything.

**Please let us know your surge version**
This information is all in the menu/about screen
I'm using Surge-linux-x64-1.6.6.deb from the github.io website.  Specifically, I'm using the LV2 version

* Surge Version:  	**1.6.6**
* Plugin type (VST2, 3 or AU):	**LV2**
* Bits (32/64): 	**64-bit**

**To Reproduce**
1. Right click 'tun' button
2. Click on 'Apply .scl file tuning'
3. Observe that nothing happens

**Expected behavior**
I don't know what the prompt *should* look like, but I expect to be prompted.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10]	**Gentoo Linux amd64**
 - Host [e.g. bitwig, logic]	**Ardour**
 - Version [e.g. 2.4] 	**6.0**

**Additional context**
n/a

**Comment by baconpaul** [comment]
If you are Linux you will need zenity installed for that to work - is zenity in your path? If it is not an error will go to stdout but your daw may not show it.

**Comment by barudaret** [comment]
It's not in my path.  I'll get that later today and see if it works.  If you're confident that zenity is the problem, then let's just close the issue.  I'll reopen if it turns out to be something else.

**Comment by barudaret** [comment]
Indeed, installing zenity solved it

**Comment by baconpaul** [comment]
Cool
zenity is in the depends: in the .deb file it seems. Is it specified in a way which didn't work on gentoo?
Thanks so much!

**Comment by barudaret** [comment]
Gentoo just doesn't use dpkg.  So to install, what I did was extract the .deb with `ar xv file.deb` and just grabbed the plugin.  Dependency resolution wasn't a part of the process.

**Comment by baconpaul** [comment]
Gotcha. Thanks!
