### ISSUE TITLE
Surge crashes after adding sync on 4x detuned saw wave in absolute mode

### ISSUE THREAD

**Issue by iCodeCoolStuff** [surge-synthesizer/surge#2112]
**Describe the bug**
surge seems to crash my entire DAW after adding a bit of sync on a 4x saw wave but only in absolute mode

**Please let us know your surge version**
![Capture](https://user-images.githubusercontent.com/25804565/84577859-ec058480-ad8d-11ea-8cfe-5f4d64019d1f.PNG)

* Surge Version: 
64 bit VST3 latest version iirc

**To Reproduce**
Add 4 unison voices on a saw wave, detune in absolute mode, and increase sync.

**Expected behavior**
Surge should not crash my DAW

**Video Evidence**
https://youtu.be/O-JCQpPP5yE

**Desktop (please complete the following information):**
Windows 10 with Ableton Live 10 Standard

**Additional context**

**Comment by VincyZed** [comment]
Good find! Thank you for the video, I can reproduce in FL Studio 20.7.1.

**Comment by VincyZed** [comment]
Upon further testing, the number of Unison Voices does not affect this. It still crashes with 1 voice. It's the Absolute detune that seems to cause the problem.

**Comment by baconpaul** [comment]
My guess is this is #1847 plus an FPE exception blowing up your DAW.
Thanks for the report.

**Comment by K0rrid0r** [comment]
I can confirm exactly the same crash, just tried.

**Comment by baconpaul** [comment]
fwiw it doesn't crash on mac, which further makes me think this is #1847 plus different os dealing with divide by zero and the like differently

I'll peek and sure I'll find the fix. Thanks.

**Comment by baconpaul** [comment]
@VincyZed thanks for merging that fix.
@iCodeCoolStuff this is fixed at master. Will be fixed in the nightly in about 45 minutes. And fix will be in 1.7.0. Thanks.
I’m also convinced that change will close #1847 too so lemme go close that.
