### ISSUE TITLE
RMB Modulator Display for inter-LFO modulations

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2119]
If you modulate, say, LFO1 -> OSC1 pitch, and rm on osc1 pitch you see a modulation from lfo1, and similarly if you rm on lfo1 you see a modulation to osc1 pitch.

If you modulate, say, LFO1 -> LFO2 rate, and rm on LFO 1 you see attachment to lfo2 rate, but you don't see the inbound.

bit tricky so push it out of the 1.7.0 milestone but still should fix.

**Comment by baconpaul** [comment]
So this was a semi-misguided comment. If you click on LFO2 rate you do see the modulation inbound
If you click on the LFO2 CModulationSource you don't
I don't think we want the modulation source button to show all the inbound modulations to all the points in the source, when they are in the UI below.
So I'm going to close this as mis-specified.

**Comment by mkruselj** [comment]
We still have a bit of a visual issue there tho.

This is when right-clicking the LFO 1 modbutton:

![image](https://user-images.githubusercontent.com/2393720/105997384-d722fa80-60ab-11eb-8915-c94231628ac1.png)

This is when right-clicking the LFO 2 Rate slider:

![image](https://user-images.githubusercontent.com/2393720/105997420-e3a75300-60ab-11eb-9935-45b2dd246c58.png)

It's missing "LFO 2" designation before rate.
