### ISSUE TITLE
Disablement states not included in oscillator, Scene, or FX copy

### ISSUE THREAD

**Issue by Jacky-Ligon** [surge-synthesizer/surge#2124]
Surge-NIGHTLY-2020-06-16-e79664b | Win-10, VST3i
Oscillator HPF-LPF states not included in oscillator copy 

Note that the copy behavior is the same for all oscillator types that feature the new HPF-LPF filters:

**Window, Sine, S&H Noise, Audio In**

![LICEcap](https://user-images.githubusercontent.com/66483816/84774998-9ce96a80-afac-11ea-96bf-07107ecdb5e7.gif)

**Audio In Observation**
Also, it's somewhat curious that there is the ability to select up to three **Audio In** per scene, being that in such a scenario, duplicate input channels would be passed through, with only the ability to RM (Mixer section) or FM (Oscillator FM Routing section), these duplicate inputs.

**Comment by baconpaul** [comment]
Oh excellent catch thank you

**Comment by baconpaul** [comment]
The same will be true for deactivated state in dc copy
