### ISSUE TITLE
MIDI PB/MW mapped to Scene Pitch, accurate in 12-equal, but not with loaded SCL files...

### ISSUE THREAD

**Issue by ghost** [surge-synthesizer/surge#2125]
Hybrid, bug-like behavior observation / FR to follow.

**Surge-NIGHTLY-2020-06-16-e79664b | Win-10, VST3i**
**MIDI PB/MW mapped to Scene Pitch, accurate in 12-equal, but not with loaded SCL files...**

Attached are two presets, one with a rational pentatonic mode embedded, the other without. Since the mode is rational, and not an equal-temperament, there will be different intervals on each starting point in the scale.

Both of these have the MIDI Pitch-Wheel, and Mod-Wheel mapped to modulate pitch-bend, and vibrato, with the former set for an interval of 151 cents (12/11) and the latter at 55 cents (32/31).

With, **DX EP without SCL.fxp**, which is essentially in 12-tone-equal-temperament, the cents intervals for pitch-bend and vibrato are rendered perfectly accurately, and one can bend up/down a precise 12/11 @151 cents, and when pushing the Mod-Wheel forward, introduce vibrato up to a depth of 32/31 @55 cents.

However, with, **DX EP with SCL.fxp**, the pitch-bend and vibrato range are rendered sharp when there is a SCL file loaded, the offset, which is likely due to some unforeseen interaction with the way Oscillator Pitch works with loaded SCL files.

If possible, and won't conflict with the way the microtuning implementation currently works, it would be helpful to be able to make these MIDI controller mappings, and have them be able to accurately render the pitch-bend and vibrato intervals in terms of (semi)cents, when SCL files are loaded. 

The application here, is being able to setup arbitrary microtonal pitch/vibrato ranges at the **Scene Pitch** level (global pitch-modulation), and are added (multiplied actually) with the **Oscillator Pitch** that interact with loaded SCL files.

[Presets-PB-MW-issue.zip](https://github.com/surge-synthesizer/surge/files/4788638/Presets-PB-MW-issue.zip)

![Surge-NIGHTLY-2020-06-16-e79664b](https://user-images.githubusercontent.com/66483816/84816926-70504580-afe2-11ea-9157-1f8e9327aeb5.png)

**Comment by baconpaul** [comment]
So pitch bend is in key space. If you load a scale where the interval between key 60 and 61 is a whole step, press key 60, and have pitch bend 1, and bend up, you will go up a whole step, not a semitone. Is that what you are seeing? When you say 'rendered sharp' do you mean 'rendered sharp compared with the tuning' or 'rendered sharp compared with 12TET`? See what I mean!

**Comment by baconpaul** [comment]
My comments from Slack on this:

So
7:17
The way surge works is we pass modulated pitch to the oscillator
7:17
The oscillator is responsible for turn in that into the appropriate internal representation of frequency using the tuning tables
7:17
So the oscillator just sees a single number (pitch) and the bend wheel is happened way way way outside (in the synthesizer controls)
7:19
to make it work like you say, Jacky, we would either have to basically re-write the entire modulation infrastructure to do modulation inside the oscillator (which would be a nightmare); pass a vector of pitch modulators which we treat differently based on which modulator property it is (which would be a big change) or ‘reverse’ solve the frequency from the pitch bend into a note to modualate. (So ‘151cents is 1.2 keys from C4 but 3.7keys from G4, in your particular tuning, say)
7:19
The later we actually do to handle absolute mode in a couple of spots. Basically we reverse-lookup the note shift to get the desired frequency shift.
7:20
We could do that with pitchwheel also (edited) 
7:20
and that’s what I’d recommend
7:20
But it is not a small change indeed

https://github.com/surge-synthesizer/surge/blob/e79664b3133c825b7b7ff7e7e8510142f5e89d87/src/common/dsp/SurgeVoice.h#L61

src/common/dsp/SurgeVoice.h:61
   inline float noteShiftFromPitchParam( float note0 /* the key + octave */, int oscNum /* The osc for pitch diffs */)
<https://github.com/surge-synthesizer/surge|surge-synthesizer/surge>surge-synthesizer/surge | Added by GitHub





7:22
There’s the reverse solve for oscillator pitch being absolute with a tuning table in place

**Comment by Jacky-Ligon** [comment]
Shall we close this now after the discussion yesterday?

**Comment by baconpaul** [comment]
nah lets leave it open. I pasted the comments above since it is possible to have the pitchbend work both ways using the solve like I suggested. Just it is a bit of far reaching work.

**Comment by baconpaul** [comment]
So lets keep it on the 'idea we had and might do one day' list! We would need a 'pitchbend mode parameter' though which is another obstacle in our way.

**Comment by Jacky-Ligon** [comment]
OK - agreed.

**Comment by mkruselj** [comment]
> We would need a 'pitchbend mode parameter' though which is another obstacle in our way.

Right-click, absolute mode? :)

**Comment by mkruselj** [comment]
This issue is now resolved by adding "Tuning applies to modulation" option @baconpaul did the other day.
