### ISSUE TITLE
Switching scenes in Single mode should not stop voices

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2126]
Currently, when we're in Single mode, and we go from one scene to another while some voices are playing, those voices are hard stopped. It would be pretty useful if we could switch scenes without such interruptions. I can also see the usefulness of this in live performance, where you could easily have two different sounds available without requiring MIDI Program Change messages.

Example: I play in scene A, holding MIDI note 60, it has a sustaining envelope. Now I switch to scene B. Scene A MIDI note 60 still keeps on playing until I release that key. If I held sustain pedal before I released that key, it should also keep on sustaining the scene A voice, all the way until I release the sustain pedal. If, during this sustain pedal holding, I play another MIDI note 60, that one should only play scene B, not scene A.

It is probably a bit tricky to get right, but it would be SO great to have it working like that!

**Comment by baconpaul** [comment]
Hard....

**Comment by mkruselj** [comment]
I concur, but I suppose we can't always have easy issues to solve :)

**Comment by mkruselj** [comment]
OK so I've come to accept this particular request is probably not really feasible with the way Surge's voice allocation mechanism is done. So we can close it.
