### ISSUE TITLE
Finish implementing deactivate for the LFO Rate parameter

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#2127]
WIP: see 0561cf4 for what has been done so far.

So at the moment the only things left to complete this implementation are the following:

- First, LFO Rate must be **activated** by default. Right now, despite attempting to make it that way, it still gets deactivated when loading the synth.

Steps that have been done from Paul over on Slack:
1. Parameter.h. assign gets another argument bool defaultDeactivation = true

2. Parameter.cpp assign gets the argument bool defaultDeactivation and after the clear_flags sets deactivate to defaultDeactivation

3. SurgePatch.spp where you see a->push_back( sc[s].lfo[l]rate.assign(…) stick a false as the last argument

For some reason, it still doesn't work.

-  Second, the LFO waveform display should still show the waveform using the Rate slider's value even when Rate is disabled. At the moment, it takes the value that's being processed in the Synth (aka 0.0 Hz). So this needs a sort of hack in CLFOGui.cpp

**Comment by baconpaul** [comment]
gonna peek now and see if I can spot it
