### ISSUE TITLE
Use a custom and uniform font

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#214]
The design folks would love to use the open font @cyanit @itsmedavep 
https://fonts.google.com/specimen/Lato

To use it reliably in draws we would want to include it in the resources so we can load it in app without requiring it installed on the underlying system. That’s platform dependent.

It also may or may be something we get done. But lets put an issue in place since it would make painted labels more consistent with vector graphics and stuff if we use a scalable vector thingy.

On windows and linux I haven’t googled yet. On Mac I found this:

ATSApplicationFontsPath (String - macOS) identifies the location of a font file or directory of fonts in the bundle’s Resources directory. If present, macOS activates the fonts at the specified path for use by the bundled app. The fonts are activated only for the bundled app and not for the system as a whole. The path itself should be specified as a relative directory of the bundle’s Resources directory. For example, if a directory of fonts was at the path /Applications/MyApp.app/Contents/Resources/Stuff/MyFonts/, you should specify the string Stuff/MyFonts/ for the value of this key.

**Comment by jsakkine** [comment]
Just a question (haven't studied sources) but how does the text rendering work at the moment? VSTGUI stuff uses its own path and stuff on screen other one?

**Comment by kurasu** [comment]
Lato is perfect, its very pretty and and renders digits at constant size so its very well suited to numerical diplays. 

@jsakkine 
I'd assume VSTGUI just uses the platform font rendering, nothing custom. We don't want a fixed-size font for stylistic reasons, and any optimizations needed can be done at a string-level instead of character level. But since we're hardly doing any text rendering at real-time intervals anyway (apart form the text-popup on mouse-drag) I don't see how this sholud ever be an issue.

**Comment by baconpaul** [comment]
yeah I think there's really no cpu benefit from a fixed width font nowadays and the UI is all double buffered properly anyway. 

@kurasu yup the vstgui uses the installed platform font tools in the PlatformFont class underneath CFont it seems. I took a quick tour after I opened this issue. Right now the 3 fonts we use in surge seem to be Lucida Grande (mac), MS Sans Serif and Arial (windows); and the "system small font" about screen.

But this issue is really about "how do we include a ttf file with our bundle which is loadable".

**Comment by jsakkine** [comment]
OK, cool. Where is the text/number rendering code located for on-screen display?

**Comment by baconpaul** [comment]
It’s all in the vstgui lib. Look in src for setFont and you will find the draw command. Pull from there

The font object will load any ttf file which is in your path. How do you include it in the bundle and put it in the path?

**Comment by baconpaul** [comment]
Well just a bit of experimenting tells me ATSAPplicationFont doesn't work for .component bundles.

**Comment by baconpaul** [comment]
https://docs.microsoft.com/en-us/windows/desktop/api/wingdi/nf-wingdi-addfontmemresourceex for my windows attempt too

**Comment by baconpaul** [comment]
https://developer.apple.com/documentation/coretext/1499468-ctfontmanagerregisterfontsforurl?language=objc sorry to spam this issue with my notes but I keep getting 5 minute windows to look and don't want to forget

**Comment by baconpaul** [comment]
<img width="1353" alt="screen shot 2019-02-08 at 5 04 25 pm" src="https://user-images.githubusercontent.com/13387561/52508789-c083f000-2bc3-11e9-9804-d64740e17fde.png">

I don't have Lato installed on my mac, but here's a surge running with lato that it loads from the bundle.

Windows next.

**Comment by baconpaul** [comment]
Sigh OK so this is easy to make work on mac but harder on windows. Let me put my notes here 

VSTGUI uses direct2d api for drawing. That means the platform font is a direct2d font created with the direct2dfactor->CreateTExtFormat method. This happens in vstgui/lib/platform/win32/direct2d/d2dfont.cpp

Now unfortunately vstgui sets the font factory to "NULL" which means use the system factory, and there's no way through the vstgui API to tell it otherwise. So I'm down in direct2d code trying to figure it out rather than the easy AddResourceFontEx thing above.

May clean up and PR mac on its own just to get us rolling. Still debating.

**Comment by baconpaul** [comment]
OK decided to move us forward with MacOS only. I think Linux may actually be the more important next choice to be honest, since the fonts there are more haphazardly chosen and some users had crashes. Will peek at that code for a few minutes but then I'm mostly offline for the weekend.

**Comment by baconpaul** [comment]
So with Windows and Linux it won't be quite as easy, mostly because the VSTGUI API is a bit in our way. Basically we need to be able to reset the PlatformFont on a CFont object. The PlatformFont for linux just has a cairo_font thingy inside which is easy to create from a binary but we have to thread it through.

So we have a couple of options

1: We can modify vstgui a bunch to allow us to weave stuff through. I don't recommend this
2: We can make local subclasses of CFontDesc which allow us to reset the platform font, and then of the IPlatformFont for each of linux and windows.

Basically where CFontDesc::getPlatformFont does if(platformFont==null) platformFont=IPlatformFont::create we want to have set the platformFont before then.

on linux we want to set it to a subclass of platform/linux/cairofont.cpp's Cairo::Font which has the binary load

on windows we want to set it to a subclass of platform/win32/direct2d/d2dfont.cpp's D2DFont which basically has the nasty CreateTExtFormat hack you can google

And then force the subclass back up in probably using the CFontDesc copy constructor

Something like that lets us add our API without having to gut vstgui

Not easy. But not impossible. But not tonight.
