### ISSUE TITLE
R2 Width is Wrong

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2140]
@mkruselj said this 

> Width in Reverb 2 is now bipolar dB just like all other widths (but code needs tweaking so that it behaves like width in all other FX)

so we should fix that

**Comment by baconpaul** [comment]
when @mkruselj changed the type to db_narrow (which is great) also needed to change the width.set_target to use a db_to_linear on the value.

Now all fixed!

**Comment by mkruselj** [comment]
Ha that makes sense! Nice to have it fixed and consistent!

1.7.0 here we come! :)
