### ISSUE TITLE
Complete Modulation Value From String Functions (was invalid values in mod typein)

### ISSUE THREAD

**Issue by Jacky-Ligon** [surge-synthesizer/surge#2141]
**Surge-NIGHTLY-2020-06-17-b3322ff | Win-10, VST3i**

In the attached GIF, which shows modulation routings to the Mixer channel levels, one can see that an **Invalid Entry** message is displayed when trying to typein dB values.

What are the expected units there for modulation ranges, if not dB?

![LICEcap](https://user-images.githubusercontent.com/66483816/84963491-8a1f8480-b0d7-11ea-9712-8b1b542d2b43.gif)

**Comment by baconpaul** [comment]
@mkruselj I think this is because you did the format side of mod but not the type side
@Jacky-Ligon the answer (for now) is [-1,1] but obviously that needs to be addressed. Great find thanks!

**Comment by baconpaul** [comment]
Oh and that's because I didn't give you an API point for that. Doh. OK I'll add that and then we have more code to write.

**Comment by Jacky-Ligon** [comment]
Addendum:

In the below GIF, one can see that the modulation range can be set to -24 dB by manually moving the slider whilst holding Shift, but when trying to type in the very same value, one gets the Invalid Entry warning.

![LICEcap](https://user-images.githubusercontent.com/66483816/84964451-25195e00-b0da-11ea-9abe-21125c0b71e9.gif)

**Comment by baconpaul** [comment]
So plan of attack

1: add parameter::calculate_modulation_from_string which takes a string and returns a value in range -1,1
2: implement it following line 3588 of SurgeGUIEditor.cpp, and call it there
3. Hand it over to @mkruselj to write the code

**Comment by Jacky-Ligon** [comment]
Thanks for the look.

**Comment by baconpaul** [comment]
Thanks for the find!

**Comment by Jacky-Ligon** [comment]
Surge-NIGHTLY-2020-06-18-8a122b5 | Win-10, VST3i

FYI: Same applies to the Sine-Osc Feedback control when making modulation routings. 

For example, when modulating the Feedback slider with an LFO, it's possible to drag the slider to a value of -25%, but trying to type in -25 shows and Invalid Entry warning.

Let me know how I can help test this further. It appears to manifest in a number of places, although I've not yet systematically tried to test or document them all.

**Comment by baconpaul** [comment]
They are all wrong! No need to be systematic 

Basically the display code is written but the parse code is not so the typeins are all still in min/max without units

**Comment by mkruselj** [comment]
The work I did last night on mod amounts was not related to typrins at all, just display values...

**Comment by mkruselj** [comment]
> So plan of attack
> 
> 1: add parameter::calculate_modulation_from_string which takes a string and returns a value in range -1,1
> 2: implement it following line 3588 of SurgeGUIEditor.cpp, and call it there
> 3. Hand it over to @mkruselj to write the code

Why couldn't we use the already existing set_value_from_string method?

**Comment by baconpaul** [comment]
> > So plan of attack
> > 1: add parameter::calculate_modulation_from_string which takes a string and returns a value in range -1,1
> > 2: implement it following line 3588 of SurgeGUIEditor.cpp, and call it there
> > 3. Hand it over to @mkruselj to write the code
> 
> Why couldn't we use the already existing set_value_from_string method?

Because the modulation calculation is a different calculation in a different spot. Will have set_modulation_value_from_string with a slightly different prototype.

**Comment by baconpaul** [comment]
This is done; bug list in #2229
