### ISSUE TITLE
Disable Rate and Phase/Shuffle in Envelope LFO mode

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#2151]
Since Rate and Phase/Shuffle don't have any functionality (at the moment) when the LFO type is set to Envelope, we should make these 2 transparent (disable them) when in envelope mode, like we do for FM Depth, Filter Feedback and Width for certain FM and filter routings.

**Comment by K0rrid0r** [comment]
What could they actually do if they had a function in the ENV? Any creative ideas ? 👂

**Comment by VincyZed** [comment]
Actually I thought about that, and just opened issue #2152. If that ends up working this issue will be closed.

**Comment by mkruselj** [comment]
@VincyZed Paul cracked this one finally! 🙂

**Comment by VincyZed** [comment]
Thank you @baconpaul ! :)
