### ISSUE TITLE
Modulation timings get broken on certain patches when opening up Sequence -> Acid Seq 1

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#2158]
**Description:**
This is a very weird bug where opening up the **Acid Seq 1** factory preset breaks speed / timings of certain modulations on certain patches. The affected patches **seem** to be patches related to the new features recently implemented (LFO freezing and manual single-cycle value travel), as "Chord Me" and this new Test patch I made are both affected, although this could affect more patches, I haven't thoroughly tested other ones. Also there might be more patches other than Acid Seq 1 that triggers the bug. Again, haven't thoroughly tested other ones. 

**Surge Version:**
Latest nightly, VST3, x64

**Desktop (please complete the following information):**
Windows 10 x64, FL Studio 20.7.1 (Release Candidate 2)

**To Reproduce**
Here's a video demonstrating the issue. Pay particular attention to the rhythmic pattern created by the filter modulation and how it interacts with the background drum loop.

https://youtu.be/JrOWmvddNKk

Here's the Test patch used in the video:
[Test.zip](https://github.com/surge-synthesizer/surge/files/4802277/Test.zip)

**Additional context**
So couple of things to note here:
1. The modulation speed of the first instance of Surge is dead on. This is our reference, and this is how it should sound like. When loading a new Surge instance and going straight to this Test patch, this is how it behaves.
2. When cloning the **Surge#2** (after the bug is triggered) to create **Surge#3**, notice how it now gets fixed (until I trigger the bug again). This means that the value of all parameters gets restored correctly, and that it's not a patch loading issue.
3. **Surge#2** and **Surge#3** 's modulation becomes **too fast** when the bug is triggered, where as **Surge#4**'s modulation becomes **too slow**. This behavior seems to be random; sometimes it gets faster, sometimes slower.
4. Cloning has no impact on this issue. Loading a fresh instance of Surge instead, then load the Test patch before reproducing the bug does the same thing.

Will investigate and post more comments if I find anything interesting.

**Comment by baconpaul** [comment]
Are these temposynced? I wonder if the sync ratio and transport handling is incorrect. We should try and reproduce in other daws and other flavors too to see.

**Comment by VincyZed** [comment]
In the Test patch, SLFO1, the one who is controlling the frozen LFO1, is tempo-synced, yes.
In Acid Seq 1, only 1 of the 3 step sequencers is tempo-synced.
I will to reproduce in reaper.

**Comment by VincyZed** [comment]
OK so I can reproduce this in Reaper as well.

**Comment by baconpaul** [comment]
Yeah a simpler version still

1. Start a fresh logic pro add a surge AU, set it to your sync test
2. Draw a 4 measure loop holding a c, put it in loop mode
3. press play - in sync
4. load up acid seq press play - in sync
5. re-load up sync test - out of sync

Something is making the SLFO run fast. I wonder what.

**Comment by baconpaul** [comment]
Even simpler. You don't need your sync test patch. Just have a simple patch which has 1/2 note SLFO modulating pitch in freerun and that's it. Works fine. Load acid seq. Reload. Works wrong.

**Comment by baconpaul** [comment]
I see Acid Seq has SLFO1 as a step sequencer. Wonder if that's it. Clearly some state is not getting reset properly when we swap back and forth and it's leaving the SLFO in a wedged state.

Great bug find. Really great. Thank you very much. "Good bug reports make good software" etc...

And this is all just me typing into GitHub because I don't quite have a plan to debug it yet ... next step is admit defeat on slack then I'm sure I'll get it. Chuckle.
