### ISSUE TITLE
Surge VST3 GUI lags on reopen in JUCE6 hosts

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#2159]
Surge VST3 commit 2c00e59
Carla 2.2.0-beta1
Debian Buster 10.3

When opening Surge for the first time the GUI displays quickly, however if minimized and re-opened takes an inordinate amount of time for the GUI to [load](https://www.youtube.com/watch?v=yB9-fhSepAc).

@baconpaul 
@falkTX

**Comment by baconpaul** [comment]
remind me again how do i get carla with vst3 support installed? Thanks!

**Comment by tank-trax** [comment]
on Linux have to add the KXStudio repo and then download that carla-git version

**Comment by baconpaul** [comment]
OK the relatively current JUCE6 AudioPluginHost exhibits the same behavior. Nothing to do with Carla (except inasmuch as Carla uses JUCE for VST3 hosting). I can debug in APH easily.

**Comment by baconpaul** [comment]
And I've found it

It seems the order of us creating widgets and the order of the XCB callback means that the frame gets its invalidation message out of order with show sometimes, leaving to the un-refresh frame. There's lots of complicated things I could do to solve this i bet, including debugging that order of creation, but instead what I'm doing is just forcing a call to frame->invalid() the first time through the idle loop, which fixes it. Push incoming. 

Thanks for the report @tank-trax !!

**Comment by tank-trax** [comment]
using commit ea02a68 the lag issue has improved in Carla but still exists
I hadn't tried AudioPluginHost prior to the fix but currently there is no lag in APH
I checked my render settings to see if that would improve it and it hadn't
There is no lag in Carla using the VST2

**Comment by tank-trax** [comment]
If the mouse is passed over the GUI it paints immediately. Tested at various zoom levels.

**Comment by baconpaul** [comment]
Yeah but with the fix this afternoon, it also repaints near immediately (at most 2 idles) for me in Carla-git. Do you not see that?

**Comment by tank-trax** [comment]
the redraw thing is better is Carla
however the VST3 does not remember its position
and when opened larger than 100% will straddle both screens
the VST2 when closed and opened will reopen in the place it was when it was closed

**Comment by baconpaul** [comment]
The VST3 API doesn’t give us an option on positioning our screen - the issue you describe is all in the DAW. I don’t think there’s more i can fix in surge here (although if there is I would be happy to do so of course). Wonder if we should open a new issue on KX repo?

**Comment by tank-trax** [comment]
I agree. I tested the VST3 versions of ACE, Podolski, Diva and Zebra and they also draw across two monitors.
