### ISSUE TITLE
negative deform values are not reflected in noise/S&H LFO waveform display

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2164]
Negative deform values are not reflected in noise/S&H LFO waveform display anymore.

VST3, 09c2a4e

![89](https://user-images.githubusercontent.com/56724286/85207900-55583b00-b32c-11ea-91ac-1c26057d6cb4.gif)

Probaby the new clamps on the noise source in the LFO.

This is what it should look like.
![90](https://user-images.githubusercontent.com/56724286/85208306-7a9a7880-b32f-11ea-8fa0-1a08ca94cecc.gif)

**Comment by baconpaul** [comment]
yeah these are the stability clamps i put in having the wrong range
