### ISSUE TITLE
Modulating 'Max Frequency" will blow up/clip the vocoder

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2167]
**Describe the bug**
Modulating 'Max Frequency" will blow up/clip the vocoder

**Please let us know your surge version**
VST3, 09c2a4e

**To Reproduce**
Activate the vocoder like normal and just modulate the Max Frequency, it blows up real quick and real loud.

![91](https://user-images.githubusercontent.com/56724286/85209358-82f6b180-b337-11ea-969a-b1120f546b2d.gif)

**Comment by baconpaul** [comment]
yeah i think the problem here is that the max of the slider is chosen at the top of the stable range and this pushes you out of it. Lemme tag this 1.7.beta.1 and see if I can put a clamp in. If that doesn't fix it I'll move it out of the 1.7.0 milestone.

**Comment by baconpaul** [comment]
Yup just a simple limit. Pushing now.
