### ISSUE TITLE
Ring Mod clips if modulated to max.

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2169]
**Describe the bug**
Ring Mod clips if modulated to max.

**Please let us know your surge version**
VST3, 09c2a4e

Just open init preset of the effect and send a sine LFO and modulate max and it will clip.
![92](https://user-images.githubusercontent.com/56724286/85210626-d241df80-b341-11ea-898d-38e6edfbfc9d.gif)

**Comment by baconpaul** [comment]
Just fixed this.
