### ISSUE TITLE
Uniform way to show errors to users

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#217]
if you `grep -r MessageBox` in src you see it shows up some, and as I'm writing wav file reader on mac, the condition which causes us to call it may show up more. In the SurgeStorageLoadWavetable even better it defines a function called error_msg which does nothing with errors. There's a lot of fprintf(stderr on mac and linux as well which doesn't help get to most users.

So I think we need to do something like have an entry point like "displayErrorToUser( title, string )" which pops a reasonable modal error message with an OK button and then go cleanup code.

Probably the way I would do this, but I'm happy to listen to other suggestions, is in SurgeSynthesizer add something like

```
public:
   static void displayErrorToUser( const char* title, const char* msg );
   static void setDisplayErrorHandler( std::function<...> f );
private:
   static std::function<...> s_displayErrorHandler
```

and have the default displayErrorHandler be fprintf(stderr). Then in the SurgeGUIEditor constructor set a display handler that does GUI stuff. That way if we want to use Surge in a headless-y mode sometime in the future we can still see user errors.

Not coding this now. Comments on design welcome.

**Comment by jsakkine** [comment]
Some questions on top of my head: 

- Why they need to be inside a class? I don't see any special association to `SurgeSynthetizer`? Alternative would be to have something like `Error.h` and global functions.
- Why `setDisplayErrorHandler()` is needed? Why not just have the platform magic inside `displayErrorToUser()`?
- Why `displayErrorToUser()` and not just `displayError()`? Doesn't everything displayed go to user?

**Comment by baconpaul** [comment]
The reason to have a handler is part of me is thinking about a GUI-less surge and so being able to pick your handler matters. 

The rest all make sense to me.

**Comment by jsakkine** [comment]
@whydoubt, how does VSTGUI expose `GtkWindow`? Would be needed to use `GtkMessageDialog`: https://developer.gnome.org/gtk3/stable/GtkMessageDialog.html

**Comment by jsakkine** [comment]
@baconpaul, @kurasu: proposal for new plug-in creation sequence

1. `new SurgeGUIEditor()` (does not take synth)
2. `new SurgeSynthesizer()`
3. `editor->setSynthesizer(synthesizer)`

This way we can use VSTGUI straight from the epoch.

**Comment by whydoubt** [comment]
@jsakkine Regarding VSTGUI and GtkWindow: FWIW, note that VSTGUI has been stripping out uses of Gtk and is targeting lower-level libraries instead.

**Comment by jsakkine** [comment]
@whydoubt, OK, that was useful remark. For VST2 I'm going forward with a solution that we would use a `CControl` to show the error message at least on Linux with a slight change in the initialization sequence.
@baconpaul, some remarks:

- It is easy to make the sequence optional i.e. leave the parameter to the constructor. That way we can use it in VST2 plug-in at first and later in VST3.
- I'm not sure why it is an issue for headless version to have a `CControl` for showing error messages that is used in GUI versions. These things IMHO do not fight with each other at all.

Especially given the @whydoubt's remarks, this is really the only feasible long-term way to go with the GUI. Other options simply fail on Linux.

After this rant I also have one question: at what point does `SurgeGUIEditor::open()` get called? Just something "good to know".

**Comment by baconpaul** [comment]
@jsakkine maybe I misunderstood you. It's totally not an issue! Remember I wanted to have a function pointer (or class) which implements these we can swap out and I still think that's a good pattern.

As to startup path, optional means it will work for AU still so I'm good with that!

in au, open gets called in initWithSurge in aulayer_cocoaui.mm which is itself called from the uiViewForAudioUnit method which is part of the AU base. Don't know about the sts.

**Comment by jsakkine** [comment]
@baconpaul, yeah, the constructor parameter stays :) You just feed null if you want to use the setter instead.

**Comment by baconpaul** [comment]
Oh and I would probably add openurl to the signature as a function and capability too

**Comment by baconpaul** [comment]
@jsakkine FYI I have this mostly coded (except for linux where your CControl work will still be needed). Will have code for review next 24-48 hours along with some other issues.
