### ISSUE TITLE
Conditioner cuts away frequencies when loaded into master FX slots.

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2170]
**Describe the bug**
Conditioner cuts away frequencies when loaded into master FX slots but not on scene level.

**Please let us know your surge version**
VST3, 09c2a4e

Just load conditioner into scene A and replicate the same settings into a conditioner into master FX slot 1 or 2 and toggle the effect on and off and you hear the difference.

Left: on/off on master fx --------------------------------------------- Right: on/off on scene level
![sd d](https://user-images.githubusercontent.com/56724286/85210652-0f0dd680-b342-11ea-8b66-f1f19a7f67f3.jpg)

or load this preset.
[conditioner cuts frequencies on master fx.zip](https://github.com/surge-synthesizer/surge/files/4808490/conditioner.cuts.frequencies.on.master.fx.zip)

**Comment by mkruselj** [comment]
I cannot confirm this over here with that patch.

**Comment by mkruselj** [comment]
Actually I can in FL for now. But not in SAVIhost or Reaper. Testing other DAWs that I have (Studio One 4, Live 10, BWS 3).

**Comment by mkruselj** [comment]
It's again about FL not being smart enough to only have main stereo outputs connected to the mixer by default, it seems!
