### ISSUE TITLE
Skin engine consolidating issues

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2174]
We have enough coded for the 1.7.0 skins.
Push this to 1.7.n
Take @itsmedavep list and consolidate

This issue subsumes the now closed #1622 #1623, #1624, #1625  

- [x] The skin engine menu 
   - [x] Uses the skin names, not directory names and is sorted.
   - [x] Only show the test skins if the dev menu is on
   - [x] Has a link to the (nascent) skin documentation (https://surge-synthesizer.github.io/skin-manual.html)
   - [x] Rescan skins rescans skins
   - [x] Rescan all data folders rescans skins
   - [x] Rescan skins includes reload current skin
   - [x] Ellipsis on load manual
- [x] Horizontal gradients mis-render (see attached below)
- [x] Tag special case in SurgeGUIEditor CHSwitch creation
- [x] Move controls around (except FX sub-elements)
   - [x] Switches
   - [x] Sliders
   - [x] Modbuttons
- [ ] Resize controls
   - [x] Switches
   - [x] Sliders (size)
   - [x] Sliders (orientation)
   - [ ] Modbuttons
- [x] Suppress/hide controls
- [x] Resize the whole GUI
- [x] A label element for the XML
- [x] Slider changes
  - [x] Handle per slider in skin (was: Ability to specify different slider thumbs in different parts of the GUI (as an example wanted to do modulation section sliders in a different color than the rest of the GUI to strengthen the relationship to “modulation”))
  - [x] Modulation handle per slider in skin (may want to do the same thing for the automated slider thumbs. AKA not rely singularly on the color change to be the only difference when adding modulation stuff)
  - [x] Tempo sync and hover slider in skin
- [ ] Write skin engine documentation in the tutorials
- [ ] Delete the test skins
- [x] Labels print over About screen
- [x] Try some bad XML and look for error reporting
- [x] Remove the `std::cout` calls
- [x] CNumberField should have a skinnable background

**Comment by baconpaul** [comment]
From #1625 

```
<skin>
  <component-classes> <!-- this allows us to extend the built in classes with properties -->
    <class name="dark-vslider" parent-class="CSurgeSlider" orientation="vertical" propone="a" proptwo="b"/>
    <class name="light-vslider" parent-class="CSurgeSlider" orientation="horizontal" propone="a" proptwo="b" bgprop="SVG/foo"/>
    <class name="modified-light-slider" parent-class="light-slider" propone="c"/> <!-- so proptwo = b and bgpro is SVG/foo still-->
    <class name="centered-text" parent-class="CLabel" font="lato" valign="left"/>
  </component-classes>
  <controls>
    <control ui_identifier="aeg.attack" class="light-vslider" posx="23" posy="47"/>
    <control ui_identifier="global.character" class="CHSwitch2" posx="89" posy="123"
             w="100" h="80" switch_sprite="SVG/bmp00161.svg"/>

    <!-- You can override a property also -->
    <control ui_identifier="modified-light-slider" propone="d"/>
  </controls>
</skin>
```

**Comment by baconpaul** [comment]
[horizontal_linear_gradient.svg.zip](https://github.com/surge-synthesizer/surge/files/4809834/horizontal_linear_gradient.svg.zip)

**Comment by mkruselj** [comment]
- [ ] Add SVGs for MPE/Tune/Zoom buttons and fallback to text if they are not found
- [ ] Add fallback to text for Store and Menu buttons.

**Comment by mkruselj** [comment]
- [ ] Add fallback to text for Digital/Analog env mode, Scene mode, LFO mode, LFO unipolar, Waveshaper mode, Play mode, FX bypass, Character?

**Comment by baconpaul** [comment]
I think I’m going to defer all the fallback texts to 1.7.1 actually

**Comment by jcmos** [comment]
Guys, this is a very powerful synth. It needs not only a new skin , but the whole user interface re-designed from scratch.
It will be easier to do this than trying replacing everything with different skins and colors.
This UI belongs to 15 years ago. We need one that makes this synth unique and modern in pair with the new synths coming up in 2020.
Roll up your sleeves and make this happen. Cheers

**Comment by baconpaul** [comment]
Is your comment offering to roll up your sleeves and make it happen, or instructing us to? Unclear.

If it is the first, would love to see what you are thinking! And are you a programmer willing to make it happen?

**Comment by jcmos** [comment]
I don't actually have a proposed design. I have been working as a Business Analyst with developers for many years, but I am not a programmer. I am just suggesting what the finished product should look it. Do we want to keep the current look? . or we want to make it attractive in pair with recent VST synth designs? In my opinion it look a bit outdated and it would be beneficial to come up with a totally different look. I could make a prototype of the user interface, but I am not a designer either.
I am just trying to put ideas on the table. As a user of this fabulous synth, I miss a bit of user experience.

**Comment by jcmos** [comment]
this is the tone 2 icarus, we could design something similar to this:
[](https://images.app.goo.gl/6ruC9rAY6K32iVeP8)

**Comment by baconpaul** [comment]
Have you tried the dark skin in the nightly? The nightly also adds a lot of modern features like hover-assets and type-ins which have really bugged us.

I'm of two minds on the UI. It's an incredibly complicated synth and the UI lets you do an enormous amount. And it is gray and orange with weird sliders.

We've fixed the second in the nightly and upcoming 1.7 release. But to really reskin it we would need a proper architecture for what the UX would be.

We have a #design channel on our slack where folks do talk about this.

There's also a load of technical change involved in rewriting the UI. We would need a programmer committed to doing it. We don't have that now.

**Comment by jcmos** [comment]
If we need a dedicated person working just on the UI and thats the only way, then it is what it is and we need someone for that task.
ok, well lets try getting more people on board somehow. We need to make a bit of noise thou.  I am also not advertising guru LOL.

**Comment by baconpaul** [comment]
We welcome anyone who wants to join the team and contribute to do so!

**Comment by jcmos** [comment]
Just thinking of a way to get people's attention

**Comment by mkruselj** [comment]
- [ ] direct RGB color entry for text labels
- [ ] CSwitchControl should be movable/resizeable/whatever (as soon as you can get to it, @baconpaul!)

**Comment by mkruselj** [comment]
-[ ] LFO mode switcher should be fully skinnable

**Comment by baconpaul** [comment]
I really like that 2D selector idea by the way!

**Comment by baconpaul** [comment]
OK the few remaining bits and bobs are now in standalone 1.8 or 1.9 issues. Closing this master issue.
