### ISSUE TITLE
Text not centered properly vertically in CNumberField

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2188]
![image](https://user-images.githubusercontent.com/2393720/85473861-2522cd80-b5b4-11ea-93de-adcd057f665a.png)

![image](https://user-images.githubusercontent.com/2393720/85473866-26ec9100-b5b4-11ea-8f17-67867c79f506.png)

![image](https://user-images.githubusercontent.com/2393720/85473870-28b65480-b5b4-11ea-804f-929d1eb62223.png)

Windows, zoom level 175%. It's fine at 150%...

**Comment by baconpaul** [comment]
fine on mac

**Comment by mkruselj** [comment]
@baconpaul And actually fine on Windows now, too, since we have skinnable CNFs and they are ACTUALLY POSITIONED PROPERLY on the GUI!

Issue down!
