### ISSUE TITLE
Shephard tone oscillator

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2196]
Jacky Korridor and me talking over in #microtuning and Jacky was working on a shepard tone patch (and he got very far).

https://en.wikipedia.org/wiki/Shepard_tone

```
Korridor  6:22 PM
make a true shepherds tone in  surge is a real challenge

Jacky  6:22 PM
Interesting idea...
Pretty pleased with the result as an interesting extrapolation of the idea, although not perfect, it's a unique sound unto itself. (edited) 

baconpaul  6:23 PM
I suppose I could just code up a shepherds tone oscillator and cheat that way :)

Jacky  6:24 PM
:smile: Yeah, that's another method....
Then use that for FM!

Korridor  6:24 PM
cheating :smile:
6:24
BUT
6:24
IMO

Jacky  6:24 PM
Yes, it tis.

Korridor  6:25 PM
thats an AMAZING idea for a osc to add  to surge
6:25
like for real

baconpaul  6:25 PM
Yeah but I’m an honest guy and you both told me that’s cheating

Korridor  6:25 PM
hahahahaha
```

and then later Korridor shared this example of a dedicated generator he had kicking around

![es_v3_big](https://user-images.githubusercontent.com/13387561/85802948-09363d80-b714-11ea-8ea8-61783dade5bd.png)

**Comment by mkruselj** [comment]
Like, really? Seems like far too much of a one trick pony to me. Pluck osc should take precedence IMHO :)

**Comment by K0rrid0r** [comment]
https://youtu.be/OIpgFg4Tn6Y

this was very interesting. apparently called "dynamic stochastic synthesis" 
this was also an extended shepard tone.

**Comment by baconpaul** [comment]
I really am thinking about a 'dynamic systems' oscillator with different modes (shepard, lorenz, double pendulum, etc...) as something I may do in the future.

**Comment by baconpaul** [comment]
Fold this into #3433 if we even do it with that cluster
