### ISSUE TITLE
Virtual MIDI controller names not shown properly

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2201]
On Studio One, Windows:

![image](https://user-images.githubusercontent.com/2393720/85855758-11938480-b7b7-11ea-96dd-c87eb9b16407.png)

![image](https://user-images.githubusercontent.com/2393720/85855788-1b1cec80-b7b7-11ea-9985-37af0fc01b80.png)

**Comment by K0rrid0r** [comment]
Can confirm the same in FL Studio.

**Comment by baconpaul** [comment]
Yeah its a wide char thing. That code should make a whidechar but it doesn't. There's a different incantation I have to use and I got them all but not that one. Will fix.

**Comment by baconpaul** [comment]
The VST3 SDK Validator shows the same. Fix inbound.
