### ISSUE TITLE
Status buttons should have the same thickness as rest of the button texts

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2204]
Status buttons should have the same thickness as rest of the button texts
![100](https://user-images.githubusercontent.com/56724286/85876258-bf159080-b7d5-11ea-9fff-2ba291ef90c5.gif)

Korridor  5:47 PM
also on 100% those three looks thicker then all of the rest of the text in surge
100.gif 
100.gif

EvilDragon  5:49 PM
yes well they will get SVGs for actual skin a bit later on so they will look consistent

Korridor  5:49 PM
right

EvilDragon  5:49 PM
those 3 buttons are generated in code rather than with SVG
5:49
so they look a bit different

baconpaul  5:50 PM
They shouldn’t look different from the patch browser tho
New
5:50
can you toss that in an issue and I’ll make sure I’m not just using the wrong font

**Comment by baconpaul** [comment]
goodness gracious I just ran this on windows and yeah it looks terrible!
