### ISSUE TITLE
Show value for macros in RMB context menu (+typein)

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2210]
So then we're consistent regarding all sliders showing their value and having a typein.

**Comment by baconpaul** [comment]
Also the macro name, if it has been renamed, should be "Name (Macro 1)" rather than "Macro 1"

**Comment by mkruselj** [comment]
Makes perfect sense!

**Comment by baconpaul** [comment]
Also they need to participate in help.
