### ISSUE TITLE
Rate of temposynced LFO resets to minimum (64 whole notes) randomly

### ISSUE THREAD

**Issue by sloast** [surge-synthesizer/surge#2213]
When I temposync the rate of an LFO, and set it to a value, it will reset itself to the lowest (i.e. slowest) value after I play/pause the track a couple of times. It both resets it on the UI, even if it is not closed, and with the sound. It makes it near impossible for me to use a LFO that is synced to the tempo of my project.

** Surge Version **
Version: 1.6.6 (64 bit windows vst3)
1.6.6
VST3
64 bit Windows

** To Reproduce **
For me, it happens everytime I temposync an LFO, and then play/pause the song a couple of times. The exact time before it resets is inconsistent. My DAW is Cakewalk by BandLab.

**Screenshots**
Where it starts: e.g.
![image](https://user-images.githubusercontent.com/67313765/85923836-4f131300-b886-11ea-8955-78141be58be5.png)
After: 
![image](https://user-images.githubusercontent.com/67313765/85923863-723dc280-b886-11ea-91fd-1370291542f7.png)

**Desktop**
 - OS: Windows
 - Host: Cakewalk by BandLab
 - Version: 2020.05 (Build 039, 64bit)

**Comment by baconpaul** [comment]
Wow Cakewalk must be sending us a DAW automation message which is incorrect.

@mkruselj do you have this DAW in your system?

@sloast we are inches away from starting the 1.7.0 beta period. If you are interested, you could try with the nightly https://surge-synthesizer.github.io/nightly and see if it's resolved.

(Obviously we haven't run into this in the DAWs we use for regular testing, which are basically logic, reaper, bitwig, and less cubasis)

Thanks for the clear report.

**Comment by sloast** [comment]
Yeah i realize that cakewalk isn't used too much, which could mean it has some odd issues communicating .. it actually doesnt even let me use most plugins at all so its nice that this one works.

**Comment by mkruselj** [comment]
> @mkruselj do you have this DAW in your system?

Nope!

**Comment by sloast** [comment]
It doesnt seem to do it as often if I use my MIDI controller instead of the notes that are written, for some reason, so it is probably to do with the input, or automation or something

**Comment by baconpaul** [comment]
Is it something we can get easily? Like can I just download it into my vm?

**Comment by sloast** [comment]
Cakewalk?

**Comment by sloast** [comment]
Its free - you can get it here:
https://www.bandlab.com/products/cakewalk

**Comment by baconpaul** [comment]
yeah. do i have to buy it? I guess I can google this for myself though :)

**Comment by sloast** [comment]
you have to run the first app to install the actual daw

**Comment by sloast** [comment]
its a strange system

**Comment by baconpaul** [comment]
When I google it I see immediately "cakewalk by band lab is free" so we can look i guess

If you give the nightly a whirl that would help too. If the nightly breaks also I'll grab the daw and look.

**Comment by sloast** [comment]
sure

**Comment by sloast** [comment]
Thanks!

**Comment by sloast** [comment]
ok so btw I was making something else, when I tested it again, and it had stopped doing it. I'm not sure what the reason for this is, but I can't seem to be able to reproduce the problem on this file.

**Comment by sloast** [comment]
Maybe it was a glitched file, but I can't even do it on the original

**Comment by sloast** [comment]
It did it before but it has completely stopped now, so it was probably something rare

**Comment by baconpaul** [comment]
OK so let me close this issue; but if it comes back please feel free to reopen it or open a new one.

Thanks!
