### ISSUE TITLE
The disappearing widgets act 

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2225]
Click on play mode, osc FM routing, filter config, filter type, waveshaper type, scene/osc octave, FX bypass, etc, hold the click then RMB.

They go poof. 

![image](https://user-images.githubusercontent.com/2393720/85948504-931f1a00-b951-11ea-9218-f056ea03cd25.png)

**Comment by baconpaul** [comment]
ruh-roh. That's scary. 
And it doesn't happen on mac.
Just click-hold and they disappear immediately or does it take some time?

**Comment by mkruselj** [comment]
Hold left click THEN do right click while still holding left click.

**Comment by baconpaul** [comment]
I don't understand. How do you physically do that?

**Comment by baconpaul** [comment]
Also once they vanish does a mod source switch bring them back (like toggle over to LFO4 or something)?

**Comment by mkruselj** [comment]
You need an actual mouse not a trackpad to physically do it :)

**Comment by baconpaul** [comment]
That fix was my bad. Not all downs generate an up so you can end up losing mouse downs.

I disabled the fix for now and will figure out a correct fix for the two buttons at once conundrum before 1.7.0. It will be trickier alas than the simple change.

**Comment by baconpaul** [comment]
git remote add baconpaul https://github.com/baconpaul/surge.git
git fetch baconpaul
git checkout baconpaul/double-mouse-down-2225

is how to test my fix
