### ISSUE TITLE
Some files have CRLF line endings

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#224]
adding audio wav reader I noticed emacs was saying (DOS) in the corner. So

```
paul:~/dev/music/surge$ find src -not -type d -exec file "{}" ";" | grep CRLF
src/common/SampleLoadRiffWave.cpp: c program text, ASCII text, with CRLF, CR line terminators
src/common/SurgeStorageLoadWavetable.cpp: c program text, ASCII text, with CRLF, CR line terminators
src/common/gui/CParameterTooltip.h: C++ source text, ASCII text, with CRLF, CR line terminators
src/common/gui/CSwitchControl.cpp: c program text, ASCII text, with CRLF, CR line terminators
src/common/gui/CNumberField.cpp: c program text, ASCII text, with CRLF, CR line terminators
src/common/dsp/effect/RotarySpeakerEffect.cpp: c program text, ASCII text, with CRLF, CR line terminators
src/common/dsp/effect/VocoderEffect.cpp: c program text, ASCII text, with CRLF line terminators
src/common/dsp/LfoModulationSource.cpp: c program text, ASCII text, with CRLF line terminators
src/common/dsp/DspUtilities.h: C++ source text, ASCII text, with CRLF line terminators
```

someone want to dos2unix those one day?

**Comment by esaruoho** [comment]
@baconpaul i could try it, but how? does sublime editor help me do this stuff easily? :)

**Comment by baconpaul** [comment]
`dos2unix` is a command line that will do it. So

* `brew install dos2unix`
* `git checkout -b crlf-fix-224`
* (foreach file) `dos2unix -o file`
* run that find again to see if you got em all. If not more dos2unix.
* check it builds look at diffs
* commit, push to origin, pr

is basically the 20 minutes of work that needs done

**Comment by jsakkine** [comment]
That kind of clean ups have the side-effect making `git blame` harder to use. Better check from upcoming commits that they don't have CRLF.

Better to do clean ups in small scale e.g. clean up only the code blocks that you do something actually useful.

**Comment by baconpaul** [comment]
Ugh except for “smart” tools which use crlf when crlf is present. And other smart tools which fix them for you everywhere when you edit one line. We can have one minute of blame pain and get over it

But I’m fine to not do this if you really object. Just makes my life mildly irritating in my toolchain while I’m doing wav file on Mac

**Comment by baconpaul** [comment]
Ahh and another bit of annoyance. Xcode (or really I guess clang) counts line numbers differently than emacs in crlf mixed mode so errors don’t match line Goto numbers between compiler and editor :(

Now my irritation and weird non alignment from yesterday makes sense!

**Comment by jsakkine** [comment]
Came to other thoughts. Probably most CRLF's are from the original code dump so it should cause minimal irritation to do this. No objections.

**Comment by baconpaul** [comment]
Ok cool! I’m also glad the line number mystery from Saturday now makes sense!

**Comment by baconpaul** [comment]
<img width="1258" alt="screen shot 2019-01-07 at 9 06 04 am" src="https://user-images.githubusercontent.com/13387561/50772371-89848c80-125b-11e9-9955-41508b10f29e.png">

Ha! Look at that. clang has different line numbers than emacs and nl.  How odd.

**Comment by baconpaul** [comment]
ANyway, now they don't any more. Checked build all platforms and pushed.
