### ISSUE TITLE
Unique icons per FX type

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2244]
We should have unique icons for each effect type, rather than merging some into one. For example, MOD is currently used for chorus, phaser, flanger, rotary. We could use CHO, PHS, FLA, ROT instead. We have that weird icon for freq shifter and ringmod, we could just use FRQ and RM instead. Vocoder uses FX but it could be VOC,

That's all.

**Comment by baconpaul** [comment]
@mkruselj I wonder if just painting the labels as strings would be an easier approach? Then we could also use RV1 and RV2 for reverbs and stuff. A bit of surgery but I bet it could also solve some of those box alignment problems.

**Comment by mkruselj** [comment]
I guess that could work but I wonder about different zoom levels and vertical alignment issues we have with sone other widgets...
