### ISSUE TITLE
Negative modulation range line is not transparent when a parameter is deactivated

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#2248]
![image](https://user-images.githubusercontent.com/50145178/86071717-f8583580-ba4d-11ea-98b9-22c8f0a55334.png)

**Comment by K0rrid0r** [comment]
![115](https://user-images.githubusercontent.com/56724286/86077143-bfd74c80-ba8b-11ea-8bef-ae42a3d56e33.gif)
just putting a picture here of all those parameters
