### ISSUE TITLE
Macro mod link/window disappears on first try then works on second try

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2251]
**Describe the bug**
Macro mod link disappears on first try then works second time 

**Please let us know your surge version**
hash 861fbe0 VST3 (downloaded version) (and my VST2 build)

**To Reproduce**
![137](https://user-images.githubusercontent.com/56724286/86131560-196c6500-bae6-11ea-9837-f6b6055064be.gif)

**Expected behavior**
Macro mod should always work on first try

**Comment by baconpaul** [comment]
Can repro AU mac. Thanks.

**Comment by K0rrid0r** [comment]
Just checked surge 1.6.2, this problem does not exist there.

**Comment by baconpaul** [comment]
I know why this is happening
