### ISSUE TITLE
add extend range to waveshaper drive 

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2253]
add extend range to waveshaper drive 

![138](https://user-images.githubusercontent.com/56724286/86164545-3a4aaf80-bb12-11ea-94a1-8582de5988b8.gif)

We need to test what that sounds like :)

Because of the time now we need to toss it into 1.7.n

**Comment by baconpaul** [comment]
This is relatively easy

1. Whack the param in the obvious way
2. SurgeVoice.cpp `float Drive = db_to_linear()` gets the extended logic
3. for each of the wave shaper functions check what happens if the range gets extreme. That's a review of the DIGI_SSE2 CLIP SINUS_SSE2 ASYM_SSE2 and TANH functions in QuadFilterUnit.cpp

**Comment by baconpaul** [comment]
Looking at the code

- CLIP TANH and DIGI_SSE2 are analytic so will scale as far as we want
- ASYM_SSE2 is a lookup but at line 673 of QuadFilterUnit we min/max it to 0/0x3fe
- SINUS_SSE2 is a lookup and uses the &0x3ff so will have the 'wrap' problem in extended mode which could sound very surprising

Also from looking at this code, adding other wave shaper tables is super duper easy. Basically you would copy ASYM_SSE2 and use different tables. Don't we have an issue on that?

**Comment by K0rrid0r** [comment]
No issue on that, because there were many ideas about redoing the waveshaper in some way to fit a flow with more wavetables, i think. Evil knows.

Anyway, id really just like to hear how the extended waveshaper would sound like. would also be super cool to be able to send the oscillator wave to the waveshaper and then waveshape the osc sound with its own waveform.

**Comment by baconpaul** [comment]
I didn't mean "have an issue" as in "have a problem". I meant "have an issue" as in "oh yeah @mkruselj wrote up #1964" :)

**Comment by baconpaul** [comment]
It's rainy here and I want a little issue to bang out so I think I'm gonna try and do this one now and see what happens

**Comment by baconpaul** [comment]
Oh ha we already have a ct_decibel_narrow_extendable ... lets see.

**Comment by mkruselj** [comment]
Don't tell me this was only about changing the ctype! 😀

**Comment by mkruselj** [comment]
I guess in order to retain the GUI we could have a "Gain compensate" option in RMB context, as well?

**Comment by baconpaul** [comment]
It was 3 changes which I was able to push before power died. Baconpaul branch ws-extend-2253

But it isn’t a very useful change - if you just push a sine wave in most things saturate about 24db so extendingnto 120 keeps you saturated. The exceptions are sin which goes silent from high harmonics and asym which diverges 

I think we don’t want to extend drive basically in this naive fashion but take a look and let me know

The idea of more shapers is one I like a lot more

**Comment by mkruselj** [comment]
> The idea of more shapers is one I like a lot more

Me too, actually. But we should still get that gain reduction switch in RMB context somehow :)

**Comment by baconpaul** [comment]
OK will merge an extend to +/- 48 and fix that scale display thing too.
