### ISSUE TITLE
Full macro mod on Amp EG R / LFO EG D / Filter EG R cuts the tone

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2256]
**Describe the bug**
Full macro mod on Amp EG R / LFO EG D / Filter EG R cuts the tone when those two sliders are already set at maximum by the visible slider

Open these and drag the macro and youll notice that if you plan the macro mod after around +62 it just cuts the tone when later listening. It's probably the same problem that existed for the LFO rate.
[full macro mod on Amp EG R cuts the tone.zip](https://github.com/surge-synthesizer/surge/files/4854358/full.macro.mod.on.Amp.EG.R.cuts.the.tone.zip)
[full macro mod on LFO EG Decay cuts the tone.zip](https://github.com/surge-synthesizer/surge/files/4854359/full.macro.mod.on.LFO.EG.Decay.cuts.the.tone.zip)

hash 99ed4aa

**Comment by K0rrid0r** [comment]
[full macro mod on Filter EG R cuts the tone.zip](https://github.com/surge-synthesizer/surge/files/4854423/full.macro.mod.on.Filter.EG.R.cuts.the.tone.zip)

same on Filter EG R

**Comment by K0rrid0r** [comment]
[full macro mod on Amp EG A cuts the tone.zip](https://github.com/surge-synthesizer/surge/files/4854444/full.macro.mod.on.Amp.EG.A.cuts.the.tone.zip)

And full macro mod on Attack upwards created a notable click where we would imagine just a super long attack and silence

**Comment by K0rrid0r** [comment]
*new kind of problem*
Latch with Amp EG ADSR all on 0 creates a tone

[Latch with Amp EG ADSR all on 0 creates a tone.zip](https://github.com/surge-synthesizer/surge/files/4854458/Latch.with.Amp.EG.ADSR.all.on.0.creates.a.tone.zip)

just open the preset and you hear it

**Comment by baconpaul** [comment]
OK can we put a new problem on a new issue? :)

On the ones you showed with ADSR can you try something for me and confirm

in `src/common/dsp/AdsrEnvelope.h` and `src/common/dsp/LfoModulationSource.cpp` change every instance of `envelope_rate_linear` to `envelope_rate_linear_nowrap` and let me know if the ADSR and LFO mod ones get fixed?

**Comment by baconpaul** [comment]
cool thanks for confirm (on slack). merging that change and closing this issue (and you can move the "new kind" into a new issue pls?)
