### ISSUE TITLE
LFO average points algorithm appears confusing by LFO EG attack and Amplitude

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2258]
**Describe the bug**
LFO display average points in drawing is exposed broken by LFO EG attack

Example how to see it.
![139](https://user-images.githubusercontent.com/56724286/86181105-b4d4f880-bb2d-11ea-8f17-38c075597fc8.gif)

**Please let us know your surge version**
this exist as a thing in the Vector LFO mode.

**Comment by K0rrid0r** [comment]
![144](https://user-images.githubusercontent.com/56724286/86189906-25d2db00-bb43-11ea-9196-469b51d467ab.gif)
![143](https://user-images.githubusercontent.com/56724286/86189907-27040800-bb43-11ea-9553-a032510f07f8.gif)
![142](https://user-images.githubusercontent.com/56724286/86189912-2c615280-bb43-11ea-96b4-def0153febf3.gif)
![141](https://user-images.githubusercontent.com/56724286/86189914-2ff4d980-bb43-11ea-90af-e48305a65eef.gif)

some pictures showing strange behavior in the lfo draw algo, will comment more about this later on.

**Comment by baconpaul** [comment]
thank you - great use cases for a fix!

**Comment by mkruselj** [comment]
@baconpaul I think I found this one.

https://github.com/surge-synthesizer/surge/blob/8112ecfeefdfecd977f4777038b5dcd29267aac0/src/common/gui/CLFOGui.cpp#L261

It's this check here. Unsure why it's needed, if I just remove the `else` branch and remove the `if` it shows up really nicely, and I cannot see any adverse effects. What was the reason behind this condition here?

![image](https://user-images.githubusercontent.com/2393720/107583085-bb1a6f80-6bfa-11eb-9bf6-3357897b4e17.png)

**Comment by baconpaul** [comment]
It makes square-ish and other discontinuous waves draw properly on windows 8 and some windows 10 systems

**Comment by mkruselj** [comment]
Hm, those seem just fine over here on my two W10 and an old W7 machine...

![image](https://user-images.githubusercontent.com/2393720/107588817-eb670b80-6c04-11eb-8580-321cd4039e25.png)

**Comment by baconpaul** [comment]
Right so it fixes a problem on windows forever ago. So either that problem has magically disappeared or it hasn’t and I don’t remember what it is. So our choices are

1: remove this, believe in magic, go forth
2: remove this, find the bug, reinstate this before 19
3: remove this, ship 19, have 19 be broken forever or
4: don’t remove this and fix it with juce 

I’m neutral but of these think 4 and 2 are the best

**Comment by mkruselj** [comment]
Let's go with 2! I scanned all the closed tickets mentioning LFO and no word on drawing issue under certain Windows... If it pops up back again, we will know. But I bet we're on JUCE by then. 🙂

**Comment by mkruselj** [comment]
Actually just found the issue... #1438

**Comment by baconpaul** [comment]
Ok!
