### ISSUE TITLE
Re-latch with Amp EG ADSR all on 0 creates a tone each time

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2259]
re-latch surge with Amp EG ADSR all on 0 creates a tone

[Latch with Amp EG ADSR all on 0 creates a tone.zip](https://github.com/surge-synthesizer/surge/files/4855238/Latch.with.Amp.EG.ADSR.all.on.0.creates.a.tone.zip)
just open the preset and you hear it, here we should just expect silence. what has happend?

EDIT: once you load the preset you should hear the tone, fix it by lifting Amp EG decay and put it back to 0 and the tone is gone. 
EDIT2: ADR are set to 1.000 s when they are supposed to be 0.000 s

![149](https://user-images.githubusercontent.com/56724286/86195163-97655600-bb50-11ea-9ee5-033bc98dbd77.gif)

that might be the problem?

**Comment by baconpaul** [comment]
The 1.00 s is a formatting bug, not a value bug. The envelope really is at zero. So there's two issues here - a formatting bug and a behavior one. I'll leave this in 1.7.0 at least until I fix the formatting one (which is in the custommin/max value in get_display for atobx)

**Comment by baconpaul** [comment]
OK PR #2261 solves the "display the min as 1.00s" issue. That was purely a display issue though.

**Comment by baconpaul** [comment]
OK with the latch here's the issue. 

First this is again only an issue in decay curve 1. If you set the envelope decay to 0 or 2 it doesn't happen.

And so again it must be a problem with the sqrt(phase) calculation not hitting zero cleanly in the case 1: around line 289 of AdsrEnvelope.h

Lemme see if I can figure out exactly why. But clearly we are getting pushed off the sustain there still, per the comment.

**Comment by K0rrid0r** [comment]
I did this one minute video before you posted that comment just showing how off the calculation actually is. it goes on to -0.021 and stops loudly there.

https://youtu.be/vbDsK-aaNHk

**Comment by baconpaul** [comment]
I have it fixed.
