### ISSUE TITLE
Corrupt patch author blows up linux

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#2266]
VST3 64 bit on Linux

Carla and Bitwig (latest builds)
Surge commit c84b66

Clicking on Store when the Store Patch dialog opens **Cancel** does not work. If No is select, **OK** will only work on the first assay. As well with **OK**, this dialog is under the app not as opposed to being on the upper most layer, hence hidden rather than displayed.

![Screenshot_20200701_170859](https://user-images.githubusercontent.com/41337033/86292086-1349b780-bbbe-11ea-9c21-6eaa593b63e1.png)

Also, if Surge is minimized and then re-opened the GUI appears as follows:

![Screenshot_20200701_170604](https://user-images.githubusercontent.com/41337033/86292113-22c90080-bbbe-11ea-9975-54b025ec74f0.png)

As an addendum Surge was crashing when clicking in the Creator field, now cannot type in and will crash Reaper, Bitwig and Carla. Same behaviour on VST2.

**Comment by tank-trax** [comment]
@bgins was wondering if you could confirm this

**Comment by baconpaul** [comment]
in the juce6 host everything seems fine.
that window behind is really nasty

**Comment by tank-trax** [comment]
looks like it was **SurgeUserDefaults.xml**

`  <default key="defaultPatchAuthor" value="0œ" type="1"/>`

I have renamed it to .old and it does not get rewritten unless I change Skin.

**Comment by baconpaul** [comment]
Oh yeah that corruption will kill you
Can you save or attach that file here and I will do a check for that case?

**Comment by bgins** [comment]
Sounds like the cause on this one has been identified. I tried the Store sequence outlined above and everything works fine on my end. No problems with the Creator field either.

I don't have a minimize option. Maybe something changed recently? (I tested on nightly 8373615 because I can't remember if I have a working build.)

**Comment by tank-trax** [comment]
[SurgeUserDefaults.zip](https://github.com/surge-synthesizer/surge/files/4861367/SurgeUserDefaults.zip)

**Comment by baconpaul** [comment]
So the trick here is we need to check if we are valid UTF-8

https://onlineutf8tools.com/validate-utf8

is the format we should check against

and we need to check that everywhere.

**Comment by bgins** [comment]
I wonder if this is related to #1672. I haven't been able to reliably reproduce it, but I still see it sometimes. Maybe some garbage was made and saved to `SurgeUserDefaults.xml`?

**Comment by baconpaul** [comment]
Yeah very possibly

I have a change coming in which checks these strings for valid utf8. Perhaps we can expand that to other strings also? (Right now I am just minimally checking default author and comment since we are so close to 170)

**Comment by tank-trax** [comment]
If I may add... in Linux when the pop up for type ins appears as well as for the Patch Store, the text is highlighted red for the type in and for Patch Store the field for the Name has the text highlighted red. There is no cursor though.

In Linux it is not possible to click into the box to make changes. Generally I must use the left or right arrow, which then places the cursor either at the start or the end depending on which arrow was selected. From there it is possible to enter/remove text.

**Comment by baconpaul** [comment]
Yeah I saw that red. I'll open another issuer that.

**Comment by tank-trax** [comment]
I was about to ask if I should. Thanks.

**Comment by bgins** [comment]
The mangled text described in  #1672 shows up in more places than the patch storage dialog. Taking another look at it, I was not able to save the patch when I opened that issue. 

Next time I see those weird boxes, I'll try to use save or use them as a typein setting to see what happens, and I'll add some more notes to #1672.

**Comment by baconpaul** [comment]
Yeah 100%
I just didn't want to add 100 new unicode checks as the last commit of 1.7.0 honestly.

**Comment by bgins** [comment]
That makes sense. Probably best to not rush in a bunch of changes right at the end.

**Comment by baconpaul** [comment]
Yeah put in #2276 so we don't forget
