### ISSUE TITLE
Modulation popup window should stay on on LMB hold down.

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2268]
**Describe the bug**
Modulation popup window should stay on on LMB hold down.

Hold down LMB should mean = stay on 
Dropping LMB should mean = the timer goes on as expected

Just and example of how it is now.
![151](https://user-images.githubusercontent.com/56724286/86296731-cd124980-bbf9-11ea-9b12-8fa10880447e.gif)

**Comment by baconpaul** [comment]
Fix inbound.
