### ISSUE TITLE
Anomalous LFO X-Mod and Typein behavior

### ISSUE THREAD

**Issue by Jacky-Ligon** [surge-synthesizer/surge#2271]
Surge-NIGHTLY-2020-07-02-9f71c83 | Win-10, VST3i

In the below GIF, x-modulation of LFO-1 Rate with LFO-2, in both non-synced and Tempo Synced modes, produce unexpected values with typeins and the resulting ranges of the handle and track.

Non-Tempo Synced LFO Range
-1 to 47999 

Tempo Synced LFO Range
1600 to -1600 

Observe the results of typeins and handle/track positions.

![LICEcap](https://user-images.githubusercontent.com/66483816/86384893-645cb880-bc5d-11ea-9717-65c128fdac6a.gif)

**Comment by baconpaul** [comment]
So the track positions are correct (the control is in 2^x space) but yeah clearly those upper bounds aren't! We cap the LFO rate well below that and should similarly cap the display. Thank you!
