### ISSUE TITLE
More Unicode Checks

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2276]
defaultAuthor being garbage memory blew up linux over in #2266 and I fixed it with a small unicode check
we should be more fulsome with those since it seems vstgui type-ins are not very resilient under bad strings.

**Comment by mkruselj** [comment]
@baconpaul Does this one need any attention for XT, still?

**Comment by baconpaul** [comment]
in a different way - wanna leave it open for a tiny but until i make sure i am fully utf8ified in juce

**Comment by baconpaul** [comment]
#4385 completely subsumes this. Closing
