### ISSUE TITLE
Change labels on Filter #2 buttons

### ISSUE THREAD

**Issue by MBYlt** [surge-synthesizer/surge#2286]
Right now, Filter 2 has two buttons for linking the cutoff and resonance to Filter 1 (making it similar to the dual-2 poles in Waldorf synths and the OSCar). However, I think these buttons are **confusingly labelled**.

1. Seeing "R" and "L" in an audio context immediately suggests stereo balance. Speaking personally, when first looking at Surge it seemed that these were intended to offer separate cutoffs for left and right channels, and even after starting to mess around with them I wasn't entirely sure that the current behavior was intended. I understand how having "R" above "L" is possibly a clue that these aren't meant to refer to stereo channels, but still, of all the letters of the alphabet, this is probably the single most confusing pair to be using in conjunction with something other than stereo channels. It's like a text editor using B and I for **B**ulletpoint and **I**ndent. :)

2. Moreover, they both fundamentally do "the same thing" - slaving particular aspects of Filter 2 to Filter 1 - so it's a little bit confusing giving them different letters. The position of the buttons relative to the Cutoff and Resonance sliders can indicate which of these aspects will be affected.

I was thinking an iconographic approach might be **the best solution** - a classic **chain-link icon** ("§" except not-ASCII) for each button is what I came up with in my brainstorming session, though I'm sure there may be even better ideas.

The main argument against my specific solution that I could think of would be the user question "hm, link them... but to what?", so I guess if I was building it from the ground up I'd box them off with a "FILTER 1 LINK" label. However, the symmetry of the GUI precludes this, and frankly I don't think it's too too crucial, since the link-icon isn't (imho) actively misleading in the same way that "R" and "L" are, and using the same icon for both buttons hints that each has a similar broad-spoken effect in both places.

Using the link icon also makes it more clear that Filter 2 Cutoff/Resonance will be affected by modulations affecting Filter 1 Cutoff/Resonance - as opposed to just using Filter 1 slider positions as a starting reference.

**Comment by VincyZed** [comment]
Good point. I agree, L and R can be confused for Left and Right, and it took me some time to figure out what they actually did as well. I'm not sure this will be changed for 1.7.0, but I agree that think this should be looked into in the future, and I really like the chain-link icon idea!

**Comment by baconpaul** [comment]
Yeah agree L and R are bad choices and a link icon is a way better idea.

Also: LOL at B and I for bulletpoint and indent. I guess "Relative-to" and "Link" was the original intention?

It's actually pretty easy to change in the skins. @VincyZed will it screw up your manual work if we do change these much?

**Comment by baconpaul** [comment]
bmp00121 and bmp00140

**Comment by baconpaul** [comment]
https://thenounproject.com/search/?q=chain&i=2952932

**Comment by mkruselj** [comment]
R should be O (because we renamed the parameter to Offset Mode). L should be a little chainlink button.

**Comment by baconpaul** [comment]
I was thinking of a little chain for both to be honest. In both cases it is clear you are then linked either absolutely (resonance) or with an offset 

Thoughts?

**Comment by mkruselj** [comment]
IMHO that might be too confusing, honestly.

**Comment by VincyZed** [comment]
I think 2 chains would be good. And no, that wouldn't screw the manual updates at all, just have to replace 1 or 2 screen shots :)

**Comment by baconpaul** [comment]
![linkbutton](https://user-images.githubusercontent.com/13387561/86543767-879e9680-beef-11ea-952c-e778449db96a.gif)

Thoughts on attached welcome. If we all think it is OK I can push it (and do the dark skin too ofc). It's on `baconpaul/filter-button-2286`

**Comment by VincyZed** [comment]
I like it!

**Comment by baconpaul** [comment]
Yeah so does corridor and it directly addresses evil's concern about the on state meaning different things. 

So I'll apply it to dark and merge.

Cool!

**Comment by baconpaul** [comment]
OK dark done also. Merging

**Comment by baconpaul** [comment]
And the change will be in the nightly this evening and our upcoming 1.7.0 release on or around 1Aug20

Thank you @MBYlt for mentioning this. We should have fixed it long ago!

**Comment by mkruselj** [comment]
I really think that two link buttons should NOT be here. If the on state is + for filter offset mode, the off state should be + as well. Easy and clearer.
