### ISSUE TITLE
LFO modulation of Mixer levels doesn't accept typein values

### ISSUE THREAD

**Issue by Jacky-Ligon** [surge-synthesizer/surge#2287]
**Surge-NIGHTLY-2020-07-03-75f7bc1 | Win-10, VST3i**

LFO modulation of Mixer levels doesn't accept typein values

Notice in the attached GIF, that not only are typeins not accepted, but attempting to typein values for the modulation range actually results in completely disabling the assigned LFO modulation-source to the Mixer level slider altogether.

Expected behavior is that since bipolar modulation works when assigning the LFO modulation-source to the Mixer slider and setting the modulation range manually, that typeins should be accepted and enable making refinements to the LFO modulation range after the initial range is manually configured by dragging the slider close to the desired depth.

![LICEcap](https://user-images.githubusercontent.com/66483816/86538449-20b7b800-bec4-11ea-8bd5-6f52178a53ee.gif)

**Comment by K0rrid0r** [comment]
can confirm!

**Comment by baconpaul** [comment]
Thanks!

**Comment by baconpaul** [comment]
Yup definitely confirmed. Cool. Lemme look.

**Comment by baconpaul** [comment]
And it's only a problem when a mixer level starts at -inf. Should be easy to find. Thanks as always for the excellent report. Stay tuned.

**Comment by baconpaul** [comment]
Yup indeed I dealt with the minimum case improperly. Fix inbound.
