### ISSUE TITLE
Random and Freerun LFO trigger modes don't work when rate is deactivated

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#2289]
**Description**
When I deactivate LFO rate, Random and Freerun trigger modes don't work, it always triggers at the Phase set by the Phase / Shuffle slider (except for Noise, random works when frozen. And S&H is always random).

**Version**
Latest nightly

**Expected behavior**
When deactivated and in Random mode, start phase should be random in the cycle like it is normally when rate is activated and after stay there.

When deactivated and in Freerun mode, start phase should correspond to the host's clock like it does normally when rate is activated, but after stay there as well.

**Comment by baconpaul** [comment]
Great - I have this fixed

It means (basically) that the LFO in random deactivated mode ignores the phase slider which is what we want. Just mentioning that for the manual.
