### ISSUE TITLE
When set to absolute mode, Unison Detune tooltip formatting is wrong 

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#2299]
This should be a quick one to fix:

![image](https://user-images.githubusercontent.com/50145178/86553306-5e463080-bf18-11ea-8351-2decb62ac047.png)

The 1.6 manual says that unison detune in absolute mode (with range not extended) goes up to 16 Hz (and it sound like 16 Hz, not 1600 Hz hehe)

Extended range shows up to 19200 Hz, which is incorrect as well.

**Comment by baconpaul** [comment]
It was

I defined absoluteFactor to be a multiple on the scaled value. So just needed an /100 in one spot in the display info.
