### ISSUE TITLE
Dragging, releasing and immediately single-clicking resets slider to default

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#2302]
**Describe the bug**
Double-click is the gesture to reset a slider to default value in Surge. However, dragging, releasing and immediately single-clicking on it act as if it was a double-click, which in my case at least, leads to lots of unintended resets.

**Version**
Latest nightly, VST3, Windows 10.

**Expected behavior**
Dragging, releasing and clicking again should just make the slider draggable when moving the mouse again, instead of resetting to default value.

**Additional information**
I guess to fix this, we should check if mouse moved for both clicks in the double-click.

**Comment by baconpaul** [comment]
ugh - the double click is delivered by vstgui so this one has me fishing in there. I'm going to tag this for 1.7.n

Great bug report.

**Comment by mkruselj** [comment]
@VincyZed I cannot seem to reproduce this anymore in current nightly... we could likely close it if you can confirm the same?

**Comment by VincyZed** [comment]
It still happens over here: 
![Mod](https://user-images.githubusercontent.com/50145178/90318736-843ff700-df00-11ea-8926-5571908c8622.gif)

**Comment by mkruselj** [comment]
Hm yeah I can't seem to get that, but then I have mouse cursor hidden and Classic mouse mode.

**Comment by VincyZed** [comment]
This doesn't happen anymore, probably since the cursor snapping and hiding changes, so we can close this.
