### ISSUE TITLE
Step Sequencer: Switch Delete and Straight Line gestures

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#2312]
I was thinking it would be a good idea to put back right-click in the step sequencer to delete steps, and use Ctrl-click and/or middle-click drag to bring up the straight line arrow thing, because I think that deleting steps is done way more often than the arrow. Ctrl+Click isn't very intuitive to do such a basic thing, where as the arrow seems more like an advanced feature which would accordingly require a more advanced action/gesture. I think this would help new users a lot.

Let me know your thoughts :)

**Comment by mkruselj** [comment]
I'd like to keep the line tool on right drag, honestly....

**Comment by VincyZed** [comment]
We can close this, we now use double-click to reset as well as Ctrl. Your right drag is safe. :)
