### ISSUE TITLE
Flakey VST3 Zoom remembering 

### ISSUE THREAD

**Issue by mortfell** [surge-synthesizer/surge#2325]
Been loving the changes to Surge!
Came upon some weirdness 
I was testing on a Surface Pro 7 laptop with windows 10 and Reaper.
but I just tested on a macbook with Reaper and on the demo of Bitwig in windows as well. 
Nightly.96a0d96

I seem to remember with the Surge VST3 there was a point where if you resized a window, this zoom level would be remembered the next time you opened that instance of Surge. This is not the case with the current nightly.
The zoom seems to only remember for instances of Surge if the project was saved with those windows open.

**For instance:**
I have my Surge zoom level set to 200% but some older projects from other screen sizes have different zoom levels.

**if I:**
- open a project made before
- set a new zoom level
- close surge window and open it again,
- it will go back to the smaller size.

**Work around:**
I've noticed if I
- save the project with the Surge windows open to the size I want
-  close and reopen the project
The instances of Surge will now remember the new size.

**another way this is a problem**
It's also problematic because the way Bitwig and Reaper handle HiDpi screens on windows seems different (I'm sure all DAWs do slightly different things), so if I set my zoom level for Surge in REAPER (200%) when I open it in Bitwig I get the surge error message about resizing the window every time I open the plugin because the scaling of 200% is a different and it doesn't remember my new size.

**Comment by tank-trax** [comment]
could this be related to issue #2110?
part of the problem with the created VST3 presets was that it also streamed Zoom level, which is not something saving the preset to FXP would do

**Comment by baconpaul** [comment]
It is sort of related to #2110 in that we do save zoom level into your DAW preset (to get the behavior that we desire but only partly get here) and the VST3 api for ‘are you a DAW save or are you a vstpreset export’ is ... wonky. #2110 talks about how to deal with that.

I think the problem here is closing and opening the editor (basically) re-queries the track for the zoom level which is why the save works and the open/close without restart doesn’t

I’ll take a look but this state stuff is tricky... may hold a fix until after 1.7.0

**Comment by mortfell** [comment]
ah I see, thats all good to know.  Thanks for the response

this is my first computer with a high dpi/retina display so I'm encountering a whole world of strange problems

**Comment by baconpaul** [comment]
Yeah the windows API is crummy. It’s per-process and spreads into dlls weirdly.

There is a VST3 optional API which some hosts support but I don’t think REAPER did. It’s on my list for post our 1.7.0 drop

**Comment by baconpaul** [comment]
Oh the state fixes in 18 also fix this issue. Closing
