### ISSUE TITLE
Add hoverability for widgets that don't have them yet

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2330]
- [x] Status buttons
- [x] LFO type
- [x] OSC and FX menu
- [x] Wavetable selector+arrows
- [ ] FX grid
- [x] Step sequencer prev-next button triangles

**Comment by mkruselj** [comment]
1.7.2 now :)

**Comment by mkruselj** [comment]
Also not hoverable:

FM routing
Filter configuration

**Comment by baconpaul** [comment]
Really? Can't you just make hover graphics for those two and it works? They are just CHSwitch2s

**Comment by mkruselj** [comment]
Oh I didn't even try it! So it might just work - it's just that assets aren't there. Will chip away at it.

**Comment by mkruselj** [comment]
LFO type switch is not hoverable!

**Comment by baconpaul** [comment]
@mkruselj I can do LFO type switch hover easily this week - do you have assets for it? That would help. (If not I can make crappy ones).

For number - what sort of hover we thinking? Change the color of the field perhaps? We should really put the background on the number field though and then we could hover that instead. I think that's a sub-issue in skin?

**Comment by mkruselj** [comment]
Dark skin has the hover assets for LFO type for sure, I thiiink I also have them for Classic but gotta check.

And yes to skinnable numberfields!

**Comment by baconpaul** [comment]
Ahh yeah! OK I'll code up the hover on that now then.

**Comment by baconpaul** [comment]
#3873 will get the FX so this issue is really now just

1. Do we want to add any more hover to the step sequencer? and
2. For the wavetable selector, we need to add a color and paint it in hover if skin->getVersion() >= 2. Pretty easy change since we know when we are over the thingies in mouse move. So just need to do the standard enter exit move hover like on other assets with the COscDisplay

**Comment by mkruselj** [comment]
1. I don't think so IMHO.
2. Yeah!

**Comment by baconpaul** [comment]
Evils says baconpaul I should've conveyed this better - the L/R arrows and the WT name area should have separate hovers, since they are separate hitzones with separate actions. Currently the whole strip changes color which is quite garish IMO. Still, better to have a hover than not

I don’t know what to draw for dark in this case tho

**Comment by mkruselj** [comment]
Instead of this:

![image](https://user-images.githubusercontent.com/2393720/108068084-f0431980-7061-11eb-93e3-bd737105344a.png)

We'd have three separate hover areas:

![image](https://user-images.githubusercontent.com/2393720/108068316-35ffe200-7062-11eb-982c-77f593c6f3f0.png)
![image](https://user-images.githubusercontent.com/2393720/108068478-6cd5f800-7062-11eb-926f-bc3760548481.png)
![image](https://user-images.githubusercontent.com/2393720/108068640-a27ae100-7062-11eb-933d-d08c8c429999.png)

Using the same skin colors we already have for hover bg/frame/text.

**Comment by baconpaul** [comment]
yeah that's what i did
it looks kinda weird with that box around it in dark
but that's what i did

looks great in royal and classic tho

**Comment by mkruselj** [comment]
Yeah that box is actually not consistent with how hover is done in dark (bg should go blue and text white). Will fix!
