### ISSUE TITLE
Surge 1.6.6 issues with Tracktion Waveform 11

### ISSUE THREAD

**Issue by marc22109** [surge-synthesizer/surge#2332]
**Describe the bug**

**Please let us know your surge version**
This information is all in the menu/about screen

* Surge Version: 1.6.6
* Plugin type (VST2, 3 or AU)VST 2 and vst 3
* Bits (32/64)54

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10]
 - Host [e.g. bitwig, logic]
 - Version [e.g. 2.4]

**Additional context**
The synth's menus wil not open in Waveform 11.  Also, the synth transposes its output up a whole step from the indicated midi notes.

**Comment by baconpaul** [comment]
which os are you running? Also we have fixed a million bugs especially if you are running Linux and plan a 170 release in about 3 weeks; can you try the nightly?

Thanks

**Comment by marc22109** [comment]
Windows 10.

**Comment by K0rrid0r** [comment]
@marc22109  download the nightly 1.7.0 beta here and see if you still experience the same thing.

https://surge-synthesizer.github.io/nightly

**Comment by marc22109** [comment]
Thanks, 1.7.0 beta version seems to have resolved both issues in Tracktion Waveform 11.   Sent from Mail for Windows 10 From: F. K.Sent: Friday, July 10, 2020 11:41 PMTo: surge-synthesizer/surgeCc: marc22109; MentionSubject: Re: [surge-synthesizer/surge] Surge 1.6.6 issues with Tracktion Waveform 11 (#2332) @marc22109 download the nightly 1.7.0 beta here and see if you still experience the same thing.https://surge-synthesizer.github.io/nightly—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by baconpaul** [comment]
Wonderful! Thank you for testing. I’ll close this issue. 170 should be out of beta aug1 or so
