### ISSUE TITLE
Relabel "tun" status button to "scl"

### ISSUE THREAD

**Issue by MBYlt** [surge-synthesizer/surge#2333]
Another GUI oddity that may or may not merit a change:

Right now there's a button labelled "tun", short for TUNings. This is where one drags .scl / Scala files, and the status button indicates whether the special .scl file is currently activated or not.

However, "tun" is also an extension for a different tuning standard, which is incompatible with Surge at this time. See #1042 

It makes things a little bit confusing - I glance at the button, _think_ it refreshes my memory as to which type of file to drag to Surge, drag a .tun file over, and... nothing! Even more confusingly, there's _another_ popular softsynth that _also_ begins with an S and is _also_ 5 letters long, but only supports .tun files, not .scl. 

Anyway, since Surge supports .scl files, I think it would be less confusing if **the button was labelled "scl" for "SCaLe"**. 

However, I also understand that people may think primarily of different selections of notes within 12-TET tuning when seeing "scale" (minor scale, bebop, etc etc). So writing out "tuning" in full might also be acceptable - though this would destroy the symmetry with "mpe" above it. A terrible solution to this problem, which I only present in the spirit of bad ideas, would be to then also change the "mpe" label to "MiPoEx" which, despite its myriad flaws, is at least the same number of letters as "tuning" :stuck_out_tongue:

**Comment by K0rrid0r** [comment]
It is already renamed to 'Tune' in the nightly beta.

![191](https://user-images.githubusercontent.com/56724286/87214578-1bc48f80-c32e-11ea-98b2-920f37b88d0a.gif)

download it here:
https://surge-synthesizer.github.io/nightly

**Comment by baconpaul** [comment]
Indeed - we agreed and changed it! 170 will have this fix in the next month so going to close this issue. 

Thanks for the suggestion @MBYlt
