### ISSUE TITLE
Virustotal detection

### ISSUE THREAD

**Issue by withviz** [surge-synthesizer/surge#2336]
**Describe the bug**
Virustotal - detects 2 things in the Win 64bit setup file
https://www.virustotal.com/gui/file/50f621ac0d2f287510953a63045deb7ebaee85d65be3fa79d1f91907ee74fe4d/detection
**Please let us know your surge version**
1.6.6 - 2020-02-27
Surge-1.6.6-Setup.exe

**Comment by mkruselj** [comment]
False positive. Please let them know that our binaries are safe.
