### ISSUE TITLE
Step-Seq randomization bug when rate is disabled and using Random trigger mode

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#2337]
When rate is deactivated in a Step-Seq and trigger mode it set to random, it will trigger randomly somewhere in **all the 16 steps** instead of **only those inside the two length markers**.

**Comment by baconpaul** [comment]
Fix inbound including of the length 0 stuff.

**Comment by baconpaul** [comment]
I don’t deal with late loop scrubs properly.
