### ISSUE TITLE
Wavetable names are not displayed when flipping between presets

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2343]
**Describe the bug**
Someone who don't use github notified me about this. Here are his words.

"When you select a preset that uses a wavetable (like Polysynth\Crisp Noise Brass), you don't get to see the wavetable name, you only see (Patch Wavetable) under the oscillator. Maybe this is normal behaviour because the preset uses a waveform that it is not in the list of waveforms included with Surge, but it happens with all presets that I have checked so far. Knowing the wavetable name helps if you want to create a new preset from scratch based on that (I use that as a way to learn sound design ;-)"

So when flipping between presets the wavetable names are not displayed. Instead only "(Patch Wavetable)" is displayed.

It might not be a bug, but it was confusing enough for that person to think it was. And indeed it it strange if the preset was based on a wavetable from the existing list.
![194](https://user-images.githubusercontent.com/56724286/87257250-e8067880-c499-11ea-9147-f6b3ba5f5f1b.gif)

EDIT: If i save a preset with a certain wavetable, the name of that wavetable will display like normal if opened.
![195](https://user-images.githubusercontent.com/56724286/87257432-22244a00-c49b-11ea-9b87-edeee9fa72f4.gif)

hash 2a94a61 VST3
Window 8.2

**Comment by baconpaul** [comment]
If you save a *new* preset, these are streamed
Old presets don't have them streamed
here's where I changed it to do that in the 17 sprint
https://github.com/surge-synthesizer/surge/commit/bb51dd3930243f87641916422e9c4f0011b8b5ad implemented it
