### ISSUE TITLE
Possible issue with the skin engine

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2347]
![skin engine bug possibly](https://user-images.githubusercontent.com/2393720/87399239-6147bd80-c5b7-11ea-9752-4ad10b9be2cb.gif)

For some reason, when doing this in the XML, entering the mod assign mode for, say, LFO1, also colorizes the controls of the LFO1 as if they're modulatable - and they aren't. What's up with that?

Test skin:

[ED Surge Dark.zip](https://github.com/surge-synthesizer/surge/files/4917296/ED.Surge.Dark.zip)

**Comment by baconpaul** [comment]
OK I can reproduce this problem. Looking.
