### ISSUE TITLE
FR: Display actual parameter value set by modulation from Macro Control 1-8

### ISSUE THREAD

**Issue by RCJacH** [surge-synthesizer/surge#2357]
## Is your feature request related to a problem? Please describe.

Version 1.6.6, REAPER, Windows 10.

Currently, parameters do not display the actual value it is currently set with Macro Controls.
For example, if I set the Output Volume to `-inf dB`, and assigned modulation from Control 1 to the Volume parameter, regardless of what value Control 1 is at, the Output Volume display stays `-inf dB`.

Just like Massive.

The problem with this is that I cannot see the actual range of the modulation of some parameters.

If I set modulation to Output Volume, I get range `-1` to `1`...umm, I'm assuming that's the modifier to the whole range of volume? But then if I try to modulate the Master Volume, I get `-48` to `48`, that's probably in dB. Do the same with Attack of an envelope I get `-13` to `13`...while the actual range of the parameter is `0` to `32s`.

So you see the point, I don't know the range of a modulation when using Controls (and LFOs, but let's just stay with Controls).

## Describe the solution you'd like

I see 2 ways of dealing with this:
1. Have the parameter actually change value based on the current Controls. So in the Output Volume example, after moving Control 1 to max, the current Output Volume is at the right most, and when we move our mouse to the slider it displays `0dB`.
2. Display the actual maximum value of modulation when doing assignment. So rather than displaying the modifier of `-1` to `1`, it displays `-inf dB` to `0 dB` or whatever.

**Comment by baconpaul** [comment]
We completely agree! That's why in Surge 1.7 (and in the current nightly) we have completely overhauled these displays to add units everywhere. Here's a demo video.

https://www.youtube.com/watch?v=A_v-PkfohpQ&t=15s

So I think that the exact request you want is the one demonstrated in this video so I'll close the issue. If it's not please reopen it with a comment!
