### ISSUE TITLE
LV2 uiextension

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2391]
Hey @falkTX and @jpcima 

when building for clang 9 over in #2386 we noticed that

```
/usr/ports/audio/surge-synthesizer-lv2/work/surge-release_1.7.0/src/lv2/SurgeLv2Export.cpp:158:15: error: expression result unused [-Werror,-Wunused-value]
              "    lv2:extensionData ui:idleInterface .\n";
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

this constant was not in the string because of the ; above. Not wanting to change the manifest I just commented it out. But I wonder if we need this at that line; and also if that could be causing #1975 so wanted to make it a separate issue since we fixed the clang problem over in that other issue.

**Comment by jpcima** [comment]
Hi, yes this is absolutely a problem and needs repairing.
This seems it was introduced by accident in the scale factor commit a0a7034.

**Comment by baconpaul** [comment]
OK let me fix it to remove the ; then. That will close this issue.

**Comment by baconpaul** [comment]
@jpcima can you peek at #2393 - that's where we will end up. Thank you!
