### ISSUE TITLE
1.7.0 macOS Mojave Skin Support Error

### ISSUE THREAD

**Issue by smilinggoat** [surge-synthesizer/surge#2394]
**Describe the bug**
When loading the AU on macOS Mojave, the dialog box "Skin Support Error" appears with the following text below it: "Default skin not located. Surge is probably mis-installed"
I initially installed via brew. When I encountered the error, I then installed via the mpkg on the DMG, and the error still occurred.
I have tried loading in Hosting AU, Logic Pro X, Ableton Live 10, Audition.
When trying to select a new skin via the Menu, a different Skin Error dialog is displayed.

**Please let us know your surge version**
1.7.0

* Surge Version: 1.7.0
* Plugin type: AU
* Bits: 64

**To Reproduce**
1. Load Surge in AU host
2. See error
![Screen Shot 2020-07-28 at 21 27 04](https://user-images.githubusercontent.com/569236/88866912-d70b7600-d1c0-11ea-8b4e-f298c5139661.png)
3. Click on Menu in Surge to select new skin
4. See other error
![Screen Shot 2020-07-28 at 21 27 32](https://user-images.githubusercontent.com/569236/88866915-d83ca300-d1c0-11ea-91bc-e26894dd20ec.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Host: Logic, Live, Audition, Hosting AU

**Comment by baconpaul** [comment]
Hi! This indicates that you have the component but you don't have the resources. Can you check two things

1. If you can get the synth to open through these errors attach a screenshot of the about screen; and
2. Can you see what is in /Library/Application Support/Surge and also if you have a ~/Library/Application Support/Surge? 
3. Can you attach the contents of /Library/Application Support/Surge/BuildInfo.txt

I just now did a `brew cask reinstall surge-synthesizer` and it resulted in this

```
cat /Library/Application\ Support/Surge/BuildInfo.txt
Version: 1.7.0
Packaged on: 2020-07-28 12:57:39
On host: Mac-1595938443293
Commit: 8fd9e67029dcd6e4d6f0b294dba31409e3c9207e
paul:~/dev/music/surge$ 
```

**Comment by smilinggoat** [comment]
Hi Paul, thank you for the quick reply!

1. The AU about screen:
![Screen Shot 2020-07-29 at 17 43 17](https://user-images.githubusercontent.com/569236/88867732-3074a480-d1c3-11ea-853e-e362b29c2b10.png)

2. /Library/Application Support/Surge contains the following:
- BuildInfo.txt
- patches_3rdparty/
- wavetables/
- configuration.xml
- patches_factory/
- wavetables_3rdparty/
- paramdocumentation.xml
- skins/
- windows.wt
- patchbrowser/
- tuning-library/

~/Library/Application Support/Surge contains the following:
- configuration.xml
- patches_factory/
- wavetables/
- patches_3rdparty/
- surge_license.txt
- windows.wt

3.   /Library/Application Support/Surge/BuildInfo.txt contains the following:

```
Version: 1.7.0
Packaged on: 2020-07-28 12:57:39
On host: Mac-1595938443293
Commit: 8fd9e67029dcd6e4d6f0b294dba31409e3c9207e
```

**Comment by baconpaul** [comment]
Right. So just rename `~/Library/Application Support/Surge` to `~/Library/Application Support/Old Surge`, then restart the lot, and you will be fine.

In 1.7.1 I'm going to change the lookup semantics so if you load the component from /Library you prefer the resources from there. Right now the (old) local copy is winning and that's what is screwing you up.

I'm somewhat curious how you got that local copy. Did you build the synth by hand at one point? That's most of how I know it gets there.

**Comment by baconpaul** [comment]
Oh also I have improved that skin error message for 1.7.1 after another user hit this on KVR yesterday.

**Comment by smilinggoat** [comment]
Amazing, thank you. That did the trick!

I don't recall ever building Surge for scratch. I've been running it via brew for probably at least a year I'd say, so maybe from some old build? Hard to say. Thanks again!

**Comment by baconpaul** [comment]
Cool let me close this. Glad you got it working.

I added an issue to 171 to do a more reasonable thing if you have an old local copy and am running from global.

Have fun making music with Surge!
