### ISSUE TITLE
Not recognised on Ableton 8

### ISSUE THREAD

**Issue by Markovitch1** [surge-synthesizer/surge#24]
I tried the 3 releases of the installer, both vst2 and vst3, tried to re-start the computer, but none of them are displayed on my Ableton 8, windows 8, I'm so disapointed, any ideas to make it work ?

**Comment by cyanit** [comment]
Does Ableton 8 support 64-bit vsts?
Even Ableton 9 doesn't support VST3, it would surprise me if AL8 would lack a core feature as well.
Please take a look at Ableton Live 8's spec sheet.

**Comment by Markovitch1** [comment]
Yes you're right, I didn't take attention that it's a 64bit plugin.. Thought it was 32bit as Surge is quite "old" now. When first release came out back in the days, it was 32bit, right ? Could be nice to make it available for those "not up to date guys" like me ;)
Thx for th answer anyway

**Comment by cyanit** [comment]
but you could probably recompile it yourself as 32bit.

**Comment by Markovitch1** [comment]
I guess but I'm not a programmer at all. I'll keep the 64bit installer on a folder til I upgrade my daw

**Comment by cyanit** [comment]
> I guess but I'm not a programmer at all. I'll keep the 64bit installer on a folder til I upgrade my daw

just use a bitbridge, jBridge works in both ways and is 15 bucks

**Comment by kzantow** [comment]
Note: as of Xcode 10, Apple has removed support for 32-bit... even with the 64-bit version, there are issues getting it recognized by DAWs at present; I've captured as much info as I've figured out in #3 so far.

**Comment by esaruoho** [comment]
here's a ticket re:Mac  32-bit versions ( #115 ) - would be good to be able to bake 32-bit windows VST2/VST3 too

**Comment by esaruoho** [comment]
@Markovitch1 hi, are you still having issues using the newer, January 2019 builds of Surge on your Ableton Live 8? Could you check?

**Comment by baconpaul** [comment]
Hi @Markovitch1 windows now has a 32 bit installer in both the nightlies and the 1.6 beta 6. Can you try that and if it works we can close this ticket? Appreciated!

You can find the installers at https://surge-synthesizer.github.io/

**Comment by Markovitch1** [comment]
@baconpaul Sur(g)e, just dowloaded it, I'll get back to u very soon

**Comment by Markovitch1** [comment]
@baconpaul Gave it a try this morning (vst2 32bit on Live 8.2.5), it works smooth so far. THANKS A LOT !!!!!!!!!!

**Comment by baconpaul** [comment]
Great; I’m super glad to hear that. I’ll close this ticket.

Please do keep checking back at the website as we move from beta6 towards a 1.6.0 final release this spring.
