### ISSUE TITLE
Options for cursor restore position after hiding

### ISSUE THREAD

**Issue by MD-78** [surge-synthesizer/surge#2408]
**Describe the bug**
Cursor restore change in 1.7.0 was not a nice change. Cursor should be restored at current drag position but not outside of fader width (when cursor is hidden while dragging). Say I drag Cutoff fader fully to the right (but the drag itself even goes behond), the mouse cursor should be restored at the right edge of the Cutoff fader when mouse button got release. Currently it jumps back to the left - why? Looks and feels weird.

**Please let us know your surge version**
This information is all in the menu/about screen

* Surge Version: 1.7.0
* Plugin type (VST2, 3 or AU): VST3
* Bits (32/64): 64

**To Reproduce**

1. drag Cutoff fader fully to the right (the drag itself even goes behond)

**Expected behavior**
The mouse cursor should be restored at the right edge of the Cutoff fader (when drag was behond right edge) when mouse button got released. Currently it jumps back to the left - why? Looks and feels weird.

**Screenshots**
[untitled.zip](https://github.com/surge-synthesizer/surge/files/5006751/untitled.zip)

**Desktop (please complete the following information):**
 - OS: Windows 8.1 Pro
 - Host: REAPER 6.13 x64

**Comment by baconpaul** [comment]
@mkruselj did you make this an option? I forget?

**Comment by mkruselj** [comment]
Yes I made this option and this is how it should work, I compared to other plugins that have this feature and it's working exactly like that (i.e. Massive X).

**Comment by MD-78** [comment]
This is not nice. I don't care what Massive X does. I also don't see an option in Surge for this.

Have a look at Voxengo plugins - they are perfect in this.

**Comment by mkruselj** [comment]
Option is in the Menu -> User settings -> Mouse behavior -> Show cursor while editing.

**Comment by MD-78** [comment]
But I don't want the cursor to be shown all the time (because you can hit screen edges).

I'm  not a programmer, that's why I bring it up here.


Current Surge behaviour mares no sense. You release the mouse button -> cursor getting moved to drag start position -> now you have to move the cursor back to the current fader position to start a new drag (this step would be unneeded when the cursor would be shown where button released).

**Comment by baconpaul** [comment]
@mkruselj Ithink @MD-78‘s point is “the 1.6.6 behavior was better”.

I’m not a windows user and this cursor hiding stuff freaks me out since mac doesn’t do it so I don’t have a strong opinion, but perhaps add an option to restore the 1.6.6 behavior is the request here?

**Comment by mkruselj** [comment]
Surge sliders react on click and drag from anywhere, you don't have to move the cursor at all. See:

![cursor](https://user-images.githubusercontent.com/2393720/89033348-e3b1da80-d336-11ea-955b-d723433e0b2f.gif)

**Comment by MD-78** [comment]
Ok, it still makes no sense really (it looks and feels weird to the eye - the eye expects the cursor at current position within fader range). Why did you do this change? Just because Massive X does it doesn't have to mean that's it's good.

**Comment by mkruselj** [comment]
Because I didn't like the 1.6.6 behavior at all, it was all kinds of wrong.

We can iterate on this, but we would appreciate more polite discourse, without stuff like "makes no sense" (it always makes sense to somebody else, maybe not you) or "stuff is bad" (yet it's someone's work and hours still spent by someone to make it happen).

**Comment by baconpaul** [comment]
Yeah I think this was very broken in 1.6.6 and is now better; but could be better still. Like I said, the cursor hiding just freaks me out every time I start a windows VM anyway!

Let me echo @mkruselj comment though too - we're all volunteering here for fun; it was a lot of work to make 170 work. While @MD-78 I think you are right there's a better choice than the one we made perhaps, and we definitely appreciate you bringing the point up, the more we can be polite and nice to each other the more fun we will have!

Anyway so perhaps the right semantic is indeed "mouse restores to point inside slider where release, bounded by the bounding box of the slider widget". That will be weird in non-exact mode still but it might be better maybe?

**Comment by MD-78** [comment]
@mkruselj: Why does it makes sense to you to show the cursor where drag started? To me it feels wrong (eye has to relocate all the time).

**Comment by MD-78** [comment]
> Anyway so perhaps the right semantic is indeed "mouse restores to point inside slider where release, bounded by the bounding box of the slider widget".

Exactly - this would be perfect. I also didn't want to be unpolite. I'm not a native english speaker.

**Comment by baconpaul** [comment]
Yeah @MD-78 I give folks the benefit of the doubt that they are not trying to be impolite. No worries. Just trying to make sure we stay focus on the issue at hand.

@mkruselj I think the idea we've converged to is a pretty good one. We should try and get it in 1.7.2? (@MD-78 we are probably doing a 1.7.1 micro-release this weekend to fix some bigger infrastructural issues - I don't think we can get this one in that release. But we can queue it up for our next major release). Thoughts?

**Comment by mkruselj** [comment]
It makes sense to me because of the way Surge sliders work which I showed. Once you get the feel for that your eye doesn't care about the mouse cursor that much (especially now that we have hover states for the sliders too, which help in identifying hotspots), and you actually _work faster as a consequence_. You don't have to chase the mouse cursor at all once you're down with this concept.

**Comment by baconpaul** [comment]
I do wonder that the proposed semantic would be weird in non-exact mode yeah. 

Hmm. Let me remember how weird this code is again. But definitely something where we can optionize it in 1.7.2 along the way.

**Comment by MD-78** [comment]
> 
> 
> It makes sense to me because of the way Surge sliders work which I showed. Once you get the feel for that your eye doesn't care about the mouse cursor that much (especially now that we have hover states for the sliders too, which helps in identifying hotspots), and you actually _work faster as a consequence_. You don't have to chase the mouse cursor at all once you're down with this concept.

My eye doesn't like it when chasing the fader cap. I know that I doesn't have to chase it but when I do it feels wrong (flickery). I personally don't care about where the drag started. I prefer less flickerung and unexpected movement of the cursor.

**Comment by mkruselj** [comment]
We're trying to iterate on this and improve it closer to what you'd expect, but unfortunately it is very, very, hard. There are too many edge cases where the cursor just doesn't appear at the position where you'd expect it to, so I am inclined to simply revert everything to the behavior that is in 1.7.0 and call it a day.

Anyone else is free to check out the code and improve this, but as it is, I don't like the half-assed iteration we ended up with because it breaks too easily.

**Comment by baconpaul** [comment]
Those credits are only good for slack, @mkruselj - chuckle.

So i converted the PR to draft. We have lots of time before 1.7.2. Lets leave this open and aspirationally tagged for that release and see if we can get it. We are close but not there for sure. And yeah it is hard.

**Comment by baconpaul** [comment]
Hey @MD-78 we've just finished re-writing a lot of the cursor code (including to work on Mac) and it now does basically exactly the right thing. I'll close this issue when I merge, but the nightly, and more importantly the January 1.8.0 release, will have way better mouse positioning behavior. (And also a much cleaner C++ cross platform API but obviously you care about that less).

The nightlies are always available on our website. The fix should be in in about an hour I bet.

Best

**Comment by MD-78** [comment]
Thanks! It's fine in 1.8.0!

**Comment by baconpaul** [comment]
Oh yeah thank you! it was quite a bit of work but we got it right. Thanks for tagging back on this issue :)
