### ISSUE TITLE
VST3 3.7.0

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2409]
Released, and includes support for mac arm apparently. So will need to upgrade this fall sometime.

Looking it seems https://developer.steinberg.help/display/VST/%5B3.7.0%5D+Process+Context+Requirements Is the one thing which we will have to adopt

**Comment by baconpaul** [comment]
So the changes needed for ARM mac it seems were in vstgui mostly and I branched those into our vstgui branch. So we actually don't have to do this in 19 if we don't want. Will leave it here but ....

**Comment by mkruselj** [comment]
Closing this because JUCE will take care of this for us, basically, and we won't be updating our hand-rolled VST3 wrapper for SDK 3.7.0.
