### ISSUE TITLE
Load/Save FX user presets

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#2410]
**Is your feature request related to a problem? Please describe.**
As a patch designer, I want to re-use FX settings, or use my other FX settings as a basis for a new FX configuration.

**Describe the solution you'd like**
Load/Save FX presets, like we do with patches.

**Describe alternatives you've considered**
It's possible to use a workaround:
* Save the current preset [1]
* Load up a source patch preset,
* Copy the preset,
* Load back the target patch,
* Paste in the FX configuration into the desired slot.
Alternatively, it might be possible to Copy + Paste across Surge instances; I haven't tried.

**Additional context**
(none)

**Comment by baconpaul** [comment]
We agree! That’s why we added this feature in 1.7.0 👍  (It’s not in 1.6.6 tho)

In the menu is a ‘save as’ option which will save the preset. You will get a blob of xml in your documents surge and you will see your preset show up at the end of the other presets for that type.

Lemme close this but please re-open it if the feature in 17 doesn’t work for you.
