### ISSUE TITLE
preset problem in Reaper 6

### ISSUE THREAD

**Issue by KimCMN** [surge-synthesizer/surge#2412]
**Describe the bug**
No presets can be loaded. When you click on the preset drop down window and select any one, nothing happens.

**Please let us know your surge version**
Surge Version: 1.7.0 - 2020-07-28 (VST3) x64

**Desktop (please complete the following information):**
 - OS: Windows 10 PRO
 - Host Reaper 6

**Comment by baconpaul** [comment]
Do you have audio transport running? That is can the synth play any notes?

**Comment by mkruselj** [comment]
I'm afraid I cannot confirm this here. More info required, maybe a video as well?

**Comment by KimCMN** [comment]
Hello.  after the question about transport, I realized that the driver for
my audio interface was disabled and this was somehow affecting the surge's
preset selection box ... when enabling the driver everything returned to
work correctly ...

Em dom, 2 de ago de 2020 17:26, EvilDragon <notifications@github.com>
escreveu:

**Comment by baconpaul** [comment]
Yeah cool that matches a bug we know that process has to be called at least once to swap presets. I’ll close this then. Enjoynsurge!
