### ISSUE TITLE
SurgeEffectsBank adds noises while processing in Reaper

### ISSUE THREAD

**Issue by takeoffmymonkey** [surge-synthesizer/surge#2415]
Version of SurgeEffectsBank : Windows 32 bit VST3, Surge 1.7.1.5270cfb
OS: Windows7 Service Pack 1
Host: Reaper 5.99 @ 44.1 kHz

==============

If you add SurgeEffectsBank to empty track it may/may not produce noise right away by itself (instead of silence).
If there is VST instrument/sample on the track, it adds noises to the sound every time.

Expected: no noise, just processing.

**Comment by baconpaul** [comment]
Thank you for the report.

Is it one time noise or continuous noise?

I don’t know that we have tested the 32 bit SFXBank on Windows 7 ever. I am curious what the problem will be!

**Comment by takeoffmymonkey** [comment]
> h

Its more like crackles that go with orginal + processed by SurgeEffectsBank sound. May be sample rate issue or something.

**Comment by mkruselj** [comment]
Hum, I can't confirm this happening in Reaper over here (x64, W10).

**Comment by takeoffmymonkey** [comment]
Looks like it is somehow connected to ASIO drivers of my sound card, because switching to other audio devices in Reaper fixes the issue. 

But this is kind of strange, because I've never had issues like this with any other plugins for many years I own this card.

**Comment by mkruselj** [comment]
Sounds like mismatched sample rate somewhere somehow.

**Comment by baconpaul** [comment]
yeah; we test surge automatically at a bunch of sample rates and I run 48 k all the time (but I'm on macOS with CoreAudio which generally just works). I'm not sure how we can debug your problem. Any ideas?

**Comment by takeoffmymonkey** [comment]
Honestly, I am pretty confused as well because its working with ASIO4ALL drivers running for this card @ 44.1k. I could try debugging myself directly on the machine, but unfortunately too busy this month with other dev stuff. I may still assist if necessary, though.

Should I close the issue for now?

**Comment by mkruselj** [comment]
Check all your audio in/out devices for these checkboxes:

![image](https://user-images.githubusercontent.com/2393720/89272057-e44fb700-d63d-11ea-8432-591fa3a3af75.png)

They should be disabled.

**Comment by takeoffmymonkey** [comment]
Tried these two options both on and off.
Also tried on and off the following options in Reaper, but card just seems to ignore any forcing:
![options](https://user-images.githubusercontent.com/25670064/89280745-bf653f00-d651-11ea-85b5-a6c33bad23ce.jpg)

**Comment by baconpaul** [comment]
No problem leaving it open. I've tagged it as 'currently unscheduled' so it won't show up on our book of work. We sweep issues every so often to see if people are still looking, but unfortunately none of us can debug this I don't think, since we can't repro it.

Sorry you are having this problem! If you decide to dive in happy to help you navigate.

**Comment by mkruselj** [comment]
Yes don't force any sample rates. Some audio interfaces/drivers don't like that.

**Comment by tank-trax** [comment]
this may be a silly question, but have you tried to clear your VST cache and rescan your plugins?

**Comment by takeoffmymonkey** [comment]
Didn't help..

**Comment by takeoffmymonkey** [comment]
Installed other version of drivers. No success.

**Comment by tank-trax** [comment]
do you have an older version(s) of SurgeEffectsBank to test to see if it happens on previous versions too?

**Comment by takeoffmymonkey** [comment]
Tried following combinations (all unsuccessful):

Win 7 64-bit - Reaper 5.99 32-bit - Surge-1.7.1-Setup-x86
Win 7 64-bit - Reaper 5.99 32-bit - Surge-1.6.6-Setup-x86
Win 7 64-bit - Reaper 5.99 32-bit - Surge-1.6.2.1-Setup-x86
Win 7 64-bit - Reaper 6.13 64-bit - Surge-1.6.6-Setup

**Comment by tank-trax** [comment]
Based on this comment:

> Looks like it is somehow connected to ASIO drivers of my sound card, because switching to other audio devices in Reaper fixes the issue.
> 
> But this is kind of strange, because I've never had issues like this with any other plugins for many years I own this card.
> 
> Update: card is Focusrite Saffire, working at 44,1k, and switching to 48k fixes the issue as well! But back to 44.1k and the issue is back.

and that you mentioned that it worked with ASIO4ALL

> Honestly, I am pretty confused as well because its working with ASIO4ALL drivers running for this card @ 44.1k. I could try debugging myself directly on the machine, but unfortunately too busy this month with other dev stuff. I may still assist if necessary, though.

I am thinking that your first hunch may be correct, that this is likely something related to the ASIO drivers provided for your sound card.

The only other thing I would suggest which may or may not be possible, is to try using SuregEffectsBank in other DAWs or hosts to see if it causes the similar behaviour; works at 48 kHz and clips at 44.1 with the provided ASIO, and works at both sample rates with ASIO4ALL,

I'd be curious to see what another sound card would do at 44.1 kHz on the same system.

**Comment by takeoffmymonkey** [comment]
Tested in FL 12. Wasn't able to get proper sound using any sample rate or driver for this card at all. (In Reaper only ASIO driver of Saffire @ 44.1k has the problem).

I am away from good internet and all my hardware this month, so can't do extensive testing, unfortunately.

**Comment by j5v** [comment]
Cakewalk (Windows 10) here. ISO4ALL is the only one that works well with Surge for me. MME stutters (and has big latency)

**Comment by mkruselj** [comment]
MME is not really good for realtime audio purposes like running a virtual instrument. :)

**Comment by j5v** [comment]
> MME is not really good for realtime audio purposes like running a virtual instrument. :)

Found that out pretty quickly, then went for ISO4ALL.

**Comment by mkruselj** [comment]
I cannot confirm this issue on three machines I have in house. Considering there was no further input from @takeoffmymonkey in half a year, I will close this issue but also label it Awaiting user information. If OP still has this issue, ping here please and we will reopen. If not, it's as good as fixed, then. 🙂
