### ISSUE TITLE
Implement build-linux wrapper for ARM (as opposed to direct cmake)

### ISSUE THREAD

**Issue by hfiguiere** [surge-synthesizer/surge#2417]
**Describe the bug**
`./build-linux.sh build` will fail on ARM or AARCH64 because LINUX_ON_ARM is never set and `-sse2` is still part of the CXXFLAGS

**Please let us know your surge version**
1.7.1 (tag from github)

* Surge Version: 1.7.1
* Plugin type (VST2, 3 or AU): doesn't matter
* Bits (32/64): either

**To Reproduce**
1. Try to build on arm or aarch64 Linux: `./build-linux.sh build`

It fails:
```
Scanning dependencies of target surge-vst3-dll
[  2%] Building CXX object CMakeFiles/surge-vst3-dll.dir/src/common/dsp/effect/ConditionerEffect.cpp.o
[  2%] Building CXX object CMakeFiles/surge-vst3-dll.dir/src/common/dsp/effect/DistortionEffect.cpp.o
c++: error: unrecognized command line option ‘-msse2’
make[3]: *** [CMakeFiles/surge-vst3-dll.dir/build.make:126: CMakeFiles/surge-vst3-dll.dir/src/common/dsp/effect/ConditionerEffect.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
c++: error: unrecognized command line option ‘-msse2’
make[3]: *** [CMakeFiles/surge-vst3-dll.dir/build.make:139: CMakeFiles/surge-vst3-dll.dir/src/common/dsp/effect/DistortionEffect.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:274: CMakeFiles/surge-vst3-dll.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:308: CMakeFiles/Surge-VST3-Packaged.dir/rule] Error 2
make: *** [Makefile:229: Surge-VST3-Packaged] Error 2
```

**Expected behavior**
It builds

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Additional context**
The changelog explicitely say these arch are supported on Linux.
Maybe the linux script should just pass the proper option to cmake.

**Comment by tank-trax** [comment]
have you tried building using instructions in the README.md?

[## Building for ARM platforms](https://github.com/surge-synthesizer/surge/blob/main/README.md#building-for-arm-platforms)

**Comment by baconpaul** [comment]
Yeah that's exactly right @tank-trax for ARM you need to use CMAKE directly since build-linux doesn't know which ARM flags you might want yet. @hfiguiere we've built on several platforms following those directions (or cross compiled using some of the other cmake stubs). And as the documentation says, would welcome any help improving the ARM build experience.

I suppose the right thing is for build-linux to do a `uname -m` and then check to see if there's a stub; or for build-linux to take an --arm-type flag and if `uname -m` isn't `x86_64` or whatever and `--arm-type` isn't set to bail out with an error.

**Comment by baconpaul** [comment]
I also updated the build-linux section of the readme for now to say

> build-linux.sh is a wrapper on the various cmake and make commands needed to build Surge. As with macOS, it is getting smaller every day as we move more things direclty into cmake. As of Surge 1.7.1, build-linux.sh only works on intel platforms. If you are building on ARM please keep reading below for directions on the ARM compile mechanism.

**Comment by tank-trax** [comment]
I tend to only use the script for installing/removing Surge

`./build-linux.sh -l install` 
and 
`./build-linux.sh -l uninstall`

**Comment by baconpaul** [comment]
yeah let me tag this 1.7.2 so that someone can add the arch flags (I'll do it before the release if no-one else gets to it) but I think this is one where "consult the manual" and "improve the script" are the answer; we do still build on ARM no problem just not in the same way as intel.

**Comment by hfiguiere** [comment]
Thanks for all the insight.

Switching to only using cmake to build works on aarch64 (passing the right option). But my point still stand. Unless you are cross compiling, it should just detect the arch it is being build.

On arm, I get another error:
```
/usr/bin/c++  -DARM_NEON=1 -DLINUX=1 -DRELEASE=1 -DTARGET_VST3=1 -DUSE_STD_FILESYSTEM=1 -Dsurge_vst3_dll_EXPORTS -Ilibs -Ilibs/filesystem -Ilibs/xml -Ilibs/catch2 -Ilibs/strnatcmp -Ilibs/tuning-library/include -Isrc/common -Isrc/common/dsp -Isrc/common/thread -Isrc/common/vt_dsp -Igeninclude -Isrc/common/gui -Ivstgui.surge -Ilibs/nanosvg/src -Isrc/linux -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/lib/arm-linux-gnueabihf/libffi-3.2.1/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -Ilintemp -Ilibs/simde -Isrc/vst3 -Ivst3sdk -Isurge-headless -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -O3 -DNDEBUG -fPIC   -march=native -mcpu=native -Wno-psabi -flax-vector-conversions "-D_aligned_malloc(x,a)=aligned_alloc(a,x)" "-D_aligned_free(x)=free(x)" -Wno-multichar -fvisibility=hidden -fvisibility-inlines-hidden -fdata-sections -ffunction-sections -std=c++17 -MD -MT CMakeFiles/surge-vst3-dll.dir/src/common/vt_dsp/lipol.cpp.o -MF CMakeFiles/surge-vst3-dll.dir/src/common/vt_dsp/lipol.cpp.o.d -o CMakeFiles/surge-vst3-dll.dir/src/common/vt_dsp/lipol.cpp.o -c src/common/vt_dsp/lipol.cpp
src/common/vt_dsp/lipol.cpp: In member function ‘void lipol_ps::set_blocksize(int)’:
src/common/vt_dsp/lipol.cpp:19:23: error: ‘vdupq_n_f32’ was not declared in this scope
   19 |    lipol_BLOCK_SIZE = vdupq_n_f32(bs);
      |                       ^~~~~~~~~~~
```

**Comment by baconpaul** [comment]
Ahh "should" - one of the most interesting words in English, especially when applied to software. Luckily Surge is open source, and the mechanism by which "should" becomes "is" is a pull request :)  I'm sure I'll get to this before we release 1.7.2 but if you want to hack that into build-linux a contribution would be welcome.

I fired up my Raspberry PI (I bought a PI4 to get this working on ARM for real a month ago - man what a cool bit of hardware!) and if I checkout at tag release_1.7.1 I get a build working fine. Here's the OS and compiler versions I'm using and commands I used

```
 cmake -Bbuild -DARM_NATIVE=native
 cmake --build build --config Release --target Surge-VST3-Packaged
```

```
pi@raspberrypi:~/surge $ uname -a
Linux raspberrypi 5.4.42-v8+ #1319 SMP PREEMPT Wed May 20 14:18:56 BST 2020 aarch64 GNU/Linux
pi@raspberrypi:~/surge $ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/8/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --disable-libphobos --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6) 
```

That symboling (vduqp_n_f32) should come from the simde headers. I wonder if your compiler is somehow skipping an include of "globals.h" in that file? Perhaps try an `#include "globals.h"` at the top of `lipol.cpp` and see if you get a build?

ARM is new; and none of us here are experts. The community has been helpful getting it to work on linux, and I'm motivated because I'm a mac user looking at the future, but I'm sure there are edges on OS/Compiler combinations we haven't seen. Again we welcome pull requests with fixes, changes, and so on.

**Comment by hfiguiere** [comment]
The failure is on `arm` not `aarch64`. (32bit vs 64bits, similar to `i386` vs `x86_64`)

So yeah `aarch64` works when not using the wrappers and passing the right option.

BTW I'm ok with the lack of `arm` (32-bits) support but then the documentation is unclear.

**Comment by baconpaul** [comment]
Hmm do we know what the right equivalent function is on 32 bits? I'd be happy to patch and correct the code?

I guess if I ran 32 bit raspbian on my pi I would see the error, yeah?

I'd much rather fix the problem than document that it exists :)

**Comment by baconpaul** [comment]
Actually can you do me a favor? That code was in there from the first port we tried, before we used the simde library. I just removed that ARM_NEON and it all compiled aarch64 still with the simde library giving me the right stuff.

Can you apply this patch and let me know if it builds in your env? If so I will merge that into the main branch.

```
diff --git a/src/common/vt_dsp/lipol.cpp b/src/common/vt_dsp/lipol.cpp
index ef4744fc..e7d233e3 100644
--- a/src/common/vt_dsp/lipol.cpp
+++ b/src/common/vt_dsp/lipol.cpp
@@ -15,11 +15,7 @@ lipol_ps::lipol_ps()
 
 void lipol_ps::set_blocksize(int bs)
 {
-#ifdef ARM_NEON
-   lipol_BLOCK_SIZE = vdupq_n_f32(bs);
-#else
    lipol_BLOCK_SIZE = _mm_cvt_si2ss(m128_zero, bs);
-#endif
    m128_bs4_inv = _mm_div_ss(m128_four, lipol_BLOCK_SIZE);
 }
```

thanks!

**Comment by hfiguiere** [comment]
Yes this works

**Comment by baconpaul** [comment]
Great I’ll merge it shortly

What does uname -a and -m say for you? Maybe I can whack build linux while in there

**Comment by hfiguiere** [comment]
`arch` or `uname -m` report `armv8l`

**Comment by baconpaul** [comment]
OK I merged this and while I was in there put in a uname check in build-linux so build-linux will now build. Updated the documentation accordingly. Closing this issue. 

Best
