### ISSUE TITLE
Surge-linux 1.71.deb not detected by Ardour 6.20

### ISSUE THREAD

**Issue by alasta4204** [surge-synthesizer/surge#2422]
Surge-linux 1.71.deb not detected by Ardour 6.20 

I have refreshed the plugin list and tried to open  in carla

Any help greatly appreciated

Alastair Fulcher

**Comment by baconpaul** [comment]
Hi!

Surge-linux deb does not contain an LV2. https://surge-synthesizer.github.io/formats

You can read why there. If you want to use the LV2 bugs and all you can build from source. There are LV2 devs trying to make surge work with the format but it is unreliable for some technical reasons in the LV2 spec.

I have asked the Ardour devs to consider VST3 (https://discourse.ardour.org/t/vst-3-support/88241/18), as it is an open source cross platform format. 

But for now if you want to use Surge 1.7 in ardour you need to build yourself, and you will have the same set of problems that the Vi exhibited in 1.6.*

Will close this issue but please feel free to reopen it with questions if the build instructions on the GitHub don't work for you or whatever.
