### ISSUE TITLE
Default Skin image colour offset

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#2426]
Default skin looks like this in Linux...

![image](https://user-images.githubusercontent.com/41337033/89322497-47e3df80-d652-11ea-819f-e727f2767262.png)

**Comment by baconpaul** [comment]
Sorry can you help me understand what's wrong with that? I'm missing it.

**Comment by tank-trax** [comment]
for example where the word Scene is, the contrast between black and greyer black, the demarcation or line that goes across... is that supposed to be that way?

**Comment by baconpaul** [comment]
![Screen Shot 2020-08-04 at 3 40 25 PM](https://user-images.githubusercontent.com/13387561/89337367-d4010180-d668-11ea-9876-2bc0697b423f.png)

Here it is on mac. Yeah there's that hard terminated gradient at the top on that control.

**Comment by tank-trax** [comment]
would it not look better if the that line matched the boundary? even for the OSC, where the squared orange number lies, to have that demarcation above so the the orange square is below the line rather than overlapping it... perhaps if the gradient had a transition, but with that line there it looked off (goes to show how infrequently I've loaded the default skin)

**Comment by baconpaul** [comment]
Ahh now I see!

Well I'm not very good at 'better' or 'worse'. I'm happy to change it if you want to make an adjustment though! I just render what people who are better designers than me give us 👍

**Comment by tank-trax** [comment]
so it's not a bug, and you get the same additional pixels near Scene -3

I took a look at the vector graphic and made a few changes but now realize that there are a few more images that need tweaking

![image](https://user-images.githubusercontent.com/41337033/89345901-36143380-d676-11ea-8055-b1ea5043ecce.png)

will close this and start my first foray into skin design, albeit a simple visual tweak
