### ISSUE TITLE
"Add Modulation From" menu item

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2428]
When you RMB on a slider lets add a menu called "Add Modulation From"

Looks like

Add Modulation From > LFO1
                                         LFO2 

etc...

the list of submenus is all the controls which are available but which are not currently modulating the parameter.

It would them pop up the enter modulation button for that.

Idea from ENV1 on KVR. Good idea too.

**Comment by mkruselj** [comment]
Indeed good stuff. Of course, that menu shouldn't show if all modulators are already (for whatever reason!) modulating the parameter.

**Comment by baconpaul** [comment]
Yeah that's right.
Making the patch to test that edge case would be really hard if we didn't have this menu. but once we have it it's an easy test :)

**Comment by mkruselj** [comment]
This part in SGE should really help:

![image](https://user-images.githubusercontent.com/2393720/89340565-388b8300-d6a0-11ea-866e-f90b5289ccbc.png)

Basically if `n_ms` here equals `n_modsources` it means all modulators have already been assigned to that parameters and we don't show that menu!

**Comment by baconpaul** [comment]
yeah that's right!

I meant 'setting up a patch that tests that will be easier if we have it'. Otherwise i have to activate all the mod sources!

This is a neat feature.

**Comment by mkruselj** [comment]
![image](https://user-images.githubusercontent.com/2393720/89343846-37108980-d6a5-11ea-8f2e-6a5d4d43074d.png)

Yep, it is!
