### ISSUE TITLE
Step sequencer snap does not work as expected on Linux

### ISSUE THREAD

**Issue by xard-dev** [surge-synthesizer/surge#2457]
**Describe the bug**
Holding **shift** and **ctrl** modifiers does first snapping to a note or zero value but moving mouse stops the snapping immediately even if a modifier key is still held down.

**Please let us know your surge version**
Built from git main commit 9cec9d864e12dc57ac4ee8509743e81078a61b22

* Surge Version: 1.7.1-dev
* Plugin type: VST2, LV2 
* Bits: 64

**To Reproduce**

1. open Step Seq from Surge UI
2. draw steps holding **shift** or **ctrl**

**Expected behavior**
The drawn values are snapped according to modifier key held down.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.20
 - Host: Carla
 - Version: 2.1

**Additional context**
Affects both LV2 and VST2 versions and behaves identically on all tested hosts which include Carla, Ardour and Jalv.

**Comment by baconpaul** [comment]
@tank-trax can you confirm in your environment also? I wonder what’s eating the modifier.

**Comment by xard-dev** [comment]
Is **x11platform.cpp** good place to start from debugging?

**Comment by baconpaul** [comment]
First thing I would check is if kShift is properly set in CLFOGUi.cpp

**Comment by xard-dev** [comment]
Okay,

As a side am I doing something wrong trying to switch from release configuration to debug:
```
./build-linux.sh clean-all
./build-linux.sh cmake --project=lv2 --debug
./build-linux.sh build --project=lv2 --debug
```

When checked this results a build with no debug symbols:
```
gdb surge_products/Surge.lv2/Surge.so
...
(No debugging symbols found in surge_products/Surge.lv2/Surge.so)
(gdb)
```

**Comment by xard-dev** [comment]
If I switch CMakeLists.txt:34 CMAKE_BUILD_TYPE to Debug it works with same command line build steps:
```
gdb surge_products/Surge.lv2/Surge.so
...
Reading symbols from buildlin/surge_products/Surge.lv2/Surge.so...
(gdb)
```
(gdb can be used like this to easily check whether binary or library has symbols)

**Comment by xard-dev** [comment]
Okay, the kShift state is 0 if shift is not pressed and it swaps to 16 when pressed and inspected in scope of onMouseUp.

**Comment by xard-dev** [comment]
When inspected from onMouseMoved the first instance of kShift when pressed is 16 but immediately falls to 0 if I keep moving mouse.

**Comment by baconpaul** [comment]
Yeah debug builds are a bit Screwy in our cmake - feel free to open an issue and I’ll look but for now whack the cmake is the way to go

Right so that’s the problem. Some part of the stack - probably vstgui - isn’t keeping the modified alive in onmousemove and yeah that would be down in x11platform. 

In debughelpers we have a built in which prints the stack trace. If you are in mousemove on the ss drop that print in there and you can see where up the stack the mistake is

We have a fork of vstgui so if the bug is there we can patch it

**Comment by xard-dev** [comment]
In gdb stack trace can be activated with backtrace command now thinking about it it's incredibly useful to see the whole stack and go up in the stack file by file!

**Comment by xard-dev** [comment]
And thanks to that tip here's a patch: 
[x11_modifier_mousemove_diff.txt](https://github.com/surge-synthesizer/surge/files/5045334/x11_modifier_mousemove_diff.txt)

It turned out that vstgui x11 frame was not extracting modifiers in **xcb_motion_notify_event_t** handling with translateModifiers.

I'm not sure if this was deliberate or an overlooked thing but once I added the handling it started working.

**Comment by baconpaul** [comment]
Oh cool! There's some git work to apply that diff in the submodule and stuff but I will do so in the next day or so

Thanks very much for the find!!

**Comment by baconpaul** [comment]
And yeah gdb backtrace is useful but catching UI events live in the debugger is hard; that's why a printf version has bailed me out so many more times! Super handy.

**Comment by xard-dev** [comment]
No problem: this makes the step sequencer so much nicer to use.

With help of the backtracing I hopefully need to ask less and less where's this and that in the future. :sweat_smile:

**Comment by baconpaul** [comment]
yeah i've been programming a long time and still i find printf a better debugger than gdb and lldb in many cases. printing is so much easier. 
Will close this issue when it's all merged. May be tomorrow. But thanks!

**Comment by baconpaul** [comment]
Had a minute so am merging it. Also submitted the fix back to steinberg to see if they would merge it into their branch.

**Comment by baconpaul** [comment]
ok all done. thanks again!
