### ISSUE TITLE
text overlap in waveshaper modulation text info window when high precision readouts is on.

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2458]
**Describe the bug**
text overlap in waveshaper modulation text info window when high precision readouts is on.

![waveshaper overlaps the text](https://user-images.githubusercontent.com/56724286/89710398-e2119380-d982-11ea-9315-e2a0c42615fa.gif)

hash cfd21e6 VST3 / VST2

Windows 8.1

**Comment by mkruselj** [comment]
My suggestion would be to just make the popup wider if HPVR is enabled.

**Comment by baconpaul** [comment]
We already do. Just not wide enough!

**Comment by mkruselj** [comment]
This seems to have been fixed?

**Comment by mkruselj** [comment]
Oh actually I see the issue still. It only happens if you try assigning a _unipolar_ modulator (velocity, aftertouch...) to a dB target.
