### ISSUE TITLE
Info: a surge package for Fedora

### ISSUE THREAD

**Issue by ycollet** [surge-synthesizer/surge#2468]
Hello,

I added a package for surge for Fedora 30 ,31 and 32 on a COPR repository.
You can find the package here:
https://copr.fedorainfracloud.org/coprs/ycollet/linuxmao/

And the spec file is available here:
https://github.com/ycollet/fedora-spec/tree/master/surge

Best regards,

YC

**Comment by baconpaul** [comment]
Thank you!

We plan to do releases of the 1.7 family every few months from hereon out. Will the signed tags we do with releases notify you to change?

Also if there's text you would recommend for this page, please let us know: https://github.com/surge-synthesizer/surge-synthesizer.github.io/wiki/Surge-on-various-unix-like-distributions
