### ISSUE TITLE
"Load patch from file..." option in the browser

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#2475]
Pretty self-explanatory. It would be nice to have it pop an explorer and be able to chose a patch from wherever on the system, instead of having to copy it inside the user folder. Useful for quickly testing a problematic patch from someone, or things like that.

Exactly like the "Load wavetable from file..." option actually.

**Comment by baconpaul** [comment]
yeah and we should also do drag n drop of patches while at it.

**Comment by mkruselj** [comment]
Absolutely +1

**Comment by sourcebox** [comment]
"Save patch to file..." would also be handy in some situations.

**Comment by mkruselj** [comment]
But that's what Store button does already (or, alternatively, your DAW when you tell it to save a .fxp or .vstpreset). 🙂

**Comment by baconpaul** [comment]
This will be in an upcoming nightly.
