### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Tox86** [surge-synthesizer/surge#2478]
**Windows Resize: **
When i try to resize the window, zoom failed

* Surge Version: 1.7.1 
* Plugin type (VST 3 )
* Bits (64)

**Screenshots :**
![Studio_One5_scale_bug](https://user-images.githubusercontent.com/7013508/90191642-4079b000-dd8f-11ea-8be8-fac77d072860.png)

**Desktop :**
 - OS: [Windows 10]
 - Host [Studio One]
 - Version [5.0.1]

**Comment by baconpaul** [comment]
Hi!

This is a duo of #2397 

We’re not sure why s1 freaks out with this internal api but arbitrary zoom will fail yeah. Some values like 150 work

Will close this as a dup
