### ISSUE TITLE
Spurious "Edit Coming Soon" when assigning modulation to modulator Amplitude

### ISSUE THREAD

**Issue by Jacky-Ligon** [surge-synthesizer/surge#2484]
**Surge-NIGHTLY-2020-08-14-32162c4 | Windows 10 Pro, x64, VST3i**

**Observed**
As seen in the below LICEcap GIF, when assigning a modulation-source to a modulator's Amplitude, an "Edit Coming Soon" message appears, yet typeins are still accepted.

**Suggestion**
That message can probably be removed.

![LICEcap](https://user-images.githubusercontent.com/66483816/90334816-501b1380-df9e-11ea-8b70-0940ac8bc1a9.gif)

**Comment by baconpaul** [comment]
Oh the bug here is when @mkruselj made it bidirectional they didn't add it to the list of 'can-support-typein' in Parameter.cpp. Good find! @mkruselj can you patch this up when you get a chance? Thanks!

**Comment by mkruselj** [comment]
I'm on it!
