### ISSUE TITLE
Version file in tarball which will work without git

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2495]
So the tarball strips git
but that means when you use it the stuff to grab version goes blammo
so what we should do is

1. write a 'scripts/make-version-stub' file
2. run it in the tarball phase
3. if git branch comes back empty look for the file and read that in cmake/versiontools

then @falkTX and other tarball consumers will be able to build with the version we want

Thanks as always @falkTX for debugging surge infrastructure in new and untested environments, patiently!

**Comment by falkTX** [comment]
Yes, exactly.

My knowledge of cmake is almost none, so I can't help here much.
But I can do the final testing.

**Comment by baconpaul** [comment]
Yeah cool. I'll let you know when the nightly tarball has it in place (that will be when this issue closes).

It's a fun distraction from some of the other harder 1.7.2 stuff so may get to it sooner rather than later

And as always, thanks for all the careful feedback and help.

**Comment by baconpaul** [comment]
So turns out this was really easy once I typed in what needed to happen. I've modified our CMake and Pipeline so that tarballs now contain a VERSION_GIT_OVERRIDE file which cmake will preferentially read. It is only generated for the tarball

I was able to grab a nightly tarball and do a build with no problem.

Unfortunately for kx, the nightly is not currently a good distribution candidate (we have a lot of in-flight features still in flight) but with 1.7.2 this problem will be resolved.

If you could do me a favor of one day grabbing the nightly tarball and confirming it builds for you, though, we can close this and the 1.7.2 kx implementation will be far easier

Thanks as always

**Comment by falkTX** [comment]
You are welcome.

Ping me when 1.7.2 is close to release, so I can give a final check that everything is fine.

**Comment by baconpaul** [comment]
will do. added to our release checklist. will close this one now since the build from tarball worked fine on my box just now.
