### ISSUE TITLE
Linux CMake Resources and Root prefix which overrides the default /usr

### ISSUE THREAD

**Issue by alex-tee** [surge-synthesizer/surge#2497]
**Describe the bug**
`src/common/SurgeStorage.cpp` assumes that the prefix is /usr. When packaging for distros like Guix and NixOS, the prefix will be different (for example `/gnu/store/...................`). Nothing is allowed inside /usr. Patching this is ugly and it makes more sense to handle this properly in Surge.

**Please let us know your surge version**
This information is all in the menu/about screen

* Surge Version: 1.7.1
* Plugin type: VST3 and LV2
* Bits: 64

**To Reproduce**
See above

**Expected behavior**
Either:
1. use the prefix that CMAKE is given (I am sure there is a way to get the prefix from CMAKE)
2. add a CMAKE option for overriding the path that Surge looks for data

**Screenshots**

**Desktop (please complete the following information):**
 - OS: GuixSD (GNU/Linux)
 - Host N/A
 - Version N/A

**Additional context**
N/A

**Comment by baconpaul** [comment]
Hi!

Surge actually has a waterfall

it checks $XDG_DATA_HOME/surge
then ~/.local/share/surge
then /usr/share/surge

None of those work for your use case?

But sure adding a SURGE_DEFAULT_SHARE_ROOT to cmake is pretty easy then read it there. 

What's the command line you would use and how would you advertise your desired root to surge?

**Comment by alex-tee** [comment]
@baconpaul hi

In the context of packaging, `$XDG_DATA_HOME/surge` and `~/.local/share/surge` should not be touched at all since those are user directories. packages only install to system directories, so only the last one is relevant.

> But sure adding a SURGE_DEFAULT_SHARE_ROOT to cmake is pretty easy then read it there.

This sounds great and is easy to implement.

Another cleaner (IMO) option, is using the prefix that CMAKE is currently using. I believe this is `CMAKE_INSTALL_PREFIX`, which defaults to /usr/local. Most distro packagers set the prefix to /usr, but Guix passes `/gnu/store/...`as a prefix to CMAKE (I assume using `CMAKE_INSTALL_PREFIX`). So you could just do something like `char * datapath = INSTALL_PREFIX "/share/surge"`, after you've made sure this value is added to a configuration header (eg `config.h`).

I also suggest adding an install phase to CMAKE that installs everything under the prefix. having to copy files manually is not very pretty. see this package definition for example:
```scheme
        (replace 'install ; no install target
          (lambda* (#:key inputs outputs #:allow-other-keys)
            (let* ((src (assoc-ref inputs "source"))
                   (out (assoc-ref outputs "out"))
                   (share (string-append out "/share"))
                   (lib (string-append out "/lib"))
                   (lv2 (string-append lib "/lv2"))
                   (vst3 (string-append lib "/vst3")))
              (mkdir-p lv2)
              (mkdir-p vst3)
              (copy-recursively "surge_products/Surge.lv2"
                                (string-append lv2 "/Surge.lv2"))
              (copy-recursively "surge_products/Surge.vst3"
                                (string-append vst3 "/Surge.vst3"))
              (copy-recursively (string-append src "/resources/data")
                                (string-append share "/Surge"))
              #t)))
```

So instead of having to do this, you could just do `make install` and cmake would install the lv2/vst2/vst3/data under the prefix

**Comment by baconpaul** [comment]
yeah we have cmake rules for the local installation on mac, just i haven't written them for linux yet. (They are still in build-linux.sh - we were on premake until the spring which was ... harder ... but so still some work to do on cmake)

On ubuntu 20, CMAKE_INSTALL_PREFIX defaults to /usr/local so that won't work but it is super easy to add a -DSURGE_INSTALL_ROOT=/blah which defaults to /usr - I'll do that and add the install rules to the cmake before 1.7.2 and then you can add it to your packaging. Sound good?

Finally: Your package manager is written in scheme (or guile or some such)? Fun!

And thanks!

**Comment by alex-tee** [comment]
> On ubuntu 20, CMAKE_INSTALL_PREFIX defaults to /usr/local so that won't work

Yes, that's the default on all GNU/Linux systems. Packagers will pass CMAKE_INSTALL_PREFIX=/usr to every cmake project they build. this way a user would install surge under /usr/local when building manually and the package would install under /usr, so there is no interference (and the user doesn't have to pass anything special, default /usr/local will do)

> it is super easy to add a -DSURGE_INSTALL_ROOT=/blah which defaults to /usr - I'll do that and add the install rules to the cmake before 1.7.2 and then you can add it to your packaging. Sound good?

yep, that sounds a bit cleaner than patching the .cpp file, even though I still think the prefix method is better

>  Your package manager is written in scheme (or guile or some such)? Fun!

i know right? writing packages in guile is so much fun

**Comment by baconpaul** [comment]
I threatened to add a scheme panel to the modulation section of surge so you could write little scheme programs to generate LFOs. The reaction was mixed ("yes we want formulae; no we don't want scheme"). Ahh well.

The reason I pause is that none of our current users are expecting to have to set CMAKE_INSTALL_PREFIX to build and get a working surge which is why I think of sort of making it explicit. I kinda don't want to go to every person who has a package working and explain that it will now break unless they do x.... 

of course I could do something hokey like 'if cmake install prefix is not /usr/local then use it' (and this is only on linux so don't have to worry about mac and windows which have separate mechanisms to resolve this problem).

**Comment by baconpaul** [comment]
Oh sorry I'm being dumb

The thing to do is just add CMAKE_INSTALL_PREFIX to the waterfall

So then the waterfall will be 

XDG_HOME/share/surge
~/.local/share
${CMAKE_INTALL_PREFIX}/share
/usr/share

and then it will work

**Comment by baconpaul** [comment]
and then when I write install rules in cmake write those to CMAKE_ISNTALL_PREFIX of course. Will do this before we ship 1.7.2

**Comment by baconpaul** [comment]
Just FYI I'm merging a change today that does what you need and will update the README also.

But basically

```
cmake -Bbuild -DCMAKE_INSTALL_PREFIX=/g/ins 
cmake --build build --config Release --target all-components
sudo cmake --build build --config Release --target install-everything-global
```

should now do what you want (namely install a surge in /g/ins which runs along with the resources)

Will merge when CI is done and that will close this issue

best

**Comment by alex-tee** [comment]
sweet, thanks! will try it later

**Comment by baconpaul** [comment]
Cool. Just reopen this if it doesn’t work. 

The current nightly is not well positioned to be in a distro - lots of incomplete features - but we don’t plan any more changes to the build infra before the next release unless you report bugs here or @falkTX has problems with the tarball
