### ISSUE TITLE
Pitchbend Routing Not Changing FM Depth Modulation When Bending Down

### ISSUE THREAD

**Issue by mclarenmartin** [surge-synthesizer/surge#2500]
The pitch bend section of the modulation/routing only seems to effect the FM Depth parameter for upwards bends. It is fully functional for bends up.

Surge Version: 1.7 
VST3
64 bit

1.  Set FM routing to 2->1.
2. Set OSC 2 to a sine (or anything that works for FM).
3. Route pitchbend to FM depth.
4. See error when pitch bending down, although completely functional when bending up.

Desktop
 - OS: Windows 10
 - Host Reaper
 - Version 6.13

**Additional context**
All other routings for pitch bend seem to work fine for me in either direction so it seems unlikely to be related to my controller.

**Comment by baconpaul** [comment]
Hi! And congratulations on being issue #2500. 

I just gave this a whirl in the AU. It is definitely the case that the UI is wrong (the green bar shows a unipolar not bipolar modulator) but in my attempt i got a bidirectional FM bend. Can you try this patch?

[pb.zip](https://github.com/surge-synthesizer/surge/files/5096222/pb.zip)

**Comment by mkruselj** [comment]
I can confirm @baconpaul's findings. PB does work bipolarly but the mod amount is not shown as such on the slider.

**Comment by mkruselj** [comment]
...and I think I may have found the reason for this behavior!

In SurgeSynthesizer.cpp, line 123, we have:

`scene.modsources[ms_pitchbend] = new ControllerModulationSource();`

If we take a look, `ControllerModulationSource` is initialized as:

![image](https://user-images.githubusercontent.com/2393720/90647637-cf2b7880-e238-11ea-909a-3c6d3b00445f.png)

It's set as if it isn't bipolar. So gotta set it to be bipolar somehow.

**Comment by mkruselj** [comment]
Hmmm, it's not that. Even if I force bipolar to be true there, it doesn't make it show as bipolar when drawing modulation amount line.

**Comment by mkruselj** [comment]
Oh but I actually think I found it, it's at line 1853 in `SurgeSynthesizer::isBipolarModulation`, just ORing `ms_pitchbend` in there should do it.

**Comment by baconpaul** [comment]
Yeah it’s just skipped from that list. Thanks!

**Comment by baconpaul** [comment]
But still need to understand @mclarenmartin problem and why we don’t see it. Do you have a patch @mclarenmartin ?

**Comment by mkruselj** [comment]
I think it was really just a visual issue. I cannot get pitch bend to NOT work bipolarly with FM Depth parameter. 🙂

**Comment by baconpaul** [comment]
Ok I merged your change

@mclarenmartin if you have a patch which shows the break you experienced please reopen the issue. There was definitely a visual bug we fixed but We couldn’t reproduce an audio bug. Best!
