### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by padfootery** [surge-synthesizer/surge#2508]
I am not managing to install in ableton. There is no way to select which folder it installs to and it doesnt install any .dll files like other VST's. Confused, please help! Thank you

**Comment by mkruselj** [comment]
Surge installs in the default VST3 folder (so, it's not .dll file, it's .vst3 file), so enable scanning for VST3 plugins in the system folder and you should be good to go.

![image](https://user-images.githubusercontent.com/2393720/91089281-a7327f80-e653-11ea-9c34-97feb47206e3.png)

**Comment by baconpaul** [comment]
@padfootery and that folder is c:\program files\Common Files\VST3 where you should see a SurgeSynthTeam folder.

I'm going to close this but please reopen it if the plug isn't there or some such.

Thanks

**Comment by padfootery** [comment]
Hmm, okay so it installs to the right folder but in Ableton I dont have a
tab in preferences that says plugins, which is quite strange.

**Comment by baconpaul** [comment]
What version of ableton are you using? I think vst3 support in love is fairly recent addition (like last 18 months or so). But I don’t run live or windows so that’s just a memory!

**Comment by padfootery** [comment]
Hey guys! Sorry I'm openng this up again a week later. So my install is
chilled, but I can't find the options you pointed out. I'm on version
10.0.6 but my menu is preferences thing is missing the whole plugins tab..
my plugin settings I've been using

Thanks :)

**Comment by baconpaul** [comment]
A quick google shows me Ableton vst3 support was introduced in 10.1. So your choices are

1 run an old version of surge
2 upgrade to a daw which supports vst3 or
3 build a vst2 yourself if you are a legitimate holder of the vst2 sdk.
