### ISSUE TITLE
Make it possible to swap macros

### ISSUE THREAD

**Issue by TheNerdyMusicGuy** [surge-synthesizer/surge#2527]
It would be great, if it was possible to swap macros.

I often assign the macro controls in the order I have ideas for them, but often want to change them around once the sound is in a more finished state. Currently, you have to unassign all the assigned modulation, remember it and reassign it to another macro, which is not very handy.

It would be great, if we could simply swap macros.
One solution would be copy and paste, which has the benefit of probably being easiest to implement, but the downside of making it difficult to use once all 8 macros are assigned.
Another possibility would be drag & drop, which would be intuitive and wouldn't have the problem drag & drop has, but is probably a whole lot more difficult to implement (however, implementing drag and drop could also come in handy for reordering FX...).
RMB > Swap macro with > "list of macros" would be another option, but I don't know if it would clutter up the menus too much.

**Comment by baconpaul** [comment]
Will investigate DnD as a first choice; although there's some problems with it on Linux (but that's mostly dragging from outside surge to inside). Thanks!

**Comment by mkruselj** [comment]
DnD reorder of macros and FX would be great. Of course, send FX don't need reordering, but any insert FX definitely do. Especially once we increase the number of FX slots.

**Comment by baconpaul** [comment]
So this is super painful to do as drag and drop. but really easy to add a final macro RMB "Swap With >" which lets you swap two macros. Any objection if we do it that way?

**Comment by mkruselj** [comment]
I really think drag&drop should be the way to go... What is making it super painful? 🙁

**Comment by baconpaul** [comment]
the vstgui drag n drop api is for OS drags into the code
so basically when a control item initiates a drag I have to push a new element back up into the frame to be the drag object
and it gets all super non-local

**Comment by baconpaul** [comment]
ICYMI on discord I wrote this UI gesture

![plumbs through](https://user-images.githubusercontent.com/13387561/94216194-cfa8d600-feac-11ea-94ef-a9250562fdc9.gif)

but then I realized I could also abuse it for these two types of extra things

![checkitmod](https://user-images.githubusercontent.com/13387561/94216213-d9323e00-feac-11ea-9453-60701d8ffd78.gif)
![orangearrow](https://user-images.githubusercontent.com/13387561/94216219-dafc0180-feac-11ea-94f9-26e2c7123366.gif)

So this should all be in a nightly soon.

**Comment by baconpaul** [comment]
Pushing the macro reordering. Leaving the other routing adjustments (drop onto slider) in the codebase but turned off. Will merge once CI is done and close this.
