### ISSUE TITLE
FX selection doesn't work under certain circumstances

### ISSUE THREAD

**Issue by TheNerdyMusicGuy** [surge-synthesizer/surge#2532]
After inserting an Airwindows effect into the first FX slot of a scene, the effect selection of the second slot of that scene doesn't work anymore. This also happens with the two master effects.
There are also instances where the other effect selections stop working, but I haven't quite figured out the logic behind that yet.

![SurgeBug2](https://user-images.githubusercontent.com/70379545/91615322-93ed2000-e983-11ea-9345-3550fb3cd84c.png)

**Comment by baconpaul** [comment]
Did you install the nightly from the installer? Can I see your about screen. Thanks

**Comment by TheNerdyMusicGuy** [comment]
Ohh Sorry, I forgot to include the version info!

![Surge Version](https://user-images.githubusercontent.com/70379545/91616990-3eb30d80-e987-11ea-9e91-12e4724653bf.png)

I used the latest nightly from the installer. However, this also happened in previous nightly versions.

**Comment by baconpaul** [comment]
Thanks
I wonder if the xml configuration is getting screwed up somehow. I’ll look sometime this weekend

**Comment by baconpaul** [comment]
Just as an FYI I can reproduce this on my mac; so not a windows or your install problem. Thanks for the accurate report.

**Comment by baconpaul** [comment]
Did a quick bisect this morning and 125c7b9ce2a0c8c2a1e89aa13ecd967c4c46b13b is the culprit

**Comment by baconpaul** [comment]
Oh hah I see it. Two character fix.
