### ISSUE TITLE
Draw a vertical line in the step seq when Rate is disabled to indicate its phase position

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#2545]
When rate is disabled in Step-Seq mode, at the moment we only have the horizontal line which tells the output value depending on the set phase. Although we can look at the actual phase slider's position to see approximately where it is, it would be visually clearer to draw a vertical line as well representing the static phase position, either the same or a slightly different color than the existing horizontal line (which is actually the step outline line). It would then slide along when moving the Phase Slider. I know @mkruselj suggested this a while back, and I think it's a good idea.

Here's an example:
![image](https://user-images.githubusercontent.com/50145178/91788148-71ecdb00-ebd9-11ea-981b-3605f4a45668.png)

**Comment by mkruselj** [comment]
This should show up in any LFO mode really. But for step seq it should be the same width as a whole step rather than a thin line.

**Comment by baconpaul** [comment]
in other modes you see all the iterations. So presume you would just want the line in the first phase (and realize if you et rate to 500hz or something it would be a bit ugly).

**Comment by baconpaul** [comment]
Oh it only makes sense for stepseq in the current UI since the LFO just shows the output value always in the other modes (so it's not like it shows the original line) and that's really painful to fix since we would have to run the LFO twice to draw. So StepSeq only is the thing to do here I think

**Comment by baconpaul** [comment]
![ssdeact](https://user-images.githubusercontent.com/13387561/91860809-1dc61300-ec3a-11ea-9dbb-bbebaddfea43.gif)

There we go. That's super easy.

**Comment by mkruselj** [comment]
That's super nice. Will tweak the colors. 🙂

**Comment by baconpaul** [comment]
The default color is just a 30% brightening but it is skinned of course - easy to find and change

**Comment by VincyZed** [comment]
Great implementation, really nice!

**Comment by K0rrid0r** [comment]
super cool!
