### ISSUE TITLE
Audio Unit Param Invalidation follows VST3 code

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2555]
Would be nice to have for i.e. FX and oscillator parameter names, or when we change the LFO phase/shuffle to only be called Phase or Shuffle depending on which LFO type we use.

https://sdk.steinberg.net/viewtopic.php?t=641

**Comment by baconpaul** [comment]
So here's a way to do this

add a static std::atomic<bool> Parameter::name_changed
in parameter::set_name() do name_changed = true.
in the process loop of the vst3 (say every 100 calls to process or so) check if name_changed is true and if so call that rebuild 

The call you want in vst3 is

```
IComponentHandler::restartComponent( kParamTitlesChanged )
```

**Comment by baconpaul** [comment]
Holy heck! This works!

**Comment by baconpaul** [comment]
Here's a bit of JUCE code which should let us do this for mac, but Its too late here for me to work on that.

**Comment by baconpaul** [comment]
see it is too late! Here's the code

```
    void sendAllParametersChangedEvents()
    {
       #if JUCE_MAC
        jassert (audioUnit != nullptr);

        AudioUnitParameter param;
        param.mAudioUnit = audioUnit;
        param.mParameterID = kAUParameterListener_AnyParameter;

        AUParameterListenerNotify (nullptr, nullptr, &param);
       #endif
    }
```

**Comment by baconpaul** [comment]
In theory the VST2 could work the same if you call the internal function `updateDisplay()` from the API

**Comment by baconpaul** [comment]
Yeah that works fine.

**Comment by baconpaul** [comment]
I'm going to close this issue. We're never going to code it in our hand-coded AU and the Juce AU does it for us if it does it for VST3.
