### ISSUE TITLE
Scene pitch doesn't change the pitch of oscillators that have keytracking disabled

### ISSUE THREAD

**Issue by TheNerdyMusicGuy** [surge-synthesizer/surge#2556]
The main pitch controls for the individual scenes don't change the pitch of oscillators that have keytracking disabled.

I would expect the control to still work, despite keytracking being disabled.
If this is intended behavior, please ignore the report.

I'm using Surge-NIGHTLY-2020-09-01-a4152d7 in Ableton Live 10.

**Comment by VincyZed** [comment]
Can confirm, and I agree that Scene Pitch should change when OSC keytracking is disabled.

**Comment by baconpaul** [comment]
Super duper tricky to do that. By the time the oscillator triggers the pitch modulators are all combined including scene pitch

**Comment by baconpaul** [comment]
The logic is all in noteShiftFromPitchParam in SurgeVoice, and you can see that is called either with the scene pitch or a constant based on the keytrack. Thats where you would have to do it. Carefully.

**Comment by mkruselj** [comment]
I think I figured it out. PR coming soon!
