### ISSUE TITLE
Velocity Slider in Amp EG is not modulatable

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#2566]
Some of us were wondering why Velocity amount in AmpEG is not modulatable...

Paul: "There’s some self modulation constraint code that may be it" ?

**Comment by mkruselj** [comment]
My thinking is since this parameter is only really applied at note on, modulating it kinda makes no sense (you can get the same effect by modulating amp gain instead).

**Comment by baconpaul** [comment]
Yeah it’s a wierd mod target. I guess an SLFO could mod it but I’m happy to close this

**Comment by VincyZed** [comment]
Yeah sounds good, I was simply curious, but @mkruselj pointed out that it wouldn't be really useful to have it modulatable anyways, and I agree. Thanks!
