### ISSUE TITLE
Unison count has no effect on Poly count

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#257]
One for @kurasu and maybe @baconpaul 

1. Increase Unison count to max (7)
2. Press a note

Expected result:
???

Current result:
Poly updates to `1/8` until sound stops.

Is Unison count separate from Poly count?

**Comment by baconpaul** [comment]
The answer to this is “yes”. Unison is a property of a single oscillator so you get one voice (which is what poly counts) with one Oscillator which itself makes sound as if it had multiple unison waveforms inside it. So this behavior is correct, expected, and matches the code. I’ll close the issue. Thanks!
