### ISSUE TITLE
PATH_SEPARATOR more cleanly everywhere, really

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2572]
bacon and evil know the score on this one

**Comment by baconpaul** [comment]
The right thing to do is have an appendPath( root, dir, ... ) function which we can call that does the right thing, including checking for trailing

**Comment by baconpaul** [comment]
Alright we now have Surge::Storage::appendDirectory( root, path ) and (root, p1, p2 ) and (root p1 p2 p3 ) which does the right thing. @mkruselj if you feel like cleaning up old code lets leave this open otherwise lets close it.

**Comment by mkruselj** [comment]
Good idea, let's clean it up!
