### ISSUE TITLE
high current playing step from the step sequencer

### ISSUE THREAD

**Issue by hems** [surge-synthesizer/surge#2577]
**Is your feature request related to a problem? Please describe.**
high current playing step from the step sequencer

**Describe the solution you'd like**
The same way we have the little "Rectangles" on top of the steps we could have one below it which would light when the step is being played / active

**Additional context**
![image](https://user-images.githubusercontent.com/27327/92316071-ea430a00-efe6-11ea-9dd6-883606b8dd90.png)

**Comment by baconpaul** [comment]
This is a dup of #2145 and there you can see me ask “for which voice” so lets close this one
