### ISSUE TITLE
Detect DAW; Disable VST3 outs in FL unless you ask for them

### ISSUE THREAD

**Issue by KosmiKFead** [surge-synthesizer/surge#2578]
Discription

When I set output gain on effects to lowest value in order to mute output, dry signal from the filters still leak through! 
Seems like the filter signal is going past the effect block! Or inside effect block: The Inserts output signal is set to zero and still filter signal leaks past the Master 2 fx! 
You can hear filters output copy mix with effect block in parallel!
I believe this is wrong! Or a bug! We need effect block final and absolute like in your diagram!

- Surge Version: 1.7.1.5270cbf as well as the Nightly Build of 09/03/2020
- Plugin type: VST3
- Bits (64)

**To Reproduce
Steps to reproduce the behavior:**

1. Set up or select a simple saw wave preset with no filters, fm, inserts or effects
2. On master2 in the effect section, add effect conditioner or an airwindows effect like totape6 (immediately the dry signal is heard mixing with the effect signal)
3. Slide output gain of effect down to 0% (the dry signal mixing with the effect becomes very obvious)
4. **With the output gain of the effect at 0% you can hear the clean signal leak past the effect in "paralell"**

**Expected behavior**
I expected the output to go down with the slider and no signal to remain! I expected conditioner and airwindows effects to be applied in-line so that eq, distortion or limiter can be final and 100% "wet"! I expected airwindows Adclip to clip the whole final output with no clean signal getting past.

**Screenshots**
![surge bug report 2](https://user-images.githubusercontent.com/70804661/92320075-0367ad00-f01f-11ea-8524-b7101835753d.png)
![surge bug report](https://user-images.githubusercontent.com/70804661/92320918-9a376800-f025-11ea-98f6-73388c48e660.jpg)

**Desktop (please complete the following information):**
 - OS: Win 7 64
 - Host: FL Studio
 - Version 20.7.1

**Additional context**
The master output meter in Surge does NOT reflect the rogue dry signal in the final output of the plugin!
The bug seems to be with all effects.

**Comment by K0rrid0r** [comment]
It has to do with the separate outputs that was added. FL cant recognize separate outputs by default so it puts all three of them on the same output if you don't chose different outputs for them manually.

Here is you solution.
![solution](https://user-images.githubusercontent.com/56724286/92324113-c8757180-f03e-11ea-9d1f-bb9a0db433dc.gif)

**Comment by baconpaul** [comment]
@K0rrid0r I wonder if we should (by default) turn off the scene A B outputs in FL and require user action to turn them on. Seems this DAW bug has caught more than one FL user with the Surge VST3. Thoughts?

**Comment by K0rrid0r** [comment]
could be a good idea!

**Comment by mkruselj** [comment]
Or we should contact Image-Line and tell them to be smarter about multiout situation 🙂

**Comment by baconpaul** [comment]
Happy for someone to do that. I thought it was hard to raise a ticket if you don’t own the daw. Also making it an option if your daw if fl is within our control. So I think that’s the right thing to do.

**Comment by KosmiKFead** [comment]
THANK YOU SO MUCH! This synth is a gamechanger and im so amped that its not BROKEN! I'll be contributing a ton of presets that take advantage of the differences surge offers!

**Comment by baconpaul** [comment]
Great! @KosmiKFead I'm going to reopen this issue so I can remember to disable-this-by-default in FL for 1.7.2. So happy it works!

**Comment by baconpaul** [comment]
OK I'm going to push a change now which

1. Adds an "Activate Extra Scene Outputs" menu to users
2. For every host except FL, that defaults to true if you haven't set it
3. For FL it defaults to false if you haven't set it
4. If you set it, it defaults to what you set it to forever more

With that in place this issue will close.
