### ISSUE TITLE
Changes to names and string in Vst2PluginInstance caused slider problems in VST2

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2584]
links to Use CMake for Version more extensively (#1786)
https://github.com/surge-synthesizer/surge/commit/40d1b891bd688c99e60db0a22ffd8b00eed3da0a

When using "Auto close device" that stops the audio driver from being taken over by FL when the daw is not in focus and then going back into FL, activating the audio driver again caused the slider bug that is seen here. (that is commit 40d1b891)
![old slider bug](https://user-images.githubusercontent.com/56724286/92441051-c8e04a80-f1ad-11ea-9428-5a5b931e77e1.gif)

and this is commit 0defcea6 (that came before 40d1b891)
![old slider bug 2](https://user-images.githubusercontent.com/56724286/92441184-0e047c80-f1ae-11ea-902e-6e1dcc1c6220.gif)

The problem was temporarily fixed by renaming getEffectName, getProductString and getVendorString back to this:
![hh](https://user-images.githubusercontent.com/56724286/92440251-85d1a780-f1ac-11ea-82d1-44c93337f8ae.gif)

@baconpaul has a better fix then this and knows what to do.

**Comment by baconpaul** [comment]
Hey @K0rrid0r can you just check quickly if you change those strings to "Surge", "Surge", and "Surge Synth Team" that it works for you?

**Comment by K0rrid0r** [comment]
@baconpaul i did try the "Surge", "Surge", and "Surge Synth Team" combo and that made the bug not go away.

**Comment by baconpaul** [comment]
Can you try "Surge" "Surge" and "Blah" and check? And also "Surge Synth T"
Then check "BlahBlah"
Then "BlahBlahBlah"
you get the idea.
I think your VST2 SDK may be old (but who knows what you have). in your effect.h what is kVstMaxVendorStrLen set to?

**Comment by K0rrid0r** [comment]
well that's wierd. (now)

but this still works.

bool Vst2PluginInstance::getEffectName(char* name)
{
   strcpy(name, "Vemberttttttttttttttt Audiottttttttttttt");
   return true;
}

bool Vst2PluginInstance::getProductString(char* name)
{
   strcpy(name, "Vemberttttttttttttttt Audiottttttttttttt");
   return true;
}

bool Vst2PluginInstance::getVendorString(char* text)
{
   strcpy(text, "Vemberttttttttttttttt Audiottttttttttttt");
   return true;
}

**Comment by K0rrid0r** [comment]
but "Surge", "Surge", and "Surge Synth Team" does not haha wooot...

**Comment by baconpaul** [comment]
Does "Surge", "Surge", "Open Source Surge Synth Team" work? I have a theory....

**Comment by K0rrid0r** [comment]
that worked!

**Comment by baconpaul** [comment]
OK!

So my theory is "somewhere there's a bug if your vendor starts with your synth name" or some such. Can you send a PR for Surge/Surge/OpenSource Surge Synth Team to close this?
