### ISSUE TITLE
Vintage Ladders Issue

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2586]
Placeholders for Vintage Ladder.

- [ ] Models
   - [x] Implement Kraj
   - [x] Implement Improved
- [ ] Model Changes
   - [x] Huov resonance clamp at 99.4
- [ ] UX
    - [x] CCursorHidingControl
- [ ] SSE
    - [ ] Do any of this
- [ ] Automation
    - [ ] Automation sends message (cool; but see that VST3 latch issue #2516)
    - [ ] Automation rebuilds interrupting drag. Why?

**Comment by mkruselj** [comment]
- [ ] Clamp filter cutoff so that it doesn't go into noise territory. Make sure it's also clamped for modulation!

**Comment by baconpaul** [comment]
EvilDragonToday at 3:05 PM
try this: cutoff at 50%, resonance close to max, full LFO mod amount
then slow sweep up to max rate
oh the menu's hitzone goes outside of menu graphic line

my final quick impressions are: Huov and RK are keepers, hopefully something can be done with Huov to not have those artifacts with fast modulation. Krajeski is a keeper if the issues above 14k are dealt with somehow, Improved needs to go unless it was a porting mistake somewhere then it needs reeval
TheNerdyMusicGuyToday at 3:13 PM
Here are mine: Huov, RK and Krak should stay. RK needs tweaking of the resonance range and it still breaks at high frequencies. Krak also needs some fixing.
EvilDragonToday at 3:13 PM
I'd like to evaluate Improved properly because what is in there now is not "proper"
viceverserToday at 3:13 PM
Keep Improved and call it "unapproved"
EvilDragonToday at 3:13 PM
ololol
TheNerdyMusicGuyToday at 3:14 PM
Ohh yeah, I'm just judging what we have now. If improved can be improved, it might be a keeper as well.
Haha

**Comment by Jacky-Ligon** [comment]
@baconpaul 

Just testing the new Vintage Filters with Surge-NIGHTLY-2020-09-09-58e60f9, Win-10 x64, VST3i, and they have a much more balanced resonance behavior overall...

One small detail though, is that while 1 and 3 have relatively the same amplitude, 2 seems a bit louder.

See attached patch. Hold a chord, and toggle between the three, and one can here the difference in amplitude.

[Saw Osc with Vintage Filters.zip](https://github.com/surge-synthesizer/surge/files/5196697/Saw.Osc.with.Vintage.Filters.zip)

**Comment by Jacky-Ligon** [comment]
Just checked a number of the other older filters for relative volume balance, and it would appear that if possible the new Vintage Filters 1 and 3 could be a bit louder in amplitude...

It's not really that 2 is too loud, but that 1 and 3 seem significantly lower in relative volume, even with different resonance levels and cutoff frequencies.

**Comment by mkruselj** [comment]
Yes they are louder becausee they are compensated. On a ladder filter as you crank resonance up, the bass drops off, which significantly reduces apparent loudness. By subtracting some of the input signal inside the filter's feedback loop (which creates the resonance), you get this bass back, so it's compensated. The old ladder in Surge is actually compensated like this, so technically it's not a "true" ladder. However we provide these options for those who want them. Compensated versions are louder (or, "as loud as the original unfiltered signal, as closely as possible") by design, not a bug.

**Comment by baconpaul** [comment]
Yeah there’s some scaling math in the oversample also. I was thinking about adding an extra root two or so in the non compensated ones to be honest since I also noticed the difference in loudness which you can see in the spectra also even at lower resonance 

Definitely tweakable

**Comment by mkruselj** [comment]
Guess it should be so that bypassed filter and vintage ladder at max cutoff no resonance have the same volume.

**Comment by baconpaul** [comment]
I was gonna run noise across the filter with resonance 0 and couple of cutoffs and look at attenuation in the pass zone sure same thing - will do soon enough

**Comment by mkruselj** [comment]
Obviously different filters will have different passband behavior as you change cutoffs, so this shouldn't be changed I think - just the situation at max cutoff min resonance vs bypassed filter?

**Comment by baconpaul** [comment]
OK we ended up with this in place just fine! I think we are in good shape here now so closing this issue.
