### ISSUE TITLE
Phaser: waveform and phase

### ISSUE THREAD

**Issue by hems** [surge-synthesizer/surge#2591]
**Is your feature request related to a problem? Please describe.**
I would like to select the shape of the modulation on the Phaser and also modulate it's offset.

Currently, I suspect it seems it's always a sine wave?

If you take Fazortan as an example you can change the shapes and the offset:

![image](https://user-images.githubusercontent.com/27327/92503270-e8509500-f1f8-11ea-9bb9-d22ed9934c1b.png)

If you add the option to "deactive" the modulation and modulate it via "phase" like you can do with the STEP SEQUENCER it would become even more powerful and you would then be able to use the MSEG Editor / Powerful LFOs / Step sequence for Surge to modulate the PHASE of the PHASING effect ( : 

I love that recursiviness and i'm loving this nightly build guys, thank you very much! 🍻

**Comment by baconpaul** [comment]
Ha @mkruselj was talking just the other day about deactivating rate and then re-using the deactivated rate as a scrubber in the phaser, flanger, and chorus. In the flanger, we added different wave shapes too.

Right now the LFO modulator is actually a pair of triangles with a phase offset. But we do have enough parameters to add extra wave shapes sure!

**Comment by hems** [comment]
awesome!

Fazortan actually have 2 LFOs and then add to each other, so when LFO2 is high up then LFO1 doesn't have any effect because it's kind of "out of bounds" which adds even more movement to the phaser, it's pretty incredible.

Also i feel that having waves with sharp edges, like SAW can give a very nice attack-y feeling on the phaser

**Comment by mkruselj** [comment]
@baconpaul Maybe we could factor in (sic!) the refactored LFO stuff Jatin did for Neuron into this one as well?

**Comment by hems** [comment]
Since we're here, there is one very nice thing on Fazortain as well, which is you can set a "Stereo phase" so the phaser becomes stereo..

i.e. 180 degrees phase on the left and on the right side for opposite phases : D

![image](https://user-images.githubusercontent.com/27327/106477098-b12c9a00-649f-11eb-9bd8-4baaa9920e86.png)

**Comment by mkruselj** [comment]
That's what we already have (Stereo slider in Modulation section).
