### ISSUE TITLE
Add Carlos-Morrison CET Microtunings to the Factory Tuning Library

### ISSUE THREAD

**Issue by Jacky-Ligon** [surge-synthesizer/surge#2598]
@baconpaul 

You'll recall when we were working together on the Tuning Workbench Synth, that you updated the tuning-library code to accommodate so-called **CET** microtunings - i.e. - **Cents Equal Temperament** intonation systems which are defined by a single interval given in cents, such as those by **Wendy Carlos** and **Gary Morrison**:

**

- 35.1 CET - Wendy Carlos - Gamma
- 63.8 CET - Wendy Carlos - Beta
- 78.0 CET - Wendy Carlos - Alpha
- 88.0 CET - Gary Morrison

**

While we already have the 'extended' versions of the Wendy Carlos microtunings in the Factory Tuning Library showing the intervals of their CET up to the closest pseudo-octaves, I would like to suggest that we replace those with ones in the attached ZIP archive, and include **88 CET** as a new SCL file, which more accurately specifies these tunings in terms indented by the theorists who discovered them.

[Carlos-Morrison CET (Single-Step Versions).zip](https://github.com/surge-synthesizer/surge/files/5194767/Carlos-Morrison.CET.Single-Step.Versions.zip)

**Comment by Jacky-Ligon** [comment]
Probably goes without saying, that it would be good to make this same change to TWS if we haven't already when we were working on this back in March.

**Comment by Jacky-Ligon** [comment]
Wendy Carlos intonation systems were derived from:

**Tuning - At the Crossroads - Computer Music Journal, Vol. 11, No. 1, Microtonality (Spring, 1987)**

**Comment by baconpaul** [comment]
Yes great thanks will merge these in soon

**Comment by Jacky-Ligon** [comment]
Thanks in advance.

**Comment by baconpaul** [comment]
@Jacky-Ligon just to make sure I understand

Replace the 3 Wendy Carlos scales with this folder?
Or add this folder's contents to the SCL library?

Just want to make sure I end up with the layout you suggest :)

**Comment by Jacky-Ligon** [comment]
Inside the original factory SCL directory are these Wendy Carlos tunings:

![image](https://user-images.githubusercontent.com/66483816/92626698-43859480-f298-11ea-8eb9-ac3fdf9b8a42.png)

Completely delete these, and replace them with the ones in the above ZIP, and add the 88-CET one as new...

Thanks!

**Comment by baconpaul** [comment]
PR #2600 will do this. Thanks!
