### ISSUE TITLE
VST3-Win: MIDI control issues

### ISSUE THREAD

**Issue by funkaloss** [surge-synthesizer/surge#26]
I discovered this gem when it became open source, and now I'm exploring it.

I can't seem to control Surge with my Nektar controller. The pitch of the keyboard works fine but nothing else: not velocity, pitch bend, mod wheel or any other fader or knob.

**Comment by cyanit** [comment]
_Disclaimer: I'm not a surge/audio plugin developer, just suggesting common troubleshooting steps, which is usually to test what works and what doesn't to narrow down the source of the issue._ 

Okay, I just tested it and can confirm that this issue is present on my setup when Surge v1.6.0b3 is loaded as VST3. However, the VST2 version works fine. 

**- Test 1.1 - (Issue occuring)**
Windows 10
Bitwig Studio v2.4
Surge v1.6.0b3, VST3
(Alesis Hardware Controller sending CC)

**- Test 2 - (Issue occuring)**
Windows 10
Bitwig Studio v2.4
Surge v1.6.0b3, VST3
(Bitwig Studio generating and sending CC)

**- Test 3 - (Issue NOT occuring)**
Windows 10
Bitwig Studio v2.4
Surge v1.6.0b3, VST2
(Alesis Hardware Controller sending CC)

**Workaround**
If you still want to use the VST3 version with the expressions / mod- & pitchbendwheel, modulate the parameters via your daws VST-Parameter control page.
![surgeworkaround](https://user-images.githubusercontent.com/26248671/46538649-d0599380-c8b4-11e8-98c0-644c1de36da5.PNG)

**Comment by funkaloss** [comment]
Nice form. I'll try to bug report/troubleshoot that organized next time.

Den fre 5 okt. 2018 15:43Leo <notifications@github.com> skrev:

**Comment by vetramiga** [comment]
thank god, i went all over the place looking for drivers and that.  being this is the only VST i had installed on a new machine... so can also confirm the whole pitch bend / mod wheel data isn't getting to this.  i finally installed another free one and it pitchbent just fine... 

that being said, this is basically my favorite synth plugin, and i was well excited to see it come back for x64 finally!  i can't use it in osx/logic anymore as it refuses 32bit plugs =(

**Comment by cyanit** [comment]
> thank god, i went all over the place looking for drivers and that. being this is the only VST i had installed on a new machine... so can also confirm the whole pitch bend / mod wheel data isn't getting to this. i finally installed another free one and it pitchbent just fine...
> 
> that being said, this is basically my favorite synth plugin, and i was well excited to see it come back for x64 finally! i can't use it in osx/logic anymore as it refuses 32bit plugs =(
> 
> win 10
> 1.6.0b3 VST3
> reaper 5.95
> umx49 controller (usb in)

As stated in my post above, **the VST 2 version works fine!** Its just the VST3 version that has these hickups.

**Comment by esaruoho** [comment]
please, could you change the title of this from `MIDI control problems` to like `VST3-Win: MIDI control issues`
:)
easier to troubleshoot.

**Comment by funkaloss** [comment]
Donera!

**Comment by esaruoho** [comment]
btw, is this issue still happening for you guys? @funkaloss @cyanit -- talking about 8th January 2019 build..
@vetramiga

**Comment by bit-101010** [comment]
I'm experiencing it on the Feb. 28th nightly build. VST2 works as expected, VST3 doesn't recieve pitch (and I'm assuming other MIDI data as well.

**Comment by baconpaul** [comment]
Thanks @bit-101010

And: Makes sense - we haven’t fixed it yet! But we plan on doing so. 

Don’t suppose you have some asset like a bitwig file which shows the difference do you? That would help

**Comment by bit-101010** [comment]
I don't have Bitwig, the best I could do is REAPER. I'll conjure up something if that works for you. If not, I can ask some friendly local bitwig users.

**Comment by baconpaul** [comment]
Sure I can try in reaper. Or just a bit more clarity on "how you show it broken" would be helpful! Thank you for anything you can share.

**Comment by bit-101010** [comment]
I will get on it!

**Comment by bit-101010** [comment]
This is the Reaper File as well as the rendered audio. The first measure uses the modwheel to change the wave shape (of the sawtooth), the next measure uses a +/- 24 semitone pitchbend. These are both audible on the VST2 plugin. Afterwards, the same modulations are applied to the VST3 plugin, and no noticeable changes arise.
[Surge_VST3_Win_MIDITest.zip](https://github.com/surge-synthesizer/surge/files/2922167/Surge_VST3_Win_MIDITest.zip)

**Comment by baconpaul** [comment]
Thank you very much!

**Comment by baconpaul** [comment]
Also - just so you aren't disappointed - our list is a bit long. We will get to this before 1.6.0 but it may not be a few weeks. The zip file will stay here though ready for us to debug and is super useful!

**Comment by baconpaul** [comment]
Yeah OK so I see why this is happening. none of the code exists! Like other than note on, note off, and poly pressure, the whole shebang is ignored in the vst3.

I just fixed up velocity but the 'tuning' in the same spot is a float-vs-char, the mod wheel and all controls are ignored, etc...

basically it looks like the vst3 host is half written in this regard. So it's a good clean thing to fix one day.

**Comment by baconpaul** [comment]
Hi everyone 

I just pushed a change to the VST3 host which supports controllers, pitch bend, modulation, and also allows DAW automation to have the correct labels and behavior and interact cleanly with the GUI.

The nightly should be rebuilt within an hour. If you want to try the nightly anytime after about 9:30am NYC time today and provide feedback if there are other VST3 bugs that would be great.

I tested extensively in bitwig and didn’t find a differences between the VST3 and VST2; I don’t have other hosts as readily available for VST3 though so testing welcome.

Either feel free to reopen this ticket if you find a bug or open a new one or let us know on slack.

Thanks!
