### ISSUE TITLE
Integrate the OB-Xd filters

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2613]
https://github.com/reales/OB-Xd/issues/35#event-3752799721

per conversation there we can go ahead and add the OB-Xd filters

I have isolated the code and made them run standalone in this repo:

https://github.com/baconpaul/saobf

So from there there's quite a lot of code shuffling to do to get a non-SSE version; and then quite a lot of parallelizing to get an SSE version. This is a rough outline of how I think we should do it

- We are actually adding TWO new filter types. "OB-Xd 2 Pole" and "OB-Xd Four Pole"
- Each has sub-types driven by different values of `f.setMultiMode` and call respectively `f.Apply` and `f.ApplyFourPole`
- the little src/main.cpp in the bacnpaul repo above shows how it all kinda does it

so here's what I would do

- Surge Storage.h add the two filter types in the enum, the list, so on
- I think the filter types for 2 pole are "LP, HP, BP" and 4 pole are "pole4, pole3, pole2, pole1" corresponding (I think) to values of multimode which are 0,1,2 and 0,1,2,3 but you wanna pre-test that with the little main. So add those to the strings
- make src/common/dsp/filters/OBXdFilters.h and .cpp following the VintageFilters model and add the appropriate calls to QuadFilterUnit.cpp and FilterCoefficientMaker.cpp which sets up the ->C coefficients as opposed to object state
- Gut the inside of Filter.h and the necessary parts of the AudioUtils.h into OB-Xd.cpp and call it with unrolled SSE
- Declare success at this point and we can merge
- Note that in the OB-Xd synth itself cutoff is clipped at 19k. I notice that the filters spit out NaNs if I drive it above there so we probably want to do the same.

If that works then also

- SSE-ify.

**Comment by mkruselj** [comment]
2-pole subtypes should be: LP, BP, HP, N (which is LP+HP summed together).

4-pole subtypes go like in legacy ladder - subtype 1 is 1-pole ... subtype 4 is 4-pole (with 4-pole being the default).

**Comment by baconpaul** [comment]
Does the legacy ladder default to 4?

**Comment by mkruselj** [comment]
Yes!

**Comment by mkruselj** [comment]
- [ ] Current implementation of OB-Xd filters is way louder than other filter types. Probably needs a gain reduction of 6 dB or maybe even more.
- [ ] Increase max number of subtypes, we will need 8 for 2-pole (to have resonance boosted versions of all 4 filter types, and later on also the morph variants

**Comment by baconpaul** [comment]
- [ ] The C can use the dC trick to be more stable under modulation in the process
- [ ] bring that mmch code into play
- [ ] lets identify the subtypes in this issue.

**Comment by mkruselj** [comment]
Subtypes:

OB-Xd 12 dB/oct:
1 - Lowpass
2 - Bandpass
3 - Highpass
4 - Notch
5 - Lowpass Pushed (`selfOscPush == 1.f`)
6 - Bandpass Pushed
7 - Highpass Pushed
8 - Notch Pushed
(Later when we have more filter params)
9 - Morph
10 - Morph Pushed

OB-Xd 24 dB/oct:
1 - 1-pole
2 - 2-pole
3 - 3-pole
4 - 4-pole
