### ISSUE TITLE
Concatenate control target-name, with parameter-name, in Macro control assignments

### ISSUE THREAD

**Issue by Jacky-Ligon** [surge-synthesizer/surge#2615]
Discussion from Discord:

Sometimes when assigning Macros, it would be useful if it were possible to concatenate the mapped target name with the parameter name.

For example, the current behavior is assigning a Macro to ENV1 Amplitude, only shows the Macro as ambiguously assigned to: **Amplitude**.

More concise would be after it's assigned, that the Macro label in this case displays: **ENV1 Amplitude**.

Obviously, it's somewhat trivial to change the name of the Macro after it's assigned, and give it better name for the context, but concatenating the target-name, with the parameter, and displaying that on the Macro, would save time and be a nice UX enhancement.

A potentially important afterthought and consideration, is with regard to having multiple parameters assigned to a single Macro, in which case, the user would probably have to intervene and rename the Macro for a given multi-assignment scenario.

baconpaul
10 character change probably. 

Change this line:

https://github.com/surge-synthesizer/surge/blob/3b8dea20c979b894e45896ff7912ca4f63d33a80/src/common/gui/SurgeGUIEditor.cpp#L2797 

...from get name to get display name is my bet

Since they can be renamed using a more fulsome default is fine with me

**Comment by mkruselj** [comment]
Nope, that line doesn't change the macro name when assigning it.

**Comment by Jacky-Ligon** [comment]
Yes, for all the reasons you stated, probably prudent to leave it as is, and just create template presets with Macro labels as needed.

Thanks for the try though.

**Comment by Jacky-Ligon** [comment]
Closing this now.
