### ISSUE TITLE
Wavetable menu doesn't have the link to manual

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2617]
And it totally should have it!

**Comment by baconpaul** [comment]
The first entry in the WT menu is currently the first set of wavetables.

So adding a help means having a place to hang it. 

That's fine! But before I push wdyt of this for placement and label.

<img width="496" alt="Screen Shot 2020-09-20 at 1 32 15 PM" src="https://user-images.githubusercontent.com/13387561/93717730-b8cd5100-fb45-11ea-9c55-00ed95553040.png">

**Comment by mkruselj** [comment]
I was thinking to put it at the bottom, like in Patch Browser. Since this is also a sort of a "patch" browser, it'd be consistent. Plus wouldn't mess with muscle memory of people.
