### ISSUE TITLE
On/Off toggle for LFO's DAHDSR envelope

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2621]
Currently the envelope is always applied to the LFO. It would be quite useful to be able to bypass just the envelope part of the LFO in a number of cases.

Plus, in case of MSEG, the MSEG editor (as mentioned in #2563) would have a "Show DAHDSR" button... in which case that button could in fact end up being the power button for the DAHDSR envelope,

This power button should be able to survive LFO type changes, unless that change is to the Envelope LFO type - then it should be forced on. However we should still be able to turn it off in Envelope LFO type - this would give us another means of having a constant value, where Sustain level could basically serve to set it.

**Comment by baconpaul** [comment]
@mkruselj why wouldn't we just do this with deactivate on the DAHDSR cluster now that we have coupled deactivation?

**Comment by mkruselj** [comment]
We could, actually, as long as we can later move it to an actual button.

**Comment by baconpaul** [comment]
This one is also super easy if we have a place I. The xt gui for a power button @mkruselj - I have envelope skip coded up I. The mod source already so it’s really just a button that does deactivations. 

If you see a spot where you would put it we can put this back into xt milestone

**Comment by baconpaul** [comment]
Oh and coupled deactivation also written since this request came in. One button or any menu could deactivate all the envelope sliders and suppress the envelope - I think we should put it in xt1 if we have a graphical spot for a little power button

**Comment by mkruselj** [comment]
Great news! Let's put it in the menu for XT1 and close this one, then 🙂
