### ISSUE TITLE
post-automation-247 bug: a couple of buttons spew forth extra data

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#263]
after @baconpaul 's `automation-247` PR got merged in, here are a couple that spew forth excess automation parameters:

`FX1 Return` throws `C1:-`
`FX2 Return` throws `C2:-`
`Master Volume` throws `C3:-`

`Split` throws `C5:-`
`Split Key` throws `C6:-`
`Poly Limit` throws `C8:-`

![splitter](https://user-images.githubusercontent.com/4966687/51049624-14a4b000-15d7-11e9-8681-0e74aa7de7bf.gif)

and here's "and remind Paul to suppress events less than 0"

**Comment by esaruoho** [comment]
will re-check these in a while.

**Comment by esaruoho** [comment]
yep, they're still here:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/4966687/53908281-ab31a280-4057-11e9-9ac8-2f5977fd6e50.png">

**Comment by esaruoho** [comment]
```
$ gg "Master Volume"
src/common/SurgePatch.cpp:          p_id++, 0, "volume", "Master Volume", ct_decibel_attenuation, hmargin + gui_sec_width * 5,
$ gg "FX1 Return"
src/common/SurgePatch.cpp:      param_ptr.push_back(fx[4].return_level.assign(p_id++, 0, "volume_FX1", "FX1 Return",
$ gg "FX2 Return"
src/common/SurgePatch.cpp:      param_ptr.push_back(fx[5].return_level.assign(p_id++, 0, "volume_FX2", "FX2 Return",
$ gg "Split Key"
src/common/SurgePatch.cpp:   param_ptr.push_back(splitkey.assign(p_id++, 0, "splitkey", "Split Key", ct_midikey, 8 + 91,
$ gg "Poly Limit"
src/common/SurgePatch.cpp:   param_ptr.push_back(polylimit.assign(p_id++, 0, "polylimit", "Poly Limit", ct_polylimit, 8 + 91,
```

okay.. so, how would i know for sure that it's `SurgePatch.cpp` that is throwing these extras?

**Comment by esaruoho** [comment]
Looks like this area is the culprit:

https://github.com/surge-synthesizer/surge/blob/3f152b02eaabf6ef30d698e1e4ddc8c3e311c0c6/src/common/SurgePatch.cpp#L53-L99

**Comment by esaruoho** [comment]
as a hint, @baconpaul fixed the previous "double-automation-spewings" by making these changes:
https://github.com/surge-synthesizer/surge/pull/262/files

**Comment by baconpaul** [comment]
yeah but this is a different problem of ids overlapping adjacent to that. I'm going to remove the good first issue label here; this one is tricky.

**Comment by lunafreya** [comment]
@esaruoho, @baconpaul, did you resolved the extra data problem for this issue? I think this might have been overlooked before the first stable 1.6 version was released.

**Comment by baconpaul** [comment]
Along the way this got resolved; probably by all the work I did in the VST3 and AU to make these controls appear. But confirming that the VST2 in Reaper no longer throws the extra controls.
