### ISSUE TITLE
Highest/latest/lowest note pitch bend

### ISSUE THREAD

**Issue by TheNerdyMusicGuy** [surge-synthesizer/surge#2648]
Currently pitch bend is applied to all voices, but maybe it would be cool if there was an option to make it effect the highest, latest or lowest note only.

There is a little bit of space around the pitch bend area in Surge. Maybe a button or dropdown could go there.

This is already possible already MPE in a sense, but I think it would be nice to have nonetheless.

@mkruselj raised a very good question: Should this apply to the actual pitch bend or to the pitch bend modulator for other targets as well? I don't know, to be honest.

**Comment by mkruselj** [comment]
With growing popularity of MPE and so on, I'm inclined to close this issue. @baconpaul Any objections?

**Comment by baconpaul** [comment]
Yes
