### ISSUE TITLE
Airwindows don't init properly in a bypassed send FX slot

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2661]
1. Bypass the send FX slot (either in the grid or via global bypass param)
2. Load AW in that same slot
3. Parameters don't initialize

![image](https://user-images.githubusercontent.com/2393720/93817200-e0f9a480-fc58-11ea-9543-f74c76bb06aa.png)

**Comment by baconpaul** [comment]
baconpaul "note to self":

The fix here is going to be, rather than using "nullptr" as a signal on the user data that we aren't initialized, set a flag on the mapper which is that it is acting as if it were a nullptr so we can still use the sentinel, but isn't a nullptr so we get the behavior.
