### ISSUE TITLE
UI crash related to non modal overlays in MSEG

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2662]
![fffff](https://user-images.githubusercontent.com/56724286/93850320-20061500-fcae-11ea-8751-e3731245cb19.gif)
This happens when having the MSEG open and then click on extend range on amplify and then click it off.

![fffff 2](https://user-images.githubusercontent.com/56724286/93850529-96a31280-fcae-11ea-903e-3f01d40fc211.gif)
Here is how you do it.

hash 51372df

**Comment by baconpaul** [comment]
#2665 closes this. Thanks for the report!
