### ISSUE TITLE
Phaser feedback stages should blade out fully at 100%

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2663]
Currently feedback at 100% just cuts the nice sounding ringing at 0,9 seconds

![abrupt stop](https://user-images.githubusercontent.com/56724286/93853380-12538e00-fcb4-11ea-89ae-28c41d77a994.gif)

As we see there are more tones that are about to ring but sound is cut, it would be nice it we could hear them all the way at 100%

Here is that exact preset
[phaser stages should blade out more.zip](https://github.com/surge-synthesizer/surge/files/5259632/phaser.stages.should.blade.out.more.zip)

hash 51372df

**Comment by mkruselj** [comment]
The main problem here is that this would change the sound and behavior of old projects.

**Comment by baconpaul** [comment]
The reason for this is `Phaser::get_ringout_decay` is set to 1000 hardcoded

I think that setting predates feedback and constitutes a bug since it results in this hard clip

I would be open to changing that ringout decay to be smarter if feedback is "high"

**Comment by baconpaul** [comment]
@K0rrid0r can you try this: if in effect_defs.h at line 219 you change

```
 virtual int get_ringout_decay() override
   {
      return 1000;
   }
```

to instead return 5000 the problem resolves yeah? (That's not the solution I just want to make sure I haven't mis-diagnosed)

**Comment by mkruselj** [comment]
You don't want to set it for all effects there, You'd want to change `Phaser::get_ringout_decay` as Paul mentioned.

**Comment by K0rrid0r** [comment]
So 5000 sounds much better and is now a full ring out. beautiful!

![abrupt stop no more](https://user-images.githubusercontent.com/56724286/93899765-f1f7f380-fcf4-11ea-9c7b-ab98073137ea.gif)

**Comment by mkruselj** [comment]
It seems like 5000 might be too much even, looks like 3000 could work too.

**Comment by K0rrid0r** [comment]
seems like 3000 works also

**Comment by baconpaul** [comment]
Yeah cool

What we really want is something like "1000 + ( feedback > 0.5 ) ( Feedback - 0.5 ) * 4000" really. But that means we need to out of line it.

The patch with the ringout is the one on this issue right?

**Comment by K0rrid0r** [comment]
the first post patch is the one that cuts at 1000 yeah.

**Comment by baconpaul** [comment]
Pushing a fix
