### ISSUE TITLE
Rename Modulator should not accept longer strings than what is accepted

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#267]
`Please provide the value` window will accept an infinite number of characters, but then crop it down to
<img width="221" alt="screenshot_11_01_2019__19_54" src="https://user-images.githubusercontent.com/4966687/51050852-d1e4d700-15da-11e9-84d4-c6410d74d4ca.png">

witness
![renamevalue](https://user-images.githubusercontent.com/4966687/51050856-d5785e00-15da-11e9-861b-9d452d55151e.gif)

suggestion: limit textfield entry to 16 characters. also, what's the `-` doing there at the end?

**Comment by baconpaul** [comment]
OK so there are two bugs here.

The extra '-' is actually a real problem with the strlcpy and null termination which needed fixing. So I fixed that and merged it.

To make the UI block at 16 chars is a lot of coding. Here's what needs doing

https://stackoverflow.com/questions/827014/how-to-limit-nstextfield-text-length-and-keep-it-always-upper-case

in cocoa_utils.mm. I think this one is probably not worth it now a long name no longer causes the over truncation which forces the -. But if someone likes cocoa and wants to write that, go for it!

**Comment by esaruoho** [comment]
loox like no-one's biting on this one :)

**Comment by itsmedavep** [comment]
Ill try and do this one. I have another UI related one to do first though(#446 ).

**Comment by baconpaul** [comment]
Closing this; the new mini-edit is all std::string based and the truncation happens after the UI. I don't want to dive into all of vstgui heck just to avoid that truncation.
