### ISSUE TITLE
About screen lifecycle and Z-order

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2673]
Currently when we're on About screen, you can still right click around and context menus tied to various controls still open. Let's block this!

**Comment by baconpaul** [comment]
You would think this is easy, but it is not.
I'll get it but it's not 5 minutes
something awful about zorder and vstgui and about box showing itself in a weird way going on.

**Comment by mkruselj** [comment]
Fixed with About page redesign sprint.
