### ISSUE TITLE
Scratchy/blocky sound when manually tweaking cutoff on vintage ladder

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2683]
It sounds like there is some smoothing missing on the cutoff control for the Vintage ladder filter type, because when manually tweaking cutoff relatively fast, it has this scratchy sound, or blocky sound with high resonance.

Here's audio comparisons between legacy ladder (first) and vintage ladder:

[legacy vs vintage ladder scratchy.zip](https://github.com/surge-synthesizer/surge/files/5276023/legacy.vs.vintage.ladder.scratchy.zip)

**Comment by mkruselj** [comment]
Same thing for OB-Xd filters actually!

[pressure_env.zip](https://github.com/surge-synthesizer/surge/files/5310566/pressure_env.zip)

**Comment by baconpaul** [comment]
Huh maybe I’m mid using dc in both

**Comment by baconpaul** [comment]
Pushed a fix to this. Closing.
