### ISSUE TITLE
Run and understand what 'include-what-you-use' says on our code

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2686]
https://github.com/include-what-you-use/include-what-you-use and so forth.

**Comment by baconpaul** [comment]
OK got this running on my mac.
It shows a lot.
I'll merge the script changes to use it but will push this out of 180

**Comment by mkruselj** [comment]
Does this mean we can make includes even leaner, making builds even faster? 😁

**Comment by baconpaul** [comment]
it means we can understand the necessary smallest set of includes, but I am not sure i like the proposed changes yet so need to ponder.
