### ISSUE TITLE
Surge in latest VCV Host crashes VCV Rack

### ISSUE THREAD

**Issue by ContemporaryInsanity** [surge-synthesizer/surge#2693]
**Describe the bug**
Selecting Surge VST3 in latest VCV Host module crashes VCV as follows:

**Please let us know your surge version**
1.7.1
VST3
64 bit

**To Reproduce**
Add the latest Host module to VCV, select Surge.
VCV Rack crashes with the following:
Surge Error
No Teensy Surge For You!
The smallest zoom on your platform is 100%. Sorry, you can't make Surge any smaller.
Jack: JackActivationCount::Signal value = 0 ref = 13
Jack: JackClient::ClientNotify ref = 13 name = VCV Rack-01 notify = 3
Jack: JackClient::kXRunCallback
Jack: JackActivationCount::Signal value = 0 ref = 13
IPlugFrame is a runloop 0x561913c3d020
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  12 (X_ConfigureWindow)
  Value in failed request:  0x0
  Serial number of failed request:  1877
  Current serial number in output stream:  1878
Gtk-Message: 13:41:01.341: GtkDialog mapped without a transient parent. This is discouraged.
Segmentation fault (core dumped)

**Expected behavior**
Surge to appear and work normally.

**Screenshots**
The following dialog remains active after VCV has crashed:
![image](https://user-images.githubusercontent.com/12547379/94268256-ccf1c380-ff34-11ea-815e-a44f3e6ba69b.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Host: VCV Rack Host module
 - Version: V1.2.0

**Comment by baconpaul** [comment]
Hi

I had tested this with Richie in august and had it working then. I don't know the version he tested vs the version you are using.

As to that message: Do you have a SurgeUserDefaults in your documents directory containing a small zoom? Does surge run for you in reaper or the juce plugin host on your system?

**Comment by RichieHindle** [comment]
Probably my fault.  😃 

Let me have a look...

**Comment by ContemporaryInsanity** [comment]
'Do you have a SurgeUserDefaults in your documents directory containing a small zoom?'

Where do I look for that exactly?

As for running elsewhere, it doesn't show up in Carla for some reason.

FYI SurgeEffectsBank works.

**Comment by RichieHindle** [comment]
It works for me:

Ubuntu 18.04.5 LTS.
Rack 1.1.6.
VCV-Host 1.2.0.
Surge 1.7.1.5270cfb VST3 (installed from downloaded .deb package).

**Comment by baconpaul** [comment]
Either ~/Documents/Surge or ~/.Surge depending on your system configuration.
Also when you installed did you install the associated assets into /usr/share or what not? What mechanism did you use to install surge?
Thanks

**Comment by baconpaul** [comment]
Oh and you need a very recent carla for VST3 support. The Juce6 plugin host is a goto testing one for me for VST3 on linux (as of course is linux reaper which works great).

**Comment by baconpaul** [comment]
Oh also: Are you using SurgeRack in the same process space as Surge in VCV-Host. I wonder if that conflicts? Or is this in a clean rack with VCVHost standalone.

**Comment by ContemporaryInsanity** [comment]
I installed from the .deb package on https://surge-synthesizer.github.io/

My SurgeUserDefaults.xml (won't let me include xml for some reason, so screengrab):

![image](https://user-images.githubusercontent.com/12547379/94276723-86a26180-ff40-11ea-9d19-62388d14b5ab.png)

Not using SurgeRack.  I just want Flute 2 back, I miss it :)

**Comment by baconpaul** [comment]
See that "defaultZoom value="0"" line?
That's the line that's wrong, for some reason
My guess is: because you don't have zenity installed and you tried to set it, and it blew up. (We have fixed this in the nightly but in 1.7.1 you need to be able to launch zenity for lots of things; in the nightly it is fewer)
Edit that XML and set "defaultZoom value="100"" then restart
and I bet it will work.

**Comment by baconpaul** [comment]
Oh and if you're a flute 2 fan, here's a short video I made taking it apart: https://www.youtube.com/watch?v=u7u49V3Loxw&t=17s

**Comment by ContemporaryInsanity** [comment]
That's fixed it - thank you!

Yeah, LOVE flute 2, you've shared that vid with me before :)

**Comment by baconpaul** [comment]
Oh ha sorry. It took me a while to figure out so I share it a lot :)
