### ISSUE TITLE
Crash on unload/quit (Ableton 9.7.1, 64-bit, Win8.1)

### ISSUE THREAD

**Issue by vX0r** [surge-synthesizer/surge#27]
The plug-in (VST2) causes crashes when removing Surge from a track or quitting Ableton, only displaying the generic "has stopped working" Windows error message.

**Comment by cyanit** [comment]
have you tried reproducing this in other daws or is this an ableton only error? 
Ill try to reproduce it in Bitwig Studio without sandboxig.

**Comment by vX0r** [comment]
I have the demo version of Bitwig Studio 2.4 installed, it is not affected.

**Comment by paulhuman** [comment]
Hi, I can confirm that Surge (v1.6 2019-01-12) almost always crashes Ableton 9.7.3 (x64, Win7) on exit.
Thank you for improving this remarkably powerful synth.

**Comment by baconpaul** [comment]
Ok! I guess it’s time to think about shutdown paths in the hosts. @paulhuman does live provide any debugging output at all? Or just “sorry it crashed”? Something like an ugly stack or a Mac crash report could be v helpful

**Comment by baconpaul** [comment]
And thanks for the thanks! Appreciated!

**Comment by baconpaul** [comment]
Oh @paulhuman can you screenshot us the about screen from the one you are running before it crashes?

**Comment by paulhuman** [comment]
Sorry for the delayed response, @baconpaul. Strange, I couldn't make crash around 10 times in a row.
Here is a screenshot of Live crashing and an auto-generated Live's crash report zipped.

![crash_screen_p1](https://user-images.githubusercontent.com/14587675/51313358-66798a00-1a5e-11e9-81c6-3a51a802e620.png)
![crash_screen_p2](https://user-images.githubusercontent.com/14587675/51313364-6bd6d480-1a5e-11e9-955c-c1ad8568dbba.png)
[Ableton Crash Report 2019-01-17 133933 Live 9.7.3.zip](https://github.com/surge-synthesizer/surge/files/2768272/Ableton.Crash.Report.2019-01-17.133933.Live.9.7.3.zip)

Hope this will help.

**Comment by baconpaul** [comment]
Thank you!

**Comment by esaruoho** [comment]
@paulhuman does this still happen in the newest build? (grab it from http://surge-synthesizer.github.io )

**Comment by baconpaul** [comment]
We haven't changed anything in the open/close path @esaruoho so I'm not sure it will be better. We have a few interesting issues kicking around which make us think we need to be more careful in that path too. @paulhuman always welcome you trying a new version of course (and the new version has cool new stuff in it!) but I don't think we've done anything which would fix this bug yet.

**Comment by esaruoho** [comment]
@vX0r hi, are you experiencing the same issue with the newest build at http://surge-synthesizer.github.io ?
