### ISSUE TITLE
Clean up Windows SVG/PNG resource files

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2706]
All those PNG names from 1.6.0 beta 8 still kicking around

@baconpaul issue to fix. Just for a rainy day.

**Comment by mkruselj** [comment]
Could also purge all the PNGs in resources/bitmaps along the way?

**Comment by baconpaul** [comment]
I believe we can now yes.But want to check one thing which I'll do when we do this issue!
