### ISSUE TITLE
Midi mapping on Macro 1 changes "Send FX 1 Return"

### ISSUE THREAD

**Issue by kanduvisla** [surge-synthesizer/surge#2725]
**Describe the bug**
I try to do a Midi learn on Macro 1 by Right clicking, selecting "Learn Midi Macro..." and turn the knob on my midi controller. 
But after that, if I turn that knob, it's not the Macro that is adjusted, but the slider of "Send FX1 Return".

Even if I unlearn it on Send FX1 Return and try again, it gets re-assigned again.

* Surge Version: 1.7.1
* Plugin type VST2
* Bits 64
* Midi controller: Arturia MiniLab MK2

**To Reproduce**
1. Select a patch with a Macro
2. Midi learn it to a knob on the midi controller
3. Try to control the macro with the midi controller after learning

**Expected behavior**
I would expect the Macro to be controlled by the Midi controller, but instead "Send FX1 Return" is changed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Host: Renoise 3.2.2

**Comment by mkruselj** [comment]
@baconpaul This looks like the same issue that happens in SAVIhost.

@kanduvisla Do you perhaps have any other host to test if the same thing happens there?

**Comment by baconpaul** [comment]
How did you build the vst2?

I know what it is - metacontroller id mapping. I fixed it in the vst3 forever ago

**Comment by kanduvisla** [comment]
@baconpaul , I did not build the VST, I just installed it. I just assumed that it was VST2, because it most certainly is not VST3 (since Renoise is not compatible with VST3). I am not at my home computer right now so I cannot check the exact version information in the about-screen. I'll update this ticket as soon as possible.

**Comment by baconpaul** [comment]
1.7 doesn't have a vst2; so the exact about screen would help. You may be running a 1.6 vst2 which had this bug?

**Comment by kanduvisla** [comment]
Yes, I see that now. I was in the assumption that installing 1.7 had overwritten the VST plugin. I switched to Renoise a while back so I wasn't paying attention.

Renoise is indeed using the VST2 plugin. Any chance that 1.7.x will also support VST2?

**Comment by baconpaul** [comment]
If you are a valid VST2 licensee you can build a VST2 from the source.
We do not have a license to distribute a binary.
https://surge-synthesizer.github.io/formats

Are you on 1.6.6? I swear I fixed this bug in the 1.6 family somewhere. You can still grab 1.6.6 from our website.

**Comment by kanduvisla** [comment]
I believe I did had this bug in 1.6.6.

I am now using a VST3 wrapper in Renoise so I can load 1.7.1 event though Renoise does not support it, but the wrapper does not update the UI. But that's not your problem ;-)

I'll disable the wrapper and check again what version I'm using natively.

**Comment by kanduvisla** [comment]
Hm, I do have this issue also in 1.6.6. However, I did manage to get a workaround by manually assigning it to a CC.

Too bad newer versions are no longer shipped in VST2. The wrapper is also not a very elegant solution. Doesn't update UI and I have the feeling that it adds some latency :-(

**Comment by baconpaul** [comment]
Yeah I mean, that's what happens when you build an entire industry on software with the wrong license. I'm not thrilled about it either.

I'll leave this open just to make sure the VST2 at head doesn't also do it.

But also: We've gone out of our way to make it easy to build surge. All the tools are free. If you have the VST2SDK you can build a VST2 and several devs do it frequently to make sure it still works. It's the binary distribution which is the thing we can't do. All explained up on the GitHub.

**Comment by kanduvisla** [comment]
I did find a VST2 version if 1.7.x on [KVR Audio](https://www.kvraudio.com/forum/viewtopic.php?p=7848899&sid=b5a655ad770bfdf5a51191479edb3c74#p7848899). I'mnot sure what version it is, because the about-screen states it's HEAD-some-hash. I believe @mkruselj put it there because it's the same avatar 😆 

I can confirm that the issue is resolved in this version, so as far as I'm concerned this ticket can be closed.

> ... and several devs do it frequently to make sure it still works

Do you know of any developers / URL's where I can find these builds?

By the way, thanks for the good support and quick response on this topic.

**Comment by K0rrid0r** [comment]
@kanduvisla you can either read the readme on how to build your own latest vst2 surge or go to this link.
https://www.soundmute-recordings.com/_gyro/surge_build/?fbclid=IwAR0n5PZrEJq4frMAA5VhfvJBmv-IleFqc59bLqiu0mkYGd6DhY_xzhn4uJA

and just out of interest, what was the exact hash number?

**Comment by kanduvisla** [comment]
@K0rrid0r :

The hash is 1.7.HEAD.8fd9e670
