### ISSUE TITLE
More robust skin resources filename lookup

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2730]
EvilDragon: oh btw @baconpaul a strange thing happens if you have a copy of svg in skin folder but rename its extension
EvilDragon: it seems it still keeps on loading it
EvilDragon: i.e. bmp00102.svg1
EvilDragon: would still load even if you actually had bmp00102.svg in the folder
EvilDragon: but if you do something like bmp00102 copy.svg then it loads the one without "copy" in the name?
baconpaul: HA this code sucks. https://github.com/surge-synthesizer/surge/blob/c8766229087617fbb333da445ffa5af6763cea02/src/common/gui/SkinSupport.cpp#L429
baconpaul: That is "sloppy still getting it right" code
baconpaul: It will also break mseg
baconpaul: can you stick that all in an issue?
baconpaul: That code is doing a 'bad job' of mapping svg names over and 'doesn't check anything other than the most fragile expected condition'
baconpaul: Easy fixes

**Comment by baconpaul** [comment]
This couples with #2817

**Comment by mkruselj** [comment]
Fixed with 6d958b4.
