### ISSUE TITLE
Remove the need for $ color ID quantifier

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2736]
Currently the skin engine uses # and $ prefixes to discern between hexadecimal color codes (#) and named color IDs ($). I think it would be more user-friendly if the $ quantifier weren't required to use the named color IDs. I mean, we define those IDs purely with a name and no $ prefix. `<color id="white" value="FFFFF"/>` So why not just use it as `value="white"` when we call upon it?

**Comment by mkruselj** [comment]
I assume the problem here is if we name an ID something like "abacab" or the like. In this case I think it should 1) take priority over the hex code if it's found in the list of defined color IDs, and 2) be discouraged to name colors like that in skin docs.

**Comment by baconpaul** [comment]
Fix inbound

basically for color vluaes

#RRGGB or #RRGGBBAA are hex

`$alias` (for backwards compatibility) or `alias` (which is what you want) are alias names

alias are late resolved so you don't even need them in order

Will close this one when merged
