### ISSUE TITLE
Debug Builds show DEBUG on the UI

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2738]
I just spent half an hour figuring out why my LPX music wouldn't render

So there you go...

LOL

**Comment by mkruselj** [comment]
![image](https://user-images.githubusercontent.com/2393720/94675199-a4454180-0319-11eb-951b-de8540aac88a.png)

`<label x="321" y="37" text="DEBUG BUILD" font-size="9" color="$red" />` 😛

**Comment by baconpaul** [comment]
yup that's exactly what I want. I just need the if in C++, not the label in skin.

**Comment by mkruselj** [comment]
Yes sure. Just wanted to save you the trouble of positioning it so you can just lift the coords and font size from there :)

**Comment by baconpaul** [comment]
yeah super handy! thank you
