### ISSUE TITLE
Color Defaults should live in the color db, not in random C++

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2748]
@baconpaul knows what this means.

**Comment by mkruselj** [comment]
Actually EvilDragon knows as well and could do the porting too if shown the way. 🙂

**Comment by baconpaul** [comment]
Oh that would be great!
Let me do one, and then write a prescription here.
Sound good?

**Comment by mkruselj** [comment]
Better than doing AW typeins! 🤣

**Comment by baconpaul** [comment]
OK the diff in #2752 shows us the change.

Basically change `getColor( Skin::Foo::Bar, kRedCColor )` to `getColor( Skin::Foo::Bar )` and take the definitions of `Skin::Foo::Bar` in SkinColors.cpp goi add the default

You are done when you can change getColor( id, default ) to private as mentioned in SkinSupport.h
