### ISSUE TITLE
Display a single-cycle LFO waveform when rate is deactivated

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#2761]
@mkruselj , I and others discussed over on Discord the other day that it would be nice to have the LFO display show a single cycle of the LFO waveform when rate is deactivated. A vertical line representing the phase would probably be the ideal way to visualize the current position in the cycle. All of this would be extremely useful, especially when scrubbing through complex waveforms, like the MSEG for example.

**Comment by baconpaul** [comment]
The formula is

1. In CLFOGui if deactivated run tlfo twice
2. The second time have rate not deactivated and set to something appropriate (like 0.5 hz or so)
3. And draw both lines

**Comment by mkruselj** [comment]
2. It should fit one whole cycle on the display. Seems that value which gets us this is 0.181 Hz.
