### ISSUE TITLE
1.71 Fails to Load in Carla Ubuntu Linux

### ISSUE THREAD

**Issue by preppert** [surge-synthesizer/surge#2773]
Using Carla in Ubuntu Studio 20.04.1, a scan fails to locate Surge 1.7.1 after extracting the .deb file into ~/.vst3/Surge. Navigating directly to the surge.so file from within Carla generates a popup error:  "Failed to load the file. Could not find the VST main entry in the plugin library"  I was able to use the previous Linux version of Surge on my current setup.  Installing from the command line appears to work but I was unable to find (or run) the application via "sudo apt install ./surge-linux-x64-1.7.1.deb"

**Please let us know your surge version**
This information is all in the menu/about screen

* Surge Version: 1.7.1
* Plugin type (VST2, 3 or AU) VST 3
* Bits (32/64)

**To Reproduce**
1. Go to Carla
2. Click on 'Add Plugin/Refresh'
3. When complete, attempt to load Surge.
4. See that Surge is not found. 

**Expected behavior**
Surge appears to have unpacked successfully.  Carla is not recognizing the .so file. At all. 

**Screenshots**
N/A but I will append any screenshots or log files that might be helpful.  

**Desktop (please complete the following information):**
 - OS: Ubuntu Studio 20.04.1 LTS
 - Host: Carla on Jack, I did not attempt to load this in Reaper or Ardour. Just wanted to play standalone.  
 - Version [e.g. 2.4]

**Additional context**
It would be really nice to see Surge in the Ubuntu Software Center (app store for Ubuntu).  Not sure how to go about it, but check out https://snapcraft.io/store This would circumvent installation issues. Note there are not very many Linux synths and few are registered in USC.

**Comment by baconpaul** [comment]
Are you using a Carla version which loads vst3? I am not sure the prod release has vst3 turned on but don’t know the versioning scheme (so tagging @falkTX )

That error message sounds like it might be vst2 path though. 

We have tested surge in a non release Carla with vst3 support, qtractor with the same, and non foss synths. Checking reaper would help make sure it’s not something else.

As to ubuntu store / snap - I understood that snap and plugins weren’t that great a combo. But if you know how to package for that system we would welcome the help! 

Probably best to hop on our discord for that.

Thanks

**Comment by baconpaul** [comment]
Hi! I’m going to close this. If you can share details please do reopen it.

**Comment by pierpo** [comment]
Hi @baconpaul! I just faced the exact same problem (exact same setup and steps). I have Carla 2.1.0, which has other VST3 plugins working.

If I drag and drop the .so directly, I get the error `Could not find the VST main entry in the plugin library`.

Any idea?

**Comment by baconpaul** [comment]
None but let me re-open this and look next time I fire up Linux.

**Comment by baconpaul** [comment]
Also: How did you get surge? That is, what mechanism did you use to get the .so and what system are you running on? For instance, if you downloaded our .deb and are on buster you will have the wrong xcb_util library in the dynamic links. (If you built from source on your system this is far less likely to the be case)

**Comment by falkTX** [comment]
Only v2.2 of Carla supports VST3 on Linux.

**Comment by baconpaul** [comment]
Well that explains it!

@pierpo some plugins, I understand, put both the VSt2 and VST3 entry point in the same .so so perhaps that explains why it seems like VST3s work.

let me close it again. And thanks for the info @falkTX!

**Comment by pierpo** [comment]
Well that settles it 😊 
Thanks both of you!
