### ISSUE TITLE
No Surge.vst3 file on x86 installation (Windows 10)

### ISSUE THREAD

**Issue by tekord** [surge-synthesizer/surge#2774]
**Describe the bug**

Nightly build and latest stable version of VST3 x86 does not install into C:\Program Files\Common Files\VST3\Surge Synth Team. There is no Surge.vst3 file. But x64 is installed OK.

**Please let us know your surge version**
This information is all in the menu/about screen

* Surge Version: Nightly build and 1.7.1(x86)

**To Reproduce**

Downloaded the installer and run it.

**Desktop (please complete the following information):**
 - OS: Windows 10 (x64)

**Comment by mkruselj** [comment]
x86 versions on 64-bit Windows install in C:\Program Files (x86)\Common Files\VST3.

**Comment by tekord** [comment]
Oh, thanks!
