### ISSUE TITLE
Profile this unexpectedly high CPU patch

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2784]
@Jacky-Ligon and I were discussing the attached patch using a somewhat higher than expected amount of CPU
I wonder why
[PROFILE THIS.fxp.zip](https://github.com/surge-synthesizer/surge/files/5330300/PROFILE.THIS.fxp.zip)
Just a note to self so I don't forget to look at this before 1.8 ships

**Comment by baconpaul** [comment]
<img width="905" alt="Screen Shot 2020-11-18 at 9 44 09 AM" src="https://user-images.githubusercontent.com/13387561/99544730-a3787580-2982-11eb-81a9-f48d0f467ed8.png">

<img width="864" alt="Screen Shot 2020-11-18 at 9 44 41 AM" src="https://user-images.githubusercontent.com/13387561/99544791-b5f2af00-2982-11eb-87e9-1dc2be8e7ecf.png">

Here's the profiling. So basically

2/3 of the time is in those mid-unison-count wavetable oscillators
1/3 of the time is in the Vintage Ladder RK calculate derivs

But clearly if I play that patch with high speed long note I get crackles and peaks.

**Comment by mkruselj** [comment]
@baconpaul so is there something to fix here or is it more like "yup, unison with WT costs CPU and RK also costs CPU so that's that"? :)

**Comment by baconpaul** [comment]
oh yeah that is that; and i shared that with jacky; and he adjusted his patches. we can close this issue.
