### ISSUE TITLE
Drag & Drop FX

### ISSUE THREAD

**Issue by viceverser** [surge-synthesizer/surge#2787]
**Is your feature request related to a problem? Please describe.**
Frustrated when I want to copy or move an effect in the FX slots to another position.

**Describe the solution you'd like**
Add drag and drop ability to rearrange FX in slots.

**Describe alternatives you've considered**
Right click (currently for mute) would be a right click menu, benefits would be flexibility in 'preset' save/recall as well as copy, paste, cut and mute... Negatives are, it would slow the workflow for some users who often use the mute functions.

**Comment by baconpaul** [comment]
![ADiversion](https://user-images.githubusercontent.com/13387561/95657089-97c2a500-0ae0-11eb-9550-c782f0bd61a4.gif)

:)

Will get this done this wkend.
