### ISSUE TITLE
Windows+Clang: Corrupt patch menu text

### ISSUE THREAD

**Issue by mvf** [surge-synthesizer/surge#2789]
The patch menu text is corrupted on Clang builds on Windows (only).

**MSVC:** Working
![ok-msvc-release](https://user-images.githubusercontent.com/304760/95297930-8af14780-087b-11eb-871b-6aba9df8e5e3.png)

**Clang Release:** Somewhat subtly broken
![nok-clang-release](https://user-images.githubusercontent.com/304760/95297951-947aaf80-087b-11eb-8cd0-344f96f52936.png)

**Clang Debug:** Chaos
![nok-clang-debug](https://user-images.githubusercontent.com/304760/95297958-980e3680-087b-11eb-85e8-d6c04727ce32.png)

This reproduces 100%. The menu remains functional.

**Comment by mkruselj** [comment]
I really wonder if this still happens now that we are on JUCE, @baconpaul.

**Comment by baconpaul** [comment]
I would be amazed the menu codeparh is completely changed
