### ISSUE TITLE
MSEG editor assets not overridden by skins

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2803]
So if I have bmp00301/2/3/4 in my skin, they don't seem to be applied at runtime at all.

Also, if I change a skin while MSEG editor is opened, it's not updated to match the skin definition. If this is intentional, then MSEG editor should be force closed on skin change/refresh.

**Comment by baconpaul** [comment]
My guess is this has something to do with the image id handling in the createImageNameMap in skin support which needs to be smarter anyway.

**Comment by baconpaul** [comment]
just as a note to self for when i debug this later on

**Comment by mkruselj** [comment]
#2817 will fix this thoroughly, but in the meanwhile PR #2819 will work.

**Comment by baconpaul** [comment]
Yeah lets close this in favor of 2817 (I will remember to test this of course when I do that fix)
