### ISSUE TITLE
Implement SSE optimizations for Sine oscillator unison

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2807]
With #4018 we are way way better. Just wanna do a bit more parallelism in the legacy loops before we close this.

--------

Now SIN is a beast which many of us use all the time

Unison can suck down CPU
even with our approximations
So you know. Lets SSE across the voices.

**Comment by jatinchowdhury18** [comment]
I wonder, if you have considered using something like a ["magic circle"](https://ccrma.stanford.edu/~jos/pasp/Digital_Sinusoid_Generators.html) algorithm to improve computational efficiency?

Advantages:
- computing a single sample of output requires only 2 multiplies
- should be pretty easy to vectorize with SSE instructions
- responds well to frequency changes (even at audio rate)

Disadvantages:
- the algorithm has some memory that needs to be managed, similar to the "phase" with a traditional oscillator, but less obvious
- it looks like the phase of the oscillator is being [changed in real-time](https://github.com/surge-synthesizer/surge/blob/main/src/common/dsp/SineOscillator.cpp#L153). I'm pretty sure there's a way to handle this in the magic circle algorithm, but I'd need to work out the math

Anyway, if you're curious about it, I have some JUCE code that implements a magic circle oscillator: https://github.com/Chowdhury-DSP/chowdsp_utils/blob/master/DSP/Sources/chowdsp_SineWave.h

**Comment by baconpaul** [comment]
In some situations we do https://github.com/surge-synthesizer/surge/blob/442de47f5754224a3ef1b9cfa7ab9f3918b0bb2a/src/common/dsp/DspUtilities.h#L50

there’s the class that implements this and we use it in the kegscy fm mode 

For the fm target waveshaper we use the pade approximations 

but the loop I was thinking about was https://github.com/surge-synthesizer/surge/blob/442de47f5754224a3ef1b9cfa7ab9f3918b0bb2a/src/common/dsp/SineOscillator.cpp#L150 where I think we can do see operations across the block since the wavetyoe is a constant per voice

**Comment by baconpaul** [comment]
Oh and thanks!

**Comment by baconpaul** [comment]
I have this underway in `baconpaul/perf-sine`. It is a "substantial change' which improves performance a lot.
