### ISSUE TITLE
Pull anything from nanosvg into our fork

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2809]
I guess there are some PRs that went in. Since its not maintained over there, lets pull them here at least.

**Comment by baconpaul** [comment]
But not for 1.8

**Comment by mkruselj** [comment]
Oooh, could support some nice things then, I guess?

**Comment by baconpaul** [comment]
Nah it's like 5-8 commits. The root project is pretty dead. https://github.com/memononen/nanosvg/commits/master

**Comment by mkruselj** [comment]
Gonna be deprecated by JUCE port.

**Comment by baconpaul** [comment]
Yeah definitely not in the drawing path

**Comment by mkruselj** [comment]
Closing this one too in favor of Surge XT/JUCEification.
