### ISSUE TITLE
Gradients exported from Figma sometimes don't display

### ISSUE THREAD

**Issue by h-v-b** [surge-synthesizer/surge#2813]
**Bug Description:**
Upon exporting SVGs, some object don't display their gradients, and only show the main color of them.

**Surge Version**
This information is found on the About screen, which you get to from the bottom right menu

* Version: Version 1.8.nightly.bc2ef79 (x86_64 64-bit macOS VST3 in Bitwig Studio. Built 2020-10-08 at 15:14:45 on pipeline host 'Mac-1602169969878.local')
* Plugin Type: VST3
* Bitness: 64

**Reproduction Steps:**
The OSC octave setting and Scene Octave setting have the same object assigned with the same fill color gradient.
One displays, the other doesn't, or prehaps has the wrong origins?

**Expected Behavior:**

**Screenshots:**
![Screenshot 2020-10-09 at 13 01 08](https://user-images.githubusercontent.com/1453415/95575914-d9dfde00-0a2f-11eb-941b-4dc4359f5d94.png)

**Computer Information (please complete the following information):**
 - OS: Osx Mojave
 - Host: Bitwig
 - Version: 3.2.8

**Additional Information:**
Vector resources can be found here: https://www.figma.com/file/D33do5XWZEAFQmUPV7eAAf/Surge-Redesign?node-id=26%3A1578

**Comment by baconpaul** [comment]
[figmag.svg.zip](https://github.com/surge-synthesizer/surge/files/5355720/figmag.svg.zip)

**Comment by baconpaul** [comment]
OK so here's the problem

The first box uses paint0_linear which is a userSpace gradient from 0 to 17, and the rect is from 0 to 17 translated by 192
the second box uses paint1_linear which is a userSpace gradient from 192 to 240 and the rect is from 192 to 240 with no translation
so what's happening is the translation of the parent is not getting applied to the gradient
so by the time you render this the gradient which is 0-17 or whatever is not in the right space

I'll debug the code and figure it out. Should be fixable.

**Comment by baconpaul** [comment]
[figmag.svg.zip](https://github.com/surge-synthesizer/surge/files/5355942/figmag.svg.zip)

Here's the minimal example which shows it

**Comment by mkruselj** [comment]
@baconpaul Is this issue now sorta adressed with the Figma fixer script?

**Comment by baconpaul** [comment]
yeah except @h-v-b needs a version which does a while directory and I forgot about that.

**Comment by h-v-b** [comment]
fixed with the directory fixing

**Comment by baconpaul** [comment]
Cool. So lets close this then. thanks and sorry to have forgotten to do that!
