### ISSUE TITLE
VST2 start of roll ppqpos missing?

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2836]
As reported by @K0rrid0r 

Using VST2 in FL and Reaper Win 32bit
Set up a freerun self or whatnot
Start at 1/64th of a beat and you are good. Start at 0 and you are not
For some reason the VST2 is not giving us a good playing/position at the start of roll. time_data.ppqpos is not getting set until the second time through perhaps? Or we are reading the flags incorrectly?

**Comment by baconpaul** [comment]
I bet the first time round you get a transportChanged or some such not a trasnportPlaying and we need to || for that

**Comment by K0rrid0r** [comment]
https://www.youtube.com/watch?v=YMgWZopkIHo

just putting the example here.

**Comment by baconpaul** [comment]
Yeah no that's it the first message is transportChanged not transportPlaying. Are you around to test a branch?

**Comment by K0rrid0r** [comment]
yepp! shoot!

**Comment by baconpaul** [comment]
`baconpaul/vst2-transport`

lemme know if that fixes it. It seems it does for me mac reaper vst2 64 bit (although I used a slightly different test than you)
