### ISSUE TITLE
Fake mouse hovers

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2852]
![](https://user-images.githubusercontent.com/13387561/95401976-99238000-08dc-11eb-88d6-0673669ca27d.png)

As shown here

![](https://user-images.githubusercontent.com/56724286/95397650-0c8cb800-0904-11eb-9e88-9c942cadb5b0.gif)

basically at wrong zooms you end up with the mouseUp event from a popup in vstgui windows getting mis-zoomed and sending a hover message to the modulation sources which, now they have higher contrast hover, is clear as day.

originally discussed in #2763 but it is nothing to do with SkinObjects so making a separate issue.

**Comment by K0rrid0r** [comment]
also this one!
![234](https://user-images.githubusercontent.com/56724286/95884775-ceb4e700-0d7c-11eb-9cb2-67a7192e505b.gif)

**Comment by K0rrid0r** [comment]
![236](https://user-images.githubusercontent.com/56724286/95885841-0ec89980-0d7e-11eb-8604-b67bf000a9ba.gif)

100% zoom

Exactly the same for Width, Sub Osc Width and Main Sub Mix

**Comment by baconpaul** [comment]
i bet if you move the parent window it will also change mis-hover

the problem is the mouse up is not getting transformed to logical coordinates properly

**Comment by mkruselj** [comment]
OK this fix actually created other problems unfortunately! Note that some hovers now happen elsewhere:

![boop](https://user-images.githubusercontent.com/2393720/100395640-fd8fcf80-3041-11eb-8270-d1abd5f08fb9.gif)

**Comment by baconpaul** [comment]
So this is the inverse problem
It used to be mouseup worked except from
Menus so menus made hovers transformed
Out

Now mouseup for non menus which used to work generate hovers transformed in

So @Kingston1 s transform needs to only trigger it the mouse up comes from a popup. Or maybe the pop needs to not send the mouse up event at all and then back out the transform 

Still plenty of time before 18 - I’m sure we will get therr

**Comment by mkruselj** [comment]
Yeah I think the latter might be a better way to go - popup not sending mouse up events at all. I can't see why we'd need those.

**Comment by baconpaul** [comment]
Yeah the primary reason is because I have no idea how to do that! But it is what we have to do (or at least we should go back to the older bug if we can’t figure it out)

I wonder if the option menu can stick something into the message so we know it came from thrrr tho..l

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/commit/b5627fc8296e2351d48d766dc29ce6e2afbec2e4 Should fix this so Closinggagain!
