### ISSUE TITLE
strange skins on VST3/VST2 both normal mode and debug

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2858]
![4 surges](https://user-images.githubusercontent.com/56724286/95928863-c8e1f480-0dc2-11eb-8cd2-6397e77c7a35.gif)

upper left SURGE 32 BIT VST2
Version 1.8.main.f61927a7 (Intel 32-bit Windows VST2 (unsupported) in Image-Line Fruity Wrapper. Built 2020-10-14 at 01:28:25 on local host 'KORRIDOR')

upper right SURGE 32 BIT VST2 DEBUG
Version 1.8.main.f61927a7 (Intel 32-bit Windows VST2 (unsupported) in Image-Line Fruity Wrapper - DEBUG BUILD. Built 2020-10-14 at 01:34:39 on local host 'KORRIDOR')

lower left SURGE 32 BIT VST3
Version 1.8.nightly.f61927a (Intel 32-bit Windows VST3 in Fruity Wrapper. Built 2020-10-13 at 21:44:45 on pipeline host 'WIN-693N3BH3EVJ')

lower right SURGE 32 BIT VST3 DEBUG
Version 1.8.main.f61927a7 (Intel 32-bit Windows VST3 in Fruity Wrapper - DEBUG BUILD. Built 2020-10-14 at 01:34:39 on local host 'KORRIDOR')

something happend!

**Comment by K0rrid0r** [comment]
sorry this report is wrong about the VST3 nightly. actually all of them are looking wrong. (i had not opened the correct vst3 symbolic link when i did this picture)

so i did another update to 

Version 1.8.main.995b36ce (Intel 32-bit Windows VST3 in Fruity Wrapper. Built 2020-10-14 at 11:49:34 on local host 'KORRIDOR')

still looking wrong on the skin

**Comment by baconpaul** [comment]
Jus5 making sure your assets are up to date as well as your dll?

**Comment by K0rrid0r** [comment]
@baconpaul just to make sure again i just installed latest nightly assets, still the same.

**Comment by K0rrid0r** [comment]
This the pictures of the surge skin goes in the commit order.
![0 list](https://user-images.githubusercontent.com/56724286/96159194-ab24a480-0f14-11eb-9d41-fb83f7a12909.gif)

I have installed latest nightly also, but i still get this. Notice after fadde1b6dbbf691bdd9250f2420ba13307aeaf38 it stay like this.

![14 080e28f](https://user-images.githubusercontent.com/56724286/96158563-f094a200-0f13-11eb-9c8f-e0c68c1683ec.gif)
https://github.com/surge-synthesizer/surge/commit/080e28fb550daa1b2183733a7d93bebfc37afbc5

![13 d1bf77a](https://user-images.githubusercontent.com/56724286/96158580-f4282900-0f13-11eb-99aa-f6d184e7ba63.gif)
https://github.com/surge-synthesizer/surge/commit/d1bf77a249f69ecf65132380c0b84e4499415c62

![12 af9b6d2](https://user-images.githubusercontent.com/56724286/96158591-f68a8300-0f13-11eb-9bd1-280622acc8a9.gif)
https://github.com/surge-synthesizer/surge/commit/af9b6d286bab9dc08400f46e322fb2db0238b407

![11 c9677aa](https://user-images.githubusercontent.com/56724286/96158601-f8ecdd00-0f13-11eb-96d3-dabc8aede073.gif)
https://github.com/surge-synthesizer/surge/commit/c9677aa9ac4408ab8487592098fe2003a68f9699

![10 995b36c](https://user-images.githubusercontent.com/56724286/96158617-fb4f3700-0f13-11eb-9d2b-4e2733bac6e1.gif)
https://github.com/surge-synthesizer/surge/commit/995b36cef1c9991f335e52f879f5319950ceaa7e

![9 f61927a](https://user-images.githubusercontent.com/56724286/96158623-fd18fa80-0f13-11eb-97c3-cbfe9d24b309.gif)
https://github.com/surge-synthesizer/surge/commit/f61927a71a2a6ff98b9731aedaca15a7205bcd00

![8 656123a](https://user-images.githubusercontent.com/56724286/96158632-fee2be00-0f13-11eb-905f-dcbb87a4e13e.gif)
https://github.com/surge-synthesizer/surge/commit/656123ab57feb078c150c9cbeddedf9d86988c74

![7 fadde1b](https://user-images.githubusercontent.com/56724286/96158639-01451800-0f14-11eb-9602-4e7ac47ca0af.gif)
https://github.com/surge-synthesizer/surge/commit/fadde1b6dbbf691bdd9250f2420ba13307aeaf38

![6 8c38970](https://user-images.githubusercontent.com/56724286/96158643-03a77200-0f14-11eb-9df4-5e44e9dbcc0c.gif)
https://github.com/surge-synthesizer/surge/commit/8c389703f23c3f2b4565f6593b946539cf33a061

![5 55b8799](https://user-images.githubusercontent.com/56724286/96158652-05713580-0f14-11eb-9dbd-d23c592b4e22.gif)
https://github.com/surge-synthesizer/surge/commit/55b8799268d5c0f7abc5d9c72766fd3e8eeac076

![4 934e33d](https://user-images.githubusercontent.com/56724286/96158661-07d38f80-0f14-11eb-9d6d-b07904d96af1.gif)
https://github.com/surge-synthesizer/surge/commit/934e33d7ed8e7b788acc1fe07cd29be56b08c895

![3 c280628](https://user-images.githubusercontent.com/56724286/96158668-0a35e980-0f14-11eb-9c4e-437645553a79.gif)
https://github.com/surge-synthesizer/surge/commit/c280628c462bf21e4596b406f651090d7a3f447f

![2 646f218](https://user-images.githubusercontent.com/56724286/96158809-30f42000-0f14-11eb-82b5-5e07b77029b2.gif)
https://github.com/surge-synthesizer/surge/commit/646f21854e9217ca65015867b21352bc6c2acd23

![1 11e8be6](https://user-images.githubusercontent.com/56724286/96158820-33567a00-0f14-11eb-9d16-937e5d20d993.gif)
https://github.com/surge-synthesizer/surge/commit/11e8be6bff8be659b1f557f8419bc83ad1f44655

**Comment by K0rrid0r** [comment]
git submodule update fixed it
