### ISSUE TITLE
Why crash happens when i open this preset?

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2860]
**Bug Description:**
Ok would love to know why this specific surge/daw crash happens when i open this preset (important to note is, this crash happen randomly, sometimes it does not happen and sometimes it does and i have many of those presets that "needs" to crash one time and then on reopening whole project and surge, no crash)

It's very random. And why crash one time then next time open no crash? 

You will probably have a hard time catching this error because it comes very randomly.

info from the dedugger
![crash 1 opening up preset that normally works 3](https://user-images.githubusercontent.com/56724286/95984623-c06dd600-0e23-11eb-953a-0734d0a4f04e.gif)
![crash 1 opening up preset that normally works 4](https://user-images.githubusercontent.com/56724286/95984628-c2379980-0e23-11eb-876a-91edec2925da.gif)

[PSY 3 - trigga med midi out wholetone.zip](https://github.com/surge-synthesizer/surge/files/5377935/PSY.3.-.trigga.med.midi.out.wholetone.zip)

Version 1.8.main.f61927a7 (Intel 32-bit Windows VST2 (unsupported) in Image-Line Fruity Wrapper - DEBUG BUILD. Built 2020-10-14 at 01:34:39 on local host 'KORRIDOR')

**Comment by K0rrid0r** [comment]
This still occurs and now i got another crash error instead.

![crash 1 opening up preset that normally works 5](https://user-images.githubusercontent.com/56724286/96195654-97496480-0f4d-11eb-846c-75489f2d0c92.gif)
![crash 1 opening up preset that normally works 6](https://user-images.githubusercontent.com/56724286/96195658-99132800-0f4d-11eb-84d9-fc7d381ad32a.gif)

**Comment by K0rrid0r** [comment]
and another one

![crash 1 opening up preset that normally works 7](https://user-images.githubusercontent.com/56724286/96195776-fe671900-0f4d-11eb-902e-01ae0439ce61.gif)
![crash 1 opening up preset that normally works 8](https://user-images.githubusercontent.com/56724286/96195778-00c97300-0f4e-11eb-87fb-e53c05c9b8f1.gif)

**Comment by K0rrid0r** [comment]
and another one

![crash 1 opening up preset that normally works 9](https://user-images.githubusercontent.com/56724286/96196021-9fee6a80-0f4e-11eb-8fc3-e4c47b31bd66.gif)
![crash 1 opening up preset that normally works 10](https://user-images.githubusercontent.com/56724286/96196029-a250c480-0f4e-11eb-81d8-05a87e7415a7.gif)

**Comment by K0rrid0r** [comment]
and another one

![crash 1 opening up preset that normally works 11](https://user-images.githubusercontent.com/56724286/96196133-f065c800-0f4e-11eb-83db-df7283de532c.gif)
![crash 1 opening up preset that normally works 12](https://user-images.githubusercontent.com/56724286/96196136-f22f8b80-0f4e-11eb-93fa-d20b4a5fe6fa.gif)

**Comment by K0rrid0r** [comment]
jumping from this preset to another really unspecial preset.

![crash 1 opening up preset that normally works 13](https://user-images.githubusercontent.com/56724286/96196489-c4971200-0f4f-11eb-9330-44b3b578b57a.gif)

![crash 1 opening up preset that normally works 14](https://user-images.githubusercontent.com/56724286/96196539-ebeddf00-0f4f-11eb-976e-1848fd8764d7.gif)

![crash 1 opening up preset that normally works 15](https://user-images.githubusercontent.com/56724286/96196548-ee503900-0f4f-11eb-83b6-44435e345468.gif)

**Comment by K0rrid0r** [comment]
![crash 1 opening up preset that normally works 16](https://user-images.githubusercontent.com/56724286/96199221-4f2f3f80-0f57-11eb-876c-41503654ac8a.gif)
![crash 1 opening up preset that normally works 17](https://user-images.githubusercontent.com/56724286/96199231-50f90300-0f57-11eb-97a5-b3cb986852ce.gif)

**Comment by K0rrid0r** [comment]
![crash 1 opening up preset that normally works 18](https://user-images.githubusercontent.com/56724286/96199396-a9c89b80-0f57-11eb-8c5b-2568f457103a.gif)
woo.. never seen this error before..

**Comment by K0rrid0r** [comment]
![crash 1 opening up preset that normally works 19](https://user-images.githubusercontent.com/56724286/96199476-e0061b00-0f57-11eb-98e4-2c589835ee71.gif)
another one??

**Comment by baconpaul** [comment]
<img width="792" alt="Screen Shot 2020-10-15 at 8 57 07 PM" src="https://user-images.githubusercontent.com/13387561/96200854-06609200-0f29-11eb-87ed-edba1979c617.png">

My current smoking gun is this one which shows non-ui-thread code in the VST2 rebuilding UIs.

My theory is that the updateDisplay in SurgeSynthesizer around line 949 is not thread safe appropriate from the audio thread; and my current code changes are not thread safe (because they shouldn't be because they should only run on the ui thread) and then blammo

@K0rrid0r will check this out by commenting out that line and running.
