### ISSUE TITLE
LFO presets

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2862]
Considering that MSEGs are being introduced, saving and loading presets will become quite important. We should do this at the LFO level, though. Basically we can utilize the existing LFO copy/paste feature, serialize that to XML and load/save just like FX presets or MIDI controller settings.

Mockup:

![image](https://user-images.githubusercontent.com/2393720/95993298-3cb9e680-0e2f-11eb-88cd-7e5872f237f4.png)

**Comment by mkruselj** [comment]
Here's the assets for classic and dark skin for the hamburger button.

[LFO Presets assets.zip](https://github.com/surge-synthesizer/surge/files/5379165/LFO.Presets.assets.zip)

**Comment by baconpaul** [comment]
These buttons are now in main.

**Comment by mkruselj** [comment]
Great implementation so far! One niggle found so far:

- [ ] Extend range for Amplitude slider is not serialized or recalled

**Comment by baconpaul** [comment]
Yeah i don’t think i want to put editor state in here.
The range thing is a real bug tho :)

**Comment by mkruselj** [comment]
- [ ] Loading a MSEG preset while MSEG editor is opened doesn't seem to update the position of loop markers (if they're different from current ones).
