### ISSUE TITLE
Mod Source buttons should show hover highlights immediately after clicking on them

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#2872]
**Bug Description:**
Right now, if you just click on a mod source button, it won't immediately highlight on hover. You have to move the mouse pointer a tiny bit for it to update and for the hover highlight to appear again.

**Expected Behavior:**
Mod buttons should be instantly highlighted after clicking on them (or maybe rather keep their hover highlight state after clicking), like other controls in the synth.

**Comment by baconpaul** [comment]
Oh darn it this is because a rebuild is not generating a mouse enter I bet. Thanks!
