### ISSUE TITLE
Number Fields should return to their default value when double-clicking on them

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#2873]
This one is pretty self-explanatory. Would be useful for stuff like Keytrack root note, for instance.

**Comment by baconpaul** [comment]
Oh that's a good idea yeah

**Comment by mkruselj** [comment]
Yep I was just thinking the other day why this isn't happening xD

**Comment by baconpaul** [comment]
This is the reason why

```
   if (buttons & kDoubleClick)
   {
      if (listener)
         listener->controlModifierClicked(this, kControl)
```
