### ISSUE TITLE
~/Documents/Surge could have a wavetables folder for user-generated wavetables?

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#288]
Since presets are saved to `~/Documents/Surge/subfolders` - it would only make sense to have the wavetables be saved into the same place (like subfolders of `~/Documents/Surge/wavetables` maybe?

Otherwise the user needs to go to `~/Library/Application Support/Surge/wavetables` and copy them there. not very user-friendly

**Comment by baconpaul** [comment]
The only trick is that we make categories based on parent directory and don’t recurse. We could easily have a special folder or we could just load looking for wt files anywhere also and you make too level dirs 

What do we want to directory layout to be in documents/surge basically?

**Comment by esaruoho** [comment]
wavetables/subfolders/cool.wt

Is that possible?

**Comment by baconpaul** [comment]
Well it’s code, it can do (almost) anything.

How about this

1. On startup if it doesn’t exist create doc/surge/user_wavetsbles
2. Scan that for directories containing wt
3. Modify save so a user can’t save a patch in user_wavetables

And be done

I’ll need to do #217 before that though to get the user feedback. @jsakkine here’s another spot where we need modal non throwing feedback. I will update 217 with some thoughts.

I don’t have a bunch of surge time until about Thursday is my guess. I’ll tuen to it the

**Comment by baconpaul** [comment]
Yeah that’s a smart solution but I don’t know how to get there from current layout. Here’s an alternate idea

We just walk every subdir in documents / surge. If it contains a wt that becomes a wt cat. If it contains an fxp that becomes a patch cat.

That way third parties can make a single directory containing patches and wave tables and you just drop them into documents/surge and it works

Kinda like when someone shares a Dropbox folder with PowerPoint and excel both (if that analogy resonates with you)

See what I mean?

**Comment by baconpaul** [comment]
Oh and obvious if doc/surge/baconfun contains a patch and a wavetable it shows up in the patch menus and the wavetable menus

**Comment by baconpaul** [comment]
Ok so here is the code I plan to write to both add wavetables and subdir (so collapsing #283)

In documents surge do a full tree walk
If you find a .fxp in directory a/b/c the you get a patch with category name “a::b::c” where “::” is a separator defined in a constant. That way it all sorts still and all the category jogs work

At menu construction time show a::b:;c as submenus not as a flat hierarchy. In the display show a::b::c with an appropriate visual separator.

Finally if you hit a .wt do the same and show it in the wt menu

This means people can make surge packs which intermix patches and wavetables, which have names based on directory, and which group I our browsers and menus.

**Comment by baconpaul** [comment]
That rendered wrong. A::b::c is just double colon separated using double colons as an example separator.

**Comment by baconpaul** [comment]
<img width="1038" alt="screen shot 2019-01-24 at 9 12 24 pm" src="https://user-images.githubusercontent.com/13387561/51720745-d23e9280-201c-11e9-9de4-eb12df1f6052.png">

Hacking away at this for patches at least.

**Comment by baconpaul** [comment]
Huh. Save just works if you put "/" in the name (on mac at least). Will clean up and check for windows sometime soon. branch baconpaul patch-subdirs-288.

**Comment by baconpaul** [comment]
OK master now has hierarchical categories for patches. Next step is to make user wavetables from ~/D/S (or really from 'userDataPath') also work. Leaving this issue open to add that feature.

**Comment by baconpaul** [comment]
Looks like fixing #603 will fix this one too just to couple em
