### ISSUE TITLE
Zyn Resonance and Vowel filters...

### ISSUE THREAD

**Issue by CurlyMC** [surge-synthesizer/surge#2885]
Due to Zynaddsubfx resonance and vowel filters, its fun and easy to very fast sculpt a sound inside zynaddsubfx.
Seeing this once being implemented into Surge code would be another dream come true.

Resonance filter :        https://zynaddsubfx.sourceforge.io/doc_2.html#w9
Vowel Formant filter : https://zynaddsubfx.sourceforge.io/doc_2.html#w0b

**Comment by baconpaul** [comment]
Hi again!

Yes we've discussed this and very much want to do it. See #1584. 

As I mentioned on the other issue, it requires param expansion which isn't set for 1.8. Although 1.8 is gonna get a heaping helping of new filter options, they are still going to be single cutoff / single resonance and both these would require we break that.

Also the resonance filter is crazy. Kinda like an MSEG for the response curve. Nutty!

But again would love to do these kinds of things but they won't make the immediate next release for the technical reasons I mentioned (which we are working on!)

Thanks

**Comment by CurlyMC** [comment]
Thanks Paul, although I'm not a programmer of course I understand !
So... just let's skip the 1.8 and direct go to the 1.9 ? :-)
A joke of course, when I see all the 1.80 features and additions, its crazy to see what the Surge Team is creating !!!
Thank you so much !

**Comment by mkruselj** [comment]
Closing as a duplcate of #1584, basically.

**Comment by baconpaul** [comment]
Yup
