### ISSUE TITLE
Global keytrack mods: MIDI input based rather than voice based

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2892]
Currently, lowest/highest/latest key modulators take the base key value of the voice, which makes them all have the same exact value in monophonic play mode, which was not the original intention I had when implementing them.

So, they should be modified so that they use the actually received MIDI note states (off, on) in an array with 128 indices, and use that as the basis for lowest/highest/latest calculations, which would make those global keytrack modulators have distinct values even in mono mode.

Thoughts:

- Regarding MPE/multichannel MIDI - I don't think this matters here, since you'd still play a single sound, so in this case we should perhaps collapse notes from all channels into a single array
- Regarding Key Split mode - each scene would only need to care about the keyrange that was assigned to it
- Regarding Channel Split mode - tricky, this would I assume require to at least have a reference for the originating MIDI channel after all? But I don't think it would require a 128*16 array, right?

**Comment by baconpaul** [comment]
OK we already have the channel state array which contains all the on keys. That's how we do mono retriever. I think we can just use that to change the calculation here. But we should add retests for these modulators too while at it. So I will do both when I tackle this

But I don't think we need a new data structure. Just a different method to calculate the key in mono mode.

Can get it before we go to beta along with the new voice modes also. Will do the voice modes first tho.

**Comment by baconpaul** [comment]
Super important to test MPE Channel Split and Non-MPE key split modes when we do this too.

A key split at 60 means that note 65 should set the highest modulator in scene b but not scene a (or vice versa you know what i mean).
