### ISSUE TITLE
Surge VST3 Fails to Load in Waveform 11 Linux

### ISSUE THREAD

**Issue by Paree24** [surge-synthesizer/surge#2898]
**Bug Description:**
Surge vst3 fails to load in waveform 11 during plugin scanning [i.e, doesn't get scanned]. It detects it as a plugin but it fails to load. I experienced it even with 1.6.6 but i used to use vst2 so i didnt notice it. vst2 version of 1.7.1 installed from kxstudio repository works well. Also other vst3 plugins work well in waveform.

**Surge Version**
1.7.1

* Version:
* Plugin Type: VST3
* Bitness: 64 bit

**Reproduction Steps:**
1. Add /usr/lib/vst3 to plugin sources list
2. Scan
3. Surge fails to load correctly.

**Expected Behavior:**
The plugin should be scanned and loadable in the DAW

**Computer Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Host: Waveform 11
 - Version: 11.1.0

**Comment by mkruselj** [comment]
Man, Waveform is notoriously flakey with plugin scanning...

**Comment by baconpaul** [comment]
Well before we worry about that does waveform support vst3 on linux? As of a few months ago I know it did not. @Paree24 can you load any linux vst3 in the daw?

**Comment by mkruselj** [comment]
He does mention that other VST3 plugins work fine in it.

**Comment by baconpaul** [comment]
Oh right.

**Comment by Paree24** [comment]
yes, i am able to load vst3 from uhe just fine, i also used to load helm vst3 and it worked fine too.
https://www.kvraudio.com/forum/viewtopic.php?f=22&t=544890&sid=57d0e26619058b0ecb9c904edc68b7c8&start=15 This thread states that vst3 version of surge worked on waveform on windows (assuming because of windows only plugins mentioned).

**Comment by Paree24** [comment]
I also tested it on carla and it loads in carla

**Comment by baconpaul** [comment]
How do I get a version of waveform for linux that loads VST3? I downloaded 11.0.something from their website and it doesn't and can't seem to find 11.1.

**Comment by Paree24** [comment]
If you download waveform from thier website, it should be 11.10 because thats the latest stable version

**Comment by baconpaul** [comment]
I did that last night and got 11.0.26 in the 'free download' page using firefox. but when i dl on my mac I get 11.1. So I seem to be getting it now. Huh.

**Comment by baconpaul** [comment]
OK grabbed 11.1 and it won't load Surge, won't load our JUCE built plugin, and won't load the VST3 from the VST3SDK demo set.

I think this is a waveform problem not a surge problem.

<img width="778" alt="Screen Shot 2020-10-19 at 1 07 13 PM" src="https://user-images.githubusercontent.com/13387561/96488479-153a9380-120c-11eb-8124-9f4038857fdd.png">

**Comment by baconpaul** [comment]
Unless there is some setting I'm missing which says 'you should expect VST3s in this folder' or some such. I'm using ~/.vst3 as my folder which works fine with the other various hosts.

**Comment by Paree24** [comment]
I think it can be, however i was able to successfully load all the UHe plugins i have on it without any problem. Thanks for the support, I'll update if i find anything.

**Comment by baconpaul** [comment]
U-He doesn't use vstgui; I wonder if that is it (although our TWS also doesn't use VSTGUI)
Are the U-He VST3s folders or standalone dlls also?
Happy to interact with the waveform devs if that helps and you can get them to hop over here.

**Comment by Paree24** [comment]
They are in folders
![image](https://user-images.githubusercontent.com/37375677/96506276-fde3c080-1274-11eb-827b-d418880435f9.png)
I'd try contacting them, I'll also hover over their forums to see if anyone have faced a similar issue and have gotten a response from the dev.

**Comment by Paree24** [comment]
After reading some threads, i decided to try out the latest beta version of Waveform and looks like the issue is fixed in that, Surge loads, there is some issue loading dark skin but the normal skin works fine.

**Comment by baconpaul** [comment]
Did you use highly assets before 171 dll? That’s what’s this image looks like.

**Comment by Paree24** [comment]
I dont know what highly assets is but i did try to compile vst3 version on my own before this

**Comment by baconpaul** [comment]
sorry nightly assets

The dark skin is read from the shared directory. The skin file in the nightly and the skin file in 1.7.1 have different names for colors. So if you compile yourself you need to install both the assets from resources and the dll. build-linux does this for you.

The about screen will show you which directories you are using for your assets.

**Comment by Paree24** [comment]
Got it fixed, thanks for the support and for making such as awesome open source synth.

**Comment by baconpaul** [comment]
Excellent!
