### ISSUE TITLE
Freerun LFO mode resets on note-on

### ISSUE THREAD

**Issue by unfa** [surge-synthesizer/surge#2902]
**Bug Description:**
I'm trying to get any LFO (poly or mono) to run independent from the notes played, but even in the "Freerun" mode the LFO resets with each note, just like "Keytrigger" does.

**Surge Version**
This information is found on the About screen, which you get to from the bottom right menu

* Version: 1.7.1
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Load the Init patch
2. Enable a lowpass filter
3. Assign LFO1 to the filter cutoff
4. Make LFO1 sync to BPM
5. Make LFO1 play in a whole note cycle
6. Play stacatto, and listen to the LFO cycle resetting with every note
7. Switch LFO1 from "Keytrigger" to "Freerun" mode
8. Play stacatto and hear the exact same result.

**Expected Behavior:**
"Freerun" LFO should not reset when a note is struck.

**Computer Information (please complete the following information):**
 - OS: Manjaro Linux
 - Hosts: Ardour 6.3, Carla 2.2

**Additional Information:**

**Comment by unfa** [comment]
Hmm. I suddenly can't reproduce this myself...
But I am sure it didn't work before.

Does anybody have issues with this?

**Comment by baconpaul** [comment]
This is a bug in 1.7.1 if you are not tempo synced.
It's fixed in the nightly at 4623dbbcac5a09ecd4f76ee1262866a46f4f13a5
If you are tempo synced it works.

Note for freerun to work reliably you do need transport on, otherwise the VST3 will make an artificial internal clock.

**Comment by unfa** [comment]
Allright, so this is fiddly. I'm glad I'm not imagining things :D

**Comment by baconpaul** [comment]
Nah it took us a long time to find also. Like I said it's been there forever but since most people use freerun with temposync it was "elusive". @K0rrid0r and I hunted it down a week or so ago.

You're OK if I close this issue?

**Comment by unfa** [comment]
Yeah, sure! Thanks! I must have had Temposync disabled when it didn't work...

**Comment by baconpaul** [comment]
Great. And of course since it's fixed in the nightly, the 1.8 release (scheduled we think for Jan) will have the total fix. Along with a pile of other new things.
