### ISSUE TITLE
Deform result isn't the same in MSEG compared to other LFO types

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#2912]
**Bug Description:**
The Deform parameter doesn't affect the MSEG curvature the same way it does for other shapes. Here's what I mean:

I drew a saw shape in the MSEG. Here's the result with Deform to -100%:

![image](https://user-images.githubusercontent.com/50145178/96473857-21b8ef00-1200-11eb-8f00-fcb1e2a341bb.png)

Here's the Saw LFO type with deform to -100%: 

![image](https://user-images.githubusercontent.com/50145178/96473774-09e16b00-1200-11eb-8046-2dda9a367532.png)

**Comment by baconpaul** [comment]
Yup different formulae
I will update mseg

```
   float a = 0.5f * limit_range( localcopy[ideform].f, -3.f, 3.f );

   x = x - a * x * x + a;
   x = x - a * x * x + a; // do twice for extra pleasure
```

is what the LFO uses and that's not what the line uses. Will fix with my CP rework.

**Comment by mkruselj** [comment]
E X T R A  P L E A S U R E
