### ISSUE TITLE
Different deform modes (or curves) options for modulators

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#2914]
After I saw that deform result in the MSEG was different than in other modulators ( see #2912 ), I was thinking that it wasn't inherently a bad curve by itself, though it would be more consistent to make it behave the same way as other modulation types.

That being said, if Deform was consistent on all modulation types, I thought it would be a good idea to being able to choose different deform curve types in the Deform parameter's context menu (a bit like the options for Portamento we have right now, for instance). This would apply for all LFO types in that modulator, including the MSEG.

I think I might be able to work on this, at least eventually...

**Comment by mkruselj** [comment]
Well, different LFO types already have different deforms (i.e. square has pulsewidth, noise and S&H have two different methods of smoothing, etc.).

But yes, why not!

**Comment by K0rrid0r** [comment]
i think that's a VERY cool idea!
