### ISSUE TITLE
When MSEG window is open moving around amongst the LFO shapes is extremely slow

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2919]
When MSEG window is open, moving around amongst the LFO shapes feel extremely slow compared to when the window is closed. After bisect i notice It has been like this all the time, didn't notice until now.

![248](https://user-images.githubusercontent.com/56724286/96518407-236bcc80-126b-11eb-89b8-3c12ea4c10af.gif)
Just try this test and feel the difference in the speed of selection.

Version 1.8.main.1fad58e4 (Intel 32-bit Windows VST2 (unsupported) in Image-Line Fruity Wrapper. Built 2020-10-20 at 00:05:25 on local host 'KORRIDOR')

Version 1.8.main.1fad58e4 (Intel 32-bit Windows VST3 in Fruity Wrapper. Built 2020-10-20 at 00:05:25 on local host 'KORRIDOR')

**Comment by baconpaul** [comment]
@K0rrid0r I just tried this mac vst2 and no problem. I think it might be related to the Win81 path crash/fix we fixed the other day. Can you reconfirm its still a live issue? Thank you.

**Comment by mkruselj** [comment]
Fixed by making MSEG editor close when choosing an LFO type other than MSEG.
