### ISSUE TITLE
Dragging any node in the MSEG past 19.00 will create crash

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2920]
![249](https://user-images.githubusercontent.com/56724286/96519645-c0c80000-126d-11eb-9bec-22aae1cb8f56.gif)
Dragging any node in the MSEG past 19.00 will create crash, i also tried do to it slow.

![MSEG CRASH](https://user-images.githubusercontent.com/56724286/96519698-d76e5700-126d-11eb-89db-51d32bdf9b61.gif)
Info from the crash debug

Version 1.8.main.1fad58e4 (Intel 32-bit Windows VST2 (unsupported) in Image-Line Fruity Wrapper. Built 2020-10-20 at 00:05:25 on local host 'KORRIDOR')

**Comment by baconpaul** [comment]
Oh ha ha this is the density code colliding with the phase > 20. Great find I will add this to my tomorrow list
