### ISSUE TITLE
Closing down surge with MSEG window still open will crash

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2925]
Closing down surge with MSEG window still open will crash
![257](https://user-images.githubusercontent.com/56724286/96594628-1f7f8f00-12eb-11eb-8b74-4d0831ea458d.gif)

Info from debug
![258](https://user-images.githubusercontent.com/56724286/96594645-24dcd980-12eb-11eb-8f17-788ffb793630.gif)

Version 1.8.main.7e2a5a83 (Intel 32-bit Windows VST2 (unsupported) in Image-Line Fruity Wrapper. Built 2020-10-20 at 15:17:42 on local host 'KORRIDOR')

same for
Version 1.8.main.7e2a5a83 (Intel 32-bit Windows VST3 in Fruity Wrapper - DEBUG BUILD. Built 2020-10-20 at 15:33:13 on local host 'KORRIDOR')

**Comment by baconpaul** [comment]
Ahh yeah see the same in the AU here. Thanks!

**Comment by K0rrid0r** [comment]
this crash still appears with the same debug info

**Comment by K0rrid0r** [comment]
![261](https://user-images.githubusercontent.com/56724286/96638640-bf0b4480-1320-11eb-94e9-05e6182f9206.gif)

**Comment by baconpaul** [comment]
OK I'll look again

**Comment by K0rrid0r** [comment]
![263 MSEG closing error 1](https://user-images.githubusercontent.com/56724286/96639812-879d9780-1322-11eb-9b4a-9f6d0633cc97.gif)
opening/closing the MSEG via the shape button does not create a crash

![263 MSEG closing error 2](https://user-images.githubusercontent.com/56724286/96639857-997f3a80-1322-11eb-9b7f-fe98a65b24a2.gif)
opening/closing the MSEG via the edit button does not create a crash

![263 MSEG closing error 3](https://user-images.githubusercontent.com/56724286/96639890-a1d77580-1322-11eb-81f1-e1ff9018e64d.gif)
opening/closing the MSEG via the edit button but closing it via the 'close' button creates a crash

**Comment by K0rrid0r** [comment]
![263 MSEG closing error 4](https://user-images.githubusercontent.com/56724286/96640026-db0fe580-1322-11eb-9836-07414594d71b.gif)
now i got this error message via opening the MSEG via the shape button? first time..

![263 MSEG closing error 44](https://user-images.githubusercontent.com/56724286/96640140-07c3fd00-1323-11eb-9708-93e349a52d6e.gif)

finally some debug info

**Comment by K0rrid0r** [comment]
and now i cant open the MSEG via shape button anymore?? wierd..

**Comment by baconpaul** [comment]
Can you just do a totally clean build to make sure it's not that?

**Comment by baconpaul** [comment]
And also going up one stack in that trace would help
It might also be that the patch you are loading is streamed incorrectly from looking at that stack?

**Comment by K0rrid0r** [comment]
i actually did a wholly new surge folder yesterday and downloaded everything again. 

and the patch is just init.

**Comment by K0rrid0r** [comment]
right ok.. the debug build of surge vst2 don't show MSEG 1 once opened. 

the nightly build with same hash show MSEG 1 once surge is opened.

so i reported two problems here. sorry about that, but just discovering these things here right now heh..

**Comment by K0rrid0r** [comment]
after bisect i find that these crashes begin with hash a1a86871
https://github.com/surge-synthesizer/surge/commit/a1a86871a6918ee5357d2b6b1e7fe607b27cecf4
