### ISSUE TITLE
FX Mod and replace Runtime ERROR of Death!

### ISSUE THREAD

**Issue by viceverser** [surge-synthesizer/surge#2948]
**Bug Description:**
Hard crash of death in Reaper.

**Surge Version**

* Version: Surge Nightly VST3i Version 1.8.nightly.8f87dd9 (Intel 64-bit Windows VST3 in REAPER. Built 2020-10-22 at 22:45:49 on pipeline host 'WIN-DKD9KECGJQS')
* Plugin Type: VST3i
* Bitness: x64

**Reproduction Steps:**
1. insert phaser FX, 
2. Use S-LFO1 to modulate the 'mix' on phaser, 
3. select airwindows to replace the phaser from FX drop down
4. Cry that your unsaved session just evaporated as a sacrifice to the Production Gods of Valhalla

**Expected Behavior:**
Replacement of FX slot and clearing of any Mod attached to removed FX.

**Computer Information (please complete the following information):**
 - OS: Windows 10
 - Host: Reaper 6.14
 - Version: 6.14

**Additional Information:**
Nightlies be Nightlies :)

**Comment by mvf** [comment]
Mea culpa! m(_ _)m
