### ISSUE TITLE
orange boxes and the text therein

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#295]
@baconpaul requested i post a ticket about this (instead of just posting it on #design on slack), so here it is:

"kinda looks like the text is right at the bottom corner of the orange boxes, which makes them feel like they're bugging just a bit"
<img width="161" alt="fullscreen_13_01_2019__17_45" src="https://user-images.githubusercontent.com/4966687/51089384-e8bf3100-1774-11e9-85c7-dbdd750ae41c.png">

and
![text going above orange box](https://user-images.githubusercontent.com/4966687/51089390-efe63f00-1774-11e9-915f-ae8addca5ebf.gif)

**Comment by itsmedavep** [comment]
Ive fixed these in the buttons now.
![bmp00161](https://user-images.githubusercontent.com/11078351/51094906-5ddf3600-1776-11e9-8bb7-076eb8baaa4f.png)

Im off for the night but, Ill get a PR pulled together for this in the AM.

**Comment by baconpaul** [comment]
In fact you can see that in this screenshot, it is aligned at the drop point (the bottom of the p) not the baseline (the bottom of the m). But that font looks a pt or two too big for that display area I think is the real problem.

**Comment by baconpaul** [comment]
that's lucida grande 9 on mac; and microsoft sans serif 9 on windows

getting a similar screenshot from prod on windows would be great.

**Comment by esaruoho** [comment]
@itsmedavep hi, looks like these could be a bit more related to eachother - what i'm getting at is that now the sine+triangle+square+ramp+noise+s&h+envelope+stepseq orange looks like it's "lower" in the "box area" than keytrigger+freerun+random.
(i.e. feels like the orange box is "align to bottom" rather than "align to center". dunno if that makes sense.

<img width="947" alt="fullscreen_15_01_2019__0_52" src="https://user-images.githubusercontent.com/4966687/51146664-2947a900-1860-11e9-85a2-597844a63582.png">

**Comment by baconpaul** [comment]
The orange box hasn't moved; that is painted with code in explicit coordinates. If you see that it means the gray area has shifted "up"

**Comment by itsmedavep** [comment]
> The orange box hasn't moved; that is painted with code in explicit coordinates. If you see that it means the gray area has shifted "up"


Yup. The orange didn't move but I must have managed to nudge the box somehow. Ill fix this up!

Sorry I introduced this BTW.

**Comment by sense-amr** [comment]
windows version here.. 
as requested by @esaruoho 

![win10_64_ramp_vst2](https://user-images.githubusercontent.com/1504019/51184856-a2f79980-1929-11e9-9c87-62f79cffbd00.jpg)

**Comment by baconpaul** [comment]
OK I have a few tweaks to the code which get us here, which I think is good enough until we can address #214. I'll do a PR shortly.

<img width="973" alt="screen shot 2019-01-18 at 5 05 48 pm" src="https://user-images.githubusercontent.com/13387561/51415291-54254c00-1b43-11e9-9c36-d9489c6f20f6.png">

**Comment by baconpaul** [comment]
So if you guys want to try that PR out and let me know, I think it makes things "better" and verging on "correct". It's not a pretty diff (any diff which contains "+= 1.6 is not great) but it does what we need for now so we can close this issue.

**Comment by baconpaul** [comment]
I think. Appreciate your input
