### ISSUE TITLE
LFO display looks aliased and "pixely"

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#2989]
Since a couple of days, LFO Display waveform has a slightly weird aliasing look (bolder, brighter and more pixely) when it updates.

- Right after opening the GUI of the plugin it's fine.
- It starts doing it after tweaking Rate, Phase, Deform, and Amplitude.
- Hovering your mouse over the display fixes it, until you mess with those parameters again.
- It doesn't do it when tweaking the LFO envelope.

I'm not sure exactly since what build it started doing it, but I can do more testing if needed.

![LFO](https://user-images.githubusercontent.com/50145178/97381576-bf1abf80-189f-11eb-9d25-b3781ac3f1f2.gif)

Hope it's not too hard to see. Don't mind the background of the LFO display, that's just GIF artifacts.

**Comment by baconpaul** [comment]
wonder if it is the cliprect change

**Comment by mkruselj** [comment]
Possibly related:

![msegweird](https://user-images.githubusercontent.com/2393720/97441654-3ea0a100-1929-11eb-82fd-1d5498ec8d96.gif)

**Comment by baconpaul** [comment]
Sigh
I wonder if VSTGUI cliprect on windows does something wrong, like mis-integralize or some such.

If you comment out CLFOGui.cpp line 377 and 380 (the two calls to setClipRect) does the problem go away?

If so we will just back out the cliprect.

**Comment by mkruselj** [comment]
Commenting out those two lines doesn't fix the thing I'm showing in my GIF, at the very least.

**Comment by mkruselj** [comment]
@VincyZed Check out latest nightly (e023b13) and see if it helps any!

**Comment by VincyZed** [comment]
@mkruselj Yes, that fixed it! Thanks.
