### ISSUE TITLE
CSurgeHyperlink

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3003]
So CSurgeHyperlink
setURL()
setFont()
setImage()
setText( const std::string &t )
setTextWithPartialLink( std::vector<std::pair<std::string,bool>> &)
type thing
the last one you call with {{"This is my "  false }, { "link", true ), {"in the middle", false }}
and you get this is my link in the middle
modulo syntax
that's what we need right?

**Comment by mkruselj** [comment]
👍

**Comment by mkruselj** [comment]
Doesn't yet support the partial text + link + text stuff, right?

**Comment by baconpaul** [comment]
THat's right but we didn't need that. So I'll close this and add an issue if we do!
