### ISSUE TITLE
Add indirection for filter type menu list, and group filter types in folders

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3006]
Since we're getting more and more filters, it would make sense to have them in a more sensible order than "new shiz is on the bottom". So gotta indirect that! Here's the suggested order:

Lowpass 12 dB/oct
Lowpass 24 dB/oct
Lowpass Sallen-Key
Legacy Ladder
Vintage Ladder
Diode Ladder
OB-Xd Ladder (renamed from OB-Xd 24 dB/oct)
Highpass 12 dB/oct
Highpass 24 dB/oct
Highpass Sallen-Key
Bandpass (in 1.9 split it to 12 dB/oct and 24 dB/oct!)
Notch
OB-Xd Multimode (renamed from OB-Xd 12 dB/oct)
Comb
Sample&Hold

Same order should be used by the draggable glyph, of course.

**Comment by mkruselj** [comment]
Since the list of filter types grew, and it seems like it will continue growing based on @selenologist's efforts (and possibly at some point @amyfurniss too), it makes it a good idea to categorize filter types into subfolders. To do so, we should also make a breaking change in the current OB-Xd implementation which is almost entirely based in subtypes (for the 2-pole).

Here is the suggested list of folders:

LOWPASS
    12 dB/oct
    24 dB/oct
    K35
    Legacy Ladder
    Vintage Ladder
    Diode Ladder
    OB-Xd 12 dB/oct (split the current OB-Xd 12 dB/oct into 4 filter types with 2 subtypes each)
    OB-Xd 24 dB/oct
    Non-linear Feedback
BANDPASS
    12 dB/oct
    24 dB/oct (split the current bandpass into two filter types with 3 subtypes each)
    OB-Xd 12 dB/oct
    Non-linear Feedback (if @selenologist manages to plug those BP biquad coeffs into the current NLF filter implementation)
HIGHPASS
    12 dB/oct
    24 dB/oct
    K35
    OB-Xd 12 dB/oct
    Non-linear Feedback
NOTCH
    12 dB/oct
    24 dB/oct (split the current notch into two filter types with 2 subtypes each)
    OB-Xd 12 dB/oct
    Non-linear Feedback
SPECIAL
    Comb
    S&H


The above list, but flattened, would be the indirection list for the draggable filter glyph, too.

**Comment by baconpaul** [comment]
I prefer “LP Vintage Ladder” as the display

**Comment by mkruselj** [comment]
Yep same. I'd still like to shorten "Non-linear Feedback" though in a way that doesn't introduce another acronym ("NL Feedback")...

**Comment by TheNerdyMusicGuy** [comment]
Yeah, I would change the name to something else too. To end users, the word "non-linear" often simply implies that it's "better", or more negatively, the other filters somehow worse.

**Comment by baconpaul** [comment]
The vintage ladder has both non-linearity and feedback in it, for instance. Names are hard but yeah a better one here. “Multi-stage Feedback” perhaps?

**Comment by selenologist** [comment]
The reason it's called "Nonlinear Feedback" is because the nonlinearity is literally *in the feedback* of the biquad. It's a literal description of what's going on. "Multi-stage feedback" implies there's some kind of multiple feedback, but there's not, the stages are separate. And feedback itself isn't special here, all our filters have feedback like this, just here it has a nonlinearity.

Blah fine maybe I'll give in and call it "warble" but ._.

> To end users, the word "non-linear" often simply implies that it's "better", or more negatively, the other filters somehow worse.

I don't see a problem with this ;). Seriously though, I don't really think people think that. Especially not that it implies the other filters are worse.
