### ISSUE TITLE
Value tooltip sometimes pops up after reset of another control when it shouldn't

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#3023]
Here's a very minor bug that I just found. Hard to explain using words, so here's a GIF demonstrating it:

![popup](https://user-images.githubusercontent.com/50145178/97790210-128d5600-1b9d-11eb-82ef-cb7be7715a14.gif)

There shouldn't be any Scene Octave tooltip appearing.

**Comment by baconpaul** [comment]
Oh this is the “deal with knopopup” item on my list ... good find

**Comment by baconpaul** [comment]
I am completely unable to reproduce this at the head of the code on either windows or mac, even if I set the info window countdown to something massive. @VincyZed can you still do it? If so how are you getting it to happen?

**Comment by mkruselj** [comment]
@baconpaul I can get this no problem... Second click is what matters. So you first click on a slider and popup goes away quickly, but then click on it again and it sticks around for longer and then the above issue crops up if you i.e. change filter type with mousewheel.

![sticky](https://user-images.githubusercontent.com/2393720/101671045-45582300-3a54-11eb-9828-18260ea8577f.gif)

**Comment by baconpaul** [comment]
OK I see a code path where this could happen even though I can't make it happen (even if I set the info window countdown super duper high). Will try in windows again.

**Comment by baconpaul** [comment]
Yeah OK super useful. Have it trapped on windows. Will be able to get it now

**Comment by baconpaul** [comment]
got it
