### ISSUE TITLE
Blip at start of notes with keytrack modulating wavetable morph

### ISSUE THREAD

**Issue by fgimian** [surge-synthesizer/surge#3046]
**Bug Description:**
When assigning Keytrack -> Wavetable Morph, higher notes have a clearly audible blip at the start of them (seemingly due to interpolation).  However other synths like Hive, Zebra and Serum don't do this, they start at the appropriate wavetable position based on the note without the little blip.

**Surge Version**

* Version: 1.7.1.5270cfb
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Set Oscillator 1 to WT and choose the Basic / Sine wavetable
2. Click the Keytrack target and assign it to the max amount against Oscillator 1 Morph
3. Play notes above middle C, especially audible 1 and 2 octaves above middle C
4. Note that the start of the note has a little blip

**Expected Behavior:**
Notes should start at the appropriate wavetable position without this blip.

**Computer Information (please complete the following information):**
 - OS: Windows 10
 - Host: Cubase Pro
 - Version: 10.5.20

**Additional Information:**
Here's a sample preset based on the instructions above
[Wavetable Problem.zip](https://github.com/surge-synthesizer/surge/files/5487219/Wavetable.Problem.zip)

And here's a sample using the wavetable which I was using to produce my sound
[SE Wavetable Problem.zip](https://github.com/surge-synthesizer/surge/files/5487222/SE.Wavetable.Problem.zip)

The goal is to obtain a sound similar to this (rendered using u-he Hive with the same wavetable and some processing).

[Solo Voice Demo.zip](https://github.com/surge-synthesizer/surge/files/5487230/Solo.Voice.Demo.zip)

**Comment by baconpaul** [comment]
Alright! I have written a retest which does this and, as expected, yes, the keytrack modulator is blipping from 0 the the value across the block on the note inception. I think I can fix it from here.

@fgimian I used your patch as test data, and would like to add it to our test patches in the repo (they are not loadable in the synth only the regrets engine). If this is a problem please let me know.

Wonder what the fix will turn out to be. Must be an order of modulation thing.

**Comment by baconpaul** [comment]
Yeah I've found a fix to this. It's a real bug and it is due to a special treatment of keytrack in switch_toggled.

**Comment by baconpaul** [comment]
OK pushing a fix. Good find! Subtle bug.

**Comment by fgimian** [comment]
Thank you so much @baconpaul 😄
