### ISSUE TITLE
SurgePatch meaningless for loop

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3059]
https://github.com/surge-synthesizer/surge/blob/11d620bff06884401a9511c8403ee00212cc8a9b/src/common/SurgePatch.cpp#L1464

We should probably use `u` here instead of `0`, otherwise this `for` loop is for naught (pun intended)!

**Comment by baconpaul** [comment]
I cannot for the life of me see why this is a [0] rather than a [u] so I will change it. Odd.
