### ISSUE TITLE
IComponentHandler::restartComponent is not called by the VST 3 version of Surge when using the menu to change preset

### ISSUE THREAD

**Issue by NickJAllen** [surge-synthesizer/surge#3066]
**Bug Description:**
When changing presets using the preset menu in the plugin window of Surge the host is not notified that parameter values have changed due to the loading of the preset.

**Surge Version**

* Version: 1.7.1.5270cfb
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Open surge window (eg from Bitwig Studio using the plugin window button on the device header)
2. Click on the patch browser to show the preset browser menu
3. Select one of the presets

The parameter values update in Surge GUI but it never tells the host they have changed with a call to restartComponent with a flag like kParamValuesChanged set. This means the values do not get refreshed in the host and stay at the old values.

**Expected Behavior:**
restartComponent will be called to tell the host the values have changes

**Screenshots:**

**Computer Information (please complete the following information):**
 - OS: Linux  (I expect others too but don't have machine to test on to confirm)
 - Host: Bitwig Studio
 - Version: 3.2.8

**Additional Information:**

**Comment by baconpaul** [comment]
Hi,

Yup 171;doesn’t do this. https://github.com/surge-synthesizer/surge/commit/8939838f45cec137946adccfdf4f4eff7a441dcf#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26 And a couple of prior commits fix this in the nightly which should become 1.8.0 in Jan 21.

**Comment by baconpaul** [comment]
And I just confirmed the path that leads to that call being activated is set by the patch reload path (even when toggling between two patches which are identical other than name) so I'm going to close this issue.

Thanks for the report!
