### ISSUE TITLE
Plugin crashes when opening preset browser

### ISSUE THREAD

**Issue by ItzShittyPaper** [surge-synthesizer/surge#3067]
**Bug Description:**

* Version: Stable 1.7.1
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Open Plugin window
2. Click on "Init" preset to open preset browser
3. Plugin Crashes

**Expected Behavior:**
VST works as expected, user can browse presets in menu.

**Computer Information (please complete the following information):**
 - OS: Pop_OS! 20.04
 - Host: Bitwig Studio
 - Version: 3.1.2

**Additional Information:**
Choosing anything in "Menu" button crashes plugin too

**Comment by mkruselj** [comment]
Is Zenity installed?

**Comment by baconpaul** [comment]
You need at least bitwig 3.2.0 for surge vst3 to work on linux. If you use bitwig newer than 3.2.5 you need to run surge in process not a sandbox. Surge vst3 does not work reliably in linux birwig 3.1
