### ISSUE TITLE
Plug-In Crashes when closing GUI [Bitwig, Linux, VST3]

### ISSUE THREAD

**Issue by TheWaveWarden** [surge-synthesizer/surge#3075]
**Bug Description:**
When closing Surge plugin editor, either via the native close button on the window, or Bitwig's close button, the plug-in crashes.

**Surge Version**
* Version: 1.7.1.5270cfb
* Plugin Type: VST3
* Bitness: 64

**Reproduction Steps:**
1. Add plugin
2. Open editor
3. Close editor

**Computer Information (please complete the following information):**
 - OS: Ubuntu 18.04 (tested with Gnome and i3 WM)
 - Host: Bitwig
 - Version: 3.2.8

**Comment by mkruselj** [comment]
See #faq channel on Discord :)

**Comment by TheWaveWarden** [comment]
Ah, I see. Thanks!
