### ISSUE TITLE
Note off applied to wrong channel

### ISSUE THREAD

**Issue by Nyle** [surge-synthesizer/surge#3084]
**Bug Description:**
When using with an MPE controller that allows one note to be played separately multiple times on different MIDI channels, if a note is pressed and held (press 1) on one channel and then the same note is pressed and released (press 2) on a second channel before releasing press 1, the press 2 release will turn off press 1, and the press 1 release will do nothing, leaving the note from press 2 sounding until that note is pressed and released again on the same channel that press 2 was on. This occurs regardless of if MPE is enabled or disabled.

**Surge Version**
* Version: 1.7.1.5270cfb
* Plugin Type: AU
* Bitness: 64

**Reproduction Steps:**
1. Send a note on message for some note (eg. note_on channel=1 note=60)
2. Send a note on message for the same note on a different channel (eg. note_on channel=2 note=60)
3. Send a note off message for the note on the second channel (eg. note_off channel=2 note=60). This will turn off the note on channel 1
4. Send a note off message for the note on on the first channel (eg. note_off channel=1 note=60). This doesn't seem to do anything, leaving the note sounding on channel 2

**Expected Behavior:**
Note off messages should apply to the specified channel, and only to that channel

**Computer Information (please complete the following information):**
 - OS: macOS 10.15.7
 - Host: Garage Band
 - Version: 10.3.5

**Comment by baconpaul** [comment]
Oh ha thanks. Guess you did this with a Linnstrument right.
We can work on repro but if you happen to have a std midi or Gb file which shows it and attach here as zip that’d be welcome 
Especially are you in poly or mono mode in surge would be handy to know

**Comment by Nyle** [comment]
With a Sensel Morph and custom midi output script to do some stuff with it that isn't supported with their overlay editor.

It looks like it happens in poly, mono, and mono fp, but not in mono st, mono st+fp, or latch.

I _believe_ this should reproduce the issue, but don't have any easy way set up to directly play it into Surge at the moment so haven't been able to verify that:
[example.mid.zip](https://github.com/surge-synthesizer/surge/files/5507334/example.mid.zip)
For reference, here's the python script I used to generate that:
```
#!/usr/bin/env python3

import mido

if __name__ == '__main__':
    f = mido.MidiFile(type=0)
    track = mido.MidiTrack()
    f.tracks.append(track)
    t = int(mido.second2tick(1, f.ticks_per_beat, mido.bpm2tempo(120)))
    for msg in [mido.Message('note_on', channel=1, note=60, time=t),
                mido.Message('note_on', channel=2, note=60, time=t),
                mido.Message('note_off', channel=2, note=60, time=t),
                mido.Message('note_off', channel=1, note=60, time=t)]:
        track.append(msg)
    f.save('example.mid')
```
And here's a similar script to directly output the same midi, which I have been able to confirm will reproduce it:
```
#!/usr/bin/env python3

import mido
import time

if __name__ == '__main__':
    with mido.open_output('demo', virtual=True, autoreset=True) as port:
        for msg in [mido.Message('note_on', channel=1, note=60),
                    mido.Message('note_on', channel=2, note=60),
                    mido.Message('note_off', channel=2, note=60),
                    mido.Message('note_off', channel=1, note=60)]:
            time.sleep(1)
            port.send(msg)
```

**Comment by baconpaul** [comment]
Gotcha. I was going to do exactly the same thing, just in our C++ test harness :)

OK Thanks! We've tagged this for 1.8 which means it will definitely be addressed before the next production release.

**Comment by baconpaul** [comment]
So I have a suspicion the problem here may relate to GB.

I wrote an assertive regrets that tries exactly your scenario (see the PR and diff above) and all the tests are correct. Voice 2 release untriggers voice 2 note. So then I thought perhaps a bug in the AU (but was dubious since I play it a lot) so fired up logic and made a one measure where there were two instances of note 60 on channel 1 and 2 with a big wobble which grew so you know which one would release. And fine. The channel 2 note released also.

So then I tried to make GB do it and couldn't for the life of me figure out how to edit a notes midi channel in GB or see the midi from the app or change a notes channel. 

So I wonder if the problem here is GB doing some clever midi compression for you or something? Could you provide any more details on this problem? I can't get anything close to it in the nightly (and we haven't changed voice management since 1.7.1)

Thanks!

**Comment by mkruselj** [comment]
I cannot confirm this in Reaper either. I agree with @baconpaul that this is probably GarageBand screwing things up.

**Comment by baconpaul** [comment]
OK @Nyle can you try any other DAW with MPE support here? Or provide us some more details? 

I've tagged this issue Awaiting User Information and knocked it from our 18 milestone into the currently unscheduled milestone for now, while we gather more details.

**Comment by Nyle** [comment]
Yeah, looks like it is a Garage Band issue. After some more playing around with it, it looks like the issue is only occurring for one specific track in one specific project, and was able to reproduce the issue there with the Dexed synth as well. Changing that track to one of the build in instruments (or at least the few different ones I've tried) and back seems to "fix" things as well. I've attached a zip of the [problematic garage band project file](https://github.com/surge-synthesizer/surge/files/5563679/MPE-Issue.zip) of for reference. Off to figure out how to report this to Apple…

**Comment by baconpaul** [comment]
Ha yeah I actually added the MPE voice management in dexed also so glad it behaves consistently :)

I’ll take a look at the GB file and see if I can figure out what its doing. Will push this back into 18 so at least I can give you a more concise debugging output from the synth for your report. Thanks for the attachment.

**Comment by baconpaul** [comment]
OK when I download that GB file it contains no midi regions so not much I can do. I think this is a problem with GB though not surge so let me close this. If you need me to help you debug or diagnose though please do reopen

**Comment by Nyle** [comment]
Ah, yeah, it only seems to happen when playing midi live into GB with that specific track selected, once recorded into GB it all acts correctly. I got it reported to Apple/sent them the GB file as well, so they should hopefully be able to figure it out/fix it if they decide its worth doing so; if not just deleting the track and making a new one seems to make the issue go away so it shouldn't be too hard to deal with if it comes up again in the future.

**Comment by baconpaul** [comment]
Great. Well glad we added the regtest anyway. Thanks!,
