### ISSUE TITLE
Modulation Section Buttons in Skin Engine

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3101]
In 1.8 the modulation section can be moved en-masse but cannot be individually addressed, repositioned, or resized. So

1. Make it so you can resize or re-arrange individual buttons in the skin engine
2. Make it so they buttons are no longer a monolith

As well as the technical demands to do this (the weird shaping API and fixed things in the C++ in 1.8) this will require some more convenient skin engine syntax than just having 29 controllers independently (like some form of grid expression).

**Comment by mkruselj** [comment]
XT2.0 will have a different way to go about modbutton area. Closing this one since it won't be done in this way.
