### ISSUE TITLE
Skin label color argument support for RRGGBBAA format

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3108]
Currently, `getColor` allows us to parse a skin XML-defined named color and get VSTGUI CColor to colorize our skin-generated text label. RRGGBB(AA) color assignment doesn't work, but we should support it because we're nice like that!

**Comment by baconpaul** [comment]
Amounts to refactor the hex to color code in global parse to a func call it thrrr still but also call it in grtcolor if you fall through the lookup and start with a # before you return default
