### ISSUE TITLE
Case insensitive bitmapstore lookup

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3109]
Currently, Surge asks for PNG/SVG skin assets by their exact name and case. i.e. hoverOn really has to be hoverOn, and not hoverON (like it happened when Hendrik and I were nitpicking around the dark skin remake).

See if this can be made case insensitive, so that Surge accepts hoveron, hoverON, HoVeroN or whatever other combination there is.

**Comment by baconpaul** [comment]
Amounts to bitmap stringid downcase on add and exit 

Can’t do for path so make sure to document path version as case sensitive while at it
