### ISSUE TITLE
FX sliders update wrongly when playing around with FX off

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#3117]
**Bug Description:**
we can end up in this state if doing in a certain way
![6](https://user-images.githubusercontent.com/56724286/98885009-85e27200-2491-11eb-920a-c2d1d5349251.gif)

or this
![7](https://user-images.githubusercontent.com/56724286/98885032-95fa5180-2491-11eb-9fc0-c3e1aa5ddc8c.gif)

**Surge Version**
Surge Synthesizer
Version:	1.8.HEAD.ec2d73c2
Build Info:	Built on 2020-11-12 at 01:51:20, using local host 'KORRIDOR'
System:	Intel CPU, Windows VST3, 32-bit  (same on VST2)
Plugin Host:	Fruity Wrapper

**Reproduction Steps:**
open up surge
choose a free random fx slot
choose any fx 
click Off
click Off again

and we have this
![8](https://user-images.githubusercontent.com/56724286/98885479-6861d800-2492-11eb-8c4e-3d760e7e60de.gif)

**Comment by baconpaul** [comment]
Yup can reproduce. Thanks!
