### ISSUE TITLE
Crackle, XRun, Overload, etc... on Patch Change

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3119]
This issue has been repurposed to generally profile patch change stuff.

-------------

Im using a Ableton, latest version on windows.  Switching presets using the patch arrows, kicks the cpu to 40 and it drops back down quick, but sometimes a preset will have a crackling noise, so i switch to a new preset, and when i go back to the previous preset, the noise is gone.  Happens often.  Gunna restart my pc to see if that helps.
NVADRYesterday at 10:27 PM
Yea this happens in cubase and reaper as well
KorridorYesterday at 10:37 PM
what about changing presets in another way?
NVADRYesterday at 10:40 PM
Nope, doesnt matter, i get crackling
Just started happening
Maybe one of the more recent nightlys?
Whatever the case, presets arent working on any daw without crackling
Tested in Live, Reaper Cubase, FL

**Comment by baconpaul** [comment]
NVADR reports this is fixed by reinstalling ASIO4ALL and stuff like that which I didn't really understand because I don't know how audio subsystem really works on windows, but which fixed it.

**Comment by inigokennedy** [comment]
@baconpaul I think there's definitely something up with the patch changes and it's causing pretty big CPU spikes. I'm seeing that with VST2 (own build) or VST3 on Windows 10 x64 with an RME Babyface Pro. Seems to be the case with Surge 1.7.n 1.8.n and 1.9.n nightly. Doesn't matter how patches are changed, arrow buttons, menu, etc. It also happens via MIDI program change with Surge GUI closed; I'm not sure if that rules out GUI redraws. In NI Maschine for example changing patches causes audio drop out glitches. In Cantabile those spikes are pretty obvious in the Profiler. I've attached an image from the Profiler, running as I change patches in Surge. One of the spikes selected and showing the numbers. I don't know how to diagnose it any deeper but does that help? Was going to raise a separate issue but found this one which seems very much like could be the same thing.

![surge cpu spikes](https://user-images.githubusercontent.com/15378640/109059842-9cc57100-76dc-11eb-8250-b3e129b5d391.png)

**Comment by baconpaul** [comment]
I wonder if somewhere along the way we dropped the allnotesoff on patch change ordering.

The fact that it happens in 1.7 though means it is not what I thought it might be but is something else.

I think ti depends quite a lot which patch you change to. But if we are running samples over the load it could be ugly so I will confirm and see what happens when i run it on my Mac under a profiler to, so reopngin this and tagging into 1.9

**Comment by inigokennedy** [comment]
It'll spike the same way even of you switch between two copies of the Init preset so I don't think it's likely to be patch specific. Just to clarify, the audio dropouts are global as an artefact of the CPU spike, not just the Surge audio stream so allnotesoff doesn't seem like the thing. Buffer size doesn't make any difference although everything else is pretty much rock solid here on the RME down to 64 samples (usually running at 128 but checked at 256 and 512 also).

**Comment by baconpaul** [comment]
Huh OK I'll look! (allNotesOff could cause Surge to calculate voices on an invalid memory state which would spike the CPU, which is why I thought of it; basically something surge is doing is causing it to suck more CPU than it should on the audio thread for you).

**Comment by baconpaul** [comment]
OK I ran surge under the mac profiler and basically just kept pressing next in init, then next in jacky/atmospheres.

About 13% of the CPU time is in draw.

<img width="848" alt="Screen Shot 2021-02-24 at 3 42 00 PM" src="https://user-images.githubusercontent.com/13387561/109063205-e69b6080-76b6-11eb-975b-e97e4d2d5957.png">


About 12% is spent loading wavetables and building mipmaps and that's about half of the time spent in ::process (I occasionally masked a keyboard note)

<img width="844" alt="Screen Shot 2021-02-24 at 3 43 06 PM" src="https://user-images.githubusercontent.com/13387561/109063303-02066b80-76b7-11eb-99e4-751ab8ec073b.png">


Interestingly the other big contribution to CPU time is process_ringout

<img width="822" alt="Screen Shot 2021-02-24 at 3 43 50 PM" src="https://user-images.githubusercontent.com/13387561/109063456-22cec100-76b7-11eb-86fc-758b43fdb5df.png">

We also spend a lot of time in threads we spin up to load the patch. There's a bunch of these

<img width="552" alt="Screen Shot 2021-02-24 at 3 45 22 PM" src="https://user-images.githubusercontent.com/13387561/109063608-5b6e9a80-76b7-11eb-96db-62c12180d2c5.png">

although that shows a very interesting potential bug. The allNotesOff is called from the loading thread and should be called instead from the audio thread before the load thread is started. So there's definitely one change to make which will at least fix the ringout problem and maybe others.

And more to investigate: The away thread calls the loadWT and the mipmap; so why are we seeing that time on the audio thread too? What's not carrying across?

<img width="720" alt="Screen Shot 2021-02-24 at 3 47 01 PM" src="https://user-images.githubusercontent.com/13387561/109063781-95d83780-76b7-11eb-84bf-5fdba414c8d7.png">

But more to explore here. Between that wrong note all notes off and audio thread load wt there's definitely something a bit odd in these results.

**Comment by baconpaul** [comment]
bet that allNotesOff should be around line 3348 of SrSyn.cpp right before the haltEngine = true when we spawn the thread. That will almost definitely help (at least it will kill the FX).

The WT loading is a mystery tho. Huh. Interesting.

**Comment by baconpaul** [comment]
Ha whoa there's a nasty bug in surge regarding initialization and loading that this profile made me find. Fix coming very soon which I bet will help a lot.

**Comment by baconpaul** [comment]
OK so here's what was happening

When we loaded a new patch we set all the WT's to "WT #0" then overwrote them
This means loading a patch with no wavetables would force 6 loads
We don't need to do that though (well we do need to once but not twice)
So I've changed ti so that ti doesn't force a reload if a WT is loaded

This will lead to a small behavior change; if you load a patch and swap to the WT oscillator and aren't in a fresh surge you can get a different WT. But it also takes about 30% of the time spent swapping patches off the audio thread.

**Comment by inigokennedy** [comment]
That's amazing detail and thanks for looking into it too. I'll try out a nightly build after commits are merged.

**Comment by baconpaul** [comment]
Just merged the diff. If you build yourself pull main (89b5e6f); if you download nightlies the pipelines are a bit backed up so may take a bit.

**Comment by inigokennedy** [comment]
I build from main as a rule (largely to keep VST2 alive for Maschine). Just tried a fresh build and the behaviour is way better. The spikes are definitely WT related. No spikes/glitches now when changing between most presets where it was before. There are spikes when WT's are involved.

I did see an error just now when switching between some presets that I've never seen before; unsure if it's related.

![error](https://user-images.githubusercontent.com/15378640/109074166-4e6d9d80-76ef-11eb-9e30-842282249211.png)

**Comment by baconpaul** [comment]
So with 18 we do deferred loads and if you queue up a lot of them it can lag. I should upgrade that threshold to pop a warning though. If you just wail on the next patch button you can get it though since the wavetable loads queue up off thread. 

But even though the cpu will be a bit high it should not be high on the audio thread now - do you have a. Way to measure that? If not I can get the linux folks to look for xruns

**Comment by inigokennedy** [comment]
Sadly I don't have any way (expertise) to profile the CPU. Similar spikes seem to be when patches trigger WT loads (possibly unloads in some cases?) - that sounds exactly what to expect given the changes re parsimony but I can't tell what threads they'll be associated with. Those spikes cause audio glitches in Maschine (and Cantabile) still but those glitches are far less frequent as most patch changes don't cause the spikes any more.

**Comment by K0rrid0r** [comment]
@baconpaul remember i saw the same error as @inigokennedy in this issue switching presets.

https://github.com/surge-synthesizer/surge/issues/2860

switching presets can now be done flawlessly in VST2 at least, can even midi modulate presets superfast, that used to crash, not anymore.

**Comment by baconpaul** [comment]
Ok I’ll keep this issue open an look again. Basically as long as surge doesn’t run on the audio thread and you have a machine with proper threading support (any cpu in last decade or so) it should be much better now and glad to hear it is. There may still be a mis lock somewhere though.

**Comment by baconpaul** [comment]
Ha OK I found the last place where we were still mis-loading a wavetable on the audio thread at patch change and have a fix for it. With that I'll close this issue. In my MacBook I can page across all the jacky atmospheres and I see only ringout processing in the profiler.

**Comment by inigokennedy** [comment]
> Ha OK I found the last place where we were still mis-loading a wavetable on the audio thread at patch change and have a fix for it. With that I'll close this issue. In my MacBook I can page across all the jacky atmospheres and I see only ringout processing in the profiler.

Brilliant work. Thanks Paul.
