### ISSUE TITLE
Add random/chaos LFOs

### ISSUE THREAD

**Issue by Jona-D** [surge-synthesizer/surge#3124]
If possible add random/chaos LFOs as modulators. It would be really useful for sound design purposes, thank you.

An example of what i'm referring to:
https://www.youtube.com/watch?v=sRW9vffKTHE&t=134

**Comment by mkruselj** [comment]
We already have those... Please check the manual.

**Comment by baconpaul** [comment]
yeah and in 1.8 we have constant-random modulators per voice also. 
gonna close this issue. Here's the screenshot of how to get there, but as mentioned, please do check the manual! The manual is great!

<img width="637" alt="Screen Shot 2020-11-12 at 5 27 38 PM" src="https://user-images.githubusercontent.com/13387561/99003641-62a8d880-250c-11eb-9764-c94bf21b09cd.png">
