### ISSUE TITLE
Modification info window stays when double clicking on slider

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#3128]
**Bug Description:**
Modification info window stays when double clicking on slider
![skinproblem q0](https://user-images.githubusercontent.com/56724286/99009535-770ac680-2548-11eb-89bc-159f380c8724.gif)

**Surge Version**
Surge Synthesizer
Version:	1.8.HEAD.d2156792
Build Info:	Built on 2020-11-13 at 00:16:20, using local host 'KORRIDOR'
System:	Intel CPU, Windows VST2/VST3 32-bit
Plugin Host:	Image-Line Fruity Wrapper

**Reproduction Steps:**
take any slider, arm it for modification
drag it slightly
double click to reposition

modification info window stays.

**Comment by baconpaul** [comment]
Stay Forever? Or does it go away eventually?

But I’ve changed that code indeed so can peek. Thanks!

**Comment by K0rrid0r** [comment]
stay forever if i don't click on anything else yeah

**Comment by baconpaul** [comment]
Cool thanks

**Comment by baconpaul** [comment]
OK so this is ONLY the double click with modulation armed case. Not the double click with regular change case.
Lemme peek.

**Comment by K0rrid0r** [comment]
after bisect i can confirm this issue began with 

hash 81848e93 Slider Hiding Tweaks (#2942)

**Comment by K0rrid0r** [comment]
yeah only if the slider has been dragged for a modulation amount. otherwise not
