### ISSUE TITLE
"Off" label to the left of the FX arrows appears momentarily when opening the GUI

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#3129]
If you look carefully, you will see "Off" appearing for a split second then disappear right away when opening the GUI. It appears right here:

![image](https://user-images.githubusercontent.com/50145178/99013629-e79ced80-251e-11eb-8bf1-3a7d31b11353.png)

Let me know if this only happens on my side. Happy to do testing as usual.

**Comment by K0rrid0r** [comment]
also here!

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/blob/d2156792fe684ba9949b1cf373206ec34be348a5/src/common/gui/SurgeGUIEditor.cpp#L319

That should be “” not “off” I bet (but am in my phone now so can’t test)

**Comment by VincyZed** [comment]
@baconpaul Indeed, that fixed it! Does that fix mess with anything else? If not I will PR it.

**Comment by baconpaul** [comment]
Nope! It is just a remnant from when I cosplayed off for off.

**Comment by VincyZed** [comment]
OK!
