### ISSUE TITLE
Feature Request:Copy Envelope settings in LFO's to LFO and SLFO

### ISSUE THREAD

**Issue by sense-amr** [surge-synthesizer/surge#313]
The ability to copy and paste LFO/SLFO settings from one LFO/SLFO to another would be useful i think especially when working with Envelope mode in LFO

**Comment by esaruoho** [comment]
@sense-amr please edit the comment (the title is fine, but the comment is a placeholder generated by github) :) when you have the time.

**Comment by sense-amr** [comment]
The ability to copy and paste LFO/SLFO settings from one LFO/SLFO to another would be useful i think especially when working with Envelope mode in LFO

**Comment by sense-amr** [comment]
Already implemented .. and working ..
