### ISSUE TITLE
Jumpy mouse cursor in certain cases

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3139]
![jumpy_cursor](https://user-images.githubusercontent.com/2393720/99070988-9722a000-25b1-11eb-99cc-51b65ddee056.gif)

When clicking on slider tray when menu is open, cursor jumps. The other one with info window is trickier to get but also happens. Same class of issue I bet!

**Comment by baconpaul** [comment]
sigh of course this doesn't happen on mac

and of course my vm doesn't handle cursor hiding properly

will ponder

**Comment by Kingston1** [comment]
I see the issue on macOS as well, both AU and VST3.

**Comment by baconpaul** [comment]
ahh right if you click and move a pixel or whatnot it repositions you even though it doesn't drag.
need some threshold in there somewhere.
thank you for looking!

**Comment by Kingston1** [comment]
Right, on Windows actually just the click will move the cursor position, not even subpixel movement needed. So it works different to macOS and as such this isn't really a problem there.

**Comment by baconpaul** [comment]
ok!

**Comment by mkruselj** [comment]
Hmmmm I can still get this to happen (try the fast exchange of single clicks between osc drift and noise color sliders).

Maybe there should be a threshold for movement?
