### ISSUE TITLE
Separate SVG asset for tempo sync hover state

### ISSUE THREAD

**Issue by h-v-b** [surge-synthesizer/surge#3145]
**Is your feature request related to a problem? Please describe.**
The dark skin offers the option to add a resource for tempo synced slider handles. Currently the expected asset by surge does not offer a hover state for tempo synced slider handles.

**Describe the solution you'd like:**
There should be two assets expected for both horizontal and vertical sliders holding the normal, assigned, hover and hover + assigned states
![Screenshot 2020-11-13 at 21 19 58](https://user-images.githubusercontent.com/1453415/99117610-44b7a280-25f6-11eb-9482-a2b3912d5e0c.png)

**Comment by baconpaul** [comment]
Done. Will merge once CI is there.

It can be set globally with TEMPOSYNC_HORIZONTAL_HOVER_OVERLAY
and TEMPOSYNC_VERTICAL_HOVER_OVERLAY in your skin.xml or can be set on a per-class
basis with handle_temposync_hover_image in your skin.xml.

**Comment by mkruselj** [comment]
@baconpaul Will it also work with bmpTS00153/157, just using hover instead of bmp?

**Comment by baconpaul** [comment]
no
