### ISSUE TITLE
Digital waveshaper is the same as Soft in effects that use waveshapers

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3155]
![image](https://user-images.githubusercontent.com/2393720/99157262-9c720e80-26c7-11eb-8a75-f44ed0a1aa34.png)

Above we can see that basically wst_digi is the same as wst_soft. For the waveshaper inside the filter unit, this is not a problem, because QFU has separate methods to calculate these waveshaper curves that are also using SSE. However...

![image](https://user-images.githubusercontent.com/2393720/99157348-3df96000-26c8-11eb-8f44-11f914d731db.png)

Effects are using the `waveshapers` array directly. Which means anyone using Digital mode will hear the exact same thing as if they selected Soft. Which is wrong. We should fix!

**Comment by baconpaul** [comment]
So: To turn this into the same thing the filters use requires some SSE-ification and some interaction with the oversampled in distortion and stuff. More tricky than I thought. I'm going to push this to 19
