### ISSUE TITLE
Move all synth settings and presets to the Surge vst root folder

### ISSUE THREAD

**Issue by Godly75** [surge-synthesizer/surge#3160]
Would it be possible for you guys to move all the preset and setting files into 1 root surge folder that can be chosen from the setup?
I like to have all my data and synths in 1 folder, makes it easy to move and reinstall.

**Comment by mkruselj** [comment]
There is a good reason for this distinction so we won't be changing it.

You can, however, place the factory and user data folders right next to Surge dll/vst3 file and it will work. The folders need to be called SurgeData and SurgeUserData.

Note that having a lot of files in your plugin folder can and will create long plugin scans with some DAWs.

**Comment by Godly75** [comment]
Thank you for your response. I will check that out.

**Comment by mkruselj** [comment]
Alrighty! I will close this issue since we won't be changing how things are installed.
