### ISSUE TITLE
Drag Zoom Hangs in some hosts

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3202]
In testing #3201 I saw a drag to zoom of the VST3 in mac bitwig 3.1.2 beachballs.  Then also saw a similar explosion in qtractor linux.

Does it in main and in the branch in #3201 so it's not that change. But we should figure out what it is!

**Comment by Kingston1** [comment]
I saw evidence of the handleZoom/onSize callbacks possibly going into an infinite loop in some drag-resize scenarios. A possible fix  is to tighten up the float vs. int truncation used on zoomScale.

**Comment by Kingston1** [comment]
This probably can be closed. bitwig VST3 works stable in macOS, but I have no way to test qtractor linux.

**Comment by baconpaul** [comment]
Confirmed bitwig is fine
Qtractor is still borked - will take a quick look but it's also still experimental vst3 support. Will close this in either case.

**Comment by baconpaul** [comment]
Yup will open an issue over with qtractor devs - it works kinda if you grow and preserve aspect ratio but can blow up otherwise
