### ISSUE TITLE
Remaining Code Cleanup

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3204]
At the start of 1.8.2, we clang-formatted the code and made the pipeline require that format.

Some things I want to do still though:

## Remove _aligned_malloc

1. Just the Phaser and the Synth for the QFB. 

## All code has the copyright header

All .cpp and .h files have the copyright header and ideally the pipelines fail if you add one that doesn’t

**Comment by baconpaul** [comment]
```
$ clang-format --dry-run --Werror foo.cpp
foo.cpp:129:23: error: code should be clang-formatted [-Wclang-format-violations]
        if (rc <= 0) {
```

for the pipeline

Script from @Kingston1 which does the find/exec and is tested

[s.zip](https://github.com/surge-synthesizer/surge/files/5583242/s.zip)

**Comment by baconpaul** [comment]
Here's my proposed .clang-format file

```
---
BasedOnStyle: LLVM
IndentWidth: 4
---
Language: Cpp
BasedOnStyle: LLVM
IndentWidth: 4
AlignAfterOpenBracket: Align
BreakBeforeBraces: Allman
ColumnLimit: 100
SortIncludes: False
---
```

I could be talked into a lower column limit easily. Other tweaks welcomed.

**Comment by mvf** [comment]
Mostly :+1:, huge fan of pedantic CI builds. There's nothing worse than inconsistent formatting.

`.clang-format` looks good, just need to change `SortIncludes` to `false` (`False` is a syntax error over here).

This issue feels too big though. I suggest we focus on:

- Clang format
- Copyright header
- Pipeline changes to enforce the previous two
- Deletion of whole files

The others aren't really "cleanup-ey" enough IMO and should go into separate issues and commits. Moving files around in particular is messy business, so I'd hold off on that until it's time to move a file to its final location in a proper library, i.e. not `surge-shared`.

**Comment by baconpaul** [comment]
Yeah the moves are all moves inside surge-shared so I might do them (I shuffled the libraries using your pattern a bit ago so surge-shared is now actually host-type free and the actual core shared code we use everywhere) but i agree probably not one massive commit.

**Comment by mvf** [comment]
Moving files somewhat obscures history. It should be done with a clear goal in mind, and the "around", "elsewhere" and "or some such" in the cover letter suggest that there isn't one. The DSP stuff in particular is a prime target for lib-ification and unlikely to stay in `surge-shared` much longer anyway.

Where moves are warranted, **reformatting and moving must go into separate commits**. Since reformatting will change most lines, moving in the same commit will throw off Git's similarity heuristic and record as a remove+add, breaking history for these files.

**Comment by baconpaul** [comment]
An excellent point thank you

**Comment by baconpaul** [comment]
Oh and the “or some such” was just an observation that vtdsp is not even in the dsp tree and needs a clearer name. Not that there isn’t a goal. 

Hey btw I’ve been trying to reach you on discord about a license issue for filesystem which i would like to reuse but would need to be in an mit context. I domed you but let me know if there’s a better way to get in touch with details.

**Comment by mvf** [comment]
IMO the key point here is the reformatting. It would be nice if this could go in ASAP so as to not blame-bury more history than necessary. Bit surprised at all the open PRs ATM...

**Comment by baconpaul** [comment]
You should really hang on discord where we make status clear but:

we just released 180
we are going to do a 181
after that we will merge some of the PRs. not all though. the luajit one will probably not merge.
we are staging them there until 181 is out

i'm also in the middle of basically gutting the code to finally port to juce.

**Comment by baconpaul** [comment]
```
 git diff --name-only --diff-filter=MA main src/ | xargs clang-format --dry-run --Werror
```

specifically that command in the codequal check in cmake will do it for us in the pipeline

**Comment by baconpaul** [comment]
The reformatting and pipeline work is done. Keeping this open for the other stragglers

**Comment by mkruselj** [comment]
I'd also like to add: consistent filename capitalization.

globals.h -> Globals.h
resource.h -> Resource.h
unitconversion.h -> UnitConversion.h
version.h -> Version.h
guihelpers.h -> GUIHelpers.h
CSurgeVuMeter -> CSurgeVUMeter
DspUtilities -> DSPUtilities
LfoModulationSource -> LFOModulationSource
AdsrEnvelope -> ADSREnvelope
etc.

Basically CamelCase the lot, and keep all the acronyms as all caps.

**Comment by baconpaul** [comment]
oh man Version.h makes my eyes bleed. Lets think about that one a bit more carefully before we jump

**Comment by mkruselj** [comment]
Whatever, just as long as it's consistent throughout. 🙂

**Comment by baconpaul** [comment]
So after todays push I think we are all good. Closing this.
