### ISSUE TITLE
MSEG multi-node selection

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3205]
- [ ] Shift+drag in plot area creates a single rubberband selection (only nodes inside the rubberband rectangle are selected)
- [ ] Ctrl+drag in plot adds to the existing rubberband selection, non-contiguously
- [ ] Shift+clicking a node without moving it toggles adding to selection (so, if it wasn't selected now it's selected, or if it was selected then it gets unselected)

**Comment by baconpaul** [comment]
I realized that I don't know, once a note is multi selected, which operations you want to do on them. The selection is actually the easy part - something like a multi-move is a big rework of the hotzone mechanism. I may bounce this one.

**Comment by mkruselj** [comment]
Moving nodes around, changing the curve type and control point, executing actions (except those that generate new MSEGs).

**Comment by mkruselj** [comment]
Also I was thinking, if we have this multi-selection thing going, RMB context menu would only show options that are available to execute on such a selection. Either hiding the menu entries altogether or graying them out would do. Things I think should work on multi-selection:

Actions - everything except Split (distribute nodes would work within the range of first-to-last-selected-node)
Settings - both deform options
All curve modes
