### ISSUE TITLE
'Copy Version Info' not working - Linux

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#3209]
Under `Menu -> About Surge`

the `Copy Version Info` function does not work 

all other Links on the About page are functioning properly

**Comment by baconpaul** [comment]
```
//------------------------------------------------------------------------
void Frame::setClipboard (const SharedPointer<IDataPackage>& data){
#warning TODO: Implementation
}
```

that's the linux vstgui implementation of setClipboard!

"Cool"

**Comment by baconpaul** [comment]
The answer is cat the string to a popned `xclip -selection c`

**Comment by tank-trax** [comment]
I just read this

Make sure you are using alias xclip="xclip -selection c" or else you won't be able to paste using Ctrl+v.

**Comment by baconpaul** [comment]
Yup 
so in cabout it is an if linux and a popen and it should all work

**Comment by tank-trax** [comment]
just tested and `xclip -selection c filename.txt` will copy the contents **filename.txt** to the clipboard

Ctrl+V then pastes those contents
