### ISSUE TITLE
MSEG mouse accuracy - Linux

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#3211]
in the MSEG screen there is no accuracy with the Mouse control

![mseg-mouse](https://user-images.githubusercontent.com/41337033/100007404-078fa500-2d9a-11eb-847a-e9bff7ebcd53.gif)

problem exists on or around 
![Screenshot_20201123_143552](https://user-images.githubusercontent.com/41337033/100007467-20985600-2d9a-11eb-8d62-d13114c8be13.png)

![Screenshot_20201123_143657](https://user-images.githubusercontent.com/41337033/100007506-2ee67200-2d9a-11eb-977a-ab6358ee2299.png)
is OK

**Comment by baconpaul** [comment]
This is because I did the reposition-when-hidden trick which linux doesn't support

**Comment by baconpaul** [comment]
Oh those aren't adjacent commits! Gotcha :)

**Comment by tank-trax** [comment]
it works now, thanks!!
