### ISSUE TITLE
Modulation pane timescale numbers cropped at the bottom.

### ISSUE THREAD

**Issue by Kingston1** [surge-synthesizer/surge#3243]
On Windows VST2/VST3 at least in Cubase 11 (looks generic, not host related).

Using Windows 125% HiDPI setting. It's cropped the same despite zoom scale.

Apparently at non HiDPI 100% this does not happen, but I have not tested myself. 

![image](https://user-images.githubusercontent.com/5409091/100377896-dffb3f80-301a-11eb-871c-752cd4204909.png)

**Comment by baconpaul** [comment]
OK I've figured this one out.
This occurs if you don't have the Lato font installed.
In RuntimeFontsWin I changed "Lato" to "Qato" so it falls back to default and see this

The installer installs Lato by default so I think the answer here is "run the installer or install Lato"

I think I can warn if lato doesn't resolve to lato. Lemme look.

![Screen Shot 2020-12-09 at 10 26 50 AM](https://user-images.githubusercontent.com/13387561/101649628-1c5e7080-3a09-11eb-9548-db6932dd1be5.png)
