### ISSUE TITLE
checkSizeContraint ignored VST3 Mac Reaper

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3268]
@Kingston1 this is related to your zoom changes I am almost sure

checkSizeConstraint basically lets us force an aspect ratio. I was whacking it to be a no-op on FL to fix #2466 and when testing in reaper noticed that the constraint is no longer forced mac Reaper VST3. I can drag to any ratio and moreover, it never narrows so i can drag to have offscreen elements. I think this is related to your re-order shuffling so wanted to toss this issue in.

I'll push ahead with the disablement for #2466 since that seems like the right fix there no matter what.

**Comment by Kingston1** [comment]
This reproduces in Windows as well. I can fix this.
