### ISSUE TITLE
Ctrl snapping on deform slider is broken

### ISSUE THREAD

**Issue by TheNerdyMusicGuy** [surge-synthesizer/surge#3282]
When holding Ctrl, the deform slider usually snaps in 5% steps, but at the moment it goes straight from -100% to 0% to 100%.

Version: 1.8.nightly.186fab3
Build Info: Built on 2020-11-29 at 00:21:03, using pipeline host 'WIN-NSSBUUS6UC1'
System: Intel CPU, Windows VST3, 64-bit
Plugin Host: Ableton Live 10.1

**Comment by baconpaul** [comment]
Confirmed.
