### ISSUE TITLE
Disabling the LFO rate is not saved with the LFO preset

### ISSUE THREAD

**Issue by TheNerdyMusicGuy** [surge-synthesizer/surge#3293]
Disabling the LFO rate is not saved with the LFO preset.

1: Disable the LFO rate on an LFO
2: Save the LFO as a preset
3: Load the preset
4: Notice how the rate is enabled again

Surge Synthesizer
Version: 1.8.nightly.971cb5e
Build Info: Built on 2020-11-29 at 15:43:41, using pipeline host 'fv-az74-970'
System: Intel CPU, Windows VST3, 64-bit
Plugin Host: Ableton Live 10.1

**Comment by baconpaul** [comment]
Good catch
