### ISSUE TITLE
Can't import wavetables created with WaveEdit - Surge crashes along with the host

### ISSUE THREAD

**Issue by unfa** [surge-synthesizer/surge#3300]
**Bug Description:**
Importing a wavetable bank exported from WaveEdit

**Surge Version**

* Version: 1.8 (nightly build downloaded on 2020-11-30)
* Plugin Type: VST3
* Bitness:64-bit
**Reproduction Steps:**
1. Create a wavetable with WaveEdit 
2. Save it using "Save Bank as..." option
3. Open Surge
4. Switch the Osc 1 to Wavetable
5. Choose loading a custom wavetable
6. Select the wave file saved before form WaveEdit
7. Watch Surge crash along with it's host

**Expected Behavior:**
Wavetable should load or an error should be thrown, but the synthesizer should not crash along with it's host.

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following information):**
 - OS: Manjaro Linux
 - Host: Carla, Ardour

**Additional Information:**

Here's a wavetable I've made in WaveEdit that I've been testing this with:

[Test.zip](https://github.com/surge-synthesizer/surge/files/5615412/Test.zip)

**Comment by mkruselj** [comment]
Yes, WaveEdit doesn't add the required metadata that Surge needs. Serum wavetables are supported, and .wt format, but nothing else.

**Comment by unfa** [comment]
Thanks. I've read in Surge manual that WaveEdit can be used to create custom wavetables, so I assumed it's gonna be compatible.
Are there any other open-source tools I could use to make a custom wavetable that Surge would load without issues?

**Comment by mkruselj** [comment]
AFAIK no. There is Audioterm, but it's Windows only (can WINE it tho), but old and quirky interface. But supports Surge .wt format out of the box.

**Comment by unfa** [comment]
Ah, I see. I should have read deeper into the manual. I'll look into that, and I'm looking forward to 1.9! Thanks!

**Comment by mkruselj** [comment]
All good! We also want to be compatible with more WT formats out of the box. But there's so many of them...

![image](https://user-images.githubusercontent.com/2393720/100605733-a8391400-3308-11eb-8488-c2cb5ef051b9.png)

**Comment by baconpaul** [comment]
If you use wave edit you need to hand tag your files before you import using the python scripts we provide in the repo. 

Here’s the full documentation on our wiki along with the set of tools (all GPL3) you can use.

As @mkruselj said this will get better in 19

https://github.com/surge-synthesizer/surge-synthesizer.github.io/wiki/Creating-Wavetables-With-WaveEdit

**Comment by baconpaul** [comment]
Gonna reopen this just because nothing should make surge crash

@unfa can you attach a wavetable or two as a zip file here and I will see why? May just be a small fix for 180 to at least pop an error.

**Comment by baconpaul** [comment]
Oh i see you attached a wt. sorry ignore me then!

**Comment by baconpaul** [comment]
Sigh. Of course that wav file loads no problem on surge mac. I'll see if I see same linux reaper.

**Comment by baconpaul** [comment]
Linux Reaper VST3 works also
Hmm
So : you are in ardour 6.5 @unfa?

**Comment by unfa** [comment]
Oh. Hahaha! Actually I tested in Carla recently.

**Comment by baconpaul** [comment]
Just built Surge and Carla at head and had no problem loading your WT @unfa?
Did you get a stack?

**Comment by baconpaul** [comment]
OK and @selenologist tested it in Ardour also - none of us can make your WaveTable crash!

Is it possible, @unfa, for you to run carla under a debugger and get a stack trace when it crashes? Really just 'gdb -- carla' and then give it a whirl?

**Comment by unfa** [comment]
Yes, I'll do that shortly!

**Comment by unfa** [comment]
I've downloaded the nightly build of Surge again and built Carla from git and on my home studio desktop it imports :D

The wavetable is improperly spliced, but it doesn't crash!

I'm going to now test on my work laptop where I've been testing this before.

I'l test before upgrading Carla so I can reproduce and see if there's a difference.

**Comment by unfa** [comment]
I can't reproduce the crash in nightly Surge, so it seems to have been fixed at least in that regard.
It doesn't load the wavetable bank saved from WaveEdit correctly, but it loads at all it and keeps working.

**Comment by mkruselj** [comment]
OK we will then tentatively close the issue. If it happens again and you have a more consistent repro case, feel free to reopen!

**Comment by baconpaul** [comment]
Yeah the reason it won’t load correctly is because WaveEdit puts no metadata into the wav file about the structure (frame size etc). Serum Surge and others all do. When Surge encounters such a file it assumes it is a ‘one shot’ with a frame size of 1024 or so.

If you want to add the metadata the python scripts in the wiki linked above will modify them for you

And again we have plans, in 1.9, for a person in this situation to get a popup which says ‘can’t find metadata - load as one shot or set it up’ and then voila you can set it up

But for now, it’s the python scripts if you want to tag the file with structure.

Gonna close this though. That code is well tested and unchanged forever. I’m not sure what caused your crash - might be other problems out there still - but I don’t think it was the wav load code path.

Thanks as always!

**Comment by unfa** [comment]
Thank you! I'll look out for similar stuff in the future and make sure to collect a backtrace if that happens.

**Comment by baconpaul** [comment]
Can you somehow make the bank available?

**Comment by baconpaul** [comment]
(I just loaded the test.zip at top of thread into XT 1.2.3 on macOS no problem - no crash and loaded as a one shot as expected)

**Comment by unfa** [comment]
Here's the wavetable bank I created with Waveedit and tried to import into Surge that got it to crash:
[unfa 01.zip](https://github.com/surge-synthesizer/surge/files/11541790/unfa.01.zip)

I tested with Surge XT VST3 on Windows in Ardour 7.3.

**Comment by mkruselj** [comment]
Thats loads fine over here on Windows. However more than a half of the sample is empty, for whatever reason:

![image](https://github.com/surge-synthesizer/surge/assets/2393720/9bfb83f5-7d38-4bfc-8f36-63008ea51cc1)

**Comment by unfa** [comment]
Yes, it's partially empty, that's correct.
WaveEdit seems to have a fixed number and length of frames in a wavetable.
I wasn't able to reduce the number of frames or up the resolution.

**Comment by baconpaul** [comment]
in the surge-for-rack wavetable oscillator I added an option to 'assume you are a wavedit table" which sets table size to 256 and frames to samples / 256. Haven't added this to the VST.

But that still doesn't mean it should crash.

**Comment by mkruselj** [comment]
Basically #3436 in disguise. 🙂

**Comment by baconpaul** [comment]
I wonder if the open dialog park has a bug that the drop file path does not. Thanks for the video!

**Comment by baconpaul** [comment]
So: if you rename "unfa 01" to "unfa 01.wav" does the same gesture work? 

Looking at the code there is an odd case when you try to load something without an extension that I think might be crashing it.

**Comment by unfa** [comment]
I was suspecting the specific way I load the wavetable is causing the problem. I don't know other ways though.

**Comment by baconpaul** [comment]
drag and drop it onto surge works.

but the fact that i can't make it crash the same way is bothersome. You are loading the file exactly named 'unfa 01' no extension using the browser on windows? makes me think the load fails silently somehow.

**Comment by mkruselj** [comment]
OK when I try using the "Load wavetable from file" dialog I actually get this straight away:

![image](https://github.com/surge-synthesizer/surge/assets/2393720/89342fe4-dc98-476e-ba2b-004f0f1df85b)

**Comment by mkruselj** [comment]
OK I see the issue, we don't filter down for extensions in this `juce::FileChooser` dialog. We need to add support for only .wav and .wt here. Very simple fix!

Files without extensions already aren't allowed for drag and drop, so it should be the same case here.
