### ISSUE TITLE
GUI errors due to weird stroke rendering

### ISSUE THREAD

**Issue by unfa** [surge-synthesizer/surge#3305]
**Bug Description:**
The Surge UI looks a bit weird, and I think the problem is a strange way that the strokes are drawn in.

Shapes that should be rectangles often have one corner sticking out at a weird angle.
Slider handles have a strange seam where the shape is bulging out
Waveform and LFO display suffer from unlimited miter on the stroke corners, which result in visual overshoot.

**Surge Version**

* Version: Nightly 2020-11-30
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Open the Surge UI and take a closer look

**Expected Behavior:**

**Screenshots:**

![image895](https://user-images.githubusercontent.com/491704/100651408-af324780-3345-11eb-98f2-b1f40ceba767.png)

Here's an example from Inkscape (libre vector graphics program):

![image](https://user-images.githubusercontent.com/491704/100651863-68911d00-3346-11eb-9e84-e6d6f1835f89.png)

The red stroke has a very long miter, creating a long overshooting spike on corner
The green is the exact same curve, but the stroke is rounded off, so there's no overshoot.

I think the latter would be a better setting for rendering waveforms and LFO/ENV functions as they wave will remain in the visual range (-1 .. +1). Currently a very sharp spike on these graphs will visually break free from the valid value ranges.

**Computer Information (please complete the following information):**
 - OS: Manjaro Linux
 - Host: any
 - Version: any

**Additional Information:**
1. I don't know if the same problem occurs on other operating systems.
2. I'm a graphics designer so I pay attention to this kind of stuff, but the UI looks a bit "melted" and wacky, and I don't think it's intentional.

**Comment by baconpaul** [comment]
Oh I accidentally merged 2x oversample on the UI last night. I’m sorry. I should back that down. I think it is causing most of these problems for you.

**Comment by unfa** [comment]
I don't think that's an issue, I like the AA, maybe add a control for it? :)

I've seen these artifact since the very beginning, it's not just this particular nighty build, I've seen them in 1.7.1 as well, it just took me so long to finally decide to report it, since it doesn't really affect the function of the synth, just it's appearance.

**Comment by baconpaul** [comment]
Ahh right. 
Well yeah VSTGUI only gives us so much
But I found out last night (when I made that fix) that Cairo VSTGUI has an integral mode problem which I fixed in several spots
So let me try and see if that helps
but i have been in there.
and vstgui limits us.

**Comment by baconpaul** [comment]
So turns out the same NonINtegral mode fix I applied last night to the MSEG display I can also apply to the SVG renderer
This makes a *massive* difference on Linux

<img width="484" alt="Screen Shot 2020-11-30 at 2 20 48 PM" src="https://user-images.githubusercontent.com/13387561/100654115-5b106e80-3317-11eb-8c2d-9443afa034d2.png">

there's a screenshot

I'll merge this now. It's the right fix. (Basically: Turns out Cairo VSTGUI implementation assumes all paths are integral unless you tell it otherwise; VSTGUI on other platforms does not; but we need to be careful).

Also: Report everything you see! Some may be easy! And if they aren't they are just open issues. We already have a pile of em. One more doesn't hurt.

**Comment by unfa** [comment]
Wow! Fabulous! This finally looks like I'd expect it to!

Also - is there way to have the Anti-Aliasing on? ;)

**Comment by baconpaul** [comment]
Compile! It's on by default on every platform and now is on by default on linux too. We have the time.

**Comment by baconpaul** [comment]
(compile once i merge. I haven't merged yet :) )

**Comment by baconpaul** [comment]
OK just pushed the change. If you build yourself, pull main at head. If you download binaries will take ~30 minutes to update on web. You know the drill.

**Comment by unfa** [comment]
Fabulous! This is gonna be great for.? making more video tutorials!
