### ISSUE TITLE
Fracture effect causes loud noise

### ISSUE THREAD

**Issue by TheNerdyMusicGuy** [surge-synthesizer/surge#3313]
The AW Fracture effect is a bit messed up and causes really loud noise.

1: Turn down your master volume (!!!)
2: Insert the Fracture effect somewhere where it does something
3: Play a note

It seems like the "Fracture" slider defaults to a value above the maximum value of the slider. Once the slider is moved once, the effect behaves fine.

Surge Synthesizer
Version: 1.8.nightly.809a376
Build Info: Built on 2020-12-01 at 00:59:41, using pipeline host 'fv-az83-597'
System: Intel CPU, Windows VST3, 64-bit
Plugin Host: Ableton Live 10.1

**Comment by mkruselj** [comment]
Incorrect default value. I set it to 0 now.
