### ISSUE TITLE
Retain MSEG snap toggles while copying Surge instances in DAW

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#3316]
At the moment also when copying just a single MSEG the 'On' state is not transferred to the new MSEG if you had them clicked in. The On state is also not saved in presets where that was the state it was made in.

Would be nice to not having to click them On again all over several MSEGS if that was the state one was working with especially when it comes to copying a whole instance of surge.

**Comment by K0rrid0r** [comment]
also Movement Mode is not saved i the state it was left in while copying a whole instance of surge or opening a preset again.

it's confusing.

**Comment by K0rrid0r** [comment]
also Snap To Grid numbers are not saved.

**Comment by baconpaul** [comment]
Right basically none of the editor state is saved in the patch or the dawExtraState. Nor is it copied. Need to ponder this one - the editor state is 'lower' in the link stack than the mseg and dsp by a lot..

**Comment by baconpaul** [comment]
This is pretty easy; we just need a data structure in the dawExtraState which copies and streams/unstreams/defaults the mseg state, and to read from it and write to it in populate/unpopulate in SGE. Bit tedious.

But have to fix #3465 first. Will probably do both at same time.
