### ISSUE TITLE
Requesting more detailed instructions on how to build on ARM

### ISSUE THREAD

**Issue by Loadus** [surge-synthesizer/surge#3317]
Hey guys,
I was trying to build Surge on the Raspberry Pi, but I ran into several little issues (as I'm not super proficient at setting up builds). I followed the instructions on the project page and got pretty far, but now I'm stuck with new errors that I have no idea how to fix. There was one package that could not be installed on the Pi (libxcb-util-dev).

Trying to build the headless Surge and this happens >>
`
[ 47%] Building CXX object CMakeFiles/surge-headless.dir/src/common/vt_dsp/lipol.cpp.o
/home/patch/surge/surge/src/common/vt_dsp/lipol.cpp: In member function ‘void lipol_ps::set_blocksize(int)’:
/home/patch/surge/surge/src/common/vt_dsp/lipol.cpp:19:23: error: ‘vdupq_n_f32’ was not declared in this scope
    lipol_BLOCK_SIZE = vdupq_n_f32(bs);
                       ^~~~~~~~~~~
make[3]: *** [CMakeFiles/surge-headless.dir/build.make:511: CMakeFiles/surge-headless.dir/src/common/vt_dsp/lipol.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:190: CMakeFiles/surge-headless.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:197: CMakeFiles/surge-headless.dir/rule] Error 2
make: *** [Makefile:176: surge-headless] Error 2
`

I cloned the Git repo and forced version 1.7.0, which I'm not sure is the correct way to go about this. I'd love to get minute details on the steps needed to successfully build Surge for the Pi (I'm using the Patchbox distro, which is optimized for audio). This might be more optimal to build on the desktop, just setting the target to arm?

My original plan was to use Surge on the Zynthian, but for some obscure reason, Zynthian is adamant that my Hifiberry card is mono so I switched to Patchbox and was just attempting to build Surge to test out some of the patches I made on the PC version.

The goal is to get a couple of Surge instances running on the Pi for some multitimbral awesomeness. \o/

Any tips would be very appreciated.

**Comment by baconpaul** [comment]
That's dll time not packaged time @mkruselj 

@Loadus can we get some more information like what architecture are you building for, what compiler, what os, etc? On a physical Pi I have only tested it with the latest 64 bit raspbian on a pi4 but as mkruselj says zynthian also has a bui.d

We cross compile to ARM in our pipelines so we know it can build aarm64

xcbutil will be required to actually use the synth yeah.

**Comment by baconpaul** [comment]
Oh also: don't force version 1.7. Force at least 1.7.1 but we have updated pi since then. So please try at head since there are changes since the 17 release.

**Comment by Loadus** [comment]
Yeah, this is definitely a user error from my end as I don't know what I'm doing while building this. :D
I forced the 1.7.0 as I saw completely different set of steps to build and used that as a guideline (with no knowledge of the current state of the codebase or structure etc), I will try the 1.7.1. Also, I think I made an error stating that xcbutil wasn't available - it is and is installed, just checked - it was something else and now I can't find what it was. > . <

The list of prerequisites was quite extensive but it was a bit fragmented. I also had to build cmake from scratch as the version that was available was too old (3.13). One complete apt-get command with everything required would be amazeballs. \o/

So here's my recipe so far:
Building for ARM (Raspberry Pi 3B armv7l) using >>
cmake -Bbuild -DARM_NATIVE=native
and
cmake --build build --config Release --target surge-headless
using cmake 3.19.1
using Patchbox OS 

just to see if anything comes out from the other end.

And yes, the Zynthian version worked (albeit with poor performance) but playing in mono as Zynthian didn't use the card properly. Also there was no fast way to load up my presets as the Zynthian build uses some [other way] to load presets, I didn't quite understand it.

I was hoping to run Surge alone, just to see the performance if it's even feasible to create a synthesizer from the Pi (Zynthian has shown that yes, it is possible with the other synths in the box, I'm just stubborn and want to use Surge because it's the best synth ever made :P).

I'll keep tweaking, eventually I will have a glorious build in the box.

**Comment by baconpaul** [comment]
So that prescription should work fine at head on arm64. But try one of the explicit toolchains maybe in cmake/*?

I don’t have my pi with me or booted but can look later in the week if you don’t get there

**Comment by Loadus** [comment]
Nice, I'll try that - I don't know the syntax of how to change the cmake toolchain but I'll look it up.

**Comment by baconpaul** [comment]
So basically how it works is when you do `-DARM_NATIVE=native` it triggers some flags in our cmake environment and includes `cmake/arm-native.cmake` which sets compiler flags and stuff.

So if you find your system needs different compiler flags you would

1. copy cmake/arm-native.cmake to cmake/arm-pi3b.cmake (or whatever)
2. edit cmake/arm-pi3b.cmake to set up what you want and
3. then do -DARM_NATIVE=pi3b when you run cmake first time

cross compiling is a bit different but you are compiling on native hardware

the error message you got means you can't find the neon library though and is exactly the problem with ARM builds I fixed on August 4 with this commit: d9e189b5531f45d6f5dec50e4f7f4d66231ea714

So really I think you don't need to do any of this stuff. Just pull the top of main rather than 1.7.* and you will be all fine.

**Comment by Loadus** [comment]
Ah, ok.

I originally tried to build from the stuff that the Git cloned from the repo but the build script was convinced I was on x86* and didn't even start. I'll have a deeper look on what was going on and could actually reset and start clean. The very first problem I ran into was github not accepting my login on the terminal so I'm getting used to having more and more exotic errors and trying to navigate my way through them. :D

**Comment by mkruselj** [comment]
> This would essentially be like having a $2000 synthesizer running in a $100 box. \o/

Surge originally costed less than $200, though. 😛

**Comment by Loadus** [comment]
> > This would essentially be like having a $2000 synthesizer running in a $100 box. \o/
> 
> Surge originally costed less than $200, though. 😛

Heh, yeah, this is comparing the features (especially the filter) to the current offerings on the hardware market, which is very skewed in both pricing and features. To get some of the tastiest sounds that Surge can produce, in hardware, you would have to go for Access Virus (around 1200€+) or something even more expensive like Novation Summit (2000€). Surge is also the first software synthesizer that I've encountered that ticks all the boxes that I need as a sound designer. :D

**Comment by baconpaul** [comment]
I have been wanting to do that project for a while. That is embedded arm surgery keyboard 

Headless runs our unit tests but right now to route midi either you are running the vst3 in a daw (reaper arm works great with surge arm on a pi) or slinging some c++

If you are planning on slinging that c++ please ask on discord - I have good ideas about how to do it but it hasn’t made it to top of stack

Since you are building I will close this now though 

Thanks!

**Comment by baconpaul** [comment]
>  I did as you instructed and added
-mfpu=neon-vfpv4
into the cmake toolchain file and the compiler just continued where it left off. This might end up with a very 'special' build but I'm interested to see what happens

Yeah if you are using the broken code that will probably fix it on 32 bit pi!
