### ISSUE TITLE
build-validate-au results in Cannot get Component's Name strings, error retrieving Component Version: -50

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#332]
one for @baconpaul maybe?
```
./build-osx.sh --build-validate-au
```

results in

```
$ ./build-osx.sh --build-validate-au

Building surge-au with output in build_logs/build_au.log
Build of surge-au succeeded

    AU Validation Tool
    Version: 1.6.1a1 
    Copyright 2003-2013, Apple Inc. All Rights Reserved.
    Specify -h (-help) for command options

--------------------------------------------------
VALIDATING AUDIO UNIT: 'aumu' - '00000000' - 'VmbA'
--------------------------------------------------
ERROR: Cannot get Component's Name strings
ERROR: Error from retrieving Component Version: -50

* * FAIL
--------------------------------------------------
TESTING OPEN TIMES:
FATAL ERROR: didn't find the component
```

**Comment by baconpaul** [comment]
did you blow everything away and then run a host so that surge was dropped? Sometimes the au cache can get confused and I need to install then reboot but it is very rare. I have no problem and run this command about 400 times a day.

**Comment by goonzoid** [comment]
I also hit this. In my case, there were two issues:

- There's an issue with iTerm2, introduced in v3.2.8, and present until at least v3.3.7, which prevents `auval` from being able to find most AU plugins. See https://gitlab.com/gnachman/iterm2/issues/7946 for details and a workaround if you're using iTerm2.

- There's an issue with the same symptoms in tmux: https://github.com/tmux/tmux/issues/1847. I've not found a workaround for this one yet.

Documenting this here in case it helps someone else in the future.
