### ISSUE TITLE
Can't locate Surge-1.7.1 after installation (MAC OSX 10.14.6)

### ISSUE THREAD

**Issue by RolandTraehus** [surge-synthesizer/surge#3321]
Hi,
After installing Surge, I cannot seem to locate the VSTi in Reaper. When I search for it on the computer using spotlight i get no results. Am I missing something?
I have used Reaper for many years, so it's not as if I'm not used to getting new plugins, and it has never been a problem before.

Surge 1.7.1 - 2020-08-02

I'm using a
MacBook Pro (Retina, 13-inch, early 2015)
Mojave 10.14.6

**Comment by baconpaul** [comment]
There’s only a vst3 not a vst. Have you looked in the vst3 group?

**Comment by RolandTraehus** [comment]
Yes, it's definitely not there...so strange

**Comment by baconpaul** [comment]
Is it in /library/audio/plugin-ins/vst3? Did the installer place it there?

**Comment by baconpaul** [comment]
Oh also I wonder if it is the fact that surge is unsigned, does this help? https://youtu.be/AHoTH-OWGnA

**Comment by RolandTraehus** [comment]
Yes, the installer did indeed place it there - spotlight wouln't find it, so this is the first time I've actually seen the file. So far, so good.
I needed to do the 'Open Anyway'-thing when I opened the installer, but maybe I need to do it again?

**Comment by baconpaul** [comment]
Yeah you need to do it for the installer and the vst3 both. That video shows how with the AU but the vst3 is similar I think.

**Comment by RolandTraehus** [comment]
He's using Pro Tools in the video - I can't figure out how to get Reaper to do it. Any ideas?

**Comment by mkruselj** [comment]
Do Reaper's plugin scanning paths include /library/audio/plugin-ins/vst3?

**Comment by RolandTraehus** [comment]
> Do Reaper's plugin scanning paths include /library/audio/plugin-ins/vst3?

Yes it does

**Comment by baconpaul** [comment]
In the video He is me; and protools is logic. But yeah it’s not reaper

I think after a scan go to security settings and look in the exact same place 

There’s also a command line version I can dig up later today for you

**Comment by RolandTraehus** [comment]
Haha sorry :)
It doesn't show up after re-scans, so I'd really appreciate it, if you could dig up said path.

Also, how weird is it, if I'm the only one who's run into this problem? Seems like this should be the main thing on the internet now.

**Comment by baconpaul** [comment]
So after a rescan if you go to the security screen do you see Surge.vst3 as being blocked?

You can (temporarily) do `sudo spctl --disable` in terminal to see if this is it

Also you can run Reaper from the command line (`/Applications/REAPER64.app/Contents/MacOS/REAPER`) and then rescan and you might see an error go by?

I run surge in reaper every day. But I also build it myself so i may have a different security setting than you. It could also be something else though.

**Comment by RolandTraehus** [comment]
It works when I run Reaper from the command line! That is absolutely wonderful! Thank you for your help and for building such a great plugin!
I'm headed for that rabbit hole now :)

**Comment by baconpaul** [comment]
Right. So that means your security settings are somehow cranked for Reaper. Maybe google around or ask on a reaper forum? 

Glad we got it working! Enjoy Surge! (Also: 1.7 is cool, but super soon we are going to be calling for beta testers on our 18 release candidate; if you are in our discord or on the facebook group you'll see the notification!)

And have fun making music with surge!
