### ISSUE TITLE
Preserve last written envelope when switching between Envelope/LFO in MSEG Edit Mode

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#3322]
Preserve last written envelope when switching between Envelope/LFO in MSEG Edit Mode.
It would be nice to get back to what was drawn if clicked on Envelope again. At the moment only the last segment is affected. 

![308](https://user-images.githubusercontent.com/56724286/100851987-2f5fc680-3486-11eb-8def-57ec1e30a326.gif)

**Korridor 13:43**
would be nice to get back to what was drawn if clicked on Envelope again. otherwise one has to memorize lotta things.
**baconpaul 17:03**
oh sure I can preserve that.
I preserve the duration I can preserve the nv1 also
The LFO behavior is correct but the toggle back is not

**Comment by baconpaul** [comment]
Fix inbound this evening
