### ISSUE TITLE
Subtype and deactivation and CSwitchControl with Filter Subtypes is weird and fragile

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3346]
The way CSwitchControl toggles the filter subtype is weird. All value changes used to be +1 and just rotate in SGE; then with wheel I input a direction and reset it. But still. This is all silly. If we weren't so close to the end of 18 I would change it, but we are.

So in 19 add a 'multi-value-switch-control' basically and use it here and have the API not be insane (like have the value be the value and stuff). You can see over in #3324 and #3345 what I did to make it work in 18 but there's still a good solid half day of fixing here later on.

The only reason I didn't do it now is all that 'ancillary' use of the subtype tag which really needs refactoring anyway.

**Comment by baconpaul** [comment]
The filter subtype is hokey as heck. It should have logic on the parameter for appears deactivated which uses its control group now we have that mechanism rather than all the special cases in the gui editor and automation paths.

**Comment by baconpaul** [comment]
line 806 of SGEVCB 
line 2260 or so of same
line 2649 - wow

and then the two places in SurgeSynthesizer

**Comment by baconpaul** [comment]
I’m going to leave this for the next release.

**Comment by mkruselj** [comment]
This also all gets rewritten in XT2, whole new SGE and so on, so... we know we will do it, closing this one ahead of time then. @baconpaul yell if you disagree!
