### ISSUE TITLE
Filter subtype should be remembered per filter type

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3348]
Currently, when we choose a different filter type, filter subtype resets to the default value.

Would be much nicer if for each filter type that has subtypes, the last selected subtype is remembered.

Investigate if it's feasible to tuck this one in into 1.8 perhaps!

**Comment by baconpaul** [comment]
You need to do this in the synth in order for it to work with automation also, not the gui. So it's a bit tricky.

Lemme look but hacking it into SGE is not the answer.

I may bounce it out of the milestone but we still have a week before we freeze and this is just a state array of size [scene][filterunit][filtertype] we need to read and write to. So may not be that bad. Just have to figure out the right 'where'

**Comment by baconpaul** [comment]
Yeah this is not hard but requires a small shuffle. I'll get to it and we can put it in. Good add.
