### ISSUE TITLE
Mono mode: note priorities

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3359]
Currently, Surge uses last note priority when dealing with note ons, but curiously (and strangely) uses highest note priority for note offs (when releasing a note to older keys that are still held down).

Add note priority modes: Latest (should be the new default), Lowest, Highest, Legacy. The difference is that Legacy would retain current weird behavior, and Latest/Lowest/Highest would be consistent in how they are applied for both note ons and note offs.

**Comment by baconpaul** [comment]
Latest should only be default if streaming version is 15
Otherwise old sessions will render differently

**Comment by mkruselj** [comment]
Yes ofc!

**Comment by mkruselj** [comment]
I'd do it like this, not put them in a submenu:

![image](https://user-images.githubusercontent.com/2393720/101292688-6250e400-3811-11eb-8631-02c34fe93779.png)

**Comment by baconpaul** [comment]
Sure easy enough change.
