### ISSUE TITLE
User unable to see plugin in ardour linux on debian testing

### ISSUE THREAD

**Issue by krznv** [surge-synthesizer/surge#3378]
Hi, just wanted to see if someone knows why this is happening. Compiling Surge or installing the .deb file successfully and the plugin is not visible in Ardour. I'm using Debian Testing.

I compiled with "make -j 2" without Surge.vst3 as it returned:
`make: *** No rule to make target 'Surge.vst3'.  Stop.`

**Comment by baconpaul** [comment]
Hi! Happy to try and help.

1. Are you running a recent enough version of ardour that it will support VST3 (Ardour 6.5 or later)
2. Are you installing surge @ head or from a tag?
3. What cmake command did you run before your make?
4. Were there any errors in your cmake pass?

The canonical way to debug this is to do

```
git clone https://github.com/surge-synthesizer/surge
cd surge
git submodule update --init --recursive
cmake -Bbuild_fresh
cmake --build build_fresh --config Release --target Surge_VST3_Packaged
```

which should deposit a working `Surge.vst3` in build_fresh/surge_products. If it does then

```
cmake --build build_fresh --config Release --target install-vst3-local
```

should do a working install into ~/.vst3

**Comment by krznv** [comment]
1. I'm running Ardour 6.3

2. I'm not sure what is the practical difference?

3. cmake . -Bbuild and the submodule update

4. Don't remember, maybe a missing dependency

I will debug, try the install and check the vst paths in ardour tomorrow.

**Comment by baconpaul** [comment]
OK. 

I think #1 is your problem. Ardour 6.3 doesn't support VST3. For that you need Ardour 6.5.

Surge VST3 definitely works in Ardour 6.5. Heck the team even used surge on the announcement screenshot!

https://ardour.org/whatsnew.html

So doing that upgrade is probably your first bet.

You could build the LV2 I suppose but the LV2 has loads of bugs and noone has fixed them. Now that basically everything in Linux supports VST3 I think it will probably stay that way. But basically same instructions as above just with install-lv2-local and Surge-LV2-Packaged

**Comment by krznv** [comment]
I did not realize Ardour only got VST3 support with 6.5.. I'm happily running Surge in it now, thank you!!

**Comment by baconpaul** [comment]
great
