### ISSUE TITLE
VU Meter Touchup

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3380]
<img width="256" alt="Screen Shot 2020-12-09 at 3 43 32 PM" src="https://user-images.githubusercontent.com/13387561/101685136-5fced400-3a35-11eb-8bfd-fa0d78d56f66.png">

Here's Nick's VU meter

Would be great if all the VU meters could do that basically have colors for low medium hot and then add the interlace overlay

**Comment by baconpaul** [comment]
Also: Different skin colors for gain reduction vs vu meter (with gain reduction falling back to vu meter if not specified etc...) which is in the vut_types (thanks to @mkruselj for pointing that out to me :) )

**Comment by mkruselj** [comment]
> (with gain reduction falling back to vu meter if not specified etc...) 

Fallback should be to the first VU meter color, colors 2 and 3 disregarded. :)

**Comment by mkruselj** [comment]
Also might be good to include this diff that properly centers the stereo meters within the VU meter frame:

[patch.txt](https://github.com/surge-synthesizer/surge/files/5668680/patch.txt)
