### ISSUE TITLE
Vst3 crashes when certain menu items are selected

### ISSUE THREAD

**Issue by reyndawg** [surge-synthesizer/surge#3386]
**Bug Description:**
Vst3 crashes when certain menu items are selected. specifically 
- any preset submenu is opened
- most items in the bottom right menu
- sometimes the about screen crashes, sometimes it loads correctly

**Surge Version**
* Version:
About screen says:Version1.7.HEAD.5270cfb9
git says HEAD detached at release_1.7.1
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. click on Preset name to open preset menu
2. scroll to desired Preset bank
3. when bank would normally open, vst crashes

**Expected Behavior:**
I expect the preset bank to open, and to be able to select my preset from the bank

**Computer Information:**
 - OS: Ubuntu Linux 
 - Host: Bitwig Studio version 3.1.2
 - Version 20.0.4 with kernel 5.4.0-54-lowlatency 

So I did build this from source, as the .deb package has other problems loading in Bitwig for me. I chose the tag 1.7.1 because it seemed to be the most recent stable build. if there is a different tag I should use I can, however this issue also appeared at tip of master. I am wondering if there are any logs anywhere that Surge writes that could provide some more information about why it is crashing. 

![Screenshot from 2020-12-09 22-15-44](https://user-images.githubusercontent.com/591583/101730282-970da700-3a6e-11eb-872f-efb231ccd6b4.png)

**Comment by mkruselj** [comment]
Update Bitwig to latest version please.

**Comment by baconpaul** [comment]
Yeah BW that old is unreliable with the VST3 on linux. The latest beta and the latest nightly are the best combo on BW (although 1.7.1 will work with some of the 3.2 family up to 3.2.4).

https://gist.github.com/abique/4c1b9b40f3413f0df1591d2a7c760db4#gistcomment-3555925

there's a full download on what works and doesn't.
