### ISSUE TITLE
Subfolders for modulator presets don't work as expected

### ISSUE THREAD

**Issue by TheNerdyMusicGuy** [surge-synthesizer/surge#3392]
When adding a subfolder to the modulator presets, it shows up as the root folder in Surge instead, with all presets in it, not just the ones that are in the subfolder itself.

1. Create a folder named "Thurston" in the MSEG folder
2. Put some presets there
3. Notice how the "MSEG" folder is now the "Thurston" folder in the Surge menu, with all presets in it, even the ones that are in the MSEG folder itself.

Surge Synthesizer
Version: 1.8.nightly.2d5acd4
Build Info: Built on 2020-12-10 at 04:31:31, using pipeline host 'fv-az80-94'
System: Intel CPU, Windows VST3, 64-bit
Plugin Host: Ableton Live 10.1

**Comment by baconpaul** [comment]
Yeah they don't work at all! Will re-configure.

**Comment by mkruselj** [comment]
Not completely fixed.

For example if we have a root folder (say "MSEG") and only subfolders in it without any .modpreset, that folder will be skipped.

Compare:

![image](https://user-images.githubusercontent.com/2393720/104858356-b675da80-591e-11eb-91c7-61b57a6664d5.png)

with:

![image](https://user-images.githubusercontent.com/2393720/104858353-b2e25380-591e-11eb-9437-30bd34d1877e.png)

**Comment by mkruselj** [comment]
We need this one for 1.8.1 if we're gonna put some LFO presets in, @baconpaul. So if you don't mind, I changed the milestone 🙂

**Comment by baconpaul** [comment]
OH I see! Gotcha.

**Comment by baconpaul** [comment]
yup repro. Will fix sometime today.
