### ISSUE TITLE
Notes dropped in old bitwig when going faster

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#340]
@sense and I had a long chat on slack this morning about bitwig 1.3 with head of surge. He notes that as notes go faster - not super fast but faster - they sometimes drop. We diagnosed a couple of things because I thought the problem may be that he is running into line 228 returning without having processed all events. See the discussion on slack #general Jan 19 around 7am for more on why I think that.

This issue lets us track it. Immediately I'm going to send him a branch for debugging.

**Comment by itsmedavep** [comment]
This tool may help with diagnosing what is happening with the MIDI. 

http://www.midiox.com/

**Comment by baconpaul** [comment]
Well we confirmed it wasn't what I thought it was. So now we don't know what it is.

**Comment by itsmedavep** [comment]
Another tool suggestion to figure out the MIDI. This one is far more up to date than MIDI OX

http://www.tobias-erichsen.de/software/loopmidi.html

**Comment by sense-amr** [comment]
here is normal build .. 
[weirdbitwigSurgePoly_NormalBuild.zip](https://github.com/surge-synthesizer/surge/files/2776524/weirdbitwigSurgePoly_NormalBuild.zip)

**Comment by baconpaul** [comment]
My special build has only debugging information so is same as master when you tested it.

**Comment by sense-amr** [comment]
yes then this is an ongoing issue through out all the builds of surge i guess.. like i said i have noticed it happening before but kinda found ways to work around it being a problem in the music and sound i was making.. but it really is still there.. and its weird cos its not consistent .. and pretty hard to reproduce exactly the same result each time..

**Comment by sense-amr** [comment]
i mean lets be honest a synth that still plays multiple notes AFTER switching it to "MONO" mode .. isn't really working properly ?

**Comment by mkruselj** [comment]
Closing due to multiple reasons: BWS 1.3 not being relevant anymore really, lack of feedback on the issue if it was maybe fixed in newer versions of BWS and/or Surge. Issue probably doesn't happen anymore. If it does, we will reopen it. If it doesn't, may it rest in peace.
