### ISSUE TITLE
MSEG Axis and Loops

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3402]
![Screenshot_2020-12-11_at_16 18 24](https://user-images.githubusercontent.com/13387561/101921324-dfc27e80-3b9a-11eb-9ed9-442e4b7e1455.png)
![Screenshot_2020-12-11_at_16 21 06](https://user-images.githubusercontent.com/13387561/101921329-e0f3ab80-3b9a-11eb-9233-a9ff4cdf5fc4.png)

The axis label if the notch is shown should hop to the other side if it would clip

**Comment by baconpaul** [comment]
could you also move the loop arrows 1-2 px down so they don't touch the bottom axis?

**Comment by baconpaul** [comment]
We decided to make the loop markers an SVG, with 2x2 grid of 10x10 images

```
<.  <Hov
>.  >Hov
```

Basically

**Comment by baconpaul** [comment]
![unknown](https://user-images.githubusercontent.com/13387561/101950540-71de7d00-3bc3-11eb-938f-2f17ba4cde89.png)

Shade the loop region (with a skin color of course)

here's the handles

**Comment by mkruselj** [comment]
Partially addressed horizontal axis labels in #3405, they are now centered to the gridlines always.
