### ISSUE TITLE
Shift+Tab in Store Patch dialog should move to previous text input field

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3403]
Indeedio.

**Comment by baconpaul** [comment]
So I just tried this on mac win and lin.

On all three, shift tab goes to the previous input in the store patch dialog.

What's exactly the problem you are seeing?

I open store patch, press tab then shift-tab and go down then up no problem.

**Comment by mkruselj** [comment]
Hmmm, it might be Savihost then. Will investigate...

**Comment by mkruselj** [comment]
Hmmm Tab/Shift+Tab doesn't even work in Reaper. Not even when enabling the option to send all keyboard input to plugin...

**Comment by baconpaul** [comment]
I ran it in reaper and it worked. Hmmmmm

**Comment by baconpaul** [comment]
On windows I see

- FL eats tabs altogether
- Reaper works just fine
- Live 10 trial version goes forward for tab and shift tab

On mac, HostingAU, LPX and Reaper all work fine and on Linux I tested in the juce host with no problem. 

So: I don't think this is a surge bug, I think this is a 'DAW eating special keys in their window' bug so I propose we close it. There's no code change we can make if we aren't getting the event, and when we do get the event, we work just fine.

**Comment by mkruselj** [comment]
Yeah weird but it just doesn't work over here in Reaper, with or without its option to send all keys to plugin...

**Comment by baconpaul** [comment]
i just downloaded 6.18 and have no problem with the tab key
i just don't think this is a surge bug!
and i am not sure what i would change.

**Comment by mkruselj** [comment]
Tested in XT, works just fine. Closing!
