### ISSUE TITLE
The VU Meter Graphic

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3411]
1. Make the gradient a single rectangle with a gradient from the API rather than the hokey stuff I did
2. Notch suppression works

**Comment by baconpaul** [comment]
Alternately perhaps have an svg of the bar which we occlude

**Comment by mkruselj** [comment]
Thar SVG would need to have two frames: normal meter and gain reduction meter.

**Comment by baconpaul** [comment]
Actually 3: Mono and Stereo normal; and gain reduction (eve though we don't use the mono VU today). Yup.
