### ISSUE TITLE
Skinheritance

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3418]
The name is too good to not write an issue, but I was thinking today

If you want to take the dark skin and change one and only one color it is a pain. You have to copy the whole lot. Or similarly one and only one image.

So there’s an obvious solution, which I am tentatively putting in the 19 milestone but we might not do (this is more a ‘proposal/brainstorm’ than a ‘we should do this’ ticket at this point).

Skin inheritance: Skinheritance

Imagine if you said

```
<surge-skin version=“2” inherits-from=“FACTORY/dark-mode.surge-skin”/>
</surge-skin>
```

As your ENTIRE skin.xml. This would then find the dark mode surge from the factory library and parse it.

```
<surge-skin version=“2” inherits-from=“FACTORY/dark-mode.surge-skin”/>
   <globals>
       <color id=“lfo.blah” value=“#ff0000/>
  </globals>
</surge-skin>
```

And then that would be basically “whatever’s in the dark skin,m with that one color made red”

Something to ponder. So wanted to write it down so I don’t forget

**Comment by mkruselj** [comment]
@baconpaul If we're planning on moving to a less SVG-driven skin for XT2, I wonder how important/useful this FR would be, then?

**Comment by baconpaul** [comment]
Yeah this will all be totally different. Closing
