### ISSUE TITLE
Dark Skin About Screen Logo used to be in skin; not removed by installer on windows

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3423]
1: No idea why
2: The logo is not null. Something is loading

**Comment by baconpaul** [comment]
OK I now know exactly why

The dark skin used to have a bmp00158.svg

It was removed in ec2d73c289e4993f695a8b90e6d6e7f34a6e0814

but if you installed a nightly before that and have not since deleted your assets then the old bmp00158 will be there it seems, since the installer does a no-delete install on factory assets.

and then that loads blank (because it is blank)

So I think (think) the solution is to just copy the classic 158 -> the dark skin for now and close this

**Comment by baconpaul** [comment]
let me run the installer to confirm this (I don't update my assets on windows as often as mac so I luckily had an old assets directory).

**Comment by baconpaul** [comment]
Yeah just confirmed that running the installer does not delete the old 158. So users who had an old nightly will have had a broken about screen since that commit.

@mkruselj I think 're-add 158 to dark as a copy' is the solution.

Other ideas or shall e do that?

**Comment by baconpaul** [comment]
The alternative is modify the installer to remove the assets
I would sooner do that in 19 not in 18; so if we want to do that I would suggest add 158 now to dark, then ship 18, and open an issue to remove that 158 and mod the installer in 19.

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/blob/35ebcd7cd8a9a40176dee61f29ec99856f8d70d0/installer_win/surge.iss#L51

We should just add skins to that actually

**Comment by mkruselj** [comment]
Yeah let's copy 00158 from classic and be done with it.
