### ISSUE TITLE
Windows Installer doesn't clean up %PROGRAMDATA%\Surge

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3427]
Over in #3423 we found that if you remove a file from a skin the installer doesn't clean it up on next install. The windows installer right now only cleans up patches basically.

We fixed that one by adding the deleted image and that's the conservative choice this late in the 18 cycle, but in 19 have a better strategy, perhaps even just InstallDelet'ing all of %PROGRAMDATA%\Surge.

**Comment by baconpaul** [comment]
So @mkruselj what's the verdict?

1: make win like mac and lin and blow away all of surge on an install
2: make win different than mac and lin and maintain a list of all the directories *other* than tuning-library and blow that away on an install?

**Comment by mkruselj** [comment]
Yeah I think 2, Blow away everything except tunings.

**Comment by baconpaul** [comment]
OK
So just add the list then and it will work
