### ISSUE TITLE
Replace the OSC menu / Snapshot mechanism with a CMenuAsSlider

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3434]
Basically: config.xml is code 
and it is annoying in its implementation of the OSC menu for all the reasons we know (we need graphics; there's no submenus; etc...)

So rather than struggle with checkmarks and stuff and COptionMenu shenanigans, the real answer is to remove CSNapshotMenu and move it to a better configuration mechanism

So do this with OSC first where basically we use a CMenuAsSlider on data.

That data could still live in an resource xml file sure. But would be way smarter

Then we get wheel, checkmark, all that jazz, much more easily.

**Comment by mkruselj** [comment]
Basically same issue as #3111 and #726, so I'm closing those other two, but linking them here for reference.

**Comment by baconpaul** [comment]
the changes we've made in 1.9 mean we are fine to ship 1.9 as is and push this issue out to xt.

**Comment by baconpaul** [comment]
the way XT i shaping up, where the CSnapshots have-a vs is-a menu, this issue is no obsolete. When I jucify the CSnapshots I will do it differently than the MenuAs, more in line with what we already have in XT. So closing this issue as 'kinda done and kinda not where we ended up'
