### ISSUE TITLE
Linux Menus in MSEG windows

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#3444]
When r/clicking and element in between 3/4 and the right wall the submenu for Actions-Create-Settings will overlap the parent menu

At the farthest edge to the right the menu will expand left

I was wondering if it is possible to have that r/clicks to get to the menu that are from 51% to 100% when passing over Actions-Create-Settings will expand the submenu to the left and all others from 0% to 50% will expand to the right as usual

![mseg-menus](https://user-images.githubusercontent.com/41337033/102268464-5e942000-3ee9-11eb-9067-0ab5351b245b.gif)

At 25% expands right, no overlapping
At 75% expands right and overlaps
at 50% expands right, no overlapping
At 100% expands left, no overlapping

**Comment by baconpaul** [comment]
i can fix this but have to patch pretty deep into vstgui so want to not do it this late in the cycle. Tagging as 1.9

**Comment by baconpaul** [comment]
hmmm may see a way to do this tagging back into 18

**Comment by tank-trax** [comment]
I thought that due to it's expanding left when hugging to the right edge may have provided a clue. Just a hunch. Could be wrong though.

**Comment by baconpaul** [comment]
yeah its the same code
basically it is pushing left
but not accounting for the offset of being in

**Comment by tank-trax** [comment]
this is a wonderful tweak and works extremely well with the preset menus too

**Comment by baconpaul** [comment]
Super! Thanks for pointing it out and glad it works well for you.
