### ISSUE TITLE
Python Bindings

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3448]
Will make testing and DSP work so much easier

Over in `baconpaul/pybind` I already have this much working

<img width="600" alt="Screen Shot 2020-12-16 at 8 29 17 AM" src="https://user-images.githubusercontent.com/13387561/102354909-2cca9a00-3f79-11eb-885c-7b7e6fa731e7.png">

So complete this very very early in the 19 cycle.

At first, don't build it in the pipelines. This is a dev only extension for now.

**Comment by turian** [comment]
This is really great and I am following this issue.

TBH I have read countless papers on synthesis using AI. All of them resorted to really really janky solutions to using VST synths. There is not a single high quality synth that is easy to use via API. If Surge is the first synth that can do this, I expect you would see it being used for a lot of groundbreaking work.

**Comment by baconpaul** [comment]
For tomorrow

http://people.duke.edu/~ccc14/cspy/18G_C++_Python_pybind11.html#Using-numpy-arrays-as-function-arguments-and-return-values

**Comment by turian** [comment]
@baconpaul this is amazing. I haven't tried building it yet. Some questions about the API:

You write:

* process makes surge calculate a block of output. The block size is surge.getBlockSize()
* playNote plays a note on channel with velocity and detune
* releaseNote releases a note on channel
* getOutput returns a 2xBLOCK_SIZE numpy array with the most recent block

If you wanted multiple patches, they would each be a separate channel? Or effectively there can only be one channel? Either is fine just want to understand.

I'll make some q's /comment's about the first example code inline:
```
def playQuickC(surge):
    # Can you print surge.getBlockSize() for informational purposes
    # Why do you start with 10 process() commands if there's nothing to do?
    for i in range(10):
        surge.process()
    
    # What are the *four* parameters specifically?
    surge.playNote( 0, 60, 127, 0 )
    wave = np.array(0)

    # so range(50) determines how long you hold the note?
    for i in range(50):
        surge.process()
        # this is very inefficient of course
        # Why do you need to select the first two? What do the rows represent?
        # Is it always returning mono?
        wave = np.append( wave, surge.getOutput()[0,:])
    
    # Also missing what these three parameters do
    surge.releaseNote( 0, 60, 0 )

    for i in range(40):
        surge.process()
        wave = np.append( wave, surge.getOutput()[0,:])
       
    # I don't understand why this extra "ring down" process happens at the end
    # if we don't keep it in the wave. Also, if it's to let the note finish or whatever (even if
    # we don't trap it) how do we make sure this isn't too short (and the next stuff has ring
    # or too long?)
    # One of the reasons I ask is because I was to generate unique isolated sounds, not
    # play something continuous with many notes
    for i in range(40): 
        surge.process()  # ring down
    return wave
    
wave = playQuickC(surge)
plt.plot(wave)
```

**Comment by turian** [comment]
"A control gorup contains a set of entries" I don't exactly understand what entries are, versus the individual parameters in a control group.

**Comment by turian** [comment]
```
    r.append( [ par, 
      surge.getParamMin( par ), 
      surge.getParamMax( par ), 
      surge.getParamDef( par ), 
      surge.getParamVal( par ),
      surge.getParamValType( par )
    ])
```

What is def?

I see that the ints return floats, I'm okay with that. Are there any types besides float and int?

val is the current value of the parameter in surge?

**Comment by turian** [comment]
For this first plot, why is the x-axis to 3000?

![image](https://user-images.githubusercontent.com/65918/102498936-e198b000-407a-11eb-8090-f45c6ad64df1.png)

**Comment by turian** [comment]
"Finally, lets define a function which plays surge for about 4 seconds, with a key relese at second 3, and returns a smoothed RMS of the output. At this point it should be clear how to do that."

Why do you need do do RMS and convolve?  Why can't the output of surge just be taken as is?

Why does the x-axis go to 5000 in the x-axis if it's supposed to be 4 seconds?

![image](https://user-images.githubusercontent.com/65918/102499220-34726780-407b-11eb-8768-a5603713d2a1.png)

**Comment by turian** [comment]
"Similarly, we can save a patch to a file. Here we take the current surge with the DXEP save it to a tmp file, then load it in a new surge and show that works since the before and after has the saw vs the dx envelope"

I don't understand exactly, the two curves are different. If you save and load shouldn't they be identical?

![image](https://user-images.githubusercontent.com/65918/102499449-7a2f3000-407b-11eb-9fa8-a9c64a5008e9.png)

**Comment by turian** [comment]
```
fd = surge.getFactoryDataPath()
print( fd )
patch = fd + "/patches_factory/Keys/DX EP.fxp"
surge.loadPatch( patch )

# Spool some blank
# I  don't understand what this does or why we need it
surge.processFor( 10 )

# So this is 32 x 50 samples?
q = surge.createMultiblockStorage( 50 )
surge.playNote( 0, 60, 127, 0 )
# Does this basically process until q is full?
surge.processCollecting( q )

# Do we need to let it ring out again?

# The multiblock can become an np array without a copy
# Just curious, what is the python type of the multiblock?
a = np.array(q, copy = False )
```

**Comment by turian** [comment]
This is great btw.  Consider add 
IPython.display.Audio to the notebook in addition to the graphs?

**Comment by baconpaul** [comment]
All questions answered inline.

**Comment by baconpaul** [comment]
BP todo list:

1. add isValidModulation bindings
2. docStrings

**Comment by baconpaul** [comment]
OK PR #3455 materially finishes the first stage here so I'm going to close this issue once that merges. Added docstrings, missing functions, etc...

lets open individual issues if there are expansions or changes we want to make.

Cool. Glad I did this.

**Comment by jorshi** [comment]
Late to the party but very excited to see this got merged! Dittoing @turian's comment on the application for research. Just installed and was able to run the Jupyter notebook -- works great so far, looking forward to digging in more. Thank you!

**Comment by baconpaul** [comment]
Wonderful! Very happy to take PRs or suggestions. Just open a new issue here or hit us up on discord.

**Comment by reekystive** [comment]
Hi! I'm trying to use the Python bindings according to [this](https://github.com/surge-synthesizer/surge/blob/main/scripts/ipy/Demonstrate%20Surge%20in%20Python.ipynb) but got

```
make: *** No rule to make target 'surgepy'.  Stop.
```

when executing the second command:

``` bash
$ cmake -Bbuildpy -DBUILD_SURGE_PYTHON_BINDINGS=TRUE -DCMAKE_BUILD_TYPE=Release
# success

$ cmake --build buildpy --config Release --target surgepy
# make: *** No rule to make target 'surgepy'.  Stop.
```

Can anyone help? Thanks!

I'm using:

- Apple M1 Chip
- CMake Version 3.23.1
- Commit 98f490712ba240e352ece24d130e619cbd45a020

**Comment by baconpaul** [comment]
Oh sorry the target name changed to 'surge-python' when we moved to the new XT cmake layout

**Comment by reekystive** [comment]
Still failed :(

``` bash
$ cmake --build buildpy --config Release --target surge-python
# make: *** No rule to make target 'surge-python'.  Stop.
```

**Comment by baconpaul** [comment]
At head I just had this work:

```
cmake -Bignore/sp -DSURGE_BUILD_PYTHON_BINDINGS=TRUE
cmake --build ignore/sp --target surge-python
```

If that doesn't work for you please attach the full output of the first stage here.
THanks

**Comment by reekystive** [comment]
I figured it out.

`BUILD_SURGE_PYTHON_BINDINGS` was changed to `SURGE_BUILD_PYTHON_BINDINGS` XD

**Comment by baconpaul** [comment]
oh thanks! if you want to send a PR to update the README that'd be great :)

**Comment by reekystive** [comment]
There is another issue. After renaming, the compiled product is `surge-python...so`, which cannot be imported in python.

``` python
import surge-python
            ^
SyntaxError: invalid syntax
```

The `-` in filename must be deleted manually to import in python.

**Comment by baconpaul** [comment]
oh ha! well we should fix that. I'll open a new issue.

**Comment by reekystive** [comment]
> I figured it out.
> 
> `BUILD_SURGE_PYTHON_BINDINGS` was changed to `SURGE_BUILD_PYTHON_BINDINGS` XD

#6312 fixed this.
