### ISSUE TITLE
I can only type capitals.

### ISSUE THREAD

**Issue by magnetophon** [surge-synthesizer/surge#3452]
**Bug Description:**
Anything I type, be it the name of a patch, the name of a macro or a parameter value, get's interpreted as if I'm holding shift.
So "l33t" becomes "L##T".

**Surge Version**
Surge Synthesizer

Version:	1.8.fetchgit.dbdad6c

Build Info:	Built on 1980-01-01 at 00:00:00, using local host 'localhost'
System:	x86_64 CPU, Linux VST3, 64-bit
Plugin Host:	Ardour

**Computer Information (please complete the following information):**
 - OS: NixOS
 - Host: Ardour
 - Version: 6.5

**Comment by mkruselj** [comment]
Sounds like Ardour doesn't send Shift keypress to Surge. Could very well be an issue on their side (this works in other DAWs I have here on hand to test).

**Comment by magnetophon** [comment]
You mean Ardour always sends shift?
Could be: when I turn on caps-lock, I get small letters.

**Comment by baconpaul** [comment]
Do other plugins demonstrate the same behavior? Would start there.

**Comment by magnetophon** [comment]
I have never noticed that, and I use Ardour quite a lot.
Also, I don't know any plugins that allow me to type, off the top of my head.
Know any?

**Comment by baconpaul** [comment]
Surge? :)

But more seriously: our tuning-workbench-synth is a 100% Juce plugin which has typeins in the area where you specify an SCL field. Totally different code base.

**Comment by magnetophon** [comment]
It stopped doing it.
Can no longer reproduce.
No updates or changes done in between.

¯\_(_)_/¯

**Comment by baconpaul** [comment]
Huh well glad it went away i guess! Wonder what it was?

**Comment by magnetophon** [comment]
It came back.
This time caps did not invert it, neither did shift.
When I tried typing with both caps and shift, I got a a segmentation fault.
``
[1]    13225 segmentation fault (core dumped)  ardour6 ~/ardour/psy10/psy10.ardour
``

The next time I started ardour, I could type normally again.

**Comment by mkruselj** [comment]
@magnetophon Is this still happening for you?

**Comment by magnetophon** [comment]
It sometimes is, but I think the sensible thing to do is to wait for the JUCE port, as you seem to indicate with that label.

**Comment by mkruselj** [comment]
I really think this is an Ardour issue.

**Comment by mkruselj** [comment]
@magnetophon OK now that we're in JUCE port - is this still happening for you? 🙂

**Comment by magnetophon** [comment]
Fixed in XT!
