### ISSUE TITLE
Move surge to the separate-repo version of filesystem

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3463]
`libs/filesystem` is useful in contexts other than surge
so I put it in a repo at https://github.com/surge-synthesizer/surge-filesystem
but I didn't move the surge pointer since we are late in cycle
move it early in 1.9

**Comment by mvf** [comment]
I looked into this and strongly advise against using `Surge::filesystem` in new projects that don't have an existing user base on pre-C++17 macOS. See https://github.com/surge-synthesizer/surge-filesystem/issues/7 for an essay.

**Comment by baconpaul** [comment]
Yeah 10.15 is not a realistic minimum version of macos for our user base; and gcc9 is not a realistic minimum compiler version for our linux user base. Many of our users are still on 10.14, for instance, because they need to retain 32 bit support. So our distribution of surge is gonna be macos 10.11 (maybe 10.12 so we can get 17-without-fs) or greater and gcc 7 or greater for a long time.

That said, over on that issue I shared an alternative more complete MIT implementation of std::filesystem which we could use instead of this. Open to that.

**Comment by baconpaul** [comment]
So as discussed over in that issue, the approach in SC was not to couple to a repo version of our filesystem, but a different implementation of a filesystem for mac < 10.15 and gcc < 9.

SC3 will do that. We should consider doing the same for surge in 1.9 and going to a much thinner bit of code we support.

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/shortcircuit3/pull/61 there's the PR moving to the other FS impl

**Comment by baconpaul** [comment]
#3589 is my proposed solution. Closing this now and will delete the surge-filesystem repo also.
