### ISSUE TITLE
MSEG doesn't snap to vertical grid when in "Draw" mode

### ISSUE THREAD

**Issue by MaZe6K** [surge-synthesizer/surge#3473]
**Bug Description:**
When in Movement Mode "Draw", nodes of the MSEG don't snap to the vertical grid if Snap To Grid "Vertical" is activated

**Surge Version**
Version:	1.8.nightly.ab4c780
Build Info:	Built on 2020-12-18 at 21:19:43, using pipeline host 'fv-az73-589'
System:	Intel CPU, Windows VST3, 64-bit
Plugin Host:	Fruity Wrapper

Windows 10, FL Studio 20.8

**Additional Information:**
That MSEG is gooooood!!! Perfect editing options, smooth UI

**Comment by baconpaul** [comment]
Thank you! Will look a and fix this weekend

**Comment by baconpaul** [comment]
Should be fixed in next nightly.
