### ISSUE TITLE
Bug with new feature in 1.8: Swap of FX-units

### ISSUE THREAD

**Issue by snesmagic** [surge-synthesizer/surge#3488]
**Bug Description:**
Bug with new feature in 1.8: Swap of FX-units(also work with empty slots)

**Surge Version**
* Version: 1.8.nightly.9b48ad9
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Go to FX-section
2. Click on empty slot
3. Swap it with any slot
4. Crash without error

**Expected Behavior:**
-

**Screenshots:**
-

**Computer Information (please complete the following information):**
 - Windows 10
 - Cakewalk by Bandlab
 - 2020.11 Update 1

**Additional Information:**

https://user-images.githubusercontent.com/49315538/102723611-33129a80-431a-11eb-8d25-85bb65bc9939.mp4

**Comment by baconpaul** [comment]
Thank you fro the clear report.

I just took a look at the code and I think I might have a threading error between the UI and Synth code. That would mean that it works sometimes, but if you do it a lot quickly it might occasionally crash. I think that’s what your video shows but just want to confirm.

It that’s what you see that makes perfect sense with the way it’s implemented now (and I can fix it pretty easily too).

Appreciate the beta test.

**Comment by baconpaul** [comment]
Ahh I was able to reproduce this by stress testing surge on my mac.

If I make the ::idle loop swap fx every 2 idles while in latch mode, eventually I do crash

It is indeed a threading thing

Thank you for the report. I would never have found this were it not for it and now I have a clear path to fixing it.

**Comment by baconpaul** [comment]
I just merged a fix for this which should be in a nightly in about an hour. Thank again for the report. Very yuseful.
