### ISSUE TITLE
MSEG: "Action -> Quantize notes" is acting weirdly when in LFO mode

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#3506]
It seems like some nodes go out of bound (above phase = 1) when using either of those 2 options. Here's a demo of one such issue:
![MSEG](https://user-images.githubusercontent.com/50145178/103040499-9b8f9080-4541-11eb-9afa-5a2bc628ac75.gif)

Switching to Envelope mode, then back again to LFO mode fixes it until you quantize again.

Maybe we should gray out "Quantize to whole units" when in LFO mode by the way?

**Comment by mkruselj** [comment]
Yeah probably the best solution to gray the quantize actions out.

**Comment by baconpaul** [comment]
Quantize to even spacing still makes sense right? But agree. Also for sanity make the model operators return immediately if they are not valid on an lfo in case we use them in other contexts
