### ISSUE TITLE
Switch to Random Bipolar (for example) doesn't immediately update target modulation slider tray color

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#3519]
After selecting the Random modulation source and applying modulation to a parameter, its slider tray will become darker blue, which is all good. But then, if we switch from Random to Random Bipolar for instance using the context menu option while keeping that mod source selected, the slider tray will still be darker blue indicating that it's being modulated by the currently selected modulation source, when in reality it's not since we're now on Random Bipolar instead of Random. 
If we select another mod source and come back to Random Bipolar (or enter routing mode), the slider tray will be updated and be lighter gray, as it should be.

So I guess we should do some sort of UI refresh when switching modulation type with the context menu?

This also applies to Alternate as well.

**Comment by baconpaul** [comment]
Oh yeah the alternates should do a refresh rebuild. Great catch. Easy fix this weekend.
