### ISSUE TITLE
Possible issue between comb filter and distortion when going from sv14->sv15?

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3521]
j5v reports that one of his sv14 patches (created after the comb filter fix was merged, since it does have the Precise tuning option checked) doesn't seem to sound correct in sv15 Surge.

[LS_Lead_Guitar_Theme_3.zip](https://github.com/surge-synthesizer/surge/files/5743110/LS_Lead_Guitar_Theme_3.zip)

Try opening the above patch in 6571f4a7 and then compare with latest nightlies. Disable all effects except distortion. There's definitely something wrong here.

**Comment by baconpaul** [comment]
Can you be more precise on what 'definitely something wrong here' is? Like i did that and they sound the same to me, but it was 2 minutes apart while I rebuilt.

**Comment by baconpaul** [comment]
yeah play a power chord in the middle octave
def doesn't sound the same here
https://discord.com/channels/744319641211633774/744324663383031821/792372879638396938
also j5v explained his take on it here

**Comment by mkruselj** [comment]
Oh also I had both versions running side by side in two savihosts... unsure if you can do the same with HostingAU?

It's quite obvious going between one instance and another playing same notes.

**Comment by mkruselj** [comment]
And now I cannot get any differences between 6571f4a and head. Twilight zone, folks.

**Comment by baconpaul** [comment]
I think the patch loading bug for bitwig I fixed this morning may be the issue 

that reaper thread fix I am glad we did but makes me nervous

**Comment by baconpaul** [comment]
@mkruselj any idea what to do with this issue?

**Comment by mkruselj** [comment]
I don't have an idea tbh... I can't repro it anymore.

**Comment by mkruselj** [comment]
OK so I tried to again compare `6571f4a` and head, no difference. Closing issue!

**Comment by mkruselj** [comment]
And actually we might have found what the issue was (or rather, @baconpaul did), so 1.8.2 should fix this issue - if you used the Hard model in Distortion effect, it sounded wrong because the waveshaper curve was borked.
