### ISSUE TITLE
Surge cross-platform standalone

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3525]
We have Surge. We have JUCE in repo that is used for the effects bank.

We can use JUCE to create standalone executables for Win/Mac/Linux basically hosting the VST3 but without requiring firing up a DAW. Our own minihost basically.

Make it look as minimal as possible. We only really need a toolbar and very few options (MIDI, audio I/O). Virtual QWERTY keyboard would be a bonus (unsure if JUCE host has that, great if it does, minor bummer if it doesn't).

Would be a terrific 1.9 feature!

**Comment by mkruselj** [comment]
Not being able to have ASIO enabled on our binaries due to licensing shenanigans puts a huge damper on this FR, at least on Windows side... What a huge bummer...

**Comment by baconpaul** [comment]
Gonna close this since the JuceXT already builds it and we won't do it with VSTGUI.
