### ISSUE TITLE
Skin engine image default folder tag

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3527]
@baconpaul will know what to do!

**Comment by baconpaul** [comment]
So 
1: add a new tag 'image-root' which everything is relative to
2: default is ""
3: IF it is set and default image is not set, default image dir is also image-root
4: IF it is s et and default image dir is set, default image dir is relative to image root
5: All image resources are relative to image root

That way all existing skins work
And for @mkruselj to use this just replace default image dir wot image root
And if you want your bmpblah in a subdirectories of your imageroo you can

**Comment by baconpaul** [comment]
So we were able to write nicks skin without this restructuring. It's a wee bit hairy so I'm going to push this into 1.9

**Comment by mkruselj** [comment]
I still kinda wanted to have this one even for Nick's skin... :(

**Comment by baconpaul** [comment]
yeah but you don't need it. it's changing c++ code used in every single render instance or type a few extra chars into an xml file. Easy choice right?

**Comment by mkruselj** [comment]
@baconpaul Ditto as with skinheritance, not really valid for XT2?
