### ISSUE TITLE
Osc drift in combination with unison causes clicks

### ISSUE THREAD

**Issue by TheNerdyMusicGuy** [surge-synthesizer/surge#3529]
Using the classic osc with some amount of unison voices, detune and osc drift causes clicks.

1: From the default patch increase osc1 unison voices, unison detune and osc drift to max
2: hold a note and listen to the clicks

Setting the sync slider to something other than 0 seems to fix the issue.
This only happens with the classic osc.

Surge Synthesizer
Plugin Host: Ableton Live 10.1
System: Intel CPU, Windows VST3, 64-bit
Build Info: Built on 2020-12-25 at 23:17:11, using pipeline host 'fv-az74-298'
Version: 1.8.nightly.7c10e73

**Comment by mkruselj** [comment]
Definitely related to my osc sync fixes. So the first commit before bf772010 has things behaving nicely (apart from that gnarly click when you move sync away from 0.0% while holding a note).

**Comment by baconpaul** [comment]
Some notes to self

1. You can get it with unison voices = 2 just as well
2. You can hear the click then happens about once a drift cycle
3. I am about 90% sure that caused by the assumption that sync is always 'behind' the osc (that is the sync is a higher frequency sync) being violated because (1) bf77201 always runs the sync and (2) the lfodrift can go negative
4. I am not sure how to fix that yet but i bet there's a judicious choice when the detune lfo pushes synch ahead of osc to wait a little which we can insert somewhere
5. tricky tricky though. tricky. and a bit scary.

**Comment by baconpaul** [comment]
oh and of course, the 4th thing above explains why sync of almost any non-zero value would fix it; that is, the sync having any value would outstrip the detune drift which is very small compared to any value in semitones. I bet if you used the VST3 API to set the sync to 0.0001 or some such you might still get a click at head.

Speculation from reading the code, to be clear, but...

**Comment by baconpaul** [comment]
For reference the drift noise we apply is an incredibly aggressively filtered rand basically, scaled down to a very small amplitude

```
float drift_noise(float& lastval)
{
   const float filter = 0.00001f;
   const float m = 1.f / sqrt(filter);
   //__m128 mvec = _mm_rsqrt_ss(_mm_load_ss(&filter));
   //_mm_store_ss(&m,mvec);

   float rand11 = (((float)rand() / (float)RAND_MAX) * 2.f - 1.f);
   lastval = lastval * (1.f - filter) + rand11 * filter;
   return lastval * m;
}
```

**Comment by baconpaul** [comment]
OK here is a way easier way to replicate

1. Take surge at head
2. Modify line 339 of SSO to say

```
 float detune = 100 * drift * driftlfo[voice];
```

that is make the detune 100 times larger.
3. Open the init patch and play a single note
4. increase detune. Will start clicking around 5%

Interestingly if you move sync off zero (like set it to 0.0001 with the RMB) at all you get no clicks. 

To get clicks you need sync identically at zero
