### ISSUE TITLE
Surge forgets setttings after disabled in Bitwig

### ISSUE THREAD

**Issue by Jurek-Raben** [surge-synthesizer/surge#3531]
**Bug Description:**
Surge forgets its settings/preset after it was disabled in Bitwig. It then resets to the default preset.

**Surge Version**
Recent V1.8 build
<img width="142" alt="grafik" src="https://user-images.githubusercontent.com/239679/103171973-5aa0c000-4850-11eb-912f-1d7a60052456.png">

* Version:
* Plugin Type: VST3
* Bitness: 64bit

**Reproduction Steps:**
1. Load Bitwig 3.31 on macos
2. Load surge vst3, edit a preset
3. Set plugin to disabled (apple + A or so on macos)
4. Enable it

**Expected Behavior:**
Should not forget settings in any case.

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Host: [e.g. Bitwig, Logic, Cubase, Reaper]
 - Version: [e.g. 2.4]

**Additional Information:**

**Comment by baconpaul** [comment]
So here's what's happening

If you load a patch and activate/deactivate the patch comes back but your modifications do not. So load mega synth, de- and re-activate and you get mega synth.

But load mega synth set pitch to something else, activate deactivate and you loose your pitch setting.

I have a suspicion that it is also related to the deferred vst load crash avoidance we put in place and messages arriving out of order.
