### ISSUE TITLE
Oscillator and LFO display in zoom mode

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#354]
Now we have zoom coming together, the oscillator and lfo display drawing code show their pixelation at large zooms. Either increase the resolution based on zoom in CLFOGui or do something else clever or live with it and close this issue, but put in a placeholder so I don't forget.

**Comment by baconpaul** [comment]
Tagging this to #305

**Comment by esaruoho** [comment]
pixelated examples
<img width="446" alt="image" src="https://user-images.githubusercontent.com/4966687/53816190-d0e17d80-3f6b-11e9-8c60-370c8228ccbf.png">
<img width="433" alt="image" src="https://user-images.githubusercontent.com/4966687/53816226-e0f95d00-3f6b-11e9-9245-9bee9ba1c706.png">

**Comment by baconpaul** [comment]
I have a cunning plan hatching for this and wavetables ...
