### ISSUE TITLE
What's on deck

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3546]
Locked issue to sort issues from the active milestone by rough order of execution.

1.9 early plan:

**Easy Stuff**
#2224

**Code Cleanups**
#3204
#3351
#2130
#3435
#3427

**Oscillators**
#3434
#3468
#3171
#3273

**Comment by baconpaul** [comment]
Some branches which do some of these

- `baconpaul/19-location-3414` will close #3414

**Comment by baconpaul** [comment]
I think we should close this issue now we have re-set-up the 182 and xt milestones. Agree? 

I unpinned it in any case!

**Comment by mkruselj** [comment]
Agreed!
