### ISSUE TITLE
Element Position from SVG

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3548]
If we have an SVG with well named ids, can we use that rather than skin control for positioning?

Open questions

1. xywh sure but what about class features?
2. parse etc
3. tabs

**Comment by h-v-b** [comment]
Here is a work in progress of the classic skin with most objects named according to their ids.

[Surge_Classic_Preview_with_IDs.svg.zip](https://github.com/surge-synthesizer/surge/files/5751737/Surge_Classic_Preview_with_IDs.svg.zip)

**Comment by itsmedavep** [comment]
What would be a test for something other than Figma?

Or rather another way of stating it:

What would be the necessary pieces to do this in Sketch?

1) Name layer appropriately
2)??????

**Comment by mkruselj** [comment]
Basically yeah, just name layer appropriately. We still have to spec it fully out, because we might want to have custom class definitions in the layer name and other skin engine arguments too...

**Comment by baconpaul** [comment]
Yeah exactly i can't couple this to figma since I only read SVG

We had discussed something like `id="lfo.rate<CKnob>;feature=val;feature=val"` being the micro syntax we push into the id (with `id="lfo.rate"` just taking the default)

**Comment by h-v-b** [comment]
@itsmedavep the best thing is to first check how sketch exports an svg with ids.

I'm not familiar with the software, but a quick google search led to this Sketch plugin which should let you do an SVG export with unique ids (such as for every slider)

**Comment by baconpaul** [comment]
oh and I can use a tag other than id also if the tools hijack id for their own use. I just need some tag on the element I can read.

**Comment by baconpaul** [comment]
(when I do this)

**Comment by mkruselj** [comment]
@baconpaul Ditto as with skinheritance, not really valid for XT2?
