### ISSUE TITLE
Airwindows: Typeins not preventing invalid entries

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3549]
Currently, if we try to edit Airwindows FX parameter values and we type a value that is out of range, the typein will not report Invalid Entry in red letters like it does for any other Surge parameter typein. Instead it ceils or floors the parameter, which is a pretty dangerous thing considering a lot of these params play with gain (with considerable ranges too)...

**Comment by baconpaul** [comment]
The mechanism to do this is in the code, just none of the AW use it.

`parseParameterValueFromString` has return type bool

If that returns `false` Surge will treat the input as invalid and leave the dialog open
If it returns `true` Surge will accept the value
But Surge will also force the value into min/max in case the true was wrong
Which is what you are seeing.

Closing this now. The API is in place. We just need to apply it to every AW.
