### ISSUE TITLE
Implement Zoom on Macintosh and Windows / VST2

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#356]
With #348 in place allowing full scalable zoom on AU driven by menu with proper retina assets, we need to implement Macintosh / VST2 zoom. All part of the #305 family of issues.

**Comment by baconpaul** [comment]
<img width="1921" alt="screen shot 2019-01-20 at 8 47 58 pm" src="https://user-images.githubusercontent.com/13387561/51448450-ca1ce500-1cf4-11e9-8e47-01c5d5a34f87.png">

So the VST2 API partially supports zooming but has quite a few bugs which are quite hard to work around. Still not perfect but getting closer this evening.

If you want to try it bugs and all checkout branch 'zoom-vst2-356' but it is very flaky now. Especially menu positions pop up in the wrong place when you are zoomed which is tough.

**Comment by baconpaul** [comment]
OK so here's the state of play on this

On the branch `baconpaul` `zoom-vst2-356` is a (not ready for merge yet) branch which implements zoom on both mac and windows using only the vstgui and vst2 apis. That is, it calls ::setSize in the vst2plugin and frame->setZoom() in the SurgeGUIeditor. On windows, of course, you don't get scalable assets so big zooms look cruddy.

But there are two bugs on vstgui, only one of which I can get around

1. The frame setZoom does not apply the zoom to the frame background image so I have to do a gross workaround specifically for the background in collaboration between SurgeGUIEditor and CScalableBitmap. This is barely commented now also but you'll figure it out
2. Way more importantly, with setZoom set COptionMenu popup in the wrong place both mac and windows. I do not know a workaround for this one at all. Probably something to do with a transform forgotten.

Both these bugs, but especially the second which I can't hack around, is what inspired #373 last night.

But good news: Using the portable vst api to implement zoom in vst did in fact implement zoom.

**Comment by kzantow** [comment]
@baconpaul so an interesting thing about the menu offset: **both the patch drop-down and the effects drop-down are positioned properly**, however all the right-click menus and the 'menu' button are not. hope that helps to diagnose/fix the issue!

**Comment by baconpaul** [comment]
So useful. Thank you.

**Comment by baconpaul** [comment]
OK just as notes-to-self

The patch browser pops up a menu in the onMouseDown handler where it uses the coordinates handed to it by the event system

The slider and menu button use the alternate pattern of sending a message back to the parent class and then the parent class uses frame->getCurrentMouseLocation and then frame->localToFrame

Two errors here

1. We are ignoring the return value of localToFrame but it doesn't matter since it is a no op
2. frame->currentmouseposition is returning a result that is double scaled. So at 1x you get 1x; at 1.25x you get about 1.58x; and at 2x you get 4x.

So I could whack this to just do an inverse zoom transformation on the point with a comment that 'this is a big ugly bug" but let me poke a wee bit more. Recording this note to myself in case I take a break coz this is the type of thing I forget when I stop halfway through.

**Comment by baconpaul** [comment]
Huh and would you look in cframe.cpp

```
bool CFrame::getCurrentMouseLocation (CPoint &where) const
{
	if (pImpl->platformFrame)
	{
		if (pImpl->platformFrame->getCurrentMousePosition (where))
		{
			getTransform().transform (where);
			return true;
		}
	}
	return false;
}
```

**Comment by baconpaul** [comment]
Oh yeah yeah that's it. That transform I think should be a .inverse() transform (or another one should be).

If I do this

```
      frame->getCurrentMouseLocation(where);
      
      where = frame->frameToLocal(where);
      frame->getTransform().inverse().transform( where );
      frame->getTransform().inverse().transform( where );
      
      menuRect.offset(where.x, where.y);
```

when I pop the menu everything works.

So somewhere in vstgui it is doing a transform the wrong way in this code path.

But this means I can now make zoom work VST2 mac and windows with just one nasty hack which is to insert that double inverse transform in on VST2. So big comment block and switch coming.

**Comment by baconpaul** [comment]
Yup that is definitely it. Applying that consistently and also working around the background image zoom give a 100% functional vst2 zoom implementation mac and windows.

It's all checked in on baconpaul branch zoom-vst2-356

not ready to pull yet. As well as adding comments and doing some code cleanup, I need a no-cruddy implementation of getScreenDimensions on windows. SO another few days before this is pull-able but any testing now would be great.

**Comment by baconpaul** [comment]
https://docs.microsoft.com/en-us/windows/desktop/api/shellscalingapi/nf-shellscalingapi-getscalefactorformonitor

https://cppkid.wordpress.com/2009/01/07/how-to-get-the-screen-resolution-in-pixels/

For notes for later

**Comment by baconpaul** [comment]
Merged
