### ISSUE TITLE
Surge segfaults ardour on store

### ISSUE THREAD

**Issue by magnetophon** [surge-synthesizer/surge#3560]
**Bug Description:**
A couple of times, surge has segfaulted ardour at the moment I clicked OK in the store dialog.

**Surge Version**
Surge Synthesizer

Plugin Host:	Ardour

System:	x86_64 CPU, Linux VST3, 64-bit
Build Info:	Built on 1980-01-01 at 00:00:00, using local host 'localhost'
Version:	1.8.fetchgit.c70d689

**Reproduction Steps:**
1. Click on 'store'
2. Click on 'OK'
3. Some times: segfault

**Computer Information (please complete the following information):**
 - OS: NixOS
 - Host: Ardour
 - Version: git 2020-12-22

**Comment by baconpaul** [comment]
Do you get a stack ever?

**Comment by baconpaul** [comment]
On this one actually can you do me a favor? I suspect it is zenity and a blocking call screwing up the UI thread. We have an issue to rewrite this in 1.9.

But to test that

1. Open src/linux/UserINteractionsLinux.cpp
2. Find the function 'promptOKCancel
3. right before this line `size_t pid = vfork()` type 'return UserInteractions::OK;`, recompile and build

this means you won't get a prompt on overwrite but if you also don't get a crash it tells us stuff.

**Comment by baconpaul** [comment]
Oh also what's up with 'fetchgit' in your branch name in the version?

**Comment by magnetophon** [comment]
> Do you get a stack ever?

I haven't figured out yet how to to stacktraces of ardour on nixos.

> I suspect it is zenity

That surprises me: in the package of previous versions I had to patch the path to zenity in the code, so it would work on NixOS.
In the current version, there is [no mention of zenity in the code](https://github.com/surge-synthesizer/surge/search?q=zenity&type=code), except in comments and in the deb pkg, so I figured zenity was not used anymore.
What's going on?

> this means you won't get a prompt on overwrite but if you also don't get a crash it tells us stuff.

I patched, but since the bug only happens sporadically, I'm not sure if that will tell us much.

> Oh also what's up with 'fetchgit' in your branch name in the version?

That is the name of the nix function that fetches the source.
IDK how it ends up there.

**Comment by baconpaul** [comment]
Zenith is definitely still in the code 

https://github.com/surge-synthesizer/surge/blob/f558f0b5cc41f32be8055239021e2d818ed58381/src/linux/UserInteractionsLinux.cpp#L109

The ok cancel blocks the ui thread with zenity and I suspect that is the problem 

#3435 talks about removing this zenity use in 19

**Comment by baconpaul** [comment]
Ha OK so I'm totally wrong about the zenity but for the wrong reason which is our check to disable zenity for this in bitwig is coded incorrectly so this ok/cancel never occurs on linux

Fine the crash must be something else. I'm going to bounce this one into 19 since it is occasional and I couldn't repro but it would be lovely to know how ardour devs grab stack traces, if they do, on linux.

**Comment by magnetophon** [comment]
Ardour stack traces on linux are not a problem, I just haven't been able to do it on NixOS.

Here's how to do it:
https://ardour.org/debugging_ardour

**Comment by mkruselj** [comment]
@magnetophon Is this issue still happening with Surge XT?

**Comment by magnetophon** [comment]
Is XT out? How does one build it?

**Comment by mkruselj** [comment]
It's not officially released yet (should be sometime this Fall) but it's been at head of the repo for some time now. I recommend cloning into a new repo, not continuing from the old non-JUCE repo state.

**Comment by magnetophon** [comment]
Fixed in XT!
