### ISSUE TITLE
macro values are not restored in ardour

### ISSUE THREAD

**Issue by magnetophon** [surge-synthesizer/surge#3561]
**Bug Description:**
When I close and re-open an ardour session, the surge macros are all set to 0.

**Surge Version**
Surge Synthesizer

Plugin Host:	Ardour

System:	x86_64 CPU, Linux VST3, 64-bit
Build Info:	Built on 1980-01-01 at 00:00:00, using local host 'localhost'
Version:	1.8.fetchgit.c70d689

**Reproduction Steps:**
1. Create an ardour session with surge instrances that have non-zero macros.
2. Save it
3. Close ardour
4. Open ardour
5. The macros are now set to 0

**Computer Information (please complete the following information):**
 - OS: NixOS
 - Host: Ardour
 - Version: git 2020-12-22

**Comment by baconpaul** [comment]
Confirmed with ardour caf55e105e5

**Comment by baconpaul** [comment]
OK I know why this is happening - it is similar to the other thing where Ardour is legitimately using an API other DAWs don't - and surge is responding incorrectly. 

I might be able to fix it. Looking.

**Comment by x42** [comment]
I'm already curious what that might be :)

I also just had a look too. Ardour's state restore function first sets all ports and then loads a plugin's custom state.

The entry point is
https://github.com/Ardour/ardour/blob/d92d70718052937e2bea69ec0a8af15b316afbe9/libs/ardour/vst3_plugin.cc#L525-L560
which then calls `VST3PI::set_parameter_internal`

I've added some printf() there and the port is correctly set (here first macro param, with value 50%
```
VST3PI::set_parameter_internal id = 20480 normalized value = 0.500000
```

So I guess the problem might be that the custom state when restoring `Vst::kControllerState` overwrites this again.
(setting this state in addition is needed for some plugins that do not expose all controls and kComponentState isn't sufficient)

**Comment by x42** [comment]
Ah, much simpler :) another `getParamNormalized` related issue.

Thanks for the quick fix!

**Comment by baconpaul** [comment]
So basically you do a setState then do a getParamNoramlized and a setParamNormalized on some items. No other DAW does that but who cares, you are not wrong to do that

Surge had a thing where setState - for these 8 macros only - set their *target* value not their *value* (these are smoothed interpolators). Again our smoothing is super quick so who cares. A couple of ::process calls and you are good.

But the combination of your *valid* usage and our *invalid* (or really *deferred*) initialization means that you asked me for the value I said "my value is 0 but it will be .45 in the future" and you say "fine 0 it is" and I say "OK now I am 0 and will be 0 in the future"

So instead in my init path I say "your value will be .45 and we are loading a patch to, so it is .45"

5 char change. but took a bit of debugging.

**Comment by baconpaul** [comment]
Ha and once again you and I found the same bug from different sides of the call stack.

**Comment by baconpaul** [comment]
Anyway all merged and fix will be in our 1.8 release in a week or two.

**Comment by magnetophon** [comment]
:tada:

**Comment by x42** [comment]
> So basically you do a setState then do a getParamNoramlized 

Yes. Under the hood, Ardour's GUI control widgets are all spin-boxes that allow users to enter numeric values in the _plain_ range, but when rendering the spin-box as sliders the value is normalized  0..1 * silider-length.

The mapping may be log-scale or exponential, so we have to ask the plugin to normalize any real/plain values.

Ardour's design is historically based on LADSPA where parameters are not normalized. Also LV2 (and AU) report the actual range by default.  Most other hosts likely implemented VST first, and are built with the assumption that parameters are always in the  0..1 range.
