### ISSUE TITLE
Can we implement this wave folding oscillator?

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3562]
http://www.dafx17.eca.ed.ac.uk/papers/DAFx17_paper_82.pdf

h/t @mkruselj for the link

**Comment by mkruselj** [comment]
Just as an additional note: that paper only explains the wavefioder part of the oscillator, this does not oscillate per se. Usually we would have 2 OP analog FM coming into this wavefolder, on a West Coast style synth.

Analog FM meaning we would need to have cleaner FM by not using naive waveforms like we do in Sine, FM2 and FM3 oscs..

**Comment by mkruselj** [comment]
More info (more electronics, not really DSP related): https://modularsynthesis.com/roman/buchla259/259cwg.htm

[Buchla 259 manual](https://modularsynthesis.com/roman/buchla259/Buchla%20259%20Description%20-%20Buchla%20Synthesizer%20User%20Guide%2011-16-1981.pdf)

**Comment by mkruselj** [comment]
https://vimeo.com/137696291

https://vimeo.com/137703047

https://vimeo.com/137706198

**Comment by baconpaul** [comment]
So this wavefolder - from exactky this paper - is now in the codebase. We still want fm4 but that’s a separate issue so let me close tbis one
