### ISSUE TITLE
FX value overlays missing: some parameters of some FX in some slots

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#3563]
**Bug Description:**
Missing value overlays while dragging some FX sliders, in some positions.

**Surge Version**
Surge Synthesizer
Plugin Host:	Cakewalk
System:	Intel CPU, Windows VST3, 64-bit
Build Info:	Built on 2020-12-24 at 16:08:57, using pipeline host 'fv-az80-319'
Version:	1.8.nightly.9c75b6a

**Reproduction Steps:**
1. Click an effect in the FX circuit diagram
2. Move one of the sliders with the mouse.
3. For some parameters [detailed below], no overlay box appears, so the value is unknown. Workaround: right-click afterwards.

**Expected Behavior:**
I should see a value in an overlay box, changing as I drag.

**Screenshots:**

**Computer Information (please complete the following information):**
(as above)

**Additional Information:**
Parameters where I see no value overlay:
1. Chorus, anywhere in the top [A] row: Modulation Rate, Delay Time.
2. Conditioner, anywhere in the top [A] row: EQ Bass, SQ Treble.

If I move the effect into a different slot in the diagram (not the top row), the previously-missing values *might* appear, depending where they are moved to.

If I move the effect out, and then create the same effect in the vacant slot, the parameters that had missing overlays before are again missing.

Tried at different zoom levels; no difference observed.

**Comment by mkruselj** [comment]
This seems to be Cakewalk related, as I cannot confirm this happening in SAVIhost, Reaper, Live 10, Studio One 4, Reason, FL Studio 20...

**Comment by j5v** [comment]
I can't reproduce it in a new session.
The above session crashed while I was arranging effects within the FX diagram.

I'll give it a prod occasionally, and come back here if I find anything new. We might not resolve this for 1.8.

**Comment by TheNerdyMusicGuy** [comment]
This bug has been around for quite a while, but it only happens sometimes, but when it does, it's super consistent. It's super strange.

The strange thing is, this always happens on the same sliders for the same effects. It's almost almost the very first slider, but it's the second slider for the delay (can't remember which one that is at the moment), for example.

This is in Ableton Live.

**Comment by baconpaul** [comment]
OK
My guess is it is something like 'change an FX with the info window open blows you up'
but i'm gonna bounce this into 19

**Comment by j5v** [comment]
I can't reproduce the problem in XT

> Version:  Surge XT 0.9.nightly.04931e2
Build:  2021-08-26 @ 19:27:26 on 'fv-az421-743/pipeline' with 'MSVC-19.16.27045.0' using JUCE 60100
System:  Windows 64-bit VST3 on Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Host:  Cakewalk by Bandlab

**Comment by mkruselj** [comment]
Great so let's close the issue!
