### ISSUE TITLE
"Add modulation from..." option should not include voice-level modulators for Scene parameters

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#3564]
Here for instance, Voice LFOs (or any other voice-level mod source) shouldn't appear in the list of available modulation sources to modulate Send FX 1 Return:

![image](https://user-images.githubusercontent.com/50145178/103450626-25003a80-4c87-11eb-9e1a-71d8adae94af.png)

**Comment by baconpaul** [comment]
This is a check to synth->isValidModulation at menu construction time

**Comment by mkruselj** [comment]
Good one and rather easy fix even this late in the cycle I'd say...
