### ISSUE TITLE
AirWindows into Config.xml

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3569]
As discussed with @mkruselj 

if we do this by hand it will kill us. think I can use surgery to get a lot of the way there.

**Comment by mkruselj** [comment]
I started working on this but found out that for some reason we cannot have multiple subfolders for an effect. Example XML (renamed to .txt):

[configuration.txt](https://github.com/surge-synthesizer/surge/files/5760447/configuration.txt)
