### ISSUE TITLE
Support for subfolders in FX presets

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3570]
If we manually rearrange .srgfx presets in subfolders, they still show up as a flat list in the plugin itself, unfortunately.

LFO presets support subfolders, so it'd be nice and consistent if FX presets did the same. Let's try and make it happen before 1.8 release, maybe?

**Comment by baconpaul** [comment]
no way it happens before 18
this is a totally different codepath (the snapshot menu) we are going to rewrite anyway which is fragile 
tagging into 19

**Comment by baconpaul** [comment]
If the above PR merges this really us just save-with \ or save-with / makes subdirectories. Rest should just work.
