### ISSUE TITLE
Deferred Asset Manager

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3573]
1. The SurgeExtraContent repo gets an azure pipeline which makes well named tars and a json of them
2. We grab that from surge in an 'extra content' menu
3. You can download that extra content into your user area
4. Update, etc...

All for XT at some point

**Comment by mkruselj** [comment]
@baconpaul Considering Skin Library and all that, I really wonder if we really need this feature at all anymore?

**Comment by baconpaul** [comment]
Agree
