### ISSUE TITLE
Oscillator mute automation is not played back in Ardour 

### ISSUE THREAD

**Issue by magnetophon** [surge-synthesizer/surge#3576]
**Bug Description:**
I can record oscillator mute automation just fine, but it doesn't play back.
I can record and play back macro automation just fine.

What can I do to find out if this is an Ardour bug or a Surge bug?

**Surge Version**
Surge Synthesizer

Plugin Host:	Ardour
System:	x86_64 CPU, Linux VST3, 64-bit
Build Info:	Built on 1980-01-01 at 00:00:00, using local host 'localhost'
Version:	1.8.fetchgit.710a7eb

**Computer Information (please complete the following information):**
 - OS: NixOS
 - Host: Ardour
 - Version: git 2020-12-22
out the problem here.

**Comment by baconpaul** [comment]
Do you ahve the same problem in any other DAW? That's the first thing I would check.

**Comment by baconpaul** [comment]
also like: how do i even install ardour git and record an automation?

**Comment by magnetophon** [comment]
It works in reaper.

I get the same behavior with Ardour 6.5, which you can download [here](https://community.ardour.org/download).

Since the automation of other parameters works, it's still not 100% sure where the bug is, correct?

**Comment by baconpaul** [comment]
Anyway I just tried Surge @ head mac vst3 in REAPER and had no problem recording and playing back mute automation button. the solo automation seems broken (it sends the event but doesn't update the UI) but mute no problem. Solo is "funny" though

**Comment by baconpaul** [comment]
> Since the automation of other parameters works, it's still not 100% sure where the bug is, correct?

correct

**Comment by x42** [comment]
* Does it always? Directly after adding the plugin, or only later after re-loading the session?
(I'm thinking that perhaps `Vst::ParamID` mismatches with Ardour's sequential index.)

* Also how dense is the automation?
(Ardour's current implementation of the `Vst::IParamValueQueue` allows only 64 changes per process cycle.)

**Comment by baconpaul** [comment]
It is absolutely the case in surge that sequential indexes and param ids are not the same 

our first four sequential params have I’d 20480 20481 etc 

If you are assuming index == id that will break things including probably causing the macro issue #3561

**Comment by x42** [comment]
> If you are assuming index == id

Ardour does not assume this. But earlier versions of 6.5.0 had issues with re-connecting automation when the parameter-count changes.

**Comment by x42** [comment]
Looks like a different issue. When showing the automation lane ctrl parameter in Ardour's interface It's not a toggle, but a slider and I regardless of value it always shows "Off"

![image](https://user-images.githubusercontent.com/30246/103481233-e3cc6f80-4dd9-11eb-90f3-9b35cd72b12e.png)

**Comment by baconpaul** [comment]
Ok so I am just sending value 0/1 out of surge - in reaper the track shows the two values as a little step ramp in the envelope. Ideas what to do?

**Comment by x42** [comment]
Can you change the  [Vst::ParameterInfo::stepCount](https://steinbergmedia.github.io/vst3_doc/vstinterfaces/structSteinberg_1_1Vst_1_1ParameterInfo.html#ac1efeff62e4ba9aea101c3327e0b5c4d) of the "A Osc 1 Mute" Parameter to 1?
It is currently reporting `0` which means _continuous_. `1` would be _toggle_.

I'm still looking why Ardour asking the plugin to change the value does not work for the given parameter.

It works the other way around though. When using surge's GUI Ardour's UI follows.

**Comment by baconpaul** [comment]
Sure - let me try that!

**Comment by baconpaul** [comment]
OK making it a bool means you get a different UI but the automation still doesn't play back

I don't want to merge it without testing it a lot more - especially since it doesn't fix the problem - and may also not merge it this late in our cycle (we plan a release in 10 days!) but you can grab `baconpaul/ardour-3576` branch if you want

lemme see if I can see what is happening now I have automation up and running tho

**Comment by baconpaul** [comment]
Pretty sure this is a surge bug. Stand by.

**Comment by x42** [comment]
Found the issue

calling surge's `IEditController::plainParamToNormalized (Vst::ParamID = 164, ParamValue = 1.0)` returns 0

**Comment by baconpaul** [comment]
yeah i just found the same
and i see the problem
hold on. fix inbound.

**Comment by baconpaul** [comment]
this problem has been there since the day it was open sourced it turns out! Just Ardour using this api huh...

**Comment by baconpaul** [comment]
Anyway #3578 will fix it

thanks for looking @x42 - you found it from the 'outside' the same minute i found it from the 'inside'. Appreciate the look.

(insert commentary about VST3 spec being way too large and therefore difficult to implement)
