### ISSUE TITLE
Ardour export has clicks

### ISSUE THREAD

**Issue by magnetophon** [surge-synthesizer/surge#3581]
**Bug Description:**
When I export a song to a wav file, the wav has clicks.
When I listen to the song in realtime, it doesn't have clicks

I attached the song here:

[psy9.zip](https://github.com/surge-synthesizer/surge/files/5762421/psy9.zip)

To export, press Alt+e and click export in the bottom right.

**Comment by baconpaul** [comment]
Which Ardour version? I remember 6.4 had this problem at release for instance

**Comment by magnetophon** [comment]
git 2020-12-22

**Comment by mkruselj** [comment]
@magnetophon Does this still happen for you?

**Comment by magnetophon** [comment]
Seems to be not related to surge.
