### ISSUE TITLE
Don't save MIDI learn to snapshot; don't MIDI learn both scenes; handle automation in Dual/Split etc properly

### ISSUE THREAD

**Issue by Oortseam** [surge-synthesizer/surge#3582]
Hello, guys! 
Happy 2021 and my best wishes!

A strange bug was found.

Any MIDI CC assignment to any chosen parameter inside A or B scene is 'shared' between A and B scene in a very strange way. It's shown at this chosen parameter RMB menu on both A and B scenes but is working only at the scene that's currently active for editing (which is absolute nonsense when using this in dual mode). 

Moreover, this assignment cannot be deleted later. You delete it inside scene A, switch to scene B, and delete it once more. Then switch back to scene A - and ooops! - it's still there. I found no other way to get rid of such assignment than loading an empty CC map from general menu. 

Any internal assignments such as LFO or ADSR or direct parameter modulations from the host work fine. This bug is only with MIDI CC's.

Version/host/desktop info: 

Surge Synthesizer
Plugin Host:	REAPER
System:	Intel CPU, Windows VST3, 64-bit
Build Info:	Built on 2020-12-28 at 18:41:53, using pipeline host 'fv-az74-298'
Version:	1.8.nightly.185c107

**Reproduction Steps:**

1. Load SAW initial preset.
2. Set scene mode to Dual
3. Copy Scene A settings to Scene B
4. Make Scene A active for editing
5. Click RMB at any chosen scene parameter.
6. Set any MIDI CC automation.
7. Switch to  Scene B.
8. Click RMB at the same parameter.
9. See it's automated with the same MIDI CC too.
10. Try to make automation work. See it works only at active scene.
11. Try to delete this automation setting at scene A
12. Do the same at scene B
13. Switch to  Scene A.
14. Click RMB at the chosen parameter.
15. See it's still automated*

*Sometimes it may disappear but after unloading/reloading Surge or the whole DAW project it's still there.

**Comment by baconpaul** [comment]
So here's what the code does

When you activate a learn (around like 1620 of surge synthesizer) it learns that on both the A and the B param. That's a 'desired behavior' (or at least 'explicitly coded behavior') which takes us yo to your 9th point. So lets for a moment posit that isn't a bug (we can disagree on that but it's what the code 'currently does').

Now as to it not working in dual mode, yeah that's a real bug

Around like 1655 of SurgeSynthesizer you can see that when a CC comes in, it only uses the active scene. There's no concept of modes (split, dual, etc...) there at all. That explains your 10th point. Definitely needs fixing with something like "if i am in dual split or chsplit mode, span both scenes'. Since we are 7 days out from the 1.8 release that's a big change but we can fix and test that in 1.9 easily.

As to the 'clear': Looking at the "Clear Learned Midi" around line 3360 of SurgeGUIEditor it looks like it clears both. When I tried it in the AU I did find that also and I didn't have an option to delete it in Scene B once I had in Scene A. So I'm curious about your step 12. Once I do step 11 there is no more step 12 available to me?

**Comment by Oortseam** [comment]
Really I found this issue hard to repeat. But what still remains actual is that deleted CC automation comes alive after plugin unloading/reloading while all other parameter states (e.g. slider positions) store/recall correctly.
Take a look at this screen grab, please: https://drive.google.com/file/d/1uNQuBGs7WByCLRNaqfFVzML4jlR58-I6/view?usp=sharing

**Comment by baconpaul** [comment]
Do me a favor?
On the about screen it will tell you the factory folder
Is that folder writable by you? Like are you running as admin? Or portably with writable factory?
I have a theory

**Comment by Oortseam** [comment]
https://drive.google.com/file/d/1sQi01O2ZB-vboN0audhspLazDAfFaGLa/view?usp=sharing
BUT! these two folders are symbolic links in fact. Maybe that's the case? I'll make them real folders and try it again now.

**Comment by Oortseam** [comment]
Didn't helped. The same with real directories,.

**Comment by baconpaul** [comment]
Are they writable though?

**Comment by baconpaul** [comment]
For most people the factory folder is not writable. I think there might be a bug if it is

**Comment by Oortseam** [comment]
Yes it's marked as read only. And when I try to check off this option, Windows shows it's checked off but when I reopen this folder it's still read only.

**Comment by baconpaul** [comment]
OK great

So i think I know the problem. Stay tuned.

**Comment by baconpaul** [comment]
Oh darn no sorry I don't. OK one more thing.

In that factory folder is a file called "configuration.xml". Can you zip it and attach it to this issue?

The thing I thought it was (that file used to be writable; now it isn't; but if it is we inconsistently write it) is not what the code does. So let me see your cf.xml to rule out one more thing.

**Comment by Oortseam** [comment]
[configuration.zip](https://github.com/surge-synthesizer/surge/files/5768655/configuration.zip)
here it is (sorry for delay - there was a late night here in Europe :) )

**Comment by mkruselj** [comment]
I tried the reproduction steps a number of times and couldn't make it happen...

**Comment by Oortseam** [comment]
@mkruselj EvilDragon, Hmm.. I also can't reproduce this today. Maybe that was a mistake of mine. 

But what still remains actual is cleared MIDI CC coming to life after Surge plugin or DAW project unload/reload

As to separate MIDI control for the same parameters of scene A and scene B, I completely agree. As to me, the 'philosophy' of parameter control by host automation and by MIDI should be similar. If A/B parameters are automated by host separately, then MIDI automation maybe should manage them the same way.

**Comment by baconpaul** [comment]
Yeah the learn to both is wierd

There's also a thing where it tries to write to config.xml when you do a learn, which is also wierd and that is what is causing your problem. At some point you had a writable configuration.xml and you wrote to it. We need to fix that in Surge 1.9 and just - well - stop doing it altogether! We have better mechanisms now.

For now to fix your problem

1. Open your factory folder (you can just click on it in about)
2. Open configuration.xml in notepad or whatever
3. At the end you see this

```
<midictrl>
    <entry p="0" ctrl="1" />
    <entry p="119" ctrl="20" />
    <entry p="194" ctrl="54" />
    <entry p="271" ctrl="1" />
</midictrl>
```

4. Delete these three lines

```
    <entry p="119" ctrl="20" />
    <entry p="194" ctrl="54" />
    <entry p="271" ctrl="1" />
```

I'll change the name of this issue to better reflect what we want it to do.

**Comment by Oortseam** [comment]
>     1. Delete these three lines

Done this but it didn't help. I see <midictrl>...</midictrl> part of this file changing every time I assign some CC to some slider. But deleting this information doesn't prevent the issue,,,  Think I simply won't use Surge  MIDI assignment atm. Fortunately Reaper allows to assign MIDI CC-s to any automation parameter with it's own means - so the problem can be bypassed.

Thanks a lot for your feedback!

**Comment by baconpaul** [comment]
Yeah. "Use DAW Automation for now and we will sort this out in 19" was gonna be my very next comment here :)

**Comment by mkruselj** [comment]
#5761 is possibly loosely related to this one.

**Comment by mkruselj** [comment]
> Moreover, this assignment cannot be deleted later. You delete it inside scene A, switch to scene B, and delete it once more. Then switch back to scene A - and ooops! - it's still there. I found no other way to get rid of such assignment than loading an empty CC map from general menu.

At least this was fixed at some point in time, so phew!
