### ISSUE TITLE
Add ChowDSP CHOW

### ISSUE THREAD

**Issue by jatinchowdhury18** [surge-synthesizer/surge#3584]
Add [CHOW](https://github.com/Chowdhury-DSP/CHOW) to the Surge effects rack.

CHOW is a digital distortion/compressor/rectifier effect. Frankly, this effect can be rather harsh and even "ugly" but can sometimes be useful for sound design. It also aliases quite a bit (which I consider part of the effect).

**Comment by mkruselj** [comment]
Already listed it in #1694 actually :)

Would not be a bad idea to add some oversampling to it, as a parameter?

**Comment by baconpaul** [comment]
Oh if you would like to 2x oversample, the RingModulator effect shows how to use the half band filter at input and output to upsample/downsample in a way which is consistent with the rest of the surge signal path. (You may want to use a different strategy or not oversample of course.).

**Comment by jatinchowdhury18** [comment]
Yeah, I suppose having oversampling as an option couldn't hurt :).

**Comment by mkruselj** [comment]
@jatinchowdhury18 Is this one in PR state already? Feel free to push a PR and I can go in and tweak if you're busy otherwise. Rebase first, of course :)

**Comment by jatinchowdhury18** [comment]
Yeah, it's pretty close, but I wanted to do a little more testing. Hoping I can put it up for PR later today, so you all can review/tweak as desired :).

**Comment by mkruselj** [comment]
Cool!

Just FYI, I am pushing a PR that adds a few enums for FX types in advance to SurgeStorage.h, which should help with those pesky merge conflicts!

![image](https://user-images.githubusercontent.com/2393720/106333130-4fdeae00-6288-11eb-9647-26257ec7b75a.png)
