### ISSUE TITLE
Add ChowDSP Aural Exciter

### ISSUE THREAD

**Issue by jatinchowdhury18** [surge-synthesizer/surge#3586]
Add an [aural exciter](https://github.com/jatinchowdhury18/Aphex_Exciter) to the Surge effects rack. As discussed in #1694.

I think this one should be a pretty straightforward port. I don't expect to run into too many issues.

**Comment by mkruselj** [comment]
@jatinchowdhury18 ok so for starters I guess let's implement the exciter with only one set of parameters. Linking L/R is a bit trickier to do en masse until we move to JUCE (according to @baconpaul), so it's simpler to just have one set of parameters now, that applies to both L and R, then at later point we can add R side params and use streaming handler to set things so they match the original state that had just one set of params.

**Comment by jatinchowdhury18** [comment]
That makes sense. I should be able to make some progress on the exciter this weekend. I'll be sure to give an update then.

**Comment by baconpaul** [comment]
Cool
As an aside: If you don't have clang-format installed, it's now required for commits to pass PR with the .clang-format file I checked in a few days ago. If you just use clion it all works, and visual studio has a plugin too.

**Comment by jatinchowdhury18** [comment]
Oh nice! I actually just recently started using clang-format on my linux setup. Not sure if this type of thing can be done through Azure pipeline, but I actually set up a little GitHub action to automatically push clang-format fixes to my pull requests: https://github.com/Chowdhury-DSP/ChowMatrix/blob/develop/.github/workflows/auto-format.yml. It would probably be much simpler if I didn't need clang-format version 12.

**Comment by baconpaul** [comment]
Yeah I run a little check that dry-runs it and fails with feedback to the author. That seemed a little more polite than modifying someones branch at a PR but had the same thought! I just now run git clang-format before git commit and have it set up in clion.
