### ISSUE TITLE
M/S transform effect in FX or scene output section

### ISSUE THREAD

**Issue by Oortseam** [surge-synthesizer/surge#3596]
Hi!

I'm speaking of a channel transformer performing the next algorithm:  Lnew=M=0.5*(L+R);  Rnew=S=0.5*(L-R)

It could be very useful in many situations. For example, it allows to build complicated unison-based pads with clear and straight control over mono and stereo part (to prevent undesired phase effects at low end and to have nice mono compatibility).

Now I'm using external plugin for this and it does the work nice. But it would also be useful if I had a possibility to store this as a part of preset (as I have many ones that I could share with others but now they need to be additionally processed with external plugin to sound right)

As I think, it wouldn't be a hard task. Just one more effect in FX group or RMB-menu controlled option for Pan or Width slider in Scene output section.

**Comment by mkruselj** [comment]
So, basicall< mid-side encoder. But then you also need a decoder to get the proper stereo signal back. So this definitely requires more FX slots as a prerequisite (#2446).

**Comment by baconpaul** [comment]
We have a m/s encoder decoder which are SSE coded already in the code base, so while I agree with @mkruselj that this would require slot expansion to be practical, it is a trivial matter to code.

The M/S encode is what is used in the 'width' parameter in many of the effects.

From the flanger code for instance:

```
  float M alignas(16)[BLOCK_SIZE],
         S alignas(16)[BLOCK_SIZE];
   encodeMS(dataL, dataR, M, S, BLOCK_SIZE_QUAD);
   width.multiply_block(S, BLOCK_SIZE_QUAD);
   decodeMS(M, S, dataL, dataR, BLOCK_SIZE_QUAD);
```

So really the thing you are after is an FX with two params

1: 'encode/decode' toggle
2: 'mix' (which is output = origin + encoded) default to 100% range -100 to 100.

Seems to me.

**Comment by mkruselj** [comment]
Or, maybe a better way would be to add M/S processing option to each effect, when right-clicking the Output/Mix slider (depending on the effect), where we would select standard processing, process sides only, process mid only?

**Comment by Oortseam** [comment]
mkruselj   Yes! To have hands completely free you should have M/S encoder also with a possibility to place it where you like at the circuit. 
BUT even the ecoder only that can be placed at the existing FX slot may be a great help.  

As an example, here is a setup for nice FM stereo bass with no phase artifacts I use now with SURGE. It looks like this:

[OSC2 (FM2 mode)]->(fm modulation)->[OSC1 (SIN mode)]
where OSC1 has 2 voice unison.

Yes,  it gives me a stereo. But it's unusable in fact (listen to MS_UNPROCESSED file)
[MS_UNPROCESSED.zip](https://github.com/surge-synthesizer/surge/files/5791651/MS_UNPROCESSED.zip)
It has the extra wide and uncontrollable low end which gets unstable on tone and character if you try to make it more narrow with some post processing.

What helps is to process the right channel with a HPF filter and to attenuate it a bit. Then I use external M/S decoder which transforms L channel into M part (with nice solid low end) and R channel into S part. which gives needed stereo feel at mids and highs. Now it sounds like this (listen to MS_UNPROCESSED file):
[MS_PROCESSED.zip](https://github.com/surge-synthesizer/surge/files/5791661/MS_PROCESSED.zip)

**Comment by magnetophon** [comment]
> PS: If every stereo FX (including two main filters, HPF and a shaper) had the next structure: [M/S encoder (on/off)] ->[L/R balance (-50...50)]->[main effect processing]->[M/S decoder (on/off)], then ALL possible situations could be managed (all these tunings could be placed to FX RMB-menu maybe)

I came here to request exactly this.
To be clear:  when you say L/R balance, you mean 1/2 balance, where 1 is either L or M and 2 is either R or S, correct?

Just the decoder as a regular FX would also be awesome: a big part of the usefulness for very little effort, I think.

**Comment by Oortseam** [comment]
@magnetophon L&R after M/S encoder is M&S in fact. You're right!

**Comment by mkruselj** [comment]
I think we should just implement mdaStereo here. :)

**Comment by baconpaul** [comment]
Hi!

Thanks to @mynameismuhl we will have these encoders and decoders in our next release so let me close this issue.

**Comment by magnetophon** [comment]
Great!
Thanks @mynameismuhl!
