### ISSUE TITLE
Global keytrack modulators not always updating properly

### ISSUE THREAD

**Issue by PopeKehoeIII** [surge-synthesizer/surge#3597]
**Bug Description:**
When you run mono mode lowest note priority and assign the highest key modulator (or vice versa) there's a one note delay in evaluation on the modulator - in the lowest note priority example the highest key modulator does not move upon striking one higher note but does if you hit two.

**Surge Version**
Verified by EvilDragon as well on discord who I assume is running a more up to date nightly.
* Version: 1.8.nightly.42c50f8
* Plugin Type: VST3
* Bitness:  64-bit

**Reproduction Steps:**
Set synth to mono and low note priority
Assign highest note keytrack to any parameter
press and hold middle C
press one higher note
note no change
press two higher notes
modulation kicks in

**Expected Behavior:**
I expected to achieve duophonic style behavior by assigning high note keytracking to various parameters while the synth was in low note priority

**Computer Information (please complete the following information):**
 - OS: Windows 10
 - Host: Bitwig
 - Version: 3.3
**Additional Information:**
There's a patch in #using-surge on the discord that showcases the issue using an LFO

EDIT: Latest keytrack modulator doesn't appear to be functioning as expected in low note priority mono mode either - it won't update when hitting higher notes that don't actually change the synth's pitch

**Comment by baconpaul** [comment]
[highest_key_bug_.fxp.zip](https://github.com/surge-synthesizer/surge/files/5788946/highest_key_bug_.fxp.zip)

that patch.

will look yup thank you.
