### ISSUE TITLE
Mono note priority mode not preserved on copy/paste

### ISSUE THREAD

**Issue by PopeKehoeIII** [surge-synthesizer/surge#3599]
**Bug Description:**
When I copy scene A into scene B the mono note priority in scene B is last note priority regardless of what it was in Scene A

**Surge Version**
This information is found on the About screen, which you get to from the bottom right menu

* Version: 1.8.nightly.d29182b
* Plugin Type: VST3
* Bitness:  64-bit

**Reproduction Steps:**
1. Set scene A to mono + low note priority
2. Copy scene A
3. Paste scene B
4. Check note priority on scene B

**Expected Behavior:**
I expected note priority context menu selection to be copied over

 - OS: Windows 10
 - Host: Bitwig
 - Version: 3.3.1

**Comment by baconpaul** [comment]
Good find. Fix inbound.
