### ISSUE TITLE
CHSwitch2 should support custom skin classes

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3602]
...so that we can add variations to the same image used multiple times on the GUI (example: jog buttons, envelope shape controls, envelope mode, etc.).

The custom class for CHSwitch2 should support tags `image`, `hover_image` and `hoveron_image`.

**Comment by baconpaul** [comment]
so the above fix blows up royal in the nightly
is the skin wrong? is the code? who knows
but reverting and reopening this issue
