### ISSUE TITLE
Surge Crashes in linux wine environment when loading into FL Studio 2020

### ISSUE THREAD

**Issue by BruhMomentInifity** [surge-synthesizer/surge#3616]
**Bug Description:**
I am running FL Studio 20 inside of Zorin OS (Linux) via WINE. The plugin has been successfully added to the plugins and is accessible. However, upon clicking on it to load it in, the plugin begins to open, expands the window size and then freezes the whole program.

**Surge Version**
* Version: 1.7.1
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Go to Sequencer in FL Studio 20
2. Click on "Replace"
3. Scroll down to "Surge"
4. Select
5. Plugin then crashes the entire DAW upon attempting to load and change window size

**Expected Behavior:**
It should freeze the software completely if done as shown, (process of adding plugin into FL Studio is the standard one you do for any other).

**Screenshots:**
I've got a short video here showing the issue.

https://user-images.githubusercontent.com/77301996/104242637-118e6580-5425-11eb-8245-0e54f7bd8b77.mp4

**Computer Information (please complete the following information):**
 - OS: Zorin OS version 15.3
 - Host: FL Studio 20 (Running via WINE)
 - Version: 20.7.2

**Additional Information:**

**Comment by baconpaul** [comment]
Surge uses direct2d which I understand does not work under wine. That’s probably it. No one has made surge work under wine to my knowledge. Googling shows wine D2D support is incomplete too. 

but we did fix some fl bugs since 171 which the nightly would have so maybe worth a try with the 18beta?

**Comment by BruhMomentInifity** [comment]
Tried that and still got same results sadly :/ I MAY have messed up the install and still tried to load 171 but  I'm not sure. Thanks for the heads-up about Direct2D! Shame it doesn't work on WINE but alright, thanks for explaining.

**Comment by baconpaul** [comment]
Yeah looking on other issues, no one has ever made it work on wine. I think the wine devs would need to intervene - I am sure they can figure out which API they don’t support.

I know it won’t solve your use case, but the plugin does work fantastically in native linux DAWs.

But I’m going to close this issue; I don’t think there’s anything for surge team to do (short of rewriting the entire UI to not use the direct2d apis on window, which isn’t in our plans). If you do end up chatting with the wine team on github feel free to connect them to this issue.
