### ISSUE TITLE
3D Waveform for OSC (when morphing waveforms)

### ISSUE THREAD

**Issue by artyfunk** [surge-synthesizer/surge#3617]
Like discussed in DIscord. I write it down here. We wish to have a Optical visualisation of the Waveform complete lengt and have the ability to morph between them.

Like Serum:
![Image 3763](https://user-images.githubusercontent.com/76977285/104245859-4f12e300-5465-11eb-8678-69f9acf31e8b.jpg)

or Pigments:
![Image 3762](https://user-images.githubusercontent.com/76977285/104245889-5d60ff00-5465-11eb-93c2-7ba993564943.jpg)

or Vital:
![Image 3764](https://user-images.githubusercontent.com/76977285/104245915-6782fd80-5465-11eb-8ca9-20ae4461b27a.jpg)

This would show what is coming next in the Waveform and would make the life little bit easier.
I understand its not THAT important but good to have.

So if you like maybe you could do it. Would be great to see this feature.

**Comment by baconpaul** [comment]
`baconpaul/19-3dwavetable` branch does this

![shaded](https://user-images.githubusercontent.com/13387561/104342122-7ea70700-54c8-11eb-885a-8cdbda8b106e.gif)

but i think it is kinda bad tbh for most of our wavetables. (I'm not yet drawing the oscillator output line there). Not convinced this is something we really want.

**Comment by baconpaul** [comment]
Oh that's at 250% on a mac retina display, so it is 5x denser than a windows 100% user would get.

**Comment by mkruselj** [comment]
@baconpaul This might be a nice one to maybe cram into 1.1 as a sort of a surprise? It seems like it's pretty much there already, it just (sorry for using that word!) needs the WT frame drawing occurence tweak as suggested above. Maybe? 🙂 

(I'm trying to relieve the XT2 milestone a little bit.)

**Comment by baconpaul** [comment]
Sure

**Comment by artyfunk** [comment]
it needs a actual display highlight. i mean the actual waveform (part of the complete waveform) should be thicker and other color.

**Comment by mkruselj** [comment]
That's a given.

**Comment by baconpaul** [comment]
Well not the actual waveform. The selected frame of the wavetable

**Comment by baconpaul** [comment]
Is there anything left to do here?
The 'actual waveform' is a bit tricky - we don't know exactly how many samples constitute one cycle easily but we can do it. 
But is there anything else we want?

I'm sort of temped to close this as done then let people argue about the look and feel.

wdyt?

**Comment by mkruselj** [comment]
Yeah we need to run the osc to show the actual waveform as it morphs and gets phase distorted too. We also need to make the display remember it's state. Right now every time UI is refreshed (i. e. selecting another osc tab or changing osc type from WT to window) it reverts back to 2D view. Maybe it could be a user default rather than DES?
