### ISSUE TITLE
Zoom window with error appear on loading the synth on MacBook Air M1

### ISSUE THREAD

**Issue by Stansom** [surge-synthesizer/surge#3623]
**Bug Description:**
Every time when open the synth zoom window error appear.
**Surge Version**
Surge Synthesizer
System:	Apple Silicon CPU, macOS AU, 64-bit
Build Info:	Built on 2021-01-11 at 19:34:21, using pipeline host 'Mac-1610391002575.local'
Version:	1.8.nightly.7667ce7

**Reproduction Steps:**
1 Install Surge
2 Place plugin in a channel strip
**Expected Behavior:**
I think that window shouldn't appear
**Video:**
https://streamable.com/e4712f

**Computer Information (please complete the following information):**
 - MacOs Big Sur 11.1
- Logic
-  1.8 nightly

**Additional Information:**

**Comment by baconpaul** [comment]
So the immediate solution to this is to either not use the royal skin or set your default zoom to 100%
Both of those can be done by deleting (or renaming) the file "~/Documents/Surge/SurgeUserDefaults.xml" and restarting logic.
We are debating getting rid of that dialog. But if you are using 125% with royal on a screen that small right now the message will pop up.

I am very curious though if the plugin otherwise works on native mac?

**Comment by baconpaul** [comment]
It's unclear from your image also: Does the dialog never dismiss? Or does it keep popping up?

**Comment by baconpaul** [comment]
We discussed this in surge discord some

The check is from back when the only place where you could adjust zoom was the menu button which would get knocked off screen.  Now the menu is available everywhere in 18 we were considering removing it anyway.

So this check won't be part of 1.8. A nightly today will also have it gone.

Thanks!

**Comment by Stansom** [comment]
Sorry for late answer.
That error appears with all skins, the windows gone after few clicks on the
ok button.
If I will change zoom from the menu it will decrease zoom percentage, even
if I want to increase to 125 or 150 percent.

śr., 13 sty 2021, 17:55 użytkownik Paul <notifications@github.com> napisał:

**Comment by baconpaul** [comment]
We disabled the check and the next nightly will have it gone - probably about an hour for the new nightly

would love to hear how it works on Apple silicon we don’t have m1 hardware in the dev team yet but have had some other testers

**Comment by Stansom** [comment]
Two videos described problem with zoom shrink.
https://streamable.com/tj437y
https://streamable.com/lksrfk

And more, it continuously shrinking even if I change zoom on same value.
https://streamable.com/5tt9zu

Some strange zoom loop appears as I think :)

**Comment by Stansom** [comment]
> We disabled the check and the next nightly will have it gone - probably about an hour for the new nightly
> 
> would love to hear how it works on Apple silicon we don’t have m1 hardware in the dev team yet but have had some other testers

If you want to know how it performs you can gave me a test file if you have and I will run it on my **Apple M1**.
I already have done some test and get strange results :
SURGE with 3 notes chord and 3 voices performance on M1
- in Reaper : 450 instances before crackling and popping audio.
- in Logic Pro : 500 instances for 2 bars continuous playing, after that appears "System Overload" window.
                          250 instances for 4 bars continuous looping for minutes without coopering "System Overload" window.

SURGE with 3 notes chord and 3 voices performance on **Ryzen 1700** @3600Hz
- in Reaper : 650 instances before crackling and popping audio.

As I can see and feel it's not a big difference in performance between that desktop monster and that little laptop processor with running not optimised Surge on the M1, as I know, you (developers) don't have M1 for debugging and bug-tracking and for me it's something like a magic, how it runs at all on this chip :)

Sorry for my not good english :( but I want to help as I can.

**Comment by mkruselj** [comment]
Do note that CPU consumption can differ really wildly depending on what is being used in the patch... Try some of Jacky Ligon atmospheric patches that use Dual mode, see how that fares...

**Comment by baconpaul** [comment]
Yeah but even that is great feedback. "It works and knocks out around the same spot as a Ryzen!" Thank you very much.

**Comment by Stansom** [comment]
> Do note that CPU consumption can differ really wildly depending on what is being used in the patch... Try some of Jacky Ligon atmospheric patches that use Dual mode, see how that fares...

Done.
Jacky Ligon Duality Patch on
M1 Logic 48 instances, Reaper 59 instances
Ryzen Reaper 70 instances

I really don't know why so big difference between Logic and Reaper all audio settings are same.

**Comment by baconpaul** [comment]
There are some AU vs VST3 differences but I'm surprised it is that big also. 
I'm also amazed that in a like-for-like with reaper the M1 is close with that Ryzen.
Very very useful information. Thank you.

**Comment by Stansom** [comment]
Spire synth same problem here with Logic vs Reaper
PAD Access Virus patch, 3 notes
Logic - 42 instances, Reaper - 58 instances.
Something very bad happens with Logic audio engine, it's very strange but it's true, Apple native application working not good as third-party developer application on beta stage :(

**Comment by mkruselj** [comment]
Reaper is just more CPU efficient and hosts plugin better than Logic, it's just a fact of life. 😛

**Comment by Stansom** [comment]
> Reaper is just more CPU efficient and hosts plugin better than Logic, it's just a fact of life (also it does something called "anticipative processing" where it processes plugins ahead of time which utilizes the CPU way better, Logic doesn't do that). 😛

That's very annoying, because that problem with "System Overload" message is here from the far 2008 year and Logic 9. 
Apple creates great processor and don't optimise professional software to beat that old bug. Sad face.

**Comment by mkruselj** [comment]
Well they did update and optimize Logic to support up to 1000 tracks and so on (back when the new cheesegrater Mac Pro was announced), so they are working on it. But Logic doesn't work _in the same way_ that Reaper does, so performance obviously cannot be the same.
