### ISSUE TITLE
Option to label the LFO display in musical time

### ISSUE THREAD

**Issue by magnetophon** [surge-synthesizer/surge#3635]
At the moment the LFO display is labeled in seconds.
It would be nice if you could also choose to label it in musical time: bars beats, notes.

**Comment by baconpaul** [comment]
Turn on temposync on any param and it will do this for you today no?

**Comment by baconpaul** [comment]
Any lfo param that is

**Comment by magnetophon** [comment]
It doesn't here.
So I guess this is now a bug report.

Surge Synthesizer
Plugin Host:	Ardour
System:	x86_64 CPU, Linux VST3, 64-bit
Build Info:	Built on 1980-01-01 at 00:00:00, using local host 'localhost'
Version:	1.8.fetchgit.1fc49f2

Do you need any other info?

**Comment by baconpaul** [comment]
So you right mouse on LFO rate and choose temposync on the LFO on display? Just want to be sure.

**Comment by magnetophon** [comment]
Yes.
I also tried to sync all.

**Comment by TheNerdyMusicGuy** [comment]
When tempo sync is enabled, numbers that indicate quarter notes should appear above the LFO display, if everything is working correctly.
The second graph still remains visible below the LFO display.

**Comment by magnetophon** [comment]
So it turns out to be BEBCAC after all.
Sorry for the noise!

**Comment by baconpaul** [comment]
Can you just try quickly in host other than Ardour also? If Ardour is not reporting the tempo properly we would probably skip it (like if the tempo is 0/0ths we don’t draw rather than explode)

**Comment by baconpaul** [comment]
Ahh cool!

**Comment by magnetophon** [comment]
Thanks @TheNerdyMusicGuy !
