### ISSUE TITLE
Surge sometimes crashes when changing presets

### ISSUE THREAD

**Issue by TheNerdyMusicGuy** [surge-synthesizer/surge#3648]
When selecting a different preset, Surge sometimes crashes. This happens somewhat frequently, but I can't figure out exactly when it happens.

Surge Synthesizer
Plugin Host: Ableton Live 10.1
System: Intel CPU, Windows VST3, 64-bit
Build Info: Built on 2021-01-16 at 17:46:37, using pipeline host 'fv-az29-734'
Version: 1.8.nightly.7016ce9

**Comment by K0rrid0r** [comment]
reminder for @baconpaul how hard it was to find the issue of the same nature in this issue
https://github.com/surge-synthesizer/surge/issues/2860

can you open debugger surge and try to crash it?

**Comment by baconpaul** [comment]
OK so in live If I change to TNMG/pads and just wail on the next button eventually it crashes

It crashes with two threads looking like this

```
Thread 3 Crashed:: AudioCalc
0   com.vemberaudio.vst3.surge    	0x00000001a464aca3 AirWindowsEffect::setupSubFX(int, bool) + 307 (AirWindowsEffect.cpp:252)
1   com.vemberaudio.vst3.surge    	0x00000001a464a7fa AirWindowsEffect::process(float*, float*) + 266
2   com.vemberaudio.vst3.surge    	0x00000001a4635db5 Effect::process_ringout(float*, float*, bool) + 165 (Effect.cpp:86)
3   com.vemberaudio.vst3.surge    	0x00000001a402ee6d SurgeSynthesizer::process() + 8029 (SurgeSynthesizer.cpp:3418)
4   com.vemberaudio.vst3.surge    	0x00000001a45c6857 SurgeVst3Processor::process(Steinberg::Vst::ProcessData&) + 983
```

and also

```
Thread 39:
0   com.vemberaudio.vst3.surge    	0x00000001a46b20e7 Wavetable::MipMapWT() + 919 (Wavetable.cpp:313)
1   com.vemberaudio.vst3.surge    	0x00000001a46b1cfc Wavetable::BuildWT(void*, wt_header&, bool) + 1452 (Wavetable.cpp:261)
2   com.vemberaudio.vst3.surge    	0x00000001a46daf71 SurgePatch::load_patch(void const*, int, bool) + 689 (SurgePatch.cpp:943)
3   com.vemberaudio.vst3.surge    	0x00000001a404914d SurgeSynthesizer::loadRaw(void const*, int, bool) + 253 (SurgeSynthesizerIO.cpp:323)
4   com.vemberaudio.vst3.surge    	0x00000001a404872a SurgeSynthesizer::loadPatchByPath(char const*, int, char const*) + 1098 (SurgeSynthesizerIO.cpp:224)
5   com.vemberaudio.vst3.surge    	0x00000001a404828e SurgeSynthesizer::loadPatch(int) + 286 (SurgeSynthesizerIO.cpp:158)
6   com.vemberaudio.vst3.surge    	0x00000001a402bbd8 loadPatchInBackgroundThread(void*) + 88 (SurgeSynthesizer.cpp:2933)
7   libsystem_pthread.dylib       	0x00007fff6df6e109 _pthread_start + 148
8   libsystem_pthread.dylib       	0x00007fff6df69b8b thread_start + 15
```

**Comment by TheNerdyMusicGuy** [comment]
Dang, I just had 2 crashes again while selecting presets from the preset menu.

Surge Synthesizer
Plugin Host: Ableton Live 10.1
System: x86 CPU, Windows VST3, 64-bit
Build Info: Built on 2021-01-21 at 01:31:57, using pipeline host 'fv-az95-512'
Version: 1.8.nightly.b7c72a6

**Comment by baconpaul** [comment]
I wonder if the menu uses a different loaf path that hasn’t been remediate. Will peek

crashes with buttons?

**Comment by TheNerdyMusicGuy** [comment]
After your fix I hammered on the prev/next buttons for a few minutes and nothing happened. Might just be a coincidence, I don't know.
The preset menu method is obviously not as easy to stress test.

It's really frustrating, the bug seems so happen quite frequently, but never happens when you want it to.

**Comment by baconpaul** [comment]
So I have a modified version of surge which simulates a preset select every 5 idles. It ran in the AU for 10 minutes with no problem. lemme try mac live. Then win live.

**Comment by baconpaul** [comment]
no crash mac or win
i wonder if it is something with the lifecycle of the popup menu or something?

**Comment by baconpaul** [comment]
OK I see the problem. Tricky to fix.

**Comment by baconpaul** [comment]
I have a fix

**Comment by TheNerdyMusicGuy** [comment]
It sadly still happens in the latest nightly after the fix.

Surge Synthesizer
Plugin Host: Ableton Live 10.1
System: x86 CPU, Windows VST3, 64-bit
Build Info: Built on 2021-01-21 at 16:30:19, using pipeline host 'fv-az224-517'
Version: 1.8.nightly.e3ee7d2

**Comment by baconpaul** [comment]
As confirmed on discord the "medium" fix fixes it and I am queuing that up for the nightly.
