### ISSUE TITLE
Cap missing from Width slider in Output section.

### ISSUE THREAD

**Issue by ContemporaryInsanity** [surge-synthesizer/surge#3650]
**Bug Description:**
Cap missing from Width slider in Output section.

**Surge Version**
Surge Synthesizer
Plugin Host:	VCV Host
System:	x86_64 CPU, Linux VST3, 64-bit
Build Info:	Built on 2021-01-17 at 14:32:16, using pipeline host 'fv-az149-89.internal.cloudapp.net'
Version:	1.8.0.2560170

**Screenshots:**
![image](https://user-images.githubusercontent.com/12547379/104851232-be685700-58eb-11eb-9c5f-77584b6a698b.png)

**Comment by baconpaul** [comment]
Hi

the cap is disabled if the filters are in mono mode. If you put the filters in stereo mode (click wide on the filter diagram) it should appear. Does it?

**Comment by ContemporaryInsanity** [comment]
That just occurred to me so came back here to close the issue!
Thank you :)

**Comment by baconpaul** [comment]
No worries! It’s actually good to know they the royal skin works in Linux vcv host too - which isn’t part of our regular test matrix!
