### ISSUE TITLE
Click on Loop in Reaper

### ISSUE THREAD

**Issue by DimiGuitar** [surge-synthesizer/surge#3651]
![1](https://user-images.githubusercontent.com/77584690/104851530-32135f80-58fe-11eb-9605-04e9c0bddd7c.png)
**Bug Description:**
Click when Looping in Reaper - A few presets, maybe more are clicking when put a simple midi 1 bar loop in Reaper with simple bass line.
As an example preset: Deep End

**Surge Version**
1.8.0

* Version:
VST3

**Computer Information (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Host: Reaper
 - Version: 6

**Comment by baconpaul** [comment]
Thanks we will look this week as we collect various 18 reports. 

I don’t suppose you can save and zip up a minimal reaper file that shows the click? That has helped us in past situations 

Thanks!

**Comment by baconpaul** [comment]
Members of the team respond this use pattern is fine in bw windows and fl windows. Haven’t done reaper test yet. I’ll check mac later today or tomorrow also.

**Comment by baconpaul** [comment]
Tagged in to 181 milestone to at least understand

**Comment by baconpaul** [comment]
Just tried logic pro AU and also no problem

@mkruselj can you try windows reaper vst3 and see if you hear a click here?

**Comment by mkruselj** [comment]
Can't get any clicks here in Reaper at loop turnaround point. Tried that exact same patch and exact same notes, at 120 BPM.

**Comment by DimiGuitar** [comment]
> 
> 
> Can't get any clicks here in Reaper at loop turnaround point. Tried that exact same patch and exact same notes, at 120 BPM
Strange, hope its not coming from some of my old Reaper settings. Maybe, I should reset everything.

**Comment by mkruselj** [comment]
I guess don't trash your Reaper settings, try on a fresh portable install of Reaper instead?

**Comment by DimiGuitar** [comment]
Found it!!! Its : Flush FX when Looping in Reaper settings. I had it enabled, who knows when. After switching it off, no more clicks.
Best

**Comment by baconpaul** [comment]
Wonderful! Thank you. Closing issue
