### ISSUE TITLE
DnD or Load WT from file always switches osc type to Wavetable

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3657]
Even if we had it set to Window. Uncool. Needs fix!

Thanks to [Gone soft on KvR](https://www.kvraudio.com/forum/viewtopic.php?p=8005838#p8005838) for report.

**Comment by baconpaul** [comment]
Oh ha yeah! We should obviously fix that. The intent was "make it use a wavetable oscillator" but not checking window first is rude :)

**Comment by mkruselj** [comment]
Ehehe :)
