### ISSUE TITLE
Oscillator waveform can go way past top/bottom of the display in some cases

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3658]
For example, with Classic oscillator:

![image](https://user-images.githubusercontent.com/2393720/104939062-3b5d0480-59b0-11eb-9603-f0bfc359ec04.png)

Or it can also happen with WT oscillator quite often, especially if you use Saturate and Formant.

Solve by adding cliprects after the top and bottom lines of the display. Pray VSTGUI doesn't screw us over on Linux.

**Comment by K0rrid0r** [comment]
will those cliprects affect the sound or was this just visual?

**Comment by baconpaul** [comment]
just visual

**Comment by mkruselj** [comment]
Reopening since the PR was reverted. JUCE will save us here. Again 🙂

**Comment by mkruselj** [comment]
Moving to XT.

**Comment by mkruselj** [comment]
XT deals with this properly, so closing the issue!
