### ISSUE TITLE
1.8.0: error: 'magnify' marked 'override' but does not override any member functions    virtual bool magnify(CPoint& where, float amount) override

### ISSUE THREAD

**Issue by yurivict** [surge-synthesizer/surge#3668]
**Bug Description:**
```

/wrkdirs/usr/ports/audio/surge-synthesizer-lv2/work/surge-release_1.8.0/src/common/gui/MSEGEditor.cpp:1657:17: error: 'magnify' marked 'override' but does not override any member functions
   virtual bool magnify(CPoint& where, float amount) override
                ^
1 error generated.
```

**Surge Version**
This information is found on the About screen, which you get to from the bottom right menu

* Version: 1.8.0
* Plugin Type: [VST2, VST3, AU]
* Bitness: 64-bit

clang-10
FreeBSD 12.2

**Comment by baconpaul** [comment]
Hmm. How are you getting surge?

This error is indicative that you are building our version of surge against the wrong fork of vstgui

We added the magnify method to cview.h in vstgui.surge e7a2bf3a7f95683dacb09988a79d252d82a48c93 which is included in the submodule at the head of surge right now.

we build against clang in our pipeline for every build. So I think you have somehow obtained the wrong copy of the code or have done a build without doing a git submodule update perhaps?

**Comment by baconpaul** [comment]
and i just checked the 180 source tarball also in case you are loading that.

```
vstgui.surge/vstgui/lib/cview.h:	virtual bool magnify( CPoint &where, float amount ) { return false; }
```

so somehow you are building in an environment which points at the wrong vstgui.

Could you share the commands you use to get the code and the commands you use to build?

**Comment by yurivict** [comment]
You are right, some of the submodules were left at the old level.

Sorry for the disturbance!

**Comment by baconpaul** [comment]
No problem! Please do let us know if it works. Thanks for updating your packages.
