### ISSUE TITLE
Modulation on TempoSync LFO Rate

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3671]
From KVR: Investigate this

> Great.  8) If I modulate a temposynced LFO rate with for instance velocity and hold CTRL I get 200% as expected, then the values skip to 360 and 440 and on to 520% before hitting a value that makes sense to me with 600%. Any reason it doesn't stop by values like 300%, 400% and 500% as I'd imagine? And if I try to enter a value manually for modulation of temposynced LFO rate it always shoots straight to the roof and goes for 4000% (?) just about no matter which value I enter. I just had an idea as I was typing this: It seems if I type in 20 instead of 200 it works. Typing 30 will give me 300% etc.

**Comment by mkruselj** [comment]
Typeins don't seem to deal with temposynced params gracefully indeed. I'm unsure why we use % here as unit, too...

**Comment by baconpaul** [comment]
We use % because in temposync mode that's kinda what the modulators do. The steps are wierd because they are stepping in units of temposync. but the typein is a bug.

**Comment by baconpaul** [comment]
```
if (temposync)
      {
         auto mv = (float)std::atof( s.c_str() ) / 10.0;
         auto rmv = mv / ( get_extended(val_max.f) - get_extended(val_min.f) );
         return rmv;
      }
``` 

like ' a typo bug'. That should be 100.
