### ISSUE TITLE
Double activation from a single click of the left/right patch arrows

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#3682]
**Bug Description:**
When I click left or right 'Patch' arrows, the selection may move twice instead of once. The skipped patch is displayed briefly.

**Surge Version**
Surge Synthesizer
System:	Intel CPU, Windows VST3, 64-bit
Build Info:	Built on 2021-01-17 at 14:32:20, using pipeline host 'WIN-LQBHPKRFL7J'
Version:	1.8.0.2560170

**Reproduction Steps:**
1. Click left or right 'Patch' arrows

**Expected Behavior:**
The selection moves once to the previous/next available patch.

**Screenshots:**

**Computer Information (please complete the following information):**
Plugin Host:	Cakewalk
System:	Intel CPU, Windows VST3, 64-bit

**Additional Information:**
Inconsistent. If I find a reproducible cause, I'll add more.

**Comment by mkruselj** [comment]
Likely fixed through #4185.
