### ISSUE TITLE
Airwindows Vari-Mu creates aliasing

### ISSUE THREAD

**Issue by Vospi** [surge-synthesizer/surge#3684]
Airwindows Vari-Mu creates rather intense artifact on Nyquist under certain conditions.

Surge ver 1.8.2560170 vst3 64-bit

**Demonstrated:**
https://youtu.be/oGwhHDd-bE0

Hosted: FL Studio 12, Win10 x64.

**Comment by Vospi** [comment]
Decided to move the issue out of Surge and think of presenting it to Chris if it is in fact unintentional.

**Comment by baconpaul** [comment]
great - if he ends up changing the fx we can merge that change into our integration easily
