### ISSUE TITLE
Automatically choose best fit zoom level on very first load 

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3686]
Currently, when freshly installing Surge (no config files present from prior installs on the system), Surge will load at its poststamp zoom level of 100%.

It makes sense to automatically choose the best zoom level we can (like we used to when detecting overzooms) in this scenario, in order to improve OOBE.

**Comment by baconpaul** [comment]
So "best zoom level we can" means first time you start surge on a 4k monitor it will come up at about 270%.
That what we want?
(I think it isn't).
Sure we can come up with some other heuristic though based on screen size. Like "if screen > res A then choose 125; bigger than res B choose 150" and then just leave it at that.

**Comment by mkruselj** [comment]
Maybe? It should not look like a post stamp either way.

I'd say maybe it should pick the closest zoom that would fill about 3/4 of the screen.

**Comment by mzed** [comment]
On Windows maybe it should default to scaling setting that has been chosen in Display Settings? Is that accessible?

On my 3840x2160 laptop display, I'm usually running at 250%. I got the postage stamp experience, and was lucky to right-click someplace where I found a zoom control.
