### ISSUE TITLE
Don't resize larger than screen

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#369]
path to zoom #305 
currently if i have a smaller screen and set to 300%, i cannot re-resize it to lower size, instead i'm stuck and need to delete the plugin and re-open it.

**Comment by baconpaul** [comment]
@esaruoho I have a preliminary fix for this on branch bacon paul / screensize-369

I want to do a few things still (like do a self-code-review, test win and lin still work, and squash) but if you want to try that on your mac and provide any feedback it would be great.

I have a 2 monitor setup and it worked fine detecting the right monitor and stuff but these graphics APIs can be fiddly so another test would be lovely.

Thank you!

**Comment by baconpaul** [comment]
OK this is all swept into master. Thanks for the eagle eyes, @esaruoho! Hope you like the error message when you try to over-grow :)
