### ISSUE TITLE
iOS version?

### ISSUE THREAD

**Issue by tomduncalf** [surge-synthesizer/surge#3693]
Hey,

I was curious if an iOS version of Surge, distributed for free on the App Store (as well as available open source), would be of interest and/or permitted? 

There seem to be potential issues distributing GPL software on the App Store from reading online, I don’t really understand why distribution on there is different to distribution elsewhere but maybe this would be a blocker? If anyone understands it in more detail I’d love to understand. 

My thinking is more cool free synths on iOS would be great and it might be fairly achievable with the project moving to JUCE. It’s something I’d be interested to work on if so. 

Cheers,
Tom

**Comment by mkruselj** [comment]
It's not going to happen, because App Store is generally incompatible with GPL3 license Surge is under.

**Comment by tomduncalf** [comment]
👍 too bad that Apple prevents this kind of thing from happening!
