### ISSUE TITLE
Erratic behavior with Wacom tablet

### ISSUE THREAD

**Issue by Brier1104** [surge-synthesizer/surge#3701]
**Bug Description:**
When moving a slider it immediately jumps to its opposite end.  Changing the mouse behavior does not change this behavior.

**Version:**
Plugin Host:	Bitwig Studio v3.3.1
System:	Intel CPU, Windows 10 Pro 64-bit, VST3 64-bit
Build Info:	Built on 2021-01-17 at 14:32:20, using pipeline host 'WIN-LQBHPKRFL7J'
Version:	1.8.0.2560170

**Reproduction Steps:**
1. Open Surge
2. Click and drag on any slider using a Wacom tablet

**Comment by baconpaul** [comment]
Weareupdating the manual to reflect this but when using touch interfaces you need to make two settings changes

1: Change the mouse mode to “exact” in the user settings menu
2: Change the mouse displays to “don’t hide cursor” (or “disable cursor hiding”)

And then touch devices will work properly.

**Comment by baconpaul** [comment]
Oh the manual update is in!

Here’s the text from the manual on what to do:

——-
User Settings
In this sub-menu, there are a numerous options regarding the user interface.

Mouse Behavior
This sub-menu contains options allowing you to change the sensitivity of the mouse when moving sliders. While Legacy is used by default, the other 3 options range from Slow (more granular) to Exact (as fast as the mouse pointer). Also, there is an option to keep showing the mouse pointer on the screen when dragging on a control.

Although Surge doesn’t officially have touch screen support, setting mouse movement to Exact and enabling Show mouse cursor while editing is likely to give you the best experience when interacting with Surge with a touch screen.
——-

**Comment by Brier1104** [comment]
Thank you very much Paul.

I had tried all the mouse settings except 'Show cursor while editing'.  It now works perfectly.

Thanks again.

**Comment by baconpaul** [comment]
Great. We get asked enough that I just pushed a menu item labeled "Touch Mode" or some other thing to the mouse menu that does what you need.  Should be in our 1.8.1 'touch up" release next week.

Glad it all worked for you.
