### ISSUE TITLE
Minor drawing bug in S-Curve

### ISSUE THREAD

**Issue by magnetophon** [surge-synthesizer/surge#3708]
**Bug Description:**
When the deform is tiny, the S-Curve draws like this:
![screenshot_20210125_150354](https://user-images.githubusercontent.com/7645711/105716537-415a6480-5f1f-11eb-9371-7fe006bab3fe.png)

It only happens with the S-Curve and only when deform is tiny, not when it is zero.

**Surge Version**

Surge Synthesizer

Plugin Host:	Ardour

System:	x86_64 CPU, Linux VST3, 64-bit
Build Info:	Built on 1980-01-01 at 00:00:00, using local host 'localhost'
Version:	1.8.git-no-branch.git-no-commit

**Computer Information (please complete the following information):**
 - OS: NixOS
 - Host: Ardour
 - Version: 6.5

**Comment by baconpaul** [comment]
Can you save the patch that does that and attach it here as a zip? I can't repro it

**Comment by magnetophon** [comment]
Here you go.

[MESG_draw_bug.fxp.zip](https://github.com/surge-synthesizer/surge/files/5867324/MESG_draw_bug.fxp.zip)

**Comment by mkruselj** [comment]
I can confirm with the deform value from magnetophon's screenshot.

**Comment by baconpaul** [comment]
yup confirmed here also.
thanks both
will figure it out today and get a fix
I have an idea

**Comment by baconpaul** [comment]
Fixed in above PR. Comment justifying the fix way longer than the fix :)
