### ISSUE TITLE
More state information in macro sliders.

### ISSUE THREAD

**Issue by magnetophon** [surge-synthesizer/surge#3709]
In particular:
1) Visually distinguish between a bipolar macro at minimum and a normal macro at 50%
    I often try to tweak a macro in a direction that is not available because of this problem.
2) Show when a macro is set to exactly 0 or 100%.  Also -100% for bipolar macros
    These are often special values in  the sound, for example the values where a patch is in tune.

**Comment by baconpaul** [comment]
Good idea.

We can put a little 'bar' in the middle for bipolar and maybe even do a little gradient color fade from 0 which can toggle at the extrema.

**Comment by mkruselj** [comment]
![image](https://user-images.githubusercontent.com/2393720/105723359-fba19a00-5f26-11eb-855b-ac51a816a7db.png)

We already do have a bar in the middle for bipolar

**Comment by magnetophon** [comment]
Yeah, you do, but the way it is now, you cannot tell the difference between bipolar at minimum and normal at 50%.
Maybe a bar in a different color would be good?

**Comment by mkruselj** [comment]
That's a valid point.

**Comment by baconpaul** [comment]
Yeah agree. We need a few new colors. "Macro Gradient Zero, Pos, Neg, Macro Bipolar Full, Macro Unipolar Full, Macro Bar" basically. Then skin designers can choose how to lay it out to their hearts content.

**Comment by mkruselj** [comment]
For starters I think just having the zero point color. I think a bog-standard gradient might look a bit cheap on these. Next level should be actually making the modbuttons SVGable.
