### ISSUE TITLE
__cdecl breaks VST2 on Linux

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#371]
Hey @jsakkine you must have some way you don't experience this

With master, when I build SurgeGUIEditor.cpp with VST2 I get error

```
In file included from ../VST2SDK/vstsdk2.4/public.sdk/source/vst2.x/audioeffect.h:16:0,
                 from ../VST2SDK/vstsdk2.4/public.sdk/source/vst2.x/audioeffectx.h:17,
                 from ../VST2SDK/vstsdk2.4/public.sdk/source/vst2.x/aeffeditor.h:16,
                 from vst3sdk/vstgui4/vstgui/plugin-bindings/aeffguieditor.h:9,
                 from src/common/gui/SurgeGUIEditor.h:16,
                 from src/common/gui/SurgeGUIEditor.cpp:4:
../VST2SDK/vstsdk2.4/pluginterfaces/vst2.x/aeffect.h:125:32: error: expected ‘)’ before ‘*’ token
 typedef VstIntPtr (VSTCALLBACK *audioMasterCallback) (AEffect* effect, VstInt32 opcode, VstInt32 index, VstIntPtr value, void* ptr, float opt);
                          
```

with the problem at the VSTCALLBACK *audioBlah

In that file you see

```
#elif defined(__GNUC__)^M
    #pragma pack(push,8)^M
    #define VSTCALLBACK __cdecl^M
```

so that expands to `__cdecl *audioMasterCallback`

Now __cdecl is no longer defined so this doesn't build

If I apply this (obviously wrong) diff

```
paul@ubuntu:~/surge$ git diff src/common/gui/SurgeGUIEditor.cpp 
diff --git a/src/common/gui/SurgeGUIEditor.cpp b/src/common/gui/SurgeGUIEditor.cpp
index 0805fcf..f589182 100644
--- a/src/common/gui/SurgeGUIEditor.cpp
+++ b/src/common/gui/SurgeGUIEditor.cpp
@@ -1,6 +1,7 @@
 //-------------------------------------------------------------------------------------------------------
 //     Copyright 2005 Claes Johanson & Vember Audio
 //-------------------------------------------------------------------------------------------------------
+#define __cdecl
 #include "SurgeGUIEditor.h"
 #include "resource.h"
 #include "CSurgeSlider.h"
```

linux builds.

So in your builds, how have you been getting __cdecl defined for VST2 so it builds?

This came up because @kzantow set up a linux build in the azure pipeline and it broke. "That's odd" I thought and went to build, and realized it broke for me too (I have to date only been doing VST3 linux so I set up VST2 linux also and saw it right away).

Don't know how far this goes back but it broke master both before and after the changes I swept today.

Any thoughts appreciated.

**Comment by baconpaul** [comment]
This somewhat more correct definition also works

```
diff --git a/src/common/gui/SurgeGUIEditor.cpp b/src/common/gui/SurgeGUIEditor.cpp
index 0805fcf..128ee0b 100644
--- a/src/common/gui/SurgeGUIEditor.cpp
+++ b/src/common/gui/SurgeGUIEditor.cpp
@@ -1,6 +1,7 @@
 //-------------------------------------------------------------------------------------------------------
 //     Copyright 2005 Claes Johanson & Vember Audio
 //-------------------------------------------------------------------------------------------------------
+#define __cdecl __attribute__((__cdecl__))
 #include "SurgeGUIEditor.h"
 #include "resource.h"
 #include "CSurgeSlider.h"
```

shall we put this back in premake? What is it in your VST2 build env that you don't see this error?

Thanks!

**Comment by jsakkine** [comment]
Looking into this actually now.

**Comment by jsakkine** [comment]
How do you attach a file to a Github issue. Anyway, no build errors.

**Comment by jsakkine** [comment]
Defining it as `__attribute__((cdecl))__` would not make any sense, because that is the calling convention that is anyway used by default (see #174). If anything you should define it as nothing i.e. `#define __cdecl`. Still

**Comment by jsakkine** [comment]
```
#elif defined(__GNUC__)
    #pragma pack(push,8)
    #define VSTCALLBACK //__cdecl
#elif defined(WIN32) || defined(__FLAT__) || defined CBUILDER
	#pragma pack(push)
	#pragma pack(8)
	#define VSTCALLBACK __cdecl
#else
	#define VSTCALLBACK
#endif
```

**Comment by jsakkine** [comment]
That is from my aeffect.h. My suggestion is to update aeffect.h, and not to trash the project because of that. You know we get our VST2 SDK's from random places and we probably want to do quirks because of that :)
