### ISSUE TITLE
Copying a wavetable osc looses it's place in the WT list

### ISSUE THREAD

**Issue by magnetophon** [surge-synthesizer/surge#3710]
**Bug Description:**
When you copy an osc and then click on the "next wavetable" button in the copy, you don't get the WT you would get if you did that on the original.

**Surge Version**

Surge Synthesizer

Plugin Host:	Ardour
System:	x86_64 CPU, Linux VST3, 64-bit
Build Info:	Built on 1980-01-01 at 00:00:00, using local host 'localhost'
Version:	1.8.git-no-branch.git-no-commit

**Computer Information (please complete the following information):**
 - OS: NixOS
 - Host: Ardour
 - Version: 6.5

**Comment by baconpaul** [comment]
True
Irritating to fix tho quickly
So pushed into the 19 milestone

**Comment by baconpaul** [comment]
The reason for this is because the copy paste doesn't copy 'wt.current_id' so the next / previous doesn't know what to do with it. lemme see if that's a quick fix.
