### ISSUE TITLE
Reverb 1 decay parameter doesn't load from FX presets

### ISSUE THREAD

**Issue by TheNerdyMusicGuy** [surge-synthesizer/surge#3717]
Loading a Reverb 1 FX preset doesn't seem to load the correct value for the decay parameter. It's the only parameter that doesn't load, as far as I can tell.
Looking at the FX preset in a text editor, it seems like it is saved correctly, just not loaded.

1. Set the decay parameter of the Reverb 1 effect to some value
2. Save the FX preset
3. Load the FX preset
4. Notice how it is now a different value

Most of the time it seems to go back to the middle (2 seconds), but I also had it go to 1 second, if the saved preset had a very low decay value. It almost seems like some sort of rounding issue. That might just be a coincidence, though.

Surge Synthesizer
Plugin Host: Ableton Live 10.1
System: x86 CPU, Windows VST3, 64-bit
Build Info: Built on 2021-01-23 at 23:52:53, using pipeline host 'WIN-HG095M3EAIA'
Version: 1.8.nightly.0b79f1b

**Comment by baconpaul** [comment]
OK so I just tried this and it worked fine.
Can you attach the broken preset here please?
Thank you!

**Comment by TheNerdyMusicGuy** [comment]
I just tired it again and it worked a few times, but now it's broken again. It happens to any I saved. There is no way of knowing, of course, but the factory presets seem to work fine, since they all have different decay times.

The "Andromeda" preset should have the decay time set to 10s, but when I load it, the slider very briefly shows at the correct position and then suddenly moves to 2s
Same with the "Resonator" preset, but the decay time should be 0.4s and loads as 1s.

[Reverb 1 Preset Bug.zip](https://github.com/surge-synthesizer/surge/files/5875381/Reverb.1.Preset.Bug.zip)

It sometimes works, but switch a few times between those two and you'll probably see the bug.

**Comment by mkruselj** [comment]
Live being a cunt again?

Can you try in Reaper or SAVIhost?

**Comment by TheNerdyMusicGuy** [comment]
Quickly tested in Fruity and it doesn't seem to happen there.

**Comment by baconpaul** [comment]
Right. So I bet it is the VST3 feedback loop problem we’ve seen elsewhere. Sigh. 
I don’t think I can fix that for 181. Lets leave this open and I’l investigate after the install.

**Comment by TheNerdyMusicGuy** [comment]
This did not happen to me for a long time now and it was fairly consistent in the past. Could some recent change have fixed this somehow?

**Comment by baconpaul** [comment]
I 100% bet it was the bitwig thing I just reverted

**Comment by baconpaul** [comment]
As were i bet all the other live double click problems and things

**Comment by baconpaul** [comment]
Maybe 99.9%.

**Comment by TheNerdyMusicGuy** [comment]
Ahh, nice! I'll test this further, when I find the time, to make sure it's really gone.

The issue regarding clicking on the filter sub-type number in Live that someone reported (did they make an issue for it?) is still there, btw. However, that one seems different than the other clicking issues we had in Live.

**Comment by baconpaul** [comment]
I’ll have a credible surge xt next week. I wonder if it will exhibit the same problems? I bet it wont!

**Comment by mkruselj** [comment]
Shall we move this one to Surge XT milestone then?

**Comment by mkruselj** [comment]
I'd love to say "this one doesn't happen in XT", but currently user presets don't even show in the FX presets menu 🙁

**Comment by baconpaul** [comment]
Problem solved!!

**Comment by mkruselj** [comment]
@baconpaul Attached presets from TNMG load fine in Surge XT now that user presets are visible again. Even in Live.

I think we are safe to close this issue.
