### ISSUE TITLE
Long category and patch names overlap

### ISSUE THREAD

**Issue by MD-78** [surge-synthesizer/surge#3725]
**Bug Description:**
Category name "Jacky Ligon\Sequences" and patch name "Quartertone  And The Pitch" overlap

**Surge Version**
This information is found on the About screen, which you get to from the bottom right menu

* Version: 1.8.1.9de9336
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Open Surge
2. Load "Jacky Ligon\Sequences: Quartertone  And The Pitch" patch

**Expected Behavior:**
There should be no overlapping.

**Screenshots:**
![Zwischenablage-1](https://user-images.githubusercontent.com/17949026/106005996-11dd6080-60b5-11eb-92f6-b886d4ef8a53.png)

**Computer Information (please complete the following information):**
 - OS: Windows 8.1 Pro
 - Host: REAPER
 - Version: 6.21 x64

**Comment by baconpaul** [comment]
Yeah we know about this one. It's pretty irritating to fix in VSTGUI - thank you for flagging it though. Will add it to our juce-port milestone. (Also we sort of plan o rewriting that when get have a proper patch browser).

**Comment by MD-78** [comment]
Ok, thank you!

**Comment by mkruselj** [comment]
Yeah once we have a patch browser, we will just show the category tag, rather than folder path. Then it's going to be much nicer.

I also don't think we absolutely _must_ have author name in the patch name display...

**Comment by MD-78** [comment]
Yeah, agreed.

**Comment by mkruselj** [comment]
In the meantime, I improved the layout of things, so stuff is much less likely to overlap now. #3735 fixes this.
