### ISSUE TITLE
Time to update vst3sdk pointer?

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#373]
Our vst3sdk pointer is very old. We are using the Jun 11 pointer and there have been 5 updates since, including ones from @whydoubt and others who have worked on surge.

I'm running into a vstgui problem now (when you setScale on a frame, opition menus appear at the wrong spot; they double-scale the mouse coordinate). Would love to know if it is fixed.

So I could, I suppose, pull vst3sdk to a latest (to hash 82380a8faa33824123104e005bcffb0451151d88) and see what happens

But before I do that work: Anyone object?

**Comment by baconpaul** [comment]
Hmm well I still think it might be time to update our vst3sdk pointer
but I was able to work around the vst2 bug a bit grossly
so I'm not going to do this work anytime soon unless I run into another unsquashable bug

**Comment by kurasu** [comment]
no objections here.. if it breaks everything we can always switch back

**Comment by baconpaul** [comment]
From looking the problem seems to be of two types

1. Things like CPoint and CColor are now in the VSTGUI namespace so either we need a lot of using namespace VSTGUI or a lot of VSTGUI:
2. enums are scoped in classes. So kNoDrawStyle -> COptionMenu::kNoDrawStyle

tedious.

**Comment by whydoubt** [comment]
I have a branch containing the needed changes (namespace and scoping), waiting for when they were useful. I've been busy elsewhere the last couple of weeks though, and hadn't been keeping up with the state of the project.

**Comment by baconpaul** [comment]
Can you attach a .patch file here at least? Or if you branch is rebaseable, toss in a PR? Would be good to know about how much work it is. Happy to work starting at your branch also if you want. Thank you.

**Comment by baconpaul** [comment]
OK I have this all building mac now with the updated pointer. Will begin some testing and seeing if it builds elsewhere.

`baconpaul/vst3sdk-update-373` is my branch

**Comment by esaruoho** [comment]
hmm.. i wonder what kinds of gems we would find in https://github.com/whydoubt/surge/branches/all and how much of it is outdated (already implemented) and how much is yet to be merged in to the main repo.. would be interesting to know.

**Comment by baconpaul** [comment]
Dunno. I do know my vst3sdk update didn't build on windows when I tried, and I'm not going to fix it tonight. But we can get this pointer moved this week (which will also help @sagantech).

**Comment by baconpaul** [comment]
Oh and with the pointer moved, everything seems to work fine on mac. On windows, it's puking on a std::numeric_limits<uint32_t>::max()

**Comment by sagantech** [comment]
Yes I had that too.

**Comment by baconpaul** [comment]
Did you get around it?

**Comment by sagantech** [comment]
Does your surgesynthesizerIO.cpp start like this:

//	Copyright 2005 Claes Johanson & Vember Audio
//-------------------------------------------------------------------------------------------------------
#include "SurgeSynthesizer.h"
#include "DspUtilities.h"
#include <time.h>
#if MAC
#include <pthread.h>
#else
#define NOMINMAX  1

**Comment by sagantech** [comment]
I think #define NOMINMAX 1 is the key

**Comment by baconpaul** [comment]
OK let me check

**Comment by baconpaul** [comment]
Yeah if I define NOMINMAX in premise it goes away. Thank you!

**Comment by baconpaul** [comment]
premake

**Comment by sagantech** [comment]
No prob.

**Comment by baconpaul** [comment]
Don't suppose you figured out the IDropTarget one also did you?
That's the last one on my list.

**Comment by baconpaul** [comment]
Sigh. I have figured it out
If you do a using namespace VSTGUI too early then when you load windows.h it conflates with vstgui::idroptarget and ::idroptarget.
That means I need to do a lot of surgery to not do the (gross) thing of including using namespace in my .h which I had hoped would save us.
So damn tedious. Giving up for now.

**Comment by whydoubt** [comment]
Just got mine rebased.  Haven't tested it though.
https://github.com/whydoubt/surge/tree/sdk_update

**Comment by baconpaul** [comment]
@whydoubt cool - i got a pr together last night that builds and works Mac win Lin. Curious how you solved the windows numeric-limits max problem tho? @sagantech found and I confirmed that nominmax in windows dealt with it but wonder if you found another way.

Thanks!

**Comment by baconpaul** [comment]
OK merged into master.  @whydoubt if you have a better way than the NOMINMAX I'm all ears! Can you just drop it into another issue? Thanks!
