### ISSUE TITLE
fractional ratios in FM oscillators

### ISSUE THREAD

**Issue by magnetophon** [surge-synthesizer/surge#3730]
Sometimes you want the modulator to have a lower frequency than the carrier.
1:1 should be the middle of the slider, imho.

**Comment by baconpaul** [comment]
If you use FM3, and choose 'extend range', it is!

**Comment by magnetophon** [comment]
Would be nice for FM2 as well though.
Feel free to reopen if you agree.

**Comment by baconpaul** [comment]
really hard for a technical reason involving ints and extending.
