### ISSUE TITLE
MSEG less zoomed when Rate is deactivated.

### ISSUE THREAD

**Issue by magnetophon** [surge-synthesizer/surge#3731]
When the rate is deactivated, the small display of the MESG zooms all the way in.
It would be nice if it could show the whole MESG in that case.

**Comment by baconpaul** [comment]
Good find. 3 line fix.

**Comment by magnetophon** [comment]
Fixing the code: seconds.
Knowing how to fix: decades!

Thank you!

**Comment by baconpaul** [comment]
Yeah mseg is the only waveform that doesn’t have period 1 so that was the fix as you saw
