### ISSUE TITLE
BBD ensemble/chorus

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3743]
Let's see if we can add one, with help from jpcima's ensemble effect emulation (if he permits).

Here's some more useful things from a certain Reaktor ensemble, this will explain how the LFOs are intermingled:

![image](https://user-images.githubusercontent.com/2393720/106208147-36bff980-61c3-11eb-9ec6-7608d3e9300f.png)

F1 - frequency of first LFO, A1 - amplitude of first LFO, etc.

![image](https://user-images.githubusercontent.com/2393720/106208185-45a6ac00-61c3-11eb-9e1f-0edb5b517d26.png)

Looking into the 3 Phase Ensemble structure, you can see 0.18, 0.6 etc, those numbers are default values for LFO rates and amplitudes. Two LFOs give out three different signals that modulate the 2-tap delay (which is our 512-stage BBD chip emulation).

![image](https://user-images.githubusercontent.com/2393720/106208699-0d539d80-61c4-11eb-9af3-925c20861b78.png)

This is the LFOs structure, where you can see how it all mingles together. ms2sec is just a multiply by 0.001 (duh!). ms is 5 as it says to the left of the port.

![image](https://user-images.githubusercontent.com/2393720/106208795-3aa04b80-61c4-11eb-9959-97fd57817993.png)

This is the LFO itself, it has a phase driver (which goes -1...1, not 0...1!), some wrapping `out = in - round(in)` and Par shaping block, which amounts to `out = (8 - (abs(in) * 16)) * in`.

This is the Phase driver:

![image](https://user-images.githubusercontent.com/2393720/106208929-720ef800-61c4-11eb-9379-5f58a911fd17.png)

SR.R is sample rate constant, SR.C is sample rate clock (I guess in Surge terms this means, process() on every sample?). Latch module holds the incoming value and reads it out at SR.C rate. Wrapper is again `out = in - round(in)`. z^-1 ndc is a one sample delay, ndc means "no denormal cancel".

That's about it. Not gonna go inside the 2-tap delay block because that's gonna be replaced by some other code anyways.

**Comment by baconpaul** [comment]
https://github.com/kunstmusik/libsyi/blob/master/solina_chorus.udo

And

https://github.com/jpcima/ensemble-chorus/issues/14

**Comment by baconpaul** [comment]
https://colinraffel.com/software/bbdmodeling/echo.cpp

That’s what jp is built on and it is super handy.

**Comment by mkruselj** [comment]
Probably better to go with that newer BBD emulation from daFX paper, of course 🙂

**Comment by baconpaul** [comment]
That’s what jos code does. All the same rhing

**Comment by baconpaul** [comment]
Ahh all caught up now. 
yes use the new stuff indeed

**Comment by jpcima** [comment]
If this can be of any use, I'm copying a relevant part of a synth service manual
It mentions also a delay rating.
![omni1](https://user-images.githubusercontent.com/17614485/106278016-42023c00-623a-11eb-8c44-1b463a379565.png)
![omni2](https://user-images.githubusercontent.com/17614485/106278027-44649600-623a-11eb-849a-6b9fc58d4572.png)
![omni3](https://user-images.githubusercontent.com/17614485/106278032-475f8680-623a-11eb-982f-9e28452d7344.png)

**Comment by mkruselj** [comment]
Right, Omni has a different scheme by using 3 individual LFOs, whereas Solina uses the 3-phase 2 LFO deal. I kinda like the Solina better personally.

**Comment by mkruselj** [comment]
Dropping this in for reference, too.

[Jiggery-Pokery_Chenille_Chorus_Ensemble_RE.pdf](https://github.com/surge-synthesizer/surge/files/5895078/Jiggery-Pokery_Chenille_Chorus_Ensemble_RE.pdf)

**Comment by mkruselj** [comment]
We can basically close this issue now, only very few things left to polish and @jatinchowdhury18 is aware of it. 🙂
