### ISSUE TITLE
Royal Surge Skin: higher zoom levels

### ISSUE THREAD

**Issue by mzed** [surge-synthesizer/surge#3746]
The default scaling setting for my laptop monitor is 250%. The other two skins can zoom to that level, and look good to my aging eyes. But, Royal Surge seems to be capped at 200%.

**Comment by mkruselj** [comment]
You can open the skin.xml and add a new line in `<zoom-levels>` section. 250% asset is already there but is used for HiDPI/Retina use case, however you can work around that by adding `<zoom-level zoom="250"/>` before `</zoom-levels>` in there.
