### ISSUE TITLE
Make patch jog buttons continue to next or previous folder

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3749]
Currently, the patch prev/next buttons only go through the currently selected folder, which is ok but is not the usual workflow I notice in other plugins.

I suggest moving the current behavior to right click on the prev/next buttons, and making left click just go through the whole flat preset list from the currently selected folder.

@baconpaul Doable for 1.8.2?

**Comment by baconpaul** [comment]
the dual mode is hard with the wya they work (they send a value change message without control keys) so it would involve a lot of plumbing.

pushing out of 182

**Comment by mkruselj** [comment]
OK but what if instead of that we add a User Settings>Workflow option, then it's chosen by the user (by default it would go through all the files, and option would restore old behavior)? Makes it easier then?

**Comment by baconpaul** [comment]
Sure then it is just handling the tag_mp messages differently in SurgeGUIEditor. That's super easy.

**Comment by baconpaul** [comment]
Basically the approach is

1. Add a second argument to SurgeSynthesizer::incrementPatch so it takes nextPrev and also insideCategory. Default inCategory to true inside the header.
2. where that is called from SGE query the user pref. (Query it in SGE not in the Synth pls) and pass it in
3. Write the code accordingly to find the next category almost definitely using 'if' and 'incrementCategory'

**Comment by mkruselj** [comment]
Back to 1.8.2 then? 🙂

**Comment by baconpaul** [comment]
Sure! The easier thing is totally 182 doable.
