### ISSUE TITLE
Have UserDefaults

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#375]
Right now, Surge makes a lot of choices for you. patches are in ~/Documents/Surge (or whatever) your default zoom is 100% your default patch is the built in init. If you imagine a world with skins (which is post 1.6) etc...

But most proximate is that default zoom so on path to zoom I was planning on adding a user defaults mechanism.

Here's a rough design of how I would do it

* Implement in the Surge::Storage namespace functions like `loadUserDefaults` 'getUserDefault(string key)`, `setUserDefault(string key, string value)`. 
* Have `getUserDefault` be implemented (in pseudocode) as

```
if( loaded_defaults.contains[ key ] ) return loaded_defaults[ key ]
else if( system_wide_initi_defaults.contains[ key ] ) return the
else promptError
```

* have `loadUserDefaults` and `setUserDefaults` write an XML file of the implicit key value map
* *Here's the one bit I haven't figured out*. Store that XML file somewhere. But where
     * An obvious choice is `~/Documents/Surge` and the mac and lin equivalent. But then we can't change that directory with defaults
    * Another obvious choice is `~/.surge_defaults` on mac and linux and the registry on windows. But registry. Ugh.
    * So this one gets a 'design required' flag

I would like to resolve this on the path to zoom #305 so we can resolve #374 in a more general way.

Welcome any thoughts. No way I'm working on this anytime soon.

**Comment by sense-amr** [comment]
is it possible to shrink by 25% or any known % when surge is at ordinary 100% size? that is .. make it smaller ?

id like to make them smaller if possible

**Comment by baconpaul** [comment]
Right now sizes < 100 onkybwork with the au zoom not the vst zoom. May be fixable. All to do with the background scaling bug. Separate issue tho

**Comment by esaruoho** [comment]
I guess for the sake of posterity I'll just create a ticket for less than 100%. Otherwise it'll get lost when this ticket closes.

**Comment by baconpaul** [comment]
thanks guys!

**Comment by baconpaul** [comment]
OK this is next in my list - working on it and default zoom (#586 and #456 included) now.

**Comment by esaruoho** [comment]
awesome.
