### ISSUE TITLE
LFO for Comb Frequency in Neuron

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3755]
@jatinchowdhury18 a request from Jacky L and we have slots

Lets add a little LFO that lets you modulate the frequency of that comb filter with some rate and depth (so 2 slots)

I'm happy to add it or happy for you to. The flanger shows how to add an LFO easily etc... but I am sure it is not even remotely surprising. Wanted to drop it here though as an issue

Only trick is we will have a choice of 'add params in the middle' which means old streamed sessions will break (which is OK - we are still in the nightlies) or 'add it at the end' which means they won't but we have to re-order the UI using that hokey API.

**Comment by mkruselj** [comment]
I'd really want to add them in the middle. Nightlies gonna nightly.

**Comment by baconpaul** [comment]
yeah cool

**Comment by jatinchowdhury18** [comment]
I would lean towards middle as well...

I'd be happy to take a look this weekend. (For reasons that would take way too long to explain, I've been insanely busy the past few days, but I expect to have a ton of time to kill in the coming week)

**Comment by baconpaul** [comment]
Yeah cool! Middle it is. It's only bee in 3 days of nightlies. We can change the streaming!

**Comment by baconpaul** [comment]
and thanks! Super cool effect.

**Comment by mkruselj** [comment]
Sine, triangle, saw, square, S&H?

**Comment by mkruselj** [comment]
Just to let you guys know, now you have controls added for the LFO at head. 🙂
