### ISSUE TITLE
Nimbus - Mutable Instruments Clouds inspired granular effect

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3756]
https://github.com/pichenettes/eurorack/issues/35#issuecomment-770001083

With this in place here's the current bug and desired change list. Feel free to edit and add or post below.

- [x] Swapping quality can silent the FX (from mkruselj - @baconpaul I don't think this is a bug, it probably purges buffers when changing quality modes- it is not a bug. The internal state resets when swapping)
- [x] 16khz modes are crashing for me right now. The reason for this is that the ::Process method in the low quality modes assumes an even number of samples. So basically what I need to do is if the downsampled gives me an odd number keep one around for the next block and always pass an even.
- [x] "Spectral Mode is among the most interesting in terms of its feedback behavior... Even with Grain Size, Grain Density, Freeze and Feedback set to zero, in this mode, really long feedback times are still possible. Seems that some degree of feedback is happening, although the above are set really low..." (This was my mis-handling of trigger)
- [x] I scale to 32627 or what not. Does that work in quality low modes? Should I bring it back a bit to give us a smidge of headroom also? Etc.... Nope; 32627 is correct
- [x] Move to the new dynamic name mechanism
    - [x] Granularizer stays as is (duh!).
    - [x] Pitch Shifter: Density becomes Diffusion, ct_percent, default value 0. Texture becomes Filter, ct_percent_bidirectional, default value middle of slider. Size becomes ct_percent. 
    - [ ] Looping Delay: Density becomes Diffusion, ct_percent, default value 0. Texture becomes Filter, ct_percent_bidirectional, default value middle of slider.
    - [ ] Spectral Madness: Density is renamed to Smear. Texture becomes ct_percent_bidirectional.
    - [ ] Spread parameter doesn't work in any mode other than Granulizer, and only in the two stereo qualities, so should be disabled in other modes. (@baconpaul - it works in mono modes as well! But indeed, only for Granulizer)

**Comment by mkruselj** [comment]
Parameter layout:

```
INPUT
    Gain

GRAIN
    Position
    Size
    Density
    Texture
    Pitch

PLAYBACK
    Freeze (integer slider)
    Feedback

OUTPUT
    Reverb
    Width
    Mix    
```

**Comment by baconpaul** [comment]
I was considering making freeze a float and comparing it with 0.5 since I think we will want to modulate it.

**Comment by TheNerdyMusicGuy** [comment]
That would indeed be very nice!

**Comment by baconpaul** [comment]
And we can use one more for mode and get this:

```
        nmb_in_gain,
        nmb_mode,

        nmb_position,
        nmb_size,
        nmb_density,
        nmb_texture,
        nmb_pitch,

        nmb_freeze,
        nmb_feedback,

        nmb_reverb,
        nmb_spread,
        nmb_mix_aka_blend,
```

**Comment by mkruselj** [comment]
Mode should be in Playback section :)

**Comment by baconpaul** [comment]
yeah we can figure out the way to make it not-as-cruddy-a-user-experience if we end up liking the integration. but from using it you clearly want it as a mod source.

**Comment by baconpaul** [comment]
Bug report: Swapping 'quality' can cause the plugin to go silent. I wonder if I need to do some other refresh/restart when I change this.

**Comment by mkruselj** [comment]
Certain parameters should change their name and polarity based on Nimbus modes:

Granularizer stays as is (duh!).

Pitch Shifter: Density becomes Diffusion, `ct_percent`, default value 0. Texture becomes Filter, `ct_percent_bidirectional`, default value middle of slider. Size becomes `ct_percent`.

Looping Delay: Density becomes Diffusion, `ct_percent`, default value 0. Texture becomes Filter, `ct_percent_bidirectional`, default value middle of slider.

Spectral Madness: Density is renamed to Smear. Texture becomes `ct_percent_bidirectional`. 


Spread parameter doesn't work in any mode other than Granulizer, so should be disabled in other 3 modes.
