### ISSUE TITLE
Curves for macros and aftetouch, pitchbend etc...

### ISSUE THREAD

**Issue by arumihsnek** [surge-synthesizer/surge#3758]
Hi Team!

This Synth it's really good to make instruments for Wind Controllers, but there are one thing that can inprove that a lot (and not only for wind controllers).

I could be amazing to add different "curves" to macros, or even beter, curves to each binding.

Click in the parameter to bind to the macro (maybe in the right click menu after select a macro or aftertouch, etc) and select a different curve.

Like that we can use the same macro to affect in different way each parameter. For example to make realistic instruments or improve de expresivity of the sounds.

It can be usefull for keyboardist the ModWhell, velocity, pitch bend with différents curves.

Thanks for the work, this synth is amazing.

**Comment by mkruselj** [comment]
We already have that on file, here:

https://github.com/surge-synthesizer/surge/issues/1384

**Comment by baconpaul** [comment]
Yeah definitely agree. We call this feature 'mod mappers' and plan them for a release sometime in 2021 (still not sure when exactly). See the discussion over here: https://github.com/surge-synthesizer/surge/issues/2676

Basically we plan on adding something like a modulation mapper which has a custom curve mapping -1,1 -> -1,1, and then you can just put that in the matrix.

**Comment by TheNerdyMusicGuy** [comment]
Hey!

"Mod Mappers" like in Zebra or Vital are definitely planned! Those would allow you to do exactly these kinds of things and a lot more!

**Comment by baconpaul** [comment]
Ha all three of us at once.

Anyway @arumihsnek as you can see we all want this! There's some technical reasons it's tricky but definitely on the radar.

**Comment by baconpaul** [comment]
Oh and thanks for the kind words on surge :)

**Comment by arumihsnek** [comment]
Wow! Thanks for the quick answers!
