### ISSUE TITLE
CMD (mac) / CTRL (windows) will revert StepSeq LFO to Sine LFO when clicking on StepSeq display with CMD/CTRL down

### ISSUE THREAD

**Issue by sense-amr** [surge-synthesizer/surge#376]
Pressing inside the selected LFO shape display whilst holding control results in an immediate snap back to Sine Wave LFO shape.. 

[Control LFO click reset to Sine.zip](https://github.com/surge-synthesizer/surge/files/2783095/Control.LFO.click.reset.to.Sine.zip)

**Comment by baconpaul** [comment]
@sense-amr the behavior I see at head is

1: shift and control *double* click returns you to sine
2: alt and *single* click returns you to sine

when clicking on the graphic of the picture

both weird but want to make sure you see what I do.

The control double click matches what happens on sliders too. But on sliders a double click without any modifier held also returns you to zero. And alt click returns you to zero also.

**Comment by esaruoho** [comment]
from my end on RenoiseVST2, it works like this:
Be in StepSequencer
CMD-Click on a step -> Sine
ALT-doubleclick on a step -> Sine
CTRL-doubleclick on a step -> Sine
Shift-doubleclick on a step -> Sine

so slightly different behaviour from windows. anyway. clarified the title a bit

**Comment by baconpaul** [comment]
@sense-amr your diagnosis is absolutely right. This is the "set default value on double click or control click" code path doing the wrong thing on this element. The code in question is the "else { p->set_value_f01(p->get_default_value" around like 1917 of SurgeGUIEditor.cpp.

**Comment by baconpaul** [comment]
Anyway I have a fix. Will sweep it in when the auto builds are done and close this issue.
