### ISSUE TITLE
SS and Mod reported on KVR

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3760]
Ficciones wrote: ↑Fri Jan 29, 2021 1:20 pm
EvilDragon wrote: ↑Fri Jan 29, 2021 1:14 pm
You can trigger envs from any of the 6 voice LFOs. That was an improvement we added vs the old commercial version. :)
Excellent, it's a great feature, but I could only get gates out of the second voice sequencer gate lane after adding a destination for the modulation lane. I'm just poking around in the dark here lol.  :lol:
I really thought I fixed that in 1.7 vintage. I’ll add your comment to github and confirm/fix or come back here

**Comment by mkruselj** [comment]
I made a patch where three voice LFOs are triggering the envs, works just fine?

**Comment by mkruselj** [comment]
Oh, I see now. For VLFO 1 you don't need to have any modulation actually assigned for the triggers to work. This doesn't seem to be the case for VLFOs 2-6.

Def warrants a fix to make it consistent!

**Comment by baconpaul** [comment]
```
for (int i = 1; i < 6; i++)
    {
        if (scene->modsource_doprocess[ms_lfo1 + i])
            lfo[i].process_block();
    }
```

this block in SurgeVoice is why it doesn't go. The special case for 0 above is why 0 works.

I think the solution is to make that

```
if( scene->modsource_doprocess[ms_lfo1 + 1] || (mod source is step sequencer && has any trigger lanes) )
   // process block
```

writing that condition is a bit tricky but not that hard. This one is 15 minutes when I have time.

**Comment by baconpaul** [comment]
Actually right fix is to pus upstream one and adjust modsource_doprocess using the same condition. Will do it that way.

**Comment by baconpaul** [comment]
yeah got it. pr today.
