### ISSUE TITLE
Reorganize FX User Preset Menu (was Request Ability to save/recall FX settings / Routings)

### ISSUE THREAD

**Issue by sense-amr** [surge-synthesizer/surge#378]
I find myself needing to remember the settings i used in a particular reverb or EQ setup if i wanted to use it again in the FX section.. I wonder if it would be possible to have the ability to save .. particular set ups in the FX section and also to save individual FX presets.. 

is it possible that 
![presetfxsaveandrecall](https://user-images.githubusercontent.com/1504019/51548242-123a3400-1ebc-11e9-9567-c14d36200d9c.jpg) could have an added menu option that allows -> Preset to be recalled? .. 
and a "store" button ?
![fx store](https://user-images.githubusercontent.com/1504019/51548588-bb812a00-1ebc-11e9-94a1-6e52e9553bb6.png)

**Comment by esaruoho** [comment]
related to #309

**Comment by baconpaul** [comment]
FYI some preliminary code exists in CSnapshotMenu.h to do this (but we would want to change it some to use a different target).

**Comment by baconpaul** [comment]
Yeah @sense-amr this is the "save" as opposed to "move" issue over here. Although I can use the same UI gesture to make this one work also so can move this from the 1.7 to the 1.6.2 milestone.

**Comment by sense-amr** [comment]
ok ill check out the latest build .. now that i have time again :)

**Comment by baconpaul** [comment]
Cool! But the copy and paste isn't in the latest build yet. I'm literally coding it right now.

(The solo muting is tho as are several other bug fixes).

**Comment by tank-trax** [comment]
this thought has come to me a few times, would really like to see a function to save user FX presets too

**Comment by baconpaul** [comment]
Just an FYI: I did a push today that has this almost completely done. Totally usable just one UI/UX thing I want to improve.

**Comment by mkruselj** [comment]
- [ ] FX preset menu should have User Presets listed under each individual effect's menu, rather than one global User Presets menu that repeats the whole FX type tree.

![image](https://user-images.githubusercontent.com/2393720/83408180-8078fa00-a412-11ea-98aa-b9030dd8cfc8.png)

Like so (but add a separator before User Presets submenu!).

**Comment by mkruselj** [comment]
Yeah we can close this one now? Or do we wait until 1.7 is officially out?

**Comment by baconpaul** [comment]
I haven't done the menu re-org so lets leave it open until I do.
