### ISSUE TITLE
Filter glyph placement

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3782]
This one is juce-independent, really just parameterizing the glyph placement

Dave wants to put the filter glyph below the menu and have it be bigger. 

So basically add a relative offset etc.... type thing to the filter properties

[filters-2.svg.zip](https://github.com/surge-synthesizer/surge/files/5901424/filters-2.svg.zip)

Here's an SVG to test with

**Comment by mkruselj** [comment]
Also add an option to just not draw the filter icon too, might not hurt.

**Comment by baconpaul** [comment]
Yup
