### ISSUE TITLE
Bitwig and Modulation

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3783]
From the massive KVR thread user "bboxdw" reports

I just checked this out and was able to duplicate it with Bitwig 3.3.1 and Surge 1.8.1.9de9336 on Win 10, but going beyond the classic LFO random. In the attached Bitwig project, I've set up an instance of Surge with 4 Bitwig LFOs (classic LFO quantized random, classic LFO random, classic LFO sine, and beat LFO triangle), each set up modulate one of Surge's 4 filter cutoff parameters. Each one is set up for bipolar modulation of 0.5 from the default value (corresponding to the center/0 point of the Bitwig parameter modulation knobs). 

I've typed "cutoff" into the search box so you can easily see the settings before and after opening the plugin window.
What I've observed is that the proper settings are retained upon saving and reopening the project, until the plugin window is opened. At that point, all the modulators' "base" values are changed to a setting other than the default value. Each time you close/reopen the project and then open the Surge window, you'll get new base values.

I'll also submit this to BW support.

[bugtest_bwlfo_surge.zip](https://github.com/surge-synthesizer/surge/files/5901447/bugtest_bwlfo_surge.zip)

**Comment by baconpaul** [comment]
My modified simpler one
[modified.zip](https://github.com/surge-synthesizer/surge/files/5901528/modified.zip)

basically run that in bus
the first time you open it when you open the editor you will hear it change the center point
now if you drag the cutoff it also changes the center point
this means when we open the editor we are sending a specious setParameterAutomated, but sending it to the modulated not the base value
so that's the bug. don't know what the fix is yet.

**Comment by baconpaul** [comment]
So that's not actually it. Its a bit weirder.

When you open the UI, Bitwig is doing a getParameterNormalized on every param and setting that as the param onto the control. I put logs in the VST3 for setParam and getParam Normalized on 200 (which is filter cutoff). When I start bitwig I see it does a bunch of gets then starts chipping away setting my param - great that's the LFO working.

But when I open the UI it does another blast of getParams

By that point, though, my params are whatever the LFO has set me to

And then it uses those getParams to re-set the LFO

So either (1) there's some VST3 API I don't know about to have 'get saved param' vs 'get param' or (2) bitwig doesn't expect set param / get param one after another to return the same result (which is super wierd) or (3) there's a bitwig bug or (4) something else.

**Comment by baconpaul** [comment]
Right you can see this clearly by adding the following into the VST3 processor

```
if( tag == 200 )
    {
        static bool didit = false;
        if( ! didit )
        {
            didit = true;
            return res;
        }
        std::cout << __LINE__ << " getParamNormalized " << tag << " " << res << std::endl;

        return 0.9;
    }
```

this means the first get is OK and everyone thereafter returns 0.9

with this in place every time you open the surge ui with the LFO on the base resets to 0.9 (which is whatever 14khz who cares) because the act of opening the UI requires the params and resets the modulator centers.

I really think this might be a bitwig bug. @abique - do you still read GitHub notifications? I'm a bit stuck here if so.

**Comment by baconpaul** [comment]
Same behavior in BW3.1.2 fwiw

**Comment by baconpaul** [comment]
So arturia Jup V4 doesn't do this. It's a surge bug of some form. Just not sure what form yet.

**Comment by NickJAllen** [comment]
What I can see from our end (Bitwig) is that when we ask you to open the Plugin GUI a timer ends up calling restartComponent() with kParamValuesChanged and kParamTitlesChanged. This makes Bitwig think that a new preset has been loaded. When we ask for the value of the parameter from the new preset we get the modulated value and we use this as the new base value. I have no idea why you are saying that the parameter values and titles have changed just when opening the GUI. GUI open or not should not affect the state of the parameters so this seems like a bug in Surge not Bitwig. Let me know if you need further help from our side...

**Comment by baconpaul** [comment]
Ahh that is profoundly useful and is definitely our bug!!!

Thank you so much!!!!

**Comment by baconpaul** [comment]
OK so your hint gave me a fix. 

The reason it was happening by the way is we were sending a message when param names changed using restartComponent. But restartComponent can only be on the UI thread so it got queued up and that's why opening the UI (and therefore starting the UI thread) sent the param name reset.

But renaming the params is really a nice to have not a necessary. We are starting a port to JUCE so we aren't on the semi-hellish combination of vstgui and vst3 hand rolled plugin we have today. So for now I just disabled the call to restartComponent and it all works (although our params keep their generic names under FX change or whatever - but that's OK).

Appreciate the help. Thank you.

**Comment by NickJAllen** [comment]
Ok great glad we could help you find the cause of the problem!
