### ISSUE TITLE
Surge: In Cubase cannot route audio into Surge. 

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#379]
I believe that given @baconpaul stated (and this is bore out in other Hosts) Surge can have audio routed to it, this is a bug.

Using either VSTi 2.4 or VST3 does not allow for side chaining. Meaning, that it does not show up in the GUI in the plug in window chrome. Additionally, Cubase does not show Surge as an audio plug in. As evidenced by these screens:

<img width="761" alt="screen shot 2019-01-22 at 12 13 55 pm" src="https://user-images.githubusercontent.com/11078351/51556960-36a4fa80-1e41-11e9-8fca-d1ba7482281b.png">

<img width="1373" alt="screen shot 2019-01-22 at 12 14 45 pm" src="https://user-images.githubusercontent.com/11078351/51556973-3d337200-1e41-11e9-94c7-789a82a0a5ff.png">

Showing Surge VST3. No side chain button along plug in window chrome. It should be showing up right next to the black drop list window but its not. 

<img width="1337" alt="screen shot 2019-01-22 at 12 30 33 pm" src="https://user-images.githubusercontent.com/11078351/51557096-913e5680-1e41-11e9-83f3-2045dbeb5d8c.png">

This video leads me to believe that there is work to be done to get this happening (at least) in the case of VST 3.

https://www.youtube.com/watch?v=PBQr-PnI6Yw

**To Reproduce**
1. Open Cubase project.
2. Insert a VSTi
3. Look at VSTi plug in window chrome for side chain button
4. Notice it's missing.

It should be here:

<img width="990" alt="screen shot 2019-01-22 at 12 44 11 pm" src="https://user-images.githubusercontent.com/11078351/51557776-78cf3b80-1e43-11e9-9029-63c64f985444.png">

**Desktop (please complete the following information):**
 - OS: [macOS 10.14.2]
 - Host [Cubase]
 - Version [9.5]

**Comment by sense-amr** [comment]
> I believe that given @baconpaul stated (and this is bore out in other Hosts) Surge can have audio routed to it, this is a bug.

maybe it should be Surge can NOT have audio routed to it :) 
@itsmedavep

**Comment by baconpaul** [comment]
Linking this to #1005

**Comment by baconpaul** [comment]
Hey @itsmedavep I bet you thought I forgot about this one? 

Well: 

<img width="516" alt="Screen Shot 2019-12-03 at 5 50 43 PM" src="https://user-images.githubusercontent.com/13387561/70096676-9ccbe380-15f5-11ea-86da-fd2aabd0ad4c.png">

Lemme get it pushed and maybe you can do a test for me in cubase beyond the test I did (which is: it showed up).

**Comment by baconpaul** [comment]
Requires the VST3 of course.
