### ISSUE TITLE
question from KVR: "would it be less work to make binaries with an install script for linux?"

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#381]
from KVR:

```
Would it be less work to make binaries with an install script for linux?
This has worked almost perfectly with the many U-he linux plugins
ported by Abique.
```

**Comment by baconpaul** [comment]
I think this is addressed in #360 and #365 
I have no particular opinion on how to package for linux desktop and UI applications. Just tagging this as a dup with the conversations over there!

Thanks
