### ISSUE TITLE
Add Mutable Instruments Plaits as oscillator type

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3810]
- [x] Profile some to see if it is prohibitive
- [x] The resampling is a lot of the CPU. We have to do it per voice also to participate in FM (and cross-osc resampling is painful) but perhaps make the resample quality an option or make sinc_fastest the default (which is fine)
- [ ] Right-click option on Aux to "extend" - alternative mode where main is L, aux is R, and the Aux slider crossfades between L-R (main-aux) and R-L (aux-main) - name the parameter Main<>Aux Spread (bipolar %)

Parameters:

Engine (meenu, 16 entries - it should map to the two buttons of 8 models on the actual Plaits module)
Harmonics (+/- 100%)
Timbre (+/- 100%)
Morph (+/- 100%)
Aux Mix (0-100%) - blends in the stuff from Aux port
LPG Response (0-100%, deactivatable to take out LPG from the picture)
LPG Decay Time (0-100%)

**Comment by baconpaul** [comment]
Aux Mix being deactivatable does a L out R aux, which is sometimes useful

**Comment by mkruselj** [comment]
Cool, that would be good, too.

If we can rename parameters depending on model, I would love to see that. Here's the list:

1. TONAL - CLASSIC WAVEFORMS
Harmonics -> Detune
Timbre -> Square Shape
Morph -> Saw Shape
Aux Mix -> Sync Mix

2. TONAL - WAVESHAPER
Harmonics -> Waveshaper
Timbre -> Fold
Morph -> Asymmetry
Aux Mix -> Variation Mix

3. TONAL - 2-OP FM
Harmonics -> Ratio
Timbre -> Amount
Morph -> Feedback
Aux Mix -> Sub Mix

4. TONAL - FORMANT/PD
Harmonics -> Ratio/Type
Timbre -> Formant/Cutoff
Morph -> Shape
Aux Mix -> PD Mix

5. TONAL - HARMONIC
Harmonics -> Bump
Timbre -> Peak
Morph -> Shape
Aux Mix -> Organ Mix

6. TONAL - WAVETABLE
Harmonics -> Bank
Timbre -> Morph Row
Morph -> Morph Column
Aux Mix -> Lo-Fi Mix

7. TONAL - CHORDS
Harmonics -> Chord Type (oct, 5th, sus4, min, m7, m9, m11, 6/9, M9, M7, Maj)
Timbre -> Chord Inversion
Morph -> Shape
Aux Mix -> Root Mix

8. TONAL - VOWELS & SPEECH
Harmonics -> Speak
Timbre -> Species
Morph -> Segment
Aux Mix -> Raw Mix

9. NOISE - GRANULAR CLOUD
Harmonics -> Pitch Random
Timbre -> Grain Density
Morph -> Grain Duration
Aux Mix -> Sine Mix

10. NOISE - FILTERED NOISE
Harmonics -> Type/Separation
Timbre -> Clock Frequency
Morph -> Resonance
Aux Mix -> Dual Peak Mix

11. NOISE - PARTICLE NOISE
Harmonics -> Freq Random
Timbre -> Density
Morph -> Filter Type
Aux Mix -> Raw Mix

12. PERCUSSIVE - INHARMONIC STRING
Harmonics -> Inharmonicity
Timbre -> Brightness
Morph -> Decay Time
Aux Mix -> Exciter Mix

13. PERCUSSIVE - MODAL RESONATOR
Harmonics -> Material
Timbre -> Brightness
Morph -> Decay Time
Aux Mix -> Exciter Mix

14. PERCUSSIVE - ANALOG KICK
Harmonics -> Sharpness
Timbre -> Brightness
Morph -> Decay Time
Aux Mix -> Variation Mix

15. PERCUSSIVE - ANALOG SNARE
Harmonics -> Tone<>Noise
Timbre -> Model
Morph -> Decay Time
Aux Mix -> Variation Mix

16. PERCUSSIVE - ANALOG HI-HAT
Harmonics -> Tone
Timbre -> Low Cut
Morph -> Decay Time
Aux Mix -> Variation Mix

**Comment by mkruselj** [comment]
> Aux Mix being deactivatable does a L out R aux, which is sometimes useful

Probably makes more sense to use extend rather than deactivate? The slider could then do panning swap perhaps, where out moves from L to R, and at the same time aux goes from R to L?

**Comment by mkruselj** [comment]
Parameters that need to change from bipolar to unipolar depending on mode:

**Waveshaper:** Fold, Asymmetry
**2 OP FM:** Amount
**Harmonic:** Bump, Peak
**Chords:** Chord Type
**Vowels/Speech:** Speak, Segment
**Granular Cloud:** Pitch Random, Grain Density, Grain Duration
**Filtered Noise:** Clock Frequency, Resonance
**Particle Noise:** Density
**Inharmonic String:** Inharmonicity, Brightness, Decay Time
**Modal Resonator:** Material, Brightness, Decay Time
**Analog Kick:** Sharpness, Brightness, Decay Time
**Analog Snare:** Model, Decay Time
**Analog Hi-Hat:** Low Cut, Decay Time
