### ISSUE TITLE
Parameterize the patch browser layout

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#3814]
Right now if you want to change the patch browser look and feel you need to cook it into the BG of the overall synth. 

Thats entirely workable, however it would also be nice to have the ability to do 

```` <control ui_identifier="controls.patch_browser" img="patch-browser" x="216" y="16" w="457" h="42"/>````

**Comment by baconpaul** [comment]
Individually position the category and author as components and update the skins

**Comment by baconpaul** [comment]
Pushing to XT like the skin model stuff

**Comment by mkruselj** [comment]
This issue is probably gonna become irrelevant considering the shift in what skinning Surge is going to mean in XT2. Right, @baconpaul?

**Comment by baconpaul** [comment]
Yeah this is a won’t do because will do better
