### ISSUE TITLE
Show modulator in display when amplitude is 0

### ISSUE THREAD

**Issue by magnetophon** [surge-synthesizer/surge#3838]
I often have the amplitude of a modulator at 0, modulated by for example a macro.
It would be helpful if the modulator at full amplitude would be shown in a different color.

**Comment by baconpaul** [comment]
Which element are you thinking of recoloeing?

**Comment by magnetophon** [comment]
I mean: draw two lines in the modulator display; one like it is currently and one in a different color showing the modulator as if the amplitude is 1.

**Comment by baconpaul** [comment]
Oh you mean the waveform! Gotcha. I thought you meant the mod matrix.

So you want a 'ghost line at amplitude 1 in the LFO waveform display' basically. Cool idea.

**Comment by mkruselj** [comment]
This is basically a variant of "show what modulation does to parameters" take 105. For which voice etc. :)

**Comment by baconpaul** [comment]
It’s a bit more like the rate deactivation ghost display - no voice ambiguity really just draw it at a and 1

**Comment by baconpaul** [comment]
![iss3838](https://user-images.githubusercontent.com/13387561/107670751-0d8e7700-6c61-11eb-97c5-f018d09cb754.gif)

Just confirming this is basically what you mean right? 

If it is I'll (1) pick a slightly better (lighter) color and (2) make it an option
