### ISSUE TITLE
Show patch comment in XT patch browser somewhere (was: as a tooltip)

### ISSUE THREAD

**Issue by sense-amr** [surge-synthesizer/surge#384]
i was wondering what the point of the patch *comment* was.. since you can never actually recall it or see it after you've saved the patch anyway ?

perhaps the ability to see the comment when rolling over the preset window or when rolling over a patch to load could work .. a bit messy maybe but still .. otherwise the comment is largely redundant

any ideas?

**Comment by baconpaul** [comment]
I like your idea of show the comment as a tooltip in the patch window.

**Comment by sense-amr** [comment]
ahh cool.. yeah cos other wise the comment is entered once and never seen again :)

**Comment by esaruoho** [comment]
the comments have not been displayed since 1.2 - according to the manual

`The comments are not currently shown in the main GUI. (v1.2)`

Would be cool to get 1.6 to show the comment / comments. Can then erase that part of the manual.

**Comment by baconpaul** [comment]
My tooltip PR shows them

**Comment by sense-amr** [comment]
is that getting merged to the master?

**Comment by esaruoho** [comment]
@sense-amr will be soon, but not right this minute.

**Comment by sense-amr** [comment]
please advise when it is .. i find building branches extremely tedious and difficult to do .. 
much easier for me to build master

**Comment by baconpaul** [comment]
Also (alas) vstgui struggles to show tooltips on windows but that is a sepaeate but. So my merge will show them “all platforms” (code wise) but Mac only today

**Comment by sense-amr** [comment]
oh those were my issues.. cool 
show slider values , show patch comment..

**Comment by baconpaul** [comment]
Yes right. 

I’m on pause while I pin down a few more vst bugs but it is underway

**Comment by mkruselj** [comment]
Would be nice to have this one sorted out once and for all. :)

**Comment by mkruselj** [comment]
Moving this issue into XT 1.0, because the patch comment should be directly in the patch browser, rather than a tooltip. Makes way more sense tbh!

**Comment by mkruselj** [comment]
Subsumed by #2359.
