### ISSUE TITLE
Content for the 1.9 manual update

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3842]
Various bits and bobs which will need explaining in detail in the manual. A place to remember them!

**Comment by baconpaul** [comment]
The "Tuning Applies to Modulation" toggle requires some pretty serious explanation. Here goes.

Microtunings map keyboard instrument keys to new pitches, but in the presence of modulation their meaning is ambiguous. Up until Surge 1.9, Surge made the choice that modulations were 'tuned'. This means that the frequency of an oscillator was resolved after all possible keyboard shifting modulations (pitch bend, octave shifts, etc...) were applied. This choice has a really positive consequence. If you have, say, pitch bend set to 2, press note 60 (middle C) and bend all the way up, you will hear the exact same tone as you would hear if you press note 62 (D) independent of tuning. That is, you observed frequency is `tuning( key + modulation)`.

It is, however, not the only choice you could make. There are situations where you want modulation to not be in the tuning space. If, for instance, you want two oscillators always spaced by a constant frequency multiple and you have a non standard tuning, that is hard to do in surge today. Sometimes you want the tuning to apply to the keyboard and the modulation to appear in semitone, not keyboard, space. That is you want the frequency of your modulator to be `tuning(key) + 12-TET-frequency-shift(modulation)`.  In this case, the constraint that "pitch bend of 2 up from C is the same frequency as D" is violated but constant frequency shifts are possible.

In Surge 1.9 we introduce the ability to pick which sort of tuning you want. This behavior is chosen with the tuning menu toggle "Tuning Applies to Modulation". If this is checked (the default) then modulation is inside the scale, and pitch bends are in key space. If it is unchecked, then tuning is only on the keyboard and modulation is in 12-TET space. Since this fundamentally changes how a patch would play in a tuned mode, it is a feature stored at a patch level. 

So lets give an example. Imagine we are using ED2-6, the even division of the octave into 6 notes with middle C amped to 261hz. If you play middle C you hear 261, if you play the C an octave higher you hear 1044Hz, the C 2 octaves up (since 6 keys span one octave). Now imagine setting up a square wave unipolar modulation and applying it to 'pitch' with depth 12.

In Surge 1.8 and in the default Surge 1.9 mode, when you press middle C the frequency will oscillate between 261 and 1044 - between the sound of key C at midi note 60 and the sound of key C 12 notes higher. If you toggle "Tuning applies to modulation" off, though, and press the same key, you will hear the note oscillate between 261 (the note you played) and 522 hz - the tuned note 12 semitones higher.

Sometimes you want that and sometimes you don't. There is no "right" answer. So we added both options to Surge.

Of course, in 12-TET this feature does nothing.

**Comment by mkruselj** [comment]
Modern oscillator is based on DPW (differentiated polynomial waveform) algorithm, from this paper:

https://www.researchgate.net/publication/224557976_Alias-Suppressed_Oscillators_Based_on_Differentiated_Polynomial_Waveforms

**Comment by mkruselj** [comment]
Sub-oscillator mode of the third waveform in Modern oscillator does _not_ participate in unison - you only ever get one single sub happening (for good reason too).

**Comment by baconpaul** [comment]
<img width="378" alt="Screen Shot 2021-03-09 at 8 43 11 PM" src="https://user-images.githubusercontent.com/13387561/110564799-74e1fe80-811b-11eb-8914-c88a0104780f.png">
<img width="271" alt="Screen Shot 2021-03-09 at 8 43 05 PM" src="https://user-images.githubusercontent.com/13387561/110564813-790e1c00-811b-11eb-99e5-dea23c096439.png">

**Comment by mkruselj** [comment]
Closing this issue in favor of #documentation channel on Discord, which @VincyZed opened exactly to keep himself updated.
