### ISSUE TITLE
Using <groups> causes some layout issues

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#3855]
I have started use the <groups> in the XML for positioning all of the LFO controls

I start out with this layout that I need to fix. I want to move all of the LFO controls together.

<img width="1443" alt="Screen Shot 2021-02-08 at 5 11 26 PM" src="https://user-images.githubusercontent.com/11078351/107294649-6bd61280-6a33-11eb-892d-e0ec21a48fd2.png">

So I plunk in this XML:

<img width="631" alt="Screen Shot 2021-02-08 at 5 40 00 PM" src="https://user-images.githubusercontent.com/11078351/107295280-b0ae7900-6a34-11eb-82d6-3e7e2ba9e112.png">

    
That yields this change:
   
<img width="1446" alt="Screen Shot 2021-02-08 at 5 12 49 PM" src="https://user-images.githubusercontent.com/11078351/107294745-9d4ede00-6a33-11eb-8bd1-0ff1f9d8ebdf.png">

Take a look at what happened to

`<control ui_identifier="fx.param.panel" x="802" y="235"/>`

It moved too. Also it no longer will respond to using x,y positions.

My hunch is that inserting the group mucks with the overall hierarchy of controls busting things for anything downstream that may be in a group (like the other panels).  BUT thats an assumption.

**Comment by itsmedavep** [comment]
`<group x="0" y="48">
    <control ui_identifier="lfo.title" x="8" y="502"/>
    <control ui_identifier="lfo.presets" x="8" y="499" w="13" h="12"/>

    <control ui_identifier="lfo.main.panel" x="32" y="490"/>

    <control ui_identifier="lfo.rate" class="hslider"/>
    <control ui_identifier="lfo.phase" class="hslider"/>
    <control ui_identifier="lfo.deform" class="hslider"/>
    <control ui_identifier="lfo.amplitude" class="hslider"/>

    <control ui_identifier="lfo.trigger_mode" x="176" y="497" w="58" h="26"/>
    <control ui_identifier="lfo.unipolar" x="176" y="532" w="58" h="12"/>



    <control ui_identifier="lfo.shape" x="250" y="492"/>

    <control ui_identifier="lfo.envelope.panel" x="618" y="503"/>
    <control ui_identifier="lfo.delay" class="vslider" />
    <control ui_identifier="lfo.attack" class="vslider" />
    <control ui_identifier="lfo.hold" class="vslider" />
    <control ui_identifier="lfo.decay" class="vslider" />
    <control ui_identifier="lfo.sustain" class="vslider" />
    <control ui_identifier="lfo.release" class="vslider" />
    </group>`

**Comment by itsmedavep** [comment]
Also, ED mentioned that the - offsets was not working on the groups but that seems like its perhaps a separate issue.

**Comment by baconpaul** [comment]
Bug confirmed.

**Comment by baconpaul** [comment]
```
   <group x="306" y="212">
      <control ui_identifier="filter.cutoff_1" x="0" y="0"/>
      <control ui_identifier="filter.resonance_1" x="10" y="26"/>
    </group>

    <control ui_identifier="mixer.panel" x="170" y="280"/>
```

that xml fails to move the mixer panel

**Comment by baconpaul** [comment]
Your guess was basically right except "recursion not downstream"
the groups recursively parse
but set up the global data structure at the end of a parse
and you only want to do that at the end of the top parse

Anyway fix inbound
