### ISSUE TITLE
The CEffectGrid should be drawn in code, not skins, with skin colors

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3873]
This would solve a variety of issues including

1: Alignment of boxes with our dicey SVG overlay (since we wouldn't be doing that any more
2: Having to generate a dumb strip of graphics ever time we add an effect
3: Hover
4: Easy expandability to more slots

So I think we should just do this for 1.9.0.

**Comment by mkruselj** [comment]
Agreed!

Except Nick's skin does use a custom font in that area, not Lato.

**Comment by baconpaul** [comment]
Alright so should we have an option to still have a graphic? Or just use Lato for the characters?

**Comment by mkruselj** [comment]
Maybe have the graphic act as an override? If it exists in the skin, use it, else draw in code?

**Comment by baconpaul** [comment]
OK! But in any case that could have all transparent backgrounds

**Comment by mkruselj** [comment]
Linking #907 here!

Merging PR that closes this issue should also close #907, then.

**Comment by baconpaul** [comment]
If someone wants to tae a swing at this, `baconpaul/ceffset-3873` has a rough start. 
If I end up doing this, `baconpaul/ceffset-3873` is how far I went before I decided to write this comment.
