### ISSUE TITLE
Skin component model additions

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3889]
General issue to hang things I need to do still

- [ ] Slider 
     - [ ] vertical and white
     - [ ] Text Positioning
     - [ ] Resizability
- [ ] Components for more types  / fewer custom
- [ ] Skin Inspector cross linkage
- [x] More doc strings
- [ ] Use this issue for further feedback from @itsmedavep and co
- [ ] Hows it all hang together a bit more in a comment pls
- [ ] cHSwitch2 image vs bg_resource below

**Comment by baconpaul** [comment]
#3894 launched the mission

**Comment by baconpaul** [comment]
Dave reports

```
     <control ui_identifier="osc.octave" bg_resource="osc-oct" x="8" y="205" w="143" h="18"/>
     <control ui_identifier="scene.octave" bg_resource="osc-oct" x="166" y="250" w="143" h="18"/>
 ```

Then the ref to the image in use.....is:

```
    <image id="osc-oct" resource="/assets/osc_oct.svg"/>
```

does not work; whereas if I use image= it does. That's clearly a sorta-bug.

**Comment by itsmedavep** [comment]
This is true these additional controls (now that Im taking a focused look):

Keytrack button
Retrigger button
Split mode button
Poly mode button
Staus buttons

using img fixes the issue.

**Comment by baconpaul** [comment]
Yeah I have to do something clever when you have a resource and an id and an image all to get them in order and that clever thing I have clearly gotten ‘not quite right’ 

I think the clever thing is “if image is set push it to resource” and “if neither image nor resource are set use id” but I don’t handle the case “if image is not set and resource is” in which case I probably push image to resource as a blank then use the id. Some logic like that will I’m sure appear when I look.

Glad image works on all of em!

**Comment by mkruselj** [comment]
Using a skin that has everything set to class="none" then loading any other skin makes that skin show up with no controls, for some reason...

[Empty.surge-skin.zip](https://github.com/surge-synthesizer/surge/files/6071333/Empty.surge-skin.zip)

**Comment by baconpaul** [comment]
Chatted some with @itsmedavep and he's held up for the 1.9 release so pushing some of this more advanced skin stuff out of 1.9 and into xt.

**Comment by mkruselj** [comment]
@baconpaul Considering the general plan for skin engine overhaul in XT2, I wonder if this issue still applies or if it could be closed?

**Comment by mkruselj** [comment]
Aaaand another ping regarding the fate of this issue, @baconpaul?

**Comment by baconpaul** [comment]
yup. dust, bitten.
