### ISSUE TITLE
Surge 1.6 is more than 10 times larger in size than 1.5 or (original 1.6)

### ISSUE THREAD

**Issue by sagantech** [surge-synthesizer/surge#395]
**Describe the bug**
Surge is way bigger than I think it should be.

**To Reproduce**
Build it.

**Expected behavior**
A size around 2 MB, original 1.6 x64 (with full optimization) was 1.5 MB. Size is now over 18MB

**Desktop (please complete the following information):**
 - OS: windows 7
 - Host: N/A
 - Version N/A

**Additional context**

**Comment by baconpaul** [comment]
Yes. To support zoom ever bitmap asset ships at 5 resolutions up to 4x. This substantially increases the size. But enables hi res displays and zoom.

**Comment by baconpaul** [comment]
Maybe! @davep can we shrink these bitmaps somehow?

**Comment by davep** [comment]
@baconpaul I suspect you meant to tag someone else.

**Comment by esaruoho** [comment]
hi @itsmedavep , i think you were the one @baconpaul wanted to tag :)

**Comment by baconpaul** [comment]
I agree a 15mb data page in a dll isn't that big a deal in a modern OS.

I have no particular opinion on the rest of this.

From reading imagemagkic man pages seems if we wanted to automate this we still need to pick a pallet to get a good result which is work.

**Comment by itsmedavep** [comment]
Im not sure I follow.

What is meant by this bit "if each instance has its own copy then I think it is a big deal as it will then limit instances especially in 32 bit OS's."

How will the plug-in's resources cause a limit to the number of instances? Are you worried about the amount of RAM it will take? Do you have a measurable example?

Im really not trying to be difficult. Just trying to move it from the hypothetical to the real.

**Comment by baconpaul** [comment]
If we end up with 32 bit builds I imagine we will want to lzy load the largest bitmap. Right now we bring them all into ram. But that’s independent of packaging size

**Comment by baconpaul** [comment]
I’ll do the lazy load when I’m fixing arity

**Comment by itsmedavep** [comment]
> I’ll do the lazy load when I’m fixing arity

TY!

**Comment by esaruoho** [comment]
doesn't svg-loading mean that filesizes will go down too? so, should this ticket just be closed..?

**Comment by baconpaul** [comment]
Either svg solves this and we close ticket when svg is in or svg is intractable and we close ticket when we index the final pngs - but let’s not close ticket yet
