### ISSUE TITLE
Debian package should specify minimum library versions

### ISSUE THREAD

**Issue by x42** [surge-synthesizer/surge#3956]
**Bug Description:**

Binary package installs, but the plugin does not load due to missing symbols in system-wide libs.

```
$ ldd /usr/lib/vst3/Surge.vst3/Contents/x86_64-linux/Surge.so
/usr/lib/vst3/Surge.vst3/Contents/x86_64-linux/Surge.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27’ not found (required by /usr/lib/vst3/Surge.vst3/Contents/x86_64-linux/Surge.so)
```
https://discourse.ardour.org/t/how-to-use-vst3-format-on-linux/105398/12 -- a user on Ubuntu 16.04.07

The issue at hand is `libc6` being too old.

**Surge Version**

* Version: 1.8.1
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**

Install the .deb on a system with libc < 2.28

**Expected Behavior:**

The installer bails out due to missing dependencies.  -- In debian/control add `Depends: libc (>= 2.28)`

Alternatively it just works (statically link against relevant libc/libm).

**Computer Information (please complete the following information):**
 - OS: Ubuntu 16.04.07

**Comment by baconpaul** [comment]
I've never been able to statically link surge, and folks who know Linux have not been able to either. But changing the DEB is smart! I'll do that for our 1.9 release. Thanks!

**Comment by x42** [comment]
Yeah, it's entirely reasonable to not support 5 year old distros.

Then again, I expect the plugin may still work when compiled locally with older libc.

**Comment by baconpaul** [comment]
Oh it does! I tested it on ubuntu 16 as recently as 4 months ago. Just the oldest version our build pipeline gives us is 18

**Comment by baconpaul** [comment]
(Sometimes I think about just not providing a Linux binary at all to be honest. Creating one that reliably works is hard and our build process is super regular)

**Comment by baconpaul** [comment]
@x42 so to make this work I had to use the line

```
Depends: libc6 (>= 2.28)
```

rather than libc and it is ready to merge in #3990. But if I say libc rather than libc6,  surge won't install from the deb on the machine where I build it.

That seems like the correct thing but before I merge it, wanted your feedback since you understand this way better than I do.

Thank you.

**Comment by x42** [comment]
Yes it's `libc6` (not libc)

**Comment by baconpaul** [comment]
Thanks for confirming. Will merge! Appreciate it.
