### ISSUE TITLE
μ, ä, ö, å, emoji not accurately displayed in popup menus + saving problem

### ISSUE THREAD

**Issue by sagantech** [surge-synthesizer/surge#396]
**Describe the bug**
Incorrect characters appear in popup.

**To Reproduce**
1. Go to surge, 
2. Click on preset
3. Scroll down to monosynth
4. See the last item in popup menu is incorrect and starts with weird character and should be "μcomputer"

This appears to be a bug in VSTGUI and can be fixed by changing:
MultiByteToWideChar (CP_UTF8 , 0, utf8Str, numCharacters, allocWideStr, numChars)  to:
MultiByteToWideChar (CP_ACP, 0, utf8Str, numCharacters, allocWideStr, numChars) 

**Expected behavior**
I would expect to see proper characters in popup menus.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Host [Metro]
 - Version [7.3]

**Comment by esaruoho** [comment]
Two important things:
1. With Mac, you can load patches within the `Stefan Hållén` -folder, and they load okay. You cannot Store into that folder/category.
2. With Mac, you can access and load a patch with an emoji in the folder, and they load okay, but you cannot Store into that folder/category.

<img width="263" alt="fullscreen_27_01_2019__16_33" src="https://user-images.githubusercontent.com/4966687/51802361-ee774500-2251-11e9-8bf3-0926d68623e5.png">
<img width="754" alt="untitled_logicx" src="https://user-images.githubusercontent.com/4966687/51802363-f0410880-2251-11e9-92cd-14a6e70dc4d2.png">

**Comment by baconpaul** [comment]
Heya @sagantech I'm going about applying your diffs to our fork. Which of the MultiByteToChars did you change? All of them or one particular one? Thanks!

**Comment by sagantech** [comment]
I think you can safely change all of them although when I did it, I only changed the ones that I saw were producing bad results.

**Comment by baconpaul** [comment]
Thanks.

As you maybe saw, my first cut at the vstgui fork only included one of your changes. If we agree the way I did it was the way we want to proceed, I can sweep in these others quickly and also send them as pull requests to steinberg.

**Comment by sagantech** [comment]
I have a new one. I need to create an issue for it but after a popup vstgui calls the invalidate procedure before calling the callback which I think is really weird. Anyway it usually has no bad affect on Surge but in the case where the host audio engine is off, or doing something else, Surge does not display the correct value selected for a popup (waveform/window/etc.) until you select it twice.

**Comment by baconpaul** [comment]
Cool. We are close to having our patch factory up and running. Another issue is best yes. If possible including the changes you make in diff format or with line numbers would make them much easier to apply. Thank you!
