### ISSUE TITLE
No checkmarks in preset browser

### ISSUE THREAD

**Issue by sagantech** [surge-synthesizer/surge#397]
**Describe the bug**
No checkmarks in preset browser (although my pull request will fix this, partially and fully with simple changes to VSTGUI)

**To Reproduce**
1. Go to Surge
2. Click on preset browser
3. Select a preset
4. Clock on preset browser
5. The item is not checked. (was in 1.5.2)

**Expected behavior**
I would expect not only the item checked by the category as well and the checks should be reset after a patch is loaded that matches a preset.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Host [Metro]
 - Version [7.3]

**Comment by baconpaul** [comment]
Merged in #402 PR.
