### ISSUE TITLE
Menu tweak 12 note to 12 tone equal

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3986]
Pretty clear. Make sure we say 12 tone not note in our menus and stuff. We missed the tuning menu.

**Comment by mkruselj** [comment]
Where in the tuning menu?

I fixed "12 note equal temperament" in the tuning lib (L161 [here](https://github.com/surge-synthesizer/tuning-library/pull/35/files#), if you're referring to that).

**Comment by baconpaul** [comment]
yeah but we didn't update the surge submodule to use the new version! As I just discovered. Will get it in a PR right now.

**Comment by mkruselj** [comment]
Ahhh ok! 🙂
