### ISSUE TITLE
Spend a day re-running leak check tools

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#4014]
No real reason to think it is leaking but I haven’t done a leak and uninitiatialized hunt with Val grind and leaks and stuff in a while - since halfway through the 17/18 cycle. So since we’ve written a lot of code lets do it again.

**Comment by K0rrid0r** [comment]
[G bowl - dist blow up in 32.zip](https://github.com/surge-synthesizer/surge/files/6091007/G.bowl.-.dist.blow.up.in.32.zip)

**Comment by baconpaul** [comment]
[vg.txt.zip](https://github.com/surge-synthesizer/surge/files/6145170/vg.txt.zip)

**Comment by baconpaul** [comment]
Alright we are definitely leaking a menu reference
Start surge, click the main menu, then run 

```
 leaks `ps -ef | grep Hosting | grep Applications | awk '{ print $2 }'`
```

and you see menu leaks. We aren't forgetting someone somewhere.

**Comment by baconpaul** [comment]
OK I got the menus done but we are also leaking a font somewhere.
