### ISSUE TITLE
Delay cut-off

### ISSUE THREAD

**Issue by jocphx** [surge-synthesizer/surge#4016]
A simple patch w/delay+reverb. If I play the keyboard the notes have the tails of the delay+reverb, but if I have a midi clip that plays back, when I stop it, the delay stops and I can only hear the tails of the reverb. I tried also in Ableton10, same thing. Am I doing something wrong? Is there a secret setup for allowing the delay to finish the playback of its buffers when the DAW sequencer is stopped?

**Surge Version**
This information is found on the About screen, which you get to from the bottom right menu

* Version: 1.8.1
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Create a short/simple midi clip that Surge will play back
2. On the Init patch, in Surge, just add a delay, either Send or Global
3. Start playback, delay works fine.
4. Stop playback, delay stops abruptly

**Expected Behavior:**
When playback transport stops, all time-based effects should continue processing
(BTW the reverb in Surge seems to work that way: when playback stops, I can hear the tails of the reverb.)

**Screenshots:**
N/A

**Computer Information (please complete the following information):**
 - OS: Windows 10
 - Host: FLStudio20 and Ableton10
 - Version: 

**Additional Information:**
While I was doodling with the delay I noticed a few other strange things: if the delay is global I can hear a broken tail when I stop. The send delay instead stops immediately. Also, I can easily drive the feedback in a nasty loop, and the only way to stop it, is by stopping the playback! When that feedback loop is on, the sliders have no effect whatsoever, even if I zero them out.

**Comment by baconpaul** [comment]
This is definitely a VST3 or a DAW setting thing. In Logic Pro with the AU I just set up a patch and I see the (far more expected) behavior that if I press play on a midi section with a long delay and then press stop, the delay continues. It is only when I press start again that it clears. (This is the same behavior as, say, Valahalla delay and the logic built ins).

**Comment by baconpaul** [comment]
@mkruselj any chance you can check this windows reaper? And you you have FL or Live running in your windows VM?

**Comment by mkruselj** [comment]
Cannot confirm the delay abruptly stopping on transport stop in Reaper, Studio One 4, Maschine 2. On the other hand, delay buffers are pured in Live, FL20 and Reason 11. This seems to be very host dependant for whatever reason.

Also regarding the feedback - the Crossfeed parameter can indeed run off "nicely". But I couldn't make controls lock up completely, it was easy to kill off the delay regeneration by dropping both Feedback and Crossfeed to 0.

**Comment by mkruselj** [comment]
@baconpaul I have retested this transport thing in XT. Previous culprits (Live, FL20 and Reason) now all behave the same as Reaper, S1 and Maschine used to in 1.9, which means - this issue has been JUCE ex machina'd! 🙂

Happy days.

**Comment by baconpaul** [comment]
Awesome!
