### ISSUE TITLE
Sustain pedal not working in Ableton Live 11

### ISSUE THREAD

**Issue by erichaleymusic** [surge-synthesizer/surge#4039]
**Bug Description:**
No Sustain pedal functionality. Tried the AU and VST version and it doesn't work on either.

**Surge Version**
1.8.19de9336

* Version:
VST & AU
64bit

**Comment by mkruselj** [comment]
Make sure MPE mode is disabled for Surge in Live 11.

**Comment by erichaleymusic** [comment]
@mkruselj you're freaking awesome! I actually had to enable MPE as it was disabled to start and that fixed it for me.

**Comment by mkruselj** [comment]
OK!

At any rate, this should not be necessary in the next Live 11 update.
