### ISSUE TITLE
Add checkmarks for sub folders

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#404]
@baconpaul will know what this is, but, yep, add checkmarks for folders.

**Comment by baconpaul** [comment]
<img width="1228" alt="screen shot 2019-01-28 at 2 37 48 pm" src="https://user-images.githubusercontent.com/13387561/51861471-54270800-230a-11e9-9149-d4cd9689e061.png">

In nested category folders, the check mark only appears on the terminus, not on the folders along the way.

**Comment by sagantech** [comment]
Seems like an argument to only nest 1 deep.

**Comment by baconpaul** [comment]
<img width="945" alt="screen shot 2019-01-30 at 8 35 56 pm" src="https://user-images.githubusercontent.com/13387561/52024536-29d27780-24cf-11e9-8861-534d25bdbcef.png">

There we go. just a few lines of code to fix it up.
