### ISSUE TITLE
recall issue with Samplitude

### ISSUE THREAD

**Issue by otison73** [surge-synthesizer/surge#4047]
**Bug Description:**
working on any patch, while using MPE in Samplitude Pro X5, fails to recall the patch correctly when reopening a Samplitude project, where sound generation (pre FX) comes hard panned to the left , while oddly enough the FX section stays panned correctly (trying on reverb FX1 for instance)

**Surge Version**
1.8.0.2560170

* Version:
VST3 64 bits

**Reproduction Steps:**
1. Open Samplitude Pro X5 Suite version 16.2.0.412 (DP3) ie the latest
2. Create new Samplitude project
3. Create a Surge VST3 MIDI track
4. Use the Init patch , use send FX level near max to a vanilla Reverb2 Cathedral
5. click Status : MPE on Surge
6. activate MPE in Samplitude's midi track
7. save Samplitude project "spam.vip"
8. Exit Samplitude
9. Reopen Samplitude project "spam.vip"

**Expected Behavior:**
The patch is recalled when opening the Samplitude project, but sound generation is hard panned to the left (regardeless of where the "Pan" slider is , while FX section staying panned center. 

**Computer Information (please complete the following information):**
 - OS:  Windows 10 Family
 - Host: Samplitude Pro X5 
 - Version: 16.2.0.412

**Additional Information:**
a (painful) workaround found is to save the patch I'm working on, and to relaunch an instance of Surge everytime I reopen a project. Note that this issue seems to NOT happen when Surge is NOT in MPE, 
Never happened in prior versions of Surge (was using 1.6.6 until now)
I first suspected it might be a Samplitude recall problem but the above detailed bug description makes me now thing problem is with the plugin (esp the fact that it only does the problem when activating the MPE in Surge + also the fact that the FX section does not get hardpanned left)

**Comment by mkruselj** [comment]
Sadly none of us use Samplitude...

**Comment by otison73** [comment]
Neither nor. But I have FL Studio 20 and  I can't replicate the bug (but FL does not support MPE anyway)
I will ask Samplitude but little hope. Let's see

**Comment by mkruselj** [comment]
Could try in Reaper trial version in a jiffy, but yeah I am not sure if it's something Samplitude is sending to Surge that it responds to, that other hosts aren't doing (CC #10?)... But I think we don't automatically link CC #10 to panning.

**Comment by otison73** [comment]
guys, sorry for late response, it happens to be Samplitude the problem. THis software simply dislikes VST3 and fails to save total recall. I wont blame Surge anymore :-) promised. thanks a lot for your support

**Comment by mkruselj** [comment]
@otison73 But can you still try the latest Surge XT nightly and see if it may actually work? A lot of things changed internally in Surge XT.
