### ISSUE TITLE
GUI is not updating when I turn the knobs on my midi controller

### ISSUE THREAD

**Issue by kanduvisla** [surge-synthesizer/surge#4050]
**Bug Description:**

If I assign a midi CC to a knob or a macro, the UI is not updated if I turn the knobs on my midi controller. The assignment works and I can see that the UI is updated if I hover my mouse over it, but that is of course not desireable.

**Surge Version**

```
Surge Synthesizer
Plugin Host:	Renoise (3.3.1)
System:	x86 CPU, Windows VST3, 64-bit
Build Info:	Built on 2021-01-27 at 12:54:59, using pipeline host 'WIN-T8F93AN0SJV'
Version:	1.8.1.9de9336
```

**Reproduction Steps:**

1. Open surge
2. Assign a midi CC to a knob
3. Twist them knobs
4. Observe

**Expected Behavior:**

The sliders should move if I turn the knobs on my controller

**Additional Information:**

I've tried other VST's to check if it's a Renoise problem, but other VST's get rendered / updated if I turn the knobs on my midi controller.

**Comment by mkruselj** [comment]
Hm. Might be a Renoise issue, because I can't confirm this in Reaper, Studio One 4, Live 10, FL20, MuLAB, Maschine...

**Comment by kanduvisla** [comment]
Hm, I'll also post my question on the Renoise forum then. I've checked another VST plugin and that got rendered / updated, so I assumed that would not be the issue.

**Comment by baconpaul** [comment]
I took a look at the code and it certainly seems like we are calling invalid() properly when a midi cc event comes in and changes a parameter. Confirm that in all the hosts I've tried on mac it works.

Can you be a bit more specific about what type of control you have mapped and how you mapped it?

And it sounds like forcing a redraw does update. Like: if you cover and uncover surge with textedit or something when you uncover it it has the right value? So just a repaint missed basically?

(I don't have renoise and anyway don't have working midi on windows really either).

**Comment by mkruselj** [comment]
@baconpaul Renoise has a macOS version and a demo.

**Comment by mkruselj** [comment]
@kanduvisla Did you manage to get it working in Renoise?

**Comment by baconpaul** [comment]
Closing due to lack of further information
