### ISSUE TITLE
LV2 plugin in Carla removes effects from bay when toggling the GUI editor

### ISSUE THREAD

**Issue by muziker** [surge-synthesizer/surge#4061]
**Bug Description:**
A user can set the effects used in the send/global fx section. However, if the gui is closed and reopened, the fx itself is gone.It does not seem to affect the airwindows fx. After further usage. It seems that adding an FX to the global fx section, and closing the gui and reopening it, the fx always changes to airwindows. Every fx is deleted and is replaced with one instance of airwindows instead.

**Surge Version**
* Version: 1.8.HEAD.9de93366
* Plugin Type:  LV2
* Bitness: 64bit

**Reproduction Steps:**
1. Add an FX
2. Close the gui
3. reopen gui
4. airwindows

**Expected Behavior:**
The fx selection should not change

**Computer Information (please complete the following information):**
Linux using carla

**Comment by mkruselj** [comment]
LV2 is currently unsupported as it has a number of issues, we recommend using VST3.

**Comment by muziker** [comment]
With this version there is a vst3, but for some reason carla doesn't recognise it.

**Comment by muziker** [comment]
Rebuilt a version of carla and the vst3 is recognized

**Comment by baconpaul** [comment]
Great. When we have our juce port done we think we may be able to use a juce fork to have the community build an lv2 which works better. See #4030

**Comment by baconpaul** [comment]
Closing this issue, since #4030 is the place we are investing in LV2 going forward. If the JUCE/LV2 port works, it works, and the problems in our hand-port will be gone.
