### ISSUE TITLE
FM feedback default to extended range

### ISSUE THREAD

**Issue by williamfields** [surge-synthesizer/surge#4064]
Please consider making the FM Feedback slider default to the extended range. 

The current default range provides very limited impact to the sound. When setting it to extended, some really great sound design capabilities open up. I have been using Surge for 13 years (!), and today I discovered this option for the first time.

At a minimum the ability to extend the range should be mentioned in the manual.

Thanks!

-Bill

**Comment by K0rrid0r** [comment]
It's because it was recently added

https://github.com/surge-synthesizer/surge/commit/f15601a0c7a0e0489835404f874303073490f37e

**Comment by mkruselj** [comment]
Extended range function by its nature cannot be the default one. The function is in fact mentioned in the manual already, and at least for FM3 oscillator it's mentioned to be extendable. I've just added the same wording to FM2 and Sine oscillator Feedback parameter descriptions.

**Comment by baconpaul** [comment]
We could totally make extend the preset default if we wanted @mkruselj so when you select FM3 from the menu the config.xml has the extend="1" in it for the param. Just a bit of code kinda like we did retrigger, honestly, not that bad an idea. Patch streaming would protect old saved sessions.

**Comment by williamfields** [comment]
When "extend" is on, that control becomes so much more interesting and useful.
