### ISSUE TITLE
Give us the option to choose the installation directory!!

### ISSUE THREAD

**Issue by SirTwsted** [surge-synthesizer/surge#4066]
Currently your application installs everything in these directories.::

```
Selected components:
      Data Files
      Surge VST3 (64-bit)
      SurgeEffectsBank VST3 (64-bit)

Installation Locations:
      Data Files: C:\ProgramData\Surge
      VST3: C:\Program Files\Common Files\VST3\Surge Synth Team
      Portable Junction: C:\Program Files\Common Files\VST3\Surge Synth Team\SurgeData

```

```
Which many of us do not want.  I myself install ALL my VST plugins in the ::
C:\Program Files\Steinberg\Vstplugins

I never put any VST plugins in the common file directory aka
C:\Program Files\Common Files\VST3\Surge

Unless its a VST3 version.  But my VST2.4+ all go into the ::
C:\Program Files\Steinberg\Vstplugins
```
But you do not allow us to do that.  I've been doing that ever since Nuendo v1.0 and Steinberg v1.2.
So ya a very very long time.  Putting the plugins by forcing us to install it in a horrible directory totally out of the way
completely messes with peoples OCD and structured files in their computer.

Thats like telling someone that visits your house not to put their shoes in the kitchen because it doesnt belong there.
But your visitor still ignores you and puts their shoes in the kitchen anyways. - Thats how I feel when I install this VST.

.

**Comment by mkruselj** [comment]
VST3 plugins are installed in the exact Steinberg prescribed location, and some hosts don't allow secondary VST3 folders. 

We will not change this.

**Comment by SirTwsted** [comment]
Thats not true.  currently all my plugins are in C:\Program Files\Steinberg\Vstplugins  for my 2.4 versions
and C:\Program Files\Common Files\VST3\  for my VST3 versions.

Also almost ALL my plugins gives me the option to install the vst anywhere I wish by letting us browse the directory of choice.

**Comment by mkruselj** [comment]
Well, Surge is not a VST2 plugin so that's alright to go into Common Files.

**Comment by SirTwsted** [comment]
ok,  I didnt know that.  I thought it also installed v2.4 versions.  no problem.  :)
I thought your vst did both 2.4 (for compatibility issues) and also VST3.

**Comment by mkruselj** [comment]
VST2 is not a compatible license for open-source projects, so we legally aren't allowed to distribute VST2 versions of Surge. However, the code is all in the repository, and if one is a legitimate licensee of VST2 SDK, one can build Surge VST2 for oneself.

**Comment by SirTwsted** [comment]
Cool to know.  :)  thank you  :)
