### ISSUE TITLE
How to install surge-fx ? Not in README

### ISSUE THREAD

**Issue by muziker** [surge-synthesizer/surge#4067]
**Bug Description:**
The documentation is unclear about how to compile and install surge-fx. It gives -DBUILD_SURGE_JUCE_PLUGINS=TRUE as a possible addition to a cmake command. However, there isn't anything about how to install the surge-fx itself. For that matter, there's a few other targets like surge-xt, that are not mentioned in the documentation.

**Surge Version**
* Version: 1.9main251000e4
* Plugin Type: ???
* Bitness: 64bit

**Comment by mkruselj** [comment]
Don't worry about Surge XT for the time being (see pinned issue about it).

README does mention what you need to do - you enter that command, then in your compiler of choice you pick SurgeEffectsBank target. then build.

**Comment by baconpaul** [comment]
To install it: after you build the targets in the readme the build directory contains a surge products directory containing the plug-in. Put it in your plug-in directory basically on a machine that has a valid surge install. That’s it!

**Comment by tank-trax** [comment]
@muziker try this

```
git pull
git submodule update --init --recursive
./build-linux.sh clean-all
cmake -Bbuildlin -DBUILD_SURGE_JUCE_PLUGINS=TRUE
cd buildlin
make all
```

this will build everything except the VST2

to get that add the one line to export to the VST location

```
git pull
git submodule update --init --recursive
./build-linux.sh clean-all
export VST2SDK_DIR=/path/to/SDKs/VST2_SDK/
cmake -Bbuildlin -DBUILD_SURGE_JUCE_PLUGINS=TRUE
cd buildlin
make all
```

**Comment by muziker** [comment]
I went through the Makefile2 targets to get the targets before reading any of the replies, so what i did was to: 
cmake --build build --config Release --target surge-fx_VST3 

after the first cmake -Bbuild -DBUILD_SURGE_JUCE_PLUGINS=TRUE . Initially cmake --target surge-fx produced a .a file but nothing else. But i was pointing out the surge fx targets aren't mentioned in the documentation anywhere. It's also not immediately obvious that --target install-everything-global uses -DCMAKE_INSTALL_PREFIX and --target install-everything-local doesn't. But everything seems to be working.

**Comment by baconpaul** [comment]
Great. I’ll clean up the doc tomorrow.
The “foo_packaged” targets are the ones to look for. They put proper assets into build / surge-products
This will all get cleaned up after 1.9 when we go juce only also

**Comment by baconpaul** [comment]
putting this in 1.9 just so i remember to update the doc this week and close the issue.

**Comment by baconpaul** [comment]
OK README updated.
