### ISSUE TITLE
Can't change installation directory

### ISSUE THREAD

**Issue by molecooler** [surge-synthesizer/surge#4079]
I've no idea what's happening. I have surge 1.6 installed correctly, however, am unable to update this to the latest 1.81.

It does not allow me to direct the installation to my VST folder and instead puts it elsewhere.

Can anyone help?

Windows 10, Live 9, Intel i5 3320M cpu

**Comment by baconpaul** [comment]
Surge 1.6 was the last surge vintage to provide a binary VST2. You will need Live 10.1 to run the VST3, or if you have a valid VST2 license can build a copy of 1.8 yourself as a VST2, but cannot distribute the resulting binary.

https://surge-synthesizer.github.io/formats

**Comment by molecooler** [comment]
> Surge 1.6 was the last surge vintage to provide a binary VST2. You will need Live 10.1 to run the VST3, or if you have a valid VST2 license can build a copy of 1.8 yourself as a VST2, but cannot distribute the resulting binary.
> 
> https://surge-synthesizer.github.io/formats

Hmm. I'm only a very basic computer nerd. I have almost no knowledge of coding so doubt I could do what's necessary.

Do you have any other suggestions I could try in order to get the latest update? Other than buy Live 11!

**Comment by K0rrid0r** [comment]
join the discord server
https://discord.com/invite/aFQDdMV

or read the readme on how to build surge
https://github.com/surge-synthesizer/surge/blob/main/README.md

**Comment by baconpaul** [comment]
To run surge you need a vst3 compatible daw. If you are committed to live you need to run at least 10.1 or build surge yourself. The other alternatives are to not use live but that is just as painful for you I would imagine.

**Comment by molecooler** [comment]
I get the picture.....although for now, I believe the answer is not to use the latest surge until I decide to upgrade my daw.

seems a shame but i've got plenty of vst's to get on with already

interesting looking synth though maybe not the most intuitive
________________________________

**Comment by baconpaul** [comment]
Yeah. And if the licensing situation were different, we would love to be able to properly make surge available to people in a VST2 contexts. But VST2 is not open software, rather it is owned by Steinberg under a closed license, and they are not allowing new developers to license and release the code. (They have however done a nice job of choosing a license for VST3 which is open source compatible, and are entirely within their rights with VST2 - I am not being critical of their choice, just factual. Unfortunately though this leads to tough situations like yours and same for a few other daws).

**Comment by molecooler** [comment]
Well i've got V1.6, which seems good enough for now. I will be upgrading my live license, just not yet.

I'm a bit daunted by Surge to be honest, it appears to be very powerful, with the patches i've heard displaying such an enormous range of possibilities that I think it'll be a while before i'm ready to dive in further.

I take it that with a strong builder community, that surge will be around for some time yet?

Many thanks to all the devs btw. I wish I could help but programming computers isn't where i'm at.
________________________________

**Comment by baconpaul** [comment]
Yeah it’s not going anywhere. Dev may ebb and flow but we’ve done 2 big releases since the pandemic started and are planning another one next month so plenty going on. Enjoy 16 and when you update live enjoy wherever we are then!

**Comment by mkruselj** [comment]
You can always try a different host, i.e. Reaper, or just try the latest version using SAVIhost, if you want to see what's new and take it for a spin.

**Comment by molecooler** [comment]
ok, maybe i'll give that a go....i've never used reaper but I think they do a 30 day unlimited trial, so that may be the way.

thanks
________________________________
