### ISSUE TITLE
Carla Volume knob does not affect volume of Surge

### ISSUE THREAD

**Issue by muziker** [surge-synthesizer/surge#4082]
**Bug Description:**
The volume knob in a carla rack is usually mapped to a global output volume of the hosted virtual instrument. In this case the volume knob in rack does not change the global volume at all, and the audio output to the main system is not affected at all.

**Surge Version**
* Version:1.9.main.251000e4
* Plugin Type: VST3
* Bitness: 64bit

**Reproduction Steps:**
1. Load a surge instance into Carla Rack
2. Turn the volume knob on the rack
3. It does not attenuate the audio
4. Use the surge global output volume
5. Audio gets attenuated 

**Expected Behavior:**
Audio in and out of an instrument should be manageable by the vst host volume knob

**Computer Information (please complete the following information):**
Linux, Carla 2.3

**Comment by mkruselj** [comment]
Question is - does Carla just send MIDI CC #7 on that knob? If so, Surge by default doesn't respond to this event, but it could if you MIDI learn the global volume slider to that CC.

**Comment by baconpaul** [comment]
Yeah that's exactly the right question @mkruselj - what is the volume knob sending. @falkTX - any thoughts on this one if you have a second?

**Comment by falkTX** [comment]
This is a carla bug then. does it happen with any other vst3 plugins?

**Comment by baconpaul** [comment]
Oh I don't know if it is a carla bug or not; I was just wondering what the volume control does. Are you sending something to me I should respond to? Or are you clipping the master volume (in which case yea it does sound like a carla big)

If it *is* a Carla bug, one thing surge does which is (relatively) unique is it has 3 pairs of stereo outputs in the VST3; the full mix; and then each scene individually pre-effect. I wonder if your volume knob is lowering the first pair and not the second two but still routing the other two to the mixer? maybe?

**Comment by falkTX** [comment]
Carla has an internal audio buffer it applies gain/volume to. Might be carla issue, that is why I ask to test with other plugins with the same format, vst3 in this case.

And Carla will only apply volume to the first 2 channels, yes.
But checking the code now, this is completely missing for vst3 haha :sweat_smile:

**Comment by baconpaul** [comment]
Ok! Well that does explain it.

so should @muziker open a Carla issue or is it ok? I’ll close this one since there’s nothing for surge to do.

thanks as always @falkTX !

**Comment by muziker** [comment]
That was fast ...
