### ISSUE TITLE
SurgeEffectsBank quantizes all parameters to the nearest percent

### ISSUE THREAD

**Issue by bit-101010** [surge-synthesizer/surge#4088]
**Bug Description:**
SurgeEffectsBank internally quantizes all parameter values to 1/100ths of the full range. For parameters displayed as percents, this means that SurgeEffectsBank truncates or rounds values even if they display more resolution.
For Nimbus' pitch control, it rounds to increments of 96 cents because that's 96/100ths of the full range.
For the GEq, it rounds to .48 dB because the total range is 48 dB.

**Surge Version**
1.9.nightly.5ce2377
(19 February 2021)

* Version:
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Open SurgeEffectsBank in Reaper
2. Create an automation envelope for any parameter (such as Nimbus' Pitch parameter)
3. create a smooth sweep with the envelope
4. watch it discretely step through specific values when it shouldn't

Alternately:
1: Open SurgeEffectsBank in reaper
2: set the percent-valued parameters to non-integer percent values
3: close the GUI
4: reopen the GUI: all percent-valued parameters will be integers. (other parameters are affected by this too, but it's most obivous with the percents)

**Expected Behavior:**
the plugin should _at least_ be able to use the full resolution it can display (tenths or hundredths of a percent) and knobs with units other than percent should have a reasonable resolution as well.

**Screenshots:**
Value display before closing the plugin GUI. These values are displayed but not actually used.
![image](https://user-images.githubusercontent.com/10576876/111172267-0e763980-857c-11eb-89e4-2ee1c86a0a1a.png)

Value display after reopening the GUI. These are the actual values being used by the FX. You can see how the parameters values are all snapped differently.
![image](https://user-images.githubusercontent.com/10576876/111172296-146c1a80-857c-11eb-996d-4e4b62facd2a.png)

**Computer Information (please complete the following information):**
 - OS: Windows 10
 - Host: Reaper
 - Version: 6.25

**Additional Information:**
Mentioned briefly in the Surge Discord - video demo of an automation sweep in the bug reports channel here: https://discord.com/channels/744319641211633774/744320274714984518/821026574589231108

**Comment by baconpaul** [comment]
Thanks! I bet I know where this is happening. Let me put it into the 190 milestone.
