### ISSUE TITLE
Click on Surge parameter and it crashes Ableton live 10 

### ISSUE THREAD

**Issue by fiddlestickzmuzik** [surge-synthesizer/surge#4094]
**Bug Description:**

**Surge Version**
This information is found on the About screen, which you get to from the bottom right menu

* Version:
* Plugin Type: [VST2, VST3, AU]
* Bitness: [32-bit or 64-bit]

**Reproduction Steps:**
2. Click on '...'
3. Scroll down to '...'

**Expected Behavior:**

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Host: [e.g. Bitwig, Logic, Cubase, Reaper]
 - Version: [e.g. 2.4]

**Additional Information:**

**Comment by mkruselj** [comment]
Could you please edit that opening post and replacing the text from the bug report template with actually applicable info and step by step reproduction, more info about your computer configuration. and so on?

**Comment by mkruselj** [comment]
@fiddlestickzmuzik We cannot do anything unless you provide us more detailed info on how to reproduce whatever you're exxperiencing!

**Comment by fiddlestickzmuzik** [comment]
Yeah nah I couldn't replicate it again so perhaps it was a one off glitch, I was using on my works wi fi system and often it creates some problems with DAW's and downloading soft synths..

**Comment by mkruselj** [comment]
Ha, ok then. We will close this issue but feel free to reopen it if you manage to get a consistent reproducible case!
