### ISSUE TITLE
Stuck notes in Ableton 11

### ISSUE THREAD

**Issue by jomicof** [surge-synthesizer/surge#4095]
**Bug Description:**
I experienced stuck notes in Ableton 11, but only on some patches ( on of which was Bass 1) when Play mode was any of the Mono choices and only when the notes were played legato-style. When 2 notes were played legato-style, the last note played got stuck (or latched?) and only released when another note was played non-legato-style. MPE was turned off on the device in Ableton and also off in Surge.
After seeing suggestion in "Stuck MIDI Notes #4013", I tried turning MPE on in Ableton device... which did not help. But, with MPE on in Surge (and off in Ableton device), the problem went away. I saw the same behavior with both Surge-1.8.1 and Surge-NIGHTLY-2021-03-16-6da806f.

**Surge Version**
Surge Synthesizer
Plugin Host:	Ableton Live 11.0
System:	x86 CPU, Windows VST3, 64-bit
Build Info:	Built on 2021-01-27 at 12:54:59, using pipeline host 'WIN-T8F93AN0SJV'
Version:	1.8.1.9de9336

**Comment by mkruselj** [comment]
Yep as mentioned in the other issue, this is a bug on Ableton side they're fixing for next update. For the time being either turn off MPE in Live for Surge instance, or turn on MPE in Surge.

**Comment by DJLevel3** [comment]
This issue is back in Live 12.0.2, the fix still works but it was stuck doing the same thing
