### ISSUE TITLE
Idiocy (no offense)

### ISSUE THREAD

**Issue by Jazzmaster101** [surge-synthesizer/surge#4096]
This is very confusing. I choose a patch in the A scene and than, I obviously go to the B scene, to choose another patch, but no ; It keeps changing the patch in the A scene, although I'm no longer in it and if I copy the A scene to the B scene, when I go back to choose another patch, to layer with the B that I've just copied from A, it goes back to the default saw tooth. I guess this is not a bug, but a feature, and because I didn't read the manual yet, I don't know. If it is a feature it's a bad one. Why can't I choose a patch for the A scene and layer it with another patch in B scene ?

**Comment by mkruselj** [comment]
Yes. this was explained in the manual. 🙂 I Surge, one patch consists of both scenes, and there are no per-scene patches.

**Comment by K0rrid0r** [comment]
interesting idea for a future feature request though, but like evil says, it's not really how surge works. But i can see how one would assume that's how surge worked.

**Comment by mkruselj** [comment]
We already have an issue about it. #1420
