### ISSUE TITLE
EffectGrid Click stolen on Windows only after loading an FX preset

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4098]
Hash 6da806f7 (but I've also noticed it way back).

Steps to reproduce:

1. Open Surge
2. Select an FX slot
3. Load any FX preset
4. Click any other FX slot that is not currently selected

Observed behavior: That other FX slot doesn't get selected

Expected behavior: It should get selected!

**Comment by baconpaul** [comment]
Stolen clicks are often someone returning kMouseEventHandled instead of kMouseEventHandledAndDontNeedDownEvents usually when a menu pops up. I would start by looking for that perhaps?

**Comment by mkruselj** [comment]
CSnapshotMenu seems to use `kMouseDownEventHandledButDontNeedMovedOrUpEvents` (really VSTGUI? REALLY?!) in its `onMouseDown` method...

**Comment by baconpaul** [comment]
If you flip it to the other one does it work?
And yeah right?

**Comment by mkruselj** [comment]
Flipping it around doesn't solve it sadly 🙁

**Comment by baconpaul** [comment]
Ok!
Thanks for checking. I can look before we ship for sure.

**Comment by baconpaul** [comment]
Oh the other thing is: I wonder if the menu callback handler is returning the wrong value.

So when yous elect an item it will call valueChanged on the listener I think. If that returns 0 it does this (remembering click stealing of yore). I don’t expect this cryptic comment to let you solve it @mkruselj but since it popped in my head want to write it down as a sort of message-in-a-bottle-to-my-future-self

**Comment by mkruselj** [comment]
Addendum: This stolen click thing also happens when changing skins. After skin is reloaded, I cannot move the plugin window (be it in DAW or in SAVIhost standalone) straight away. Need to click once somewhere else in order to be able to move it.

**Comment by baconpaul** [comment]
Sigh.
This is, of course, windows only.
We had a stolen mouse with the modulation source button forever ago right on windows? Wonder how I fixed that.

**Comment by baconpaul** [comment]
Ahh right it was https://github.com/surge-synthesizer/surge/issues/1465 and it was something else

**Comment by mkruselj** [comment]
Wiill check if the same thing happens in JUCE version. Bet it doesn't!

**Comment by mkruselj** [comment]
Well, FX grid doesn't even work in XT build as it is currently. 🙂

**Comment by baconpaul** [comment]
baconpaul — Today at 4:51 PM
on this mouse stealing I see this on windows
1. CHoose an FX and click play mode to mono - no steal
2. Choose an FX and mouse over a slider - get hover gestures
3. Choose an FX and mouse over the EFFECTS selector - no hover gesture
so it seems that chosing an FX eats a mouse click but ONLY in the effect selector not elsewhere
What you see also?
EvilDragon — Today at 4:52 PM
the report was only for FX grid anyways
but yep lemme verify
baconpaul — Today at 4:52 PM
yeah but that means it is a bug in the fx grid not in the fx menu!
EvilDragon — Today at 4:53 PM
I do get a hover gesture in the grid
but if I click it doesn't work
baconpaul — Today at 4:53 PM
right

**Comment by baconpaul** [comment]
Confirmed this does not break on mac or linux; and does not break with other controls.

**Comment by baconpaul** [comment]
So this is the case with either snapshot menu.

If the snapshot menu went from isa- to hasa- i bet this would work.

lemme ponder. that's a big change and one i kinda want to do in native juce. I may bounce this and ship with this little bug.

**Comment by baconpaul** [comment]
Pushing this to XT. Lets see if JUCE fixes it.

**Comment by mkruselj** [comment]
Of course JUCE fixes this just by virtue of existing. Tried it, now that you've fixed mouse clicks not working in FX grid. Closing!
