### ISSUE TITLE
Stack Traces in User Reporting

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#411]
Lots of times I find myself wanting a stack trace when I'm debugging. Enough times that I just want to make this something I don't have to hack in and hack out.

Anyone object if I add

```
std::vector<std::string> getCallStack()
```

to UserInformation and then add to promptError an `appendCallStack = false` option? @jsakkine would you reject that at review time before I code it up? :)

**Comment by jsakkine** [comment]
No immediate objections. Just googled for ready made options.

Could we use https://github.com/boostorg/stacktrace? I mean it is a good idea, but do we want to maintain all the name mangling etc.?

**Comment by jsakkine** [comment]
I'm not against adding, I'm more worried about maintaining one in the long run with all possible corner cases. That is why I'm thinking that if we want this, we should turn into 3rd party option.

**Comment by baconpaul** [comment]
Yeah mac has it built in with Xcode super easily. Maybe I will leave this out tho since windows definitely doesn't. I'll just c-n-p it in when I need to debug. I'm going to close this and not do it for now. Code already has enough complexity.

**Comment by baconpaul** [comment]
Thanks for reading tho!
