### ISSUE TITLE
Set Init-Highpass setting to "zero" instead of 50hz

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#414]
Currently the Highpass setting in Surge is 50Hz.

Proposal: Set the Highpass to minimum the slider will go (which is something like 6Hz).

The parameter in question is here:
![vember_audio__surge__ 64bit__and_renoise__intel_64bit_](https://user-images.githubusercontent.com/4966687/51982797-a5b4cb80-249f-11e9-91bd-8e026ea9039c.jpg)

**Comment by baconpaul** [comment]
SurgePatch.cpp has a method called init patch or some such which sets the in memory default init patch.

**Comment by esaruoho** [comment]
starting at line 539 there's a `void SurgePatch::init_default_values()` 
which lists a ton of parameters, none of which are HP though. interesting.

hmm.. unless if `scene[sc].lowcut.val.f = -36; // scene[sc].lowcut.val_min.f;` is it.
