### ISSUE TITLE
Update the links on the KVRAudio Surge-by-vember-audio

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#415]
https://www.kvraudio.com/product/surge-by-vember-audio/details

Currently this links to kurasu/surge/releases for 1.53 Mac and 1.6.0 Windows. So the data is pretty inaccurate.

Not sure how to get the data fixed - I take it @kurasu might've been involved in making this, so.. any chance the URLs + info there could be updated?

**Comment by itsmedavep** [comment]
Hey did this get fixed?

Thought I saw something about it in the slack channel.

**Comment by esaruoho** [comment]
closing
