### ISSUE TITLE
Let different channels transpose octaves for microtuning support

### ISSUE THREAD

**Issue by battaglia01** [surge-synthesizer/surge#4151]
Surge has great tuning support, but one problem is that the MIDI standard only has 128 notes per channel. This is 10 octave in 12, but as soon as you start using even a modestly large EDO like 22 or 31, it is much less (only 6 octaves of 22 and 4 of 31). As a result you quickly run out of notes.

I would prefer this solution be the same as Pianoteq's, which has a "multi-channel MIDI layout mode" that you can put on. If you do, then channel 2 transposed up an octave from channel 1, and channel 3 transposed up 2 octave, etc. Also, channel 16 is transposed an octave below. So it looks like this:

Channel 1: main tuning
Channel 2: +1 oct
Channel 3: +2 oct
Channel 4: +3 oct
Channel 5: +4 oct
Channel 6: +5 oct
Channel 7: +6 oct
Channel 8: +7 oct
Channel 9: +8 oct
Channel 10: -7 oct
Channel 11: -6 oct
Channel 12: -5 oct
Channel 13: -4 oct
Channel 14: -3 oct
Channel 15: -2 oct
Channel 16: -1 oct

I would suggest this kind of thing. That way, we just go to the next MIDI channel to get another octave of notes past the end of the 128 note range. This setup lets you hypothetically play in any equal temperament up to 128 notes per octave, which is pretty far beyond the largest equal temperaments that are frequently used (such as 72 or 96).

I don't know if there's already some way to do this in Surge (is there?), but this would be best for my setup. I have a few scripts written that already use the Pianoteq style of doing things so this would be great.

Of course Surge already has another mode that uses different MIDI channels for some kind of MIDI split mode, so this would need to be mutually exclusive from that.

**Comment by baconpaul** [comment]
I like this idea but indeed it would have to distinct from scene and MPE mode 
Let me put it into our summer milestone

**Comment by Jacky-Ligon** [comment]
What controller are you using?

**Comment by Jacky-Ligon** [comment]
If you could work with multiple Surge instances, a workaround might be possible in the interim...

Would need to know more specifics of your system, such as your DAW, etc. 

For example, this could very likely be setup with relative ease in Reaper, where discrete instances of Surge could be inserted on different tracks and MIDI Channels. I'm thinking here specifically of the above stated case of 31-equal, where with a couple of Surge instances, one could play close to a range of 8 octaves.

Join our Discord if you'd like to explore this together as an option.

**Comment by Jacky-Ligon** [comment]
Just posted in the SST Discord microtuning channel how to set this up, with SCL-KBM included.

**Comment by battaglia01** [comment]
Hi @Jacky-Ligon, I am using Logic Pro X and was just using a Casio digital piano (AP 450) as a MIDI controller. I can have mutliple Surge instances, but I am using a monophonic synth timbre with portamento, so I don't think this would work with multiple instances, right?

**Comment by mkruselj** [comment]
It would, it's just notes. Portamento happens in the synth, not in the MIDI.

**Comment by baconpaul** [comment]
@mkruselj if we change surge it would work

If @battaglia01 does the workaround Jacky suggests (which is have multiple identical surges with a midi splitter in front and pitch their octaves) it would not, in this case, since they woudln’t share voice state.

**Comment by battaglia01** [comment]
@baconpaul yes, that is correct. I guess you could also change Surge to permit multiple Surge instances to be side-chained to one another, but the way I suggested would certainly be cleaner, probably internally and also in that it's similar to how other microtunable synths work...

**Comment by Jacky-Ligon** [comment]
@battaglia01 

Here's part 1 of 2 in response to your question posted today on our Discord:

Let different channels transpose octaves for microtuning support #4151

What follows is one method for getting there with Reaper, using two Surge instances on MIDI Channels 1 and 2, for mapping close to eight octaves of ED2-31...

Attached here is a ZIP archive containing two linear KBM files, as follows:

! 0-55-0.kbm
! 
! Size of map:
0
! First MIDI note number to retune:
0
! Last MIDI note number to retune:
127
! Middle note where the first entry in the mapping is mapped to:
0
! Reference note for which frequency is given:
0
! Frequency to tune the above note to (floating point e.g. 440.0):
55.000000
! Scale degree to consider as formal octave:
0
! Mapping.


! 0-962-0.kbm
! 
! Size of map:
0
! First MIDI note number to retune:
0
! Last MIDI note number to retune:
127
! Middle note where the first entry in the mapping is mapped to:
0
! Reference note for which frequency is given:
0
! Frequency to tune the above note to (floating point e.g. 440.0):
962.332720

! Scale degree to consider as formal octave:
0
! Mapping.

The first one maps a Surge instance on a track set to MIDI Channel 1 and covers MIDI Notes 0-127, with a frequency range of 55 to 941.054135 Hz. This first KBM maps MIDI Note 0 to an A at 55 Hz. 

The second one maps a Surge instance on the next track, set to MIDI Channel 2, and also covers MIDI Notes 0-127, but here, MIDI Note 0 has a starting pitch of 962.332720 Hz, which basically is the next step in the tuning from the previous mapping above.

The MIDI Channel 2 configuration then covers a frequency range of 962.332720 to 16,465.585180 Hz.

So, using a similar logic, with multiple Surge instances on different MIDI channels, and purpose made linear KBM for mapping the frequency ranges of each MIDI Channel/instance, it would be possible to do the same for many other large equal-temperaments.
[KBM_for_2-Channel_256_Note_Ed2-31_Mapping.zip.zip](https://github.com/surge-synthesizer/surge/files/6184823/KBM_for_2-Channel_256_Note_Ed2-31_Mapping.zip.zip)

**Comment by baconpaul** [comment]
Yeah the change you suggest isn’t really all that hard actually with the internal data structures, but it’s a bit beyond what I want to do 3 weeks before our next release date which is why I pushed it into summer.

**Comment by Jacky-Ligon** [comment]
@battaglia01 
Part 2 of 2:

640 Note Mapping of ED2-72

Related to the above, and for the sake of conceptual discussion, similarly, imagine needing to configure an array keyboard mapping with ED2-72 (72 tone equal temperament) onto multiples of the MIDI range, and a number of Surge instances to achieve this end goal.

128 MIDI Notes / 72 = 1.778 
1.778 Octaves of ED2-72 would fit within one unit of the MIDI range of 128 notes.

So, it would take 5 times the MIDI range to have 8.89 octaves of ED2-72 mapped across five instances of Surge on MIDI Channels 1-5.

Imagining a slightly different mapping scenario here, let's start the mapping in MIDI Range Zone 1 of 5, with MIDI Note 0 on E at 41.203445 Hz; still within the range of many speakers and headphones.

With this data, now we know that we can configure this mapping with five discrete KBM files for each MIDI Range Zone, with the 1/1 on MIDI Note 0, and each with the following frequencies:

41.203445
141.285621
484.464995
1661.218806
5696.279302

And this, as above, would give us 640 notes with 8.89 octaves of ED2-72 mapped to the controller, with a frequency range spanning from 41.203445 to 19,345.267537 Hz.

**Comment by battaglia01** [comment]
@Jacky-Ligon thanks, I think this is a good workaround for now... the only instance is the portamento between notes where it splits, but with some careful editing (and overlap between the channels) this can probably be minimized...

**Comment by Jacky-Ligon** [comment]
@battaglia01 

Tested the ED2-31 scenario earlier with my Roland controller, and it worked seamlessly across the MIDI channel split zones.

The ED2-72 scenario was purely conceptual, but should work without problems as well.

As above, feel free to join our Discord. Usually I'm hanging out on the microtuning channel, and would be curious to learn how this will work for you, and to learn more about your music and practice.

**Comment by battaglia01** [comment]
@baconpaul I have so little time right now, but I am curious if this would be easy to do as a quick PR sometime these next few weeks... I'm already familiar with JUCE and it looks like some of that is used in the Tuning GUI? At https://github.com/surge-synthesizer/surgesynthteam_tuningui

Anyway you'd need to

1. Add in the tuning menu a "Enable Multichannel MIDI Layout" thing, which sets an internal parameter when this is checked
2. Write a quick function to map channel+note data to some internal representation of the note (not sure how this is done now, but if it's just an int that goes from 0-127, could just have the internal representation go beyond that, or could store channel+note directly)
3. Not sure if there are precomputed internal tuning tables w/ 127 notes, just would need to extend them...

Anyway, just some thoughts...

**Comment by battaglia01** [comment]
@Jacky-Ligon "Tested the ED2-31 scenario earlier with my Roland controller, and it worked seamlessly across the MIDI channel split zones."

I'm sure it does, except for the very particular thing I wrote before...

@battaglia01 "the only instance is the portamento between notes where it splits"

**Comment by Jacky-Ligon** [comment]
Yes, that will very likely be an issue, and there would almost certainly be some discontinuity there, since, as we know, they'd be on discrete MIDI channels.

**Comment by Jacky-Ligon** [comment]
There's always a rub isn't there? 

And they seem to proliferate in the world of microtuning virtual-instruments. Empathy with your plight and compositional requirements though.

**Comment by Jacky-Ligon** [comment]
One slightly prickly detail and potential issue about portamento across split channel zones, it that these features - as we know - are often tied to the typical MIDI range, so, I'd be at a loss to imagine how to handle that, although normal polyphonic performance should work in a seamless fashion.

**Comment by baconpaul** [comment]
@battaglia01 would be thrilled for you to do this. Let me layout how I would do it.

1. We probably want a midi menu one day but for now we could add a tuning menu which was "override midi channel for octave shift" indeed. That's in SurgeGUIeditor.
2. To SurgeStorage I would add an `std::atomic<bool> mapChannelToOctave`. Set that to true or false in your callback from step 1. Add a comment to the effect of "when other midi modes come along clean this up". Put it next to the mpeEnabled bool if that's on storage.
3. To SurgePatch.cpp handle the streaming of this. You can see the places where we stream and unstream and default tuningApplicationMode. (the revision <= 15 at line 1352 is how we make sure we deal with old patches. Set your thing to false in all defaults and try and unstream it)
4. In SurgeVoice.cpp around line 70 do something like 'res = 1-frac * b0 + frac * b1' then 

```
if storage->myBool 
   res += channel
return res
```

where you replace that with more appropriate math of course 
5. Set surge to "Apply Modulation at Midi Input" mode and you should be good

doing it in after modulation mode is harder. If you are into MTS you can also do it in the block above

6. Add yourself to AUTHORS, run clang-format, push it to GitHub for review.

I'd be willing to merge this if you can get it together soon enough in this form more or less and can confirm it works.

If that seems too much I can also do it once we are past the 1.9 wrap up! Your option.

**Comment by baconpaul** [comment]
ahh no and the other thing you have to do is, in SurgeSynthesizer, when the channel mask is calculated for scene masking, skip that and choose voices based on dual single or split mode when here. That's a bit trickier. Not impossible. But trickier...

We are really hoping to freeze for release in about a week though. So it may be better to push this FR into XT? But again don't want to dissuade you and would merge working code happily!

**Comment by battaglia01** [comment]
Thanks Paul - if I had more time I'd be happy to do it this week; I don't know how I'd be able to fit it in though. It'd at least be good to get clear on how to do this... That last thing about the channel mask threw me off somewhat...

**Comment by baconpaul** [comment]
Yup well its good to have notes for myself too!
The channel mask is in SurgeSynthesizer::playNote; it is how we do the current dual mode per channel scene splitting thing.
Anyway we welcome contributions of any size! This is a somewhat meaty one but happy for code changes and so forth any time.
