### ISSUE TITLE
LFO wave gets pixelated at low frequency and at high freq

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#416]
looks like the lfo-drawing could use with some clarity + pinsharpness. especially obvious if you are in zoomed modes.

![lfo-drawing](https://user-images.githubusercontent.com/4966687/51985579-de0bd800-24a6-11e9-8cd8-70a298e8ab0f.gif)

**Comment by baconpaul** [comment]
Closing this as a dup of #354
