### ISSUE TITLE
Questions regarding previous issue

### ISSUE THREAD

**Issue by mexanik619** [surge-synthesizer/surge#4172]
As u know I had. A issue where surge wasn't able to load GUI and welcomes me with a white blank screen. I had. A question that
Which openGL VERSION does surge use.

**Comment by mkruselj** [comment]
Surge does not use OpenGL at all.

**Comment by mexanik619** [comment]
So

**Comment by mexanik619** [comment]
What does it use then

**Comment by baconpaul** [comment]
Dirsct2d on windows

**Comment by mkruselj** [comment]
... which should be widely supported even by the crappiest GPUs...

**Comment by K0rrid0r** [comment]
@mexanik619 can you load older versions of surge? can you try loading the vst2 version 1.6.6

https://github.com/surge-synthesizer/releases/releases

![image](https://user-images.githubusercontent.com/56724286/112759731-9e909600-8ff4-11eb-97d2-4c2048e948ad.png)

**Comment by mexanik619** [comment]
Well yeah finally it worked
There was some problem in my OS 
So I installed the surge in Windows 8.1 that was installed in my laptop...
It works good

**Comment by mexanik619** [comment]
NAA I am working on surge 1.8.1
Latest
Royal skin in good one

**Comment by mexanik619** [comment]
Well I need to learn C++ can I contribute here and learn

**Comment by mkruselj** [comment]
Glad to hear you have it running now!

By all means we welcome any contributions, spend some time to learn C++ and explore Surge codebase on your own.

Closing this issue since you have it resolved now.
