### ISSUE TITLE
User Favourites

### ISSUE THREAD

**Issue by Eyal2** [surge-synthesizer/surge#4173]
Hi
is there a way to create a favourites folder for my favourite patches?
do I need to manually create a folder and duplicate the patches there or can I do it from the Surge interface?
TIA!

**Comment by mkruselj** [comment]
You can do it from the interface. When you save a patch, in Category field just type Favorites. You can also add subfolders by writing i.e. Favorites\Pads etc.

**Comment by Eyal2** [comment]
Works! Thanks!
