### ISSUE TITLE
correlated_noise_o2mk2_suppliedrng in SurgeVoice

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#4177]
We added a suppliedrng version of correlated noise and use it in a few places
but we don't use it in SurgeVoice
so the srand(time(nullptr)) in SurgeSynth reseeds all RNGs every time you create any surge synth

So my proposal is

1. Add a uniform_rng from`<random>` as a member to surge synth
2. Initialize it in the constructor
3. Refer to it in SurgeVoice when we call correlated_noise

**Comment by williamfields** [comment]
@baconpaul I installed the latest nightly, and I can no longer reproduce the "flangy noise" problem I was experiencing before. 👍

**Comment by baconpaul** [comment]
Wonderful!

that means by the way that something in your audio stack is seeding the global rng - no idea what a but surge is immune to that now!

yhanks for the report
