### ISSUE TITLE
Surge osc to filter routing and other stuff

### ISSUE THREAD

**Issue by bigtonesounddesign** [surge-synthesizer/surge#4183]
hi guys,
again - thanks for giving us surge - what a serious thing this is... just great.
however - i noticed some shortcomings that are a bit of a bummer, so i thought i'd mention it here. these are _not_ bugs. but in my experience as someone who screws around on synths since 1986 are not correctly - or let's say not beneficial - implemented or missing - so rather take it as a feature request:

routing osc to filter:
- when using both filters in l-r mode, routing one osc to both filters and using more than one unison voice, these should be spread evenly to the filters, to have a real stereo output of both filters. i.e. when using two unison voices, with the routing as just explained, one unison voice should go to filter one and the other to filter two. if three unison voices are used, one should go to filter one, the next to both filters and the third should go to the second filter - and so on. with the widh parameter one can then adjust the overall stere width at the amp before the fx.

- i _really_ miss the ability not only to restart the oscs - but to actually set up the starting phase of each osc seperately in 360°.

filter env modulation via the modulation tabs:
- if i rout f.e. the filter env to another parameter (additionally to the hardwired cutoff), then route f.e. velocity to the env depht, the additionally controlled parameter which is modulated by the filter env should also react. afterall i assigned the env to that additional parameter, so the depth of the env should reflect the changes that the velocity does on that additional parameter, too. it is the same env. in other words, the additional routing should not be exclusive. as soon as the filter env controls various parameters and the velocity (or any other parameter) controls the depth of that env, that should of course affect all parameters, that this env is routed to.
even easier spoken - if i route the filter env to the resonance and the velocity to the filter env depth - the resonance should also reflect the changes that the velocity does on the env depth.
i hope i was clear, so that you understand what i mean - when it comes to such comples explanations, my english sucks. :-)

maybe you guys can do something about these things. 

thanks again...

kind regards,
nico from bigtone sounddesign, germany

**Comment by mkruselj** [comment]
Hello!

Regarding osc phase, this is a long standing feature request that we will tackle sometime this summer, at last. We have it tracked under #867.

Regarding filter envelope modulation (and all modulations for that matter), they are all separate. Meaning, when you use FEG to modulate, say, wavetable position, and then you use velocity to modulate wavetable position, they act as separate modulations, rather than velocity > FEG amount. FEG amount is not a modulation target in Surge. This will be resolved at some point in Surge XT by using modmixers (think Zebra). Then you will be able to assign FEG x velocity then use that as modulator for whatever.

As for osc to filter routing... The plan is definitely to stereoize all the filters in all the filter configs, but I am not exactly sure we'd want to do it the way you suggest. The idea was to have stereo output from the oscillator which you can pan L/R and then pan separately between F1 and F2 (think Waldorf Q).


Thanks for comments!

**Comment by bigtonesounddesign** [comment]
> Hello!
> 
> Regarding osc phase, this is a long standing feature request that we will tackle sometime this summer, at last. We have it tracked under #867.
> 
> Regarding filter envelope modulation (and all modulations for that matter), they are all separate. Meaning, when you use FEG to modulate, say, wavetable position, and then you use velocity to modulate wavetable position, they act as separate modulations, rather than velocity > FEG amount. FEG amount is not a modulation target in Surge. This will be resolved at some point in Surge XT by using modmixers (think Zebra). Then you will be able to assign FEG x velocity then use that as modulator for whatever.
> 
> As for osc to filter routing... The plan is definitely to stereoize all the filters in all the filter configs, but I am not exactly sure we'd want to do it the way you suggest. The idea was to have stereo output from the oscillator which you can pan L/R and then pan separately between F1 and F2 (think Waldorf Q).
> 
> Thanks for comments!

ah ok, bummer... but thanks for the fast answer. btw - filter env depth _is_ a modulation target. at least i can assign velocity or any other source from the modulation tabs to it and it works just fine.

kind regards,
nico from bigtone sounddesign, germany

**Comment by mkruselj** [comment]
Ah right, there are those F1 and F2 sliders, but they only pertain to cutoff modulation, this has no relation to other FEG assignments done from the modbutton area. Surge's modulation system is all about one modulator to many targets, but no chains in between, so you can't do velocity > FEG output > whatever else. Until we introduce modmixers, that is. :)

**Comment by bigtonesounddesign** [comment]
> Oh and by the way, there's a rough plan for voice unison #3895 (duplicating voices then offsetting them in pitch and so on, with voice count modulator etc) so this could be a way for you to do the unison to different filters thing, you'd use voice count modulator on filter routing knob once we have all that. But that's probably happening closer to 2022.

man, that's nice to hear. though it has to be said - while this is a nice feature indeed (i often use it in other synths that can do it), it simply sounds different, if you f.e. feed a multiple of oscs into one saturating filter as opposed to use voice based unison, where you feed one or two iscs into one foílter, but clone the voice. sometimes one is beneficial, sometimes the other. not to speak of cloning the whole voice needs a fairily bigger chunk of cpu usage than just a "supersaw". but yeah - nice to have that option to choose from in future. 

btw - a question i always forget to ask:
is it possible to _save_ single cycles to wave format from within surge? as in surge to create great waveforms is a breeze. being a sounddesigner, i always seek for synths where i can create single cycles or wavetables in a synth, that i then can export as wave to be imported into other synths that can import single cycle waves to create a band-limited single cycle waveform (via fft->ifft) or a complete stitched table, created and saved to wave from another synth. that would indeed help me a lot. now i know - you don't build the synth for me personally - but i could see quite some people using that feature except of me.
so yeah, is this possible in surge?

kind regards,
nico from bigtone sounddesign, germany

**Comment by mkruselj** [comment]
Unfortunately no, you can only export the whole wavetable, by right clicking the wavetable selector.

If you're thinking just exporting anything that's currently in the oscillator as a single cycle, nope we don't have that sorry to say.

As for voice unison, I hear ya. We can discuss most anything and you're welcome to join us on Discord if you want, but

**Comment by mkruselj** [comment]
Since this is just a discussion thread that doesn't contain any actionable items that we don't already have in other issues, I will close this one, and make a mental note to contact Nico directly on KvR via PM when we have something to show pertaining to his requests. 😃
