### ISSUE TITLE
Investigate making Window osc Morph continuous

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4184]
Currently, the Morph parameter in Window oscillator is quantized to just directly select frames of the loaded wavetable, no interpolation like what Wavetable oscillator is doing.

It would be really cool if we had an option (use Extend range switch) to make it interpolated just like Wavetable oscillator is. Windowing an oscillator is just an envelope applied to the original waveform, retriggered at every cycle of the oscillator, so it should (in theory) not matter what the underlying waveform is or how it's generated really.

@baconpaul Let's investigate if this is possible somehow!

**Comment by baconpaul** [comment]
This is not that hard. basically have a fractional table between now and next, handle the special case of 'off the end' wraps from n-1 -> 0 or just stays at n-1, the add a WaveAddrPlusOne which you set up, and then do interpolation in i16 space using SSE between the two tables before line 251

**Comment by mkruselj** [comment]
So maybe even for 1.9? :grin: :grin: :grin:

**Comment by baconpaul** [comment]
Nah risk reward is too high. Lets push it to xt.
