### ISSUE TITLE
no escape when zoom level larger than screen size

### ISSUE THREAD

**Issue by mynameismuhl** [surge-synthesizer/surge#4188]
From the series: What happens if i push that button?
Today: Zoom to 400%
(linux/64bit/reaper)

What happens is:
- It shows for a tiny moment what 400% would look like
- then jumps to full screen mode 
 (but the kind of full screen you would get with F11)
 hiding all options to close that window.
- All Zoom options in menu stop working. 

- close surge UI with alt-F4
- unhide surge again and regain control

this is not restricted to 400%. 
same with any zoom level larger than screen.

expected behaviour: 
don't know really
it probably should stop at "zoom to largest"

**Comment by baconpaul** [comment]
It used to stop at zoom to largest and it was one of our most hated features because most people don't have the experience you did when they use mac or windows

We could restore the zoom to largest on linux which seems to deal with the screen-oversized window "worse" perhaps?

**Comment by baconpaul** [comment]
If you want to try that, in `src/common/gui/SurgeGUIEditor.cpp` change this

```
bool SurgeGUIEditor::doesZoomFitToScreen(float zf, float &correctedZf)
{
    correctedZf = zf;
    return true;
```

to this

```
bool SurgeGUIEditor::doesZoomFitToScreen(float zf, float &correctedZf)
{
    // correctedZf = zf;
    // return true;
```

then rebuild and see if the experience is a better one. If it is I can merge a #if LINUX around those two lines (or you could also put a #if LINUX around those two lines and send in a PR which we would gladly merge!)

**Comment by mynameismuhl** [comment]
cool i'll try this.
(but i am personally also fine with just not pushing that button, seemed a find worth reporting :) )

**Comment by baconpaul** [comment]
Well we removed that check because mac and windows were fine at 800% and stuff
if linux isn't we should restore the check on that platform
so would appreciate a test! thanks!

**Comment by baconpaul** [comment]
if you have time of course etc...

**Comment by mynameismuhl** [comment]
quick test with commenting out works
it shows that warning pop up now.
i remember this one, maybe the pop up is the reason for the hate?

**Comment by baconpaul** [comment]
The primary reason people hated it is because they thought it would work at arbitrary size. They were wrong for a while (the zoom menu used to only be in the corner) but now you can RMB anywhere to get the zoom menu they are right. Except it seems on linux1

I think you have a smart solution of ‘add the constraint and don’t pop the warning’. Lemme tag this into 19 and we can decide before we release.

Thanks!!

**Comment by mynameismuhl** [comment]
so there are now these changes on my fork.
without the warning pop-up. (the warning for size smaller than 100% i left in)
you want the pr or decide later?

**Comment by baconpaul** [comment]
Merged your change. Thanks!
