### ISSUE TITLE
Store MIDI mapping to SurgeUserDefaults.xml

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4194]
Because we shouldn't be doing it in the factory configuration.xml, due to write permissions and so on.

**Comment by mkruselj** [comment]
Also looks like "Clear current MIDI mapping" option doesn't really work.

**Comment by baconpaul** [comment]
We can do this fully by modifying the path in `SurgeStorage::load_midi_controllers` and `SurgeStorage::save_midi_controllers` and it will take me an hour or so to bang out when I'm back

**Comment by baconpaul** [comment]
So @mkruselj I implemented this but haven't merged it. Just sanity checking we are sure we want this default write. I think we do and if you agree merge my PR and this issue will close. But we might also want to make it a workflow option ("Always Save MIDI Controller State as Default" or some such?)

But my fix in #4222 means at least it doesn't "only work for people running as admin on windows" any more!

**Comment by baconpaul** [comment]
But feel free to merge if you think the change is good!

**Comment by mkruselj** [comment]
I was thinking that the active MIDI config should be saved in SurgeUserDefaults.xml rather than a separate file in MIDI Settings folder. This might be a bit confusing because then we get that file showing in the menu along with all our other MIDI setups...

The idea being: MIDISettings folder contains various different mappings we might want to choose between, and our actual selected mapping would then be written to the actual user config file, which is SurgeUserDefaults.xml

**Comment by baconpaul** [comment]
Ugh that’s a total pita since that file is the record of the user defaults and this is different. I can move it out of the midi directory though so it doesn’t scan.

**Comment by baconpaul** [comment]
But anyway I will either do the pain in the neck bit or make a surgeusermidi.xml in the top dir

the tricky bit is I’m careful to cache the user defaults so a get is cheap but that means our writes invalidate the cache so putting the write for midi in there involves some work outside of storage.
