### ISSUE TITLE
Sudden pops and long sound dropouts occur in 1.9  beta

### ISSUE THREAD

**Issue by Oortseam** [surge-synthesizer/surge#4207]
Sudden pops and long sound dropouts occur in 1.9 beta while v1.8 works stable with the same patch and midi track

Surge Synthesizer
Plugin Host:	REAPER
System:	Windows 64-bit VST3 on         Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
Build Info:	Built on 2021-03-28 at 07:45:15, using pipeline host 'WIN-S2NGKRSV6OL' with 'MSVC-19.16.27045.0'
Version:	1.9.nightly.ee2acf1

Reproduction Steps:

1. Load Surge into the host
2. Load the patch attached.
3. Try to repeat any same note 10-15 times in fast tempo.
4. Meet some pops and dropouts like in audio attached.

Notes:

The effect is unstable. Sometimes it takes some time for it to occur. Sometimes it's there at just 2-d or 3-d note.
[Audio.zip](https://github.com/surge-synthesizer/surge/files/6217883/Audio.zip)
[Bug_demo_patch.zip](https://github.com/surge-synthesizer/surge/files/6217885/Bug_demo_patch.zip)

**Comment by baconpaul** [comment]
I can’t look now but in 19 we started obeying the polyphony in the patch. Is the Max poly the same in 18 and 19 when you compare? If we went from 8 to 16 and you have a long release or some such...

**Comment by baconpaul** [comment]
But also will definitely properly investigate before we ship 19 too - just thought of that as first idea

**Comment by Oortseam** [comment]
Seems it doesn't depend on polyphony. The issue is present even if polyphony is set to 64 and the meter shows 2/64 or 4/64.
Now I'll check it with 1.8.

**Comment by Oortseam** [comment]
Compared it to v1.9.nightly.f28c104 now. It's also absolutely stable in this case.
Even if polyphony  is set to 2 and the meter shows 4/2 everything is okay.

**Comment by baconpaul** [comment]
Ok! I’m taking a few days break from dev but will definitely investigate this - wonder what it could be but I need to be at a laptop and open your patch to determine that :)

thanks for the clear report - will revert here as I find out more

**Comment by mkruselj** [comment]
This seems to be related to inter-osc FM routing. If I disable it, all is good.

**Comment by baconpaul** [comment]
Ooh what’s the pattern the patch uses? And what are the endpoint oscillator types?

**Comment by mkruselj** [comment]
Oh, and osc 2 has some modulation happening on Sine Shape parameter, which should not be possible because integer parameters (like Sine Shape here) are not modulatable. If you just select another oscillator then back to Sine, it also doesn't seem to happen.

**Comment by baconpaul** [comment]
Ahh interesting I wonder if my cpu optimization for sine is somehow exploding in that case?

**Comment by mkruselj** [comment]
Nah it's stray modulation from previous oscillator ending up on integer param I bet (since 1.8.1 didn't have this change where we clear modulations when changing osc types).

**Comment by baconpaul** [comment]
So if you clear the modulation in the shape then it all works ok? 

@Oortseam in 19 we rewrote the sine oscillator to be in some cases as much as 5x faster so lots of change in this code path - super useful report.

**Comment by baconpaul** [comment]
> Nah it's stray modulation from previous oscillator ending up on integer param I bet (since 1.8.1 didn't have this change where we clear modulations when changing osc types).

Right but clearing it solves the problem?
In that case I should at least figure out what it is doing! Or maybe block invalid modulations from unstreaminf also. Or both!!!

**Comment by mkruselj** [comment]
Yeah that's what I wrote above, clearing it the patch seems fine :)

**Comment by baconpaul** [comment]
Oh right. Sorry. And cool

ok so @Oortseam if you clear that modulation you can make music but please leave this open so I can run original patch and clear up the problem when I’m back doing dev

**Comment by Oortseam** [comment]
Thanks guys! I've cleared this strange modulation setting (wonder where it came from :) ) and everything works fine now. 
Keep making nice music !

**Comment by baconpaul** [comment]
It used to be when you changes osc type it didn’t clear modulations so if you had classic modulates width and swap to sine you get something wrong

In 19 we fixed that. Change an osc type clears modulations just like fx 

But in 18 you could then end up with invalid patches basically which it seems wirh 19 went from harmlessly invalid to catastrophically invalid!
