### ISSUE TITLE
UI Tweaks for Alias Spectrum (was Separate storage for alias spectrum mode)

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#4209]
@selenologist ’s spectral mode in alias is cool but @baconpaul didn’t love hijacking step sequencer 1, so after a convo on discord which also included @mkruselj, @baconpaul suggested that before 1.9 ships he would do the following

1. Add a per-oscillator spectrum storage of 16 floats which streams etc.. (and if it isn’t there on unstream, uses the data comments of VLFOSS1)
2. Modify the oscillator display code so that it can ask of the oscillator ‘has extra data’ which launches an editor based on type
3. Make OscillatorBase::has extra data() be return false
4. Make AliasOscillator::has extra data() be return mode == spectrum mode
5. Write and editor which replaces the oscillators display in edit mode which is basically the step sequencer editor kinda where you drag around the 16 bars with reasonable colors and stuff and it updates the data structure

Et voila. Feature stays, we add a new paradigm for editing things, alias keeps its wierd but awesome feel, and there’s no hidden Easter egg magic in the workflow.

This is actually fun code to write and I’m psyched to do it! First thing I’ll knock off when I’m back from my coding break at the middle to end of week.

**Comment by baconpaul** [comment]
While there's UI changes here, i just pushed code that does materially all of this so changing the subject

**Comment by mkruselj** [comment]
- [ ] While holding the mouse drag, going out of COscDisplay bounds kills the mouse movement. Compare with the step sequencer where this doesn't happen.
- [ ] Double-click resets the bar that was clicked on to 0
- [ ] RMB menu contains some preset waveforms, randomize, flip vertically, flip horizontally, normalize
- [ ] When entering Additive mode, reduce the height of display (to match the size and position in Wavetable/Window oscillators), and position the Edit button in exactly the same position as wavetable selector (might also make the button wider and make it say "Edit Partials")

**Comment by VincyZed** [comment]
As discussed on Discord, adding mouse wheel to the alias additive editor would be a nice touch and would be consistent with the way the step sequencer works. 🙂

**Comment by mkruselj** [comment]
Reopening due to this inconsistency when mouse cursor is out of bounds of bar area, compared to step sequencer:

![stepseq out of bounds](https://user-images.githubusercontent.com/2393720/113435345-dfb4eb80-93e2-11eb-96e5-e5497dada009.gif)

![additive edit out of bounds](https://user-images.githubusercontent.com/2393720/113435365-eb081700-93e2-11eb-8bf3-764fecc9448d.gif)
