### ISSUE TITLE
Profile this patch before 1.9

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#4232]
from @j5v on discord
[Shimmering_choir.fxp.zip](https://github.com/surge-synthesizer/surge/files/6247114/Shimmering_choir.fxp.zip)

Seems to do everything you can to destroy CPU but

1. Are the ring outs correct
2. In the profiler do we see anything super-dumb or clever we can fix
3. etc

**Comment by baconpaul** [comment]
OK this is the same problem as #4235 - all the time goes to the resampler. I need to find a better strategy

<img width="909" alt="Screen Shot 2021-04-02 at 7 35 28 PM" src="https://user-images.githubusercontent.com/13387561/113461473-bac47680-93ea-11eb-9fd6-d05f1cc3024a.png">

**Comment by mkruselj** [comment]
Close as a duplicate then?

**Comment by baconpaul** [comment]
No because i still want to keep this open to look at the ringouts once I’ve got the SR under control. I’ll close em eventually.
