### ISSUE TITLE
More GCC11 issues? -Werror=free-nonheap-object causes surge-fx build to fail

### ISSUE THREAD

**Issue by plaimbock** [surge-synthesizer/surge#4251]
**Bug Description:**
error: 'void operator delete [](void*)' called on unallocated object 'juce::emptyString' [-Werror=free-nonheap-object]

**Surge Version**
main HEAD from earlier today git rev 523fde07d9af5991ba57251e8236fc07cbde7af9

* Version:
* Plugin Type: not sure
* Bitness: 64-bit

**Reproduction Steps:**
1. Build Surge-FX main HEAD & JUCE-6.0.8 with GCC11 on Fedora 34

**Expected Behavior:**
Build succeeds.

**Computer Information (please complete the following information):**
Fedora 34 (up-to-date) with GCC11 and JUCE-6.0.8

**Additional Information:**
[surge-fx-gcc11-error.txt](https://github.com/surge-synthesizer/surge/files/6255706/surge-fx-gcc11-error.txt)

**Comment by baconpaul** [comment]
Wow well that’s way upstream of us
I think that one needs reporting to the juce forum and, for now, if gcc 11 in cmake, disable that warning as error.

Did you look at the code to see if the warning is correct?

**Comment by plaimbock** [comment]
Thanks for the quick reply @baconpaul I've removed -Werror and everything builds. My C++Foo is insufficient to judge if the code is correct but I'll report the issue in the JUCE forum.

**Comment by baconpaul** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54202

turns out that one caused some consternation

Rather than getting rid of -Werror you could add -Wno-free-nonheap-object around line 75 of CMakeLists.txt

If that works firing in a PR with the change so we can merge it would be welcome!
