### ISSUE TITLE
Add distinction between all-notes-off and all-sound-off

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4256]
Currently sending both CC 120 and CC 123 to Surge results in the same thing - all voices cut out. However, this is what the MIDI spec says:

**All Sound Off (CC 120)**

Mutes all sounding notes that were turned on by received Note On messages, and which haven't yet been turned off by respective Note Off messages. This message is not supposed to mute any notes that the musician is playing on the local keyboard. So, if a device can't distinguish between notes played via its MIDI IN and notes played on the local keyboard, it should not implement All Sound Off.

Note: The difference between this message and All Notes Off is that this message immediately mutes all sound on the device regardless of whether the Hold Pedal is on, and mutes the sound quickly regardless of any lengthy VCA release times. It's often used by sequencers to quickly mute all sound when the musician presses "Stop" in the middle of a song. 

**All Notes Off (CC 123)**

Turns off all notes that were turned on by received Note On messages, and which haven't yet been turned off by respective Note Off messages. This message is not supposed to turn off any notes that the musician is playing on the local keyboard. So, if a device can't distinguish between notes played via its MIDI IN and notes played on the local keyboard, it should not implement All Notes Off. Furthermore, if a device is in Omni On state, it should ignore this message on any channel.

Note: If the device's Hold Pedal controller is on, the notes aren't actually released until the Hold Pedal is turned off. See All Sound Off controller message for turning off the sound of these notes immediately.

**Comment by baconpaul** [comment]
So assuming that we don' have a "local keyboard" this means that "All Notes Off" neads to do (basically) for i : 127 if note is down note off.

That's actually pretty easy code to write. SurgeSynthesizer has a structure `midiKeyPressedForScene` which distinguishes by scene but that's OK. It means you could write something like this in pseudocode

```
SurgeSynthesizer::allNotesOff()
{
   std::set<int> onNotes;
  for( int s=0; s<n_scenes; ++s )
    for( int n=0; n<128; ++n )
      if( midiKeyPressedForScene[s][n] )
         onNotes.insert(n);
   for( auto n : onNotes )
      for( int c = 0; c < 16; +=c )
         if( channelstate[c].keyState[n].velocity )
            releaseNote(c,n,0);
}
```

That channel state stuff can probably be cleaner - maybe check gate not velocity. Dig around.

Then once you have that call it in 4 places: The VST2, VST3, AU, and LV2 layers. But since we will probably do this in XT we can just call it in the JUCE plugin layer instead.

And done.

**Comment by mkruselj** [comment]
OK so the logic here is a bit more complicated - it's not just counting which notes are pressed. It's also taking into account sustain and sostenuto pedals. Examples:

1. Press a key, hold sustain pedal, release a key. Note is held down. Send CC 123, note is still held down until sustain pedal is released.
2. Press a key, hold sustain pedal, release sustain pedal, keep holding the key. Send CC 123, note gets released.
3. Press a key, hold sostenuto pedal, release a key. Note is held down. Send CC 123, note is still held down until sostenuto pedal is released.
4. Press a key, hold sostenuto pedal, release a key. Note is held down. Play another key and hold it. Send CC 123, second key played is released, the older note is still held down until sostenuto pedal is released.
