### ISSUE TITLE
Prior patches malfunctioning (possible Sine oscillator type initiation issue or out of bounds parameters)

### ISSUE THREAD

**Issue by inigokennedy** [surge-synthesizer/surge#4260]
**Bug Description:**
A number of my prior patches are malfunctioning when loaded e.g. Inigo Kennedy > Leads > Glitter 2 or Inigo Kennedy > Rhythms > Ladder 2. Seems likely in connection with the Sine oscillator type.

**Surge Version**
1.9.main.58c00fe3 VST2 and VST3 (own builds) but also in previous builds. Unsure when it began.

From about screen (VST2):
Plugin Host:	Native Instruments Maschine 2
System:	Windows 64-bit VST2 (unsupported) on Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
Build Info:	Built on 2021-04-06 at 10:08:38, using local host 'LAPTOP-1GDA1OI2' with 'MSVC-19.28.29336.0'
Version:	1.9.main.58c00fe3

**Reproduction Steps:**
Steps to reproduce the behaviour:
1. Load affected patch e.g. Inigo Kennedy > Rhythms > Ladder 2
2. Press keys
3. Horrendous noise from time to time :o

**Expected Behaviour:**
Patch should function as before.

**Additional Information:**
I think the issue is with the Sine oscillator type. The horrendous noise is reproducible on loading affected patches (like Ladder 2). When muting the affected Sine oscillator the noise is cut. Flipping the affected oscillator from Sine to another oscillator type and back to Sine appears to resolve the noise. This makes me think there is potentially an out of bounds value in older patches that might be causing the issue. Noted also that I think the Sine oscillator type uses a wave-table to govern available shapes and wave-table initiation has had some change recently also.

**Comment by baconpaul** [comment]
I am almost 100% sure this is the errant-modulation bug. Used to be that an errant modulation onto sine shape was ignored but with the rewrite of the sine oscillator (to make it about 4x faster) it now makes a nasty fart sound. Flipping to and away from sine clears the modulation manually. So

1: Can you check if your sine oscillators have an errant modulation onto shape?
2: If they do, I fixed it in 0dad99148811c76f95a4ca66c5e63235c85c9e2b which is one commit after the one you are running
3: So can you pull the top of main and test again?

Thanks!

**Comment by mkruselj** [comment]
Try the latest nightly, it should be fixed.

**Comment by baconpaul** [comment]
And yeah looking at that leads patch

```
  <a_osc1_type type="0" value="1"/>
                <a_osc1_octave type="0" value="-2"/>
                <a_osc1_pitch type="2" value="0.000000"/>
                <a_osc1_param0 type="0" value="2">
                        <modrouting source="17" depth="0.062500"/>
                </a_osc1_param0>
```

it has the errant routing. So I bet a pull to head will fix it.

**Comment by inigokennedy** [comment]
Thanks @baconpaul @mkruselj

I've tried a new build pulled from head and 0dad991 has it fixed.

Fixed before I'd got in front of a keyboard to report it after hitting it last night. Awesome stuff!

**Comment by baconpaul** [comment]
Great!
