### ISSUE TITLE
UI freeze after: paste to Scene B then LFO selection

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#4274]
**Bug Description:**
Some of the UI freezes after copying to Scene B and selecting LFOs.
https://discord.com/channels/744319641211633774/744320274714984518/829834148314349619

**Surge Version**
Surge Synthesizer
Plugin Host:    Cakewalk
System:    Windows 64-bit VST3 on Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Build Info:    Built on 2021-04-08 at 19:57:52, using pipeline host 'fv-az177-31' with 'MSVC-19.16.27045.0'
Version:    1.9.nightly.799a6cd

* Version: 1.9.nightly.799a6cd
* Plugin Type: VST3
* Bitness: 64

**Reproduction Steps:**
1. load a patch
2. right-click Scene A, Copy
3. right-click Scene B, Paste
4. click on Scene B
5. left-click on LFO-4, LFO-5, ...

Sliders and LFO/marco buttons no longer respond. Buttons work fine.

**Expected Behavior:**
Further edits are possible

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following information):**
 - OS: Windows 10
 - Host: Reaper, Cakewalk
 - Version:

**Additional Information:**

**Comment by j5v** [comment]
Alternative reproduction Steps:
Steps to reproduce the behavior:

1. Load a patch
2. Right-click Scene A, Copy
3. **Remain on Scene A, Paste**
4. Left-click on LFO-4, LFO-5, ...

Paste looks responsible, as if it's loading Surge with data the UI cannot parse.

**Comment by j5v** [comment]
On Paste, LFO EG only shows D stage; A, H, D, S, R are blank. 
![image](https://user-images.githubusercontent.com/13245475/114104491-ddf79600-98c2-11eb-8149-e06f16a0e81c.png)

**Comment by baconpaul** [comment]
Copy and Paste onto self crashes immediately on macOS.

**Comment by baconpaul** [comment]
Right
So what's happening is paste is screwing up the internal state of the params.
Hmm. Wonder what did it! Lemme look.
