### ISSUE TITLE
Surge GUI modulation 2019 coloring makes modulation difficult to see, and pitch slider ends vanish

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#428]
one for @itsmedavep and @baconpaul maybe?

![tying greying_v2](https://user-images.githubusercontent.com/4966687/52045414-27166780-254d-11e9-9af0-e9cec8297355.gif)

**Comment by sense-amr** [comment]
modulation colouring also makes modulated sliders.. very difficult to see as a dark blue on a dark grey background.. the slider that is modulated almost dissapears from normal view..

**Comment by itsmedavep** [comment]
I think this is fixable in the skin file. I’m curious though, what did this look like in the previous version?

Or rather, is this a new issue or one that previously existed? 

Regardless, I’ll dig into it.  I’m just curious if I’m trying to make it like the previous version or improve on it.

**Comment by sense-amr** [comment]
I find it hard to say if it existed before or .. it's something i JUST noticed now .. when i was trying to make a patch.. i tend to think it didnt exist the same way it looks NOW .. than it did before when i made patches.. i only noticed it since building and using the latest master build.

**Comment by itsmedavep** [comment]
I’m on a phone right now but on my computer I’m making a bunch of changes to the skin. 

I’ll look into what this was like previously then figure out how to fix. 

If anyone has 1.5 installed it would be interesting to see what these states look like there. 

It’s a problem that should be addressed. I’m just trying to understand how. 

Nice catch BTW.

**Comment by baconpaul** [comment]
I’m not sure what part is the problem but except for the green blink that’s all in the skins

**Comment by itsmedavep** [comment]
I have a this now. Could you take a look before sweeping? @baconpaul @sense-amr 

Cheers!

Screen shot just in case
<img width="1833" alt="screen shot 2019-01-31 at 8 49 15 pm" src="https://user-images.githubusercontent.com/11078351/52099666-ba758a00-2599-11e9-9d80-544e7d43afdb.png">

**Comment by itsmedavep** [comment]
Thoughts on the animated sliders?

**Comment by baconpaul** [comment]
I haven’t quite followed the slider stuff so will leave that to you esa and sense.

But in this screenshot I do notice 
* the “X” in the oscillator routing between 1/2 and 2/3 is still pixelated 
* The drawn filters in the filter configuration graphic are not vectorized
* the arrows where they enter the “+” in a circle in the effects routine section seem to have some bitmap and stuff and extra lines.
* the corners of the VU meter are vectorized not round (although that may be the code not the graphics)
* The mute and solo buttons are still pixeled not vectored

Don’t know if you know that or if those are separate issues but figured I’d mention it.

I tried to get lato loading from the bundle on mac tonight. I failed. I’ll try and take another approach this weekend. I may fail again. But hey. We’ll see!

**Comment by baconpaul** [comment]
Oh and: it looks great. I should have added that 👍

**Comment by sense-amr** [comment]
Thats definitely a lot easier to see @itsmedavep

**Comment by baconpaul** [comment]
Also the orange background on the Scene buttons (for ‘split’ or whatever and ‘a’ ‘b’) have bitmapped not vectored corners.

**Comment by baconpaul** [comment]
And it looks like the orange you use in the LFO drawing section is not exactly the original orange,since the LFO waveshape is a slightly different background. The color in the code is #FF9000

And that’s it, I promise!

**Comment by baconpaul** [comment]
Ok I will look at Vu this weekend
I agree this is awessome and super close! Great stuff!

**Comment by sense-amr** [comment]
@itsmedavep this ? 
![wsauto](https://user-images.githubusercontent.com/1504019/52120715-51614580-2671-11e9-833e-182d15b1fa56.jpg)

**Comment by esaruoho** [comment]
@itsmedavep i've sent you a video that Zvenx made, showing how Surge 1.52 works when it comes to showing "active modulation" and "latent modulation". hope it helps!

**Comment by itsmedavep** [comment]
> And it looks like the orange you use in the LFO drawing section is not exactly the original orange,since the LFO waveshape is a slightly different background. The color in the code is #FF9000
> 
> And that’s it, I promise!

Bummer. This one is a head scratcher right now. Ill revisit once I knock off more of the other issues.

<img width="2252" alt="screen shot 2019-02-01 at 10 26 57 am" src="https://user-images.githubusercontent.com/11078351/52136368-8340c080-260d-11e9-832e-2364e89626b1.png">

**Comment by itsmedavep** [comment]
The bitmaps from 1.5.2 use sRGB 2.1 color space. Changing sources document to that color space from unmanaged yielded no change. Colors still different somehow.

Still testing.
<img width="1450" alt="screen shot 2019-02-01 at 3 07 36 pm" src="https://user-images.githubusercontent.com/11078351/52149679-25bf6a80-2633-11e9-886c-838441d4bb6f.png">

**Comment by baconpaul** [comment]
So I don't know anything about any of this color space stuff. Never bothered to figure it out.

But I do know that the LFO drawing code does "set color #ff9000; fill"

So can't you just set the color to #ff9000 and be OK?

This question may be hopelessly naive.

**Comment by itsmedavep** [comment]
> So I don't know anything about any of this color space stuff. Never bothered to figure it out.
> 
> But I do know that the LFO drawing code does "set color #ff9000; fill"
> 
> So can't you just set the color to #ff9000 and be OK?
> 
> This question may be hopelessly naive.
> 
> Oh I see you did that.
> I'm hopelessly naive.

Could you point me to where that code is being drawn? 

I have a couple of thoughts but nothing too concrete. Plus if I know the dims that are being drawn... I can put a border around it (ducks and leaves room). LOL.

**Comment by baconpaul** [comment]
line 65 or so of CLFOGui.cpp

but that code is ... hairy. Not obvious how the pixels are laid out. I'm actually looking at that for #354 right now.

**Comment by baconpaul** [comment]
You know I could also make it transparent.

**Comment by baconpaul** [comment]
Hmm transparent doesn't work sorry no.

**Comment by itsmedavep** [comment]
When I was doing a bit drawing in code for macOS I would specify the color space that I was using. 

[NSColor colorWithCalibratedRed: 0 green: 0 blue: 0 alpha: 1] or similar. 

Im curious about the draw code to see if there is something similar in the C++ that is drawing this stuff. Maybe thats off base, just my line of thinking.

**Comment by itsmedavep** [comment]
@sense-amr @baconpaul I updated the PR #437 now. I believe I have addressed all of the items brought up so far in this thread. 

Please review at your convenience!
<img width="1819" alt="screen shot 2019-02-01 at 3 54 33 pm" src="https://user-images.githubusercontent.com/11078351/52151853-0f68dd00-263a-11e9-8312-9f875f29a7cf.png">

**Comment by sense-amr** [comment]
![image](https://user-images.githubusercontent.com/1504019/52159182-ab571f00-26f4-11e9-96eb-ccb654747b4a.png)


All possible parameters modulated.. 

Largest screen cap i can manage here.. 

Pan slider dissapeared.. 

Reverb .. 

ROOM SIZE 
ROOM SHAPE 
PRE DELAY 

All unavailable for modulation .. even via SLFO .. 
note for another issue i guess..

**Comment by sense-amr** [comment]
Additionally a video showing animation of on off sates for automated paramaters.. 

Sorry i should state this is VST2 BITWIG 2.43 and Windows 10 .. 
[Surge Latest_routingviewON_OFF.zip](https://github.com/surge-synthesizer/surge/files/2824012/Surge.Latest_routingviewON_OFF.zip)

**Comment by sense-amr** [comment]
Also are we aware of this ? 

![missingparameter](https://user-images.githubusercontent.com/1504019/52159522-a34dae00-26f9-11e9-939a-b8399242f109.jpg)

**Comment by esaruoho** [comment]
@sense-amr If you check the Preset Bass->Mellow, the Pan Width appears. Not all presets utilize Pan Width. It is not gone, just disabled when the patch in Surge does not specifically ask for it.

**Comment by esaruoho** [comment]
@sense-amr as per the manual at https://surge-synthesizer.github.io/manual/
```
Width – the amount of stereo spread 
(only present for the wide & stereo filterblock configurations)
```

**Comment by esaruoho** [comment]
as illustrated by this GIF
![filterblockswitching](https://user-images.githubusercontent.com/4966687/52161782-46d79800-26d3-11e9-9e8c-3a235c03cde1.gif)

**Comment by esaruoho** [comment]
> @itsmedavep @esaruoho @baconpaul
> SCREEN 1 shows All parameters modulated by single SLFO 1 ..
> ![image](https://user-images.githubusercontent.com/1504019/52159317-93809a80-26f6-11e9-9020-18fecd08fa3a.png)
> 
> Screen 2 shows .. SLFO2 modulating SLFO 1 envelope and parameters
> ![image](https://user-images.githubusercontent.com/1504019/52159325-a85d2e00-26f6-11e9-9019-55e69f4f4ebf.png)
> 
> Largest screen cap i can manage here..
> 
> Slider above Pan slider dissapeared..
> 
> Reverb ..
> All unavailable for modulation .. even via SLFO ..
> 
> * ROOM SIZE
> * ROOM SHAPE
> * PRE DELAY
> 
> Also Uni Count .. not able to be modulated.
> note for another issue i guess..

this has been isolated into a separate case. #449 "Future Feature: Make Reverb: Pre-Delay,Room Shape,Size modulation with SLFO possible". there are also separate, related cases for future features. #316 , #233, #354, and #367.

**Comment by baconpaul** [comment]
Hey guys - just checking I think Dave got all these things fixed right? Can we close this ticket and leave it to the other ones referenced in here? Or is there still something in the book of work?

Thanks!

**Comment by baconpaul** [comment]
OK I'll close it!

If others disagree, lets either reopen it or open a new issue.

Thanks @itsmedavep !!!

**Comment by itsmedavep** [comment]
@baconpaul 
Thanks!
