### ISSUE TITLE
Press [Esc] while using parameter slider: cancels and restores pre-drag value.

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#4280]
**Is your feature request related to a problem? Please describe.**
If I'm experimentally dragging a slider, I often change my mind and want to leave it untouched.

**Describe the solution you'd like:**
Either of these will exit the slider drag, and reset the value to its pre-drag state:
1. [Esc] key.
2. Press the other mouse button (only makes sense with two-button mouse).

**Describe alternatives you've considered:**
Currently, I have to remember what the value is, and then manually tweak it back into place, which can be difficult if it wasn't at the default value.

**Additional context:**
--

**Comment by baconpaul** [comment]
Oh we already have this with ALT (I use a microsoft keyboard on my mac so it is the windows key on that keyboard)

Hold ALT when dragging gives you a rubber band mode that returns to original on release.

So I think we have this feature already? If so lets close this

**Comment by mkruselj** [comment]
Yep that's Alt/Option on Mac.

**Comment by j5v** [comment]
Indeed, it is. It's even documented in **Sliders and controls**.
Closing with thanks.
