### ISSUE TITLE
Dynamic scale tunings 

### ISSUE THREAD

**Issue by muziker** [surge-synthesizer/surge#4281]
**Is your feature request related to a problem? Please describe.**
I want to dynamically alter the tuning from 4edo to 12edo to 72edo during the duration of a work. 

**Describe the solution you'd like:**
I'd like to map a CC to the edo length and alter it dynamically instead of having to load up a scl file or a kbm file to map the notes.

**Describe alternatives you've considered:**
Currently i've a pure data patch that maps the incoming midi notes to a 72edo scale. With a divisor & modulo of 12, the 12edo scale can be generated from 72edo. However, at high or low midi output notes, surge doesn't generate the pitches. So a midi output of > 127 or < 0 has no effect on pitch. Additionally only <midi note value, velocity 0 > turns off a note, when doing this midi note mapping technique. 
The other method is to use the pitchbend + note method of getting the correct pitch. But, a pitch bend operates globally, so to do this for polyphonic sounds means to have multiple surge instances, and getting pure data to handle the routing.

**Comment by baconpaul** [comment]
Can I recommend you explore https://oddsound.com/ ODDSound MTS, a product which does exactly this and which integrates perfectly with the surge 1.9 beta? It is a commercial product, but they have midi-based realtime warping of scales which works great, and does exactly what you want.

**Comment by baconpaul** [comment]
Oh and if you don't want to use odd sound, you can use pitchbend + note method in MPE mode if you have PD generate the data with a voice-per-channel and kick surge into MPE mode. Just FYI!

**Comment by muziker** [comment]
oh hey that's great ! I'll have to give that mpe + pitchbend a try.

**Comment by baconpaul** [comment]
Cool
And it turns out that one of the odd sound beta testers working with us has done exactly what you wanted - set up MTS-Master so that a midi control morphs between ED2-13 and ED2-12 - the surge discord has a pretty active micro tuning channel (I'm sorry I don't remember if you are on discord) where lots of folks are around to brainstorm.

I'm going to close this issue if that's OK - I don't think we will add this to surge native with the other options in place. If you think we still should though or have questions please do feel free to reopen it!

**Comment by Jacky-Ligon** [comment]
While you're installing MTS-ESP Suite, I'll proceed with creating a Morph preset for you that will start on ED2-4 and terminate on ED2-72. 

As Paul pointed out, I just created and shared one that morphs between ED2-13 (equal division of 2 into 13 parts), up to ED3-13, which is essentially Bohlen-Pierce. 

Drop by the SST Discord microtuning channel and I can give it to you there if you like, and if not, I can drop it here as well.
