### ISSUE TITLE
Store polyphony limit in patch

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#429]
Surge manual says

> The state of the polyphony limit setting is **not** stored in patches.

We could have the polyphony limit state saved in the new patch format, right?

**Comment by baconpaul** [comment]
So if we do this, there's one state transition which is weird.

Lets say you set poly to 16
You load a new style patch which sets it to 3
Then you load an old style patch
What do you want poly to be.

Your choices are 8 (the default); 16 (the prior non-patch-delivered-version) or 3 (the hangover from the last patch).

And even if we add this feature, you want patch streaming versions in place first. Thats #391. So I think I'm going to tag this as "future release" and "new feature" unless you feel very strongly to the contrary.

**Comment by mkruselj** [comment]
In your scenario above, it should be 16 IMHO.

Not sure why polyphony is not stored in presets. Makes no sense that it isn't...

**Comment by baconpaul** [comment]
Yeah I think I agree but the fact that it’s not means we need to deal with patch version plumbing before it is. So this one will sit for a while

**Comment by baconpaul** [comment]
Tagging this 1.6.6; but also I think I will include a warning if you load a patch which decreases polyphony so you can override.
