### ISSUE TITLE
Combulator behaves abnormally after being bypassed and re-enabled in this patch

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#4295]
**Bug Description:**
Only the left channel can be heard when un-bypassing the combulator in the test patch attached below.

**Surge Version**
Latest nightly, VST3 x64

**Reproduction Steps:**
1. Open the patch below in Surge. It should sound fine and come out from both speakers.
2. Bypass the Combulator effect (either by right-clicking on it or using the FX Bypass setting)
3. Re-enable the Combulator in the same manner.
4. The output will only come out from the left channel.

**Additional findings:**
Tweaking Pan 3 slightly brings it back to normal behavior, so I guess the issue is somewhere related to that control.

[Bugged 2.zip](https://github.com/surge-synthesizer/surge/files/6292798/Bugged.2.zip)

**Comment by baconpaul** [comment]
Off by 1 in an upper bound compared with a limit range. Have a fix.
