### ISSUE TITLE
regression in patch browser: manual says that right-clicking will bring up a menu with just the patches in that category

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#430]
Surge manual says

> A right-click will bring up a menu with just the patches of the current category.

Suppose this means we could implement this behaviour?

**Comment by baconpaul** [comment]
Oh it did that a week ago. It doesn’t now? Yeah I know what would have changed that if it is broken.

**Comment by baconpaul** [comment]
Huh yeah that went away. Some changes in that code last week or two. I can fix in the next bit. Thanks for finding!

**Comment by esaruoho** [comment]
@baconpaul well it was totally worth checking out the manual while trying to fix it. anyway, back to tabling that..
