### ISSUE TITLE
Twist Oscillator chords type

### ISSUE THREAD

**Issue by CurlyMC** [surge-synthesizer/surge#4326]
Would be handy if chords engine could display the 11 chordtype's instead of percentage-slider.
oscillator > twist > engine chords > type rename percentage to chordtype ( oct. 5, sus4, m, m7 ect ).

**Comment by CurlyMC** [comment]
since I'm not a programmer, maybe it's more easy to add a 'send baconpaul a pizza for all the hard work' button to the Surge UI :-)
All programmers, thank you for the upcoming 1.9 version !!!

**Comment by baconpaul** [comment]
Mildly painful and too late to get that into 1.9 but a good idea. I'll tag it into XT.

**Comment by mkruselj** [comment]
Yeah I'd love this too 🙂

**Comment by baconpaul** [comment]
Oh man I though this would be a quick and easy one to bang out this morning and it almost was...

PR #4513 adds support for alt being dynamic. I'll merge it and when I do if you turn line 240 of TwistOscilaltor from return false to return true you will see the display of the chord name in the alt position

But it didn't line up with changes as I dragged the slider

And then I realized why. 

The plaits engine has hysteresis in the knob. Do this

Open twist
Choose chord
Set the chord to 0 (octave)
latch and you will hear the chord. Great

Now - pull the slider slowly up. Around 7% or so it will change to 5th
Pull the slider back down. At about 3% it changes back to octave

Even better

Set the slider to 0
Chose edit value and type in 6%
You still get an octave
Now pull the slider up to 10 or so so you get the fifth
Choose edit value and type in 6%
and you still get the 5th

This is a "problem" and probably requires us patching the knob code in plaits for this engine. I'll merge my code that does the display and we can turn it on once i've figured out that patch. But that patch isn't a quick morning PR. 

Sigh

**Comment by baconpaul** [comment]
Yup. 

```
const int chord_index = chord_index_quantizer_.Process(
      parameters.harmonics * 1.02f, kChordNumChords);
```

**Comment by CurlyMC** [comment]
Dear Paul, thank you for your great work and this feedback !
I understand. Replacing the slider with a dropdown menu isnt an option i guess ?

**Comment by baconpaul** [comment]
Nah the problem is the engine not the UI
I almost have it fixed.

**Comment by CurlyMC** [comment]
Looking perfect !!
Hoping to be able to check this one out soon, with a SurgeXT version on a Windows machine.
Again, thank you so much, the Surge team gives so much joy every day :-)

**Comment by baconpaul** [comment]
And glad you enjoy surge!
