### ISSUE TITLE
Surge XT Locations

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#4335]
Surge XT gets config.xml, paramdocumentation.xml and windows.wt from the binary. But the factory patches still need a home. So

- [x] Move from Surge to Surge XT for factory
- [x] Test windows portable mode to find SurgeDataXT
- [x] Change user settings file to SurgeXTUserSettings
- [x] Build cmake rules to do a local install

**Comment by mkruselj** [comment]
Can we also do FX presets as a separate folder structure in the binary rather than crammed into config.xml? Would be much easier to expand the factory FX presets then.

**Comment by baconpaul** [comment]
yeah sure. but lets open a separate issue for that.
