### ISSUE TITLE
Allow installation to D: or alt drive

### ISSUE THREAD

**Issue by K8inLA** [surge-synthesizer/surge#4345]
Please allow the option to choose a location for installation other than the C: drive on Windows. Many people have small SSD C: drives with the majority of memory on D:. I keep all my programs, data and VSTs on D:  Many plugins allow you to choose the location to install to, but this one doesn't. It would be great if that could be implemented in the next version.

**Comment by mkruselj** [comment]
We have a number of closed issues regarding this. We are following VST3 path guideline and leave the option of users symlinking to another drive. Please search through closed issues on this topic.
