### ISSUE TITLE
Extend Range on Filter Feedback

### ISSUE THREAD

**Issue by selenologist** [surge-synthesizer/surge#4354]
It is currently possible to push the filter feedback beyond +/-100% using e.g. maxed out envelope modulators.

Rather than 'fix' this behaviour by clamping modulators, we should add Extend Range to the slider, because greater than 100% feedback can produce interesting results in some cases.

I'm happy to do this one myself, just making a note here because I'd like to wait a moment in case we push out a 1.9.1, and to collect any feedback on the idea, no pun intended.

**Comment by mkruselj** [comment]
Let's do it similar to FM feedback - extend goes to +/-400%. But then also clamp FB in general so that it _doesn't_ go beyond +/-400%. Sound good?

**Comment by selenologist** [comment]
Sure, +/-400% seems like a useful extension in my testing.

But why clamp it? Letting people keep going to even more insane amounts if they want is fine. They shouldn't get any DSP bugs they wouldn't otherwise get with huge amounts of gain or other weird signals.

**Comment by mkruselj** [comment]
It's just that we're clamping pretty much any other gain related parameters, is all.
