### ISSUE TITLE
Remove midifile dependency

### ISSUE THREAD

**Issue by yurivict** [surge-synthesizer/surge#4358]
**Bug Description:**
```cmake/FindLibMidiFile.cmake``` only hooks up the bundled ```midifile``` sources and makes no attempt to find the library.

**Surge Version**
1.9.0

**Comment by baconpaul** [comment]
I think I'll just remove midi file instead. We don't use it for anything other than an ancient rendering case in headless. So let me add that as a task here.

**Comment by baconpaul** [comment]
OK removing the dep in our XT branch. If we end up needing it we can use juce;:MidiFile instead. But I don't think we will end up needing it. Will close this issue when merged.
