### ISSUE TITLE
No install target in cmake scripts

### ISSUE THREAD

**Issue by yurivict** [surge-synthesizer/surge#4359]
**Bug Description:**
This was one of TODO items in https://github.com/surge-synthesizer/surge/issues/1206
However, it was closed without this itemn being fixed.

**Surge Version**
1.9.0

The FreeBSD port currently has this script to install Surge:
```
do-install:
        # LV2 plugin
        ${MKDIR} ${STAGEDIR}${PREFIX}/lib/lv2
        cd ${BUILD_WRKSRC}/surge_products && ${COPYTREE_SHARE} Surge.lv2 ${STAGEDIR}${PREFIX}/lib/lv2
        ${STRIP_CMD} ${STAGEDIR}${PREFIX}/lib/lv2/Surge.lv2/Surge.so
        # VST plugin
        ${MKDIR} ${STAGEDIR}${PREFIX}/lib/vst
        ${INSTALL_LIB} ${BUILD_WRKSRC}/surge_products/Surge.vst3/Contents/*/Surge.so ${STAGEDIR}${PREFIX}/lib/vst
        # data
        cd ${WRKSRC}/resources/data && ${COPYTREE_SHARE} . ${STAGEDIR}${DATADIR}
```

This is error-prone because something can be missed in it.

```build-linux.sh``` doesn't work for the port because it assumes fixed paths instead of paths that cmake uses.

**Comment by yurivict** [comment]
Now I tried ```install-vst3-global``` but it breaks:
```
[ 16% 2/6] cd /disk-samsung/freebsd-ports/audio/surge-synthesizer-lv2/work/surge-release_1.9.0 && echo Installing\ local\ resources\ into\ /usr/local/share/surge && /usr/local/bin/cmake -E make_directory /usr/local/share/surge && rsync -r --delete resources/data/ /usr/local/share/surge/
FAILED: CMakeFiles/install-resources-global.util 
cd /disk-samsung/freebsd-ports/audio/surge-synthesizer-lv2/work/surge-release_1.9.0 && echo Installing\ local\ resources\ into\ /usr/local/share/surge && /usr/local/bin/cmake -E make_directory /usr/local/share/surge && rsync -r --delete resources/data/ /usr/local/share/surge/
Installing local resources into /usr/local/share/surge
Error creating directory "/usr/local/share/surge".
[ 33% 2/6] cd /disk-samsung/freebsd-ports/audio/surge-synthesizer-lv2/work/surge-release_1.9.0 && /usr/local/bin/cmake -D PROJECT_VERSION_MAJOR=1 -D PROJECT_VERSION_MINOR=9 -D SURGESRC=/disk-samsung/freebsd-ports/audio/surge-synthesizer-lv2/work/surge-release_1.9.0 -D SURGEBLD=/disk-samsung/freebsd-ports/audio/surge-synthesizer-lv2/work/.build -D AZURE_PIPELINE= -D WIN32= -D CMAKE_INSTALL_PREFIX=/usr/local -D SURGE_COMPILER_INFO="Clang-10.0.1" -P /disk-samsung/freebsd-ports/audio/surge-synthesizer-lv2/work/surge-release_1.9.0/cmake/versiontools.cmake
-- VERSION_GIT_INFO file is present; using that rather than git query
-- Setting up surge version
--   git hash is 0000000 and branch is unknown
--   buildhost is yv.noip.me
--   buildarch is amd64
-- Developer Local Build
-- Using SURGE_VERSION=1.9.unknown.0000000
-- Configuring /disk-samsung/freebsd-ports/audio/surge-synthesizer-lv2/work/.build/geninclude/version.cpp
ninja: build stopped: subcommand failed.
```

It doesn't use proper stage directory and installs into the read-only ```$PREFIX```.

**Comment by baconpaul** [comment]
OK guess it doesn't work then!

Will add this to our next milestone.

Is there a spec you are looking for us to work towards against which we could test?

**Comment by baconpaul** [comment]
(for context we are moving to JUCE and rewriting most of the cmake rules so now is a good time to plan for what you expect)

**Comment by yurivict** [comment]
We do have the JUCE package, so hopefully Surge would be able to build with the pre-installed JUCE package.

**Comment by yurivict** [comment]
> Is there a spec you are looking for us to work towards against which we could test?

It should just be able to install the project by itself.

**Comment by baconpaul** [comment]
> We do have the JUCE package, so hopefully Surge would be able to build with the pre-installed JUCE package.

The current build allows you to set a single CMAKE variable and pick another JUCE if you want.

**Comment by baconpaul** [comment]
> > Is there a spec you are looking for us to work towards against which we could test?
> 
> It should just be able to install the project by itself.

My experience with the variety of operating systems in the linux-and-bsd-adjacent family is that each distribution and flavor thinks that installation is obvious and none of them agree on what that obvious thing is :)

Are there paths and prefixes which FreeBSD uses which are well documented for how an install should work? Clearly just writing into /usr/local isn't want you want (and we use the CMAKE prefix thing now for instance). 

Thanks

**Comment by yurivict** [comment]
> Are there paths and prefixes which FreeBSD uses which are well documented for how an install should work? Clearly just writing into /usr/local isn't want you want (and we use the CMAKE prefix thing now for instance).

Installation in cmake is fairly straightforward.
```
install(TARGETS {exe-target} DESTINATION bin)
install(TARGETS {lib-target} DESTINATION lib)
```

cmake takes care of paths.

**Comment by baconpaul** [comment]
but that would install in /usr/lib or what not which isn't the correct vst3 or lv2 path isn't it? Does that actually work for soft synth plugins?

Do you have another soft synth packaged with cmake in freebsd that works? Perhaps I could consult that

**Comment by yurivict** [comment]
> but that would install in /usr/lib or what not which isn't the correct vst3 or lv2 path isn't it? Does that actually work for soft synth plugins?

No, this would install into the currently set ```$STAGEDIR$PREFIX```.
It should be sufficient for any plugins.

In cmake you don't need to think about this detail.

**Comment by mynameismuhl** [comment]
--target install-vst3-local 
puts it into ~/.vst3
if that helps

**Comment by yurivict** [comment]
The port currently uses the custom script that seems to install Surge correctly.

**Comment by baconpaul** [comment]
OK great. I'll look at this for linux across the xt cycle, and sorry you have to keep your crufty script alive. 

If you are willing, Is there a good way to inform you of when a beta cycle is happening on our next version? It seems you often find infrastructural problems after we release but would be great if you could test before and let us know so we could fix them for a stable release point!

Thanks

**Comment by yurivict** [comment]
> [...] Is there a good way to inform you of when a beta cycle is happening on our next version?

Just ping me @ yuri@FreeBSD.org.

**Comment by baconpaul** [comment]
cool will leave this open and ping you when there's something testable before our release. 
thanks.

**Comment by baconpaul** [comment]
Heads up - later this evening I will merge to head install targets in the cmake file for unix-not-apple

Following works for me on ubuntu

```
cmake -Bignore/sxt -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
cmake --build ignore/sxt --config Release --paralllel 8
sudo cmake --install ignore/sxt
```

This issue will auto close when it merges.

**Comment by yurivict** [comment]
Thanks!

I'll update the port with the next release.

**Comment by baconpaul** [comment]
Yeah that’s months out yet but i made a not to ping you when we are closer

**Comment by yurivict** [comment]
Okay!
