### ISSUE TITLE
Sliders are missing on the 'Low Cut' and 'High Cut' widgets

### ISSUE THREAD

**Issue by yurivict** [surge-synthesizer/surge#4360]
**Bug Description:**
I am comparing the Surge plugin image on the YouTube video (left) with an actual Surge window (right) and observe the difference that sliders are missing in the actual window:

![image](https://user-images.githubusercontent.com/271906/115769848-de7f3a80-a360-11eb-9c55-6284c40fe81b.png)

This doesn't seem normal to me. Sorry for the noise if this is normal.

**Surge Version**

* Version: 1.9.0

**Comment by baconpaul** [comment]
Well it's not quite normal but it is known

On linux with vstgui we can't draw transparent sliders so we remove them there

if you RMB/Enable they will appear

On mac and windows (and on linux in our juce port) they can appear ghosted out.

So known issue. thank you for reporting!
