### ISSUE TITLE
Bitwig Typing Keyboard hung notes

### ISSUE THREAD

**Issue by XtremeSounds** [surge-synthesizer/surge#4367]
**Bug Description:**
Im using my typing keyboard in Bitwig Studio 3.3.7 and sometimes the notes hang and I have to click off the track to get it to go quiet. 

**Surge Version**
1.9

* Version:
* Plugin Type: [VST2, VST3, AU]  VST3
* Bitness: [32-bit or 64-bit]  64bit

**Reproduction Steps:**
2. Click on '...'
3. Scroll down to '...'

**Expected Behavior:**
no hung notes when playing the synth

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following information):**
Window 10 64 bit
Bitwig Studio 3.3.7
FL studio Asio drivers

**Additional Information:**

**Comment by mkruselj** [comment]
Do the notes ever hang when simply playing stuff from piano roll? Would also appreciate if you could test with a proper MIDI controller.

**Comment by baconpaul** [comment]
And also how do you use the typing keyboard? Thanks

**Comment by XtremeSounds** [comment]
In Bitwig if we press Caplocks key it allows us to use the typing keyboard to play notes.   That is waht is causing the hung notes.  I just tried with the midi controller and it seems fine.

**Comment by mkruselj** [comment]
Bitwig issue then, more likely than not.

**Comment by XtremeSounds** [comment]
Maybe they will of course deny it.  
![Capture](https://user-images.githubusercontent.com/49108783/115873411-e4ccef80-a410-11eb-975b-4d5e1506d42e.JPG)

**Comment by baconpaul** [comment]
Can you attach that FXP here?

That error message occurs when the FXP you are loading was not created by surge or is otherwise corrupted. There's no "Init Patch.fxp" in our factory library so we need to see your patch to debug it.

That error message used to have a lot of extra stuff. I am now wishing we hadn't taken it all out :)

**Comment by mkruselj** [comment]
> Maybe they will of course deny it.

Doubt it. They're not Steinberg. 😁

**Comment by XtremeSounds** [comment]
I think its because all the presets that come with surge are listed as fxp on my system.  Bitwig doesn’t load fxp files only its own file format in their browser.  I just wont use that method to load a preset

**Comment by baconpaul** [comment]
OK!
