### ISSUE TITLE
cannot load patch from file

### ISSUE THREAD

**Issue by XtremeSounds** [surge-synthesizer/surge#4368]
**Bug Description:**
When I try to load patch from file in the patch menu I get this message "Unable to load" 

**Surge Version**
1.9

* Version:
* Plugin Type: [VST2, VST3, AU]  vst3
* Bitness: [32-bit or 64-bit]  64bit

**Reproduction Steps:**
1. right click preset name
2. select "load patch from file" 
3. select patch you wish to load

**Expected Behavior:**
Load patch correctly. I was trying to load an Init patch as I dont see another way to do that. 

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following information):**
 - OS: [e.g. Windows 10] Windows 10 64 bit
 - Host: [e.g. Bitwig, Logic, Cubase, Reaper]  Bitwig 3.3.7
 - Version: [e.g. 2.4]

**Additional Information:**

**Comment by baconpaul** [comment]
Can you attach the patch here and the screenshot with the complete message?
Also could you try dragging and dropping the file onto your surge?

The init patches are all in "Templates"

**Comment by XtremeSounds** [comment]
Its all patches.  Dragging them onto Surge works ok. Its just selecting them using the windows explorer menu after selecting "load patch from file" option

**Comment by baconpaul** [comment]
Huh can you share the exact error box?
@mkruselj thisnwork for you on win? Works fine for me on Mac. 
@XtremeSounds do you have any odd characters in the file paths? Like your load directory contains a diacritical or emoji or something?

**Comment by baconpaul** [comment]
And thanks also for reporting!

**Comment by XtremeSounds** [comment]
No problem.  I didn’t realize how versatile this synth is.  The new skin caught my attention and with Twist and other additions  I can get eurorack like stuff out of this thing.

**Comment by XtremeSounds** [comment]
Hi Paul

 

My Surge 1.9 just went quiet.  No sound coming out.

**Comment by XtremeSounds** [comment]
Never mind it was the popup screen that was still open from the screenshot I just sent

**Comment by mkruselj** [comment]
We don't see any screenshots.

**Comment by baconpaul** [comment]
The screenshot was on the other thread


![](https://user-images.githubusercontent.com/49108783/115873411-e4ccef80-a410-11eb-975b-4d5e1506d42e.JPG)

basically: It looks like @XtremeSounds is loading a patch which isn't a surge patch. We need that FXP.

**Comment by mkruselj** [comment]
Two issues got mixed up, this one should be closed instead.
