### ISSUE TITLE
Toggling routing mode with mouse3, 4 or 5 when hovering over Alias additive editor doesn't work

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#4374]
Mouse3, 4 or 5 to enable routing mode should work everywhere (no matter where the mouse pointer is), but in the Alias harmonic editor it acts as a left-click, modifying the harmonic content.

This is a *very* minor bug, and I don't know what milestone to tag it with. 
IIRC Paul said that it would be very easy to fix.

**Comment by mkruselj** [comment]
So mouse3/4/5 is very much a VSTGUI thing, JUCE doesn't have it, and since we're moving to JUCE...

**Comment by VincyZed** [comment]
Let's only keep Mouse3 then. I agree that we should avoid 1.9.1 if possible, just opened this in case we actually do have to release it.

**Comment by mkruselj** [comment]
ED's got this 🙂
