### ISSUE TITLE
ED's XT pedantikons

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4377]
- [x] ~The menu button doesn't unhover after you see the menu~ The menu button now reverts the hover state as soon as clicking on it, instead of when closing the menu
- [ ] ~These things are back at 175% zoom (non-HiDPI):~ (moved to #4438)
![image](https://user-images.githubusercontent.com/2393720/115920845-082c8480-a47b-11eb-928a-53ef979b088a.png)
- [x] FX preset names aren't shown at all in the text label
- [x] Miniedit button and text input fields should follow skin colors etc.
- [x] Text input fields need some vertical alignment to center (Patch Store dialog, miniedits)
![image](https://user-images.githubusercontent.com/2393720/115921450-ccde8580-a47b-11eb-99a8-bf9d66a86881.png)
- [x] Filter type menus need vertical text centering
![image](https://user-images.githubusercontent.com/2393720/115921504-df58bf00-a47b-11eb-9ba2-ad336d9a0d5b.png)
- [x] VU Meter doesn't draw properly - white edges not black
- [x] FX bank standalone exe (nor VST3 plugin bundle) doesn't have an icon
![image](https://user-images.githubusercontent.com/2393720/116008561-80c74880-a615-11eb-9ffc-7194262528f1.png)
- [x] When double-clicking on a slider to default it, the value popup sticks around

**Comment by baconpaul** [comment]
yeah the multi-column thing should be doable but i kinda want to rewrite at least the patch menu to be less sucky and use some new juce features (like colored headers and stuff).
rest are very good thank you!

**Comment by baconpaul** [comment]
Moved a couple of these from this list into independent issues of their own (as I did with the now dead #3737)
Lets keep this one open for other observations though and for the smaller ones you list here.
