### ISSUE TITLE
JUCE menus and labels deal incorrectly with Emoji

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#4385]
I have a "The magic of 🥓" patch category which doesn't render properly
@selenologist has a version of config.xml with japanese characters that also doesn't
If you load ucomputer 

I've confirmed we get proper UTF-8 all the way down to PopupMenu.addEntry

It's somewhere in juce labels. If I load " Sine 🌊.fxp" from "The magic of 🥓" the UI I get is this:

<img width="591" alt="Screen Shot 2021-04-23 at 9 55 23 PM" src="https://user-images.githubusercontent.com/13387561/115943560-9f470b80-a47e-11eb-9f50-60b29676e41e.png">

and in 1.9 I get this

<img width="516" alt="Screen Shot 2021-04-23 at 9 55 56 PM" src="https://user-images.githubusercontent.com/13387561/115943575-b1c14500-a47e-11eb-9ead-90431d406c89.png">

**Comment by baconpaul** [comment]
A better fix is to use TextLayout in the LnF of Combo and PopupMenu which will find fallback fonts when glyphes are not available in the current one.

from https://forum.juce.com/t/embedding-unicode-string-literals-in-your-cpp-files/12600/2

**Comment by baconpaul** [comment]
https://forum.juce.com/t/how-to-render-an-emoji-with-juce-graphics/45699

**Comment by mkruselj** [comment]
@baconpaul Are we closing this one as JUCE has limits here?

**Comment by baconpaul** [comment]
not yet

**Comment by baconpaul** [comment]
Really need to wait for JUCE on this one, alas. Bouncing out of XT1

**Comment by baconpaul** [comment]
This is in the JUCE 7 feature list. So let me close it here since there's nothing to be done other than upgrade juce in the future.
