### ISSUE TITLE
preset management

### ISSUE THREAD

**Issue by XtremeSounds** [surge-synthesizer/surge#4388]
**Is your feature request related to a problem? Please describe.**
Cannot find favorite preses or browse all presets of a certain character ie pad, brass, kick etc

**Describe the solution you'd like:**
A way to star favorite a preset, also a way to search all presets by keywords to apply filter. 

**Describe alternatives you've considered:**
resaving a preset to user folder. This only would solve the favorites issue not finding all presets that are pads etc. 

**Additional context:**

**Comment by mkruselj** [comment]
We already have a feature request for tag/category filter based patch browser, it will happen in Surge XT. #2359

I'd urge you to please search existing issues before posting a feature request in order to prevent duplicates. Thanks!
