### ISSUE TITLE
help popup for parameters

### ISSUE THREAD

**Issue by XtremeSounds** [surge-synthesizer/surge#4389]
This may be useful. I did a search and no one has requested it.  Perhaps simply opening the manual to the page that deals with the controls that we right click and select look up in manual.  I dont need it but thought it would be useful for many.

**Comment by mkruselj** [comment]
Right click any parameter and first entry has [?] which takes you to the manual....

Explore around please 🙂

**Comment by XtremeSounds** [comment]
I did a search for this feature but I couldn’t find it.  Thanks for that. You have thought of everything!
