### ISSUE TITLE
Add option to rename and delete presets

### ISSUE THREAD

**Issue by Altarberg** [surge-synthesizer/surge#4391]
It would be great to have an option to rename and delete presets within surge. I thought about it countless times while using it and saving presets, so here goes the FR.
Thanks!

**Comment by baconpaul** [comment]
You mean user presets right? That’s a good idea and we can it as a fr to the xt patch browser

**Comment by Altarberg** [comment]
Yes, the user patches. 
I usually save multiple versions of the same patch and later delete the older/bad/unfinished ones.
This will speed up the process.

**Comment by baconpaul** [comment]
Linking to #2359

**Comment by baconpaul** [comment]
@mkruselj this is super easy to code; but where do you think we should hang it in the stripped back 1.0 UI?

I could easily make a "Functions/Rename" and "Functions/Delete" in the menu for instance. Delete would prompt an are you sure and send you back to init; rename would pop a new name dialog and do the right thing.

but before i code wanted your opinion

**Comment by mkruselj** [comment]
That's exactly what I thought we'd do! Both options would show only after loading a preset, of course.

**Comment by baconpaul** [comment]
OK! Will bang it out before the weekend then. Cool.
