### ISSUE TITLE
Royal surge resizing with mouse not working

### ISSUE THREAD

**Issue by XtremeSounds** [surge-synthesizer/surge#4396]
**Bug Description:**
When using the mouse to drag the corner of royal surge the window should resize, it does not instead the border moves only.  The free netrunner skin works properly using the mouse to resize.  https://www.stanleygurvich.com/

**Surge Version**
1.9

* Version:
vst3 64 bit

**Reproduction Steps:**
use the mouse to drag an edge of the plugins border, move the mouse to resize

**Expected Behavior:**
the plugin should resize instead of just the border moving.  If it cannot resize then please lock the border from moving. 

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following information):**
Windows 10 64 bit bitwig 3.3.7

**Additional Information:**

**Comment by baconpaul** [comment]
Yeah royal doesn’t use vector graphics for its background so has constrained zoom levels. If you want arbitrary zoom you need to use a vector skin like classic dark or one or netrunner
