### ISSUE TITLE
MSEG Editor Rendering Issues

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#4409]
- [x] The gradient isn't there
- [x] Dashed and Dotted lines for the axis are mostly skipped

**Comment by mkruselj** [comment]
Mousewheel doesn't seem to zoom in-out either.

**Comment by mkruselj** [comment]
So this issue is now basically done, except dashed/dotted lines are still not there :(

**Comment by baconpaul** [comment]
Oh the api for that is pretty easy. I figured it out for lfo. When I finally get time to wrap that up (crazy week here) we can go back to mseg snd do it there
