### ISSUE TITLE
Add Accessibility Handlers to the TinyLittleIconButton (was: Expanded multi button menus)

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#4418]
Only thing left is accessibility APIs

<img width="363" alt="Screen Shot 2021-09-12 at 9 29 22 AM" src="https://user-images.githubusercontent.com/13387561/132990002-a3d87a40-ebd6-4d2c-b081-f3277e4f1da0.png">

----

Talking on discord @mkruselj and I thought of turning this menu

<img width="399" alt="Screen Shot 2021-04-25 at 10 22 46 PM" src="https://user-images.githubusercontent.com/13387561/116020957-45c51500-a615-11eb-8ab8-49cc35e6116c.png">

into the far mode compact version where the edit menu item also has a 'clear' button. So it becomes kinda like this with that red box being a "x" of some sort. (@mkruselj wanted to get rid of those edit and clear altogether but the rest of us didn't like that idea at all!).

<img width="549" alt="Screen Shot 2021-04-25 at 10 26 42 PM" src="https://user-images.githubusercontent.com/13387561/116021003-56758b00-a615-11eb-8a2d-223c1dedf8d1.png">

So this issue is: can I use a custom menu renderer to have the menu send two different messages somehow and plumb it through so that is doable and the menu is more compact. Placeholder so we don't forget the convo.

This also relates to #2049 but is obviously distinct.

**Comment by baconpaul** [comment]
mute too next to that obvs

**Comment by tank-trax** [comment]
might I propose two buttons... one for clear (an x) and another to edit (a pencil)
even more compact

**Comment by baconpaul** [comment]
Yeah clear and mute for sure - the menu can do something if you click outside the button but we can add a pencil too.

**Comment by mkruselj** [comment]
There's no need for pencil. I bet we can make the value displayed a text edit field directly.

**Comment by baconpaul** [comment]
So I started hacking on this and I realized its gonna run head first into the accessibility changes if I'm not careful. Need to think a bit.

`baconpaul/custom-menu-4418` so i have it stashed away at least

**Comment by baconpaul** [comment]
OK so right now this menu

<img width="269" alt="Screen Shot 2021-11-11 at 11 10 52 AM" src="https://user-images.githubusercontent.com/13387561/141330867-3ce751a0-f205-4e18-bad5-2e07d7580dcd.png">

shows up this way in accessible query

```
MENU>>  'menu' (AXWindow actions=['Raise'])
MENU>> |-- 'Surge XT' (AXWindow actions=['Raise'])
MENU>> |--|-- '' (AXMenuItem actions=['Press'])
MENU>> |--|-- '' (AXGroup actions=[])
MENU>> |--|-- 'Edit Value: 0.00 dB' (AXMenuItem actions=['Press'])
MENU>> |--|-- '' (AXMenuItem actions=['Press'])
MENU>> |--|-- '' (AXGroup actions=[])
MENU>> |--|-- '' (AXMenuItem actions=['Press'])
MENU>> |--|-- '' (AXGroup actions=[])
MENU>> |--|-- '' (AXGroup actions=[])
MENU>> |--|-- '' (AXGroup actions=[])
MENU>> |--|-- '' (AXGroup actions=[])
MENU>> |--|-- 'Add Modulation from' (AXMenuItem actions=['ShowMenu', 'Press'])
MENU>> |--|-- 'Modulation List...' (AXMenuItem actions=['Press'])
MENU>> |--|-- 'Assign to MIDI CC' (AXMenuItem actions=['ShowMenu', 'Press'])
MENU>> |--|-- 'MIDI Learn...' (AXMenuItem actions=['Press'])
```

which is 'bad'

**Comment by baconpaul** [comment]
And after I merge #5368 we will get

```
MENU>>  'menu' (AXWindow actions=['Raise'])
MENU>> |-- 'Surge XT' (AXWindow actions=['Raise'])
MENU>> |--|-- '' (AXMenuItem actions=['Press'])
MENU>> |--|-- 'Pre-Filter Gain' (AXMenuItem actions=['Press'])
MENU>> |--|-- 'Edit Value: 0.00 dB' (AXMenuItem actions=['Press'])
MENU>> |--|-- '' (AXMenuItem actions=['Press'])
MENU>> |--|-- 'MODULATIONS' (AXMenuItem actions=[])
MENU>> |--|-- '' (AXMenuItem actions=['Press'])
MENU>> |--|-- 'ENV 3 by 4.63 dB' (AXMenuItem actions=['Press'])
MENU>> |--|-- 'Clear ENV 3' (AXMenuItem actions=['Press'])
MENU>> |--|-- 'Mute ENV 3' (AXMenuItem actions=['Press'])
MENU>> |--|-- 'Edit ENV 3' (AXMenuItem actions=['Press'])
MENU>> |--|-- 'Add Modulation from' (AXMenuItem actions=['ShowMenu', 'Press'])
MENU>> |--|-- 'Modulation List...' (AXMenuItem actions=['Press'])
MENU>> |--|-- 'Assign to MIDI CC' (AXMenuItem actions=['ShowMenu', 'Press'])
MENU>> |--|-- 'MIDI Learn...' (AXMenuItem actions=['Press'])
```

which is "good"
