### ISSUE TITLE
Hovers not working on switches (XT)

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4423]
![nohovers](https://user-images.githubusercontent.com/2393720/116083176-9e8bc080-a69c-11eb-9f01-fb5c7aff5cc0.gif)

As can be seen, hover doesn't seem to happen on CHSwitch2 (also doesn't happen on CSurgeSwitch and filter type menu). Sliders are fine.

**Comment by baconpaul** [comment]
So: Mac Classic th hovers work fine
Switch to dark and *some* of them work but not *all* of them
I wonder if the hover bmp resolution is failing somehow?
but not an all-or-nothing but a few-if-you-swap is what i see here. curious.
