### ISSUE TITLE
SurgeEffectsBank Can't Load in FL with .vst3 folder extension 

### ISSUE THREAD

**Issue by ramij294** [surge-synthesizer/surge#4434]
When Surge 1.9 released, i installed it and found out that when i try to load SurgeEffectsBank it gave me error that something went wrong with loading vst3 plugin, please make sure it is installed properly.
Then i checked the folders and found that in  program files\common files\vst3\Surge synth team\  there is a folder named SurgeEffectsBank.vst3 . If you remove .vst3 from the name of folder and rescan in daw, it now works perfect.
I just wanted to make sure that when you will make new updated binary keep this point in mind so that everything install perfectly.

Daw: FL studio 20.7
Surge Version: 1.9.0
Plugin Type: [ VST3]
Bitness: [64-bit]

**Comment by baconpaul** [comment]
Thanks for the report. That sounds like a fl bug to me! The vst3 spec suggests a folder named .vst3 with the contents inside and our vst3 for sfx just comes out the back of juce

@VincyZed you run this version of fl? Any thoughts?

**Comment by VincyZed** [comment]
I haven't really tried SurgeFX yet, I will and keep you guys posted.

**Comment by mkruselj** [comment]
It loads fine here in FL 20.8. FL doesn't seem to detect plugin type properly, so I needed to manually adjust Type to "Effect" in FL Plugin Manager.

![image](https://user-images.githubusercontent.com/2393720/116365456-8f745200-a805-11eb-9070-2d3b04661a1d.png)

**Comment by baconpaul** [comment]
#4401 is the prescription for how we set effect and instrument and stuff in juce CMake so just tagging that here.

Is there anything to be done on this thread?

**Comment by mkruselj** [comment]
Probably not, as I could cleanly load FX bank in FL...
