### ISSUE TITLE
Lots of clicks when using SurgeEffectsBank

### ISSUE THREAD

**Issue by jedix273** [surge-synthesizer/surge#4437]
**Bug Description:**
A high amount of clipping-sounding clicks are produced when using SurgeEffectsBank.
This bug happens with (almost) any effect, in some cases occurring immediately and, in others, after modifying some parameters.

**Surge Version**

* Version: 1.9.0.91069f8
* Plugin Type: VST3
* Bitness: 64-bit

https://user-images.githubusercontent.com/83146012/116329879-e17b9000-a791-11eb-8ff5-8516a7ac156b.mp4

**Computer Information:**
 - OS: Windows 10
 - Host: Reaper (v6.25)

**Comment by baconpaul** [comment]
OK so running drums into the 1.9 au and vst3 in logic and reaper mac at 48k respectively makes no click here. @mkruselj can you give it a whirl in windows reaper when you get a chance?

The windows audio subsystem is a mystery to me but I wonder if there's some chance that it is some driver thing or something?

**Comment by baconpaul** [comment]
@jedix273 reports that switching from FlexASIO to DirectSound fixes this
that had @baconpaul look at the code and realized that he coded it so that SFXBank requires a block size of 32 or larger and also divisible by 32
Damnit. Maybe there will be a 1.9.1 after all.

**Comment by mkruselj** [comment]
I think no pressure, let's just tell people to use common buffer sizes that are powers of 2 divisible by 32 🙂

**Comment by baconpaul** [comment]
Right. So the prob

**Comment by baconpaul** [comment]
Closing this.
