### ISSUE TITLE
Surge XT doesn't play Scene B when in Dual play mode

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#4440]
This at least happens on my side, with the following config:

Surge XT VST3 x64
FL Studio 20 x64
Win 10 x64

**Comment by baconpaul** [comment]
Can you just quickly check a couple of things fo rme

1. in single mode scene b does it play
2. are you sure you don't have the scene a output as your main output as opposed to the final output? i wonder if fl is confused with the way i set up the busses

**Comment by VincyZed** [comment]
Yes, in Single Mode scene B plays. This probably means that it isn't an issue related to individual scene outputs, and I disabled the option just to be sure.

**Comment by VincyZed** [comment]
Ah! So here's some more info after trying stuff in XT:

- MIDI channel 1 plays only Scene A
- MIDI channel 2 plays only Scene B
- MIDI channels 3+ play both Scene A and B

So basically the MIDI channel -> scene relation has shifted by one channel. Here's the intended behavior, which is what happens in 1.9:
- MIDI channel 1 plays both Scene A and B
- MIDI channel 2 plays only Scene A
- MIDI channel 3 plays only Scene B
- MIDI channels 4+ play both Scene A and B.

**Comment by baconpaul** [comment]
Off by 1. I bet juce is 0 based. Awesome.
Bet you can fix it. Surgesynthprocessor.cpp sub or add 1 to m.getchan

**Comment by VincyZed** [comment]
Let me try that.. :)

**Comment by mkruselj** [comment]
Says so in the docs:

![image](https://user-images.githubusercontent.com/2393720/116366495-a4051a00-a806-11eb-9807-8aff01e19b75.png)
