### ISSUE TITLE
Surge XT: Both filter Cutoff controls take 3 clicks to reset, instead of a standard double-click

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#4441]
**Bug Description:**
The filter cutoff sliders require a triple-click to reset to default value, instead of a double click like the rest of the controls.

**Surge Version**
XT Alpha 11a18d4

VST3 x64, in FL Studio 20.8.3 x64 on Windows 10 x64.

**Comment by mkruselj** [comment]
They actually take two clicks and a mouse move. 😛

**Comment by baconpaul** [comment]
so weird and it is *only* the filter cutoffs.
a double click and anything to force it to lose focus does it

**Comment by baconpaul** [comment]
got it
