### ISSUE TITLE
SurgeXT/Linux Crash on click on LFO-Preset-Menu

### ISSUE THREAD

**Issue by mynameismuhl** [surge-synthesizer/surge#4445]
Linux 64bit
built at commit 0c7d9d0d4acd51e450fc3b859ce051ea5e5cfa33
SurgeXT Standalone and Vst3

Crash when clicking on Modulator-Preset-Button 

Terminal:
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

Syslog:
[new file.txt](https://github.com/surge-synthesizer/surge/files/6394226/new.file.txt)

**Comment by baconpaul** [comment]
Thanks! Super appreciated
There’s a million bugs in xt and each one we get reported helps. But there are also a million bugs so patience appreciated :)

**Comment by mynameismuhl** [comment]
too early for reporting is what you mean?

**Comment by baconpaul** [comment]
No not at all! Reports super duper useful

But too early to expect the stability of any part of the 19 cycle. And too early for production music making

**Comment by mynameismuhl** [comment]
don't worry, no expectation, no music

**Comment by baconpaul** [comment]
Yeah cool. Just wanted to make sure you knew! Would hate for you to try and write a magnum opus with xt when 1.9 is sitting there :)

And thanks as always for all the help!

**Comment by baconpaul** [comment]
100% reproducible by the way

**Comment by baconpaul** [comment]
oh the problem is because of my semi-non-matching coptionmenu semantics.
