### ISSUE TITLE
XT Patch database poof crash

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4453]
Just can't explain this. Sometimes happens after two or three tries, sometimes after more. I just keep on typing "panda", then Ctrl+A to select all text then type it all up again... In this case it hung then poofed when I typed "n".

![poof](https://user-images.githubusercontent.com/2393720/116733116-fc494100-a9eb-11eb-8f44-730af8eda24f.gif)

**Comment by baconpaul** [comment]
man if you can run this under a debugger and get a stack
i just typed panda 20 times on macOS with no crash
but also that's not the code at head. (although i haven't made any crash proofing changes).
i can try on windows tho!

**Comment by baconpaul** [comment]
@mkruselj can you try this again at head? no crash for me after yesterdays merges.

**Comment by mkruselj** [comment]
@baconpaul Still happens! Got it in 2 seconds.

**Comment by baconpaul** [comment]
Wow well that’s upsetting, 
Did you blow away your database?
No crashes in my vm here.

**Comment by baconpaul** [comment]
The threading flags are ok according to the doc but I can try a few other things

**Comment by mkruselj** [comment]
![image](https://user-images.githubusercontent.com/2393720/116939884-5e64a900-ac6d-11eb-8cc8-86ab77264136.png)
