### ISSUE TITLE
Tape FX in Surge takes ~2x more CPU on my machine compared to ChowTape

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#4455]
On my machine, when simply loading both FXs, ChowTape takes ~3% CPU when idle, where as Surge's Tape takes ~6%.

**Steps to reproduce**
Simply take an init patch and load Surge Tape FX on any FX Slot (or more than one, it pretty much scales linearly) . Compare to what ChowTape takes when loaded in the DAW.

Here's my config:
- OS: Windows 10 x64
- DAW: FL Studio 20.8.3 x64
- CPU: Ryzen 7 3700X

Tagging @jatinchowdhury18 and @baconpaul as suggested on Discord.

**Comment by mkruselj** [comment]
@jatinchowdhury18 Could add it on right-click as one of "deform modes", perhaps. Doesn't need a new physical parameter I don't think.

**Comment by jatinchowdhury18** [comment]
Okay, that could be good. @mkruselj is there another effect that does something like this that I could use for reference?

**Comment by baconpaul** [comment]
It’s not an effect but the way the modern oscillator supports the alternate shapes and subs on the third shape uses deform this way if I recall

The code is sort of splattered in surgeguieditor a bit and I would like to clean it up but you can follow that splatter trail

**Comment by mkruselj** [comment]
Wait, this one is sorted out with Jatin's recent commit, right?

**Comment by baconpaul** [comment]
Yup.
