### ISSUE TITLE
Some drawn elements are still pixel-y

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#446]
Some drawn elements are still pixel-y

<img width="196" alt="screen shot 2019-02-01 at 8 28 20 pm" src="https://user-images.githubusercontent.com/13387561/52157781-ebb88d80-265f-11e9-9ca6-7d6070237699.png">

arrows in the wavetable browser

<img width="421" alt="screen shot 2019-02-01 at 8 28 40 pm" src="https://user-images.githubusercontent.com/13387561/52157787-f83ce600-265f-11e9-8eea-74fcb98443a6.png">

edges of VU meter

These are all things drawn by code not by bitmaps so need C++ changes.

(If we find more add them to this issue)

tagging @itsmedavep and @esaruoho

**Comment by baconpaul** [comment]
And connecting with #305

**Comment by baconpaul** [comment]
<img width="469" alt="screen shot 2019-02-01 at 8 55 24 pm" src="https://user-images.githubusercontent.com/13387561/52158172-b3b34980-2663-11e9-9055-895bfaced6ba.png">

Got one of them.

**Comment by esaruoho** [comment]
imo those arrows could be at least one pixel higher.. and .. sharper? :)

**Comment by itsmedavep** [comment]
Nice! 

@esaruoho 
`//// Drawing Methods

        public static void DrawTriangle()
        {
            DrawTriangle(new CGRect(0.0f, 0.0f, 3.0f, 5.0f), ResizingBehavior.AspectFit);
        }

        public static void DrawTriangle(CGRect targetFrame, ResizingBehavior resizing)
        {
            //// General Declarations
            var context = UIGraphics.GetCurrentContext();
            
            //// Resize to Target Frame
            context.SaveState();
            var resizedFrame = ResizingBehaviorApply(resizing, new CGRect(0, 0, 3.0f, 5.0f), targetFrame);
            context.TranslateCTM(resizedFrame.X, resizedFrame.Y);
            context.ScaleCTM(resizedFrame.Width / 3.0f, resizedFrame.Height / 5.0f);


            //// Color Declarations
            var color = UIColor.FromRGBA(0.000f, 0.000f, 0.000f, 1.000f);

            //// Polygon Drawing
            context.SaveState();
            context.TranslateCTM(3.0f, -0.0f);
            context.RotateCTM(90.0f * NMath.PI / 180.0f);

            var polygonPath = new UIBezierPath();
            polygonPath.MoveTo(new CGPoint(2.5f, 0.0f));
            polygonPath.AddLineTo(new CGPoint(4.67f, 2.25f));
            polygonPath.AddLineTo(new CGPoint(0.33f, 2.25f));
            polygonPath.ClosePath();
            color.SetFill();
            polygonPath.Fill();

            context.RestoreState();
            
            context.RestoreState();

        } `

Will that take care of it for you?🤪

**Comment by baconpaul** [comment]
Oooh where does that code live? Or did you just write it? That would help a lot.

**Comment by itsmedavep** [comment]
We sort of. I had similar stuff laying around from another project.

**Comment by baconpaul** [comment]
So I think replacing those triangles with proper draws using vstgui is the way to go.

You can do this with a graphics path

```
  VSTGUI::CGraphicsPath* gp = dc->createGraphicsPath();
      for (auto path = shape->paths; path != NULL; path = path->next)
      {
         for (auto i = 0; i < path->npts - 1; i += 3)
         {
            float* p = &path->pts[i * 2];

            if (i == 0)
               gp->beginSubpath(p[0], p[1]);
            gp->addBezierCurve(p[2], p[3], p[4], p[5], p[6], p[7]);
         }
         if (path->closed)
            gp->closeSubpath();
      }
```

is an example of the code with VSTGUI

You can then call context->drawGraphicsPaht( path, kPathFilled ) and then path->forget()

So then figure out where the triangle points re and make a path with 3 points for a triangle, close it, and voila.

**Comment by itsmedavep** [comment]
I have a PR that fixes the wt and window pixelated triangles (that Paul already fixed before LOL). 

https://github.com/surge-synthesizer/surge/pull/803
