### ISSUE TITLE
Ensemble modifies signal at 100% dry

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#4463]
Ensemble at 100% dry still modifies signal

problem seems to be where we do

```
 // reduce input by 3 dB
            dataL[s] *= 0.75f;
            dataR[s] *= 0.75f;

            // soft-clip input
            dataL[s] = lookup_waveshape(wst_soft, dataL[s] + fbStateL);
            dataR[s] = lookup_waveshape(wst_soft, dataR[s] + fbStateR);
```

which seems like it should probably be a copy (so wsDataL[s] = 0.75 * dataL[s]) to leave dataL unchanged for the final mix.

**Comment by mkruselj** [comment]
This one is on me, I should have been more careful. Fix incoming.
