### ISSUE TITLE
Menus don't invalidate their components

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#4487]
some do but not all
i fixed one of these (filter reset to default) but do a filter set to keytrack and see that you need to force a repaint

**Comment by baconpaul** [comment]
I bet if we just add 

https://docs.juce.com/master/classComponent.html#a7845e402a21d2b86d8c4ec48bc7c93b1

to a low enough point set to true we will be 100% of the way there. Probably something like where the CControl sets its juce buddy in evfg

**Comment by mkruselj** [comment]
Man, JUCE is just superbly thought out software...
