### ISSUE TITLE
LV2 disabled in pipeline

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#4488]
LV2 in azure pipeline started crashing in ttl generator. Don't know why but disabled it for time being.

**Comment by KottV** [comment]
I found that too.

the python generator seems to work https://github.com/lv2-porting-project/lv2-ttl-generator/blob/master/generate-lv2-ttl.py
and if i build `lv2_ttl_generator.c` locally it works too, but crahes with OBS builded version

**Comment by KottV** [comment]
ok
commenting this line `1380` did the trick:

`            set_source_files_properties(${JUCE_SOURCE_DIR}/extras/Build/lv2_ttl_generator/lv2_ttl_generator.c PROPERTIES LANGUAGE CXX)`
