### ISSUE TITLE
Future Feature: Make Reverb: Pre-Delay,Room Shape,Size modulation with SLFO possible

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#449]
Currently the SLFO does not allow for modulating the following Reverb EFX parameters

```
Pre-Delay
Room Shape
Size
```

(all the other EFX offer modulation possibilities with SLFO, just these ones in the reverb are not available).

<img width="914" alt="fullscreen_02_02_2019__10_18" src="https://user-images.githubusercontent.com/4966687/52161832-fa408c80-26d3-11e9-89e2-61de89c67c9b.png">

**Comment by baconpaul** [comment]
This is the same issue as #235 namely these are integer parameters. So closing this one and leaving that master integer param mod issue open with this linked.
