### ISSUE TITLE
SurgeXT/Linux crash when click on about 

### ISSUE THREAD

**Issue by mynameismuhl** [surge-synthesizer/surge#4495]
Linux 64bit
Vst3 and Standalone
After #4494 clicking on "About Surge" leads to segfault

gdb output of a Standalone Debug build at 4d2f58c6:
[aboutbox_crash.txt](https://github.com/surge-synthesizer/surge/files/6432122/aboutbox_crash.txt)

**Comment by baconpaul** [comment]
very useful thanks! will fix today

**Comment by baconpaul** [comment]
oh and it crashes all platforms - my fix to not leak gradients last night deals poorly with nullptr sets
