### ISSUE TITLE
Make 32-bit macOS AU,VST,VST3 buildable

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#450]
Objective: Find someone that is passionately interested in getting the 32-bit versions of Surge (AU,VST2,VST3?) building on macOS.

Maybe @asimilon would like to talk about older/previous versions of Xcode that are required to bake 32bit 

some stuff from @kzantow  and automated builds:

```
it's using Xcode 9 for Mac builds, so adding 32-bit VST 2 seems like a no-brainer
```

**Comment by baconpaul** [comment]
The kurasu comment is win only and is in master now
FYI

**Comment by kzantow** [comment]
@esaruoho I think this is working now; its just a matter of providing the installers #464 please reopen if incorrect

**Comment by esaruoho** [comment]
@kzantow windows 32-bit maybe, but surely not macos 64-bit??

**Comment by kzantow** [comment]
whoops misread this, sorry. yeah agreed to punt 32-bit macOS for now

**Comment by baconpaul** [comment]
I’m going to close this. We have literally never been asked for it; and it is more or less impossible with modern mac tools to test this. If someone comes along and wants to do it we can re-open it but I think macOS has successfully moved its user base into 64 bit land where that user base intersects with “try a free synth from the internet”
