### ISSUE TITLE
Surge Effects Bank 1.9.0 corrupt audio in FL Studio when not using fixed size full buffers

### ISSUE THREAD

**Issue by akx** [surge-synthesizer/surge#4518]
**Bug Description:**

When using Surge Effects Bank in FL Studio 20.8.3 on Windows, the audio is corrupt unless using the Compatibility > Use Fixed Size Buffers switch and the "Process Maximum Size Buffers" additional option.

Some other effects behave even more badly.

**Surge Version**
This information is found on the About screen, which you get to from the bottom right menu

* Version: 1.9.0.91069f8
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Add Surge Effects Bank to an effect track in FL Studio 20.8.3.
2. Play a sound.
3. Be horrified.

**Expected Behavior:**
1. No horrifiedness.

**Screenshots:**

See (rather hear) the blank video below. It has a single kick drum sample run through Surge FX Bank's delay with the compat options, then without. 

https://user-images.githubusercontent.com/58669/117497854-acd1ba80-af81-11eb-8fa0-0b6e5510d484.mp4

**Computer Information (please complete the following information):**
 - OS: Windows 10
 - Host: FL Studio
 - Version: 20.8.3

**Comment by mkruselj** [comment]
Known issue, FX bank requires buffers of 32 samples at all times.

**Comment by baconpaul** [comment]
Or multiples thereof

**Comment by akx** [comment]
For the time being, then, it might be a good idea for the plugin to warn if the host is using mal-sized buffers, because I was getting _very_ interesting noise otherwise?

**Comment by baconpaul** [comment]
The correct fix i think is to add and andvertise 32 samples of latency then let the daw sort it out.

https://docs.juce.com/master/classAudioProcessor.html#abae54a8c1bcfd88bcba9d42b752e006d

**Comment by akx** [comment]
Isn't that just advertising processing latency for e.g. compressors such that need lookahead?

**Comment by baconpaul** [comment]
yes so basically advertise the 32 blocks, use that latency to collect enough input to process, and process

the problem is : surge processes in blocks of 32. So the two options are fixed block sizes which are multiples of 32 or latency while we fill the input buffer.

**Comment by baconpaul** [comment]
So chatted with a few folks. Here's the state of play

1. Most DAWs don't send a block < 32
2. FL will
3. Logic in 'high resolution' mode will sometimes
4. DAWs deal poorly with switches in latency at play time

So the way to do this I think is

1. Have the FX bank have two options: Realtime but blocks gotta be > 32 or latent 32 and send me whatever
2. Make that a user switch stored in prefs and patches
3. Default to realtime except in the VST3 for fruity
4. If you switch it, you need to suspend and reactivate the plug to have the new latency scanned reliably
