### ISSUE TITLE
Provide an RPM package alongside .deb installer

### ISSUE THREAD

**Issue by gnac** [surge-synthesizer/surge#4524]
**Is your feature request related to a problem? Please describe.**
Surge provides a .deb package for Linux users. This is great, and savvy users can extract the deb package and manually install the files. However, many users will balk at this step and therefor not bothering to use Surge. Making an RPM available as part of the build process would open up the user base and provide a consistent mechanism of software installation to users of rpm supported  platforms, eg Fedora and OpenSuse.

**Describe the solution you'd like:**
An option to build an RPM package in the build system.

**Describe alternatives you've considered:**
Issue #1143 requests a .sh file. Ignoring potential binary incompatibilities, this would be cross platform solution, but still many users never leave the confines of their systems package manager.

**Additional context:**

**Comment by gnac** [comment]
related to #1143 1143

**Comment by baconpaul** [comment]
Great! We generally don't assign issues - our protocol is more folks hop onto an issue and self-volunteer with a quick 'got this' -  but happy to leave this one to you and sounds like a great add!

I'll need to make one pipeline change to upload the rpm also but if you just make it so the distribution target builds a deb and an rpm, it's a 5 char pipeline change once that's in.

**Comment by gnac** [comment]
> Great! We generally don't assign issues - our protocol is more folks hop onto an issue and self-volunteer with a quick 'got this' - but happy to leave this one to you and sounds like a great add!
> 
> I'll need to make one pipeline change to upload the rpm also but if you just make it so the distribution target builds a deb and an rpm, it's a 5 char pipeline change once that's in.

Ok, I'm preparing a checkin to my fork at the moment (cleaning things up). I'll put in a PR when its ready.

**Comment by baconpaul** [comment]
Super! I think this is your first pr yeah? If so please also add yourself to authors when you do! And look forward to it

**Comment by gnac** [comment]
PR #4525

**Comment by baconpaul** [comment]
All in the pipelines. Closing.
