### ISSUE TITLE
W32 builds need a distinct target

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#454]
Right now W32 and X64 both create target/vst2/Release/Surge.dll

Make it so that W32 changes the name so we can build all 4 dlls at once.

**Comment by esaruoho** [comment]
sounds awesome! nice :)

**Comment by esaruoho** [comment]
yeah, for sure, now that people are downloading automated builds that are actually 32-bit versions.. here's an interesting thing for ya @kzantow :)

**Comment by baconpaul** [comment]
Fixed with that PR
