### ISSUE TITLE
Change default zoom to NOT 100%

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#456]
I believe great majority of people are not running 1024x768 or similar monitor resolutions, so it might be very safe to assume that the default zoom level of 100% should not be considered the default anymore.

Over here, at 1920x1200, 150% zoom is perfection. 125% still looks a bit smallish, particularly some fonts are tiny and harder to read (but at least things are sharp!).

So my suggestion is twofold: first renaming the zoom levels. Maybe 125% could be the "new" 100%, 100% would be 75%, and then go from there. Second, detect monitor resolution when instantiating the plugin and pick the most comfortable zoom level for that resolution - there's already overzooming detection so that sounds to me like it would go hand in hand :)

Thanks!

**Comment by sense-amr** [comment]
already had a discussion about it with baconpaul .. when zoom was in its infancy .. i dont know THE TICKET .. where the conversation took place .. but its there.. i requested less than 100% it was said it isnt possible at the moment .. but for future enhancement

**Comment by esaruoho** [comment]
there's now a ticket for it. baconpaul pretty expressly said "separate issue" == that means that it should be made into a separate ticket, so it doesn't get lost.

anyway, here it is:
https://github.com/surge-synthesizer/surge/issues/458

**Comment by baconpaul** [comment]
Good idea

**Comment by baconpaul** [comment]
For a rather annoying technical reason which is annoying, this is annoying to implement. We should do it but it will be more involved than the set of other zoom cleanups I'm doing so will wait a little more.

(The annoying reason is: We want to do it early in the plugin construction phase but if we are too early we don't have a window and if we are too late then window will show up and visibly resize but we need a window to detect desktop size).

So not ignoring this one, just not getting it done this morning.

**Comment by baconpaul** [comment]
Oh and for my memory, here is the code I want to call once I figure out exactly the right moment

```
   /*
   ** Our default zoom factor used to be 100, but with our new vector graphics, 
   ** some folks thought 150 may be better. Making an editorial choice, 
   ** I'm going to choose the zoom factor which is the 25% percent tick
   ** which uses no more than 70% of the users screen as a default, floored at
   ** 100. 
   */
   int startingZoomFactor = findLargestFittingZoomBetween( 100, 150, 25, 70, WINDOW_SIZE_X, WINDOW_SIZE_Y );
   std::cout << "STARTING ZOOM IS " << startingZoomFactor << std::endl;
   setZoomFactor(startingZoomFactor);
```

**Comment by baconpaul** [comment]
OK so I'm going to sweep this one in with user defaults. With user defaults you get a menu option at any zoom you pick to "set ... as default zoom"

I think the right semantic is

1: Leave default zoom at 100% if you haven't made a choice
2: Let you make a choice which sticks forever

so if/when I sweep the commit above (9442b76 or subsequent fixes thereof) I'll close this issue.

All works on mac now. Need to test and maybe fix win and linux.
