### ISSUE TITLE
Money discussion ...

### ISSUE THREAD

**Issue by HackersCardgame** [surge-synthesizer/surge#4564]
Hello from Switzerland

your synth is great, and i would like to show my appreciation and send the project some money, do you have eg. paypal or an bank account where i could send the money to?

With kind regards

Marc jr. Landolt
eidg. dipl. Informatiker HF
Neuenburgerstrasse 6
5004 Aarau

Betreiber von http://hackerscardgame.ch

**Comment by mkruselj** [comment]
We don't require any money at all, but thank you for your intention. Perhaps donate to a local charity, instead? 🙂

**Comment by HackersCardgame** [comment]
![spende](https://user-images.githubusercontent.com/74041568/118853380-fd2b0f80-b8d3-11eb-880e-ba6786ab41a4.JPG)
as you wish master-troll :D and thank you again for this free VST3
