### ISSUE TITLE
Typo in installer_mac/make_installer.sh ?

### ISSUE THREAD

**Issue by JanosGit** [surge-synthesizer/surge#4573]
I came here from the JUCE forum as this repo was mentioned as a good example on how to build a plugin installer pkgbuild. Reading the script I found line 76 a bit suspicious

```
if [[ -d $INDIR/$AU ]]; then
    build_flavor "AU" "$AU" "com.surge-synth-team.surge-xt.component.pkg" "/Library/Audio/Plug-Ins/Components"fi
if [[ -d $INDIR/$FXAU ]]; then
    build_flavor "FXAU" "$FXAU" "com.surge-synth-team.surge-xt-fx.vst3.pkg" "/Library/Audio/Plug-Ins/Components"
```

Shouldn't that be `com.surge-synth-team.surge-xt-fx.component.pkg` instead of `vst3` ;) ?

**Comment by baconpaul** [comment]
It should! Thank you!

(I rewrote this all for XT so very much appreciate the typo). Will fix it today unless you want to happen to toss in a PR.

**Comment by baconpaul** [comment]
anyway merged a fix just now. ty!
