### ISSUE TITLE
Crash in Logic

### ISSUE THREAD

**Issue by Zoskiakultus** [surge-synthesizer/surge#4576]
**Bug Description:**

Hi.
I've been using Surge for a good while now, and it is my favourite synth of all, used exclusively in many of my projects.
Since the latest version though, I have experienced many crashes in Logic, and they just seem to happen randomly and I suddenly find myself staring at a blank desktop.

**Surge Version**

* Version:1.9.0.91069f8
* Plugin Type: AU
* Bitness: 64bit

**Reproduction Steps:**

No warnings or error messages.

**Expected Behavior:**

No crashes.

**Screenshots:**

Just a blank desktop.

**Computer Information (please complete the following information):**

 - OS: Macos El Capitan on a 2008 Mac Pro 2.8 Ghz Quad core
 - Host: Logic 
 - Version: 10.3.3

**Additional Information:**

Before this version, everything has worked pretty much perfectly, and I do appreciate the amount of work involved must be astronomical, especially when supporting so many OSs, versions, etc.
I have tried doing all the usual restarts, maintenance tasks etc, but to no avail.
I have been unable to find any relevant crash reports so far.
Some days I have hardly any problems.
Others (like today) are a bit of a nightmare, and I would like to continue to use this latest version rather than going back to a previous one as the new features are amazing and I enjoy the tweaking possibilities very much.
Thank you for all the work you have put into this amazing synth, which like I already mentioned, is my go to synth for everything I do.

All the best.

Steve.

**Comment by mkruselj** [comment]
A crashlog would be very velcome.

**Comment by baconpaul** [comment]
Yeah when Logic bites the dust there’s often an option to report the log
One other question - do you have a documents/surge directory and does your logic have permissions to read the documents directory? We changed our filesystem access in 1.9 and I am wondering if there’s an exception path with OS X file perms

I use surge 1.9 almost every day in logic 10.6 on OS X 10.15 without crashes but you aren’t the only person to see a sporadic crash

**Comment by Zoskiakultus** [comment]
Hi, and thanks for the quick replies:)
No. Nothing comes up when it crashes; just the desktop.
I looked in the Surge directory (I think), and all I could find was a file with all the default settings for Surge referring to skin colour, presets etc, but I doubt that was what you were referring to, and I'm too thick to know about anything deeper:))
As far as permissions go, I only know about the info panel, where all permissions (Myself, Admin, and everyone) are set to read and write, but once again, I highly doubt this is what you are referring to.
If and when it crashes again, I will look out for any crashlog info, and copy and paste it here.
Thanks again for all your help, and apologies for being unable to find the relevant information for you to analyse.
Cheers.

Steve:)

**Comment by baconpaul** [comment]
I just realized that’s a very old cpu. I wonder if we are running into an instruction your cpu doesn’t support in the sse code. I don’t know how to test that but it would do what you say (namely toh would hit a sigill and vanish)

lemme see if I can find if macos would log that somewhere

**Comment by mkruselj** [comment]
That Mac Pro has a Xeon E5462, which supports all forms of SSE up to 4.2...

**Comment by baconpaul** [comment]
yeah
but i wonder if we are using some os level thing since we build on 10.15 with a new mac.
probably not but ... 

Anyway @Zoskiakultus if you do Applications/Utillities you will see an app called "Console" which has a section called "CrashReports" - do you see a logic pro there? If so can you send us the whole log for that session?

**Comment by Zoskiakultus** [comment]
OK. Thanks.
I'll check it out:)

**Comment by Zoskiakultus** [comment]
I couldn't find the 'Crash reports' option, but I did find this, which may have the relevant info in there somewhere.
I do remember the crashes generally happened when I tried to open instances of Izotope Neutron Elements from the plugins in the mixer window, but I had no problems with that before the latest Surge update.
Maybe there's some compatibility issue with the Izotope plugin?
Anyway, here's what I found...

[Logic Pro X_2021-05-21-040821_Steves-Mac-Pro.crash.txt](https://github.com/surge-synthesizer/surge/files/6526885/Logic.Pro.X_2021-05-21-040821_Steves-Mac-Pro.crash.txt)

I had to convert it to txt format, as I was unable to paste the crash report directly.
Hope it isn't too much of a confusing mess. (It is to me me, but hey, what do I know?:))

**Comment by baconpaul** [comment]
Well that's exactly what we need. But unfortunately: None of those crashes are in surge. That shows that izotope is crashing on mouse down and the rest of the threads are doing standard logic stuff.

Do ou get crashes if you open izotope and *don't* open surge? And did surge 1.8 work as well for you?

**Comment by Zoskiakultus** [comment]
Firstly, Thanks for going to all this effort, and I'm glad it's not Surge that's the problem:)
Surge 1.8 worked fine: Maybe a couple of crashes here and there, but I don't expect computers to work perfectly 100% of the time anyway.
I got the izotope stuff via an offer on plugin boutique after having already decided to pretty much exclusively use Surge as my main synth, so I don't think I have used the izotope stuff without Surge.
The izotope plugins are replaceable, but Surge isn't, so it's a relief to me that it isn't the problem:)
My mac is pretty ancient anyway, so I do plan to upgrade when I get enough cash, but Apple are making customisation/upgrade options so difficult I'd still probably go for an older model that is newer than 2008 in the end.
I can't thank you enough for all the time and effort you've put into helping me solve this issue, and can only apologise for probably wasting a lot of your time which could have been put to better use elsewhere.
Thanks again.

Steve:)

**Comment by Zoskiakultus** [comment]
Thanks Evildragon too for your input:)

**Comment by baconpaul** [comment]
Well it still might be the two plugins interacting in some way. It might also be the age of the system. And it might be surge!

If you keep getting crashes attach a few more logs here and I am happy to look yeah?

We also have a new version coming together which fixes a lot of the infrastructure which made surge hard to develop. It's not ready for testing yet - still super alpha and crashy - but we hope to have a beta as the summer goes on.

**Comment by Zoskiakultus** [comment]
Thanks bud:)
I'll try whatever I can (Not much, unfortunately) to contribute to the further development of this amazing software:)
If you ever find yourself needing a coding illiterate bumpkin to test your stuff on an abacus, I'm your guy:))

All the best...

**Comment by baconpaul** [comment]
ha well robust testers who can send us crash logs are among the most valuable team members. if you want hop on our discord any time.

**Comment by Zoskiakultus** [comment]
Will do:)
