### ISSUE TITLE
XT Standalone No sound when Input set to none

### ISSUE THREAD

**Issue by mynameismuhl** [surge-synthesizer/surge#4580]
Linux 64Bit
9ce88da8

-In "Audio/Midi Settings" set Input to "none" in dropdown
 or uncheck Active Input Channels
-Pressing "Test" successfuly plays test tone
-In Surge click Latch: no sound and nothing on the VU
-Enable Input to get Sound

I am pretty sure it worked about a week ago
so it might be related to #4562
(or even expected?)

**Comment by baconpaul** [comment]
Oh thank you it is definitely related to #4562. I'll try and look this weekend.

**Comment by baconpaul** [comment]
Got it. Will merge when CI is done

**Comment by baconpaul** [comment]
Fixed at head. Thanks!
