### ISSUE TITLE
more keyboard shortcuts?

### ISSUE THREAD

**Issue by hems** [surge-synthesizer/surge#4607]
I love to press TAB to engage into "modulation" mode..

I wonder if it wouldn't be also cool to have other shortcuts such as:

 - `1` -> change OSC  panel to OSC 1
 - `2` -> change OSC  panel to OSC 2
 - `3` -> change OSC  panel to OSC 3
 - `shift + a` -> change to layer A
 - `shift + b` -> change to layer B

**Comment by mkruselj** [comment]
1/2/3 are not gonna happen because DAWs might be intercepting those.

Keyboard shortcuts in plugins are a huge problem because every DAW does things differently, there's zero consistency altogether. So it's better not to waste effort in this area.

**Comment by hems** [comment]
> Instead of pressing Tab, you know what works in every DAW? Pressing mousewheel. :)

didn't know that, but TAB always works for me, but then i just use ABLETON.

regarding the keys i didn't know it was such a mess. i'll close this then

**Comment by baconpaul** [comment]
yeah 1/2/3 change screen sets in logic shift-a does a select etc...

there is no good protocol for plugins to get a first-chance. it's really terrible actually and it's also not clear what we want (do you want space to start and stop transport when surge is focused? do you want surge to make that choice? etc...)
