### ISSUE TITLE
Win Installer should ship 32 and 64 bit

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#464]
With #463 done, the windows build now creates assets called

```
target\vst2\Release\Surge.dll
target\vst2\Release\Surge32.dll
target\vst3\Release\Surge.vst3
target\vst3\Release\Surge32.vst3
```

which means innosetup could ship all 4 dlls and allow a choice

I have no idea how innosetup works though. I can kinda guess what needs to happen from reading surge.iss but don't know how to test.

@kzantow do you understand this bit of kit at all?

At least by having that naming convention, the nightlies should return to shipping a 64 bit build by default.

**Comment by kzantow** [comment]
@baconpaul yeah, i did some tweaks to innosetup, I can probably sort this out. Based on discussion on Slack, there are some registry settings also to check for to determine default installation locations for VST plugins:
```
64-bit: Computer\HKEY_LOCAL_MACHINE\SOFTWARE\VST\VSTPluginsPath DWORD
32-bit: Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\VST\VSTPluginsPath DWORD
```

**Comment by baconpaul** [comment]
I don't know innosetup well enough to do that. But the assets are there and are even built in the azure pipeline so it really is just the final step of configuring and running and uploading that needs doing.

Agree we want a separate installer for 32.
