### ISSUE TITLE
anybody having issues using surge with a Wacom Tablet?

### ISSUE THREAD

**Issue by morerecords** [surge-synthesizer/surge#4645]
The mouse/cursor behaviour is wonky with pen tablet on Mac OS,

**Comment by baconpaul** [comment]
I have never used it with This configuration but there’s a set of options for touch devices which make the mouse reasonable (majes it exact and turns of cursor hiding) in the menu. I think we have the touch option on mac but if not set mouse speed to exact snd mouse hiding off (which is what touch mode is) and see if that helps?

**Comment by mkruselj** [comment]
I will remove the define for limiting touch mode to just Windows. Wacom tablets can also work on Mac and I bet Linux too.
