### ISSUE TITLE
Allow Dual mode MIDI configuration as option (defaulting to 1/2/3 to not break old sessions)

### ISSUE THREAD

**Issue by khr128** [surge-synthesizer/surge#4657]
macOS Big Sur 11.4. Surge 1.9. When I choose Dual mode, I expect both scenes to make sound, only the Scene A is audible, when I set gain for scene A to 0 and gain for scene B to the max, there is no sound.

**Comment by baconpaul** [comment]
Are you sending midi on channel 1?

In dual mode there is midi routing between the channels.

I just set up S1.9 in LPX 10.6 on macOS 11.4 and sent the following events to a dual mode surge. I got both / A / B over the section.

<img width="574" alt="Screen Shot 2021-06-09 at 9 47 57 AM" src="https://user-images.githubusercontent.com/13387561/121366852-ce6aec80-c907-11eb-9339-9c39df1651f5.png">

**Comment by khr128** [comment]
I am sending midi on channel 2 (from Arturia BeatStep Pro). Is there a way to change midi routing in dual mode so that both scenes are audible on midi channels other than 1?

**Comment by khr128** [comment]
OK, after reading the manual about midi routing in Dual mode, I understand that it is setup so that on channel 2 only Scene A is playing and on channel 3 only Scene B is playing. I did not know that and I was sending midi on ch2, got only Scene A by design (whether it is a good design is questionable IMHO).

**Comment by baconpaul** [comment]
I am not sure if it is an obvious design but, it is an ancient one. we can't change it without breaking projects.

We could however make it configurable per session defaulting to 1/2/3. If you think that's of interest reopen the issue and we can turn it into a feature request although wouldn't be top of stack.

**Comment by khr128** [comment]
Thank you for your assistance, Paul. It really helped me understand the issue. I do think the design is a bit quirky. It really should be a user configurable option. One can really see that it can be useful occasionally, but as a default setting it creates confusion. 

Yes, please make it a feature request, but I agree that it’s not urgent.

**Comment by mkruselj** [comment]
Let me see if I can hack this one in for 1.1.n, actually.

**Comment by baconpaul** [comment]
ok but be careful. that channel mask and mpe interact in uncertain ways. and it's not all in one spot. the easy fix may be incomplete so test quite a few scenarios just fyi.

**Comment by baconpaul** [comment]
oh you said 1.1.n. Oh yeah plenty of time for that :)

**Comment by baconpaul** [comment]
sorry i thought you said 1.1.0 :)
