### ISSUE TITLE
Error message when loading patch that exists both in factory and user data

### ISSUE THREAD

**Issue by selenologist** [surge-synthesizer/surge#4668]
**Bug Description:**
When a patch exists in both the user patch folder and the factory patch folder, e.g. my `Luna/Leads/96 Osc Supersaw` patch, attempting to load the patch from the user folder causes an error box to appear, then Surge behaves as the patch in the factory folder is loaded. A screenshot of the error box is attached.

**Surge Version**

* Version: Surge XT 1.0.main.7b8f5491
* Plugin Type: Standalone!
* Bitness: AMD 64-bit Linux GCC 11

**Reproduction Steps:**
Try to load one of my patches that shipped in 1.8 from my user folder.

**Expected Behavior:**
The patch loads as normal.

**Screenshots:**
![err box](https://user-images.githubusercontent.com/16075411/121709549-03e82380-cb1c-11eb-9070-8181f0fb3306.png)

**Comment by baconpaul** [comment]
FYI both the patch and category name need to collide for this to occur.

**Comment by baconpaul** [comment]
So even worse
if you quit XT with your user area one selected
then restart
you get your user area one shown
and the checkmark in the factory area

we need a more fulsome resolution *but* that requires us to put information into the patch. So fixing this one is actually tricky. Gotta ponder the right approach.
