### ISSUE TITLE
Surge 1.9 does not show its GUI in Reaper

### ISSUE THREAD

**Issue by redwood75** [surge-synthesizer/surge#4669]
**Bug Description:**
It is not possible to start Surge with the right GUI in Reaper. You can use the Reaper GUI of Surge with the different parameters and play sounds, but it is not possible to see Surges surface.

**Surge Version**
Latest version 1.9

* Version:
VST3, 64bit

**Reproduction Steps:**
1. Start Reaper
2. Start Surge
3. Surge will not appear with its GUI

**Comment by mkruselj** [comment]
Please add more info about your computer/OS, this is crucial.

Many people are using Surge just fine, so there's something weird happening here. Also - is this a fresh install or an update of an older version?

**Comment by redwood75** [comment]
It is Win 10, a laptop, I was long time satisfied with Surge - and the problem is completely new. I made an update.

**Comment by redwood75** [comment]
[
![surge](https://user-images.githubusercontent.com/85901599/121994237-35bfeb00-cda5-11eb-9e46-3765deb03a89.jpg)
![surge2](https://user-images.githubusercontent.com/85901599/121994243-36588180-cda5-11eb-8941-8cfe452e5339.jpg)

](url)

**Comment by redwood75** [comment]
Above, you can see the strange behavior. When clicking on "UI", the GUI changes from the lower image to the upper image (It is as some parts of the image on the right and low side vanish.

**Comment by mkruselj** [comment]
Looks like things didn't properly install. Do a full uninstall then reinstall, see what happens.

**Comment by redwood75** [comment]
I made an uninstall with CC Cleaner and then a reinstall. Same problem... I am wondering that no one else has this problem.

**Comment by mkruselj** [comment]
Yeah we have thousands of downloads and lots of people with Reaper use it just fine...

What was the previous Surge version you had installed?

**Comment by redwood75** [comment]
Not so easy... 
It still does not work.
That is what I did...
- Deleting the folders you described (only the AppDate-folders, I could not find).
- New install of Surge 1.9
- Uninstall of Surge
- Install of Surge 1.7.1 (which worked some time ago...)
- Deleting Reaper-Surge-presets
- Installing the newest Reaper version
- Starting a new reaper project to test if the actual reaper project has a problem

What else can I do? - For me, it seems to be a Surge-problem because other plugins work without problem. I made an upgrade of the driver of the graphic card in the past. Perhaps, this causes the problem? It is strange that I can choose and play Surge presets (as Reaper presets), and only the GUI of Surge is "wrong".

**Comment by mkruselj** [comment]
I'm a Reaper and Windows 10 user and Surge works perfectly fine over here, so it's unlikely that it's a Surge issue. 

I don't think the graphics driver update would mess it up, because Surge doesn't use hardware graphics accelleration (or if it does, it uses bog-standard Direct2D, which works even with just a potato)...

**Comment by redwood75** [comment]
No, the graphic driver was not the problem either.
I send you three more screenshots:
- Screenshot 1: Surge and Surge effect bank in a Reaper track, the effect bank is chosen (normal GUI)
- Screenshot 2: see Screenshot 1, but Surge chosen (GUI of Surge effect bank rests, but cut off)
- Screenshot 3: Surge loaded as VST3 into Bluecataudio patchwork, Surge GUI is blank

**Comment by redwood75** [comment]
![1 surge effect bank](https://user-images.githubusercontent.com/85901599/122159643-e6de8800-ce6e-11eb-859d-93f88738fedb.jpg)
![2 surge error](https://user-images.githubusercontent.com/85901599/122159645-e9d97880-ce6e-11eb-86d6-fbb85372b20c.jpg)
![3 patchwork-surge](https://user-images.githubusercontent.com/85901599/122159655-ecd46900-ce6e-11eb-9ac1-70a2e309644e.png)

**Comment by mkruselj** [comment]
I have no idea... We have plenty of Reaper users that have Surge working just fine...

**Comment by redwood75** [comment]
"Join our Discord server and we can try to arrange this."

I do not know this system. What do I have to do?
An alternative perhaps... Team Viewer?

**Comment by mkruselj** [comment]
Yes we would use Teamviewer, but I don't want to leave session IDs and passwords here on github. On Discord we can have a private chat.

You can join our Discord through this invite link: https://discord.com/invite/aFQDdMV

**Comment by mkruselj** [comment]
Found the issue through TeamViewer. Reaper had to be set to run on integrated Intel graphics rather than nVidia, and then it worked. It would probably also work on nVidia, but it'd require tweaking various per-application settings that it has.

Closing the issue!

**Comment by redwood75** [comment]
@mkruselj, you are a hero!
