### ISSUE TITLE
Royal skin missing from LV2 plugin?

### ISSUE THREAD

**Issue by heretoenhance** [surge-synthesizer/surge#4670]
**Bug Description:**
It is not a "bug" per se but I don't have the Royal skin.

**Surge Version**
1.9.0 from the Arch repos

* Version:
* Plugin Type: LV2
* Bitness: 64bit

**Reproduction Steps:**
1. Go to Menu -> Skin
2. There is no Royal skin

**Computer Information (please complete the following information):**
 - OS: Arch Linux
 - Host: Ardour 6.7

Sorry to bother you but I can't find it on github, do you release it only with precompiled binaries?

**Comment by mkruselj** [comment]
Arch guys may have removed that skin from the install because it adds 40 MB to download size. 

Either way you can get it from here: https://github.com/surge-synthesizer/surge-extra-content

**Comment by heretoenhance** [comment]
Thanks!

**Comment by baconpaul** [comment]
Also with ardour 6.7 you will get a much more reliable result with the 19 vst3 than lv2, FYI.
