### ISSUE TITLE
Step Sequencer Cursor Hiding (was LFO Laundry List)

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4697]
- [x] The below drag was not possible in VSTGUI version 🙂 
![image](https://user-images.githubusercontent.com/2393720/123864616-4175ea80-d92b-11eb-9d66-7074c37933e5.png)

- [x] The width of LFO display is wider than how it was before (top is XT, bottom is 1.9)
![image](https://user-images.githubusercontent.com/2393720/123864927-974a9280-d92b-11eb-9133-8f14b519d82a.png)

- [x] We need to show more units for super fast LFO times now. Beyond certain point labels disappear so any compass is lost
![lfo](https://user-images.githubusercontent.com/2393720/123865092-c8c35e00-d92b-11eb-841f-ade280122036.gif)

- [x] Some skin color is used for background color when it shouldn't have been
![image](https://user-images.githubusercontent.com/2393720/123865202-e8f31d00-d92b-11eb-9d2d-f2bbd6790d5d.png)

**Comment by baconpaul** [comment]
- [ ] Cursor Hiding isn't there in the step sequencer
- [ ] There was a menu on MSEG in the past which is missing

**Comment by mkruselj** [comment]
- [ ] Add more units for tempo synced ruler. Make sure beat 1 never disappears.

![lfo ts](https://user-images.githubusercontent.com/2393720/124320357-08808480-db7c-11eb-8779-f2707645746b.gif)
