### ISSUE TITLE
spectral morphing

### ISSUE THREAD

**Issue by mexanik619** [surge-synthesizer/surge#4706]
actually this is a **request ** not a issue 
can we have  spectral morphing or something like this on surge
a little change in GUI

**Comment by mkruselj** [comment]
Spectral morphing of what, exactly?

GUI updates are planned for next year.

**Comment by mexanik619** [comment]
spectral morphing of oscillators and fm modulations

**Comment by mexanik619** [comment]
i was suggesting a GUI update like Vital vst by matt tytel or something like that

**Comment by mkruselj** [comment]
I'm not exactly sure how that would work, if you're thinking about FFT, that would add latency so it's a no-go in an instrument plugin.

And we will most certainly not make Surge look like Vital. However the skin engine is there and you can try and make it yourself. :)

**Comment by mexanik619** [comment]
i know but not like vital but 
make similar to that can be more readable and usable to users

**Comment by mexanik619** [comment]
and as that i was telling of 3D view of morphing oscillators

**Comment by mexanik619** [comment]
but there is FFT in many other instrument vst you can get on current market

**Comment by mexanik619** [comment]
I am really tired of black screen issue in vital so thats y i was telling

**Comment by mkruselj** [comment]
We don't have anything spectral related in the next two [milestones](https://github.com/surge-synthesizer/surge/milestones).

**Comment by mexanik619** [comment]
What are the next milestones...?

**Comment by mkruselj** [comment]
Click the link above, everything is listed out. XT 1.0 is next to come, many deep architectural changes.

**Comment by ryukra** [comment]
> I'm not exactly sure how that would work, if you're thinking about FFT, that would add latency so it's a no-go in an instrument plugin.

You could cache the result and use it without latency maybe?

**Comment by mkruselj** [comment]
How would that work when the input is constantly changing?

FFT is inherently a latency inducing process, to the best of my knowledge (if I'm wrong in any way I will gladly accept that) , and this latency is longer the more FFT bins you have (and you need to have them a lot if you want things to have reasonable resolution).

**Comment by baconpaul** [comment]
So there's obviously no way to figure out the spectrum of a pattern from a single sample. So understanding a spectrum requires a set of samples, hence the latency in figuring out the spectral adjustment.

That's not insurmountable though. First of all many realtime / streaming algos use something other than FFT (there's forms of continuous DFT which keep sort of a rolling view) so you get a warmup cost. Or they just apply the spectral shift with a bit of latency even though the sound itself doesn't have latency. If you think about spectral operators in, say, a wavetable context you are restating the wavetable as your spectral operator and traversing it as your audio operator; the fact that you are latent in the second doesn't mean you have to be latent in the first it just means you have a 256 sample lag between the application of modulation and the modification of the spectral image or whatever (and you can improve this with overlaps and windows). So @mkruselj even though you are completely correct that an FFT requires a window and is thus latent, you can make practical compromises which make that latency acceptable, from looking at the literature.

The bigger thing that's not clear to me from this issue is, in a surge context, what's the spectral operator people want and where do you want it inserted? "spectral morphing" is a super generic term and so i'm unclear where you want to apply it. Is it, for instance, a standalone oscillator which has a modulatable spectrum based on tables? Or a sort of complex frequency shifter in the filter bank? so rather than worrying about details of latencies and so on, I'd suggest maybe trying to be a bit more precise about what changes you want to the spectrum, where, and how you want them specified?

**Comment by mexanik619** [comment]
Yeah, I requested this because I have seen in other vsts like phaseplant, serum or vital
All the famous ones that there is a 3d visualization of the waveform morphing or waveform changing
So I wanted in surge too .....

**Comment by mexanik619** [comment]
Cuz I wanted to make spectral morphing dubstep basses on surge
As vital requires higher opengl version to run that's y I wanted to make the basses in surge.

**Comment by mexanik619** [comment]
If surge would spectral morphing features 
I m literally sure that it would get famous.

**Comment by mexanik619** [comment]
Actually I wanted to ask you
One thing it's kinda personal
Since surge is open sourced and free of cost
How do u guys earn money from
@baconpaul and @mkruselj ???

**Comment by mkruselj** [comment]
We are not doing this for money.

You seem to be confusing waveform display with actual DSP processing method. It is not too difficult to add a 3D view for wavetable display.

**Comment by K0rrid0r** [comment]
@mexanik619 i think you need to be very much more specific and show some examples of what you look for sound wise think. 

Also surge is already a quite famous synth within the VST community, remember surge has existed for over 14+ years. People that work on this project have jobs on the side, this is a free time work and a passion project, we are all glad that there is no money involved, like really.

I also think you need to explore the synth more, you can already do things that sounds like spectral morphing and you can already do --incredibly-- complex 'dubstep' sounds (or whatever sounds you want for that matter).

Remember there is a lot of work and testing behind every fix, request and implementation in the codebase.

**Comment by baconpaul** [comment]
I'm still not sure what the actual request is

Is the request 'show the oscillator display for the wavetable oscillator in fake 3d'?
Or is the request add something to the dsp layer?
if so, what?

the wavetable oscillator now can do all sorts of changes to the spectrum of a wavetable and morph across frames and so on. So I really think some specificity here would help

**Comment by mexanik619** [comment]
Yeah I m also glad
Also I accept I'm not using surge to its full potential
I needed a 3d display of waveform changing.

**Comment by mexanik619** [comment]
Yeah I m also glad
Also I accept I'm not using surge to its full potential
I needed a 3d display of waveform changing.

**Comment by mexanik619** [comment]
Plus add some more basic wavetable
I see there are complex waveforms like
A sine+square wave or something like that
This create actually confusion for us who is starting in sound designing who watch from yt and try to do that in surge
I also want to add that there is not that much basses or other video regarding surge
So I try it watching serum or vital tutorials
Hope u understand ^w^  :)

**Comment by mexanik619** [comment]
And I'm really sorry that I m offending
UwU

**Comment by mexanik619** [comment]
U can add a 3d display of morphing wavetables
😊😊

**Comment by baconpaul** [comment]
> And I'm really sorry that I m offending
> UwU

You aren’t offending! We are just trying to figure out how to help you best :)

**Comment by baconpaul** [comment]
> Plus add some more basic wavetable
> I see there are complex waveforms like
> A sine+square wave or something like that
> This create actually confusion for us who is starting in sound designing who watch from yt and try to do that in surge
> I also want to add that there is not that much basses or other video regarding surge
> So I try it watching serum or vital tutorials
> Hope u understand ^w^ :)

Check out the “generated” section in the factory library which has the basic wavetables

**Comment by mexanik619** [comment]
Does it really 
I have checked there are some mixed wavetables...

**Comment by mexanik619** [comment]
Yeah I will check!!

**Comment by mexanik619** [comment]
I have a doubt the future surge xt will be different from this version right ??
Does it change the requirements of current surge
Cuz I have a very old laptop and I really can't afford little bit high requirement
Especially opengl requirements sucks alot
Literally it feels sad when the thing u want u have but u can get it because only u don't have requirements to get it.

**Comment by mkruselj** [comment]
OK so you just want a 3D wavetable display. We already have that filed as an issue (#3617), so I am going to close this one.

**Comment by baconpaul** [comment]
And funnily since you are asking for 3d graphics, we don’t plan to require ogl for the surge ui

**Comment by mexanik619** [comment]
Hey can u add hyperdimension and multiband compression

**Comment by mexanik619** [comment]
And a wavetable position Morpher or editor

**Comment by mkruselj** [comment]
Please don't put multiple different feature requests in an already closed issue. Also, before opening a new issue, please read existing issues that we have already - your feature request might already be filed.

**Comment by baconpaul** [comment]
Also the wavetable oscillator has a variety of morph and position parameters already

**Comment by mexanik619** [comment]
Sorry guys it was my mistake thank u for Ur help
