### ISSUE TITLE
Last chance doesn't work above widgets

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4708]
Middle mouse click above slider, multiswitch, osc display etc. doesn't toggle mod assign mode like it used to in 1.9.

**Comment by baconpaul** [comment]
> It’s also worth noting that if you add the parent as a mouse listener to the child and set setInterceptsMouseClicks(true, false) for the parent, MouseEvent::originalComponent will actually point to the child. To use your example:

```cpp
// whichever mouse callback(s) you need
void mouseDown(const MouseEvent &e)
{
    if (e.mods.isRightButtonDown())
        // handle right click
    else if (e.originalComponent != this)
        e.originalComponent->mouseDown(e);
}
```

from https://forum.juce.com/t/how-to-intercept-some-mouse-events-in-the-parent-component/32653/6 is the rough answer inside MainFrame. Probably. This one is trickier since mouse events don't cascade in juce like they do in VSTGUI

**Comment by baconpaul** [comment]
`baconpaul/last-chance-4708` got it started and @mkruselj can bring it home
