### ISSUE TITLE
Constant rate mode for portamento

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#472]
Currently, portamento in Surge always works in constant time, which means that no matter the distance between two notes, portamento time will always be the same.

I am favoring the constant rate portamento instead, which is going to result in longer portamento times the wider the interval between two notes is. I find it more musical while performing.

Would be nice to have this down the road sometime.

**Comment by adamski** [comment]
I think this should be an option, i.e. 2 portamento modes.

**Comment by mkruselj** [comment]
Yes, of course, an additional mode :)
