### ISSUE TITLE
Adding some more effect

### ISSUE THREAD

**Issue by mexanik619** [surge-synthesizer/surge#4721]
Hey,
I wanted to request to add more effects as follows:
1) a wavetable editor
2) a hyperdimension
3) corpus (if u can)
4) a multiband compressor
Thank u

**Comment by mexanik619** [comment]
Can I know by how much time this would take to add

**Comment by mkruselj** [comment]
Wavetable editor is not an effect.

We don't have any firm deadlines or timetables.

**Comment by mexanik619** [comment]
Oh I didn't new about that
Sorry bro

**Comment by mexanik619** [comment]
So can't u make corpus like effect
I also know the wavetable editor

**Comment by mexanik619** [comment]
So make a effect that is close to hyperdimension and corpus

**Comment by mexanik619** [comment]
OTT

**Comment by mexanik619** [comment]
I know wavetable is not an effect but I personally needed a feature to make custom wavetables
I also needed  a wavetable position Morpher or changer

**Comment by mkruselj** [comment]
Can you please EDIT your one single post instead of posting a barrage of single sentence or word posts? Please? We get notifications to all of these, and what you're doing is not considered polite.

As I have explained, we have our rough book of work written down in milestones, and they are more or less decided on what we'll do in the next year or so. 


As for wavetable editor, there are plenty of them out there that you can already use. Surge will read Serum wavetable format, among others.

**Comment by mexanik619** [comment]
Sorry UwU I didn't knew actually
^w^ 
I m really sorry
My internet is not good nowadays that's y I was sending u that much MSG's
This won't happen again
^=^✓

**Comment by mkruselj** [comment]
If you can send a new message, you can also edit an existing message. :)

![image](https://user-images.githubusercontent.com/2393720/124601406-1417c800-de68-11eb-8501-7e29ba3931c6.png)


This is how.

**Comment by mexanik619** [comment]
I have done it thanx

**Comment by mexanik619** [comment]
Actually I m also starting out in juce
Can u give me some tips
OwO UwU

**Comment by baconpaul** [comment]
> Actually I m also starting out in juce
> Can u give me some tips
> OwO UwU

1. Have something you want to do. Namely articulate a goal ("I want to implement a delay that does xyz")
2. use the latest juce and cmake
3. follow the tutorials carefully
4. set up your build pipeline so it is reliable

**Comment by mexanik619** [comment]
Can it done with python

**Comment by mkruselj** [comment]
Not for Surge, no.

**Comment by mexanik619** [comment]
Sorry sorry actually I also forgot that

**Comment by mexanik619** [comment]
And for surge which language should I use

**Comment by mkruselj** [comment]
You're again not editing your posts here...


Surge uses C++.

**Comment by mexanik619** [comment]
So which language should I use ??
C or C++

**Comment by mkruselj** [comment]
I think I was rather specific when I said what Surge uses. :)

**Comment by mexanik619** [comment]
So tell me which should I use
I really want to know...!¡¡¡!!!¡

**Comment by mkruselj** [comment]
I said what Surge uses above.

**Comment by mexanik619** [comment]
sorry like i said my internet is not good so thats y im not able to see ur latest comments

**Comment by mexanik619** [comment]
thanks fo ur help
Do u have yt channel or something
