### ISSUE TITLE
User WT/Presets columns still show even if they don't exist

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4735]
If we have any user content in user data folder, _except_ patches themselves, the patch browser still displays the User Patches column still shows, but is empty.

Same thing happens in wavetable list. In fact, if all I have in user content folder is a custom skin, I get this:

![image](https://user-images.githubusercontent.com/2393720/124969391-edec5680-e026-11eb-9e61-5302f4ddf6d5.png)

![image](https://user-images.githubusercontent.com/2393720/124969470-06f50780-e027-11eb-9a1d-2ebdd0b72b83.png)

And this is my user content folder:

![image](https://user-images.githubusercontent.com/2393720/124969501-12e0c980-e027-11eb-878e-7fb066def4cc.png)

**Comment by baconpaul** [comment]
Confirmed
