### ISSUE TITLE
Jumpy behavior when holding Shift while dragging a slider

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4738]
![shiftjumpy](https://user-images.githubusercontent.com/2393720/125164312-e3020500-e191-11eb-8899-fbb16b6b096b.gif)

Every time the slider jumps, I pressed Shift. This is not how it worked in 1.9 and before - it just slowed down the slider movement from current value, no jumps. Doesn't matter if cursor is hidden when dragging or not.

What could the cause be?

**Comment by baconpaul** [comment]
I wonder if I have a limit or a rounding wrong?
I would place a print/debug in notifyValueChange in the mixin and see what the getValue is
but it could also be (and I bet it is) that I set the value but not the quantized_value - the slider kinda has two values
Just guesses quickly on where I would start

**Comment by baconpaul** [comment]
ahh now i understand
this occurs if you press shift *within* a drag
gotcha
so start a drag and *while draggin* press and release the shift button
