### ISSUE TITLE
Probably run linux emit on each build

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#474]
@jsakkine I think we should run the linux emit on each build. Here's why

When resources change we need to emit

* mac: never. It just reads it from the bundle
* windows: When we add a file. We are just putting references in the .rc file and the .rc compiler makes the res based on the file system
* linux: when we change a file. If file sizes change then the offsets are wrong

This is why @falkTX and I don't see images with your current diff. Overnight I swept a new bunch of graphics from @itsmedavep and while windows and mac were fine, on linux we needed to re-emit. So at master if I run emit I get images.

So clearly we could re-run emit every time there's a new graphic (which we will forget to do)

But I vote that premake just emits a pre-build script run to update the files and put them somewhere outside of source control. Or even in source control and we check them in and don't care.

But anyway: if you want images now, rerun the emit script and check in the result :)

**Comment by jsakkine** [comment]
Will do it tomorrow. Just thinking. Could not @itsmedavep just run the script after updating images? I'm OK to adapt with either option.

**Comment by baconpaul** [comment]
He could sure or I could. But computers don’t forget! And my primary worry about windows (python not installed on dev machines) is not a prob on Linux so I think we save ourselves pain if we just run it

**Comment by jsakkine** [comment]
Should not be a problem. I'll patch it tomorrow.

**Comment by falkTX** [comment]
You can always setup a git-hook that runs the re-emit script before committing, so we do not forget about it again

**Comment by baconpaul** [comment]
That requires python on the designers machine the no? Trying to avoid that requirement if possible

**Comment by jsakkine** [comment]
Yes requires Python, but there is no Linux distribution that does not have it preinstalled.

**Comment by jsakkine** [comment]
I would make it part of the build. I do not like the hard dependency to the GIT infrastructure. PR coming ASAP.
