### ISSUE TITLE
Output Master Volume can´t be saved with the preset

### ISSUE THREAD

**Issue by cybpun** [surge-synthesizer/surge#475]
Output Master Volume can´t be saved with the preset.
With this fixed we have the possibility to level all the presets.

**Comment by baconpaul** [comment]
Thanks!

Linking to #391 since I have to do that one before this one

**Comment by baconpaul** [comment]
I may do this in 16 @esaruoho seems pretty important to patch leveling

**Comment by baconpaul** [comment]
So turns out this is a conscious choice in the code. I'm not quite sure why but because of that, I chose to not implement it with the 1.6.2 patch change. I'll keep this issue open and revisit with 1.6.3

**Comment by mkruselj** [comment]
@baconpaul let's do this, along with saving polyphony in patch, for 1.9?

**Comment by baconpaul** [comment]
Yup great

**Comment by baconpaul** [comment]
@mkruselj we did this yeah? Closing but reopen if I’m wrong

**Comment by mkruselj** [comment]
@baconpaul We didn't AFAIK, saved it for XT because of patch balancing considerations IIRC.

**Comment by baconpaul** [comment]
Oh right the reason I was confused is because the fix is the same as poly but we only fixed poly

**Comment by mkruselj** [comment]
Indeedio!
