### ISSUE TITLE
Enveloppes always restart to zero.

### ISSUE THREAD

**Issue by philnsicab** [surge-synthesizer/surge#4757]
**Is your feature request related to a problem? Please describe.**
We can't emulate analog enveloppes accurately because the enveloppe always restart to zero, whereas an analogue synth would restart the enveloppe where it was.
See this article :
https://www.soundonsound.com/techniques/synthesis-techniques-emulating-vintage-sounds

**Describe the solution you'd like:**
Adding an option to the play mode.

**Describe alternatives you've considered:**
A "Analog mode" option when right clicking on the attack of the amp and filter enveloppes?

**Additional context:**
Cheers !

**Comment by mkruselj** [comment]
We already have an issue for this. #824

Closing this as duplicate.
