### ISSUE TITLE
XT doesn't recall plugin state on project load in Reaper

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4759]
1, Open Reaper
2. Load Surge XT
3. Pick any patch
4. Save project and close it
5. Reopen project

What you get: Init Saw, instead of the patch you picked.

**Comment by baconpaul** [comment]
Quick q
If you set your default patch to something else does that pop up?

**Comment by mkruselj** [comment]
Yup!

**Comment by baconpaul** [comment]
Right. Damnit.

**Comment by baconpaul** [comment]
Anyway tbis one is too
Of my stack
To fix next

**Comment by baconpaul** [comment]
So interestingly there's three startup loads when I load reaper for me

1. The init patch
2. Overwwritten by the stored in song patch
3. Overwritten by some other random thing

I think 3 is coming from the VST3 preset mechanism but I am not sure. Debugging.

But it's not the init patch thing. 

I'll also check AU Logic.

**Comment by baconpaul** [comment]
yeah it's a mistake in the vst3 preset mechanism. Almost have it.

**Comment by baconpaul** [comment]
OK I have a fix and I am sure it is correct but I've onlytestyd it on mac.
I'll leave this open until we get confirm it fixes windows reaper also and I will test logic too.
but let me put the PR in.

**Comment by baconpaul** [comment]
Confirmed fixed windows reaper with that disabling.

**Comment by eliasdorneles** [comment]
Hello,

I have a similar problem with Surge XT LV2 plugin, on Reaper (on Linux, Ubuntu 22.04).

Steps:

1. Create a new Reaper project
2. Setup a track with Surge XT plugin, pick any patch (e.g. Bass 2), do not make any modification
3. Save project, close Reaper
4. Reopen reaper, reopen project

What you get: the plugin is loaded as if the patch is modified, the patch name has a `*` and the sound is different as well.

Screenshot on a brand-new project just opened:

![image](https://github.com/surge-synthesizer/surge/assets/37565/b0d5e61d-9e88-42f1-95b9-a7c3f26942be)

**Comment by eliasdorneles** [comment]
I've just tried now the VST3 plugin, and can't reproduce the bug with it -- so it seems it's indeed a problem in the LV2 plugin implementation.

**Comment by mkruselj** [comment]
Moving forward we will not be supporting LV2 anymore, just FYI.

**Comment by eliasdorneles** [comment]
ah ok, good to know
