### ISSUE TITLE
XT passes audio input instead of blocking it

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4766]
1.9 didn't do this. Try these steps:

1. Load XT on a track
2. Add an audio file on the same track
3. Hit play on transport

In 1.9 you would hear nothing until you pick the Audio In oscillator or use the vocoder. In XT you hear it straight away, and worse yet, once you **do** route it into Audio In, it doesn't kill the pass-through audio so you hear it twice. And there's no way to kill that dry signal.

**Comment by baconpaul** [comment]
https://forum.juce.com/t/question-on-vst3-bus-layout/47014

there's the juce forum discussion

this will almost definitely only impact reaper (remember we filed a reaper bug report on this behavior) but we do want it correct of course.

**Comment by baconpaul** [comment]
oh and for now you can work around it by routing audio from a separate track into the side chain etc... but that's not a fix.
