### ISSUE TITLE
Can’t resize Surge plugin window

### ISSUE THREAD

**Issue by alexjetmusic** [surge-synthesizer/surge#4787]
**Bug Description:**
When opening surge with logic pro x, the plugin window is on full zoom and i cannot resize it. Hence most of the bottom features of plugin is unaccessible

**Surge Version**
1.9.0

* Version:
* Plugin Type: macos Intel/ARM Universal AU and VST3
* Bitness: [32-bit or 64-bit]

**Reproduction Steps:**
1. Open logic pro x
2. Add new track
3. Change plugin to surge
4. Open surge

**Expected Behavior:**
Being able to resize the plugin window of Surge!

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following information):**
 - OS: MacOs, Big Sur, 11.2, macbook pro 13inch, M1, 2020, 16gb ram
 - Host: Logic Pro x
 - Version: 10.6.3

**Additional Information:**

**Comment by baconpaul** [comment]
Yeah this is a bug in M1 surge which I haven't been able to crack (I don't have an M1 mac yet). I think it will be fixed in our upcoming version but for now, as @mkruselj says, if you one time set your default zoom to something reasonable it should work. Please let us know if it does.

**Comment by mkruselj** [comment]
Since XT is gonna fix it, I'm closing the issue.
