### ISSUE TITLE
please PLEASE make it easier to install it on a different drive than your C drive

### ISSUE THREAD

**Issue by akakluci** [surge-synthesizer/surge#4804]
it's 2021, there are 0 reasons the installer should not have the option to install directly onto another drive. this process of it installing to a drive without asking you and then me having to dig for the files and attempt to put them on a different drive in a way that it'll actually work is so antiquated. I cannot even use the vst currently because it just wants the files to all be on my c drive and thats never gonna work for me,

**Comment by mkruselj** [comment]
We have discussed this a number of times. It's a VST3 thing.
