### ISSUE TITLE
Sub-sub-folders of presets are not sorted by A-Z

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#481]
I have a  `~/Documents/Surge/3rdparty/folders/presets.fxp` situation.
When I go to check out what's underneath `3rdparty` - the A-Z sorting is not accurate.

Here is a screenshot to illustrate.
<img width="477" alt="fullscreen_03_02_2019__19_11" src="https://user-images.githubusercontent.com/4966687/52179815-7ecfff80-27e7-11e9-9cad-4643941ae308.png">

expected: a-z is sorted a-z
current result: all over the place.

**Comment by esaruoho** [comment]
Also something strange about not being able to show a folder name with an actual space in it..? on patches_3rdparty

**Comment by esaruoho** [comment]
Okay something is definitely going awry here. I am deleting folders from `patches_3rdparty` and then restarting daw + VST2 and the folders do not vanish. i am deleting them from `/Library/Application Support/Surge` .. ok this is about this discrepancy and nothing else  :O

**Comment by esaruoho** [comment]
i'll re-fix/re-write this ticket later.. there should be no state where there's a ~/Library and /Library factory presets after installing with the macOS installer.

**Comment by baconpaul** [comment]
Oh right if categories have colliding names the sort will blow up. Can you rename ticket to that and then we can fix it?

**Comment by esaruoho** [comment]
clarified ticket :)

**Comment by baconpaul** [comment]
Yeah it's not your sorter. It's my menu maker.  I'll get it!

**Comment by baconpaul** [comment]
Fix is in. 
<img width="519" alt="screen shot 2019-02-03 at 3 32 24 pm" src="https://user-images.githubusercontent.com/13387561/52182255-6b15a080-27c9-11e9-9c42-7856007f6250.png">

**Comment by baconpaul** [comment]
Will merge once I get a quick review. Thanks for finding this!
