### ISSUE TITLE
Surge XT's "legacy" mouse behavior isn't the same as 1.9's.

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#4810]
Surge XT "Legacy" mouse behavior acts the same as "Exact" instead of "Slow" like in 1.9.

Running the latest version of FL Studio in Windows 10 in case that matters.

**Comment by baconpaul** [comment]
Yup 1.9 multiplied the moverate per item by the slow factor. Got a fix. Thanks. Nice catch.
