### ISSUE TITLE
Custom installation location???

### ISSUE THREAD

**Issue by YourStarling** [surge-synthesizer/surge#4817]
So confused. Am I missing something, or is there no way to install Surge anywhere other than the default, preselected folders? Why would the developers not allow you to install Surge on another drive or in a different folder? It's such a basic installation feature that I can't believe Surge has been out as long as it has without this being addressed.

**Comment by baconpaul** [comment]
Vst3 requires an install location in its spec. Some daws - notably fl - don’t allow you to customize or override this.

If your daw does you can configure after the fact per the manual
