### ISSUE TITLE
Linux "Open User Data/Patches..." puts backslash in filename

### ISSUE THREAD

**Issue by mynameismuhl** [surge-synthesizer/surge#4820]
With Linux "Open User Patches Folder" and "Open User Data Folder" 
currently looks for a folder called "Surge\ XT" which doesn't exist.
(meaning backslash being part of the name)
Load & save of Patch & preset works correct though.
probably/maybe related to #4736

**Comment by baconpaul** [comment]
Confirmed. Not solved but confirmed.

**Comment by baconpaul** [comment]
https://forum.juce.com/t/linux-spaces-in-path-startasprocess-and-process-opendocument/47296

Turns out this is a JUCE bug. I raised it in their forum.

**Comment by baconpaul** [comment]
If JUCE doesn't get to this before 6.1 I can also just do a #if linux xdg-open path in SurgeGUIUtils.cpp before release.
