### ISSUE TITLE
Deform in StepSequencer looks broken

### ISSUE THREAD

**Issue by mynameismuhl** [surge-synthesizer/surge#4821]
Linux 64bit
b0bb41cc925ad4eab231572e05d45f6ea2dc011c

I don't know since when, just saw this when comparing older patches
with rhythmic sequences that sounded off.

I made a simple example patch to demonstrate what i mean (with deform 25%):
[huiuiui.fxp.zip](https://github.com/surge-synthesizer/surge/files/6962177/huiuiui.fxp.zip)
which looks (and sounds) like this in 1.9
![19_stepseq](https://user-images.githubusercontent.com/80534683/128879761-e33791db-2532-435d-95fe-d6896f143655.png)
and like this in xt
![XT_stepseq](https://user-images.githubusercontent.com/80534683/128879823-95c014f4-9255-4fe9-82c9-cca50f67a9b2.png)

**Comment by baconpaul** [comment]
hmmm somewhat disconcertingly that patch loads the same way on mac with 1.9 and xt

that might mean there's some uninitialized memory somewhere though

i wonder if the shuffle extend is at fault perhaps?

@mkruselj when you get a chance can you try this patch windows with xt and 19? I'll look linux also when i next boot a vm.

but can't repro on mac so will require a bit of digging.

**Comment by baconpaul** [comment]
Huh well confirmed that it is broken on linux.

**Comment by baconpaul** [comment]
Confirmed also that backing down ea252d2cd42e fixes it. 
But again still not sure why

**Comment by baconpaul** [comment]
Got it

@mkruselj the arguments to `limit_range` are `x, low, high` not `low, high, x` :)

**Comment by mkruselj** [comment]
Whoopsie! 😅
