### ISSUE TITLE
Surge XT Font rendering issues for slider labels and routing bar on Windows

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#4856]
Surge XT on the left and 1.9 on the right.
![image](https://user-images.githubusercontent.com/50145178/129781129-9f917ed0-bcfc-437b-8a2b-ed21bb3a04eb.png)

I think that in 1.9 the font used on Windows changes from 130 something % zoom level to that clearer font on the right. However, it doesn't on XT, and it looks a bit more pixelated (and a bit harder to read to a certain extent).

We've discussed this over on Discord a couple of days ago. Here's the first message's link:
https://discord.com/channels/744319641211633774/744324663383031821/874758651448029215

**Comment by mkruselj** [comment]
Yeah JUCE font renderer is just different. It might be a live with it.

**Comment by baconpaul** [comment]
So now I know why I didn't see this

Here's mac XT v 1.9 side by side VSTGUI vs Juce at 150%

<img width="475" alt="Screen Shot 2021-08-17 at 9 29 08 PM" src="https://user-images.githubusercontent.com/13387561/129822072-b54a6bc3-46cc-4f37-8c8c-4265ae76c333.png">

**Comment by baconpaul** [comment]
XT dies look a smidge smaller though. When I copy "Sync" from XT over to 1.9 with preview and line up the lines I see this:

<img width="253" alt="Screen Shot 2021-08-17 at 9 31 53 PM" src="https://user-images.githubusercontent.com/13387561/129822255-3be559ef-ac53-4f49-aa18-ce9a11605df0.png">

So I wonder if "9pt lato" in vstgui uses a different size than "lato with px height 9" in juce. lemme noodle a bit.

**Comment by VincyZed** [comment]
@baconpaul So I tested with 9.5 as you requested, and at least on my side it makes 0 difference to the font size (I compared side-by-side screenshots and they're the exact same). I had to bump it to 10 to see the font increase, and now it's definitely a little too big imo:
![image](https://user-images.githubusercontent.com/50145178/129824232-1b0572d2-b06a-481e-86c0-cf5d44fdc8bd.png)

No difference between 10 to 10.5 either. Looks like it's integer only?

**Comment by baconpaul** [comment]
Huh wow ok so windows is definitely different than mac! I’ll look into what juce is doing 

thanks for trying

**Comment by baconpaul** [comment]
So in https://forum.juce.com/t/codeeditorcomponent-windows-linux-broken-6-0-8-6-1-including-in-projucer-and-demorunner/47565/19. 

Find out that system fonts on win use a D2D path and ttf do not

so one solution here is probably to

1: reinstate the Lato font install in the windows installer and
2: use that system font and render path if it is installed bu5 fall back to memory if not

Mac and Linux don’t have this bifurcated path

**Comment by mkruselj** [comment]
Doing `return juce::Font("Lato", size, style).withPointHeight(size);` in RuntimeFont.cpp yields this (JUCE right, VSTGUI left):

![image](https://user-images.githubusercontent.com/2393720/132229364-d7b17f5e-c96c-4e05-9347-c3208be4ee7c.png)

So we have the font drawing to match like that.

**Comment by baconpaul** [comment]
So the fix is

install lato in the windows installer
If you can use it from os, do so
If you can’t fall back to memory

**Comment by baconpaul** [comment]
got it. pr in.
