### ISSUE TITLE
Surge XT - Small white border around value popups

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#4857]
![image](https://user-images.githubusercontent.com/50145178/129782741-88aa8580-99fa-49e2-99a8-772e48769900.png)
We can see it over dark backgrounds. I've tried at different zoom levels from 100% onwards and I saw that it stopped doing this at 200% and up.

Here's 1.9 as comparison:
![image](https://user-images.githubusercontent.com/50145178/129783217-f74113b0-4d76-45a7-aee3-420fcc569f2a.png)

I don't know if this just happens on Windows and on certain screen resolutions. I guess some testing on other configs (like other resolutions) would be beneficial here?

**Comment by baconpaul** [comment]
oh huh that looks like an int -> float quantization error. I can paint that differently though to avoid that
thank you!
