### ISSUE TITLE
XT - Drag-and-drop of mod sources behavior and appearance issues

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#4858]
![image](https://user-images.githubusercontent.com/50145178/129785742-59e5afd8-8fcc-4589-ae94-7d2b7c8c4e11.png)

So basically a couple of things have changed since 1.9:
1. You can drag and drop mod sources without pressing Ctrl. (I think that this is a good change FWIW)
2. However drag and dropping mod sources over sliders to bring up the mod amount numerical input window doesn't work, and doesn't work while holding Ctrl either.
3. When dragging a mod source, instead of making a visual copy of the blue rectangle, it moves it, creating a hole at its original position in the routing bar.
4. When dragging over sliders, the mod rectangle is drawn **below** sliders, where it should be drawn over them.
5. This wasn't there in 1.9 either, but it would be nice if elements that can be modulated showed either the hover state, or even better the corresponding blue slider appearing when hovering over an element. Then when dropping, show the popup value as usual.

**Comment by baconpaul** [comment]
oh yeah that's broken
fwiw the macros do swap if you drag and drop between them though. At least that handler works :)

**Comment by baconpaul** [comment]
an accessibility change i made to group components broke this. i have it fixed now. PR shortly.
