### ISSUE TITLE
Piano keys to the bottom of Surge

### ISSUE THREAD

**Issue by jsakkine** [surge-synthesizer/surge#486]
Would be really nice to have for testing (especially on Linux where we still mostly use Carla) piano keys in the bottom of the UI, maybe with a show/hide button. Does VSTGUI have something of-the-shelf for this?

**Comment by baconpaul** [comment]
I almost did this on Mac also but then just made midi routing work in the hosts and uses someone else’s keyboard

Afaics there is no such widget

A much easier thing is to add some special keystrokes which put you in midi keyboard mode. So press CTRL alt x r 17 or something and then a sends an a note

But Carla should have a routing screen keyboard available no? May be easier!

**Comment by jsakkine** [comment]
Ping @falkTX (again) :)

**Comment by jsakkine** [comment]
@baconpaul, I believe you, but feels that such isn't in the default stock of widgets.

**Comment by falkTX** [comment]
I have almost no experience with vstgui, cant help much here.
you can use carla on mac and windows though, which provides the keyboard widget thing playable with pc keys :)

**Comment by baconpaul** [comment]
Yup; bitwig does it with caps lock too on all platforms; and hosting AU has keyboard input as does logic on mac. So I think you and I are saying the same thing, @falkTX which is it is better to get running in one host and then use the host to route midi than to kill ourselves adding a keyboard.

**Comment by baconpaul** [comment]
@falkTX does “Carla-single” have a way to generate midi into the plugin? That would completely solve the problem for @jsakkine. (That’s basically what I use hosting AU for on mac; a super lightweight AU host which can route audio and so on and starts in a second, not in 14 seconds like full blown logic)

**Comment by falkTX** [comment]
> @falkTX does “Carla-single” have a way to generate midi into the plugin? That would completely solve the problem for @jsakkine.

carla-single plugs into JACK in a modular way, exposing midi and audio ports. so you can use then `jack-keyboard` to feed midi into it.

regarding juce: since this is already cross-platform, there is no need for bloating the code with juce stuff.
also, I got surge to build with my own tiny framework (DPF), this is how I made the first advances regarding the event loop. but for now getting the VST2 version out is already awesome.

**Comment by jsakkine** [comment]
@baconpaul, Yes, this was not really proposal to use Qt right now. This was more like explanation why JUCE would be a bad choice at any point :) I could do a PR and derive something based on that text directly to our developer documentation. It is a design choice that should be documented.

If someone puts issue suggesting JUCE we can point them to the documentation.

**Comment by baconpaul** [comment]
Ok so how about we write up a short readme section on using Carla single and jack keyboard configured to play notes and then close this issue?

Cool!

**Comment by baconpaul** [comment]
Sounds good. I like documentation

What would be great is documentation on “here’s the Carla and jack commands which pop up surge and a keyboard and lets you make noise” tho. Honestly as a Linux desktop noob I could use that!

**Comment by falkTX** [comment]
See repos at http://kxstudio.linuxaudio.org/Repositories
(requires gcc5 too, but I will remove the need for this very soon)

When done, install `carla-git`

```
# terminal 1
carla-single vst /path/to/surge.so
# terminal 2
jack_connect Surge:output_1 system:playback_2
jack_connect Surge:output_2 system:playback_2
jack-keyboard
```

**Comment by falkTX** [comment]
jack commands are tricky, depends on the hw you have...

**Comment by baconpaul** [comment]
Thanks!

**Comment by baconpaul** [comment]
OK so I just dropped the latest surge.so into the carla patchbay and wired it up to the output and pressed the keyboard and got sound in my ubuntu vm.

So I really don't think we need to add this, @jsakkine - we can use external tools and keep the code much simpler.

Mind if we close it?

**Comment by jsakkine** [comment]
Please re-open it just so that I remember do to README.md update.  That analysis about JUCE is worth of documenting.

**Comment by jsakkine** [comment]
I will close it after doing a PR.

**Comment by jsakkine** [comment]
Getting this done tomorrow. Busy week at work.

**Comment by jsakkine** [comment]
Check #564.
