### ISSUE TITLE
Why does get_extended modify val_max and val_default and stuff

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#4861]
I was about to make this const and realized it isn't
Why on earth isn't it?

**Comment by baconpaul** [comment]
this in turn means get_display can't be const and so on.

**Comment by mkruselj** [comment]
Because some params need to have different default values in extended mode only (i. e. certain params going from unipolar to bipolar etc.).

Any other way to deal with this?

**Comment by baconpaul** [comment]
yeah the answer is to make a set_extend_range() which is non const and call it consistently and do the change there. On it.

**Comment by baconpaul** [comment]
(the reason you want things marked const correctly is so this would fail to build when we made the change, btw; its why #3808 is important).
