### ISSUE TITLE
Sticky hover states

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4874]
When opening a context menu by right-clicking a modbutton, then right-clicking another modbutton without closing the menu, etc, we get this:

![image](https://user-images.githubusercontent.com/2393720/130230667-5d7dd21d-d93a-4219-9db2-9efac7115460.png)

Similar thing happens when clicking on A/B boxes in FX grid - hover state is frozen if clicking away the context menu to close it:

![image](https://user-images.githubusercontent.com/2393720/130230736-b75a3c16-2266-475c-8c57-42d5ec7dae46.png)

**Comment by baconpaul** [comment]
totally different reason for them happening but see why
effect is i forgot to unhover
grid is more hacktastic but i have a fix i think

**Comment by VincyZed** [comment]
Here's one more case where this is present: 

![Sticky mod](https://user-images.githubusercontent.com/50145178/133856234-25229055-1119-43fc-b420-a19caeb768da.gif)
:

Only happens with sources that have a Hamburger menu.
