### ISSUE TITLE
XT: Step Sequencer and other Modulation editor graphical bugs

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#4877]
Here are some UI glitches I found using the Step Sequencer mod source (and in some cases other mod sources) in XT so far:

(@baconpaul: I edited this into a checklist)

- [ ] Click + dragging allows you to drag outside of the SS boundaries (it will move the LFO shape if you continue dragging to the left of the SS, for instance). 
- [x] The mouse pointer doesn't update to the pointed finger when hovering over the MSEG display like it does in 1.9 to indicate you can click on it. This also applies to the formula modulator.

Hope that helps! :) I may add more stuff below if I find more.

**Comment by baconpaul** [comment]
super useful thank you
