### ISSUE TITLE
Surge Menu could have a button that opens the user folder on OS file browser

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#488]
as suggested by `EvilDragon` at https://surgesynth.slack.com/archives/CF6NVE4RW/p1549216822192300 - 

It would be really useful to give the user a button in the Menu that opens the user documents folder of Surge, and another for factory folder (in case wavetables have not been integrated into `~/Documents/Surge` by the time that button starts existing.

**Comment by baconpaul** [comment]
Oh that’s a really good idea!! I like it a lot.

**Comment by baconpaul** [comment]
(I have no idea how to do it on Linux!)

**Comment by baconpaul** [comment]
Here's how I would do this:

* read https://github.com/surge-synthesizer/surge/blob/master/doc/git-howto.md and https://github.com/surge-synthesizer/surge/blob/master/doc/developer.md
* make a branch
* to src/common/UserInteractions add a function `void openPathOnDesktop(const std::string &path)`
* in each of src/mac src/windows src/linux and src/headless/UserInteractionsBlah.cpp implement it
    * windows is probably `ShellExecute(NULL, NULL, path, NULL, NULL,  SW_SHOWNORMAL);`
    * mac is probably `system( "open " + path )`
    * lin is probably `system( "xterm -e \"cd " + path + " && /bin/bash\"" )`
    * headless is a no op
* In `src/common/gui/SurgeGUIEditor.cpp` at the end there's a showSettingsMenu function. You'll see where About and Manual menu items are added
* Add similar menu items which call your new function
    * one called "Open User Patch Folder" with path variable userDataPath from SurgeStorage
    * one called "Open Factory Patch Folder" with path variable dataPath from same
    * those variable names are from memory - check em!
* build, test, cleanup
* make a PR and let us know!

**Comment by baconpaul** [comment]
Oh and while we are at it let’s put these paths into the about screen text (GUI/cabout.cpp)

**Comment by esaruoho** [comment]
@baconpaul would they be clickable urls?-)

**Comment by baconpaul** [comment]
Clickable about screen is a mild pain - for now I would say just show em

**Comment by baconpaul** [comment]
On linux, you want to do `"xdg-open file://" + storage->userDataPath`

**Comment by itsmedavep** [comment]
Well, I suppose I could take a stab at this one. It might take a minute to get there. I  might get cycle this weekend. If I do Ill let you know I've started on it.

**Comment by baconpaul** [comment]
I started putting it together in one of my dev areas Dave. Was gonna do it along with user wavetables and 3rd party wavetables. But happy either way. The issue is easy but I realized you need a dev env on all 3 oses to test it alas.

**Comment by itsmedavep** [comment]
I don’t have three environments to test unfortunately.  I’ll pass one I suppose. 


I’ll cruise the other issues for low hanging fruit!
