### ISSUE TITLE
Modulator index adjacent bugs in mod grid

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#4884]
[ macro name fixed ]

**Comment by mkruselj** [comment]
There's also this that might be related:

![wut](https://user-images.githubusercontent.com/2393720/130598479-9994f0ba-51cc-4ceb-9ab3-2607e7155912.gif)

**Comment by baconpaul** [comment]
Oh I bet it is the internal state variable

**Comment by baconpaul** [comment]
Here's the bug
if you are on an alternate mod source (So the Unis) the green doesn't stick
If you are just on an alternate index (so the distro) of the first mod source (the bis) it does

**Comment by baconpaul** [comment]
The problem is the loop in ::refresh_mod incorrectly assumes 1:1 from mod source to gui_modsource[i] after I rewrote the alternates.
