### ISSUE TITLE
Add a menu to swap send/return index

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#4888]
With the closing of #2446 I left the code in a state where moving around the FX send grid will change the FX send sliders for you.

We want to have a menu to decouple those on the slider, but it is fiddly, so I left it out of the commit that added it and instead added an issue to the pile.

**Comment by baconpaul** [comment]
Or: Maybe don't. @mkruselj and i want to play with it a bit first.

**Comment by mkruselj** [comment]
@baconpaul I'm playing with it and I think the answer is "we don't need the menu option after all".

**Comment by baconpaul** [comment]
I’m glad you think that. I agree.
