### ISSUE TITLE
Context menu with modulator alternates/index not just on the burger

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4902]
We used to have a right-click context menu that listed all alternates. That doesn't seem to be working anymore, since mousewheel on hamburger'd modbuttons happened (or maybe since index mods happened).

**Comment by baconpaul** [comment]
Click on the hamburger

**Comment by baconpaul** [comment]
OK so here's what we actually need to do

- [ ] Add the hover dismiss to the hamburger menu
- [ ] add the alternates to the main RMB also

**Comment by mkruselj** [comment]
Right.

Can just show the whole modbutton menu with alts on RMB across the whole modbutton, and on LMB on the burger.

**Comment by baconpaul** [comment]
yes
