### ISSUE TITLE
XT regression: no tuning loaded, LMB on Tune button doesn't open context menu

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4909]
This is how it worked in 1.9 so we should retain that behavior, of course!

**Comment by baconpaul** [comment]
Oh I just never call "setUnValueClickable" on the tune button after I refactored.

**Comment by baconpaul** [comment]
Oh and now I see why. That data structure is a mess. Need a new variable to not carry over the spaghetti from 1.9 to XT. A bit more work here than I thought - will leave it for another day. Good catch.
