### ISSUE TITLE
Opening patches you have saved in Logic library crashes the app

### ISSUE THREAD

**Issue by LelleOstman** [surge-synthesizer/surge#4913]
When I try to open my own patches from the Logic Pro library The whole of Logic crashes when I select a patch and open Surge. I have not saved the patches inside of Surge but have used the Logic menu inside the plug in window.

Surge version 1.9.0.91069f8 Au on intel Core i7 - 4870HQ 64 bit

 - macOS Big Sur 11.5.2
 - Host: Logic Pro 10.6.3

**Comment by baconpaul** [comment]
That is very useful
What I think is happening is the daw zoom state is getting saved as a logic patch and our restore of that is coming before the editor is set up, I see the 19 code path that could crash after set zoom
For our next release we’ve rewritten this entire code path so I gotta think about what to do. We don’t plan to patch 1.9 and none of this crashing code is in the codebase any more. 
thank you very much for the crash log,

**Comment by LelleOstman** [comment]
Glad I could be of help. I'll just use the internal Surge library until the next version comes out. Thanks for an incredible synth. It will be heavy featured on my new album 😀

Lennart Östman

**Comment by baconpaul** [comment]
Oh excellent! When you release your album let us know.
I'm going to make sure this doesn't happen with our new release a couple of times, and if it doesn't i'll close this once we are in beta. Will let you know by posting to this issue. Sept or Oct. Thanks!

**Comment by LelleOstman** [comment]
Will do!

**Comment by mkruselj** [comment]
@LelleOstman Can you perhaps try if this issue happens in Surge XT nightly? It's a separate install so your Surge 1.9 installation won't be affected. You can download it [here](https://surge-synthesizer.github.io/nightly_XT).

**Comment by baconpaul** [comment]
Oh I was gonna test this this week @mkruselj - if it does break I can catch it in a debugger and I could repro in 19

**Comment by LelleOstman** [comment]
The XT build works. It does not crash when loading saved patches from the Logic library.

Lennart

**Comment by mkruselj** [comment]
That's great to hear! It means we can close this issue (1.9 codepath will not be updated anymore).

Thanks for the report back!

**Comment by baconpaul** [comment]
Yes thanks!,

**Comment by LelleOstman** [comment]
One more question though. The nightly build is not compatible with the sounds I saved in the ordinary version. When the new version arrives will it be able to play my old pathches? If not will it be able to play the patches I made in the nightly build?

**Comment by baconpaul** [comment]
All your old patches will work in XT, but it will have a different id so you will need to move them over to your new directories

**Comment by baconpaul** [comment]
(We will provide documentation and perhaps tooling on how to do this closer to final release)

**Comment by mkruselj** [comment]
I think Lelle asks about his 1.9 Logic saved patches. Yeah those will not convert to XT - you will have to save them using Surge's patch storing mechanism, then load them into XT, then save them again using Logic's saving facilities.

**Comment by LelleOstman** [comment]
Thanks! I suspected that. Can I continue using the XT nightly build or is it time restricted?

**Comment by baconpaul** [comment]
you can continue using it. none of our software is time restricted
but you probably want to update it fairly recently. We keep adding and fixing things and it is still a bit alpha-y

**Comment by baconpaul** [comment]
fairly frequently sorry

**Comment by LelleOstman** [comment]
Sorry to bother you again. I was wondering if there is any Surge XT compatible skins to download somewhere?

All the best
Lennart

**Comment by baconpaul** [comment]
If you run a recent surge xt you can do menu / skins library and it will take you to a collection we are starting to curate ahead of our 1.0 release

**Comment by baconpaul** [comment]
You need an xt from the last 5 days or so for that tho
