### ISSUE TITLE
Hosts on Linux: Several hosts failing on VST2; all failing VST3

### ISSUE THREAD

**Issue by jsakkine** [surge-synthesizer/surge#492]
I'm able to successfully load the VST2 plugin in Renoise, but neither VST2 nor VST3 loads in Bitwig.

**Comment by baconpaul** [comment]
Os?

**Comment by baconpaul** [comment]
So Tractkion 7 and Carla both work Ubuntu 18.04

Bitwig also does not work for me.

```
paul@ubuntu:~/surge$ /opt/bitwig-studio/bin/BitwigPluginHost64 test ~/.vst/Surge.so 


--------------------------------------------------------------------

Testing plugin /home/paul/.vst/Surge.so
About to start the following process:  /opt/bitwig-studio/bin/BitwigPluginHost64 host 44100 256 15810-1 1
Successfully set thread realtime priority to 19
Creating plug-in instance
Waiting for reply...
Could not test plug-in: createAEffectInstance returned NULL.
Lost connection on audio thread: End of stream
Passed plugins:



Failed plugins:

    /home/paul/.vst/Surge.so:      createAEffectInstance returned NULL.


Passed : 0 Failed: 1
```

I had debugged this earlier before I found the XML thing and didn't get very far. But there's a standalone to try and understand. There's no way  can see that createAEffectInstance would return null though (it is implemented as `return &cEffect;`) without there being a memory error somewhere in the dll.

**Comment by jsakkine** [comment]
@baconpaul, Ubuntu 18.10

**Comment by tank-trax** [comment]
I use Debian Stretch w/KDE plasma as DE.

I have managed to build the VST2, VST3 and standalone. The standalone is non-operational. If I try running ./Surge from the command line it does not return any errors and no process starts.

The VST3 is not recognized by any DAW or Host

The VST2 however is recognized and is functional in Reaper, Waveform 9, Tracktion 7, Mixbus 5, Radium and Carla. It shows up in Ardour but for some reason the MIDI Out cannot capture any Audio Output. There's a pulse but no beat. Odd because it does work well in Mixbus. It is recognized by Qtractor but crashes immediately upon loading.

**Comment by tank-trax** [comment]
To add...

The VST2 is not recognized by Renoise

Both the VST2 and VST3 are recognized by Bitwig but they return this error and can't be loaded (it appears to be a generic error as all failed plugins return the same):

```
com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Could not read VST plug-in metadata
64 bit plugin host reported errors: Pluginhost returned non zero exit code 255

32 bit plugin host reported errors: Pluginhost returned non zero exit code 255
```

**Comment by baconpaul** [comment]
@tank-trax thanks.

I have fixed (or more accurately "fixed") the problem with the app with this PR I will sweep in 5 minutes when the auto builds are done https://github.com/surge-synthesizer/surge/pull/516. It makes the app at least print out that it isn't supposed to work. Sorry about that confusion!

Most importantly: thank you for the exhaustive set of hosts on which you have tested. That's great. Did QTractor report any error or did it just poof and segfault?

That bitwig experience is the same one we had yes. The plugin host seems to get confused about some feature of the vst2 which we don't understand yet.

**Comment by tank-trax** [comment]
when it scans the VST it returns this...

```
Surge Error
Software Error
getScreenDimensions not implemented yet on linux. Returning 1400x1050
Surge Error
Software Error
getDisplayBackingScaleFactor not implemented yet on linux.
Surge Error
Software Error
getScreenDimensions not implemented yet on linux. Returning 1400x1050
Surge Error
Software Error
getDisplayBackingScaleFactor not implemented yet on linux.

```
When I load the VST this is the output from the crash.

[qtractor.surge.errs.txt](https://github.com/surge-synthesizer/surge/files/2834530/qtractor.surge.errs.txt)

**Comment by baconpaul** [comment]
Right; those shouldn’t matter; it is returning a reasonablish default in those cases but I agree the message is alarming.

That stack trace though is super useful mostly because *none* of it is in surge. That sort of supports a theory that the mysterious bitwig error also made me think that something is going wrong in memory when VST is bootstrapped (that createAEffect being null is really hard to figure out) and that memory error is splatting something else.

Thank you. This is all very useful.

**Comment by baconpaul** [comment]
So @falkTX saw the magic to make it all work with bitwig VST2 on Linux

but the nature of the problem actually makes me think that it may solve some other hosts also on linux

We should try the ones which we think are broken.

Especially interested if qtractor now works

**Comment by baconpaul** [comment]
Need to build from top of master to get the fix tho. Include this b4eea62eff4459d25df68ea98fc307a93cbc6cfe commit at least

**Comment by khusseini** [comment]
I tried the latest nightly build on Debian Stretch and also getting this error on bitwig 2.4

**Comment by falkTX** [comment]
VST3 version is known to be broken on Linux, don't use that.
The VST2 should work

**Comment by baconpaul** [comment]
I didn't think the linux .deb files contained the VST3 at all. Looking at make_deb.sh there's no VST included. If you build it yourself you get one indeed but as @falkTX says, it doesn't work (which is why we don't ship it in the .deb files in beta7 or the nightlies).

**Comment by baconpaul** [comment]
Oh and if you build it yourself, you need the VST2 SDK if you want to build a VST2. Without that, the VST2 will not be installed.

**Comment by khusseini** [comment]
Is there an estimation when VST3 will be available for Linux? I can't find the VST 2 SDK as it has been discontinued by Steinberg

**Comment by baconpaul** [comment]
No. The primary problem is we need to figure out how to run an event loop. The rest of the code will work I think and in fact it partly loads. Happy to review a pull req if you also that!

The binary release has the vst2 in it if you want to try the synth.

**Comment by khusseini** [comment]
I just installed the nightly build (Surge-linux-x64-NIGHTLY-2019-03-17-be47bbc.deb) again after removing the other version. Now it is shown as VST2 (guess I had a caching issue in Bitwig). However the metadata error is still popping up 

```
com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Could not read VST plug-in metadata
64 bit plugin host reported errors: Pluginhost returned non zero exit code 255

32 bit plugin host reported errors: Pluginhost returned non zero exit code 255
```

Traktion 7 also throws an error when I scan for plugins

**Comment by khusseini** [comment]
I just ran the bitwig host test. Seems I got some libs missing in my system 

```
/opt/bitwig-studio/bin/BitwigPluginHost64 test /usr/lib/vst/Surge.so 


--------------------------------------------------------------------

Testing plugin /usr/lib/vst/Surge.so
About to start the following process:  /opt/bitwig-studio/bin/BitwigPluginHost64 host 44100 256 11457-1 1
Successfully set thread realtime priority to 19
Creating plug-in instance
Waiting for reply...
Could not test plug-in: Failed to load VST plug-in /usr/lib/vst/Surge.so: libxcb-util.so.1: cannot open shared object file: No such file or directory
Lost connection on audio thread: End of stream
Passed plugins:



Failed plugins:

    /usr/lib/vst/Surge.so:      Failed to load VST plug-in /usr/lib/vst/Surge.so: libxcb-util.so.1: cannot open shared object file: No such file or directory


Passed : 0 Failed: 1
```

**Comment by khusseini** [comment]
So, Debian Stretch does not include the correct version for `libxcb-util`
I installed the correct version from [software.opensuse.org ](https://software.opensuse.org//download.html?project=home%3Astevenpusser%3Alibxcb-util1&package=libxcb-util1#directDebian) and it worked :)

**Comment by baconpaul** [comment]
Great
Also don’t use the lib directly use the .vst3 packaged in products. Vst3 uses a bundle format on Linux now.
But black ui right? That’s the event loop problem

**Comment by tank-trax** [comment]
yes Debian uses libxcb-util0 and the builds use libxcb-util1, so installing libxcb-util1 is needed for the deb to install

I've been able to find the correct VST2 SDK by Googling it. 

if you do manage to find it I can confirm that Surge builds on Debian Stretch using libxcb-util0
to build the VST2 it's necessary to export the path to the VST2 SDK folder and run
`./build-linux -p vst2 build
`
