### ISSUE TITLE
Formula Editor: indents not displayed

### ISSUE THREAD

**Issue by mynameismuhl** [surge-synthesizer/surge#4925]
d83e03ed
Linux Vst3 and Standalone

opening formula editor in Linux looks like this
![form](https://user-images.githubusercontent.com/80534683/131065353-98fcfae1-522f-4085-bd97-df937f8b8c5b.png)
- When using TAB the cursor jumps 4 spaces to the right but the text does not.
- Trying to delete "1" at the end of line 7 in the default example script
  deletes "2" instead (4 spaces to the left).

meaning TAB/indent is applied just not displayed correct.

**Comment by baconpaul** [comment]
I branched juce so this should be fixed at head.It is in my ubuntu vm. A confirm and I'll close it thanks.

Remember

```
(pull upstream as normal but then also)
git submodule sync
git submodule update --init --recursive
ls -l libs/JUCE/README.surge
```

should show a file before you build.

**Comment by mynameismuhl** [comment]
looks good on mint as well

**Comment by baconpaul** [comment]
Excellent. Let me close this then.
