### ISSUE TITLE
Virtual keyboard should always receive keypresses when possible

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4930]
So currently, one first needs to click on the virtual keyboard to make it take keyboard focus, and then QWERTY works to play it. 

I hope there's a way to force VKB to always take keyboard input, unless we're typing in a parameter value, or typing in patch store dialog, or typing in a miniedit. 🤞

**Comment by baconpaul** [comment]
our internal keybindings need to be on the parent no the sge. easy enough change!

**Comment by VincyZed** [comment]
Possibly related:
Pressing tab to arm mod mode works now, but only if I clicked somewhere on the UI before.
If I click on the plugin wrapper window frame to move the plugin window, it activates the tab function of FL instead, which is cycle between opened windows.

**Comment by baconpaul** [comment]
my fix didn't work
"when possible" may be "never", in which case, in the most pedantic sense, I could close this issue as done.

**Comment by baconpaul** [comment]
"when possible" was "when applying above diff" :)
