### ISSUE TITLE
I cannot use Surge at all

### ISSUE THREAD

**Issue by nomihs** [surge-synthesizer/surge#4931]
**Bug Description:**
After being going to store a patch in a state of init, an error was displayed, and DAW came to crash when thereafterI was not able to start surge in all DAW which I had.. I do not remember it exactly, but think that the version was a version before one of 1.9.0.

**Surge Version**
This information is found on the About screen, which you get to from the bottom right menu

* Version:1.9.0
* Plugin Type: [ VST3]
* Bitness: [64-bit]

**Reproduction Steps:**
1. Click on 'store'
2. See error

**Expected Behavior:**
An error is displayed by a screen of DAW, and any DAW cannot use surge afterwards.
**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Host: [FLstudio 20 ,Cubase8]
 - Version: []

**Additional Information:**

**Comment by nomihs** [comment]
I am sorry for bad writing.

DAW:FL Studio 
version of DAW:20.8.3
OS:Windows 10 home
version oh OS:20H2

This picture is a picture when I was going to use surge now.
The version of surge is 1.9.0.

https://user-images.githubusercontent.com/89652635/131219588-ba49d186-588d-4411-9f9c-6d995c8c103f.mp4

**Comment by mkruselj** [comment]
This is loading from a .fst file in FL's left side browser, right?

Can you try deleting that specific .fst file then rescan plugins, then try loading Surge directly from FL Plugin Manager by dropping it onto a channel?

**Comment by nomihs** [comment]
I dropped it directly from FL Plugin Manager.

https://user-images.githubusercontent.com/89652635/131220855-745dad1c-a3ff-4e19-9055-75aa12960cf4.mp4

**Comment by mkruselj** [comment]
Oh I see you have both Surge VST2 and VST3 there. Should probably remove the VST2 version, completely annihilate Surge folders on your system (except the user folder, of course!), and install from scratch.

**Comment by nomihs** [comment]
I deleted the surge file from the system and installed it again.

https://user-images.githubusercontent.com/89652635/131223169-b4130d1d-7669-42f7-b879-7d1e5f53c8d0.mp4

**Comment by baconpaul** [comment]
Are you in a machine with a non us English only code set? We had a report of a crash on a Korean only windows for instance but we don’t know the fix

we also have a new version going to hit beta soon - I wonder if that works. Grab the xt nightly from our homepage perhaps?

hard to tell what’s wrong … appreciate the clarity though

**Comment by mvf** [comment]
Could be a language pack, but the desktop in the first capture is Japanese. I can't repro this on my Japanese Windows 10 though. Also created a user called 俺様 so the homedir isn't ASCII, but no dice. Sure does look a lot like #4838.

**Comment by baconpaul** [comment]
Would be very interested if XT crashes similarly for the user.

**Comment by mkruselj** [comment]
@nomihs Could you perhaps try if the issue you outlined here happens with Surge XT?

You can download Surge XT nightly [here](https://surge-synthesizer.github.io/nightly_XT). It installs side by side to Surge 1.9 so don't worry about existing projects.

Thanks!

**Comment by nomihs** [comment]
Such an error appeared.


https://user-images.githubusercontent.com/89652635/131341307-4cb62d41-02ec-448e-a9d8-6a07a4fd1f4a.mp4

**Comment by mkruselj** [comment]
Can you please check if the folder C:\ProgramData\Surge XT exists, and is not empty?

**Comment by nomihs** [comment]
It was not empty when I confirmed the folder C:\ProgramDate\Surge XT.

**Comment by mkruselj** [comment]
@baconpaul What do we do here?

**Comment by mkruselj** [comment]
I am closing this issue. If @nomihs ever returns with more info, please feel free to reopen.
