### ISSUE TITLE
Zip file drop 

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#4933]
Drop a zip on surge
And unpacks it in the right spot
Patches wavetables skins the lot
Juce:;zip file will help

**Comment by baconpaul** [comment]
And #4814

**Comment by baconpaul** [comment]
OK for this one it is pretty simple

line 4887 of SurgeGUIEditor.cpp will get called if you drop a .zip file onto surge. Right now it will do nothing. So what should it do?

Well lets assume it is a zip file of mixed wavetables and patches and they ahve directories. So step one I would do is use https://docs.juce.com/master/classZipFile.html to at least print out everything in the zip file. (You will get a variable pointing to the path of the dropped file in SGE.cpp).

Once you have that I would do something like

1. Prompt to see if you want to unpack it like we do right above for skins
2. Traverse the zip file with something like

```
foreach element
    if (element ends with .fxp)
        move the element to userDataPatchesPath / (directory from zip ) / file
   if (element ends with .wav or wt )
       WavetablePath
   if (element ends with .surge-skin)
      SkinsPath
```

those paths are all fs::path members on surgesotrage which at this point of the code you can get with `synth->storage.userPatchesPath` or the like.

**Comment by cannero** [comment]
Hi, currently I'm on this and will create a PR draft in the next days. I just wanted to clarify the structure of the zip file.
Can we assume that no top level directories are used, for example
```
|- Chords
     |- Minor 7.fxp
     |- Tek Stab.fxp
|- dark-mode.surge-skin
   |- all skin files...
```
That file we can unzip the content to `userPatchesPath` and `userSkinsPath`.

Or is it also possible that the toplevel directories are there?
```
|- patches
    |- Chords
       |- Minor 7.fxp
       |- Tek Stab.fxp
```
This file we would unzip to the `userDataPath`. Or should there be a check that this file is not unzipped?

And again thanks for your suggestion @baconpaul.

**Comment by baconpaul** [comment]
I think if a user has a top level folder called "patches" we move it into the resulting "userDataPath" and the name is redundant. Assume no top-level directories and let folks clean up if it is otherwise. (We have to choose one or the other, and assuming there isn't a structure is much more flexible)
