### ISSUE TITLE
download dosn't work for me:-( I went thru the auto load process, box said all good, but I can't find anyway to get Surge to fire up. Please help! I want to make noise.

### ISSUE THREAD

**Issue by Stevensea** [surge-synthesizer/surge#4964]
**Bug Description:**

**Surge Version**
This information is found on the About screen, which you get to from the bottom right menu

* Version:
* Plugin Type: [VST2, VST3, AU]
* Bitness: [32-bit or 64-bit]

**Reproduction Steps:**
2. Click on '...'
3. Scroll down to '...'

**Expected Behavior:**

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Host: [e.g. Bitwig, Logic, Cubase, Reaper]
 - Version: [e.g. 2.4]

**Additional Information:**

**Comment by Stevensea** [comment]
I'm technically a little illiterate, So I'm asking here out of despiration. Hope thats okey.

**Comment by baconpaul** [comment]
I see you popped up in discord also so I will answer your question there and close this.
