### ISSUE TITLE
Web page info correction

### ISSUE THREAD

**Issue by neoscopio** [surge-synthesizer/surge#4965]
> Linux  The plugin itself, preset library and wavetables are at /usr/share/Surge with a standard install. The user presets are at ~/Documents/Surge.

1. Should be without capital S, that is: `/usr/share/surge`
2. The directory `~/Documents/Surge` was not created when I installed.
3. also I suggest you mention that the plugin .so location goes to` /usr/lib/vst3/Surge.vst3/ `

**Comment by baconpaul** [comment]
On #2, in Surge 1.9 the directory will be created when you take an action which needs it, like saving a preset. (In surge XT it will be created the first time you run the synth). The installer doesn't create user space stuff.

On #1, both /usr/share/surge and /usr/share/Surge work although we prefer the first, and there's other options too

On #3, VST3s are bundles so the VST3 really is the directory. The location of the plugin .so inside is sort of an implementation detail (and it should be in Surge.vst3/x86_whatzit or something right?). 

But anyway if you can let me know which part of the website had this info we can fix up the first and second to make it clearer for sure!

Thanks

**Comment by baconpaul** [comment]
Thanks!

**Comment by baconpaul** [comment]
Merged the manual change. Appreciated both! Closing this now.
