### ISSUE TITLE
Base preset as starting point to use inbuilt effects on external input audio signal

### ISSUE THREAD

**Issue by jjYBdx4IL** [surge-synthesizer/surge#4966]
A lot of synths/plugins come with their extensive set of audio effects. So does Surge. However, most of them do not allow to use these effects outside of the plugin itself. In surge, I have discovered that one can select audio input instead of a wave form. However, I could not figure out yet, how to apply a surge audio effect to an external stereo signal without having clicks or generally inconsistencies in the output signal. A base preset that just pumps an unmodified input stereo signal to the output would be quite helpful in this regard. Maybe it could include a simple stereo reverb.

I'm aware of the surge effects bank, however, Surge's FX chain seems way more flexible and also allows direct combinations with the rest of the synth.

TY!

**Comment by baconpaul** [comment]
Hi!

In "templates" there are four "audio in" presets which do exactly this. To hear anything though you will want to run them in 'latch' mode of course.

The trick is

DAW side chain -> surge
OSC1 -> Audio In Stereo
Play mode -> latch
A and Master FX put whatever you want

and voila. That's basically what the preset is.

So I think we've done exactly this already. If so, can you let us know and we will close this issue? Thanks!

**Comment by jjYBdx4IL** [comment]
I had to disable MIDI INPUT for the plugin. Or set one channel to MONO ST. TY!

**Comment by baconpaul** [comment]
yeah or put the play mode in latch so there is always one voice open. you need surge voices to be gated for the oscillator to gate. and if you are in poly mode it will introduce multiple copies of the audio into the graph per voice. Which is sometimes but not usually what you want.
