### ISSUE TITLE
Potential bug in Mono FP low/high priority modes

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4971]
1. Init saw, set to Mono FP play mode, right click set to low priority
2. Add a healthy amount of portamento
3. Play middle C, hold it, play C an octave lower -> we're still on middle C
4. Now lift middle C, we glide down an octave -> all good
5. Now while holding that lower C, play middle C again - we're still on C an octave lower
6. Now lift the lower C, we **don't glide back**  to middle C -> super weird and unexpected!

In all other mono modes the glide back does happen. Investigate why Mono FP is different.

The same happens in highest priority mode, but then you play a higher octave C rather than lower octave C to reproduce.

**Comment by baconpaul** [comment]
Even easier

Init / Mono FP / Low Prio / High Porta
C4
C3 (hear the glide)
release C3 (jump to C4)

all the other moni work
