### ISSUE TITLE
sans GUI for linux headless or embedded

### ISSUE THREAD

**Issue by gminorcoles** [surge-synthesizer/surge#499]
Are there clear points in the code where the GUI can be suppressed? I would like to play around with a headless version for semi-embedded use on linux.

**Comment by baconpaul** [comment]
Welcome!

Yes but it would be a chunk of work. I’ve wanted headless surge for a while and the classes are fairly GUI separated. 

So my question back to you is: which of the following best describes your question 

1: you are a c++ dev and want to make it work headless - can anyone give me a guide to get started. If so I’m happy to do so when I’m not on my phone!

2: I’m not really a c++ dev and I want to use it headless. In that case we gotta weite some code and I think it will be a little before we do. But entirely possible.

If it is #1 I am sure @jsakkine or I could finish up the bones of surge app both in premake and c++ for you to get started. 

Thanks!

**Comment by gminorcoles** [comment]
Bacon Paul,
 1. I am a c++ developer. I tell myself to keep music about playing music not coding, I kind of can't help it. 

A super rough binary estimate is what I was hoping for from one of you who has been into this code for a few weeks. Like, has the previous maintainer kept decent separability between gui and logic? And as a person with no VST coding experience, are good programming practices encouraged by the VST framework?

I don't want to tax you, but opinions are very helpful and your informed opinion might influence me to try to not try to make the headless version work, because I have a very specific use case on mind, I am thinking about making this run on zynthian or another linux based environment where there is either only a custom GUI or no windowing at all. 

Thanks,
BTW I am already using surge on my Surface Pro on windows 10 and it so far just works and is pretty awesome.

**Comment by baconpaul** [comment]
Ok great! I’ll write up some notes or maybe even some small bits of code in the next few days to help. Like I said I’ve always wanted exactly this too.

You’re not in any rush right?

**Comment by gminorcoles** [comment]
no rush at all. I cloned the repo I have never used premake so I am looking into that.

**Comment by baconpaul** [comment]
OK. I was just chatting on slack. I may try and do a basic headless binary quickly now to get you started. It would also guarantee that we are segmenting the code properly. Stay tuned.

**Comment by baconpaul** [comment]
Hi! So it turns out, mostly because @kurasu was careful and we've stayed careful, that this wasn't that hard and is valuable. Pull request #502 introduces a headless main executable which sets up and configures a surge and ascii-art renders the sawtooth wave.

When that's swept, it will auto-close this issue most likely, unless I edit the commit message. But I think that's exactly what you were looking for yeah?!

**Comment by baconpaul** [comment]
We will probably merge this tomorrow or Thursday. I incorporated @jsakkine review comments and want to give him time to do one more look

Thanks for promoting me to do this! Would be very interested in staying in the convo on where we can take it next

**Comment by gminorcoles** [comment]
I read through your PR and except for all those really shameful trailing new lines :) it was very informative. I have no experience in VST or audio so there is a learning curve to be surmounted. 

I built vst3 on my linux mint laptop last night and could not get the plugin to be recognized by Reaper, Carla, or Tracktion 7. I don't know what I did wrong. I guess I will try vst2 tonight.

**Comment by baconpaul** [comment]
Great! And yeah, ha, indeed. My excitement meant I didn't even do a self-review before I sent it to @jsakkine so feel a bit bad about wasting his time on some of those. But he's a great reviewer.

None of us have really tried vst3 linux yet; it is not clear you did anything wrong at all!

**Comment by tank-trax** [comment]
just curious... are there an instructions on how to build Surge without GUI?

**Comment by baconpaul** [comment]
Once this PR is swept, it will happen automatically on linux. We just need to merge the code in #502. ./build-linux will build it along with the vst-en and the (empty) app.
