### ISSUE TITLE
XT: Value popups appear below other GUI elements after the Waveshaper visualization pane has been opened

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#4994]
**Bug Description:**
If I open the new Waveshaper visualization pane, then close it, then move a slider, this happens:

![image](https://user-images.githubusercontent.com/50145178/132132302-00d7efbf-0802-4817-be46-f4772b2cdf31.png)

Closing the GUI and re-opening it fixes it.

**Comment by baconpaul** [comment]
Oh I know what that is thank you
It will go away when I rewrite it as a proper overlay 
But I should force them infowindow front always

**Comment by baconpaul** [comment]
https://forum.juce.com/t/question-on-grouping-and-accessibility/47683 I will do a tactical fix but I hope for a better overall solution
