### ISSUE TITLE
Add visual feedback when drag-and-dropping mod sources on parameters

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#4995]
Right now, when drag-and-dropping modulation sources on parameters to access the type-in window quickly, there is no visual feedback such as hover or anything like that. 

What I think would be great and intuitive is if we drag a mod source over a parameter, we temporarily show its blue mod slider (only the blue sider of the parameter you're currently hovering over before dropping) as a visual hover state. This will show the user if the control is already modulated by that modulation source (and by how much) or not, in addition of providing visual feedback as to where they're hovering over before dropping.

I think this would make a big difference in making this gesture look and feel more polished.

**Comment by baconpaul** [comment]
Good idea
Not sure if it is easy but if it is I will add it
If it isn’t I might still add it but also might not
