### ISSUE TITLE
Airwindows Mackity and MackEQ as effects

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#4996]
It would be amazing to adapt these to Surge as well as the Zfilters. Adding these would complement the Zfilters for a large(ish) portion of a fairly desirable signal chain that is a certain type of "sound" in DnB. When people (DnB producers) talk about the emu "sound" from the e6400 series samplers they are often really meaning the zfilters.... the emu chorus, driven through an old *ss cheapish Mackie desk (and a bunch of other stuff).  

Anyway, would be cool to have these as FX.

**Comment by baconpaul** [comment]
It is easy to do but I want to check if they are latent first. Surge basically can’t handle high latency effects and that has knocked out a few

**Comment by baconpaul** [comment]
Took a peek at both and they are 0 latency (modulo standard biquad lags which al the other filters have) so happy to add em

In our existing categories where would you put them? Lemme know and I'll add them this week or next.

Thanks!

**Comment by mkruselj** [comment]
Mackity would go into Saturation And More category.

**Comment by ExhibitusTechno** [comment]
on my Mac MackEQ works but Mackity doesn't sho up in Ableton. I am Using big nur on a none M1 Macbook pro. 
All Files are correctly placed in VST and components Folder. Any advise ?

**Comment by mkruselj** [comment]
@ExhibitusTechno This is not helpdesk for standalone Airwindows effects, sorry. Contact Chris at Airwindows directly, please.
