### ISSUE TITLE
MIDI parameter learn cannot be aborted

### ISSUE THREAD

**Issue by cannero** [surge-synthesizer/surge#5004]
**Bug Description:**
MIDI parameter learn cannot be aborted in popup menu.

**Surge Version**

* Version: XT 0.9
* Plugin Type: Standalone
* Bitness: 64-bit

**Reproduction Steps:**
1. Right click on a control and select 'MIDI learn parameter'
2. Right click again, 'Abort parameter MIDI learn'
3. MIDI icon is hidden, but in popup menu MIDI learn is still active

**Expected Behavior:**
MIDI learn is aborted.

**Computer Information (please complete the following information):**
 - OS: Windows 10

**Additional Information:**
Abort does not set the state back to `-1`:
https://github.com/surge-synthesizer/surge/blob/6dc4b74d1e466f3b43315c5f461b4f35d7ea7f63/src/gui/SurgeGUIEditorValueCallbacks.cpp#L187

**Comment by mkruselj** [comment]
That was a typo. Thanks for the report!
