### ISSUE TITLE
cmake --install of LV2 uses the wrong file-name

### ISSUE THREAD

**Issue by dromer** [surge-synthesizer/surge#5014]
As discussed on the chat:

The LV2 have their spaces removed from the .so files, but the installer expects the default filenames and thus fails to find them.

Please adjust cmake so it knows what filename to expect when installing.

**Comment by baconpaul** [comment]
Basically the vst3 hack 2 lines above needs copying sigh

**Comment by baconpaul** [comment]
Just merged a fix for this.
