### ISSUE TITLE
Resizing the Window in Standalone Causes the Window to Spasm

### ISSUE THREAD

**Issue by SeanMcGoff** [surge-synthesizer/surge#5025]
**Bug Description:**
In attempting to resize the windows of the standalone version of Surge XT, the window rapidly changes from a myriad of different sizes.

**Surge Version**
This information is found on the About screen, which you get to from the bottom right menu

* Version:
* Plugin Type: Standalone
* Bitness: 64-bit

**Reproduction Steps:**
1. Clone Repository
2. Build from Source
3. Open Standalone
4. Try to Resize Window

**Expected Behavior:**
When the window is dragged to resize, it shouldn't violently blink to and from existence.

**Screenshots:**
[Link to Video](https://drive.google.com/file/d/1lvk5JXmdPT_eGGRra_DCHnwlHYGdXO84/view?usp=sharing)

**Computer Information:**
 - OS: MacOS 11.5.2
 - Host: Standalone
 - Version: N/A

**Additional Information:**
@baconpaul indicated that the issue might have to do with how the window resize handles values < 1

**Comment by baconpaul** [comment]
This seems far worse below 100% than above when I try it … will look

tsgging as pre beta also

**Comment by baconpaul** [comment]
So what's happening here is <100% the resize is forming an self-shrinking loop. I'm not quite sure why but when I set size to 100 and drag it down a bit and print out the factors I get this from one drag. Basically once we ask for a zoom below 100 we never stop shrinking.

It looks like an unstable resize around that 840 / 524 pair keeps on shrinking us a bit.

```
889x559 zfn = 0.973713 100.499
837x522 zfn = 0.916758 101.327
838x523 zfn = 0.917853 92.8927
839x524 zfn = 0.918949 85.2618
840x524 zfn = 0.920044 78.3512
841x524 zfn = 0.920914 72.0866
842x525 zfn = 0.922234 66.3855
843x527 zfn = 0.92333 61.223
844x528 zfn = 0.924425 56.529
846x530 zfn = 0.926616 52.2568
847x530 zfn = 0.927711 48.422
848x531 zfn = 0.928806 44.9216
848x532 zfn = 0.928806 41.7235
849x533 zfn = 0.929901 38.753
849x536 zfn = 0.929901 36.0365
850x538 zfn = 0.930997 33.5104
853x540 zfn = 0.934283 31.198
854x540 zfn = 0.935378 29.1478
855x541 zfn = 0.936473 27.2642
858x541 zfn = 0.939759 25.5322
860x542 zfn = 0.94195 25
```

**Comment by baconpaul** [comment]
For now I disabled drag to resize
