### ISSUE TITLE
Consolidate all font usage into a style sheet

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5027]
So that we have a clear tree of what is used where at which size and which weight etc. Basically deprecate `getLatoAtSize()` and create a namespace with font definitions, much like what we do for colors in SkinColors.cpp and so on.

**Comment by baconpaul** [comment]
OK @mkruselj #5032 is a first pull request that creates the data structures and uses them in two spots. I am *not* going to merge it but I am happy for it to be merged if you want to work on this

Basically from that PR there are three steps

1. Walk over the rest of the code replacing the uses of getFontManager and so on with skin->getFont(new object)
2. Once that is done, make the interior of the RuntimeFont.h private with a skin friend, which will force everyone to the new API
3. Once that is done, make the skin engine able to populate non defaults. We will also want to be able to partially override in the skin engine (that is replace "Lato" with "Comic Sans" everywhere without specifying each font, but that's easy if you follow this pattern and *don't* specify Lato anywhere in the model other than as a default signifier).

We can do 3 in parallel with 1 and 2, but it is only useful if 1 and 2 are done.

So read the diff and if you want to get the other 100 odd spots in the code then we can do this for XT1

**Comment by mkruselj** [comment]
This is now basically sorted out in the Figma wireframe for XT2.
