### ISSUE TITLE
One last mod index related bug (hopefully)

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5029]
![whoops](https://user-images.githubusercontent.com/2393720/132510327-b07a57a5-beaa-4e1e-b0ec-7573e9e162fa.gif)

**Comment by baconpaul** [comment]
oh wow thanks!

**Comment by baconpaul** [comment]
ha ha ha
the reason is
very dumb
but i bet easy to fix

basically the LFO displays the modsource_index of course
but not of the LFO
instead of the selected item
where 0 is almost always the right answer
except here
and with a formula mod
