### ISSUE TITLE
Opening and closing editor can put surge in a bad state

### ISSUE THREAD

**Issue by sagantech** [surge-synthesizer/surge#504]
for VST2 opening the editor multiple times puts Surge in a very bad state. Depending on the host this could mean crashes down the road, incorrect frame rendering and more.
**To Reproduce**
1. Open surge editor
2. Close the editor keeping sound going
3. re-open the editor.
4. Bad things will happen now or later

**Expected behavior**
Everything just works

My fix  for this was to not do anything in the SurgeGUIEditor::open function if (editor_open) is true.

**Comment by baconpaul** [comment]
Could you package your fix as a branch for us to look at or a PR if you are confident it is correct? Or if not, paste a diff into this issue? Thanks.

**Comment by lunafreya** [comment]
Is this issue resolved as of now? I believe that Surge must have gone more stable in later releases.

**Comment by mkruselj** [comment]
This seems to be fixed, yeah. @baconpaul we could close?

**Comment by baconpaul** [comment]
I think so yes. It has certainly been reworked several times since this issue was opened.
