### ISSUE TITLE
Waveshaper as effect

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5050]
We have the scaffolding, let's use it to have all the waveshapers in an easy to use FSU FX unit!

Parameters:

Type (menu - all the same options that we have in QFB)
Input (+/- 48 dB)
Bias (+/- 100%) - makes it so that input signal can go fully positive or fully negative, targetting different parts of the waveshaper. Will probably need to clamp to [-1 ... 1] before hitting the waveshaper
Low Cut (same as in ringmod - right click option to route filter pre or post waveshaper)
High Cut (same as in ringmod - right click option to route filter pre or post waveshaper)
Output (+/- 48 dB)

**Comment by baconpaul** [comment]
oh man i just want to bang this one out. it will be lovely. and fun to write.
On the bias: The wrveshapers all do appropriate internal clamping so i think we will be OK.

**Comment by baconpaul** [comment]
We actually have a lot of param room so we can do

Input-Stage
1. Input Boost
2. High Cut
3. Low Cut

Shaper Stage
4. Model
5. Bias
6. Gain

Output Stage
7. High Cut
8. Low Cut
9. Output Boost
10. Wet/Dry Mix

and we are totally fine. So I think that's the way to do it yeah?

**Comment by mkruselj** [comment]
Ha maybe. Really unsure if we absolutely need two sets of filters, but it may be needed with polyphonic content. Easy to chuck out after testing, I guess.

**Comment by baconpaul** [comment]
yeah that's right. So pre-filter, shaper, output stage.

**Comment by mkruselj** [comment]
Perhaps Pre-filter, Shaper, Post-filter, Output?
