### ISSUE TITLE
Modify title bar and window border color for standalone

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5061]
The default JUCE dark green is not very fitting so it would be nice to change it before release. Bonus points for being able to change it via skins too.

**Comment by baconpaul** [comment]
So I spent a bit of time on this
You can whack the colour scheme on the look and feel and it works but does it for every widget 
You can ovrrride draw document window title in the landf and it works but it doesn’t get the buttons
So my plan is put a skin ref in rhe l and f and override things. Get a surge logo up there from the db while at it also 

will also matter if I do tear our overlays which should be pretty easy now

**Comment by mkruselj** [comment]
Ohhh nice thinking about Surge logo up there!

**Comment by baconpaul** [comment]
`baconpaul/titlebar-5061` branch sets this up
to modify the drawing in there look at the SurgeJUCELookAndFeel

**Comment by baconpaul** [comment]
ooooh ... lemme try and rebase this

**Comment by baconpaul** [comment]
oh wasn't that hard. all caught up!
