### ISSUE TITLE
suggestion: adding surgesynth to homebrew?

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#507]
http://brew.sh is pretty hot. Would be wonderful to go: 

`brew install surgesynth` and have it grab the newerest versionrest.

anyone know how, and is this a low hanging fruit?

**Comment by baconpaul** [comment]
Doesn't look impossible at all. You write and commit some ruby which grabs from the website and runs the current packager is one solution.

A quick google shows

https://tech.cars.com/distributing-your-home-grown-tools-to-the-masses-with-homebrew-acb7a62518a8

I've never done it, but not a bad thing to have on the list. Hard part would be to configure it for changing versions. I think we should only do this when we print a 1.6.0 final.

**Comment by baconpaul** [comment]
When we go about doing this we can just make a homebrew cask directly to our installer

https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md

> Here is a last example for airdisplay, which uses a pkg installer to install the application instead of a stand-alone application bundle (.app). Note the uninstall pkgutil stanza, which is needed to uninstall all files which were installed using the installer.

**Comment by baconpaul** [comment]
Totally gonna do this once we get 1.6.0 up this weekend

**Comment by baconpaul** [comment]
https://github.com/Homebrew/homebrew-cask/pull/64210

if that PR gets merged we are done here and I can close this issue.

**Comment by baconpaul** [comment]
This is done

```
brew udpate
brew cask install surge-synthesizer
```

should do it for you!
