### ISSUE TITLE
Crash when opening WaveShaperAnalysis view

### ISSUE THREAD

**Issue by jatinchowdhury18** [surge-synthesizer/surge#5091]
**Bug Description:**
Surge crashes when trying to open the WaveShaperAnalysis view when the WaveShaper is on the "Off" setting.

**Surge Version**
Version:  Surge XT 0.9.nightly.57092c7
Build:  2021-09-14 @ 15:50:16 on 'Mac-1631633988512.local/pipeline' with 'AppleClang-12.0.0.12000032' using JUCE 60101
System:  macOS 64-bit AU on Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Host:  Ableton Live 10

**Reproduction Steps:**
1. Open Surge
2. Set the Waveshaper to "Off" (if it's not there already)
3. Try to open the WaveShaper Analysis view
4. Crash

**Screenshots:**
No screenshots, but here's a stack trace:
```
Thread 0 Crashed:: MainThread Dispatch queue: com.apple.main-thread
0   Surge XT                      	       0x16b1c1b67 Surge::Overlays::WaveShaperAnalysis::paint(juce::Graphics&) + 775
1   Surge XT                      	       0x16ad5c6ce juce::Component::paintComponentAndChildren(juce::Graphics&) + 110
2   Surge XT                      	       0x16ad5c972 juce::Component::paintComponentAndChildren(juce::Graphics&) + 786
3   Surge XT                      	       0x16ad5c972 juce::Component::paintComponentAndChildren(juce::Graphics&) + 786
4   Surge XT                      	       0x16ad5c972 juce::Component::paintComponentAndChildren(juce::Graphics&) + 786
5   Surge XT                      	       0x16ad5c742 juce::Component::paintComponentAndChildren(juce::Graphics&) + 226
6   Surge XT                      	       0x16ae0d846 juce::ComponentPeer::handlePaint(juce::LowLevelGraphicsContext&) + 262
7   Surge XT                      	       0x16ae60bd8 juce::NSViewComponentPeer::drawRect(CGContext*, CGRect, float) + 232
8   Surge XT                      	       0x16ae60a86 juce::NSViewComponentPeer::drawRect(CGRect) + 278
9   Surge XT                      	       0x16ae5eab5 juce::JuceNSViewClass::drawRect(objc_object*, objc_selector*, CGRect) + 69
10  AppKit                        	    0x7ff80c443823 _NSViewDrawRect + 121
11  AppKit                        	    0x7ff80cb594a3 -[NSView _recursive:displayRectIgnoringOpacity:inContext:stopAtLayerBackedViews:] + 1832
```

**Computer Information (please complete the following information):**
 - OS: MacOS Monterrey
 - Host: Ableton
 - Version: Surge XT Nighty

**Comment by baconpaul** [comment]
Oh duh sorry - and thanks

**Comment by ztnl** [comment]
Confirmed on Windows 10:

Version:  Surge XT 0.9.nightly.2581694
Build:  2021-09-14 @ 18:50:21 on 'fv-az179-614/pipeline' with 'MSVC-19.16.27045.0' using JUCE 60101
System:  Windows 64-bit VST3 on        Intel(R) Core(TM) i7
Host:  Reaper

Same steps as above, which makes this version of XT hang where none of the UI controls work.

**Comment by baconpaul** [comment]
Yeah got a fix
