### ISSUE TITLE
Restore/Remake the cmake targets to run standalone and test

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#5099]
- [x] reinstate the install() rules on Linux https://github.com/surge-synthesizer/surge/blob/fafe52f70c2708302fb21ee5864b9d2b0e1b163c/CMakeLists.txt#L1197
- [x] Have a split target so we can build staged rather than stage and make installers 
- [ ] Restore the run targets (outlined below)
- [x] Reorg the code to break the GUI and xt circular relationship 

we can add other stuff here as we need. Tagging @mvf also

**Comment by mvf** [comment]
The Linux `install` rules are now in `surge_juce_package`:
https://github.com/surge-synthesizer/surge/blob/5ef1eb86763e5a91a648bef296bbc1f6970cd0e6/src/cmake/lib.cmake#L31-L43

**Comment by baconpaul** [comment]
So on the run targets, here's the current state of play and my proposed change

In Linux and Mac we read the env var `PIPELINE_OVERRIDE_DATA_HOME` and use that to override the inferred data path. This allows us to run build and test steps without copying resources. On windows this isn't implemented yet. So my proposed change for that is

- [ ] Add `bool SurgeStorage::getOverrideDataHome(std::string &value)`
- [ ] Make that check PIPELINE_OVERRIDE as it does now for legacy reasons but also check `SURGE_DATA_HOME`
- [ ] Call that as an override in each of the windows mac and linux paths rather than the direct getenvs now
- [ ] Once that is done, use `add_test` to add a cmake test directly which depends on headless and runs it with that env set to `${CMAKE_SOURCE_DIR}/resources/data`
- [ ] And also add a `run_standalone` which gives us a surge-xt_Standalone-run and surge-fx_Standalone-run target which sets it and runs the associated standalone.
