### ISSUE TITLE
Surge 1.9.0 VST3 black screen and crash in Newsonicarts Freestyle

### ISSUE THREAD

**Issue by SWey60** [surge-synthesizer/surge#5102]
Build: NIGHTLY-2021-04-25-e679f24 built at 2021-04-25 15:05:03 UTC - VST3

Freestyle 1.6.023 (this is an internal beta, but the public beta has this problem too)

Steps (100% reproducible):

1) Insert Surge instance in Freestyle (standalone host) and open GUI

2) GUI is black rectangle

3) Close plugin window

4) Crash - crashlog attached

My system: OSX Mohave 10.14.6 (18G9323), RME Fireface, 4K Retina iMac with 8 GB RAM, 1TB Fusion Drive, 6 Core i5 CPU, Radeon Pro 560X GPU
[Surgecrash.txt](https://github.com/surge-synthesizer/surge/files/7178422/Surgecrash.txt)

**Comment by baconpaul** [comment]
I really don't think that's a crashlog from the XT alpha. 

```
0   com.vemberaudio.vst3.surge    	0x00000001a0600e9a VSTGUI::CVSTGUITimer::stop() + 10
1   com.vemberaudio.vst3.surge    	0x00000001a054e3c2 SurgeGUIEditor::close() + 306
2   com.vemberaudio.vst3.surge    	0x00000001a05c9b37 non-virtual thunk to Steinberg::Vst::VSTGUIEditor::removed() + 39
3   com.newsonicarts.Freestyle.Standalone	0x000000010a52652e Freestyle::Engine::(anonymous namespace)::VST3::Editor::~Editor() + 30
4   com.newsonicarts.Freestyle.Standalone	0x000000010a512960 Freestyle::Engine::Plugin::CloseEditor() + 224
5   com.newsonicarts.Freestyle.Standalone	0x000000010a51b4b5 Freestyle::Engine::PluginProcessor::Editor::OnRequestClose() + 21
6   com.newsonicarts.Freestyle.Standalone	0x000000010a7463a3 -[AppfsinV2_Window windowShouldClose:] + 35
```

1. xt no longer uses the vemberaudio package name
2. xt no longer uses VSTGUI::CVSTTimer
3. SurgeGUIEditor::close no longer calls stop on a timer, because of 2

so can we first make sure you have the nightly installed properly and are using the nightly build?

I have an ancient version of freestyle installed. let me grab latest.

**Comment by baconpaul** [comment]
Oh hold on. You are running XT nightly from April!? I'm amazed it works at all. 

Can you please grab a more recent nightly and re-test

**Comment by SWey60** [comment]
It's the nightly I downloaded this morning actually

**Comment by SWey60** [comment]
OK so that seems to install a Surge and a Surge XT (or is the Surge just leftover from previously?) - the Surge still crashes but the Surge XT build gives me the black window but not the crash

**Comment by baconpaul** [comment]
i don't know why the old surge nightly crashes 
let me upgrade my freestyle demo and see if i can repro your surge xt black screen
but at this point we are just a juce plugin. does, say, dexed or obxd work in your system?

**Comment by baconpaul** [comment]
and the surge is just leftover yes

**Comment by SWey60** [comment]
The nightly I was running was from here (not XT) https://surge-synthesizer.github.io/nightly

**Comment by SWey60** [comment]
I don't have Dexed or OBxd

**Comment by SWey60** [comment]
But I do have plenty of JUCE plugins

**Comment by baconpaul** [comment]
hmmm so how do i make it rescan?
when i download 1.5 or whatever it seems to see my system plugins but not my local ones, and also not my vst3-only ones i think.

**Comment by mkruselj** [comment]
So, with 1.6.002 build XT runs just fine over here on Windows. But that's not the latest public beta, so let me test the latest one (1.6.022).

**Comment by SWey60** [comment]
I don't think 1.5 supports VST3 - try the public beta

**Comment by mkruselj** [comment]
I didn't type 1.5 :)

**Comment by baconpaul** [comment]
how do i get the public beta?

**Comment by SWey60** [comment]
I know, Baconpaul did :)

**Comment by baconpaul** [comment]
i just went to the website and downloaded the thing, tbh. and that's what i got.

**Comment by mkruselj** [comment]
I think for public beta you need to have a purchased version.

But anways, latest public beta still opens XT fine over here on Win.

**Comment by SWey60** [comment]
Yeah this is probably a Mac issue - does it use Open GL for the GUI?

**Comment by baconpaul** [comment]
oh
right well i'll give it a test if someone gives me an NFR and instructions
but I also suggest trying the dexed or obxd vst3.
we do not use OpenGL.

**Comment by SWey60** [comment]
I've asked James (Freestyle dev)

**Comment by baconpaul** [comment]
Cool
and in the interim would be helpful to know if these VST3 also work: 

Dexed - https://asb2m10.github.io/dexed/
Surge TWS - https://github.com/surge-synthesizer/tuning-workbench-synth/releases/tag/Nightly

we are structurally very similar in SurgeXT to those two

Thank you

**Comment by SWey60** [comment]
Oh yes Dexed has the same problem as XT - black rectangle (but not the crash I had with the earlier version of Surge)

**Comment by baconpaul** [comment]
Right - So then sounds like "FreeStyle beta doesn't work with JUCE 6 VST3s" is the actual bug here.

hmm... i wonder if we should close this or move it to a freestyle GitHub. I don't think there's a surge change required if both dexed and surge xt do the same thing. (I am curious if your JUCE VST3s also do it; obviously your JUCE VST2s will not).

**Comment by SWey60** [comment]
Thanks I just reported this back to the Freestyle dev and found another JUCE based plugin that has the same issue

**Comment by baconpaul** [comment]
Great closing this then.
