### ISSUE TITLE
Middle-click also includes left-click gestures in some situations

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#5108]
- If you double-middle click on a slider when mod routing is disabled for instance, it will have mod routing mode still armed instead of arming then de-arming it.
- Middle-clicking then holding and dragging on a slider all in one motion allows to start dragging the modulation slider. This isn't bad actually, I quite like that, but unfortunately it leads to unwanted behavior when doing it again from the modulated state (the slider will jump and stuff, you can try it out).
- Middle click+drag on button rows also works when it probably shouldn't ?

This has lead to some strange and unintended gestures and actions from testing on my side. Is this something we can fix?

**Comment by baconpaul** [comment]
I don’t have a middle mouse button so coded this up blind - but we manage all the state ourselves and can fix it I’m sure

**Comment by baconpaul** [comment]
So this is super hard for me to test but the sketch of how to fix is

In widgetbasemixin.h after the forwardedMainFrameMoueDowns add 

```
bool supressMainFrameMouseEvent(const juce::MouseEvent &e) 
{
   if (firstListenerOfType<SurgeGUIEditor>() && e.mods.isMiddleButtonDown()) return true;
   return false;
}
```

then into MutliSwitch::mouseDrag and ModulatableSlider::mouseDoubleClick and so forth, add at the top

```
if (supressMainFrameMouseEvent(event)) return
```

for each method where the behavior is wrong

repeat until fixed, merge, close issue.
