### ISSUE TITLE
surge 1.5.0: when loading one-shot wavefiles, shape slider adjusts playback-start-position

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#511]
```
oh, and when you load a one-shot wav file into v1.5.0,
you can even use the "shape" slider to adjust where 
the wav begins playing! love it... its the next best
thing to my ol Ensoniq VFX!
```

from 
https://www.kvraudio.com/forum/viewtopic.php?p=7305174#p7305174

**Comment by baconpaul** [comment]
Yeah cool. 

That's exactly what https://github.com/surge-synthesizer/surge/issues/198 does also. Actually should work on windows now if you drag a wav file in. But I need to finish and rebase that.

So this issue will close when #198 does.

**Comment by esaruoho** [comment]
awesome. what do you think the possibilities are for getting that to work on macOS though? (drag wav in)

**Comment by baconpaul** [comment]
Oh no problem at all. Like I said, I have most of the code working. Just need to test it with loop markers, which thanks to you I now have.

4-5 hours dev time and this whole family can get closed (with one left over for linux).

**Comment by esaruoho** [comment]
@baconpaul as per your request, i've tagged wavetable / wav related stuff at https://github.com/surge-synthesizer/surge/issues?utf8=✓&q=is%3Aissue+is%3Aopen+label%3A%22path+to+wav%22+ . hope it helps.

also, thanks for taking the time to respond to these tickets :)
