### ISSUE TITLE
Basses/Bass 3 patch Window osc Formant out of range

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5111]
![image](https://user-images.githubusercontent.com/2393720/133858685-b95148a8-47a1-4251-a51a-b5ac3de8199d.png)

Not only is there no slider thumb, the slider track doesn't suggest a bipolar control, the value is out of whack, and even if you default it to 0, the Formant parameter just doesn't work until you reselect Window oscillator. Weird.

**Comment by baconpaul** [comment]
```
                <a_osc1_type type="0" value="7"/>
                <a_osc1_octave type="0" value="0"/>
                <a_osc1_pitch type="2" value="0.000000"/>
                <a_osc1_param0 type="2" value="0.833928"/>
                <a_osc1_param1 type="2" value="-33.321423"/>
                <a_osc1_param2 type="0" value="2"/>
                <a_osc1_param3 type="0" value="0"/>
                <a_osc1_param4 type="0" value="0"/>
                <a_osc1_param5 type="2" value="0.200000"/>
```

no bug here, just a corrupted patch. 

Let me make it 0.3 or some such and then you can edit it

**Comment by mkruselj** [comment]
I do wonder if there are similar patches in our factory content....
