### ISSUE TITLE
Cursor not hidden for FEG/AEG Digital mode curve selectors

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5114]
And something weird happens with hover states - they are scrolled through three times?

![envcurvesel](https://user-images.githubusercontent.com/2393720/133881668-7d50fc9e-a75a-46bf-9fa8-000a4c153826.gif)

Maybe also add a left-right cursor icon when hovering over these controls?

**Comment by baconpaul** [comment]
3 graphics 3 hovers i bet. so it is spanning through the decay and release hover probably

**Comment by baconpaul** [comment]
Cursor on Hover and Hiding is really gross and not what we want. I have the code in but it is terrible
I committed code that does change-cursor-on-drag and that feels way more natural
If you disagree i left the hide stuff in there for you to try.

Also fixed that hover bug. But that was just one line :)

**Comment by mkruselj** [comment]
Cursor on hover and hiding is exactly what we do in MSEG. It's perfectly fine IMO.
