### ISSUE TITLE
FL studio's pitch parameters distort custom scales in Surge which messes up perfect intervals

### ISSUE THREAD

**Issue by tristanbay** [surge-synthesizer/surge#5119]
**Bug Description:**
FL studio's "channel pitch" and "master pitch" parameters appear to distort the tuning of Surge beyond transposing, causing perfect intervals created using a custom tuning to become noticeably out of tune.

**Surge Version:**
* Version: 1.7.1.5270cfb
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Load Surge as an instrument in FL Studio and keep it on default preset
2. Load a .scl file into Surge that has perfect intervals (such as Pythagorean or 5-limit just tuning)
3. Play a perfect interval with a simple ratio (such as a perfect fifth, which has the ratio 3/2) so that you don't hear any flanging between the notes. It should sound pure or almost pure.
4. Move the master pitch knob near the top of the application window to a different position OR click the little gear icon near the top left of the plugin window for Surge and then move the channel pitch knob that's near the right hand side of the ribbon that appeared when you clicked that gear icon.
5. Play the same two keys you did before. It should sound flangey, like if you increased the spread of two unison voices from zero to at least 2 or 3 cents. Depending on the interval and/or which keys you play, the interval may not seem to go out of tune until you turn either of these knobs past a certain point or in the other direction.

**Expected Behavior:**
Perfect intervals stay proportionately in tune no matter how you transpose them with these parameters.

**Example:**
This is some audio of a fifth interval where the pitch parameters are at zero and the interval sounds almost totally pure, followed by what I get when I play the same two keys, but the channel pitch is tuned down by 200 cents, where what is supposed to be a fifth is way out of tune:

https://user-images.githubusercontent.com/85427980/133907728-5d9f1d03-81b1-4d89-be8a-5ee2e8caa585.mp4

**Computer Information:**
 - OS: Windows 10 Home version 21H1
 - Host: FL Studio version 20.8.4

**Additional Information:**
Vital, another open source synth with custom tuning capability, does not seem to have this issue.

Also, I noticed that even when neither of these pitch parameters are active, perfect intervals still seem to be ever so slightly out of tune. If you hold a perfect interval and let it play out for 15 seconds or so while watching a spectrogram, you can see that the shapes that the amplitudes of the higher frequencies make appear to drift very slowly in one direction. This tells me that float and/or double values are likely used to calculate the frequency of each note directly and are responsible for the slight amount of error I find in Surge's tuning. In order to fix this, I suggest keeping these frequency values as mathematical expressions and using those directly in the final math to calculate the output of each oscillator (instead of the floating point values). I may be wrong about the cause of this issue, though, which in that case, the solution I provided would likely not apply.

**Comment by baconpaul** [comment]
This is almost definitely where we apply tuning

in the tuning menu there’s an option like tune at midi and tune at modulation - one will be checked

if you check the other does this resolve?

I presume fl is just moving notes around with pitch bend with that control

**Comment by mkruselj** [comment]
Also, you're using a quite old version of Surge by now. Please update to 1.9!

**Comment by tristanbay** [comment]
> This is almost definitely where we apply tuning
> 
> in the tuning menu there’s an option like tune at midi and tune at modulation - one will be checked
> 
> if you check the other does this resolve?
> 
> I presume fl is just moving notes around with pitch bend with that control

I don't see those options in my version of Surge. I'll update to 1.9 and then try

**Comment by baconpaul** [comment]
Oh right. 1.7 doesn’t even have that option
So upgrade to 1.9 flip the option and I bet it works

**Comment by tristanbay** [comment]
I didn't even have to check/uncheck either of those boxes and now it works fine. Even the issue at the end of my original comment seems to be better than it was on 1.7. Thank you!

**Comment by baconpaul** [comment]
Ahh yeah the midi tune is check by default in 1.9

some of your 1.7 patches may remember themselves in the other mode. Toggle it back if you need.

The manual has a long discussion of the difference and why we have two modes. Sometimes you want one, sometimes you want the other.
