### ISSUE TITLE
Linux Drawing Errors

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#513]
The CHSwitches are very eager to disappear. This is code in src/common/gui/CHSwitch2.cpp and .h mostly. Haven't debugged at all yet.

![linux_draw_one](https://user-images.githubusercontent.com/13387561/52312469-a73b3380-2978-11e9-9115-092fac44d72e.gif)

OS:
```
paul@ubuntu:~/surge$ uname -a
Linux ubuntu 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Host:
```
 ~/Carla_2.0-RC3-linux64/carla/carla-bridge-native vst2 ./target/vst2/Release/Surge.so '(none)' '0'
```

**Comment by baconpaul** [comment]
![linux_draw_two](https://user-images.githubusercontent.com/13387561/52312579-0f8a1500-2979-11e9-8c17-26fbc5cae6df.gif)

Another CHSwitch one. This time when you pick "random" (which basically moves the bitmap to the last selected and crops) it blanks out the area above.

This makes me think that the drawing crop rectangles in CBitmap::draw are not being properly respected but there could be other causes.

**Comment by baconpaul** [comment]
Using the modulators basically blows away the UI. This is what happens when I double click on LFO2 to start modulating

![linux_draw_three](https://user-images.githubusercontent.com/13387561/52312671-61329f80-2979-11e9-8c57-0ff1f796a1b9.gif)

**Comment by baconpaul** [comment]
Lots of other examples too. Like if you zoom after double click you end up getting much but not all of the UI restored; and if you tab (to end the modulation) then zoom you get almost all of it back.

I think this is all the same problem. But it is a pretty big one. Do you guys see the same in your builds?

**Comment by falkTX** [comment]
moving any slider causes the same issue.
I guess it is all related...

**Comment by baconpaul** [comment]
Yeah the sliders are also Trane!ated and clipped since they change color based on state

**Comment by baconpaul** [comment]
I have identified what causes this problem and have a fix which is local to the surge code, even though I think somewhere vstgui is incorrect still.

PR forthcoming with explanation.

**Comment by baconpaul** [comment]
OK Pull Request in. @jsakkine or @falkTX your quick scan appreciated. It is a one line change to work around a bug but want to make sure the comment is clear enough. Thank you.

Gotta say, with this fix in place surge on linux feels basically like surge on windows or surge on mac.

Turning to mis-positioned menu next.
