### ISSUE TITLE
Filter bypass action

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5134]
- [x] Double-click on filter type icon to toggle the filter on/off
- [x] Use existing filter icons, just make them 50% transparent when the filter is off
- [x] Stream that filter state
- [x] ~~Add parameters for host automation~~

**Comment by CurlyMC** [comment]
I very agree with this.
Would also be nice to have this feature for the waveshaper.

**Comment by mkruselj** [comment]
@baconpaul Toldya it would make sense to have double-click on waveshaper curve to bypass it. 🙂

**Comment by CurlyMC** [comment]
ok just say 'sorry' to BaconPaul, i'm afraid he's programming his fingers off :-)

**Comment by CurlyMC** [comment]
... this man must be having terrible nightmares because of all the feature requests for the Surge Synth Project :-)

**Comment by baconpaul** [comment]
> ... this man must be having terrible nightmares because of all the feature requests for the Surge Synth Project :-)

Again the requests aren’t the problem. Fulfilling them is! Chuckle. 

Thanks for the kind words. I have a pretty good idea of a clever and easy way to do this now (use “deform” as a deactivation flag @mkruselj ) and we should be able to put it in next release. It’s a feature I’ve wanted for a while too

**Comment by baconpaul** [comment]
Ok first cut off this is in nightly 
I didn’t add params and used rmb / deactivate as a gesture
Feedback welcome

**Comment by mkruselj** [comment]
RMB is fine I guess but double-click is just faster, so I would like to see that available as well.

**Comment by baconpaul** [comment]
it’s kinda a pain - you have to trap double click, cancel the drag events, generate the call and special case the handler in sgevc for just these types - and absolutely nothing else in surge deactivates on double click (it is a reset to default gesture) so it seems pretty inconsistent - which were all reasons I didn’t do it. But we can type in that code if we want I guess!

**Comment by mkruselj** [comment]
I mean sure, I would also like a dedicated button to toggle bypass instead, but since we don't want to overhaul the UI at this point, I figured this would be an excuse enough to slightly stray from my "consistency is king" credo. 😛 And double-click IS way faster than going through the menu...
