### ISSUE TITLE
vstgui - applying some changes

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#515]
I am writing this issue mostly so folks like @jsakkine @falkTX @kzantow @kurasu @esaruoho and others can talk me out of the path I'm thinking of.

We've come across several VSTGUI errors. @sagantech identified quite a few and put them as issues on the VSTGUI repo; I worked around some but just discovered the vst3sdk upgrade broke drag n drop maybe; Linux isn't painting properly. I think it is inevitable we will need to patch vstgui soon.

Now obviously the ideal world would be: we find a patch, we send a PR to steinberg, they integrate it quickly and seamlessly, we do a pointer upgrade on our submodule, and we rebuild.

But it doesn't seem that's necessarily timely. So I had a thought

How about we fork steinberg/vstgui into surge-synthesizer. Once we've made that fork *we never touch the master branch*. We just constantly pull that from upstream.

But we do three things

1. We add a branch called 'surge' to our repo in vstgui
2. We add another submodule "vstgui.surge" which points at our repo and that branch and modify premake to use that software, not the software in vst3sdk/vstgui
3. We adopt the following workflow
     * Find a vstgui bug we make a new branch in surge (say "surge-menu-check-bug")
     * We send steinberg a PR from that branch
     * But also we merge that branch int our cumulative changes surge branch and move our pointer

That way we are not running any changes which aren't sent as PRs to steinberg, but we can also run ahead of them with fixes.

Every so often, we rebase our surge branch to master and so on.

It's some tricky git machinery but I don't see how we are going to avoid this.  Bugs like #394 are real ones.

Your thoughts welcome.

**Comment by falkTX** [comment]
I think a vst3sdk fork (for updated vstgui) makes sense, I was trying to push from it from the start.
vstgui development (for linux) can be slow, and since it ends up being part of the binary (it is compiled in), makes sense to have control over it.
waiting for upstream to do new releases is going to take forever...

**Comment by sagantech** [comment]
> I think a vst3sdk fork (for updated vstgui) makes sense, I was trying to push from it from the start.
> vstgui development (for linux) can be slow, and since it ends up being part of the binary (it is compiled in), makes sense to have control over it.
> waiting for upstream to do new releases is going to take forever...

100% agree.

**Comment by baconpaul** [comment]
Ok. Does the protocol I suggest seem to be missing anything important?

I think you are correct. We will have to do this. Not happy about it but let's try and do it in a safe way.

Thanks

**Comment by baconpaul** [comment]
Oh and @sagantech if I get time to do this do you mind if I walk a couple of your changes through the protocol? Presume you are happy not fighting git any more than you have to.

**Comment by baconpaul** [comment]
Finally I checked and the usage contemplated here is well within the terms of the vstgui license so we are OK on that front. We don't even have to push our PRs back to them if we don't want! (We do need to update our docs to link to their license more cleanly but I put an issue on the website repo for that).

Absent strenuous objections in the next 24 hours or so, I will make this next on my list of "big chunks of dev work" since it will allow us to close quite a few tickets.

**Comment by sagantech** [comment]
Please implement any changes I have suggested. The whole point of me suggesting them was to improve Surge. I don't care who they get attributed to.

**Comment by esaruoho** [comment]
@sagantech which changes are those? could you link the issues? you can link an issue by referring to it like `#592` (type the # and then the number of the issue).

**Comment by sagantech** [comment]
@esaruoho I was simply replying to @baconpaul comment:

> Oh and @sagantech if I get time to do this do you mind if I walk a couple of your changes through the protocol? Presume you are happy not fighting git any more than you have to.

**Comment by baconpaul** [comment]
<img width="425" alt="screen shot 2019-02-05 at 6 52 34 pm" src="https://user-images.githubusercontent.com/13387561/52375461-b5975700-2a2d-11e9-90ac-631ba0c0d899.png">

so this builds with my soon to be PR version of surge with the forked vstgui. See that checkmark there? 

Have to write some docs and stuff but this plan works fine.

**Comment by baconpaul** [comment]
<img width="480" alt="screen shot 2019-02-06 at 4 39 57 pm" src="https://user-images.githubusercontent.com/13387561/52375532-deb7e780-2a2d-11e9-80f0-ca4cf81b971f.png">

Hey here's the right image

So that's building surge using our fork of vstgui with @sagantech's menu change attached

All mergeable and doable

Need to write up some docs and do a couple of other bits of git magic but this will all work fine.
