### ISSUE TITLE
Set velocity for mouse clicks on the virtual keyboard

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#5150]
**Is your feature request related to a problem? Please describe.**
Currently, mouse clicks have low **Velocity**. I'd like to be able to set velocity in advance, so that clicks on the virtual keyboard can use that set velocity.

**Describe the solution you'd like:**
I don't mind what method, but it should be quick to set the velocity, e.g. a vertical slider to the left of the virtual keyboard, or keyboard shortcuts for a +/- step increment.

**Describe alternatives you've considered:**
n/a

**Additional context:**
XT1

**Comment by mkruselj** [comment]
My suggestion is to use X and C keys to change velocity in increments/decrements of 6 (126 possible values, so that results in 21 jumps). Default velocity value should be 96.

**Comment by j5v** [comment]
Works well, thanks!
