### ISSUE TITLE
Slider moves too fast with scrollwheel 

### ISSUE THREAD

**Issue by hellerdejanuar** [surge-synthesizer/surge#5164]
**Bug Description:**

adjusting a slider with the mouse wheel is to fast and renders it pretty unusable. 
It would be nice to be able to adjust the scroll wheel speed as a part of mouse wheel behaviour. 
Also a modifier key for finer adjustment would be great

**Surge Version**

* Version: 1.9.0.91069f8
* Plugin Type: vst3
* Bitness: 64

**Reproduction Steps:**

1. click any slider
2. scroll
3. see error (moves too fast)

**Expected Behavior:**

the slider should move slower

**Computer Information:**
 - OS: OSX
 - Host: Ableton
 - Version: 11

**Comment by baconpaul** [comment]
Hold shift while moving the mouse wheel and the resolution will increase by a factor of 30 or so (I forget the exact factor in 1.9 but just tried it and it works!)

**Comment by baconpaul** [comment]
Oh also there's menus for mouse speed in general i workflow which also impact the wheel.

**Comment by hellerdejanuar** [comment]
I think mouse speed doesnt impact on the wheel. I tried but it doesnt make a change. It would be great if it was a preference to modify scroll speed and change shift resolution factor (for greater and smaller factors, I would use the finer resolution a lot more than the coarse steps wich are fast but unmusical) Should I post this on feature request?
Thanks :)

**Comment by baconpaul** [comment]
sure but before you do please try with the XT nightly where we have fixed and improved many a gesture.
