### ISSUE TITLE
Notes do not play near max polyphony limit (64)

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#5165]
**Bug Description:**
If the number of notes playing is at or near 64, and a number of new notes are received simultaneously from the host, then some of those new notes might not play.

**Surge Version**
Version:  Surge XT 0.9.nightly.b27200c
Build:  2021-09-24 @ 18:04:05 on 'WIN-A9UQVQS0QTE/pipeline' with 'MSVC-19.16.27045.0' using JUCE 60101
System:  Windows 64-bit VST3 on Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Host:  Cakewalk by Bandlab

**Reproduction Steps:**
Patch: `Grand Piano 2021a`, uploaded to https://discord.com/channels/744319641211633774/744320274714984518/891822107837751316
Example MIDI file: attached as `Polyphony test.mid`
[Polyphony test.zip](https://github.com/surge-synthesizer/surge/files/7232654/Polyphony.test.zip)

**Expected Behavior:**
New notes play, and old notes are prioritized for discarding, to remain within the patch polyphony limit.

**Screenshots:**
n/a

**Computer Information (please complete the following information):**
 - OS: Windows 10
 - Host: Cakewalk by Bandlab
 - Version: 2021-09

**Additional Information:**
Discussion about `margin`:
https://discord.com/channels/744319641211633774/744320274714984518/891846097721495602

**Comment by j5v** [comment]
Using **Nightly 2021-09-30**: All notes seem to trigger, even when polyphone hits 64/64.
Thanks.

I did find what I thought was a related but, but I can't reproduce it, and assume I unknowingly fumbled the UI while setting polyphony to 64. Here for reference:

> However, the polyphony reduces to 58/58 (from 64/64) in the UI, as it's rendering offline. If I start from 58, it doesn't reduce below 58.

**Comment by baconpaul** [comment]
Thanks for confirming and reporting!
