### ISSUE TITLE
wavetable: "surge can't morph through the waveformsets"

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#517]
copied from kvr: 

----
In surge there's interpolation between the waves in the array as long as you use the 'wavetable' algorithm and not the 'window' one, you couldn't get that smooth transitions otherwise. But yes, it's certainly not "true wavetable" in the sense that there's a lookup-table containing wave-ids which are then interpolated between. 
----
For the waldorf wavetables this was done during the conversion and as far as that step was done correctly, which I don't really know for sure if it was, there should be no audible difference afaics. I never did any comparisons though as sounding like waldorf was never a goal for the synth.
----

https://www.kvraudio.com/forum/viewtopic.php?t=205443

**Comment by baconpaul** [comment]
I think there's no work implied in this issue so I'm closing it.
