### ISSUE TITLE
Modulation over-clear

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#5171]
slowboat — 09/26/2021
Dont know if i missed something somewhere... but is it right if both scene A and scene B clear the mod routing, when i use the right click to "clear all mod routings"
i made a cope of A onto B and wanna clear up some of the routings?
on B
baconpaul — 09/26/2021
Are you in 1.9?
I fixed that bug in XT about 2 weeks ago
i think
but if you are on xt
i didnt
slowboat — 09/26/2021
Xt!
thanks 🙏 .
baconpaul — 09/26/2021
Ok so can you describe the scenario a bit more closely? And also share your xt about info? And if you have GitHub ideally do it there but if not here
slowboat — 09/26/2021
Sorry to leave you hanging.. got lost patching😂
will do the git hub bug report
Version:  Surge XT 0.9.nightly.1631ad4
Build:  2021-09-07 @ 12:56:05 on 'fv-az93-843/pipeline' with 'MSVC-19.16.27045.0' using JUCE 60100
System:  Windows 64-bit VST3 on Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz
Host:  FruityLoops
when right click "clear all mod routings" on Scene B, also clears mod routings on Scene A
baconpaul — 09/26/2021
On a scene lfo or@voice lfo?
Or on something else?
slowboat — 09/26/2021
both
only on "clear all mod routings"
not  "clear mod" as in "clear cutoff routing"
baconpaul — 09/26/2021
Oh right it’s like all overclears
EvilDragon — 09/26/2021
I mean it does say ALL
it doesn't say all in current scene
baconpaul — 09/26/2021
Yeah but the vlfo and slfo are per scene
So it should clear what it shows on the menu
EvilDragon — 09/26/2021
ha, right

**Comment by baconpaul** [comment]
that's an old xt. i asked showboat to re-test at head where I can't repro this.

**Comment by mkruselj** [comment]
Was fixed by redoing the menus with icons.
