### ISSUE TITLE
LFOs are able to modulate Send FX 3 and 4 Levels

### ISSUE THREAD

**Issue by ztnl** [surge-synthesizer/surge#5183]
Version:  Surge XT 0.9.nightly.73d1544
Build:  2021-09-30 @ 19:56:44 on 'fv-az325-205/pipeline' with 'MSVC-19.16.27045.0' using JUCE 60101
System:  Windows 64-bit VST3 on        Intel(R) Core(TM) i7
Host:  Reaper

It appears that LFOs are able to modulate both Send FX 3 and 4 Levels.

**Comment by mkruselj** [comment]
Note: this is only a visual niggle. Voice LFOs actually don't end up modulating the send levels. It just appears as if they can, by mistake.

**Comment by ztnl** [comment]
Yes, merely appears as if they can be assigned.

**Comment by baconpaul** [comment]
<img width="608" alt="Screen Shot 2021-09-30 at 7 00 46 PM" src="https://user-images.githubusercontent.com/13387561/135540836-9bffd293-77b3-4ac7-9a00-16e69668d091.png">

the lack of a [2] and [3] there is the bug

**Comment by baconpaul** [comment]
that's in SurgePatch.cpp
