### ISSUE TITLE
Surge window resize does not size/render viewport correctly

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#5211]
**Bug Description:**
When I resize the Surge plugin window, redraw does not size/render viewport correctly, or [speculation] does not respond to the latest event.
This means one or more of:
1. When making the window bigger, Surge is rendered smaller than the window, with a black border to the right/bottom.
2. When making the window smaller, Surge is rendered bigger than the window, with scrollbars.
3. When opening a Surge instance, or maximizing, the render viewport may be too small and clip the canvas.

This happens with or without display scaling (200%, 100%) on Windows.

Selecting Zoom > 100% works fine.
Zoom  > 125% has scrollbars and a black margin where Surge is clipped to the right, after multiple resize events.
Zoom > 200% shows all of Surge, without scrollbars, with narrow black margins to the right and bottom about half the width of a scrollbar.

**Surge Version**
Version:  Surge XT 0.9.nightly.1e11513
Build:  2021-09-30 @ 13:46:18 on 'fv-az165-140/pipeline' with 'MSVC-19.16.27045.0' using JUCE 60101
System:  Windows 64-bit VST3 on Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Host:  Cakewalk by Bandlab

**Reproduction Steps:**
Open a new Surge instance, or resize an open Surge window.

**Expected Behavior:**
Surge scales the canvas to suit the resized window, without: scrollbars, clipping, or margins to more than one edge.

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following information):**
-

**Additional Information:**
Attached images show the result of a mouse resize.
While resizing, scrollbars pop in and out of existence and likely cause extra resize events.

![Surge resize - no VK - BL-to-TR resize](https://user-images.githubusercontent.com/13245475/136186689-9b93cf04-112c-4308-8275-79e543c51954.jpg)
![Surge resize - drag bigger](https://user-images.githubusercontent.com/13245475/136186695-1305eb0b-ed35-45a9-8310-a0d5d6b740c9.jpg)
![Surge resize - clip](https://user-images.githubusercontent.com/13245475/136186701-b70ace02-8390-4c6f-80d0-335b4b45c48a.jpg)

**Comment by VincyZed** [comment]
I also see a black border on the right and bottom in FL Studio:


![image](https://user-images.githubusercontent.com/50145178/137175715-80af509a-e19e-4ea1-bb9d-79d447b0245e.png)

**Comment by mkruselj** [comment]
@baconpaul I reckon we need to use `ResizableWindow::ComponentBoundsConstrainer` here to make the resize actions have a fixed aspect ratio.

**Comment by baconpaul** [comment]
yeah i thought about that and looked at the code but there was some reason it didn't work. lets keep this open and see if we can.

**Comment by baconpaul** [comment]
so i played with these APIs some this morning and couldn't get them to work. Harumph. Not sure about this one.

**Comment by baconpaul** [comment]
i think i'm just going to have to install cakewalk on my windows box to understand this bug. Sigh.

**Comment by baconpaul** [comment]
@mkruselj I wonder if the above, which improves the situation on mac, would also help windows so we could close this issue?

**Comment by mkruselj** [comment]
Standalone - works perfectly
Reaper - constrains to aspect ratio but Reaper's window can still be extended beyond aspect ratio. Thankfully not in a way that obstructs the actual GUI (until you get to very tiny zoom levels)
Studio One - works perfectly
FL Studio - works perfectly
Live 11 - works perfectly
Bitwig 4 - works perfectly

I have a couple other VST2 only hosts (MuLAB and Maschine) but we don't have drag-to-resize in VST2 (is there a way to quickly enable it just to test?)

I don't have Cakewalk so I will leave that to @j5v to test when he can get around to it. But we are looking pretty good! That said, Valhalla plugins are JUCE too, and they don't have that resizing issue in Reaper, they resize constraining Reaper's window as well. Maybe you could ping schwa on CLAP board and ask what's up about that? 🙂

**Comment by j5v** [comment]
Cakewalk behaviour is now not problematic. I haven't seen the 'missing resize events' problem for a few months, but my usage has been light.

When resizing a Surge instance in Cakewalk, I momentarily see old-style region invalidation (white background) when resizing, so it looks like there's more than one effective repaint while different APIs resolve the resize events. I suspect the earlier problem was due to one of these APIs not acting as expected in the stack.

[observation, perhaps not related to Surge] for magnification of less than 100%, aspect ratios outside the range 5:2 and 5:6, Cakewalk shrinks the content to fit the window without cropping. For other ratios, it expands the content to fill one dimension and crop the other.

**Comment by mkruselj** [comment]
@j5v So in short, situations like what you showcased in screenshots in opening post are not happening anymore in Cakewalk?

**Comment by baconpaul** [comment]
Vst2 does t have a host resize api so it really is just turn on the juce corner widget which generates the same events as our resize. If you want to do hat set the second argument of setresizable to true in surge synth editor but it will paint a corner booger over surge.

I’ll see if. Can figure out what Valhalla does differently yeah. But it seems like the change is the right change and this is fixed?

**Comment by mkruselj** [comment]
Yeah, Valhalla gets the corner booger too in VST2.

**Comment by mkruselj** [comment]
That said, I suppose we could override the paint method of [ResizableBorderComponent](https://docs.juce.com/master/classResizableBorderComponent.html)?

**Comment by baconpaul** [comment]
We have a zoom menu and keybindings. VST3 CLAP and LV2 support host drag. I don't think we want the component.

I'm going to close this I think!
