### ISSUE TITLE
kvr-ideas: a program that takes 16bit mono single-cycle wavfiles and assembles them into 1024 length .wt files for surge

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#522]
from https://www.kvraudio.com/forum/viewtopic.php?p=7306639

----
i'm not a programmer or i would do this: a program that takes a bunch of mono 16bit single-cycle wav files in a folder and randomly assembles them in your desired waveform length .wt files for surge, then dump the assembled .wt's into another folder. would be nice, huh?
----

**Comment by baconpaul** [comment]
Yeah so tackling Mac wav file has me having assembled most of this code in Mac and windows at least. Basically rebake something equivalent to audioterm. Not that hard. Just the list is long!

**Comment by baconpaul** [comment]
Oh it occurs to me that doing this in python makes it way easier.  Just adding that note here

**Comment by baconpaul** [comment]
Hey I have this done. PR coming in in a second.
