### ISSUE TITLE
Some delay presets are misspelled

### ISSUE THREAD

**Issue by sagantech** [surge-synthesizer/surge#523]
**Describe the bug**
Some delay presets are misspelled

**To Reproduce**
1. Go to surge
2. Click on delay
3. Scroll down to 'Rhytmic'

**Expected**
"Rhythmic"

**Additional context**
The source of the problem is hard to find but is contained within the file:
surge-1.6.0b1\resources\data\configuration.xml

**Comment by esaruoho** [comment]
the question is what happens when it is changed to `rhythmic` and a patch that uses this `rhytmic` preset tries to call a effect-preset that is not there. can you check what happens, @sagantech ?

**Comment by esaruoho** [comment]
@sagantech it is actually really easy to find by using `git grep rhytmic`

```
$ git grep Rhytmic
resources/data/configuration.xml:        <snapshot p0="-2.000000" p0_temposync="1" p1="-1.415038" p1_temposync="1" p2="0.484821" p3="0.830357" p4="-14.105346" p5="43.901775" p6="-1.179463" p7="0.091071" p8="0.000000" p9="0.000000" p10="1.000000" name="Rhytmic 1" />
resources/data/configuration.xml:        <snapshot p0="-1.000000" p0_temposync="1" p1="-0.415038" p1_temposync="1" p2="0.000000" p3="0.830357" p4="-14.105346" p5="43.901775" p6="-1.179463" p7="0.091071" p8="0.000000" p9="0.000000" p10="1.000000" name="Rhytmic 2" />
resources/data/configuration.xml:        <snapshot p0="-2.000000" p0_temposync="1" p1="-1.415038" p1_temposync="1" p2="0.484821" p3="0.334821" p4="-14.105346" p5="43.901775" p6="-1.179463" p7="0.091071" p8="0.000000" p9="0.000000" p10="1.000000" name="Rhytmic 3" />
```

**Comment by sagantech** [comment]
@esaruoho it seems like you don't understand the role I am playing right now in this open-source project. I am currently in a state where I am not building/testing or debugging. I am simply pointing out problems in the current source if I find them. If and when the Win7 debugging issue is addressed and resolved, I would be more than happy to come back and resume building/testing and debugging.

**Comment by baconpaul** [comment]
@esaruoho the presets aren’t what the stream patches the resulting parameters are. So changing the name is safe for existing patches.

**Comment by esaruoho** [comment]
@baconpaul cool, i'll change them

**Comment by esaruoho** [comment]
@baconpaul i baked a tiny three character PR at https://github.com/surge-synthesizer/surge/pull/524

**Comment by baconpaul** [comment]
Hi @sagantech did you see my comments and questions on #505 about debug surge in win32?

Thank you

**Comment by sagantech** [comment]
Which part exactly? I am using the latest version of VS2017!

**Comment by baconpaul** [comment]
Well any of it really! But also that part. Your version matches mine? 

Perhaps I am doing something different than you. Like I said I built debug w32 on win10 and ran the plugin without problem. What steps are you taking that show it not working?

Finally, it seems some windows versions mis-set _NO_DEBUG_HEAP. I wonder if building with _NO_DEBUG_HEAP=1 would solve your problem? 

I'm honestly trying to help you solve your problem, but every attempt I make to replicate it fails, so I think either (1) I don't understand what the problem is or (2) something is critically different between your environment and mine. Anything you can or choose to do to help us narrow it down would be welcome, if you are interested in the problem being solved.

Best

**Comment by sagantech** [comment]
I am running under Windows 7. To show it not working (last time I tried), I clone the repository, create the VS2017 vst project, add the win32 build configuration, set the debugger executable and the output file target destination to point to my VST plugins folder and then debug. That is it. This is not "my" problem. This problem was introduced with C++17.

**Comment by baconpaul** [comment]
I only meant it was "your" problem in the narrowest sense of "it is a problem you are experiencing" not that you caused it. Again acknowledging that we communicate poorly with each other, let me encourage you to read messages sent in this forum as constructive and not accusatory; that is certainly the spirit in which they are written

Thank you for sharing your workflow. Which executable are you using to launch the VST?

Best

**Comment by sagantech** [comment]
If you are asking which host, I am using [Metro](http://www.sagantech.biz/).

**Comment by sagantech** [comment]
BTW I appreciate you looking into this.

**Comment by baconpaul** [comment]
Thank you. 

I'm in the middle of setting up the vstgui branch but at my next available dev cycle let me download the metro demo and see if I can attach a debugger to it. 

Let me make a new issue for this and recap, OK?

**Comment by sagantech** [comment]
This is not a host issue.

**Comment by sagantech** [comment]
Also if you email me privately, I will set you up with a NFR copy.

**Comment by baconpaul** [comment]
Thanks. Mailed the support address on sagantech.biz. That will help!
