### ISSUE TITLE
XT: Gradient on dark skin shows defined dark lines

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#5239]
In this screenshot:

![image](https://user-images.githubusercontent.com/50145178/137177298-964d85b1-b22d-4492-9838-952f529ac19d.png)

Towards the right of the UI (in the middle of the FX section), you can see dark lines in the gradient. This is more or less what I see on my screen when using XT as well.

As a reference, @mkruselj said that "that is probably our radial gradient" a little while ago.

**Comment by baconpaul** [comment]
oh that circle cutting across there?
I wonder if the asset is just wrong. Does the edge of the gradient have transparency 0?

**Comment by mkruselj** [comment]
Yeah the edge of the gradient has 0% transparency. Howewver, Chromium/Edge seem to render that just fine, without that circle cutting across...

**Comment by mkruselj** [comment]
Don't think there's anything we can do about this one. Moving out of the milestone.

**Comment by mkruselj** [comment]
And actually, closing it for good, since for XT 2.0 we will redo the GUI anyways, and then we'll see what happens with stuff like this.
