### ISSUE TITLE
Linux: When mis-installed crashes on drop down menu

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#525]
When the left hand menu below the Oscillator is selected a drop down menu appears.

If the VST is in its initial state,
If clicking on either Wavetable or Window the VST and DAW/Host will crash
The other selections will not crash the app.

![vlcsnap-2019-02-06-15h25m57s880](https://user-images.githubusercontent.com/41337033/52372772-fa6bbf80-2a26-11e9-9b1d-62e15ba37875.png)

However if a Preset is loaded clicking on Waveform will not crash the app however clicking on Window will still cause a crash.

![vlcsnap-2019-02-06-15h26m40s276](https://user-images.githubusercontent.com/41337033/52372821-1b341500-2a27-11e9-82b3-edc3db6b8ad6.png)

Using Debian Stretch KDE plasma and Fast Track Pro USB audio sound card

**Comment by baconpaul** [comment]
Thank you again. These are really clear and useful bug reports!

**Comment by baconpaul** [comment]
Just quickly: Are these 32 or 64 bit builds? Can you screen shot the Menu/About screen for us?

I poked at it a bit tonight and didn't get exactly your crashes so want to make sure I'm doing apples to apples.

Thank you.

**Comment by tank-trax** [comment]
I only made 64 bit builds.

I was about to ask if you could explain where or what is the Menu/About screen, then I saw the Menu link at the bottom right hand corner. Funny thing is I never saw it until now... because it stays hidden in Linux until there is a Mouse Down/Click on that area. It does appear in the screen shot. 

Bad news is resizing does not work in Reaper. Good news is it works in Carla. However once resized the Menu option is dead. I noticed why. If made smaller the window that opens is misaligned towards the centre. I am thinking when enlarged the menu is flying off the grid.

FYI. The About and Manual links are dead.

Would it be possible to get involved on the design part and if so who would I contact to work on the GUI? 

I am seeing some other issues with the menu that I would post soon.

**Comment by tank-trax** [comment]
Here is an example of the menu displacement after resizing...

![surge resize 01 gif](https://user-images.githubusercontent.com/41337033/52389571-0f197900-2a62-11e9-9da8-10feca69767e.gif)

**Comment by baconpaul** [comment]
Yeah that menu repaint is part of Linux paint generally

The flyaway menus I had to explicitly fix on Mac and win. I wonder if either I conditioned that fix incorrectly or if it isn’t needed on Linux and is double applying. Easy for me to look and I have a bit of time today. Thank you!

**Comment by baconpaul** [comment]
As discussed on slack this crash occurs if the assets aren't in ~/.local correctly.

Keep the issue open because that should not crash, but lower priority

And link to #543

**Comment by baconpaul** [comment]
Ha so i just gave this a quick try before I close down for the night. The problem wasn't where I thought it would be!

```
#0  0x00007ffff1eb8235 in WavetableOscillator::convolute(int, bool, bool) () from ./target/vst2/Release/Surge.so
#1  0x00007ffff1eb8e20 in WavetableOscillator::process_block(float, float, bool, bool, float) () from ./target/vst2/Release/Surge.so
#2  0x00007ffff1e4c907 in COscillatorDisplay::draw(VSTGUI::CDrawContext*) () from ./target/vst2/Release/Surge.so
#3  0x00007ffff1f44e38 in VSTGUI::CViewContainer::drawRect(VSTGUI::CDrawContext*, VSTGUI::CRect const&) () from ./target/vst2/Release/Surge.so
#4  0x00007ffff1f453f6 in VSTGUI::CFrame::drawRect(VSTGUI::CDrawContext*, VSTGUI::CRect const&) () from ./target/vst2/Release/Surge.so
#5  0x00007ffff1f454ad in non-virtual thunk to VSTGUI::CFrame::platformDrawRect(VSTGUI::CDrawContext*, VSTGUI::CRect const&) () from ./target/vst2/Release/Surge.so
#6  0x00007ffff1f6405b in std::_Function_handler<void (), VSTGUI::X11::Frame::Impl::invalidRect(VSTGUI::CRect)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
   from ./target/vst2/Release/Surge.so
#7  0x00007ffff1f64ade in VSTGUI::X11::RedrawTimerHandler::onTimer() () from ./target/vst2/Release/Surge.so
#8  0x00007ffff1ed8494 in VSTGUI::LinuxRunLoop::idle() () from ./target/vst2/Release/Surge.so
#9  0x00007ffff1ed8549 in VSTGUI::LinuxAEffGUIEditor::idle2() () from ./target/vst2/Release/Surge.so
#10 0x00007ffff1e8332c in SurgeGUIEditor::idle() () from ./target/vst2/Release/Surge.so
#11 0x00007ffff1ebb25f in AudioEffect::dispatcher(int, int, long, void*, float) () from ./target/vst2/Release/Surge.so
#12 0x00007ffff1ebcafd in AudioEffectX::dispatcher(int, int, long, void*, float) () from ./target/vst2/Release/Surge.so
```

so yeah, of course, with no wavetables we can't render the wavetable oscillator

We should fail out more cleanly obviously. But want to avoid the problem above WaveTableOscillator; that code is called in the audio loop and we don't want to put an unnecessary if in there.

**Comment by baconpaul** [comment]
OK I fixed this so you no longer crash when there are no wavetables. PR forthcoming.
