### ISSUE TITLE
Patch DB / TypeAhead work for XT 1.0

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#5253]
- [x] Schema Upgrade broken with new scheme (requires double run)
- [x] Author and Category searches are in the grammar but not the SQL

**Comment by mkruselj** [comment]
@baconpaul There's still two semi-related issues left regarding patch typeahead, more visual though:

- [ ] Typeahead border is not drawn at all (it's set to black in the skin)

![image](https://user-images.githubusercontent.com/2393720/142738264-51196258-e8a3-49e4-9478-c1201f61b09d.png)

- [ ] At least on Windows, there's that prickly leftover/cutout at the bottom in the magnifier and heart icon SVGs (I see it on 125, 150 and 175 zoom here):

![image](https://user-images.githubusercontent.com/2393720/142738294-8da93366-bf3b-4569-a24c-a7fdeb2fb484.png)
![image](https://user-images.githubusercontent.com/2393720/142738295-0ed3a0f6-2ef9-4fca-bdfc-3a89f3dcf13b.png)

**Comment by baconpaul** [comment]
Thanks!
