### ISSUE TITLE
Portamento doesn't work correctly in octave-per-channel mode

### ISSUE THREAD

**Issue by cgibbard** [surge-synthesizer/surge#5259]
Several things go wrong in various mono modes.

In mono single-trigger mode, or mono single-trigger + fingered portamento mode:

Sending a note-on for key 0 on channel 3 and then sending another for key 0 on channel 4 results in ignoring the second note-on entirely, while it should result in an octave rise in pitch.

Sending a note-on for key 0 on channel 3 and then sending another for key 1 on channel 4 results in the same pitch being produced as key 1 on channel 3, when it should be an octave higher. Then, if you send note offs for both notes (in either order), the voice is latched on rather than ending, and will continue latching notes in other channels until an additional note on channel 3 occurs and finishes.

In mono fingered portamento mode:

Sending a note-on for key 0 on channel 3 and then sending another for any key k on channel 4 results in producing the higher note without a smooth portamento, but then if the note on channel 4 ends first, we don't hear the note on channel 3 again.

In mono single-trigger + fingered portamento mode:

There's something weird and special about channel 2. If we press key 0 in channel 2, and then any key other than 0 in any other channel, we get a portamento to a corresponding note in the same octave, but then when keys are released in either order, the voice is latched on, and continues to be latched on until another note starts and ends on channel 2.

In latch mode:

For reference, I'm testing this with Jacky Ligon's "Sines of our Times" patch, and I have the ED2-31.scl loaded. Switching into latch mode results in a note starting immediately, which, for some reason, is always the same C flat produced by note 29 on channel 3. Latch mode mostly appears to work other than that, except that if any note in channel 2 ends, it switches back to the mystery C flat.

Once I've been in latch mode, if I switch back to mono st+fp mode, or most other apart from mono fp, it seems to remain latchy, including the strange behaviour with channel 2 and the C flat thing.

Once I've been in latch mode, if I switch back to mono fp mode, it's mostly normal, except that when notes on channel 2 end, they result in C flat getting latched again.

I have a PR that I'm working on here which, despite the fact that I don't fully understand most of this behaviour, seems to fix a lot of it but still misses out on smooth portamentos when changing between channels/octaves of the same key: https://github.com/surge-synthesizer/surge/pull/5258

**Comment by baconpaul** [comment]
OK so: I have a test which shows the simple case failing in mono_st mode. Basically held and released keys are finding the wrong endpoint across channels. I'm going to commit that test with the broken cases ifdefed out and update here

**Comment by baconpaul** [comment]
OK @cgibbard I think in #5276 i have fixed most of this. We have good tests on mono voice management so if CI passes I'll merge it, but would appreciate a look and test also. I'll leave this issue open for other things which may arise.

**Comment by cgibbard** [comment]
It seems like it's fixed the portamentos on note-on, but the note-off still only looks for playing notes on the same channel.

**Comment by baconpaul** [comment]
OK yeah I have a good test now. And there's lots of things that still aren't quite there. Will hack away for a bit more

**Comment by baconpaul** [comment]
OK when I merge #5280 I think we are all done. If you don't mind checking that post merge (or grab the branch i you want) I would appreciate it. I can test this in retests but having the actual hardware is obviously more compelling.

**Comment by baconpaul** [comment]
@cgibbard I added some more tests for lowest (PR in) which all pass.

Time is sort of starting to catch up with us. We want to sort of do a beta freeze in 10 days or so, and I'm reluctant to mess with the voice allocator after that. Any chance we can get a set of tests or clear explanation of what is still wrong relatively soon? Otherwise we will ship as-is (which is way improved but I'm still not sure what is wrong).

**Comment by baconpaul** [comment]
Just a quick ping here!

**Comment by baconpaul** [comment]
As reported:

Okay, so I started with the Init Saw, changed it to sine, just to preserve my ears, turned on mono st, high note priority, set use midi channel for octave shift, and loaded 31edo.scl, apply tuning at midi input...
Then I played note 0 on channel 3
Well, let me list this more like midi events...
note-on 0 channel 3, note-on 10 channel 3, note-off 10 channel 3, (and then later) note-off 0 channel 3
after the note-off for 10, I expect to hear the same note as I heard after the initial note-on
but instead, I hear the same note as would be produced by note 24 on channel 3
(which seems like a 12-edo assumption creeping in somewhere)
i.e. that would be the C two octaves up in 12edo, which would still a little weird, but at least the right pitch class then
But in this scale it's Bbb
