### ISSUE TITLE
Win32 Debug Performance

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#526]
@sagantech reports that running the debugger on current codebase is prohibitively slow 32 bit debug win 7 build. Here's the facts we know so far

1. @sagantech w32 debug w7 metro with latest visual studio attached as debugger is prohibitive
2. @baconpaul w32 debug w10 running in bitwig no debugger attached works fine
3. @sagantech did not experience this on his codebase which is both before the alignas() changes and subsequent /c++17 switch

**Comment by sagantech** [comment]
If the only reason to switch to c++17 is to get alignment working under win32, I have a different alignment solution, I have also solved the priority inversion problem under windows 32 & 64 using a private heap.

**Comment by baconpaul** [comment]
Well the primary reason to switch was to allow the alignas() keyword to work, so yeah that is what motivated it.

I'd like to imagine there's a day where interesting sounding changes like the one you outline could get into the code base and into the hands of the users who download the synth from here. Hope we can figure out what's going wrong.

**Comment by sagantech** [comment]
My alignment solution is handled by my code so it cannot break regardless of the compiler. The code to fix the priority inversion you will not like and the most work on it requires removing std structures like <list> and it is currently platform dependent (win only). [push.back](http://www.cplusplus.com/reference/list/list/push_back/) apparently calls new/malloc so I had to replace it. Luckily there is already "max_voices".

**Comment by baconpaul** [comment]
Ahh yeah ... well that does sound a bit less mergeable! :)

But still I would like to solve this problem so you can track mainline (bidirectionally) as much as possible. Many of your changes are ones which would be great to integrate I'm sure.
