### ISSUE TITLE
Just contact Tunefish 4 author cause it’s the most lighter plugin down so you could maybe have some idea to help surge to be lighter in ressources :)

### ISSUE THREAD

**Issue by Leihael** [surge-synthesizer/surge#5263]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. e.g. I'm always frustrated when [...]

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by baconpaul** [comment]
Thanks for the tip!

**Comment by mkruselj** [comment]
Surge is mostly very efficient already...
