### ISSUE TITLE
Headless linux - surge exe runs, no sound, but expected console output appears

### ISSUE THREAD

**Issue by gminorcoles** [surge-synthesizer/surge#528]
This is not a feature request really.

On linux mint headless Surge runs and prints out the sample values and the little x's. 

Now what?

**Comment by baconpaul** [comment]
Someone writes the code to make it do the thing we want it to do!

I just did the factoring and build work to allow it to happen.

Ideas? If not I’m happy to toss some around!

**Comment by gminorcoles** [comment]
I intend to make this one of the synths that zynthian will load from its menu. They have their own way to control from their modui interface. I don’t have any idea of entry points or anything. But I guess making it load a patch from command line or api is a start. Sorry it will take me sometime to catch up in this domain.

**Comment by baconpaul** [comment]
No worries! We can also make multiple executables easily if needs be. We can take our time on the design here.

**Comment by baconpaul** [comment]
Heya I'm going to close this issue mostly because we just pushed a change to headless that shows you how to actually play note streams to a buffer and does so.
