### ISSUE TITLE
waveshaper popup gone with latest NIGHTLY-2021-10-21-fe94917

### ISSUE THREAD

**Issue by CurlyMC** [surge-synthesizer/surge#5290]
* Surge XT NIGHTLY-2021-10-21-fe94917
* Windows 10 / 64bit
* Reaper 6.38 / 64bit

Just a small awareness, in this latest nightly the waveshaper popup window is gone ( bug ? or feature :-).

**Comment by CurlyMC** [comment]
Hi Paul, well thats really strange. Over here there's no popup showing for the waveshaper anymore ( just for the waveshaper ).
The only thing happened, is that I did manage to drag this popup window outside the surge xt's window left top, but that was in the nightly version previous to this actual installed version ( NIGHTLY-2021-10-21-fe94917 ).
When I did drag the waveshaper popup outside Surge's XT window, I couldn't get it back in view anymore in the previous version.
Thats why I did instal this latest version reading "f4499a2 : Restore in-window drag bounds limits (#5288) - Paul" info.

**Comment by baconpaul** [comment]
So it saved the offscreennposition basically.

**Comment by CurlyMC** [comment]
..and I also did update Reaper from version 6.37 to 6.38 ( but I can't imagine this is causing this behaviour ).
Also after each install, I do copy the Surge XT.vst3 file from it's default installer location to my own vst folder, but that also never caused any issues.

Well is it possible that offscreenposition off the waveshaper popup is indeed saved ??

**Comment by CurlyMC** [comment]
Well, that did indeed fix it !!
Because I didnt find the waveshaper position line, I did remove SurgeXTUserDefaults.xml completely, restarted reaper, loaded SurgeXT, and the waveshaper popup is back. Fantastic, again you're my hero off today :-)

**Comment by baconpaul** [comment]
Cool

**Comment by CurlyMC** [comment]
well, so it is a feature :-) whahaha. 
Thanx again !
