### ISSUE TITLE
JUCE has corrected their mouseExit modal bug; adapt.

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#5318]
https://forum.juce.com/t/popupmenu-and-mouseexit/46822/5

**Comment by baconpaul** [comment]
I think the way to adapt in XT1 is to "not merge this change into our juce fork" and ship with juce where we have it
The correct change is to remove all the random endHovers and add a hoverable interface which has an 'upHover' and 'downHover' and so on for a counter.

But i'm gonna bump this out of XT milestone and just remember to leave our juce build where it is.

**Comment by baconpaul** [comment]
OK @mkruselj once I merge the above slider and multi switch should work

The trick is i've added a state to the base class which we increment and decrement properly. So the only change that *should* be needed is

in every widgets startHover add

```cpp
  if (incrementHover() > 1)
        return;
```

and in every widgets endHover add

```cpp
    if (decrementHover() != 0)
        return;
```

but then we have to test them all.

My theory is if we do that everywhere with the version I pushed, everything will work, and you can merge it and close this issue. Second best would be to do that everywhere, merge it, and add a checklist of things which *didnt* work to this issue and i can wrap it up. Third best is I am wrong and this doesn't fix anything other than the two cases i tried in which case, back to the drawing board!

**Comment by mkruselj** [comment]
Things left after PR #6019:

- [ ] LFO type
- [ ] LFO edit pencil
- [ ] Buttons in MSEG Editor
- [ ] Buttons in Formula Editor
- [ ] For some reason osc type menu doesn't work (hover disappears on RMB) but FX menu does work, and they have exact same code...
