### ISSUE TITLE
Wavetable display will sometimes go "outside" it's limitations, clashing with the rest of the UI

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#532]
I loaded the `Nick Moritz - PAD - Sorrowful` patch and put arrows where the wavetable actually goes outside of the UI limitations.

<img width="1787" alt="screenshot_07_02_2019__18_26" src="https://user-images.githubusercontent.com/4966687/52426075-f6629f00-2b05-11e9-8cbe-8f8673eedc1a.png">

**Comment by esaruoho** [comment]
same with `Noisegeek - Rubberband Fight`
<img width="234" alt="screenshot_07_02_2019__18_30" src="https://user-images.githubusercontent.com/4966687/52426339-76890480-2b06-11e9-96c2-da6a091ff417.png">

**Comment by esaruoho** [comment]
`ZooZither - zzsurge_Elephantshok`
<img width="651" alt="image" src="https://user-images.githubusercontent.com/4966687/52426557-e0091300-2b06-11e9-919b-449783565b3e.png">

**Comment by esaruoho** [comment]
wavetable clipping occurring
![wavetable clipping](https://user-images.githubusercontent.com/4966687/52426947-ae447c00-2b07-11e9-94d4-e577ec2ef547.gif)

**Comment by esaruoho** [comment]
this is what it looks like on Surge1.5.2 -- so, they always used to go above the limit. Looks weird.
@kurasu is this "over-the-topness" designed so that it implies that the wavetable clips?

![screenshot 2019-02-08 at 12 48 34](https://user-images.githubusercontent.com/4966687/52474267-a5ec4f80-2ba0-11e9-98ab-58c949ed4f08.png)

**Comment by baconpaul** [comment]
So looking at the code, it appears the toppling and bottom line are at 80% not 100% saturation. (COscillatorDisplay.h at line 47)

This code just works by sampling the oscillator and drawing the output. That means these wavetables actually are getting very close to 1.0.

Not quite sure what a fix is.

**Comment by baconpaul** [comment]
Still not sure what a fix is; I'm going to close this since I don't want to compress the display any further.
