### ISSUE TITLE
When using cursor left & right or category+/-, if you end up in an empty category (like a parent) nothing happens

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#533]
I opened a ticket about this ages ago, because it occurred with the +/-, but now i got it replicated with cursor keys left and right.

Steps to replicate:
1. Go to `ZooZither 3 - zzsurge_Brainstem` ( this is the last "factory" preset before the user presets start )
2. Press the Right cursor key.

Expected result:
You are now in `3rdparty/Analog Monsters - BRASSY`. (the first user preset category preset)

Current result:
Nothing happens.
Press Right cursor key again. You are now in `3rdparty/Analog Monsters - BRASSY`.

Now press left cursor once.
Expected result:
You are in `ZooZither 3 - zzsurge_Brainstem`. (the last library preset category preset)

Current result:
Nothing happens.
Press Right cursor again -and you are now in `ZooZither 3 - zzsurge_Brainstem`

**Comment by esaruoho** [comment]
here's the culprit "line". 
<img width="307" alt="fullscreen_07_02_2019__18_45" src="https://user-images.githubusercontent.com/4966687/52427488-aafdc000-2b08-11e9-875d-d75ae3960bac.png">

**Comment by esaruoho** [comment]
This "transcend the boundary" bug does not appear when in Factory `Wind` category and getting to `Argitoth`.. Only when crossing from factory3rdparty to "userpresets"

**Comment by esaruoho** [comment]
And the same issue will occur when at "wavetables" or "last userpreset category" and pressing right once = doesn't go to Bass. Press right another time = does go to bass.

**Comment by esaruoho** [comment]
Another addition: When you are in the same place (Zoozither) and press Category `+` - nothing happens. Press Category `+` again, and you will be in the first user-preset folder's first preset.

Same twice happens when you press Category `-` - need to press it twice to transcend the boundary.

**Comment by baconpaul** [comment]
The problem here is pressing "+" into a category which has children. So if your categories look like

``
zither
nested
nested/foo
nested/bar
```

(which they do) but nested contains no patches you end up with this behaviour

The fix is to skip patch-free categories in +/-

That's a bit tricky - won't do it right now i don't think

thanks @esaruoho good catch!
