### ISSUE TITLE
Linux: PatchSelector Crash 

### ISSUE THREAD

**Issue by mynameismuhl** [surge-synthesizer/surge#5337]
bd0973349653db862444fcdc64d9a4ed97ce0b60

RightClick on Patchselector menubar crashes

```
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_create
```

stack:
[rclick_n_crash.txt](https://github.com/surge-synthesizer/surge/files/7464861/rclick_n_crash.txt)

**Comment by baconpaul** [comment]
OK it works on mac. i can try linux next day or two
when the crash happened which category were you in?
does the crash happen every time?
thanks as always for the excellent bug report

**Comment by mynameismuhl** [comment]
Init Saw (thats "templates" I  think)
was crash on left and right click
after (re)installing resources its just right click
and yes every time

**Comment by baconpaul** [comment]
Ok I’ll look asap
