### ISSUE TITLE
A moved FX leaves behind modulations

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#5348]
**Bug Description:**
Modulations onto FX parameters are not moved when the FX is moved.

**Surge Version**
Version:  Surge XT 0.9.nightly.3988237
Build:  2021-11-03 @ 15:09:11 on 'WIN-EH9TN3FK03B/pipeline' with 'MSVC-19.16.27045.0' using JUCE 60102
System:  Windows 64-bit VST3 on Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Host:  Cakewalk by Bandlab

**Reproduction Steps:**
1. Add an FX to a patch
2. Modulate one of the FX parameters.
3. Move the FX. The modulation disappears.
4. Move the FX to the original FX slot. The modulation re-appears

**Expected Behavior:**
The modulation should remain with the FX as it moves.

**Screenshots:**
.

**Computer Information (please complete the following information):**
.

**Additional Information:**
If fixing this bug, also look at the more complicated variant, where the user **swaps** FX slots (much more fun!).

**Comment by baconpaul** [comment]
Oh good eyes

**Comment by baconpaul** [comment]
OK yeah this is "all sorts of broken". The code tries to do stuff but it just doesn't work properly. 

This is a good one for regtests!

**Comment by baconpaul** [comment]
Quick poll

We have three gestures, swap, copy, and move

swap and move are obvious

copy should copy modulation also?

I think 'yes' but want to be sure.

**Comment by mkruselj** [comment]
Yeah I think it should. Or maybe with a modifier?

**Comment by baconpaul** [comment]
I made it so it does :)
