### ISSUE TITLE
Linux Menu Clipping

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#535]
VSTGUI/Cairo paints the menu in the current window not in a new parent window (since it has no access to a parent window naturally).

As such menus bigger than surge clip.

<img width="414" alt="screen shot 2019-02-07 at 1 59 30 pm" src="https://user-images.githubusercontent.com/13387561/52435814-be953080-2ae0-11e9-8d3f-8b3085fd47a7.png">

Compare that with the mac equivalent

<img width="606" alt="screen shot 2019-02-07 at 2 00 57 pm" src="https://user-images.githubusercontent.com/13387561/52435853-d2d92d80-2ae0-11e9-9462-ea872016681a.png">

May be hard to fix.

**Comment by baconpaul** [comment]
First reported by @tank-trax

**Comment by rghvdberg** [comment]
I think we need to implement scrollable menus for this. 
I like the way Ardour handles these menus
![werkblad 1_008](https://user-images.githubusercontent.com/10710663/52706931-d2c8aa00-2f86-11e9-9f33-aa5bf53b68c6.png)
The little `⌄` scrolls the menu on mouse hover.

**Comment by baconpaul** [comment]
This problem seems to be fixed now I have the menu zooming and arrow keys working. I'll close it tomorrow when I sweep in my menu positioning vstgui fixes for linux.

**Comment by baconpaul** [comment]
Yup confirmed this is now all good. Closing and adding one other issue with our last two linux ui menu problems.
