### ISSUE TITLE
Crash upon loading these patches

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5351]
[Patches.zip](https://github.com/surge-synthesizer/surge/files/7491257/Patches.zip)

These patches have streaming version 10 (Surge 1.6.2), and upon loading they crash Surge hard (1.9 or XT doesn't matter).

In debug build, we get this:

![image](https://user-images.githubusercontent.com/2393720/140623962-7c39ac9c-a0aa-43d1-90c3-a74d675f90b2.png)

Then after continuing, we get:

![image](https://user-images.githubusercontent.com/2393720/140624077-cdb5c06a-f1cc-47f4-940c-4a89522468fc.png)

Which points to:

![image](https://user-images.githubusercontent.com/2393720/140624079-e47c7a68-5887-4c8b-9ddc-78cf29b9ab51.png)

**Comment by baconpaul** [comment]
Turns out these patches have corrupt headers so I'm gonna close the issue but #5352 makes the crash less crash-to-desktop and more -show-an-error
