### ISSUE TITLE
Renoise/VST2: temporary value popup could disappear less quickly

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#537]
* The temporary values that show up when editing a value disappear very quickly; too quickly to read. Not sure if this is just a Renoise thing.

from 
https://www.kvraudio.com/forum/viewtopic.php?p=7307924#p7307924

**Comment by kippertoffee** [comment]
This was my report (on KVR). I just tested it in Bitwig and it works as expected there, so it is a Renoise issue. Rather than describing it as the display values disappearing too quickly, it's more like they are only displayed on value change, then they disappear instantly.

**Comment by baconpaul** [comment]
Thanks. The pop up on change code is code we wrote in surge so could enitely be succeptible to event differences on different hosts. Appreciate the accurate bug report. 

Curious which os?

Thabks

**Comment by kippertoffee** [comment]
Windows 8.1

**Comment by baconpaul** [comment]
When we turn to debugging this, just as a note to either myself or some other dev, the code is in src/common/gui/CParameterTooltip.h

My bet is renoise is having the window go through a draw loop more frequently than the other hosts and/or the setDirty(false) at the end of draw is being ignored. I'd probably start with some sort of log in the draw method to see when I'm called and what visible is.

I don't have renoise or windows 8.1 but hope that helps whomever looks a this in the future, even if it's me!
