### ISSUE TITLE
Windows installer puts data folder where Surge can't find it

### ISSUE THREAD

**Issue by FineArtMaths** [surge-synthesizer/surge#5373]
**Bug Description:**
Running the installer on Windows 10 puts the data folder into C:\ProgramData, but installs the vst3 into the default location (in my case, C:\Program Files\Common Files\VST3). When trying to load Surge into a DAW it reports that it can't find configuration.xml and crashes. The user must search the hard drive for the folder containing this file, then move its contents into [VST dir]/Surge Synth Team/Surge Data, after which everything works correctly.

**Surge Version**
1.9.0.91069f8

* Version:
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Run the Surge installer on Windows 10, installing the VST3
2. Attempt to load Surge in a DAW

**Expected Behavior:**
Presumably this is dependent on environment variables but the installer should always put the data files in a place where Surge can find them, relative to where the .vst3 file was installed.

**Screenshots:**
N/A

**Computer Information (please complete the following information):**
 - OS: Windows 10
 - Host: Reaper
 - Version: 6.34

**Comment by ztnl** [comment]
Add this to your REAPER options Plugins/VST tab:

;C:\Program Files\Common Files\VST3

This will set the path for VST3.

**Comment by ztnl** [comment]
![image](https://user-images.githubusercontent.com/81161256/141479466-0fa9f41b-9810-43d7-a845-6b83fe0d45e2.png)

**Comment by FineArtMaths** [comment]
Cheers but that's not quite it -- Reaper knows where to find the Surge vst3 file, but Surge doesn't know how to find SurgeData because it's installed in C:\ProgramData, which isn't where it looks.

**Comment by baconpaul** [comment]
So the only reason it wouldn’t look there is if reaper has a different program files environment than the installer did

If you install the nightly of xt what result do you get?

**Comment by FineArtMaths** [comment]
Interesting. Work is about to intervene for a while but I'll try the nightly XT & update.

**Comment by baconpaul** [comment]
Cool
And if xt is incomplete snap a picture of the about screen here if you don’t mind since it will show all the paths

xt is very very close to our beta candidate and installs side by side with a new id so is safe to try

**Comment by FineArtMaths** [comment]
Nice -- the nightly XT build installed flawlessly, no issue at all.

**Comment by baconpaul** [comment]
Great.
So we are headed to XT beta in a week or two and not really updating 1.9; many folks got 1.9 working so there's 'something' about our installer and your world which is different, but since xt doesn't exhibit it, i'm going to close this issue if you don't mind?

sorry for the 1.9 problems but xt is gonna be way cooler!

**Comment by FineArtMaths** [comment]
Yeah of course, makes complete sense. Thanks for all the work on this great project!
