### ISSUE TITLE
Small issues with the Modulation List

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#5378]
Here are some bugs I found in the modulation list panel or related to it :

- Sticky hovers : "Filter By" and "Select Source" button menus stay hovered after opening them and clicking away to close the menu.
- Framerate dip when dragging the mod amount sliders in the mod list, or moving stuff in the background such as OSC parameters. It's definitely choppier, at least on my end.
- Clicking on the "Mute" icons doesn't seem to work (yet?).
- For some reason, at least in this picture, when Sorted by target, the second modulation in the list has its range values smaller than the rest, and has additional gray text reminding the mod target which is already written above.
![image](https://user-images.githubusercontent.com/50145178/141604610-54581d29-3bb2-4d7d-8d42-f5a1d3a7d111.png)

**Comment by baconpaul** [comment]
oh that font one is a great find. we don't reset the font after the little repeated label
rest are good too!
note button should work. i'll look. it works in the menu!

**Comment by baconpaul** [comment]
OK consolidated all of this in #5323 so will close this and just use that issue as the book of work. Thanks for the reports!
