### ISSUE TITLE
Indexed modulators incorrectly interact with some parts of UI state 

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#5380]
Here's how to reproduce :
1. Open a fresh instance of Surge XT.
2. Go straight to the Random or Alternate modulator - click on the hamburger menu and switch to another random type (or mouse wheel over it)
3. Engage routing mode. You will see the first issue here: you won't be able to modulate parameters of LFO-1 (just below) when normally you should.
![image](https://user-images.githubusercontent.com/50145178/141610006-bf639d49-5a18-4ded-89a2-8be85aa80d7a.png)

4. Apply some modulation to scene control(s).
5. Disengage routing mode. You will see the second issue: the modulation source will not have the bright border indicating that it is active.
![image](https://user-images.githubusercontent.com/50145178/141610012-c6eabedd-d1a4-4df7-8083-e16be9dccdc5.png)

You may try multiple times to do these steps if it doesn't work the first time.

**Comment by baconpaul** [comment]
great bug report
the reverse hovers (slider turns source green) are also broken

**Comment by baconpaul** [comment]
In fact, the reverse hovers are generally just not index aware. Make a formula and map 1 and 2 to some features of another LFO. The 1 hovers the formula even if it is set to 2
