### ISSUE TITLE
Sub-folders for EFX presets too

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#539]
currently configuration.xml is where the efx are stored. so you gotta kinda carve it up a bit to add more stuff.

Would be great to support sub-folders for EFX presets, so that we can have an `Arty` folder for Reverb + Distortion instead of dumping the Arty EFX parameters (for Reverb,Distortion, still trying to find the Delay ones) into the selector itself, like in the screenshots at #518

**Comment by baconpaul** [comment]
They are separate and the document surge one belongs with the safe fix ticket somewhere. Can we have this one just be the config XML subfolders and move the documents to the safe fix ticket?

The config XML alone one could almost be a good first issue type issue too!

**Comment by esaruoho** [comment]
ok, edited

**Comment by esaruoho** [comment]
Here's the arty snapshots for reverb

```
	<snapshot p0="-5.432145" p1="2" p2="0.400302" p3="-0.735899" p4="0.278571" p5="-1.275021" p6="0.000000" p7="0.000000" p8="36.991055" p9="1.000000" p10="0.000000" name="Arty Standard Reverb" />
		<snapshot p0="-8.000000" p1="1" p2="0.420187" p3="1.201775" p4="0.399732" p5="33.235435" p6="-1.592857" p7="24.004318" p8="26.215553" p9="0.250241" p10="0.000000" name="Arty HDIR Opera House Reverb" />
	        <snapshot p0="-8.000000" p1="1" p2="0.500088" p3="-0.736442" p4="0.199554" p5="14.214897" p6="61.120544" p7="20.144630" p8="36.393860" p9="0.250241" p10="0.000000" name="Arty Short Sustain Ambience Reverb" />
	        <snapshot p0="-8.000000" p1="1" p2="0.449729" p3="0.765167" p4="0.249645" p5="21.241875" p6="52.345413" p7="10.002838" p8="26.403572" p9="0.350447" p10="0.000000" name="Arty Warm Hall Reverb" />
```

Here's the arty snapshots for distortion

```
<snapshot p0="-14.400009" p1="43.723221" p2="1.944644" p3="70.000000" p4="0.000000" p5="0.000000" p6="0.000000" p7="3.000000" p8="2.031250" p9="33.333015" p10="0.000000" name="Arty Distort Warm 1" />
		<snapshot p0="-14.400009" p1="43.723221" p2="1.944644" p3="70.000000" p4="0.000000" p5="0.000000" p6="-20.057150" p7="37.125023" p8="2.031250" p9="33.333015" p10="0.000000" name="Arty Distort Warm 2" />
		<snapshot p0="0.000000" p1="3.873554" p2="1.944644" p3="33.234497" p4="0.000000" p5="0.000000" p6="0.000000" p7="2.240891" p8="2.031250" p9="61.103157" p10="0.000000" name="Arty Distort Warm 3" />
		<snapshot p0="5.039993" p1="21.238914" p2="1.944644" p3="26.235390" p4="0.000000" p5="0.000000" p6="3.985725" p7="2.237354" p8="2.031250" p9="42.229935" p10="0.000000" name="Arty Distort Warm 4" />
		<snapshot p0="5.039993" p1="21.238914" p2="1.944644" p3="14.228958" p4="0.000000" p5="0.000000" p6="3.985725" p7="2.237354" p8="2.031250" p9="26.222519" p10="0.000000" name="Arty Distort Warm 5" />
		<snapshot p0="6.004265" p1="47.901802" p2="2.999101" p3="70.000000" p4="0.000000" p5="0.000000" p6="6.004417" p7="54.079567" p8="2.998620" p9="70.000000" p10="0.000000" name="Arty Distort Bright 1" />
		<snapshot p0="9.995064" p1="52.254967" p2="2.003750" p3="70.000000" p4="0.000000" p5="0.000000" p6="10.000389" p7="61.096107" p8="1.999999" p9="70.000000" p10="9.995163" name="Arty Distort Bright 2" />
		<snapshot p0="19.997894" p1="-13.645096" p2="5.000000" p3="45.234993" p4="-0.428587" p5="0.000000" p6="14.001465" p7="2.237419" p8="5.000000" p9="30.083092" p10="-8.004837" name="Arty Deep Distort 1" />
		<snapshot p0="19.997894" p1="-13.645088" p2="5.000000" p3="45.234993" p4="-24.000000" p5="0.000000" p6="14.001465" p7="-9.079617" p8="5.000000" p9="30.083092" p10="-8.004837" name="Arty Deep Distort 2" />
```

I'd keep #518 open though unless if it bothers someone that a PR stays open

**Comment by baconpaul** [comment]
OK maybe this is a good second issue but it's not that hard

`CSnapshotMenu` subclass `CFxMenu` draws the actually menu. It does it by loading the `fx` segment from xml through the snapshot loader in storage. This happens in CSnapshotMenu::populate which you can see walks the XML pretty clearly.

It does this by walking a 2 level hierarchy. There's "types" which are the parent menu and "items" which are the leaves. The leaves set up as CCommandMenuItems which call loadSnapshot(type_id,nullptr).

So the trick is to make CSnapshotMenu::populate less of an explicit parent/child loop and let it recurse. So basically add a function called "populateForType" which populates a menu by iterating and either adding items when it finds an "item" or calling populateForType when it finds a type

Then make the XML look like

```
<fx>
  <type i="1" name="Delay/Chorus">
     <snapshot
     <snapshot
         <type i="1001" name="Arty Delays">
              <snapshot
              <snapshot
         </type>
     </type>
```

you get the idea. I chose "1001" since I didn't look too deeply into what the `i="1"` is used for. That's some research to be done when this issue gets tackled.
