### ISSUE TITLE
125% is more pixelated than 100%, and more pixelated than 150%

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#540]
from KVR 
https://www.kvraudio.com/forum/viewtopic.php?p=7308336#p730833 6

```
maybe I'm wrong - that zooming to 125% blurs the GUI
(more than 100%), while to 150% makes it crispy sharp
again. Is there some merit to this observation, or I 
just have to consult an optician?
```

from kvr 
https://www.kvraudio.com/forum/viewtopic.php?p=7308336#p7308336

**Comment by baconpaul** [comment]
The user is correct. We exported 100 and 150 assets but not 125 so on windows it intrrpolates.

I think 125 is turning out to be very popular so perhaps we should add the resolution. @itsmedavep how hard is this graphics wise? Easy code wise.

**Comment by baconpaul** [comment]
Oh and to confirm from slack: We are interpolating down from the 150 assets. Just 125/150ths isn't a very natural zoom.

But best thing is to make 125 a support resolution clearly.

**Comment by itsmedavep** [comment]
Ill hop on gettin getting a PR with 125% assets together tonight!

**Comment by baconpaul** [comment]
Thanks! I'm offline most of the weekend and have a busy Monday but can put the code change together next week or maybe Sunday night once they are there.

Appreciated.

**Comment by itsmedavep** [comment]
This exists #547 

Ill be busy with client work over the weekend.  I may find some time to work on stuff just not sure how much. Ill be online though.
