### ISSUE TITLE
Extract FX presets from configuration.xml to actual files + folders

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#541]
Would be awesome to be able to grab the configuration.xml preset EFX and make them available in ~/Documents/Surge/EFXPresets or something like that. Or in the /Library/Application Support/Surge.

**Comment by baconpaul** [comment]
Connecting this with #378

**Comment by mkruselj** [comment]
So this won't happen for factory presets, but now you can save your own presets in the user data folder. You can totally port over all factory presets and just not worry about them ever again (can remove them from config.xml after you resave them to individual .srgfx presets). Closing this one!
