### ISSUE TITLE
Group labels in surge-fx are mislabeled 

### ISSUE THREAD

**Issue by mynameismuhl** [surge-synthesizer/surge#5414]
For any Fx with more than 6 params 
the Group labels display wrong names 
example:
![surge-fx](https://user-images.githubusercontent.com/80534683/141865081-22eb91ab-a900-4855-8c28-70a552cad9a4.png)

**Comment by baconpaul** [comment]
<img width="917" alt="Screen Shot 2021-11-15 at 7 29 16 PM" src="https://user-images.githubusercontent.com/13387561/141873984-1d277c9f-9bba-4415-9e84-611ef8893489.png">

Just so I can compare without keeping both open sticking this here as note to self
