### ISSUE TITLE
Linux Paths

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#542]
@falkTX @tank-trax @rghvdberg and @jsakkine heya!

So lets get linux paths sorted out.

Remember Surge has two core paths it cares about

* dataPath 
   * Stores the factory and 3rd party patches and wavetables
   * Stores configuration.xml on mac and windows (on Linux it is compiled in)
* userDataPath
   * Stores user patches when they save them using the "store" button

These paths are as follows

* Mac
   * dataPath = ~/Library/Application/Surge if it exists and /Library/Application/Surge if it does not
   * userDataPath = ~/Documents/Surge
   * This is correct behavior and we shouldn't change it
* Windows
   * dataPath = %LOCALAPPDATA%/Surge
   * userDataPath = `My Documents`/Surge where `My Documents` is the OS setting for your documents folder
* Linux
   * Built from master
      * dataPath is $XDG_DATA_HOME/Surge if it exists and ~/.local/share/Surge if it does not
      * userDataPath is ~/Documents/Surge
   * As patched by @falkTX for kxstudio using his packaging mechanism
      * dataPath is /usr/share/Surge
      * userDataPath is ~/Documents/Surge

So there's a couple of things which would be great to change

1. @falkTX your packaging step changing the code - it would be ideal if we didn't have to do that. Can we merge your change into master somehow?
2. It would be great if there was a mac-equivalent of look-local then look-global. So can we do the same trick of looking in ~/.local/... and if that doesn't exist look in /usr/share? Or the other way round, depending on what is more "linux-y"
3. Can we figure out what @esaruoho should put in the manual as correct behavior?

I don't think this is a big change. In fact I think most of it just happens if we check /usr/local in the mainline if ~/.local doesn't work just like mac does literally 30 lines above the code which does the linux setup (which is at around like 150 of SurgeStorage.cpp). 

But I don't know what linux users expect. Nor what windows users expect. I just know the mac behavior is correct.

Getting this cleaned up before we have lots of linux users would be super duper. 

Thanks!

**Comment by tank-trax** [comment]
to confirm, the command

`./build-linux.sh install-local 
`

will create the Surge folder in ~/.local/Share and add the contents of the surge/resources/data/ folder

- the Surge folder in ~/Documents/ gets created with the first user preset is created


would it be possible to update the Locations section of the front page and README to add

```
Linux
For user-made presets, the folder is ~/Documents/Surge
For Surge factory presets, wavetables and preferences, the folder is ~/.local/share/Surge
```

**Comment by jsakkine** [comment]
Packaged version should put them under /usr/share/Surge e.g. we need install command to do that. For that there should be a separate command `install`.

**Comment by jsakkine** [comment]
What is the standard path for VST plugins in Linux?

**Comment by rghvdberg** [comment]
local install `~/.vst` `~/.vst3`
system install `/usr/lib/vst` `/usr/lib/vst3`

**Comment by rghvdberg** [comment]
also, I prefer lowercase in paths  ~/usr/share/Surge~ `/usr/share/surge`

**Comment by jsakkine** [comment]
Why in some places they refer to /usr/lib/lxvst as the location for VSTs? Like for example VST synth called Helm. https://tytel.org/helm/

**Comment by rghvdberg** [comment]
good catch, I actually got that dir too, but only Helm in it.
very odd, gonna ask in #lad (freenode)

**Comment by jsakkine** [comment]
Hope that at least that the LAD world could do. Easier problem than getting single audio server like CoreAudio on macOS. Don't get this PulseAudio and Jack mess that exists at all.

**Comment by rghvdberg** [comment]
from LAD 
"lxvst is a path made up only by ardour, and no one else"
/usr/lib/vst ftw

**Comment by jsakkine** [comment]
I mean with systemd, Wayland (yes it is very usable, use it on my work laptop) etc. everything else is pretty much the same same across all the major distributions except audio, which is like back to the 90s Linux world... Sorry, wanted to let this all out.  Won't complain anymore :)

**Comment by jsakkine** [comment]
Thanks! PR coming up.
