### ISSUE TITLE
Surge when mis-installed should be much noisier

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#543]
@tank-trax found a lot of problems on linux around crashes and non working elements which were all because his `~/.local/share/Surge` was not correctly populated.

Now of course Surge shouldn't crash in those situations and so on but also: Surge should report that it can't find information.

So I propose a simple check, at the end of SurgeStorage, that if wavetable count is 0 or factory patch count is 0, we show a user error clearly reporting the problem. If we follow good install procedures this should "never" be needed. But it could have saved some headaches for @tank-trax and will for other users in the future I bet.

**Comment by baconpaul** [comment]
The way to do this is as follows.

* read #542 so you know where everything is going
* src/common/SurgeStorage.cpp
* in the function "refresh_patchlist" if no patches are found before user category (so if firstThirdParty == 0) throw up an error with Surge::UserInteraction::PromptError
* in `refresh_wtlist` try to figure out with the Surge::UserInteraction which is already there doesn't fire. It's either a bad condition or (maybe) we create categories even if the directory is empty because we don't require any files to be found to create a category above

To test

* build and install
* remove your appropriate directory containing user patches and wavetables
* Run the synth and make sure you get error messages
* re-install
* remove just the patches and test
* re-install
* remove just the wavetables and test

For "re-install" any of the install-local options should be fine.

**Comment by tank-trax** [comment]
just an FYI

the location for factory and 3rd party presets and wavetables would be Linux is ~/.local/Share/Surge

after placing the contents or /surge/resources/data in ~/.local/Share/Surge many previous reported issues resolved
