### ISSUE TITLE
SVG Image Clip Goobits on Windows

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#5437]
- [x] ![image](https://user-images.githubusercontent.com/2393720/142738294-8da93366-bf3b-4569-a24c-a7fdeb2fb484.png)

- [x] ![image](https://user-images.githubusercontent.com/2393720/142738295-0ed3a0f6-2ef9-4fca-bdfc-3a89f3dcf13b.png)

- [x] ![image](https://user-images.githubusercontent.com/2393720/115920845-082c8480-a47b-11eb-928a-53ef979b088a.png)

Figure these out

**Comment by rovingeye** [comment]
![mseg](https://user-images.githubusercontent.com/68129072/142944240-daadca99-56ac-4d6b-b1a9-1ed9f786ed58.gif)

**Comment by mkruselj** [comment]
![env](https://user-images.githubusercontent.com/2393720/143059231-ab901e54-1f90-4078-9928-8d41b23a5e02.gif)

**Comment by baconpaul** [comment]
The MSEG problem was code
The rest has to do with strokes which exactly abut the image edge bleeding into the neighbor at zooms due, I think, to the zoomed anti-aliasing of the 1px stroke and subsequent clip. Rework the SVGs, alas, is the answer on those.

**Comment by baconpaul** [comment]
@mkruselj What do we need to close this? There's no more code to be written its just adjusting that mseg handle graphic?

**Comment by mkruselj** [comment]
Yeah I'll give a shot for the envelope graphics but might also bump it out of milestone.
