### ISSUE TITLE
Overlays don't stay fronted on skin refresh

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5445]
As below:

![image](https://user-images.githubusercontent.com/2393720/142914342-70f66646-41f8-4564-9e89-7cfc5bfb9201.png)

![image](https://user-images.githubusercontent.com/2393720/142914352-88436cfd-0c29-4e51-86b1-090e4565b814.png)

**Comment by mkruselj** [comment]
Reopening for one edge case:

1. Open MSEG editor
2. Click patch save button
3. F5 to refresh skin

Result: MSEG goes in front of patch save (which is supposedly modal)

Expected: patch save is modal so should be always on top.

Miniedit is also modal but they autoclose on skin refresh so we need not worry about them. But patch save should be always on top.

**Comment by baconpaul** [comment]
yeah that one may be hard to fix. the z-order on skin refresh is lost

**Comment by baconpaul** [comment]
this is all related to #5512 basically
the mseg/formula is 'special' in an annoying way and i want to make it non special and the skin refresh actually replaces components.
this edge case may bounce out of the xt milestone basically

(note as of last night you can change Z order by clicking on a title bar)

**Comment by baconpaul** [comment]
Managed to fix this extreme edge case in XT1. When you press F5 with a patch over the mseg, the mseg blinks through (fixing that required #5512) but then the modal overlay re-fronts. Will merge that and close this issue and the blink through will get fixed when #5512 gets done
