### ISSUE TITLE
Scaling of Delete Patch dialog is blown up compared to others

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5446]
![image](https://user-images.githubusercontent.com/2393720/142915375-ca0163ba-1844-40c5-a908-d0bc51013a32.png)

vs

![image](https://user-images.githubusercontent.com/2393720/142915422-826b327c-2bea-4060-95ad-d2f3647de2bc.png)

**Comment by baconpaul** [comment]
Oh this is because i give it a parent component as opposed to nullptr. easy fix.

**Comment by mkruselj** [comment]
Oh I think I see that. I can do that!
