### ISSUE TITLE
Surge fails in qtractor linux

### ISSUE THREAD

**Issue by davephillips** [surge-synthesizer/surge#545]
Fedora 23 Linux
GCC 5.3.1

Greetings ! Just a quick report on the deployment of Surge on my system. I build the synth from the latest git codebase and can test it in a variety of DAWs. What I've got so far:

QTractor (latest) - Surge is found by the program but QTractor crashes when it tries to load the plugin.
Ardour6 (beta) - Plugin not found.
Carla (latest) - Plugin loads but sound is nothing but clicks and pops.
VCV Rack (v0.6.2c) - Plugin loads via Host module and works perfectly there.

Please note that I build all these programs from source, so they're probably not the versions that most users have. Other users on the Linux Musicians forum have reported success with Carla but I think they're using the version in falkTx's repos.

Anyway, vast thanks to all the developers involved in this project, keep up the fine work !

**Comment by baconpaul** [comment]
Thanks Dave! We had another report of QTractor so something is definitely up there. And I didn't know Rack even had a VST host yet! How cool? (I have a small set of rack plugins I wrote 6 months ago).

This is very useful. 

Did any of them give any odd looking error messages or stack traces?

And appreciate the thanks!

**Comment by davephillips** [comment]
@baconpaul  I suspected you were the same fellow who did the plugins ! :) The Rack VST Host module is a commercial offering from Andrew Belt, it works very well with most of the plugins I've tried, including the u-he synths. 

QTractor kicks out quite a nice stack trace, I've posted it at  https://pastebin.com/rdrwiWv4. 

I also used the Bitwig plugin host to test it, got the same results as other users have reported:

```
$ /opt/bitwig-studio/bin/BitwigPluginHost64 test ~/.vst/Surge.so
--------------------------------------------------------------------
Testing plugin /home/dlphilp/.vst/Surge.so
About to start the following process:  /opt/bitwig-studio/bin/BitwigPluginHost64 host 44100 256 27971-1 1
Successfully set thread realtime priority to 19
Creating plug-in instance
Waiting for reply...
Could not test plug-in: createAEffectInstance returned NULL.
Lost connection on audio thread: End of stream
Passed plugins:

Failed plugins:
    /home/dlphilp/.vst/Surge.so:      createAEffectInstance returned NULL.
Passed : 0 Failed: 1

```

So no new news there, I guess, but at least it verifies what others have found.

**Comment by baconpaul** [comment]
Just FYI: We fixed bitwig yesterday as well as a variety of other problems.

**Comment by baconpaul** [comment]
Hey @tank-trax if you get a chance in the next week or two, can you check a couple of these hosts with 1.6.1.1 and see if we are any closer? I think QTractor still blows out; and I run Carla regularly (from the repo); but taking a look at Ardour would be great if you can.

**Comment by tank-trax** [comment]
Qtractor still explodes when loaded. Ardour's stable release is 5. Ardour 6 is still in development. I tested Surge in Ardour 6 and it loads without issue. The only host that it has problems with in Linux as far as I know is Qtractor. All others work perfectly.

To my understanding the issues in this ticket (apart from Qtractor) have been resolved many builds ago.

**Comment by baconpaul** [comment]
Thanks! I will rename to qtractor fails then

**Comment by tank-trax** [comment]
there is an issue with the new SCL feature and Waveform 10 
when Zenity is called it is below the app so in order to access it must use the Move function, it's impossible to move or Minimize Waveform as Zenity owns the screen even though it is not the top element

![wf10 zenity scl](https://user-images.githubusercontent.com/41337033/59889738-c5d81f00-939b-11e9-9fff-e0bb811821f3.gif)

also Surge will freeze Waveform if one of the patches that can't load is selected -> related to https://github.com/surge-synthesizer/surge/issues/924

**Comment by baconpaul** [comment]
I wish linux was a desktop OS. Sigh.

Well thanks for the report! I know the problem with #924 but no idea what's here. Maybe zenity has an --ontop option or something. I'll look.

**Comment by baconpaul** [comment]
https://askubuntu.com/questions/197099/zenity-window-on-top look at that insane answer.

**Comment by tank-trax** [comment]
I almost posted a *sigh* earlier

**Comment by tank-trax** [comment]
it doesn't happen in Carla, Renoise or Reaper, so far only in Waveform 
I've seen this behaviour before with Waveform and another VST
possibly because Waveform is built using JUCE and draws things 'uniquely'

**Comment by tank-trax** [comment]
also, Zenity is not working in Ardour or Mixbus (which is based on Ardour)

**Comment by baconpaul** [comment]
@tank-trax hey I think JP’s fix where he increased the buffers fixes this issue; can you if you have a moment check a recent surge in qtractor and if it works close this issue for us? Zero rush of course!

Thanks!

**Comment by tank-trax** [comment]
The Zenity menus work in Ardour now. however the same issue with Waveform and Zenity layers persists, but will close this issue as Surge VST2 in qtractor loads fine.

**Comment by baconpaul** [comment]
Thanks!
