### ISSUE TITLE
Ellipses in context menus

### ISSUE THREAD

**Issue by ztnl** [surge-synthesizer/surge#5452]
Version: Surge XT 0.99.nightly.f0a5482
Build: 2021-11-23 @ 02:22:09 on 'WIN-QI2H93HHA86/pipeline' with 'MSVC-19.29.30137.0' using JUCE 6.1.2
System: Windows 64-bit VST3 on        Intel(R) Core(TM) i7
Host: Reaper @ 48.0 kHz

As I'm continuing with beta-testing (now with the active newest betas), all features that interact with the two microtuning modes: SCL-KBM and MTS-ESP, wanted to make a small aesthetic suggestion about the Tuning menu:

Please consider dropping the "..." from the end of some of them menu items for consistency and a cleaner look, which will also be a nice enhancement when writing documentation about these features.

Not a bug, but have some actual in the queue for discussion ahead and need a place to consolidate reports.

![image](https://user-images.githubusercontent.com/81161256/143039877-16b89f60-0084-485a-b78b-c97d0fa30bd8.png)

**Comment by mkruselj** [comment]
Ellipsis is there because that's normal for menu entries which open a new dialog or change contexts. It's also a convention in both Windows and macOS to do that in exactly the same situation, so we're just doing the same thing as them.

**Comment by baconpaul** [comment]
Yeah the … bug me also but they are consistent with the rest of both main oses when you open a window from a menu.

**Comment by mkruselj** [comment]
With that said, let's please keep things to one github issue per report in the beta phase, so closing this one after renaming it appropriately.

**Comment by baconpaul** [comment]
Yeah lots of small issues best working model if we can agree. Thanks both!
