### ISSUE TITLE
Tooltip hover timer not reset on rebuild (probably)

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5457]
As per this video:

https://user-images.githubusercontent.com/2393720/143131552-a1145968-2372-4c5d-8bfb-c8c1bc637d9b.mp4

**Comment by baconpaul** [comment]
ugh this one is a bit painful

**Comment by baconpaul** [comment]
Oh I fixed this in https://github.com/surge-synthesizer/surge/commit/d04ac3d3a2233e5532e9e46c4d614d6da6084035 and forgot to tag this issue.
