### ISSUE TITLE
MTS-ESP and Portamento

### ISSUE THREAD

**Issue by ztnl** [surge-synthesizer/surge#5458]
Version: Surge XT 0.99.nightly.4490f0e
Build: 2021-11-23 @ 17:29:02 on 'fv-az98-635/pipeline' with 'MSVC-19.29.30137.0' using JUCE 6.1.2
System: Windows 64-bit VST3 on        Intel(R) Core(TM) i7
Host: Reaper @ 48.0 kHz

**When the intonation of Surge XT is being controlled by MTS-ESP Master, any scales with </> 12 notes create one-note portamento glides**

To reproduce:

1. Load SXT and an instance of MTS-ESP Master into a DAW project.

2. Load any </> 12 size scale into the MTS-ESP Master Scale List.

3. Set the SXT Portamento slider to a positive value (such as 1 to 2 seconds).

4. Play single repeated MIDI Notes from an external MIDI controller below and/or above middle C.60.
 
Notice that around C.60, the portamento is stable, but when playing notes further away from middle C, there an increasingly pronounced pitch-bending effect from only single note input. Note also that scale size has an affect on the depth of the glide.

**Comment by baconpaul** [comment]
Oh thank you.
Can you let me know which voice mode you are in when you here this?
I have an idea.... but it may be different in mono_fp vs mono_st etc...

**Comment by baconpaul** [comment]
(my guess by the way is the 'portable starting point' is not key adjusted - and in theory the same thing may happen if you use native with tune before midi)

**Comment by baconpaul** [comment]
yup here's another way to repro

1. Load init sine
2. Load a long scale like ED2-22
3. Set the tuning mode to "tune after modulation"
4. Set porta to 2 seconds
5. play a high note like C6. You may hear an initial glide from wherever but repeated notes after that will be fine
6. Set the tuning mode to "tune at midi input"
7. Play a high note like C6. Each and every time you get a portable

So I think what's happening is the 'retune at midi input' (which really means 'remap the keyed and stay internally in 12-tet) which is also how MTS-ESP works is setting the portamento target on note on to the unmapped key not the mapped key.

Great great find.

**Comment by baconpaul** [comment]
oh and in theory a 12 tone scale with some notes "very" off tune (so like the cents are 0 1 2 3 4 5 6 7 8 9 10 1200) should exhibit a similar problem

**Comment by ztnl** [comment]
Thanks for the confirmation and explanation. That's really interesting that it also happens in SCL-KBM mode. Hadn't noticed that yet, so good mutual catches.

Voice mode was Poly during that test. Let me know if there's anything else I can check here.

**Comment by baconpaul** [comment]
Nope I have what I need. I’ll tag this issue when there’s a fix, thanks!

**Comment by baconpaul** [comment]
OK i have this trapped in the regtest engine. Good.

**Comment by baconpaul** [comment]
And then it was a small fix. Inbound.

**Comment by ztnl** [comment]
> And then it was a small fix. Inbound.

Fantastic news. Glad it was an easy fix and thanks for it.

**Comment by baconpaul** [comment]
Oh my fix may only fix native not MTS so reopening until I confirm

**Comment by ztnl** [comment]
Yes, just noticed this going through my testing routine this morning. Thanks for the confirmation here.

**Comment by ztnl** [comment]
Should add from beta-testing notes:

Still happening in build d66cc10 with MTS-ESP Master loaded for all Play Modes, except Mono ST+FP.

**Comment by ztnl** [comment]
What follows should perhaps go in a separate issue, but pasting it here for related interest:

**Related finding for both microtuning modes: With Glissando and Retrigger At Scale Degrees checked, the degrees appear to be related to 12-equal. Tested with ED2-31 and a glide across 31 MIDI Notes, plays 12 retriggered notes.**

[Let me know if I should actually create a new issue for this one, since it's actually not directly related to the one-note portamento behavior with MTS-ESP.]

**Comment by baconpaul** [comment]
that's a separate issue and is trickier. In RETUNE_AT_MIDI/MTS mode portamento is in key space so retrievers when you run over a key. If you work in RETUNE_AFTER_MODULATION it should work. But we should open a separate issue, since I have this particular one closed. I'll do that now.

**Comment by baconpaul** [comment]
#5483

**Comment by baconpaul** [comment]
Anyway the MTS-equivalent fix that I made for native on portamento is in now. This will close again when it's merged. This time I actually tested it with MTS not just native!

(wish: MTS could run in the test harness. Sigh.)

**Comment by ztnl** [comment]
Thanks for the quick fix. Once the new build is up, I'll double check it here again too.
