### ISSUE TITLE
Pitch Expressions from Bitwig do not repond in Surge 

### ISSUE THREAD

**Issue by sense-amr** [surge-synthesizer/surge#5461]
bitwig allows pitch of a clip to be altered in a controlled yet potentially chaotic way ..

![image](https://user-images.githubusercontent.com/1504019/143172681-d25ed88c-d729-446f-87fd-6db646605bdd.png)

When using the Pitch Expression on a clip .. on an instrument with SurgeXT or Surge .. on it .. there is no change of the pitch 

This occurs in both bitwig 4.0.8 Latest stable release.. version of bitwig ... and also the Beta 4.1 beta 5 version..

i urge someone with bitwig to try it out and see ...

Surge simply does not respond to these Pitch Expressions

**Comment by sense-amr** [comment]
i've also sent a bug to bitwig about this .. so lets hope its from their end .. since it wont work for any non bitwig synths either ,.,

**Comment by sense-amr** [comment]
actually ill close this because it must be a bitwig issue..

**Comment by sense-amr** [comment]
i will revisit this after i hear from bitwig ..

**Comment by sense-amr** [comment]
Synth requires micropitch support ..

**Comment by mkruselj** [comment]
This probably ties into VST3 Note Expression, which Surge doesn't support (and is actually [the oldest issue we have](https://github.com/surge-synthesizer/surge/issues/11), opened by Claes himself). Unfortunately, JUCE has no means of supporting VST3 Note Expression, so this is not going to happen until JUCE somehow supports them (if ever).
