### ISSUE TITLE
Scene Morphing A B Slider 

### ISSUE THREAD

**Issue by sense-amr** [surge-synthesizer/surge#5468]
It would be awesome .. to have a slider to morph between scenes.. 
a slider that could be modulated by SLFO or LFO .. 
i think it would bring a great new potential to surge patch creation .. 

now i wait for someone to tell me it cant be done :D

**Comment by baconpaul** [comment]
What’s the difference between that and just cross fading?

**Comment by mkruselj** [comment]
Morphing continuous parameters makes sense. Switches/integer parameters, not really. Also, morphing doesn't make sense if the scenes don't contain same things in same places (i.e. same oscillator type for oscillator 1, etc).

**Comment by baconpaul** [comment]
Oh yeah right. What to do if scene a osc 1 not the same as scene b osc 1. 

But gotcha. Basicalky a big single mod slider between all the parameters if all the discrete types line up

**Comment by mkruselj** [comment]
Yeah but... I think doing this between scenes is really just not practical, both code-wise (too many things to check if they match etc) and UX-wise.

**Comment by baconpaul** [comment]
Right you more want a single scene to have 2 param configurations and you morph between them or some such. Kinda like if you auto assigned a macro to two endpoints on every continuous slider

**Comment by mkruselj** [comment]
No, have the whole patch to have 2 param configurations. Both scenes (and macros) included!

**Comment by sense-amr** [comment]
Scene morph A B was really only considering their main output ...cheers

**Comment by baconpaul** [comment]
Oh then you can do that today! Just modulate their output level with a macro

**Comment by sense-amr** [comment]
OK fantastic

**Comment by sense-amr** [comment]
More appropriately my request was a "scene mix" slider

**Comment by baconpaul** [comment]
Right
so if you run XT you can look at the formula tutorial for cross fades
you can use the same technique to cross fade any mixer element you want if you are an SLFO
and the each scene has a separate volume
So make a modulation source which fades scene A volume from 0 -> 1 and scene B volume from 1 -> 0 and you get what you want. You can do it linearly with just a simple macro but you can also use power laws if you look at that formula tutorial.

**Comment by sense-amr** [comment]
yeh i dont know how to route an SLFO to a macro ..

**Comment by baconpaul** [comment]
a macro to an SLFO actually. That's shown in the tutorials but you only need it if you want a power law for your cross fades.

I should just make an example of this in the tutorials. Jacky had asked about it also.

**Comment by baconpaul** [comment]
[Scene Cross Fade.fxp.zip](https://github.com/surge-synthesizer/surge/files/7599145/Scene.Cross.Fade.fxp.zip)

Here you go. That has a macro that crossfades between two scenes for you
