### ISSUE TITLE
Loaded SCL-KBM names showing in Tuning menu when in MTS-ESP mode...

### ISSUE THREAD

**Issue by ztnl** [surge-synthesizer/surge#5485]
Version: Surge XT 0.99.nightly.d66cc10
Build: 2021-11-25 @ 03:25:31 on 'WIN-VJ1J0M0KRJQ/pipeline' with 'MSVC-19.29.30137.0' using JUCE 6.1.2
System: Windows 64-bit VST3 on        Intel(R) Core(TM) i7
Host: Reaper @ 48.0 kHz

Loaded SCL-KBM names showing in Tuning menu when in MTS-ESP mode...

![image](https://user-images.githubusercontent.com/81161256/143460225-749b92b3-44d1-495f-9315-6eb8445b9e25.png)

**Comment by baconpaul** [comment]
Right that ed2-21 at bottom is the scale name from mts and should replace the top stuff in mts mode

**Comment by ztnl** [comment]
Splendid idea to move that to the top. Agreed.
