### ISSUE TITLE
Figure out why hover for FX preset jog doesn't work in Royal Surge

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5488]
Exactly as above.

**Comment by baconpaul** [comment]
Do the other jogs (patch category etc) work!

**Comment by rovingeye** [comment]
[testskin.surge-skin.zip](https://github.com/surge-synthesizer/surge/files/7604898/testskin.surge-skin.zip)

This test using the classic assets shows that hover_image is not working properly. Both methods from the skin guide are shown not working for hover_image= but image= seems to work. Is this an XML problem or a code problem?

**Comment by mkruselj** [comment]
They do but they use the default asset. FX jog uses a custom asset.

**Comment by baconpaul** [comment]
oh shoot i just totally failed to port over this code (custom hover image name) from surge 1.9 into xt

**Comment by mkruselj** [comment]
Phew!

**Comment by baconpaul** [comment]
Yeah got it
Great test case @rovingeye
