### ISSUE TITLE
Show keybinds in relevant menu entries

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5489]
Would be really nice to show these directly in context menus, when "Use keyboard shortcuts" option is enabled. Like in Pianoteq:

![image](https://user-images.githubusercontent.com/2393720/143484233-e3e91ffb-a13e-4bf6-a6a7-6b7e613acab6.png)

**Comment by baconpaul** [comment]
Use the item menu directly and it has a shortcut string you can set so this is mostly adding an api or two to do that un surgejuceheklers 

do the tuning editor with those apis then turn it over to @mkruselj is my plan

**Comment by baconpaul** [comment]
```
   if (s == 100)
+        {
+            auto i = juce::PopupMenu::Item(lab).setAction([this, s]() { resizeWindow(s); });
+            i.shortcutKeyDescription = "ctrl-v-100";
+            zoomSubMenu.addItem(i);
+        }
+        else
+        {
+            zoomSubMenu.addItem(lab, true, (s == zoomFactor), [this, s]() { resizeWindow(s); });
+        }
     }

```

**Comment by baconpaul** [comment]
OK @mkruselj the branch `baconpaul/keybind-hints-5489` has the starting point i would use
you probably need one more helper API for making the name of the control (alt/cmd/ctrl etc...)
and also you need to determine whether to include it based on the state of the default
but that' basic api is where i would start

I'm fine to leave this till after 1.0 though too. It's not uninvasive.
