### ISSUE TITLE
Portamento issues with larger scales (31edo) low/high note priority and channel per octave

### ISSUE THREAD

**Issue by cgibbard** [surge-synthesizer/surge#5492]
**Bug Description:**
Sometimes the note which is picked to switch to after a note-off isn't the right one. See the repro steps.

**Surge Version**
main

**Reproduction Steps:**
Set mono st, high note prio, apply tuning at midi input, channel per octave, load 31edo.scl.
Play note-on 29 channel 2, note-on 3 channel 3, note-on 8 channel 3, note-off 8 channel 3.
Expected: hear note 3 channel 3
Actual: hear note 29 channel 2.

And another:
This time in low note prio, but same other settings
Play note-on 0 channel 3, note-on 26 channel 2, note-on 21 channel 2, note-off 21 channel 2
Expected: hear 21 channel 2
Actual: hear 0 channel 3.

**Comment by baconpaul** [comment]
got it
