### ISSUE TITLE
Modulation reset with double-click on FX target, with Scene B active

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#5500]
**Bug Description:**
When modulation is armed, a double-click to reset a modulation on a modulated parameter in FX: doesn't work if Scene B is active.

**Surge Version**
Version: Surge XT 0.99.nightly.6f95a0f
Build: 2021-11-24 @ 02:41:21 on 'WIN-9PGFOSL2U6B/pipeline' with 'MSVC-19.29.30137.0' using JUCE 6.1.2
System: Windows 64-bit VST3 on Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Host: Cakewalk by Bandlab @ 44.1 kHz

**Reproduction Steps:**
1. init.
2. Select Scene B.
3. Choose an FX
4. Arm a macro, modulate an FX parameter.
5. Double-click on that FX parameter.
The modulation is not removed.

**Expected Behavior:**
The modulation is removed.

**Screenshots:**
-
**Additional Information:**
-

**Comment by baconpaul** [comment]
Confirmed.
Moreover, with the SLFO it *does* reset
so this must have to do with items which are not per-scene distinguished
For instance it also happens with modwheel

**Comment by baconpaul** [comment]
And yeah as suspected this has to do with the A/B per-scene modulation changes we made in this revision.
