### ISSUE TITLE
Portamento in octave-per-channel mode starts from wrong octave when starting from all notes off

### ISSUE THREAD

**Issue by cgibbard** [surge-synthesizer/surge#5503]
**Bug Description:**
In octave-per-channel mode with any portamento, it seems as though the last played note when all notes are off is always treated as if it were on channel 1 (or 0 depending on how you count), so if you set a long portamento time and play separated notes on channel 3, say, you'll hear the pitch rise up slowly from way down in the bass.

**Surge Version**
main e5d4b4c77fb7bfa997513a57514dd101d84fde10

**Reproduction Steps:**
Set init sine, set portamento to some long time like 1 to 4 seconds, apply tuning at MIDI input, use channel for octave shift. This seems to happen even in poly mode, as well as mono, mono st, mono fp. 

Play note 0 on channel 3 a few times.

Expected: Hear only the pitch that note 0 on channel 3 makes, or possibly a slide from some other pitch initially, but thereafter only that note.

Actual: Each new note slides up from the pitch of note 0 a couple octaves below.

If you switch between different notes, you'll notice that it starts on the octave equivalent of the last played note, but in the wrong octave.

**Comment by baconpaul** [comment]
This is basically adding a map octave if statement the same way I added an mts fix in https://github.com/surge-synthesizer/surge/commit/d0623d833362b186601f9f71b1e0e0db2d46c223
