### ISSUE TITLE
Mousewheel on Airwindows type doesn't match the sorted menu order

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5507]
1. Load AW
2. Load Ambience>Bright Ambience
3. Mousewheel down - expected Chamber, got Hombre

**Comment by baconpaul** [comment]
Did this work in 19 also?
Do the filter menus work?

**Comment by mkruselj** [comment]
It worked in 1.9. Filter menus do work fine!

**Comment by baconpaul** [comment]
well it kinda does but it breaks in some spots that I don't quite understand
like galactic mouse down gives you infinity
but calactig mouse up gives you the wrong thing

**Comment by baconpaul** [comment]
ahh i see now i think the bug

**Comment by mkruselj** [comment]
#5511 fixed AW effect menu but messed up filter type menus. Reopening the issue!
