### ISSUE TITLE
MSEG tear-out reverts to tear-in when switching MSEG presets

### ISSUE THREAD

**Issue by ztnl** [surge-synthesizer/surge#5509]
Version: Surge XT 0.99.nightly.1408e7c
Build: 2021-11-26 @ 16:06:20 on 'fv-az424-579/pipeline' with 'MSVC-19.29.30137.0' using JUCE 6.1.2
System: Windows 64-bit VST3 on        Intel(R) Core(TM) i7
Host: Reaper @ 48.0 kHz

Just noticed that when an MSEG is in tear-out state, when switching MSEG presets, the tear-out switches back to tear-in.

**Comment by baconpaul** [comment]
Oops closed wrong one in https://github.com/surge-synthesizer/surge/commit/d45997a5c34e0dea1009b1b2eeb06ebc4e14467a

this is fixed
