### ISSUE TITLE
List of CC's for each parameter 

### ISSUE THREAD

**Issue by sense-amr** [surge-synthesizer/surge#551]
I would like to have a list of CC's corrosponding to Surge parameters .. for use in such sequencing applications which utilise direct CC manipulation..

**Comment by baconpaul** [comment]
The modulation controls let you map them a call shows them on the rmb menu. Is this what you mean or do you mean something else? The defaults for the unnamed ones come in the 40s

**Comment by esaruoho** [comment]
I could take a stab at this in the manual. CC is gold.

**Comment by esaruoho** [comment]
Well, starting with Controller 1 - Controller 8, they are CC 41 - CC 48 - but so far I'm only seeing fader data coming out from Logic re: the rest of the sliders.

**Comment by baconpaul** [comment]
timbre is 73
velocity is velocity
etc

**Comment by esaruoho** [comment]
Logic: getting faders (cutoff = F2,200)  to control knobs is not exactly what we're after, i feel like. faders aren't CCs.. but i _guess_ this could be an additional list that would be useful. 
or wdyt?

![hmm_fader_is_not_cc](https://user-images.githubusercontent.com/4966687/52520815-a820dd80-2c76-11e9-912d-6a4cc8b02a21.gif)

**Comment by baconpaul** [comment]
Isn't that just standard external control of parameters? I think that's so host specific I would skip it for the manual

**Comment by esaruoho** [comment]
okay :)

**Comment by esaruoho** [comment]
Here's a list of the only CCs that are automatically available to Surge Init state.

https://surge-synthesizer.github.io/manual/#cc--continuous-controller-information
