### ISSUE TITLE
MSEG open close tear out is a bit messy

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#5512]
Clean this all up after XT1

**Comment by baconpaul** [comment]
i'm gonna bump this out of the milestone. and may even close it when we get around to xt2

**Comment by mkruselj** [comment]
@baconpaul Can we say this one is not worth doing at all for 1.x and everything is better anyways in XT2/SCXT realm?

**Comment by baconpaul** [comment]
Sure
