### ISSUE TITLE
Toggle MIDI inputs between parameters

### ISSUE THREAD

**Issue by turtlebirb** [surge-synthesizer/surge#5521]
**Is your feature request related to a problem? Please describe.**
I'm using a midi controller with Surge, and I'm finding that I simply do not have enough knobs to control enough parameters of the synthesizer. I think there is a good solution, based on how hardware synthesizers often cut down on the number of knobs required by toggling between different parameters. Check out the "Edit" panel on this [Monomachine](http://medias.audiofanzine.com/images/normal/elektron-monomachine-sfx60-mkii-259814.jpg).

**Describe the solution you'd like:**
The solution I want is best given as an example:

If I assign the _same_ midi input to control the pitch of oscillator 1 and oscillator 2, I would like for that input to only send to the oscillator panel which is _currently_ displayed. This is the way that scenes work at the moment. If I assign a midi input to control the pitch of oscillator 1 in scene A, it also controls oscillator 1 in scene B, but only sends the input to the scene that is currently selected (changing oscillator 1's pitch in scene A doesn't change the pitch of oscillator 1 in scene B, even if they share the same midi input.) That way, instead of needing 24 knobs to independently control the parameters on all three oscillators, I would only need 8, and could simply toggle between the oscillators to change which oscillator I am currently controlling.

But: If I assign _different_ midi inputs to oscillators 1 & 2, then inputs can be sent as they currently are, regardless of which oscillator is currently toggled on the interface. That way if someone does happen to have 21 knobs to spare to control all the oscillator parameters simultaneously, they can!

I would for like this to apply to all panels whose parameter controls are identical and occupy the same space on the interface:
Oscillator 1, 2, 3
LFO & S-LFO 1 - 6

I think this would increase the ease of use of Surge for folks with different hardware available to them, without diminishing flexibility or requiring any change in the interface itself.

**Comment by baconpaul** [comment]
in the event the ui was closed, what would you want to happen with that midi event?
this matters a lot for things like recorded midi events
i'm intrigued by your idea but not sure i love it for a variety of reasons - including that one, that recorded midi ccs would render different audio based on the selection of a tab in the ui.
but understand the underlying problem

**Comment by turtlebirb** [comment]
In my use case, I'm treating my controller as a synthesizer control panel while the ui is open, and being able to use the knobs this way would make wave shaping much easier and more intuitive. It's a tactile/workflow thing. When the ui is closed, I'm not really playing with the parameters of the synth itself.

But, with regard to the problem you describe: isn't that how scenes already work? If I close the ui, I believe that the midi event sends to the scene that is currently active. In either case, I think that if my proposal is implemented you'd basically have to "opt-in" to this behaviour by configuring (for example) oscillator 1 pitch and oscillator 2 pitch to the same input. If you really need to have a midi event trigger oscillator 2 pitch regardless of whether it is currently selected, you can still assign it to a different midi input.

I'm open to other solutions! I'm just looking for ways to bridge the gap between hardware which does not necessarily correspond to the software layout.

**Comment by baconpaul** [comment]
Yeah I like the problem - like I said

scene is a bit different since the synth has a concept of an active scene in single mode and that drives the sound whereas active lfo and osc is not something the engine understands, but I agree this is deeply confusing

we also have pretty flexible mapping so we can do things like “be osc1 pitch unless the ui is open and osc2 is selected” although like I said I really do worry about that live performance idiom clashing with the recorded midi stream idiom

In any case we are feature frozen for xt1 now in our beta period so plenty of time to think. The problem is real just we need to poke to the right solution indeed. Appreciate you participating here to discuss it!

**Comment by mkruselj** [comment]
The solution for this is issue #574.

**Comment by turtlebirb** [comment]
Perhaps the distinction between "live performance" and "recorded midi stream" is part of the answer? A "live" mode and a "prerecorded" mode, which could allow different approaches to inputs?

**Comment by baconpaul** [comment]
Yeah that’s a good insight 

in live mode are you using a okugin in main stage or something or are you using the standalone out of curiosity?

**Comment by turtlebirb** [comment]
At the moment I'm playing with it as a plugin in Reaper, but I'm recording "live".

**Comment by mkruselj** [comment]
To me, this "toggling MIDI CCs between parameters" should be a feature of the hardware controller, not the plugin. So, something like Behringer BCR2000 or those Novation controllers allow you to set different CCs based on which page you're on. Then in the plugin you just have a 1:1 mapping instead of multiplexing what a single CC does (which is really just thoroughly uncool for a number of reasons).

What we need to do is #574 in order to expand the number of CCs we can map to parameters.

**Comment by turtlebirb** [comment]
i mean, i'm probably not going to shell out more money for a control surface specifically so i can use a free plugin more effectively. i'm more likely to just choose a different plugin which maps more effectively onto the control surface i already have. i guess it comes down to how important it is as a project goal to support a wide variety of controller configurations or not.

**Comment by mkruselj** [comment]
To be honest, I don't know of a plugin which would support this way of destructive/multiplexable MIDI CC learn...

**Comment by baconpaul** [comment]
If there's one which does it well would love to know also yeah!

My gut is if I wanted to do this with my plugins i would route them in MainStage or something. 

But I am also sympathetic to the idea that the oscillator pitch slider is a 'slider' not a 'virtual thing on a tab' and so the learn being selection focused is ergonomically natural in that mental model.

Anyway my view on this is "not no" but "not now" and it requires some careful thought about making it non-conflicting with our mainline use case of recorded tracks with automation through midi ccs.

**Comment by turtlebirb** [comment]
Makes sense! If you have a specific use case you are tailoring to then it is totally reasonable to focus on that.

I think with regard to choosing another plugin, i mainly meant i'd just go with one with fewer sliders.

**Comment by baconpaul** [comment]
> I think with regard to choosing another plugin, i mainly meant i'd just go with one with fewer sliders.

Ha yeah well that is definitely one way to solve the problem :)

**Comment by mkruselj** [comment]
@baconpaul The more I read this issue the more I think it's definitely not a good fit for Surge (or any other instrument plugin, tbh). It's a completely idiosyncratic and super niche way of dealing with MIDI controllers... I don't think we should support this.

**Comment by baconpaul** [comment]
I still can’t get over the fact that your playback state and ui state couple so much yeah. If we were to do it I would want active Osc lfo fx etc to be streamed synth side params otherwise the fr is impossible to be bug free and even then…. 

I really do think channel plus controller pages are the way to go here.

**Comment by mkruselj** [comment]
We have decided we will not do this ticket in the end.
