### ISSUE TITLE
Sine Distortion FX can oscillate and produce loud clicks with negative feedback

### ISSUE THREAD

**Issue by selenologist** [surge-synthesizer/surge#5525]
**Bug Description:**
Sine Distortion FX can oscillate and produce loud clicks with negative feedback.

**Surge Version**
Confirmed on:
Version:  Surge XT 0.9.main.57932618
Build:  2021-11-12 @ 23:56:41 on '[hostname redacted]' with 'GNU-11.1.0' using JUCE 60102
System:  Linux 64-bit Standalone on  AMD Ryzen 7 2700X Eight-Core Processor
VST3

**Reproduction Steps:**
1. Add a distortion FX
2. Set Model to Sine
3. Drag feedback slider to the left (negative)
4. Play a note to get it started.
5. Observe oscillation produced. The oscillation may sometimes decay, or continue forever.
6. Now drag the Drive slider around wildly.
7. Observe the loud clicks produced.

**Expected Behavior:**
This is sort of expected behaviour from a DSP side, but probably not the behaviour a user expects. We should not deafen the user with loud ringing and clicking when this parameter is pushed negative for Sine. Perhaps we should clamp the feedback at zero for this distortion type?

**Additional Information:**
Performing such a clamping would break patches that (un)intentionally (ab)used this quirk. So this issue will be unscheduled for now, maybe to be revisited in XT2.

**Comment by baconpaul** [comment]
I can't reproduce this now and I feel like I fixed it in 5c5331e51d1923e01604a8fccfba18d2c49c6f36

Can you still get this happening @selenologist and if not can we close it?

Thanks!

**Comment by mkruselj** [comment]
Indeed I cannot confirm this anymore, following the steps outlined by Luna.

**Comment by selenologist** [comment]
Ah, sorry for not being more on top of this - yes, AFAICT you fixed it with that patch. Thank you.

Closing.
