### ISSUE TITLE
Support MTS-ESP multi-channel tuning tables

### ISSUE THREAD

**Issue by battaglia01** [surge-synthesizer/surge#5535]
**Is your feature request related to a problem? Please describe.**
MTS-ESP, which is positioning itself as a new standard for microtuning in software, has two types of tuning tables:

1. The standard kind, which are 128 notes
2. The extended, multi-channel kind, in which the channel data is also used for tuning information, for a total of 16*128=2048 notes

Multi-channel tuning support is extremely important - otherwise, 128 notes is simply not enough range for most popular tunings. For instance, even with 24 tone equal temperament you only have 128/24 = 5.3 octaves, which is not even enough for a grand piano. For 31-equal you get only about 4 octaves and etc.

So this is a request to support multi-channel tuning tables, which lets you extend the range by using channel 2, channel 3, etc to get the missing notes.

**Comment by baconpaul** [comment]
We pass the channel to mts already

https://github.com/surge-synthesizer/surge/blob/d04ac3d3a2233e5532e9e46c4d614d6da6084035/src/common/dsp/SurgeVoice.cpp#L57

So would love a more precise description of what’s not working

**Comment by battaglia01** [comment]
Oops, sorry about that! This is already good with Surge. My apologies for the spurious post - closing

**Comment by baconpaul** [comment]
Oh that was easy! :)
