### ISSUE TITLE
allow saving and loading of midi & midi CC configuration

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#554]
a method of having user-set specifics of CC - and with a choice to apply it across any patch you load. or not.

related to userprefs ticket at #375

**Comment by baconpaul** [comment]
#1678 and #1774 are also related. All the same thing. Let me link these up.

**Comment by baconpaul** [comment]
![midi](https://user-images.githubusercontent.com/13387561/84387706-6c2abf00-abc1-11ea-849e-8f6b1778e146.gif)

Coming to the nightly today and into the 1.7.0 release this summer.
