### ISSUE TITLE
RPM nightly release fails to install

### ISSUE THREAD

**Issue by dieggsy** [surge-synthesizer/surge#5542]
**Bug Description:**
Reopening in this repo as requested:

I'm using Fedora 35. I tried to install the RPM release and got the following (the last two lines are the error):

```
> sudo dnf install ./surge-xt-x86_64-NIGHTLY-2021-12-01-bc53d94.rpm
Last metadata expiration check: 0:22:06 ago on Wed 01 Dec 2021 08:33:00 PM EST.
Dependencies resolved.
================================================================================
 Package     Arch      Version                            Repository       Size
================================================================================
Installing:
 surge-xt    x86_64    9.NIGHTLY.2021.12.01.bc53d94-1     @commandline    141 M

Transaction Summary
================================================================================
Install  1 Package

Total size: 141 M
Installed size: 282 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Error: Transaction test error:
  file /usr/bin from install of surge-xt-9.NIGHTLY.2021.12.01.bc53d94-1.x86_64 conflicts with file from package filesystem-3.14-7.fc35.x86_64
```

**Surge Version**

* Version: Surge XT 0.99.main.bc53d94
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Download RPM from: https://github.com/surge-synthesizer/releases-xt/releases/tag/Nightly
2. Try to install using `sudo dnf install ./surge-xt-x86_64-NIGHTLY-2021-12-01-bc53d94.rpm`
3. Installation fails with the above message

**Expected Behavior:**
Installation succeeds.

**Computer Information (please complete the following information):**
 - OS: Fedora 35
 - Host: N/A but Ardour 6

**Additional Information:**
As a temporary workaround, I was able to use rpmrebuild on the file and remove the line specifying /usr/bin. The resulting RPM was installable, but did not contain a standalone binary, which I now suspect is what the /usr/bin line *should* have been specifying.

The issue appears to be with this line, according to @baconpaul:
https://github.com/surge-synthesizer/surge/blob/2f2509ec55b632eccf2e15d3c1c95663dd5b704e/scripts/installer_linux/make_rpm.sh#L130

**Comment by baconpaul** [comment]
Yeah the files section is what you “did” install and we don’t install usr/bin. Or usr/lib/vst3 for that matter. I’ll clean it up in a sweep before the weekend and tag this issue when I do 

thanks!

**Comment by baconpaul** [comment]
So I think I have this resolved but it is super hard for me to test. I'll merge 5543 but leave this issue open until we have a confirm. Will need the nightlies to run also.

**Comment by baconpaul** [comment]
Sigh my fix blew up the nightly so no test image yet. Working on it

**Comment by dieggsy** [comment]
This is fixed in the latest nightly. Thank you!

**Comment by baconpaul** [comment]
Great thanks!
