### ISSUE TITLE
Slider redraw lags with overlays open

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5555]
There's a framerate dip when dragging the mod amount sliders in the mod list, or moving stuff in the background such as OSC parameters. It's definitely choppier, at least on @VincyZed's end (and ED's end too).

Easy repro steps:

1. Init saw
2. Pick one of the osc sliders and move it moderately from side to side
3. Alt+M to toggle the modlist on/off

Note how the slider movement becomes way less smooth when modlist is open.

Happens with other overlays too.

Does NOT happen if overlay is torn out!

**Comment by baconpaul** [comment]
So the entire overlay redraws on every idle

Dint know why yet

but that's gonna be the problem

**Comment by baconpaul** [comment]
OK so if it sits over the VU meter it does that
but it also does a full redraw on each slider drag
and doesn't if torn out
That's going to add quite a lot of draw load I think.

I'm gonna have to profile this properly on windows to figure out what triggers the draws.

**Comment by baconpaul** [comment]
wow this is really terrible yeah now i boot into windows
wonder what it is.

**Comment by baconpaul** [comment]
huh
windows is just slow when painting this non-front element. 
i really do wonder why.
right now i have no idea how to fix this.

**Comment by baconpaul** [comment]
So reading the JUCE 7 release notes thread, I think this draw-with-overlay is some of the rectangle invalidation stuff they are addressing in juce 7. I'm going to knock this out of the xt1 milestone.

**Comment by baconpaul** [comment]
Ahh no change that

The reason for this is this code in SGE

```cpp
           if (!queue_refresh)
            {
                // There was infowindow code here. Do I need it still?

                if (oscWaveform && ((p->ctrlgroup == cg_OSC) || (p->ctrltype == ct_character)))
                {
                    oscWaveform->repaint();
                }
                if (lfoDisplay && (p->ctrlgroup == cg_LFO))
                {
                    lfoDisplay->repaint();
                }
                for (auto &el : juceOverlays)
                {
                    el.second->repaint();
                }
            }
```

that is: every open overlay repaints if any parameter changes

We should clearly change that to be that overlays can opt into repainting. For instance, none of formula, tuning, or mseg need to (but modlist does as does the new wave shaper analyzer)

**Comment by baconpaul** [comment]
In theory #6030 should resolve this on windows. If it does, we should close this. If ti doesn't then it is, indeed, the juce 7 rectangle issue we are waiting for.

**Comment by VincyZed** [comment]
Will give it a whirl and let you know :)

**Comment by mkruselj** [comment]
Smooth as baby's butt now!

**Comment by baconpaul** [comment]
Awesome - closing
