### ISSUE TITLE
Patch searching using non-ASCII characters does not work

### ISSUE THREAD

**Issue by xard-dev** [surge-synthesizer/surge#5563]
**Bug Description:**
Patch searching using non-ascii characters does not work.

**Surge Version**
Surge XT 0.99.main.007a427

* Version:
* Plugin Type: LV2
* Bitness: 64-bit

**Reproduction Steps:**
1. Click on search icon.
2. Paste μ character to the search.

**Expected Behavior:**
μcomputer preset should be listed.

**Screenshots:**
![image](https://user-images.githubusercontent.com/65303522/144832445-f0cafbdc-1a36-4ccf-961b-22c15e14baaf.png)

**Computer Information (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Host: Carla
 - Version: 2.1.0

**Comment by baconpaul** [comment]
Oh good catch - the entire chain is supposed to be utf-8 so I wonder where it isn’t

**Comment by xard-dev** [comment]
Actually this could be more specific to that patch itself as umlaut characters do seem to work:
![image](https://user-images.githubusercontent.com/65303522/144846199-b8d3af68-a55e-4e3f-826e-60fde70b4145.png)

**Comment by baconpaul** [comment]
Ahh right I wonder if there are multiple mu characters - did you copy the character from the file name itself?

**Comment by mkruselj** [comment]
As an aside, looking at that screenshot, I wonder if we should also dynamically expand the typeahead results window based on number of results (up until its current size)...?

**Comment by xard-dev** [comment]
Baconpaul I you are correct as "µ" is not "μ":
![image](https://user-images.githubusercontent.com/65303522/144848808-b08be8a6-dc7f-4b2a-b1ac-892ba7070c76.png)

**Comment by xard-dev** [comment]
I don't know unfortunately the semantic difference between these characters but if I save the preset using the latter (common utf-8 symbol) I can also search the preset with it.

**Comment by baconpaul** [comment]
ok so it seems this one is all OK and I can close it yes?
Great test in any case :)

**Comment by xard-dev** [comment]
Yes, this can be closed :)

**Comment by mkruselj** [comment]
The joys of Unicode? 😆

**Comment by xard-dev** [comment]
Perhaps the patch could be renamed? (and I'm not sure if the patch actually works in XT)

**Comment by mkruselj** [comment]
It's a legendary patch kinda (and it does work in XT!) since it was used for so many different tests since open-sourcing!

**Comment by xard-dev** [comment]
Ok, as I don't know the difference between these characters it can also be technically correct so it's best left as is unless someone familiar with Greek alphabets in digital form disagrees. :smile:
