### ISSUE TITLE
Long patch names can overlap with category and attribution

### ISSUE THREAD

**Issue by xard-dev** [surge-synthesizer/surge#5564]
**Surge Version**
Surge XT 0.99.main.007a427

* Version:
* Plugin Type: LV2
* Bitness: 64-bit

**Reproduction Steps:**
1. Open preset "10 Example - Both Time And Space".

**Expected Behavior:**
The patch name does not overlap any other text.

**Screenshots:**
![image](https://user-images.githubusercontent.com/65303522/144833769-dd5c465e-c3a9-4e5f-bfcc-b59bf1c3a050.png)

**Computer Information (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Host: Carla
 - Version: 2.1.0

**Comment by baconpaul** [comment]
Oh yeah we were going to remove the word category and author in that case at least to give us some room. Thanks!

**Comment by mkruselj** [comment]
I'd actually reduce the font size of patch name in that case instead, if possible.

**Comment by baconpaul** [comment]
yeah so my idea was

1. drop the pre-labels category and author
2. if we still need space shrink the font of the patch

the only problem with 2 is it won't overlap with the typeahead replacement

**Comment by mkruselj** [comment]
Can we not change the font size of both the patch name text and what's used in typeahead? I think both are justified vertically and horizontally centered across the whole height of the patch selector...

I'm really not feeling dropping the cat/by labels (at least not until XT2, but that's for a completely different reason!)...

**Comment by baconpaul** [comment]
![PatchFont](https://user-images.githubusercontent.com/13387561/144855312-c0407474-c060-4239-9d57-1179727e0ff1.gif)

Here we go.
That's the dynamic approach which does best it can

**Comment by baconpaul** [comment]
So what that does is: if it can leave the thing in place by dropping the category and by label, it does. if it can't it starts the shrinking and non-collision. I'll merge that for XT1

**Comment by xard-dev** [comment]
That looks nice!
