### ISSUE TITLE
Offer auto-generated 0-127 CC list for each Surge parameter in context menu

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#557]
Control 1 - Control 8 have this auto-populated CC-list (0-127) 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/4966687/52530551-6c3a5680-2d10-11e9-8134-03aae3088af0.png">

Whereas none of the other sliders in Surge have the auto-populated CC-list (0-127)
<img width="274" alt="image" src="https://user-images.githubusercontent.com/4966687/52530560-7ceacc80-2d10-11e9-9bc7-195ccbf0b680.png">

Proposal: all the sliders etc functions in Surge could have the auto-populated CC-list (0-127) in the context menu - for easier binding.

**Comment by baconpaul** [comment]
Fold into #566
