### ISSUE TITLE
After saving a modified patch as new patch UI is not completely refreshed to point the new patch

### ISSUE THREAD

**Issue by xard-dev** [surge-synthesizer/surge#5570]
**Bug Description:**
After saving a modified patch as new one the drop down menu active patch points to old patch.
Update: the favorite is not selected in the new patch but the UI does not update the state correctly.

**Surge Version**
Surge XT 0.99.main.007a427

* Version:
* Plugin Type: LV2
* Bitness: 64-bit

**Reproduction Steps:**
1. Open a patch to edit.
2. Click on Save.
3. Fill the name and modify the category. 
4. Press OK to save the patch.
5. Open Patch drop down menu.

**Expected Behavior:**
The patch drop down menu points to the created patch.

**Screenshots:**
![image](https://user-images.githubusercontent.com/65303522/144851783-efbf0c14-ee4f-43dd-8517-2d7b1e73c9d7.png)

**Computer Information (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Host: Carla / Standalone
 - Version: 2.1.0

**Comment by baconpaul** [comment]
Just the checkmark is wrong, no other part of the UI, correct?

Thank you!

**Comment by baconpaul** [comment]
Anyway able to repro and confirmed. Should be an easy enough fix i hope.
