### ISSUE TITLE
Patch search typeahead vertical offset niggle only at first show/hide toggle

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5574]
As showcased by this GIF:

![offset](https://user-images.githubusercontent.com/2393720/144858500-439e5158-b01c-4ea4-b987-83e103237dd1.gif)

It only happens once - when closing the typeahead first time after a fresh instantiation of Surge.

**Comment by baconpaul** [comment]
OK in good (ish) news this also happens on mac at 200%

**Comment by baconpaul** [comment]
and found it

**Comment by mkruselj** [comment]
👏
