### ISSUE TITLE
Clicking open drop down menus does not close them

### ISSUE THREAD

**Issue by xard-dev** [surge-synthesizer/surge#5577]
**Bug Description:**
Clicking open drop down menus does not close them in Surge XT unlike in old Surge.

**Surge Version**
Surge XT 0.99.main.007a427

* Version:
* Plugin Type: LV2 / VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Click any button or widget which opens a floating menu.
2. Click the button again while the menu is open.

**Expected Behavior:**
The open floating menu is closed.

**Screenshots:**
![Peek 2021-12-06 17-12](https://user-images.githubusercontent.com/65303522/144871188-f6a13b1c-ba93-4998-ae15-a75337ee53ad.gif)

**Computer Information (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Host: Carla / Ardour 6 / Standalone
 - Version: 2.1.0 / 6.9

**Additional Information:**
Example of old Surge:
![Peek 2021-12-06 17-13](https://user-images.githubusercontent.com/65303522/144871333-aefc2bb0-9b73-4a52-aa7e-74d2546e8a04.gif)

**Comment by mkruselj** [comment]
Duplicate of #5395
