### ISSUE TITLE
Weird floating patch menu placement when the Surge window is in the right side of the screen

### ISSUE THREAD

**Issue by xard-dev** [surge-synthesizer/surge#5578]
**Bug Description:**
Weird floating patch menu placement when the Surge window is in the right side of the screen.

**Surge Version**
Surge XT 0.99.main.007a427

* Version:
* Plugin Type: LV2 / VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Click patch selector which opens a floating menu.

**Expected Behavior:**
The floating menu has horizontal offset in case the floating menu is too close to the screen border.

**Screenshots:**
![image](https://user-images.githubusercontent.com/65303522/144873880-c755680f-ee45-4505-af2e-e73adf66622e.png)
Update: The image shows the space to the right edge of the screen.

**Computer Information (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Host: Ardour 6 / Standalone
 - Version: 6.9

**Additional Information:**
This issue seems to trigger when moving the window past 1722 pixels on screen (3840px total width).

**Comment by baconpaul** [comment]
yeah i'll try and figure it out and put it to their forum at least

that looks like the patch widget crosses the screen midpoint and so it chooses the 'other side' to me.

**Comment by baconpaul** [comment]
OK my mac does this on my 4K monitor also
will look

**Comment by baconpaul** [comment]
found it
its a juce weirdness if we call their api in one way but i can fix our call
