### ISSUE TITLE
Sub-folder says 120-127, but the last bindable CC is 126.

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#558]
I'm experimenting with modifying the "subfolder split code" from "split by 10" to "split by 20". looks good so far, but raises weird questions:
Where's CC127? last CC is CC126.
![image](https://user-images.githubusercontent.com/4966687/52531666-71ec6800-2d21-11e9-8c99-85d0013dd62d.jpeg)

**Comment by esaruoho** [comment]
pushing fix into branch `commentsAndCC`, fix looks like this
->
![image](https://user-images.githubusercontent.com/4966687/52531737-a7de1c00-2d22-11e9-884e-408d94008797.jpeg)

**Comment by baconpaul** [comment]
Fold into #566
