### ISSUE TITLE
Formant slider is invisible at first when opening a "Choir Pad Thing" factory patch

### ISSUE THREAD

**Issue by xard-dev** [surge-synthesizer/surge#5581]
**Bug Description:**
Formant slider is invisible at first when opening a "Choir Pad Thing" factory patch.

**Surge Version**
Surge XT 0.99.main.007a427

* Version:
* Plugin Type: LV2 / VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Open factory patch "Choir Pad Thing".
2. Look for the initial state of the Formant slider.

**Expected Behavior:**
The format slider is rendered.

**Screenshots:**
![image](https://user-images.githubusercontent.com/65303522/144888826-f5e5fcbe-661b-4cf6-9b06-fc9e536d54db.png)

**Computer Information (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Host: Carla / Ardour 6 / Standalone
 - Version: 2.1.0 / 6.9

**Additional Information:**
This is not an issue in older Surge.

There is also something unexpected going on when clicking the S-LFO1 control to show the slider which might or might not have anything to do with the main issue:
![image](https://user-images.githubusercontent.com/65303522/144888732-23abf7dd-55d3-4d35-92f6-58901ab6cda6.png)

**Comment by xard-dev** [comment]
I discovered this thing when manually testing and comparing all factory presets between the versions for audible differences. So far I've found none including fiddling macros, pitch bending and a quick modwheel testing.

**Comment by mkruselj** [comment]
This is not a bug - that just means those filters are disabled. In 1.9 we had to show this differently on Linux due to VSTGUI, but with JUCE, we can show it transparent across all platforms!

**Comment by xard-dev** [comment]
Okay, I tested the Format behavior and it was exactly as you said: On both versions it's disabled (though the patch shows a value of "-3075.00 %". I need to look up how the disabling actually works as I did not find a way disable it again after touching the control.

**Comment by xard-dev** [comment]
The Low Cut and High Cut have Activate and Deactivate context menu items and that works as expected. 

However the Formant control does not have activation option at all. Also the sound changes after I touch it once in both versions and I can't get it back to way it was unless I'm reloading the patch. Could this be a separate issue?

**Comment by mkruselj** [comment]
Ah so that would just be a patch versioning issue for Formant parameter. Corrupt value stored, or something. I vaguely remember stumbling upon it.

**Comment by xard-dev** [comment]
Thank you for the clarification! If the value is corrupted then I guess it's "garbage in garbage out" situation in terms of the UI.

**Comment by xard-dev** [comment]
I'll go through at least the factory presets and so far I've found problematic ones:
- Choir Pad Thing
- Pad 7

I'll open a ticket with full listing about this regression issue once I'm done with the factory presets.

**Comment by mkruselj** [comment]
@xard-dev No need for a ticket, I've located the issue and one of next nightlies are going to have it fixed!

**Comment by mkruselj** [comment]
Fixed at head now!

**Comment by xard-dev** [comment]
Oh, nice!
These were the direct findings on my testing until I realized that I forgot the B dual feature... oops.

The issue was related to Window type waveform.

Pads
* Choir Pad Thing
* Computers In Space
* Hmm... 
* Pad 7
* Primes (very minor difference after changing value)

Polysynths
* Embarrass
* Eyan
* Fonk 
* Hombre 
* Jim
* Japanese Space-ulation Wheel
* Past tense
* Quantization Choice

Sequences
* Burial Ground

Oh, and I did not notice any audible difference between Surge and Surge XT Factory presets when comparing them with same midi notes and 75% panning (left older, right XT). Unfortunately the older VST3 version does not have audio inputs in Ardour so I could not test the vocoder and inputs against the older verion the LV2 version sounded ok.

**Comment by baconpaul** [comment]
Awesome thank you
This bug has been there forever. You are correct that it wouldn't change the patch playback, but it would have made it uneditable.
Appreciate all the diligent testing today!
