### ISSUE TITLE
Various new tabs/multibutton states not stored in DAWstate

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5588]
As per subject line. We store other tabs in there, so we should store these, as well. Here's what's not stored in DAWstate:

In Memory:
- [x] Modulation List Sort By
- [x] Modulation List Filter By
- [x] Tuning Editor Edit Mode
- [x] Formula Code (Modulator/Prelude)
- [x] Formula Debugger

Streamed
- [x] Modulation List Sort By
- [x] Modulation List Filter By
- [x] Tuning Editor Edit Mode
- [x] Formula Code (Modulator/Prelude)
- [x] Formula Debugger

**Comment by baconpaul** [comment]
OK have it working in memory; just need to stream it and this will get wrapped up. Soon.
