### ISSUE TITLE
Tear-Outs/Ins When Switching Scenes In Dual Mode

### ISSUE THREAD

**Issue by ztnl** [surge-synthesizer/surge#5590]
Version: Surge XT 0.99.nightly.f017900
Build: 2021-12-06 @ 20:51:57 on 'fv-az223-812/pipeline' with 'MSVC-19.29.30137.0' using JUCE 6.1.2
System: Windows 64-bit VST3 on        Intel(R) Core(TM) i7
Host: Reaper @ 48.0 kHz

Realizing there is some ongoing work and discussion about the behavior of tear-outs/ins in general, thought I'd ask a related question before creating an issue about an observed behavior...

Q: Is it normal, or otherwise known behavior, for MSEG tear-out states to revert to tear-in upon switching Scenes?

Notice in the attached GIF, how the MSEG tear-out reverts to a tear-in state when switching between Scenes in Dual mode, with a patch that uses MSEGs in both Scenes.

![Tear-Out state when switching between Scenes](https://user-images.githubusercontent.com/81161256/145016485-a006fe1b-38bc-460b-8bc3-adf362eb4c1b.gif)

**Comment by baconpaul** [comment]
Whoa on mac I get an even worse situation here which is a crash-to-desktop in the standalone with init sine / mseg on lfo 1 in both / tearout / swap scene

good catch!

**Comment by baconpaul** [comment]
(The crash was unrelated to this by the way but got this fixed :) )

**Comment by baconpaul** [comment]
Mseg to formula has Same bug
