### ISSUE TITLE
Royal Surge skin jumbled/unusable. Win64 SurgeXT under Wine

### ISSUE THREAD

**Issue by Eirikur** [surge-synthesizer/surge#5599]
This drawing issue only happens with Royal Surge and it's 100% of the time. It looks like a skin compatibility issue, but I don't know where to report that. The old skin and the dark skin work fine. Having this skin would make Surge much more usable to me, personally.
![royal](https://user-images.githubusercontent.com/96312/145268599-168bb0c2-704c-46c8-88f5-f77d77d267e7.png)
.

**Comment by Eirikur** [comment]
This behavior happens at all zoom levels.

**Comment by baconpaul** [comment]
yes royal doesn't work with XT currently. We are hoping that we can get it working for the release.
