### ISSUE TITLE
Replace RMB on FX grid slot with context menu

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5613]
Currently we use right-click to toggle bypass of an effect slot in the FX grid. And we use double-click on waveshaper curve display and filter type icons. Inconsistent!

What's worse, in order to load an effect, you need to first select the slot you want, then move mouse down and pick an effect. Inefficient!

So for 1.1, replace RMB bypass on FX grid slot with a context menu (same as the FX preset menu, for simplicity), ~~and add double-click to bypass~~. Easy!

**Comment by baconpaul** [comment]
When we do this, do shift f10 for the menu also, don't forget.

**Comment by baconpaul** [comment]
And an acceiniliry check
I can do that if someone else does the core feature of course but let’s not close this until we have both the menu and accesibility checked. Cool fesruee

**Comment by baconpaul** [comment]
What's the code hint needed here?

I think it really is just have RMB do control modifier clicked and then handle the menu in SurgeGUIValueEditorCallback::controlModifierClicked. Something else stuck on?

**Comment by mkruselj** [comment]
The whole FX preset menu is created not in SGEVC but in XMLConfiiguredMenus, that's what trips me up.

**Comment by baconpaul** [comment]
Yeah but just ad a method to the menu which calls a method on fxmeny which then does the first listener of type on sge then calls a method on sge of your choosing.

**Comment by baconpaul** [comment]
Oh but I see you want the preset menu on the rmb menu of the effect widget right. Gnunk. Have to think about that one if so. Putting hints back on this issue
