### ISSUE TITLE
Surge VST3 on Ubuntu with Pipewire 0..3.40 crashes on load

### ISSUE THREAD

**Issue by kaerumy** [surge-synthesizer/surge#5614]
**Bug Description:**
When opening Surge 1.9.0 and Surge XT nightly build VST3 in Carla or Bitwig, it immediately crashes.
Surge XT LV2 loads up fine.

**Surge Version**

* Version:  XT 0.99.main.f695156 and 1.9.0
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Try to load Surge VST3 in Bitwig or Carla Patchbay
2. See what seems like Windows animation opening, and then immediate crash

**Expected Behavior:**
1. Surge VST3 is loaded, and able to see Surge UI.

**Screenshots:**
N/A

**Computer Information (please complete the following information):**
 - OS: Ubuntu 21.10 
 - Host: Bitwig, Carla
 - Version:  Bitwig 4.1

**Additional Information:**
 - Wayland window manager
 - Pipewire 0.3.40.r59.g1b06d4d-1~ubuntu2

Surge XT Delay and Surge XT FX VST3 loads up fine.

**Comment by kaerumy** [comment]
Working:

 * VST3: Surge XT Delay, FX
 * LV2: Surge XT Synth, Delay, FX
 
 Not working:

* VST3: Surge XT Synth

**Comment by mkruselj** [comment]
What is "Surge XT Delay"? We don't have a separate delay plugin.

**Comment by baconpaul** [comment]
Also is the behavior the same in bitwig as it is in reaper? And which version of bitwig?

**Comment by baconpaul** [comment]
I mean Carla not reaper

**Comment by kaerumy** [comment]
> I mean Carla not reaper

The behavior when loading Synth VST3 from Carla is the same as in Bitwig 4.1.2. Surge Synth/Surge XT Synth crashes on load.

Surge XT Effects and SurgeEffectsBank VST3 load up fine, and the GUI can be displayed.

**Comment by baconpaul** [comment]
and the LV2 works right?
then i have a theory.
the LV2 is stereo out and VST3 has between 1 and 3 stereo outputs.
I wonder if that's blowing up with the pipe wire config.

**Comment by tank-trax** [comment]
OS: Linux Mint 20.2 Uma
Server Name: PulseAudio (on PipeWire 0.3.42)

I am able to run the VST3 in Carla without issue

![image](https://user-images.githubusercontent.com/41337033/146562701-e7212107-345a-4048-a553-276e821e949b.png)

**Comment by tank-trax** [comment]
@kaerumy 

it could be corrupt configuration files

could you please try this?

delete `~/.config/Surge XT.settings`

and rename `~/Documents/Surge XT` to  `~/Documents/Surge XT.old`

and then try the Standalone Surge XT again, if it opens go to Options -> Audio/MIDI Settings 

then choose **ALSA** as the **Audio Device Type** and **PipeWire Sound Server** as **Output**

for **Input** you may have to use **JACK Audio Connection Kit** if **PipeWire Sound Server** doesn't hold or freezes Surge XT

**Comment by kaerumy** [comment]
@tank-trax tried removing configs. That didn't work. 

Linux Mint 20.2 is on based on Ubuntu 20.04 LTS. I don't have the crashes on Ubuntu 21.04.
I'm on Ubuntu 21.10. 

I managed to capture Carla log on loading Surge VST3 before Carla crashes. 

```
JUCE Assertion failure in juce_AudioProcessor.cpp:362
JUCE Assertion failure in juce_AudioProcessor.cpp:365
```
![image](https://user-images.githubusercontent.com/1060743/146882806-a3e5b787-668d-4ef1-8674-fb0bbf14e845.png)

JUCE code it references, seems to point to  @baconpaul guess that it's related to input/output channels.

```    // the processor may not support this arrangement at all
    jassert (success && newNumIns == getTotalNumInputChannels() && newNumOuts == getTotalNumOutputChannels());

    setRateAndBufferSizeDetails (newSampleRate, newBlockSize);
    ignoreUnused (success);
```

https://github.com/juce-framework/JUCE/blob/master/modules/juce_audio_processors/processors/juce_AudioProcessor.cpp

```
void AudioProcessor::setPlayConfigDetails (int newNumIns, int newNumOuts, double newSampleRate, int newBlockSize)
{
    bool success = true;

    if (getTotalNumInputChannels() != newNumIns)
        success &= setChannelLayoutOfBus (true,  0, AudioChannelSet::canonicalChannelSet (newNumIns));

    // failed to find a compatible input configuration
    jassert (success);

    if (getTotalNumOutputChannels() != newNumOuts)
        success &= setChannelLayoutOfBus (false, 0, AudioChannelSet::canonicalChannelSet (newNumOuts));

    // failed to find a compatible output configuration
    jassert (success);

    // if the user is using this method then they do not want any side-buses or aux outputs
    success &= disableNonMainBuses();
    jassert (success);

    // the processor may not support this arrangement at all
    jassert (success && newNumIns == getTotalNumInputChannels() && newNumOuts == getTotalNumOutputChannels());

    setRateAndBufferSizeDetails (newSampleRate, newBlockSize);
    ignoreUnused (success);
}
```

**Comment by tank-trax** [comment]
could you create a new user and try in that user to see if the same crash happens? if it does you may need to dig deeper with Ubuntu support or see if there is something in PW causing this

I run Surge VST3 on Debian Buster 11.2 using JACK and Mint Uma 20.2 using [PipeWire 0.42](https://github.com/pipewire-debian/pipewire-debian) without issue, I am hard pressed to think this is a Surge problem or something that can be fixed in Surge code, but I could be wrong

which type of PipeWire build are you using? is it bundled with Ubuntu 21.04, did you build it locally or is it from this [PPA](https://github.com/pipewire-debian/pipewire-debian)

**Comment by kaerumy** [comment]
I'm using pipewire-debian PPA already and there are no custom config files.
It's pretty much pipewire defaults as packaged by the Debian PPA, and
configured as per pipewire-debian wiki.

Will poke around some more to track where the problem might be. Everything
else works fine, even Surge XT LV2, it's just the VST3.

**Comment by kaerumy** [comment]
As mentioned earlier. I am on Ubuntu 21.10. Surge VST3 is working fine on
Ubuntu 21.04 with JACK.

There is a likely possibility that something changed in Ubuntu 21.10 that
broke VST3, and it may not be pipewire related.

**Comment by mynameismuhl** [comment]
To see whether the problem is related to the extra outputs you could also disable them in in the defaults:
In `~/Documents/Surge XT/SurgeXTUserDefaults.xml` try changing that line so it says
`<default key="activateExtraOutputs" value="0" type="2"/>`

Or if that file doesn't exist create it and add this:
```xml
 <?xml version = "1.0" encoding = "UTF-8" ?>
<!-- User Defaults for Surge Synthesizer -->
<defaults version="1">
  <default key="activateExtraOutputs" value="0" type="2"/>
</defaults>
```

**Comment by kaerumy** [comment]
Not exactly sure if this was what fixed it, but changes recommended by yabridge docs https://github.com/robbert-vdh/yabridge on plugins crashing and setting pipewire rtkit priority might have fixed the crash for VST3 plugin for me.

The only changes, done from what is otherwise the stock debian pipewire ppa on Ubuntu 21.10 configuration, that might have fixed the crashes.

pipewire.conf:

```
    # Uses RTKit to boost the data thread priority.
    { name = libpipewire-module-rtkit
        args = {
            nice.level   = -11
            rt.prio      = 88
            rt.time.soft = -1
            rt.time.hard = -1
        }
        flags = [ ifexists nofail ]
    }
```
Enabling threadsirq in kernel.

**Comment by tank-trax** [comment]
@kaerumy those are my settings too so I would agree that it is the fix 
I also enabled threadirq

I would suggest to try [this](https://github.com/raboof/realtimeconfigquickscan) to test your system
