### ISSUE TITLE
Interface UI Fix on blurred fonts when zoomed over 100%

### ISSUE THREAD

**Issue by iamlykan** [surge-synthesizer/surge#5619]
Team Surge, 

I have been using surge for a very long time and its the incredible work by you. Loved the efforts you had implemented to release such a marvellous synth. But the only thing which bothers when it comes to working on sound design is the resolution fix. 

Since the UI lacks with Vector Scalability. The fonts get blurred when zoomed. By default 100% looks small and so the fonts on a 23 inch monitor with a resolution of 1920x1080. When Zoomed to 125% the fonts loose their sharpness and the crucial detail of the VST gets slightly blurred. Please do fix the blur of the font when zoomed or scale the 100 percent with sharpness.

Please do check the attached files with this post. It might explain and can provide better detail about this. 
Again this is not a bug or glitch its just a feature request needed for such incredible synth to work with. 

Thank you. 

![100 percent on 1920x1080](https://user-images.githubusercontent.com/95950595/145662948-035600f1-70ba-47e0-9433-831d4049a07a.png)
![Both on Zoom of 100 percent Still Sylenth looks decently sharp](https://user-images.githubusercontent.com/95950595/145662949-74c80902-7e33-44ec-90a4-f95f624a4926.png)
![Slightly Blurred in 125 Percent Zoom](https://user-images.githubusercontent.com/95950595/145662951-88366a8e-8ef0-4e86-9d67-53df59fbdf10.png)

**Comment by baconpaul** [comment]
Hmm everything is vector based and in my 4k Mac monitor I get perfect crispness from 100 up to 500 percent

so let me ask a few questions

1: which surge version?
2: that looks like windows yes? Windows 10?
3: is the situation improved at 150 or 200?

Our font rendering is just handled by the os so I’m not quite sure if there’s anything we can do to improve it in your system, but I’m also curious if the beta of our upcoming version is better (assuming you are running 19)

**Comment by baconpaul** [comment]
Oh no that’s a Mac screenshot! Sorry

**Comment by baconpaul** [comment]
https://surge-synthesizer.github.io/nightly_XT

Here’s the beta of our upcoming version; curious if that is better?

**Comment by iamlykan** [comment]
Since, I am on Mac OS Mohave, I do see other plugins UI much better. As I
said on the basic resolution of 1080p which is overall a standard
resolution when it comes to people who are still on old screens or
specially laptop users definitely facing this issue. On the other hand, on
a 4k resolution it won't appear that way. So my only question stays why the
interface of Surge cannot adapt Font sharpness within the plugin itself
depending on the UI structure of its own instead of relying on font
optimization of the operating system. If a scalable TrueType font is
included inside the vst itself it will use the font size type automatically
through itself when scaled on percentage. I hope you understand.

**Comment by iamlykan** [comment]
If possible, if you can switch your 4k monitor to a standard 1080p 22
inches monitor or a 13 inch laptop screen. You might easily get what I am
talking about. If the skin zoom are optimized according to screen
resolution would be more logical. I hope that will be taken care of by
version 1.10, since I am on 1.9 which the current version.

**Comment by mkruselj** [comment]
1.10 will not happen, please try Surge XT nightly (baconpaul posted a link above) and see if it's better.

**Comment by baconpaul** [comment]
Looking more carefully the assets circled are SVG paths not fonts. They will not get the same subpixel rendering on low dpi monitors thst fonts will. But the new version has a mostly improved SVG renderer so it may improve your situation.

**Comment by iamlykan** [comment]
That sounds great. Hope so its fixed. Will keep you posted if this still
looks the same.

**Comment by iamlykan** [comment]
Thank you for the most earliest response by the Surge Team.

**Comment by baconpaul** [comment]
No problem!

If it still renders poorly at low dpi on mac there's not an enormous amount we can do, but may have an idea or two. let us know.

**Comment by mkruselj** [comment]
@iamlykan Can you please tell us if Surge XT is looking fine for you now?

**Comment by mkruselj** [comment]
@baconpaul I'm gonna close this one.

@iamlykan If at any rate you want to clue us in if how Surge XT works for you and if it looks "right", do let us know.
