### ISSUE TITLE
Virtual keyboard: octave shift with note off

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#5620]
**Bug Description:**
Note-off is sent for the wrong MIDI note when octave shift has been used since note-on.
Likely a bug in JUCE rather than Surge.

**Reproduction Steps:**
1. Enable the virtual keyboard in an open Surge window.
2. Press and hold a key (say "F")
3. Press C to shift octave
4. Release the note key ("F")
The note remains on.

**Expected Behavior:**
The note ends.

**Screenshots:**
.

**Computer Information (please complete the following information):**
Version: Surge XT 0.99.nightly.78fd32b
Build: 2021-12-04 @ 21:39:10 on 'fv-az33-805/pipeline' with 'MSVC-19.29.30137.0' using JUCE 6.1.2
System: Windows 64-bit VST3 on Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Host: Cakewalk by Bandlab @ 44.1 kHz

**Additional Information:**
.

**Comment by mkruselj** [comment]
This is #5480 in disguise. All the same reasons.

**Comment by j5v** [comment]
Let's use this as a test case when #5480 is done. If it's because the note-on ID differs from the note-off ID (because the octave transpose happened in the time in between), then the bug will remain.

**Comment by mkruselj** [comment]
From what Paul says, #5480 is really really difficult and might not be fixable.
