### ISSUE TITLE
Keep TARGETS pop-up open after deletion of an entry

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#5622]
**Is your feature request related to a problem? Please describe.**
Currently, when you select the red 'X' to delete an item from the pop-up modulation list, the list then closes. This can be cumbersome when deleting larger numbers of modulations.
![image](https://user-images.githubusercontent.com/13245475/145691854-dc5b6332-1961-4647-b4d1-29c45b9088c5.png)

**Describe the solution you'd like:**
Keep the pop-up open after deleting items.
Consider doing this also for more functions, like Rename.

**Describe alternatives you've considered:**
.

**Additional context:**
This need not apply to the 'All' options.

**Comment by mkruselj** [comment]
Basically #2463 covers this issue!
