### ISSUE TITLE
Copy FX result: source FX not identical to target FX

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#5624]
**Bug Description:**
When I copy an FX to a blank slot, using [Ctrl]+[left-drag], the existing FX slot is initialized to the same type, and the target slot contains the moved FX.

**Surge Version**
Version: Surge XT 0.99.nightly.78fd32b
Build: 2021-12-04 @ 21:39:10 on 'fv-az33-805/pipeline' with 'MSVC-19.29.30137.0' using JUCE 6.1.2
System: Windows 64-bit VST3 on Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Host: Cakewalk by Bandlab @ 44.1 kHz

**Reproduction Steps:**

1. init patch
2. In FX Slot A1, select EQ.
3. Move the first gain lower. This is an arbitrary change, which we'll check later.
4. [Ctrl]+[left-drag] FX A1 to A2.
A2 contains what was in A1.
A1 contains an initialized FX of the correct type. The change we made in step 3 is not present in the A1 slot.

**Expected Behavior:**
Parameters of A1 and A2 are identical.

**Screenshots:**
.

**Computer Information (please complete the following information):**
.

**Additional Information:**
Occurs for any slots other than A1, A2.

**Comment by mkruselj** [comment]
Hmmmm cannot confirm over here in standalone. Can you try in standalone on your side?

**Comment by j5v** [comment]
I can. I'll grab the latest nightly and try again.

**Comment by j5v** [comment]
I've updated the **Reproduction Steps** to be more explicit about what to observe.

**Comment by mkruselj** [comment]
I can confirm it now. The keyword was doing a manual slider tweak. If you just load an FX preset, it copies over correctly.
