### ISSUE TITLE
LFO names not copied from Scene A to Scene B

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#5628]
**Bug Description:**
When I copy from Scene A and paste into Scene B, the LFO names remain as-is in Scene B.

**Surge Version**
Version: Surge XT 0.99.nightly.78fd32b
Build: 2021-12-04 @ 21:39:10 on 'fv-az33-805/pipeline' with 'MSVC-19.29.30137.0' using JUCE 6.1.2
System: Windows 64-bit VST3 on Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Host: Cakewalk by Bandlab @ 44.1 kHz

**Reproduction Steps:**
.

**Expected Behavior:**
.

**Screenshots:**
.

**Computer Information (please complete the following information):**
.

**Additional Information:**
When implementing LFO names recently, maybe we forgot to add the LFO name structures to the clipboard copy functions. :)

**Comment by baconpaul** [comment]
Oooh good catch yeah. Thanks. Tagged into XT1 milestone.

**Comment by baconpaul** [comment]
It also doesn't copy in scene fwiw. So name lfo1 as 'foobaz' and copy to lfo2 and the name stays 'lfo2'
