### ISSUE TITLE
1.9.0 compilation fails on Fedora 35, `error: call to non-‘constexpr’ function ‘long int sysconf(int)’`

### ISSUE THREAD

**Issue by joshhansen** [surge-synthesizer/surge#5629]
**Bug Description:**

Running `sh build-linux.sh build` in the Surge 1.9.0 source code results in this:

```
[ 95%] Building CXX object CMakeFiles/surge-headless.dir/src/headless/UnitTestUtilities.cpp.o
In file included from /usr/include/signal.h:328,
                 from /home/josh/Downloads/surge/libs/catch2/include/catch2/catch2.hpp:7714,
                 from /home/josh/Downloads/surge/src/headless/UnitTests.cpp:3:
/home/josh/Downloads/surge/libs/catch2/include/catch2/catch2.hpp:10455:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
10455 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/bits/sigstksz.h:24,
                 from /usr/include/signal.h:328,
                 from /home/josh/Downloads/surge/libs/catch2/include/catch2/catch2.hpp:7714,
                 from /home/josh/Downloads/surge/src/headless/UnitTests.cpp:3:
/usr/include/unistd.h:640:17: note: ‘long int sysconf(int)’ declared here
  640 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
In file included from /home/josh/Downloads/surge/src/headless/UnitTests.cpp:3:
/home/josh/Downloads/surge/libs/catch2/include/catch2/catch2.hpp:10514:45: error: size of array ‘altStackMem’ is not an integral constant-expression
10514 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
      |                                             ^~~~~~~~~~~~
[ 96%] Building CXX object CMakeFiles/surge-headless.dir/src/headless/UnitTestsDSP.cpp.o
gmake[3]: *** [CMakeFiles/surge-headless.dir/build.make:272: CMakeFiles/surge-headless.dir/src/headless/UnitTests.cpp.o] Error 1
gmake[3]: *** Waiting for unfinished jobs....
gmake[2]: *** [CMakeFiles/Makefile2:492: CMakeFiles/surge-headless.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:499: CMakeFiles/surge-headless.dir/rule] Error 2
gmake: *** [Makefile:248: surge-headless] Error 2

** Build of surge-headless failed**
```

**Surge Version**

* Version: 1.9.0
* Plugin Type: n/a
* Bitness: 64-bit

**Reproduction Steps:**
On Fedora 35 x86_64, and probably other distros:
1. Download surge 1.9.0 source
2. Unzip
3. Install necessary libraries and headers as per official instructions
4. sh build-linux.sh build

**Expected Behavior:**
Surge builds successfully

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following information):**
 - OS: Fedora 35 x86_64
 - Host: n/a
 - Version: n/a

**Additional Information:**
My efforts at finding a solution suggest that this may be related to a bug glibc, see https://bugs.launchpad.net/ubuntu/+source/segyio/+bug/1951658

**Comment by mkruselj** [comment]
Can you try building Surge XT and see if it's all good? We won't be updating the 1.9 branch anymore.

**Comment by baconpaul** [comment]
Also tbis is indeed a libc bug. Which compiler version are you using?

**Comment by baconpaul** [comment]
(You can still run surge by the way - just don’t build the unit tests on your platform)

**Comment by baconpaul** [comment]
Right and cafch2 has a patch for this we applied in xt https://github.com/surge-synthesizer/surge/commit/7a552038bab4b000d188ae425aa97963dc91db17 so I’m going to close this if you don’t mind
