### ISSUE TITLE
Trying to open MSEG editor crashes REAPER

### ISSUE THREAD

**Issue by ztnl** [surge-synthesizer/surge#5632]
Version: Surge XT 0.99.nightly.edd2344
Build: 2021-12-14 @ 21:30:30 on 'fv-az166-643/pipeline' with 'MSVC-19.29.30137.0' using JUCE 6.1.2
System: Windows 64-bit VST3 on        Intel(R) Core(TM) i7
Host: Reaper @ 48.0 kHz

**Trying to open MSEG editor crashes REAPER**

To reproduce:

1. Load INIT Sine

2. Load an MSEG into LFO slot 1

3. Click the icon to open the MSEG editor

REAPER crashes instantly.

I'm thinking now that this is the actual bug causing the crash — just trying to open the MSEG editor — rather than the more complex modulation scenario I was working with when I noticed the behavior.

See attached GIF.

![MSEG Crash edd2344](https://user-images.githubusercontent.com/81161256/146180896-174c019e-cc07-48dd-acc1-0b6ca5f33fcc.gif)

**Comment by ztnl** [comment]
Addendum:

Was curious to see if any previous builds I had in my SXT installer directory would similarly crash the host, so installed, surge-xt-win64-NIGHTLY-2021-12-11-320f685 to see...

With this build, it was possible to open the MSEG editor without crashing REAPER, so it appears to be something unique to edd2344.

**Comment by baconpaul** [comment]
Darnit will look first thing

**Comment by baconpaul** [comment]
Fixed - thanks @ztnl  as always!!
