### ISSUE TITLE
Natural sorting library we use doesn't put whitespace as more important than alphanumerics

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5634]
In Surge:

![image](https://user-images.githubusercontent.com/2393720/146212031-c6e6fd1c-ab87-45fc-ac81-287d41b3b77c.png)

In OS (Explorer in this case):

![image](https://user-images.githubusercontent.com/2393720/146212064-1d983893-2cca-4d8d-abd9-144f8d20181c.png)

**Comment by baconpaul** [comment]
ugh so i see why this happens but it is rather painful to fix. basically the compare is ignoring spaces to strip leading spaces so that `foo   2` is less than `foo 1`

but that means that `Scream Lead` ends up comparing as `ScreamLead`

i need to think about how to fix this.

**Comment by baconpaul** [comment]
I think (think) the fix is consecutive spaces become one space rather than spaces are stripped.

need to write some good tests here though.

**Comment by baconpaul** [comment]
<img width="169" alt="Screen Shot 2022-01-18 at 3 35 05 PM" src="https://user-images.githubusercontent.com/13387561/150014449-ce0125d1-ce20-4408-9cb4-9278ff7510ea.png">
