### ISSUE TITLE
Ability to trigger advancing the step sequencer on note input

### ISSUE THREAD

**Issue by kiwijam** [surge-synthesizer/surge#5635]
I'd like to be able to trigger advancing the step sequencer on note input.

An example:

I have a bar with 12 notes.
I have a step sequence like 0001.
I'd like every note to advance the sequence by exactly one step, such that every 4th note lands on a 1 in the sequence, regardless of the note's position in the bar, length of the note or any other factors.

**Comment by mkruselj** [comment]
This issue will be covered by modmappers (#1384) which will contain this as a mode.

**Comment by baconpaul** [comment]
although the advance-on-key may be a useful special purpose mode for the step sequencer which would be pretty easy too at least for an SLFO. Definitely a good idea we should build in!

**Comment by mkruselj** [comment]
Closing this one in favor of modmappers. They really will do this same exact thing.
