### ISSUE TITLE
"Activate individual scene outputs" option stored per instance

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5657]
Actually I wonder if this option should maybe only be displayed for FL Studio, and just have it enabled always in other DAWs, since they don't have problems with scene outputs being active all the time and they only enable them when you route those outputs to some tracks...

**Comment by baconpaul** [comment]
only displaying it for FL is a reasonable idea; I would be more into suppressing it in hosts we know work though. but either way.

As to how to do this one (so I can clear the code hints requested flag). it's pretty simple

1. The variable is called 'SurgeSynthesizer::activateExtraOutputs' and is set up from the SurgeSynthProcessor in the call to setupActivateExtraOutputs. Leave all of this unchanged. But also
2. Add it as a variable to the dawExtraState, stream and unstream it in the storage, and use that to write back onto the synth. 

Pretty straight forward. Just like editing any other synth param from the Daw Extra State. Leave the initialization path unchanged so the default is the same. Voila.
