### ISSUE TITLE
Make juce::AlertWindow look like our miniedits

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5663]
So that styling and `dialog` skin colors are all picked up the same way.

This means they should have a titlebar just like miniedits and overlays do, the whole nine yards with Surge icon in top left etc. What is currently the headline of AlertWindow should be printed centered in the titlebar.

**Comment by baconpaul** [comment]
When we do this, give them a component argument too so they center over the screen. This will fix Jacky's problem that a popup opened on primary when he was working on secondary.

**Comment by baconpaul** [comment]
So the way to do this is with an AlertOverlay basically and dump the juce alert windows.

**Comment by baconpaul** [comment]
So here’s My thought 

1. copy the typein overlay we use for prompt for mini edit 
2. Replace all the calls to juce alert box with a call to sge-> show alert 
3. Make that call show overlay
4. Style accordingly 

along the way you may want a developer menu option to call the function in the various modes so you can test without causing an actual error 

so Basically dup the about or prompt modal overlays for this purpose

**Comment by baconpaul** [comment]
So this is actually quite a bit of work if we are going to do all the accesibility work also. Shall we move this out of the milestone?

**Comment by mkruselj** [comment]
I still haven't given up on doing this, just was busy on NI side of things...
