### ISSUE TITLE
LFO display doesn't update when switching from indexedto non-indexed modsource

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#5670]
**Bug Description:**
When switching directly from FORM 1.2 to any other shape in that same modulator, the display will not update.

**Surge Version**
Latest nightly.

**Reproduction Steps:**
1. Open a new Surge instance.
2. Set LFO1 to the FORM shape.
3. Change the index to FORM 1.2, for instance.
4. Switch to any other shape in that same modulator (modulator 1)
5. The modulator display won't update.

**Screenshots:**
![modbug](https://user-images.githubusercontent.com/50145178/147401803-a0e08d34-59cd-4a61-b3da-97a2e44da415.gif)

**Comment by baconpaul** [comment]
Oh good catch. If you change type to an Unndexed type it should refer the index to 0

**Comment by mkruselj** [comment]
@baconpaul But, I think it would be nice if the selected index would be remembered so that it doesn't throw you back to FORM 1.1 every time you go back to Formula as LFO type. Agree?

**Comment by baconpaul** [comment]
for 1.1. that's an additional bit of state i don't want to add and stream this late.

**Comment by mkruselj** [comment]
Fair point. So fix the messy UI before 1.0 release and add nice UX in 1.1. Fine by me!
