### ISSUE TITLE
ARM linux build

### ISSUE THREAD

**Issue by gminorcoles** [surge-synthesizer/surge#568]
I would like to build surge for ARM devices. I have not had time to start this but it seems like a good idea to have a placeholder issue for it. 

I guess related issues that could be linked from here pertain to linux paths and such. I have been building and getting to know a raspberry pi based synth called zynthian this week and it installs everything under root, it would be good to be able to force all surge stuff into its own path prefix and not assume any nice layout of directories (if needed.)

**Comment by baconpaul** [comment]
Do the arm chips support sse2 instructions? If not the stuff in src/common/dsp will be a challenge. I think start with that question maybe?

Would love this to work if feasible!

**Comment by jsakkine** [comment]
Let us close this now as #570 is in a more concrete and has the same definition of done.
