### ISSUE TITLE
Pasting a modulator does not update UI to show that the modulator has targets

### ISSUE THREAD

**Issue by selenologist** [surge-synthesizer/surge#5684]
**Bug Description:**
When copying and pasting modulators with targets (or a whole scene), the ring around modulators that shows that it has connections does not light. The targets themselves work, but the UI does not reflect it. Saving and reloading the patch goes back to displaying correctly.

Copying and pasting a whole scene turns off the modulator rings even when they were on before, regardless of what they should be.

**Surge Version**
Version: Surge XT 0.99.main.e3c300be
Build: 2021-12-30 @ 19:52:49 on 'rainbow/local' with 'GNU-11.1.0' using JUCE 6.1.2
System: Linux 64-bit VST3 on  AMD Ryzen 7 2700X Eight-Core Processor
Host: Ardour @ 48.0 kHz

**Reproduction Steps:**
1. Create a connection from any modulator to any target.
2. Right-click Copy Modulator with Targets
3. Right-click Paste on a modulator without any existing targets

**Screenshots:**
Expectation
![expectation](https://user-images.githubusercontent.com/16075411/147742794-f574ccd7-510a-4137-b070-986c7d6bb65d.png)
Reality
![reality](https://user-images.githubusercontent.com/16075411/147742800-5831db7b-6efa-4870-8a28-165f28ee9997.png)

**Comment by baconpaul** [comment]
great bug report
i wonder what's wrong
can repro

**Comment by baconpaul** [comment]
Oooh the internal state is getting confused on paste

If I copy with mods and paste and look in the list i see
<img width="906" alt="Screen Shot 2021-12-30 at 7 50 37 PM" src="https://user-images.githubusercontent.com/13387561/147796882-75f00acd-bfe8-4186-be88-6d9979fd3038.png">

If I save and reload that patch, it's gone back to a
