### ISSUE TITLE
Clicking outside of Surge XT window with open menus can lead to undefined mouse focus behavior

### ISSUE THREAD

**Issue by ServusCarolus** [surge-synthesizer/surge#5692]
**Bug Description:**
Using the Cinnamon 5.0.7 desktop on Manjaro Linux, after respectively left- or right-clicking on the Surge XT patch browser rectangle or another component that can open a menu, then clicking outside the focus of the Surge XT window instead of clicking on a menu item or pressing ESC, the mouse pointer will show undefined behavior either regarding pointing mode or visibility.

**Surge Version**
Two versions are tested: standalone and VST3

Standalone
Version: Surge XT 0.99.main.c01a819f
Build: 2021-12-30 @ 12:35:57 on 'elbereth/local' with 'GNU-11.1.0' using JUCE 6.1.2
System: Linux 64-bit Standalone on  AMD Ryzen 7 1700 Eight-Core Processor
Sample Rate: 48.0 kHz

VST3
Version: Surge XT 0.99.main.c01a819f
Build: 2021-12-30 @ 12:35:57 on 'elbereth/local' with 'GNU-11.1.0' using JUCE 6.1.2
System: Linux 64-bit VST3 on  AMD Ryzen 7 1700 Eight-Core Processor
Sample Rate: 48.0 kHz

**Reproduction Steps:**

Standalone: Clicking on Patch Browser, then desktop
1. Open Surge XT using Cinnamon desktop.
2. Left- or right-click on the patch browser rectangle.
3. While the menu is open, move the mouse pointer outside the main Surge UI window and left or right click on the desktop background.
4. Move mouse pointer over Surge UI.
5. The mouse pointer is in a window-resizing mode: Moving the pointer over the Surge UI will attempt to resize the window. One must hover over the Surge window edge, wait for the resizing arrow to appear, then left-click. Then see if normal focus has resumed. Otherwise repeat until successful.

Standalone: Clicking on Patch Browser, then app window
1. Open Surge XT using Cinnamon desktop.
2. Left- or right-click on the patch browser rectangle.
3. While the menu is open, move the mouse pointer outside the main Surge UI window onto an open app window and click to change focus.
4. Move mouse pointer over Surge UI.
5. If the pointer passed over the desktop background at any time when moving from the Surge UI to the app window, the mouse pointer is in a window-resizing mode: Moving the pointer over the Surge UI will attempt to resize the window. One must hover over the Surge window edge, wait for the resizing arrow to appear, then left-click. Then see if normal focus has resumed. Otherwise repeat until successful.
6. If the pointer did not move over the desktop background, then one may move the pointer back over the Surge UI (but not over the desktop background. One of two things will happen subsequently:
7. If one left-clicked on the patch browser, one must simply left-click once in the Surge UI to change focus, then a second time to interact with UI elements.
8. If one right-clicked on the patch browser, as soon as one moves the pointer over the UI, a slider or some other element may be auto-selected and changed as a result. Another left-click will be needed to release that selection. The slider would have to be set back where it was.

Standalone: Right-clicking on UI menu, then desktop
1. Open Surge XT using Cinnamon desktop.
2. Right-click on a UI element to open a menu.
3. While the menu is open, move the mouse pointer outside the main Surge UI window and left or right click on the desktop background.
4. Move mouse pointer over Surge UI.
5. The mouse pointer is in a window-resizing mode: Moving the pointer over the Surge UI will attempt to resize the window. One must hover over the Surge window edge, wait for the resizing arrow to appear, then left-click. Then see if normal focus has resumed. Otherwise repeat until successful.

Standalone: Right-clicking on UI menu, then app window
1. Open Surge XT using Cinnamon desktop.
2. Right-click on a UI element to open a menu.
3. While the menu is open, move the mouse pointer outside the main Surge UI window onto an open app window and click to change focus.
4. Move mouse pointer over Surge UI.
5. If the pointer passed over the desktop background at any time when moving from the Surge UI to the app window, one click on the Surge UI restores focus and expected interaction. This is actually the expected behavior. 
6. If the pointer did not move over the desktop background, then as soon as one moves the pointer over the UI, a slider or some other element may be auto-selected and changed as a result. Another left-click will be needed to release that selection. The slider would have to be set back where it was.

VST3: Left-clicking on Patch Browser, then desktop
1. Open Surge XT UI.
2. Left-click on the patch browser rectangle.
3. While the menu is open, move the mouse pointer outside the main Surge UI window and left or right click on the desktop background.
4. Move mouse pointer over Surge UI.
5. As soon as one moves the pointer over the UI, a slider or some other element may be auto-selected and changed as a result. Another left-click will be needed to release that selection. The slider would have to be set back where it was.

Otherwise, in the VST3, right-clicking on the patch browser, then desktop; clicking on the patch browser, then an app window; and right-clicking on a UI menu, then an app window all produce the expected behavior, regardless of whether the pointer transects the desktop or not.

**Expected Behavior:**
One would expect that the mode of the mouse pointer would not change, only the focus, and the menus, etc., would just close. One would click back on to the UI without any additional interactions.

**Computer Information:**
 - OS: `Linux elbereth 5.10.84-1-MANJARO #1 SMP PREEMPT Wed Dec 8 09:50:30 UTC 2021 x86_64 GNU/Linux`
 - Desktop: Cinnamon 5.0.7
 - Host: Carla
 - Version: 2.4.1

**Additional Information:**
I use the following script to update the standalone modules, then update the VST3 folders manually:

#!/bin/bash
cd ~/git_repos/surge
git pull -p
git submodule update --init --recursive
#cmake -Bbuild
#cmake --build build --config Release --target surge-staged-assets
cmake -Bignore/sxt -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/charles/.local
cmake --build ignore/sxt --config Release --parallel 8
cmake --install ignore/sxt

**Comment by mkruselj** [comment]
Cannot confirm on Windows, at least.

**Comment by baconpaul** [comment]
Those were exactly my thoughts (along with being appreciative for the detailed bug report) but I am yet to look

**Comment by haenkel** [comment]
I can confirm the above with a Cinamon desktop

and slightly different behaviour with the default Ubuntu20 desktop,
where a click outside of the UI doesn't close the menu.

Same also happens with b-step ('options' is the only popup there)

While on cinamon I played with some conditionals in juce's PopupMenu.cpp
and got to a point where the above stops happening ... but also broke patch selection.
 
So no solution yet but something somewhere here:
https://github.com/juce-framework/JUCE/blob/master/modules/juce_gui_basics/menus/juce_PopupMenu.cpp#L728

**Comment by baconpaul** [comment]
Oh excellent

Shall I post up on the juce forum? Or would you like to? I'm sure they would merge this or something very close to it!

**Comment by haenkel** [comment]
I don't have an account in their forum, so if you could tell them would be great.
There is surely a better solution but good enough for "problem goes away if you do this",
from there they know best what to do.

**Comment by baconpaul** [comment]
https://forum.juce.com/t/problem-with-menus-cursors-linux-with-patch-that-solves/51350

**Comment by baconpaul** [comment]
Oh cool I merged the surge branch change just now. Thanks!
