### ISSUE TITLE
Right-Clicking repetitively on an FX unit to bypass it doesn't work reliably

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#5695]
**Bug Description:**
Right-Clicking repetitively on an FX unit to bypass it doesn't work reliably. The first time I reach over to the unit selector and you do it it works fine, but if I right-click repetitively without really moving the mouse, it won't always toggle.

I'm running FL Studio 20.9 inside Windows 10 x64.

**Comment by mkruselj** [comment]
I'd use the new double click to bypass anyways, since in 1.1 we will change the right click to open FX preset context menu so that you can load the FX right there in the grid.

Still, good report, curious why this happens.
