### ISSUE TITLE
Combulator in Debug Mode on M1 is very very slow

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#5699]
Details to come

**Comment by baconpaul** [comment]
Its just super slow in debug mode. Not sure why. I'm gonna bump this to 1.1. None of the code changes we made in 1.0 from 1.9 make the difference.

**Comment by baconpaul** [comment]
this really is only a debug mode problem. i'm going to bump it again.

**Comment by mkruselj** [comment]
@baconpaul Do we even care, then?
