### ISSUE TITLE
Typein range error shows per param message

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#5715]
You know like “you entered a number below the minimum value of 8.73”

**Comment by mkruselj** [comment]
Suggestion:

* if larger "Input must not be larger than x!"
* if smaller "Input must not be smaller than x!"

**Comment by baconpaul** [comment]
OK here's how this works. 

- When you enter a value `src/surge-xt/overlays/TypeinParamEditor.cpp` method `::textEditoReturnKeyPressed` 
- which subsequently calls `::handleTypein`.  
- which subsequently calls `src/surge-xt/gui/SurgeGUIEditor.cpp` methods `setParameterModulationFromString` or `setParameterFromString` or `setControlFromsString`
- which subsequently call `src/common/Parameter.cpp` method `Parameter::set_value_from_string` or variants thereof

The actual parsing happens in `Parameter::set_value_from_string` (with variations for modulation and stuff) - you can see how SurgeGUIEditor makes the calls.

Now if that returns true and the value is set we are all good. But if it returns false you can see that `TypeinParamEditor::textEditrReturnKeyPressed` does two things

1: sets `wasInputInvalid = true` and repaints
2: sets a timer to set that to false and repaint in 2 seconds

That's what causes the error message to blink. As you can see around line 66 of TypeinParamEditor, if wasInputInvalid we replace the primary val with an error message (look for "Input out of range!")

So the work here is

1: have Parameter.cpp crete the error message and pass it back through the stack and
2: have Typein paint that while
3: dealing with the case where parameter doesn't make an error message

So here's how I would do it

1. Change the signature of set_value_from_string from  `bool Parameter::set_value_from_string(const std::string &s)` to `bool Parameter::set_value_from_string(const std::string &s, std::string &errmsg)` and in the top of set_value_from_string say 'errmsg = std::string()` to default it to empty. Then build surge-xt and the tests and clean up the compile errors by adding a string argument. (set_value_from_string is called in about 6 places so not so bad).
2. Then wind from TypinParamEditor down to that set_value call with an optionl string. So change the signature of handleTypein and setParameterFromString and call with a string argument
3. Then add a member to the type param which is 'errorToDisplay' or some such. Change the paint to paint that
4. Then in the type callback if you are false, also set the error to display to whatever came back if it isn't empty, or to "Invalid value!" if it is (whatever the current message is)
5. Then take one and only one case in parameter.cpp set value and make it populate the error with whatever like 'you blew it ha' and see if you can see the error

So good now you are close. Now the work is

1. Repeat above for modulation and controls

and then

In parameter.cpp and so forth make reasonable error messages if you can. 

BUT you can get this merged by only having one of each of modulation, value, and control show a custom message. You don't have to get every control type, since we default if it isn't there. At this point you have something mergable and from there we can get the rest of the control type ranges.

So not a small change but not an impossible one.

**Comment by baconpaul** [comment]
before we close this @baconpaul want's to add a few retests for the string conversion
