### ISSUE TITLE
Surge plugin keeps on crashing in Cakewalk

### ISSUE THREAD

**Issue by MandelaEffectBS** [surge-synthesizer/surge#5724]
**Bug Description:**
I installed the Surge synth plugin but when I try to insert it as an instrumental track, Cakewalk crashes.
I reinstalled, tried safe mode...but it didn't work out. Dump file seems to suggest it's nothing to do with the cakewalk but something to do with the Surge plugin.
Thanks so much for helping me.

**Surge Version**
Surge-1.9.0

* Version:
* Plugin Type: VST3i (VST3 instrument)
* 64-bit

**Reproduction Steps:**
1. Open Cakewalk (You have already downloaded and installed Surge, and rearrange preferences so that the .dll file of Surge can be recognized by Cakewalk.)
2. Click on plugin>instrument rack of Cakewalk (on the right. If you press "B," and it appears)
3. Drag and drop Surge icon, press "Ok"
4. Then you get this error:
5.  (https://user-images.githubusercontent.com/93069875/147949885-87713d36-53f6-48ed-afc9-adb7d454b60f.png)

**Expected Behavior:**
I'd love to open the Surge plugin.

**Screenshots:**
(https://user-images.githubusercontent.com/93069875/147949885-87713d36-53f6-48ed-afc9-adb7d454b60f.png)

**Computer Information (please complete the following information):**
 - OS: Windows 10 Home
 - Host: Cakewalk
 - Version: Cakewalk 27.12.0.102 (the latest version)

**Additional Information:**
I have already sent the dump file to people at Cakewalk, and they suggested the error is happening within Surge.

**Comment by baconpaul** [comment]
Do you have windows set up with a japanese or korean or russian charset by any chance? 1.9 had some problems in those cases.

We are about 2 weeks away from trying our next version. Would be very curious if the beta of that version works for you . You can download it here: https://surge-synthesizer.github.io/nightly_XT

**Comment by MandelaEffectBS** [comment]
I will write back to you in detail very soon, but unfortunately, the beta version still crashes. (I use windows with Japanese charset. ) Thanks for your response!

**Comment by mkruselj** [comment]
@MandelaEffectBS Thanks for reporting back!

Is there any chance you could try this with another DAW, for example Reaper?

**Comment by baconpaul** [comment]
Or the standalone too!
And yeah I agree

**Comment by MandelaEffectBS** [comment]
Sorry, but I don't have any other DAWs.  And there is a standalone version of Surge??? I'm not sure

**Comment by baconpaul** [comment]
Surge xt (the beta you installed) does have a standalone version which should be in program files

**Comment by mkruselj** [comment]
> Sorry, but I don't have any other DAW. And there is a standalone version of Surge??? I'm not sure

You can [download Reaper](https://www.reaper.fm/download.php) and try it out for 60 days for free, easy.

**Comment by MandelaEffectBS** [comment]
I need to apologize...just realized I had installed 2021-04-25-e679f24 and had thought it was the latest beta version. I reinstalled NIGHTLY-2022-01-04-9c1ef76 and not only the standalone version works fine, but there's no crash in Cakewalk! Also, it works on reaper, too. The latest beta version is great.

Thus, case is closed! Thank you all for being so patient.

**Comment by mkruselj** [comment]
Great news - thank you!

**Comment by baconpaul** [comment]
Wonderful!! Thank you
