### ISSUE TITLE
NIGHTLY-2022-01-07-8cbc44f won't install on Mac due to a signature error

### ISSUE THREAD

**Issue by pitermach** [surge-synthesizer/surge#5736]
Downloaded the version in the title (multiple times to rule out internet problems). Clicking on the pkg file in the dmg errors out saying Apple can't check this package for malicious software. Overriding the security check by choosing open from the context menu does launch the installer, but it errors out with

> surge-xt-macOS-NIGHTLY-2022-01-07-8cbc44f.pkg can’t be installed because its digital signature is not trusted.

Mac OS 12.1 on M1

**Comment by baconpaul** [comment]
hmm let me look

**Comment by baconpaul** [comment]
yeah it's my fault. reverting something quickly. next nightly should be fine.

**Comment by baconpaul** [comment]
Anyway thank you very much. This is resolved and the new nightly at https://github.com/surge-synthesizer/releases-xt/releases/tag/Nightly comes through fine with no signature problem.
