### ISSUE TITLE
No audio inputs for VST3 in Ardour

### ISSUE THREAD

**Issue by magnetophon** [surge-synthesizer/surge#5743]
**Bug Description:**
The VST3 version of both 1.9 and XT don't have audio inputs when used in Ardour.
Not sure if that's an Ardour issue or a Surge issue.
The LV2 and standalone are fine.

**Surge Version**

* Version: Any.
* Plugin Type: VST3
* Bitness: 64-bit

**Computer Information (please complete the following information):**
 - OS: Linux
 - Host: Ardour

**Comment by baconpaul** [comment]
Really pretty sure this is an ardour problem not a surge problem.

**Comment by baconpaul** [comment]
audio in with the VST3 works in reaper, bitwig, live, fl, cubase, studio one, and carla
I think the thing the ardour devs need to do is deal with non-main input busses on synths in the vst3 spec
so I'm going to close this one here.

**Comment by magnetophon** [comment]
Thanks, I reported it on the [ardour bugtracker](https://tracker.ardour.org/view.php?id=8855).
