### ISSUE TITLE
Mod/Pitch Wheel interface support

### ISSUE THREAD

**Issue by Altarberg** [surge-synthesizer/surge#5746]
It would be very useful to have some way of being able to change the mod and pitch wheel value from the interface, especially when creating patches without using a midi controller.

Also VK!

**Comment by mkruselj** [comment]
Extra: dragging up-down via mouse on an already mouse clicked key could do aftertouch, and dragging left-right could pitch bend, perhaps.

**Comment by baconpaul** [comment]
knocking this one off next, at least the basics of pitch and mod wheel on the vk

**Comment by mkruselj** [comment]
Great! Rough it out and I'll finesse 🙂
