### ISSUE TITLE
Disallow (at least) following MIDI CCs for MIDI learn: 0, 32, 120, 123

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#575]
The above mentioned MIDI CCs are not supposed to be utilized for MIDI learn because they have reserved special functions as far as MIDI goes: CC#64 is sustain pedal, CC#120 is all-sound-off (kills all sound and releases all voices immediately) and CC#123 is all-notes-off (sends note off to all keys, all voices have their envelopes immediately proceeding to their release stages).

0 and 32 are used for Bank Select, which is important if Program Change support is going to be implemented to Surge (which I will open another ticket for).

**Comment by baconpaul** [comment]
We chatted and 64 is useful to be learnable!

**Comment by mkruselj** [comment]
Indeed it is!

**Comment by baconpaul** [comment]
This is all in SurgeSynthesizer::channelController in src/common/SurgeSynthesizer.cpp

Some of these are already blocked for coming in and shouldn't learn.

but that's where you want to start.
