### ISSUE TITLE
Crash when playing two notes with 03 The Init Function And State at the same time

### ISSUE THREAD

**Issue by xard-dev** [surge-synthesizer/surge#5752]
**Bug Description:**
Surge XT crashes when playing two notes with **03 The Init Function And State** instrument from different instances at the same time. Currently tested on Ardour.

**Surge Version**
Surge XT
* Version: 0.99.main.efad089
* Plugin Type: LV2 and VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Add two instances of Surge XT to the project.
2. Change both instance instruments to **03 The Init Function And State**
3. Create two midi tracks where one instance plays first then the other at the same time
4. Play the track

**Expected Behavior:**
The two instances of Surge XT play the notes as expected.

**Screenshots:**
![image](https://user-images.githubusercontent.com/65303522/149003706-40b3fad8-69ee-4001-824d-08a2dc58eca7.png)

**Computer Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Host: Ardour
 - Version: 6.9 (tested with stable release and later debug build)

**Additional Information:**
Repeatable every single time.

Error output in terminal:
```
SurgeXT VST3
  - Version      : 0.99.nightly.efad089 with JUCE 60102
  - Build Info   : 2022-01-11 13:41:05 using GNU-7.5.0
  - Data         : "/usr/share/surge-xt"
  - User Data    : "/home/xard/Documents/Surge XT"
[Thread 0x7fffae7fc700 (LWP 19470) exited]
[Thread 0x7fffc9438700 (LWP 19462) exited]
[New Thread 0x7fffc9438700 (LWP 19575)]
[Thread 0x7fffc9438700 (LWP 19575) exited]
Guarded stack leak: [prepareForEvaluation::subscriptions::gv] exit=5 enter=4
PANIC: unprotected error in call to Lua API (attempt to index a boolean valuePANIC: unprotected error in call to Lua API (attempt to index a boolean value)
)
pure virtual method called
terminate called without an active exception
malloc(): unsorted double linked list corrupted
```

*Update 1*
No crash when using mixed VST3 + LV2 instances. (Though using the plugins with this combination might separate LUA contexts)

*Update 2*
Crash with VST3 + VST3 instances confirmed.

**Comment by baconpaul** [comment]
Oh that’s very bad.
Let me see if I can reproduce it on mac 
Thank you very much

**Comment by baconpaul** [comment]
yeah confirmed reaper mac
i must have something improperly static
i will look.
thank you very much

**Comment by baconpaul** [comment]
Very good i see the change that made this happen, and i also see the correct fix for it.
Will have something tonight.
Thank you very much.

**Comment by baconpaul** [comment]
So here's what was happening

when i first wrote formula, i would leak the functions. Not anything else but the functions would stay in the loa state forever. That was a bummer. but who cared. I tested everything and it worked. Including the two surge case.

Then I added function cleanup

And didn't test the two surge case

Anyway turns out the function cleanup state was global not per instance. The rest you can imagine

So I did the right thing which is have function state per instance and now it all works.

Merge soon, new nightly tonight.

Thank you very much. This was a critical bug and we found it very late in the cycle.
