### ISSUE TITLE
DeRez noise - envelope doesn't suppress

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#5771]
Altenberg — Today at 5:16 PM

Ancient Fm > sometimes when loaded emits a constant sound until a key is pressed. It comes from DeREz, but if it has the envelope assigned I understand that it shouldn't produce any sound.

**Comment by mkruselj** [comment]
@baconpaul I reckon the antidenormal removal PR might actually fix this?

**Comment by baconpaul** [comment]
Yeah almost definitely but why is the envelope open also? Those are the two things I want onto check before we close

**Comment by baconpaul** [comment]
OK this is resolved; if i assign an SLFO to Voice of Starship it no longer plays on load. I remember fixing this when Jacky raised it also but can't find the commit. But closing this

**Comment by mkruselj** [comment]
Wonder if it was indirectly fixed by #5878.

**Comment by baconpaul** [comment]
Nah it’s a scene tbing and I remember fixing it for Jacky but I can’t find the commit (or can’t be bothered to hunt for it more accurately)
