### ISSUE TITLE
BuildRoot environment for Raspberry PI 3

### ISSUE THREAD

**Issue by jarkk0sakkinen** [surge-synthesizer/surge#578]
Fork BuildRoot under this project and add commits on top to:

- BuildRoot recipe for headless version of Surge.
- Derive`raspberrypi3_surge_defconfig` from `raspberrypi3_defconfig`. The only difference will be to include newly created Surge recipe.

BuildRoot can be used on Windows and macOS by using an awesome tool called Vagrant [1][2].

[1] https://www.vagrantup.com/
[2] https://buildroot.org/downloads/manual/manual.html#getting-buildroot

**Comment by baconpaul** [comment]
Need me to do a fork for you at surge-synthesizer or do you have perms for that? Just lemme know

Pretty amazing if we can make this work on the pi. Might send me out to the wood shop to build a keyboard case!

**Comment by jsakkine** [comment]
I think I've today managed to fill out the blanks from where we are now to make ARM happen. Without already having some kind of headless version this would much more notorious workload. GUI probably can be probably made also eventually work with Carla but it is great that we don't need to make the "full stack" happen to see some results (and close this issue).

**Comment by baconpaul** [comment]
Ok! If you need some GitHub shenanigans you can’t do just ping me or kzantow or what not. Exciting stuff!!

**Comment by jsakkine** [comment]
I  will also make the board accessible in headless way:

- DCHP query
- SSH server
- Zeroconf (the broadcast surge-synthesizer.local hostname to LAN).

Then you can just build an image, hook up the power cable and network cable to the board and `ssh surge@surge-synthesizer.local`.

**Comment by jsakkine** [comment]
I can apply some of this to try out the image in QEMU: https://github.com/wimvanderbauwhede/limited-systems/wiki/Raspbian-%22stretch%22-for-Raspberry-Pi-3-on-QEMU
