### ISSUE TITLE
cmake generated ZIP files cannot unpack with built-in Windows unpacker

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5782]
So cmake is lying to us, apparently. I suppose the answer is to try and use Azure's Archive Files task, or a PowerShell command. Up to @baconpaul to decide.

**Comment by baconpaul** [comment]
OK well you can test this locally!
https://github.com/surge-synthesizer/surge/blob/1edd725e51c236022d5f4cbc939e68453de15af4/src/cmake/lib.cmake#L95

that line
change it to `COMMAND 7z a -r ${SURGE_XT_DIST_OUTPUT_DIR}/surge-xt-win${SURGE_BITNESS}-${SXTVER}-pluginsonly.zip ${SURGE_PRODUCT_DIR}`
then locally build the target surge-xt-distribution
and if you get a zip that works push in the PR
