### ISSUE TITLE
Make all those tiny url files in the pipeline

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#5784]
Which, as we found on 1.0 install day, I had not done!

**Comment by mkruselj** [comment]
@baconpaul So, this one fixed now?

**Comment by baconpaul** [comment]
we will find out when we ship 1.0.1 :)

**Comment by baconpaul** [comment]
One to make releases in the url as situated

**Comment by baconpaul** [comment]
Something completely different and sorry if I post it here, but it's the fastest way to tell you:
The download link 'https://github.com/surge-synthesizer/releases-xt/releases/download/1.0.1/surge-xt-win32-1.0.1-setup-x86.exe'
offered on 'https://surge-synthesizer.github.io/downloads' to download 'Windows 32-bit VST3' doesn't work.
Edit:
I think the correct link would be:
'https://github.com/surge-synthesizer/releases-xt/releases/download/1.0.1/surge-xt-win32-1.0.1-setup.exe'
(This one worked for me)

**Comment by baconpaul** [comment]
OK this should be resolved with the above commit, but we can't test it until the 1.1 release without doing a fake release which i want to avoid. So close this if 1.1 gets done and mark it resolved.

**Comment by baconpaul** [comment]
This worked!
