### ISSUE TITLE
Drag and Drop Modulator with MSEG Open

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#5797]
Drop a modulator onto the MSEG window and it pops for the coordinate at that location

![unknown](https://user-images.githubusercontent.com/13387561/150140613-5456f57e-03ca-4913-9776-4c7b3bd018c0.png)

**Comment by baconpaul** [comment]
mildly fiddly. let me grab this one sometime in cycle.

**Comment by mkruselj** [comment]
I think I managed to figure it out!
