### ISSUE TITLE
ASIO missing from list of Audio Device type in Standalone

### ISSUE THREAD

**Issue by wibblemonkey** [surge-synthesizer/surge#5798]
**Bug Description:**
The dropdown list of Audio Device type in the standalone on Windows does not include ASIO.

**Surge Version**
* Version: Surge XT 1.0.0.1edd725
* Plugin Type: Standalone
* Bitness: 64-bit

**Reproduction Steps:**
1. Go to 'Options | Audio/MIDI Settings...'
2. Click on 'Audio Device type...'
3. List does not contain ASIO.

**Expected Behavior:**
ASIO is available in the list of audio device types.

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following information):**
 - OS: Windows 10
 - Host: Standalone
 - Version: n/a

**Additional Information:**
See the same dialog in the standalone version of OB-Xd for comparison.

**Comment by baconpaul** [comment]
Hi

We are unable to distribute an ASIO build of the standalone due to ASIO not having a GPL3 compatible license.

You can build your own here: https://github.com/surge-synthesizer/surge#building-with-support-for-asio

Or you can host the VST3 in a standalone ASIO host like savihost.

Thanks
