### ISSUE TITLE
Overzealous hovers in oscillator select multiswitch

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5801]
![hovers](https://user-images.githubusercontent.com/2393720/150218676-1004be35-9406-4894-a030-d3f0f756bf79.gif)

And ONLY that one. All other multiswitches seem to be perfectly fine otherwise.

**Comment by mkruselj** [comment]
Something similar happens when dragging the scene select multibutton:

![eeep](https://user-images.githubusercontent.com/2393720/153724130-8dbb9410-3ec3-44aa-ac29-966776ebd23f.gif)

**Comment by mkruselj** [comment]
Aaaaaaaand same thing happens with envelope digital/analog mode button.

**Comment by baconpaul** [comment]
I bet I know what it is. Hold on.

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/blob/3e966c521ef40b0c039fd6bb09efbb32974b2af5/src/surge-xt/gui/widgets/MultiSwitch.cpp#L192

If you comment out that line does it go away?

**Comment by mkruselj** [comment]
@baconpaul Nope, still happens.

**Comment by baconpaul** [comment]
huh ok lemme switch over to windows and see if i can find it then.

**Comment by baconpaul** [comment]
ahhhhhhhh what a pain
this happens because changing that value rebuilds the ui and that blows up the hover state
I know why but I am not sure what to fix yet

**Comment by baconpaul** [comment]
which in turn causes a focus gained but we don't have a mouse position so we fake one to set the hover on focus input. let me adjust that.
