### ISSUE TITLE
Touch-based input issues

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5802]
So this one is gonna be a bit difficult to explain, but using my Surface Pro 4, I can notice these weirdities:

- [ ] Context menus (i.e. patch browser, filter type, osc type, FX type, main menu) don't always open under the location where I pressed
- [x] Long press to right click doesn't work
- [x] Touchscreen mode doesn't set the mouse sensitivity to Exact in the back end, so if we're at default Legacy setting, moving sliders doesn't follow finger movement either

**Comment by baconpaul** [comment]
So the long-press-to-right-click after seeing jatin's solution is really just a timer.
maybe i could do that so it printed in the slider on a long hold and you could go from there?
sound good?

**Comment by baconpaul** [comment]
OK so for the main menu position try this

replace this code

```
if (tag == tag_settingsmenu)
        {
            useDevMenu = true;
            showSettingsMenu(juce::Point<int>{}, control);
            return 1;
        }
```

with 

```
if (tag == tag_settingsmenu)
        {
            useDevMenu = true;
            showSettingsMenu(control->asJuceComponent()->getTopLeft(), control);
            return 1;
        }
```
