### ISSUE TITLE
Drop-Down Menus are small on a 4k screen

### ISSUE THREAD

**Issue by tsigoulas** [surge-synthesizer/surge#5811]
**Bug Description:**
All the Drop-Down Menus are small on a 4k screen (4096x2160)

**Surge Version**

* Version: XT 1.1 nightly.8d294da
* Plugin Type: [VST3]
* Bitness: [64-bit]

**Reproduction Steps:**
click to open any drop-down menu
**Expected Behavior:**
Small drop-down Menus

**Screenshots:**
https://i.imgur.com/758xm0T.jpg

**Computer Information (please complete the following information):**
 - OS: Windows 10 64bit
 - Host: Reaper
 - Version: v.6.46
![Surge XT small size drop-down menus](https://user-images.githubusercontent.com/93413808/150655607-01119a2c-b1cd-4d39-be3d-769a91bdf3ed.jpg)
 
 - 
**Additional Information:**

**Comment by baconpaul** [comment]
So the menus follow the os scaling not the plugin scaling. When I tested windows 4k at 100% the menus in surge were same Size as in reaper

I’m assuming you are after a mode where the menus are a scaled up version consistent with surge 100%? That’s a bit painful but can I first confirm your scaling and hdpi settings? 

Thanks

**Comment by tsigoulas** [comment]
My OS scaling is at 200%, Surge XT scaling is at 159%, Reaper shortcut properties setting "high DPi Scaling override" is set to application.  Also, I would like to mention that  the Original Surge v1.9 is scaling the drop-down menus just fine, so it seems that something broke with the XT code. Hope that helps, thanks again for your amazing work!

**Comment by mkruselj** [comment]
XT UI code is totally different from 1.9 because we have changed frameworks. 1.9 used OS based menus, whereas XT uses JUCE managed menus. These are very different, but I would not say "broken".

**Comment by tsigoulas** [comment]
I see... So, is this something that can be improved in future updates? Unfortunately, to be able to use the plugin on a high resolution screen is only possible with WIndows Magnifier, at least for my old eyes :). Thanks!

**Comment by baconpaul** [comment]
Maybe! 

It is trivial to fix if I want everyone else’s menu to be way too large - but obviously we don’t! So gotta figure out the windows hdpi shenanigans 

if you could record every scale setting you have (os and reaper) in this issue I can look

there may be a way to make them “optionally way too big” which you would turn on and others would turn off. (I say “way too big” because really they would be).

**Comment by tsigoulas** [comment]
So, windows scaling is at 200% and HDPi settings for the Reaper exe are set to "application", when I switch back to "system" or "system enhanced" menus are normal but all graphics are blurry. I guess an option in the settings would be ideal for that issue...
Here are the Reaper.exe HDPi settings [https://i.imgur.com/17fLnrS.jpg](url)
Thanks again!!!

**Comment by baconpaul** [comment]
ok cool i'll look before 1.1
i may be able to add an option
thank you for the settings.

**Comment by tsigoulas** [comment]
> ok cool i'll look before 1.1 i may be able to add an option thank you for the settings.

Great, thank you so much!
