### ISSUE TITLE
Sporadic lock on favorites

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#5815]
From KVR

[quote=margaret0547 post_id=8332551 time=1642943087 user_id=538748]
Edit: I can't reproduce this, FYI.

I'm getting this in a popup when I try to do save or heart.

"SQL Error[5]: database is locked"

The popup won't go away by clicking "OK"

Thanks.

[Reaper v6.46, Windows 8]
[/quote]

[I responded]

Hmm I worked super hard to make sure that case didn't happen. Do you remember anything about your system at the time? I wonder if the favorites lock while the db is being built - that isn't a conflict case i tested. I'll add this to GitHub to poke on that thesis some.

Thanks!

**Comment by baconpaul** [comment]
OK here's the situation where this happens

you have no database or are undertaking a long database write activity in one instance of surge

You favorite in another instance of surge

that second instance will throw a locked error at you

the popup at least goes away now at head. but i'm not sure i know how to fix this edge case. I mean the database *is* locked.

I propose we change the error message to say something like its locked try again later.

**Comment by mkruselj** [comment]
Agreed with that error message!
