### ISSUE TITLE
Surge XT 1.0 - unclosed XML in skin.xml crashes Cubase (SIGSEGV)

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#5821]
Cubase 11
MacOS 11.6.2

You can repro this with the factory dark skin. 

factory-->dark-mode and open the skin.xml
edit any lines XML tag to not be closed
So this:
`<color id="lfo.waveform.background" value="bggray"/>`
becomes this
`<color id="lfo.waveform.background" value="bggray">`
Then reload the skin and Cubase crashes. 

Here is a partial crash dump

> Process:               Cubase 11 [11308]
Path:                  /Applications/Cubase 11.app/Contents/MacOS/Cubase 11
Identifier:            com.steinberg.cubase11
Version:               11.0.41.448 (11.0.41.448)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Cubase 11 [11308]
User ID:               501

Date/Time:             2022-01-24 10:10:50.852 -0600
OS Version:            macOS 11.6.2 (20G314)
Report Version:        12
Anonymous UUID:        95BE6ADA-F5D2-CF59-4EFC-F37ED40BB79E

Sleep/Wake UUID:       34CEFE45-D1FF-40A2-B3DD-EB1D7FA961B9

Time Awake Since Boot: 140000 seconds
Time Since Wake:       180 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000020
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [11308]

VM Regions Near 0x20:
--> 
    __TEXT                      10abbf000-10e1a9000    [ 53.9M] r-x/rwx SM=COW  /Applications/Cubase 11.app/Contents/MacOS/Cubase 11

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.surge-synth-team.surge-xt 	0x00000001714039df SurgeImage::scaleAdjustmentTransform() const + 31
1   org.surge-synth-team.surge-xt 	0x00000001714a3d50 SurgeImage::draw(juce::Graphics&, float, juce::AffineTransform const&) const + 48
2   org.surge-synth-team.surge-xt 	0x0000000171497960 Surge::Widgets::ModulatableSlider::paint(juce::Graphics&) + 2272
3   org.surge-synth-team.surge-xt 	0x00000001716e4b8e juce::Component::paintComponentAndChildren(juce::Graphics&) + 110
4   org.surge-synth-team.surge-xt 	0x00000001716e4e32 juce::Component::paintComponentAndChildren(juce::Graphics&) + 786
5   org.surge-synth-team.surge-xt 	0x00000001716e4e32 juce::Component::paintComponentAndChildren(juce::Graphics&) + 786
6   org.surge-synth-team.surge-xt 	0x00000001716e4c02 juce::Component::paintComponentAndChildren(juce::Graphics&) + 226
7   org.surge-synth-team.surge-xt 	0x00000001716e4e32 juce::Component::paintComponentAndChildren(juce::Graphics&) + 786
8   org.surge-synth-team.surge-xt 	0x0000000171796646 juce::ComponentPeer::handlePaint(juce::LowLevelGraphicsContext&) + 262
9   org.surge-synth-team.surge-xt 	0x00000001717e9b18 juce::NSViewComponentPeer::drawRect(CGContext*, CGRect, float) + 232
10  org.surge-synth-team.surge-xt 	0x00000001717e99c6 juce::NSViewComponentPeer::drawRect(CGRect) + 278
11  org.surge-synth-team.surge-xt 	0x00000001717e7a05 juce::JuceNSViewClass::drawRect(objc_object*, objc_selector*, CGRect) + 69
12  com.apple.AppKit              	0x00007fff232cb06b _NSViewDrawRect + 139
13  com.apple.AppKit              	0x00007fff239fcfcf -[NSView _recursive:displayRectIgnoringOpacity:inContext:stopAtLayerBackedViews:] + 2115
14  com.apple.AppKit              	0x00007fff232ca685 -[NSView(NSLayerKitGlue) _drawViewBackingLayer:inContext:drawingHandler:] + 967
15  com.apple.QuartzCore          	0x00007fff270e63fb CABackingStoreUpdate_ + 613
16  com.apple.QuartzCore          	0x00007fff2714d84d invocation function for block in CA::Layer::display_() + 53
17  com.apple.QuartzCore          	0x00007fff270e5787 -[CALayer _display] + 2247
18  com.apple.AppKit              	0x00007fff232ca1f5 -[_NSBackingLayer display] + 475
19  com.apple.AppKit              	0x00007fff232352e2 -[_NSViewBackingLayer display] + 555
20  com.apple.QuartzCore          	0x00007fff270e46f3 CA::Layer::display_if_needed(CA::Transaction*) + 863
21  com.apple.QuartzCore          	0x00007fff2722fbee CA::Context::commit_transaction(CA::Transaction*, double, double*) + 666
22  com.apple.QuartzCore          	0x00007fff270c5b6f CA::Transaction::commit() + 713
23  com.apple.AppKit              	0x00007fff232df46c __62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke + 285
24  com.apple.AppKit              	0x00007fff23a35112 ___NSRunLoopObserverCreateWithHandler_block_invoke + 41
25  com.apple.CoreFoundation      	0x00007fff20953731 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
26  com.apple.CoreFoundation      	0x00007fff209535c5 __CFRunLoopDoObservers + 543
27  com.apple.CoreFoundation      	0x00007fff20952a58 __CFRunLoopRun + 841
28  com.apple.CoreFoundation      	0x00007fff2095204c CFRunLoopRunSpecific + 563
29  com.apple.HIToolbox           	0x00007fff28b9aa83 RunCurrentEventLoopInMode + 292
30  com.apple.HIToolbox           	0x00007fff28b9a7e5 ReceiveNextEventCommon + 587
31  com.apple.HIToolbox           	0x00007fff28b9a583 _BlockUntilNextEventMatchingListInModeWithFilter + 70
32  com.apple.AppKit              	0x00007fff2315ad72 _DPSNextEvent + 864
33  com.apple.AppKit              	0x00007fff23159545 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1364
34  com.apple.AppKit              	0x00007fff2314b869 -[NSApplication run] + 586
35  com.steinberg.cubase11        	0x000000010cd339c8 0x10abbf000 + 35080648
36  com.steinberg.cubase11        	0x000000010cb4eb26 0x10abbf000 + 33094438
37  com.steinberg.cubase11        	0x000000010c6cb62a 0x10abbf000 + 28362282
38  com.steinberg.cubase11        	0x000000010c6cf11b 0x10abbf000 + 28377371
39  libdyld.dylib                 	0x00007fff20877f3d start + 1
<img width="1592" alt="Screen Shot 2022-01-24 at 10 15 53 AM" src="https://user-images.githubusercontent.com/11078351/150822376-2ba344b6-e9b0-4cac-a589-155939ba9045.png">

**Comment by baconpaul** [comment]
OK so when you *load* a corrupted skin from an uncorrupted state you get an error and it resets to classic

But if you swap to a skin and then corrupt it in place, it loads with no error checking. And then goes haywire. Crash maybe sure, depends on your skin but definitely not work.

**Comment by baconpaul** [comment]
anyway have a fix for the spurious path inbound
