### ISSUE TITLE
Move an FX being modulated by FORM.7 or FORM.8: crashes

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#5823]
**Bug Description:**
If an FX is being modulated by the 7th or 8th element of a Formula LFO, then moving that FX crashes Surge.

Version: Surge XT 1.1.nightly.d1f5980
Build: 2022-01-24 @ 22:46:16 on 'fv-az60-592/pipeline' with 'MSVC-19.29.30139.0' using JUCE 6.1.2
System: Windows 64-bit Standalone on Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Sample Rate: 44.1 kHz

**Reproduction Steps:**
1. Start with *Init sine*.
2. Switch any scene LFO to Formula type.
3. Select the 7th element from the LFO's hamburger menu.
4. Arm the LFO as a modulator.
5. In any FX slot, choose an FX (say DLY).
6. Move a slider in the FX (with the LFO armed).
7. Move the FX to another slot.
Surge crashes.

**Expected Behavior:**
The FX moves

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Additional Information:**
Attached: a patch state before after step 7, in .zip.
[2022-01-24 precondition.zip](https://github.com/surge-synthesizer/surge/files/7929617/2022-01-24.precondition.zip)

**Comment by baconpaul** [comment]
confirmed the crash

**Comment by baconpaul** [comment]
the scene and index are getting confused during the move event for vector indices.

**Comment by baconpaul** [comment]
yeah i see it. there's a 2 char fix but i want to fix the underlying problem (i used an anonymous tuple not a named struct)
but swap the 2 and 1 at line 2523 of surge synth and this gets fixed

**Comment by baconpaul** [comment]
Anyway PR with a fix in. Excellent bug report as always, thanks @j5v
