### ISSUE TITLE
Feb 7 2019 report of VST2,AU not loading properly on macOS

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#583]
Got this from Andy Buchanan via Facebook:

Results shortly
**OS X 11.13.6, 3.4GHz i5, 24GB DDR3**, **Surge Build Feb 7 2019 16:14:34**

Ableton 9.7.7
AU     Failed to load
VST2 Ok

Ableton 10.0.4
AU     Ok
VST2 Failed to load

Ableton 10.1b12
AU     Failed to load
VST2 Ok
VST3 Failed to load

Reaper 5.965
AU      Ok
VST2  Missing in Action
VST3  Failed to load

Reason 10.2.2d1
VST2      Ok

Logic Pro 10.4.4
AU    Ok

Fl Studio 20.0 [build 14]
AU      Failed 2 load
VST2  Failed 2 load
VST3  OK

Waveform 9.3.2
AU      Failed to load
VST2  Failed to load
VST3  Ok

After reboot here is Surge clicking as AU in Ableton 10.0.4
After this `(surge?)` is removed it and re-added, and the clicking stops

Ran all the other DAW/plugin combos. No further clicking, but every combo giving a different result this time. Except for Logic & Reason which were both still fine with their one supported plugin variety.

question: "does the plugin dump error logs anywhere?"

If you'd like to run any logging builds and send back log files etc, I'm happy to help. I'd offer to run actual code in a debugger, but I recently removed XCode and all my dev stuff from my Mac due to a free-space emergency.

**Comment by baconpaul** [comment]
As I mentioned in #658 with reaper:

> OK so this close to a bug in REAPER. I downloaded latest reaper mac demo and found: If both a VST and VST3 have the same component name (Surge.vst and Surge.vst3) it only scans the VST3
> 
> If I move ~/Library/Audio/Plug-Inst/VST/Surge.vst to Surge2.vst then reaper loads it no problem and the about screen shows I"m running vst2. But then bitwig shows the name "Surge2".
>
> So clearly this is a mis-behavior in REAPER. It shouldn't think Surge.vst and Surge.vst3 are the same thing to the point over overwriting. But I'm not sure what we should do.
