### ISSUE TITLE
Do you recommend to replace Surge with Surge XT?

### ISSUE THREAD

**Issue by yurivict** [surge-synthesizer/surge#5836]
I maintain the FreeBSD port for Surge.

Now Surge XT is out. Should the Surge port be renamed into Surge XT, or they should exist in parallel?

**Comment by baconpaul** [comment]
We recommend they exist in parallel, and set up homebrew and our binary installers that way

**Comment by mkruselj** [comment]
They are installed in parallel and have different plugin IDs. Old Surge 1.9 branch won't be updated anymore.

**Comment by yurivict** [comment]
But if Surge XT is a complete replacement, why keep Surge 1,9 ?

**Comment by K0rrid0r** [comment]
sometimes its nice to keep track how changes were made, and old projects was maybe done with older version of surge

^^
![image](https://user-images.githubusercontent.com/56724286/151669719-0b39fe46-de4a-4819-9f30-d4295dc5f640.png)

**Comment by baconpaul** [comment]
Yeah exactly surge is a renderer for projects in daws. Almost everyone (including me) keeps the old and new version around so they can render and edit older projects

**Comment by baconpaul** [comment]
(And surge 16-19 were drop in compatible in daws but xt is not for a variety of reasons, hence the separate I’d and so on)

**Comment by baconpaul** [comment]
Oh just fyi @yurivict we plan a 1.0.1 release in next 48 hours to fix some bugs found after release if that adjusts your packaging plans

**Comment by yurivict** [comment]
> [...] we plan a 1.0.1 release in next 48 hours to fix some bugs found after release if that adjusts your packaging plans

Thanks for the heads up. I'll package it then.
