### ISSUE TITLE
Different types of NOISE

### ISSUE THREAD

**Issue by hems** [surge-synthesizer/surge#5839]
**Is your feature request related to a problem? Please describe.**
Being able to select different kinds of noise or even use your own samples for NOISE would be really powerful.

Also being able to have noise to TRACK pitch would be great.

I guess the only way now is using the WAVETABLE oscillator and loading some noise into it?

One idea could be to have an extra "N" oscillator on the oscillator window where you could setup all sorts of extra options for noise.

![image](https://user-images.githubusercontent.com/27327/151651577-fac232c4-a950-47cf-9481-5e0f3fe95ccd.png)

Serum has a great implementation for it... Can be useful as reference:

![image](https://user-images.githubusercontent.com/27327/151651598-9dd87dc5-3910-493f-9b25-b6d2083069e5.png)

**Comment by mkruselj** [comment]
You can use S&H Noise oscillator to have noise that tracks pitch. Twist oscillator also uses noise in certain modes to produce various interesting sounds.

And yeah technically you could use WT oscillator for this. So what we're gonna do is in XT 2.0 we increase the number of oscillators per scene to 6. And there is probably gonna be chaos oscillators for various noisy types of sounds. So I would consider this FR covered by #3433 and #1080.

**Comment by baconpaul** [comment]
Just to hop in and say the alias noise is also a very interesting tonal noise.

but i agree twist + S&H + those two issues

You did make me think that when we add the noise cluster oscillator having a 'bandpasses feedback white noise' mode would be very musical though. Now the issues are linked we can remember that too!

Thanks for all the suggestions this morning.
