### ISSUE TITLE
When switching between MSEGs with Movement Mode Shift Selected, the mode changes to Draw.

### ISSUE THREAD

**Issue by ztnl** [surge-synthesizer/surge#5841]
Version: Surge XT 1.0.nightly.0874a1c
Build: 2022-01-28 @ 01:07:22 on 'WIN-G8OUDR116IA/pipeline' with 'MSVC-19.29.30139.0' using JUCE 6.1.2
System: Windows 64-bit VST3 on        Intel(R) Core(TM) i7
Host: Reaper @ 48.0 kHz

When switching between MSEGs with Movement Mode Shift Selected, the mode changes to Draw.

To reproduce:

1. Load MSEGs into modulation slots 1-3 for Scenes A and B.

2. Select Movement Mode Shift for each.

3. Notice that when switching between the other MSEGs, Movement Mode switches to Draw in both tear-in/out states.

Expected behavior is that the selected Movement Mode of Shift should persist upon switching to the other MSEGs.

**Comment by mkruselj** [comment]
@baconpaul This is a regression in behavior from 1.9. Maybe a nice 1.0.1 fix?

**Comment by baconpaul** [comment]
Oh that is me mis handling state probably. My guess is it’s too small a bug and too big a fix to sweep into the point but I will peek

**Comment by baconpaul** [comment]
Ahh yes i see it and the change is small. Can definitely put in 101
