### ISSUE TITLE
Support for changing modbutton font to custom font

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#5843]
You can change the font on sliders by utilizing font_family and then assigning a custom font. 

I would like to be able to do that for the modbutton. 

Right now it is here :
https://cdn.discordapp.com/attachments/758804883180355594/937123683409985566/Screen_Shot_2022-01-29_at_5.14.49_PM.png
https://cdn.discordapp.com/attachments/758804883180355594/937123683166728192/Screen_Shot_2022-01-29_at_5.14.22_PM.png

Also it might be relevant to consider the changes that will be taken over here:
https://github.com/surge-synthesizer/surge/issues/5027

And finally, perhaps it really boils down to wanting to be able to use a custom font everywhere fonts are used. AKA if I dont want to have Lato in the GUI I can not have Lato in the GUI. 

Regardless, thank you for your consideration.

**Comment by mkruselj** [comment]
Linking to #5027.

**Comment by baconpaul** [comment]
yeah we didn't get all the fonts for 10 but we can for 11. thanks @itsmedavep !

**Comment by itsmedavep** [comment]
Per a discord convo Paul had asked me to add another issue to this one (if I understood him correctly!). 

FR: I would like to be able to change the stroke color on the macro slider box. 

<img width="129" alt="Screen Shot 2022-02-03 at 7 01 00 PM" src="https://user-images.githubusercontent.com/11078351/152465505-bb49ab50-6713-4fcc-a6b1-6aed8a8c4387.png">


 Seems like these are the only options available (when I look at the skin guide nothing jumps out):

`<color id="modbutton.macro.slider.fill" value="blue"/>
  <color id="modbutton.macro.slider.background" value="base01"/>
  <color id="modbutton.macro.slider.currentvalue" value="orange"/>`

Unfortunately those dont hit the stroke around the slider box.

**Comment by mkruselj** [comment]
Currently that stroke is using `modbutton.used.fill` color. Not ideal, and yes a new color is certainly very easy to add!

**Comment by baconpaul** [comment]
OK @itsmedavep we are working towards a global font list like we have a global color list. We aren't there yet but to test it, i made it work for the modbuttons

Once I merge #6018 you can look at example 10 which will let you change mod button fonts

If there are other fonts which need styling similarly, this is now actually 'very easy' (in fact we may sweep across everything for XT 1.1 and give proper font names now we can override at a skin level). Just lemme know where you get stuck if/when you return to this.
