### ISSUE TITLE
Digital EG pattern

### ISSUE THREAD

**Issue by XtremeSounds** [surge-synthesizer/surge#5847]
vst3 for 64 bit windows. This looks strange.  

![Capture](https://user-images.githubusercontent.com/91672260/151794093-58b444e7-c579-40a5-a1db-93d6a92177c0.JPG)

**Comment by mkruselj** [comment]
This is not a skin that we deploy with Surge, it's a skin done by a 3rd party, so it needs to be fixed by the 3rd party which did the skin.

**Comment by XtremeSounds** [comment]
ok thanks

**Comment by mkruselj** [comment]
Yeah, looks like you might've had an older, work-in-progress version of that skin.
