### ISSUE TITLE
Tune button unexpectedly toggles when dragging tab-group selectors

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#5852]
**Bug Description:**

**Surge XT Version**
Version: Surge XT 1.1.nightly.eb7be88
Build: 2022-01-31 @ 20:22:31 on 'WIN-TH67P0TFHGU/pipeline' with 'MSVC-19.29.30139.0' using JUCE 6.1.2
System: Windows 64-bit Standalone on Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Sample Rate: 44.1 kHz

**Reproduction Steps:**
Steps to reproduce the behavior - cases:
1. Click and hold the OSC **1** select button, and then drag the mouse.
The accessibility focus (blue) highlights the OSC **3** selector, and **Tune** toggles on and off.

2. If you click and hold the Filter 1 (or Filter 2) icon for filter type, and drag up and down to change filter type, then in addition to the expected functionality, **Tune** toggles on and off.

**Expected Behavior:**
Tune should not toggle with these UI actions.

**Additional Information:**
.

**Comment by mkruselj** [comment]
Probably a duplicate or closely related to #5801.

**Comment by j5v** [comment]
The appearance of the blue label is - I remember discussing that in Discord, for pre-XT1.0, just after the main accessibility/keyboard changes. The Tune button being highlighted is (guess) probably group/component IDs.

**Comment by mkruselj** [comment]
This seems fixed now, as a consequence of fixing #5801.
