### ISSUE TITLE
More macros

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#5858]
**Is your feature request related to a problem? Please describe!**
I run out of macros, particularly with 'physical model' instruments.

**Describe the solution you'd like:**
Another row of macros.

**Describe alternatives you've considered:**
It's possible to assign a MIDI CC to other places and use those as modulators, but I think that's hacky and not transparent to users of the patch.

**Additional context:**
I think for the Surge engine, and MIDI CC allocation, extra macros are not a problem. This is really a UI design problem (which I overthink  below).

The first solution we often think of is to permanently adjust the available height of Surge window, but understandably there are reasons we don't default to this for all the 'moar things' requests.

Instead, we could adopt 'gradual disclosure', where there's a '+' button to the right on Macro 8, which inserts another row of macros into the UI. Ideally this would increase the height of the window, or reduce the scaled width, which might create its own UI problems when it changes users expectations of UI positioning. 

Gradual disclosure could be applied to LFOs, SLFOs (yes, moar LFOs!), or filters as design pattern for >XT1.x.

Blocker: It would impact skin design patterns, particularly skins with 'hard wired' zoning in their backgrounds.

**Comment by mkruselj** [comment]
I would rather keep it at 8 tbh. It throws a massive wrench into the redesign for XT2, which already has increased height. Adding more height is not an option, and gradual discosure option sucks UX wise IMO.

**Comment by j5v** [comment]
Fair.

Practically, users with hardware controllers are unlikely to use more than 8. More than 8 is in the domain of DAW automation and patch configuration (rather than CC during performance). 

If I run out of macros, it's usually a sign that I'm trying to cover too much ground with a patch, and it's better to create a specialized patch that covers the intended new controls. There's then usually more freedom in the sweet spot. That removes some variables that would demand macros.

With XT-future having more scenes, oscillators, etc, there might be more demand to have more of it controllable, but that's 'future' :)

**Comment by j5v** [comment]
Happy to close, if you want.

**Comment by mkruselj** [comment]
We could leave it open for posterity, but it's really a can of worms IMO.

**Comment by mkruselj** [comment]
Nah, let's close it. 🙂
