### ISSUE TITLE
Opt-In LFO multi out

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#5859]
For the LFO other than formula (and maybe envelope), we should be able to opt into having 1 or 3 outputs. 1 output is as is now. 3 outputs would be output 1 is what we have now, 2 is env only, and 3 is lfo only absent env

so 1 = 2 * 3 basically

we have these separated in the code anyway

**Comment by mkruselj** [comment]
I'm not sure why this should be opt-in. So we show the extra hamburgers only if a certain option is enabled? And then what with the patches that use those other LFO vectors but you have the option disabled? Then you can't access those parts of the patch... Not cool really.

It's either all in or nothing with this one.

**Comment by baconpaul** [comment]
Why? We show the hamburger if you opt in and don’t if you don’t. And store your choice per modulator. So I’m imagining a patch with 3 LFOs but only one is hamburgered.

if you opt in per session you are right but that wouldn’t work so it’s not what I meant :)

**Comment by baconpaul** [comment]
Specifically I’m imagining he mod button RMB has an enable extra outputs menu item which turns them on for thst modulstor and updates a state on the modulstor which is streamed in the patch.

**Comment by mkruselj** [comment]
This just seems contrary to the general UX of Surge, which is show as many things as possible right there in the front panel. Otherwise you could make the same case that hamburger should also be opt in for formula...

**Comment by baconpaul** [comment]
Yeah I actually thought about requiring a subscription to multi out to activate the hamburger 

but I’m also fine to just burger all the lfos
