### ISSUE TITLE
Zoom state vs View state on open / close

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#586]
Reported by @sense-amr 
vst2 bitwig

* Open bitwig
* Add an instrument and pick surge
* open the editor
* shrink by 25%
* close the editor
* open the editor - it appears to be 100%
* shrink by 25% it probably goes to 50% view
* close the editor
* open the editor - it appears to be 100%
* shrink by 25% and you get the "no teensy surge for you warning" even though it looks like 100%
* and then it goes to 50%

What is happening is when you open the editor the display is ignoring the in memory zoom value. So re-open is displaying at 100% but "shrink by 25%" is reading the prior zoom value.

Another perverse version of the bug is

* add a surge
* zoom to 200%
* close surge
* open surge and see 100%
* shrink by 10% and it gets bigger (goes to 190)

The fix is in the ::open to make sure you setZoom properly. Just find the right codepath.

**Comment by baconpaul** [comment]
A simple fix (setZoomFactor of getZoomFactor in ::open) doesn’t work since the window isn’t shown yet and so the panel is blown up larger but the window frame isn't. Same reason that I can't set initial zoom to something other than 100. So related to implementing #456 properly also.

Probably need to find some frame onOpen handler thingy or something in CFrame land.

**Comment by baconpaul** [comment]
Yup same problem as #456. This obvious change doesn't resize the window at the right time.

```
--- a/src/common/gui/SurgeGUIEditor.cpp
+++ b/src/common/gui/SurgeGUIEditor.cpp
@@ -1266,6 +1266,11 @@ bool PLUGIN_API SurgeGUIEditor::open(void* parent, const PlatformType& platformT
    frame->registerKeyboardHook(this);
    openOrRecreateEditor();
 
+   setZoomFactor( getZoomFactor() );
+   // Now it's too early for the vstgui to work so
+   frame->setSize( WINDOW_SIZE_X * getZoomFactor() / 100.0,
+                   WINDOW_SIZE_Y * getZoomFactor() / 100.0 );
+   
    return true;
 }
```

so we need to be 'later' to resize it in vst2 land.

**Comment by baconpaul** [comment]
OK i have figured out a way to do the zoom call at the right time with one minor side effect. I've only tested it mac vst2 and it is late but I will walk it through the tests this week and see if I can get this fixed.

**Comment by baconpaul** [comment]
branch `baconpaul/zoomstate-586` has my WIP just in case I forget.

**Comment by geoslake** [comment]
So I know nothing guys, but couldn't the size of the gui be defined in the configuration.xml, as i guess, most people wont play with the size, just set it once for all to suit their preferences and screen size/resolution, so does it even need to be handled by some kind of vst state saving or something ? I would like to just select the size and then "save as default size" and be done...

**Comment by esaruoho** [comment]
@geoslake there's a separate ticket for user-preferences, and eventually surge will have it - and then we'll have a "default zoom setting" which could be 125% or something by default. :)

**Comment by baconpaul** [comment]
OK so here's what I really want to do. I want to add a parameter to the synth called "zoom" which is not streamed to patches but is streamed to hosts so hosts remember it. 

The thing that scares me about this is if I add the patch in the middle, patch indexing will be broken. Also a parameter which doesn't render as a slider is hard. So I'm going to ponder this one for a bit more. May be dicey.
