### ISSUE TITLE
Velocity modulation LFO Amplitude

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#5872]
Discord user musicalman reports

> Hmm. I think I found a bug? But not sure. So let's say I assign an lfo to modulate something. All is well. But I want to adjust the lfo amplitude with velocity. When I do that, there's a weird problem: it seems the modulation targets start at the bassline lfo amplitude before reaching bassline+velocity. With Surge's smoothing, it creates an annoying effect like you increased the attack time of something. I hope I'm making some sort of sense lol. If it helps I'll try to make a patch and send it

evil and i banter with them and I say

> I bet the lfo attacks before the velocity applies - it’s a modulation order in attack tbing - so you get a smoothed amplitude sweep

Here's their FXP file

[t.zip](https://github.com/surge-synthesizer/surge/files/8020309/t.zip)

**Comment by musicalman** [comment]
After more banter on the Discord I did some testing.
Modulators which don't rely on a note-on seem okay. These include: Channel AT, Pitch Bend, Mod Wheel, Expression, Breath and Sustain.
Other modulators such as Key Track and Poly AT exhibit the bug. Lowest/Highest/Latest Key are also affected.

During the Discord conversation, Baconpaul wrote a succinct explanation of the cause. It looked helpful so I'll repost it:
"i bet it is the midi modulators being copied to local state after the lfo attach in surge voice
the thing is if thats true you really need a topological sort. but we can use a heuristic that midi comes before lfo attack to get close enough"
