### ISSUE TITLE
Channel crosstalk of polyphonic aftertouch

### ISSUE THREAD

**Issue by cgibbard** [surge-synthesizer/surge#5879]
**Bug Description:**
All polyphonic aftertouch events having a given note number will apply to a note played with that note number, regardless of whether they're on the same channel or not. This is particularly noticeable when using channels to indicate an octave shift, since octaves of the same note will overwrite each other's Poly AT targets.

**Surge XT Version**
Surge XT 1.0.0.1edd725

* Version:
* Plugin Type: LV2
* Bitness: 64-bit

**Reproduction Steps:**
1. Make sure Poly AT has something reasonably audible as a target.
2. Hit two keys that are mapped to the same MIDI note number but different channels (on a synth that supports polyphonic aftertouch), and push on them with varying pressure. Alternately, load the attached Ardour project, or use the MIDI file "MIDI 1-3.mid" from the interchange directory inside it.
3. There will be some "crunchiness" whenever the polyphonic aftertouch numbers disagree with one another.

**Expected Behavior:**
Polyphonic aftertouch events should only apply to the channel (as well as note) they're marked for.

**Computer Information (please complete the following!):**
 - OS: Linux
 - Host: Ardour (or Standalone)

**Additional Information:**
[Poly AT Octave Test.zip](https://github.com/surge-synthesizer/surge/files/8053997/Poly.AT.Octave.Test.zip)

**Comment by baconpaul** [comment]
Ha yeah well it just ignores channel altogether

```
void SurgeSynthesizer::polyAftertouch(char channel, int key, int value)
{
    float fval = (float)value / 127.f;
    storage.poly_aftertouch[0][key & 127] = fval;
    storage.poly_aftertouch[1][key & 127] = fval;
}
```

Since each note has a channel we can just add another [16] to that data structure and it should "just work" (famous last words) if we read it with channel in SurgeVoice.

**Comment by cgibbard** [comment]
Did that, and it seems to work. :)
