### ISSUE TITLE
Merge bmp00188 into bmp00186

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5882]
It would be nicer and cleaner from skin dev perspective to have all favorites related thingies in one asset. So, the icon that shows in the patch browser menu should be the 5th frame in bmp00186, as attached.

![bmp00186](https://user-images.githubusercontent.com/2393720/153726636-868c23f4-3009-4968-8c06-994f31affe17.svg)

**Comment by baconpaul** [comment]
If we *don't* do this does anything bad happen? The sizes are different and its less code to just close this as 'don't do' until we rework the assets in XT2.

**Comment by mkruselj** [comment]
I wouldn't then close this issue but just change the milestone to 2.0. 🙂

**Comment by baconpaul** [comment]
Yeah right. Whatever assets end up being in 2.0 have these consolidated. Agree with that.

**Comment by mkruselj** [comment]
This one probably won't apply to XT2.0 in the end, considering the way we do skins will massively change and rely way less on lots of SVGs.
