### ISSUE TITLE
Plugin doesn't remember scale

### ISSUE THREAD

**Issue by DarceyLloyd** [surge-synthesizer/surge#5892]
**Bug Description:**
I set to 120%, re-open project and plugin is back at 150%, please add stored variable to config or something so on load/init it can be set to the size it once was.

**Surge XT Version**
XT 1.0.1.60228e8

* Version:
VST3
x64

**Reproduction Steps:**
Open, change setting, close daw, re-open.

**Expected Behavior:**
Remember selected scale for all future opening of VST (add to common settings file for XT versions)

**Computer Information (please complete the following!):**
 - Win 10
 - Bitwig 4.?.? (latest)

**Comment by baconpaul** [comment]
If you go to the zoom menu there is a “set default scale” which is remembered in an ini file.

**Comment by DarceyLloyd** [comment]
Ah the manual way, didn't see that, would be good to automate this however ;)

**Comment by baconpaul** [comment]
We decided not to since we didn’t want a transient grow or shrink to write to the ini.
