### ISSUE TITLE
OSC Volume, Balance, Mute & Solo section

### ISSUE THREAD

**Issue by DarceyLloyd** [surge-synthesizer/surge#5893]
3 rectangles for 1,2, 3, 1x2, 2x3 and N.

Would be nice to be able to put an LFO/S-LFO on these.

**Comment by baconpaul** [comment]
You can modulate the levels! Just modulate the sliders the normal way. Integer modulation is tricky and we want to handle the routing another way covered elsewhere.

**Comment by mkruselj** [comment]
7ndeed, just modulate the levels.
