### ISSUE TITLE
Show favourites on preset browser

### ISSUE THREAD

**Issue by DarceyLloyd** [surge-synthesizer/surge#5895]
Show favourites on preset browser

**Comment by baconpaul** [comment]
If you have anything favorited it should add as a category right under user presets in the second column. Does it not?

**Comment by mkruselj** [comment]
Yes and you also did a commit that shows a heart next to preset name in actual preset browser menus. Closing as implemented.

**Comment by DarceyLloyd** [comment]
Well, I was thinking something a bit more...
![Surge-XT-Preset-Browser](https://user-images.githubusercontent.com/932191/154848093-654dae32-345a-42d8-b682-7d86383d5144.png)
.
