### ISSUE TITLE
Enhanced Preset Browser (concept top bar and browser design attached)

### ISSUE THREAD

**Issue by DarceyLloyd** [surge-synthesizer/surge#5896]
Enhanced Preset Browser (concept top bar and browser design attached)

Top Bar

![Surge-XT-Top-Bar](https://user-images.githubusercontent.com/932191/154848196-ac368b96-c53e-434b-9d2f-f59d9d9832e0.png)

Enhanced preset browser (needs more buttons but I'm not spending all day doing UX work)

![Surge-XT-Preset-Browser](https://user-images.githubusercontent.com/932191/154848199-7bc4d181-7079-4ef5-b7fc-512fc17f8abc.png)

**Comment by baconpaul** [comment]
So this is basically a dup of the discussion in https://github.com/surge-synthesizer/surge/issues/2359

those features didn’t make xt1 but a lot of the code is in place. Are you a c++ dev? If so would love help!

**Comment by DarceyLloyd** [comment]
Sorry not versed with all the discussions...

RE: Am I a C++ Dev
I know a bit of C++ but not that clued up on it enough for VST development probably, I'm a Full stack Web Dev, but I specialise in application UX and WebGL.

**Comment by baconpaul** [comment]
No worries about not being versed! 

The patch browser data structures are basicalky all there but we ran out of time on the ui dev and actions. A juce dev who wanted to work on that would be super welcome

**Comment by DarceyLloyd** [comment]
I've actually been looking at JUICE docs in my spare time, however there's very little of that the last 6 months. I checked out scripting for kontakt and was not impressed by that, would rather work in perl all day and using nothing but regular expressions lol. Then I dug into falcon scripting a bit, but its very poorly documented and the examples / demo projects are not that useful either and so I ended up on JUICE. I was .NET (c#) for 6 years but moved on to php and node (soon deno) etc.

I will have a wander around the source code, see if I can make any sense of it... But I suspect will take a while for me to get up to speed with both JUICE, C++ not so much I doubt there will be much to surprise me there but using it correctly and optimally that's a different story.

**Comment by mkruselj** [comment]
Yeah for XT 2.0 we do plan on a basically complete overhaul of the whole GUI. And indeed my hopes for the full fledged patch browser would be heavily inspired by u-he's patch browser. They did pretty much everything right.

**Comment by DarceyLloyd** [comment]
Very true, u-he's preset browser is pretty much spot on, but as long as you emulate windows file explorer (maybe not the looks) your pretty much there. OSX file browser would probably take a lot of pc users by surprise. Then just add a star or rating and what more could you ask for really. u-he did get the mouse wheel scroll the wrong way round though, glad they included the setting to invert the mouse scroll and the option to prevent a re-scan on every start up.

You've done hell of a better job with XT than native instruments did with massive x's preset browser, how can you have that kind of resource available and mess that up? Baffles me... Then again, we've all used knontakt, GUI for that was probably done when windows 3.1 was released... Even massive has issues, try adding more than 1000 presets to that, you can pretty much forget about using it, it just locks up or takes a good long cup of tea to change from preset to preset and I can't see any reason why their db should have any issues, but there are a lot of redundant columns in there and fav's are sym links (1 way to solve a copy your fav's from 1 machine to another).

Quantity wise I've been surprised with serum and it's sqlite db, it can take a long time to scan and their programming to clean up the db on a re-scan is a bit messed up as it will grow forever with redundant data being left in it but during one of my initial builds running my preset auto clean up and organise utility, it mistakenly didn't delete any but duplicated each one 5 to 10 times appending a number to it. I didn't realise this and started it up. Very very long scan time (exponentially slows down after a while), something like 120,000 presets but it had no lag in selection, scroll was still smooth, a bit slower to open but not bad, impressive for sqlite.

But I am curious with the JUICE framework, will see if I get some time next weekend to compile, run and modify some of the examples. But I'm in a contract at the moment and the pace is not slow and the days can be very long...

**Comment by mkruselj** [comment]
I actually work for NI (Kontakt instruments team) and I know the whole Massive X backstory... it is really, really, really complicated, you wouldn't believe. That said, they _are_ working on a much much better browser for it, so not all is lost. At any rate that's a bit offtopic 😅 

sqlite is pretty spiffy! And it's pretty much everywhere. u-he use it too.

**Comment by DarceyLloyd** [comment]
Yeah I think we spoke about that on KVR with my corrupt NI downloads last year? You told me about the hidden folder native access creates when it starts and I wrote a monitoring program to rip the download links so I could get an intact download (after pressing start and then stop). Thanks for that BTW, still using it for anything that comes my way with native access :)

RE: SQLite
Yeah you can't really go wrong with that little db, free and does a pretty good job. I've been wandering around a lot of them in the VST world. Oddly I don't get to use it much in the day job, more maria, mysql, sqlserver or mongo.
