### ISSUE TITLE
User data folder not showing in the patch browser

### ISSUE THREAD

**Issue by fractalf** [surge-synthesizer/surge#5897]
**Bug Description:**

I upgraded from Surge 1.9 to Surge XT (1.0.1)

Now after I have set the User data folder, no presets are shown :(

![image](https://user-images.githubusercontent.com/5707457/154856250-4088f6b8-c71d-42ec-ae4e-bb3b2e639522.png)

**Comment by baconpaul** [comment]
Xt uses a different directory. Copy your user presets from the old documents/Surge to the new documents/Surge xt/patches directory, and if using 10 or 101 make a sub dir in patches just like you did in the old surge dir

**Comment by fractalf** [comment]
@baconpaul Nah, that's not it, I'm not using the defaults. You see I use a *custom" user data folder, and Surge doesn't like that

![image](https://user-images.githubusercontent.com/5707457/154866716-37ad57ae-77bc-4c33-b56a-1d334eeae0bd.png)

**Comment by baconpaul** [comment]
That’s fine. But your patches will still be searched for in patches not the root 

we changed the scan logic in xt to use a directory structure by type

**Comment by baconpaul** [comment]
If you save one patch in xt where is it? That’s where your user patches need to be basicalky. That should be (your dir)/patches/category/name.fxp

**Comment by fractalf** [comment]
I'm not sure what you're actually saying here...
Are you saying that this feature of using a custom user preset folder is no longer working, and that is how it should be?

When resetting everything and saving a patch, ofc it will be saved to the default folder `./Documents/Surge XT/Patches`,
but my whole point here is that the custom user folder is not working...

Anyway, I replaced the default patch folder with a symlink to where I want my presets, and I can live with this.

Just thought I'd mention that this here is probably a bug

**Comment by baconpaul** [comment]
No I’m saying if you have a custom folder “x” 19 looks for folders in “x/category” and xt in “x/patches/category”

but I’ll reopen to test that again to make sure it does that

it does mean though if you share a folder between 19 and xt it won’t work as mentioned in the release notes

**Comment by fractalf** [comment]
ah, ok I get what you are saying now. I added `Patches` to my custom folder and added all my presets there and then it's working.

I will probably just use a sym-link anyway, cause then I dont have to mess up my preset-folder structure (which resides on another HD partition etc)

Thank you, I'm closing again as this is not a bug

**Comment by baconpaul** [comment]
Great! Thanks
