### ISSUE TITLE
Zoom to biggest

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#590]
@esaruoho made a comment on slack like “I zoom to 150 then jog up by 10s to the biggest I can get”. 

We have the function to find the biggest. Maybe just bind it to a menu item “zoom to biggest” which does that in one step

**Comment by esaruoho** [comment]
would be greatest

**Comment by baconpaul** [comment]
Super easy. I’ll knock it out next time
I have some dev minutes
