### ISSUE TITLE
Patch change during play

### ISSUE THREAD

**Issue by Gypsy2GS** [surge-synthesizer/surge#5905]
Using win11, Cakewalk, Surge 1.9.0.91069f8 64bit
I want to change a patch on the fly, during playback)  I can do this via Cakewalk Event List. The problem is that I cannot see any way to  identify patch numbers in Surge.  Is there any way of identifying Surge patch numbers?

**Comment by baconpaul** [comment]
unfortunately we don't currently support daw-initiated patch changes.

**Comment by mkruselj** [comment]
Duplicate of #576.
