### ISSUE TITLE
Tuning Editor, Save Scale, Save As Type: SCL

### ISSUE THREAD

**Issue by ztnl** [surge-synthesizer/surge#5907]
Version: Surge XT 1.1.nightly.455ecc4
Build: 2022-02-23 @ 18:25:23 on 'fv-az423-76/pipeline' with 'MSVC-19.29.30139.0' using JUCE 6.1.2
System: Windows 64-bit VST3 on        Intel(R) Core(TM) i7
Host: Reaper @ 48.0 kHz

Add SCL extension to Save As Type from Surge XT Tuning Editor/Actions/Save Scale

**Comment by baconpaul** [comment]
as discussed on discord
pretty sure this is just making the file chooser add two args juce::File(), "*.scl" but that does nothing on mac so need to boot win to try
note that no matter what you type we give you an scl extension 

10 minutes work when i next have windows running tho
