### ISSUE TITLE
dead links 

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#591]
https://surge-synthesizer.github.io/

At the bottom of the page ->

In the section Downloads
Latest builds:

USE CAUTION, LATEST BUILDS MAY BE VOLATILE. 

- THE MANAGEMENT

The following links ->
Download latest macOS 64-bit Build -> produces 404 error 
Download latest Windows 64-bit Build -> produces 404 error 
Download latest Windows 32-bit Build -> produces 404 error

**Comment by baconpaul** [comment]
Oh yeah @kzantow and @esaruoho werent you fixing this up the other day? It needs the same include as the top right?

**Comment by esaruoho** [comment]
fixed, closing
