### ISSUE TITLE
Remappable keybinds

### ISSUE THREAD

**Issue by ironcross32** [surge-synthesizer/surge#5912]
**Is your feature request related to a problem? Please describe!**
A clear and concise description of what the problem is. e.g. I'm always frustrated when [...]
Related to accessibility for the blind and visually impaired, the current shortcuts for moving between patch categories are very close to two NVDA shortcuts that allow us to jump through Surge's window quicker than using tab and shift+tab. I therefore propose that keybinds that Surge accepts be made re-mappable to other keys. Where this leads to frustration currently is that patches in progress can be lost due to an accidental situation where the capslock or insert key isn't being held fully for NVDA to capture it as an NVDA keystroke.
**Describe the solution you'd like:**
The ability to define mappings for hotkeys that Surge uses. Ultimately, somehow in the UI would be preferable, but adding them to a configuration file would also be acceptable.
**Describe alternatives you've considered:**
Switching NVDA to desktop input mode, but not every keyboard has a numpad, such as the one I use every day.
**Additional context:**
Everything was described in the fields above.

**Comment by baconpaul** [comment]
You know I wanted this also for turning off ctrl s in the plugin in logic (and that’s not even screen reader usage! Just the key binding is an annoying conflict). 

I think this is a good request and I have a couple of ways I can see to do it. Let me add it to the 1.1 milestone

**Comment by baconpaul** [comment]
I'm tackling this one next.

**Comment by baconpaul** [comment]
For some reason when I run the key bind manager in my mac in logic it comes up blank. So need to debug that too. Just a reminder.

**Comment by mkruselj** [comment]
Bugs after #6087:

- [ ] Ctrl doesn't work in learn mode
- [ ] Chorded modifiers don't work at all in learn mode

**Comment by baconpaul** [comment]
Oh darn the ctrl cmd windows thing again! Thanks

**Comment by mkruselj** [comment]
I think we're good on this one now. Design of the overlay can likely be improved, but for MVP this is perfectly sufficient, so imma close this issue!

**Comment by baconpaul** [comment]
Great!
