### ISSUE TITLE
Not recognised on Ableton 11

### ISSUE THREAD

**Issue by ulshv** [surge-synthesizer/surge#5914]
Searching for `surge` after installation and restart has no results in Ableton 11.
Ableton 11.1, MacBook M1, Monterey.

**Comment by baconpaul** [comment]
Did you rescan plugins? And just to be sure is it in library audio plugins in the standard spot? Is the standalone in applications and does thst run? And which version did you try to install?

**Comment by ulshv** [comment]
Right, the plugin folder was not configured in Ableton by default (I'm new to it).
After going to `Preferences` -> `Plug-Ins` and selecting `Use VST3 Plug-In System Folders` to `On` and doing `Rescan` I can now see the Surge XT in Plug-Ins section. Thanks for pointing me out!

**Comment by baconpaul** [comment]
Cool! Glad you got it working and enjoy making music with surge!

**Comment by mkruselj** [comment]
Bugs after #6087:

- [ ] Ctrl doesn't work in learn mode
- [ ] Chorded modifiers don't work at all in learn mode
