### ISSUE TITLE
Notch filters broken by regression in filter modularization refactoring

### ISSUE THREAD

**Issue by selenologist** [surge-synthesizer/surge#5928]
**Bug Description:**
12dB and 24dB Notch filters now explode if the cutoff is raised beyond a certain point. This does not happen in 1.9 and appears to have been recently introduced following the rework.

The other filters appear to remain stable, however, the existence of problems with notch suggests possible unintended changes to tuning that may affect other filters.

**Surge XT Version**
Version: Surge XT 1.1.main.ee01d41f
Build: 2022-03-03 @ 20:16:39 on 'rainbow/local' with 'GNU-11.2.0' using JUCE 6.1.5
System: Linux 64-bit VST3 on  AMD Ryzen 7 2700X Eight-Core Processor
Host: Ardour @ 48.0 kHz

**Reproduction Steps:**
[warning: will generate >0dBFS loud pop]
1. Set filter type to Notch 12dB or Notch 24dB
2. Set cutoff all the way to the right.
3. Increase filter envelope mod amount.
4. Play a note. Observe loud pop followed by silence.

**Expected Behavior:**
Filters stop exploding and retain behaviour from 1.9. Any intentional changes made as part of refactoring are placed behind a right-click option so that legacy patches sound the same.

**Comment by jatinchowdhury18** [comment]
The original Surge filter code was using a `boundFreq` macro to clamp the filter frequency range:
```cpp
void Coeff_Func(float Freq, float Reso, int SubType)
{
    boundFreq(Freq)
    ...
}
```

With the submodule migration, I removed the macro in favor of an inline function, but failed to correctly update the call sites to:
```cpp
void Coeff_Func(float Freq, float Reso, int SubType)
{
    Freq = boundFreq(Freq);
    ...
}
```
I'm updating the call sites now, plus I'll make the function `[[nodiscard]]` so if anyone forgets in the future, the compiler will warn them.
