### ISSUE TITLE
Update UI control positions when control is being modulated.

### ISSUE THREAD

**Issue by THX2112** [surge-synthesizer/surge#5937]
In a complicated patch it's difficult to understand what's going on when there's a bunch of modulations happening but it's not immediately apparent what's being modulated.

The UI should update the control positions (knobs, sliders, etc) when they're being modulated, in real-time.

Alternatively an indicator could to used to show the modulated control position. 

Going further, directly indicating which modulator is linked to that control would also be useful.

**Comment by baconpaul** [comment]
Have you opened the mod list? That's designed to solve exactly this class of problem. It solves your first, third, and fourth point. Press "LIST" in the section beside the modulators.

But we have chosen not to do displays of animations from modulators. there's a couple of reasons for this

The primary one is: Most of our modulators are polyphonic, so with no voices playing we don't have an instance to show, and with 2 or more voices playing it's not clear which one to pick, especially to a single item near a slider.  So we aren't going to add realtime display of modulation to the sliders.

Thanks!

**Comment by mkruselj** [comment]
Linked to #3618, , #3289, #691. So we already have this sort of issue tracked, hence closing this as a duplicate.
