### ISSUE TITLE
Linux:  Zoom and resize issues

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#594]
When attempting to Zoom to a size larger than the screen in Windows it will give a warning. Here an attempt at 150% was made and it warned that it was selecting 135% and refit.

![resize warning win](https://user-images.githubusercontent.com/41337033/52737912-7cb23180-2f9b-11e9-9bff-890b4c1d6cb8.gif)

In Linux if selecting 150% it will not warn that the monitor/screen limits will be exceeded and will in fact exceed them.

![noresize warning lin 150](https://user-images.githubusercontent.com/41337033/52739855-cac93400-2f9f-11e9-9185-035877c55d7d.gif)

**Comment by baconpaul** [comment]
This problem amounts to making displayinfolinux return the actual screen size

**Comment by tank-trax** [comment]
also zooming to 200% 

![noresize warning lin 200](https://user-images.githubusercontent.com/41337033/52740839-f77e4b00-2fa1-11e9-8b93-e84790612cfc.gif)

and 300% 

![noresize warning lin 300](https://user-images.githubusercontent.com/41337033/52740865-0402a380-2fa2-11e9-8b28-32a977cd82a7.gif)

give the same result as zooming to 150%

**Comment by baconpaul** [comment]
Same bug. Linux does t detect screen size and hardcodes 1440x1050 or some such

**Comment by baconpaul** [comment]
Hi! Pull Request #598 should improve this when merged. Should merge before this weekend unless I've done something wrong (waiting for review).

Thanks for another great bug report.
