### ISSUE TITLE
Linux: Elements disappear from Output section

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#595]
when an item in the  modulation source selection bar is highlighted and flashing green, if the Volume or Pan in the Output section is adjusted the element will disappear

![element 02](https://user-images.githubusercontent.com/41337033/52744055-9195c180-2fa9-11e9-9968-e21aae170dd6.gif)

**Comment by baconpaul** [comment]
Wow thanks clear report!

That is the same behavior we saw elsewhere across the whole ui when painting with a wrong alpha. That’s where I’d look first for this

**Comment by tank-trax** [comment]
- since recent revisions, the Output section is less likely to disappear at 100% 
- elements in this section tend to disappear mostly when the resolution is higher than 100%

**Comment by baconpaul** [comment]
I have kind of a fix for this. At least a fix good enough for 1.6.0. PR inbound for you to test @tank-trax

**Comment by baconpaul** [comment]
@tank-trax its "baconpaul/vanish-alpha-595"

You will notice modulation sliders are darker but they don't vanish on you.

Lemme know.

If this works I can open a 1.7.0 milestone issue to fix the underlying vstgui bug.

**Comment by tank-trax** [comment]
@baconpaul 

tested master versus baconpaul/vanish-alpha-595 and that looks to have corrected it

**Comment by baconpaul** [comment]
Cool. Swept it to master. Thanks for testing!
