### ISSUE TITLE
Increasing Nimbus feedback in Looping Delay mode results in the delay tail sounding bit-crushed

### ISSUE THREAD

**Issue by efthymik** [surge-synthesizer/surge#5954]
**Bug Description:**

**Surge XT Version**

* Version: 1.0.1.60228e8 (2022-01-31)
* Plugin Type: VST3
* Bitness: [64-bit]

**Reproduction Steps:**
1. In any DAW make a looping pattern with a bass sound
2. Insert SurgeEffectsBank and choose Nimbus in LoopingDelay mode, 32k 16bit Stereo
3. Increase feedback sufficiently i.e. 75% (please watch your speakers)
4. Listen to the feedback tail becoming garbled and bit-crushed. Possibly numeric issue?

**Expected Behavior:**
Unintended audio artifacts should not exist 

**Screenshots:**
![NimbusFeedbackBug](https://user-images.githubusercontent.com/74734668/157120212-58eec7e5-00a9-47a4-aae3-fa2b6686bb7d.png)

**Computer Information
 - OS: Windows 10
 - Host: Bitwig
 - Version: 2.4.3

**Additional Information:**
I also attach a wav audio file, screenshot of the aforementioned setup as well a Bitwig 2.4.3 project file. It can be opened with any later version. Furthermore (if I remember correctly) the VCV Rack version of Nimbus does not exhibit this behavior. If needed I will do more testing.

[NimbusFeedbackBug_WAV.zip](https://github.com/surge-synthesizer/surge/files/8200963/NimbusFeedbackBug_WAV.zip)
[NimbusFeedbackBug_Bw2.4.3_project.zip](https://github.com/surge-synthesizer/surge/files/8201045/NimbusFeedbackBug_Bw2.4.3_project.zip)
[VCV2_NimbusFeedback.zip](https://github.com/surge-synthesizer/surge/files/8201859/VCV2_NimbusFeedback.zip)

**Comment by baconpaul** [comment]
Is this actually a bug? I always assumed the 32k but and 16 but busses lose resolution just like the actual devices do. Have you compared with the rack or hardware version at all?

**Comment by baconpaul** [comment]
Oh you said the rack version doesn’t. Hmm. Wonder what it could be.

**Comment by efthymik** [comment]
Hi! I just uploaded a VCV2 test project with Audible Instruments. You need the Vult Free modules and Mindmeld Mixmaster to open it. Play with the BLEND knob to increase feedback.

32k 16bit stereo never ever overflows regardless of my efforts :-) So it seems it is inherent only to Surge version.

**Comment by baconpaul** [comment]
huh i have no idea what i could have done wrong but perhaps we have a level set improperly. i'll tag this into 1.1 and investigate this cycle. Thanks!

**Comment by efthymik** [comment]
Thanks so much to you as well and the rest of the wonderful community of Surge!

**Comment by baconpaul** [comment]
I've confirmed and heard this. I have a theory. Not a fix yet but a theory.

**Comment by baconpaul** [comment]
so 

it seems far far worse in the fx bank
also the fx bank doesn't invalidate parameter labels under changes
so quite a bit to look at here but first and foremost fxbank version is terrible! It's almost like something isn't set up properly in this mode. and the in-synth version has some noise but the rack version also has noise (albeit different noise)

but hard to tell what's going on exactly. I thought it was SRC for a while but I don't think it is.

**Comment by baconpaul** [comment]
@efthymik curious what sample rate you are running at?

**Comment by baconpaul** [comment]
Just documenting my theory

The way our resampled works means for b locks of size 32 we end up calling the lower bitrate with blocks of 23 24 23 24 in surge (and even more peculiar pairs in the fx sometimes I think). and i think this alternating size just kinda screws stuff up.  So my plan is to kinda refactor the resampled so we always call clouds with 4 samples and see if that fixes things. That makes managing the 'leftover' samples a bit trickier though which is why i haven't done it yet. Definitely a 'need a rainy day or sleepless evening' type thing :)

**Comment by baconpaul** [comment]
I've finally found what causes this and have a fix forthcoming which will be in 1.1

**Comment by efthymik** [comment]
I am apologize for the absence @baconpaul , I just saw everything and also commented on your fix. For what it's worth at this moment I have been always running at 48khz.

**Comment by efthymik** [comment]
Just tested it from the latest nightly. Looping delay now works great.

**Comment by baconpaul** [comment]
Super!

the current nightly has a midi learn bug I just fixed so you may want to re update later tonight but glad this got resolved!
