### ISSUE TITLE
Long press (touch) doesn't open context menu for EffectChooser and OscWaveformDisplay

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5980]
Continuation of #5802.

There's widget mixin stuff in EffectChooser.cpp but maybe I badly positioned some of those mixin methods there, or maybe drag and drop fights it somehow. As for OWD, when I tried deriving the widget mixin, it didn't wanna compile saying `notifyControlModifierClicked()` is undefined etc.

**Comment by baconpaul** [comment]
Ahh for the oscillator we get to use template specialization.  Here's the patch for how to do it.

What this does is it makes onLongHold callback give you the option to call code just for the OWD. It can call any method on the OWD if prefaced with `asT()->` as shown.

With this diff plus the method hooks you should be good to go.


[Specialize.patch.txt](https://github.com/surge-synthesizer/surge/files/8311353/Specialize.patch.txt)

**Comment by baconpaul** [comment]
(That diff calls showCustomEditor which is obviously wrong but shows that it compiles and links)

**Comment by mkruselj** [comment]
Partially addressed with #5983, however context menu for Alias additive editor opens quite far away from where finger was on long press.

![image](https://user-images.githubusercontent.com/2393720/159372313-ff130a9e-fbe3-45ca-985c-8d333e5950c5.png)
