### ISSUE TITLE
surge XT not showing up under audio FX in logic pro

### ISSUE THREAD

**Issue by EricE549X** [surge-synthesizer/surge#5994]
**Bug Description:**
idk if this is a bug per se, but whenever i try to open surge on audio FX, only the effects plug-in comes up, not the main synth.

**Surge XT Version**
* Version: 1.0.1
* Plugin Type: AU
* Bitness: 64-bit

**Reproduction Steps:**
1. open logic pro
2. create empty project
3. create software instrument or audio track
4. click "audio FX" in the track inspector
5. in the drop-down menu, scroll down to "audio units"
6. hover over "audio units", then "surge synth team"
7. see error

**Expected Behavior:**
the main synth should come up alongside the effects rack.

**Screenshots:**
<img width="475" alt="Screen Shot 2022-03-26 at 1 22 29 AM" src="https://user-images.githubusercontent.com/86898409/160226146-fc8c86d2-9bf9-4df7-a046-d540855b3b24.png">

**Computer Information (please complete the following!):**
 - OS: macOS (version 12.3)
 - Host: logic pro (version 10.7.3)

**Additional Information:**
again, idk if this is really a bug or if i should just use the app version. thanks

**Comment by mkruselj** [comment]
Not a bug, Surge XT Effects is an effect plugin, Surge XT is instrument only.

**Comment by baconpaul** [comment]
If you want to use the synth as an fx you can roue in either side chains too

**Comment by EricE549X** [comment]
> Not a bug, Surge XT Effects is an effect plugin, Surge XT is instrument only.

ok was just curious, thanks!
