### ISSUE TITLE
Menu not Working

### ISSUE THREAD

**Issue by bowalk69** [surge-synthesizer/surge#5995]
**Bug Description:**
Menu only works on about

* Version: VST3 1.9.0.9106918

**Reproduction Steps:**
2. Click on '...'
3. Scroll down to '...'

**Expected Behavior:**
Be able To open anything on menu

**Computer Information (please complete the following!):**
 - OS:Linux  AVL MX-21
 - Host: Mixbus32c
 - Version: 7.2.0

**Additional Information:**
am able to open patches and able to play them 
It does work in ardour

**Comment by mkruselj** [comment]
We don't support Surge 1.9 anymore. Try Surge XT?

**Comment by bowalk69** [comment]
hank you

**Comment by mkruselj** [comment]
Does it work with Surge XT for you? Let us know!

**Comment by mkruselj** [comment]
Going to close this one. @bowalk69 Please let us know if Surge XT works fine for you. If not, reopen the issue and we will investigate.

**Comment by bowalk69** [comment]
Yes, it works.
