### ISSUE TITLE
How to disable VST in Surge XT?

### ISSUE THREAD

**Issue by yurivict** [surge-synthesizer/surge#5996]
**Bug Description:**
I'm getting this error on FreeBSD:
> error: To build JUCE VST3 plug-ins on BSD you must use an external BSD-compatible VST3 SDK with JUCE_CUSTOM_VST3_SDK=1

Rather than making VST work, how to disable it altogether for now?

**Surge XT Version**
1.0.1

**Comment by baconpaul** [comment]
if you disable it, how will people use the software?

but if this error is in the build phase, you can simply not build the vst3 target. and if it is in the initial cmake phase you can remove "VST3" from SURGE_JUCE_FORMATS in src/CMakelists.txt with a patch and replace it with Standalone.

**Comment by baconpaul** [comment]
and if this turns out to be useful to your user base, easy for us to add a `SURGE_SKIP_VST3` cmake option to our 1.1 release. Just let us know!

**Comment by yurivict** [comment]
@baconpaul I just want to disable VST, and leave LV2, etc.

Adding ```SURGE_SKIP_VST3``` should be useful.

**Comment by baconpaul** [comment]
Ok I’ll add it to head this week and the you can apply as parch against 101 if you want. 

Thanks

**Comment by baconpaul** [comment]
Hi

Commit [3ba6b82](https://github.com/surge-synthesizer/surge/pull/5998/commits/3ba6b82d559c5026ebdc187c8af3a048508e6463) provides both the features you asked for (VST3 off; ALSA off) as options.

You should be able to merge that diff as a patch against 1.0.1 for your purposes.

It will be in our next 1.1. release, but there's currently not a scheduled date for that.

Thanks!

**Comment by yurivict** [comment]
Thank you!
