### ISSUE TITLE
How to disable ALSA?

### ISSUE THREAD

**Issue by yurivict** [surge-synthesizer/surge#5997]
**Bug Description:**
ALSA isn't supported well on FreeBSD because it is a Linux technology. JACK should be the default.

How to disable ALSA?

**Surge XT Version**

* Version: 1.0.1

**Comment by baconpaul** [comment]
There is a juce_alsa flag which is on in a standalone only. Is there a reliable way to detect free bsd and not Linux in cmake?

**Comment by baconpaul** [comment]
But anyway when I add the vst3 suppression o can also add alsa and jack independent toggles with good defaults

**Comment by yurivict** [comment]
> Is there a reliable way to detect free bsd and not Linux in cmake?

> if ("${CMAKE_SYSTEM_NAME}" MATCHES "FreeBSD")

**Comment by baconpaul** [comment]
Thank you
