### ISSUE TITLE
Linux: +/- Resize issue 

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#600]
the minus key to the left of Backspace if pressed will Shrink the app however the plus key will not Zoom in

the - key is active whether shift is pressed or not
the + key is inactive whether shift is pressed or not

**Comment by baconpaul** [comment]
I am pretty sure I fixed this on branch `baconpaul/linux-plus-zoom-600` as described in PR #668 

@tank-trax don't suppose there's a chance you could test if that branch also works for you with + zooming? If so I'll merge it in. Thanks!
