### ISSUE TITLE
Filter analysis issues

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#6043]
- [x] Combs don't plot
- [x] Weird plot for OB-Xd 24dB
- [x] Pre-filter gain slider should impact the plot too
- [x] Selecting a subtype from RMB menu doesn't update the plot
- [x] Tearing out doesn't resize properly:
![image](https://user-images.githubusercontent.com/2393720/162595626-457e347e-f374-4b95-988b-8701e0790231.png)
- [x] Add an asset for filter analysis button, not to reuse the waveshaper one
- [x] When closing the filter analysis tearout, the button which opens the overlay doesn't go to "off" state

**Comment by baconpaul** [comment]
- [ ] Make these displays consistent (and prefer the one for the filter not the wave shaper, with mseg colored axis and labels)
<img width="495" alt="Screen Shot 2022-04-10 at 8 36 52 AM" src="https://user-images.githubusercontent.com/13387561/162618461-66738bf4-4e8b-4282-8d1e-b4dbaec49071.png">
<img width="497" alt="Screen Shot 2022-04-10 at 8 36 44 AM" src="https://user-images.githubusercontent.com/13387561/162618462-c2e4cce6-d174-4190-9fb7-d29fe5085f69.png">

**Comment by baconpaul** [comment]
tackling a few of these now
