### ISSUE TITLE
holding shift-down while hovering on macvst2/au will shoot forth tons of popups/tooltips that take ages to vanish

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#605]
<img width="345" alt="fullscreen_14_02_2019__21_07" src="https://user-images.githubusercontent.com/4966687/52811355-8f149400-309d-11e9-8064-4ff4990ce808.png">
<img width="1440" alt="fullscreen_14_02_2019__21_08" src="https://user-images.githubusercontent.com/4966687/52811360-90de5780-309d-11e9-806c-b6012758abca.png">

video posted at
https://surgesynth.slack.com/files/UF7BKN3D2/FG79RPW3V/hold-shift-down-and-move.mov

**Comment by baconpaul** [comment]
The problem here is that the drag implementation doesn't implement beginEdit/endEdit the same way the click implementation does.

**Comment by baconpaul** [comment]
And there's some awful state dependent behavior which makes VST2 and AU different

in AU shift-moving over the control doesn't even show the popup. In VST2 it goes away eventually - probably due to the dismiss timer loop - but doesn't go away as quickly as on mouse click.

I think I need to review the whole info window open close state. That's a big annoying problem.

But this is nothing to do with the shift change. The shift change just lessens the footprint of the problem.

**Comment by baconpaul** [comment]
So here's the problem (adding @rghvdberg )

if you call beginEdit and not endEdit, a timer is supposed to kill the popup. Line 431 of SurgeGUIEditor

but if you have popped it up somewhere else and left it open and then haven't hit the timeout and popup a second place, voila

So the trick is before you go moving the parameter tooltip for the next show you have to check if it is showing and if so hide it.

**Comment by baconpaul** [comment]
So that's around line 2491 of SurgeGUIEditor 

```
 if (buttons || forceMB)
   {
/*
   add here if info window is visible then hide it and invalidate before you move it
 */
      ((CParameterTooltip*)infowindow)->setViewSize(r);
      ((CParameterTooltip*)infowindow)->Show();
      infowindow->invalid();
      clear_infoview_countdown = 40;
   }
   else
```

**Comment by baconpaul** [comment]
(I'm in a totally different branch now so can't fix this right now but wanted to put this in here)

**Comment by rghvdberg** [comment]
like this ?
```
 if (buttons || forceMB)
   {
      if (((CParameterTooltip*)infowindow)->isVisible())
      {
         ((CParameterTooltip*)infowindow)->Hide();
         ((CParameterTooltip*)infowindow)->invalid();
      }    
      ((CParameterTooltip*)infowindow)->setViewSize(r);
      ((CParameterTooltip*)infowindow)->Show();
      infowindow->invalid();
      clear_infoview_countdown = 40;
   }
   else
```

**Comment by baconpaul** [comment]
Yes I think that’s what we need. Does Linux still basically work with that in place?

And with that you should be safe to not call endedit in the mouse scroll wheel (if you add a comment explaining why)
