### ISSUE TITLE
Tearouts remember size and position but don't paint the editor properly

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#6059]
Tested on Debian 11 using KDE and Mint 20.2 using Cinnamon

Version: Surge XT 1.1.nightly.462ec98
Build: 2022-04-13 @ 13:35:58 on 'fv-az304-307.5u0vy1jg2qkunbkkuu5dnyfkvd.ax.internal.cloudapp.net/pipeline' with 'GNU-7.5.0' using JUCE 6.1.6
System: Linux 64-bit VST3 on  Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
Sample Rate: 48.0 kHz

when opened looks like this

![image](https://user-images.githubusercontent.com/41337033/163590112-61a1af3f-51c6-4dbd-a279-fe3f54c6a48c.png)
 
 al it takes is the slightest of adjustments on bottom right corner or resize to paint all elements
  
![image](https://user-images.githubusercontent.com/41337033/163590241-69ac15f2-c994-46aa-af26-f39f4f7512ec.png)

this will happen when opening and closing the editor and when quitting and restarting app when using standalone, also the VST3 in Reaper 

I've seen this issue with other apps built using JUCE, MOK and Waveform (both built using JUCE) had this issue with a few VST3's when opening.... 

happens with all elements that can tear out.... 

it affects all windows/editors that can detach and happens at the bottom of the window.... 

https://user-images.githubusercontent.com/41337033/163592569-4e330bae-d03d-4aaf-b4fe-5d836dfe89c7.mp4

**Comment by baconpaul** [comment]
right this is a sizing/positiong glitch when torn out not accounting for the window decoration somehow. a resize fixes it obviously but why doesn't the original size get it? Probably because i force size the window size not the content size in the tearout.
