### ISSUE TITLE
Option to make Find Patch typeahead listbox stick around after loading the patch

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#6063]
Currently, this listbox automatically closes after loading a patch. However, it would be so much better to be able to make it stick around, so that we can quickly audition all patches in our search term.

I did a little bit of exploration, and commenting out these lines make the listbox stick, and survive UI rebuild (unless you destroy then recreate the whole editor):

TypeAheadTextEditor.cpp L135 L144
PatchSelector.cpp L1089

Things that would need improving:

- [x] When using arrow keys, after loading the patch they will always start browsing from the first entry in the listbox, instead of currently selected entry in the listbox
- [x] Magnifier button should be a toggle - when we're in typeahead mode it should drop out of it and close the listbox. Ditto the Find Patch keyboard shortcut!
- [x] By default, Ctrl+click or Ctrl+Enter should load the patch with the listbox sticking around - regular click or Enter would load patch and close the listbox
- [x] But also, add a Menu->Workflow preference to flip the behavior, so that the listbox sticks around by default, and if you Ctrl+click or Ctrl+Enter then it loads the patch and closes the listbox
- [ ] As a bonus nicety (not a requirement but it _would_ be mega nice) - listbox surviving UI destroy and recreate?

Plausible for 1.1 @baconpaul?

**Comment by mkruselj** [comment]
Will definitely give it a whirl, thanks! 👍

**Comment by baconpaul** [comment]
Ahh ha ha ha
here's why the magnifier doesn't act as a toggle
if you click it once it arms typeahead
if you click it a second time, it defocuses the typeahead and the typeahead dismisses on defocus, so when you get to the second click the defocus has happened and the thing isn't showing, so the second click shows it again.
that is annoyingly hard to fix. i will need to ponder

**Comment by mkruselj** [comment]
And with that, we're good for 1.1!
