### ISSUE TITLE
Mouse Wheel controls Sliders

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#607]
@rghvdberg wants to do this and I think it is cool

You select a slider and scroll mouse wheel. Slider scrolls.

control has a `virtual bool onWheel()` method which we can override to do the appropriate setValue for the slider akin to the onMouseMoveDelta etc... stuff already in the codebase. (May need a bit of a refactor to avoid copy and paste).

**Comment by rghvdberg** [comment]
I've tried
```
bool CSurgeSlider::onWheel(CPoint& where, const float& distance, const CButtonState& buttons)
{
printf("CSurgeSlider::onWheel distance %f\n",distance);
return true;
}
```
nothing showing up in ..
however
CMouseEventResult CSurgeSlider::onMouseEntered(CPoint& where, const CButtonState& buttons)
{
printf("Mouse entered\n");
 return kMouseEventNotImplemented;
}
works
so ....

**Comment by baconpaul** [comment]
Two thoughts 

1: virtual and override done properly in the h file? 
2: move the print statement to the vstgui lib platform code which calls onwheel if it exists
2a: if it doesn’t exist there’s the problem

**Comment by rghvdberg** [comment]
I did it like this
https://github.com/rghvdberg/surge/commit/26e6910ff26751a385e3df3f5e23745ca630d7fe
trying to override
https://github.com/surge-synthesizer/vstgui/blob/1dced2b2d82d78173dcaddfff998c0d21f199871/vstgui/lib/cview.h#L109

**Comment by baconpaul** [comment]
Right
So that looks correct
I wonder if the implementation of cview on Linux just doesn’t send the message
I would do a grep -r of onwheel in vstgui/lib/platform/Linux as a next step and stare at whatever code you find maybe?

**Comment by rghvdberg** [comment]
https://github.com/rghvdberg/surge/commit/d3f29c97fab238b5fddbceca8cca394e2aa470af
https://github.com/rghvdberg/surge/commit/72e88b626a9958088cbc0a8802e16d4f5d203a84
I haven't figured out yet to determine the type of a control value (int/float/bool)
so any advice there is welcome

**Comment by mkruselj** [comment]
Would be cool to have Shift+mousewheel doing fine movement just like when you drag via mouse cursor itself. :)

**Comment by rghvdberg** [comment]
and we probably want the popup with values , just like when moving the slider with the mouse

**Comment by baconpaul** [comment]
Absolutely want the popup
figuring out when you are editing will be tricky though
same problem which makes shift-mouse-move a messing #605

**Comment by baconpaul** [comment]
You also have to behave differently in modulation mode than in regular edit mode. So if you are modulating you need to change modval not val

I don't think you need to worry about type. setValue does the cast. But you do need to worry about the modulation status

Take a look at how onMouseDown / onMouseUp and onMouseDrag interact by setting edit_value to either &mod_value or &value and calling begin edit and end edit. That's the same pattern we want here.

The only problem is there is no natural way to indicate "begin" so you probably want to do a "beginEdit" at the top, an "endEdit" at the bottom and for now that will flicker the popup

The shift handling is in getMoueDeltaScaling

The mouse scaling also uses range just like you do. So good there

and the mod mode binary controls where you are modulating. 

Oh and from looking at your commits, please do remember to indent properly and stuff before PR!

Thanks

**Comment by rghvdberg** [comment]
ok, this seems to work
```
bool CSurgeSlider::onWheel(const CPoint& where, const float& distance, const CButtonState& buttons)
{
   double rate = 0.1 * moverate;
   if (buttons & kRButton)
      rate *= 0.05;
   if (buttons & kShift)
      rate *= 0.05;
   beginEdit();
   edit_value = modmode ? &modval : &value;
   oldVal = *edit_value; // do I need this ?
   *edit_value += rate * distance;
   bounceValue();
   if (modmode)
   {
      setModValue(*edit_value);
   }
   else
   {
      setValue(value);
   }
   setDirty();
   if (isDirty() && listener)
         listener->valueChanged(this);
   endEdit();
   edit_value = nullptr;
}
```
now for that *popup* ... how the heck do I pop that up ? :wink:
