### ISSUE TITLE
Surge FX Type-In

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6072]
@whitecatcafe asked in https://github.com/surge-synthesizer/surge-fx/issues/44 for type in params for the effect bank.

Moving that (reasonable) request over here. Since we have the code to do the reverse conversion we should be able to get there I think. Need to figure out the UI gesture. Let me tentatively tag this 1.1 but also tag as may bounce.

**Comment by mkruselj** [comment]
UI gesture would simply be - double click on the value string directly. No need to open a separate context menu, just make the JUCE label editable.

**Comment by baconpaul** [comment]
Yes that was my plan. And then I need to figure out the accessible gesture too (but I’m sure we can figure that out)

**Comment by baconpaul** [comment]
Ahh need to remember that continuous become a type-in but discrete values become combo boxes. So a bit of nuance here.

**Comment by baconpaul** [comment]
baconpaul — 04/19/2022
Hey accesibility friends. We have had a request to enable value typein on the FX bank. This is easy to do - we have the inverse code - and the natural gesture in the UI is to double click on the label and it becomes an editor. (the UI has a knob by the big label and the label is an obvious target). Curious what the gesture in the screen reader would be to initiate edit on the label? I could add an invisible 'edit' button for instance but wonder how others do this. Thanks!
bscross — 04/19/2022
We could have the screen reader jump the mouse to it and double click. That is not what some would call natural for screen readers, but it can easily be done. My thing is not how could a screen reader user do it, but how would they know they can do it.
Also, in NVDA at least, there is a keystroke that will attempt to figure out what the default action for a control is, and then perform that action. If it's a button, it presses it, if its a radio button, it invokes the option you pressed the keystroke on, etc.
pitermach — Yesterday at 2:38 PM
First thought that comes to mind is a key, like enter since it doesn't do anything on a slider and it would feel pretty natural. You could also set the "press" accessibility action to trigger this as well which would help on Mac. THen for notifying people you can set the controls description (I think that's what it'll be called in Juce at least) which is going to be spoken by screen readers if someone has the option to read help messages on. So if you set the descriptions for those sliders to something like "press enter to type in a value" it'll be spoken after all the other info.
Or you can always just mention this in the manual as well
