### ISSUE TITLE
String oscillator oversampling and interpolation

### ISSUE THREAD

**Issue by SirPrimalform** [surge-synthesizer/surge#6081]
I know that Surge XT uses oversampling in certain blocks depending on the host sample rate, but I was wondering if the string oscillator uses any oversampling?

I adore the string oscillator but I have some ideas that could potentially improve its response, particularly in the upper register.
I have a feature request in mind but I thought it was best to start a discussion first in order to make the FR in a sensible manner.

**Comment by baconpaul** [comment]
Oh also check out #5992 where we contemplate changing or optionally changing the frequency response at high stiffnessss

**Comment by SirPrimalform** [comment]
Wow, that was an incredibly fast reply, thanks!

So my line of thinking is:

-Karplus-Strong synthesis tends to sound quite muffled in the upper register due to the effects of the buffer interpolation becoming more significant the higher you go.

-Interpolation is necessary for tuning accuracy and modulation. The tuning problems are slight at longer, deeper buffer lengths but become more significant the higher you go. The tonal quality of KS synthesis is clearer without interpolation.

-The normal reason for oversampling oscillators is to avoid aliasing, but oversampling the KS buffer provides other tonal benefits. Every doubling of the OS factor moves the problems described an octave up. Without interpolation this increases tuning accuracy and with interpolation this shifts the damping problems further out of reach.

I am not a real programmer but I've done enough experiments with Reaper JSFX and VST hosts that provide oversampling and the results sounded great. It's obviously horribly inefficient to oversample the entire synth at 8 or 16x though.
Oversampling just the actual buffer should have all of those benefits and be much more efficient. I imagine it might be beneficial to oversample the exciters along with it (if audio-in is selected then it would have to be upsampled at the input to the oscillator block).

Does any of this make sense or have I misunderstood things?

I was thinking along the lines of context menu options with the defaults being the current behaviour.

**Comment by SirPrimalform** [comment]
If any of this seems remotely sensible I'll try and formalise it into a feature request.

**Comment by SirPrimalform** [comment]
Hey there, I'm back with examples!

https://drive.google.com/open?id=11KhDdrsUM5QEpc1cjs-5b-v4BT1PMyTr
I chose some ridiculously high notes to give the clearest example, the top notes almost don't sound pitched at 48kHz because the interpolation steals all of the energy almost straight away.

The methodology here was first I set up the most basic string oscillator patch imaginable in Surge hosted in Reaper. Then I offline rendered the short clip first with a project sample rate of 48kHz, 192kHz and finally 192kHz downsampled to 48kHz using Reaper's highest quality option. I think it makes a pretty huge difference! The test should be easily replicable in any DAW that allows offline rendering at high sample rates.

Being able to oversample only the oscillator should give the same benefit without increasing the CPU overhead quite so much (obviously the memory usage would increase by the oversampling factor). It would be nice to be able to take the oversampling factor even further than this example - I had good results with 16x using the JSFX synthesiser Hammer and Chord by Geraint Luff.

It would be amazing to have a right click menu option on the string oscillator that lets you select 2x, 4x, 8x and 16x and possibly an option to disable interpolation (i.e. only use integer buffer lengths) with the caveat that tuning accuracy will suffer slightly (but less at high OS factors) and pitch modulation would be steppy. Without interpolation, the buffer feedback is transparent which improves both sustain and frequency response and the slight tuning errors can be considered 'character'. ;) 

Hopefully I've at least convinced you about the value of oversampling the buffer if not the rest.

**Comment by baconpaul** [comment]
Wow that is a huge difference. Much bigger than I expected. 

the interpolation method is the easiest one. The delay line class already has a linear interpolation and adding a zoh would be trivial. We could then make that a deform parameter 

the oversampling is a wee bit trickier. We pretty carefully manage memory pools but I can imagine a way to segregate the pool easily. And yeah a rmb would work well there too.

without committing to do this for 1.1 let me kick this issue into the 1.1 milestone since I want to open up the oscillator for the tuning issue anyway. May not happen for next release but if it doesn’t it’s worth knowing what’s hard about the naive solution at least

**Comment by baconpaul** [comment]
Also thank you for taking the time to make examples. Appreciated

**Comment by baconpaul** [comment]
Heya the next nightly will have 3 interpolation modes as well as 2x oversampling


<img width="409" alt="Screen Shot 2022-05-02 at 11 38 31 AM" src="https://user-images.githubusercontent.com/13387561/166265862-a425a2d8-d8af-43a7-89e2-4996bcf28779.png">

this issue will close when i merge that change and a nightly will appear about an hour after that.
