### ISSUE TITLE
surge_32.dll apparently causes issues with windows users because of other plugins by that name

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#610]
@baconpaul suggested `Surge32bit.dll` 

from KVR:
```
32bit Windows keeps giving:
”The 32-bit Windows build has the same file name (Surge32.dll) as 32-bit Airwindows Surge, http://www.airwindows.com/surge/
At least 32-bit REAPER finds/loads only one of these, might be a problem in some others too but I have only REAPER to test with (and Jeskola Buzz 32-bit as a sort of a relic, loads both plugins fine).
Both plugins load in the 64-bit version of REAPER as the file names are different (and 64-bit REAPER is what I use anyway).”
```

So looks like filenames could be tweaked.

**Comment by baconpaul** [comment]
1. premake5.lua gets `targetsuffix 32` changed to `targetsuffix _32bit_x86`
2. update installer_win/surge-x86.iss to reflect new name
3. test, push

**Comment by tank-trax** [comment]
I experienced the same issue in Linux using Radium.It did not know which file to load and ended up loading the airwindows by default.

I changed the file name of the airwindows VST as they were the same for both.

**Comment by esaruoho** [comment]
cool, so surge-x86.iss name will not be much of an issue. @kzantow do you wanna help me with this? need to make sure the build will go fine for windows 32-bit builds

**Comment by esaruoho** [comment]
@tank-trax issue has been fixed. it'll be `surge_x86.dll` and `surge_x86.vst3` from now on.
