### ISSUE TITLE
KVR Request for More AirWins

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6114]
https://www.kvraudio.com/forum/viewtopic.php?p=8420895#p8420895

Lets take a look at this list and choose a yay/nay on them and sweep them if easy

Haven't Evaluated

YAY

- [x] ChromeOxide
- [x] DubSub
- [x] DubCenter
- [x] FireAmp
- [x] GlitchShifter
- [x] NonlinearSpace, 
- [x] Pafnuty
- [x] PowerSag
- [x] TapeDust
- [x] ToVinyl (ToVinyl4 exists so prefer that at least if we are yay)

NAY

- [x] toTape5 (we include toTape6 so don't do this one)

**Comment by mkruselj** [comment]
YAY (-> to which category):

ChromeOxide -> Tape
DubSub, DubCenter ->Filter
FireAmp -> Saturation and More
GlitchShifter -> new category, Pitch
NonlinearSpace -> Ambience
Pafnuty -> Filter
PowerSag -> Saturation and More
TapeDust -> Noise
ToVinyl4 -> Lo-Fi

Others are NAY.

**Comment by baconpaul** [comment]
on it

**Comment by baconpaul** [comment]
pafnuty has too many params. knocking that one out.

**Comment by baconpaul** [comment]
I guess I could just leave it fixed at default sure. I’ll look. Got the rest of them in

**Comment by mkruselj** [comment]
DOH I forgot the AW Type parameter.

XT2 can't come soon enough. 😀
