### ISSUE TITLE
Tearout issues

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#6115]
From Jacky:

- [x] "In earlier iterations of Surge XT, I seem to recall that tear-outs (MSEGs, Tuning Editor, etc.) remained in an 'on top' state until closed, but as I've been working with the newer versions starting with 1.0.1 and subsequent nightlies, after opening these tear-outs, when one clicks back onto the main Surge XT UI, the open tear-out disappears behind the host, requiring ALT+Tab to bring it back to the front..."  [@baconpaul comment: XT 1.0.1 on macOS doesn't have always-in-front. Can we check if 1.0.1 on windows did? Also i wonder if this is a DAW setting?]

From me:

- [x] First issue, reproduction steps:
[ @baconpaul comment here: the problem is on startup you get an extra turn of the zoom factor for some reason ]
1. open MSEG editor, pop it out
2. exit standalone by clicking X on the main window
3. reopen Surge
4. the popped out MSEG editor is now much larger, didn't retain old size

This can actually also be reproduced like so:

1. open MSEG editor, pop it out
2. switch to Formula
3. go back to MSEG - now it's increased in size
4. go back to Formula - now it's increased in size
5. repeat steps 2-4

- [x] Second issue, reproduction steps: [@baconpaul comment - doesn't occur on linux or macOS with standalone]
1. Tear out an overlay
2. Resize it to make it as small as it gets, and then keep on dragging the mouse to resize it further below the minimum size. Observe the redraw issue killing the title bar etc.:

![image](https://user-images.githubusercontent.com/2393720/166701998-978dffdc-5cfe-4785-8126-6096f4fdc86b.png)

- [x] Double-click on title bar in a tearout should reset to default size

- [x] When MSEG editor is torn out, pressing Unipolar button doesn't refresh tearouts 🙁 [@baconpaul comment - this was fixed when i fixed the unipolar repaint issue in tear-in]

**Comment by baconpaul** [comment]
Also if we resize can we restore to default size through a ui gesture

**Comment by mkruselj** [comment]
We can't, double-click on title bar doesn't work on tearouts the way it does for inside Surge overlays. Should be consistent ofc!

**Comment by baconpaul** [comment]
OK @mkruselj once I merge #6203 I think we have fixed these problems. I tested on windows and mac no problem and fixed a few bugs.

I'm gonna leave it open for you to give it a test once merged, but I think we have this one.

A proper juce constrainer and correct understanding of the component borders and also not doing multiple updates of the user state on restart were the key.

**Comment by baconpaul** [comment]
Oh and we show on top but we never were always on top. So I'm not sure what to do about jacky's comment

**Comment by mkruselj** [comment]
Confirmed fixed for the two leftover issues except Jacky's.

I did notice that there's some flickering/jittering when starting Surge with an overlay popped out. Not sure how easy that would be to resolve.

**Comment by mkruselj** [comment]
@baconpaul Confirmed 1.0.0 and 1.0.1 behaved the same w.r.t fronting tearouts in DAWs as we do now. So, this would actually be a feature request then. Is it tricky?

**Comment by baconpaul** [comment]
I don't see an API that can do it. And I don't have control over the DAW parent window. So "yes"

but it's not a regression so lets add it as a separate FR issue in unscheduled

Lemme see if I can find that jump-on-startup and if i can i'll close this.
