### ISSUE TITLE
125x images have mis-aligned background

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#612]
@itsmedavep seems the 125x image has the background mis-aligned

Here's linux zoomed to 125. Windows does the same.

I didn't catch it because on mac with my retina display 125 == 250 so it uses the 300 asset

![image](https://user-images.githubusercontent.com/13387561/52863987-31b52d00-3107-11e9-8e5c-667dbe098d46.png)

can you check and re-export the 125 images when you get a chance? We can sweep immediately when you do.

Thanks.

**Comment by baconpaul** [comment]
Hi @itsmedavep I turned off 125x in the builds for now so the urgency is less. When you get a chance!

Sort of need to do a code change and a windows or linux build to test it.

**Comment by itsmedavep** [comment]
Obviously that’s busted. Ouch. 

I’m not near a machine right now but I’ll take a look when I get close to one. Should be in an hour.

**Comment by itsmedavep** [comment]
Sorry BTW!

**Comment by itsmedavep** [comment]
https://github.com/surge-synthesizer/surge/pull/618

**Comment by baconpaul** [comment]
No need to apologize! Sorry my testing skipped it! It was only in master for 40 minutes so no big deal at all!!

**Comment by baconpaul** [comment]
Hi! So @esaruoho @itsmedavep and I are working on a different way to deal with 125x images (and for that matter all images) so I'm going to close this issue for now in anticipation of our approach working.
