### ISSUE TITLE
Surge XT Effects crashes

### ISSUE THREAD

**Issue by autonym8** [surge-synthesizer/surge#6120]
**Bug Description:**
When some bypass buttons are toggled in one of the effects of Surge XT Effects, choosing another effect will cause Ableton Live 10 to crash.

**Surge XT Version**

* Version: 1.1.nightly.5013ebd
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**

1. Load Surge XT Effects in empty track of Ableton Live 10 and Surge XT Effects 1.1.nightly.5013ebd
2. Change to any effect that has some knobs that can be by passed (eg : EQ)
3. Toggle any bypass of the effect (eg : bypass Band 1)
4. Choose another effect (eg : Exciter)
5. Ableton Live crashes

**Expected Behavior:**
The new chosen effect should load without crash.

**Computer Information (please complete the following!):**
 - OS:Windows 11
 - Host: Ableton Live 10
 - Version: 10.1.42

**Comment by baconpaul** [comment]
Thanks for the great bug report!

**Comment by baconpaul** [comment]
Have a fix. Will be in a nightly later today. Thanks!
