### ISSUE TITLE
Un-static the sample rate

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#6126]
Reaper has per-plugin oversampling now, so if somebody wants to oversample Surge, they have to do it for all instances, or none (or host Surge out of process).

It would be nicer if this could be a per instance member rather than a per process static. So let's see if Paul needs to give up on Discord or not. Chuckle. 🙂

**Comment by baconpaul** [comment]
this issue amounts to "what parts of the codebase use sample rate and don't have a reference to a SurgeStorage *"

I think the way to fix it is, as they say, f__ around and find out. I tried it before and the filters broke me, but we resolved that when we refactored them. So may be doable.

The reaper feature means this will break everyone if we don't fix it so i'll tag it into 1.1, more aspiration ally than commitment wise
