### ISSUE TITLE
Teensy is too teensy for linux

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#613]
At smallest (50%) on mac and windows you can still click menu. On linux not so. So make smallest zoom for linux 75%.

Heuristics are all we have here. @rghvdberg and I both confirmed linux is too small when it is as small as it can be.

**Comment by sense-amr** [comment]
is Teensy a thing ? for zoom option ? in windows?

**Comment by baconpaul** [comment]
Not in the patch I gave you for livestream
But in the latest master, yeah
And soon it will all be savable also.

**Comment by sense-amr** [comment]
i mean "TEENSY" as an actual named option ?:) to choose MINIMUM size surge for set detected screen size? and ofcourse maintaining the all important access to the MENU function to bring it back .. ? i read you were saying something about it remembering size? when would this memory occur?.. saved with patch data or ? .. cos i personally would love to see 100%  all the time everytime i load surge.. and memory is not needed at all in my view.. i just wanted the option to make teensy cute little surges if i have 10+ of them going in a thing..

**Comment by baconpaul** [comment]
Oh no teensy is not a named option. It says "zoom to smallest". The only place the word teensy appears is in the error message if you try to zoom smaller

The semantics are going to be, shortly

1. Surge is always 100% when you startup if you don't do anything
2. You can zoom up and down and inside that session the zoom is remembered. If you save your session file and restart, though everything goes back to 100%
3. On a per user basis you can opt in with a menu item which says "set ... to default zoom" so you can zoom to 125 then click "set 125 to default zoom" and every surge forevermore will start at 125 in a fresh session

Obviously #2 needs fixing. We want to save zoom state not in a patch but definitely in a host. That's tricky so I'm still thinking about it.

**Comment by baconpaul** [comment]
The semantics right now in your patch are the first and second; the semantics right now in master are 1 only.

"Shortly" will be very soon. I have 1-3 working in a branch on mac all hosts. Just need to run it around the vms for testing and then drop in a PR for review.

**Comment by sense-amr** [comment]
oh come on @baconpaul "teensy" is the best possible name for it .. and you know it!

**Comment by baconpaul** [comment]
Only if we replace "grow" with "embiggen".

**Comment by sense-amr** [comment]
ahhahaha 
i think that should also be done :)

**Comment by baconpaul** [comment]
May be that it’s not too teensy but rather that linux menus at scale < 100% are broken as reported in #617 ... lets see.

**Comment by baconpaul** [comment]
Turns out this isn’t that linux is too teensy; it is rather, as reported in #617, that the menus get double clipped while shrinking. I have a good idea what’s happening and will try and fix that, but then this issue is not what we thought so I’m gonna close it. (If, when I get menus rendering when shrunk, it is still too tiny I may reopen it but its fine on mac and win so should be fine in Lin)
