### ISSUE TITLE
"Download Additional Content...." link in menu reporting a 404 error.

### ISSUE THREAD

**Issue by richardkrone** [surge-synthesizer/surge#6132]
**Bug Description:**
"Download Additional Content...." link in menu reporting a 404 error. It goes to https://surge-synthesizer.github.io/Additional-Content which reports "Page not found :( The requested page could not be found."

**Surge XT Version**
Boy, it would be nice to be able to copy this data and just paste this from the About screen of Surge thus preventing typos. Just a thought.

* Version: Surge XT 1.0.1.60228e8
* Plugin Type: LV2
* Bitness: [64-bit]

**Reproduction Steps:**
Just downloaded the Deb file and installed it. Opened up Carla to check it out. Tried the MENU >> Download Additional Content link and found it was broken.

**Expected Behavior:**
Anything but a 404.

**Computer Information (please complete the following!):**
 - OS: Linux Mint 20.2
 - Host: Carla
 - Version:2.1.0

**Additional Information:**
Great synth but a bit 1995 Windows feel.

**Comment by baconpaul** [comment]
> Boy, it would be nice to be able to copy this data and just paste this from the About screen of Surge thus preventing typos. Just a thought.

It would! That's why we have this link that copies it to the clipboard :)

<img width="1048" alt="Screen Shot 2022-05-06 at 11 04 19 AM" src="https://user-images.githubusercontent.com/13387561/167160260-509aeb11-4d6d-4bdf-99c6-f5dc990e1236.png">

Thanks for reporting the broken link. Tagging into the 1.1 milestone.

**Comment by mkruselj** [comment]
Found it! PR soon.

**Comment by richardkrone** [comment]
You devs are great. Thank you for the speed of the fix. Did not expect it.
