### ISSUE TITLE
Font Patches for vstgui

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#614]
@rghvdberg reports crashes ubuntu 16.04 at vstgui startup loading fonts since he has not installed Arial

He suggests the following. Symbol is not used so leave it be.

```
@@ -42,6 +42,16 @@ namespace VSTGUI {
  static CFontDesc gNormalFontVerySmall ("Arial", 9); 
  static CFontDesc gSymbolFont ("Symbol", 13); 
 
#elif LINUX 
  static CFontDesc gSystemFont ("sans-serif", 12); 
  static CFontDesc gNormalFontVeryBig ("sans-serif", 18); 
  static CFontDesc gNormalFontBig ("sans-serif", 14); 
  static CFontDesc gNormalFont ("sans-serif", 12); 
  static CFontDesc gNormalFontSmall ("sans-serif", 11); 
  static CFontDesc gNormalFontSmaller ("sans-serif", 10); 
  static CFontDesc gNormalFontVerySmall ("sans-serif", 9); 
  static CFontDesc gSymbolFont ("Symbol", 13); 
 
#else 
  static CFontDesc gSystemFont ("Arial", 12); 
  static CFontDesc gNormalFontVeryBig ("Arial", 18);
```

**Comment by rghvdberg** [comment]
>...since he has not installed Arial

It was even weirder, I have installed Arial, and in a clean 16.04 vm , without Arial, I had no crash...
This patch solves it anyway and .. Arial on Linux makes no sense whatsoever ;-)

**Comment by KottV** [comment]
Hi. I struggling with run it on my openSUSE TW:
It's long lasting issue in vst(gui)
https://github.com/steinbergmedia/vst3sdk/issues/1
https://github.com/steinbergmedia/vstgui/issues/88


[bt.txt](https://github.com/surge-synthesizer/surge/files/2873673/bt.txt)

**Comment by baconpaul** [comment]
OK tell you what; I can apply @rghvdberg in surge super quickly. Let me do that tonight and then we can see if that works for you.

**Comment by KottV** [comment]
Hmm... I built rghvdberg branch and got same segfault. But changing "Microsoft Sans Serif" to "Ubuntu" in "surge/src/common/gui/CLFOGui.cpp" solves my issue for now.

**Comment by baconpaul** [comment]
Huh there's another "Microsoft Sans Serif" font in there? Wow we missed that one.

Hold on - I can patch it along with my branch.

**Comment by KottV** [comment]
SurgeGUIEditor.cpp too )

**Comment by baconpaul** [comment]
That one is fixed in master.

**Comment by baconpaul** [comment]
SurgeGUIEditor that is. That's the one we fixed a week ago.

**Comment by baconpaul** [comment]
OK I have a fix together that both patches vstgui and also CLFOGui. Let me just run it through the auto build after I force push and you should be good at master @KottV

**Comment by baconpaul** [comment]
OK this is all fine in master. If you git pull upstream etc... to reset your fork to master, and also make sure to git submodule again you should be good. If you are building at these refs you are fine:

The current refs at the correct master are:
```
git log | head -1
commit da9e3e97c50c0297f44c6ee311e10e2597469619
(cd vst3sdk; git log | head - 1)
commit 82380a8faa33824123104e005bcffb0451151d88
(cd vstgui.surge; git log | head -1)
commit 711772715fe66bbab4e02f9fad08c9bff3356d13
```

**Comment by KottV** [comment]
thanx, runs well

**Comment by baconpaul** [comment]
Awesome! Thanks for the clear report and fix.
