### ISSUE TITLE
Shouldn't versions of the XT variant be higher than previous versions?

### ISSUE THREAD

**Issue by yurivict** [surge-synthesizer/surge#6143]
Since the repository is shared, version auto-discovery systems discover 1.9.0 as new versions for XT.

Shouldn't the XT version be higher than previous versions, for example 2.0.0 ?

**Comment by baconpaul** [comment]
Hi!

XT starts a new version scheme starting at 1.0. We consciously chose not to call it 2.0 (and have plans for a 2.0, again with a distinct plugin id and product name) in the XT family.

I'm not sure what tags or semantics auto discovery schemes use, but we have distinct tag and branch prefixes for both products. 

Thanks
