### ISSUE TITLE
Alt + Shift + key command not working on Linux

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#6144]
On Linux systems Alt + Shift + K should open Keyboard, Alt + Shift + T opens Tuning Editor...
these key commands are no longer functioning

the break happens at commit **64de2258217ab449812268ee07c0350fa0eefac0** 

Author: Paul <baconpaul@users.noreply.github.com>
Date:   Sun Apr 17 18:39:59 2022 -0400

the prior commit **39ff66b31517a6d9456291088822555666d571c0** works OK

Author: Paul <baconpaul@users.noreply.github.com>
Date:   Sun Apr 17 14:47:16 2022 -0400

**Comment by baconpaul** [comment]
Thanks!

**Comment by baconpaul** [comment]
I think this is a bad bisect. At 39ff66b alt-shift-t also does not work.

**Comment by baconpaul** [comment]
The problem seems to be, at least on my linux box, that alt-shift-t sends a keycode of T but drops the alt modifier. Let me look at head and see if I can figure out a way to make just alt-T work without the shift.

**Comment by baconpaul** [comment]
OK so lets for a moment assume (1) ubnutnu and your distro are different and (2) your bisect was correct for you

That means you are getting an event which is alt-shift-t and the change you bisect would fail because shift isn't a modifier. I can fix that.

It still means it won't work for me on ubuntu where we drop the alt.

@tank-trax what would be really useful is: at head apply this diff

```
diff --git a/src/surge-xt/gui/SurgeGUIEditor.cpp b/src/surge-xt/gui/SurgeGUIEditor.cpp
index b28cee7a..82735d40 100644
--- a/src/surge-xt/gui/SurgeGUIEditor.cpp
+++ b/src/surge-xt/gui/SurgeGUIEditor.cpp
@@ -6720,6 +6720,12 @@ void SurgeGUIEditor::setupKeymapManager()
 
 bool SurgeGUIEditor::keyPressed(const juce::KeyPress &key, juce::Component *originatingComponent)
 {
+    {
+        auto &p = key;
+        std::cout << "A=" << p.getModifiers().isAltDown() << " S=" << p.getModifiers().isShiftDown()
+                  << " CM=" << p.getModifiers().isCommandDown()
+                  << " CT=" << p.getModifiers().isCtrlDown() << " KC=" << p.getKeyCode() << " TC=" << p.getTextCharacter() << std::endl;
+    }
     auto textChar = key.getTextCharacter();
     auto keyCode = key.getKeyCode();
```

and then let me know what you see on stdout when you press alt-shift-t. I get no alt, a shift, and a T.

**Comment by baconpaul** [comment]
@tank-trax  also can you try this patch (applied in libs/sst/sst-plugininfra)

```
diff --git a/include/sst/plugininfra/keybindings.h b/include/sst/plugininfra/keybindings.h
index 0453dd6..28887fc 100644
--- a/include/sst/plugininfra/keybindings.h
+++ b/include/sst/plugininfra/keybindings.h
@@ -107,7 +107,22 @@ template <typename FUNCS, int maxFunc, typename KEY /* = juce::KeyPress */> stru
             };
 
             if (!check(SHIFT, key.getModifiers().isShiftDown()))
+#if LINUX
+            {
+                if (modifier != SHIFT && type == KEYCODE)
+                {
+                    /* this could b e alinux user trying to upcase a key
+                     * and chording is odd. Lets see if this fixes it
+                     */
+                }
+                else
+                {
+                    return false;
+                }
+            }
+#else
                 return false;
+#endif
```

**Comment by tank-trax** [comment]
this fixed it

> cd libs/sst/sst-plugininfra
> git remote add bp https://github.com/baconpaul/sst-plugininfra
> git fetch bp
> git checkout bp/linux-chord
> git log   # (log showed e84b6514)
> cd ../../.. (one extra level up)

now...

Alt + Shift + K opens Keyboard
Alt + Shift + T opens Tuning Editor
Alt + Shift + M opens Mod Menu

**Comment by baconpaul** [comment]
Awesome I will merge that up and close this issue then! Thanks!

**Comment by tank-trax** [comment]
All 3 worked on Debian 11 w/KDE desktop _and_ Mint 20.3 w/Cinnamon desktop

**Comment by baconpaul** [comment]
OK great getting it all merged up now. Thanks for the testing and reporting!
Wonder what's wrong on ubuntu 20? maybe I should just upgrade to 22 :)

**Comment by tank-trax** [comment]
> Wonder what's wrong on ubuntu 20?

Which Desktop are you using?
