### ISSUE TITLE
Apple Silicon Logic Native: Key Focus Permanently Lost after Zooming

### ISSUE THREAD

**Issue by jcampbellcodes** [surge-synthesizer/surge#6154]
**Bug Description:**
When you resize the GUI in Logic (native M1 only), key presses no longer go to the plug, only to the DAW. This means for example you can no longer search presets using the Surge preset manager, and if you hit delete during this time, you may accidentally delete your tracks etc.

**Surge XT Version**
Version: Surge XT 1.0.1.60228e8
Build: 2022-01-31 @ 16:53:52 on 'Mac-1643647381380.local/pipeline' with 'AppleClang-12.0.0.12000032' using JUCE 6.1.2
System: macOS 64-bit AU on Apple M1
Host: Apple Logic @ 44.1 kHz

**Reproduction Steps:**
1. Open Surge in Logic M1
2. Try to enter text in the preset search bar; note that it works as expected
3. Use the Zoom option in the menu to resize the GUI
4. Try again to enter text in the preset search bar (or any other key shortcut). Note that no key presses make it to Surge, they all pass through straight to the DAW

**Expected Behavior:**
Key presses should go to the plug in focus; for instance if you have selected the preset search bar, you should be able to enter text in it.

**Workaround:**
Close and reopen GUI

**Computer Information (please complete the following!):**
System: macOS 64-bit AU on Apple M1
Host: Apple Logic 10.7.3 @ 44.1 kHz

**Comment by baconpaul** [comment]
So I can confirm this in 10.7.4 also on an M1.

I have absolutely no idea what to do about it

But I can confirm it.

Lemme try asking on the juce forums if nothing comes to mind.

**Comment by baconpaul** [comment]
Yeah OK so Surge XT AU in Reaper doesn't do this

and Pianoteq AU in Logic does the exact same thing (rezoom and  key focus is lost)

This is almost definitely a logic bug in their window reparenting on M1. I have no idea how to report that to apple but I can ask the juce team if maybe they know.

I don't think there's a surge fix to be done here. Will keep this open to track the conversations which may arise though.
