### ISSUE TITLE
unknown target 'surge-headless'

### ISSUE THREAD

**Issue by jvrignon** [surge-synthesizer/surge#6155]
Hello
following README.md I try to Cross-compiling for aarch64
with following command
```
cmake -Bignore/xc64 -DCMAKE_TOOLCHAIN_FILE=cmake/linux-aarch64-ubuntu-crosscompile-toolchain.cmake -DCMAKE_BUILD_TYPE=DEBUG -GNinja
cmake --build ignore/xc64 --config Debug --target surge-headless
```
but ninja tells me "ninja: error: unknown target 'surge-headless'"

is surge-headless still an available target on the main branch of surge ?

My final goal being to build an headless version to make surge work in a Debian 10 box without UI, just controlled through MIDI
Also wonder if "surge-headless" could be used this way

Thanks for your help

**Comment by jvrignon** [comment]
Thanks for your tip, cmake work better now
any clue if this test-runner would be suitable for running Surge without UI ? or is there another way recommended to do so ?

**Comment by baconpaul** [comment]
The test runner runs a few thousand instances of surge without a ui. But it really depends on what you mean “run without a ui”. If you mean like listen for Jack midi and output Jack audio in a small application, the test runner would show you how to write that c++ code from the surge side but doesn’t do it.

so what do you mean run without a ui? Like what’s the exact deployment you want thst isn’t available through hosting today?

**Comment by jvrignon** [comment]
Hi @baconpaul
Thanks for the info
here's what I mean by "run whithout ui"
use case is to start surge in a box that does not have a screen nor mouse keyboard while using it on stage. The box still has midi and audio capabilities, and is connected to a midi keyboard controller. Thus I could use surge live and play with it like with my hardware synth, with access through the midi controller to sub part of the surge control (it could sound like under using surge, but hardware synth do not have has much control than surge provides anyway)
I have two options for the box, an RPI3, which I believe is too small to host surge, and an home made debian 10 based AMD noiseless box packed in a 1U rack (where surge compile like a charm allready)
on this last one there is typically only a power button while on stage, starting everything using linux service
so that's where I'd like to run "surge whitout ui" (start and audio-midi routing with my linux service, or using surge config file not sure yet, then get ready to play with the controller)

I saw the "headless / surge-testrunner" target in the README.md, and I though it could be an entry point, and has you suggest the c++ code looks pretty informative on how to do what I want

And being pretty new to surge code, I'm not sure if an available surge deployment already matches my plan, do not hesitate to tell me if so.

**Comment by mkruselj** [comment]
You should still be able to run Surge standalone executable. Yes it has a GUI but if no display is connected it should still work quite alright. You set your MIDI input(s) and audio output (and/or input if you want to use that aspect of Surge as well), then forget about it.

**Comment by baconpaul** [comment]
yeah exactly. just dump the standalone to an xvfb or some such even and it will work would be easiest.

you could also do something like run it as a plugin in one of the super-minimal hosts. I think carla has a completely headless mode.

Or you could really quite easily just write a little standalone executable which bound to rtaudio and rtmidi in C++ that called surge if that works too. If you did that would be happy to host it in the source tree and stuff.

**Comment by jvrignon** [comment]
OK, thanks for all your suggestion
I'll do some test and try and let you know if eventually I could contribute
Thanks for your work on surge, this synth rocks a lot :)

**Comment by baconpaul** [comment]
Hmm the login is required for an x session or something else?

**Comment by jvrignon** [comment]
I guess it is for the X session, has some DISPLAY is required for the UI
without session, surge crash with "segmentation fault"
but lightdm autologin + ~/.config/autostart/surge.desktop
[Desktop Entry]
Type=Application
Name=Surge
Exec=/usr/bin/surge
StartupNotify=false
Terminal=false

works fine so far, but 33 sec to get sounds out of the system after pressing the power on button, still a bit long

**Comment by mkruselj** [comment]
> but 33 sec to get sounds out of the system after pressing the power on button, still a bit long 

Korg Kronos boots for like 2 minutes. 😛

**Comment by baconpaul** [comment]
you can probably save a lot of time with a virtual X buffer rather than full blown desktop

but optimizing for boot up time is gonna be hard. The PI takes 20 seconds to boot to a prompt right through raspbian for me.

**Comment by jvrignon** [comment]
Thanks for the tip @baconpaul , and you're right, most of boot time is debian, xfce login and surge taking about 1s. I gain a bit of time by setting bios boot to fast, and in comparison as @mkruselj reminds me, hardware synth takes significant time to boot actually, even my recent Minologue XD takes 25s to start and tune, nevermind
and FYI I'm using mididings as a "smart midi patch bay", enabling to switch between scene, i.e. either "Minilogue + X Touch Midi" controling Minilogue, or controling Surge, with mididings even converting CC in NRPN or Sysex for Minilogue, really cool tool too

**Comment by baconpaul** [comment]
awesome. So do you have it working? Cool!

**Comment by jvrignon** [comment]
Hi @baconpaul  Yep have it working :)
Looks like that
![XD_Synth drawio](https://user-images.githubusercontent.com/91246238/168256963-4326f3c8-1803-413b-8639-4f5ae0bbe01f.png)
debian box fitting nicely under the minilogue, and mididings used to switch controls between Minilogue, Surge, or Linux Sampler, all started at boot up in about 30s
Still while I use Surge Midi Mapping to maps minilogue CC on Surge, I didn't find yet how to control some parameters of surge, like octave or wave form, while having nice button to do so on the minilogue, do happen to you know if they are supposed to be controllable with midi too and how I can maybe ?

**Comment by baconpaul** [comment]
That's great! Right now we don't have midi control of discrete parameters, just continuous ones. I guess we could add it! We similarly don't have great patch selection control as I'm sure you've discovered. All things where dev could help.
