### ISSUE TITLE
Twist: Analog Kick malfunctions?

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#6162]
Here it is:

Use Twist Oscillator in Analog Kick mode.

With LPG disabled the "variations" are tuned to different notes, sounding very odd to my ears. (Intended?)

With LPG enabled the variations work better together, but now there's an occasional ugly click at the onset of the kick sound. 
A spiky shape is also shown in the oscillator waveform window, appearing and dissapearing sporadically when parameters are moved. The shape seems like it'd cause the sound I'm hearing, but the picture and the sound both occur at random independently. 

This video shows what that looks and sounds like:
https://user-images.githubusercontent.com/105538426/168416703-b0e18be9-7e0e-43e2-bc7a-3eb67573ba49.mp4

In related news, I'm wondering if the Twist LPG is working as intended. Like, across the Twist engines? For me, enabling/disabling it always changes the sound of the engine in a pretty reasonable way, but for most of them the sliders don't really seem to do anything. Maybe a topic for a separate issue but I figure it might be related, since the glitchy clicks don't occur with LPG disabled.

Version: Surge XT 1.1.nightly.2e48c9d
Build: 2022-05-10 @ 20:14:52 on 'Mac-1652213335737.local/pipeline' with 'AppleClang-12.0.0.12000032' using JUCE 6.1.6
System: macOS 64-bit VST3 on Apple M1
Host: Reaper @ 48.0 kH

**Comment by mkruselj** [comment]
> With LPG disabled the "variations" are tuned to different notes, sounding very odd to my ears. (Intended?)

This is by design, at least. There are two kick flavors there, and Variation Mix slider crossfades between them.

**Comment by baconpaul** [comment]
Ahh I see the problem I think.

Inside the twist implementation is this code

```
    // Delay trigger by 1ms to deal with sequencers or MIDI interfaces whose
    // CV out lags behind the GATE out.
    trigger_delay_.Write(modulations.trigger);
    float trigger_value = trigger_delay_.Read(kTriggerDelay);
```

but we aren't in that situation. If I make trigger_value = modulations.trigger the noise seems to vanish.

gotta think about exactly how i want to patch that in.

**Comment by baconpaul** [comment]
yeah ok got it. next nightly should have this fixed. it's a bit hard to repro but i could get it 1 time in 10 without my patch and never in a couple of hundred notes and drags with it applied.
