### ISSUE TITLE
Action History list or overlay

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#6175]
![image](https://user-images.githubusercontent.com/2393720/168830818-009c8d86-f10c-4de1-af73-4acec2489595.png)

This was the initial idea - so that we can list all actions that were executed and jump to any particular one directly, rather than sequentially.

Overlay is not needed for MVP, but being able to show the last x undo steps could be nice and useful.

**Comment by baconpaul** [comment]
Just pushed a #6176 which shows how this code works (but tagged the issue incorrectly in the comment)

Basically

1: UndoManagerImpl::toString() - pretty clear
2; SGEVC you can see where we construct the menus and their action - also pretty clear
