### ISSUE TITLE
Instrument preset changing on its own

### ISSUE THREAD

**Issue by Zombee0804** [surge-synthesizer/surge#6193]
**Bug Description:**
Recently, Surge started changing instrument preset on its own. After recording with one preset, as soon as the track starts playing it changes to 'FM Bass 2'. This happens no matter what instrument I record with, however, it always changes to 'FM Bass 2'. I have uninstalled and reinstalled Surge multiple times

**Surge XT Version**
Version: Surge XT 1.0.1.60228e8
Build: 2022-01-31 @ 16:53:06 on 'fv-az172-31/pipeline' with 'MSVC-19.29.30139.0' using JUCE 6.1.2
System: Windows 64-bit VST3 on Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Host: Tracktion Waveform @ 48.0 kHz

**Reproduction Steps:**
Steps to reproduce the behaviour:
1. Select an instrument in Surge
2. Record a MIDI clip
3. Start playback
4. Once the MIDI clip starts playing, the error occurs

**Expected Behavior:**
The instrument preset should not change

**Screenshots:**
https://user-images.githubusercontent.com/79462745/169605088-ddc0ad93-6a6f-4d99-9132-4722025e63f8.mov
As shown in the screen recording above, I choose the instrument preset 'Cell' and record a MIDI clip with it. As soon as its starts playing, the preset changes

**Computer Information (please complete the following!):**
 - OS: Windows 10
 - Host: Waveform Free
 - Version: 11.5.18

**Comment by baconpaul** [comment]
I found a bug which in some cases where the daw has an unexpected start order this could occur and fixed it a few days ago. Can I ask two questions

1 is fm bass 2 tour default preset? If you open a new surge is it the one it goes to? And

2 if you grab the surge nightly (which is a few weeks away from being called the 1.1 beta) from https://surge-synthesizer.github.io/nightly_XT does it resolve?

**Comment by baconpaul** [comment]
Thank you! 

If the nightly fixes it it is the same problem (which it sounds like) and if not then I have a longer list of questions. Which I will think of if I find out the nightly doesn’t fix it :)

appreciate the report.

**Comment by Zombee0804** [comment]
The nightly did not fix the issue. It also didn't change it any way, it is still the same preset and occurs under the same conditions

**Comment by baconpaul** [comment]
Ok. And just to be sure there’s not a program change message in your midi clip is there? Can your u export the midi from one of the tracks and also do you mind sharing the traction project.?

I will think about what it could be. Puzzling. 

Thank you for trying the nightly. It means it is “something else” so. Have to think a bit.

**Comment by Zombee0804** [comment]
I am happy to send the project, however, it happens with any project, even a completely new one. The project is attached below
[surgeTest.zip](https://github.com/surge-synthesizer/surge/files/8747516/surgeTest.zip)

**Comment by mkruselj** [comment]
We don't respond to program change for VST3 though...

**Comment by baconpaul** [comment]
That’s not quite true. We don’t support the nutso vst3 patch shenanigans but if you send the 3 bytes which are a midi program change then something will happen. https://github.com/surge-synthesizer/surge/blob/5ad5e49fc4209e2156c5033d3f2e220e45fdc8af/src/surge-xt/SurgeSynthProcessor.cpp#L690

**Comment by baconpaul** [comment]
So one theory is: is there something in the midi rig sending those bytes. I don’t quite know how to figure that out and am not quite sure what would happen if it did

**Comment by baconpaul** [comment]
One thing I could do is make a custom build which turns that off or pops an alert if it happens and share it via Dropbox or what not but then I need to get my windows box running again.

**Comment by mkruselj** [comment]
> That’s not quite true. We don’t support the nutso vst3 patch shenanigans but if you send the 3 bytes which are a midi program change then something will happen.
> 
> https://github.com/surge-synthesizer/surge/blob/5ad5e49fc4209e2156c5033d3f2e220e45fdc8af/src/surge-xt/SurgeSynthProcessor.cpp#L690

Hmmm OK that doesn't work here in Reaper at all as far as I can tell.

**Comment by Zombee0804** [comment]
Ah. The settings for my Virtual MIDI device (my laptop keyboard) had a program selected. Turning this off fixed the problem. I never really knew what this setting did, as it does nothing with most of the other plugins I use, so I didn't think to check it. Apologies. Thanks for all your help

![surge_virtualProgram](https://user-images.githubusercontent.com/79462745/169654594-c2d79278-9454-4026-b643-5ac6bd91eb6b.png)

**Comment by baconpaul** [comment]
ahh yes that's it then. Let me close this issue. Thanks for the quick response!

**Comment by baconpaul** [comment]
> > That’s not quite true. We don’t support the nutso vst3 patch shenanigans but if you send the 3 bytes which are a midi program change then something will happen.
> > https://github.com/surge-synthesizer/surge/blob/5ad5e49fc4209e2156c5033d3f2e220e45fdc8af/src/surge-xt/SurgeSynthProcessor.cpp#L690
> 
> Hmmm OK that doesn't work here in Reaper at all as far as I can tell.

In the most lawyerly fashion possible, I will remind you that when I said "something will happen" that does include the possibility of nothing happening, since nothing happening is itself an event. :)

It is flaky and very daw dependent but the bits on a midi stream can do something indeed in some daws.

**Comment by mkruselj** [comment]
Eheheh. Lawyerly indeed. 😛
