### ISSUE TITLE
Shift+F10 on hover things that don't work

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#6244]
With the new option to Shift+F10 open context menu when hovering above stuff:

- [x] LFO Hover (really: implementation of isCurrentlyHovered) is wrong
     - For MSEG editor (and actually any other overlay too!), Shift+F10 only ever shows the LFO Type context menu, instead of relevant context menu of whatever widget we're hovering above
  - Same happens when Shift+F10ing over the LFO display when in MSEG or Formula mode. Instead of showing context menu tied to those modes, it shows LFO Type context menu

**Comment by baconpaul** [comment]
Each of these widgets needs to implement the method is currently hovered correctly 

i thought there was a bass class but there isn’t 

but look at that method on the modulatable slider and implement it on each of these classes and it will work.

**Comment by mkruselj** [comment]
- [ ] For Alias additive editor, Shift+F10 opens the context menu way way over at the bottom of the GUI
- [ ] For WT prev-next buttons, Shift+F10 opens the wavetable info menu (as if you had RMBd on the waveform display itself), instead of showing the whole populated WT menu, which is what happens with RMB

**Comment by baconpaul** [comment]
The last two are because the LFO display doesn't unhover properly so it reports isCurrentlyHovered as true and my component search finds it before the mseg controls.

**Comment by mkruselj** [comment]
Got second one out of those 4 (or 3, if you will)!

**Comment by ultrasound1372** [comment]
Does using the keyboard focus with a screen reader to tab to it count as hovering in this case? I've noticed that I can't seem to get the MSEG/seq/formula menus in particular easily. I think I managed to fudge the step one by doing shift+f10 on the step sliders...

**Comment by mkruselj** [comment]
Yes by default it will use keyboard focus.
