### ISSUE TITLE
Wavetable name not remembered after just switching to WT/Window osc type

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#6248]
1. Open standalone
2. Set Osc 1 to Wavetable or Window
3. Close standalone
4. Reopen standalone

Instead of Sine, wavetable name will say (Patch Wavetable). It seems the name sticks only if you literally choose it through the menu or via arrows.

**Comment by baconpaul** [comment]
wow i thought i knew what this one was but i can't find it tonight

I thought wavetable_display_name was being set wrong, but instead it is being blanked somewhere and i can't see where.

**Comment by mkruselj** [comment]
@baconpaul It seems L131 in SurgePatch.cpp seems to be the culprit?

**Comment by mkruselj** [comment]
Nope, it's not. xD

**Comment by mkruselj** [comment]
Oh but L1907 in SurgePatch.cpp is!

**Comment by baconpaul** [comment]
ugh ok i see why this is happening. harumph.

**Comment by baconpaul** [comment]
and it will only happen on osc1
