### ISSUE TITLE
Missing icon in gnome-software / flatpak

### ISSUE THREAD

**Issue by abique** [surge-synthesizer/surge#6255]
This issue is about the flatpak distribution of Surge and Surge XT.

As you can see in the screenshot below, there is no icon for surge.
![image](https://user-images.githubusercontent.com/31200/172365556-de338866-1dba-4071-82ac-6097db14fff5.png)

Maybe this link will provide useful info: https://docs.flatpak.org/en/latest/conventions.html#application-icons

I'm using gnome-software 42.2-1.
I'm using flatpak 1.12.7.

Cheers!
Alex

**Comment by abique** [comment]
I suspect that adding the icon, will make it visible here too: https://flathub.org/apps/search/surge
In my opinion it would not be shocking if an app store requires an app/plugin to have an icon in order to be shown to the user.

**Comment by baconpaul** [comment]
I still am not entire sure how surge shows up in flatpak! We have an icon in our repo which you could use but i'm not sure what else to connect?

**Comment by abique** [comment]
For Bitwig we provide an icon that has the name `com.bitwig.BitwigStudio.svg` I think.
https://github.com/flathub/com.bitwig.BitwigStudio/blob/master/com.bitwig.BitwigStudio.yaml

**Comment by abique** [comment]
I think that this file, ideally should be maintained within surge repo: https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.Surge-XT/blob/branch/21.08/org.freedesktop.LinuxAudio.Plugins.Surge-XT.metainfo.xml

**Comment by abique** [comment]
Yeah we put the icon in: `share/icons/hicolor/scalable/apps/com.bitwig.BitwigStudio.svg`

**Comment by abique** [comment]
Maybe try to install the icon here: https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.Surge-XT/blob/branch/21.08/org.freedesktop.LinuxAudio.Plugins.Surge-XT.json#L104
`cp xxx.svg $FLATPAK_DEST/share/icons/hicolor/scalable/apps/org.freedesktop.LinuxAudio.Plugins.Surge-XT.svg` maybe that will do it.

**Comment by abique** [comment]
@hfiguiere would you have time to help us get the icon working for surge? Thank you very much :-)

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/blob/main/resources/surge-xt/SurgeLogo.png

the logo is in the repo as a PNG. Our .deb file installs that. but yeah I don't know how to change or update or really even generally do anything with flatpak I'm sorry :( Would love some help!

**Comment by abique** [comment]
I've made a PR, maybe that fixes it: https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.Surge-XT/pull/2

**Comment by abique** [comment]
Is it the same icon for both surge and surge xt?

**Comment by mkruselj** [comment]
I think it was, yeah.

**Comment by abique** [comment]
So this PR places the icon in the right place and with the correct name, but now we need someone to merge it.
https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.Surge-XT/pull/2

Also it seems that in generals flatpak isn't ready for showing icons for plugins.

**Comment by abique** [comment]
I've created a ticket so @baconpaul can have push right: https://github.com/flathub/flathub/issues/3241

**Comment by abique** [comment]
If anyone else from your team should have it, better to follow up there :-)

**Comment by hfiguiere** [comment]
With https://github.com/flathub/flathub/pull/3286 there will be the standalone version of surge XT, and the plugins will be visible next to it. This is I think the best we can do with the existing infrastructure.

**Comment by hfiguiere** [comment]
This is how it looks
![image](https://user-images.githubusercontent.com/114441/175782367-19f8e82a-a9e4-49c1-8721-84e6f1c2b9a1.png)

**Comment by mkruselj** [comment]
OK, that sounds like we can close this issue, then? 🙂

**Comment by abique** [comment]
Will there be a single package that provides both the plugin and the standalone app?

**Comment by hfiguiere** [comment]
no. Just a single source.
