### ISSUE TITLE
Switching to latched patch plays old data

### ISSUE THREAD

**Issue by haenkel** [surge-synthesizer/surge#6265]
Switching from a non-latched-saw to a latched-noise patch
plays latched saw until keypress or parameter change.

Or try: Select "Init Emu" and click one patch back  (to "Audio In  ...") 

First occurence is #6231

**Comment by baconpaul** [comment]
Oooh super solid bisecting. Thanks @haenkel

**Comment by baconpaul** [comment]
Yeah the problem here is we now allow modulatable integers, so the special case of launching a latch voice needs to apply internal modulations before launching latch. We had it out of order. Lovely find!
