### ISSUE TITLE
Resizability for the FX plugin

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#6267]
Let's see if this is feasible in time for 1.1. Here's a list of things to do:

- [x] Hide the JUCE triangle in the corner just like we do for Surge XT
- [x] Implement aspect ratio constrainer, with minimum zoom level (75% of the current default size?)
- [x] Add zoom options to the menu
- [x] Make zoom options actually work
- [x] Saving and loading the set zoom level to user prefs
- [x] Use the same keyboard shortcuts that Surge XT does by default

**Comment by baconpaul** [comment]
@mkruselj I'm debating keeping this code in place but toggling the default back to (false, false) for 1.1.0 and making this a 1.1.n - your comments or thoughts?

**Comment by mkruselj** [comment]
Hmm, any specific reason for doing that? It seemed to work just fine (including saving default zoom level) when I tested it, so it seems production ready (minus kbd shortcuts). We can leave kbd shortcuts for 1.1.n but to me it looks good to ship, unless you have an objection. Either way we go is fine with me tho.

**Comment by baconpaul** [comment]
Oh OK I was waiting for feedback from you which I thought would be a bunch of 'i hate it in this way or that way'

if you are happy with current and just want keyboard shortcuts I'll get this one closed today :)

**Comment by mkruselj** [comment]
<homer>WOOHOO!</homer>
