### ISSUE TITLE
Portamento and ADR envelope times show 0.0 s minimum, but don't accept such typeins

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#6278]
As per subject line. It's because minimum value of these params is actually non-zero, but we special-case the value displays.

**Comment by baconpaul** [comment]
I think I fixed this in #6334 but if i missed any, i do want to fix them. So just dropping that comment here.

**Comment by baconpaul** [comment]
ahh right because they use a different (but similar) path. OK it's easy to fix up now - I know where the point is.
