### ISSUE TITLE
Minimum Zoom on Linux below 100%

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#628]
Minimum zoom on Linux is 100%. This issue explains why in case someone wants to fix it in the future.

**Comment by baconpaul** [comment]
So here's how far I got.

When zoomed <100% the menu, which draws in lib/platform/common/genericoptionmenu.cpp has ::drawRect called with a clip which is smaller than the size. With zoom >100% the clip and the size are the same. Tracing up the stack this comes from the cviewcontainer ::drawRect which has the clip at the top.

This means the container of the cviewcontainer - which is the frame - must be doing a repaint mis-calculating the intersection of the invalidation rectangle and the clip rectangle. Probably the clip rectangle is getting transformed the wrong wan in cframe::drawRect but I can't for the life of me find it.

So leaving these notes here for the next brave soul, and not working on this any more. Rather setting us to 100% as a floor.

**Comment by mkruselj** [comment]
AFAIK @selenologist confirmed that Surge now shows just fine on Linux below 100% if the guard is removed from SurgeGUIEditor. We should then, I suppose, officially remove that guard and close this issue. 🙂

**Comment by mynameismuhl** [comment]
I can confirm, via Zoom-menu you can shrink it down to thumbnail size on Linux remaining correct borders and shape.
You can also make the UI disappear if you shrink once too often, hide/unhide in Reaper 
then makes it jump back to 100% which is cool.
corner-drag-resize doesn't work but i guess that's known.

**Comment by baconpaul** [comment]
Yeah the guard is gone!
Thinking if it: we probably want the guard to be floored at 25%.
I'll add that and close this
