### ISSUE TITLE
Can't left click - several places in Cubase 

### ISSUE THREAD

**Issue by TorbjornHedberg** [surge-synthesizer/surge#6284]
**Bug Description:**
So here are a few more places where left click doesn't work in Cubase 12. All work in stand-alone. 
* Digital / Analog filter switch 
* Filter 2 offset mode
* Osc solo (this is the worst because there is no other way to solo) 

**Surge XT Version**
Version: Surge XT 1.1.nightly.190ad75
Build: 2022-06-10 @ 23:11:04 on 'WIN-OKUI4NKA6QD/pipeline' with 'MSVC-19.29.30145.0' using JUCE 6.1.6
System: Windows 64-bit VST3 on AMD Ryzen 9 3900X 12-Core Processor            
Host: Steinberg Cubase @ 48.0 kHz

**Computer Information (please complete the following!):**
 - OS: Windows 11
 - Host: Cubase 12

**Comment by baconpaul** [comment]
Yeah this will be the same problem as the one I found last week I bet. I can get to it this week sometime but def for 1.1

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/commit/66cfdde3a74f5d304069709ea4b5a1735abd2994

**Comment by baconpaul** [comment]
Anyway this should all be fixed in a nightly later tonight. Give us a few hours - after 6pm eastern on sunday - busy pipelines today.
