### ISSUE TITLE
Find patch doesn't show selected row when clicking

### ISSUE THREAD

**Issue by TorbjornHedberg** [surge-synthesizer/surge#6285]
**Bug Description:**
The find patch function is very much better - thanks a lot!

But. 
When left clicking on a row the patch loads fine. But the corresponding row isn't selected in the drop down menu. This means that if you subsequently try to move with the up/down keys the menu hops back to whichever row happens to be selected. If the result list is long, this gets a bit confusing. 

Also (should maybe be a separate report?):
There is no logical way to close the menu with the mouse. 

**Surge XT Version**
Version: Surge XT 1.1.nightly.190ad75
Build: 2022-06-10 @ 23:11:04 on 'WIN-OKUI4NKA6QD/pipeline' with 'MSVC-19.29.30145.0' using JUCE 6.1.6
System: Windows 64-bit VST3 on AMD Ryzen 9 3900X 12-Core Processor            
Host: Steinberg Cubase @ 48.0 kHz

**Computer Information (please complete the following!):**
 - OS: Windows 11
 - Host: Cubase 12

**Comment by baconpaul** [comment]
Yeah it used to close on select so the lack of highlight was fine. But now it stays open and that gives us new sharp edges, sepscislly when crossed with the screen reader stuff we are still working through with thst control 

appreciate the report 

Oh can’t you click the magnifier again to close it though?

**Comment by mkruselj** [comment]
Pressing Ctrl+Enter or double clicking the row will load the patch and close the list.

**Comment by baconpaul** [comment]
oooh have you tested that doubleclicking since the click broke? I'm not sure I coded that behavior. (If it is broken just add a mouseDoubleClick next to the mosueDown I added in the accessible row renderer)

**Comment by mkruselj** [comment]
Oh actually I haven't tried it. Ha.

**Comment by TorbjornHedberg** [comment]
Nope. Doubleclick doesn't close the search list, neither in Cubase nor in standalone here on Windows. 

Two single clicks on the search icon closes it, though.
