### ISSUE TITLE
CLAP plugin not found within default install

### ISSUE THREAD

**Issue by mobiuscog** [surge-synthesizer/surge#6291]
**Bug Description:**
Windows CLAP plugin not found within Bitwig 4.3 Beta 7

**Surge XT Version**
This information is found on the About screen, which you get to from the bottom right menu.

* Version: 1.1 Nightly
* Plugin Type: CLAP
* Bitness: 64-bit

**Reproduction Steps:**
Install the plugin using the MSI installer and install both VST and CLAP
Launch Bitwig and after scanning, note the CLAP plugin is not available.

**Expected Behavior:**
The CLAP plugin to be available.

**Computer Information (please complete the following!):**
 - OS: Windows 11
 - Host: Bitwig
 - Version: 4.3 Beta 7

**Additional Information:**
This seems to be due to the install location creating folders ending in .clap
`C:\Program Files\Common Files\CLAP\Surge Synth Team\Surge XT.clap\Surge XT.clap`
If the outer folder is renamed to have .clap removed, the plugin is correctly found.

**Comment by mkruselj** [comment]
Paging @mthierman on this one!

**Comment by baconpaul** [comment]
Oh thank you for the report also!

**Comment by baconpaul** [comment]
Oh shoot @mkruselj this line just has a .clap on the dir

https://github.com/surge-synthesizer/surge/blob/946a890a4d1f87811263e3f9e19e9239e9bcf900/scripts/installer_win/surge64.iss#L100

I don’t have windows here. Are you around to try a fix to that?

**Comment by baconpaul** [comment]
It’s copied from the vst3 which is a dir whereas the clap is a file so should look like the exe
