### ISSUE TITLE
Moving an Airwindow FX instance by drag-and-dropping it in the unit selector doesn't keep its settings

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#6300]
Happens consistently, and confirmed by EvilDragon.

**Comment by baconpaul** [comment]
So this is ugly

when you drag and drop an airwindo setupFX gets called three times

first by process correctly with the FX type and everything is fine
Then a second time with fx type 0
and a third time with the correct fx type

but that second time screws you up

When you just *Create* or *type swap* an air win no such thing happens

so some sort of nasty in fx lifecycle with int params and the creation sequence on drag going wrong here. Hard.
