### ISSUE TITLE
Contextualized help when pressing F1 and hovering over something

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#6309]
It would be cool if the F1 keyboard shortcut to open the manual would be contextualized, meaning if you hover your mouse over a control and press F1, it would open the manual at the right section to read about that control, as if you used its context-menu option instead.

Not sure how easy or hard this would be to implement so I'm not going to put any milestone on it, but feel free to do so!

**Comment by baconpaul** [comment]
Oh this is quite easy I think. What a good idea

**Comment by baconpaul** [comment]
Basically in the f1 handler 
Can you dyncast to an ICompondntvakue
And if so is your tag above start paramtabs
And if so look up help by param
Otherwise just open the manual

**Comment by mkruselj** [comment]
What a sick idea!

**Comment by baconpaul** [comment]
The keyboard focus will be defaulted yes, but mouse focus option - that's a good idea and when we hack it in, we should make sure it does.
