### ISSUE TITLE
Rename surge python output target

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6311]
There is another issue. After renaming, the compiled product is surge-python...so, which cannot be imported in python.

```python
import surge-python
            ^
SyntaxError: invalid syntax
```

The - in filename must be deleted manually to import in python.

**Comment by baconpaul** [comment]
per convo with [reekystive](https://github.com/reekystive) in #3448

**Comment by baconpaul** [comment]
@reekystive fyi

**Comment by baconpaul** [comment]
I think the solution here is as simple as

1. Change the `project` tag in CMakeLists.txt in surge-python and
2. Update the readme and the azure pipelines file

**Comment by reekystive** [comment]
That's right! I tried it. I opened a PR #6313.
