### ISSUE TITLE
Spring reverb compiler error

### ISSUE THREAD

**Issue by TomCoalfish** [surge-synthesizer/surge#6318]
error: no matching function for call to ?chowdsp::SchroederAllpass<juce::dsp::SIMDRegister<float>, 2>::setParams(float, __m128)?
         apf.setParams(msToSamples(0.35f + 3.0f * params.size), _mm_load_ps(apfGVec));

**Comment by mkruselj** [comment]
Which compiler?

**Comment by TomCoalfish** [comment]
Ok, I had it set to gcc8, I will try it with 9

**Comment by TomCoalfish** [comment]
It was completely my fault I use some little script to run cmake and use all kinds of optimizations specifically for my machine which do not work with this.
