### ISSUE TITLE
How to use Surge as a library

### ISSUE THREAD

**Issue by TomCoalfish** [surge-synthesizer/surge#6324]
I am experimenting but haven't connected the code yet
Surge builds a few libraries : surge-xt, surge-fx
I am going to try and link to them and see if I can use the library with the headers

I can already use sst-waveshapers and sst-filters like that, but there is alot of cool things in surge

**Comment by baconpaul** [comment]
The cmake target surge common is the one you want, surge xt surge fx surgery and surge test runner all depend on that, each of those projects is a good example of using surge as a Library, actually

**Comment by baconpaul** [comment]
@TomCoalfish I'm going to close this issue but happy to reopen it if you have further questions; Also happy for you to hop in our discord which may be better for realtime stuff if you are a discord user.
