### ISSUE TITLE
SQL database bug

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#6326]
From j5v:

I have a single quote in the patch name. It saves but then if I hit the search, it immediately shows the attached error. I guess the query isn't parameterized, and is instead string-built without escaping SQL delimiters. The workaround is to accept the error and then save with a name that doesn't break the SQL syntax.

![image](https://user-images.githubusercontent.com/2393720/177109608-4ea30775-ae6d-4bc0-97ef-f0079a798ac4.png)

**Comment by aaylward** [comment]
Is this due to https://github.com/surge-synthesizer/surge/blob/main/src/common/PatchDB.cpp#L1376 used at https://github.com/surge-synthesizer/surge/blob/main/src/common/PatchDB.cpp#L1407 ?

**Comment by baconpaul** [comment]
Almost definitely yes.

**Comment by baconpaul** [comment]
Anyway PR #6335 will fix this!
