### ISSUE TITLE
Win x64 installer error for the CLAP

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#6328]
**Bug Description:**
The attached error displays when running the Win x64 installer. Latest nightly.

**Surge XT Version**
Surge XT NIGHTLY-2022-07-04-da4b83c
(standalone)

**Reproduction Steps:**
Install over an existing nightly (about 3 weeks old).

**Expected Behavior:**

**Screenshots:**
![image](https://user-images.githubusercontent.com/13245475/177218162-7c815ddf-dd73-4e18-80b1-48db94f0be83.png)

**Computer Information (please complete the following!):**
Windows 10

**Additional Information:**

**Comment by j5v** [comment]
![image](https://user-images.githubusercontent.com/13245475/177218275-925d854c-26b0-4a84-95be-72d0f596f7b7.png)
(original image broke for some reason)

**Comment by mkruselj** [comment]
I don't think we should bother with this since it's a nightly only issue. Great majority of users is gonna be A-OK.

**Comment by baconpaul** [comment]
Right but to fix it those users should blow away that clap directory before installing 

@j5v this was a bug in literally 7 nightlies hence the suspected low impact surface
