### ISSUE TITLE
Press Space or Enter with any popup menu open -> exit

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#6329]
**Bug Description:**
Crash to desktop (hosted or standalone), if I press Enter or Space with the RMB context menu open for a parameter.

**Surge XT Version**
Version: Surge XT 1.1.nightly.da4b83c
Build: 2022-07-04 @ 16:11:24 on 'fv-az239-965/pipeline' with 'MSVC-19.29.30145.0' using JUCE 6.1.6
System: Windows 64-bit Standalone on Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Sample Rate: 48.0 kHz

**Reproduction Steps:**
1. Right-click on any parameter
2. Press Space or Enter.

**Expected Behavior:**
(nothing)

**Screenshots:**
n/a

**Comment by haenkel** [comment]
It seems to be the nullptr check here:
https://github.com/surge-synthesizer/JUCE/blob/379b0c6229ab5ad998091b20333a6c3faf481aea/modules/juce_gui_basics/menus/juce_PopupMenu.cpp#L675
`if (currentChild && currentChild->item.customComponent != nullptr)` instead?

**Comment by baconpaul** [comment]
100% - great find
