### ISSUE TITLE
Pressing Tab while in Store-preset-mode no longer does tab in the dialog, instead toggles modulation binding on/off

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#633]
here's me pressing Tab while in the Store preset dialog window. tab doesn't actually happen, cos something else grabs it first.

![presstab](https://user-images.githubusercontent.com/4966687/53096371-ad5c1300-3527-11e9-9fdc-9debdf7da229.gif)

**Comment by baconpaul** [comment]
Oh! The tab for binding was in the code and broken. I fixed it (since it is super useful) but yeah this will break the store dialog. I'll remove the tab and add another modulation

**Comment by baconpaul** [comment]
modulation keybinding
