### ISSUE TITLE
Bad display of EG curves in macos Monterey

### ISSUE THREAD

**Issue by hellerdejanuar** [surge-synthesizer/surge#6330]
**Bug Description:**
the Filter EG and amp EG load distorted (like cropped up) in Macos Monterey.
The bug is persistent from the last stable release (1.0.1) through this nightly.
surge XT 0.9 worked just fine.

**Surge XT Version**
surge xt 1.1.nightly.da4b83c

* Version:
* Plugin Type: [App, Vst3]
* Bitness: [64-bit]

**Reproduction Steps:**
It works fine with classic and dark skins, also with the new updated Royal skin.
It bugs when using old custom skins like the Funtime, Royal (the previous version),

**Computer Information (please complete the following!):**
 - OS: [Macos]
 - Host: [App, Ableton Live]
 - Version: [12.4]
<img width="457" alt="Screen Shot 2022-07-05 at 12 28 34" src="https://user-images.githubusercontent.com/73609560/177363728-51fde85c-2f6b-472c-a75e-d30f7fb090b2.png">

**Additional Information:**

**Comment by baconpaul** [comment]
Could you share a screen shot perhaps? And also let us know which skin?

Thank you!

**Comment by hellerdejanuar** [comment]
I updated the post, paul!. thank you

**Comment by mkruselj** [comment]
You're using an older version of that skin which wasn't updated for XT1.1.

**Comment by baconpaul** [comment]
Yeah just grab the latest version from he skin library and you should be fine! (And if it is not a library skin ask the author to hop here and we can explain the graphics change)
