### ISSUE TITLE
Support CLAP NOTE_CHOKE

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6332]
This should just terminate the voice immediately (or after a few block fade) independent of the release.

**Comment by mkruselj** [comment]
Was this perhaps sorted out with #6334? I saw this:

![image](https://user-images.githubusercontent.com/2393720/178163909-38727df7-6315-43ac-8f47-55c6c9da10e9.png)

**Comment by baconpaul** [comment]
Thst means we don’t ignore it but we are t doing the right thing

choke isn’t quote note off. And so I need a different api point which is all sounds off but just for the one note basically

**Comment by baconpaul** [comment]
This may not make 1.1 since it seems bitwig doesn't generate the event?

**Comment by baconpaul** [comment]
https://github.com/free-audio/interop-tracker/issues/39

**Comment by baconpaul** [comment]
BWS 4.4.5 sends the right event so we can now go to implement this. Basically do an uber-release of the voice when you get a choke.
