### ISSUE TITLE
Presets completely break when rendering song or copying tracks

### ISSUE THREAD

**Issue by Lopyt** [surge-synthesizer/surge#6338]
**Bug Description:**
When I try to render a song or copy a track or open a project with SurgeXT on Reaper 6.53, latest version of Linux Mint, the SurgeXT preset changes to something randomized, and often plays really loud hurts my ears. This seems to happen only with the LV2 plugin, but I can test it with VST3 plugin to see. It randomizes some values on the built in presets, my presets, and settings I've changed but havent saved. I hope there is a fix because I reeeally like this synth

**Surge XT Version**

* Version:
* Plugin Type: LV2
* Bitness: 64 but

**Reproduction Steps:**
1. Install Linux Mint and Reaper and SurgeXT
2. Open a preset on the .LV2 plugin 
3. Make some MIDI for to hear the sound
4. Copy and paste the SurgeXT track, or
4. Render the song via File > Render, or
4. Save the song, close Reaper, and reopen the project
5. Listen to the new version of the synth sound and cry because it hurt your ears
6. Seems to be the problem there

NOTE: Rendering via right clicking the track and them doing Render Tracks As Stems does not seem to wreck the settings as rendering from the song renderer does.

**Expected Behavior:**
The synth values should stay the same on loading, copying, or rendering the synthesizer.

**Screenshots:**
Will add later, not using computer right now

**Computer Information (please complete the following!):**
 - OS: Linux Mint (latest version at 2022 June 10)
 - Host: Reaper
 - Version: 6.53

**Additional Information:**
Will find SurgeXT version later just give me a few hours. Also thanks for the synth!

**Comment by baconpaul** [comment]
So: We fixed a problem with initialization of muted tracks in reaper between 1.0 and 1.1 which sounds like it might be the same thing here. So

1. Can you try the latest nightly / 1.1 beta and
2. Also can you check if the VST3 exhibits the same behavior in the nightly?

**Comment by Lopyt** [comment]
Sure thing! Wow thats was a quick response thanks!!

-------- Original Message --------

**Comment by Lopyt** [comment]
The problem doesn't seem to be presemt on the VST3, on the LV2 though SurgeXT 1.1.nightly.2f3adc4 it is still here.

I didn't have a discord account but I wanted to ask if you guys were open to any new presets, I've made a bunch and can send them over if yes
-------- Original Message --------

**Comment by baconpaul** [comment]
Huh OK we use the community for for the LV2; if it is LV2 only that means it might not be fixed, since I know @falkTX is waiting for folks to port to juce 7 for LV2 support. (Surge probably won't hop to Juce 7 at the next release). I would recommend the VST3 for now. But let me tag him in case I misunderstood!

On new presets - sure! @mkruselj is our librarian. We have some suggestions and rules in our discord about naming, levels, and the like. Let me tag him here.

I'll rename this issue to make it clear that it is linux / reaper / LV2 also

Thanks

**Comment by Lopyt** [comment]
Awesome! Yeah definitely will be using VST3, I'm really happy to have that VST3 solution now!

Discord hasn't been very friendly with letting me actually make an account for whatever reason, so I'll get someone else to send in the files for me :). Thank you for your time!!

-------- Original Message --------

**Comment by mkruselj** [comment]
@baconpaul Should we close this one? We won't be putting more effort into community fork LV2, and JUCE 7 LV2s don't work in Reaper, and we're team CLAP anyways?

**Comment by baconpaul** [comment]
Well we are team open standards but I agree the fix here is to upgrade juce to an appropriate 7 vintage since it seems the community fork is mostly abandoned. So do that one day and use that
