### ISSUE TITLE
Provide a clean compile time message if platform is neither x86/SSE2 nor ARM

### ISSUE THREAD

**Issue by yurivict** [surge-synthesizer/surge#6363]
You include SIMDE [here](https://github.com/surge-synthesizer/surge/blob/main/src/common/globals.h#L43) for x86 on riscv64 architecture.

Please check architecture in the cmake script during the configure phase.

error:
```
In file included from /wrkdirs/usr/ports/audio/surge-synthesizer-lv2/work/surge-release_1.9.0/src/common/dsp/effect/BBDEnsembleEffect.cpp:16:
In file included from /wrkdirs/usr/ports/audio/surge-synthesizer-lv2/work/surge-release_1.9.0/src/common/dsp/effect/BBDEnsembleEffect.h:22:
In file included from /wrkdirs/usr/ports/audio/surge-synthesizer-lv2/work/surge-release_1.9.0/src/common/dsp/VectorizedSvfFilter.h:3:
In file included from /wrkdirs/usr/ports/audio/surge-synthesizer-lv2/work/surge-release_1.9.0/src/common/vt_dsp/portable_intrinsics.h:4:
In file included from /nxb-bin/usr/lib/clang/14.0.5/include/immintrin.h:21:
/nxb-bin/usr/lib/clang/14.0.5/include/mmintrin.h:71:12: error: use of undeclared identifier '__builtin_ia32_vec_ext_v2si'
    return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
           ^
/nxb-bin/usr/lib/clang/14.0.5/include/mmintrin.h:101:1: error: functions that differ only in their return type cannot be overloaded
_mm_cvtm64_si64(__m64 __m)
^
/usr/local/include/simde/x86/mmx.h:681:30: note: expanded from macro '_mm_cvtm64_si64'
#  define _mm_cvtm64_si64(a) simde_mm_cvtm64_si64(a)
                             ^
/usr/local/include/simde/x86/mmx.h:661:1: note: previous definition is here
simde_mm_cvtm64_si64 (simde__m64 a) {
^
```

**Comment by baconpaul** [comment]
That’s simde providing the x86 instruction set to non x86 architectures. 

I will have to see if simde upstream supports riscv64. But for now we won’t be able to build on that architecture.  

Surge uses direct hand coded sse intrinsics internally and simde provides an implementation of those which vectors to neon etc.

**Comment by baconpaul** [comment]
Yeah

https://github.com/simd-everywhere/simde#hardware

looks like simde doesn’t support riscv64. We will be unable to fix this until it does or until N equivalent library for thst architecture is available and someone integrates it.

**Comment by baconpaul** [comment]
Oh but if you let me know what the cmake architectur variable for this platform is I can make a fatal error earlier with an explicit message in our next release so packagers don’t have to waste time with more obscure errors. Thanks!

**Comment by baconpaul** [comment]
Oh thinking of it the right answer is for the (new version) of that header to do

```cpp
#if SSE2 defines
include mmtrin
#elsif ARM defines
include the simde x86 equivalence layer
#else
#error sorry we don't support your CPU which is neither SSE2x86 nor ARM
#endif 
```

I'll get that into the 1.1 release.

**Comment by mr-c** [comment]
> Yeah
> 
> https://github.com/simd-everywhere/simde#hardware
> 
> looks like simde doesn’t support riscv64. We will be unable to fix this until it does or until N equivalent library for thst architecture is available and someone integrates it.

Hello from 2024, even in 2022 SIMDe worked on riscv64, but there were no optimized routines. This is basically true for any modern hardware platform.

SIMDe provides a plain-C/C++ implementation for every function.

So if https://github.com/surge-synthesizer/surge/pull/6366 was added just because of SIMDe, then it should be removed.

**Comment by baconpaul** [comment]
Also is there any way to do an automated riscv build given that I have an ARM MacBook and a linux intel box I wonder?

**Comment by mr-c** [comment]
> Also is there any way to do an automated riscv build given that I have an ARM MacBook and a linux intel box I wonder?

You can crossbuild for riscv64 and then test using qemu. Here are some example GitHub Actions recipes we use for our own testing: 

Crossbuilding using gcc and qemu: https://github.com/simd-everywhere/simde/blob/32c959c1039a15cec465bfa1103b4bcf34b3ac3a/.github/workflows/ci.yml#L371
Likewise for clang & qemu https://github.com/simd-everywhere/simde/blob/32c959c1039a15cec465bfa1103b4bcf34b3ac3a/.github/workflows/ci.yml#L534

**Comment by baconpaul** [comment]
Thank you!

**Comment by baconpaul** [comment]
Turns out we had a subsequent commit add a `defined(__riscv)` to that if, but I am going to push a change now using SIMDE for *all* branches other than intel. thanks!
