### ISSUE TITLE
https://surge-synthesizer.github.io/ says "Download for null"

### ISSUE THREAD

**Issue by yurivict** [surge-synthesizer/surge#6364]
What does this mean?
![image](https://user-images.githubusercontent.com/271906/179160647-d1705e95-e447-4fb0-95e1-a764325d6cd1.png)

I think it meant to say "Download for FreeBSD" and link to https://www.freshports.org/audio/surge-synthesizer-xt-lv2/

OS: FreeBSD 13.1

**Comment by mthierman** [comment]
Well, looks like we check for the following platforms:
```
      platform = window.navigator.platform,
      macosPlatforms = ["Macintosh", "MacIntel", "MacPPC", "Mac68K"],
      windowsPlatforms = ["Win32", "Win64", "Windows", "WinCE"],
      iosPlatforms = ["iPhone", "iPad", "iPod"],
      os = null;
```
so null = anything not the above. Not sure what our policy is about linking unofficial builds but could add if the team is OK with that and if we are able to detect with window.navigator.

We should at least do something better than null.

**Comment by yurivict** [comment]
FYI: ```window.navigator.platform``` on FreeBSD evaluates to ```FreeBSD amd64```.

**Comment by mthierman** [comment]
Cool, thanks for checking! I have no problem adding other platforms with unofficial links, what does the team think? I'm sure everyone using these systems know it's unofficial but we could add a note as well.

**Comment by mkruselj** [comment]
Website related issues should go [here](https://github.com/surge-synthesizer/surge-synthesizer.github.io/issues), first and foremost. Please reopen this issue there.

**Comment by haenkel** [comment]
@mthierman you can link here: 
https://github.com/surge-synthesizer/surge-synthesizer.github.io/wiki/Linux-and-other-unix-like-distributions#surge-on-freebsd
and replace the (outdated) wiki part with: 
```
## Surge on FreeBSD

The FreeBSD port is available at: https://www.freshports.org/audio/surge-synthesizer-xt-lv2/

Users can install it with the command: <br/>
`pkg install surge-synthesizer-xt-lv2` (using a binary package) <br/>
`cd /usr/ports/audio/surge-synthesizer-xt-lv2 && make install clean`
(build and install from source)
```
