### ISSUE TITLE
Controller / Rename doesn't work on linux; no mini edit

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#637]
Controller/ Rename doesn't work on linux

The reason for this is because spawn_miniedit_text on linux (line 147 of common/gui/PopupEditorDialog.cpp) is not implemented.

**Comment by tank-trax** [comment]
@baconpaul 

this may be an ugly workaround but would it be possible to implement these two functions via JavaScript?

**Comment by baconpaul** [comment]
Nah if you are gonna do that you can do it with a system of kdialog or zenity instead. Super easy just kinda gross on the processing chain.

**Comment by tank-trax** [comment]
can those fields be available on the generic GUI?

**Comment by baconpaul** [comment]
<img width="934" alt="Screen Shot 2019-04-29 at 11 50 26 AM" src="https://user-images.githubusercontent.com/13387561/56908813-0c349000-6a75-11e9-8841-a98fc62f21a6.png">

zenity is built in (or kdialog on kde systems). So what I'm proposing is you implement spawn_miniedit by doing

1: if env zenity - do that on a pipe
2: if env kdialog - do that on a pipe
3: else do nothing

it's gross for a variety of reasons (popen in the gui will hang the gui; you may get clicks and pops; etc...) but it will at least start working.

**Comment by tank-trax** [comment]
the name part is not critical, it's the +-48 for pitch bend, fortunately Bitwig has a feature that can override this and push the value to Surge, but can't find such a feature in Reaper or Waveform, which are the other two DAWs in Linux that can support MPE, 

is it possible to have these fields in the generic GUI?

**Comment by baconpaul** [comment]
The +-48 you can edit in a text file.

```
paul:~/dev/music/surge-rack$ more ~/Documents/Surge/SurgeUserDefaults.xml 
<?xml version = "1.0" encoding = "UTF-8" ?>
<!-- User Defaults for Surge Synthesizer -->
<defaults version="1">
  <default key="defaultZoom" value="150" type="2"/>
  <default key="mpePitchBendRange" value="48" type="2"/>
  <default key="sliderMoveRateState" value="2" type="2"/>
</defaults>
```

Just change the 48 to whatever you want in that file and then save it and restart your surges
