### ISSUE TITLE
Effects Parameters as Modulation Destinations

### ISSUE THREAD

**Issue by mrniceguy1234** [surge-synthesizer/surge#6377]
Luckily with the daw I use its easy to add key-resettable lfo/envelope automation to parameters, but it would be really powerful for presets if Insert/Send/Global parameters were available as modulation destinations.

**Comment by baconpaul** [comment]
They are. You just have to use SCENE rather than VOICE LFOs.

**Comment by mrniceguy1234** [comment]
Oops! Thank you.
