### ISSUE TITLE
Global Volume is stored with the patch while the manual states otherwise

### ISSUE THREAD

**Issue by martijndeluxe** [surge-synthesizer/surge#6385]
The Manual says:

"
Global Volume controls the last gain stage before the output. The VU meter above it shows the output level and will become red if it goes above 0 dBFS. You can choose to hard clip the global output either at +18 dBFS (default) or 0 dBFS.

The state of these two settings are not stored with patches. They are however stored by the host application in your project files.
"

However the Global volume appears to do get stored and recalled by the patches.

I would prefer the behavior as described in the manual. But i can also live with the current behavior but than it would be a good idea to reflect this in the Manual.

Greetings,

 -Martijn-

**Comment by mkruselj** [comment]
Manual will be updated with the explanation of the current behavior. Pinging @VincyZed.
