### ISSUE TITLE
Typeahead Passes On Keypresses During Rebuild

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6414]
j5v — Today at 7:35 AM
Not quite a bug; more a behaviour to question: When I click to search, and it's rebuilding the database, Surge doesn't absorb keypresses.

So if I go to search, and start typing straight away as usual, my keystrokes go to the DAW instead, and trigger unintended things.
baconpaul — Today at 7:36 AM
ahhh right i know why that happens. but what would you expect to happen to those keypresses? drop on the floor right?
j5v — Today at 7:37 AM
maaaybe 🙂
baconpaul — Today at 7:37 AM
Chuckle. Exactly
j5v — Today at 7:37 AM
or queue up for the search (huge bug potential 🙂 )
baconpaul — Today at 7:37 AM
Let me add it as a 1.1.n issue. The typeahead doesn't have an editor while rebuilding and so doesn't have a keypress handler so the keypresses percolate
Yeah "queue up" .... welll
sounds like 'state bugs galore' to me but let me add an issue. it may be entirely doable!

**Comment by j5v** [comment]
Suggest that preventing propagation to the DAW is the main goal. Queueing keypresses is a stretch goal, probably more effort than it's worth to finesse that?

**Comment by baconpaul** [comment]
The solution here is in `PatchSelector::keyPressed` add a line like

`if (isTypeaheadSearchOn && storage->patchDB->numberOfJobsOutstanding()) return true;`

and test it quite a bit.
