### ISSUE TITLE
Changing oscillator type while a note is held causes incorrect oscillator behaviour

### ISSUE THREAD

**Issue by selenologist** [surge-synthesizer/surge#6423]
**Bug Description:**
If an oscillator's type is changed while a note is held, oscillators don't appear to be initialized correctly, leading to behavior dependent on the oscillator in use before.

**Surge XT Version**
Version: Surge XT 1.1.HEAD.beab6b17 (whoops - it says HEAD because I didn't update libs/sst-filters correctly, but this is [#beab6b17](https://github.com/surge-synthesizer/surge/commit/beab6b17fb6c63a9a77542f142b49ca86066d594))
Build: 2022-07-26 @ 15:56:33 on 'rainbow/local' with 'Clang-14.0.6' using JUCE 6.1.6
System: Linux 64-bit VST3 on  AMD Ryzen 7 2700X Eight-Core Processor
Host: Ardour @ 48.0 kHz

**Reproduction Steps:**
1. Load init saw.
2. Hold a note on your MIDI controller.
3. While the note is still held, change oscillator 1 type to something else, String's usually fun.
4. Observe weird glitchy behavior!

**Expected Behavior:**
Oscillators will initialize themselves correctly on type change even on currently active voices.

**Comment by baconpaul** [comment]
I wanna look at this quickly for 1.1 to see if it is a regression of one particular form - not committing to fix but may be able to.
