### ISSUE TITLE
Global Volume won't modulate.

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#6424]
...even though it looks like it should. 

In the UI, the global volume slider accepts modulation input from Macros, SLFO's or MIDI, but none of them will actually affect the output volume at all.

**Comment by baconpaul** [comment]
This problem has always been there. It is caused by this line

https://github.com/surge-synthesizer/surge/blob/beab6b17fb6c63a9a77542f142b49ca86066d594/src/common/SurgeSynthesizer.cpp#L4184

which reads the parameter directly rather than the local copy / modulated value.

**Comment by baconpaul** [comment]
The plan is: fix `storage.getPatch().volume.val.f` to `gsobalcopy[storage.getPatch().volume.id].f` or similar, based on what's the actually syntax for global modulators in that file :)

**Comment by baconpaul** [comment]
oh also we probably want to up the patch version number and clear any modulations onto global volume from old patches which we don't want to suddenly work. I think? @mkruselj your view here valued.

**Comment by Andreya-Autumn** [comment]
That makes a lot of sense. If the mod didn't work in the first place obviously clearing it is the way to ensure the patches keep sounding the same.

**Comment by mkruselj** [comment]
Yup upping the patch version makes sense.

**Comment by baconpaul** [comment]
I dont want to up the patch version and change streaming response in 1.1.1 and this is neither a regression nor absolutely critical so I'm going to push it back into 1.1.x
