### ISSUE TITLE
Noise LFO shape in Phaser FX stands still. 

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#6430]
In the phaser FX, all the LFO waveforms work correctly, except for Noise which stops the modulation completely. 

This seems to have been the case since pre-XT.

The flanger FX has the exact same LFO wave options, but with the Noise option working, so presumably this is a simple oversight. 

EDIT, never mind that last sentence, looks like those two effects in fact handle these LFO options a bit differently. I notice the phaser FX has the deactivateable LFO but the flanger doesn't, maybe that's connected somehow?

**Comment by mkruselj** [comment]
Same thing for Neuron effect, since it also includes ModControl.h just like Phaser does.
