### ISSUE TITLE
High CPU usage on certain standalone configs when disabling audio output

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#6437]
J5V on Discord reported the following :
"I'm testing the Windows standalone. Minor performance issue: if audio output becomes unavailable, CPU stays high (equivalent to 2 threads at 100%). Could be redraws or foreground polling.
I'll update to nightly, and test more things. "

@mkruselj has tested this and couldn't reproduce the issue.
However I tried it on my side and I could also replicate this behavior.

Here's what I found:

Input is enabled, then I disable the output: High CPU usage
Then I also disable the input: still high CPU usage
Then I enable the output: CPU usage goes down
Then I disable the output again with input still disabled, CPU usage stays low

**Comment by baconpaul** [comment]
i may ship 11 with this in place if i can't repro it. (I can't repro it on my mac).

**Comment by baconpaul** [comment]
Pushing out of MS for now. Will return to this once we collect all the 1.1 bugs from release.

**Comment by mkruselj** [comment]
@VincyZed Does this still happen with 1.2?

**Comment by VincyZed** [comment]
I just tested and this is not happening here anymore, so it seems to have been resolved. I will now close this issue.

**Comment by mkruselj** [comment]
Wahey!
