### ISSUE TITLE
Crash when selecting wonky preset "Cybersoda / FX / Evening on Pluto"

### ISSUE THREAD

**Issue by defiantnerd** [surge-synthesizer/surge#6447]
**Bug Description:**
Select the Preset "Cybersoda / FX / Evening on Pluto", observe the crash because a UI component goes to "inf" and "nan" during calculation.

**Surge XT Version**
1.1.main.81681b7c

* Version:
* Plugin Type: [CLAP]
* Bitness: [64-bit]

**Reproduction Steps:**
1. Select Preset "Cybersoda / FX / Evening on Pluto"
2. Observe Boom

**Expected Behavior:**
The preset should load.

**Screenshots:**
![image](https://user-images.githubusercontent.com/97224712/182032691-4a2d5301-3fd0-4a92-a376-961493604f0b.png)

**Computer Information (please complete the following!):**
 - OS: [Windows 10]
 - Host: [VST3 Test Host]
 - Version: [e2.7.5]

**Additional Information:**

**Comment by baconpaul** [comment]
The problem here is somehow you sent us a time signature of 0/0 and we don't defend against that. 

No other host does it, so that's why we haven't needed the defense, but #6449 handles this case too. And looks like I can merge that.

Thanks!

**Comment by baconpaul** [comment]
If you can test this either by pulling to head and rebuilding or waiting for next nightly we can close it with the defense! Thanks.
