### ISSUE TITLE
macOS Installer requires rosetta even though plugin is universal

### ISSUE THREAD

**Issue by postprivee** [surge-synthesizer/surge#6453]
any news on M1 compatible installers without Rosetta requirement?

**Comment by baconpaul** [comment]
What’s the problem exactly? The synth is universal and does t require Rosetta

**Comment by postprivee** [comment]
Ive tried to install using latest release + nightly build. both installers require Rosetta.
this is the warning I get - https://support.apple.com/en-us/HT211861

**Comment by baconpaul** [comment]
Ahh so the installer itself needs Rosetta - got it. I will see why! Thanks

**Comment by baconpaul** [comment]
https://developer.apple.com/forums/thread/667672

Looks like I need to tell pkgbuild that

**Comment by baconpaul** [comment]
OK I added those flags to our installer and, when I run on my M1 mac, the activity monitor shows no new intel processes so I think it worked. But I have rosetta installed so I can't tell for sure.

There should be a new nightly with this in it in about an hour or so. Any chance you can give it a whirl later in the day? I'll post back here when the nightly is up.

**Comment by baconpaul** [comment]
OK new nightly is available https://surge-synthesizer.github.io/nightly_XT 

if you could give it a try I would really appreciate it. According to apple docs this should launch without rosetta now. (The plugins have been universal since before logic hosted M1 plugins! Just not the installer. Appreciate you flagging this to us)

**Comment by postprivee** [comment]
> OK new nightly is available https://surge-synthesizer.github.io/nightly_XT
> 
> if you could give it a try I would really appreciate it. According to apple docs this should launch without rosetta now. (The plugins have been universal since before logic hosted M1 plugins! Just not the installer. Appreciate you flagging this to us)

just installed latest nightly build without any issues! thank you for the update!

we've been using SurgeXT on another M1 -Rosetta installed- without any issues. we're just trying to use new macs without Rosetta. thanks to you + devs like Jatin -he also released new builds without R requirement- we are able to install our fav plugins without any issues.

**Comment by baconpaul** [comment]
Awesome! Thanks for letting me know it worked.
