### ISSUE TITLE
Surge XT isn't controlled by Novation Automap

### ISSUE THREAD

**Issue by mvdev0** [surge-synthesizer/surge#6458]
Hi!

I love your synth, it is amazing what you developer did for us! Thank you so much!

It is not really an issue, it's more a question I have.

I'm using an (older) Novation ZeR0  SL MkII Controller and it's Automap software for some Plugins in PreSonus Studio One.

I like the way how easy we can transmit parameter designations and limits to the controller(s) which isn't if we
use MIDI-CC, particularly meaningful 14bit values.

It's also wunderful possible with Surge v1.8.1.9de9336, but I can't do with Surge XT.

I do not know I'm doing it right, but it looks like it isn't easy as with it's previous version.

Is there something I pay attention to or isn't it possible anymore (because Automap isn't under development anymore)?

Thank you very much for reading and spend time!

Wish you all the best!

Supplement:

What I can determine is if I let Automap contruct the special file for Surge 1.8 and Surge XT and use them both
in S1 DAW, close the host and put them both out of Automap, only Surge 1.8 can't be loaded anymore..
it looks like the XT PlugIn isn't the Automap controlled version the DAW is loading.
(After reconfiguring PlugIns in Automap I always rescan the PlugIn folder in S1.)

(Attached is the constructed Automap VST3 file)
[!Surge XT (Automap).zip](https://github.com/surge-synthesizer/surge/files/9237481/Surge.XT.Automap.zip)

**Comment by baconpaul** [comment]
Thanks for your kind words 

we ported surge to juce with xt - I wonder if there’s something to be gleaned from other juce plugins maybe? Do you have the Korg series or odin or vital?

i don’t use auto map so I’m not sure how it works - does it map to vst3 params? I wonder if there is an index vs id tbing. @mkruselj you know anything about how it works!

**Comment by mvdev0** [comment]
Hi @baconpaul, thanks for responding so fast!

I use Vital (v1.0.7) in S1 too, and it is working with Automap, but not all the time I load the project, sometimes I
have to reload several times, but than it is automap'd.

**Comment by mvdev0** [comment]
Paul, I can't really tell you how it is working, Automap is creating a secondary file with a exclamation mark at the beginning
and "Automap" in round brackets, but I believe the hosts loading this file and refer to the VST/AU/RTAS..

**Comment by baconpaul** [comment]
Oh I wonder if automap doesn’t work with bundled vst3

what did you copy it to?

**Comment by mvdev0** [comment]
> Oh I wonder if automap doesn’t work with bundled vst3
> 
> what did you copy it to?

I installed Surge XT alone, only the VST3, without the FX section.. but this won't help.

Btw. .. Odin 2 (v2.2.4) doing same as Vital, but the last ~5 times I reload S1, Vital is everytime listed in Automap,
Odin 2 only one time.

But I never saw Surge XT in Automap.

**Comment by mvdev0** [comment]
Mhh.. now I tested this again in Reaper DAW..

I have two versions of Surge (1.8) there, both with the same name without reference to Automap, but only one is recognized as expected in Automap.. and only have one file for XT. But at this moment I do not paste the automap'd file elsewhere, it's
as automap do. .. hopefully it's "only" about this and the mapped file is in a not recognized folder.

**Comment by mvdev0** [comment]
Now I can see that the mapped XT is in "Plug-ins that failed to scan" in Reaper, but not 1.8 .

**Comment by mkruselj** [comment]
This to me definitely looks like Automap might not be working well with VST3 plugins that are bundles (on Windows: folders with .vst3 extension). So this one would be on Novation's side to inspect, and if true, fix.

**Comment by mvdev0** [comment]
Hi mkruselj, thank you for reading!

Okay, I think this will never done.

.. but this behaviour is true for Odin2, which is in the main VST3 folder.

**Comment by mvdev0** [comment]
It was really good asking here, thank you all very much.. I can now concentrate on the synth itself, and will find another solution
controlling it from a piece of hardware.

Thank you all very much spending so much time in developing this nicely software!!

The topic can be closed, thanks!
