### ISSUE TITLE
Glissando Follows Tuning Set in Tuning Editor - Possible?

### ISSUE THREAD

**Issue by mrniceguy1234** [surge-synthesizer/surge#6461]
For now, a glissando glide will go between two notes of a custom scale, but the steps are 12edo semitones and it will snap on to the closest scale note at the end of the glide. It would be interesting to have the glissando follow custom tunings for different scale settings.

**Comment by baconpaul** [comment]
Answered on discord but yes this is the difference between tune at midi vs tune after modulation.

**Comment by mrniceguy1234** [comment]
This already exists. Right click tuning, must select option "Apply Tuning after Modulation"
