### ISSUE TITLE
100% CPU while loading XT1.1

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#6468]
Sluys reports: 
"...when I try adding surge to a track it just pegs the cpu at 100% and never finishes loading."
VST3, Reaper/Waveform/SaviHost, Windows, 64bit.

Emptying user folder fixed it. Moving SurgeXTKeyboardMappings.xml (attached, renamed to.txt) back in broke it again
[SurgeXTKeyboardMappings.txt](https://github.com/surge-synthesizer/surge/files/9259162/SurgeXTKeyboardMappings.txt)

**Comment by mkruselj** [comment]
@baconpaul Did we fix this regarding malformed keyboard mapping files, I forget?

**Comment by baconpaul** [comment]
I don't remember either.

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/sst-plugininfra/commit/a3f2a93857e7359074567a1255890c667dd40cec

we did.
