### ISSUE TITLE
CLAP -> MIDI controller stuck notes.

### ISSUE THREAD

**Issue by STOP63** [surge-synthesizer/surge#6470]
CLAP version 24d4a4b
Reaper 6.64+dev0803
Stuck midi notes when a MIDI controller keyboard is played. 
No issue with VST3i version

**Comment by STOP63** [comment]
I know from Reaper forum but  did you test with a real keyboard mine are M-Audio Axiom69 and a Roland A-34.
No issue with VST3 plugin.

**Comment by mkruselj** [comment]
Yes, tested with Korg nanoKEY Studio and NI S49mk2. All works.

**Comment by baconpaul** [comment]
You don't happen to have surge in MPE mode do you @STOP63

**Comment by STOP63** [comment]
What is MPE mode?

Just want to be clear.  I drag  Surge XT VST plugin in Reaper everything is default and it work when I play with my keyboard.

 I drag  Surge XT CLAP plugin in Reaper everything is default and all the notes that I play on the keyboard get stuck.

**Comment by baconpaul** [comment]
Right there is a light button next to patch browser that says “mpe” between zoom and tune. is it lit up in the clap in reaper?

can you record and send an rpp file?

and are all your notes on the same midi channel?

appreciate the report - sure we can solve it

**Comment by STOP63** [comment]
OK  MPE not activated but i tried it on and same issue.

I tried USB AXIOM61 > channel 1 only and same issue.

Here is a rpp file
[surge_xt.zip](https://github.com/surge-synthesizer/surge/files/9262736/surge_xt.zip)

**Comment by mkruselj** [comment]
Looks like somehow release velocity data is corrupted (see Reaper's MIDI event list). It should say 0 instead of --. Or maybe Reaper isn't handling release velocity towards CLAP very well. Forwarding your RPP to Reaper devs.

**Comment by STOP63** [comment]
Never mind the sustain pedal, I just mention the sustain pedal  (on the dev reaper thread **_like if_**) to explain what it sound like.

**Comment by mkruselj** [comment]
Well ok, even regularly played notes, works just fine here. I can't get any stuck notes...

**Comment by baconpaul** [comment]
Yeah I’m traveling today but let me load the rpp and see what it actually sends surge! That should help us triangulate 

which reaper by the way? Still the 0803 one?

**Comment by STOP63** [comment]
Yes, still the 0803 one.

**Comment by mkruselj** [comment]
From schwa: "that is most likely the 0x90 + velocity=0 note-off protocol, which should be handled for the next REAPER build".

**Comment by STOP63** [comment]
Maybe but I have to mention that the CLAP version of "ODIN II" work fine.

**Comment by STOP63** [comment]
It work!  +dev0804
