### ISSUE TITLE
AD Clip

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6479]
Reported by Chris S on KVR

> BUG(?): Airwindows - AD Clip not working properly?
> 1) The parameters (Boost, Soften, ..) do not have an effect.
> 2) When switching to another Clipping-Preset (eg. Slew1) via the selector-box and back to AD Clip the parameter-set is not updated (stays on clamping).

**Comment by baconpaul** [comment]
Confirmed both of these at head on macOS. No diagnosis yet.

**Comment by baconpaul** [comment]
Oh damnit
This is because ADClip has ID 0
and the change i made around the multi-drag re-initialization thought ID 0 was bypass

Hmm will be tricky to fix.

**Comment by baconpaul** [comment]
So this was caused by  91bc21cb

**Comment by mkruselj** [comment]
Can we not change the ID of AD Clip then handle streaming etc?

**Comment by baconpaul** [comment]
yeah that's my thinking indeed. but that's a bit tricky to fix :)
