### ISSUE TITLE
Sometimes is not possible to access the plugin controls

### ISSUE THREAD

**Issue by cdelacruzpinto** [surge-synthesizer/surge#6482]
I can use the plugin (i.e: if I play the keyboard, it plays sound), but when I open the controls, when I try to click in any UI item, is not possible to click. Weirdly enough, it reacts to keypresses, but not to the mouse clicks.

OS X Version: 13
MacBook Pro M1
Logic Version: 10.7.4

**Comment by mkruselj** [comment]
@baconpaul I assume you can't repro this one?

**Comment by baconpaul** [comment]
I cannot but I’m on12 not 13

I wonder if a zoom has gone wrong somewhere. Do any clicks anywhere work? Does right mouse open a menu?

**Comment by mkruselj** [comment]
@baconpaul What do we do with this one? @cdelacruzpinto is this still reproducible with the latest nightly (or soon to become Surge XT 1.3 official release)?

**Comment by baconpaul** [comment]
with logic 10.8 on macOS 14 i get mouse pointer oddities but no other problems with controls.

**Comment by mkruselj** [comment]
OK so we could close this one?

**Comment by baconpaul** [comment]
Lets but if OP is still having problem they could reopen it.
