### ISSUE TITLE
Loud pops when changing filter types and subtypes

### ISSUE THREAD

**Issue by robysweettrip** [surge-synthesizer/surge#6489]
**Bug Description:**
With a sustained note is playing, when changing filter types and subtypes, Surge XT makes loud pops, some louder than others, which is hurtful if one doesn't a) stop playback before making a change; or b) lowers the volume. In some cases, making this type of change makes a loud pop, followed by a few seconds of silence, until sound is heard again from the synth.

**Surge XT Version**
* Version: SurgeXT v1.1 stable and nightly from 8/3/2022, but I have noticed this for at least a few months, across several versions.
* Plugin Type: VST3, CLAP
* Bitness: 64-bit

**Reproduction Steps:**
In Bitwig:
1. Create a MIDI clip of any bar length
2. Insert a MIDI note that spans the clip's bar length
3. Load an instance of SurgeXT (CLAP or VST3)
4. Start playback
5. While playback is on, switch through the Lowpass options in sequence, and for each chosen option, choose a filter subtype in sequence: expected result is a "pop-less" transition; current result is that pops of varying degrees of loudness appear on playback
6. While changing filter types as explained above, when switching from LP Vintage Ladder at subtype 4 to KS3, a loud pop occurs, followed by a few seconds of silence before audio is resumed.

**Expected Behavior:**
To be able to switch filter types and subtypes without audible pops that can be hurtful when using headphones, or damaging to monitor speakers.

**Screenshots:**
https://user-images.githubusercontent.com/107824400/183276707-1b22851f-d216-4feb-a535-f98ee67154ab.mp4

If playback appears to be corrupted, please follow the [Discord link where I shared the above video, and had a short discussion on the issue](https://discord.com/channels/744319641211633774/744320626273288224/1005698826994204732).

**Computer Information (please complete the following!):**
 - OS: Kubuntu 22.04
 - Host: Bitwig 4.3.4 RC, Renoise 3.4.2
 - Version: *See above*

**Additional Information:**
N/A

**Comment by mkruselj** [comment]
Probably closely related, if not identical issue to #6227.

**Comment by baconpaul** [comment]
Maybe but it’s more likely to be related to the int modulation in voice changes if 101 doesn’t do it

**Comment by baconpaul** [comment]
Yeah this is definitely caused by the local copy int in d29e67f38 the same way that screwed up oscillator switches on running voices. I'll revert the relevant other bits that I didn't revert from there in 110 for a 1.1.1

**Comment by baconpaul** [comment]
Unison too
