### ISSUE TITLE
Option to make noise oscillator mono

### ISSUE THREAD

**Issue by erroreyes** [surge-synthesizer/surge#6494]
**Is your feature request related to a problem? Please describe!**
There are some use cases when I need to have a mono noise signal for a patch that I am working on, and it seems that the only way to achieve that is to either set the global Width to 0.00%, or to choose one of the serial routing options. This unfortunately by doing so, one loses the ability to use oscillator unison with stereo widening on a patch.

**Describe the solution you'd like:**
It would be great if there was an option in the oscillator's mix panel's context menu that would allow to toggle noise from mono to stereo.

**Describe alternatives you've considered:**
N/A

**Additional context:**
N/A

**Comment by baconpaul** [comment]
Oh that’s interesting - you mean the noise source in the mixer right the one labeled “n”?

we could easily put an rmb option on the noise color slider to choose mono or stereo - that would do it right?

**Comment by baconpaul** [comment]
The way to do this is

1. Put a deform option on noise color and add the RMB and stream it
2. Read that deform option in SurgeVoice into a 'is_noise_narrow'
3. Change https://github.com/surge-synthesizer/surge/blob/35318e3f685d75e0f0cb97e13b1c62d2d87b0280/src/common/dsp/SurgeVoice.cpp#L1046 to say

```cpp
if (is_wide)
{
    if (isNoiseNarrow)
       tblockR = tblock
    else
       that code
}
```

and then test

**Comment by robysweettrip** [comment]
> Oh that’s interesting - you mean the noise source in the mixer right the one labeled “n”?

Yes, exactly.

> we could easily put an rmb option on the noise color slider to choose mono or stereo - that would do it right?

That would work. Wherever it is most suitable for something like that to exist would be great. I thought about a width control for the noise source which would be super great, but for me personally, a simple stereo/mono switch is enough.

**Comment by baconpaul** [comment]
yeah we have a plan for "the future" which we call "XT2" which would have much more stereo control. in the XT1 family a mono stereo switch is easy though. We can add it as a small feature enhancement to one of our dot releases. (If you happen to be a coder I'm also happy to walk you through it but if not that's also fine).

**Comment by robysweettrip** [comment]
Oh that would be wonderful. That said, I am mainly a Java person, I've been out of the game for almost 2 years, and I really don't want to be nuisance if this would be a lot faster to implement by the team. Otherwise, yes, I would love the experience.

**Comment by baconpaul** [comment]
Great this will be in a nightly later today.
