### ISSUE TITLE
Disable or remove the dirty patches query when loading a new patch

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#6495]
Now that we have undo, perhaps we don't even need this dialog at all.

**Comment by mkruselj** [comment]
Tbh I kinda feel we could even remove the option...

**Comment by baconpaul** [comment]
I didn't want to do that much surgery. We can supress the menu if you want I guess though! But maybe some folks would like it. I dunno. Trying to keep changes "smaller" for 1.1.1
