### ISSUE TITLE
Wt accessible buttons 

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6511]
I'm not sure if this is an accessibility thing or not.When my oscillator is a wave table and I use the next and prev buttons to load wavetables, the direction of travel is the wrong way around.   For example, I was going through VT Growl wavetables.  There are 8 of them.  When on Growl 5, and I hit next, it goes to Growl 4.Possibly the buttons are just labelled the wrong way around as prev is second in the tab order.

From discord user chessel - I am sure I just flipped the labels on the overlays

**Comment by mkruselj** [comment]
Yes, it is mislabelled. Pushing a fix!
