### ISSUE TITLE
After closing the context menu the screen reader does not update the focus

### ISSUE THREAD

**Issue by Lo-lo78** [surge-synthesizer/surge#6515]
Hello to all the team!
Congratulations on the work on accessibility.
The navigation on Surge is very good but when the context menu is opened with shift + F10 "and an item is selected. When it returns to the main window the screen reader does not update the focus automatically. I have to" tab "or" shift + tab "to update focus It takes three seconds and then you can continue working with Surge.
I don't know if it's Juse's problem.
Greetings!
👍👍👍

**Comment by mkruselj** [comment]
Thanks for the report! We already have it tracked as #6426, so I hope you won't mind if I close this issue as duplicate.

Cheers!

**Comment by Lo-lo78** [comment]
No problem!

Il 14/08/2022 22:46, EvilDragon ha scritto:
