### ISSUE TITLE
Step Sequencer value typeins

### ISSUE THREAD

**Issue by Lo-lo78** [surge-synthesizer/surge#6516]
Hello,
I am learning to use Surge and I noticed that I wanted to enter the values ​​in the step sequencer with the keyboard.
With the progress slider the values ​​are approximate.
If I do the shortcut shift + f10 it doesn't make me edit a precise value in an editing field.

The bug is that if I do the shortcut shift + f10 it goes to the LFO context menu where I can choose the type of LFO. But that contextual menu isn't exact.

**Comment by baconpaul** [comment]
I have no idea why we don’t do this, yeah. (I mean I do know why it is a bit clumsy but it’s not *that* bad). Let me tag it into a 1.1.n milestone

**Comment by Lo-lo78** [comment]
Hi, I closed it because I thought it was in the wrong category.

I moved it to the issue:


https://github.com/surge-synthesizer/surge/issues/6518

Thanks friend!

**Comment by Lo-lo78** [comment]
It would also be very nice if the individual steps could be edited with track envelopes.
In the context menu you could put the item:
  Show track envelope.
Greetings!

**Comment by mkruselj** [comment]
That would be overly complicated IMO. You can use the Deform slider to make plucks etc with the Step Sequencer modulator.

**Comment by baconpaul** [comment]
I think the request was to have a reaper track envelope per step - which basically means each step is a param (or maps to one of a set of reserved generic params). Agree that doesn’t belong in this issue tho.

**Comment by Lo-lo78** [comment]
@baconpaul 
If it were possible to put individual steps in the track envelope it would be a quantum leap for the step sequencer which is a bit static.
It could be a great revolution. Change values ​​during the song.
If the Surge team develops it, it's a super feature!
😂

**Comment by mkruselj** [comment]
I will vote against that.

**Comment by baconpaul** [comment]
Yeah that would explode params

i am thinking a bit about voice level macros ans being able to use a step as a mod target which could be interesting but is tricky 

the idea of adding 16*12*2 params for the steps though seems pretty ugly especially since most would mostly do nothing

**Comment by mkruselj** [comment]
Wait, isn't it 16 steps * 12 LFOs * 2 scenes = 384? And I guess triggers would be another 384 (integer valued so you can have off, FEG, AEG, FEG+AEG). Still, UGLY.

**Comment by baconpaul** [comment]
Yes if you look at the plaintext of my message it us `16 * 12 * 2` which absent backticks from my phone renders as 16*12*2

**Comment by mkruselj** [comment]
Ahahahaha that's some next level trickery. 😀
