### ISSUE TITLE
Is it possible to develop an arpeggiator for Surge?

### ISSUE THREAD

**Issue by Lo-lo78** [surge-synthesizer/surge#6517]
Hello to the team!
In addition to the step sequencer it is very useful in a synth to have an arpeggiator.
An arpeggiator with all the basic and even advanced features:
up, down, up, inverted down, random, sine and a very interesting function could be to prioritize the pressed notes.
I don't remember what this latest arpeggiator feature is called. I try to explain it:
if I type three notes the synth should understand which one I pressed first.
For instance:
a major chord: press mi sol do and the arpeggiator will play mi sol do; sol do mi and the arpeggiator will play sol do mi.
Greetings!

**Comment by baconpaul** [comment]
I see you closed this but #3675 is where we have been discussing an arp
