### ISSUE TITLE
Is it possible to develop an arpeggiator for Surge?

### ISSUE THREAD

**Issue by Lo-lo78** [surge-synthesizer/surge#6518]
**Is your feature request related to a problem? Please describe!**
Hello to the team!
In addition to the step sequencer it is very useful in a synth to have an arpeggiator.
An arpeggiator with all the basic and even advanced features:
up, down, up, inverted down, random, sine and a very interesting function could be to prioritize the pressed notes.
I don't remember what this last arpeggiator function is called. I try to explain it:
if I type three notes the synthesizer should figure out which one I pressed first.
For instance:
a major chord: press mi sol do and the arpeggiator will play mi sol do; sol do mi and the arpeggiator will play sol do mi.
Greetings!
A clear and concise description of what the problem is. e.g. I'm always frustrated when [...]
Yes, I always have to use an arpeggiator with another midi plugin.
**Describe the solution you'd like:**
It would be very interesting if Surge had an advanced arpeggiator.
**Describe alternatives you've considered:**

**Additional context:**

**Comment by baconpaul** [comment]
Hi!

This is a dup of #3675 and yes we would love an arpeggiator in the synth also!

**Comment by baconpaul** [comment]
Oh but since it is a dup, let me close this one!
