### ISSUE TITLE
Is there a way to run Surge XT as a standalone application on Linux?

### ISSUE THREAD

**Issue by soonan5** [surge-synthesizer/surge#6521]
I love this synth <3, but I wish I could run it solo as well as Vital or OB-Xd to focus only on sound design. :D

**Comment by baconpaul** [comment]
You mean like a standalone app? Xt ships with a standalone for all oses 

or can you be a bit more specific?

**Comment by baconpaul** [comment]
Like if you install the deb you should get usr bin surge-xt

**Comment by soonan5** [comment]
Oh! Sorry I hadn't updated since `1.0.1` In `1.1.0` this binary is included. Thanks for your help. :D

**Comment by baconpaul** [comment]
Great

**Comment by baconpaul** [comment]
(1.0.1 had the binary as well it just didn’t have the desktop goobits to make it findable -which we fixed for 1.1.0!)
