### ISSUE TITLE
Why did switching between presets with the Mouse Wheel stop working since XT version?

### ISSUE THREAD

**Issue by soonan5** [surge-synthesizer/surge#6522]
Surge 1.9.0 had this feature that I really liked, which suddenly disappeared with the arrival of Surge XT =>1.0 Was it on purpose? Or do I need to activate something to get it to work again? o_O
![xt](https://user-images.githubusercontent.com/109312533/184930552-c46d99b6-0c06-430c-9220-74168936f530.png)

**Comment by baconpaul** [comment]
Wow 19 did that? Which control did you focus for the wheel gesture to work? 

I don’t think we removed this on purpose but we did kinda rewrite the ui when we went to juce so could easily have just forgotten.

**Comment by soonan5** [comment]
It worked in Category and Patch section.

**Comment by baconpaul** [comment]
Huh @mkruselj did we get rid of this on purpose or did we just forget?

**Comment by mkruselj** [comment]
Probably the latter...

**Comment by baconpaul** [comment]
The FX Presets button also used to do this and no longer does.
