### ISSUE TITLE
Wavetable frame size options when loading WTs without metadata

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6544]
Idea I floated on discord which folks liked for the 1.1 series ahead of a full wavetable metadata editor

If you drag a .wav file on with, say, `5120=1025*4` samples and no metadata surge will I think make it a one shot. Wouldn't it be nice if it also added a menu to the wavetable menu like

```
Change table marks...
   5 tables of 1024
   10 tables of 512
   20 tables of 256
   40 tables of 126
   80 tables of 64
   Oneshot of length 5120
```

so you could just drag on a wave and modify it appropriately

**Comment by mkruselj** [comment]
Maybe make it into a quick overlay instead that just queries the user if there's no metadata found? I would find that much nicer than something tucked away in a dropdown...

**Comment by baconpaul** [comment]
Smart. Just as long as we don't accidentally spec a 1.2 :)

**Comment by mkruselj** [comment]
My thinking is with this we have an overlay to work with and update later with proper WT editing stuff. Hell, we already have a commented out WT editor overlay we could use as a starting point, in fact!

**Comment by baconpaul** [comment]
that's the lua generator which I think is distinct

I'll ponder. Maybe we do neither and just push this into 2 also!

**Comment by mkruselj** [comment]
I mean sure but we could use the existing overlay for the script WT generator, ifdef out the UI part of it and add our WT metadata widgets in, then worry about other stuff later?

**Comment by mkruselj** [comment]
So hey @baconpaul, we already basically had this issue outlined as #3436. So I'm closing this one and moving that one to 1.1.1 milestone, while referencing this one.

**Comment by baconpaul** [comment]
Great. Moving it to 1.1.x tho :)

**Comment by mkruselj** [comment]
Sure!
