### ISSUE TITLE
Keybinding to Arm Modulation

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6549]
Used to be tab
We basically took that out when we added proper focus traversal
and added a hundred other keybindings
but not an arm one

I propose COMMAND-M which i sunused

@mkruselj unless you object I'll bang this into 1.1.1

**Comment by mkruselj** [comment]
I wonder for how many DAWs Ctrl+M is an already bound shortcut tho...

**Comment by mkruselj** [comment]
Maybe Alt/Opt+A (for "Arm")?

**Comment by baconpaul** [comment]
Oh sure!
