### ISSUE TITLE
Align installer names

### ISSUE THREAD

**Issue by kzantow** [surge-synthesizer/surge#655]
Currently, the installers are not named consistently. We should change this. I propose: `Surge-Setup-<platform>-<bits>-<version>.<extension>`

e.g. this would be something like: `Surge-Setup-Windows-x86-1.6.0.exe` or `Surge-Setup-macOS-x64-1.6.0.dmg`. Feedback welcome!

cc @itsmedavep @baconpaul

**Comment by baconpaul** [comment]
Makes sense to me

**Comment by baconpaul** [comment]
You know, I just don’t think we’r going to do this one. We’ve released about 1000 installers since we wrote the ticket and everything is fine, so I’m just gonna close it unless you object!
