### ISSUE TITLE
A Basic CPU Load Implementation

### ISSUE THREAD

**Issue by danielhoey** [surge-synthesizer/surge#6576]
**Bug Description:**
Playing very many notes with multiple sine OSC with unison voices will produce a lot of clicking/fuzz/digitial distortion.

**Surge XT Version**
Surge XT 1.0.1.60228e8
64 bit
Stand alone executable

**Reproduction Steps:**
1. Initialize patch
2. Set OSC 1 to Modern/Sine, Unison Voices -> 16
3. Set OSC 2 to Modern/Sine, Unison Voices -> 16
4. Set Amp EG release to a high value (0.3s or higher)
5. Play as many note as possible for a 5+seconds.

**Expected Behavior:**
The sound produced by pressing the first key should not be significantly different then the sound produced when pressing later keys.

**Computer Information (please complete the following!):**
Windows 10 - 64bit
Stand alone executable ("Surge XT.exe")

**Additional Information**
Surge is utilizing about 25% of CPU during this process

**Comment by baconpaul** [comment]
It sounds like you are running into the clipper. If you turn the amplitude down for each osc in the mixer does the problem resolfe? 

Also 25% is quite a lot of cpu. May want to take that unison count to 7.

**Comment by danielhoey** [comment]
Thanks for the prompt reply. Changing the osc amplitude makes no difference
(except that the artefacts are quieter).
The magnitude of the problem reduces as the the unison count is decreased
and at 10 it disappears completely and the the cpu usages is limit to 21%
Apologies if this is expected behaviour, I didn't realise that I was
pushing the synth to a limit by selecting max unison voices.

**Comment by Andreya-Autumn** [comment]
Yeah the 16 voice unison is something of a legacy option at this point. There's severely diminishing returns after around 7 or so anyway, and you're not the first to run into CPU and/or level issues with it. 

Seems like the consensus is that the next major update (not strictly scheduled but planned sometime next year maybe) will have a more sensible max to the unison parameters. :)

**Comment by mkruselj** [comment]
Yeah those digital artifacts are your CPU being overloaded, not an error in Surge. Since this happens at 25% CPU,  this tells me one core (assuming you have a quad core CPU) simply got oversaturated and since Surge doesn't do multicore processing, everything falls over.

At any rate,  not a Surge bug.

**Comment by baconpaul** [comment]
We really will have to do multi core when we do xt2.

**Comment by danielhoey** [comment]
Just a thought, but would it be useful to have an indicator showing when the CPU is overloaded? It wasn't obvious to me, but I'm newish to software synths so maybe this not such a mystery to most users. 

I'm happy to look at implementing this if it is wanted

**Comment by baconpaul** [comment]
I’ve thought about doing a hires timer on process and comparing i with sr/32 yeah. If you want to give that a shot lemme know and I will add some more detailed notes here on how I would proceed. Welcome the dev help! I’ll reopen this and if your game add notes tomorrow am

**Comment by danielhoey** [comment]
Sure, I'm keen.

**Comment by baconpaul** [comment]
OK so the basic idea is

1. Time the main ::process loop and compare it with max time
2. update a value smoothly with that ratio
3. Display it in the UI (probably in the VU meter for now)

but before that begins, you want to make sure you can build and change surge. Standard advice is clone, checkout, build, modify one of the strings in `src/surge-xt/gui/overlays/AboutScreen.cpp` and then see that modification in menu/about in your running environment. For this exercise the standalone will be perfectly fine.

So to each of the steps

## Time the main ::process loop. 

1. At the very start and end of `SurgeSynthesizer::process` add a call to `std::chrono::high_resolution_clock::now` (https://en.cppreference.com/w/cpp/chrono/high_resolution_clock/now) storing the results in local variables (like `auto perf_start = ....`)
2. After you record the end time, subtract to get a duration and use `duration_cast` (https://en.cppreference.com/w/cpp/chrono/duration/duration_cast) to cast it to microseconds or whatever
3. The number of microseconds the block has available at the absolute max is `BLOCK_SIZE * storage->dsamplerate_inv * 1000000` so then you can make a ratio

## Update a value

The UI thread runs much more slowly than the audio thread and you want to smooth the CPU anyway. The way we do this with the VU meter is an exponential decay. So lets do same here

1. In `SurgeSynthesizer.h` near the VU stuff add `std::atomic<float> cpuLevel{0.f}`
2. We already have a `vu_falloff` on storage. So we can do the same here, namely CPU is max of cpu and falloff. https://github.com/surge-synthesizer/surge/blob/c8fb77e9d0318addfa384329701884c736a6f721/src/common/SurgeSynthesizer.cpp#L4526 there's how the VU meter works so you can do just the same on cpuLevel

## Show the value

first thing I would do is in `SurgeGUIEditor::idle` just print the `synth->cpuLevel` on every idle and then see if it basically works to stdout. You can easily make high CPU with a high unison modern oscillator running into vintage ladder filters at high poly count. If it is working then we want to whack the VU meter to show the value if it is above some level.

I would do this as follows, but follow the code

1. Add a cpuLevel member to the VUMeter class (src/surge-xt/gui/widgets/VuMeter.h) initialized to 0
2. https://github.com/surge-synthesizer/surge/blob/c8fb77e9d0318addfa384329701884c736a6f721/src/surge-xt/gui/SurgeGUIEditor.cpp#L797 after that code do the same thing with the cpuLevel from the synth
3. In the paint method of VuMeter for now just paint the cpu level on the right using g.drawText() with a fixed color
4. If that works then we need to add a style color and stuff. You can either follow along from the code, ask on discord, or push a PR at this point which we can merge and then help you do that.

Discord is best way for realtime help and questions. Hope this helps!

**Comment by mkruselj** [comment]
Oh hey, we have actually implemented this in 1.1.2! So, closing!
