### ISSUE TITLE
Don't work VST2 in Reaper DAW

### ISSUE THREAD

**Issue by Vitzen** [surge-synthesizer/surge#658]
Don't work VST2 in Reaper DAW on my mac os - the vst 2 plugin is not even displayed in the FX list after rescan
i try both versions of installer:  1.6.0 beta 5 for mac os and last nightly build

ps: vst 3 and au Surge plugins work fine in Reaper

**Comment by baconpaul** [comment]
OK so this close to a bug in REAPER. I downloaded latest reaper mac demo and found: If both a VST and VST3 have the same component name (Surge.vst and Surge.vst3) it only scans the VST3

If I move ~/Library/Audio/Plug-Inst/VST/Surge.vst to Surge2.vst then reaper loads it no problem and the about screen shows I"m running vst2. But then bitwig shows the name "Surge2".

So clearly this is a mis-behavior in REAPER. It shouldn't think Surge.vst and Surge.vst3 are the same thing to the point over overwriting. But I'm not sure what we should do.

**Comment by baconpaul** [comment]
Actually @Vitzen I hope you don't mind - let me close this issue and we can move the convo over to #583 which has several other host reports. 

Again, if you want to use the VST2 in reaper you can fix this yourself after installing the 1.6beta5 by renaming the component (which for you will be in /Library/Audio/Plug-Ins/VST/) and then both will be loadable.

**Comment by Vitzen** [comment]
baconpaul, big thnx man!!! it work - thank you again for this help
I deleted VST3 plugin and reaper find vst2 plugin without problem

ps: but I can't understand - why other vst2 plugins that have the same name as their vst 3 versions are normally scanned by Reaper

**Comment by baconpaul** [comment]
Oooh if you have a plugin that does that (vst2 and 3 in reaper) can you let us know which one? One of our users pointed out fab filter does the same thing as surge. A counter example may help us resolve surge reaper behavior
