### ISSUE TITLE
Consider End Binary Distro of LV2

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6605]
The LV2 with the community fork has several bugs. We keep getting reports like this:

<img width="630" alt="Screen Shot 2022-09-10 at 11 01 01 AM" src="https://user-images.githubusercontent.com/13387561/189489285-3ce472dc-a1f6-4e27-82d2-596396b01f35.png">

so lets stop the binary distribution of it at least, since it seems with juce 7 the community juce 6 fork is no longer actively maintained.

**Comment by haenkel** [comment]
Not enough time to create anything pullrequestworthy
but I quickly tried something and thought I'd share it.
If I do something like this:
https://github.com/haenkel/surge/commit/9943a02c743d0d048353352184df93c8d052a1b1
then patches seem to (re)load correctly in all formats for me.
(haven't tried ardour but same happens in reaper)

**Comment by baconpaul** [comment]
So that just forced things to load twice right?

**Comment by haenkel** [comment]
simplified the above example
but yes it does that

**Comment by dvzrv** [comment]
> so lets stop the binary distribution of it at least, since it seems with juce 7 the community juce 6 fork is no longer actively maintained.

JUCE 7 has native support for lv2 :)

**Comment by baconpaul** [comment]
Yes I know. It doesn't seem to work quite properly for us when we check in the hosts that support it; but also we are on juce 6 still!

**Comment by baconpaul** [comment]
or more accurately: a version of juce 6 with some accessibility patches which are critical so moving is a pain.

you can build surge today with juce 7 if you want and get an lv2. this is just about whether we should continue to ship a binary built with the community build.

**Comment by mkruselj** [comment]
> JUCE 7 has native support for lv2 :)

Yep and LV2 produced by JUCE 7 doesn't work in Reaper, for example.

**Comment by baconpaul** [comment]
meh lets not change anything for 1.2
