### ISSUE TITLE
Surge's control changes at preset loading don't refresh hosts' corresponding knobs or values.

### ISSUE THREAD

**Issue by phazec** [surge-synthesizer/surge#6607]
**Bug Description:**
If you load a new preset with SurgeXT's preset loader, no values refreshed in host. It seemed first time like a takeover issue, but it's basically just this: no automation "actual" value, nor GUI knobs on host side refresh to their real value when you load a new preset. The big impact on my workflow is: I have a default preset saved for SurgeXT in Ableton Live. Surge's 8 macro knobs are made to show up as first 8 controls on live's little plugin GUI at bottom of the screen (Opening VST controls with [>] button on it and pressing Configure just to move Surge's controls to show up on Push 2's knobs. When you load a new preset in Surge, Live's GUI "Macro1..8" controls stay greyed at previous presets' last value and instantly jump there when you start to move given Push knobs. They are rotary encoders showing actual values on screen. This behavior completely destroys this simple use case.

**Surge XT Version**
Version: Surge XT 1.1.1.ecf7fe6
Build: 2022-08-25 @ 21:56:20 on 'WIN-KDGQ3UVP6AT/pipeline' with 'MSVC-19.29.30146.0' using JUCE 6.1.6
System: Windows 64-bit VST3 on Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz (Windows 10)
Host: Ableton Live 11 @ 44.1 kHz

**Reproduction Steps:**
Ableton live 11, change to midi clip view on Surge's track (Shift+Tab from device view), switch to envelopes view (two dots connected backslash form, Alt+2), move any of Surge's controls (one is enough), switch/load preset in Surge, watch that parameter changing on Surge's GUI and not changing on Live's GUI.
My use case: Switch to Device view (Shift+Tab from Clip view), open Surge's extended view on it with little triangle button pointing down/right. Press Configure button, it stays active. Move any controls on Surge GUI, watch them appearing on Live's Device view, Switch off "Configure" mode, and load a new preset in Surge. None of them will move. When you move any of them, their corresponding controls on Surge will jump to that wrong value first.

2. Click on '...'
3. Scroll down to '...'

**Expected Behavior:**
Please give the host your controls new state when required! Especially on preset load.

**Screenshots:**
https://drive.google.com/drive/folders/1Q0YGVp2dTx6391n3MdCbsGKhF3zkZjQw?usp=sharing

**Computer Information (please complete the following!):**
 - OS: Windows 10
 - Host: Ableton Live 11
 - Version: 11

**Additional Information:**
Push2's knobs are practically unusable after Surge preset load (even when loading partial presets with that hamburger menu like button)

Edit: typo

**Comment by Andreya-Autumn** [comment]
Ouch, that's unhelpful indeed. 

Confirming this (and removing the "host specific" label I overzealously tacked on), I'm seeing the same behavior when showing Surge XT params in track controls in Reaper. The parameters in question cease to update when changing patches. Other synths do not do this, they update the values in the track controls when changing presets.

@baconpaul Any ideas?

**Comment by Andreya-Autumn** [comment]
Oh btw, this is only when changing the patch using SXT's internal patch selector. If I save some presets using Reapers preset management, and then switch between those, the track control parameters update correctly. 
I'd hazard a guess, that's the same behavior you're getting @phazec ? Assuming Live has a preset system of its own that is.

**Comment by baconpaul** [comment]
Oh probably i just need to send an automation event on all params when patches change and have forgotten. 

But oddly when I run it in LPX10 with the AU and bind a smart control to Cutoff Frequency and toggle through patches I see those change (and same with macro) so there's something about surge + VST3 + invalidation here for sure. 

Will look for the 1.1.2 release.

**Comment by Andreya-Autumn** [comment]
I'm getting the same behavior with VST3 and AU in Reaper though!

**Comment by baconpaul** [comment]
Maybe logic cheats and repulls? 
or maybe we sent an event reaper ignores? 
but anyway we can debug for sure. Solid bug report.

**Comment by Andreya-Autumn** [comment]
Good! :)

**Comment by baconpaul** [comment]
OK I've confirmed this and it's a bit subtle. If a parameters name changes when you change patches, the value updates also. But if only the value changes, then nope.

Lemme see if I can get a fix into 1.1.2

**Comment by baconpaul** [comment]
Ahh no this is a bigger change; will bump this one into 113.

**Comment by phazec** [comment]
Works perfectly, tiny CPU spikes, doesn't matter I think. Thank you so much!

**Comment by baconpaul** [comment]
Great! Thanks for confirming and reporting
