### ISSUE TITLE
Disable scroll-wheel on category and patch buttons.

### ISSUE THREAD

**Issue by rghvdberg** [surge-synthesizer/surge#661]
My idea to add scroll-wheel support for controls was to speed up editing.
Now the scroll-wheel also works on the [+-] buttons for category and patch selection and it doesn't really work well in my opinion and it certainly doesn't speed up editing.
I think the best option is to disable the scroll-wheel on these particular controls.

**Comment by baconpaul** [comment]
think the way you do this is add another member (bool usesMouseWheel) to CHSwitch2 and add a method setUsesMouseWheel( bool ) and then in SurgeGUIEditor for the ones you want to suppress (like say around line 725) do mp_cat->setUsesMouseWheel(false). Then in your mouse wheel handler do "if ! usesMouseWheel return false" at the very top.

I don't think scroll wheel on those little buttons is what people expect. I would be happy to sweep a PR like the one outlined.

**Comment by baconpaul** [comment]
This is swept in now just we forgot to close the issue.
