### ISSUE TITLE
FX Unit shows more clearly if you violate latency implicit guarantee

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6638]
FX Unit by default runs 0 latency and assumes a multiple of 32 block size
If you are in 0 latency mode and get a non-multiple-of-32 block you should

1: not segfault (duh) and
2: put up a message on the UI pointing people to the option for that host

**Comment by mkruselj** [comment]
Linking this one to #6524, these two issues should have the same resolution.

**Comment by baconpaul** [comment]
the resolutions are different since the fx already has a latent option. This i just detection and handling.

**Comment by baconpaul** [comment]
Fixed in #6866
