### ISSUE TITLE
Filter Analysis: Visualization does not update when Cutoff/Resonance is changed via MIDI learned CC

### ISSUE THREAD

**Issue by planist79** [surge-synthesizer/surge#6644]
**Bug Description:**
Filter Analysis Window: Visualization does not move when Cutoff/Resonance is changed via CC (MIDI learn with + external Midi controller)

**Surge XT Version**
* Version: 1.1.1
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Open Surge XT as VST3 in Cakewalk by Bandlab
2. Assign Cutoff  to MIDI Controller (e.g. CC 118) via MIDI learn
3. Open Filter Analysis Window
4. Try to change Cutoff via MDII controller, result: The cutoff slider moves, but not the visualisation in the Filter Analysis Window 
(ps. The frequency visualisation in the Filter Analysis Window moves when i move the cuoff slider with the mouse)

**Expected Behavior:**
 The frequency visualisation in the Filter Analysis Window should also move when cutoff is changed via external CC/MIDI controller. 

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following!):**
 - OS: Windows 10
 - Host: Cakewalk by Bandlab
 - Version: 9/2022

**Additional Information:**
 Its a Notebook with Intel Graphic Card.

Thank you for this great synth and for having a look at this issue.

BR; Peter

**Comment by baconpaul** [comment]
Oh I bet vst automation also doesn’t dirty it
Thank you

**Comment by mkruselj** [comment]
Same thing with waveshaper overlay, ofc.

**Comment by planist79** [comment]
Thank you! @baconpaul

**Comment by baconpaul** [comment]
no problem! Thanks for reporting it and sorry we took a while. we spent the fall on the rack modules and i'm just now cleaning up some of the smaller vst backlog.
