### ISSUE TITLE
Oscillator Shaping

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6646]
Over in https://github.com/surge-synthesizer/surge-rack/issues/303 user posted super useful ideas about PD and stuff which since they were in the rack repo we didn't consider properly.

Tagging @Kwurqx  and moving the content here and closing that issue as we move to rack xt.

-------------
Even more oscillator wave shape shaping control would be great.

More flexible "shaping" options for the oscillator shape will give you countless custom waveshapes (with their own tuneable spectra). A great addition to (custom) wavetables, that have their own pro's and con's (e.g. finding/selecting/building them).

Surge already has several (many!) great oscillator shaping functions. Surge also already has the slider controls to control the shaping amount. And these slider are also a modulation targets. All great! But it could be even better!

Even some extra "simple" squeeze/stretch transformations in the Horizontal (Time) and Vertical (Amplitude) domain are great.

Maybe add extra shape distortion curves/functions as a modulator for the oscillator shape in time and/or amplitude domain. Or even allow custom shapes (via editor or import). Or even dynamically shapeable shaping shapes....

Anyway...

Of course there are infinite possibilities in Wave shaping shapes and functions. Even when just applying this to the amplitude domain. Sort of companding/distortion of the amplitude (vertical) domain of the wave shape. A common wave shaping/distortion function). Already implemented in Surge in some forms / signal path stages.

But of course this can also be applied to the time (horizontal) domain. Surge already offers this in some form too. With the right shape/function you can achive something "simple" as "PWM" of say an symmetric SAW into a asymetric SAW. By companding/distoring over the time domain. To visualize: where the zero crossing is shift left, compressing anything left of the zero crossing, expanding anything to the right.

Since the time domain is revlevant for both frequency and phase, you could als modulate phase to distort/shape a wave. Some words on that below in the "special" bit on FM/PM/PD.

In general, you can apply any wave shaping curve at any amount to the time and/or amplitude domain of the oscillator wave shape. Added control over the Oscillator Shape Wave Shaping curve (in the Oscillator section) would be great to. Some edit functions would be tops. But some clever presets would be great too. Or some "wavetable" like option, where you can morph between fixed shapes?

Random link to amplitude shaping

https://www.testandmeasurementtips.com/basics-of-amplitude-distortion-faq/
Some "special" waveshaping functions that might deserve a seperate feature request: Phase Distortion

https://en.wikipedia.org/wiki/Phase_distortion_synthesis
Peavy/Casio Phase Distortion.

"non-cyclic" shaping functions
https://theproaudiofiles.com/phase-distortion-synthesis/
Yamaha "FM" phase distortion wave shaping

phase modulating a 0 Hz carrier as offered by e.g. Yamaha SY77/99.
16 operator/modulator "cyclic" operator/modulator waveshapes
There have been some Korg implementations of FM/PM/PD too: Variable Phase Modulation (e.g. Prophecy, Z1). Trying to avoid the Yamaha FM patents.

Bowl of mixed fruit on FM/PM/PD:

https://www.perfectcircuit.com/signal/phase-distortion-frequency-modulation

**Comment by mkruselj** [comment]
To me, this issue is basically already covered with: #3273, #4847, #4627, #3619, #3670, #867. Kinda.

It's one of less helpful feature requests since it's unfocused and more of a "and a kitchen sink" sort of thing...

**Comment by baconpaul** [comment]
Yeah I just didn’t want to lose it and figured we would refactor it but also wanted to clean up the rack issues :)

**Comment by mkruselj** [comment]
Closing this as we have it covered with all of the above mentioned issues.
