### ISSUE TITLE
Show modulation of parameters (to give visual feedback how the Modulation Source is changing the Destination)

### ISSUE THREAD

**Issue by planist79** [surge-synthesizer/surge#6650]
Hi,

here is a Feature Request: Visualize the modulation of parameters as value changes of the sliders in modulation mode (= middle mouse click). 
Objective: This would give immediate visual feedback how the Modulation Source is changing the Destination, and which Destinations are changed by the Source..

_Example:
So, e.g. if the Cutoff slider is set to ~C5, and the Cutoff slider has a as modulation source LFO1, which is set to sine, bipolar and 1 Hz rate and 100% left/right (13 Hz/25000Hz). The grey/green line should move accordingly from full left/ full right to the center, back and forth._ 

Kind regards, 
Peter

**Comment by mkruselj** [comment]
We already have this tracked: #691, #3618. Closing this as duplicate.
