### ISSUE TITLE
"Latest" release

### ISSUE THREAD

**Issue by ThePython10110** [surge-synthesizer/surge#6653]
**Is your feature request related to a problem? Please describe!**
I would like to be able to download the latest installer for Surge from a Python program (which would basically install all my favorite software on a new computer). But since there is no release marked as "latest," I would have to change my code every time there was an update.

**Describe the solution you'd like:**
Many GitHub repositories have their latest release marked as "latest." It would be great (and AFAIK not particularly difficult) if this one did too.

**Comment by ThePython10110** [comment]
> a Python program (which would basically install all my favorite software on a new computer

By the way, the "favorite software" part was an intentional compliment.

**Comment by baconpaul** [comment]
https://surge-synthesizer.github.io/versions.xml

I just noticed the stable version is correct but the nightly is still 1.9 so I’ll fix thst today 

 It our ci pipeline updates that with the name of the directly downloadable asset each time we do a build.

**Comment by baconpaul** [comment]
And glad you like surge!

**Comment by baconpaul** [comment]
```
paul ~/dev/music/surge-synthesizer.github.io (master) % curl https://surge-synthesizer.github.io/versions.xml
<versions name="Surge Synthesizer">
  <license>https://github.com/surge-synthesizer/surge/blob/master/LICENSE</license>
  <website>https://surge-synthesizer.github.io/</website>
  <stable>
      <macOS>https://github.com/surge-synthesizer/releases-xt/releases/download/1.1.1/surge-xt-macOS-1.1.1.dmg
</macOS>
      <linux_x64>https://github.com/surge-synthesizer/releases-xt/releases/download/1.1.1/surge-xt-linux-x64-1.1.1.deb
</linux_x64>
      <win_x64>https://github.com/surge-synthesizer/releases-xt/releases/download/1.1.1/surge-xt-win64-1.1.1-setup.exe
</win_x64>
      <win_x86>https://github.com/surge-synthesizer/releases-xt/releases/download/1.1.1/surge-xt-win32-1.1.1-setup.exe
</win_x86>
  </stable>
  <nightly>
      <macOS>https://github.com/surge-synthesizer/releases-xt/releases/download/Nightly/surge-xt-macOS-NIGHTLY-2022-10-14-b999324.dmg
</macOS>
      <linux_x64>https://github.com/surge-synthesizer/releases-xt/releases/download/Nightly/surge-xt-linux-x64-NIGHTLY-2022-10-14-b999324.deb
</linux_x64>
      <win_x64>https://github.com/surge-synthesizer/releases-xt/releases/download/Nightly/surge-xt-win64-NIGHTLY-2022-10-14-b999324-setup.exe
</win_x64>
      <win_x86>https://github.com/surge-synthesizer/releases-xt/releases/download/Nightly/surge-xt-win32-NIGHTLY-2022-10-14-b999324-setup.exe
</win_x86>
  </nightly>
</versions>
```

There you go!
