### ISSUE TITLE
cmake stuck at "building juceide"

### ISSUE THREAD

**Issue by cuanyu** [surge-synthesizer/surge#6654]
I am trying to build surge on rpi 3B. After I" cmake -Bbuild -DLINUX_ON_ARM=True", rpi3 just freezes at "building jucetable" forever. Here is the output of the command:

pi@rpi3:~/surge $ cmake -Bbuild -DLINUX_ON_ARM=True
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- It's Surge XT, folks! Version is 1.1.0
-- CMAKE_BUILD_TYPE is Release
-- CMake version is 3.18.4
-- Compiler version is 10.2.1
-- Targeting 32-bit configuration
-- Setting -no-pie on EXE flags; use SURGE_SKIP_PIE_CHANGE=TRUE to avoid
-- Performing Test SURGE_ARCH_I386
-- Performing Test SURGE_ARCH_I386 - Failed
-- Performing Test COMPILER_HAS_AVX_OR_IS_ARM
-- Performing Test COMPILER_HAS_AVX_OR_IS_ARM - Success
-- Using JUCE from /home/pi/surge/libs/JUCE
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'alsa'
--   Found alsa, version 1.2.4
-- Checking for module 'freetype2'
--   Found freetype2, version 23.4.17
-- Checking for module 'libcurl'
--   Found libcurl, version 7.74.0
-- Checking for modules 'webkit2gtk-4.0;gtk+-x11-3.0'
--   Found webkit2gtk-4.0, version 2.34.6
--   Found gtk+-x11-3.0, version 3.24.24
-- Configuring juceaide
-- Building juceaide

The rpi3 is running 5.15.61-v7+ and is updated before the building. Is it simpliy because rpi3 is just too slow to handle building juceaide? Is it possbile to not to build juceaide at this stage?

What should I check for the issue of this problem? Thanks!

**Comment by baconpaul** [comment]
How long was forever? Did you give it 30 minutes? Was it taking cpu in the build?

I build on a rpi4b every now and then and the build is slow but finishes eventually. 

but also I think surge inky runs on 64 bit pi os 

you may have better luck with surge 19 which you can grab from a tag in this repo - it didn’t use juce (but also was missing loads of cool new things (but those new things may struggle in a pi3))

anyway it’s almost time to get my Christmas lights together so I will be booting my pi soon and will check head in a pi4 the

**Comment by baconpaul** [comment]
I did a build on a pi 4b 64 bit and juceaide took about 10 minutes but finished. I think you just need to be more patient. I'm going to close this since i had no problem building in a pi. if you get an error after an hour of waiting please reopen!
