### ISSUE TITLE
oscillator parameter sliders snap to a different value when first touched

### ISSUE THREAD

**Issue by aviwastaken** [surge-synthesizer/surge#6656]
1. Add a fresh instance of Surge XT
2. Set OSC1 to any type
3. Try and adjust an OSC parameter with the mouse
4. Some of the parameters will suddenly snap to a different value (from the default) as soon as the left mouse button is pressed

Particularly, this always happens with FM2 and FM3 Feedback, causing me great distress as it goes from 0% to -396% immediately, but I also found it occurs with most parameters in all oscillators, for example, all parameters of the String oscillator snap to some other value from what they were initially, except for Pitch. The values they snap to don't appear to be entirely consistent (other than FM2/3's remarkably consistent -396% Feedback) (nvm this time it snapped to -270% idk)

By setting the oscillator type to reset the sliders, this bug seems to reset and can be retriggered again, although some, like FM2/3's Feedback, would be seemingly cured and won't snap again until I initialize a new instance of Surge XT.

Doesn't appear to occur with any sliders outside of the OSC section.

Version: Surge XT 1.1.1.ecf7fe6
Build: 2022-08-25 @ 21:56:20 on 'WIN-KDGQ3UVP6AT/pipeline' with 'MSVC-19.29.30146.0' using JUCE 6.1.6
System: Windows 64-bit VST3 on Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
Host: Ableton Live 11 @ 44.1 kHz

**Comment by baconpaul** [comment]
Yeah it definitely is. I’m working on getting live set up so I can debug it

**Comment by mkruselj** [comment]
Closing this one as a duplicate, then.

**Comment by baconpaul** [comment]
Hi @aviwastaken i think I’ve found a workaround to this live behavior. Can you try the new nightly at https://surge-synthesizer.github.io/nightly_XT and if that works I can prep a 112 release with the fix after a bit more testing

**Comment by aviwastaken** [comment]
@baconpaul seems to fix it for me! (checked that the bug wasnt gone before installing the nightly as well)

**Comment by baconpaul** [comment]
Wonderful. I’ll do some testing and try to get a point release this weekend. Will also report the problem to our friends at ableton - live acts very differently than bitwig reaper etc and while I’m not sure they are wrong will definitely want them to know :)
