### ISSUE TITLE
Turn off things for 112 then revert 

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6661]
Turn off scope menu
Make cpu metrr off by default 
Merge
Release
Revert
Close this

**Comment by mkruselj** [comment]
Also add Shift-click on Save button to open dialog with tag entry to this list of things to turn off before release.

**Comment by synthriffsgirl** [comment]
I try to understand why this is needed?
Can somebody explain why features need to disabled just before a new release?

**Comment by baconpaul** [comment]
Because the features aren't finished and we want to release other features
