### ISSUE TITLE
manual: Dutch translation

### ISSUE THREAD

**Issue by ghost** [surge-synthesizer/surge#6665]
Hi!

I'm a woman speaking Dutch as native language.
I'm interested in translating the surge XT manual to Dutch.

However I have no knowledge of html, tools, compiling documentation, websites, ... 
So I only can use a text editor or a program like LibreOffice

Is there a way I can translate the text and provide the team with a LibreOffice document containing the translated text, so you can convert it to the right format to put online (like the English version)?
I will put in all pictures too and respect all paragraphs of the text, so you can exactly see where the text is located and it can be copy-pasted very easy for the person who will put it in the desired format.

Ps: please note I'm autistic and need VERY clear instructions on how to do this correctly (I mean the format to use for the translation. The translation itself is no problem as I have good English knowledge).
As a consequence of my autism, I don't like to go into chatboxes like Discord (real-time chat) so going to surge's Discord server is not an option for me.
So I prefer contacting on github here or if anybody wants to help me personally by email (to get me up-and-running) that's OK too.

Ps 2: I have a very strong dedication when I'm doing something. This means I want to keep updating my translation for updates.
Unfortunately I never worked with github and don't know how to do a PR, ... I'm actually a bit scared of doing something wrong.
If it's possible, I would like to give my translation here as an attachment so a contributor can submit it in the correct way.
Maybe if it's easy to do this on github (I never used github), I can try to do it myself.

So that's why I ask if somebody can 'guide' me here so I can contribute to this wonderfull project by translating the manual to Dutch.

Thank you
Lien

**Comment by baconpaul** [comment]
Welcome @synthvst great instructions @mkruselj  :)

**Comment by synthriffs-babe** [comment]
I have put this "on hold" because I don't have enough experience with Surge XT.
So it's better to translate it when I fully know everything.

**Comment by synthriffs-babe** [comment]
How would I know what added things are added to the manual, when the English version gets updated?
Can somebody explain me for the future?

**Comment by mkruselj** [comment]
This is done through pull requests. You can always see how our website is updated in the [commit log, here](https://github.com/surge-synthesizer/surge-synthesizer.github.io/commits/master).

**Comment by synthriffsgirl** [comment]
That was not what I mean :)
I mean: how to find out which lines are added or changed in the manual?
I can't compare my translation MD file line by line with the English MD file, update after update? That's crazy.
Or is this the way to do it?
If yes, then I'm not really interested anymore because the updating is then very time consuming.

**Comment by baconpaul** [comment]
Git shows diffs (changes) in the transaction log so you would use that to see what was changed, at the link above.
