### ISSUE TITLE
feature request: standard/advanced mode

### ISSUE THREAD

**Issue by synthriffsbabe** [surge-synthesizer/surge#6667]
**Is your feature request related to a problem? Please describe!**
I think everybody agrees Surge XT is becoming a synth swiss army knife of features which is good, but it's also a bit bad for beginners.
Why? Because it gets overwhelming when you want to learn then basic synth concepts. There are so many options it's hard for beginners to see the 'big picture' of how a synth works at basic level. I'm a beginner myself and I'm learning Surge myself by 'ignoring' the most advanced features (just to not have too much concepts to understand all at once) and then slowly learning those too, when I know the basics.

**Describe the solution you'd like:**
I would like to' request a feature that can set Surge into standard or advanced mode.

Standard mode allows changing the most basic features so Surge can be used as a learning tool for people wanting to learn digital synths or for people not needing the more advanced features. But Standard mode should make certain advanced options unavailable (disable the menu item or button so it requires not much code changes and the user just can't click it) so beginners are not 'lost' in the ever growing amount of features. 
Maybe limiting the number of parallel things too (or number of LFOs, ...)

Advanced mode should be Surge XT as it is now: all options and features enabled.

What does the dev team think of this?

**Comment by synthriffsbabe** [comment]
I also think a standard/advanced mode is not only good for beginners to limit the amount of features but also for users that just use Surge for the first time, even if they already know another synth. As the number of features grow, there should be a way to present only the basic features to a user because at one point, the learning curve will be too high if every feature is enabled (because of the 'overwhelming' feeling you can get).

This is just my opinion and I would like to hear the dev team's opinion.

Ps: please note I'm not saying the amount of features in Surge are bad! They are great but just this idea for the future in order to have a way to make new users not get overwhelmed.

**Comment by baconpaul** [comment]
This is a good but difficult to implement idea. We’ve talked about a player mode in a future version with just macros and patch browser for instance but which features are basic is not easy and a useful stripped back mode is hard to imagine. Plus we are all just having fun and adding features is more satisfying than turning them off :)

but your perspective as a new user is super valuable. Which things did you find most overwhelming when you approached the tool? That will definitely help us with future designs 

thanks for the input! And welcome!

**Comment by synthriffsbabe** [comment]
Compared to other synths having less features (or having those features not at all) I had troubles to understand:

- scene A and B and how they interacted
- oscillator settings with the sub-oscillators
- the FX schema and how to understand it
- the modulation list

**Comment by synthriffsbabe** [comment]
Also 2 controls were hard to find out to which setting they were referring to:

- the wave shaper of the filter configuration: here we see the little icon matching the filter configuration which we can make use of to identify it. But I would suggest moving the wave shaper next to the filter configuration

- the HP slider (next to wave shaper): i think this is the high pass filter at the end of the filter configuration but it's not at all intuitive to find this. Because the little icon (as IS used in the wave shaper) is not present. So this icon should be added and even better the slider should be located next to the filter configuration.

But of course this would change the UI a bit.
I think a filter configuration 'section' with wave shaper en HP slider next to it would be a better way.

The oscillator'routing part would then be moved to the oscillator 'section'
Now it's not really separated by oscillator/filter.

**Comment by mkruselj** [comment]
We plan to tackle this with #6225. Closing this one since it's a similar sort of idea.
