### ISSUE TITLE
request: linux appimage

### ISSUE THREAD

**Issue by synthriffsbabe** [surge-synthesizer/surge#6668]
**Is your feature request related to a problem? Please describe!**
I see there is a DEB and RPM file made for linux. Not being a Linux expert, but I really enjoy the comfort and ease of an appimage, see:

https://appimage.org/

For example I use it for LMMS.

https://lmms.io/

**Describe the solution you'd like:**
Maybe it's a good idea to provide an ampimage for Linux?
See the LMMS project as an example.
It would be also very handy for testing nightly builds since you don't need to install the appimage to run it.

**Comment by baconpaul** [comment]
I think (think) @KottV maintains an app image of xt in his obs farm. Am I correct?

**Comment by KottV** [comment]
@baconpaul I haven't builds of AppImage for surge. AppImage is for standalone apps only, no way to put a plugin with filesystem image. 
So I can make AppImage with standalone Surge-XT. If it makes a sense at all.

**Comment by synthriffsbabe** [comment]
Oh ok! Yes then it makes no sense I think :D

**Comment by synthriffsbabe** [comment]
I closed this because it's a useless request, now I understand how appimage works.
