### ISSUE TITLE
EG graphical editable ADSR points

### ISSUE THREAD

**Issue by ghost** [surge-synthesizer/surge#6669]
**Is your feature request related to a problem? Please describe!**
The ADSR of the EG seems to me a poor design of Surge's filters compared to other very intuitive settings.
Other synths use a graphical view in which you can drag with the mouse the ADSR points.
For example see Exakt Lite 

https://www.sonicbits.com/exakt-lite.html

**Describe the solution you'd like:**
It would be great if we could click the current EG graph and a bigger windows pops up with a Exakt Lite's similar bigger graph with editable (with the mouse) ADSR points so users can choose not to use the 4 sliders (which I don't think are user friendly controls here). Also immediate feedback in the graph is seen (which is now according to my understanding much harder to see in this small graph).
Maybe the ADSR sliders can be replaced completely in the future by this method?

**Comment by synthriffsbabe** [comment]
In addition I also think the current EG graph is too small even if it has no editable ADSR points.
I know it's a trade-off between what to show and how to fit it all in the UI but for'me the envelope graph is just too important to be so small.

**Comment by mkruselj** [comment]
I'd disagree that the 4 ADSR sliders are not user friendly - they are super well known from many, many synthesizers. Plus they would be way more precise to edit than moving dots on a graph. The graph only serves for choosing different curves for ADR stages, nothing else.

**Comment by synthriffsbabe** [comment]
How can I choose a graph in current Surge with the 4 sliders? No graphical feedback, no curve, nothing...
So it's clearly not user friendly. Did you try Exakt? Compare this to Surge.

**Comment by baconpaul** [comment]
If you want to do graphical editing of arbitrary envelopes the mseg has you covered. Evils point was - 4 sliders for adsr is a ui as old as the wind which works well. 

I suppose we could draw the envelope in that little area exactky or add an envelope preview window like we did for filter and cutoff and stuff. The later is especially idiomatic to the current ui. But no plans to do that

**Comment by synthriffsbabe** [comment]
Very funny. So you guys use a graph thatdoes NOTHING when editing the 4 ADSR sliders.
THEN REMOVE THE GRAPH IF IT IS DOING NOTHING...

**Comment by mkruselj** [comment]
It's not doing nothing in Digital envelope mode. Please read the manual.

**Comment by synthriffsbabe** [comment]
IT IS NOT DOING ANYTHING IN ANALOG MODE TOO
THE GRAPH IS A PIECE OF SHIT

IT SHOULD EITHER

_ UPDATE ACCORDING TO THE SLIDERS WHICH IT DOES NOT 
_ HAVE A GRAPH EDITABLE WITH THE MOUSE

NOT THIS SHIT YOU HAVE RIGHT NOW

**Comment by synthriffsbabe** [comment]
FUCK YOU LOSERS

**Comment by synthriffsbabe** [comment]
> Your caps lock tone is not appreciated, as well.

YOUR UGLY FUCKFACE IS NOT APPRECIATED AS WELL

CHANGE THE ADSR GRAPH SO IT WORKS IN A MODERN GREAT WAY INSTEAD OF USEING 4 SLIDERS
LAZY FUCKFACE

**Comment by synthriffsbabe** [comment]
THE GUI IS A FUCKING GAZ FACTORY AND YOU GUYS KEEP ADDING STUFF

*NO PERSON ON EARTH* WILL EVER UNDERSTAND IF YOU CONTINUE LIKE THIS

FOLLOW MY ADVICE OR BURN IN HELL!!!!!!!!!!!!

**Comment by synthriffsbabe** [comment]
STICK THE SHIT UP YOUR ASS
I DONT USE SURGE ANYMORE
DO WHAT YOU WANT 
NOBODY LISTENS HERE

**Comment by mkruselj** [comment]
You've had good chance to get what you want until you started abusing capslock and resorting to abusive language. Now this won't happen.

Thousands of people have no problems with using Surge.

**Comment by tranceriffsbabe** [comment]
1. I USE CAPS WHERE I WANT
2. IT IS ALREADY HAPPENING SINCE I COPIED THE SOURCE CODE AND WORKING ON SURGE PRO, MY OWN VERSION WHICH WILL HAVE A GLORIOUS ADSR GRAPH AS CAN BE SEEN IN EXAKT LITE...
3. YOU ARE STILL A FUCKFACE AND HAVE NOTHING TO SAY ABOUT ME OR WHAT I DO

FUCK YOU SURGE LOSERS

**Comment by tranceriffsbabe** [comment]
SURGE PRO WILL HAVE A STANDARD AND ADVANCED AND PERFECT FOR BEGINNERS

SOON THE WEBSITE WILL BE PUT ONLINE AND I WILL D E S T R O Y SURGE XT ...

**Comment by tranceriffsbabe** [comment]
I AM TRANCE RIFFS BABE
N O B O D Y MESS WITH ME

**Comment by tranceriffsbabe** [comment]
I EAT EVIL DRAGONS FOR BREAKFAST
