### ISSUE TITLE
my apologies: please read private message on KvR forum

### ISSUE THREAD

**Issue by synthriffs-babe** [surge-synthesizer/surge#6670]
Hi

What happened here on github?
To @baconpaul  and @mkruselj : please read private message on KvR forum

I hope i'm allowed back on github. I really want to report bugs or propose ideas. I use Surge XT each day , it's really great!
(I was the person that wanted to translate the manual too)

Feel free to delete this issue, just for explanation.
To @baconpaul  and @mkruselj: my apologies.

**Comment by mkruselj** [comment]
As long as things are kept polite and sociable, everyone is welcome. Feel free to continue discussion regarding manual translations [here](https://github.com/surge-synthesizer/surge-synthesizer.github.io/issues/182).

**Comment by synthriffsgirl** [comment]
Yes, sorry, you know the reason why it happened :(
I do my best to become a member of the community: I want to test ,report bugs and share my opinion on the UI more specificly.

**Comment by synthriffsgirl** [comment]
YOU KNOW WHAT
SUCK MY FUCKING CLIT

YOU GUYS
_ DONT USE TABS
_ DONT ACCEPT ANY IDEAS
_ ....

I AM MAKING MY OWN SYNTH USING QT, TABS AND COMBINING CODE FROM SEVERAL SYNTHS OUT THERE

AND IT IS CLOSED SOURCE AND I DONT PUT IT ONLINE

I DONT USE YOUR SHIT ANYMORE
