### ISSUE TITLE
Scale LFO/EG separate outputs by amplitude optionally

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6674]
The raw outputs don't take amplitude into account

They probably should but that will break old patches so

1. Add a toggle and a menu
2. Maybe update patch version and have the new default be true

**Comment by Andreya-Autumn** [comment]
Agree, both seem good.

**Comment by baconpaul** [comment]
So I have this coded but @mkruselj and @Andreya-Autumn an opinion

Should this setting/option be per LFO or per patch.

I have coded it as per LFO but that makes it hard to change an entire patch.

Everything else (default, scale, extend, option) works without problem. But as I was going to write the streaming code I thought: do I want to stream this 12 times or 1?

I have my code stashed away in baconpaul/lfo-scale-6674 and once we decide above it is 30 minutes to close this issue

My gut is "per patch" is right.

**Comment by mkruselj** [comment]
It should per LFO IMO.

**Comment by Andreya-Autumn** [comment]
Agreed. Default to on, turn-offable per LFO seems best to me.

**Comment by mkruselj** [comment]
It should default ti off to retain existing behavior.

**Comment by Andreya-Autumn** [comment]
Is that necessary you think? It should be off for saved patches obviously. But beyond that I'm not sure we need to stay consistent here.

**Comment by mkruselj** [comment]
We should for the XT1 cycle at least. We did so far for pretty much all other cases, always kept existing behavior as default.

**Comment by Andreya-Autumn** [comment]
We didn't for the mono retrig-from-current behavior, but admittedly the new behavior is more obviously "better" in that case. 
I feel like this change is also for the better. But I'm not attached, if y'all disagree let's keep current default until XT2.
