### ISSUE TITLE
Tabs for controls

### ISSUE THREAD

**Issue by synthriffsgirl** [surge-synthesizer/surge#6675]
**Is your feature request related to a problem? Please describe!**
The problem is that Surge XT is getting more and more features.
Everything is jammed in 1 window, which will:

- give no overview anymore
- create overwhelming feeling for beginners or not experienced users
- give less space to nicely put the widgets in place. We can already see this in current Surge XT. The window is completely filled...
- at a specific moment leave no space anymore AT ALL to add things. You can't keep adding drop down menus or things to trying to put everything in an already extremely filled window

**Describe the solution you'd like:**
A tab for each controls category: one for oscillators, one for LFOs, one for filters, ...
=> in this way a dedicated window with a lot of space is available for those widgets
=> you don't have all other things on the screen when modifying something (no need to see oscillators when you're changing a filter etc)
=> no overwhelming feeling
=> future proof: many features can be added and the UI is not a gaz factory full of widgets in 1 screen
=> you switch to a tab when you need to change the controls, it's nice and used in many software because it's a good solution

The only disadvantage is that you NEED to switch tabs when changing a control in another category.
But the disavantages of using NO tabs are the ones above. Much more ...

Thanks for reading

**Comment by synthriffsgirl** [comment]
In addition to this, I wanted to ask some questions about the use of JUCE to quickly understand how/what.

- what UI framework did the original Surge use before it was ported to JUCE?
- what where the reasons it was ported?
- is the current UI made by a UI designer that can drag and drop widgets to visually build it with minimal code required?
- are the current widgets standard JUCE widgets or are there custom widgets too?
- what other UI frameworks were considered when looking for a good choice when JUCE was chosen and why was JUCE the best choice?

**Comment by baconpaul** [comment]
> In addition to this, I wanted to ask some questions about the use of JUCE to quickly understand how/what.
> 
> * what UI framework did the original Surge use before it was ported to JUCE?

vstgui

> * what where the reasons it was ported?

because of many bugs and shortcomings in vstgui

> * is the current UI made by a UI designer that can drag and drop widgets to visually build it with minimal code required?

no

> * are the current widgets standard JUCE widgets or are there custom widgets too?

custom

> * what other UI frameworks were considered when looking for a good choice when JUCE was chosen and why was JUCE the best choice?

myriad reasons why juce was the best choice, including widespread use in the audio field, completeness, portability, accessibility, open source compatibility, and a strong team

**Comment by mkruselj** [comment]
Adding more tabs is directly against the design philosophy that Claes Johansson initially set up with Surge. Surge is all about minimizing the amount of tabbing the user has to do! And we do intend to keep it that way. As mentioned before, we will have a player mode for beginners, #6225, but we won't slow. down the main edit interface by introducing even more tabs, that would make it a completely different synth, that wouldn't be Surge anymore.

**Comment by synthriffsgirl** [comment]
Ok! IF the goal is to have all in 1 window (which I didn't know) then of course it can be a strong idea too: you have direct access to everything.

**Comment by synthriffsgirl** [comment]
Ok, so I close this. It's the opposite of what Surge's goal is and not desired.

**Comment by mkruselj** [comment]
> then of course it can be a strong idea too: you have direct access to everything.

That is _exactly_ what Surge is all about!

**Comment by synthriffsgirl** [comment]
YOU KNOW WHAT
SUCK MY FUCKING CLIT

YOU GUYS
_ DONT USE TABS
_ DONT ACCEPT ANY IDEAS
_ ....

I AM MAKING MY OWN SYNTH USING QT, TABS AND COMBINING CODE FROM SEVERAL SYNTHS OUT THERE

AND IT IS CLOSED SOURCE AND I DONT PUT IT ONLINE

I DONT USE YOUR SHIT ANYMORE
