### ISSUE TITLE
Dedicated Settings window

### ISSUE THREAD

**Issue by synthriffsgirl** [surge-synthesizer/surge#6676]
**Is your feature request related to a problem? Please describe!**
I see now settings are scattered across some menu item checkboxes (and maybe somewhere else)
This is not easy to find where everything is set. Also you need to open the menu and submenus to edit a setting.
So i'm talking about the "menu" and the many submenus for settings.
It should go into a settings window with tabs for each submenu.

**Describe the solution you'd like:**
A dedicated settings window (with tabs) that groups all settings in categories. The user can change everything in one place. 
=> you have an overview of all settings

=> quicker acces to all settings in one place: you don't need to go to a menu to change a checkbox there. Sometimes changing a setting requires you to open the "menu", then another submenu and ANOTHER submenu inside the previous one... (a lot of steps until you reach the setting AND you can't see which settings are in the submenus too without going through all of them...)

=> the "menu" can then be shrinked to essential things you can run/load when surge is running. But the real settings you can choose (mostly the checkboxes of the "menu") are in a dedicated settings window, that has tabs for each setting's category (as now are the submenus). It's faster (choosing a tab is faster then opening another menu with the mouse) and more organized.
Each submenu of the "menu" can become a tab. All submenus of the parent menu will be inside the same tab. So this makes all settings of a specific category in 1 tab, giving you immediate overview what settings there are and how they are currently set.

=> maybe an export file format for the settings can be made that can be imported in case you install surge on a new PC (the user can save his/her settings to a file. Probably the amount of settings will grow when new features are released and at some point it would be nice to export it to a settings file for Surge XT)

Solution:
- So the "menu" should be used for things you can run/load when working with Surge but not for real settings you choose.
As Surge gets bigger, this settings window will even be more useful because we don't want a big amount of menus with submenus in the "menu"...
- So the "menu" can contain an item "Settings" that opens the settings window when clicked.
This window has tabs to group the different categories of settings (as now are the submenus)
- this reduces the amount of submenus in "menu" and groups all settings of a category on one tab in a dedicated settings window: you open settings and go to the desired tab. No more switching submenus (with even more submenus inside...)

Thanks for reading
synthriffsgirl

**Comment by baconpaul** [comment]
This is a good idea and one we've discussed although not written up.

A few comments

1: Even with the settings overlay keeping context specific settings menus is a good idea
2: The current settings mechanism already makes a portable file so there's no need for export; It's in %DOCUMENTS%/Surge XT/SurgeXTUserSettings.xml or some such.

But an overlay with organized total view of settings is something I think would be useful.

**Comment by synthriffsgirl** [comment]
THE MENUS SUCK
NOBODY WANTS TO GO OPEN A MILLION MENUS WITH SUBMENUS JUST TO CHANGE A SETTING

YOU KNOW WHAT
SUCK MY FUCKING CLIT

YOU GUYS
_ DONT USE TABS
_ DONT ACCEPT ANY IDEAS
_ ....

I AM MAKING MY OWN SYNTH USING QT, TABS AND COMBINING CODE FROM SEVERAL SYNTHS OUT THERE

AND IT IS CLOSED SOURCE AND I DONT PUT IT ONLINE

I DONT USE YOUR SHIT ANYMORE
