### ISSUE TITLE
Translation of UI

### ISSUE THREAD

**Issue by synthriffsgirl** [surge-synthesizer/surge#6677]
**Is your feature request related to a problem? Please describe!**
People not speaking English can be confused already by the specific synth terminology (if they are a beginner). So it would be nice if the UI is in their own language while specific synth terminology stays in English (oscillator, ...). This is especially for the "menu" settings. 

**Describe the solution you'd like:**
Translation of the UI. I don't know if there are plans for this but if there are, I can do translation to Dutch and French (as I speak both languages)

**Comment by synthriffsgirl** [comment]
I don't know JUCE but I think it has built-in class:

https://docs.juce.com/master/classLocalisedStrings.html

**Comment by mkruselj** [comment]
We don't use that class at all, and this would be a tremendous amount of work. However we did discuss it internally at a few points. As it stands it's not the most immediate priority.

**Comment by baconpaul** [comment]
The primary problem is lots of strings are baked into the SVG assets; translating the displayed strings is actually pretty reasonable (and would involve a class like that) but making every string in the SVG set a dynamic string rather than a rendered one is a massive amount of work

That said for XT2 / ShortCircuit I've been thinking about exactly this and that widget/UI set would allow us to do so, depending how we lay out the rendered assets.

**Comment by synthriffsgirl** [comment]
You could only translate the menu strings. The strings in the UI itself are mostly staying in English too (oscillator, LFO, ... doesn't have to be translated).

**Comment by baconpaul** [comment]
yes and other things like "Save" or "Menu" would also need translating; there's definitely dynamic elements.

Plus, of course, theres 600 params which would need translating.

the string set for the synth is not small. I'd have to be convinced someone was actually going to translate all the strings to add the infrastructure to let them do so, honestly.

**Comment by synthriffsgirl** [comment]
YOU KNOW WHAT
SUCK MY FUCKING CLIT

YOU GUYS
_ DONT USE TABS
_ DONT ACCEPT ANY IDEAS
_ ....

I AM MAKING MY OWN SYNTH USING QT, TABS AND COMBINING CODE FROM SEVERAL SYNTHS OUT THERE

AND IT IS CLOSED SOURCE AND I DONT PUT IT ONLINE

I DONT USE YOUR SHIT ANYMORE

**Comment by baconpaul** [comment]
Sorry you are blocked forever.
