### ISSUE TITLE
Per channel parameter modulation not working

### ISSUE THREAD

**Issue by Xenakios** [surge-synthesizer/surge#6680]
**Bug Description:**
Surge XT publishes parameters for per-channel modulation in the Clap plugin version. However those don't actually currently work per channel.

I can see a couple of ways to handle this :

1) Make Surge not publish parameters as supporting the per-channel modulation. Not preferable but at least hosts could avoid in that case showing any per-channel modulation options for the user.
2) If possible, make the parameters actually work so that the Clap note event channel is taken into account.

**Surge XT Version**
Latest nightly

* Version:
* Plugin Type: Clap
* Bitness: 64-bit

**Computer Information (please complete the following!):**
 - OS: Windows 10/Mac Os
 - Host: Custom host

**Comment by baconpaul** [comment]
Link to #6799 which is really the solution here
