### ISSUE TITLE
Linux: first time use help

### ISSUE THREAD

**Issue by linuxsynth** [surge-synthesizer/surge#6684]
Hi everybody,

First, thanks for all the work on this amazing synth!

I'm a Linux beginner, and I use Ubuntu.

I have installed this file surge-xt-linux-x64-1.1.2.deb but now I don't know how I can run the standalone Surge.

Also I don't know where the VST files are copied in order to use them in my DAW LMMS.

I hope somebody can help.

**Comment by linuxsynth** [comment]
I was also wondering if there can be made some explanation in the manual specificly for Linux (that answers my questions above)

**Comment by baconpaul** [comment]
The executable should be in usr bin 
The product ships with a vst3 and clap neither of which lmms natively supports - you need to use a bridge and I think Carla may do that but I don’t know how.

**Comment by linuxsynth** [comment]
Hmm ok :(
I don't have the knowledge to install Carla. But I found Ubuntu Studio exists which has another Linux DAW installed, Ardour.

https://ubuntustudio.org/tour/audio/

Does Ardour support Surge out of the box?
Which Linux DAW does support Surge and what DAW you use to test the Linux version of Surge?

**Comment by baconpaul** [comment]
Almost every daw except lmms has vst3 support. On Linux ardour qtractor and zythian are foss and reaper and bitwig are excellent commercial daw offerings

**Comment by baconpaul** [comment]
Almost every daw except lmms has vst3 support. On Linux ardour qtractor and zythian are foss and reaper and bitwig are excellent commercial daw offerings

**Comment by linuxsynth** [comment]
Thanks!
Can you finally tell me where I have to look for the VST files of Surge and what are their file names?
I don't find the folder to be honest.

**Comment by mkruselj** [comment]
The DAW should already be set up to scan for VST3 plugins, you shouldn't need to do anything. Maybe if the DAW doesn't do it automatically on startup, try to find an option in the DAW to rescan plugins.

**Comment by linuxsynth** [comment]
Ok I see. I try to find out
What is the default installation folder where the Surge VST files are copied to on linux when you installed it using the .deb file on the Surge website?

**Comment by baconpaul** [comment]
Usr bin for the stand-alone and usr lib vst3 for the plugin iirc

**Comment by linuxsynth** [comment]
Do you know if the LV2 plugin of Surge works in LMMS?

**Comment by mx** [comment]
> Does Ardour support Surge out of the box?

This could actually be mildly complex depending on how the Debian package works.

Ardour does support VSTs. However, it expects files to have a ".vst" extension. Surge's VST has a ".so" extension by default in the build process. So you may need to do some renaming.

**Comment by linuxsynth** [comment]
> This could actually be mildly complex depending on how the Debian package works.
And can you check this package, because I see you are a contributor?
I just installed it but until now I don't see Surge appearing in Ardour. I use Ubuntu Studio with pre-installed Ardour.

> Ardour does support VSTs. However, it expects files to have a ".vst" extension. Surge's VST has a ".so" extension by default in the build process. So you may need to do some renaming.

So the file contents is the same, it's just another extension?
Can you tell me the exact files I need to rename and in what folders they are?

**Comment by linuxsynth** [comment]
What Linux DAW is used to test the official Surge Linux version?
Is it normal you rename the files to .vst in any DAW or is this just the case for Ardour?
(I think it's a bit weird)

**Comment by mx** [comment]
> And can you check this package, because I see you are a contributor?

No, I do not use Debian or a Debian-based system. I have no connection to whoever makes the packages. I am only recounting my experience from testing Surge in a DAW a long time ago.

**Comment by baconpaul** [comment]
Is this still the case with the vst3 bundle @mx ?

To answer your question @linuxsynth i test surge in reaper and bitwig, sometimes in juce audio plugin host, and rarely on ardour. I use ububtu lts versions. I know other members of the surge community use ardour regularly and use arch 

the dev should just drop it in usr lib vst3 and it will scan. That has worked for most users but Linux distros are varied

**Comment by baconpaul** [comment]
also make sure your distro isn't using an old ardor. Ardour has only had vst3 support working in the last year or two iirc. So ardour versions like 6.1 or some such will definitely not work properly.

**Comment by haenkel** [comment]
Surge loads and runs succesfuly in a current **ardour** version, without renaming.
You would have to compile that version yourself though, 
which I don't recommend if it is your first compiling adventure.
Your pre-installed ardour is an older version so the mentioned renaming workaround
may or may not work for you.

More linux hosts that defenitly run the surge-xt plugin are:

**qtractor** 
https://sourceforge.net/projects/qtractor/files/

**carla**
https://kx.studio/Applications:Carla#Download
(which is a standalone host that also installs itself as vst,
so you can try loading carla in **lmms** and then load surge in the carla plugin.
I've never used lmms but have heard of people doing it that way)

**BespokeSynth**
(which we are not allowed to call a daw :)
but it runs the surge vst3 just fine)
https://software.opensuse.org//download.html?project=home%3Abespokesynth&package=bespokesynth

**reaper**
https://www.reaper.fm/download.php
(which you can use 60 days for free)

there is more, but this is what i've tested in debian/ubuntu-based and arch-based distros.
one of these should get you there

**Comment by linuxsynth** [comment]
Hi

Thanks for the overview!

As a beginner in Ubuntu,compiling is not for me...

Why is Ubuntu Studio not providing latest Ardour you think?

Do you know if a DAW run as an AppImage on linux can load any plugins, since an AppImage is not installing anything ?
Or does this not matter?

**Comment by haenkel** [comment]
- distros lock software versions for a number of different reasons
  for a more exact answer you would have to ask ubuntu-studio
- an appimage can load plugins
  the one thing you may have to do is allow it to execute
 which if you don't use the terminal you can set via rightclick/properties/permissions

**Comment by linuxsynth** [comment]
Is there a Surge forum?
It seems to me that could be very usefull with sticky posts about things that are asked a lot.
For example my topic here.

I don't like discord

- people are talking at the same time and it becomes a mess
- answers dissapear since it's scrolling

So not good for help according to me

**Comment by baconpaul** [comment]
No

**Comment by linuxsynth** [comment]
Is it not a good idea for a forum?
It can serve as an addition to the manual with sticky posts of questions asked a lot or for tutorials of users, etc etc

**Comment by mkruselj** [comment]
We already have enough communication outlets to moderate, what with GitHub, Discord and the KvR thread in Instruments section. So, no. we don't feel like we need a forum.

**Comment by haenkel** [comment]
https://linuxmusicians.com/
maybe another helpful place (and forum) for you.
It also covers general linux audio and beginner questions, 
which is an area that can be somewhat "out of scope" for this issue tracker.

**Comment by linuxsynth** [comment]
FUCK YOU UGLY MOTJERFUCKER

**Comment by baconpaul** [comment]
user blocked as abusive. closing issue.
