### ISSUE TITLE
video tutorial

### ISSUE THREAD

**Issue by linuxsynth** [surge-synthesizer/surge#6687]
Hi

Is there maybe a user or developer interested in making youtube video tutorials on all important parts of Surge (separate video for each topic)?
I noticed the learning curve is very big (because of the incredible amount of features) and therefore the manual is less usefull then video demonstrations I think.

Just a question!

**Comment by baconpaul** [comment]
This 2 hour 22 minute masterpiece covers (almost) every part of the synth

https://www.youtube.com/watch?v=kTvBgb4HGx0&t=6211s

there's other good more targeted tutorials if you just search Surge XT on youtube, but the garron one is the most comprehensive.
