### ISSUE TITLE
Virtual keyboard shortcuts configuration

### ISSUE THREAD

**Issue by jpggithub** [surge-synthesizer/surge#6688]
In Surge XT, the shortcuts configuration could be enhanced.

Example 1: The Surge XT manual precises: "Note: Some actions in Surge XT are done by doing Alt + Drag or scroll wheel. On certain Linux distributions, those shortcuts and gestures may cause conflicts between Surge and the desktop environment. We decided we couldn't give up alt-drag for all platforms because one window manager in one distribution used it by default. Therefore, it's often possible to disable that global gesture in desktop environments, and would be the easiest way to solve that possible issue."

In fact, when we use a desktop environment and other applications with their own requirements, wo don't always want to change our shortcuts for just one application, even if it is Surge XT that we love a lot!

On Linux, the key "Alt" in Surge could be changed by the "Windows" key for example but it should always be a user choice.

Example 2: On my desktop environment, the "Shift + F10" does not work and this combination can't be changed in the shortcuts configuration panel while it is an important shortcut.

Example 3: How can we configure the keys of the virtual keyboard? By trials and errors, I discovered that "}" and "c" are my keys to change the octave, that "a" give a C note, and so on. Perhaps i could be configured somewhere but I didn't found where.

Example 4: Some people use DVORAK or other keymap that fits their needs. All the shortcuts often needs to be configured to have a pleasant experience.

Long live to Surge XT! 

Configuration: Debian Linux, XFCE desktop environment, BÉPO keymap.

**Comment by mkruselj** [comment]
We currently don't offer support for changing virtual keyboard keys...

Also, JUCE doesn't support Windows key so we cannot use it to replace Alt.

**Comment by baconpaul** [comment]
Adding Shift-F10 to the configuration as opposed to having it in the accessibility set is a good idea though; and we should do that.

I do wonder if we could paint the keybindings on the vkeyboard somehow also.

but yes we don't have Dvorak support. That goes in the camp of 'would be thrilled to merge it, but don't think I will code it personally' if you happen to be a dev.

**Comment by mkruselj** [comment]
IIRC JUCE does offer capability to remap individual VKB keys, so we should def add that to keyboard shortcuts overlay.
