### ISSUE TITLE
[RFE] On Linux, changing the name of the binary "Surge XT"

### ISSUE THREAD

**Issue by jpggithub** [surge-synthesizer/surge#6689]
On Linux, the custom is not to have spaces in the name of the executable file because it causes all sort of problems especially when you want to use it in a script or when you use completion in a terminal. Also the use of upper case letters is not very frequent.

Perhaps you could consider to change the name of the file "Surge XT" by something like "surge-xt" or "surgext".

**Comment by mkruselj** [comment]
We have agreed internally we won't be changing the name of the binary just for a single platform, IIRC.

**Comment by baconpaul** [comment]
yeah it was a long argument but space is a valid character so we kept it. Thanks for the comment though!
