### ISSUE TITLE
It would be nice to have an oscillator for one shot samples.

### ISSUE THREAD

**Issue by TheGuyWhoo** [surge-synthesizer/surge#6698]
While it is not necessary since we have audio input, having to rely on the audio input means we can't package sounds that use samples as presets. Surge is an ideal synth for creating drum sounds, the only issue is it's a bit of a bother to layer in noise and attacks and so on.

**Comment by mkruselj** [comment]
As mentioned previously, wavetable oscillator will do this if you just drop a raw wav file that has no wavetable related metadata, Surge will play it as a oneshot...

**Comment by TheGuyWhoo** [comment]
In this case, it would be nice to be able to tell surge to ignore that metadata when you want to use the wavetable osc as a sampler. What specific format does the file have to be for surge to treat it as a sample?

**Comment by baconpaul** [comment]
Any I tagged wav file will load as a one shot

just take a drum hit wav and drag it on

although it is not the same as a sampler it will work for attack shaping and the like

**Comment by TheGuyWhoo** [comment]
What is an untagged wav file? Sorry if that's a stupid question, but it seems pretty random to me which files are loaded as a sample or wavetable.

Yeah ultimately though it would be nice to have a osc specifically dedicated to loading one shots, as opposed to an osc that is both depending on the format.

**Comment by TheGuyWhoo** [comment]
It's a fair suggestion and something I would consider, but it does require you to either have a bunch of duplicates or replace the samples with a different format, which is definitely not ideal imho.

**Comment by baconpaul** [comment]
yeah if your samples are marked with loops and cues now and you want them as one shots you have to do 'something' to them outside of surge. Remove the loop/cue markers etc

and even when you do that, you probably will be dissatisfied with the one shot playback.

**Comment by TheGuyWhoo** [comment]
Something like the sampler in vital would be a very welcome addition to surge, that's my 2 cents at least.

**Comment by baconpaul** [comment]
yeah i hear you!

i keep thinking, once we get shortcircuit up and running, maybe there's a place for a stripped down single sample player. but i'm not sure it's a great idea. you aren't the first to say it is a good idea though!

**Comment by TheGuyWhoo** [comment]
Maybe there can be some kind of communication between surge and shortcircuit where you can have presets for the combination of them, so that one preset stores all of your settings in both surge and shortcircuit. Don't think I've ever heard of plugins that do this, though.

**Comment by TheGuyWhoo** [comment]
Maybe there can be some kind of communication between surge and shortcircuit where you can have presets for the combination of them, so that one preset stores all of your settings in both surge and shortcircuit. Don't think I've ever heard of plugins that do this, though.

**Comment by baconpaul** [comment]
nah i was thinking much simpler - just have a new oscillator type that does sample playback, but base it on the code in shortcircuit that does all the stuff shortcircuit does.

maybe? i dunno some people like that idea for surge and others hate it. both have good arguments.

**Comment by TheGuyWhoo** [comment]
That would be good too haha. At the end of the day everyone can have their way. Using a different sampler and just piping it into surge isn't such a big deal, it's really just a matter of convenience.

**Comment by mkruselj** [comment]
For more info: https://github.com/surge-synthesizer/surge-synthesizer.github.io/wiki/Overview-Of-Wavetables-In-Surge

**Comment by mkruselj** [comment]
Closing this issue as it is basically covered by #1069.
