### ISSUE TITLE
Surge standalone hangs on launch on Mac

### ISSUE THREAD

**Issue by halfbeing** [surge-synthesizer/surge#6709]
Surge standalone hangs on launch on my Mac. 

Version: Surge XT 1.1.2.d3568a9
Build: 2022-11-01 @ 14:28:23 on 'Mac-1667312250086.local/pipeline' with 'AppleClang-13.0.0.13000029' using JUCE 6.1.6
System: macOS 64-bit AU on Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
MacOS 13.0 (22A380)

When I double-click on the Surge XT icon in Finder, the Surge icon appears in the Dock and soon starts jumping up and down, and it gets labelled "not responding" in Activity Monitor. No GUI appears. "Force quit" is the only way to stop it.

Surge works fine, however, as an AU plugin in Ableton Live 11 (which is where I copied the version info from).

**Comment by baconpaul** [comment]
I have a couple of thoughts but my best guess is you somehow got corrupted standalone settings, since the AU works.

Can you try removing the file `~/Library/Application Support/Surge XT.settings` (if you need help doing that let me know but just remove it in a terminal is fine) then restart the standalone. If that doesn't work I have a few other ideas but this is the most likely I bet.

**Comment by halfbeing** [comment]
~/Library/Application Support/Surge XT.settings doesn't exist. If it ever existed, maybe it got deleted when I purged Surge XT using AppCleaner and then reinstalled it. But as far as I can remember, I never managed to get standalone Surge XT to start.

**Comment by baconpaul** [comment]
@halfbeing this is the only report of this we have had; wondering if the latest production version (1.2.3) starts up for you successfully on your system in standalone?

**Comment by halfbeing** [comment]
> @halfbeing this is the only report of this we have had; wondering if the latest production version (1.2.3) starts up for you successfully on your system in standalone?

I still get the same issue. This was after removing Surge XT and Surge XT Effects with App Cleaner and then installing the latest version.

**Comment by baconpaul** [comment]
OK! Well are you able to use terminal? There's a couple of favors you could do me

In a terminal type `/Applications/Surge\ XT.app/Contents/MacOS/Surge\ XT` and let me know if anything happens

If it is hung, leave it running and in a second terminal do this

`ps -ef | grep Surge`

You will see something like this

```
  501 23075 50039   0  9:45AM ttys001    0:01.48 /Applications/Surge XT.app/Contents/MacOS/Surge XT
  501 23126 23080   0  9:45AM ttys003    0:00.00 grep Surge
```

but you will have different numbers. Read the second number by the /Applications line (here 23075) then type

```
kill -3 23075
```

where you replace `23075` with the number you saw

This will force a crash dialog to open.  Copy the text and paste or attach it here. Then I can at least see where you are hung up.

**Comment by halfbeing** [comment]
> then type
> 
> ```
> kill -3 23075

kill -3 won’t do it. I have to do a kill -9.

**Comment by baconpaul** [comment]
One other thought

If you grab the latest nightly and install it, then type

```
/Applications/Surge\ XT.app/Contents/MacOS/surge-xt-cli --list-devices
```

does it work?

**Comment by halfbeing** [comment]
Good news!  1.3.nightly.448b4ef starts up fine. Thank you!

For information: I think I waited a minute or more in vain yesterday for
kill -3 to do its stuff before I did kill -9.

**Comment by baconpaul** [comment]
ok great!
So 1.3 has moved to JUCE 7. I wonder if some combination of your OS, your audio device, and JUCE 6 caused the hang

Unfortunately the software that would let me diagnose this would only work with JUCE 7, which doesn't show the problem :)

I'll close this issue - thanks for responding. And 1.3.nightly will become a production release sometime this fall. (The nightly is pretty stable if yo udon't use the new features of course, but the new features could break, and we have had bugs in the nightly in this cycle. If you are doing commercial or archival DAW work you probably want to run 1.2.3 for everything except the standalone).
