### ISSUE TITLE
request: trance supersaw preset

### ISSUE THREAD

**Issue by tranzedude** [surge-synthesizer/surge#6712]
Hi

Thanks for the awesome work on Surge XT!!!

I would like to request (I'm not experienced enough) if somebody can add in the next update a trance supersaw preset.
The only thing I know is that it uses 2 or 3 oscillators (saw of course) but I don't know how to construct it together.
Would be nice to have an example preset in included in Surge.

Thank you!

**Comment by mkruselj** [comment]
Please search among the included 2800 patches there's bound to be something of the sort in there already!

**Comment by tranzedude** [comment]
It's not in there. I checked all.

After a long time, I finally was able to make a Trance Supersaw.
Can you add it in the next update please? See attachment

[SuperSaw.zip](https://github.com/surge-synthesizer/surge/files/10115455/SuperSaw.zip)

**Comment by tranzedude** [comment]
Will you add it in next release?
