### ISSUE TITLE
MPE enabled by default

### ISSUE THREAD

**Issue by gexahedron** [surge-synthesizer/surge#6716]
Hi, I'm running SurgeXT in Supercollider, and it always opens with MPE disabled by default. From what I see, it's also not possible to set it through SurgeXTUserDefaults.xml file, and it's not in the list of parameters. When I open Surge XT as a standalone app, though, it remembers the MPE setting.
Is it right now possible to set it somehow to be enabled by default?

**Comment by mkruselj** [comment]
You can send the necessary RPN message to Surge to enable MPE remotely.

See https://d30pueezughrda.cloudfront.net/campaigns/mpe/mpespec.pdf

**Comment by gexahedron** [comment]
Thanks! Second approach is suitable for me. (For reference: it's savePreset and loadPreset in VSTPluginController),
I'll close the request then : )
