### ISSUE TITLE
Virtual Keyboard does not display key presses with CLAP plugin

### ISSUE THREAD

**Issue by rmt** [surge-synthesizer/surge#6720]
**Bug Description:**

When using the CLAP plugin, Surge XT's virtual keyboard does not highlight key presses.

Everything seems to work fine otherwise.

**Surge XT Version**

1.1.2 (1.1.makepkg.d3568a9ae on ArchLinux)

* Version: 1.1.2
* Plugin Type: CLAP
* Bitness: 64bit

**Reproduction Steps:**
1. Add SurgeXT CLAP plugin to a track on Reaper or Bitwig under (Arch)Linux
2. Enable Virtual Keyboard
3. Play MIDI controller and watch virtual keyboard not be highlighted

**Expected Behavior:**

The keys on the virtual keyboard should be highlighted, same as in the VST3 plugin.

**Computer Information (please complete the following!):**
- OS: Arch Linux
- Host: Reaper & Bitwig 8 track
- Version: Latest

**Comment by baconpaul** [comment]
Oh thank you. My theory is the custom clap process loop just factored wrong and we only update on the juce side.

**Comment by baconpaul** [comment]
Right so `SurgeSynthesizer::applyMidi` does 

```
    auto m = it.getMessage();
    const int ch = m.getChannel() - 1;
    juce::ScopedValueSetter<bool> midiAdd(isAddingFromMidi, true);
    midiKeyboardState.processNextMidiEvent(m);
```

`CLAP_EVENT_MIDI` calls that so if you are using the CLAP in pure midi mode (which bitwig will not) they keyboard will light up.

So basically the `CLAP_EVENT_NOTE_ON` and `_OFF` (and `_CHOKE`) branches need to mock up a midi message and apply it to the keyboard state. Should be an easy fix.

**Comment by baconpaul** [comment]
Yup that's exactly it. have the fix together and will be i nightly soon.
