### ISSUE TITLE
Windows Lato-Semi-Bold is too bold

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#673]
I picked a slightly bolder font on windows than mac due to render differences when I was working. Seems those render differences are a function of parallels VM and the font looks a bit too bold on windows. Back it down from lato-semi-bold to lato-regular in time for 1.6. beta6. Reported by @sense-amr

**Comment by sense-amr** [comment]
it is pretty damn bold .. to be honest :)
