### ISSUE TITLE
vst.preset to FXP file?

### ISSUE THREAD

**Issue by dylaness** [surge-synthesizer/surge#6735]
Hi, I have all these old .vstpresets made on linux surge, and want to load them into the windows surge.  it seems to takesonly FXP files though.

![image](https://user-images.githubusercontent.com/119985571/206068402-996103a4-1619-47f9-a273-2ed50b8ea9d9.png)

![image](https://user-images.githubusercontent.com/119985571/206067740-4e9b2b3a-bb46-4619-8636-c61fcd8ccc9d.png)

**Comment by baconpaul** [comment]
you must have used some other host software to make those; surge itself has never written or read vst preset files. Did you save them with reaper or bitwig or something? You probably need to import them using the same

**Comment by dylaness** [comment]
Yep I see now 
![image](https://user-images.githubusercontent.com/119985571/206365052-379f8288-d8ef-4458-8524-dbc54a8f19da.png)
![image](https://user-images.githubusercontent.com/119985571/206365114-73056610-3ad6-43ed-a5ca-19fb852e9d87.png)

I imported .vstpreset files into reaper, but get this error when loading. I'm guessing ill have to log back into linux, re save the presets as fxp files.

**Comment by mkruselj** [comment]
Closing the issue due to lack of activity. @dylaness always welcome to comment back in this issue, but there's nothing to fix here on Surge side.
