### ISSUE TITLE
Unison is snapped at note trigger

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#674]
It's not clear this is a bug but it seems bug-like. This one may get tagged as 1.7+ after I do some research.

@sense-amr reports that the unison count only adjusts if you retriever a note.

Set a unison to 2 with a big spread. Play a note. Move the slider. unison stays at 2. Play the note again and the unison is where you have it.

So you can sort of see how this would happen - integers aren't modulatable in surge so it is snapped at voice creation. But since we can modulate everything externally it's not clear it is what we want.

So go read surge voice and see how it routes changes to underliers and stuff and see if there is a more straight forward fix. But this one could be tricky.

**Comment by sense-amr** [comment]
I should clarify @baconpaul i didnt say the count doesnt advance .. i said the effect of the unison increasing its voices .. doesnt occur untill the next retrigger of the note .. that is to say the slider shows count up but the effect of that increased voice to unison is not heard or actioned untill the note is retriggered..!

**Comment by baconpaul** [comment]
Yeah that’s exactly right. If you change unison while a note is sounding using whatever mechanism the note does not change. Sorry to not make that clearer

**Comment by mkruselj** [comment]
I don't think this is possible to do without some sort of artifacts when changing it during an active voice.

The only plugin that I have that can do this live update of unison stacks is Synapse Audio Dune 3, and it also has minor artifacts while doing so. It's also not a modulatable target.

**Comment by baconpaul** [comment]
if you were to do it either you would have pops or you would have to detect a new unison and crossfade. I've sort of left this lurking open in case someone ever wants to do the later, but it would be quite a lot of work since, as you know, each oscillator implements unison independently.

**Comment by baconpaul** [comment]
We should close this as a never do
