### ISSUE TITLE
FX section Delay/Chorus = Delay only 

### ISSUE THREAD

**Issue by sense-amr** [surge-synthesizer/surge#675]
After looking through the FX section scrutinizing various aspects of it with @itsmedavep and @oddy.o.trax
I discovered something which i had noted before but not thought much of .. 

The Delay/Chorus section.. actually NEVER shows Chorus and only ever delay .. regardless of any preset that is selected .. 
![delaychorusneverchorus](https://user-images.githubusercontent.com/1504019/53465730-397bb680-3aa3-11e9-89c5-0da9174dcf0f.jpg)

in the above picture i selected the wide chorus preset effect.. as you can see no indication of it being selected is present in the UI...and to the contrary the UI displays that i have selected a DELAY not a CHORUS.. effect..

Whilst understanding clearly that technically a "Chorus" is just a delay with modulation.. we consider that it might be useful to have it explicitly separated for the user .. 
 
We propose as a fix.. that the Chorus related FX be moved to a separate Chorus related dropdown .. which will populate in the dropdown .. as Chorus .. and  "CHOR or CHRS" in the box area.. 

thoughts?

**Comment by esaruoho** [comment]
this is fixed by #676 - @baconpaul pls review when you have the time.

**Comment by sense-amr** [comment]
and now an adendum to the previous observation..

there appears to be a DELAY/CHORUS .. and a separate CHORUS .. in the FX section..
Incidentally the separate CHORUS selection results in [MOD] in the box .. 
hmm now this is the question is the CHORUS fx section different to the DELAY/CHORUS .. if so how and why ? .. 

seems a bit redundant to include in the DELAY/CHORUS section considering there is already a CHORUS section ..

**Comment by esaruoho** [comment]
closed #676 since not what's wanted

**Comment by sense-amr** [comment]
looking further into this i discovered that Chorus and Delay/Chorus are separate modules in the fx section as these images show. 

![chorus](https://user-images.githubusercontent.com/1504019/53476807-6215a780-3ac7-11e9-97a0-dd005c02d92d.jpg)
![delaychorus](https://user-images.githubusercontent.com/1504019/53476808-6215a780-3ac7-11e9-9d37-a7e9b578b1cc.jpg)


So bearing this in mind.. it would definitely be something to look into as to why the Chorus presets are housed within the Delay/Chorus section as @esaruoho has noted .. its probably incorrect placement of those presets.. but also bearing in mind they are separate FX sections with slightly different layouts....

**Comment by baconpaul** [comment]
Hey @esaruoho did your sweep fix all the stuff in this issue or is there other stuff here also?

**Comment by esaruoho** [comment]
@baconpaul nope, i killed the bits in my PR (where would've moved delay/chorus's chorusFX to chorus-subfolder) - since the chorusFX in Delay/Chorus subfolder made sense to stay in Delay/Chorus subfolder.

**Comment by sense-amr** [comment]
but i still dont know what "Delay/Chorus" is ?

**Comment by esaruoho** [comment]
> but i still dont know what "Delay/Chorus" is ?

well, delay/chorus has delays, some of which also have chorus. there's a delay-like slapback / echo on the chorus-delays, too. they wouldn't really necessarily fit in with Chorus category, because they also use delay, instead of being raw&pure chorus.

**Comment by baconpaul** [comment]
Gotta say @esaruoho your answer doesn’t exactly clear it up for me either :)

So are some of the settings in “Delay/Chorus” basically making a chorus using a delay; and all of the settings in chorus making a chorus using a chorus? Is that it?

“Delay/Chorus” is a wierd name though.

**Comment by sense-amr** [comment]
yeah i still don't get it i mean a chorus with a delay is still a chorus .. but a delay with out chorus , is it just a delay ?

**Comment by baconpaul** [comment]
I agree. Why not move the chorus-made-with-delay to the chorus folder and then have this just be delays?

**Comment by baconpaul** [comment]
OK there is a super stupid reason why we can't do the obvious thing of moving the chorus-with-delay to the chorus menu which means we will stick with Delay/Chorus for a little until we do a code change

Right now the structure of the XML which guides the menu is

```
  <type i="2" name="foobaz">
     <snapshot p0=... name="my thing"/>
  </type>
```

All the elements contained inside that type menu have the modulator or oscillator type of the container.

So moving the delays to chorus section means they don't use the delay DSP effect any more so don't work.

The fix is to optionally check for the type on the snapshot itself so you can override it. That would happen at CSnapshotMenu around line 70.

May actually not be that hard to code up. Lemme give it a whirl.

**Comment by baconpaul** [comment]
So that C++ code to allow an i= per item was actually super duper easy.

@esaruoho can you beat up on the branch in PR #777 a little and see what you think? Would be nice to get this into beta 7 and I tested it quite a lot.

Thanks
