### ISSUE TITLE
AudioUnit with mono mapping choices crashes or is silent 

### ISSUE THREAD

**Issue by Yooplaboom** [surge-synthesizer/surge#6751]
**Bug Description:**
Hello, I just installed Surge XT on my MacBook Air 2014 (Big Sur). And no sound is coming because of "Audio output unavailable".

**Surge XT Version**

* Version: Surge XT 1.1.2
* Plugin Type: VST3, AU
* Bitness: 64-bit

**Reproduction Steps:**
1. Go to 'Open Surge XT'
2. See error 'Audio output unavailable'

**Expected Behavior:**
I expected Surge XT to produce sounds.

**Screenshots:**
![Surge XT - Audio output unavailable](https://user-images.githubusercontent.com/121051337/208484658-e1d0f713-33cd-41eb-932c-6ef03d5de037.png)

**Computer Information (please complete the following!):**
 - OS: Big Sur
 - Host: Logic
 - Version: 10.7.4

**Additional Information:**
Thank you by advance !

**Comment by baconpaul** [comment]
So not to be rude but - is audio output available? Like is logic set up to generate sound, and the track is powered on and routed to an output and stuff? Your core audio is attached to an output device and surge is routed to it?  If you replace surge in that track with (say) retro synth does it make noise?

that message appears when the host never calls our process method which indicates that there is no audio running.

**Comment by Yooplaboom** [comment]
Normally everything is set up to produce sounds. I tried with different outputs (internal speakers, bluetooth) and it still doesn't work. But for other synths it works (from Logic or others brands).

**Comment by baconpaul** [comment]
Oh that’s interesting. Obviously it shouldn’t crash but that makes more sense. Let me rename this issue and tag it into the next release

**Comment by Yooplaboom** [comment]
I precise that my Logic version is totally legit :)

**Comment by baconpaul** [comment]
OK confirmed that 1xmono gives you no audio out and 3x mono gives you a crash in LPX with the AU

I think what I should do is just not make those mappings available in the AU.

**Comment by baconpaul** [comment]
<img width="419" alt="Screen Shot 2023-01-08 at 2 48 35 PM" src="https://user-images.githubusercontent.com/13387561/211215859-f5c18fb4-4b52-4126-b6be-ec61975c7870.png">

Yup there we go
