### ISSUE TITLE
Surge XT VST3 Menus crash Reason 12 Ventura (patched; reported to Reason)

### ISSUE THREAD

**Issue by oimseng** [surge-synthesizer/surge#6752]
**Bug Description:**
Surge XT was promoted by Reason Studios during its VST3 update. The synth crashes Reason 12 almost instantly however on my machine. I have a Macbook Air M1 running Ventura 13.0.1 (22A400). Reason is running in Version 12.5d29 and build 14528.

**Surge XT Version**
Version: Surge XT 1.1.2.d3568a9
Build: 2022-11-01 @ 14:28:23 on 'Mac-1667312250086.local/pipeline' with 'AppleClang-13.0.0.13000029' using JUCE 6.1.6
System: macOS 64-bit VST3 on Apple M1 (Using Rosetta)
Host: Reason @ 44.1 kHz / 32 Sample Surge Block

* Version:
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Open a an empty reason song
2. Add Surge XT
3. Click in the first Filter slot
4. Reason crashes to Desktop
5. Reason produces Warning that it crashed.
6. Reopen Reason
7. Load Surge XT
8. Click on anything but the filter slot
9. Works as expected.
10. click in the filter slot
11. Reason Crashes

**Expected Behavior:**
No crashing when accessing functions in Surge XT.

**Screenshots:**
non available

**Computer Information (please complete the following!):**
see description

**Additional Information:**

**Comment by baconpaul** [comment]
Does the standalone run? Or the AU in GarageBand? I’m wonde4ing if it is reason or Ventura or both.

**Comment by oimseng** [comment]
Only tried the VST3 version as I currently don't have an AU Host installed on my system. I will file a request there as well, from what i see in the crash report of reason the plugin produces an authentication failure which results in a bad kernel access erorr or something like that. Trying to locate the crash report.

**Comment by mkruselj** [comment]
Surge is not authenticating anything, though...

**Comment by oimseng** [comment]
Where can I find the crash logs from a certain app on Ventura?

**Comment by baconpaul** [comment]
Probably in the console application. 

Also the standalone doesn’t require an au host. Does that run?

**Comment by oimseng** [comment]
Here is the Reason Crash Log.
[Reason-2022-12-20-010604.pdf](https://github.com/surge-synthesizer/surge/files/10268354/Reason-2022-12-20-010604.pdf)

**Comment by oimseng** [comment]
Will try to install and run it standalone tonight. Thanks for analysing the crash log.

**Comment by oimseng** [comment]
Yes I just sent them a bug report and included the link to this issue. Hoping they reach out soon. They promoted Surge XT in their latest update video and thats why I tried it out again after a few years. Yes I try to click on the UI element "box" for the first filter slot. When it crashes it once I tried to click there. Other parameters seem to be not as crash prone as the filter box.

**Comment by baconpaul** [comment]
Yeah I have tried to reach em through another route also but more help always helps!

**Comment by mkruselj** [comment]
Yeah looks like Reason people are not implementing the VST3 menus feature of it.

**Comment by baconpaul** [comment]
Right but it shouldn't crash!

I'll see if I can get an NFR and look but @oimseng can you let them know that the problem really seems to be we are trying to use their VST3 menu extensions and it crashes (or maybe has a bad lifetime?)

**Comment by oimseng** [comment]
Thanks for your replies. I will add this to their ticket. Hope they reach out soon for all of us :)

**Comment by oimseng** [comment]
Hi there, haven't heard from them, looks like I posted the bug into the wrong entry channel that is for third party developers only. Have you heard back from them?

**Comment by baconpaul** [comment]
I just submitted the NFR request today so have not heard yet. Will update here if I do hear anything.

**Comment by oimseng** [comment]
Ok let's wait and see. Hope they reach out. Guess they used the vst2 version in their video, can't imagine it just crashing like that on my machine only.

**Comment by baconpaul** [comment]
Maybe they didn’t use Mac

we don’t have a vst2 version. If the bug is what I think it is it could also be os specific.

**Comment by oimseng** [comment]
Hi Paul,
just let me know if I can do anything further, if you have an alpha built or anything i should test I am all open for it.
Thanks anyway for the awesome communicatio.

**Comment by oimseng** [comment]
Have you heard back from them?

**Comment by baconpaul** [comment]
I have not yet no. 
let me check my junk folders tho

**Comment by baconpaul** [comment]
Yeah nothing but they may also be short staffed this week. I opened my ticket dec 22

I will ask again in the new year

**Comment by baconpaul** [comment]
The team has been back in touch and I am getting set up with Reason and their dev portal and stuff now. I don't know how long it will take me to get it diagnosed and reported, but just an update that something is happening (and they've been super friendly now they are back from holidays!)

**Comment by baconpaul** [comment]
<img width="181" alt="Screen Shot 2023-01-03 at 8 45 15 AM" src="https://user-images.githubusercontent.com/13387561/210369335-c1c2719b-197c-4ff1-9a93-72ed530b2ec4.png">

So running this version of reason I don't see a crash on surge menu

Can you let me know exactly how you make it crash and if you see the crash with that version?

Thanks!

**Comment by oimseng** [comment]
Hi Paul
yes I can reproduce the crash on my system.

1. Start Reason with a blank song
2. Drag Surge XT into the Rack panel of Reason
3. Open Surge XT instrument Editor in Reason.
4. Play a couple of Midi Notes.
5. While Playing or shortly after last played note select the filter menu drop down in Surge XT.
6. Reason Crashes.

**Comment by mkruselj** [comment]
And what is the exact version of REason you're running?

**Comment by oimseng** [comment]
n 12.5d29 and build 14528 same as yours

**Comment by baconpaul** [comment]
thanks - let me poke at it a bit more.
and 'filter menu' is menu to select a filter or some other menu?

**Comment by oimseng** [comment]
Yes sorry its the drop down menu to the left of the label Filter 1 Once I click there it crashes.

**Comment by baconpaul** [comment]
hmm ok i can't make it crash with those gestures here. i'll have to dig more. but that all works fine for me with surge.

**Comment by oimseng** [comment]
just did it again and it crashed reason immediately

**Comment by oimseng** [comment]
Here's part of the newest log:

Crashed Thread:        0  MainThread  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000c93d9ae5b288 -> 0x0000493d9ae5b288 (possible pointer authentication failure)
Exception Codes:       0x0000000000000001, 0x0000c93d9ae5b288

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [78324]

VM Region Info: 0x493d9ae5b288 is not in any region.  Bytes after previous region: 80047904240265  Bytes before following region: 25024175689080
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      commpage (reserved)        1000000000-7000000000   [384.0G] ---/--- SM=NUL  ...(unallocated)
--->  GAP OF 0x5f9000000000 BYTES
      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-/rwx SM=PRV  

Kernel Triage:
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage


Thread 0 Crashed:: MainThread Dispatch queue: com.apple.main-thread
0   Surge XT                      	       0x12b0e534a juce::JuceVST3EditController::EditorContextMenu::getEquivalentPopupMenu() const + 618
1   Surge XT                      	       0x12b0ed7e8 SurgeSynthEditor::hostMenuFor(Parameter*) + 104
2   Surge XT                      	       0x12b19186d SurgeGUIEditor::controlModifierClicked(Surge::GUI::IComponentTagValue*, juce::ModifierKeys const&, bool) + 56333
3   Surge XT                      	       0x12b264b92 Surge::Widgets::MenuForDiscreteParams::mouseDown(juce::MouseEvent const&) + 482
4   Surge XT                      	       0x12b4e21e1 juce::Component::internalMouseDown(juce::MouseInputSource, juce::PointerState const&, juce::Time) + 625
5   Surge XT                      	       0x12b5af158 juce::MouseInputSourceInternal::setButtons(juce::PointerState const&, juce::Time, juce::ModifierKeys) + 744
6   Surge XT                      	       0x12b4e7b11 juce::MouseInputSourceInternal::handleEvent(juce::ComponentPeer&, juce::Point<float>, juce::Time, juce::ModifierKeys, float, float, juce::PenDetails) + 369
7   Surge XT                      	       0x12b592192 juce::ComponentPeer::handleMouseEvent(juce::MouseInputSource::InputSourceType, juce::Point<float>, juce::ModifierKeys, float, float, long long, juce::PenDetails, int) + 210
8   Surge XT                      	       0x12b5e604f juce::JuceNSViewClass::asyncMouseDown(objc_object*, objc_selector*, NSEvent*) + 367

It crashes when opening that menu.

**Comment by baconpaul** [comment]
Do you have any particular reason settings which would expand the menu? I see the two reason additional items there and they work fine which means I can run that code without a crash. I wonder what’s different between your and my setup

**Comment by oimseng** [comment]
ehm what kind of settings, i am not aware of any settings for the expand menu function, is there such a thing?

**Comment by baconpaul** [comment]
I used reason for the first time in my life 11 hours ago! So I have no idea :)

im just trying to understand what could be different between your test and my test since I can’t make it crash

**Comment by oimseng** [comment]
Ha ha and I use it for 20 years and I am like, what is he talking about :)

**Comment by oimseng** [comment]
The funny thing is it happens with this particular handler all other menus work
just as soon as I touch that one, reason is gone :)

**Comment by oimseng** [comment]
happens with filter 2 menu as well
checked I dont' see any settings i could make

**Comment by baconpaul** [comment]
Oh so it is *just* filter not cutoff or pitch or anything else?

**Comment by oimseng** [comment]
only with the two filter menu drop downs so far.

**Comment by baconpaul** [comment]
OK well I'm out of time today alas but will keep looking this week. Thanks for help!

If you know any other reason 12 users would love an independent confirm of the bug too. Is it anomalous that it works for me or crashes for you would be a useful bit of data.

**Comment by baconpaul** [comment]
I also asked in various synth communities to see if i can find another reason 12 mac user.

**Comment by oimseng** [comment]
Yes of course, that would be nice. I reckon this is rather a specific case, as the Plugin was advertised on the update video I guess you would have had way more bug reports if this was a global fault.

No worries, thanks for your help.

**Comment by baconpaul** [comment]
Maybe! But also the vst3 api is a nightmare in many ways so it may be we can get a cleaner bug report to reason so not giving up. 

I think also since vst support in reason is new we don’t have a big community overlap so right now I would just say it is 50/50 there’s a general problem. Bayes helps with reaper but not reason basically

so let’s keep at it!

**Comment by baconpaul** [comment]
(Just not today :) )

**Comment by esselfortium** [comment]
Hmm, it's working for me in Reason 12.5d29 on macOS 11.4 on an Intel Mac:

![](https://cdn.discordapp.com/attachments/753313514977755317/1060237443288289410/image.png)

**Comment by baconpaul** [comment]
Yeah that’s what I see also. And if you pick automate it adds a lane in reason rack right?

**Comment by oimseng** [comment]
Yes exactly that's how it works in Reason. You mentioned the two additional reason items, what were you referring to there?

**Comment by baconpaul** [comment]
Those last two menu items are added to surge by reason. In bitwig and reaper the menu is different. And that’s the api which the crash points at

**Comment by oimseng** [comment]
Ok but interesting thing, so why does it work for some and for some not. My machine is a m1 based macbook air.
Whats your's where it is running ok?

**Comment by baconpaul** [comment]
Few other thoughts 

1. what’s your surge version from about 
2. Do you have your Mac set to something other than us english? I wonder if there’s a utf8 thing maybe?

**Comment by oimseng** [comment]
Hi there,
Surge Version is following:

Version: Surge XT 1.1.2.d3568a9
Build: 2022-11-01 @ 14:28:23 on 'Mac-1667312250086.local/pipeline' with 'AppleClang-13.0.0.13000029' using JUCE 6.1.6
System: macOS 64-bit VST3 on Apple M1 (Using Rosetta)
Host: Reason @ 44.1 kHz / 32 Sample Surge Block

Mac is set to Switzerland (German)

**Comment by baconpaul** [comment]
Ok in Swiss German do the reason menus contain any diacritical marks? I guess I can try and set my mac to that later

**Comment by oimseng** [comment]
Nothing i can see, its normal german the only thing that the swiss setting differes from the german setting is the keyboard layout.

**Comment by baconpaul** [comment]
I don't get the crash in swiss german so that probably not it. hmm

**Comment by oimseng** [comment]
Well its strange...I mean why should the code behave differently you are checking the Vst3 version of this right?

**Comment by oimseng** [comment]
did a reinstall of the vst today no change still crashes upon first click in that menu

**Comment by baconpaul** [comment]
I just saw you are using Rosetta. I didn’t check if I was but wonder if that’s it?

**Comment by oimseng** [comment]
Well as Reason is still running via Rosetta there's nothing you can change about this.

**Comment by baconpaul** [comment]
yeah. hmmm

well if i can't actually repro it i can't figure out what to do obviously. Do you have Xcode installed? I wonder if you could do a debug build of the synth and see if we get more information?

**Comment by oimseng** [comment]
Yes I know, working in Software development myself...
No I swept this of my machine long ago, not enough space left for that to install

**Comment by baconpaul** [comment]
right

well its a bit of a pain for me to send you a debug build but lemme think about a good way to do that perhaps?

i'll take a look at the code next week when i'm inside surge and see if I see anything else it could be also.

sorry to not have a better answer!

**Comment by mkruselj** [comment]
> M1 Max MacBook Pro running 12.6

Right so I'm thinking we have 3 Mac users in this thread. You're on 12.6, esselfortium is on 11.4 and OP is on Ventura. So maybe Ventura is the culprit?

**Comment by baconpaul** [comment]
oh right. interesting. that is a very good guess.

**Comment by oimseng** [comment]
Ah ok, that could be something, I am on Ventura thats true. Don't worry, it's ok, I mean I don't have any pressure, would be cool to solve this and actually be able to use the synth but no worries and no stress.

**Comment by oimseng** [comment]
Just realised I should update to Ventura 13.1. haven't done this yet. Will try this and report back if that changes anything.

**Comment by baconpaul** [comment]
Great

We have a ventura user in our community and he reports that ventura + reaper + surge that menu doesn't crash.

So we have narrowed to the window of error down to "ventura + surge + reason + rosetta" at the widest and "something about your setup other than that" at the narrowest.

Appreciate all the updates here. Wonder what it will turn ut to be.

**Comment by baconpaul** [comment]
Confirmation btw is that 13.2 public beta reaper both arm and rosetta work with surge.

**Comment by oimseng** [comment]
Updated to 13.1, still the same immediate crash.

**Comment by baconpaul** [comment]
OK I've found a person in my network who has ventura and surge but they have an older reason. They are going to try and upgrade their reason this weekend or early next week and see what happens.

**Comment by baconpaul** [comment]
OK so amazing news. It's not just you. My colleague who has ventura and reason 12 tells me he gets a crash in exactly the same spot you do.

**Comment by baconpaul** [comment]
So there's two things I can do

I can add a user setting to not use VST3 menus which you could turn on; and
I can make a debug build with some logging information

I can't get to those tonight but it's a good "next step" plan. The first would at least let you run the nightly without this crash.

**Comment by baconpaul** [comment]
OK! So my colleague (who is also an audio dev) did a debug build and found that, yes, reason 12 on macOS 13 is returning a bad pointer from this point of the VST3 API.

He added

```
juce::PopupMenu SurgeSynthEditor::hostMenuFor(Parameter *p)
{
    if (juce::PluginHostType().isReason())
        return {};
```

and the feature was gone but so was the crash. So what I'll do is

1. Put that in the hostMenuFor etc... functions and build a nightly. You can grab that and use surge 
2. Open a bug report with the Reason beta program (which I'm part of) so they know there's a problem and they can use surge 1.1 or a hand build to test it

should be able to do 1 this weekend. I'll then rename this issue but leave it open in case reason team looks at it

Thanks for your patience.

**Comment by baconpaul** [comment]
OK step 1 was pretty easy to do and to test so I have it in. Since you are in switzerland and I assume you are not reading GitHub at 3am your time, when you wake up you should be able to grab a new nightly and have it work for you.

https://github.com/surge-synthesizer/releases-xt/releases/tag/Nightly

**Comment by baconpaul** [comment]
OK I've also reported this to reason in their beta program. So I think it is in their hands now.

Thanks for your patience. Let me know if the nightly works!

**Comment by mkruselj** [comment]
Ideally Reason fixes this on their side and we don't need to have a per host query to remove the feature...

**Comment by baconpaul** [comment]
> Ideally Reason fixes this on their side and we don't need to have a per host query to remove the feature...

Yes

**Comment by oimseng** [comment]
Ha thank you guys so much, works :) Can access the menu, yay 🥇 . Awesome now I can explore the synth finally.

**Comment by baconpaul** [comment]
Great. I'm going to leave this open until at least I hear back from the Reason beta bug report team, but glad it works for you now. Enjoy surge!

**Comment by baconpaul** [comment]
Moving this to "currently unscheduled" as there's nothing we can do about it until we hear back from Reason now.

**Comment by oimseng** [comment]
Awesome, thanks again for your support!

**Comment by luzpaz** [comment]
Anyway to bump upstream Reason ticket ?

**Comment by baconpaul** [comment]
Oh reason reported back to me this is fixed in their betas a month or so ago. But I didn’t check. Someone needs to grab latest turn on the menus and see.  Lemme bump this into 13 so I remember

**Comment by mkruselj** [comment]
I'll push a PR enabling the menus for Reason a bit later and ask @esselfortium to test.

**Comment by baconpaul** [comment]
@mkruselj you tested this in reason right and it worked? So lets close this.

**Comment by mkruselj** [comment]
I haven't but a friend did. And yes, let's 🙂
