### ISSUE TITLE
It is not possible to switch patches with Ctrl+arrows in CLAP

### ISSUE THREAD

**Issue by Lo-lo78** [surge-synthesizer/surge#6762]
**Bug Description:**
With the CLAP version of Surge XT the shortcuts ctrl+arrows to change the patch don't work.
**Surge XT Version**
This information is found on the About screen, which you get to from the bottom right menu.
surge-xt-win64-NIGHTLY-2022-12-30-0b4e951
* Version:
* Plugin Type: [VST2, VST3, AU]
* Bitness: [32-bit or 64-bit]
§Surge XT CLAP 64-bit
**Reproduction Steps:**
2. Click on '...'
3. Scroll down to '...'
I open Surge XT and enter the Plugin and use the shortcuts CTRL+left arrow and CTRL+right arrow to switch patches and it has no effect.
**Expected Behavior:**
I expect CTRL+arrows to work in the CLAP version as well.
In the VST3 version It works.
**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following!):**
 - OS: [e.g. Windows 10]
 - Host: [e.g. Bitwig, Logic, Cubase, Reaper]
 - Version: [e.g. 2.4]
Windows 10 22H2 (x64) build 19045.2364
Reaper 6.73. 64-bit
**Additional Information:**

Thank you and happy 2023!

**Comment by mkruselj** [comment]
What happened here? Did you manage to get these to work in the end?

**Comment by Lo-lo78** [comment]
@mkruselj 
Yes, I hadn't activated the Reaper function:
"Send all keyboard input to plug-in"
It was my mistake.
Sorry!
