### ISSUE TITLE
Oscilloscope: Final 1.2 signoff

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6778]
@mx and @mkruselj - what's needed on the scope for us to ship a 1.2?

**Comment by mkruselj** [comment]
Ah I should do some UI work on the overlay...

**Comment by mx** [comment]
On my end nothing. I might add a high-definition variable-frequency mode since the CQT didn't work out but that's not necessary to ship.

**Comment by baconpaul** [comment]
Cool
Are we actually using pffft in the codebase right now by the way? If not I may turn off the sub-build before I ship 1.2 then turn it on again after (but will see!)

**Comment by baconpaul** [comment]
Things I noticed

1. Tearout at zoom needs a resize
2. The scope doesn't remember waveform vs spectrum setting when saved and open/closed

**Comment by baconpaul** [comment]
<img width="730" alt="Screen Shot 2023-01-24 at 9 27 43 PM" src="https://user-images.githubusercontent.com/13387561/214467068-cbead3d4-bbbd-4e6b-b325-be5325188dbe.png">

The controls not appearing is only in spectrum view. I think the spectrum view should grow to fill since there's no control

Also we should probably draw the spectrum gradient filled like everything else.

**Comment by mx** [comment]
The plan is to eventually add some controls (I have some prototype ones
that don't do anything) which is why I haven't expanded it to fill yet.

**Comment by mkruselj** [comment]
Dooooooneeeeeeee #6903!

...except maybe we want right-click context menu entries to point to manuall?

**Comment by baconpaul** [comment]
Do we have manual entries for the scope yet? Its pretty easy to add to the paramdocumentation.xml if there's a target.

**Comment by mkruselj** [comment]
I have added #level-meter to paramdocumentation.xml (for the ? menu entry in level meter's right-click context menu), but yeah we should indeed add right-click menus to all scope parameters just like MSEG editor has, too...

**Comment by Andreya-Autumn** [comment]
...and with https://github.com/surge-synthesizer/surge-synthesizer.github.io/pull/302 I have now given it a place to land in the manual. So I do believe we're finally ready. :)

**Comment by Andreya-Autumn** [comment]
ED counters: "If you use RMB menus on trigger mode or scope mode it changed value but doesn't update GUI", so re-opening.

**Comment by Andreya-Autumn** [comment]
...which is adressed by #6921, so closing again. :)
