### ISSUE TITLE
Lato font locked access - plugin doesn't load on Windows (beta-5)

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#678]
This one is for @baconpaul.

![image](https://user-images.githubusercontent.com/2393720/53490868-1813ce00-3a95-11e9-9066-ac7fc3b6228a.png)

Long story short, seems there's an issue in loading Lato font on Windows, which makes the VST not loadable at all. Solution would be to install the font to the system, and this is how:

https://stackoverflow.com/questions/28186646/install-fonts-to-pc-using-inno-setup

**Comment by baconpaul** [comment]
Couple this with checking the font installation at runtime using enumfontfamyex and we should be good
