### ISSUE TITLE
In reaper, macOS, menus hang around too long and so it crashes

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6796]
Open Surge UI in Reaper
Open patch browser.
Flick your mouse around there a bunch.
CMD+W to close ("all keyboard to plugin" must be off)
Repeat the above until you get the bug (pretty consistent for me)
The menu will linger, and moving the mouse over the options will paint them.
Crash happens when you paint the last one.
That's 100% repeatable here.

**Comment by baconpaul** [comment]
This no longer happens for me. @Andreya-Autumn you and i both saw this for a while but now I don't with the nightly and latest reaper. Can you see it happening?

**Comment by Andreya-Autumn** [comment]
I see the menu hang, but no longer crashes.

**Comment by Andreya-Autumn** [comment]
Here's more details: I haven't updated to Reaper 6.77 yet, I'm on 6.75

The VST3 won't do the thing at all.
The Clap does it, but won't crash.
The AU does it, and crashes when painting the last menu option. Attaching stack:
[Lingering Menu Crash 2 .txt](https://github.com/surge-synthesizer/surge/files/10899226/Lingering.Menu.Crash.2.txt)

**Comment by Andreya-Autumn** [comment]
Hmmm, actually the crash condition is moving now too. A couple times now I had to click a patch to get the crash. Stack looks a little differen
[Lingering Menu Crash 3.txt](https://github.com/surge-synthesizer/surge/files/10899299/Lingering.Menu.Crash.3.txt)
t:

**Comment by baconpaul** [comment]
Oh yeah the AU does it consistently. Great. Thank you.

**Comment by baconpaul** [comment]
found it

**Comment by Andreya-Autumn** [comment]
Niiice. This one has really been bothering me lol. :D
