### ISSUE TITLE
CLAP - Virtual Keyboard does not track MIDI notes 

### ISSUE THREAD

**Issue by Xasman** [surge-synthesizer/surge#6798]
**Bug Description:**
In the CLAP version, the Virtual Keyboard does not track MIDI notes 

**Surge XT Version**
Version: Surge XT 1.1.2.d3568a9
Build: 2022-11-01 @ 14:45:37 on 'fv-az158-875.f4ropmtjuqjehdfvnxibh2r4wg.parx.internal.cloudapp.net/pipeline' with 'GNU-9.4.0' using JUCE 6.1.6
System: Linux 64-bit CLAP on  AMD Ryzen 7 5700G with Radeon Graphics
Sample Rate: 48.0 kHz / 32 Sample Surge Block

* Version:
* Plugin Type: [CLAP]
* Bitness: [64-bit]

**Reproduction Steps:**
1. Go to 'Menu->Workflow'
2. Click on 'Show Virtual Keyboard Alt + K'
3. Play notes on MIDI keyboard or play recorded MIDI notes from DAW
4. Virtual Keyboard does not track the notes in blue (as it does with the VST3i version) 

**Expected Behavior:**
Virtual Keyboard should track the notes in blue (in the same way it does with the VST3i version) 

**Screenshots:**
Not needed

**Computer Information (please complete the following!):**
 - OS: [Manjaro Linux]
 - Host: [Reaper]
 - Version: [6.73]

**Additional Information:**
Works correctly in the VST3i version

**Comment by mkruselj** [comment]
Update your nightly, this was fixed in e9dec.a.

**Comment by baconpaul** [comment]
Or wait until we release 1.2

but thanks for the report also!

**Comment by Xasman** [comment]
OK, thanks - will do. It's not at all a showstopper - just thought I should report it. BTW. My current install is the latest version available from the official Manjaro repo.

**Comment by baconpaul** [comment]
Yeah you are in 1.1.2 that’s fine - if you ran the nightly it will be fixed but also you can just wait until 1.2 is out sometime in the next month or so I bet
