### ISSUE TITLE
Dump Current Settings To An HTML File

### ISSUE THREAD

**Issue by jhomme** [surge-synthesizer/surge#6811]
**Is your feature request related to a problem? Please describe!**

It would be nice to have a quick way to review settings for patches without the need to tab and arrow through everything for keyboard users.

**Describe the solution you'd like:**

A button or menu choice to export the control names and settings for the current patch to an HTML file that reflects the interface groups of controls, but with headings and bulleted lists. For example, Seen 1 would be a heading 2, Osc 1 would be a heading 3, and so on. Perhaps it would even be possible for the feature to open the browser to this file.

**Describe alternatives you've considered:**

I considered either talking and recording the settings I have found or typing them into a file.

**Additional context:**

I know we could also simply save patches and give them to each other, but this feature would speed up looking through settings for people who only use keyboard who are blind, and even prevent accidental changing of parameters, although leaving the warning on about not over-writing the patch is also a good thing to keep active.

**Comment by zseramnay** [comment]
I was hopping for this to help patch analysis and teaching
can't wait...

**Comment by baconpaul** [comment]
There’s a very initial draft in the nightly now

**Comment by zseramnay** [comment]
Thanks, I will test it asap !

**Comment by jhomme** [comment]
Hi,
Suggestions by me. An h1 at the top. H2’s that mirror the big sections in the UI, and so on. Grateful for this great start.

Thanks.

Jim H

On Jan 29, 2023, at 8:44 AM, Yan Maresz ***@***.***> wrote:


Thanks, I will test it asap !

**Comment by baconpaul** [comment]
Great yes I didn't know if you wanted plain text or HTML so I went with just a massive pre block for the start :)

I'll do some formatting today or tomorrow and update this issue.

Thanks!

**Comment by baconpaul** [comment]
What I really need to know is "is this basically what you thought you wanted" - if it is I will flesh out the details (like the modulation section has wrong units and so on)

**Comment by jhomme** [comment]
Hi Paul,

Yes, yes, yes. Thank you so very much. This is already very cool, especially for some new as I am. I really want to understand how synthesizers work and get control over this one and not just move controls and hope something good happens. I’ll be able to find patches I like and make them better according to my taste.

Wonderful tuff.

Jim

On Jan 29, 2023, at 9:03 AM, Paul ***@***.***> wrote:


What I really need to know is "is this basically what you thought you wanted" - if it is I will flesh out the details (like the modulation section has wrong units and so on)

**Comment by baconpaul** [comment]
Great let me take this to a more complete state then and then I will update this issue and we can include it in our 1.2 release this spring

**Comment by mkruselj** [comment]
@jhomme Upcoming nightly version of Surge will contain a better formatted HTML export of current patch. Do let us know if it's working out for you!

**Comment by jhomme** [comment]
Hi All,
Thank you so much for this. This is such a great learning tool.

Jim

On Feb 17, 2023, at 7:41 PM, EvilDragon ***@***.***> wrote:


@jhomme <https://github.com/jhomme> Upcoming nightly version of Surge will contain a better formatted HTML export of current patch. Do let us know if it's working out for you!
