### ISSUE TITLE
Documents permission macos

### ISSUE THREAD

**Issue by qpzm34** [surge-synthesizer/surge#6813]
I am not good at English because I am Korean.

When you try to run Surge in Logic Pro, the following window appears:
![KakaoTalk_Photo_2023-01-20-19-05-47](https://user-images.githubusercontent.com/123163508/213677609-3b5b0744-3c53-44b0-893f-223cc72f21b3.jpeg)
How can I solve this?

macOS 11.6

**Comment by baconpaul** [comment]
In the security panel in macos you need to give Logic Pro access to your documents directory

https://support.apple.com/guide/mac-help/control-access-to-files-and-folders-on-mac-mchld5a35146/mac

**Comment by mkruselj** [comment]
Closing the issue since it's likely Paul's answer solved your case - if you need further help, feel free to keep commenting here, we will see it!
