### ISSUE TITLE
Pre-select menu location in patch browser based on last selection (or at least on current category)

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6832]
SkycladSound — Yesterday at 5:25 AM
> On another subject, sorry if this has come up before but, when dealing with tree views such as the patch browser tree view and the configuration tree, is there any way to make the cursor retain its position after an option has been selected? In this way, once a patch has been selected, you could carry on your keyboard browsing from that point and when, for example, making changes to the workflow menu to optimise accessibility, you would have to keep renavigating the tree again.

baconpaul — Today at 8:03 AM
> There is `PopupMenu::Options:::withInitiallySelectedItem (int idOfItemToBeSelected) const;` which we might be able to use. Let me open an issue. But i don't think it will be easy since we have to remember. But we already remember with checkmarks so maybe it would be. Won't tackle today but will toss an issue into the 12 milestone to at leST look

**Comment by mkruselj** [comment]
I'm not sure that one will help us with submenus tho?

**Comment by baconpaul** [comment]
No but it does mean the patch browser could set initial focus on the category you have at least. Which could save 10s and 10s of screen reads

**Comment by mkruselj** [comment]
Ah that is definitely true! Even as sighted I would appreciate this for keyboard navigation through menus.

**Comment by Alexander-Zyurkalov** [comment]
looking

**Comment by Andreya-Autumn** [comment]
Completed, thanks and welcome Alexander!
