### ISSUE TITLE
Reliable Crash, 1.1.2, Windows, Reaper latest

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6835]
From William Fields

[crash-example.zip](https://github.com/surge-synthesizer/surge/files/10609352/crash-example.zip)

this minimal reaper project crashes at measure 4 when played with XT 1.1.2

baconpaul confirmed on his win 11 box.

**Comment by baconpaul** [comment]
OK so what's happening is the pitch bend is going to inf. The modulation source has the 'b' value go o like 1e24 and it blows out.

If you add 

```
if (std::isinf(value[idx]))
                {
                    auto x = 0.f;
                    value[idx] = x;
                }
```

to controller modulation source the problem 'goes away'. william says he sends two pitch bends at the same instant.

**Comment by mkruselj** [comment]
@baconpaul Is there any subtlety as to why that `auto x` is there instead of just assigning `value[idx] = x`?
