### ISSUE TITLE
We steal Esc from host in CLAP

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#6838]
Try opening Surge CLAP in Reaper as a floating window, then press Esc. The expected behavior is that the floating window would close (like with any other plugin loaded in Reaper), but it doesn't.

VST3 works fine as expected.

**Comment by baconpaul** [comment]
Ahh yes the clap keypress issues.
Sigh.

**Comment by mkruselj** [comment]
This doesn't happen with u-he or TAL CLAPs, just for reference.

**Comment by baconpaul** [comment]
Ahh joy of joys in reaper 6.73 on macOS, esc closes a clap just like it does a vst. lemme upgrade to 6.77 and check also.

your reaper version @mkruselj ?

**Comment by mkruselj** [comment]
Happens in any Reaper version for me. Currently I'm running the latest prerelease (dev0302).

**Comment by baconpaul** [comment]
yup ok 6.77 macOS arm escape closes the window no problem.

**Comment by baconpaul** [comment]
Maybe try with an explicit `return false;` at this line https://github.com/surge-synthesizer/surge/blob/6ad105a2ce5d7c2947677480ef84922aef88994b/src/surge-xt/gui/SurgeGUIEditor.cpp#L7219 and see if that helps?

**Comment by mkruselj** [comment]
@baconpaul Nope, that didn't help. 🙁

**Comment by mkruselj** [comment]
OK so... this is weird. That line seems to work but only if Reaper's option "Send all keyboard input to plugin" is DISABLED. WTF?!

**Comment by baconpaul** [comment]
remind me where i find that option?

**Comment by mkruselj** [comment]
OK so this is in the end not our bug. WIth that option enabled Esc doesn't work with TAL or u-he or even VST3, so it's not CLAP specific.

I guess the logic is - by default, Reaper intercepts Esc and uses that to close the plugin window. If we enable the option that is specifically named "Send ALL keyboard input to PLUGIN", that means plugin gets to handle that Esc and not the host. Hence the window doesn't close.

Oh well!
