### ISSUE TITLE
Cannot load Surge 1.6.0-b5 on LMMS

### ISSUE THREAD

**Issue by PatPast** [surge-synthesizer/surge#684]
As I said on the title, I cannot open the lastest Surge beta on LMMS (beta-5)
When I try to load it, but the loading doesn't finish, the beta-3 works.
Please fix it, I'm making a big Dubstep project since I discovered Surge for sound design.
Thx.

**Comment by baconpaul** [comment]
Is this a windows thing? We found a windows bug in beta 5 we plan to fix tonight. 

What is lmms?

**Comment by baconpaul** [comment]
Huh so I installed LMMS and it was basically unusable because I have an HDPI display. I was able to load surge but it painted in the internal window in the wrong position and I'm not sure why. I was using the latest code which doesn't have a binary release yet.

Do you still have beta 3? I am not sure how to debug this.

**Comment by PatPast** [comment]
Hi, sorry for the lat reply,
yes I still have b3 but I havent found on the Surge web page, so for issues on the future releases it would be good to keep old beta downlaod link

**Comment by PatPast** [comment]
And yes I use windows 10

**Comment by baconpaul** [comment]
Well keep that beta 3 - don’t think any of us have it! 

I installed lmms and it was basically unusable in my vm but I found a button which let me click on surge dll and it didn’t hang with latest code. We had a nasty bug in beta 5. Can you reboot and before you run any audio app install beta6 and see if that solves your problem? It has solved the problem for other people in other hosts.

Thanks

**Comment by PatPast** [comment]
Ok I'll try it now

**Comment by PatPast** [comment]
Oh nice it works as well ! thx!

**Comment by baconpaul** [comment]
Wonderful thanks for reporting the issue and sorry you got caught by the bug.

16beta6 has a load of cool stuff beta3 lacks. Enjoy!

**Comment by PatPast** [comment]
Yes now how can I see all the new features from b5 - b6 ?

**Comment by baconpaul** [comment]
we're working on how to make a change log. for windows the answer is "better font; scroll wheel on all controls; big font bug fix". For b3->b5 there's literally hundreds of fixes and changes.
