### ISSUE TITLE
Likely streaming issue with comb filter tuning

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#6840]
Load Dan Maurer - Flute 1 (note it has "precise tuning" disabled)
Re-save under a different name
Next time you load your re-saved version, "precise tuning" is enabled.

**Comment by baconpaul** [comment]
Quick q: once you load it if you toggle and re save does it stick then?

I wonder if it is a 17-21 streaming version or if saving is just broken 

I can check this of course

**Comment by Andreya-Autumn** [comment]
Nope, even toggling it off again and re-saving, it still loads with precise tuning on.

**Comment by mkruselj** [comment]
![image](https://user-images.githubusercontent.com/2393720/217196796-adf6aa19-b425-4031-a6e8-151452f74f26.png)

Wouldn't this be the cause?

**Comment by mkruselj** [comment]
H-hold on... we only have **one** flag for `correctlyTunedCombFilter`, but it can be set separately for each filter? Uhhh...
