### ISSUE TITLE
Random patch reset to Init - Surge XT - Logic Pro X - MacOS Mojave 10.14.6

### ISSUE THREAD

**Issue by kookin** [surge-synthesizer/surge#6845]
**Bug Description:**
After save and relauch of a Logic project with multiple Surge XT instruments, all Surge XT patches get reset to init. Seems to be an intermittent occurrence.

Nothing that I tell which triggers this. Unfortunately I don't have more helpful info.

**Surge XT Version**

* Version: 1.0.1.60228e8
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
2. Click on '...'
3. Scroll down to '...'

**Expected Behavior:**
Goes without saying that this shouldn't happen.

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following!):**
 - OS: MacOS Mojave 10.14.6
 - Host: Logic Pro X 
 - Version: 10.5.1

**Additional Information:**
So far this has happened twice within the space of the last month. I will update if it happens again. 
I am using an external SSD which contains my project data.

**Comment by mkruselj** [comment]
Which version of Surge is this? You haven't edited the bug report so it's showing the template version and that it's VST3, which we know Logic doesn't load.

**Comment by baconpaul** [comment]
But 1.0.1 AU had this exact bug in lpx in some situations. It is fixed in the current stable release

**Comment by baconpaul** [comment]
So if you upgrade to 1.1.2 this will no longer happen. (I am assuming the vst3 is just a typo and the 1.0.1 is not)

**Comment by kookin** [comment]
1.0.1.60228e8 was my actual version. VST3.. my bad.

Thanks for the quick responses. I've upgraded to 1.1.2, will report back if it happens again.

**Comment by baconpaul** [comment]
Great I’m going to close tbis but please do reopen if you see it again - I found it myself after we shipped 1.0.1 and also lost work so I’m sympathetic and sorry!
