### ISSUE TITLE
Live never stops showing that it's scanning Surge VST3

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#6858]
![image](https://user-images.githubusercontent.com/2393720/221362700-f576c478-1791-4f85-993e-6a532db84b69.png)

Pretty weird one. No matter how long you wait this message never disappears. Not sure if it prevents scanning other plugins that come alphabetically after Surge, it might.

**Comment by baconpaul** [comment]
OK so this doesn't happen for me on macOS with live 11.2
which means it will be painful to debug and won't get fixed this morning

**Comment by mkruselj** [comment]
Is there anything I can printf() somewhere to debug this, or a line to put a breakpoint to?

**Comment by baconpaul** [comment]
yes
but i don't know what :)

My guess is: Is it getting to the end of the SurgeSynthesizer constructor or not?

If I was debugging it I would also do the following

in `src/surge-xt/SurgeSynthProcessor.cpp` add a little thing like this

```
struct DebugPrints
{
   std::string f;
    DebugPrint(const std::string &s) : f(s) { std::cout << "Entered " << f << std::endl; }
    ~DebugPrint() { std::cout << "Exited " << f << std::endl; }
};
```

then for each of the juce functions (like `isBusSupported` and `process` getParamCount and things) add at the top of the function

```
DebugPrints dpXXX(__func__);
```

and it will print when it enters and exits every function. That's where I would start.

**Comment by mkruselj** [comment]
OK it seems this is not our issue. I removed Surge VST3 from the folder and it got stuck on another plugin. This is with Live 11.2.6 here. I guess it's something to report to them. Closing this issue.
