### ISSUE TITLE
CLAP preset discovery

### ISSUE THREAD

**Issue by sagantech** [surge-synthesizer/surge#6861]
I think this is an important feature that should be added to Surge.

**Comment by baconpaul** [comment]
Yeah we will add it same time we add context menus. We need to string both through the juce extensions.

**Comment by baconpaul** [comment]
Hmm this is harder than I thought it would be. I'm moving it out of the 1.2 milestone.

**Comment by mkruselj** [comment]
Closing in favor of #6930
