### ISSUE TITLE
Pasted scenes don't light up assigned modulators 

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#6875]
I remember we've talked about this before actually, but no issue was made it seems. It's a visual bug only, the mods all seem to work. They just don't show on the UI in the pasted scene. The param sliders get the altered appearance, but not the source tabs. This Gif shows it: 

![CopyPasteBug](https://user-images.githubusercontent.com/105538426/222970212-bb819441-9878-4777-b20e-ee3d2d98a599.gif)

**Comment by baconpaul** [comment]
Huh I thought this would just be adding a call to `refresh_mod` to the paste callback but it isn't.
