### ISSUE TITLE
Surge XT host tempo

### ISSUE THREAD

**Issue by limpier** [surge-synthesizer/surge#6883]
Hi, there's a way to set host tempo or change the default tempo of 120 for sequences?

**Comment by mkruselj** [comment]
Tempo for standalone can be adjusted in virtual keyboard area.

**Comment by Andreya-Autumn** [comment]
Oh nice! I see that now. Hmm... that's not in the manual it seems? Or am I just not finding it?

**Comment by mkruselj** [comment]
Could be that it's not there... you know what to do then 🙂

**Comment by limpier** [comment]
Thanks :)
