### ISSUE TITLE
LFO parameter sliders blinking

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#6889]
**Bug Description:**
When we select an LFO, then click on it again to engage routing mode, then select another LFO, you will see its parameters in the editor very briefly showing their own modulation sliders, and immediately disappear. This shouldn't happen.

As always, and since this is a minor bug, feel free to move it out of XT 1.2 if it's tricky to fix.

**Comment by Alexander-Zyurkalov** [comment]
looking

**Comment by Alexander-Zyurkalov** [comment]
Actually, the briefly highlighted sliders are not "their own modulation sliders". They are sliders of previously selected LFO.

**Comment by baconpaul** [comment]
probably a call to refresh_mod() out of order with updating the mod state is my guess?

**Comment by baconpaul** [comment]
@Alexander-Zyurkalov just FYI we will probably freeze merges around April 4 or 5 so we can release 1.2. I'm happy to have the fix here on either side of the release - its not an install blocker - but just letting you know!

Thanks for joining in the fun and your contributions to the 1.2 release of course, even if this one slips past 1.2

**Comment by baconpaul** [comment]
Great. We might also slip. No pressure, no deadlines, just wanted you to know!

**Comment by Alexander-Zyurkalov** [comment]
It seems I have finally found out what is the problem. When we click on another modulation source button, we change `modsource_editor[i] = newsource` and `queue_refresh = true;`. Doing that we cause recreating all sliders. But we also repaint some components that cause repainting the sliders of the modulation source and we have that blinking. I will recheck this hypothesis again and than will think how to fix that

**Comment by baconpaul** [comment]
Ahh right so we want like a “reset mod source on refresh” state which we set there and then in the refresh read it type thing

**Comment by baconpaul** [comment]
@Alexander-Zyurkalov we will probably do the 1.2 release friday morning so I pushed this into a (newly created) 1.2.1 milestone since I'm *sure* we will have some 1.2 followups anyway

**Comment by Alexander-Zyurkalov** [comment]
> Ahh right so we want like a “reset mod source on refresh” state which we set there and then in the refresh read it type thing

Where to call refresh_mod()? In openOrRecreateEditor()? If I place the call there, I can't see what we modulate any longer.

**Comment by baconpaul** [comment]
Add a Boolean refresh mod on next idle 
Set it to true 
Check it in open or recreate or in idle
Something like that - basicalky reverse the order of the create and refresh with a little smidge of state

**Comment by Alexander-Zyurkalov** [comment]
> Add a Boolean refresh mod on next idle Set it to true Check it in open or recreate or in idle Something like that - basicalky reverse the order of the create and refresh with a little smidge of state

Oh, there is already such a variable. And it is working solution! Thank you!

**Comment by baconpaul** [comment]
Awesome
