### ISSUE TITLE
Small Ctrl + Dragging issues in the Step Sequencer

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#6906]
**Bug Description:**
Very minor thing, but when holding Ctrl and dragging **quickly** across the steps in the step sequencer modulator to clear out all the steps in one swipe, it will sometimes leave some steps untouched, meaning you have to go back and clear them afterwards.

Also, when holding down Ctrl and then moving the mouse outside of the bounds of the step sequencer and dragging, it doesn't clear the steps, when in reality it should (just like it does fill the steps if you don't hold down Ctrl).

**Computer Information:**
 - OS: Windows 11
 - Host: FL Studio 21

**Comment by mkruselj** [comment]
Confirmed on both accounts.

**Comment by mkruselj** [comment]
#6909 resolves the drag outside bounds, makes it work again.
