### ISSUE TITLE
L and R buttons in the oscilloscope don't update immediately upon switching skins

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#6907]
**Bug Description:**
Pretty self-explanatory. The L and R buttons in the oscilloscope don't update after changing the skin if the scope is opened while the skin is changed. It will only update when hovering over those two buttons.

**Comment by baconpaul** [comment]
onSkinChanged() { repaint(); } probably

**Comment by mkruselj** [comment]
Nope that doesn't fix it.
