### ISSUE TITLE
Waveform display dynamically affected by modulation

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#691]
```
Can we make feature requests here?

I'd really appreciate it if the waveforms would
move and change to show the effect of
modulation like they do when you use the mouse.

Thank you.
```

mirrored from
https://www.kvraudio.com/forum/viewtopic.php?p=7323766#p7323766

**Comment by mkruselj** [comment]
Link to #3618

**Comment by mkruselj** [comment]
Closing this one in favor of already linked #3618 which contains more info that should be helpful when implementing this feature.
