### ISSUE TITLE
This MSEG preset is borked

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#6918]
[Borkened?.modpreset.zip](https://github.com/surge-synthesizer/surge/files/11183482/Borkened.modpreset.zip)
That one. It looks like this:
![What](https://user-images.githubusercontent.com/105538426/230726536-e3d838b9-8682-49b3-a95a-83096d196e2f.png)

**Comment by baconpaul** [comment]
<img width="167" alt="Screen Shot 2023-04-08 at 10 57 28 AM" src="https://user-images.githubusercontent.com/13387561/230728186-c9d62f7b-e1d7-42be-9e4e-199d3e1066fd.png">

if i edit that file and replace the nan with 0.5 it works
so clearly somehow you naned that (how) and then it stuck (bad) and didn't recover on load (worse)

**Comment by baconpaul** [comment]
so "how did you make that" is one question but also "we shoould make it so you can't make that" is another 🙂
my guess is if you crunch the sine to time zero and back you nan out the cpv
yeah thats it
if you drag the 0 point forward it nans out CPV

**Comment by baconpaul** [comment]
![BlowItUp](https://user-images.githubusercontent.com/13387561/230728375-8fd96547-0a5f-493b-81d9-1290f26fe19d.gif)

**Comment by baconpaul** [comment]
The brokered thing has a loopEnd of 0 and that's why you can drag the end around to break it. So we need to figure out how that state was made too. I have an UnBorkened with nan->0 and then i can drag 0 and UnBorkened2 with nan->0 and loopEnd -> -1 and the second is just fine.

Basically once corrupted its pretty easy to fix but lets try and find that path to corruption also.

**Comment by baconpaul** [comment]
Another flavor from Trace98 on discord

Windows 10 
Surge XT 1.3.nightly.41942bf (also previous nightly)
CLAP and VST3 version

When having two nodes at the same vertical value, and having the segment between them set to linear, moving the "curve node" between them makes the curve node disappear permanently. Changing the segment type to bezier, or any other, displays extremely weird and erratic graphs. Also the mouse cursor is teleported to the top of the screen. Only way to reverse this is deleting the node or using the undo button.

How to replicate: INIT patch -> MSEG default -> grab the third segment curve node and pull it up -> bug!

**Comment by baconpaul** [comment]
That's different but i'll leave it on this issue since I have it fixed.
