### ISSUE TITLE
Missing scrollbars in VST3 and CLAP under REAPER

### ISSUE THREAD

**Issue by YutMarma** [surge-synthesizer/surge#6924]
**Bug Description:**
When using REAPER (which I'll henceforth capitalize as "Reaper") and attempting to resize Surge beyond single-screen size, you are unable to scroll up/down or left/right to view the entire GUI. Trying to manually shrink/unshrink the window to "trick" the scrollbars into appearing likewise does not work.

**Surge XT Version**
1.1.2

* Version: As previously stated, 1.1.2
* Plugin Type: [VST2, VST3, AU] VST3 and CLAP
* Bitness: [32-bit or 64-bit] 64

**Reproduction Steps:**
1. Open Reaper
2. Load Surge
3. Change zoom level to something beyond the capabilities of a single screen to show at once

**Expected Behavior:**
Scrollbars should appear if the plugin real estate is larger than the available window/screen real estate.

**Screenshots:**
I can post if deemed necessary.

**Computer Information (please complete the following!):**
 - OS: [e.g. Windows 10] Windows 10
 - Host: [e.g. Bitwig, Logic, Cubase, Reaper] Reaper
 - Version: [e.g. 2.4] Reaper version 6.78

**Comment by YutMarma** [comment]
> Hmmm, but those scrollbars are host generated, not plugin generated... so the issue might be on Reaper side?

Reaper has scrollbar-related "issues", to be sure, but it's still plugin-dependent to some degree. Serum and Plogue plugins load with scrollbars, though the scrollbars go away if you resize the windows after loading them. On the other hand, Surge / Vital / Full Bucket plugins are all in the same "no scrollbars never-ever no-how" camp.

**Comment by mkruselj** [comment]
This seems to be a Reaper issue with VST3/CLAP.

https://forum.cockos.com/showthread.php?p=2149656

Maybe it's intentional, since both VST3 and CLAP have better ways of negotiating plugin window size with the host compared to VST2.

Closing the issue on our side, nothing we can do about it.
