### ISSUE TITLE
ModMapper which is a note quantizer

### ISSUE THREAD

**Issue by Dionisio765** [surge-synthesizer/surge#6929]
Hi all

I wonder if it´s possible or make any sense request a note quantizer like VCV Rack Quantum.

Thank you for your time

Dionisio

**Comment by baconpaul** [comment]
It does! But it’s a bit different in surge and here’s how it works 

basically all the pitch sliders are in keys so if you set a modulation depth to 12 and modulate it by 1/12 or 2/12 you get uniform pitch offsets 

the mseg step sequencer and formula modulator all have ways to outout quantized data like this. In the step sequencer you ctrl or alt drag for 1/12 steps or use a typein and in the mseg set the snap to 12. In the formula you just type the code 

we have a far future plan to add mod mappers into which quantization would be an operator also but today you can get the quantization result in the vst using the techniques above so I’m going to close this. But if I missed  something please reopen!

**Comment by Dionisio765** [comment]
Hi baconpaul
 
 Yes, i know it´s possible to draw pitch sliders pressing shift. Sorry, but i find much more easy choosing notes from a quantizer like Quantum than draw notes, that´s why i mention Quantum.
 If  i have a note quantizer to chose specific notes , i can draw freely and always keep in scale.
 I respect your point, don´t worry about my request, maybe is a limitation from my part.
 
 Thank you for your time and reply, and thank you once more for upgrading PolyGnome, i use it all the time in all my patches. Sorry for my poor English.
 
 All the best
 
 Dionisio

**Comment by baconpaul** [comment]
OK let me reopen this and mark it as "quantizer as type of mod mapper in xt2" then.

**Comment by mkruselj** [comment]
If this is for modmappers, I would close this issue and defer to #1384 which covers this use case too.

**Comment by baconpaul** [comment]
Yeah lets just make sure we remember to add a quantizer in the mappers.
