### ISSUE TITLE
CLAP features now BWS 5 is out for 1.3

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6930]
- [x] Parameter control panes are cool and it looks like Jatin is close to getting those working
- [ ] The modulation parameter update exists and we could use that to potentially mark sliders which were modulated
- [ ] Preset discovery
- [x] Test Param menus
- [x] Update to latest CJE

**Comment by mkruselj** [comment]
@baconpaul I would bump this one out of the 1.3 milestone.

**Comment by baconpaul** [comment]
ha you and i are thinking alike. i'm sitting here right now with my coffee looking at 1.3 and thinking 'lets bump that - we did menu"

**Comment by baconpaul** [comment]
I'm going to close this and open a separate issue for clap preset discovery actually
