### ISSUE TITLE
Keybinding accessibility

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6937]
reported by bscross on discord

There are 3 unlabeled buttons in the shortcut editor. They are at the very end of the list, though this doesn't mean they are there visually. Consequently, when I set things here, they do not take past the session. I think I saw that there's supposed to be a CTRL+0 keybind for speaking various info, but it does nothing for me.

I went in there to bind the initialize patch key. It lasted the session but then when Surge is loaded again, it's gone. I did the same thing, set it, lasts for the session, then gone. So repeated the procedure twice.

**Comment by ironcross32** [comment]
Version: 1.2.nightly.97ccf6d

Using CLAP

**Comment by mkruselj** [comment]
These buttons seem to be just the same bypass/learn/reset buttons that all other keybind assignments have, except they are scrolled off-viewport, but somehow still visible for a11y... I wonder if this is maybe a bug somewhere in `juce::ListBox`...

**Comment by mkruselj** [comment]
This GIF should show the issue better perhaps:

![kbe](https://github.com/surge-synthesizer/surge/assets/2393720/718eef71-3e30-4b8a-8d56-8e872bc4f1e2)

**Comment by baconpaul** [comment]
I'm pretty sure the accessible view has the entire list. The scrollbar is a visual only construct. Is that not what you see?

**Comment by baconpaul** [comment]
Are the OK/Cancel/Reset buttons labeled properly?

**Comment by ironcross32** [comment]
No. I can OCR two of the three, one is cancel, the other is reset. The one far left with screen reader is probably OK. There is a labeled close button though. When this is fixed, this will resolve the settings don't take part of this issue because I'm imagining the close button isn't saving the new settings.

**Comment by mkruselj** [comment]
The Close button is not supposed to store the keybinding changes, the OK button is.

**Comment by mkruselj** [comment]
@ironcross32 Do let us know if this is sufficient to consider this issue closed or not, after you check it out!

**Comment by ironcross32** [comment]
Will do.

**Comment by ironcross32** [comment]
Issues resolved.

**Comment by mkruselj** [comment]
Waheeeeey! Thanks for feedback!

**Comment by baconpaul** [comment]
Awesome!
