### ISSUE TITLE
WaveShaper mode plot

### ISSUE THREAD

**Issue by DerozerDSP** [surge-synthesizer/surge#6941]
Hi,

is there any way on WaveShaper to see the shape plot as -1/1 (input) to -1/1 (output) mapping instead of sine (as input) to -1/1 (output)?

Usually on WaveShaper thats the way it visualize the input/output (Fruity WaveShaper for example, or Trasher2 and so on).

Not sure how thats mapping is named, but any way to display it “classic way”? 

Thanks

**Comment by mkruselj** [comment]
We decided to show how the selected waveshaper affects a sine wave, so this is by design.

**Comment by Andreya-Autumn** [comment]
> @mkruselj but baconpaul ask to me to open this issue here https://community.vcvrack.com/t/surge-xt-2-1-testing-and-feedback-thread/18813/148.
> 
> I meant Surge on Rack, wrong section?

Ah! Yes, this is for the Surge VST. Here's the repo you need: https://github.com/surge-synthesizer/surge-rack

**Comment by DerozerDSP** [comment]
Done. Thanks!
