### ISSUE TITLE
Oneshot Factory WTs are no longer oneshots

### ISSUE THREAD

**Issue by selenologist** [surge-synthesizer/surge#6966]
**Bug Description:**
Oneshot Factory WTs are no longer oneshots after moving to assuming 1024 frames when loading a WAV file without loop metadata.

**Surge XT Version**
Version: Surge XT 1.2.main.d57eed25
Build: 2023-04-17 @ 23:02:03 on 'rainbow/local' with 'Clang-15.0.7' using JUCE 6.1.6
System: Linux 64-bit VST3 on  AMD Ryzen 7 2700X Eight-Core Processor
Host: Ardour @ 96.0 kHz / Process block size: 8 samples

**Reproduction Steps:**
1. Select a WT oscillator
2. Load Factory Wavetables -> Oneshot -> [any of them]
3. Notice it's not a oneshot anymore, but a WT with 1024 frames.

**Expected Behavior:**
Oneshots are still oneshots.

**Additional Information:**
A proper fix for importing WAVs without loop information is issue #3436 but until then we should patch the factory files to have the correct metadata.

**Comment by baconpaul** [comment]
none of the factory one shots are wav files
what is the mechanism by which you "notice"?

**Comment by selenologist** [comment]
The WT file was indeed being loaded, not a WAV. A periodic tone was produced instead of a one-shot sample.

But recompiling with commit 46050fd3c241007c3e7ef2b2565f2a0c257860a4 (after fixing an unrelated null pointer crash) caused the files to load as one-shots again correctly despite apparently nothing relevant changing since d57eed2594719c00000a1ea2eb540dd32b319cea. Wish I'd kept my bugged build to work out what the hell happened, but eh, mysteries of the universe.
