### ISSUE TITLE
Pitch type-ins are a tiny bit borked with "Apply tuning after modulation"

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#6977]
So... you have loaded a tuning with a 3/2 in it, and checked the mentioned option. You type-in "3/2" in the pitch field of an oscillator, it won't play 3/2. 

That's because with apply after modulation checked, putting pitch to 7.00 exactly is remapped to 7 keys up, and typing in 3/2 doesn't land you on 7 steps it lands you on ≈7.02. 

So you probably expected to land on 3/2 since that's what you typed in, and that interval is in your scale. But instead you landed a bit sharp of the 7th degree in your scale. How sharp depends on what the 8th degree is, since this mode interpolates the pitches between the integer degrees.

There are two options for solving this. Either we just document it as it is, basically saying "in this mode, always type in pitch offsets as 100 cent intervals. 

...or make it so whenever the user types in a ratio that's present in the scale, make sure the param ends in the place that actually makes that sound. 

The latter would be more intuitive in some cases. But of course, it'd still only be when playing the root of the scale that you'd actually be guaranteed to hear the interval you typed in.

**Comment by baconpaul** [comment]
I think the best bet here is, in after modulation mode, if you type in a fraction or tuning value it actually returns a clear error saying "tones not supported in after mode" or some such.

thoughts?

**Comment by mkruselj** [comment]
I agree with that, Occam's razor.

**Comment by Andreya-Autumn** [comment]
For 1.3 sure! For XT2 it'd be nice to solve it differently but that's already noted in #6983
