### ISSUE TITLE
Absolute mode on pitch is also a tiny bit borked with scl/kbm. 

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#6978]
Bring up two modern saw oscs, and load any unequal tuning with scl (kbm not necessary).

Make one of them absolute pitch, but keep its pitch at 0. 

Play some different notes. You'll hear the root of the scale is perfectly in tune, but there's a small amount of beating on others, indicating that absolute mode makes the osc interpret tuning very slightly wrong. Note that this happens even in "apply tuning at MIDI input" mode.

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/blob/d84de1c5931acbf954ca930f91fd1f9e579a76d9/src/common/dsp/SurgeVoice.h#L111

it is almost definitely that not special casing the ==0 case

**Comment by baconpaul** [comment]
i bet if you stick at the very top of that
```
if (localcopy[scene->osc[oscNum].pitch.param_id_in_scene].f == 0)
{
   return note0;
}
else // rest of code
```
it will solve that issue actually
but my surge is in bits around me on the shop floor right now so i can't easily test that
