### ISSUE TITLE
Loud popping that kills the sound

### ISSUE THREAD

**Issue by jasnov** [surge-synthesizer/surge#698]
crackling and popping

try the pop vocoder preset and play lots of notes at once

loud popping that momentarily cuts out all sound. output meter goes into red even thought  actual sound is not that loud

**Screenshots**

windows 7
ableton 10

**Comment by jasnov** [comment]
Just tried the new nightly version - same problem
go to choirpadthing patch and hold down more than 6 notes and change chords.
increasing polyphony makes no difference

**Comment by baconpaul** [comment]
Ha I literally opened the issues to make a master "click and pop" issue with the start of my debugging. Something is wrong.... and we have to hunt it. Thank you for the clear report.
