### ISSUE TITLE
setting portamento time to 0ms stilll produces pitch slides in single trigger play modes

### ISSUE THREAD

**Issue by musicalman** [surge-synthesizer/surge#6984]
If a portamento time of 0ms is used, and the scene play mode is set to one of the single trigger options, there is still a subtle slide between notes. This slide is absent when using non single trigger play modes i.e. 0ms is truly instantaneous, but it of course does not quite sound the same as single trigger.

I first noticed this with linear curve and all other portamento options unchecked. I was advised by a user on the Discord to try checking constant rate and using logarithmic curve shape, since in their testing at least, this was a bit better. However, all settings will still produce a slide. Furthermore very large note jumps (a few octaves or more), have longer slides with constant rate checked than unchecked, even if the portamento time is kept at 0ms.

At first I thought this was a design limitation of the oscillators, and for string and modern types this indeed seems to be the case as they will quickly ramp/slide when performing pitch change by any means. However all other osc types can be forced into extreme, non-ramped pitch changes with lfos, or modulation from CC (if midi smoothing is disabled), so most oscs seem capable of instant portamento.

**Comment by baconpaul** [comment]
I am almost entirely sure the fix is to change

https://github.com/surge-synthesizer/surge/blob/75778568c806f603d8092b84f1295a50d24d5484/src/common/dsp/SurgeVoice.cpp#L633

to read


```cpp
if(localcopy[scene->portamento.param_id_in_scene].f <= scene->portamento.val_min.f)
{
    state.portaphase = 1;
}

if (state.portaphase < 1) { ... 
  
```

Or perhaps alternately

```cpp
if ((state.portaphase < 1) && 
     (localcopy[scene->portamento.param_id_in_scene].f > scene->portamento.val_min.f))
```

and then that will force all val-min portamentos to 0. An oscillator which smooths pitch over the block may still have a 32 sample adjustment but this will stop the portamento from evolving.
