### ISSUE TITLE
Incorrect "OSC Type" order in the VST parameter

### ISSUE THREAD

**Issue by cyanit** [surge-synthesizer/surge#701]
**Problem**
Sine is selected before, not after, wavetable when you control the "OSCx Type" parameter from the DAW.

**Expectation**
Sine should be selected after wavetable.

**Reproduction**
In order to reproduce the bug, take a look at them here:
[![Take a look at this bug](https://img.youtube.com/vi/52h1REqogk8/0.jpg)](https://youtu.be/52h1REqogk8 "Take a look at this bug")

**System Infos**
OS: Windows 10
DAW: Bitwig Studio 2.4
Type: VST2, 64bit
Build: NIGHTLY 2019-03-02-96dac41

**Comment by baconpaul** [comment]
Haven’t looked at this one closely but I do note that these are set up in configuration.xml and the i=“” fields in there are not in display order (i=0 is classic; i=1 is sin; i=2 is wavetable etc...)

So when someone looks at this I would start lookin at the snapshot loader for how that i= is used. I think it maps to ct_osc_type or some such but maybe it also sets parameter order?

**Comment by baconpaul** [comment]
yeah just confirming that the control does move these in exactly the i="x" order specified in configuration.xml. Unfortunately that id is the oscillator type so we can't change it in the xml. The only safe fix to this is to reorder the menu into the nonsensical i="" ordering. Anything else can break streamed patches and daw setups. Hmm. Need to think.

**Comment by cyanit** [comment]
Well, if reordering the list in the UI is all what it takes, I'd argue that its a pretty convenient user experience improvement :)

**Comment by baconpaul** [comment]
Well I would postpone that judgement until you see the order! It's weird. Also the classics don't get picked quite normally. Lots of weird hair on the way this works.

**Comment by cyanit** [comment]
Hmm. Well, anyway im sure there's also more important stuff, but if you find the time, the issue will be ready ;)

**Comment by baconpaul** [comment]
Yup definitely thanks!

**Comment by mkruselj** [comment]
I think reordering the menu is a no-go due to how established it is. I mean this order makes no sense:

Classic
Sine
Wavetable
S&H Noise
Audio Input
FM3
FM2
Window


So I'd rather close this with a wontfix.

**Comment by baconpaul** [comment]
reordering the menu is one thing which we might do in the ui when we add oscillators, but re-mapping the ids for automation which is what we would need to do here is a no-go. i agree we close this one.
