### ISSUE TITLE
Surge / Surge-XT attack resolution from MIDI controller Nektar impact LX49+

### ISSUE THREAD

**Issue by huornlmj** [surge-synthesizer/surge#7010]
**Bug Description:**
Attack resolution is only 1 bit when MIDI control is assigned to controller CC#38

**Surge XT Version**
1.2.2.832c875

* Version:
* Plugin Type: [VST3]
* Bitness: [64-bit]

**Reproduction Steps:**
1. Right click on the Attack controller in the Filter EG section and learn from MIDI controller.
2. On Nektar Impact LX49+, use the first slider (called attack)

**Expected Behavior:**
A expect the slider to travel from bottom to top in correspondence to the controller.  It does not.  It only moves 1 bit, from 0 to 1.  I have confirmed the controller itself is fine as my DAW (Renoise) can see full 128 bit resolution coming from the same physical control.

**Comment by mkruselj** [comment]
MIDI CC #38 is supposed to be reserved and not available to MIDI learn, as evident by the MIDI learn submenu:

![image](https://user-images.githubusercontent.com/2393720/235773942-718c13c5-aef9-4312-9c70-08dd014ff7f6.png)

That it even does pass MIDI learn procedure is a bug. Thanks for the report!
