### ISSUE TITLE
AMP EG - too fast???

### ISSUE THREAD

**Issue by therealkitman** [surge-synthesizer/surge#7018]
Hi, having questions about the Amp EG in the standalone version 

Version: Surge XT 1.2.git-no-branch.git-no-commit
Build: 2023-04-12 @ 00:00:00 on 'hci-snode2-m0/local' with 'GNU-13.0.1' using JUCE 6.1.6
System: Linux 64-bit Standalone on  Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Sample Rate: 44.1 kHz / Process block size: 32 samples

I am trying to reverse engineer the Factory Pad "Canadians" into the VCV Rack version. After not getting the same 'noise' between the two synths I noticed that the standalone version does something 'weird'. The AMP EG has an attack value of ~1.5secs. But as soon as I press a note on the keyboard the volume is nearly max immediately.

https://user-images.githubusercontent.com/14888092/236718946-af04ee54-b9a2-4d10-b9d3-2caa0a0a7b07.mp4

Whereas in my Rack equivalent I get an attack time I expect -

https://user-images.githubusercontent.com/14888092/236720149-04e24ff2-1c11-47b2-bfa7-4bab3ed08c47.mp4

Either the attack on the standalone's AMP EG is wrong OR I am misunderstanding the signal path in Surge and my VCV patch is wrong. I have read the manual's technical stuff (honestly!) but I am curious as to why the standalone attck is so fast.

**Comment by baconpaul** [comment]
Isn’t your delay inline in rack with 100 pct mix and is a send position in the vst?

**Comment by therealkitman** [comment]
I made the Delay Mix in rack 100% the same as the vst. Am I misunderstanding something?

**Comment by therealkitman** [comment]
OK I took the Delay out of both vst and rack and now they are comparable. What did I do wrong?

**Comment by therealkitman** [comment]
OHHHHHHHHHHH!!!!!! I should have done this?
![image](https://user-images.githubusercontent.com/14888092/236729807-761913a1-0709-45f1-baa7-d443af11696e.png)

**Comment by mkruselj** [comment]
So, no bug then it seems! Will close the ticket. 🙂

**Comment by baconpaul** [comment]
> OHHHHHHHHHHH!!!!!! I should have done this?
> ![image](https://user-images.githubusercontent.com/14888092/236729807-761913a1-0709-45f1-baa7-d443af11696e.png)

Yes. The middle row is sends the top is inserts
