### ISSUE TITLE
In "Additional Content" the command to download all is not working

### ISSUE THREAD

**Issue by jdg511** [surge-synthesizer/surge#7026]
**Bug Description:**
When I run the command on the additional content page I get the following result:

`toor@Studio:~$ svn checkout https://github.com/surge-synthesizer/surge-synthesizer.github.io/trunk/assets/wiki/Additional%20Content
svn: E170000: URL 'https://github.com/surge-synthesizer/surge-synthesizer.github.io/trunk/assets/wiki/Additional%20Content' doesn't exist`

**Surge XT Version**
N/A

* Version: N/A
* Plugin Type: N/A
* Bitness: N/A

**Reproduction Steps:**
1. Run command "svn checkout https://github.com/surge-synthesizer/surge-synthesizer.github.io/trunk/assets/wiki/Additional%20Content"

**Expected Behavior:**
I expected to download all patches

**Screenshots:**
https://imgur.com/a/34OXhzb

**Computer Information (please complete the following!):**
 - OS: Windows 11
 - Host: Windows subsystem for linux
 - Version: 1.2.5.0

**Additional Information:**
N/A

**Comment by mkruselj** [comment]
This is a website related report, so please repost to https://github.com/surge-synthesizer/surge-synthesizer.github.io/issues
