### ISSUE TITLE
lv2 version can't remeber itself status

### ISSUE THREAD

**Issue by sdfsfsfwrt** [surge-synthesizer/surge#7036]
**Bug Description:**
after choose preset in  lv2 version if you restart your daw surge xt cant reload your preset 
it initialize preset or choose random one
**Surge XT Version**

* Version:1.1.2 and 1.2.3
* Plugin Type: lv2
* Bitness: 64

**Reproduction Steps:**
1.load surge xt lv2 version in your daw
2.then choose a preset you want 
3. now quit from you session / quit from daw
4. then reload session 
5. you see surge xt  cant reload your choosed preset 

**Computer Information :**
 - OS: xubuntu 22
 - Host: Ardour  
 - Version: 7.0 to 7.4

**Comment by baconpaul** [comment]
The lv2 has never worked reliably. We recommend using the vst3 or clap versions of surge and with 1.3 will stop binary distribution of lv2.

thanks

**Comment by romasq** [comment]
Why wasn't it removed in version 1.3.4 still?
