### ISSUE TITLE
Tuning editor - editing number of notes

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#7048]
**Bug Description:**
If I change the 'number of degrees' line in the tuning editor, then when a note is played, the editor highlights the wrong note in the text, and plays the old scale length.

**Surge XT Version**
Version: Surge XT 1.2.nightly.cb11acd
Build: 2023-04-09 @ 23:14:19 on 'fv-az33-642/pipeline' with 'MSVC-19.29.30148.0' using JUCE 6.1.6
System: Windows 64-bit Standalone on Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Sample Rate: 44.1 kHz / Process block size: 32 samples

**Reproduction Steps:**
1. Drag "SD2 10-05.scl" into Surge
2. Open the editor
3. Decrement the degree count (e.g. from 5 to 4)
4. Delete the first ratio, leaving 4 entries.
5. Play notes. They highlight correctly in the VK (based on MIDI IN) at the left of the tuning editor, but the sound is a 5-note scale (should be 4), and the wrong notes highlight in the editor.

**Expected Behavior:**
When I play the notes, I expect those entries to be highlighted.

**Additional Information:**
I'm debugging my own app that generates .scl files, and came across this bug. I can reproduce it with the .scl files provided with Surge, so provided that as a clean example and avoid external factors.

**Comment by baconpaul** [comment]
Thanks! There’s a line to note map we have to do that scl highlighting and I bet we just don’t refresh it under some gesture.

**Comment by baconpaul** [comment]
Specifically this api rebuilds https://github.com/surge-synthesizer/surge/blob/605b717d054c59049e045a7541aaa1449724b5c0/src/surge-xt/gui/overlays/TuningOverlays.cpp#L1796 and that with a repaint and force refresh in the code editor should do it

**Comment by j5v** [comment]
Please also look out for the key mapping (or calculated array for frequencies - or whatever) not updating - I could play a 5-note scale when I'd edited the .scl text to be a 4-note scale (from 5-note scale).

**Comment by Andreya-Autumn** [comment]
@j5v Just checking, are you pressing the "apply" button bottom right after editing? I see exactly the behavior you describe before pressing the button, and the expected behavior after.

**Comment by j5v** [comment]
@Andreya-Autumn Confirming, I did not press **Apply**. Thanks for checking against the expected use of the interface.
Not pressing **Apply** is likely the source of my problem. I'll test that soon and feed back.

**Comment by mkruselj** [comment]
Pretty sure that's the issue 🙂

**Comment by j5v** [comment]
Yes, that was entirely the problem.
So this is just a minor bug where edited (but not applied state) highlights strangely in the text editor.

It might be helpful to users, if we highlight the **Apply** button more when there are uncommitted changes in the editor (dirty state).
