### ISSUE TITLE
What shall i do after compiling lv2 package on Arch

### ISSUE THREAD

**Issue by queengab** [surge-synthesizer/surge#7050]
Hi to all,

and thanks for this great synth.
I'm configuring my digital workstation with some software and i want to test surge.
I'm running arch linux with pipewire and pipewire jack clients.
I wanted to test some synth so i decided to test also vst3 plugin in Carla. When i find your synth i discovered that there was an lv2 version so i compiled it with cmake.

```
git clone https://github.com/surge-synthesizer/surge.git
cd surge/
git submodule update --init --recursive
cmake -Bbuildlv2 -DSURGE_BUILD_LV2=TRUE
cmake --build buildlv2 --config Release --target surge-staged-assets
```

```

[100%] Linking CXX shared module "surge-fx_artefacts/Release/LV2/Surge XT Effects.lv2/libSurge XT Effects.so"
surge-fx: Relocating LV2 component
[100%] Built target surge-fx_LV2
[100%] Built target surge-fx_Packaged
[100%] Built target surge-staged-assets
```
Now what can i do? I have to copy the compiledi directory in `usr/share` or in the lv2 dir plugin which carla use to scan plugins?
Where is the lv2 plugin?
Where can i have to copy the assets?

Sorry for this question, but this is the first time i compiled some software from source with cmake
Thanks

**Comment by baconpaul** [comment]
First, the vst3 and clap generally work way better than the lv2 and we will discontinue the lv2 in binary form with 1.3

you should see the lv2 in your build directory which you can then move to your lv2 path

**Comment by queengab** [comment]
Hi,

thanks for your support. I now understand :)
I'm using actually the lv2 and it seems to work well with Carla, no xruns.
But maybe i will replace it with CLAP. I have to learn how to start a vst3 plugin in arch via wine...
Anyway thanks Surge is really interesting!

**Comment by baconpaul** [comment]
You don’t need wine! The native vst3 works fine on Linux 

the lv2 at head of code uses some features that means some daws don’t work properly. The 1.2 lv2 has state problems. But neither will xrun indeed! 

Enjoy!

**Comment by baconpaul** [comment]
Oh also I’ll close this issue since I don’t think there’s anything left to do but please reopen if I misread
