### ISSUE TITLE
Vst3 plugin error: not configured to have stereo output

### ISSUE THREAD

**Issue by queengab** [surge-synthesizer/surge#7051]
Hi after this https://github.com/surge-synthesizer/surge/issues/7050,
i removed the lv2 plugin and inserted instead the vst3 plugin using with carla on my Arch Linux.
When i load the plugin on Carla i receive this error:

"Bus configuration error Surge XT was not configured to have stereo output, which is required. The main output bus has 0 channels ans is disable"

I didn't receive any error with lv2.

Sure is something related with configuration that i don't know. Thanks!

**Comment by baconpaul** [comment]
Yeah I don’t mean to be rude but the problem is you have loaded surge in an environment where the main output is not a stereo output. I don’t use Carla so I don’t know how to fix that but you have to insert surge in a bus with stereo outs

**Comment by mkruselj** [comment]
I would also suggest for any sort of troubleshooting with Surge Synth Team related products, it's better to hop on to Discord rather than use GitHub as a support tool - it's a bug tracker first and foremost.
