### ISSUE TITLE
Building Cardinal on Arch Linux fails with an error pointing to Surge

### ISSUE THREAD

**Issue by maxigaz** [surge-synthesizer/surge#7061]
**Bug Description:**
When I try building Cardinal with all the submodules pulled on Arch Linux, the building process fails with an error pointing to Surge.

**Surge XT Version**
Commit a1601da407db331a39b337b213ed0a66e196262c

**Reproduction Steps:**
Run the following commands from the terminal:

```
git clone --depth=1 https://github.com/DISTRHO/Cardinal
cd Cardinal
git submodule update --init --recursive
make
```

**Expected Behavior:**
Cardinal compiles.

**Computer Information (please complete the following!):**
 - OS: Arch Linux
 - GCC version: 13.1.1 20230429
 - Host: -
 - Version: -

**Additional Information:**
Here's the error:

```
In file included from /media/pici/Cardinal/plugins/surgext/surge/src/common/SkinColors.cpp:1:
/media/pici/Cardinal/plugins/surgext/surge/src/common/SkinColors.h:22:36: error: ‘uint32_t’ has not been declared
   22 |     Color(const std::string &name, uint32_t argb);
      |                                    ^~~~~~~~
/media/pici/Cardinal/plugins/surgext/surge/src/common/SkinColors.h:23:36: error: ‘uint32_t’ has not been declared
   23 |     Color(const std::string &name, uint32_t rgb, char alpha);
      |                                    ^~~~~~~~
/media/pici/Cardinal/plugins/surgext/surge/src/common/SkinColors.h:29:5: error: ‘uint8_t’ does not name a type
   29 |     uint8_t r, g, b, a;
      |     ^~~~~~~
/media/pici/Cardinal/plugins/surgext/surge/src/common/SkinColors.h:5:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
    4 | #include <vector>
  +++ |+#include <cstdint>
    5 |
make[5]: *** [src/common/CMakeFiles/surge-common.dir/build.make:174: src/common/CMakeFiles/surge-common.dir/SkinColors.cpp.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[5]: Leaving directory '/media/pici/Cardinal/deps/surge-build'
make[4]: *** [CMakeFiles/Makefile2:782: src/common/CMakeFiles/surge-common.dir/all] Error 2
make[4]: Leaving directory '/media/pici/Cardinal/deps/surge-build'
make[3]: *** [CMakeFiles/Makefile2:789: src/common/CMakeFiles/surge-common.dir/rule] Error 2
make[3]: Leaving directory '/media/pici/Cardinal/deps/surge-build'
make[2]: *** [Makefile:332: surge-common] Error 2
make[2]: Leaving directory '/media/pici/Cardinal/deps/surge-build'
make[1]: *** [Makefile:299: /media/pici/Cardinal/deps/surge-build/src/common/libsurge-common.a] Error 2
make[1]: Leaving directory '/media/pici/Cardinal/deps'
make: *** [Makefile:176: deps] Error 2
```

**Comment by falkTX** [comment]
Seems that this has already been fixed in https://github.com/surge-synthesizer/surge/commit/d2fba1c6ff02cbdfa9db2ce06508745c247629b5

But there is no surge-rack release that includes the fix.

To surge devs: Can a new surge-rack release be made, or a backport of the fix?
thanks!

**Comment by mkruselj** [comment]
Please post this issue in [surge-rack](https://github.com/surge-synthesizer/surge-rack/issues) repo.

**Comment by baconpaul** [comment]
Surge at head is very far from surge rack and is not ready for a stable release. Can you add a `-Icstdint` to your makefile for surge for now? A rack with an upgrade or a fork of the submodule are both painful and will take a while.

**Comment by maxigaz** [comment]
@mkruselj I opened an issue for surge-rack here, as you asked: https://github.com/surge-synthesizer/surge-rack/issues/889

**Comment by falkTX** [comment]
could this repo perhaps have a "hotfix" branch that surge-rack uses? so important bugfixes are pushed there, but doesnt stop regular development and changes on the main branch.
