### ISSUE TITLE
Memory junk displayed in modulation hover text

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#7066]
**Bug Description:**
When I modulate a DLY FX parameter, I see random memory rendered in the bottom line of the hover text.
Patch attached.
[Handbells Dev 2.005.fxp.zip](https://github.com/surge-synthesizer/surge/files/11848511/Handbells.Dev.2.005.fxp.zip)

**Surge XT Version**
Version: Surge XT 1.3.nightly.605b717
Build: 2023-06-05 @ 22:22:33 on 'WIN-9J4PM7PJGLL/pipeline' with 'MSVC-19.29.30148.0' using JUCE 7.0.5
System: Windows 64-bit VST3 on Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Host: Cakewalk by Bandlab @ 44.1 kHz / Process block size: 32 samples

**Reproduction Steps:**
1. While editing Scene B [might not be relevant], create a delay in FX slot G2.
2. Arm a macro.
3. Modulate the Mix [or any] parameter of created DLY.

![image](https://github.com/surge-synthesizer/surge/assets/13245475/a8220324-293d-4608-942d-6d784fbcbe56)

When you click on the slider to modulate, the hover text shows memory junk, where I expect to see the possible range of the applied modulation.

**Expected Behavior:**
I expect to see the possible range of the applied modulation.

**Screenshots:**
![image](https://github.com/surge-synthesizer/surge/assets/13245475/f239bebb-8915-4596-bc75-0c9beee865ce)

**Additional Information:**
Likely a mistyped variable, bad pointer, or old string, where the text is composed?

**Comment by mkruselj** [comment]
Probably has something to do with lib-izing effects to sst::effects...

**Comment by baconpaul** [comment]
definitely yes

i thought i tested that but it seems i missed something

will look

thanks as always for the outstanding report @j5v

**Comment by baconpaul** [comment]
Anyway got it fixed (and fixed one other related bug along the way). PR soon.
