### ISSUE TITLE
Flanger FBV

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#7083]
Flanger post port has this code

```
if (fbv < 0)
        fbv = fbv;
    else if (fbv > 1)
        fbv = fbv;
    else
        fbv = sqrt(fbv);
```

which looks pretty fishy. What's with that self assign? So just check I didn't blow it in the port before we ship 1.3.

**Comment by mkruselj** [comment]
Uhhh yeah that is probably supposed to be a clamp?

**Comment by baconpaul** [comment]
well i want to se what it was before the port. Has it been that way forever? That logic kinda makes sense and is continuous but it is a weird way to code it. (If that is correct it should be if(fbv > 0 && fav < 1) fav = sqrt(fav) etc

**Comment by mkruselj** [comment]
Looks like it was like that all the way back to XT 1.0:

https://github.com/surge-synthesizer/surge/blob/release-xt/1.0.0/src/common/dsp/effects/FlangerEffect.cpp#L251
