### ISSUE TITLE
Crash when left-click, drag & holding Mojo FX and dropping onto itself on a certain preset.

### ISSUE THREAD

**Issue by Jxp955** [surge-synthesizer/surge#7085]
**Bug Description:**
Dropping the Mojo FX onto itself will cause Reaper to crash when on a specific preset.

**Surge XT Version**
This information is found on the About screen, which you get to from the bottom right menu.

* Version: 1.2.0.cb11acd
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. 1st select the 'Slowboat > Rhythms > Bellish Shape Shimmer' preset from the 3rd party section.
2. Look for the Airwindows Mojo FX on the Global FX 2 slot at the end.
3. Left-click, drag and move the FX box slightly, and then release so it drops onto the same spot (onto itself).
4. Reaper will then crash.

**Expected Behavior:**
There should be no change to the FX or slot when dropping onto itself, and there usually isn't.

**Screenshots:**
N/A.

**Computer Information (please complete the following!):**
 - OS: Windows 10 Home
 - Host: Reaper
 - Version: 6.80

**Additional Information:**
This doesn't happen on the initial patch.

**Comment by baconpaul** [comment]
Thank you! I don’t know if we consider that case and I can imagine a bunch of ways it crashes 

let me tag this into 1.3

**Comment by baconpaul** [comment]
Can repro in standalone at head also. Real bug. Lemme peek.

**Comment by baconpaul** [comment]
Yup got it. Thank you. Will push fix later today into nightly and 1.3 will have this resolved.

Also the FX Swap now participates in undo properly also, which I discovered it didn't when resolving this issue.

Thanks for the very high quality bug report. Appreciated.
