### ISSUE TITLE
MPE 24 Semitones pitch bend for the linnstrument

### ISSUE THREAD

**Issue by fredericcormier** [surge-synthesizer/surge#709]
The Linnstrument defaults to 24 semitones pitch bend up and down while roli defaults to 48.

Currently I have to use a separate split on my LS just to use surge (@48)

Could you give us the option in the menu or the gui to select either 48 MPE semitones or 24 MPE semitones.

Keep up the good work.

**Comment by baconpaul** [comment]
Oh sure! Good idea. May take a little while to get to this

Hey while I have you did you get note sticking in mono modes with your linnstrument? I did with my Roli and need to go fix it still

Thanks

**Comment by fredericcormier** [comment]
Yes, I Did but did not stress test it. Anything you want me to test ?

**Comment by baconpaul** [comment]
Not yet let me get a few fixes in first but I will definitely take you up on that offer once we get some mpe stuff fixed. Thank you!!

You may want to watch #339 also.

**Comment by baconpaul** [comment]
Oh just a reminder to myself this is the kinda thing to put in userprefs hanging off a menu / MPE submenu

**Comment by baconpaul** [comment]
<img width="711" alt="screen shot 2019-03-06 at 3 05 56 pm" src="https://user-images.githubusercontent.com/13387561/53910226-61c66080-4021-11e9-8041-3eb396bb0360.png">

Hey just an FYI that I'm about to push this feature

which with the nightlies on mac and windows will let you select and permanently store your pitch bend range. (When you change it it will change on all surges opened thereafter).

Will put a note in this ticket when the nightlies have the feature. You can grab the nightlies at https://surge-synthesizer.github.io. This will also be in beta 7 which we will probably drop in the next 10 days.

**Comment by fredericcormier** [comment]
That was fast.
Thank you very much

**Comment by baconpaul** [comment]
No problem! Should be in the nightlies in about half an hour.

Now if you can do me a favor: Can you beat up the synth in MPE mode? I keep getting stuck notes in the mono modes. If you do to and you happen to have a midi file or some such which shows that it would help me debug.

Also any other feedback about bugs always welcome

**Comment by fredericcormier** [comment]
OK, I'll test that tomorrow.
