### ISSUE TITLE
"Use MTS-ESP..." option no longer necessary.

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#7112]
Now that we know how stable MTS-ESP is, and now that the user has a good option to disconnect individual Surge instances from it if needed, that option isn't needed. So let's remove it to alleviate confusion. :)

**Comment by baconpaul** [comment]
removing the menu item is easy; we just need to also remove the check for the condition in case someone set this on in the paleolithic era and then changed their mind.
