### ISSUE TITLE
Surge Is not available to ProTools on Mac

### ISSUE THREAD

**Issue by BHudders01** [surge-synthesizer/surge#7114]
Hi I hope you can assist, I have had Surge XT installed on my Mac (version 12.4 Monterey) for quite some time now see below for version info

My problem is it does not appear in my Protools (version 2023.6) track inserts options so I cannot use it and I'm eager to get going with it, it looks great on the surface but I want to hear it and do things with it

I have version: Surge XT 1.0.1.60228e8
Build: 2022-01-31 @ 16:53:52 on 'Mac-1643647381380.local/pipeline' with 'AppleClang-12.0.0.12000032' using JUCE 6.1.2
System: macOS 64-bit Standalone on Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
Sample Rate: 44.1 kHz

Maybe it is superseded but I do remember running the installer and it showed no errors

Your guidance is much appreciated

Feel free to drop a mail to bhudders@gmail.com preferably

Best regards
Brian Hudson

**Comment by mkruselj** [comment]
Surge as a free and open source project cannot be built using AVID's AAX SDK, hence is not available as an AAX plugin. You may use one of VST plugin hosts, like BlueCat Patchwork, Komplete Kontrol, etc that are available as AAX plugins, to host a Surge VST3 instance, but that's about it.

**Comment by baconpaul** [comment]
I’m also going to close this issue; alas there’s nothing we can do with the current state of available apis which pt supports.

**Comment by BHudders01** [comment]
Thanks Paul greatly appreciate the quick response please close the call 

Best regards Brian Hudson
