### ISSUE TITLE
Channel sustain pedal 

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#7115]
Yeah <https://github.com/surge-synthesizer/surge/blob/448b4efcc9b1279277b892a18ee7d11038cab889/src/common/SurgeSynthesizer.cpp#L2100> the channel hold only applies to the channel with the sustain pedal. That’s an oddity in all our modes. There’s special mpe treatment elsewhere but you aren’t in mpe mode. I’ll open an issue

In octave per channel mode sustain pedal is channel limited basically 

Discord user conradtao

**Comment by mkruselj** [comment]
Right, so the solution is to accept sustain pedal as omni in channel per octave mode.

**Comment by baconpaul** [comment]
Yeah exactly

and I should re test mpe 

and we should think about 2/3 mode also

**Comment by mkruselj** [comment]
I'd say let's keep that mode for 1.x and axe it in XT2.

**Comment by baconpaul** [comment]
Yeah agree. or perhaps have a better midi control overall. Like if a scene has a midi filter etc then it’s not hardwired and mysterious 

if we write arpeggiators and chord modes we are messing with the front of the note stack anyway so it’s a good opportunity 

but that’s not this issue! And not this year :)

**Comment by mkruselj** [comment]
To me, a more elaborate MIDI channel handling only has merit if we resuscitate the old "more than two scenes" feature request. 🙂

**Comment by baconpaul** [comment]
oh yeah excellent points all!

**Comment by mkruselj** [comment]
Hell, maybe we should axe this behavior for 1.3 already? Although I can imagine some projects relying on this behavior... maybe we could detect events being received from ch2/3 if MPE is not enabled then throw a dialog to then automatically set channel split accordingly?

**Comment by baconpaul** [comment]
Nah it works and we have an option. More trouble to axe it than leave it
