### ISSUE TITLE
SF2 oscillator type

### ISSUE THREAD

**Issue by CurlyMC** [surge-synthesizer/surge#7120]
Would it be feasible to add soundfont SF2 as an oscillator type into Surge XT ?

Since discovering Swami Project ( http://www.swamiproject.org/ )  on my linux system, having lots of fun creating my own soundfonts & playing with existing soundfonts.
Although maybe dated, the open soundfont format is  very powerfull, almost endless possibilities for making professional sounds & presets from short wav files into a single sf2 file ! 
Wav files can be looped, played once, layered ect, would be super to be able to combine this with surge XT's synth features.

Thank you Surge team for all superb instruments !

**Comment by mkruselj** [comment]
We have already had this topic, there was no need to open a new one.

The focus is to enable SF2 loading for Shortcircuit XT, not Surge.

**Comment by baconpaul** [comment]
Short circuit even in pre alpha form has pretty good sf2 support already though. If you are interested in trying that!

**Comment by CurlyMC** [comment]
Hi there @baconpaul & @mkruselj, thank you for the fast reply.

Yes, I would be very interested in giving ShortCircuit a try, looks promising and I'm sure the development is in good hands :-)
Already put it on my linux system and it also opens perfectly in my Qtractor daw, but I can't load SF2, because the gui still looks very alpha.
![ShortCircuit 27-07-2023 on Qtractor](https://github.com/surge-synthesizer/surge/assets/72344251/84550ba4-85c6-4bdf-ac97-e61a5d521ea2)

**Comment by CurlyMC** [comment]
Hi there @baconpaul & @mkruselj  , thank you for the fast reply.

Did ask for SF2 support in SurgeXT because still dreaming to be able to load some wav file using it as  an oscillator type ( either via some wav import or feature sfz implementation.. ). Sorry ok, mkruselj with [#1069](https://github.com/surge-synthesizer/surge/issues/1069) you're right.

Yes be very interested in trying SC, it's looking promising and I'm sure development is in good hands :-)
In fact I just put the latest version 27/07/2023 on my linux system and it also opens perfectly as a clap / vst3 plugin inside Qtractor daw.
I succesfully can import SF2 files, as long as I don't save them as 24bit from Swami ( the editor in which I create my soundfonts ).
When saving a soundfont in 24bit format, ShortCircuit displays : SF2 Load Error - Unable to load SF2 bit-depth 48.
For your information, Kind Regards, Luc.

**Comment by mkruselj** [comment]
SC currently doesn't support 24 bit samples, this is a known issue and is tracked in SC github repository, not here.

**Comment by baconpaul** [comment]
Oh it supports 24 bit wav but not sf2

@CurlyMC if you are on discord can you dm me a link to the sf2? I only have 16 bit ones in my test suite

**Comment by CurlyMC** [comment]
@baconpaul 

Created a zip with the soundfont files.
If you need any other 16 or 24 bit soundfonts, let me know.
[SF2-Test.zip](https://github.com/surge-synthesizer/surge/files/12194150/SF2-Test.zip)

**Comment by baconpaul** [comment]
Thanks so much. Lets continue over https://github.com/surge-synthesizer/shortcircuit-xt/issues/616 here
