### ISSUE TITLE
Would it be possible to be a little more strict with changelog formatting?

### ISSUE THREAD

**Issue by luzpaz** [surge-synthesizer/surge#7131]
Currently 1.2.1, 1.2.2 and 1.2.3 are consolidated. This makes it hard to remotely parse the changes that were made in the 2 minor versions after 1.2.1 

![Screenshot_20230731_164255](https://github.com/surge-synthesizer/surge/assets/4140247/d727d81b-aa53-41c1-8cf4-a622c2f3102e)

ref: https://surge-synthesizer.github.io/changelog/

**Comment by baconpaul** [comment]
oooh the changelog is really not designed for parsing. What's your use case?

1.2.1 and 1.2.2 lasted order days or hours so we didn't break them out; but that was more for human consumption.

**Comment by luzpaz** [comment]
Usecase: http://freshcode.club/submit/surgext

![Screenshot_20230731_170343](https://github.com/surge-synthesizer/surge/assets/4140247/c01f7c81-deac-4475-94ea-a6340a06286c)

But there are other downstream packagers that may be parsing changelogs as well.

**Comment by baconpaul** [comment]
Oh you should track our releases with tags not parsing the change log! We have signed git tags for each release and a distinct branch for each release which is atomic with the code changes

**Comment by mkruselj** [comment]
What Paul said.
