### ISSUE TITLE
Tracking Surge XT in the downstream package ecosystem

### ISSUE THREAD

**Issue by luzpaz** [surge-synthesizer/surge#7132]
Currently there is a lot of conflicting data in downstream package repos, see https://repology.org/project/surgext/related

Once we've sorted them in repology I'll post a badge here to see what repos are up to date and which repos are missing Surge. Then the need to request said repos for a package to be implemented (if warranted).

At the time of this post repology is tracking the following surge* downstream packages:

<a href="https://repology.org/project/surge-xt/versions">
    <img src="https://repology.org/badge/vertical-allrepos/surge-xt.svg?header=surge-xt" alt="Packaging status">
</a><a href="https://repology.org/project/surge/versions">
    <img src="https://repology.org/badge/vertical-allrepos/surge.svg?header=surge" alt="Packaging status">
</a> 

### TODO

- [ ] Alpine
- [ ] Void

**Comment by baconpaul** [comment]
Thank you for looking at this 

The surge 1.9 and surge xt should exist both in parallel; there’s an archival reason to have both installed.

but I agree the 1.7 and 1.0.1 and all the names is not really … good 

there’s also the question of whether these packages work. Many apply patches and changes which we never test. But there’s nothing to be done about that

**Comment by mkruselj** [comment]
Packages maintained by someone other than us (especially doing changes not sanctioned by us) are not our responsibility.

**Comment by baconpaul** [comment]
Yeah but wrangling them into shape a bit as @luzpaz offered to do is welcome

**Comment by luzpaz** [comment]
So to be clear how should the packages in repology look like?

> The surge 1.9 and surge xt should exist both in parallel; there’s an archival reason to have both installed.

Does this mean there should be a placeholder for `surge1.9` and for `surge-xt` ?

Which are the ones that are acting as 'forks' ?

**Comment by mkruselj** [comment]
From my POV packages should be called `surge` and `surge-xt`.

**Comment by baconpaul** [comment]
There was already a home brew package called surge for completely different software hence the surge-synthesizer moniker there just fyi

**Comment by mkruselj** [comment]
Hmmm well darn. How about `sst-surge` and `sst-surge-xt`?

**Comment by baconpaul** [comment]
Oh it’s too late to change homebrew - I was just sharing we have two packages there and we could model the distros the same

**Comment by luzpaz** [comment]
We can tell repology to associate the homebrew packages with whatever project name you choose.

**Comment by baconpaul** [comment]
so if repology tracks homebrew, then 

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/surge-synthesizer.rb

and

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/surge-xt.rb

are the two packages

**Comment by luzpaz** [comment]
At the time of this post repology is tracking 2 package names:

<a href="https://repology.org/project/surge-xt/versions">
    <img src="https://repology.org/badge/vertical-allrepos/surge-xt.svg?header=surge-xt" alt="Packaging status">
</a><a href="https://repology.org/project/surge/versions">
    <img src="https://repology.org/badge/vertical-allrepos/surge.svg?header=surge" alt="Packaging status">
</a>

**Comment by baconpaul** [comment]
Wow thank you. So I guess we need to find a nix maintainer yeah?

**Comment by luzpaz** [comment]
Are these current name assignments amicable? (Or does anything need to be tweaked?)

**Comment by mkruselj** [comment]
No, that's perfectly fine!

**Comment by luzpaz** [comment]
Added request for downstream Chocolatey: https://github.com/chocolatey-community/chocolatey-package-requests/issues/1443

**Comment by baconpaul** [comment]
thank you so much for doing this work. It's really appreciated.

If you join (or have joined) our discord please let us know your name and we can tag you with the team member role!

**Comment by mkruselj** [comment]
@baconpaul @luzpaz So what do we do with this ticket? Do we close so we don't need to track it, but still open for discussion, or?

**Comment by luzpaz** [comment]
I vote to keep open for exposure to help improve downstream availability.

**Comment by mkruselj** [comment]
Yeha let's try doing that.

**Comment by luzpaz** [comment]
You can also transfer this ticket to a discussion... ?

**Comment by mkruselj** [comment]
It is already tagged as a discussion but as long as it is open it counts towards our open issues. And it's not really an issue per se.

**Comment by luzpaz** [comment]
Opened a ticket request to bump nixOS unstable to 1.2.3

**Comment by baconpaul** [comment]
OK!

We are about to release 1.3 - probably this weekend latest - just so you know!
Is there a way we would let you know that that works? If so we can add it to our release checklist.
Thanks so much

**Comment by luzpaz** [comment]
> Is there a way we would let you know that that works?

Just post to this ticket :+1:

**Comment by baconpaul** [comment]
Good morning! We updated to 1.3.0 this morning. 

Thanks for all your efforts.

**Comment by luzpaz** [comment]
Flagged Arch repo that new update is available

**Comment by baconpaul** [comment]
Hi! Just FYI we updated to 1.3.1 today

**Comment by luzpaz** [comment]
No response from Arch maintainer :disappointed:

**Comment by Andreya-Autumn** [comment]
> No response from Arch maintainer 😞

Oof! Well, we may do a 1.3.2 with some bugfixes and small QOL stuff anyway. We'll let you know when that's up and you can ping them again, hopefully just a hiccup.

**Comment by luzpaz** [comment]
nixOS unstable updated to 1.3.1

**Comment by mkruselj** [comment]
@luzpaz We have released 1.3.2!

**Comment by baconpaul** [comment]
@luzpaz FYI we released 1.3.3

**Comment by luzpaz** [comment]
Bumped Arch and Nix repos

**Comment by baconpaul** [comment]
Hi!

1.3.3 had a nasty bug in it. 1.3.4 is out now. Thanks and sorry about that.

As to surge-xt vs surge, both packages are valid. But most users want surge-xt indeed!

**Comment by luzpaz** [comment]
Note: Chocolatey has added surge-xt to its package repo.
