### ISSUE TITLE
Extended Keyboard Maps are not necessarily reliable on all keyboards and oses? maybe?

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#7133]
Teeny tiny question;
Is it a mistake - or - 
are the left bracket and apostrophe keys reversed on the SurgeXT Virtual Keyboard QWERTY layout?
Kinda hoping there's a way to edit that?

Along with changing the Right Bracket key opening the context menu?

From Jason brachter on github

**Comment by baconpaul** [comment]
hmm on my mac

1: the qwerty layout doesn't extend anyway and
2: ] still opens menus

i think the table is not right quite for laptop keyboards and the like. 

i'm not really sure what's to be done here. the left bracket doesn't even play for me and the apostrophe is not in a spot where i would see it on the keyboard. Any ideas?

**Comment by baconpaul** [comment]
Ahh #7802 fixed the menu button

so this is just 'they layouts don't seem to quite work' more than anything else.

**Comment by mkruselj** [comment]
Yeah the extended QWERTY keys is more for a regular fullsize keyboard. I went by the picture of US ASCII on Wikipedia, heh. But who knows, maybe some keycodes are wrong?

**Comment by baconpaul** [comment]
i think some might be a bit ambitious but its partly stuff getting eaten elsewhere. The accessibility glitch is fixed and this feature basically works. I'm going to close this since there's nothing else to *do* on it I don't think. See what people say when we ship 1.3.
