### ISSUE TITLE
Surge breaks all rendering on Linux Mint

### ISSUE THREAD

**Issue by Nukiloco** [surge-synthesizer/surge#7140]
**Bug Description:**
Surge window will start to corrupt graphics by rendering almost everything black, until all the monitors are black.

**Surge XT Version**
Latest debian package version.

**Reproduction Steps:**
1. Just open the program, it completely breaks the whole OS rendering until you close it.

**Expected Behavior:**
To not bug out rendering.

**Screenshots:**
None

**Computer Information (please complete the following!):**
 - OS: Linux Mint
 - Host: None
 - Version: Latest

**Additional Information:**
nvidia-driver-525
Geforce GTX 750 Ti
Geforce GTX 1050 Ti

I'm pretty sure no other programs, including games break rendering like this so I wouldn't have a clue why surge does this.

**Comment by baconpaul** [comment]
what version is 'latest'?
do any other juce programs (like dexed or odin2) work for you?

**Comment by Nukiloco** [comment]
Can't debug that, since LMMS does not support using so files as a VST3 plugin, this would probably use Wine instead which would probably just outright not show the issue at all.

**Comment by baconpaul** [comment]
How are you using surge then?

**Comment by mkruselj** [comment]
I'm guessing standalone.

**Comment by Nukiloco** [comment]
I can't reach it. Also this time when closing the application, the application stays as a window even though its not a process anymore on Linux. And I can click through it now.

**Comment by Nukiloco** [comment]
![Selection_018](https://github.com/surge-synthesizer/surge/assets/16618467/466a88e7-fb63-493f-9378-6e503f67e5cd)

**Comment by Nukiloco** [comment]
The version I have is surge-xt-linux-x64-1.2.3.deb

**Comment by Nukiloco** [comment]
Updating linux mint seem to fixed the issue.
