### ISSUE TITLE
Is it possible to add track envelopes in the start and end loop of the step sequencer?

### ISSUE THREAD

**Issue by Lo-lo78** [surge-synthesizer/surge#7144]
Hi, I wanted to make track envelopes in the project to change the sequencer over time.
I couldn't find anything to trigger track envelopes for the loop.
I don't know if it could be down to the screen reader. Maybe it is already possible?
If it's possible it would be great if you could control all the step sequencer from the track envelopes to give more dynamics to the sequence.
Thank you!

**Comment by Andreya-Autumn** [comment]
Hello there! It's not just the screen reader, the params of the step sequencers are not exposed to DAW automation. One good reason for that is that adding another (counts real quick) like 700 parameters to the DAW param list seems like a non-starter. MSEG has the same problem. 

Just automating the start end points and jog buttons seems more reasonable though. And this request has been logged before as issue #1798 and the answer seems to be "Hopefully for XT2". So I'm gonna go ahead and close this one as a duplicate.
