### ISSUE TITLE
Tuning Editor functionality in MTS Client Mode

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#7146]
Currently if Surge is in MTS-ESP client mode the Tuning Editor is dormant and not reading data

The request is to have Radial and True Keys provide scale information as it would if Surge was playing from a loaded .scl file

As per our discussion on Discord:

True Keys display would require:

1: The currently pressed keys
2: Their frequency
3: The ability to subtract and take a log 

*Since we show actual keys not scale tones. We have all of that in MTS mode

The Radial display would require:

1: The currently pressed key
2: The scale tone for each of those keys
3: The repetition interval of the scale
4: Their frequency
5: The ability to subtract and take a log

*We are missing 2 and 3 in the MTS api but have it in the tuning library

**Comment by baconpaul** [comment]
Yup. So basically this amounts to

1. In MTSmode enable the tuning editor menu but
2. Have the SCL/KBM, Interval and Radial tabs not available
3. Just show tru interval and the side keyboard
