### ISSUE TITLE
Add Tone Circle to Radial

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#7150]
Scala and Entonal offer a Radial Dial where the notes appear at their distance from each other whereas Surge's radial has notes equally apart based on the number of notes per scale while showing their deviation from equal. As per a discussion on Discord there was interest in having this Scale Tone circle feature added to Surge.

Currently the Radial dial in Surge appears as follows 

![Screenshot_20230808_211100](https://github.com/surge-synthesizer/surge/assets/41337033/b33129ae-415e-45e3-8b51-7c119460a05b)

For the same tuning, Scala offers this variation:
![Screenshot_20230808_211001](https://github.com/surge-synthesizer/surge/assets/41337033/1652c36a-2916-4ee5-aee6-118fcee38b31)

Same tuning for Entonal displays with this style:
![Screenshot_20230808_211213](https://github.com/surge-synthesizer/surge/assets/41337033/26d0c713-5f10-43d4-9986-2e84bd4eff40)

The tuning for reference:

```
! 17 Tone 5 5ths down 4/3 generator.scl
!
17 Tone 5 5ths down 4/3 generator
 17
!
 256/243
 65536/59049
 9/8
 32/27
 8192/6561
 81/64
 4/3
 1024/729
 262144/177147
 3/2
 128/81
 32768/19683
 27/16
 16/9
 4096/2187
 243/128
 2/1
 ```
 
As for the display, having both the fractions (or cents) for the notes (as per Entonal) as well as the distance between the notes in cents (as per Scala) would be ideal.

**Comment by baconpaul** [comment]
If it’s easy I’ll put it in 13

if it’s not I won’t :)

**Comment by mkruselj** [comment]
To me this should be an additional button in Radial mode, rather than a whole new mode on the bottom.

**Comment by baconpaul** [comment]
Absolutely
And probably a sticky pref

**Comment by mkruselj** [comment]
Yeah it would just be a global setting set by that button, no need to add anything to any menu.

**Comment by baconpaul** [comment]
indeed. we are thinking the same way

**Comment by baconpaul** [comment]
<img width="776" alt="Screen Shot 2023-08-09 at 9 15 27 AM" src="https://github.com/surge-synthesizer/surge/assets/13387561/ac80e287-0f0a-4406-82a8-52bfcc6c2666">

Basically change it to look like this yeah?

**Comment by baconpaul** [comment]
oh that's `baconpaul/angular-7150` just so i remember and don't lose the code. that button doesn't do anything yet either.
