### ISSUE TITLE
VST2/AU EFx area will sometimes flicker when moving "master sliders" or other "stuff on the right"

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#716]
this seems to have been reduced with PR#715 - only appears in VST2 now. will try a Master build and see if that flickers too

![surge-mastervolume](https://user-images.githubusercontent.com/4966687/53747501-0de63b00-3eac-11e9-910d-b2edec8e0b45.gif)
![surge-mastervolumev2](https://user-images.githubusercontent.com/4966687/53747504-0faffe80-3eac-11e9-962f-3b67d4f77ad2.gif)

**Comment by esaruoho** [comment]
<img width="155" alt="screenshot_04_03_2019__18_41" src="https://user-images.githubusercontent.com/4966687/53748016-24d95d00-3ead-11e9-8a34-28e2167b5387.png">

**Comment by esaruoho** [comment]
here's another video that shows more of it:
https://surgesynth.slack.com/files/UF7BKN3D2/FGN0B4F2L/file_from_ios.mov
(requires surgesynth slack access tho)

**Comment by baconpaul** [comment]
I can do this pretty reliably by using an SLFO modulation on a sub-Parm of a reverb with current master. Definitely something off in the invalidate/redraw of that effects panel.

**Comment by baconpaul** [comment]
Figured this out. It's my VU meter optimization getting over excited.

Fix coming shortly.
