### ISSUE TITLE
Scene copy + paste doesn't handle Insert FX as modulation targets.

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#7166]
I was unsure whether this should be a bug report or a feature request, but I opted for bug report, because the mapping resulting from a **Paste** doesn't make sense.

**Bug Description:**
If I'm merging two patches, and **Copy scene** A, then **Paste** on Scene B, then for modulations that target Scene A Insert FX, the source of the modulation is still Scene A.

Screenshots: After pasting Scene A to Scene B, we see Scene A has the new copies. Scene B has none of them (because the corresponding FX don't exist there).

Scene B
![image](https://github.com/surge-synthesizer/surge/assets/13245475/d00e6cd6-9a49-4c96-b4fa-8c49f7c628c8)

Scene A (which targets Scene B Insert FX)
![image](https://github.com/surge-synthesizer/surge/assets/13245475/4ef12728-608e-40c0-abba-bcb5a8db8ff0)

**Surge XT Version**
Version: Surge XT 1.3.nightly.448b4ef
Build: 2023-07-23 @ 10:21:58 on 'fv-az515-638/pipeline' with 'Clang-15.0.7' using JUCE 7.0.5
System: Windows 64-bit Standalone on Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Sample Rate: 48.0 kHz / Process block size: 32 samples

**Reproduction Steps:**
(above)

**Expected Behavior:**
Ideally:
1. Scene A Insert FX should copy into Scene B Insert FX, then
2. Modulations are copied from Scene A to Scene B, and target the corresponding Scene B Insert FX, from Scene B sources.

**Screenshots:**
(above)

**Additional Information:**
High impact, infrequent occurrence.

**Comment by baconpaul** [comment]
This one is a bit tricky but let me look in this cycle. Thank you for the detailed report.

**Comment by baconpaul** [comment]
```
baconpaul — Today at 10:48 AM
surgo said they were interested so lets leave it
OK so in #7166 @j5v has proposed a behavior change which I think is a good one but lets just discuss. Right now if you make scene A with FX A1 = Delay and copy scene A to scene B, then A1 stays delay but B1 does not become delay. So

Do we want to copy insert effects with scenes always or optionally (so add a copy and copy-with-inserts) or never
If we don't copy the insert fx, what do we want to do with modulators that point at the fx now in scene b. Options are
  a) don't copy them
  b) leave them pointing at A
  c) have them point at random stuff in B

Right now we choose "never and 2c" which seems the worst possible choice. 

I personaly like optionally and 2a myself but am all ears
EvilDragon — Today at 10:52 AM
2a
baconpaul — Today at 10:52 AM
right so 1 optional 2 a
EvilDragon — Today at 10:52 AM
well
baconpaul — Today at 10:52 AM
i think is the best
EvilDragon — Today at 10:52 AM
I gurss
if you consider insert A as part of scene
to me FX grid is a global thing
scene ends at output section
baconpaul — Today at 10:53 AM
so you are 1 never 2 a
but that does mean there's no way to move a scene from A to B easily
EvilDragon — Today at 10:53 AM
but both views are valid
if the code is not tricky do 1
maybe throw a prompt if B has FX already
baconpaul — Today at 10:54 AM
I guess if we go 1 optional then "no fx copy -> pointing at FXA gets removed; yes fx copy -> pointing at FXA poitns to FXB"
EvilDragon — Today at 10:54 AM
if it doesn't just copy directly
no need for a another copy option to confuse
baconpaul — Today at 10:54 AM
gotcha so copy always copies; but paste prompts with a never ask again
EvilDragon — Today at 10:54 AM
could jive with that
EvilDragon — Today at 10:54 AM
well maybe not bad to always ask tbh
without option to disable prompt just for safety
baconpaul — Today at 10:55 AM
so "copy always copies inserts; paste prompts if B inserts are set up, and A modulations move to B modulations if you say yes and blank if you say no"
```
