### ISSUE TITLE
Minor: String oscillator > Stiffness filter option is not copied with Scene C+P.

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#7168]
**Bug Description:**
When I copied and pasted a scene, the Stiffness Filter option was unset at the target scene.

**Surge XT Version**

* Version:
Version: Surge XT 1.3.nightly.448b4ef
Build: 2023-07-23 @ 10:21:58 on 'fv-az515-638/pipeline' with 'Clang-15.0.7' using JUCE 7.0.5
System: Windows 64-bit Standalone on Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Sample Rate: 44.1 kHz / Process block size: 32 samples

**Reproduction Steps:**
-

**Expected Behavior:**
-

**Screenshots:**
-

**Computer Information (please complete the following!):**
-

**Additional Information:**
I tracked down the difference between two scenes that should have sounded the same. Stiffness Filter was the difference, and I hasn't deliberately set it in that session.

**Comment by j5v** [comment]
**Oversampling** and **Interpolation** options are similarly affected.

**Comment by baconpaul** [comment]
hmmm i can't reproduce this so maybe i dont understand

here's what I did

init sine
change to string
change stiffness to static
Copy scene A
Select scene B
Paste scene

and the stiffness is static

I can also see in the code where the deform type is being copied

so either I didn't understand or theres some extra step we need?

**Comment by j5v** [comment]
Perhaps I was working with legacy patches. I'll try a few things soon.

**Comment by mkruselj** [comment]
I cannot confirm over here.

**Comment by mkruselj** [comment]
@j5v Any further info on this one? Can we close if it's not reproducible even on your end?

**Comment by j5v** [comment]
Likewise, I can't reproduce.
I've tried loading patches from Surge 1.9, old XT, and XT nightlies.
I've tried minimal steps from init patches.
I suspect it was maybe an issue with streaming or default values, caused by non-public nightlies.

Agreed, I'll close. Thanks.
