### ISSUE TITLE
Make hover popups smaller for filter banks + FM routing

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#717]
see how they spill over?
they could be slightly smaller and better fit with the filterbank + oscillator fm routing "slider size"

![make-surge-popups-smallerv2](https://user-images.githubusercontent.com/4966687/53748717-982f9e80-3eae-11e9-8a20-b08f05ab8816.gif)

**Comment by mkruselj** [comment]
Considering now that we have skin engine quite flexible, this could mean that these two controls could look quite different, depending on how the skin designer does his job. So I wouldn't really worry about the width of these popups in the grand scheme of things. Will close this issue if you don't mind, Esa.
