### ISSUE TITLE
Single self-drawn buttons should respect colors of their SVG cousins

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#7173]
When using the Dark skin for instance, single self-drawn buttons have a blue hover as well as a blue on state (see the Waveform and Spectrum pane for instance), where they should have an orange on state like other SVG single buttons.

From this convo on Discord: https://discord.com/channels/744319641211633774/744320274714984518/1139553876127784980

**Comment by baconpaul** [comment]
the problem is that the off-hover isn't orange right?
since MSEG does do off-hover orange for the horizontal button must just be a setting. i'll look.
