### ISSUE TITLE
Surge XT Effects Crashes when audio driver is Jabra Elite 75t

### ISSUE THREAD

**Issue by jdr-ableton** [surge-synthesizer/surge#7186]
**Bug Description:**
Surge Effects standalone briefly opens and then crashes when using Jabra Elite 75t bluetooth headphones. I'm not sure if this would happen with other bluetooth headphones. I don't have any on hand to test.

**Surge XT Version**
Surge XT Effects 1.2.3.bb8dd2b
2023-05-05

* Bitness: 64-bit arm

**Reproduction Steps:**
1. Have the Jabra earbuds activated, connected, and set as the computer's audio output.
2. Play some audio. I was listening to something on Apple Music.
3. Click on Surge XT Effects to open it.
4. It will open for a little bit, and you will hear the sound change as the system audio gets rerouted(?). Then it will close, and probably cause an Apple crash report to be generated.

I think this has something to do with either this model of bluetooth earbuds or bluetooth audio in general, as the app works fine when system audio is set to laptop speakers. Switching to the jabras after the app has successfully opened does not cause the crash.

**Expected Behavior:**
Surge XT Effects opens and can be used.

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following!):**
 - OS: 13.4.1 (c) (22F770820d)
 - Host: Standalone

**Additional Information:**

Snippet from crash report.

```
Thread 10 Crashed:: Jabra Elite 75t
0   Surge XT Effects              	       0x104f294c4 SurgefxAudioProcessor::processBlock(juce::AudioBuffer<float>&, juce::MidiBuffer&) + 1464
1   Surge XT Effects              	       0x104f3ce80 juce::AudioProcessorPlayer::audioDeviceIOCallback(float const**, int, float**, int, int) + 1020
2   Surge XT Effects              	       0x104f13274 juce::StandalonePluginHolder::CallbackMaxSizeEnforcer::audioDeviceIOCallback(float const**, int, float**, int, int) + 120
3   Surge XT Effects              	       0x1052b3e2c juce::AudioDeviceManager::audioDeviceIOCallbackInt(float const**, int, float**, int, int) + 380
4   Surge XT Effects              	       0x1052bd940 juce::CoreAudioClasses::AudioIODeviceCombiner::run() + 1128
5   Surge XT Effects              	       0x10519f4dc juce::Thread::threadEntryPoint() + 288
6   Surge XT Effects              	       0x1051cf53c juce::threadEntryProc(void*) + 32
7   libsystem_pthread.dylib       	       0x191b53fa8 _pthread_start + 148
8   libsystem_pthread.dylib       	       0x191b4eda0 thread_start + 8
```

**Comment by jdr-ableton** [comment]
Nice :)

**Comment by baconpaul** [comment]
OK I applied the appropriate rhyming fix to the FX tonight and tested it with my headset. I really do like that headset!

Anyway this issue will auto close when I merge the issue, and about an hour after that, the new nightly will have the fix.
