### ISSUE TITLE
FM Don't work on Init SAW?

### ISSUE THREAD

**Issue by hems** [surge-synthesizer/surge#7197]
**Bug Description:**
Added second oscillator
Set to SINE
Setup FM to 2>1 
Set FM Depth to Max

**sounds DIDNT CHANGE change**

**Surge XT Version**
23/08/2023 build

* Version:
VST 3, 64 bits @ Windows 10
Ableon 11

**Expected Behavior:**
FM the SAW wave.

Download FXP example -> https://www.dropbox.com/scl/fi/8enamhoh09vklmueg58jp/Init-Saw.fxp?rlkey=bsgkuwac8171mb4477rhvuex2&dl=0

**Comment by baconpaul** [comment]
So the BLIT FM implementation is kinda hosed. If you move the pitch of the sin by half a step you can hear the effect is there.

If you want something more like a classic FM onto a saw, use the modern oscillator saw.

But what you are experiencing here is (1) real and (2) a dup of #6750 so let me close this one.
