### ISSUE TITLE
Why default MAX modulation for PITCH is 14 semitones?

### ISSUE THREAD

**Issue by hems** [surge-synthesizer/surge#7198]
I would expect the max to be 12 semitones as octaves are very useful.

Or 7 semitones to keep it the same as the regular pitch fader.

![image](https://github.com/surge-synthesizer/surge/assets/27327/b90eb2bd-714c-4b0b-bf3b-26cfda65aad9)

**Comment by baconpaul** [comment]
The modulation depth for any slider is (min...max), which in this case is 7 - -7 = 14, allowing you to do a full unipolar sweep across the range from min to max with one modulator.

if you want 12 semitones you can just type in 12 also!

if you extend the modulation depth goes to 96 - -96 = 192

but nothing to change here so I'm going to close this.
