### ISSUE TITLE
Why won't clang windows debug build in azure?

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#7199]
but release will

**Comment by baconpaul** [comment]
this seems to be a problem with yvals_core.h building juceaide

for now back down to msvc.

**Comment by haenkel** [comment]
win-clang is broken in the current runner image:
https://github.com/actions/runner-images/issues/8125#issuecomment-1691194433
an update was merged but not deployed yet.

**Comment by baconpaul** [comment]
Ahh thank you!

**Comment by haenkel** [comment]
It's up now

**Comment by mkruselj** [comment]
OK so we can close this I guess.
