### ISSUE TITLE
Clicking Bluetooth Midi crashes Surge XT

### ISSUE THREAD

**Issue by halfbeing** [surge-synthesizer/surge#7204]
**Bug Description:**
Clicking on "Bluetooth MIDI" in the Settings instantly crashes Surge XT on Mac.

**Surge XT Version**
1.3.nightly.174ba3f (and also occurred in a nightly released a couple of months or more prior to this).
Occurs in standalone application.
64-bit.

**Reproduction Steps:**
1. Open settings
2. Click on "Bluetooth MIDI"

**Expected Behavior:**
Not crashing.

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following!):**
 Mac OS 13.4.1 (Intel)
Standalone version of Surge XT

**Additional Information:**

**Comment by baconpaul** [comment]
hmmm i just tried it and got the bluetooth midi scan screen

did you get a crash log at all?

**Comment by baconpaul** [comment]
I’m going to close this as a non repro no follow up - if you do get a crash log please reopen it. Thanks
