### ISSUE TITLE
Popping noises for Grand Piano 2022 by John Valentine

### ISSUE THREAD

**Issue by Phylliida** [surge-synthesizer/surge#7216]
**Bug Description:**
Grand Piano 2022 by John Valentine makes popping noises when you play lots of notes really fast for a few seconds

**Surge XT Version**
Surge XT 1.2.3.bb8dd2b

**Reproduction Steps:**
1. Select Grand Piano 2022 by John Valentine
2. play CDEFGFEDCDEFG ... really fast for a few seconds
3. observe the popping and clicking noises

**Expected Behavior:**
Playing notes really fast with other patches doesn't have this issue, there should be no popping and clicking

**Computer Information (please complete the following!):**
 - OS: Windows 10
 - Host: None, I'm just running surge xt as a standalone thing and connecting it to my midi piano (Impact LX61+)
 - Version: NA

**Comment by mkruselj** [comment]
It's probably CPU overload. Does the same happen when you reduce polyphony?

**Comment by Phylliida** [comment]
I think you're right, the issue goes away once I reduce Poly to 13 or less

**Comment by mkruselj** [comment]
Yup so not much we can do here. Some rare patches just need (way) more juice.

Gonna close the issue, sorry!

**Comment by Phylliida** [comment]
No problem thanks for the help :) For those also having this issue, I found it helped to do:
- Also in the top left, Mode, Single (instead of Dual or anything else)
- Settings: Audio device type: Windows Audio (Exclusive Mode)
- Task manager set task priority to High
Those changes got me up to 24 poly without issues

**Comment by mkruselj** [comment]
You can also right-click the Play Mode parameter and use the "Reuse single" mode there. So then playing the same key will reuse a voice instead of trigger a new one. This should help considerably.
