### ISSUE TITLE
Midi Learn should be available for patch browsing.

### ISSUE THREAD

**Issue by wpostma** [surge-synthesizer/surge#7222]
**Is your feature request related to a problem? Please describe!**

Some plugins, especially Arturia's plugins have a lovely patch browsing system which let you midi learn the next/previous preset buttons. This makes playing through banks of presets a joy. Easy and fun. For people with less than perfect eye-sight, also, a keyboard and or a midi shortcut for patch navigation would be a usability improvement.

**Describe the solution you'd like:**

A.  Cursor Up/Down keys mapped to next/previous preset.
B.  Ability to right click on next and previous preset and click midi learn.

**Describe alternatives you've considered:**

There could be alternative ways to do this via some other way of setting up midi mappings, but midi learn would be the most clear and direct method.

**Additional context:**

This is not just a feature request it's a usability improvement for people with limited vision, and for people who are using Surge XT as a live instrument.

**Comment by baconpaul** [comment]
There’s already a big cable key for nex prev cat and patch. We bind it to nothing be default I think since it is pretty dangerous, especially was before we had undo. But the kbd options should let you set it.

**Comment by mkruselj** [comment]
As Paul said, you can bind prev/next patch actions if you press Ctrl+B to open the Keyboard Shortcuts overlay.

In the latest nightlies it is also possible to set up a MIDI Programs folder so that you can use MIDI Program Change and Bank Select messages to change patches, pretty much exactly as u-he plugins implement it.
