### ISSUE TITLE
Incorrect patch version message on "INIT SQUARE" with latest Surge XT VST3 plugin

### ISSUE THREAD

**Issue by mdkberry** [surge-synthesizer/surge#7225]
**Bug Description:**
So far it only happens with INIT SQUARE patch but I havent tested many others. I installed the latest Surge XT over my older version of Surge and I now get the attached version error message on INIT SQUARE. 

**Surge XT Version**
* Version: Surge XT 1.2.3.bb8dd2b
* Plugin Type: [VST3]
* Bitness: ?

**Reproduction Steps:**
- Open Surge XT as plugin
- Click through patches
- as soon as it reaches INIT SQUARE a pop up appears (see attached image screenshot)

**Computer Information (please complete the following!):**
 - OS: Windows 10 x64
 - Host: Reaper 6.82

**Additional Information:**
The old version of Surge 1.8.1.9 VST3 is still listed and runs, but I was expecting it to be over-written. Though given the nature of the error message I dont think it relates, I thought I would mention it.

Screenshot of error message for INIT SQUARE patch:
![surge vrs mismatch](https://github.com/surge-synthesizer/surge/assets/810955/63d49940-871d-4316-bf37-4a16d524e9b7)

**Comment by mkruselj** [comment]
This was fixed in 1.3.0 nightlies. Closing the issue.
