### ISSUE TITLE
Include response to MIDI Bank and Program change messages

### ISSUE THREAD

**Issue by nesdnuma** [surge-synthesizer/surge#7226]
I thought it was implicitely included but I didn't succeed in changing a preset with the VST3 version without even trying to choose a bank. Also, I couldn't find a MIDI implementation chart in the user's guide.

**Comment by mkruselj** [comment]
It's coming in Surge XT 1.3, it's in nightlies now.

https://github.com/surge-synthesizer/surge/pull/7171

VST3 is... problematic in this regard as long as we use JUCE for our plugin layer.
