### ISSUE TITLE
macOS VST2/AU: enable right-clicking on wavetable to get dropdown menu

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#724]
currently if you click on the wavetable name with left-mouse button, you get the list.
but if you click on the wavetable name with right-mouse button, nothing happens.

i propose: make right-mousebutton also show the list.

this was spoken about at #29 and seems like it was forgotten. so, i'm gonna look at what baconpaul did and make a PR out of it.

tried to PR #723
dunno if i'm doing it right :)

**Comment by esaruoho** [comment]
#723 didn't make it happen either, closing the PR

**Comment by baconpaul** [comment]
@esaruoho if you want to do this change

```
CMouseEventResult COscillatorDisplay::onMouseDown(CPoint& where, const CButtonState& button)
{
   if (!(button & kLButton))
      return kMouseDownEventHandledButDontNeedMovedOrUpEvents;
```

to

```
CMouseEventResult COscillatorDisplay::onMouseDown(CPoint& where, const CButtonState& button)
{
   if (! ( (button & kLButton) || (button & kRButton ) )
      return kMouseDownEventHandledButDontNeedMovedOrUpEvents;
```

and it should just all work.
