### ISSUE TITLE
Patch Binaries

### ISSUE THREAD

**Issue by zfarrell13** [surge-synthesizer/surge#7246]
Hello, I am trying to generate many random patches for a project that im working on.  I want to build a script that will generate and save patches, altering each parameters for the patch at specific intervals, but I do not know how to decode the patch binaries.  can someone point me to some documentation that can help me find this?

**Comment by baconpaul** [comment]
check out the `scripts/patch-tool` directory for python code that reads them

the basic format is

A VST2 "fxp" wrapper
the content block comprises an XML doc and optional wavetables
The XML block is written and read in src/common/SurgePatch.cpp
We do not have documentation beyond the code

Would be happy to expand the tooling or documentation here.

**Comment by baconpaul** [comment]
Oh and, speculating you might be doing some sort of machine learning training thingy which has you generating lots of patches, direct patch generation may not be the only option. We have an entire python embedded api which lets you configure the synth, and in the nightlies, have full open sound control access to the parameters also.  Those may be easier routes for re-configuring the synth repeatedly.

**Comment by mkruselj** [comment]
We will close the issue for the time being, but you are welcome to keep us updated here.
