### ISSUE TITLE
Skins parser produces "parse error" when encountering __MACOSX folders

### ISSUE THREAD

**Issue by jolohaga** [surge-synthesizer/surge#7249]
**Bug Description:**
When folders are zipped using the Finder, MacOS can add a __MACOSX folder to the contents of the zip archive. If such a zip file is passed to the skins parser, the parser will fail on the __MACOSX folder and issue a "parse error" message in the skins list.

**Surge XT Version**
* Version: 1.2.3
* Plugin Type: AU
* Bitness: 32-bit

**Reproduction Steps:**
1. Using Safari, download a skin archive from [the library](https://surge-synthesizer.github.io/skin-library/)
2. The download will be automatically unzipped. In the Finder find the download, right-click on it and select "Compress"
3. In Surge, drag-and-drop the Finder zipped file
4. Open the skins list and a list will appear tagged with "parse error". (see attached screenshot for an example)

**Expected Behavior:**
I expected to see a single set of skins to appear without "parse error" appearing.

**Screenshots:**
<img width="370" alt="Screenshot 2023-10-10 at 6 45 04 PM" src="https://github.com/surge-synthesizer/surge/assets/53976/8cd0a9f5-de99-4760-8c2a-bd58bb7ec3f1">

**Computer Information (please complete the following!):**
 - OS: MacOS Ventura 13.4.1
 - Host: Logic 10.7.9
 - Version: 10.7.9

**Additional Information:**
Please let me know if you need additional info. I can be reached in Discord.

**Comment by baconpaul** [comment]
Thanks. This will be easy to fix and I'll get it for 1.3. Excellent bug report. Appreciated.

**Comment by baconpaul** [comment]
Confirmed bug

**Comment by baconpaul** [comment]
Ahh there's two ways to solve it. The easy way is ignore __MACOSX directories form the zip file. The harder but better way is do that but also don't create them. I'll try and do both.
