### ISSUE TITLE
Wavetable Label on UI

### ISSUE THREAD

**Issue by sense-amr** [surge-synthesizer/surge#725]
Good afternoon/day or evening folks.. i was just playing with the wavetable feature of surge and it struck me that ive found yet  another example of a nomenclature within surge that isnt fit for purpose

Currently the Wavetable Section contains a parameter labeled "Shape" in order to describe effectively the traversal of wavetables from one to another.. it also displays this value as a % .. presumably a % of the total of 64 waveforms/waves in a wt.

![wtdisplay](https://user-images.githubusercontent.com/1504019/53795469-2dea2d00-3f86-11e9-915a-311c20c9544d.jpg)

presuming there is a format for WT which there certainly is and presuming that format consists of a maximum of 64 0-63 wavetable files or oscillators ..

that parameter should ..
1. display the current wavetable number ..
2. be labeled something like "travel" or "morph" because thats actually what its doing .. its traversing the "wave: table"

thoughts?

bang up job boys..

**Comment by baconpaul** [comment]
“Shape” is the wrong name
I think the control interpolates between tables so it will be fractional. That is with 5 tables the 12.5% setting is .5 * table0 + .5 * table1 - although I agree that would ideally show table number of “1.5” perhaps? And also i need to check that my statement is true :)

**Comment by sense-amr** [comment]
@baconpaul i would advocate a leaning to a more traditional nomenclature .. such as "morph" ?

**Comment by baconpaul** [comment]
Good suggestion!

**Comment by baconpaul** [comment]
Renaming this is in src/dsp/WavetableOscillator.cpp at line 103 or so (in ::init_ctrltypes). Changing the name shouldn't break streamed patches (the stream as a_osc1_param1 - the name is just for display) but this change would confirm that also in a couple of hosts.

**Comment by baconpaul** [comment]
Oh and we should change this in both Wavetable and Window when we do it.

**Comment by sense-amr** [comment]
yes they both refer to "shape"

**Comment by itsmedavep** [comment]
I have a branch that updates the label to morph. Do we want this to display something other than 0 - 100% morphed?

Im not sure what the correct answer would be. 

"wt position" for label and then the wt # seems to be the correct thing TBH. But im not sure that is actually what is happening. Is it mixing between wt's or just switching?

Doing the formula that Paul suggested above would take a bit of work and Im not sure it's very clear.

What does a morph of 1.5 mean exactly? A wt being 0% morph'ed or 100% morph'ed seems fairly understandable. 

Regardless, I can open a PR if all we want to do is update the label.

**Comment by baconpaul** [comment]
It mixes in wavetables mode and switches in window mode I bekeivr; the percentage is the percent along the table count for that wt 

Changing to not a percent is hard. With lots of ramifications. Even though it may be correct eventually

Morph vs position vs count I don’t have an opinion

**Comment by itsmedavep** [comment]
Given that updating the label to morph makes the most @sense-amr  to me <-- See what I did there?!?!

I opened a PR for this #760

**Comment by baconpaul** [comment]
OK I'll merge it when I look at PRs and stuff tomorrow. Thanks @itsmedavep!!
