### ISSUE TITLE
Sporadic loud noise when changing presets 

### ISSUE THREAD

**Issue by pkstone** [surge-synthesizer/surge#7250]
EDIT: I can produce this bug without playing *any* notes; it is merely a matter of changing to/from certain presets enough times to make the bug appear.  The new Python script does this, but it can also be done manually with the synth. See updated "Steps to reproduce, below".

**Bug Description:** 
Surge XT sometimes makes a loud blast of noise when changing presets under a moderate load of notes. The preset most noticeable in presenting the behavior is ".../patches_3rdparty/Inigo Kennedy/Leads/Happy Saws", but it may happen with others as well.

**Surge XT Version** 
Version: Surge XT 1.3.main.c694f89d
 NOTE: a recent nightly is required to ensure OSC support, which is used for this test.

Build: 2023-10-12 @ 13:49:40 on 'MacBook-Pro.local/local' with 'AppleClang-15.0.0.15000040' using JUCE 7.0.5
System: macOS 64-bit Standalone on Apple M2 Pro
Sample Rate: 48.0 kHz / Process block size: 32 samples
OS: [Mac OS 13.6]

**Steps to reproduce the behavior, with Python script:**
1. Grab 'Surge_Tester.py.txt' python program attached here; remove the '.txt' extension.
2.  Edit the patch path at the top of Surge_Tester.py to match your system; save changes
3. Start an instance of Surge XT (WARNING: KEEP AMPLIFIED VOLUME LOW AT FIRST!)
4. Run (Python 3) program Surge_Tester.py
5. Noise blast should happen before too long, but let it run a couple of minutes if you don't hear anything. 
7. Hit 'ctrl-c' to stop the endless test loop.

**Steps to reproduce, with Surge GUI:**
1. Load the following two patches:
  - Monster Feedback.fxp         (from "/patches_3rdparty/Argitoth/FX/Monster Feedback)
  - Tolk.fxp.                     (from "/patches_factory/Leads/Tolk")
 2. Cycle between the patches at about 1 change per second (hint: use the 'history' arrows), until the bug manifests.

**I want to stress again...do NOT run this test at high amplifier levels (especially with headphones)! The noise blast is quite loud.**

[Surge_Tester_2.py.txt](https://github.com/surge-synthesizer/surge/files/12907807/Surge_Tester_2.py.txt)

**Comment by pkstone** [comment]
I want to stress, do NOT run this test at high amplifier levels (especially with headphones)! The noise blast is quite loud.

When changing presets up and down, stay in the neighborhood of "Happy Saws". It's the most consistent at manifesting the problem.

**Comment by baconpaul** [comment]
Phil reports this fixed by 7523.

Good hunting!
