### ISSUE TITLE
iPad?

### ISSUE THREAD

**Issue by unculcated** [surge-synthesizer/surge#7251]
Any way to run surge Xt on an IPad? Maybe as a vst?
thanks

**Comment by baconpaul** [comment]
No for two reasons 

firsr we don’t build an auv3
Second if we did we couldn’t distribute it because the license is not compatible with the app store

sorry!

**Comment by vicwomg** [comment]
If you're willing to sideload or have a Apple developer account to build from source, I was able to port to iOS in this fork: https://github.com/vicwomg/surge-ios

IMO, it works excellently, even on my 2018 iPad.

Totally understand the Surge team's position, and not trying to shake things up as I'm a huge fan of their work, just took this on as a personal project for my own needs.

**Comment by baconpaul** [comment]
neat. and yeah *i* can run surge on my iPad is definitely achievable for jailbroken or apple devs. cool you did it! I'll look at the fork

but there's just no way we can distribute this as you know. which is a bummer.

**Comment by vicwomg** [comment]
> neat. and yeah _i_ can run surge on my iPad is definitely achievable for jailbroken or apple devs. cool you did it! I'll look at the fork
> 
> but there's just no way we can distribute this as you know. which is a bummer.

Technically, you do not need to jailbreak, anyone can sideload the pre-built .ipa file in the fork using Sidestore/Alt Store, no need to compile the code yourself. It's a bit of a pain, because you have to refresh the certificate every 7 days, but it is achievable and probably the approach I will take.

Also FYI the EU requires Apple to allow alternate iOS app stores in Europe, in which case an official iOS build is possible through those means (I believe the most popular alt store is called Alt Store PAL). Certainly worth looking into

For more on the current alt app store situation allowing 3rd party app stores in Brazil, Japan, or the European Union see: https://support.apple.com/en-us/117767?cid=ot-ols-apps-article_117767-installation_message-02022024

**Comment by nuoun** [comment]
Neat fork, thanks for sharing. I'm not an Apple user myself but would love to see an iOS build target like OB-XF has.

So there is no way around disabling LuaJITs JIT compiler (see: https://luajit.org/install.html#ios), and `-DLUAJIT_DISABLE_JIT` is totally correct. It would be a shame if we have to disable Lua altogether so I do wonder how is performance without the JIT? My wild guess is it loses about 10-50x speedups, does that bite? Using the Lorenz Attractor Formula preset to modulate a parameter is probably a decent benchmark here.

**Comment by baconpaul** [comment]
> For more on the current alt app store situation allowing 3rd party app stores in Brazil, Japan, or the European Union see: https://support.apple.com/en-us/117767?cid=ot-ols-apps-article_117767-installation_message-02022024

yeah its an evolving situation i agree. I'm not in those jurisdictions (but i do have developer certs so I could just do it).

**Comment by ironcross32** [comment]
I'm a blind screen reader user, and this is actually working... sort of. But hey, if it worked flawlessly, I'd be blown away. As far as the synth doing what it's supposed to be doing, yeah, that's definitely working. Never thought I'd see SUrge on an iPad but hey...

**Comment by baconpaul** [comment]
yeah the only reason its not on the iPad for years is the spread between the FSF and Apple view of GPL3 in the app store.

**Comment by vicwomg** [comment]
FYI, I also successfully got it running on Android. Filesystem permissions were a chore, but it seems to work. Works OK on my Pixel 6, UI is a bit more choppy and the phone gets pretty hot, but audio output seems fine down to 352 samples (some sample rates were not selectable for some reason)

apk is here for anyone who wants to try: https://github.com/vicwomg/surge-ios-android/releases/tag/v0.1.0-alpha
