### ISSUE TITLE
change this message on .deb files to mention it stores clap too

### ISSUE THREAD

**Issue by RustoMCSpit** [surge-synthesizer/surge#7257]
Subtractive hybrid synthesizer virtual instrument
Surge XT includes VST3 and LV2 instrument formats for use in compatible hosts and a standalone executable

**Comment by mkruselj** [comment]
Nice spot! We will update.

**Comment by baconpaul** [comment]
Oh and remove the lv2 mention since we don’t do that binary in 13 too

**Comment by mkruselj** [comment]
Do the same for ROM.
