### ISSUE TITLE
Have a plugins only version for the .deb files

### ISSUE THREAD

**Issue by RustoMCSpit** [surge-synthesizer/surge#7258]
I use the Flatpak for the standalone, I'd like a plugins only download

**Comment by RustoMCSpit** [comment]
also have a clap only, lv2 only, vst 3 only options

**Comment by mkruselj** [comment]
There already is one, tar.gz [here](https://github.com/surge-synthesizer/releases-xt/releases/tag/1.2.3) .

**Comment by RustoMCSpit** [comment]
> There already is one, tar.gz [here](https://github.com/surge-synthesizer/releases-xt/releases/tag/1.2.3) . We won't fragment the downloads any further.

huh? how does that work sorry. also could the release notes clarify this

**Comment by mkruselj** [comment]
You unpack the archive and overwrite old plugins with new ones, at whichever location they are supposed to be on the system.
