### ISSUE TITLE
MSEG hover tooltip Y value doesn't update

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#7267]
X values update contiuosly when you move points around, but Y values stay where they were on mousedown.

**Comment by Andreya-Autumn** [comment]
@mkruselj You see the same behavior?

**Comment by baconpaul** [comment]
I see the exact same

**Comment by baconpaul** [comment]
here's the bug
grab it in the left half of the handle and it updates
grab it in the right half of the handle and it does not
that's because it assumes you are dragging the endpoint
but the right half drag is dragging the start point
so it uses the value from the wrong point

**Comment by mkruselj** [comment]
Additionally: tooltip shows on its own when changing Loop Mode?!

**Comment by Andreya-Autumn** [comment]
I'm getting something more like: All points except the next to last one show the y position of the next point over to the right. The next to last updates correctly.

**Comment by Andreya-Autumn** [comment]
Oh and I can also confirm what Mario said.

**Comment by baconpaul** [comment]
yeah i confused second to last and halfway
