### ISSUE TITLE
Critical: Disable Cursor keys from bleeding to Surge when Patch save dialog is visible

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#727]
as reported by @sense-amr 

let's disable cursor keys from save dialog so that they do not bleed to Surge and change presets. 

You want to be able to go left and right with cursor keys while saving preset name, without losing the preset.

**Comment by esaruoho** [comment]
tabs were disabled by #641 so maybe this is something that can be easily done.

**Comment by esaruoho** [comment]
comment from @baconpaul : 
yeah it’s the exact same diff. Just move it from the tab block up to the entire keyhandling block.
I can get this tonight. Or if you just move that block to above the switch statement rather than after the tab case it wil work

**Comment by sense-amr** [comment]
tested here on Windows 10 .. Vst2 .. 
works fine as expected..
No Arrow interference .. to save ..

**Comment by sense-amr** [comment]
tested here on Windows 10 .. Vst3 ..  Bitwig.. 2.43
works fine as expected..
No Arrow interference .. to save ..
