### ISSUE TITLE
Where is Init Patch 

### ISSUE THREAD

**Issue by ksv1999** [surge-synthesizer/surge#7274]
Hi all, 
I made a patch the default patch of Surge by mistake. 
Now I can't reset to the original Init Saw - I tried to look in finder for the original file but it seems it has been overwritten. 

How can I reset to the original Init patch (reset all default settings?) 
I can't see to find that option anywhere
Thanks

**Comment by baconpaul** [comment]
you can reset to factory by deleting Documents/Surge XT/SurgeXTUserSettings.xml
The init saw patch exists in the "Factory / Templates" setting. Load it and choose "make this default"
If this isn't clear please feel free to reopen.

**Comment by ksv1999** [comment]
Thanks
