### ISSUE TITLE
Option Menu window doesn't resize

### ISSUE THREAD

**Issue by Miscuglio2** [surge-synthesizer/surge#7277]
**Bug Description:**

**Surge XT Version**
This information is found on the About screen, which you get to from the bottom right menu.

* Version:
* Plugin Type: [VST2, VST3, AU]
* Bitness: [32-bit or 64-bit]

**Reproduction Steps:**
2. Click on '...'
3. Scroll down to '...'

**Expected Behavior:**

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following!):**
 - OS: [e.g. Windows 10]
 - Host: [e.g. Bitwig, Logic, Cubase, Reaper]
 - Version: [e.g. 2.4]

**Additional Information:**

**Comment by Miscuglio2** [comment]
I am using a Netherblade controller with Surge installed on its internal Windows engine.  The options menu doesn't resize hence it gets cutoff without the abliity to scroll.

**Comment by baconpaul** [comment]
You mean the options menu in the standalone which lets you pick audio inputs? Or some internal menu in surge?

**Comment by Miscuglio2** [comment]
Yes indeed the options menu in the stand alone version. 


Sent from the all new AOL app for iOS


On Saturday, October 28, 2023, 11:53 AM, Paul ***@***.***> wrote:




You mean the options menu in the standalone which lets you pick audio inputs? Or some internal menu in surge?
