### ISSUE TITLE
Is Surge FX portable on windows ?

### ISSUE THREAD

**Issue by geoslake** [surge-synthesizer/surge#7278]
Hi

I know how to make Surge synth portable, but it seems Surge FX doesnt use the same folders (surgextdata & surgeuserdata), which makes sense of course. So, at least for the clap version, it recreates its own "surge xt" folder in $documents.
Is there a way to make it portable as well ?

Thanks a million !!

**Comment by geoslake** [comment]
Hi Paul, thanks for replying and for your amazing work on Surge !!!
I guess Surge FX doesn't require have any VC++ dependencies on Windows either (?)
Cos i remember you added the required dll to Surge Synth directly (its called static linking i think ?), not sure about FX but as im on a clean Windows 10 with nothing installed....

**Comment by baconpaul** [comment]
that's right; all our MSVC compiled tools statically link the runtime. 
surge fx needs nothing other than the vst3 file. just it uses a codepath which makes a documents directory regardless. we can fix that just requires a code change.

**Comment by geoslake** [comment]
Ok, thank you very much Paul, and looking forward to the "fixes". Cheers

**Comment by baconpaul** [comment]
OK this fix will be in a nightly later today and in the 1.3 release this year.

**Comment by geoslake** [comment]
thanks Paul !!
