### ISSUE TITLE
If someone else becomes an mts source, cede and be a client 

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#7291]
Mts has a clear api to slam everyone out of being a source and becoming a source. Surge can use this!

If someone else uses it while surge is a source, you should detect that, cede, and become a client

**Comment by baconpaul** [comment]
OK so here's the problem making this impossible.

Workflow is:

1. Have no MTS master. MTS_CanRegisterMaster = true
2. Register surge as a master. MTS_CanRegisterMaster flips to false
3. Then start odd sound MTS-ESP Master and it shows the reset screen.
4. Press the reset and MTS-ESP is the master but
5. Surge still show MTS_CanRegisterMaster as false
6. And no other API changes state

so there's nothing in the libMTSMaster api which lets you know someone else has kerchunked you. So no code I can write for 1.3. Let me leave this open in case we find an API but knocking out to currently unscheduled.

**Comment by Andreya-Autumn** [comment]
"Doctor, it hurts when I haphazardly kerchunk MTS-ESP sources."

**Comment by baconpaul** [comment]
yeah the primary issue is surge still thinks it is the master. so the UI looks wrong etc.

**Comment by Andreya-Autumn** [comment]
Indeed. And Marcus' source will do the same. Doesn't seem like an unfair request to make of the user to try to avoid bonking sources against each other though, I would say.

**Comment by baconpaul** [comment]
Yeah I agree.
It would have been nice to be able to know it and adjust, which was really the point of this issue, but looks like theres no MTS api for that. So I guess I'll close this!
