### ISSUE TITLE
I'm trying to build locally to fix the windows install location picker in the wizard, but Surge XT.clap not found...

### ISSUE THREAD

**Issue by instancer-kirik** [surge-synthesizer/surge#7292]
**Bug Description:**
Parsing [Files] section, line 98... Surge XT.clap not found. no results in file search repo, idk :/ 
"D:\Work\Coding\surge\scripts\installer_win\..\..\build\Release\surge_xt_products\Surge XT.clap" does not exist.
when trying to build from Inno Setup
either fix this and I'll send pull request, or add install location picker, here's probably how:
function GetInstallPath(Param: String): String;
begin
  Result := ExpandConstant('{app}');
end;

**Surge XT Version**
I haven't installed it yet.. this is about building the installer 11/6/2023
* Version:
* Plugin Type: [VST2, VST3, AU]
* Bitness: 64-bit

**Reproduction Steps:**
1. Go to 'Inno Setup'
2. Uncomment the 2 lines
3. Click on 'Build->Compile'
4. Scroll down to 'Compile Aborted'
5. See error

**Expected Behavior:**
Build into installer, check if code works

**Computer Information (please complete the following!):**
 - OS: [e.g. Windows 11]
 - Host: [Inno Setup, Couldn't get VSCode to compile either, no log]
 - Version: ["" or 0.0.0]

**Additional Information:**
maybe it's a path thing? but I don't have access to Surge XT.clap
maybe it's just not hosted on github??

**Comment by baconpaul** [comment]
Did you use the cmake build to run inno? Or at least before you ran inno to make the assets?

also have you consulted < https://github.com/surge-synthesizer/surge/issues/4818> on install path windows issues?

thanks!

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/issues/4818 Correct link sorry

**Comment by mkruselj** [comment]
Indeed, you first have to build Surge locally before you can run Inno script to build the installer. Not a bug.
