### ISSUE TITLE
OSC doesn't automatically start up in DAW

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#7293]
The problem being that `tryOSCStartup()` is currently called from `prepareToPlay`, but it requires data from `DAWExtraState`, however we only get this data when `setStateInformation()` is called, which happens _after_ `prepareToPlay`.

Atomics, etc. @baconpaul.

**Comment by baconpaul** [comment]
@mkruselj I think (think) the right approach is https://github.com/baconpaul/surge/tree/maybe-this-7293 but I am not sure how to test. Can you give that a whirl and let me know?

**Comment by mkruselj** [comment]
@baconpaul Unfortunately that doesn't seem to have done it.

How to test? Open this Reaper project:

[osctest.zip](https://github.com/surge-synthesizer/surge/files/13334788/osctest.zip)

It has two Surge instances (note, they are both opened side by side on a dual monitor setup, you may not see the second one). DAWExtraState already has the right flags for is OSC started and OSC ports stored (which you can query if you breakpoint at a convenient point). It's just that OSC connections aren't starting upon project load/plugin init/unstream from plugin chunk. You would see the OSC Settings menu entry say "stop connections" instead of "start connections" if connections were active.

**Comment by baconpaul** [comment]
OK my branch works exactly like that with your test case *if* you have audio running and tracks unmuted.

But if you don't, no luck.

That is, luckily, easy to fix. Push coming soon.
