### ISSUE TITLE
Bonsai Preset Levels

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#7295]
```
In other news: @morgan and others - I got a report from a rack alpha tester that bonsai results in massive level cuts in some situations and I can confirm it. Just latch a modern and drop in a bonsai and you get like a 20db drop in signal right away. the input gain also doesn't seem to help. I'm curious if there's something amiss in the circuit or if the test case is an odd one. I get really big signal cuts with latches across the spectrum though across most of the presets.
EvilDragon — Today at 6:00 PM
could it be a wrongly initialized member?
morgan — Today at 6:03 PM
huh
only thing that comes to mind is the input level was very much not set correctly and i always turn it down all the way on the input
but i've been off doing other things (working on opengl burnt me out and i haven't done any audio dev in months) so i have no clue what might be the cause in the code
baconpaul — Today at 6:05 PM
no the vst does the same thing as the rack module
EvilDragon — Today at 6:05 PM
maybe the input gain range needs to be recalibrated then?
morgan — Today at 6:05 PM
yeah it should
baconpaul — Today at 6:05 PM
right.
so i kinda think we need to fix it to ship though right?
like play a c chord, turn it on, you get a big drop?
or do others not see that?
EvilDragon — Today at 6:06 PM
yeah obv it's a blocker
morgan — Today at 6:06 PM
if it's suuuper clipped it'll be quiter
baconpaul — Today at 6:06 PM
(it sounds good if you crank the output level)
morgan — Today at 6:06 PM
i turn the input down 24 and output up 24
baconpaul — Today at 6:07 PM
you mean in code or on the UI?
morgan — Today at 6:07 PM
ui
baconpaul — Today at 6:07 PM
right so it sounds like a gain callibration then?
morgan — Today at 6:07 PM
i think there;s already a gain in and out scale, so changing those would fix that
baconpaul — Today at 6:07 PM
ok i'll open an issue
```

**Comment by baconpaul** [comment]
OK PR above adjusts this; after its merge we will just need to re-level the presets.

**Comment by fractalgee** [comment]
Much better! Will bash it some more later and see if I find anything else (except the presets which are still to be re-leveled).

**Comment by baconpaul** [comment]
Wonderful! Thanks for flagging it to us!

It is a super interesting effect when you set it right just the parameter space is a bit tricky indeed as you noticed. Any other thoughts please do share them here!

**Comment by fractalgee** [comment]
OK, some more on Bonsai InputGain staging, something is still weird:

This is Bonsai at default setting:

<img width="487" alt="Bonsai_Default" src="https://github.com/surge-synthesizer/surge/assets/12473856/91f5adbc-3393-4c0d-9333-41835f06c707">

Now turning Input gain up to full clockwise actually makes it go quieter instead of louder:

<img width="487" alt="Bonsai_InputGainFullClockwise" src="https://github.com/surge-synthesizer/surge/assets/12473856/559bc096-e220-45d2-a1ac-1913193994bc">

**Comment by baconpaul** [comment]
that's not unexpected. what's happening is you are super-clipping the input and the distortion is replacing the signal with loads of high frequency stuff which doesn't survive the downstream filters. 

Leveling the effect is tricky - like i said the parameter space is big and odd - and we just sort of decided to have the presets meet the constant level. You can easily drive it well outside of the comfy regime though. Including silencing it by radically overdriving it. (This was essentially the problem you had yesterday; our fix was to turn down the input gain by 20 and turn up the output gain by 24db, respectively)

**Comment by fractalgee** [comment]
ah, OK, understood. Thanks for the explanation.

**Comment by mkruselj** [comment]
We're basically done here with last commits that @Andreya-Autumn did.
