### ISSUE TITLE
Surge XT Patch Version Mismatch

### ISSUE THREAD

**Issue by SimonCHHo** [surge-synthesizer/surge#7297]
I have continuously got this prompt when using Surge XT :

 " Surge XT version you are running (1.2.3.bb8dd2b) is older than the version which created this patch. Patch version mismatch is: 22 (patch) vs 21 (current).Certain features of the patch will not be available in your session". 

Although I had completely uninstalled the synth & installed the latest version twice, this problem still persist, just do not know hoe to fix this. Would appreciate it for any advices.

**Comment by mkruselj** [comment]
This was fixed sometime during 1.3 nightlies IIRC. Don't worry about it. You can either install a current nightly version, or wait for 1.3 release which should happen within a month or so.

**Comment by SimonCHHo** [comment]
Thank you for your prompt reply. Have a nice day!
