### ISSUE TITLE
feature request: method for drawing ramps into stepsequencer

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#730]
would be neat to be able to press buttons in the UI that would generate ramps such as these into the stepsequencer, for instance.

<img width="520" alt="vember_audio__surge" src="https://user-images.githubusercontent.com/4966687/53814655-ad690380-3f68-11e9-8c53-f29abdf9ef0a.png">

**Comment by sense-amr** [comment]
@esaruoho you saw this from the manual right ? 
Holding down shift while drawing will quantize the values to 1/12th steps, hence if the LFO is used to modulate pitch by an octave, each step will represent a semitone.

**Comment by sense-amr** [comment]
i definitely advocate .. User presets load and save for Step seq envs. Also Rnd .. 
copy and paste.. too

**Comment by baconpaul** [comment]
Yeah that’s all useful; lemme bump it into the 1.6.n group

**Comment by mkruselj** [comment]
This is how Kontakt does it: right mouse drag gives you a line overlay and when you release it you get your linear ramp!

![Kontakt table linear ramp](https://user-images.githubusercontent.com/2393720/83451262-e9826100-a456-11ea-9fe8-7d65f105bb57.gif)

**Comment by baconpaul** [comment]
that's exactly what we want yeah.

**Comment by K0rrid0r** [comment]
I wanted that feature for years, Would be very useful!

**Comment by baconpaul** [comment]
![stepline](https://user-images.githubusercontent.com/13387561/83472808-15511700-a456-11ea-88e3-352a96c9c83d.gif)

merging now. This is what happens when you RMB-drag across the step sequencer.

**Comment by mkruselj** [comment]
Just a quick reopen to update the spec of the suggested behavior: 

- [ ] ramp should only be applied on RMB mouse up
- [ ] if while dragging the ramp we return the endpoint back to the starting step, ramp shouldn't be drawn at all and table should not be updated

**Comment by VincyZed** [comment]
Really cool! However, on my system, steps don't update in real-time (like that GIF you sent above), only when releasing right mouse drag.
