### ISSUE TITLE
Independent pan control

### ISSUE THREAD

**Issue by STOP63** [surge-synthesizer/surge#7307]
I didn't find any requests about independent pan control for each oscillator. Is it in the plan for the future?

**Comment by Andreya-Autumn** [comment]
Hello! This has been a very common request. It was one of the first things I found myself wishing for in Surge. It is planned, see #3257. This won't happen until Surge XT2 though. Closing as duplicate, but feel free to comment if you have anything to add.

**Comment by baconpaul** [comment]
Also #304

one of the earliest things I wanted was modulatable pan per osc. Funny how I never added it

**Comment by STOP63** [comment]
«modulatable pan per osc»
I use it on other plugins like Vital; it's difficult to explain, but it creates some kind of three-dimensional effect.

PS 
Thank you, beaconpaul, for all your work on the marvelous Surge plugin.

**Comment by baconpaul** [comment]
Yeah I use it all the time in rack also. 

And it’s a team effort but thank you for your appreciation!

**Comment by Andreya-Autumn** [comment]
I really love the sadly unfinished Crust synth by Eugene Yakshin. It has a hardwired random modulator on the pan of each osc. So yeah that sound has a special place in my heart also. We'll get there eventually (god willing). ;)

**Comment by STOP63** [comment]
Yesterday, I found a site to download Crust. What a quirky but good-sounding plugin, love it!  Thank you!

Right now, I'm trying to wrap my head around another plugin from Eugene called Ribs.
