### ISSUE TITLE
Formula editor window doesn't update on patch/preset load

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#7308]
If you have the Formula editor open and do one of:

Load a formula preset
Switch to a different patch (which has a formula LFO in the same slot)
Undo/Redo the "Apply" formula action

...the editor won't update. Close it and re-open and you'll see that the actual formula does update correctly in each case. Just the UI doesn't. MSEG and Tuning Editor overlays do not have this problem.

**Comment by mkruselj** [comment]
> Switch to a different patch (which has a formula LFO in the same slot)

This one I cannot confirm over here, tried it with Formula tutorial patches.

I have a fix for refreshing after loading an LFO preset, at least. The undo/redo case seems a bit trickier.

**Comment by Andreya-Autumn** [comment]
Yeah I was probably imagining things earlier. I don't see the patch one either.

**Comment by mkruselj** [comment]
Aaaaaaaand I found a fix for the undo/redo case. PR soon!
