### ISSUE TITLE
FX bypass via OSC 

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#7309]
Bypass FX would be a useful thing to add. 
This would need an additional boolean address per FX slot.

It would also be useful to be able to clear an FX slot. 
My first thought was that sending /param/fx/*/1/type = 0 should clear it. This address has type "contextual" in the spec (and I've misplaced my Touchosc somehow lol) so I don't know, perhaps it already does this already? If so, let's just clarify that in the spec, and otherwise let's perhaps make it so?

**Comment by baconpaul** [comment]
the clear action internally is same as set to 'fxt_off' which is 0, yeah

**Comment by mkruselj** [comment]
So yes then we just need the bypass action in the spec.

**Comment by pkstone** [comment]
> the clear action internally is same as set to 'fxt_off' which is 0, yeah

I've confirmed that the OSC message '/param/fx/a/3/type 0' does indeed clear the associated effect slot.
