### ISSUE TITLE
Warn user if loading another patch causes loss of current preset modifications

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#733]
some magic way of warning the user if their modified preset / wonderful new sound is gonna be lost if they change the preset or category. dialog window-stylee

**Comment by baconpaul** [comment]
So just a note on this. Playing with a commercial synth today I noticed when I loaded a factory patch and modified it it changed the name from “Some Lead Thing” to “Some Lead Thing *” and I liked that very much - I knew I had to save.

When we do this user warn thing (which may be a bit tricky) I like the idea of doing that * also.

It may not be that that tricky; all the UI to patch changes go through one point in the code path. It may be easy to do a conservative one (conservative as in “it over-flags a patch as changed”).

We also need to think: If I modulate a parameter from my DAW should it could as changing the patch? The slider moves so it is sorta different...

**Comment by itsmedavep** [comment]
Interestingly, testing automating a parameter with Serum and Kontakt when I change things on a patch the GUI doesnt update at all. Nothing is marked dirty. 

Its only at the point of removal of the synth or in Kontakt's case changing the instrument or removing the Kontakt instance that the user is prompted to save (at least in Logic). 

My expectation was to have both behaviors TBH. I would have expected the patch to get marked dirty in some way. Then if removing a synth instance or navigating away from a dirty patch that was unsaved I would be prompted about loosing information.

**Comment by mkruselj** [comment]
Yes doing the * thing is a sensible thing to do. No popup dialogs, please.

> Interestingly, testing automating a parameter with Serum and Kontakt when I change things on a patch the GUI doesnt update at all. Nothing is marked dirty.

Kontakt is a bit of a special case because one instance of Kontakt can contain a WHOLE LOT of data in the plugin chunk (all the NKIs loaded, can add up to megabytes!), so marking dirty states on host automation doesn't seem like a good thing to do in that case.

**Comment by mkruselj** [comment]
So just pondering:

We add an `isDirty` bool. You load a patch - clean that flag. Then on any parameter change (regardless of parameter) flip the value of `isDirty`.

Additionally we could add a `prev_value` member that is set when we change the parameter value, and we check if the next param value is different from previous one before flipping `isDirty`. This could prevent overflagging the case where host automation spams the synth with the exact same value with transport stopped.

**Comment by baconpaul** [comment]
Yes that’s exactly how to do it. And modulation. And formula. And steps. And mseg contents. From the ui or from automation paths.

**Comment by baconpaul** [comment]
The orev value can’t cover all those so we shouldn’t do it with this

**Comment by baconpaul** [comment]
So I started this in `baconpaul/dirty-flag`. 
Not everything dirties yet (especially the modulators with compound data) but lots of stuff does
I'm not sure if it is useful or annoying
and would like a second opinion before i do a lot more work

If you have time to do a build and give me feedback @mkruselj would appreciate it.

**Comment by mkruselj** [comment]
@baconpaul This is basically perfect. The only thing we could do is then, when a patch is dirty, upon attempting to load another patch we pop up a dialog asking the user if they really want to do this, plus checkbox not to ask this again.

**Comment by baconpaul** [comment]
OK so with the PR above we have a working dirty flag. Here's what we need to do still

1. Menu Item : Reload Patch from Disc  / active if dirty and if you are in lib
2. Popup to block patch change if you are modified with turn off

Then close this

**Comment by mkruselj** [comment]
After shaking things out a bit, these are not marking the patch as dirty:

* Changing any Tuning Editor parameters
* Toggling Tune or MPE
* Changing deform, absolute, extend range, tempo sync, probably safe to say any and all context menu toggle options too
* Double-clicking on waveshaper or filter icons to bypass them
* Right-click bypassing FX in the FX grid
* Mousewheel over filter subtypes
* Adjusting snap to grid and movement mode in MSEG editor

**Comment by mkruselj** [comment]
- [ ] Mute/unmute, clear, mute/unmute all, clear all actions when right-clicking the modbuttons

**Comment by mkruselj** [comment]
@baconpaul I think we're basically good on this one, so I'm gonna close it for now. Can always reopen if we find any further actions that don't pop up the dirty flag.

**Comment by baconpaul** [comment]
Oh I thought we wanted a dialog to pop up if you move off of a dirty patch didn’t we? And I was too lazy to write it. Lol.

**Comment by mkruselj** [comment]
Oh, right, I will do that today then 🙂
