### ISSUE TITLE
Formula Undo is borked

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#7336]
Load formula.
Change something and apply.
Undo with the editor open. 

You get the previous formula back, working correctly. But the editor window has two copies of the code in it, with the second one not applied. Close the editor and reopen and you're fine, but press apply before that and you get an error obviously.

Likely related to #7310

**Comment by baconpaul** [comment]
Am on phone otherwise would do obvs. Good catch
