### ISSUE TITLE
Warning when formula is not applied should also trigger on Close button, not just Esc

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#7337]
Looking at the code for the previous issue this caught my eye: 

https://github.com/mkruselj/surge/blob/76966ebf18405326a914ee3d9b1da302b9260c36/src/surge-xt/gui/overlays/LuaEditors.cpp#L864

I had not seen that dialog ever, since I click the x to close. Would be friendly to pop that window in this case also.

**Comment by Andreya-Autumn** [comment]
Oh hahaha. I also realized now that it's not working correctly. 🙃 Pressing yes, the window stays open.

**Comment by baconpaul** [comment]
Oh we should fix this for 1.3. On it.

**Comment by baconpaul** [comment]
Oh no it's harder to fix. Rebumping

**Comment by baconpaul** [comment]
Above PR fixes the esc key shenanigans at least which were a result of the alert box ports in 1.3

**Comment by Andreya-Autumn** [comment]
Oh haha sorry, I misread you and un-re-bumped it. 😆 Let me re-un-re-bump.

**Comment by mkruselj** [comment]
Wahey!
