### ISSUE TITLE
Make the prev/next patch buttons controllable through MIDI

### ISSUE THREAD

**Issue by jjYBdx4IL** [surge-synthesizer/surge#7343]
Would be great if I could go through all patches via my MIDI foot controller and not having to use a mouse, point and click every time.

**Comment by mkruselj** [comment]
In Surge 1.3 you will be able to use the MIDI Programs folder to navigate patches with MIDI Bank Select and Program Change messages. We will not be making the prev/next buttons MIDI learnable, sorry.
