### ISSUE TITLE
Plugin crashes on wave wavetable selection

### ISSUE THREAD

**Issue by baermathias** [surge-synthesizer/surge#7347]
**Bug Description:**
The plugin crashes if you select wavetable and then click left or right as in the screenshot below:
![Screenshot from 2023-11-29 22-25-33](https://github.com/surge-synthesizer/surge/assets/45003352/250d603f-c3ea-442b-94fd-43021d006941)

Crashed:
![Screenshot from 2023-11-29 22-25-54](https://github.com/surge-synthesizer/surge/assets/45003352/949fc3f1-2995-42e1-8a0b-9b0a54902d43)

**Surge XT Version**
* Version: Surge XT 1.2.3.bb8dd2b
Build: 2023-05-05 @ 14:59:40 on 'fv-az493-544.npju1gewetwu1gntkjzzphrm3e.parx.internal.cloudapp.net/pipeline' with 'GNU-9.4.0' using JUCE 6.1.6
System: Linux 64-bit VST3 on  Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Host: Bitwig Studio @ 48.0 kHz / Process block size: 32 samples

* Plugin Type: [VST3, CLAP]
* Bitness: [64-bit]

**Reproduction Steps:**
See the screen shots above.

**Expected Behavior:**
No crash

**Computer Information (please complete the following!):**
 - OS: Ubuntu 22.04.3 
 - Host: Bitwig
 - Version: 1.2.3

**Comment by baconpaul** [comment]
Hi

A few questions

1. If you click on the wavetable name, do you get a menu where you can select wavetables? So is it just the jog button?
2. Are you running in bitwig flatpak? And if so are you running surge-xt flatpak or standard install

My theory is

(1) you don't have any resources / can't find factory wavetables and
(2) the jog button freaks out then (which we should fix)

If you look at the paths in the about screen you will see where your data is.

But - good news! (And great timing). I've just confirmed that if I run surge at head locally with no wavetables the jog buttons do indeed crash. So I can fix that.

So the changes are

(1) I'll fix up surge to avoid this bug. Great timing - we are just wrapping up 1.3. But
(2) you should fix your install so the factory wavetables are present!

**Comment by baconpaul** [comment]
OK the PR above fixes #1 and when I merge it it will auto close this issue. If you need help getting your install working with resources, please feel free to comment here or hop into our discord where we can help.

You really want that wavetable content. Without it the wavetable oscillator is uninteresting! But it shouldn't have crashed of course and I really appreciate the great report.
