### ISSUE TITLE
Metadata Mismatch on patch selection

### ISSUE THREAD

**Issue by pkstone** [surge-synthesizer/surge#7349]
**Bug Description:**

messages in console:
Metadata Mismatch (Can Extend): param[3]='Crossfeed'; paramValue=0 expected=1
Metadata Mismatch (Can Extend): param[7]='Depth'; paramValue=0 expected=1

**Surge XT Version**
Version: Surge XT 1.3.osc_work.1fa1a993
Build: 2023-11-29 @ 12:52:36 on 'MacBook-Pro.local/local' with 'AppleClang-15.0.0.15000040' using JUCE 7.0.5
System: macOS 64-bit Standalone on Apple M2 Pro
Sample Rate: 48.0 kHz / Process block size: 32 samples

* Version: Standalone

**Reproduction Steps:**
1. Select patch "Grand Piano 2022" (John Valentine)
2. Errors appear in console.

**Computer Information (please complete the following!):**
 - OS: [Mac]
 - Host: [standalone]

**Comment by baconpaul** [comment]
I’ll fix this
