### ISSUE TITLE
Formula retriggering EGs don't obey "from current"

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#7360]
...and it'd be nice if it could I guess. Not sure how hard. Put in 1.3 if easy/safe, otherwise it can wait.

**Comment by baconpaul** [comment]
Do MSEG and STEP retrievers obey this?

**Comment by Andreya-Autumn** [comment]
I don't know but I would not be surprised if they don't. I've never used this trick from the MSEG and rarely use the step sequencer... Lemme try it and see.

**Comment by Andreya-Autumn** [comment]
Indeed they do not.

**Comment by baconpaul** [comment]
Yup OK fixed it!

**Comment by baconpaul** [comment]
OK got a fix to this one queued up.
