### ISSUE TITLE
Filter analysis window: Filter 1 button appears hovered

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#7361]
After opening the filter analysis window, the Filter 1 button appears hovered, until you actually hover over it.
![image](https://github.com/surge-synthesizer/surge/assets/50145178/6d7970aa-6464-43fc-8240-305e15615eca)

**Comment by baconpaul** [comment]
The ur-problem here is we don't have non-accessible overlays so the focus grab happens for no reason.

**Comment by baconpaul** [comment]
turns out i had solved this already for the scope. so now it is fixed here too.
