### ISSUE TITLE
Generate stub files for Python bindings

### ISSUE THREAD

**Issue by KingaJanicka** [surge-synthesizer/surge#7362]
**Is your feature request related to a problem? Please describe!**
The python build process does not generate stub files, meaning developers using VS Code don't get autocomplete or inline documentation.

**Describe the solution you'd like:**
Running `pybind11-stubgen surgepy` and moving the contents of stubs/surgepy to inside the site-packages surgepy directory results in quite nice inline documentation. This should be added to build process, PR forthcoming.
![image](https://github.com/surge-synthesizer/surge/assets/50145113/1da20244-c834-419d-b938-59ff76e278ce)

**Describe alternatives you've considered:**
Tried to generate using mypy stubgen but it didn't work.

**Comment by baconpaul** [comment]
Oh cool! Please add yourself to AUTHORS when you pr since this will be your first pr.
