### ISSUE TITLE
Tuning editor: Clicking on the vertical keyboard on the left of the UI should play the corresponding notes

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#7365]
Not a big deal, but I would expect to be able to click on a note on the vertical keyboard in the tuning editor to hear it.
![image](https://github.com/surge-synthesizer/surge/assets/50145178/cc081922-c7b4-4c46-b0e2-8707305e5680)

Tagging this for 1.3.1 for now.

**Comment by baconpaul** [comment]
that ui has been there for nearly 3 years and i never once thought of that. LOL.

Good idea!

**Comment by baconpaul** [comment]
Oh this one is a bit annoying. I have to figure out how to push from inside the tuning editor to the juce processor midi from gui lock free queue. editor->juceEditor->getProcessor recast etc....

**Comment by baconpaul** [comment]
ok bit more work than i originally thought but have it put together!
