### ISSUE TITLE
How do I interact with wavetable programmatically?

### ISSUE THREAD

**Issue by turian** [surge-synthesizer/surge#7375]
**Is your feature request related to a problem? Please describe!**

I'm experimenting with creating new synths programmatically, that involve inserting custom wavetables. However, it is not clear how to do this in Surge.

**Describe the solution you'd like:**
1) Ideally, there would be an XML format that captures the complete state of the synthesizer, nothing missing (https://github.com/surge-synthesizer/surge/issues/6627)
The test suite for this could have scripts to roundtrip from FXP to XML and back, to make sure they are identical. I would be happy to contribute.
2) The Python API could be extended. If it is incomplete, an XML solution would be preferable.

**Describe alternatives you've considered:**
IDK.

**Additional context:**
I've made a lot of progress in getting AI to program synths, which I'll be sharing with the community soon, but wavetables is a missing link.

**Comment by turian** [comment]
@mkruselj writes "if you check the scripts/patch-tool folder you will see how you can read FXP", so I'll close for now

**Comment by baconpaul** [comment]
And scripts wt-tool has full wavetable round trips

The fxp  is an envelope some xml for everything except the wavetable binary, and the wavetables.
