### ISSUE TITLE
CLAP and Reaper text input issue.

### ISSUE THREAD

**Issue by JoeMegalos** [surge-synthesizer/surge#7382]
**Bug Description:**
When using the CLAPi in Reaper and renaming a preset the space bar is captured and toggles playback instead of being used for naming. Normally handled by enabling a Reaper option "pass all keyboard input to plugin" but that is greyed out with the CLAPi version. This doesn't happen with the VST3i version or a CLAPi I tried from Full Bucket which implies this is specific to the CLAPi of Surge.

Oddly, I've found that I *can* enable the Reaper keyboard input option when I first load the CLAPi but haven't tried to edit anything. If I don't enable it and try to rename the preset it captures the space key as I described and the input option is greyed out in the FX container menu.

**Surge XT Version**
1.3.0

* Version:
* Plugin Type: CLAPi
* Bitness: 64

**Computer Information (please complete the following!):**
 - OS: Windows 10
 - Host: Reaper
 - Version: 7.06

I hope that's enough to go on. Let me know if you need more info or if it's something better brought up with the Reaper folks. Thanks.

**Comment by mkruselj** [comment]
This is just how it is with CLAP in REAPER,  AFAIK. Not much we can do here.
