### ISSUE TITLE
VST3 patch browser glitchy in Ableton + Wine

### ISSUE THREAD

**Issue by pgcd** [surge-synthesizer/surge#7383]
**Bug Description:**
In version 1.2.3 hovering on a category in the patch browser seems to randomly render the patches below the window, making it impossible to select a patch; occasionally, the submenu opens at the right level and displays items but clicking on the individual item still results in no selection. Patches can be selected by clicking on the arrows next to `category` and `patch`, and the rest of the UI seems to work normally (highlights where expected, controls behaving as expected).

In version 1.3.0, the GUI is frozen: patches can still be selected throught the `category` and `patch` arrows but there is no feedback of any kind (neither in the name nor in any of the controls) until the plugin window is closed and reopened.

**Surge XT Version**
* Version: 1.2.3, 1.3.0
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Add plugin to track
2. Open plugin window
3. Attempt to select a patch with the browser, or edit a patch parameter/control

**Expected Behavior:**
Active and properly updated GUI

**Screenshots:**

[surge1.2-patch-browser-glitches.webm](https://github.com/surge-synthesizer/surge/assets/2361956/6368c3cf-f34b-4bfe-8cd9-ae5e3aa5589f)
[surge1.3-GUI-not-updating.webm](https://github.com/surge-synthesizer/surge/assets/2361956/3154de52-83d3-4880-b34b-be57e80d5711)

**Computer Information (please complete the following!):**
 - OS: Linux Mint 21.2 (Cinnamon), wine-9.0-rc1 (Staging)
 - Host: Ableton Live (Win10 compatibility)
 - Version: 11.3.13

**Additional Information:**

**Comment by mkruselj** [comment]
Sorry to say, but we don't really support WINE. This is likely some incompatibility between JUCE popup window widget and how WINE behaves differently in some regard compared to actual Windows. At any rate I don't think we can look into this with any sort of rigor.

**Comment by pgcd** [comment]
Yes, I understand - I'll try to see if I can find something with JUCE, thanks!

**Comment by tank-trax** [comment]
@pgcd 

If I may offer a suggestion. You can try [creating](https://linuxconfig.org/using-wine-prefixes) a new WINE PREFIX for testing... and clean install Ableton and Surge XT to that PREFIX to see if the issue is reproduced.

As well, can you tell us, which version of WINE and WINEASIO are you using?

**Comment by tank-trax** [comment]
You can try and change the renderer for WINE using WINETRICKS. Try flipping between GDI and GL. 

Once you've selected your prefix, select change settings then OK and scroll down to this section:

![image](https://github.com/surge-synthesizer/surge/assets/41337033/55d86af4-7dcb-4b7c-8616-3d9257a5d2b8)

I am using GL and can navigate to all submenus, however they float and detach a bit.

**Comment by pgcd** [comment]
I have tried with all the available renderers (gid, gl, no3d and vulkan) without apparent change - that is, the menus are displayed but clicking on them doesn't cause the rest of the GUI to update, and the hover effects don't work either, regardless of renderer. Perhaps worth looking at the other rendering-related settings?

**Comment by tank-trax** [comment]
at this point am out of ideas..... other than switching to Bitwig :-)

**Comment by pgcd** [comment]
Yeah, I was looking into that - unfortunately it's not cheap (I haven't checked again but the base version didn't have all the instruments I'd need to import my tracks from Ableton) so it's on hold for now.
Thank you for the assistance, and for the great synth (I'll stick with 1.2, it's plenty good enough!)

**Comment by tank-trax** [comment]
I have to apologize. I hadn't tested it further. I get the same result but it's worse on my end in Reaper or as a Standalone. I am using wine-staging 8.2 with an apt-mark hold. Not sure if the latest version is better as I am hesitant to upgrade due to issues with wineasio. I also tried all renderers and had the same result. This does not look like an easily resolvable issue, likely something to be investigated by the Wine development team. Perhaps try a bug report there?

> Thank you for the assistance, and for the great synth (I'll stick with 1.2, it's plenty good enough!)

Thanks for your understanding.
