### ISSUE TITLE
Hi Surge

### ISSUE THREAD

**Issue by Dionisio765** [surge-synthesizer/surge#7384]
**Bug Description:**

**Surge XT Version**
This information is found on the About screen, which you get to from the bottom right menu.

* Version:
* Plugin Type: [VST2, VST3, AU]
* Bitness: [32-bit or 64-bit]

**Reproduction Steps:**
2. Click on '...'
3. Scroll down to '...'

**Expected Behavior:**

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following!):**
 - OS: [e.g. Windows 10]
 - Host: [e.g. Bitwig, Logic, Cubase, Reaper]
 - Version: [e.g. 2.4]

**Additional Information:**

**Comment by baconpaul** [comment]
Hi!

Did you mean to share anything in this issue? If not we can close it. Thanks!

**Comment by Dionisio765** [comment]
Hi Surge

After installing SurgeXT 1.3.0
I cannot open VCV Pro in Reason 12 Windows 10 64

After uninstall Surge VCV  opens normally

Thanks

**Comment by baconpaul** [comment]
Oh I wonder if yu are aging thst odd bug a few nightly users had.
Can you attach the rack log? Or alternately try installing the 2.2.1 surge xt release here https://github.com/surge-synthesizer/surge-rack/releases/tag/v2.2.1.0 which will be in the library in a day or two

a very small number of users saw a crash with surge rack 2.1 and our nightly which we fixed but I didn’t think about the install order

**Comment by Dionisio765** [comment]
Same problem on Reaper 7.06 and Bitwig 5.04
They recognize VCV Pro as a plugin but don´t open it

Thanks Paul

I will install and try again

**Comment by baconpaul** [comment]
The solution is probably downgrade to vst 123 or upgrade to xt 22 or remove surge from your VCV

**Comment by baconpaul** [comment]
But if yu include your rack log here it will help

**Comment by Dionisio765** [comment]
Problem solved
Now VCV opens normaly in Reason 12

Thanks Paul for your time and patience

All the best

Dionisio

**Comment by baconpaul** [comment]
Great. I posted a warning in community rack forum also
