### ISSUE TITLE
Download v1.3 Win x64 exe - does not work

### ISSUE THREAD

**Issue by planist79** [surge-synthesizer/surge#7385]
Hi, changelog looks great!
But the download v1.3 Win x64 exe - does not seem to work. It won't download an exe file but something like this

f1252fdc-74d7-42ac-8d65-8690e556c902

**Comment by baconpaul** [comment]
did you download this file? https://github.com/surge-synthesizer/releases-xt/releases/download/1.3.0/surge-xt-win64-1.3.0-setup.exe

**Comment by mthierman** [comment]
Did you try the download button at [https://surge-synthesizer.github.io/](https://surge-synthesizer.github.io/) or somewhere else? I can't find a broken link there or on our GitHub releases

**Comment by mkruselj** [comment]
@planist79 Any feedback on the above, please?

**Comment by planist79** [comment]
@mkruselj @baconpaul @mthierman 
sorry for the late reply..i was sick the last few days.. Download of x64 exe file is OK now. I don#t know what happened the last time..

**Comment by baconpaul** [comment]
Thanks!
