### ISSUE TITLE
Surge XT 1.3.0 not found by any host

### ISSUE THREAD

**Issue by codecollider** [surge-synthesizer/surge#7397]
**Bug Description:**
I had some trouble first installing the deb package in MX-21.3_x64 Wildflower as dpkg is yet not using zst compression. I repacked the deb with 

```
ar x nameofdebfile.deb
zstd -d < control.tar.zst | xz > control.tar.xz
zstd -d < data.tar.zst | xz > data.tar.xz
ar r surgenewdeb.deb debian-binary control.tar.xz data.tar.xz
```
Installation worked and the the files are under /lib/.vst3. 

However, Reaper and Bitwig do not find the vst3 plugin. Renoise lists it, but initialization fails. Clap version also doesn't work. 

**Surge XT Version**
1.3.0

* Version:
* Plugin Type: [VST3, CLAP]
* Bitness: [64-bit]

**Reproduction Steps:**
see above

**Expected Behavior:**

**Screenshots:**

**Computer Information (please complete the following!):**
System:    Host: fox Kernel: 5.10.0-26-amd64 x86_64 bits: 64 Desktop: Xfce 4.18.1 
           Distro: MX-21.3_x64 Wildflower September 18  2022 
Machine:   Type: Desktop Mobo: MSI model: H81M-E34 (MS-7817) v: 3.0 serial: <superuser required> 
           UEFI: American Megatrends v: 17.5 date: 03/30/2015 
CPU:       Info: Quad Core model: Intel Core i5-4460 bits: 64 type: MCP cache: L2: 6 MiB 
           Speed: 1777 MHz min/max: 800/3400 MHz Core speeds (MHz): 1: 1777 2: 1275 3: 1970 
           4: 2071 
Graphics:  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics 
           driver: i915 v: kernel 
           Display: x11 server: X.Org 1.20.11 driver: loaded: modesetting unloaded: fbdev,vesa 
           resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 4600 (HSW GT2) v: 4.5 Mesa 20.3.5 
Audio:     Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor HD Audio driver: snd_hda_intel 
           Device-2: BEHRINGER UMC204HD 192k type: USB driver: snd-usb-audio 
           Device-3: AKAI Professional M.I. MPK Mini Mk II type: USB 
           driver: hid-generic,snd-usb-audio,usbhid 
           Sound Server-1: ALSA v: k5.10.0-26-amd64 running: yes 
           Sound Server-2: JACK v: 1.9.21 running: yes 
           Sound Server-3: PulseAudio v: 14.2 running: yes 

Reaper 7.03

**Comment by baconpaul** [comment]
Our pipelines build with ubuntu 22 whcih my guess injects a dependency with a different library version than your distro. I would suggest build from source on your os is your best bet.

**Comment by codecollider** [comment]
Oh that was fast 8) . I checked 1.2.3 and this worked. Thanks, I'll try building from source.

**Comment by baconpaul** [comment]
Yeah between 123 and 13 the free resources Microsoft provides is for builds (for which we are very grateful) eoled Ubuntu 18 and we moved to a mix of 20 and 32 so there’s probably a libc rev which is tripping you up

**Comment by mkruselj** [comment]
@codecollider Knowing the info that Paul mentions above, do you think we can close this issue?

**Comment by codecollider** [comment]
Hi,

yes can be closed

Best
Marco

EvilDragon ***@***.***> schrieb am Mi., 27. Dez. 2023, 00:15:

**Comment by baconpaul** [comment]
Hi!

I set up a dockerfile using u18 and so on and our nightlies now use an older libc

i can’t actually test this though! Since I don’t have an older Debian around.

Can you try https://github.com/surge-synthesizer/releases-xt/releases/tag/Nightly this binary and let us know if it works?

thanks!

**Comment by baconpaul** [comment]
Another test found a bug. Please hold on… I’ll update when we fix it

**Comment by baconpaul** [comment]
OK if you could give it a try when you have a minute that would be great.

**Comment by codecollider** [comment]
Hi,

I checked it and installation worked. But the VST3 is not found by Reaper
and it fails to initialize in Renoise.

I checked: surge-xt-linux-x64-NIGHTLY-2024-01-19-816b259.deb
<https://github.com/surge-synthesizer/releases-xt/releases/download/Nightly/surge-xt-linux-x64-NIGHTLY-2024-01-19-816b259.deb>

Best,
Marco

Am Fr., 19. Jan. 2024 um 17:45 Uhr schrieb Paul ***@***.***>:

**Comment by baconpaul** [comment]
Ok we have an alternate approach we are working on for 1.3.1 - I don’t think we will be able to do better than this nightly on Azure. Stay tuned!

**Comment by baconpaul** [comment]
And thanks for testing!
