### ISSUE TITLE
debian installer error

### ISSUE THREAD

**Issue by stephenbreitling** [surge-synthesizer/surge#7398]
**Bug Description:**
 error message running the debian installer

**Surge XT Version**
surge xt 1.3.0
 Linux 64-bit (Standalone, CLAP, LV2, VST3 - .deb built on Ubuntu 18.04, LV2 with JUCE 6 community branch)]

**Reproduction Steps:**
i tried installation on an avl-mxe system, but it broke off with an error message.
the previous version 1.2.3 was installing and running on my computer without any issues.

**Comment by baconpaul** [comment]
The error message would have helped but my guess is you are in an older distro. Our build servers upgraded to Ubuntu 22 for this release

probably a build from source is the answer

**Comment by baconpaul** [comment]
See #7397
