### ISSUE TITLE
Patch Selection via Program Change Not Working in REAPER

### ISSUE THREAD

**Issue by williamfields** [surge-synthesizer/surge#7400]
**Bug Description:**

Surge is not changing patches when sending Program Change messages from ReaControlMIDI inside REAPER.

**Surge XT Version**

Version: Surge XT 1.3.0.20a8e16
Build: 2023-12-08 @ 12:55:35 on 'fv-az390-357/pipeline' with 'MSVC-19.37.32826.1' using JUCE 7.0.5
System: Windows 64-bit CLAP on Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Host: Reaper @ 44.1 kHz / Process block size: 32 samples

**Reproduction Steps:**
1. Set up patches in folder structure inside ...\Surge XT\Patches\MIDI Programs
2. Add instance of ReaControlMIDI to track.
3. Add instance of Surge (Clap) to track (after ReaControlMIDI).
4. In ReaControlMIDI, click "Load file" button and choose "GM.reabank".
5. In ReaControlMIDI, choose MIDI channel 1 at the top.
6. Use the Bank and Program dropdowns to send Program Change messages.
7. Surge does not respond to the Program Change messages.

**Expected Behavior:**
Surge should change patches as per the description in the 1.3 release notes.

**Screenshots:**

![image](https://github.com/surge-synthesizer/surge/assets/9380730/54ac6e8f-5261-4b34-918e-e6c0ccf1d24d)

**Computer Information (please complete the following!):**
 - OS: Windows 10
 - Host: REAPER 7.06

**Comment by mkruselj** [comment]
Note the bank select MSB value that is there. This needs to be 0 if you want to select patches that are directly at root of MIDI Programs folder. Then bank select 1 will pick patches from the alphabetically first subfolder of MIDI Programs, and so on.

**Comment by williamfields** [comment]
@mkruselj: I see! I was looking at the LSB instead of the MSB. Thanks!

**Comment by baconpaul** [comment]
Great so all works then? Super!
