### ISSUE TITLE
how does vst3 support mpe in ableton live?

### ISSUE THREAD

**Issue by modosc** [surge-synthesizer/surge#7402]
i've been digging through the code and i can't figure this one out. 

when i load up surge as a vst3 in live i see it supports mpe because it has the mpe tag in the display:

<img width="405" alt="image" src="https://github.com/surge-synthesizer/surge/assets/2231664/b40a61f8-3043-41f9-851d-d5e133765eb4">

however, in a plugin i've created with juce, i cannot get "mpe" to display for vst3 (works fine with au/auv3).

i found [this conversation](https://github.com/surge-synthesizer/surge/issues/3776) but didn't see any changes come out of it from your end. 

i noticed the rpn implementation but also that ableton doesn't call this so i'm guessing this isn't the issue?

if you can offer any insight here it would be greatly appreciated, thanks!

**Comment by baconpaul** [comment]
Does your juce class override `AudioProcessor::supportsMPE` to return true?

That's the only thing we do I think.

**Comment by modosc** [comment]
> Does your juce class override `AudioProcessor::supportsMPE` to return true?
> 
> That's the only thing we do I think.

yep. i'm going to try opening a ticket with ableton, thanks!

**Comment by mkruselj** [comment]
> Does your juce class override `AudioProcessor::supportsMPE` to return true?
> 
> That's the only thing we do I think.

We also respond to RPN message to set up MPE.
