### ISSUE TITLE
Lfo x Eg Module in VCV rack does not have a working envelope generator 

### ISSUE THREAD

**Issue by Sojourner00** [surge-synthesizer/surge#7404]
Envelope generator has an output which stays on maximum voltage.

**Comment by mkruselj** [comment]
if it's the EG output that one would be max voltage by default.

**Comment by baconpaul** [comment]
We improved the way it works in a multi gate mode with 2.2, but 2.1 does output an envelope if you wire correctly. Can you share your network or a screen shot of it?

**Comment by baconpaul** [comment]
![Screenshot 2023-12-21 at 10 22 22 AM](https://github.com/surge-synthesizer/surge/assets/13387561/43a78fec-97b4-4a1f-b9b2-0db82cdf23b1)

Anyway here's how you can wire the module to get a working envelope generator. Please reopen the issue if you see differently! Thanks
