### ISSUE TITLE
Rename modern sin

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#7405]
To semi-sin or similar

**Comment by mkruselj** [comment]
Parabola is probably correct? Semi-sine is something else.

**Comment by baconpaul** [comment]
Or near sine. Or sin approx. sin-like maybe?

parabola is too far from what it is musically even though it’s correct mathematically

**Comment by mkruselj** [comment]
If it's a parabola mathematically it should be called like that IMO. Even Reaktor does this:

![image](https://github.com/surge-synthesizer/surge/assets/2393720/58d9fa38-9090-49e9-abb7-157e1bb68387)

**Comment by baconpaul** [comment]
Oh huh! Neat.

one other thought:

So I bet if we call it “sin approx” we will get no more questions about either “why isn’t this sin” or “where did sin go”

if we call it sin we get the first

if we call it parabola I worry we will get the second….

mash surge menu is a different sophistication level than set up a realtor network

**Comment by baconpaul** [comment]
We decided not to
