### ISSUE TITLE
User only patch menu

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#7407]
See convo in accessibility 

basically a keybind which pops just the user patches column makes reader nav way faster

we already do right click for just current category maybe there’s a similar one free or some such

**Comment by mkruselj** [comment]
Ctrl/Cmd+right click to show just user patches, otherwise the full menu? so for a11y that would be Ctrl+Shift+F10.

We should hardcode this, don't think it's needed to add this to keybind manager dialog.

**Comment by baconpaul** [comment]
If that’s free then yeah that’s perfect and I agree completely

**Comment by mkruselj** [comment]
Yeah that is free!
