### ISSUE TITLE
OSC (open sound control) - /q/all_params can crash Surge XT on Mac

### ISSUE THREAD

**Issue by gitsmol** [surge-synthesizer/surge#7410]
**Bug Description:**
I'm the guy making a TouchOSC-template for Surge XT. Currently, to keep the TouchOSC interface in sync with Surge, I have to get a number of different params when changing oscillator types. This is because the osc-types have different controls for param 1-7 and so when changing osc-types I just query for all parameter info. 

When switching from osc-type 'String' to 'Twist', and immediately fetching all params, Surge will reliably crash on Mac OS.
I'm sending these OSC messages:
```
/param/a/osc/1/type 10
/q/all_params
```

Unfortunately I'm away from home right now and don't have a linux box on hand to test other setups.

**Surge XT Version**
* Version: 1.3.0.20a8e16
* Plugin Type: Standalone
* Bitness: 64-bit

**Reproduction Steps:**
As described, using TouchOS. 
In the testscript used by @pkstone, adding and running the following code will crash Surge.

```
def trigger_crash():
    msg = obp.OSCMessage("/param/a/osc/1/type", ",f", [9.0])
    osc_send(msg, "oscout")
    osc_process()
    
    msg = obp.OSCMessage("/param/a/osc/1/type", ",f", [10.0])
    osc_send(msg, "oscout")
    osc_process()
    
    msg = obp.OSCMessage("/q/all_params", ",", [])
    osc_send(msg, "oscout")
    osc_process()
```

**Expected Behavior:**
After changing the osc type, Surge sends OSC messages for all of its params.

**Computer Information (please complete the following!):**
 - OS: Mac OS 13.6.1
 - Host: Standalone

Attached is a crashlog generated by Mac OS.
[surge_crashlog_231225.txt](https://github.com/surge-synthesizer/surge/files/13767103/surge_crashlog_231225.txt)

**Comment by baconpaul** [comment]
I was sitting here thinking “I bet the crash log is in the dynamic value code” and hey voila there it is

I bet there’s a timing issue with the oscillator switching later than the Param inquiry. Thanks for the excellent report

**Comment by pkstone** [comment]
Yes, great use of the script for an excellent report. Paul, is there anything I need to help with on this?

**Comment by baconpaul** [comment]
Nah I'll just have to look and fix it - something is out of order or on the wrong thread or not defensive enough with the parameter type switches

**Comment by pkstone** [comment]
Great!
I can only repeat the crash if I turn off the printout of the resulting parameter dump in the Python script. Maybe the printing slows things down enough to not cause the crash?

**Comment by baconpaul** [comment]
That makes sense. If the audio thread runs and settles down then is configuration won’t be there any more
