### ISSUE TITLE
Midi control over unison voices

### ISSUE THREAD

**Issue by Keessie** [surge-synthesizer/surge#7414]
The whole front panel allows for midi control, except for the unison voices slider.

**Comment by mkruselj** [comment]
This is because integer parameters are not modulatable in Surge. Very old issue that is not at all easy to fix.

Duplicate of #235.

**Comment by Keessie** [comment]
Thanks for clarifying this, it seemed like so obvious long hanging fruit, there has to be a reason

**Comment by mkruselj** [comment]
You can use OSC to control the parameter, or host automation of course. That all works.

**Comment by Keessie** [comment]
Thanks for the suggestion. I'm building a custom hardware controller, so have the opportunity of customisation.
