### ISSUE TITLE
MPE Stuck notes in mono ST + FP if playing legato

### ISSUE THREAD

**Issue by fredericcormier** [surge-synthesizer/surge#742]
Stuck notes when using mono ST + FT when MPE is enabled
Only if playing legato.
No stuck notes when playing staccato

See attached Logic X Project.

Note. I couldn't use a midi file because when importing that midi file, the daw creates as many tracks as channels that my controller uses ( 8 in the case of the Linnstrument ).
Joining/Merging this tracks produces a track that plays differently than the original
[MPE-Mono-test.zip](https://github.com/surge-synthesizer/surge/files/2940966/MPE-Mono-test.zip)

Linnstrument 128
OSX 10.12.6
Logic 10.4.4
Nightly build 2019-03-06

**Comment by baconpaul** [comment]
Thank you! Very useful. I was also able to stick it last night in logic and have been staring at the voice stealing code ... with our examples I will be able to fix this no problem before beta 7!

**Comment by baconpaul** [comment]
Oh and @fredericcormier I'm thinking we should have some MPE patches included in the synth factor layer. I have one or two going but if you end up coming up with any you want to contribute that work well for you, we would be happy to include them. I'll make a separate issue if you are interested. (cc: @esaruoho)

**Comment by fredericcormier** [comment]
OK, good idea

**Comment by baconpaul** [comment]
Just an FYI: Your excellent example allowed me to find a fix to this this morning. I need to test it extensively still (which I will do today) but I think we can get this problem resolved in a nightly this weekend and in beta 7 for sure. Thank you very much.

**Comment by fredericcormier** [comment]
You're welcome.

Happy to help.

**Comment by baconpaul** [comment]
@fredericcormier I have fixed this tonight. Boy it was a bit fiddly....

It will take about an hour for the new nightly to show up on the website I think, but if you have some time this weekend, grabbing a nightly from later tonight and really stress testing some of the MPE mono mode would be great. I stressed it with both my roli and in non mpe mode with my keyboard but the more the better.
