### ISSUE TITLE
CPU spike when playing very low frequencies using some tunings

### ISSUE THREAD

**Issue by williamfields** [surge-synthesizer/surge#7423]
**Bug Description:**

When playing very low notes / frequencies using a tuning that has a small number of steps per octave, CPU usage spikes severely. 

**Surge XT Version**

Version: Surge XT 1.3.0.20a8e16
Build: 2023-12-08 @ 12:55:35 on 'fv-az390-357/pipeline' with 'MSVC-19.37.32826.1' using JUCE 7.0.5
System: Windows 64-bit VST3 on Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Host: Reaper @ 44.1 kHz / Process block size: 32 samples

**Reproduction Steps:**

Oscillator = Twist
Engine = Harmonic (others may be affected)
Oscillator tuned down -3 octaves
Tuning = ED2-05.scl
Play the lowest notes on the keyboard

**Expected Behavior:**
No significant change in CPU usage.

**Computer Information (please complete the following!):**
 - OS: Windows 10
 - Host: Reaper 7.07

**Comment by williamfields** [comment]
I just realized that this problem also affects the "String" oscillator. Others could be affected as well. I haven't tested all oscillator types.

**Comment by baconpaul** [comment]
String has a different type of way to clamp and it was done in process but not init. Have a PR inbound.

**Comment by baconpaul** [comment]
OK I merged that. @williamfields if you can try the nightly that emerges a couple of hours from now that would be wonderful. I'll leave this open until i get confirmation.

**Comment by williamfields** [comment]
@baconpaul Confirmed fixed. Thanks!

**Comment by baconpaul** [comment]
Excellent!
