### ISSUE TITLE
With Milliseconds for the param meta data things

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#7424]
port it to param metadata
update surge for dela
etc

**Comment by mkruselj** [comment]
Maybe we should do the same thing for Hz parameters, so that they start using kHz when above 1000 Hz?

**Comment by baconpaul** [comment]
Maybe, a filter cutoff going from 972hz to 1.00 khz would be a bit off I think. Perhaps khz above 2500 or something?

**Comment by mkruselj** [comment]
That's not how you would see it in the EQ either. that's not how we show things in the filter analysis overlay... kilo starts at 1000.
