### ISSUE TITLE
Installing XT 1.3.0 causes VCV plugin to crash

### ISSUE THREAD

**Issue by jocphx** [surge-synthesizer/surge#7427]
**Bug Description:**
I installed the VST3 version of XT 1.3.0 and all of a sudden all my VCV patches containing the Surge XT module started to crash.
I uninstalled it and the VCV patches started to open fine, again.

**Surge XT Version**
* Version: 1.3.0
* Plugin Type: [VST3]
* Bitness: [64-bit]

**Reproduction Steps:**
1. Create a VCV patch using the Surge XT modules, say the Wavetable Osc, and save it
2. Install the VST3 of XT 1.3.0
3. Try to open the VCV patch again - in my case, VCV crashes, and it will keep crashing, until I uninstall the VST3!

**Expected Behavior:**
VCV not being affected

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following!):**
 - OS: [Windows 7, Windows 10]
 - Host: [N/A]
 - Version: [N/A]

**Additional Information:**

**Comment by baconpaul** [comment]
Hi!

The fix for this has been in the library queue for about a month and is set to be released this week. In the interim you can install the 2.2.1 release from our GitHub as outlined https://community.vcvrack.com/t/surge-rack-sporadic-crashes-after-installing-vst-1-3/21156/6 here
