### ISSUE TITLE
Surge - Pressing Bluetooth Midi in Settings crashes on Mac OS

### ISSUE THREAD

**Issue by gitsmol** [surge-synthesizer/surge#7429]
## Bug Description:
Pressing the bluetooth midi button crashes Surge on Mac OS.

## Surge XT Version
Version: 1.3.0.20a8e16
Plugin Type: Standalone
Bitness: 64-bit

## Reproduction Steps:
Go to settings, press the bluetooth midi button.

## Computer Information (please complete the following!):
OS: Mac OS 13.6.1
Host: Standalone

## Additional Information:
The crash reporter helpfully indicates that:
```
Termination Reason:    Namespace TCC, Code 0 
This app has crashed because it attempted to access privacy-sensitive data without a usage description. 
The app's Info.plist must contain an NSBluetoothAlwaysUsageDescription key with a string value explaining
to the user how the app uses this data.
```

[Surge XT-2024-01-04-210528.ips.zip](https://github.com/surge-synthesizer/surge/files/13835550/Surge.XT-2024-01-04-210528.ips.zip)

**Comment by mkruselj** [comment]
Can you attach the whole crashlog please? (ideally as a zip file)

**Comment by gitsmol** [comment]
> Can you attach the whole crashlog please? (ideally as a zip file)

Sure can, here it is.
[Surge XT-2024-01-04-210528.ips.zip](https://github.com/surge-synthesizer/surge/files/13835550/Surge.XT-2024-01-04-210528.ips.zip)

**Comment by baconpaul** [comment]
Hmm this is a dup of #7204 which I couldn't repro. Will look when I'm back

**Comment by baconpaul** [comment]
It looks like we need to add

```
  _juce_append_target_property(file_content BLUETOOTH_PERMISSION_ENABLED         ${target} JUCE_BLUETOOTH_PERMISSION_ENABLED)
    _juce_append_target_property(file_content BLUETOOTH_PERMISSION_TEXT            ${target} JUCE_BLUETOOTH_PERMISSION_TEXT)
```

those properties to the standalone. Let me try that and then build a nightly and see if it fixes your problem, since I still can't repro it here (but also don't have a bluetooth midi device)

**Comment by baconpaul** [comment]
OK @gitsmol I just merged what I think is a fix for this crash. Manually inspecting the info.plist adds the missing field mentioned in your crash.

In about 90 minutes from now this change will be in our nightly build which you can download <https://surge-synthesizer.github.io/nightly_XT/> here

If you get a chance in the next few days, but again after 90 minutes from now, to download the nightly and try again i'd appreciate it. I'll leave this issue open but marked as potentially resolved until we hear from you.

We will do a 1.3.1 bug fix release in early feb I bet, and this change will be included in it.

**Comment by gitsmol** [comment]
@baconpaul Just built from source and the bluetooth menu pops up now. Looks fixed to me.

**Comment by baconpaul** [comment]
Oh that's great!

I think this is an os 13 bug. I'm on 14 and I see generic boilerplate text without this set 

But glad it's fixed. Will close this. And thanks! Great bug reports make great software. Appreciated
