### ISSUE TITLE
Linux mint 20, reaper 6.79, surge xt 1.3.0. GLIBC issue.

### ISSUE THREAD

**Issue by TheGuyWhoo** [surge-synthesizer/surge#7431]
When I try to load vst3, I get this:
        
        swell: dlopen() failed: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /usr/lib/vst3/Surge XT Effects.vst3/Contents/x86_64-linux/Surge XT Effects.so)
        swell: dlopen() failed: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /usr/lib/vst3/Surge XT Effects.vst3/Contents/x86_64-linux/Surge XT Effects.so)

only vst3 scans. All other plugins do not scan successfully. VST3 scans successfully, but does not load successfully.

**Comment by TheGuyWhoo** [comment]
Output from standalone:

        /bin/Surge XT: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /bin/Surge XT)
        /bin/Surge XT: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /bin/Surge XT)
        /bin/Surge XT: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /bin/Surge XT)
        /bin/Surge XT: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /bin/Surge XT)

**Comment by baconpaul** [comment]
Yeah our build pipeline upgraded to Ubuntu 22. The solution for now is self build

**Comment by TheGuyWhoo** [comment]
Will that stay temporary, or is self building just the move from now on?

**Comment by baconpaul** [comment]
You could also upgrade your glibc 

I’m not sure if there’s an easy way for me to do a lib231 build on our free build resources. If you know how it would be not temporary! Or if I figure it out! Or if someone else does!

I have an idea with a docker image which may work - will see

**Comment by baconpaul** [comment]
Hi!

I set up a dockerfile using u18 and so on and our nightlies now use an older libc

i can’t actually test this though! Since I don’t have an older Debian around. 

Can you try https://github.com/surge-synthesizer/releases-xt/releases/tag/Nightly this binary and let us know if it works?

thanks!

**Comment by baconpaul** [comment]
Ok another test caught a bug. Please hold off

**Comment by baconpaul** [comment]
OK if you could give it a try when you have a minute that would be great

**Comment by TheGuyWhoo** [comment]
I'm sorry for taking so long, but I recently switched to windows 10 after a hard drive failure and can no longer test this.
