### ISSUE TITLE
How do I send OSC output to a remote tablet?

### ISSUE THREAD

**Issue by kmitch95120** [surge-synthesizer/surge#7432]
My apologies if this is documented somewhere but I've searched and can't find anything.  I'm trying to create a TouchOSC template for Surge XT and I can only seem to get OSC output (i.e. /q/all_params) to TouchOSC if it's running on the same computer as the synth.  I can only find OSC input and Output port settings but not an output IP address setting.   It appears that all output goes to 127.0.0.1. 

Here's the version info from Surge XT:

Version: Surge XT 1.3.0.20a8e16
Build: 2023-12-08 @ 12:56:16 on 'Mac-1702036315614.local/pipeline' with 'AppleClang-14.0.0.14000029' using JUCE 7.0.5
System: macOS 64-bit Standalone on Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Sample Rate: 48.0 kHz / Process block size: 32 samples

**Comment by baconpaul** [comment]
Yeah we realized after 130 we only had localhost! That’s fixed in the nightly and will be part of a 131 release early this year. You can grab the nightly now and it has worked with touch Osc (or join our discord and chat with the folks in surge dev channel)

**Comment by kmitch95120** [comment]
Thanks for the quick reply. I'll grab the nightly build and join the Discord server if I have any questions.
