### ISSUE TITLE
Undo doesn't work on manual inputs.

### ISSUE THREAD

**Issue by Jxp955** [surge-synthesizer/surge#7433]
**Bug Description:**
Left-click and dragging any slider will be able to be undone.
Using right-click to manually change a slider's value, will not be able to be undone.

**Surge XT Version**
Surge XT 1.3.0.20a8e16

* Version: Build: 2023-12-08 @ 12:55:35 on 'fv-az390-357/pipeline' with 'MSVC-19.37.32826.1' using JUCE 7.0.5
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Start up patch
2. Right-click any slider
3. Input a value
4. Cannot undo

**Expected Behavior:**
It appears you cannot undo any manual input on any slider.

**Screenshots:**
N/A

**Computer Information (please complete the following!):**
 - OS: Windows 10
 - Host: Reaper
 - Version: v7.07

**Additional Information:**
N/A

**Comment by baconpaul** [comment]
Holy heck! How could we forget this! Thanks!
