### ISSUE TITLE
Minor MSEG graphical bug

### ISSUE THREAD

**Issue by Jxp955** [surge-synthesizer/surge#7453]
**Bug Description:**
MSEG doesn't show left-most vertical snap lines, 
when on a horizontal division above 10 when in LFO mode.

**Surge XT Version**
Surge XT 1.3.0.20a8e16

* Version: 2023-12-08 @ 12:55:35 on 'fv-az390-357/pipeline' with 'MSVC-19.37.32826.1' using JUCE 7.0.5
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. On an LFO, select the MSEG.
2. Click on the screen to bring up the editor.
3. Set the Horizontal to anything above 10.
4. Set 'Edit Mode' to LFO.
5. Left most line will have disappeared.

**Expected Behavior:**
The left most lines can be useful for sharp attacks.

**Screenshots:**
![image](https://github.com/surge-synthesizer/surge/assets/55408938/c5d5e731-9597-4423-ba03-2b2802c577f0)
![image](https://github.com/surge-synthesizer/surge/assets/55408938/7abda6b7-c1a4-4329-969c-95952dc2bf65)

**Computer Information (please complete the following!):**
 - OS: Windows 10
 - Host: Reaper
 - Version: 7.09

**Additional Information:**
N/A

**Comment by baconpaul** [comment]
ooh ha yeah the code to make sure we draw every (n) lines clearly has a starting error.

Thanks we can get this fixed for 1.3.1
