### ISSUE TITLE
Selecting OSC type FM2 will be shown and FM3

### ISSUE THREAD

**Issue by tavasti** [surge-synthesizer/surge#746]
When I select OSC type FM2, OSC type FM3 is shown. Parameter setting seem to be bit different on selecting FM2 and FM3, so I assume this is just copy-paste in string. 

**Desktop (please complete the following information):**
 - OS: Linux
 - Host carla

**Comment by baconpaul** [comment]
That’s actually an error in the bitmaps! I noticed it when porting to SVG but forgot to open an issue.

@itsmedavep check this out! 

![](https://github.com/surge-synthesizer/surge/blob/master/assets/original-vector/exported/bmp00119%402x.png)

So good we have FM3 twice :)

Good eyes @tavasti thanks!

**Comment by itsmedavep** [comment]
Done now for the 1.6 bitmaps here:

https://github.com/surge-synthesizer/surge/pull/748

**Comment by itsmedavep** [comment]
> When I select OSC type FM2, OSC type FM3 is shown. Parameter setting seem to be bit different on selecting FM2 and FM3, so I assume this is just copy-paste in string.
> 
> **Desktop (please complete the following information):**
> 
> * OS: Linux
> * Host carla

Thanks for reporting this! Nice catch and sorry for any frustrations I may have caused.
