### ISSUE TITLE
Add UI for OSC Setup dialog

### ISSUE THREAD

**Issue by pkstone** [surge-synthesizer/surge#7472]
<img width="990" alt="Screenshot 2024-01-22 at 10 15 20 AM" src="https://github.com/surge-synthesizer/surge/assets/6858202/8fc5fa00-26e5-4d4e-9ed3-214c4fee09fa">

Please add the graphics for this dialog to Surge, and I will fill in all the callbacks.

**Comment by baconpaul** [comment]
OK with 7474 this is over to phil to get it working and laid out to spec. Then push it back to me for a quick ally/screen reader fix up and we are done.

**Comment by baconpaul** [comment]
Oh this is in the release now! Closing the issue
