### ISSUE TITLE
Using Surge XT in the GarageBand DAW (macOS 14 Sonoma)

### ISSUE THREAD

**Issue by UdderNonsense** [surge-synthesizer/surge#7473]
Hi!

I've been having fun with the standalone app, but when I try to use it as an instrument/plugin, I am greeted by a massive list of sliders and drop-downs instead of the nice GUI.

I don't know if this is to be expected, or if I have installed something wrong. Attached is a picture of my view.

<img width="1440" alt="Screenshot 2024-01-22 at 4 43 29 PM" src="https://github.com/surge-synthesizer/surge/assets/90730357/c80ad768-c5ae-473e-8c87-c774fead35d2">

More broadly, I'm confused about opening Surge as a plugin in a DAW at all: when I open it, should I see the fancy GUI?

**Comment by baconpaul** [comment]
You definitely should. I do in logic all the time. And when I just tried in GB I get this

![Screenshot 2024-01-22 at 6 39 15 PM](https://github.com/surge-synthesizer/surge/assets/13387561/f28e7553-a963-4afd-9c8c-daddfb48c211)


https://www.youtube.com/watch?v=WX3An_dhG54

that video seems to show the fix which is in preferences dont select "open plugins in control view"

if that works let us know

(That's the 'generic parameter' view which in logic is one of the editor types - seems GB has it as a global option)

**Comment by baconpaul** [comment]
![Screenshot 2024-01-23 at 9 32 44 AM](https://github.com/surge-synthesizer/surge/assets/13387561/70911204-ddb8-4b6e-a52e-35b056a93399)

Yeah just confirmed that with this checked surge does what you see and with it unchecked surge does what i see

So I'm going to close this issue - I don't think its anything for us to change in surge - but if that doesn't do it for you please do re-open it.
