### ISSUE TITLE
Memory leaks in Surge standalone on Windows

### ISSUE THREAD

**Issue by RobinSchmidt** [surge-synthesizer/surge#7478]
**Bug Description:**
I get memory leak reports in debug builds  with Visual Studio of Surge standalone on Windows when closing the synth.

**Surge XT Version**
Surge XT 1.3.work.1ddf4df
Build: 2024-01-27 @ 00:37:47 on 'DESKTOP-UG17QSV/local' with 'MSVC-19.21.27702.2' using JUCE 7.0.5
System: Windows 64-bit Standalone on Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz
Sample Rate: 48.0 kHz / Process block size: 32 samples

**Reproduction Steps:**
1. I forked the repo on 2024/01/26, cloned my fork to a local folder, created my own working branch from the main branch and generated the Visual Studio 2019 project files via CMake. 
2.  Then I fired up the generated Surge.sln VS solution file via double-click in Windows Explorer. 
3. In VS, I built the surge-xt/surge_xt_Standalone project in Surge.sln on Windows with Visual Studio 2019 in Debug configuration. To do this, one must right-click on surge-xt_Standalone in the "Solution Explorer" and  click on "Set as StartUp Project". The text of the project name will then become boldface. Make sure that the "Debug" configuration is selected (I think, it should be), 
4. Then I click the "Build+Run" button (the green "Play" button). This will initiate the build and when its done run Surge. 
5. After the Surge GUI has openened, I immediately close it. 

**Expected Behavior:**
 The "Output" window of VS now says (among other things):

> Detected memory leaks!
> Dumping objects ->
> {357844} normal block at 0x000001DB106116A0, 60 bytes long.
>  Data: <            <   > 00 00 00 00 00 00 00 00 00 00 00 00 3C 00 00 00 
> {357822} normal block at 0x000001DB10611820, 60 bytes long.
>  Data: <            <   > 00 00 00 00 00 00 00 00 00 00 00 00 3C 00 00 00 
> {357800} normal block at 0x000001DB10611BA0, 60 bytes long.
>  Data: <            <   > 00 00 00 00 00 00 00 00 00 00 00 00 3C 00 00 00 
> {357778} normal block at 0x000001DB106129A0, 60 bytes long.
>  Data: <            <   > 00 00 00 00 00 00 00 00 00 00 00 00 3C 00 00 00 
> {357756} normal block at 0x000001DB10612E20, 60 bytes long.
>  Data: <            <   > 00 00 00 00 00 00 00 00 00 00 00 00 3C 00 00 00 
> {357734} normal block at 0x000001DB10612FA0, 60 bytes long.
>  Data: <            <   > 00 00 00 00 00 00 00 00 00 00 00 00 3C 00 00 00 
> Object dump complete.

When I do not immediately close the window but play a note and then close the window, I get even more leaked objects:

> Detected memory leaks!
> Dumping objects ->
> {357844} normal block at 0x000001C5FC3D6130, 60 bytes long.
>  Data: <            <   > 00 00 00 00 00 00 00 00 00 00 00 00 3C 00 00 00 
> {357822} normal block at 0x000001C5FC3D6B30, 60 bytes long.
>  Data: <            <   > 00 00 00 00 00 00 00 00 00 00 00 00 3C 00 00 00 
> {357800} normal block at 0x000001C5FC3D6430, 60 bytes long.
>  Data: <            <   > 00 00 00 00 00 00 00 00 00 00 00 00 3C 00 00 00 
> {357778} normal block at 0x000001C5FC3D65B0, 60 bytes long.
>  Data: <            <   > 00 00 00 00 00 00 00 00 00 00 00 00 3C 00 00 00 
> {357756} normal block at 0x000001C5FC3D6DB0, 60 bytes long.
>  Data: <            <   > 00 00 00 00 00 00 00 00 00 00 00 00 3C 00 00 00 
> {357734} normal block at 0x000001C5FC3D6AB0, 60 bytes long.
>  Data: <            <   > 00 00 00 00 00 00 00 00 00 00 00 00 3C 00 00 00 
> {310443} normal block at 0x000001C5FC275180, 16 bytes long.
>  Data: <  s             > F8 ED 73 FA C5 01 00 00 00 00 00 00 00 00 00 00 
> {310442} normal block at 0x000001C5FC275130, 16 bytes long.
>  Data: <  s             > D8 D4 73 FA C5 01 00 00 00 00 00 00 00 00 00 00 
> {310441} normal block at 0x000001C5FC274C80, 16 bytes long.
>  Data: <  s             > B8 BB 73 FA C5 01 00 00 00 00 00 00 00 00 00 00 
> {310440} normal block at 0x000001C5FC275590, 16 bytes long.
>  Data: <  s             > 98 A2 73 FA C5 01 00 00 00 00 00 00 00 00 00 00 
> {310439} normal block at 0x000001C5FC275310, 16 bytes long.
>  Data: <x s             > 78 89 73 FA C5 01 00 00 00 00 00 00 00 00 00 00 
> {310438} normal block at 0x000001C5FC274B90, 16 bytes long.
>  Data: <Xps             > 58 70 73 FA C5 01 00 00 00 00 00 00 00 00 00 00 
> Object dump complete.

**Computer Information (please complete the following!):**
 - OS: Windows 10
 - Host: None (Standalone)

**Additional Information:**
Apparently, the 6 objects of 60 bytes are always leaked and additionally, additional 6 objects of size 16 bytes are leaked for each midi note that has been played. It doesn't matter if the notes are played via the virtual keyboard or a hardware midi keyboard. Trying to figure it out by defining _CRTDBG_MAP_ALLOC to get more detailed information about the leak was unsuccessful because with this macro defined, Surge doesn't compile anymore (when trying to build, 17 projects succeed, 4 fail). This seems to be due to the fact that defining _CRTDBG_MAP_ALLOC will cause standard library function names like malloc, free, etc. to be re-#defined via preprocessor macros which breaks compilation of code that uses these names for some of its own (member) functions. Using these names will cause syntax errors. JUCE does this, see here: https://forum.juce.com/t/conflict-with--crtdbg-map-alloc-visual-studio/6040. Something in the "eurorack.vcxproj" project apparently does this, too.

**Comment by baconpaul** [comment]
Reported as fixed after #7480 so closing!
