### ISSUE TITLE
Linux - surge-xt-cli using OSC ignores quit, ^-d, ^-c

### ISSUE THREAD

**Issue by gitsmol** [surge-synthesizer/surge#7493]
**Bug Description:**
When running surge-xt-cli (built from git) and using OSC, typing 'quit' or ^-d or ^-c doesn't exit surge.

**Surge XT Version**
Latest git build (2023-02-01). Also present in 1.3.0.
Ran on aarch64, archlinux

**Reproduction Steps:**
Run Surge:
`./build/surge_xt_products/surge-xt-cli --midi-input=1 --sample-rate=44100 --buffer-size=256 --audio-interface=0.5 --osc-in-port=53820 --osc-out-port=53821`

Now press
`^-d` or '^-c' or type 'quit'

Nothing happens.

**Expected Behavior:**
Surge exits.

**Computer Information (please complete the following!):**
Raspberry Pi 4
ArmArchlinux Aarch64

**Additional Information:**
This only happens when OSC is enabled.
(quick edit: it does work on Mac)

**Comment by baconpaul** [comment]
Oh I bet we forget to join the osc thread thanks

**Comment by baconpaul** [comment]
Ahh this is a bit trickier than I thought. The OSC implementation has a per-platform 'private/pimpl' implementation so I can't see the missed close from just reading code on my mac.

I'll have a linux box bootable Monday I'll try and repro and fix this, and will delay 1.3.1 until I do (we were planning 1.3.1 on Tuesday. My bet is this is a 4 line addition to shut down a thread/listener on linux so we will probably still make that)
