### ISSUE TITLE
Chord storage/memory

### ISSUE THREAD

**Issue by quirkylemon** [surge-synthesizer/surge#7507]
# Chord storage/memory concept and implementation.
## Concept
Chord storage is playing a chord or multiple notes with one key.  
There are several patches that do something similar but use multiple oscillators for multiple notes instead of multiple voices.

Benefits over the current workaround
- It allows you to use all 3 oscillators.
- You can play more than 3 notes per scene.  

Some examples of synths that have this feature 
- Roland Alpha Juno 1/2
- Korg Poly 800
- Novation Ultranova

## Implementation

You first enable chord storage by opening the poly playmode context menu.    
If there isn't a chord stored a popup opens saying to play some notes.  
There will be a button that says record chord.

the chord could be stored in SurgeSceneStorage as a list of integers representing midi notes. 

whenever surge recieves a midi on message it transposes and plays all the notes in the chord.

whenever surge recieves a midi off message it transposes and turns off all the notes in the chord.

---

I might try to make this but I haven't contributed to surge before so who knows how that will go.

**Comment by mkruselj** [comment]
Hello!

This is a feature request we've already had and it currently lives under a different guise in this ticket: #3895. So closing this issue in lieu of that one. Please continue discussion there!
