### ISSUE TITLE
Soft Takeover mode for MIDI learned parameters

### ISSUE THREAD

**Issue by sjomae** [surge-synthesizer/surge#7510]
Some MIDI controllers have a 'snap mode' (Faderfox for instance), is this supported by Surge?

The synth or plugin hosts sends MIDI cc values to the controller. When in snap mode, the controller doesn't send MIDI data, until it reached / picked up the value which it got from the synth / host.

Does the standalone version have a MIDI Out? Couldn't test, cause the standalone didn't launch properly on Linux.

**Comment by mkruselj** [comment]
This is not supported by Surge as it stands.

**Comment by mkruselj** [comment]
This is going to be better handled by MIDI 2.0 whenever that gets implemented at large (it seems this year might be an important one for MIDI 2.0!).

As it stands, we recommend using OSC for bidirectional synchronization of parameters.

**Comment by sjomae** [comment]
Will look into OSC later. Are current MIDI controllers compatible with MIDI 2.0?

**Comment by sjomae** [comment]
Ok, that doesn't sound very hopeful. MIDI 2.0 will not be the solution for me in the near future I'm afraid. Will look into OSC. 

You guys could still consider a MIDI 1 compatible MIDI Out though, but I'll leave that up to you. Thanks.

**Comment by mkruselj** [comment]
As it stands we are now focusing our efforts on getting Shortcircuit XT out this year, so Surge updates are likely going to slow down as a consequence. Perhaps there could be a soft takeover mode added for each MIDI learned parameter (received MIDI value is checked against current parameter value and only if the incoming value has crossed the current value it would take on), but there is no immediate priority to implement this.

**Comment by baconpaul** [comment]
The fr would basically be that the cc crosses the preset value once before midi control kicks in?

**Comment by mkruselj** [comment]
Yeah. And is optional per parameter.

**Comment by sjomae** [comment]
> The fr would basically be that the cc crosses the preset value once before midi control kicks in?

I think it's indeed useful when loading a preset. But also when changing the value with the mouse, instead of the controller, then the controller needs to know the changed value.

To get the best understanding of the feature, one could best just contact the creator of the Faderfox devices (see website). He seems to be responsive and has experience with different implementation in different software I suppose.

I had contact with him and he told me for instance:

"some programs like ableton live send only the last value after you don't send new values from the controller for a while."

**Comment by sjomae** [comment]
So, then you just ignore controller MIDI cc messages which differs from the current value?

**Comment by mkruselj** [comment]
Yup, until you meet and cross over the current parameter value as you tweak your MIDI controller.

**Comment by baconpaul** [comment]
Cool thanks for helping me understand

**Comment by sjomae** [comment]
> Yup, until you meet and cross over the current parameter value as you tweak your MIDI controller.

I think it should be only meet (40), not crossover(41) right? At 40, the user can turn the knob in the opposite direction (39).  :)

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/blob/a1bfbc0727437b28affa3ce4e6f0143c29626248/src/common/SurgeSynthesizer.cpp#L2337

That’s the rough location where you would want to put code to that effect

**Comment by sjomae** [comment]
Can't it just check if the incoming value is equal to the currently set value? If so, change wait_for_first_matching_value to false?

**Comment by baconpaul** [comment]
And add your takeover state to the Param so you can just blam it into the if 

I would also make it a global option if I was doing it in 13 lifecycle and check that option when constructed as an atomic - doing it Param by Param has streaming impacts and ui impacts which I think are too gnarly

**Comment by mkruselj** [comment]
> Can't it just check if the incoming value is equal to the currently set value? If so, change wait_for_first_matching_value to false?

That's what the code is doing but it is not enough to check for equalness, because you are not guaranteed to receive continuous stream of values. Say param value is 40, but your MIDI controller is at 80, and it's sending: 70, 60, 45, 20. 40 might never be hit. This is why you have to check both directions always, and also have some error margin due to floating point shenanigans etc.

**Comment by baconpaul** [comment]
Yes the fp stuff is important since Param sliders are not quantized to 1/127 so you need an imputed midi cc for the Param from the 01 value

**Comment by sjomae** [comment]
I see. One day you guys need to help me with learning C++ I suppose. ;)

**Comment by baconpaul** [comment]
Ha yeah! This is more just “the Param has higher resolution than a controller” and “controllers skip values” meaning == isn’t the right comparison

**Comment by mkruselj** [comment]
@baconpaul Some beginning effort is in mkruselj/soft-takeover-attempt. I'm missing some tricks, it's not quite working out well :(
