### ISSUE TITLE
De-baconpaul the OBS builds 

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#7511]
When @KottV and I set up the obs builds we did it under baconpaul 

someday soonish let’s do this

- [ ]  @mkruselj makes an obs account
- [x] I create a surge-synth-team obs account and invite kott and evil as maintainers
- [ ] I invite baconpaul kottv and evil to it
- [ ]  We port the surge nightky and release jobs
- [ ]  I connect GitHub using a long lived surge rack updated token rather than a short lived baconpaul one
- [ ]  We move the nightky 
- [ ]  We update the doc and links and retire the bp builds
- [ ]  We do a short circuit nightky to see if we can 

and voila. Bacon-free urls

thoughts?

**Comment by KottV** [comment]
Hi,

I set the version pattern for `surge-xt-nightly` as `PARENT_TAG+git.TAG_OFFSET.HASH` (as I did for the most of others my packages), so it's "1.3.1+git.0.4b53827e" now

on the surge website it's versioned as "NIGHTLY-2024-02-08-a1bfbc0"
I can make OBS nighlty version mostly the same, like "NIGHTLY-20240208-a1bfbc0" (without dashes)

does it make sense?

**Comment by baconpaul** [comment]
That would be handy! It’s mostly useful when people send us bug reports and we see they are running a 10 week old nightky without having to look up the hash

**Comment by KottV** [comment]
> That would be handy! It’s mostly useful when people send us bug reports and we see they are running a 10 week old nightky without having to look up the hash

I changed it to `%cd~%h`, the dash is not allowed in rpm version variable.
