### ISSUE TITLE
back forward buttons for patch Surge on Raspberry don't work

### ISSUE THREAD

**Issue by grbfst** [surge-synthesizer/surge#7516]
Hi,
I'm building a "machine" that is touch oriented based on Surge for a music therapist who works with the (demented) elderly.

I compiled it on a Raspberry but unfortunately the backward-forward patch (and category) buttons don't work, I have also tried with OSC commands, no luck.

Is this a (Linux) Raspberry specific problem, because in downloadable windows version the buttons work as expected?

Regards,
Marc

Version: Surge XT 1.3.main.c26bb0ba
Build: 2024-01-15 @ 17:31:54 on 'Synths/local' with 'GNU-12.2.0' using JUCE 7.0.5
System: Linux 64-bit Standalone on  Raspberry Pi 3 Model B Plus Rev 1.3
Sample Rate: 44.1 kHz / Process block size: 32 samples

**Comment by grbfst** [comment]
Thanks, that worked!

**Comment by baconpaul** [comment]
Great!
