### ISSUE TITLE
Channel split is off by one

### ISSUE THREAD

**Issue by pauleye** [surge-synthesizer/surge#7517]
**Bug Description:**
The split MIDI channel in Chan Split Scene Mode is off by one. Meaning that if I set the split channel to 8, notes on channels 1-8 are played by Scene A, and channels 9-16 are played by Scene B. The manual at https://surge-synthesizer.github.io/manual-xt/#scene-select-and-scene-mode states "Channel Split Notes from MIDI channels **below** the split MIDI channel will be played by scene A, notes from MIDI channels **above and including** the split MIDI channel will be played by scene B." If that's the intended behaviour, then this is a bug. Or alternately, you could change the manual text to read "below and including" and "above" respectively to match the current behaviour.
As a side note, I'm wondering how this is actually supposed to work if the split channel is set to 1, and if the "above and including" behaviour would be the intended one. This would practically mean that channels 1 and above (literally meaning "all channels") would be played by scene B.
As it is now of course, if you set the split channel to 1, then channel 1 is played by Scene A and channels 2 and above will be played by Scene B.

**Surge XT Version**
* Version: 1.3.1
* Plugin Type: CLAP, VST3
* Bitness: 64-bit

**Computer Information:**
 - OS: Windows 10
 - Host: Reaper
 - Version: 7.11
 - All 64-bit

**Comment by mkruselj** [comment]
Manual is incorrect on this one. We should be showing values 2-15 on this one instead.

**Comment by VincyZed** [comment]
Indeed, it was a mistake from the manual. Just fixed it, thanks for reporting @pauleye !
