### ISSUE TITLE
Ensemble effect is sample rate dependent

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#7519]
Specifically, its internal clock frequency is- And it'd be better if it weren't.

**Comment by jatinchowdhury18** [comment]
Hmmm, I haven't been able to re-create this issue yet locally. For example, here's an experiment where I loaded the "Init Sine" patch, added the Ensemble Effect, turned the "Depth" controls to 0%, and brought the clock rate all the way down. From there it's pretty easy to see what the BBD aliasing artifacts look like in a spectrum analyzer.

At 48 kHz sampling rate:
<img width="1100" alt="Screenshot 2024-02-18 at 11 41 44 AM" src="https://github.com/surge-synthesizer/surge/assets/13724188/265d9f16-30f8-4753-9e2d-9b2d094b7ee5">

And at 96 kHz sampling rate:
<img width="1100" alt="Screenshot 2024-02-18 at 11 41 20 AM" src="https://github.com/surge-synthesizer/surge/assets/13724188/3e5a7d4e-9be7-447f-8bef-71fe1449f953">

Do we have any more information about specific sample rates that the effect has problems with? Or specific settings of the Ensemble effect?

**Comment by Andreya-Autumn** [comment]
Honestly, I only tested with Reapers oversampling option, which as we learned in #6834 might not behave the same as changing host sample rate properly. I don't know what the user who reported was seeing, but lemme test real quick.

**Comment by Andreya-Autumn** [comment]
I am getting different results running the session at 48 vs 96 also. I did the same thing you did, depth 0 clock rate 1.5k. This is on Mac, CLAP Surge. 
 
<img width="813" alt="48" src="https://github.com/surge-synthesizer/surge/assets/105538426/3f5b3057-6c33-4b03-9802-5bcbf4884fd7">

<img width="824" alt="96" src="https://github.com/surge-synthesizer/surge/assets/105538426/0050c791-6f11-4d82-bbf5-eacb0942d1b9">

**Comment by jatinchowdhury18** [comment]
Hmmm... maybe the issue has more to do with the effect sample rate getting reset properly relative to the DAW's. I'll have another look soon.

**Comment by baconpaul** [comment]
some of the sample rates seem to be set in the constructor not init? Wonder if that's the issue indeed?

sample rate changes do call `virtual void Effect::sampleRateReset()` but the ensemble effect doesn't seem to implement that. Maybe that's the answer?
