### ISSUE TITLE
VST3 Automation in Bitwig doesn't move Surge UI

### ISSUE THREAD

**Issue by sense-amr** [surge-synthesizer/surge#752]
Previously sliders and knobs assigned from the bitwig knob gui  would move when pressed in surge and routed to the inbuilt interface in bitwig for modulation ..  

Previous version of bitwig 2.4.3 ... 

Change of behaviour where knobs and sliders dont respond .. in surge to bitwig .. in Bitwig v 2.5

**Comment by baconpaul** [comment]
As discussed on slack: The problem is that bitwig 2.5 hides a vst2 if a vst2 and vst3 are both available; and as documented elsewhere, the vst3 surge is broken. So I'm gonna change the name of this issue to "vst3 doesn't handle automation with a repaint" or something.

**Comment by sense-amr** [comment]
cool yes i couldnt easily check in bitwig 2.5 which version i was using .. it turns out VST3 .. which always had this problem of not moving sliders :)

**Comment by baconpaul** [comment]
<img width="723" alt="screen shot 2019-03-08 at 8 49 03 am" src="https://user-images.githubusercontent.com/13387561/54032238-090cda00-417f-11e9-8aff-a6934a7a5218.png">

And picking this "show all version" thing in bitwig settings restores your ability to load the vst2

**Comment by sense-amr** [comment]
just in time .. to show me the ONE Surge i have installed now :D
