### ISSUE TITLE
Saving tempo value in current patch

### ISSUE THREAD

**Issue by Nuri-Bou** [surge-synthesizer/surge#7529]
**Is your feature request related to a problem? Please describe!**
I'm only using Surge XT _**standalone version**_ (thx for doing it too, besides the plugin ones).
My problem is that when I'm loading a patch for a song, I've always have to set the tempo of the song manualy (on the left side of the virtual keyboard of Surge).
After a fresh start, Surge XT standalone always set the tempo at 120 bpm. This value seems to be hard coded since I could not find in any config file a way to set another default (or start up) value.

**Describe the solution you'd like:**
I would like that Surge saves the current tempo value in the current loaded patch when I'm saving/overwritting it.
When used as a DAW plugin, Surge XT could simply ignore this parameter of the patch, since Surge should receive the current tempo value from the DAW.

**Describe alternatives you've considered:**
No idea...

**Additional context:**
I'm using Surge XT standalone in Debian 12 (stable with KDE Plasma) on an used Dell Latitude 7200 2-in-1 (only with touch screen). Surge XT is controlled by a hardware MIDI keyboard Nektar Impact GX61. Audio output over the onboard sound card (phone output) of the Dell Latitude.
It's a killer standalone instrument for < 400,- EUR!!!
(and I'm also using Dexed and other software synths on this cheap but powerful hardware)

**Comment by baconpaul** [comment]
Oh that’s a good idea. Save the standalone tempo in the daw extra state (not the patch per se but that’s a detail you don’t care about) and use it if and only if you are in standalone

**Comment by nuke1984** [comment]
same here, it would be nice to recall tempo value when recall a patch in standalone mode, even if you recall the patch via MIDI Program Change.

**Comment by Nuri-Bou** [comment]
Thank you very much Paul!
I will use this new feature in the next release.
