### ISSUE TITLE
Formula LFOs behave differently if they have more than one output

### ISSUE THREAD

**Issue by butscher** [surge-synthesizer/surge#7531]
**Bug Description:**
I tried to create some kind of vocal sounds by filtering noise through an equalizer added to the insert FX chain. It should emphasize two frequencies from [this Wikipedia table](https://en.wikipedia.org/wiki/Formant#Phonetics).

To allow switching between the vowels, I wrote lua scripts. In the attached patch [Formant Filter Basic_bug.zip](https://github.com/surge-synthesizer/surge/files/14406956/Formant.Filter.Basic_bug.zip) the desired vowel is selected by Macro 1 (named "Vowel Select"). 

In scene A, S-LFO1 contains code to calculate the first frequency for the equalizer, S-LFO2 code for the second frequency.

In scene B, S-LFO1 contains code to calculate both frequencies.

All the scripts are nearly identical except for the final output. All other settings are identical between the scenes, so theoretically both scenes should generate the same sound but they don't do this.

**Surge XT Version**
* Version: 1.3.1
* Plugin Type: Standalone
* Bitness: 64-bit

**Reproduction Steps:**
1. Load the attached patch
2. Play a note with scene A set
3. Compare to same note with scene B

**Expected Behavior:**
Same sound generated by both scenes.

**Computer Information (please complete the following!):**
 - OS: Windows 7 64bit

**Comment by baconpaul** [comment]
oh for goodness sake. slfo just ignores routing index. that bug has been there forever. Stay tuned.

**Comment by baconpaul** [comment]
This is fixed in #7533 and will be in a nightly build later tonight. We're gonna make a mini 1.3.2 release also which increases the fix.

Thank you for the excellent bug report. Really top rate GitHub issue reporting. Appreciated.
