### ISSUE TITLE
AboutBox should use lato also

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#754]
AboutBox has a font. It should just use the surge lato font used for other stuff.

This amounts to making the about box set the info font rather than to kDefaultFont to (probably) the lfoTypeFont (which is 8 pt lato) then fixing the spacing in src/CAboutBox.cpp

**Comment by baconpaul** [comment]
I played with it for 10 seconds and displayFont (which is 9pt lato) is too small. So we want to make another font and set it up in the 3 runtime fonts. Bit more tedious but not that hard.

**Comment by baconpaul** [comment]
This is a good first issue. Here's how to do it

1: In src/common/gui/RuntimeFontLoader.h add another extern font called "aboutFont"
2: in src/common/gui/SurgeGUIEditor.cpp declare the font with the other fonts at the global level
3: in src/common/gui/SurgeGUIEditor.cpp when the fonts are setup with defaults, set a default 10pt for the about font
4: in each of src/(os)/RuntimeFontLoader.cpp setup the about font as 10 point lato

is one way to do it. Then use that font in CAboutBox rather than the kDefaultFont

The alternate approach, which is alternate, is to have RuntimeFontLoader have a method called "constructLatoFace(int size)" which you implement on each OS and so on and which falls back if Lato isn't available. That's probably more useful but a bigger refactor. I would happily sweep the 4 step method above and it is quicker and easier.

**Comment by itsmedavep** [comment]
There is a PR for this issue now:

#765
