### ISSUE TITLE
Fatal Error with missed symlinked fxp preset, causes the DAW to crash to desktop

### ISSUE THREAD

**Issue by parduz** [surge-synthesizer/surge#7547]
**Bug Description:**
In order to have all the patches organized by category, i've symlinked all the factory and 3rdparty pathces in the User patches
(so it contains folders like "Basses", "Pads", "keys" etc. with all the presets ssymlinked inside).
Due to an error in the batch file i've made to do that, one link is pointing to an inexistent file.

When Surge XT browses the user patches folder this results in a fatal error and it closes.
If it was the VST in my DAW (FLStudio) the DAW crashes to desktop.
If instead it was the SurgeXT standalone, it produces the attached screenshot.

* Version:
Plugin Type: VST3 64-bit

**Expected Behavior:**
I think it SurgeXT should handle the problem more gracefull. ignoring the "bad" patch (missing the file in this case) and not listing it, or maybe showing it in a different way in the patces broswer.
Anyway, it should not close and cause the DAW to crash.

**Screenshots:**
![image](https://github.com/surge-synthesizer/surge/assets/9556348/e68400a0-a5f8-47e9-ac16-6a73728e9f7d)

 - Windows 10
 - Host: Any, the standalone version also

**Comment by mkruselj** [comment]
I would advise not using symlinks for patch organization. You can also simply list all patches that are pads by clicking the magnifier button and typing CAT=pads.

**Comment by parduz** [comment]
>You can also simply list all patches that are pads by clicking the magnifier button and typing CAT=pads.
Yup, but then using the patches arrow will keep you inside the original author folder, while i wanted to parse the whole categories, no matther the authors

> I would advise not using symlinks for patch organization.
Why not?

**Comment by baconpaul** [comment]
The primary problem is that symlinks on windows still don’t quite act like normal files so when we traverse them the code throws an exception which is what you see here 

Fixing that is going to require work

so practically “don’t use symlinks because they crash our code right now”

**Comment by baconpaul** [comment]
But this is definitely one we should fix to be clear 

lemme see if Mac symlinks have the same problem if underliernis missing

**Comment by baconpaul** [comment]
![Screenshot 2024-03-02 at 3 12 29 PM](https://github.com/surge-synthesizer/surge/assets/13387561/80934fcd-6fce-48ba-bbeb-b64a0f50f075)

OK great I can get a similar error by making a link and deleting the underlies on mac. Let me see if I can find out what's doing that.

**Comment by baconpaul** [comment]
![Screenshot 2024-03-03 at 10 01 37 AM](https://github.com/surge-synthesizer/surge/assets/13387561/42d5ca88-20ac-4bbb-9aad-1ffef7fcd9cb)

OK I can get a similar error on my mac if a softlink points to a missing underlie. Lemme see what I can do

**Comment by baconpaul** [comment]
OK I have a fix for this condition on my mac. I don't have a windows box here to test it on but I'll merge it and then if you can test with a nightly to see if it solves your problem, I would appreciate it.

**Comment by baconpaul** [comment]
OK @parduz this is merged. If you can download a nightly in about an hour and confirm it fits the problem for you I would appreciate it.

**Comment by parduz** [comment]
Glad to to, but i'm not an expert.... where i will get the nightly build?

**Comment by baconpaul** [comment]
https://surge-synthesizer.github.io/nightly_XT/

it should be there in about an hour. It's building now.

**Comment by mkruselj** [comment]
That nightly does not contain the change Paul was talking about. It seems the latest nightlies are not yet pushed to the website.

**Comment by baconpaul** [comment]
Yeah the build is still running sorry - it got held up 

Will ping here when it is ready or keep checking that page if you want

**Comment by baconpaul** [comment]
Nightky is now up. Should in theory fix your issue. Please do let us know

**Comment by parduz** [comment]
It works!
The symlinked patches are still in the browser, but clicking on them does nothing.

**Comment by parduz** [comment]
Maybe a warning or ... something could be useful (other VST, when loaded in the DAW project, warns about the patch being invalid or missing with a sort of "modal box" you have to click on).

Thanks ;)

**Comment by baconpaul** [comment]
Yeah when I coded this morning I didn’t have a way to propagate that error but the commit after made it so I could. I’ll pop an error box before 1.3.2 

thanks for the report!

**Comment by baconpaul** [comment]
Oh and let’s leave this open until I get that on screen
