### ISSUE TITLE
Wrong patches menu items when a folder contains more than 256 patches

### ISSUE THREAD

**Issue by parduz** [surge-synthesizer/surge#7548]
**Bug Description:**
When a folder in the user patches contains more that 256 patches, the patch browser mangles the folder name, spitting it in multiple menu items, loosing charachters in the way
(sorry, hard to explain for my poor english)

This is a screenshot of my "Leads" patches folder:
![image](https://github.com/surge-synthesizer/surge/assets/9556348/722d2744-1bd3-48a8-98b0-534523d58ff3)
it shows 396 elements.

This is how it appears in SurgeXT:
![image](https://github.com/surge-synthesizer/surge/assets/9556348/16756372-2bf0-4bb2-9adf-476cc3f28162)
You can see there's a "_eads_" and a "_ads_" menu item, where there should be a "**_Leads_**" one.
(this also happens for "**_Basses_**" and "**_Pads_**", in this picture)

Going on "_eads_" it shows the first 256 patches, and in "_ads_" the remaining ones:
![image](https://github.com/surge-synthesizer/surge/assets/9556348/52e1b17b-17bb-423d-a157-912e841dbb44)
![image](https://github.com/surge-synthesizer/surge/assets/9556348/07ca4f63-86dc-4c5c-ae51-0fd09f1f02fb)

**Surge XT Version**
![image](https://github.com/surge-synthesizer/surge/assets/9556348/95b4ffc9-bf3f-4d75-a433-ae61f188fdd1)

**Comment by mkruselj** [comment]
Splitting the folder is intentional but what it was supposed to do is append incremented numbers. So you would get Leads 1, Leads 2 etc. Will fix.

**Comment by mkruselj** [comment]
Next nightly (in about 45 minutes) should have this fixed).
