### ISSUE TITLE
Ship a set of MPE Factory Patches with 1.6

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#755]
we should ship MPE factory patches with 1.6.

If you have a patch for MPE you would like to include, please either add it in a PR or if you want attach it to this issue in a zip file and we can pull it in.

**Comment by baconpaul** [comment]
@fredericcormier just FYI.

**Comment by fredericcormier** [comment]
Here we go, 3 patches.
[Patches.zip](https://github.com/surge-synthesizer/surge/files/2946339/Patches.zip)

**Comment by baconpaul** [comment]
Cool; I swept those in along with 2 of my own. If you come up with any others you would like to share, please do drop them here and we can sweep them in.

**Comment by fredericcormier** [comment]
3 more patches
[2019-03-14-patches.zip](https://github.com/surge-synthesizer/surge/files/2966294/2019-03-14-patches.zip)

**Comment by baconpaul** [comment]
Thanks! We just released beta 7 which had your prior 3 and 2 of mine in it; we can get these into the upcoming release.

Strongly recommend you upgrade to beta 7 by the way. Lots of good fixes.

**Comment by fredericcormier** [comment]
Downloaded Beta 7.

 It looks like the installer did not install the MPE folder in the patches_factory folder.

OSX 10.12.6

**Comment by baconpaul** [comment]
Oh no! I'll check. Thanks.

**Comment by baconpaul** [comment]
OK I just ran the installer and /Library/Application Support/Surge/patches_factory contains an MPE directory with 5 patches. I ran the surge and it said beta7 and I have the MPE patches.

One thought: do you have a ~/Library/Application Support/Surge directory? If so, surge will preferentially choose that. You can also do "menu/open factory data folder" and see where you get dropped in finder. If it is ~/Library as opposed to /Library you may have old runtime data and patches.

**Comment by fredericcormier** [comment]
Yes you’re right.

Surge was using the directory in the home application support folder .

Thanks

**Comment by baconpaul** [comment]
Great! (Also: Thanks for the patches).
