### ISSUE TITLE
Revisioned Pathes broswer

### ISSUE THREAD

**Issue by parduz** [surge-synthesizer/surge#7550]
**Is your feature request related to a problem? Please describe!**
I find the "menu based" patches browser unconfortable. His efficiency is depending on how many patches it have to shows, the screen size (as the menus floats around "out" of the plugin windows) and also with limited "filtering" capabilities.

**Describe the solution you'd like:**
Since one picture is worting 1000 words (and my english is bad) here's how I would envision it:

![image](https://github.com/surge-synthesizer/surge/assets/9556348/530ef79b-55b2-4f35-a14a-f5155b48a1a7)

Nothing new, really, other plugins do the browsing in a similar way.
The "buttons" on the top allows to pick what you want, the leftmost column will be useful just for the 3rd party, then all the available categories (depending on what's picked on the leftmost column), then all the patches in the categories, with a scrollbar to go down.

As SurgeXT already indexes the patches (for the Search feature) i think that a browser like that could be feasible.

**Comment by mkruselj** [comment]
We already have a plan for a tag-based patch browser, but it is not going to happen this year, it is planned for Surge XT2.

https://github.com/surge-synthesizer/surge/issues/2359

I will close this issue as duplicate.
