### ISSUE TITLE
Mono, Poly mode for LFO

### ISSUE THREAD

**Issue by uairyu** [surge-synthesizer/surge#7561]
Hope to add two new buttons, mono mode and poly mode for LFO. Some interesting rhythms can be performed in both modes when pressing or releasing multi keys

**Comment by mkruselj** [comment]
This is already possible, use scene LFO for monophonic and voice LFOs for polyphonic behavior. Even in voice LFOs you can set trigger mode to Freerun and then it's monophonic.

**Comment by uairyu** [comment]
> This is already possible, use scene LFO for monophonic and voice LFOs for polyphonic behavior. Even in voice LFOs you can set trigger mode to Freerun and then it's monophonic.

Thanks for the suggestion, and I check the User Manual again. Maybe the problem I found is the "Keytrigger" mode, I confused Keytrigger mode and Retrigger mode. Keytrigger mode is quite different form Retrigger mode, the former is "when using a scene LFO, the first voice sets the LFO’s position, then the other ones will follow it", but in Retrigger mode, however, the newest key always updates a new LFO's position.
Can Surge XT add "Retrigger mode for LFO" feature?

**Comment by baconpaul** [comment]
![Screenshot 2024-03-09 at 8 53 43 AM](https://github.com/surge-synthesizer/surge/assets/13387561/f9969ef0-0863-4902-b8a0-0fe56c68181d)

That's exactly what this screen element does.

I think you were consulting the oscillator section of the manual perhaps? Take an SLFO, set it to freerun, and it will be song locked monophonic. Take an SLFO, set it to key trigger and it will be a first-key-in-the-door monophonic LFO

**Comment by uairyu** [comment]
> ![Screenshot 2024-03-09 at 8 53 43 AM](https://private-user-images.githubusercontent.com/13387561/311441921-f9969ef0-0863-4902-b8a0-0fe56c68181d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5OTUyNjgsIm5iZiI6MTcwOTk5NDk2OCwicGF0aCI6Ii8xMzM4NzU2MS8zMTE0NDE5MjEtZjk5NjllZjAtMDg2My00OTAyLWI4YTAtMGZlNTZjNjgxODFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDE0MzYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjZjI0NDQ3M2I1Y2YyZWJhZWU0YzU4MDU3NmU2YWM5NjQ3MWFhZTkzZjcwZGMzZmYyNTBiYzhkZDUxY2Q1NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gvR3Z9pU3w0bll3_JXnl_CxVI2uag3n4S0R_YSua6EQ)
> 
> That's exactly what this screen element does.
> 
> I think you were consulting the oscillator section of the manual perhaps? Take an SLFO, set it to freerun, and it will be song locked monophonic. Take an SLFO, set it to key trigger and it will be a first-key-in-the-door monophonic LFO

I think I already know the difference between the "Keytrigger" and "Retrigger". But what I need is "Retrigger". 
For example, in poly voices, I need a 1/4 note mono LFO, then I will press 3 keys(all will not be released) in sequence, each key will have an 8th note interval. Every key pressed, will trigger a new LFO immediately, and the past key's LFO(If have) will be disabled. In this case, there is always only one LFO active.

**Comment by mkruselj** [comment]
Well, in voice LFOs this is not possible because there is literally one LFO per every voice played, they just get synced in phase if in Freerun mode. Keytrigger restarts from start on every new played note in voice LFOs. This is "poly". If you want it "mono", then use Freerun mode.

**Comment by mkruselj** [comment]
After rereading what you're saying, are you perhaps talking about this?

https://github.com/surge-synthesizer/surge/issues/2462

**Comment by uairyu** [comment]
> After rereading what you're saying, are you perhaps talking about this?
> 
> #2462

Yes, it's quite similar to this issue. In other synthesizer this feature called "Retrigger", The most important point of this feature is "Retriggered by last note", instead of the first note, because maybe the first part of some chords‘ notes will show at the end of previous bar, then the final note shows at the head of next bar. If use "Keytrigger", it will break the rhythm!
I've search the key word "Retrigger" in issues, but there doesn't seem to be an issue that exactly meets what I want... Maybe I should change this issue's title to "Retrigger mode for LFO"? I think if the LFO in Surge Xt owns both "Retrigger" and "Keytrigger", it will become more powerful

**Comment by baconpaul** [comment]
Ahh I see so basically a mode where slfo restart on any keystroke not the first keystroke

**Comment by mkruselj** [comment]
> > After rereading what you're saying, are you perhaps talking about this?
> > #2462
> 
> Yes, it's quite similar to this issue. In other synthesizer this feature called "Retrigger", The most important point of this feature is "Retriggered by last note", instead of the first note, because maybe the first part of some chords‘ notes will show at the end of previous bar, then the final note shows at the head of next bar. If use "Keytrigger", it will break the rhythm! I've search the key word "Retrigger" in issues, but there doesn't seem to be an issue that exactly meets what I want... Maybe I should change this issue's title to "Retrigger mode for LFO"? I think if the LFO in Surge Xt owns both "Retrigger" and "Keytrigger", it will become more powerful

You don't have to rename this issue, I've closed it since it's basically a duplicate of #2462 after closer inspection.

I think having both "retrigger" and "keytrigger" will be confusing to many, so it's better to pick one. And retrigger is definitely more often found, and so that's how it's going to be.

This new mode you request would not apply to voice LFOs, it would only apply to scene LFOs.


But also, the problem here is that LFOs don't really know about "chords". To me it sounds like you also want to input quantize the LFO starting its oscillation to the grid...

**Comment by uairyu** [comment]
> Ahh I see so basically a mode where slfo restart on any keystroke not the first keystroke

Yeah, so basically a mode, that's why I felt strange the first time I used "Keytrigger", and everything went diffrent from my past experience

**Comment by uairyu** [comment]
> > > After rereading what you're saying, are you perhaps talking about this?
> > > #2462
> > 
> > 
> > Yes, it's quite similar to this issue. In other synthesizer this feature called "Retrigger", The most important point of this feature is "Retriggered by last note", instead of the first note, because maybe the first part of some chords‘ notes will show at the end of previous bar, then the final note shows at the head of next bar. If use "Keytrigger", it will break the rhythm! I've search the key word "Retrigger" in issues, but there doesn't seem to be an issue that exactly meets what I want... Maybe I should change this issue's title to "Retrigger mode for LFO"? I think if the LFO in Surge Xt owns both "Retrigger" and "Keytrigger", it will become more powerful
> 
> You don't have to rename this issue, I've closed it since it's basically a duplicate of #2462 after closer inspection.
> 
> I think having both "retrigger" and "keytrigger" will be confusing to many, so it's better to pick one. And retrigger is definitely more often found, and so that's how it's going to be.
> 
> This new mode you request would not apply to voice LFOs, it would only apply to scene LFOs.
> 
> But also, the problem here is that LFOs don't really know about "chords". To me it sounds like you also want to input quantize the LFO starting its oscillation to the grid...

I think keeping both "Retrigger" and "Keytrigger", this can be a great feature of this software. #2462 is a 4 years issue, and added to "Surge XT 2.0" milestone, It means "Keytrigger" has been at least part of LFO for the past 4 years or even longer. If just keep one in future, the users who are already accustomed to using it will feel regretful , and the project which had used "Keytrigger", but found no "Keytrigger" in new version, then a compatibility problem occurred...
User Manual has explained a lot, and I think user will know the difference between two. I hope both "Retrigger" and "Keytrigger" could be kept in future
