### ISSUE TITLE
Release as gate 

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#7563]
Basically 

let’s add a deform mode to the aeg and feg envelope release where instead of fading to 0 they just hard gate at level to zero 

this would allow basically attack 0 sustain 1 release deform envelop to just gate a voice and other modulators could modify the level as you saw fit

**Comment by mkruselj** [comment]
I don't think this is needed for FEG, since we can just use an LFO EG directly to filter cutoff. Only AEG matters for this.

**Comment by baconpaul** [comment]
Yeah I agree but the types are super symmetric so i wanted to see where the if had to go. If the code isn't super ugly do AEG only. Otherwise code both and just suppress the menu item on FEG.
