### ISSUE TITLE
Skinning or Support for Very Small Screens

### ISSUE THREAD

**Issue by RK11111111111** [surge-synthesizer/surge#7572]
My goal is to run Surge on a Raspberry Pi as a dedicated synth device, it will just run Surge the only input is a small touchscreen and a midi keyboard.

I have Surge up and running with jalv.gtk and jack.  However, my screen is 800/400.  Just too small to show some of the features, like effects and LFO.  With a touchscreen there is no way to scale or move the screen.  I can use a keyboard, but that isn't part of the goal.  Make a standalone hardware synth based on surge.

I tried to scale the screen down, via the menu button, but it is only supported at 100%.

I did something similar with Mixxx a cdj software.  I wrote a custom skin.  Does Surge support some skinning functionality.  A tab based interface would be great!  For example moving effects into a tab group, modulators etc.  

In the end I want it to be mostly controlled via the keyboard and midi.

**Comment by mkruselj** [comment]
Yes we do support skinning. Please check the Skins submenu of the main Menu in bottom right. Tutorials are there and Figma templates you can get from pinned posts on our Discord in #ui-design-etc channel.

**Comment by baconpaul** [comment]
On linux the minimum zoom is set at 100, due to #628

I'm not sure if that still applies post juce. @RK11111111111 you can figure that out by editing SurgeGUIEditor.cpp and searching for "minimumZoom = 100" and change that to 20 and then rebuild and then do the type.

**Comment by baconpaul** [comment]
Oh ignore that. That's just code still fluffing around because of the VSTGui port.

**Comment by mkruselj** [comment]
Gonna remove that code in a PR now.

**Comment by RK11111111111** [comment]
Nice! I will keep an eye out for that build.  So exciting.

**Comment by mkruselj** [comment]
Oh you don't need to wait for that build! It's just stale code that doesn't do anything anymore. You can reduce Surge zoom level down to 25% as it stands, today. Right now. Just click the Zoom button and use **Set default zoom level to...** option.

**Comment by RK11111111111** [comment]
It said the smallest zoom on my platform is 100%...  sorry....

**Comment by RK11111111111** [comment]
Maybe I'll try a different build.

**Comment by baconpaul** [comment]
Ahh we need to build it on linux and find that check. We don’t need it any more.

**Comment by RK11111111111** [comment]
I figured out how to install the nightly --fix-install... Zoom is working after a fashion, though it still has some issues rendering/resizing sometimes the bottom LFO block is hidden when I do full screen.  Probably good enough.  I'll play with it more.  Thanks!

**Comment by mkruselj** [comment]
Well that message is definitely not there in the latest nightly anymore. But even then it couldn't be reached since showMinimumZoomError() method was never called. You are likely using an older version of Surge, then?

**Comment by RK11111111111** [comment]
Yes, I was using the one from kxstudios, the nightly build didn't install immeadiatly (fix-depedencies.)

I noticed that surge-xt doesn't seem to get the midi PC messages though.

**Comment by mkruselj** [comment]
There is no support for PC messages in VST3 because of reasons... CLAP version does support them!

**Comment by RK11111111111** [comment]
Interesting, I thought I was loading the LV2 version with jalv.

**Comment by mkruselj** [comment]
I wouldn't know about how it is with our LV2. It does have some issues so we recommend everyone to use VST3 or CLAP instead.

**Comment by baconpaul** [comment]
the LV2 should get program changes, but with 1.3 program changes do something different. They scan your midi folder as opposed to picking a 'random' patch (which is basically what they did pre 1.3).

**Comment by RK11111111111** [comment]
> I wouldn't know about how it is with our LV2. It does have some issues so we recommend everyone to use VST3 or CLAP instead.

I noticed it crashes with some patches something about lua.

**Comment by baconpaul** [comment]
did you build with surge skip lua true or use a binary distribution from someone other than us?

**Comment by RK11111111111** [comment]
> did you build with surge skip lua true or use a binary distribution from someone other than us?

It happened with the nightly build I downloaded last night.  The release build I installed today, doesn't appear to have this problem.
