### ISSUE TITLE
Surge XT Standalone Window Inside of a Window

### ISSUE THREAD

**Issue by RK11111111111** [surge-synthesizer/surge#7577]
Continuing on my theme of creating a Rasperry Pi device that boots directly to Surge.  I have piggy backed on the Mixxx-pi-gen project that has a similar idea for CDJ controllers.  I have the release version of Surge standalone installed.  It works fabulous.  It's easy to map the Audio and Midi drivers.  Remembers my settings and everything.

One issue is with the windows.  It starts up with a window inside of a window.  One is the wayland Raspberry pi window, but then there is the Surge XT window with the Surge Icon.

I don't really want either of them, at least not every time.  The options button in the Surge XT bar is nice that is where all the midi audio stuff is, but there is already an options button on the skin.  

Also, oddly enough the Audio Midi settings window has no close button, though I can press escape to close it.  In the long run I won't be using this with a PC keyboard.
![IMG_20240315_145707096](https://github.com/surge-synthesizer/surge/assets/365328/f3c97098-9a82-4ae5-8718-56fdf267e93e)

**Comment by baconpaul** [comment]
Nice

surge is an x11 not Wayland app. Changing that is first order impossible 

 Juce provides the standalone wrapper with a window. You could write an alternate standalone which didn’t use a window

we do have a full screen mode but it has never worked quite properly so it is disabled by default. If you search for full screen in the src/surge-xt directory you can find out the commented first attempt at this.

**Comment by mkruselj** [comment]
Also,  these sorts of discussions are better done on Discord. Github should be for actual issues. For help, Discord is way better. :)

**Comment by RK11111111111** [comment]
Sway worked out pretty well surprisingly well.  I think sway is geared towards these full screen dedicated apps. 
 Still some rough edges, but I was able to make it default to full screen in sway in a robust way.  Then used lisgd, to map a gesture for closing the top window.  The aspect is a little weird.

Still, somethings like right clicks and what not, but for live usage, I wasn't planning on diving into the menus anyway, mostly using prebuilt patches.  As far as PC messages, I think the touch screen is better for navigating the patch menu even than the mouse.  Back it up, stick a fork in it, it is done.
