### ISSUE TITLE
Random note triggering

### ISSUE THREAD

**Issue by PapaDumHun** [surge-synthesizer/surge#7582]
**Bug Description:**
Since I updated my Surge XT, when i play a C or sometimes other note, it triggers a second. If i hit stop on my transport it goes away, but as soon as I move a slider in Surge, it happens again. 

**Surge XT Version**
Surge XT 1.3.1.4b53827

* Version:
* Plugin Type:, VST3
* Bitness:  64-bit

**Reproduction Steps:**
1. Go to Surge
2. Click on note using qwerty keyboard
3. move slider or knob
4. play note and it triggers another

**Expected Behavior:**
It didn't use to happen as far as I remember in the previous version

**Screenshots:**

![Screenshot (547)](https://github.com/surge-synthesizer/surge/assets/163860364/85127a62-7138-414f-8d91-99db473f8e5d)
![Screenshot (548)](https://github.com/surge-synthesizer/surge/assets/163860364/ad04136d-f5e3-4375-aab4-dc63231c33e7)

**Computer Information (please complete the following!):**
 - OS: Windows 8
 - Host: Renoise
 - Version: 3.4.3 latest

**Additional Information:**

**Comment by Andreya-Autumn** [comment]
Hello, and thanks for reporting! 

I can't reproduce this here, but then I'm on Mac in Reaper. Perhaps @mkruselj could give this a look as time permits?

**Comment by PapaDumHun** [comment]
> I wonder if renoise is somehow getting the keyboard press twice? The qwerty + virtual keyboard + 2 keyboards on display made me think. I wonder if you turned off the surge virtual keyboard if the problem would resolve?

THATS IT!!!!!
Good thinking.  I didn't even realize you could turn off the Surge Keyboard until you mentioned it. 
Weird that it didn't happen until I updated for some odd reason.  Plus it frees up screen real estate, so two birds with one simple uncheck click. 
Thanks loads, it was driving me bonkers.  
PS...I love bacon..hehe

**Comment by PapaDumHun** [comment]
Fair play.  Keep up the good work!
