### ISSUE TITLE
Remote wavetable selection

### ISSUE THREAD

**Issue by michaelohagan912** [surge-synthesizer/surge#759]
Please make wavetables selectable by both midi and automation for use with devices like push or automap enabled controllers.

**Comment by baconpaul** [comment]
Oh that's a good idea, but it is a bit painful for a couple of reasons, including wavetables aren't really parameters (the file gets loaded as binary onto the patch) so aren't exposed in a normal way.

We're really trying hard to not add parameters for 1.6.0 so I'm going to tag this as a 1.6.n at least thing.

Thanks for the suggestion!

**Comment by mkruselj** [comment]
Yeah this is not really that easy to do because as soon as you add new wavetables, the list order gets messed up and any MIDI messages you used to select your wavetable is suddenly in great risk of choosing all the wrong wavetables.

I vote not to do this.

**Comment by michaelohagan912** [comment]
It's up to the end user to create folders and categorize their wavetables according to their own liking, I would actually update this feature request that I think it should be 2 midi cc #'s, one to select banks/catagories/folders of wavetables and a second midi CC to select wavetables from within that bank.

**Comment by mkruselj** [comment]
@baconpaul My proposed solution for this issue:

1. Make prev-next wavetable buttons MIDI learnable. Guess they will need to be proper parameters for that.
2. Make right-click on prev-next wavetable buttons jump to prev-next folder. Add a separate MIDI learn for that (I guess another option in the context menu - MIDI learn file jog vs MIDI learn folder jog).
3. Close this issue?

**Comment by mkruselj** [comment]
Another option to solve this issue is to expose wavetable selection to OSC (#2355).

**Comment by mkruselj** [comment]
We do have loading wavetables via OSC now. Closing this issue.
