### ISSUE TITLE
cant see 'factory patches' bitwig clap

### ISSUE THREAD

**Issue by RustoMCSpit** [surge-synthesizer/surge#7590]
**Bug Description:**
no factory patches can be seen with the .clap on bitwig .

**Surge XT Version**
1.2.3.bb8dd2b

* Version:
* clap
* 64
* linux mint

**Reproduction Steps:**
1. click on patch browser
2. see no factory patches

**Expected Behavior:**
visible factory patches

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following!):**
 - OS: linux mint
 - Host: [bitwig
 - Version: 5.1

**Comment by mkruselj** [comment]
In Surge's patch browser or Bitwig's?

**Comment by RustoMCSpit** [comment]
> In Surge's patch browser or Bitwig's?

surges

**Comment by baconpaul** [comment]
So

1. Are you using the flatpak or deb surge? and bitwig?
2. If you re using the flatpak what does the about screen say? A screenshot of the surge about screen will show where it looks for patches. Does that directory exist.
3. If you upgrade to 1.3.1 you will get clap preset support which will be generally better in bitwig anyway. but if surge sees no patches bitwig wont either

My guess is you are using the flatpak version and the paths are not resolved properly on your system.

**Comment by RustoMCSpit** [comment]
1) surge is a .clap, i dont know if thats flatpak or deb. bitwig is .deb.

2) not using flatpak. i chrcked and the directory isnt there however. where do i install JUST the patches, wavetables, etc.

3) upgrade what to 1.3.1? i installed the latest surge

**Comment by baconpaul** [comment]
the latest surge is 1.3.1 not 1.2.3. 

How did you install it? It sounds like your install process just didn't install the wavetables and patches.

**Comment by RustoMCSpit** [comment]
> the latest surge is 1.3.1 not 1.2.3.
> 
> How did you install it? It sounds like your install process just didn't install the wavetables and patches.

i downloadef the most recent release surge-xt-linux-1.3.1-pluginsonly.tar.gz and extracted Surge XT.clap and put it in my .clap directory

**Comment by RustoMCSpit** [comment]
whats the rpm or obs build?

**Comment by baconpaul** [comment]
Rpm is the fedora equivalent of a deb file. Obs is open build service, a multi platform build linked from our install page for various non Apple unixes.

**Comment by RustoMCSpit** [comment]
related to https://github.com/surge-synthesizer/surge/issues/7607
