### ISSUE TITLE
audio input only mode

### ISSUE THREAD

**Issue by RustoMCSpit** [surge-synthesizer/surge#7591]
**Describe the solution you'd like:**
a mode where all presets are automatically set to audio input as the oscillator and latch as the play mode.

**Describe alternatives you've considered:**
having a way to right click a parameter and have it "remain static" (as in it wont change if the patch is changed) until surge is either closed or it is turned back to dynamic

**Additional context:**
using surge as a vocal effects synth lol

**Comment by Andreya-Autumn** [comment]
Hello! 

Sorry to say, I don't think we'll do this. Whether a given patch makes any sense at all as a vocal fx patch is a total toss-up. Percussion patches would not work at all for example. I'd recommend finding some good candidates to adjust and saving to a "vocal fx" user category. 

We do have a standing feature request for parameter locking, that's something that could happen! Meanwhile, I'll close this if you don't mind.

**Comment by RustoMCSpit** [comment]
> Whether a given patch makes any sense at all as a vocal fx patch is a total toss-up.

re-open and rename 'fx metadata' 

in this, we are able to add metadata for whether it can work as vocal / guitar / bass / etc. fx and be able to filter that in the patch browser

**Comment by RustoMCSpit** [comment]
> We do have a standing feature request for parameter locking, that's something that could happen! Meanwhile, I'll close this if you don't mind.

where?

**Comment by baconpaul** [comment]
Tagging is covered here https://github.com/surge-synthesizer/surge/issues/2359

Param lock here https://github.com/surge-synthesizer/surge/issues/7380
