### ISSUE TITLE
Should OSC messages be sent when MIDI input is received?

### ISSUE THREAD

**Issue by botoxparty** [surge-synthesizer/surge#7592]
Hey,

I've observed that OSC messages are only output if the controls are changed with the UI. When receiving MIDI input, the updates don't appear to be sent over OSC.

Is that the expected behaviour?

In my use case it would even be cool if it also outputted incoming OSC messages.

e.g. Controller 1 sends OSC message to Surge XT.
Surge XT sends an update to Controller 2 that the parameter was changed.

**Comment by baconpaul** [comment]
Well since you didn’t expect it it’s clearly not expected! But we definitely didn’t think of this case 

so you set up a midi learn control basically and want that to send an osc message? That means the midi automation path needs to fire the parameter listener on the right thread. Doable but just want to make sure that’s the case you are in

also tagging @pkstone who has written most of the osc code.

the code is around here Phil https://github.com/surge-synthesizer/surge/blob/2834ca4c4fb270b1987bc0de1c47b9c0830563e6/src/common/SurgeSynthesizer.cpp#L2337

**Comment by botoxparty** [comment]
Yeah for claritication..

If the Pitch in OSC1 of Scene A has a MIDI CC assigned to it, when it
received changes then it should output them to "/param/a/osc/1/pitch"

**Comment by pkstone** [comment]
I think I get what you're asking for, but I can't promise anything on it for the near future. I would like to make the 'echoing' part of OSC (i.e., outputting Surge state changes to OSC) more consistent and comprehensive, but it's a big job. Things are a bit all over the place right now. For instance, modulation mapping changes always echo, even when changed by incoming OSC messages (this is a side-effect of using an already existing modulation change listenener). Nothing else does that though, yet.

**Comment by pkstone** [comment]
There also starts to arise an issue of how much data pouring out of OSC is acceptable for a given user-case. Do we have to start adding on/off options for it so a perhaps slow client on the other end of the pipe is not overwhelmed?

**Comment by mkruselj** [comment]
My thinking here is: how does host automation behave when receiving MIDI to set MIDI learned parameters? OSC should behave the same.

**Comment by pkstone** [comment]
@botoxparty  I'm not meaning to be discouraging here, this is a good ask, and is something I really want to improve in the future. But it may be a while!  :-)

**Comment by pkstone** [comment]
I've taken a shot at this, but have run into some basic architectural problems; 'learned' MIDI is processed in SurgeSynthesizer, which cannot directly echo data to OSC out (OSC out processing is managed mostly in SurgeSynthProcessor, which is not visible to SurgeSynthesizer).

**Comment by pkstone** [comment]
I'm not giving up yet; when Paul gets back from vacation, we'll see if we can't figure something out.
