### ISSUE TITLE
Mod List Unipolar Values

### ISSUE THREAD

**Issue by Jxp955** [surge-synthesizer/surge#7597]
**Bug Description:**
Using Velocity (or any Unipolar LFO) to modulate any of the Envelope parameters, 
or Filter Cutoff, seems to lead to incorrect values in the mod list.
Bipolar modulations seem to always work.

**Surge XT Version**
Surge XT 1.3.1.4b53827

* Version: 2024-02-06 @ 15:34:52 on 'fv-az527-661/pipeline' with 'MSVC-19.37.32826.1' using JUCE 7.0.5
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Click Velocity modulator, or a LFO and set to Unipolar.
2. When green, change some of the EG or filter cutoff values.
3. When done click on the mod List.
4. The numbers don't seem to add up.

**Expected Behavior:**
The math on bipolar LFO's seems to be fine.
The actual modulation may work, it could be just the numbers.

**Screenshots:**
![image](https://github.com/surge-synthesizer/surge/assets/55408938/7fa721bf-8a35-40c8-844c-3faca8317890)
Notice on both Attacks the 0 plus a value still equals 0.
![image](https://github.com/surge-synthesizer/surge/assets/55408938/e44bb2e2-5b9d-4991-aec8-c9b659b9ddb9)

**Computer Information (please complete the following!):**
 - OS: Windows 10
 - Host: Reaper
 - Version: 7.12

**Additional Information:**

**Comment by baconpaul** [comment]
Oooh thanks.

**Comment by baconpaul** [comment]
Right theres two problems here

1. The envelope time modulation depths are shown in seconds not milliseconds
2. The 'target endpoint' indeed shows incorrectly in unipolar mod mode

Here's a clear example. Let me see if i can fix it today.
 
![Screenshot 2024-04-19 at 1 23 37 PM](https://github.com/surge-synthesizer/surge/assets/13387561/b0b93151-dc07-4985-b33f-9f04fa07f677)
