### ISSUE TITLE
Surge-AU: 64-bit AudioUnit not recognised with Renoise 64-bit v3.1.1

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#76]
Interestingly, the 64-bit macOS AudioUnit which can be built by following the PR #69 does not show with Renoise 64Bit v3.1.1.. I wonder what's up with that.
Any ideas?

**Comment by esaruoho** [comment]
Yep, tried the wipe cache with Renoise but still didn't show.

**Comment by baconpaul** [comment]
Still a problem at head, @esaruoho?

I am not sure if this is a surge problem or a renoise problem. Any diagnostics at all?

**Comment by esaruoho** [comment]
@baconpaul i will ask on the renoise forums after baking a new audiounit.. if i can get it properly packaged with the resources/data -folder..

**Comment by esaruoho** [comment]
yeah i think it's a renoise problem, maybe. can get a 64bit VST detected with Renoise, but 64bit AU just won't get detected. immensely annoying.

**Comment by baconpaul** [comment]
Should we close this issue then? The internet seems full of folks complaining about AU Renoise compatibility but unless there’s a dev here who uses it who can fix it, I’m not sure what to do, especially since the VST works.

**Comment by esaruoho** [comment]
i'll close this since we can't do jack about Renoise + AU issues.
