### ISSUE TITLE
offline documentation

### ISSUE THREAD

**Issue by RustoMCSpit** [surge-synthesizer/surge#7618]
**Is your feature request related to a problem? Please describe!**
i shouldnt have to be connected to the internet to right click something and see what it does

**Describe the solution you'd like:**
a downloaded folder of the contents of the online docs, which my computer then opens via a browser to view the local files

**Describe alternatives you've considered:**
something like how bitwig does documentation (look it up, i cant explain it well. it's like an interactive anatomy of something, labelled and all. it's called "show item help")

**Additional context:**
![image](https://github.com/surge-synthesizer/surge/assets/134429563/8562f55c-f9ea-4217-a455-97e8a05cd581)
![image](https://github.com/surge-synthesizer/surge/assets/134429563/56f4645e-5461-4c08-8ebd-60e620587442)

**Comment by mkruselj** [comment]
This was already discussed before and we decided against doing that. Closing the issue.

**Comment by mthierman** [comment]
Hey, thanks for the feature request, I agree. I made the case but looks like we will keep the software links online so that it can be updated in between releases.

I am looking into making the manual an installable PWA or perhaps at least bundling up the manual and publishing an offline version on the website repo.

**Comment by RustoMCSpit** [comment]
whats a pwa

**Comment by RustoMCSpit** [comment]
> This was already discussed before and we decided against doing that (#4961). Closing the issue.

if i changed the title to 'have bitwig styled info boxes' can we re-open

**Comment by baconpaul** [comment]
We thought about tooltips for each control a couple of times with help text. I don't think anyone on the team is going to invest in writing them which is the hard part.  They are separate from the manual and need to be maintained.

PWA is a progressive web app. Kinda a local cache of a website kinda.

**Comment by mthierman** [comment]
I tried to generate an embedded version of the manual, our website builder Astro does not do this out of the box. There is a [plugin](https://www.npmjs.com/package/astro-relative-links) that may work once I finish some other work on the table of contents. So not impossible, but it will have to wait.

We do publish a [PDF](https://github.com/surge-synthesizer/surge-synthesizer.github.io/releases/tag/surge-xt-manual) version of the manual you can use offline. If I get an html build working I will publish it alongside that. I don't think it will ever be included with the software, though.

**Comment by mkruselj** [comment]
> > This was already discussed before and we decided against doing that (#4961). Closing the issue.
> 
> if i changed the title to 'have bitwig styled info boxes' can we re-open

No because we will not change how our in app help system works since it was proven to be helpful enough for many people so far.

**Comment by baconpaul** [comment]
Also the only way to do the bitwig style thing is to maintain the entire manual in two places and keep it updated for all versions going forward. So far - unlike the great team who does the manual - no volunteer for that has shown up. So we chose a direct link approach and one item to maintain.
