### ISSUE TITLE
gui keyboard

### ISSUE THREAD

**Issue by RustoMCSpit** [surge-synthesizer/surge#7619]
**Is your feature request related to a problem? Please describe!**
id like to see on surge what notes im inputting when i use my computer keyboard as a midi instrument. that can be done with a piano display

**Describe the solution you'd like:**
a piano display that shows inputted notes, and can be interacted with by pressing a note with a mouse

**Additional context:**
a really crappy looking one is below
![image](https://github.com/surge-synthesizer/surge/assets/134429563/1aa68510-52c6-4df0-828c-c13ae5bbb749)

**Comment by mkruselj** [comment]
Please read the manual, Surge already has a virtual keyboard built in...
