### ISSUE TITLE
Init missing for Most Fx presets.. 

### ISSUE THREAD

**Issue by sense-amr** [surge-synthesizer/surge#762]
it's strange to have an Init state for only a FEW of the fx in the fx section .. i propose an init "preset" for each FX type ..

**Comment by baconpaul** [comment]
Ooh thats pretty easy - we just need the right params for init as a line in configuration.xml

Do you happen to have good settings for init for each effect type?

**Comment by sense-amr** [comment]
Well no .. because i cant save them and send them to you anyway can i ?:)
i mean i could make settings with NO parameters being used and save them as Patches? ..

**Comment by baconpaul** [comment]
Yeah ugh right they aren’t saveable. Got it.

**Comment by sense-amr** [comment]
not yet they arent :)

**Comment by baconpaul** [comment]
Yeah ha! I know I know....

**Comment by baconpaul** [comment]
[InitFX.zip](https://github.com/surge-synthesizer/surge/files/2953269/InitFX.zip)

@sense-amr so this init has each of the FX without an init set up in the chain and disabled

If you can edit that patch and re-attach it here I can transfer the presets to config.xml

**Comment by sense-amr** [comment]
hmm let me look into this

**Comment by sense-amr** [comment]
[FX inits.zip](https://github.com/surge-synthesizer/surge/files/2955365/FX.inits.zip)
better?
also tried to keep them all the same level when in "init" state

**Comment by baconpaul** [comment]
Thanks. I’ll try and find time to look and get this into beta 7!
