### ISSUE TITLE
How does audio input work?

### ISSUE THREAD

**Issue by RustoMCSpit** [surge-synthesizer/surge#7623]
hi, the wiki isnt super clear and i cant find any online YT videos. how does the audio input mode work? none of the presets with audio input in the title produce an output sound? im very confused and dont really know what to ask. im trying to run my guitar through the synth but ive been left scratching my head for an hour. sorry for being so vague but idk where to start

**Comment by baconpaul** [comment]
In your daw connect the input you want to the side chain input and then put surge in latch mode 

How you do that depends a greatly on your daw 

if you are using the standalone choose a stereo input in the options drop down and do same 

surge still gates on voice so you need latch mode 

https://youtu.be/sQyxk-LhV3s?si=Mrsi5bjO32GrprKx

There’s a video showing it in logic pro

**Comment by mkruselj** [comment]
Github is not supposed to be used for requesting help on how to use Surge. Please connect with us on Discord in the future in case you need help and manual or wiki are somehow not helping. Thanks for understanding!

**Comment by RustoMCSpit** [comment]
> In your daw connect the input you want to the side chain input and then put surge in latch mode
> 
> How you do that depends a greatly on your daw
> 
> if you are using the standalone choose a stereo input in the options drop down and do same
> 
> surge still gates on voice so you need latch mode
> 
> https://youtu.be/sQyxk-LhV3s?si=Mrsi5bjO32GrprKx
> 
> There’s a video showing it in logic pro

this isnt working for me, im using bitwig and followed your tutorial but it still wont produce sound

**Comment by RustoMCSpit** [comment]
are you familiar with bitwig and can i video call you via discord or something?

**Comment by RustoMCSpit** [comment]
whenever i turn on latch it just holds the last midi note forever and whenever i turn on vocoder it just mutes entirely

**Comment by RustoMCSpit** [comment]
i got it working but the problem is that this doesnt run my audio as an input but rather relies on the midi to "sample" it? i want to run my guitar through it like an effect pedal. also i think it's bugged on bitwig

**Comment by RustoMCSpit** [comment]
like this audio input plugin https://www.youtube.com/watch?v=Nn7vW8qURF8

**Comment by baconpaul** [comment]
Just pull your audio in, latch it with audio in oscillators, and it will route. Bitwig works fine. Make sure your guitar signal comes into a track and attach that as the side chain to your surge 

but really GitHub is for dev things. For user support can you please join the help channel of our discord? There’s lots of bitwig users there
