### ISSUE TITLE
discord links to wrong place in readme

### ISSUE THREAD

**Issue by RustoMCSpit** [surge-synthesizer/surge#7624]
https://raw.githubusercontent.com/surge-synthesizer/surge-synthesizer.github.io/master/_includes/discord_invite_link

thats what i get when i click it

**Comment by Andreya-Autumn** [comment]
Confirmed, thanks for reporting. Will check it out. Meanwhile, the link on our website does work: https://surge-synthesizer.github.io/feedback/

**Comment by RustoMCSpit** [comment]
ewhy was this closed

**Comment by baconpaul** [comment]
dunno. it didn't get fixed yet!
