### ISSUE TITLE
Some patches don't play on raspberry pi (3)

### ISSUE THREAD

**Issue by grbfst** [surge-synthesizer/surge#7625]
Hi, As mentioned before I'm building a touch instrument running on a Raspberry (3 or 4).
All is running smoothly now except for some patches who don't play. I.e. the "Grand Piano" by John Valentine only plays for one second and then stops.
Is there a complexity to some patches a Raspberry can't handle?
"Axel's Sharp Atmosphere" doesn't give any sound at all. Not sure where to look for.

**Comment by baconpaul** [comment]
Yeah for a pi4 you need to curate features and patches - stuff in factory as opposed to third party is more likely to work
