### ISSUE TITLE
Using latch mode causes hanging note in mono mode when playing via VKB

### ISSUE THREAD

**Issue by gitsmol** [surge-synthesizer/surge#7628]
**Bug Description:**
When playing a note in latch mode and then switching to mono mode, that note keeps playing after triggering any note in mono mode.

**Surge XT Version**
It's present in (at least) 1.3.1 and on.

**Reproduction Steps:**
1. Switch to latch mode
2. Hear note playing
3. Switch to mono mode: silence.
4. Play any note
5. The note latch mode note starts playing again.
6. Playing any other note 'overrides' the latch mode note, but it returns after.

**Expected Behavior:**
Mono mode does not play this 'hanging' latch mode note.

**Computer Information (please complete the following!):**
MacOS 13.6 Ventura
64-bit, Surge XT standalone

**Comment by mkruselj** [comment]
Not sure I can reproduce this, at least not with these steps.

**Comment by gitsmol** [comment]
Strange. The problem isn't there on my linux build either.
I shot a video to demonstrate. Had to use iphone to capture audio.
https://youtu.be/p89g_WMjBro

I can see if wiping my userdata works?

**Comment by mkruselj** [comment]
Ah, you are clicking the virtual keyboard. This does not happen with actual MIDI input. That's the difference here, which was not mentioned in reproduction steps. :)

**Comment by gitsmol** [comment]
Ah, of course. It could be a UI issue. Sorry for the confusion :)

**Comment by baconpaul** [comment]
Can totally reproduce.

The virtual keyboard and midi input are the same codepath so wonder what it is. Let me just make sure it doesn't happen with my midi kbd.

**Comment by baconpaul** [comment]
Yeah happens standalone with my midi keyboard too. Its just voice management bug in mono release.

**Comment by baconpaul** [comment]
(or in un-latch)

**Comment by baconpaul** [comment]
OK PR is in!
