### ISSUE TITLE
Installation Security; Request for Information

### ISSUE THREAD

**Issue by FPAinGHUB** [surge-synthesizer/surge#7631]
Hello,
I'd like to install the surge-xt plugin in a linuxmint machine to be used with muse. Is the following the appropriate package:

- -  surge-xt-linux-1.3.1-pluginsonly.tar.gz

How can integrity of a downloaded package be verified?
Is there an alternative (apt) installation method?

Thanks in advance!

**Comment by baconpaul** [comment]
That has inky the plugins and not the content. The same place as that content has a deb and rpm file which contains the full package.  

as to validating the content: our azure build steps are all open source. We sign tags in our GitHub on release. If you prefer to not trust our binaries, building the synth is easy. Does that answer your question?

**Comment by FPAinGHUB** [comment]
Thanks, 'baconpaul', for informing.

If you could please clarify, as follows:

 - is the deb package the ideal package to use surge-xt as a plugin in a DAW?

 - I'd have no problem in trusting the package. As a somewhat beginner, I thought that any to-be-downloaded package (outside official repositories) is subject to 'malicious changes' by third parties (by others than the entity that has uploaded for distribution). Any 'education' regarding this is welcome. And, if that deb-package is secure to download and install, then just please inform this out-right and I'd go with it.

Thanks again.

**Comment by baconpaul** [comment]
Yup exactly. If you are on mint deb is the way to go and then dpkg -i to install it or use the open build service builds here: https://software.opensuse.org//download.html?project=home%3Asurge-synth-team&package=surge-xt-release

you are wise to not trust binaries. We go out of our way to assure people that our binary distributions are safe, with full build path open and so on, as mentioned above, but self build is always an option if you prefer. 

Oh and yeah the deb has all the content as well as the synths and you definitely need that to fully enjoy the synth 

I’m going to close this as answered but if you have other concerns please do let us know here 

Best

**Comment by baconpaul** [comment]
Thanks!
