### ISSUE TITLE
audio in should not require a MIDI Event that triggers the oscilator

### ISSUE THREAD

**Issue by RustoMCSpit** [surge-synthesizer/surge#7634]
**Is your feature request related to a problem? Please describe!**
When I do audio in, I cant' hear sound as I need to send a MIDI Event that triggers the OSC, even if it's an Audio In it needs a Note that triggers it.

**Describe the solution you'd like:**
audio in should work like the trash 2 plugin or the vocalsynth plugin

**Comment by baconpaul** [comment]
If you want that, use latch mode whcih drones all the oscillators.

**Comment by Andreya-Autumn** [comment]
Yeah, short answer, what Paul said.

Slightly longer: There's a few technical reasons why this is hard to change. Audio in (the oscillator) is an oscillator just like all the others, which means it needs the voice manager to start a voice to make sound. Even if you could somehow keep the Amp EG open without an active voice, it wouldn't play. Also, audio in gets summed with all the other oscillators going into the filters/ws, and eventually into said AEG. So even if we made audio in ignore the voice management, it wouldn't play without keeping the AEG open. 

Making it do what you want would mean giving the audio in its own path through the whole synth, which would be undesirable in every situation except the one you want. So I don't think that'll happen. 

So, short answer again: Latch mode is your friend.

**Comment by RustoMCSpit** [comment]
> Making it do what you want would mean giving the audio in its own path through the whole synth, which would be undesirable in every situation except the one you want. So I don't think that'll happen.

would this be bad as a setting? it wouldnt affect the rest of the system if it was a turn on / off setting for audio in

**Comment by baconpaul** [comment]
it would not be bad as a setting which is why we have latch mode which is that setting.

there's also the audio in effect which you an add to an effect chain post-voices and it will also push the audio out the back, but that's post voice.

**Comment by RustoMCSpit** [comment]
> Even if you could somehow keep the Amp EG open without an active voice, it wouldn't play

why? what is a voice, a midi event?

> Also, audio in gets summed with all the other oscillators going into the filters/ws, and eventually into said AEG. So even if we made audio in ignore the voice management, it wouldn't play without keeping the AEG open.

cant it be made that audio in is the only oscillator, as an option?

> Making it do what you want would mean giving the audio in its own path through the whole synth, which would be undesirable in every situation except the one you want. So I don't think that'll happen.

oh yeah thats what i meant, why would this be undesirable?

> there's also the audio in effect which you an add to an effect chain post-voices and it will also push the audio out the back, but that's post voice.

what are the implications of that but?

**Comment by Andreya-Autumn** [comment]
In this case, a voice is roughly the thing the synth creates in response to a MIDI note. 
The audio in oscillator could be made to function differently. But is a lot of work for something that is already easily solvable with the latch button, as Paul points out. 
Making it bypass everything would be undesirable whenever you want the audio input to mix with the other oscillators going into the filters etc. 
The implications of that last statement is that the audio is inserted after all the per-voice stuff (waveshapers and filters etc). 

Really, changing this would be lots of work for no real benefit. Latch is your friend. :)

**Comment by baconpaul** [comment]
You can already do all of this

A voice is when the synth is playing something pre effects. 

if you want audio in as the only oscillator just set up the synth thst way 
If you want the audio in to be voice processed and don’t want to trigger voices with midi use latch
If you want the audio in to be post voice use the effect slot
If you want to mix and match the use one scene latch one scene not

**Comment by RustoMCSpit** [comment]
> You can already do all of this
> 
> A voice is when the synth is playing something pre effects.
> 
> if you want audio in as the only oscillator just set up the synth thst way If you want the audio in to be voice processed and don’t want to trigger voices with midi use latch If you want the audio in to be post voice use the effect slot If you want to mix and match the use one scene latch one scene not

this might be useful to add to documentation in the section around audio inputs. having preset examples would also be helpful for people who mightnt understand.

**Comment by Andreya-Autumn** [comment]
We do have preset examples! They are in factory - templates. And also each of the features mentioned above are already documented in the manual.
