### ISSUE TITLE
Update to Juce 7.0.12 (should fix Audio/MIDI settings dialog not opening on Ubuntu)

### ISSUE THREAD

**Issue by dgtized** [surge-synthesizer/surge#7640]
**Bug Description:**

Audio/MIDI settings dialog is not opening on Ubuntu.

**Surge XT Version**

Version: Surge XT 1.3.1.4b53827
Build: 2024-02-06 @ 15:30:18 on '1e9cd081d390/local' with 'GNU-9.4.0' using JUCE 7.0.5
System: Linux 64-bit Standalone on  AMD Ryzen 9 3900X 12-Core Processor
Sample Rate: 44.1 kHz / Process block size: 32 samples

* Plugin Type: [VST2, VST3, AU] -- not quite sure, I opened Surge XT as a standalone app.
* Bitness: 64
* Skin: Surge Dark

**Reproduction Steps:**

Start Surge XT standalone app using Ubuntu's launcher.

![image](https://github.com/surge-synthesizer/surge/assets/6784/ae5a7f49-9b10-4d43-8ab4-d79775f60f29)

Click on the "Options" in the upper left. Menu opens to show "Audio/MIDI settings", clicking on that and nothing opens.

Similarly, on the line below it has a notification in yellow that says "Audio input is muted to avoid feedback loop", and on the right there is a button labeled "Settings ...", clicking on that does not open any dialog.

**Expected Behavior:**

Clicking on Audio/MIDI settings or the settings button should open the dialog to select MIDI inputs and audio input/output.

**Computer Information (please complete the following!):**
 - OS: Ubuntu 23.10 (mantic)
 - Display: Dual 4k (3840x2160) monitors at 100% scaling on Wayland
 - Host: [e.g. Bitwig, Logic, Cubase, Reaper] - standalone?

**Additional Information:**

I haven't been able to reproduce, but *once* when I clicked on settings since install, it did open the dialog hidden underneath the Surge XT window, so I was able to change the settings once to connect a MIDI keyboard as input. Unfortunately I have not been able to reproduce whatever allowed it to work that one time. I've tried to retrace my steps 10+ times (including restarting the computer and reopening Surge XT) but have not been able to reproduce the one time it worked.

Both the load/save current state dialogs open correctly, though sometimes I receive a notification from Zenity like: "Save current state" is ready at the same time the dialog opens.

![image](https://github.com/surge-synthesizer/surge/assets/6784/ccfe2e53-f3ee-4246-8f39-4ea9c36454a7)

I installed Surge XT using the `.deb` I downloaded from the releases for 1.3.1 using `dpkg -i`. However it did fail on first install as `libxcb-cursor0` was missing, so I manually installed that with `sudo apt install ibxcb-cursor0` and then repeated the dpkg install.

I also notice that there is very odd behavior on resizing the window, where it appears to "ease" into the new resolution but there is a definite lag. I suspect that is another issue though.

**Comment by mkruselj** [comment]
This dialog is entirely handled by JUCE, it is not on us. So, this should first be verified by standalones of other JUCE plugins (try Dexed, OB-Xd...) and if it also happens with them, report to JUCE directly. We will not be forking JUCE just to fix this.

**Comment by dgtized** [comment]
I don't know what JUCE is let alone Dexed, OB-Xd, etc, so it's very unlikely I can verify any of this behavior in any other circumstances outside of this application. As a user of this application, I don't know how to distinguish which parts of the UI are in this app or an upstream library.

However, given you identified the upstream project, I looked briefly in the closed issues and found: https://github.com/juce-framework/JUCE/issues/1242, and from that the previously reported (and closed) https://github.com/surge-synthesizer/surge/issues/7071.

I'm sorry for re-reporting a known issue, but as it was closed I didn't see it, and I certainly was unaware of any history here. Given the issue seems to be ping-ponging between surge and JUCE, maybe it makes sense for one of the projects to leave it as an open issue so folks can see it's still a problem that some folks are encountering on the latest build?

**Comment by baconpaul** [comment]
Oh right so that means we just need to pull juce to a higher version than our forked 7.0.5

**Comment by baconpaul** [comment]
Sorry so let me re-open this and we can go to juce 7.0.12 + patches for our next update (and a nightly before that)

**Comment by hfiguiere** [comment]
Adding this JUCE patch to the flatpak.

**Comment by baconpaul** [comment]
Link to #7699 
Link to #7700

**Comment by baconpaul** [comment]
Ok we are in 7.0.12 in the nightlies!
