### ISSUE TITLE
Weird echo on Raspberry build with "virtual midi"

### ISSUE THREAD

**Issue by grbfst** [surge-synthesizer/surge#7643]
I have built a touch synthesizer with Surge and a Raspberry Pi meant as a therapeutic instrument that gets its midi notes from sensors on the outside of the box. It all works wonderfully but the weird thing is that about 20 seconds after the last touch all notes get played again without any input. Not sure if this is a Surge or a Raspberry or maybe the capacitive sensor board thing .

Has anyone encountered this echo before?

what you see is a temporary build, the final version is way more organic in looks.

![TouchWithSurgeXT](https://github.com/surge-synthesizer/surge/assets/23706335/691c044f-97a4-428a-9983-f8250451cfd1)

**Comment by baconpaul** [comment]
I have never heard of an echo like this.

You self build or you use the OBS build? If you self build I could suggest a place to put some logging messages to maybe help in the CLI?

What a lovely looking device. Congratulations on your project advancing.

**Comment by baconpaul** [comment]
Oh wow! Well that's sort of good news but sort of concerning!

**Comment by mkruselj** [comment]
Glad you have it sorted out in the end!
