### ISSUE TITLE
Pitch bend messages affect every note, ignoring midi channel match

### ISSUE THREAD

**Issue by AlzMar** [surge-synthesizer/surge#7649]
Hello Surge team,

In surge XT, any pitch bend message affects all notes ignoring midi channel match.
In many synths, the pitch bend messages sent on a given channel affect only the notes of the same channel.
If this behavior was not intentional, it would be very useful to match pitch bend messages with only the corresponding channel notes. 
It would allow many more modulation power. (e.g. : reproduce one string slide against another string constant pitch, achieved by many guitar players)

Best Regards,

Marc Alvarez

**Comment by baconpaul** [comment]
Sounds like you want MPE, which does exactly that per channel pitch assignment and voice management. Surge supports that with the MPE mode enabled in synth.

**Comment by mkruselj** [comment]
Correct, enable MPE mode.
