### ISSUE TITLE
Quick way to compare edited patch with original patch

### ISSUE THREAD

**Issue by pierredewilde** [surge-synthesizer/surge#7658]
Hi,

**Is your feature request related to a problem? Please describe!**
To compare edited patch with original one, you need to undo all changes then redo changes which is very cumbersome.

**Describe the solution you'd like:**
A shortcut key to easily compare edited patch with original patch would be welcome.

**Describe alternatives you've considered:**
If I want to hear original patch, I can save edited patch under another name and compare both which is also cumbersome.

Thanks,
Pierre

**Comment by pierredewilde** [comment]
Related to discussion https://github.com/surge-synthesizer/surge/issues/7657

**Comment by mkruselj** [comment]
It was not needed to open a duplicate ticket, we can just retag the original one. Closing.

**Comment by baconpaul** [comment]
Seems like one of them should be open though @mkruselj
