### ISSUE TITLE
Allow oscillator pitch to be modulated by more than an octave

### ISSUE THREAD

**Issue by andrewcb** [surge-synthesizer/surge#7659]
**Is your feature request related to a problem? Please describe!**
I want to be able to use Surge XT to make patches in which the pitch of an oscillator is modulated by an envelope or LFO by more than an octave. However, the oscillators' pitch controls have a range of +/- 7 semitones, with any further pitch changes being an octave selector.  This limits the possibilities for sound design with Surge XT.

**Describe the solution you'd like:**
I would like a way of modulating the pitch of an oscillator continuously by the full range of the oscillator. I don't know how this would fit in the current control schema: perhaps a switch to switch between the octave/pitch controls and a continuous semitone pitch, or if all else fails, another transposition parameter which is summed with the existing ones.

**Comment by Andreya-Autumn** [comment]
Right click on the oscillator pitch and select "Extend Range". ;)
