### ISSUE TITLE
Audio dropout when using Spring Reverb on a patch

### ISSUE THREAD

**Issue by Witcharrr** [surge-synthesizer/surge#7681]
**Bug Description:**
There's audio dropout when using Spring Reverb on a patch with Asio4All

**Surge XT Version**
1.3.2.f5bd0e1

* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Load Surge XT with init saw patch
2. Add Spring Reverb to FX Section
3. Play some notes
4. Get audio dropouts and message "Audio Output Unavailable" in top right corner

**Expected Behavior:**
No audio dropouts while using Spring Reverb.

**Computer Information (please complete the following!):**
 - OS: Windows 10 64-bit
 - DAW: Reaper v7.16; Renoise 3.4.4
 - Audio Interface: Behringer UMC404HD with latest drivers
 - CPU: Intel Core i5-10400F
 - RAM: 64GB DDR4

**Additional Information:**
1) This bug only occurs with Asio4All setup. If i'm using ASIO UMC drivers - it's all fine (but due to buggy sound interface drivers Surge consumes twice of CPU power, so that's why i'm using Asio4All + some other reasons). 
2) Also, if Spring Reverb is disabled (but not deleted from FX Section), it continues to give drop outs. 
3) If used with Renoise there's a chance it will crash

**Screenshots:**
Here's the screenshots of Asio4All setup
![2024-06-30 17_23_50-🔊 ASIO4ALL v2 15](https://github.com/surge-synthesizer/surge/assets/14049568/7a89f557-d1c3-4a84-af76-8d22a66432c9)
![2024-06-30 17_24_17-🔊 ASIO4ALL v2 15](https://github.com/surge-synthesizer/surge/assets/14049568/4e934018-e4f5-4112-9642-8bbb32c724a9)
![image](https://github.com/surge-synthesizer/surge/assets/14049568/f1a935e5-5541-465c-b211-3a0a32ecf124)

Renoise audio settings:
![image](https://github.com/surge-synthesizer/surge/assets/14049568/fe495794-6729-4a1e-9be8-afcd1e4aca30)

Reaper audio settings:
![image](https://github.com/surge-synthesizer/surge/assets/14049568/fa2837a0-bbeb-4e73-babe-6a357f7b9a18)

**Comment by mkruselj** [comment]
I'm not sure there's anything we can do about this.

**Comment by baconpaul** [comment]
Sounds to me like a CPU overload which is causing xruns for asio4all. The Spring Reverb is our most CPU intensive effect.

**Comment by Witcharrr** [comment]
Played around with Asio4All settings, and discovered 2 things:
1) There's no such heavy dropouts when Asio4All has only one multi-out and one multi-in from sound interface, like on this screenshot:
![image](https://github.com/surge-synthesizer/surge/assets/14049568/b0e99596-4e6a-45a5-9590-6c7f2903b092)
2) But now there's a 1-2 second "hiccup" after adding Spring Reverb and playing one (or several) notes. When this initial hiccup is gone everything works and plays like it should.
If this is unfixable, i think this kind of solution should be stated somewhere, like "troubleshooting" section in Surge XT Manual or smth. 
Have a nice day!

**Comment by baconpaul** [comment]
Curious if the surge cpu meter goes to 100 when this happens?

**Comment by Witcharrr** [comment]
> Curious if the surge cpu meter goes to 100 when this happens?

No, it doesn't. If it helps, here's a video (sorry for phone recording, it's kinda difficult to record video with internal audio with Asio4All)

https://github.com/surge-synthesizer/surge/assets/14049568/ef3c8868-a40d-4059-bad5-67f119c86d35

But during recording i found out if i'll wait like 3-5 seconds after loading Spring Reverb it doesn't give such "hiccup". So maybe there's some kind of problem with slow initialization of this module or smth like that?

**Comment by baconpaul** [comment]
The thing I don’t get is we don’t see this with other oses or drivers - like no problem here macOS and core audio - and the sr isn’t doing anything special os wise. A bit of a mystery

**Comment by mkruselj** [comment]
I would chalk this up to a computer specific shenanigan. This is the first and only report we have of such an issue. I think there's probably nothing we can do to fix it, unfortunately.
