### ISSUE TITLE
Surge XT on user arch system is differentially slow and consumes a lot of CPU

### ISSUE THREAD

**Issue by arik123** [surge-synthesizer/surge#7739]
**Bug Description:**
The application is slow, it takes about a minute to startup, and then each click takes about a minute - making it completly unusable.
The application also has unusually high CPU usage while running.

**Surge XT Version**
* Version: 1.3.2 (f5bd0e16)
* Plugin Type: None?
* Bitness: 64-bit

**Reproduction Steps:**
1. Build
2. Run

**Expected Behavior:**
Run without too much lag

**Computer Information (please complete the following!):**
 - OS: Arch Linux - X11

**Additional Information:**
First I tried the version from package manager, but it had problems, so I compiled it on my own, both normally and in the Debug configuration, neither showed anything that would give me an idea why would this be happening

**Comment by mkruselj** [comment]
High CPU while running sounds like you're always running a debug build somehow. What's the hardware specs of your computer?

We've had well over a hundred of thousands of downloads and no reports of anything like this, so it is most likely an isolated case to something related to your machine only...

**Comment by arik123** [comment]
```
OS: Arch Linux x86_64
Host: Latitude 5420
Kernel: 6.10.3-arch1-1
Uptime: 2 hours, 2 mins
Packages: 1697 (pacman)
Shell: zsh 5.9
Resolution: 1920x1080, 2560x1440
WM: i3
Theme: Adwaita [GTK2/3]
Icons: Adwaita [GTK2/3]
Terminal: st
Terminal Font: Dejavu Sans Mono
CPU: 11th Gen Intel i7-1185G7 (8) @ 4.800GHz
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics]
Memory: 9731MiB / 31485MiB
```

I'm quite sure when I built it the first time it was not debug build, and the second time I build it as debug it had different logs during make.

Also I started a timer to see how long does the GUI take to load - and it was over 5 minutes

**Comment by baconpaul** [comment]
So on my Ubuntu 24 box built from head the app starts sub-second as it does on my Mac and windows box and does for our other users. So the question is what’s different about your system which is interacting poorly 

Thanks to the magic of arch the answer is limited to “anything at all” though so not quite sure what to do

a few thoughts though 

1. if you do a debug build you can break the startup and see where it is - that may give a hint 
2. Is your audio subsystem somehow non standard?
3. If you run the vst3 in a daw do you get the same behavior? 

My suspicion is that the most likely answer is the standalone code connecting to your audio system is hanging for some reason so looking in the log may help or if you don’t have jack or pipe wire configured properly that could do it too?

**Comment by mkruselj** [comment]
Also, why not try to do a performance profiler since you already also self-build? See where it's locking up.

**Comment by baconpaul** [comment]
yeah if its taking 5 minutes it is hung somewhere timing out on something. Just run it under gdb and break and look at the stacks is exactly the right first idea.

Again my guess is you will find something like there's a jack server which is configured to answer requests but not respond to them or some such, and juce breaks with that. Most likely is a timeout trying to enumerate the audio or midi sub-system. Which is why a DAW test would also be useful.

But really it could be anything at all. For instance, we iterate the filesystem at startup so we could be in some sort of infinite loop in surge storage scanning if theres a file system weirdness under the directories where we start.

But without a few break-and-look-at-stack in an in progress session we won't be able to tell for sure.

**Comment by baconpaul** [comment]
Hi @arik123 - any chance to look at any of these suggestions?

Thanks!

**Comment by arik123** [comment]
Thank you for all the suggestions - I did run it with GDB attached, and after a short while found that the issue seems to be with my tiling window manager.
The app keeps receiving X11 events to resize the window, but it seems like it ignores them

**Comment by arik123** [comment]
Thank you for all the suggestions - I did run it with GDB attached, and after a short while found that the issue seems to be with my tiling window manager.
The app keeps receiving X11 events to resize the window, but it seems like it ignores them.
I verified this is the issue by forcing the windows to be floating all the time and now it works just fine.

**Comment by baconpaul** [comment]
Ahh that makes sense, we try to preserve aspect ratio because we are a fixed aspect ratio app and I bet if you respond to that by changing back we get in a nasty fight

cool thanks for letting us know! I’ll close this and we will remember if other tiling users come along
