### ISSUE TITLE
32 seconds for Release time On EG  .. may be a bit long?  At least is incorrectly displayed..? 

### ISSUE THREAD

**Issue by sense-amr** [surge-synthesizer/surge#774]
Now i'm a passionate .. advocate for high release times.. as i typically like to make nice long string/pad patches.. But i couldnt help noticing that 32 seconds is a VERY LONG time .. for release especially when you are likely to retrigger another note before 32 seconds is up .. 

As i say i love long release times.. but i couldnt help noticing that if i triggered another note during the time of between 0-32 seconds .. it just increased the poly count .. presumably for another 32 seconds.. so this might be contributing to some poly issues as the poly just keeps going up and up and and up .. and when considering you might be using 3 or more notes for a chord in this instance.. you have 3 x 32 going up and up everytime another chord is struck!.. which typically WONT take another 32 seconds and certainly wont wait 32 seconds for the poly count to clear.. 

This is just a thought i had when i was making pads here.. 
32 seconds is a LONG time in the air .. to hang..

any thoughts?

in tests here.. also i found that the poly count sticks around for quite a while AFTER the release sound is inaudible .. a good 2-3 seconds ! .. 

is this possibly an area we could look into .. to maximise poly use AND cpu efficiency ?..

**Comment by sense-amr** [comment]
@esaruoho @baconpaul @kzantow others who make sounds ? what do you think ?

**Comment by sense-amr** [comment]
also THIS release.. in .. 
ENV on LFO .. may cause problems if it truly is "FOREVER"
![image](https://user-images.githubusercontent.com/1504019/54183288-ef112580-44f7-11e9-9a91-8899090ffbe0.png)

**Comment by sense-amr** [comment]
Ok now testing further i found that under no circumstances does the Release on AMP EG ever actually go for 32 Seconds.. its alot closer to 16 seconds..

**Comment by sense-amr** [comment]
so now at the very least im going to say "32 seconds" on A D R Envelopes  is incorrectly reporting maximum time value for each of these parameters..

**Comment by mkruselj** [comment]
I have actually tested this now and in fact the display is correct - all envelope times are indeed going up to 32 seconds. Was pretty easy testing with Voxengo SPAN to see the frequency content with AEG release set to max,  even if the signal ends below -90 dB or so (still means the sound is running even if very very quiet). Closing the issue.
