### ISSUE TITLE
Where are the ring modulation options?

### ISSUE THREAD

**Issue by Airlane1979** [surge-synthesizer/surge#7740]
I'm confused. My version of Surge XT (1.2.3.bb8dd2b) seems not to have the options for ring modulation types described in the manual. When I right click on the mixer's ring mod channels, I just get the attached pop-up. What am I doing wrong?
![Screenshot (7)](https://github.com/user-attachments/assets/e0cdb0e1-1e7e-433f-9024-7f31b582e3d6)

**Comment by mkruselj** [comment]
You need version 1.3.2 not 1.2.3.
