### ISSUE TITLE
Move int voiceCount out of SurgeStorage and use polydisp directly from SurgeSynthesizer class

### ISSUE THREAD

**Issue by nuoun** [surge-synthesizer/surge#7742]
#7727 added voice parameters to the Formula modulator and for this reason the active voice counter is stored as an int in SurgeStorage [here](https://github.com/surge-synthesizer/surge/blob/c914d3bbc20e1ebbf6e0da73aa2f46e2fbf69d39/src/common/SurgeStorage.h#L1347) from which the voice count is updated inside the valueAt() function in FormulaModulationHelper.cpp [here](https://github.com/surge-synthesizer/surge/blob/c914d3bbc20e1ebbf6e0da73aa2f46e2fbf69d39/src/common/dsp/modulators/FormulaModulationHelper.cpp#L490,).

Ideally, this value should be retrieved directly from the atomic int `polydisplay` in the SurgeSynthesizer class similar to how it's being used by SurgeGUIEditor.cpp [here](https://github.com/surge-synthesizer/surge/blob/af631b506566184f438f5dfeb24c7acb7d8e6ed7/src/surge-xt/gui/SurgeGUIEditor.cpp#L797), either also as an atomic int or some other type, if the same `polydisp` is used it should probably also be renamed as it would no longer be used to only display a value on the GUI.

**Comment by baconpaul** [comment]
Probably the thing to do is

1. make voiceCount in storage atomic
2. remove polydisp all together and fix the code to use storage->voiceCount
3. problem solved

its a *bit* gross. the voice count is really part of the synth not the storage. but the lfos don't have synth access so this cheat is the more practical thing I think.
