### ISSUE TITLE
Changed code signature in macOS version 1.3.4?

### ISSUE THREAD

**Issue by suschizu** [surge-synthesizer/surge#7753]
The code signature has changed:

EXPECTED 'Paul Walker (G4Y62M4JQ6)' 
FOUND 'Paul Walker (547U7G7MZC)'

can you confirm this? 

thanks!

**Comment by baconpaul** [comment]
Yes I migrated my certs to a different Apple ID just for surge projects, this is correct

**Comment by suschizu** [comment]
thanks for the fast answer :)

**Comment by baconpaul** [comment]
No prob. Curious if you checked by hand or if you have some scanner set up. If you have a scanner I’ll let more folks know in case others do.

if you checked by hand congratulations on your diligence :)
