### ISSUE TITLE
Missing 'enable keyboard' option?

### ISSUE THREAD

**Issue by mageejp** [surge-synthesizer/surge#7766]
I'm using Surge XT in Renoise 3.4.4 on Ubuntu 22.04. I wanted to save a patch, couldn't type in the box, and forums suggested I should click 'enable keyboard'---but that checkbox is not there. Has this option gone somewhere else? Is this a Surge issue or a Renoise issue?

![image](https://github.com/user-attachments/assets/448f14dc-c51f-4e5a-ad8c-aa43d5f630a9)

**Comment by baconpaul** [comment]
which version of surge?
but I think the answer is it is a renoise issue
You need to somehow tell renoise to allow keyboard events to go to the plugin

**Comment by mageejp** [comment]
I can confirm this is a Renoise issue. No resolution yet but I see confirmation that this is something that needs to be fixed from the Renoise side--previous versions have added the 'enable keyboard' checkbox as part of the Renoise plugin GUI.

**Comment by baconpaul** [comment]
OK good luck and have fun making music with surge!
