### ISSUE TITLE
Wavetable initial morph value is zero

### ISSUE THREAD

**Issue by blancoberg** [surge-synthesizer/surge#7774]
**Bug Description:**
When modulating the morph parameter, the initial value is always set to zero, which cause the wavetable to interpolate to the correct morph/frame during the first block, which can cause glitches/clicks in the beginning of each note.

**Surge XT Version**
All versions

* Version:
* Plugin Type: [VST2, VST3, AU]
* Bitness: [32-bit or 64-bit]

**Reproduction Steps:**
1. Load a noisy wavetable.
2. Modulate the morph parameter with for example the modwheel. set the modwheel to 100% before playing.
3. play some notes. compare that to when morph is set to 100% manually without modulations.
Manually setting it will have no glitch, but modulating it will. 

**Expected Behavior:**
The morph value should start with the modulated value. instead it starts on zero and interpolates to it.

**Comment by baconpaul** [comment]
it starts on the patch value, not zero, right? That is, if you set morph to 0.5 with the slider it will start there.

basically ignoring the modulated value. Just for future readers.

**Comment by blancoberg** [comment]
Yes you are right. It always starts at the manually set slider value
