### ISSUE TITLE
Wavetable morph interpolation is not continuous

### ISSUE THREAD

**Issue by blancoberg** [surge-synthesizer/surge#7777]
**Bug Description:**
The interpolation between frames is not continuous. This is especially apparent on noisy wavetables. 

**Surge XT Version**
All versions

* Version:
* Plugin Type: [VST2, VST3, AU]
* Bitness: [32-bit or 64-bit]

**Reproduction Steps:**
1. Load the preset included in this ticket
2. Increase LFO1 rate to make the glitching more appearant. 

**Expected Behavior:**
The signal should be continuous and have a lot less noise

[wt_interpolation_bug.zip](https://github.com/user-attachments/files/16796824/wt_interpolation_bug.zip)

**Comment by mkruselj** [comment]
Also fixed now, so closing.
