### ISSUE TITLE
Sending notes via OSC on a Raspberry Pi crashes Surge

### ISSUE THREAD

**Issue by KingaJanicka** [surge-synthesizer/surge#7779]
**Bug Description:**
Sending /mnote and /fnote messages to Surge-XT-CLI on a raspberry pi 5 will segfault the synth.

As the messages are sent after some time (up to 20-25s but usually about 10 or less) the synth will output "Segmentation Fault" and close itself.

**Surge XT Version**
* Version: 1.4.main/20240817~4bf7265-0...git-no-commit
* Plugin Type: CLI
* Bitness: 64bit

**Reproduction Steps:**
[oscBarrage.txt](https://github.com/user-attachments/files/16824645/oscBarrage.txt)
1. Launch Surge-XT-CLI with following command ``surge-xt-cli --osc-in-port=53280``
2. Copy the text of oscBarrage.txt to a python file (Can't attach .py files, sorry!)
3. Install needed deps
4. Run the python file
5. Surge will play the notes but will crash after several seconds; with Segmentation Fault in the command line

**Expected Behavior:**
Notes to be played without synth segfaulting, like when I send midi

**Screenshots:**
![image](https://github.com/user-attachments/assets/9129b87c-7c72-4b5a-bcca-68405da64ea3)

**Computer Information (please complete the following!):**
 - OS: Raspbian
 - Host: CLI

 - Version: Tested 1.3.1 up to 1-4

**Additional Information:**
This problem does not occur via midi on a raspberry pi- I have sent chords to surge-xt-cli via midi, 1/32nd at 300BPM and it didn't crash

It also seems that desktop enviroments are either harder to trigger or don't have the bug present as we've tested this on a M2 mac. My own AMD Ryzen 7 laptop also doesn't encounter this bug.

**Comment by pkstone** [comment]
This occurs on Mac CLI as well, so CPU as the cause is ruled out.

(There's a typo in the command line above; it should read: `surge-xt-cli --osc-in-port=53280` )

**Comment by KingaJanicka** [comment]
Fixed the typo

**Comment by baconpaul** [comment]
Fixed the bug. :)
