### ISSUE TITLE
Add wavetable fixes deform menu thingy

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#7784]
Now that @blancoberg has fixed up the wavetable oscillator I need to do the patch version / deform / right mouse dance to make old patches work the old way. I'll do this next week just wanted to drop in a reminder issue.

**Comment by blancoberg** [comment]
Is this the switch implementation?

**Comment by baconpaul** [comment]
Yes just a reminder to myself to do it

**Comment by mkruselj** [comment]
Don't worry, Paul's got it. If he's writing the if he can just as easily copy the required diff to make it work :)

**Comment by baconpaul** [comment]
Yeah I'll add a switch and retrieve it at the top of process and then you can indeed just plumb it through helpful. thanks

**Comment by baconpaul** [comment]
OK guys sorry i've gotten a bit unexpectedly super busy

I found some time tonight though to add the option and its in PR #7785

That sets up and version the option properly. A few things

1. It doesn't do anything with it other than extract it in the WT oscillator at the top of process block. Theres an if 0 knocked out process block print to check it
2. I don't know what we want as the names for the various states so I chose long things

I'm happy to merge and then let you proceeed or also happy for one of you to pick it up from there and use it as a starting point. I'll be up early in the AM then traveling / offline a lot of the day though so unless I hear otherwise I'll leave it hanging out ask an open PR for you to start with or merge at your leisure.

**Comment by mkruselj** [comment]
It should just be an on off toggle to enable or disable all fixes at once. Or rather, it should work in reverse, call the option Legacy Mode, if it's enabled use everything how it was, if it's disabled use the fixes.

**Comment by baconpaul** [comment]
Yeah that’s just a menu construction change. The rest of the code would be the same. Still suggest we use named values in Case there’s 1.5 changes but one menu with a bool is an easy twist of this pr

**Comment by baconpaul** [comment]
Hold on i have 10 minutes. I'll change it to a binary menu display and then merge

**Comment by baconpaul** [comment]
ok merged the binary option setup 

over to you! (or me but then next week :) )

**Comment by blancoberg** [comment]
@baconpaul Would it be possible to use this switch as a selector for multiple types of interpolation modes? 
So instead of having a on/off switch, we could have a menu item named "interpolation mode" with a submenu containing the modes. ( which today would be legacy and continuous ).

Because I know atleast one other type of interpolation mode that would be a useful complement to the existing one

**Comment by mkruselj** [comment]
We already have an option for disabling the continuous morph (which skips interpolation and just hard switches the frames). Which other mode did you have in mind?

**Comment by baconpaul** [comment]
I wrote the switch with an enum rather than a binary internally for exactly that reason. The menu presents as a binary but my original presented as a list

so: “yes”

**Comment by blancoberg** [comment]
> We already have an option for disabling the continuous morph (which skips interpolation and just hard switches the frames). Which other mode did you have in mind?

Yeah but that is not really an interpolation. its more like an "integer mode" on top of the interpolation mode. 

The mode that I would like to add is a "morph", which instead of always moving through frames, this one fades between the previous frame and the current during a block.
It would sound similar to the already existing one at moderate speeds. The main difference will be when you make big jumps between frames. 
For example if you set the frame to 255 with a formula modulator, instead of scrubbing through the entire range of frames during a block, it will simply fade to the last frame. Very useful, as it would produce minimal noise. 

The "interpolation skip" will still apply on top of these of course

**Comment by blancoberg** [comment]
> I wrote the switch with an enum rather than a binary internally for exactly that reason. The menu presents as a binary but my original presented as a list
> 
> so: “yes”
Perfect. 
So I was thinking. Would it be possible to be able to access this parameter via a formula modulator? making it possible to switch mode on the fly. It would be incredibly useful.

**Comment by mkruselj** [comment]
Formula modulator has no access to parameter deform values. They are non modulatable.

**Comment by blancoberg** [comment]
> Formula modulator has no access to parameter deform values. They are non modulatable.
> 
> I would say your proposed new mode doesn't need a new option. Just make it the new default behavior when legacy mode is off!

I know its not accessible today, but could it be? 
I mean the retrigger_AEG and retrigger_FEG shouldnt be modulatable either, but is still accessible via the formula mod

This new mode would definitely need a new option, as its not the same as the continuous mode/fix. One is scrubbing through the table, this one "fades" between the last table pos value and the current.

**Comment by mkruselj** [comment]
What I'm saying is, if you disable legacy mode, it would just use last and current tables instead of going through the range. Unrelated to the current Continuous option. I think that will be just fine. Let's not go overboard with options here. New playback mode does all the changes in one go and that's it.

**Comment by blancoberg** [comment]
hm not sure I'm following cause there is currently no mode where that happens.  Old legacy mode does scrub through the entire table, although buggy. The new does the same. If you disable "continuous moprh", it  will still scrub through the table, but stepwise on whole numbers. 

I don't think it is overboard to have other modes. Its not like you have to even consider what mode you want to use, its just something on the side for those who want to dial it in for specific cases.

**Comment by mkruselj** [comment]
I want to minimize option paralysis. It is easier to explain away legacy mode with "this is how it was and this is how it is now". And so what I'm saying, regardless of the fact that legacy mode did not have this new option you want to add, we still don't need it. We just make the new playback mode to NEVER scrub through the table, instead always go between last and current frame. No extra option needed.

**Comment by baconpaul** [comment]
Architecturally the formula modulator outputs values and also can send triggers to one point in the instrument (like step and mseg also). It’s not able to set deform on a param without rebuilding most of the modulation architecture or doing some rather gross internal state exposing

**Comment by blancoberg** [comment]
@mkruselj Im still not following how this should work without adding another mode in the menu. 
If the new mode never scrubs, then what mode will? the legacy mode isn't doing it correctly

**Comment by baconpaul** [comment]
the enum could easily have style XT_13 = 0 then feature by feature us 1<<1, 1<<2, 1<<3 so it can be flags you set and if. we've done that on other things too like the modern sub-types

**Comment by mkruselj** [comment]
Legacy mode would scrub through and have all the buggy behaviors you fixed. Legacy mode disabled would have all your fixes and would not scrub.

**Comment by blancoberg** [comment]
so the options here are: 
one buggy scrub through and a scrub through  VS
one buggy scrub through and fade

if that is the case, then i'll ditch the fade as a working scrub through is way more important

**Comment by baconpaul** [comment]
sorry joel i'm not quite sure. you want two different discrete morph modes basically? so you want 'discrete jump' and 'discrete cross-fade'? is that the idea?

I think it would be handy to have a tiny matrix of the proposal.

The problem (nay, mistake) we made was use extend range for morph vs continuous, which is a binary, but there's no reason we can''t use masking on deform to add that. I just want to make sure I understand the dimensions of proposal.

So you could, for instance, have the deform values be "XT13 = 0, XT14_SCRUB = 1<<1, XT14_FADEJUMP=1<<2, XT14_SOMETHINGELSE=1<<3` and then have the menu or-onto the deform type and read it off bitwise in the wavetable and pick the new default for the 1.4 patches.

**Comment by mkruselj** [comment]
> so the options here are: one buggy scrub through and a scrub through VS one buggy scrub through and fade
> 
> if that is the case, then i'll ditch the fade as a working scrub through is way more important

I'm not sure we're on the same page.

If the crossfade is helping to fix the buggy scrub, it should be the new default, period. It should not be an option.

**Comment by blancoberg** [comment]
since my explaining skills are lacking; This is what I had in mind:
![image](https://github.com/user-attachments/assets/2305e16d-d4a2-4e97-b067-ff9a272d3483)

I don't think the "extend range" changes the interpolation. It just switched "smoothing" between frames on/off.  So it makes more sense to have the actual interpolations in a separate menu like this. 

The extend range will still affect all of those interpolations as before. 

The "Scrub" in this case is the bug fixed interpolation and will be the default. All other modes other than legacy would have those bugs fixed as well. 
just a though. We don't have to add that right now. but was just an idea.

**Comment by baconpaul** [comment]
So basically “all the fixes or none” but not buffet style. Does that work Joel?

**Comment by baconpaul** [comment]
What’s the difference between fade and scrub basicalky? 

Can we make two choices “old” and “new” or do we need two news?

(I just don’t know the answer to that but if we can avoid two news all the better)

**Comment by mkruselj** [comment]
Old and New options is exactly what I'm proposing. Not 3 options. Just old way and new way. So my question to @blancoberg is: which way do you think works better overall, scrub or fade?

**Comment by blancoberg** [comment]
> Old and New options is exactly what I'm proposing. Not 3 options. Just old way and new way. So my question to @blancoberg is: which way do you think works better overall when compared to old buggy morphing: scrub or fade?

If I can only have one then its scrub , as that is the one that is already commited.  Its also more efficient than a morph

**Comment by blancoberg** [comment]
> So basically “all the fixes or none” but not buffet style. Does that work Joel?

Its the same as just having legacy and the fixed. just one additional option/interpolation mode. I'm still confused as to why this wouldnt work? Judging by the scepticism on display here I'm clearly missing something :D

But anyway its not needed, so we'll just go with legacy and the fixed one. No problem!

The difference between the interpolation modes is this:  ( this happens during one block cycle though, so its probably only audible on large frame jumps. In the example below it morphs between frame 0 and 255.
![interpolation](https://github.com/user-attachments/assets/3ddd3d09-e1af-46fe-98ab-b61712620e00)

**Comment by mkruselj** [comment]
That's the animation that we were missing! :)

Looking at it I def agree we don't really need the morph mode. Fixed scrub is the way to go.

**Comment by baconpaul** [comment]
Ahh right but a block is only 32 samples so this would really only be changing the data set for that one block? Does that sound different? I worry that nuance may be better with us just making a choice rather than presenting that subtle an option

**Comment by blancoberg** [comment]
tbh I'm not sure as I haven't tried it yet lol

**Comment by blancoberg** [comment]
most likely not needed for anyone but me, so lets just ditch that idea.
I was thinking it could be useful for a very niche situation where I need to jump from one frame to another. In those cases it would produce less noise than scrubbing, that is all

**Comment by baconpaul** [comment]
Oh ha well my intuition is that it won’t be that big a difference but never hurts to try. I just think we should pick the better one rather than add this fine grained an option unless it’s somehow a radical difference

**Comment by mkruselj** [comment]
This is implemented now, yeah? So, closing the issue :)
