### ISSUE TITLE
Provide a PDF manual that can be downloaded and read offline

### ISSUE THREAD

**Issue by juanriccio** [surge-synthesizer/surge#7796]
I am one of those crazy nerdy guys - maybe with too little of a life...
But I would like a PDF manual that can be read offline
It would also be nice to be able to look things up when I'm working on my airgapped DAW machine.

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge-synthesizer.github.io/releases/tag/surge-xt-manual

I'm not sure why this isn't linked obviously from the online manual though. @mkruselj / @mthierman where should the link to this live?

**Comment by mthierman** [comment]
It was removed because it was broken after the website redesign and I didn't want to fix it =D

It uses puppeteer now, and I think the quality is sufficient if we want to link it from the manual again.

**Comment by baconpaul** [comment]
Gotcha. Yeah it looked fine to me when I looked at it! I get GitHub notifications when it rebuilds so I kinda figured it was live!!

**Comment by juanriccio** [comment]
Thank you @baconpaul and @mthierman.
From your words, I'm assuming it will be linked from the online docs soon.
I'm impressed by the quickness of the responses here!

**Comment by mkruselj** [comment]
We're gonna close this issue here, since it's a website change. @mthierman I reckon you got it from here?
