### ISSUE TITLE
Patch browser: make the Category search work across Authors

### ISSUE THREAD

**Issue by juanriccio** [surge-synthesizer/surge#7797]
When I'm looking for a patch by category, even if I enter "CATEGORY=perc" or some similar search string, the results I get are limited to the currently selected author. So if I want to have a bird's view of the whole patch database, I still have to use the mouse and manually go through all the authors. This is unconvenient. It would be nicer if I could see at a glance all the patches that have a Category matching "perc".

**Comment by baconpaul** [comment]
![Screenshot 2024-09-23 at 9 36 42 AM](https://github.com/user-attachments/assets/1888ed34-51b6-415a-8d40-5e1ee028451f)

When I do `CAT=perc` I get patches spanning multiple authors.

**Comment by juanriccio** [comment]
Thanks for pointing that out, @baconpaul. You're obviously right. My bad.

I was referring to the fact that once the patch is selected, clicking the <- or -> patch buttons shown in the picture below will stay in the currently selected category but won't change author any more. I'd like those buttons to keep traversing the category across authors.

![image](https://github.com/user-attachments/assets/f56852fa-68a7-43b8-a980-ab15c908b820)

**Comment by baconpaul** [comment]
Oh there’s a user preference for that somewhere - check the workflow menu.

**Comment by mkruselj** [comment]
That preference is not for prev-next patch buttons, though.

@juanriccio You will want to enable Workflow->Retain patch search results after loading, so that you can use up/down arrows after you've loaded a patch from the search results.

**Comment by juanriccio** [comment]
Hello and thanks for your input, @mkruselj 

> That preference is not for prev-next patch buttons, though.

There is a pref for prev/next patch buttons - to constrain the movement within the current category. It actually constrains the movement to the author+category couple, though.

> @juanriccio You will want to enable Workflow->Retain patch search results after loading, so that you can use up/down arrows after you've loaded a patch from the search results.

Yes I noticed, and I do use that. However, once you commit to one patch (e.g. to see the whole synth panel unobstructed), patch scrolling is constrained as discussed.

**Comment by mkruselj** [comment]
That's correct and working as intended - the constraint is within the physical folder on the hard drive. Not within the search results.
