### ISSUE TITLE
Virtual keyboard has wrong mapped (frequency) note

### ISSUE THREAD

**Issue by oswanderson** [surge-synthesizer/surge#7808]
**Bug Description:**

**Surge XT Version**

* Version: 1.3.2
* Plugin Type: VST3
* Bitness: 64-bit
![image](https://github.com/user-attachments/assets/ee266fde-ad23-4d12-8964-34d2b1c4fc9a)

**Reproduction Steps:**
1. Open Surge XT
2. Press any note
3. e.g. when C1 is pressed, Surge XT shows C2

**Expected Behavior:**
When a note is pressed, the right one should be shown in the virtual keyboard.

**Screenshots:**
![image](https://github.com/user-attachments/assets/4bf685fd-87bd-4ac6-a58a-c5c870b48f61)

**Computer Information (please complete the following!):**
 - OS: macOS Sequoia 15.0
 - Host: Cubase 13
 - Version: 13.0.41 Build 256 (Apple Silicon)

**Additional Information:**

**Comment by mkruselj** [comment]
Not a bug. We provide options for how middle C should be designated (C3, C4, C5), with C4 being the default.

**Comment by baconpaul** [comment]
Hi!

there are three different standards for note numbers where note 60 / 261 hz is either c3 c4 or c5. The closest we have to a standards body has c4 as the answer but cubase chose differently. You can remap the note name to octave in one of the menuse
