### ISSUE TITLE
MPE Surge doesn't remember user pitch bend range

### ISSUE THREAD

**Issue by fredericcormier** [surge-synthesizer/surge#781]
MPE Surge doesn't remember user pitch bend range

- Instantiate Surge.
- Menu>MPE (enabled)>Change default pitch bend range
- Type the desired value.
- Quit Daw
- Launch Daw and instantiate surge 
- The default pitch bend range  defaults back to 48

Surge should remember my settings

Logic Pro OSX Sierra and High Sierra

**Comment by baconpaul** [comment]
I’m sorry you have that behavior. I coded it to save and it does save for me

Can you check if you have a ~/Documents/Surge directory and if it contains a file like “surgeusersettings.xml” (or something like that)? That is where it should save.

**Comment by fredericcormier** [comment]
Yes SurgeUserDefaults.xml

BUT the ~/Documents/Surge is a symlink pointing to the original in my Dropbox folder so I can sync my presets on all my computers.

Could that be the problem?

**Comment by fredericcormier** [comment]
Also the pitch bend range is set correctly
` <default key="mpePitchBendRange" value="24" type="2">`
So the problem is reading?

**Comment by baconpaul** [comment]
Symlink shouldnt be a problem 
Lemme look at the setup code before I get away

**Comment by baconpaul** [comment]
Hmm the reader code looks correct to me

If you do menu/open user data folder does finder open in the right spot?

I can try a symlink tonight maybe. Is the symlink documents or surge?

I’m about to take a 2 week trip/dev break btw ... so not ignoring you if I go silent!

**Comment by baconpaul** [comment]
Oh and: Can you temporarily try it without the symlink just to be sure that’s not it? Fine if not but would help!

Thanks

**Comment by fredericcormier** [comment]
Accessing the data folder via the menu with the symlink opened the correct folder in dropbox
Plus, in the xml file, it looks like the value is set to 24.
Same problem without the symlink.

It's no big deal
Have a nice break

**Comment by baconpaul** [comment]
So another minor issue has held up my break and I took a look at this. There is a bug and it is a very annoying one. Fix is inbound. The writer writes invalid XML

But you can fix this by editing the xml and making
```
<default type="2" name="foobaz" value="132">
```

instead be valid and say 

```
<default type="2" name="foobaz" value="132"/>
```

see that trailing slash? Every time you save with beta7 it will be wrong. Code fix coming in and getting swept to nightlies right now.

**Comment by baconpaul** [comment]
OK fixed this. If you download any nightly after about an hour from now you'll be fine; or edit the xml and you'll also be fine.

so sorry! what a dumb bug :(

**Comment by fredericcormier** [comment]
Yes! Nightly build fixes the problem.

Thank you for the quick fix.
