### ISSUE TITLE
Second submenu selection borked (JUCE 8.0.2 related)

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#7813]
As shown by the following GIF.

![802menus](https://github.com/user-attachments/assets/dee387b5-fd3d-4aaf-90f5-3cd0ed27fc25)

**Comment by baconpaul** [comment]
This is caused by juce commit  515e9b9f89ed2af8e541d19493929c0be2556066

**Comment by baconpaul** [comment]
https://forum.juce.com/t/menu-item-dispatch-broken-on-windows-between-8-0-0-and-8-0-1-major-regression/63679
