### ISSUE TITLE
Surge on tablets (android)

### ISSUE THREAD

**Issue by Cianello** [surge-synthesizer/surge#7816]
Hi guys, is it possible to run Surge xt as a Stansalone on a tablet (android)? If yes how? Any advice? (I'm new here)
Thanks

**Comment by baconpaul** [comment]
Sorry we only run on windows macOS and Linux not android or iOS

**Comment by Cianello** [comment]
Ok. Thank you for the quick reply

Il mer 2 ott 2024, 01:52 Paul ***@***.***> ha scritto:
