### ISSUE TITLE
Ableton 12.1 is frrezing at the opening while is scanning last SURGE XT update.

### ISSUE THREAD

**Issue by Fardeau666** [surge-synthesizer/surge#7826]
**Bug Description:**

**Surge XT Version**
This information is found on the About screen, which you get to from the bottom right menu.

* Version:
* Plugin Type: [VST2, VST3, AU]
* Bitness: [32-bit or 64-bit]

**Reproduction Steps:**
2. Click on '...'
3. Scroll down to '...'

**Expected Behavior:**

**Screenshots:**
If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following!):**
 - OS: [e.g. Windows 10]
 - Host: [e.g. Bitwig, Logic, Cubase, Reaper]
 - Version: [e.g. 2.4]

**Additional Information:**

**Comment by mkruselj** [comment]
I cannot confirm this over here on Windows 10. You didn't leave any information about your machine...

**Comment by Fardeau666** [comment]
Sorry. I'm a french guy, discovering that forum interface. I use a MAC (ventura 13.7)... I suppose that i have to downgrade the SURGE XT firmware, but which one ?

**Comment by baconpaul** [comment]
Which version did you install? 

If you install 1.3.4 from our website we believe it scans live12 macOS. Im not on Ventura but we build for oses way older than that 

I can take a look this weekend - I think I have live 12.1 somewhere 

also curious if you have any other daws and if they run? Or if the surge standalone works for you?

**Comment by Fardeau666** [comment]
Thank you for your answer ! Yes, i have installed the 1.3.4. The old  one (i don't remember witch one) was workin perfectly. I've tried the 1.3.4 on Logic, and it's fine. I will try the stand alone version after work...

**Comment by baconpaul** [comment]
My guess is that live 12.1 has lost its document folder permission and that the scanner is suppressing the pop up.

can you look in macOS settings and make sure live has access to documents folders? I would start there

I remember Ventura can be more picky about when to ask permissions but I don’t remember the details.

you can always try 1.3.2 or earlier which are here https://github.com/surge-synthesizer/releases-xt/tags (don’t install 1.3.3 - it had a nasty bug)

**Comment by Fardeau666** [comment]
Thank you, baconpaul & mkruselj ! I've tried by installing the 1.3.2 version, and it works, now.... I certainly can not explain what is missing on the last firmware applied on ABLETON 12.1, but i'm so happy to play again with SURGE. A huge thank you for your kindness. Cyril.

**Comment by mkruselj** [comment]
If you now try installing 1.3.4 again, does it keep on working?

**Comment by Fardeau666** [comment]
Hello mkruselj. I've just tried the 1.3.4. again. That works perfectly with my system, now. Is it you who modified it ? A huge thank you, my dear !

**Comment by baconpaul** [comment]
We didn’t modify 134 (our installers are all immutable)

something in the 134 install process must have gone wrong which the 132 to 134 subsequently fixed. I think diagnosing what this was would require access to your system alas, so I’m going to close this as a mystery since it worked, but I am glad it worked and hope you enjoy making music with surge!
