### ISSUE TITLE
Small GUI bug with FX Bypass buttons

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#783]
![fx byp offset](https://user-images.githubusercontent.com/2393720/54478626-8c2fcf00-4814-11e9-9b99-2c3a1f4f2487.gif)

That's at 125% and 150% zoom. Some other zoom levels just seem to offset Send+Master button. W10 64-bit.

**Comment by itsmedavep** [comment]
I have a PR for the send+master button label. That is on this PR

https://github.com/surge-synthesizer/surge/pull/784

I cant repro your button frame jiggle issue on my mac unfortunately. So Im not sure if my PR will resolve that part of it. 

150%
![FX150](https://user-images.githubusercontent.com/11078351/54484893-1b50dd00-483d-11e9-915c-66f1d6152ebf.gif)

125%
![FX](https://user-images.githubusercontent.com/11078351/54484894-1b50dd00-483d-11e9-9e21-dd279e0e1696.gif)

**Comment by baconpaul** [comment]
Dave: Rememberer on mac it uses 2x resolution since you have a retina display. I find that if I edit src/mac/DisplayInfo.cpp and make BackingStore return 1.0 I can often repro windows issues more easily (since the windows HDPI API is too painful for me to support).

**Comment by itsmedavep** [comment]
Nice! TY for that bit of info. I’ll fold that into my testing regimen.

**Comment by baconpaul** [comment]
Np. Oh and svg should fix most of this. Once I’m back from vaca! (To which I now return :))

**Comment by itsmedavep** [comment]
![Testing@125x](https://user-images.githubusercontent.com/11078351/54570868-3f7ffb80-49ae-11e9-9d3f-236d1468bfc0.gif)


Ive tried what Paul suggested to get at 1x desktop usage. So the above gif is with returning 1 with BackingStore. Im unable to repro the button frame wiggle present in Evil's video.

**Comment by kzantow** [comment]
Pretty sure @itsmedavep fixed this one; please reopen if the latest nightly still seems to have the issue.

**Comment by mkruselj** [comment]
Unfortunately still happens in beta-8 over here :(

**Comment by mkruselj** [comment]
Fixed in 165844b nightly!

**Comment by baconpaul** [comment]
Awesome thanks! Closing.
