### ISSUE TITLE
Truncated numerator in Surge XT Tuning Editor Polar tab

### ISSUE THREAD

**Issue by ztnl** [surge-synthesizer/surge#7837]
Hi.

Here's a SCL loaded into the Surge XT Polar tab that's an 11-tone, Rank-2 MOS, formed from a chain of ten 11/7 reduced within a 2 period...

As we can see, although I've stretched the Polar tab to fill the screen to make this screenshot, since the ratios are 64-bit integer, the n/d are rather large and are not displayed in their entirety. 

They appear left-justified in the degrees fields, with the numerators cropped from three of the ratios.

Q: Might it be possible to have these fields automatically resize to fit, or manually drag-able, such that the n/d could be displayed in their entirety?

The way Polar displays these MOS modes is a thing of beauty really, so it would be kind of nice if it were able to fully display the ratios that make up the scales.

![2024-11-07 16_24_46-Tuning Editor - 11o7 MOS-11 (-1, 9)  P2](https://github.com/user-attachments/assets/120121a7-9899-4a63-b73c-36754e131d75)

**Comment by mkruselj** [comment]
It should be fairly straightforward to make those fields a bit wider (there's enough room to extend like 20 px perhaps), but there's really no telling how long of a text string a user would want to have displayed here...

**Comment by mkruselj** [comment]
This should be better. ow in the latest nightly.
