### ISSUE TITLE
Repeated block of code for Tone settings

### ISSUE THREAD

**Issue by Dave-Lowndes** [surge-synthesizer/surge#7839]
https://github.com/surge-synthesizer/surge/blob/16fc23961027c5f324bfb66b2a8b5c93d2209bd0/src/common/dsp/effects/chowdsp/ExciterEffect.cpp#L121

L121-124 are the same as 126-129

Is one block redundant, or should it be something else?

**Comment by baconpaul** [comment]
It is just redundantly copied it looks like to me

**Comment by Dave-Lowndes** [comment]
That's what I assumed, but I don't know the intention.

**Comment by baconpaul** [comment]
Yeah when you set those up you generally take one and copy it then configure the rest. Just looks like a code time harmless error

can the pvs thing make a pr to fix it too or do we need to do that by hand?
