### ISSUE TITLE
Both blocks of code in if/else are identical

### ISSUE THREAD

**Issue by Dave-Lowndes** [surge-synthesizer/surge#7840]
https://github.com/surge-synthesizer/surge/blob/16fc23961027c5f324bfb66b2a8b5c93d2209bd0/src/common/dsp/modulators/MSEGModulationHelper.cpp#L855

L855-865

Should one block be different, or should the condition be removed?

**Comment by baconpaul** [comment]
My guess is one block used to be different and that was wrong and the if should go but I want to walk the git blame history on this one

two neat finds. Do you have some static analysis tool or are you just a super careful reader? Either is welcome!

**Comment by baconpaul** [comment]
Oh awesome! And it has an open source friendly license 

well feel free to keep opening issues here or on short circuit or any of the sst libraries all of which are actively maintained! I’ll see if I can apply for an oss project license for surge too

thanks!
