### ISSUE TITLE
Duplicate header inclusion

### ISSUE THREAD

**Issue by Dave-Lowndes** [surge-synthesizer/surge#7847]
https://github.com/surge-synthesizer/surge/blob/16fc23961027c5f324bfb66b2a8b5c93d2209bd0/src/common/ModulatorPresetManager.cpp#L28

**Comment by mkruselj** [comment]
Thanks for all of these!

But frankly I think I'd prefer one overarching GitHub issue for all of these reports, one post per report. And then adding a checkbox to each. Could all be sorted out in one PR.

**Comment by Dave-Lowndes** [comment]
Do you have an example of what you're proposing?
I'm trying to group similar issues together, admittedly this one is trivial.

**Comment by baconpaul** [comment]
I’m fine with them one by one evil. Although I’ll probably close them with one pr

having them in a list issue or some such makes it easy to miss one

**Comment by baconpaul** [comment]
Oh @Dave-Lowndes - @mkruselj has discord and forum screen name evildragon hence my referring to him as such!

**Comment by baconpaul** [comment]
Actually let me just sweep them now.
