### ISSUE TITLE
Change Pitch Bend Cap from 24 to 48

### ISSUE THREAD

**Issue by gustebeast** [surge-synthesizer/surge#7849]
I go back and forth between using an MPE controller with a pitch bend range of 48 to a MIDI 1.0 controller with a standard bend range of 2. In order to have this work with synths like Dexed, I have a script which takes the 2 bend range from the 1.0 controller and compacts it to fit within a 48 bend range space. This way I can leave all the settings in place and quickly swap between instruments.

I see that Surge supports a bend range of 48 for handling MPE data, but the 1.0 bend range is capped at 24. Could this be raised to 48?

**Comment by baconpaul** [comment]
I wish there was a way to version automation streams more easily in the codebase. Automating pb depth is the only thing which would break if we changed the max. But it would indeed break 

something to ponder

**Comment by gustebeast** [comment]
I found a decent workaround so no rush, was just asking in case it was a simple "change this number to this other number" kind of change.
