### ISSUE TITLE
Surge fails to restore state properly on Live 10

### ISSUE THREAD

**Issue by kzantow** [surge-synthesizer/surge#785]
When reloading a project with multiple Surge instances in Live 10, it appears to fail to correctly load the state of the plugin somewhat randomly.

Environment: Win 7 64bit, Live 10

No specific steps to reproduce.

Expected: state is always properly restored.

This was from a KVR user, Guenon:
> Oh, one thing I should mention about Surge... These betas seem to have difficulties loading patches (or recalling the plugin states on project load) in Live 10 over here. I needed to load the project multiple times, and even then remove and reload some instances so that I could get them all play nice at the same time. This manifested as the failing instances loading in a state that caused loud overs/snaps instead of the intended sound. I can easily reproduce this in Live 10, almost every time. Even small test projects with a handful of Surge instances do this. Can't get it to fail like this on Reaper, and it also works in Live 8 on the same Win 7 64bit system, so this seems specific to Live 10.

More info:

It happens with any project, really. I even reproduced it with the init saw preset just now, without changing anything. If unlucky, it can happen right off the bat when you first load Surge. But these are the steps of what I just did:

1) Load Live 10
2) Load Surge on a track, no need to touch its contents afterwards
3) Record a short clip in the arrangement with some noodling (using init preset here)
4) Duplicate the track 3-4 times so that you have multiple Surges ready to play in the project
5) Save the project
6) Close the project ("New Live Set" in Live's File menu)
7) Open the project and try playing back what's there

If you repeat 6-7, there's a high probability some instances load bad and the project sounds like in my second example clip up there. Just now, I got it to corrupt the plugin states on two Surge instances on the second reload attempt like this ^

Anyway, sorry for the semi-off-topic, this is in no way to discourage OSCer trying Surge  :D ... I think it's great in any case. Just a warning on these current betas, to those who happen to be using them in Live 10. As mentioned, it seems this happens just in that one, and in Reaper and Live 8 it's clean.

https://www.kvraudio.com/forum/viewtopic.php?p=7347636#p7347636

**Comment by baconpaul** [comment]
The oversnaps are related to the same thing we see sometimes (and only sometimes) in logic when we go about switching bitrate. It hadn’t occurred to me that that would stream the state on and off the plugin but it makes sense. 

The click and overpop also occur when you have a SurgeSynth where the sample rate is never set.

So I wonder if the “stream from saved” has some effect like using a new instance and not setting it up correctly or somehow racing.

I’m not in a dev state for a while but wanted to add this comment here since it’s related to what I was investigating before I started my vacation.

**Comment by baconpaul** [comment]
Hey @kzantow I'm going to close this issue; the bad load was the uninitialized filter I fixed in 1.6 beta 8 and I think this is the exact same issue that is now resolved.
