### ISSUE TITLE
OpenMPT compatibility

### ISSUE THREAD

**Issue by nycos62** [surge-synthesizer/surge#7851]
hello, the vst3 is not recognize as a valid vst plugin in openMPT, any idea ?

**Comment by mkruselj** [comment]
This is probably a question for OpenMPT developers. Surge works in all other VST3 hosts...

**Comment by baconpaul** [comment]
A quick google seems to show openo mpt supports vst2 but not 3.

**Comment by nycos62** [comment]
it seems to handle vst3 as the plugin manager ask to browse .vst3 files, but nevermind, as @mkruselj told me , it should be on the OpenMPT side to ask, sorry to bother you

**Comment by baconpaul** [comment]
Gotcha 

and you are 64 bit and so on? 

But yeah. I would ask open mpt forum first but if we are doing something wrong happy to hear about it!

**Comment by nycos62** [comment]
btw, do you know a good free tracker ?

**Comment by baconpaul** [comment]
Oh also maybe a vst2 vst3 rehostrr could work. Modalics plugin buddy perhaps? https://www.modalics.com/products/plugin-buddy-free

**Comment by nycos62** [comment]
@baconpaul , hello, you were right for vst3, even if they browse the extension, OpenMPT does not support VST3 : (from OpenMPT dev)
"OpenMPT does not support VST3 plugins, and probably isn't going to anytime soon due to Steinberg's unfortunate decision to release the VST SDK under either a proprietary or GPL license. However, the upcoming OpenMPT 1.32 will support VST shell plugins, which means that you can use polac's [vst3shell](https://www.kvraudio.com/forum/viewtopic.php?t=565924) plugin in OpenMPT."

**Comment by baconpaul** [comment]
Yeah modalics plugin buddy will do the same as will kishview elements 

let the open mpt devs know that if they want to support clap I’m happy to help them connect with the clap community (I’m a reviewer and committee on the clap standard which has a much cleaner license than vst3)
