### ISSUE TITLE
Surge Uninstaller app for macOS

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#788]
A Surge uninstaller for macOS, Linux, Windows.

What it does (on macOS)

Wipes 
`~/Library/Application Support/Surge`
`/Library/Application Support/Surge`

removes
`~/Library/Audio/Plug-Ins/Components/Surge.component`
`~/Library/Audio/Plug-Ins/VST/Surge.vst`
`~/Library/Audio/Plug-Ins/VST3/Surge.vst3`
`/Library/Audio/Plug-Ins/Components/Surge.component`
`/Library/Audio/Plug-Ins/VST/Surge.vst`
`/Library/Audio/Plug-Ins/VST3/Surge.vst3`

And the same or similar for Windows. Does not touch `~/Documents/Surge` .

This would help immensely with people (on KVR, etc) running into the "Well err something's wrong" installer report :)

And it's a nice thing to do overall.

**Comment by baconpaul** [comment]
Seems innosetup adds an uninstaller for surge
On Linux since we ship a deb you can just `apt-get remove` it once you install it
So this is mac only I think
Don't really have good instinct on what mac uninstaller semantics should be.

**Comment by baconpaul** [comment]
pig-info does this for you as does homebrew so i'm gonna close it.
