### ISSUE TITLE
Add unicode support to wavetable oscillator name

### ISSUE THREAD

**Issue by nuoun** [surge-synthesizer/surge#7899]
The wavetable name in the WT oscillator does not display unicode characters and treats UTF-8 encoded sequences as separate characters, would be neat if that can be fixed.

**Comment by baconpaul** [comment]
![Screenshot 2024-12-03 at 6 59 44 PM](https://github.com/user-attachments/assets/a2caf2bd-a82c-4811-8d58-663277a2578a)
