### ISSUE TITLE
Can we change the GUI?

### ISSUE THREAD

**Issue by michaelohagan912** [surge-synthesizer/surge#791]
I was wondering how difficult it would be to change the GUI of surge.

it would be nice to see some different color schemes, there's something about surges GUI that I find difficult to look at for to long.

I've done some decent GUI's in Reaktor and I'm willing to consider chipping in on a new color scheme or organization of the surge GUI if it's not too much to do.

can the graphics be extracted for color editing?

can the overall layout be adjusted?

I would like to see the 3 oscillators side by side across the top left instead of selected one at a time.

If this is possible and people are willing to consider doing it I could create some mock ups of possible solution to the  cluttered feeling of the GUI.

**Comment by baconpaul** [comment]
So it’s really quite hard. The assets are mostly separate files but they layout right now is c++ constants intermixed with the code as are a couple of colors. And things like the multi select buttons require pixel accurate placement of the different states in the assets. It’s not really very flexible at all. Vstgui is also in the mix pretty heavily which adds complexity.

Our plan for 1.6 is to keep the current GUI but use vector versions of the assets for all the components (that’s on the svg branch @itsmedavep and I have been working on). Then maybe once that’s stable move the layout out of the c++ if there’s a desire and assets for skinning.

Hope this helps. Folks who hang out in the design room on slack also have thoughts I know.

**Comment by baconpaul** [comment]
I added #810 to explain the core concern and my plan if I were to tackle this.

**Comment by baconpaul** [comment]
Linking to #1117

**Comment by baconpaul** [comment]
Closing this one since it is covered in the s++a1 milestone. @michaelohagan912 if you are still interested in that, check out the various s++ issues and/pr hope into our slack!
