### ISSUE TITLE
No success using Program Change in Ableton Live 10

### ISSUE THREAD

**Issue by espegermen** [surge-synthesizer/surge#7910]
Hi,
has anyone had success using program change messages in Ableton Live 10?
I believe I have followed the instructions but nothing happens.
Thanks!

**Comment by baconpaul** [comment]
Vst3 doesn’t support program change. So I very much doubt this will work.

**Comment by mkruselj** [comment]
VST3 does support Program Change (in a weird but possible way) but Live does not support sending it to VST3.

**Comment by espegermen** [comment]
Thank you so much @baconpaul and @mkruselj for the information. 
I am disappointed since I wouldn't imagine that it is unsupported by vst3.
So, this pretty much means for me that in Ableton "Live" for Windows I cannot actually perform "live"....
Actually, Ableton's internal instruments also do not support a way to change presets from a controller. Am I missing something here or it is quite a turn down for live performances?.

**Comment by mkruselj** [comment]
You could try using Chain Selector device. Program Change in Live is AFAIK only tied to the beginning of a clip.

If you want a better Live, check out Bitwig.

**Comment by espegermen** [comment]
Thanks @mkruselj! I have tried Chain Selector, but it not satisfying to be honest.
Yes, program change is only at the beginning of the clip, but for me was working good (when I used macOS).
Thanks for the recommendation, I will try Bitwig!.
