### ISSUE TITLE
Surgepy: Contextual parameters not updated when parent parameter changes

### ISSUE THREAD

**Issue by cwalo** [surge-synthesizer/surge#7943]
**Bug Description:**
When setting a parent parameter via surgepy, I'm not seeing its child parameters updated. For example, changing osc1_type to window (7), it is expected that osc1_p1 now controls the formant. As a result, attempting to set the formant either has no effect (if outside of min/max range) or is incorrect altogether. I assume FX suffer the same issue.

Note that loading a patch from an fxp behaves as expected.

I traced the codepath a bit and it looks like `setParameter01` _should_ be calling `storage.getPatch().update_controls()`, but maybe it's not?

**Surge XT Version**
This information is found on the About screen, which you get to from the bottom right menu.

* Version: 1.3.4 / surgepy @ main
* Plugin Type: [VST2, VST3, AU]
* Bitness: 64 bit

**Reproduction Steps:**
```
import surgepy
import surgepy.constants as srco
    
surge = surgepy.createSurge(44100)
    
patch = surge.getPatch()
osc = patch['scene'][0]['osc'][0]
osc_type = osc['type']
p1 = osc['p'][1] # Should be formant after changing osc type
    
surge.setParamVal(osc_type, srco.ot_window)
surge.setParamVal(p1, -32) # set formant to -32 semitones
print(surge.getParamInfo(osc_type)) # value: 7, display: Window (correct)
print(surge.getParamInfo(p1)) # expecting value: -32, display: Formant, but is actually Width
```
Output:
```
Parameter name: A Osc 1 Type
Parameter value: 7
Parameter min: 0
Parameter max: 11
Parameter default: 0
Parameter value type: int
Parameter display value: Window

Parameter name: A Osc 1 Width 1 // Expecting Formant
Parameter value: 0
Parameter min: 0
Parameter max: 1
Parameter default: 0.5
Parameter value type: float
Parameter display value: 0.00 %
```

Similarly dumping the control group after changing osc type:
```
cg_OSC = surge.getControlGroup(srco.cg_OSC)
osc1 = cg_OSC.getEntries()[0]
for param in osc1.getParams():
    print(f"n: {param.getName()}, v: {surge.getParamVal(param)}")
```
Output:
```
n: Osc 1 Type, v: 7.0
n: Osc 1 Octave, v: -1.0
n: Osc 1 Pitch, v: 0.0
n: Osc 1 Shape, v: 0.0
n: Osc 1 Width 1, v: 0.0
n: Osc 1 Width 2, v: 0.32946398854255676
n: Osc 1 Sub Mix, v: 1.0
n: Osc 1 Sync, v: 0.0
n: Osc 1 Unison Detune, v: 0.20000000298023224
n: Osc 1 Unison Voices, v: 1.0
n: Osc 1 Keytrack, v: 1.0
n: Osc 1 Retrigger, v: 1.0
```
**Expected Behavior:**
Contextual child parameters are updated when a parent parameter changes.

**Screenshots:**
N/A

**Computer Information (please complete the following!):**
 - OS: macOS 15.1.1
 - Host: Ableton
 - Version: 12

**Additional Information:**

**Comment by baconpaul** [comment]
The answer here i think is that: osc and fx type changes are special in that the parameter set enques a change for the audio thread and so they take effect in the next call to process (roughly)

try running a single block after these set params 

There is a function which does it when audio is not running called something like unsafe something which the vst ui will call when audio isn’t running. But surgepy sets audio running to true

**Comment by cwalo** [comment]
Ah, that did the trick, with one caveat - the parameter names aren't updated unless you make another call to `getPatch()`, presumably to rebuild the dictionary, and get new named params from the respective path. 
 
Without refresh:
```
Parameter name: A Osc 1 Width 1 // Expecting A Osc 1 Formant
Parameter value: -32
Parameter min: -60
Parameter max: 60
Parameter default: 0
Parameter value type: float
Parameter display value: -32.00 semitones
```

With refresh:
```
surge = surgepy.createSurge(44100)
patch = surge.getPatch()
osc = patch['scene'][0]['osc'][0]
osc_type = osc['type']
p1 = osc['p'][1] # Should be formant after changing osc type

# set params
surge.setParamVal(osc_type, srco.ot_window)
surge.process() # process one block to refresh conditional params
surge.setParamVal(p1, -32)

# refresh patch
patch = surge.getPatch()
osc = patch['scene'][0]['osc'][0]
p1 = osc['p'][1]

# now prints correct param info
print(surge.getParamInfo(p1))
```
```
Parameter name: A Osc 1 Formant
Parameter value: -32
Parameter min: -60
Parameter max: 60
Parameter default: 0
Parameter value type: float
Parameter display value: -32.00 semitones
```

I think I can work with this though - reliable values and min/max are the most important anyway. I'm using surge for ML research, so creating a reliable parameter map has been a bit of a challenge. Is it fair to say that osc/fx child params are the only conditional parameters (ignoring mod routing for now)? Thanks again for the help.

**Comment by baconpaul** [comment]
Yes fx and Osc are the only conditional param drivers.

I’ll close this issue if that’s ok? Please reopen if anything else is needed

**Comment by cwalo** [comment]
Yep, I can do the honors. Also just joined the discord so will probably throw some questions there as they come up without necessarily formalizing an issue.
