### ISSUE TITLE
Rearrange FX

### ISSUE THREAD

**Issue by kzantow** [surge-synthesizer/surge#798]
A slack user (zerofox97) suggested he would like to be able to rearrange the FX section, e.g.:
![image](https://user-images.githubusercontent.com/3009477/55350255-a4952000-5489-11e9-8443-f0ef66aba597.png)

**Comment by baconpaul** [comment]
I think this is a dup of https://github.com/surge-synthesizer/surge/issues/309 basically. Or is there something else to it?

**Comment by baconpaul** [comment]
Yeah this is just a #309 dup I am almost sure. Closing it. Please reopen if it isn't. Also look at #309 for how I plan to solve it!

**Comment by baconpaul** [comment]
![CopyPaste](https://user-images.githubusercontent.com/13387561/61065030-e01c8000-a3d0-11e9-90e4-5320fb991613.gif)

in the nightlies now.
