### ISSUE TITLE
MPE Release Velocity

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#811]
From KVR:

>> baconpaul wrote: ↑Sun Mar 31, 2019 7:33 pm
>>> Ah_Dziz wrote: ↑Sun Mar 31, 2019 7:18 pm
 Also, does the MPE implementation include release velocity?
>>Reading the code, the velocity sent with note off goes through to the synth and gets sent to the voice in the release cycle. I'm honestly not sure how you'd use this in surge easily but haven't played with it or even thought to! Would love to know what you find. The VST2 and AU are better with MPE than the VST3 at this point.
>If the release velocity could be added to the mod matrix, it’s incredibly useful. Mostly for modifying effects to change how long a delay keeps going or adding a longer release with a slight pitch drop if you pull your finger off very fast, but having no release at all if you lift your fingers gently.

**Comment by baconpaul** [comment]
Again from KVR

>Thanks baconpaul! 
> It’s slightly tricky to implement sometimes since many controllers send a note-on with a velocity of zero in place of a note-off with a velocity of it’s own. Others do send a proper note off, but just use an arbitrary fixed value for the velocity.
>
>This has caused me troubles in the past when doing Kontakt scripting and stuff. 
>
>Thanks for even checking it out. It seems to be left out pretty often in the implementation of MPE.

**Comment by mkruselj** [comment]
Release velocity can be useful even outside of MPE mode.

**Comment by Kwurqx** [comment]
Maybe RENAME Issue #811 to a more general:

**Note-Off (Release) Velocity**

I have (and had) several synths that offer(ed) Release Velocity (active or passive):

- Kawai K5
- Kurzweil K2000
- General Music S2R  (the S2/S3 Keyboard has both Note-off Velocity and Polyphonic aftertouch!)

I find it very usefull. Especially to modulate String/Pad type Release times. Generally you can use Note-On Velocity to modulate the Attack (and/or Decay). But few synth engines offer Note-off Velocity to control the Release (e.g. AMP, FILTER, PITCH).

And since it's the PASSIVE bit (the synth engine) and the Note-off Velocity modulation is optional (like all modulation), there's no need to worry to much about (in)compatibility of all sorts of MIDI controllers.

**Comment by baconpaul** [comment]
Yeah I need to figure out where to put this. I was thinking of having one of the controller spots mappable to note off but they are not per note. Veclocity is treated a little specially in a few spots also. This one is a touch tricky

**Comment by mkruselj** [comment]
Maybe a suggestion:

Could be a good idea to merge Poly AT and Channel AT into a single modulator source called Aftertouch (Surge should be smart enough to recognize which one it received and act upon it). Then you could scoot Keytrack one slot to the right, and on its place put Rel Velocity.

The only possible problem that I can see here is current patches that have different modulation assignments for PAT vs CAT, or they have been assigned to a single target, but with different mod amounts...

**Comment by baconpaul** [comment]
I’ll look. I think poly AT is voice level and channel AT is scene level though (which makes sense) which means they have not just different mappings but different mapabilities.

**Comment by baconpaul** [comment]
So here's a release velocity question I could use an answer too

Imagine that you can map release velocity so that you can adjust pitch based on how you release. Easy enough.

Now you are playing with the sustain pedal down. You release. Does the release velocity apply when you let go of the key (which is when the velocity is delivered) or when you let go of the pedal? Either is doable but curious which we want.

**Comment by baconpaul** [comment]
I'm going with apply release velocity modulation at the later of release or pedal up with the release velocity observed at release. Seems the most natural. I actually have it plumbed through the DSP engine already! Now for the UI hack hack hack work...

**Comment by baconpaul** [comment]
https://youtu.be/-_FUjQL0up0 shows how I implemented this.
