### ISSUE TITLE
Chan AT cannot modulate SLFOs, when it should

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#814]
SLFOs are monophonic and as such can be modulated by monophonic mod sources like modwheel, pitch bend, channel aftertouch.

Except when you select Chan AT to assign modulations, LFO sliders aren't blue and cannot be used to assign channel aftertouch to modulate LFO parameters.

Please fix :)

**Comment by baconpaul** [comment]
Hey I actually don’t have a device which generates channel aftertouch. Do you have a one track standard midi file with some chanat it it which you could attach to this for testing? Thanks!

Probably not a hard fix if we can test it. Probably not that hard if we can’t but I’d sooner test if if we can!

**Comment by baconpaul** [comment]
OK actually taking a quick look at the code I don't see any obvious difference in the implementation between the mod wheel and the channel at so really do need a way to test this. Can you play something which channel AT on - a simple track - and just export it as standard midi, zip it, and attach it here @mkruselj? Thanks so much!

**Comment by mkruselj** [comment]
You don't have a DAW with piano roll where you can draw channel AT events? Well, ok... Here's middle C with some AT happening. :)


[channel AT.zip](https://github.com/surge-synthesizer/surge/files/3048690/channel.AT.zip)

**Comment by baconpaul** [comment]
Yeah I got that. But reading the code there’s no difference between modwheel and chan At I saw so wanted to run it with debug to find out why the modulator is set up differently. Do you see a difference in the code? It was hard for me to spot.

And duh yeah of course I could have drawn it in logic. Sorry!

**Comment by mkruselj** [comment]
I'm not even sure where in the code to look. And it'd probably all be Chinese to me since I don't know how things are structured here (and am basically pretty lame at C/C++ unfortunately) :(

**Comment by baconpaul** [comment]
Yeah I was looking for that and did t see it. There are some ifs that change config but they were opaque 

But now I can run with chan At I just need to read the code and fix it - won’t be hard. Of course I could have done that myself duh! I create midi so rarely on screen (vs edit) that it just didn’t occur to me this morning. Duh!

Anyway I’ll put it on the list and we can fix it. Will be good to figure out ;)

**Comment by mkruselj** [comment]
Great - thanks! :)

**Comment by baconpaul** [comment]
OK well this is much easier than I thought now I actually ran it and saw it.

src/common/ModulationSrc.h explicitly tagged ms_aftertouch as scene level. If I change that then you get the same behavior as pitchBend. I reviewed the pitchblende implementation and the channel at implementation in both MPE and non MPE mode and both are correct. So I think this is just a wrong setting from the first implementations of MPE.

Let me put in a PR and sleep on this. Any edge cases where we wouldn't want this?

**Comment by baconpaul** [comment]
OK swept this. Nightlies should have it in 30 minutes or so. Enjoy your weekend

**Comment by baconpaul** [comment]
Hey I just remembered this change this morning for some reason.

Turns out this was “wrong” in MPE mode (which is the same as #1221) but “right” in non-MPE mode so I want to couple this to 1221 which I really want to try and fix in 1.6.4 properly so we can get the diff linked up.
