### ISSUE TITLE
Add wavetable support for the .uhm scripting format

### ISSUE THREAD

**Issue by bmrzycki** [surge-synthesizer/surge#815]
The **u**-**h**e **m**ath (uhm) wavetable format is a scripting language to procedurally generate different kinds of wavetables with short text files. This format has considerable flexiblity for traditional (lowpass, morphing) to other less-traditional (fm, karplus-strong) wavetable morphing options.

Here are relevant links regarding the format in the first synth supporting it, u-he's Hive:
https://uhedownloads-heckmannaudiogmb.netdna-ssl.com/betas/public/hive/Hive_Wavetable_Script_Language_WIP.pdf
https://www.kvraudio.com/forum/viewtopic.php?f=31&t=511390
https://www.kvraudio.com/forum/viewtopic.php?f=31&t=511639
https://www.kvraudio.com/forum/viewtopic.php?f=31&t=511486
https://www.kvraudio.com/forum/viewtopic.php?f=31&t=517197

A procedural python generator to create new waveforms (by KVR user drzhnn):
https://www.kvraudio.com/forum/download/file.php?id=19660

**Comment by baconpaul** [comment]
Ahh gotcha. So it is basically a mini language for waveforms. Kinda like a teensy subset of csound orc files or what not. Cool.

So two thoughts come up about integrating this into surge

1: Is the spec an open spec? The licensure of the language isn't clear?
2: And is there software that goes UHM -> collection of wave data structures?

If the answer is "yes" and "yes" then this is almost trivial - especially if the code that goes UHM -> Data structures is standalone C++ code in a git module we can just submodule in. You could at least offline generate a .wt. If the answer is "yes" and "no" this is hard. If the answer is "no" and "yes|no" then I don't think we could integrate this.

Is there a good way to get in touch with the author of the spec to ask him/her these sorts of questions? I'd be happy to chat with him/her these kinda questions on kvr or on GitHub.

I must say: It looks awfully cool and looks quite a lot like what I've been doing in iPython notebooks to render stupid .wt files for surge. Would be lovely to have this feature if it is feasible.

**Comment by bmrzycki** [comment]
Hi @baconpaul, thanks for the feedback. Here's the best answers I have to your questions:

1. I don't actually know. The author, [Urs Heckmann of u-he](https://u-he.com/about/team/urs.html), is a really good guy and is often open about things like this. But I agree we need a concrete answer before any work can proceed. I have a private PM to him but he hasn't replied yet. I do recall Urs mentioning in a KVR post he was interested in nurturing the environment for uhm beyond Hive so I am hopeful here.

2. Externally, not that I am aware of. The design of uhm is only about 6-8 months ond and only exists in u-he's Hive, and a beta version of Zebra2 to generate uhm -> wav.  I have a path today to get this into .WT using uhm (text editor) -> Zebra2 beta -> wav -> surge wt pyhon script but it's a bit clunky. It's possible this issue may facilitate some subset of C++ routines for uhm being open-sourced. But I am only speculating at this point.

The best way to get in touch with Urs is probably the u-he subforum on KVR with a new post. He has PMs disabled there due to overwhelming messages. And I agree, it would be wonderful if we could start an ecosystem for uhm, they're so much more convenient to play with and share than giant binary blobs of tables.

**Comment by baconpaul** [comment]
OK super useful. I summarized my questions on KVR just now

https://www.kvraudio.com/forum/viewtopic.php?f=31&t=523235

**Comment by baconpaul** [comment]
Oh urs wrote back right away saying

> We have no plans to open source/open spec it, but we're also neither totally against it. We just absolutely have no time and resources to do/support anything in that direction.

> Some functionality (filters, certain interpolators) are certainly regarded as company secrets and will not be disclosed.

So I think your path through zebra and python is probably best.  If there’s something we can do here with the python scripts to make that easier let me know - happy to help - but considering above I’m going to close this issue.

Thanks!

**Comment by bmrzycki** [comment]
Thanks @baconpaul for the thorough follow-up. I agree with your reasoning here. Thanks again for your work on Surge! :)
