### ISSUE TITLE
Preset name at the top of the window does not change ( until i close and reopen GUI).. i'm on FL STudio 20 on win10

### ISSUE THREAD

**Issue by marlboonyer** [surge-synthesizer/surge#817]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10]
 - Host [e.g. bitwig, logic]
 - Version [e.g. 2.4]

**Additional context**

**Comment by baconpaul** [comment]
Few questions

1: What version of surge are you running (what does help/about say)
2: How are you changing the preset? Like what action do you take to make the preset change?
3: And which name exactly isn't changing? Where at the top of the window? 

I think you might mean "the name on the FL Studio Window Decoration" so you get a surge which says "FooBaz" in the patch browser but the FL Studio name is still "init".  If that's the case I think this is a dup of #405 

but if its something else please let us know!

**Comment by marlboonyer** [comment]
1. It is 1.6.0-beta-82. By selecting the preset drop down...3. As shown here: https://snag.gy/lr8wYO.jpghth,marl
    On Friday, 5 April 2019, 22:21:18 BST, Paul <notifications@github.com> wrote:  
 
 
Few questions

1: What version of surge are you running (what does help/about say)
2: How are you changing the preset? Like what action do you take to make the preset change?
3: And which name exactly isn't changing? Where at the top of the window?

I think you might mean "the name on the FL Studio Window Decoration" so you get a surge which says "FooBaz" in the patch browser but the FL Studio name is still "init". If that's the case I think this is a dup of #405

but if its something else please let us know!

**Comment by baconpaul** [comment]
Thanks

Here’s the url without GitHub mangling it

https://snag.gy/lr8wYO.jpg

I’m not a fruity loops user. What is wrong with that screenshot? The patch name seems clearly displayed.  Sorry it I am missing something obvious

**Comment by marlboonyer** [comment]
The problem is when i select a different patch the name does NOT change. i know it's probably a small thing. that's how it has been for last few versions.

    On Friday, 5 April 2019, 23:50:55 BST, Paul <notifications@github.com> wrote:  
 
 
Thanks

Here’s the url without GitHub mangling it

https://snag.gy/lr8wYO.jpg

I’m not a fruity loops user. What is wrong with that screenshot? The patch name seems clearly displayed. Sorry it I am missing something obvious

**Comment by baconpaul** [comment]
Huh wierd - obviously it changes for us!

Next time I fire up my windows vm I will take a look

Thanks!

**Comment by baconpaul** [comment]
![FLPatch](https://user-images.githubusercontent.com/13387561/55735768-00aef580-59f0-11e9-9abc-4b2f3fe3172c.gif)

OK that's a gif of me running the Surge VST3 in FL20 on Windows 10. Click the patch button or change the name with menu and it clearly changes.

So I guess I don't understand what the bug is. Do you see the same thing?

Thanks

**Comment by baconpaul** [comment]
Hey just a note that @itsmedavep on slack said was able to wedge the Mac host into a similar state today - but we aren’t quite sure how yet. Tagging him here so he can add details when he has a chance

**Comment by itsmedavep** [comment]
I see this too. I havent been able to nail down the exact steps as it seems somewhat intermittent.

Here is the detail:

Logic Pro X <- AU format plug

Surge (for my repro was built with this version baconpaul:render-with-svg)

Steps to repro (roughly):

1) Zoom biggest
2) Reset zoom to 100%
3) Zoom biggest again 

Periodically see this
![zoom](https://user-images.githubusercontent.com/11078351/56209464-3cae1000-6019-11e9-864c-59359c9d3136.gif)

For a while I was convinced that switching focus away from Surge and back after zooming contributed to the issue. Unfortunately, this one seems very intermittent so I can quite nail it down. 

<img width="552" alt="Screen Shot 2019-04-16 at 7 30 15 AM" src="https://user-images.githubusercontent.com/11078351/56209577-8b5baa00-6019-11e9-8c6c-fdb02b20eb4c.png">

<img width="551" alt="Screen Shot 2019-04-16 at 7 30 32 AM" src="https://user-images.githubusercontent.com/11078351/56209588-91518b00-6019-11e9-8fcd-cc0d936b7e2d.png">

**Comment by baconpaul** [comment]
So I still can't reproduce this but looking at the code I do see a couple of places where maybe if your system was running the idle thread ahead of the patch load thread you could miss an update. I'll try and figure out an appropriate update.

**Comment by baconpaul** [comment]
@marlboonyer as I noted on KVR also, I have put a change into the nightlies that, even though I can't reproduce this, fixes the one case I could see that might cause it. (Are you running on a lower power or smaller CPU count computer btw? That could lead to the race condition I see coming up more).

If you could try a nightly I would appreciate it. I want to cut 1.6.0 this weekend (and will include this change whether you test it or not) but would love to know if this fixes it for the release notes.

Thanks

**Comment by marlboonyer** [comment]
i am not technically knowledgeable to answer some of your points.
all I can say is , i am on windows 10 running FL Studio 20 and when i change a preset via the Patch Browser at the top of the surge window the preset changes but the name does not.
when i close the window and then re-open it, the change IS displayed.
i also have a problem where i am unable to zoom the window other than it's default size. Even though it is obvious that i have plenty of space on the monitor..
if you require any technical info you'll have to give me instruction, i know nothing about coding ets..
marl

**Comment by baconpaul** [comment]
OK. Well tell you what I think I have a fix in 1.6.0 which I'm about to release. Why don't I do that, you download the new version, and then we revisit this if it is still broken. Sound good?

And thanks!

**Comment by marlboonyer** [comment]
yep, no probs...

**Comment by baconpaul** [comment]
Oh and on the zoom thing: FL20 has a problem that VST2 can't zoom (technically the VST2 api does not support resizable UIs and FL is strict about that). If you want zoom in FL you should use the VST3.

**Comment by marlboonyer** [comment]
for the life of me i don't know why i didn't see the vst3 version previously.
so, it works as expected in FL 20, the preset name changes. however the resizing issue remains.
i think that is down to my old monitors so it is probably not an issue for users with more current displays...

**Comment by baconpaul** [comment]
Is that with 1.6.0 or 1.6 beta 9? There are some changes for 1.6.0 which may help. But if you are on 1.6.0 can you give me a bit more idea about what the resize problem is? FL20 on Win10 is one of my "test occasionally" DAWs and I can resize pretty seamlessly in it with the VST3.

Thanks!

**Comment by marlboonyer** [comment]
i installed your latest build earlier... vst2 still with preset name bug. 
vst3 works fine.
this is the error i get when attempting to zoom:
"Surge limits zoom levels so as not to grow Surge larger than your available screen. Your screen size is 1024x768 and your target zoom os 125% would be too large.
Surge is choosing the largest fitting zoom 100%"

**Comment by baconpaul** [comment]
Oh right. So that's just us being conservative. We found that window decorations eat an unpredictable amount of space so we set max surge size to about 90% of pixel size available. In your case that means at 1024x768 (the screen size surge was originally designed for btw!) you don't get zoom alas.

Very useful to know that the VST2 is the one showing the preset name bug. I'll leave this open and try and reproduce it at some point. Appreciate that!

**Comment by baconpaul** [comment]
From KVR:

baconpaul wrote: ↑Sun Jun 09, 2019 5:02 pm
Dandruff wrote: ↑Sun Jun 09, 2019 4:54 pm
Another issue:

When the hosts audio engine isn't running, the Surge UI is not getting updated (when choosing different patch for example).
Thanks - can you let me know which daw which os and which host flavor? Then I’ll log it as a github issue unless you want to.
REAPER 5.978/x64 on Windows 8.1 Pro

Options/Preferences/Audio/Playback: Run FX when stopped = disabled


Just change a patch in Surge when playback is stopped and the track is not record/monitor-armed ...
