### ISSUE TITLE
Slider Dragging: Create a "sweet spot" for the drag to send values

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#819]
Today in Surge, if you drag a slider thumb and your mouse cursor goes beyond the extents of slider track and then drag in the opposite direction it will immediately begin to update the values. 

Essentially, you can drag waaaay right/left and when you drag in the opposing direction it will update values immediately. 

This video probably does a better job explaining it than I am:
![Mouse](https://user-images.githubusercontent.com/11078351/55670931-b7c03b00-584f-11e9-9380-55eae4b66fb0.gif)

My expectation would be that the slider would remain at the extents of the slider track until your mouse cursor enters the bounds (AKA sweet spot) of the slider track. Once within the bounds of the slider track it would start to update the values again.

Again, Im probably doing a poor job of an explanation. Here is a video to illustrate my expectation:

![Mouse_expectation](https://user-images.githubusercontent.com/11078351/55670967-11c10080-5850-11e9-9684-6d65d333384a.gif)

**Comment by itsmedavep** [comment]
Hey @fonkle IDK if your interested in wadding into this one, but I thought of you since you fixed up the mouse drag speed so well!

Not trying to put you to work or anything LOL. Just thought you may be interested as it's the general vicinity of stuff you were just working on.

**Comment by fonkle** [comment]
I was going to suggest having a look at exactly this next, since it's the next biggest issue I ran into using Surge :)

It should only react to movement within the boundary of the slider imo, and ignore everything outside?

I'll take a look to see if I am able to fix that.

**Comment by baconpaul** [comment]
In exact mode that’s true
In slow mode it sort of has an expanded range and you do want to react to those deltas

I think the problem is if you are beyond Max it stops accumulating delta to eat when you change direction 

Would be cool to fix this yeah! Thanks!

**Comment by fonkle** [comment]
I think the original idea of the sliders was to abstract mouse movement by hiding the cursor and moving the knob. That way, the knob could be moved in different speeds independent from the speed of the mouse cursor. Increased speed as well as precision and use of modifier keys.

The exact mode however maps the slider speed 1:1 to the mouse movement, thus eliminating the independent slider speed and all its advantages. Although it doesn't feel like a slider, it is possible to start dragging it from outside the knob, which feels weird. Also, when the mouse cursor leaves the slider range the mapping to the mouse cursor is distorted.

The _Exact_ slider was meant as a fix to make Surge better usable in Linux. The next step would be to either improve the fix or to improve the sliders :). Therefore I am now considering how the sliders _should_ work, which raises some questions:

1. Are there any plans for a UI rewrite, possibly using a framework other than VSTGUI?
2. Does any form of design-document exist in which the concept of the original sliders was defined?
2. Have you already decided if the sliders _should_ work independent of the -hidden- mouse cursor?

Thx!

**Comment by baconpaul** [comment]
1. Not with the 1.6 family 
2. Not that we have. Maybe in a 2006 doc in the original plan
3. None of us on Mac liked the hidden cursor. That’s not a decision per se but may inform your choice

Happy for design proposals. And happy for this to be changed. As you’ve seen doing user preference stuff isn’t that hard if we aren’t sure

**Comment by fonkle** [comment]
Thanks @baconpaul, I'll try some stuff out.

So to be clear: you guys (on Mac) use the indirect sliders (Classic / Slow / Medium) with a _visible_ mouse cursor that moves faster than the knob itself? Do you use it with a mouse, touchscreen or tablet? Or even something else?

**Comment by baconpaul** [comment]
Yes that’s right. I use it with Mac trackpad variations. Dave checked logic and realized logic does the same. Feels pretty intuitive to me.

**Comment by fonkle** [comment]
Ok, I am just trying to understand, since all videos I can find about Surge have the mouse cursor disappear when using sliders, including this one on Mac:

https://www.youtube.com/watch?v=YSJ9cpLKJoA&t=189s

Note that while he drags the sliders, the mouse cursor stays put and reappears at the exact position where it was before sliding started. That would prevent the issue with moving the mouse over the edge of the screen from occurring...?

So, to be honest, I think the sliders in the videos actually look like the best solution so far. Could it be possible that a hiding mouse cursor _would_ work _if_ the cursor wouldn't move while being hidden and sliding?

**Comment by fonkle** [comment]
All videos I can find about Logic Pro hide the mouse cursor as well...?

**Comment by itsmedavep** [comment]
That video is of Abelton and Surge 1.5x I think. But the bottom .gif I posted up top is how the sliders work in Logic. Those are the native sliders for track volume though. Not sliders in Surge. I was just using it to illustrate what my preference for interaction was. 

Now having said that, my preference is to not hide the cursor on drag but thats just a bias. 

The issue that I ran into was a usability concern when dragging and disappearing the slider if you hit the bounds of your monitor it appeared as though the slider got stuck if you weren't paying close attention. 

This .gif kinda illustrates the issue. 

![No_Cursor](https://user-images.githubusercontent.com/11078351/55914070-d6099c00-5bab-11e9-9ed0-3d37aeb19d0e.gif)

Hope that helps a bit!

**Comment by itsmedavep** [comment]
Oh BTW here is a video of dragging a slider in Surge loaded in Logic.

![Logic_mouse](https://user-images.githubusercontent.com/11078351/55914327-7495fd00-5bac-11e9-8166-74aabd97ab68.gif)

**Comment by fonkle** [comment]
I see, but that is no good i.m.o. It **must** feel sluggish / laggy to move that slider.

I have just tested the Windows version some more extensively and the sliders work beautifully there. It has none of the issues Mac + Linux have, and I think I understand why: if the cursor is hidden **and** the actual mouse does not move until the slider knob is finished, all works fine. If I then go beyond the range of the slider, the knob just stays at the end and starts moving as soon as the mouse reverses. It feels great :).

Now to implement that in Mac seems relatively easy, assuming the Cursor can be hidden / shown and positioned using the Apple APIs.

In Linux on the other hand, it appears a lot harder since the different X toolkits seem to have differing implementations of mouse cursor handling. I would at least have to read up on those. To be continued.

**Comment by itsmedavep** [comment]
Sorry, what bit feels no good? 

Also IMO hiding the mouse cursor (which doesn't currently happen on mac) introduces a usability issue that doesn't exist now. Thus making things worse overall. I would kindly suggest _not making_ that change. 

I am testing this on a MacBook pro with using a trackpad. 

The sluggishness of the slider is not what this issue is about. Or rather it is not why I opened the issue. 

The reason I opened the issue is that in the very first .gif I posted the behavior feels wrong. I then posted my desired behavior. 

Again, my expectation is for it to work the way it does in the video I posted of **Logic's** track volume slider.

**Comment by fonkle** [comment]
You're right. It diverts from your original 'sweet spot' issue you opened.

The logic slider you posted follows a path which is comparable to how the current Slow or Medium modes work, except that the movement beyond a certain point should be ignored, as we said before. I will focus this issue on fixing this 'overshoot' behavior for the current modes.

Which current mode (Classic, Slow, Medium, Exact) do you use or is closest to how you would prefer it to work?

I can't tell from the GIF how linear the slider works since I can't see exactly when the mouse button is being pressed. Does it feel linear or is it faster in the center?

**Comment by fonkle** [comment]
Still, I don't understand why in every video I can find on Youtube about Logic, the cursor **does** hide when the sliders and faders are moved? Is that a difference in versions or in user settings?

Like here (02:00): https://www.youtube.com/watch?v=4hUWYrAgJUk

**Comment by itsmedavep** [comment]
OH! I know understand what you are asking. Sorry this has been so confusing. 

Logic turns the cursor into a very tiny 1px line when dragging the slider. Its super easy to miss in a video and real life. I dislike that as well.

Here is a vid. Pay _really close_ attention to the slider thumb. Its super easy to miss. 

![tiny cursor](https://user-images.githubusercontent.com/11078351/55919190-88e0f680-5bba-11e9-806c-84c8f777f6f3.gif)

**Comment by baconpaul** [comment]
Wow ok I have never really noticed most of this. I had written the code to hide the cursor on a branch if we do end up wanting it but agree that’s a separate issue I agree. This is about overdrag and drag back which is odd if you don’t hide the cursor right? So I guess it’s all coupled?

**Comment by itsmedavep** [comment]
This thread is making me wish I hadn’t opened the issue. 

PLEASE don’t hide the cursor.  

Full stop. 

As a UX Designer I find loosing the affordance of the mouse cursor problematic for usability. Yes you have the white label below the slider that updates. That’s true. 

I dislike hiding things on the user user for no real reason though. If you fix the drag issue I opened there is no need to do any of that. 

Or to state it another way, what benefit to the user is there in hiding the affordance of the cursor if the drag issue is fixed?

Also, what is wrong with my expectations specifically? What is unintuitive in what I’m asking for with my initial post.

**Comment by fonkle** [comment]
Ok, so `CSurgeSlider::onMouseMoveDelta` is called on moving the mouse (while dragging) with a CPoint   and deltax and deltay. The delta is added (multiplied with the multipliers) to the slider value, which is then minimized and maximized to the slider range.

Now if we -instead of deleting the overshoot 'rest value' in `CSurgeSlider::bounceValue()`- accumulate the overshoot values in a variable, which is then subtracted on the next omMouseMoveDelta, then the slider won't start moving again until the accumulated counter has depleted to 0. When the mouse buttons are released, the accumulated 'rest-value' would reset to 0.

That could work as a fix, however I am not sure how it will work if the mouse is lifted while dragging the slider. I would have to try that out...?

**Comment by baconpaul** [comment]
@itsmedavep I agree the invisible cursor freaks me out

@fonkle that is the kind of fix I was imagining we would have to do - sounds spot on. Reset the deltas on mousedown and mouseup should fix the problem

Wheel uses mousedelta also and there we don’t want to use overshoot so I think you will need to have the mode controlled by a bool 

But your plan sounds right

**Comment by fonkle** [comment]
@itsmedavep: Which current mode (Classic, Slow, Medium, Exact) do you use or is closest to how you would prefer it to work?

**Comment by baconpaul** [comment]
I set medium as my default once the feature was in fwiw and like it a lot. (Thanks for adding it!)

**Comment by itsmedavep** [comment]
@fonkle I agree with Paul. Thanks for adding the speed!

Ive been at medium as well.

**Comment by fonkle** [comment]
I think I solved the puzzle :):

I modified `CSurgeSlider::bounceValue()` to optionally keep the remainder when the value (or modval) is rounded to the min or max. If so, it can be reapplied the next bounceValue() before rounding again. I added an optional bool argument to bounceValue() so the mousewheel does not overshoot.

It seems to work fine in all 4 modes, though I wouldn't want to change the way it works in the Classic mode on Windows (will test that). Is there any way I can get the changes your way to test on Mac without a PR to the master branch?

**Comment by baconpaul** [comment]
Cool!

Yeah just push a branch to your fork and we can check it out and test it. I have about 13 developer remotes in my repo. 

So if you have 'fonkle/whatzever-819' as a clean branch from master on GitHub both @itsmedavep and I can build it. (look in the git-howto if you don't know how to do this btw).

**Comment by fonkle** [comment]
Ok I squashed 2 commits (to try it out) and force-pushed the branch _fonkle/sweetspot-819_ to my forked repo: http://github.com/fonkle/surge.

Please let me know if I did anything wrong this time :).

**Comment by baconpaul** [comment]
So I just built your branch and it works well but there's one edge case. Here's what I did

1: Start a fresh surge in medium mode
2: Grab the cutoff and drag it to zero and keep dragging all the way to the edge of your screen and release
3: Move mouse back unpressed and grab the cutoff at zero and drag all the way positive

You have to "eat" the buffer again - you'll see. It doesn't start moving.

I think on mouse down you want to reset any buffer you've accumulated from prior drags (or perhaps on mouse up) to avoid this

But outside that it works just as I would expect!

**Comment by baconpaul** [comment]
Oh and git-wise seems everything worked perfectly!

**Comment by fonkle** [comment]
Glad to hear it (sorta) works. The issue makes sense; I will fix it asap. Can I just commit to the same branch and force push again?

**Comment by baconpaul** [comment]
Yup that’s perfect

**Comment by fonkle** [comment]
Fixed and squashed to a single commit :).

**Comment by baconpaul** [comment]
Hey sorry I got held up and then was looking at tunings. I’ll try your branch tomorrow I hope.Have a bit of time in the am.

**Comment by itsmedavep** [comment]
Oh wow! This is really exciting. Sorry I haven’t been able to test it out. I’ve been caught up with client business and haven’t had time to test for ya. 

I’m still jammed up a bit but will get some cycles for Surge in roughly 8 hrs.  

I’ll check your branch then and report back. I’m inclined to believe it’s all good though given Paul’s feedback. 


Thank you for your efforts!

**Comment by baconpaul** [comment]
I just took a chance to build the latest and it works great! Thanks so much!! 

I took a look at the code. I had two teensy code review comments

1. A couple of things were miss-tabbed. Perhaps run git clang-format master if you have the git clang-format extensions?

2. The new members you introduce (restvalue and restmodvaplue) should be initialized to 0 in the CSurgeSlider constructor. I don't think it matters that much that they aren't but I'm on a separate quest to make sure our constructor initializers are complete.

Last thing and this is for next time - you don't need to name your branch 'fonkle/foo-baz' unless you want to. I was using fonkle/ to mean your repo. I actually had to check out 'fonkle/fonkle/foo-baz' to specify the remote then your branch name. No biggie of course it all works but just for next time.

Awesome stuff. Thanks for fixing this! Medium Mode feels really great with this diff in. Can't wait to merge it!

**Comment by fonkle** [comment]
@baconpaul:

1. Oops. i have the extensions but I forgot to apply them. Sorry about that.
2. Fixed (squashed the commit + force-pushed)
3. I will get rid of the fonkle/ in the branch name in the future. Thanks for the tips, learning fast here :).

Shall I create a PR?

**Comment by baconpaul** [comment]
Yeah I would definitely create a PR! I'll take a quick once over again in the next 24 hours and merge.

Don't know if you saw #831 which is in a similar spot in the code in case you want to look there too (but lets do that separately from this issue of course).

And thanks so much!
