### ISSUE TITLE
Crash when receiving MSB bank changes (CC0)

### ISSUE THREAD

**Issue by ThrashJazzAssassin** [surge-synthesizer/surge#820]
Surge crashes my DAW sometimes when I send it bank changes. First time it crashed at bank 14 second time it crashed at bank 17.

Win10
Surge 1.6.0-beta-8 
Reaper 5.974

**Comment by baconpaul** [comment]
Thanks

Program changes are pretty weakly supported now. I’ll link the other issues on how we plan to support it to this issue in a bit

Appreciate the crash report! It shouldn’t dump core for sure. Even before we do fill pc support we should stop it doing that!

**Comment by baconpaul** [comment]
Ha OK this is a pretty easy bug to see

The program change message makes the patched = Bank * 128 + patch.

There's about 1700 patches shipped with surge

17 * 128 + 5 > 1700

and we never check if we run off the end hence the crash.

So a simple check in loadPatch to check the patchId is in range can address your crash.

#576 contains a fulsome conversation about how this *should* work. Won't do that with my fix though!

**Comment by baconpaul** [comment]
OK so I have a fix for the crash. Still makes the midi program control work not very well but at least it won't core out your DAW any more. 

When someone does #576 the midi program change stuff will change, FYI. Just so you know.

Thanks for the report. Appreciated! Fix should be in the nightlies in the next few hours.
