### ISSUE TITLE
Some UI asset is missing when opened from FL Studio through PlayOnLinux

### ISSUE THREAD

**Issue by henzosabiq** [surge-synthesizer/surge#823]
**Describe the bug**
I managed to successfully run Surge, but some of its UI Asset is missing. 

**To Reproduce**
1. Install FL Studio through PlayOnLinux
2. Open Plugin Manager, Scan for new plugin
3. Add Surge to Channel Rack after its detected
4. Here's what I got : 

![Screenshot_20190410_120523](https://user-images.githubusercontent.com/26890032/55853068-a6499c80-5b89-11e9-8a8d-92be8b4aa8f8.png)

**Expected behavior**
All UI asset should load. 

**Desktop (please complete the following information):**
 - OS: Kubuntu 18.04
 - Host: FL Studio 
 - Version: 20.1.2

**Comment by baconpaul** [comment]
I have no idea how to debug or fix this but: that screenshot is consistent with the assets loading but the assets which have a non-255 alpha not rendering. The whited our spots on your screen shot are areas where there’s some images with some transparency

From looking I would diagnose the problem as: the rendering pipeline in your configuration blows up alpha channel rendering

I don’t know if that helps you diagnose any settings. I don’t even know what playonlinux is!

**Comment by fonkle** [comment]
@baconpaul: PlayOnLinux is sort of a wrapper around Wine, making it easier for a lot of Windows software to be run in Linux. So FL Studio is a Windows application running (on Wine) in Linux.

This should be fixed through PlayOnLinux and / or Wine. You could try overriding libraries like gdiplus, direct3dx9 and opengl32 using `winecfg` (libraries->new override).

**Comment by baconpaul** [comment]
Gotcha - thank you - useful

So I don’t think there’s any surge code changes here then are there? Vstgui does use the direct 2d apis for rendering on windows so I guess look at settings for that emulation is the advice to affected users?

**Comment by fonkle** [comment]
Yes one can override a lot of Wine built-in libraries with different -installed- versions using `winecfg` or install them using `winetricks`. Beyond the scope of Surge i.m.o.

**Comment by henzosabiq** [comment]
I see. So this is more about required libraries not provided in wine than an issue within Surge itself, correct? I'm closing this issue for now for reasons stated by @fonkle .
