### ISSUE TITLE
High Frequency distortion in some wavetables

### ISSUE THREAD

**Issue by RCJacH** [surge-synthesizer/surge#830]
**Describe the bug**

I noticed that there are some high frequency overtone in basic/generated wavetables.
Almost all sine related wavetables have this distortion, except sine invpower 1024.
Some saw and other harmonic wavetables have this distortion as well, in the form of notch filter.

**Screenshots**

![Distortion in Sine wavetable at C1](https://user-images.githubusercontent.com/12930244/56042081-ca190800-5d6c-11e9-89a6-d56666f90364.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Host: REAPER
 - Version: Surge 64bit NIGHTLY-2019-04-06-debd603

**Comment by baconpaul** [comment]
Thanks. Out of curiosity what did you use to do the spectrum analysis? And did you do it on the .wt directly or on the result of surge playing the WT into your spectrum analyzer.

Appreciate the clear report.

**Comment by RCJacH** [comment]
The screenshot was from a JSFX plugin in REAPER, but the distortion shows up in Voxengo Span as well. It's audible.

I was monitoring the result of surge playing the WT, didn't have a chance to look at .wt directly.
This problem did not occur in other modes, including window mode. Also no distortion in most of layzer's wts, which are mostly bandlimited within 8k or so.

**Comment by baconpaul** [comment]
Great thank you.

**Comment by baconpaul** [comment]
Hi! So I pulled surge into logic and played it out into their eq / spectrum analyzer. With morph set at zero wavetables like 'generated/sine fb' and 'generated/sine oneharmonic' show no high frequency notches in my display in wavetable or window mode.

Could you perhaps be a bit more specific about exactly a patch which shows this?

Obviously we want to fix it! Especially if it happens in WT and not Window for you; but step one is for us to be able to reproduce it and I couldn't repro it from the info you gave this morning.

Thanks so much

**Comment by baconpaul** [comment]
OK I just saw this also. Sorry I didn't realize you needed low notes to hear it.

With sample/mallets you get it at low notes and you can indeed hear it! Around D#2 it becomes audible to me. I'm not sure if it is the oscillator or of it is the wavetable; but I get the same effect in the Rack implementation of the WT OSC also.

**Comment by baconpaul** [comment]
<img width="980" alt="Screen Shot 2019-05-12 at 5 51 18 PM" src="https://user-images.githubusercontent.com/13387561/57588185-a3223300-74de-11e9-9a1a-e8ec97b9ab45.png">

Huh well that's pretty clear right? I mean look at that wave. It's like the oscillator is getting the interpolation backwards somewhere at low frequencies.

**Comment by baconpaul** [comment]
(oh and I know that doesn't look like surge but it is - just the oscillator running in rack.)

**Comment by baconpaul** [comment]
And somewhere around line 261 of WaveTableOscillator.cpp is the problem with that interpolation I bet. But I'm not debugging this easily unless I can make it work in headless or some such. So let me turn to that.

**Comment by baconpaul** [comment]
<img width="887" alt="Screen Shot 2019-05-12 at 6 11 16 PM" src="https://user-images.githubusercontent.com/13387561/57588379-5c820800-74e1-11e9-9190-583edfc38e9f.png">

And just to finish it off: Here is frame 0 of that .wt which clearly contains no high frequency distortion. So this must be coming from the WaveTableOscillator interacting with this relatively small wavetable.

**Comment by baconpaul** [comment]
<img width="622" alt="Screen Shot 2019-05-13 at 11 28 12 AM" src="https://user-images.githubusercontent.com/13387561/57633867-39536900-7572-11e9-8b8f-4ecdcb83264f.png">

There's 64 samples of the WaveTable Oscillator playing "generated/sine fm 2" at midi note 40. Pretty clearly not smooth!

**Comment by baconpaul** [comment]
So I spoke with @kurasu and this is the correct behavior for low frequency wavetables. He said

> “Its a feature not a bug”
>
> What that oscillator is doing is essentially simulating a variable-rate D/A converter running at the rate of the original wavetable. The convolute method is generating a band-limited impulse with a sub-sample time localization precision, which is then integrated to provide the stepped function.
>
> This means that it basically doesn't produce any inharmonic aliasing (which make stuff sound messy). But it does produce harmonic aliasing, ie the waveform spectrum will continue indefinitely as opposed to other interpolation methods. It similar to very early pre-interpolation samplers that had a dedicated D/A converter per-voice (and analog filters) instead. But yeah, its not the right choice if you want a triangle wave without any additional overtones.

So I’m going to close this issue once I’ve added that text to the manual.

I’m considering re-rendering some of the very low sample rate wavetables into a “hires” version but have to figure out the interpolation which works best.
