### ISSUE TITLE
Shift + Mousewheel moves slider in opposite direction

### ISSUE THREAD

**Issue by RCJacH** [surge-synthesizer/surge#831]
Sliders move in opposite direction when using mouse wheel while holding shift.
Releasing shift returns to normal behavior, thus I assume it's a bug with shift modifier.

Desktop (please complete the following information):

    OS: Windows 10
    Host: REAPER
    Version: Surge 64bit NIGHTLY-2019-04-06-debd603

**Comment by baconpaul** [comment]
Which OS? Thanks!

**Comment by RCJacH** [comment]
Oops, sorry I meant to copy and paste the OS info from the other issue but forgot.
Updated original post.

**Comment by baconpaul** [comment]
Thanks!

**Comment by fonkle** [comment]
I cannot reproduce this with:

Windows 10 + Reaper 5.974 / Ardour 5.12 / Live 10.0.6
Kubuntu 18.10 + Bitwig 2.5.1 rc5
Nightly 2019-04-12 / Fresh from master
Classic / Slow / Medium / Exact

SHIFT + Wheel functions as per manual (fine adjustment in the same direction).

**Comment by baconpaul** [comment]
I just tried it macOS with a trackpad. 2 finger swipe works as expected; shift and 2 finger swipe goes the wrong direction. So I see the mac-gesture equivalent to original report.

hmm. wonder what's going on!

**Comment by baconpaul** [comment]
Oh and thanks for trying in various situations @fonkle

**Comment by baconpaul** [comment]
Huh really straight forward. When the shift key is held on my mac, the distance which is passed to onMouseWheel is the opposite of when it is not.

When I use safari or excel, the shift does not flip the direction. 

But hey look in `vstgui.surge/vstgui/lib/cview.cpp`

```
bool CView::onWheel (const CPoint& where, const CMouseWheelAxis& axis, const float& distance, const CButtonState& buttons)
{
        if (axis == kMouseWheelAxisX)
        {
                #if MAC // mac os x 10.4.x swaps the axis if the shift modifier is down
                if (!(buttons & kShift))
                #endif
                return onWheel (where, distance*-1, buttons);
        }
        return onWheel (where, distance, buttons);
}
```

So cool. 10 versions of macOS later I think we don't need that. Harumph. 

Wonder what's doing it on windows though? I don't have my VM up and running now so can't look there.

**Comment by fonkle** [comment]
In Windows 10 (no VM) the SHIFT modifier refines the adjustment of the slider. It does not change direction. Both horizontal and vertical sliders work fine in my situation.

**Comment by baconpaul** [comment]
Yeah I think the mac problem is distinct from the windows one (I mean the code is in an #if MAC block :) ) where shift changes both direction and speed for horizontals. I still want to fix that but it won’t close this issue when I do.

@RCJacH is there something peculiar about your setup with mouse settings or anything?

**Comment by baconpaul** [comment]
Shared the issue with steinberg for mac also: https://github.com/steinbergmedia/vstgui/issues/106

**Comment by baconpaul** [comment]
Just put in a pull request to fix this on mac.

**Comment by baconpaul** [comment]
Fired up my VM and built master and I also can't reproduce the windows problem. Scroll and shift scroll go the same way for me in SaviHost running the vst2.

So @RCJacH I think we need to know more about your settings. Surge code and vstgui code paths seem to not be changing direction on us. Do other apps work with shift depressed OK?

**Comment by RCJacH** [comment]
I installed surge on my laptop and the same issue happens, both in REAPER and in VSTHost.

To clarify, the shift modifier issue in Windows that I'm describing only happens when using the MouseWheel. Shift + Left Click functions normally. And this behavior is consistent.

I couldn't find another vst that changes parameter with Shift + MouseWheel. Some plugins do work with Ctrl + MouseWheel, and it works normally. So...I don't really know where the problem is.

**Comment by baconpaul** [comment]
Ok! Well I have a Mac trackpad and fonkles setup doesn’t show this behavior so hard for us to debug alas.

Do things like excel and what not change scroll direction when you shift wheel? I wonder if you have some system setting

**Comment by fonkle** [comment]
@RCJacH: I think some other software, like your mouse / keyboard drivers, cause your mousewheel to invert in combination with SHIFT.

**Comment by RCJacH** [comment]
> 
> 
> @RCJacH: I think some other software, like your mouse / keyboard drivers, cause your mousewheel to invert in combination with SHIFT.

You are correct!
Your comment reminded me that I had AltDrag open in the background. And indeed it does specifically change the behavior of SHIFT + MouseWheel.
Sorry for the trouble. Problem solved.

**Comment by baconpaul** [comment]
Ha great! But also the Mac problem was real and we found it here so all good!
