### ISSUE TITLE
Rescan documents directory

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#836]
Right now if you add a wt file to documents it doesn’t rescan unless you restart surge. The rescan is easy to do just we don’t know when to trigger it

Could do loads of complicated stuff like file system listeners but that’s all dumb. Let’s just add a menu item to rescan documents folder

**Comment by esaruoho** [comment]
that'd be awesome to have!

**Comment by baconpaul** [comment]
Turns out it is super easy too. PR coming.
