### ISSUE TITLE
Implement directory and filter in fileOpenDialog in UserInteractions

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#840]
The first version of FileOPenDialog I just pushed (https://github.com/surge-synthesizer/surge/commit/fcc8c43bb315c7a86b91f6ffbdce3b75080b0416) ignores the filter and starting directory arguments.

This issue exists to nag me to not do that.

**Comment by baconpaul** [comment]
@mkruselj if you want to here's the issue

**Comment by mkruselj** [comment]
Managed to implement initial directory working just fine, but not the filter.

Also if the initial directory is not found (i.e. somebody renames it), it should fallback to the factory data folder, but for now I didn't manage to figure out how to do that.

**Comment by mkruselj** [comment]
Additional nicety that could be implemented (again hand-holding welcome): maybe remember the last folder the user browsed to in configuration.xml (separately for SCL and KBM of course!), and then use that the next time loading dialog is called. If the folder is later not found, revert back to factory tuning folder for SCL or KBM, and again if THAT is not found, fallback to factory data root.

**Comment by baconpaul** [comment]
the macOS does that automatically and i think zenity does too but I'm not sure.
there's some advanced windows ones which did too but they coupled to some newer sdks which we didn't use

**Comment by mkruselj** [comment]
We have a separate issue for "additional niceties" (#1864) so closing this one!
