### ISSUE TITLE
Redraw issue in Linux Reaper

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#845]
When zooming any size above 100% will not draw the complete image although it will expand it.

![reaper surge 125x](https://user-images.githubusercontent.com/41337033/56435615-18676300-62a7-11e9-9405-b36ec31cb44e.png)

**Comment by baconpaul** [comment]
@tank-trax reports this closed with the changes at cd29df1

**Comment by tank-trax** [comment]
this looks to be resolved with the latest build
