### ISSUE TITLE
Vst3 pitch bend mis-centered

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#854]
![D006F448-4F0C-4741-B8EB-36707B1E08FD](https://user-images.githubusercontent.com/13387561/56973265-83802780-6b3a-11e9-96b6-9d0707193616.png)

Few reports like that

**Comment by baconpaul** [comment]
OK so on mac bitwig with the master / nightly there is no off by one. I pull the VST2 next to the Arturia Jupiter and they are in tune; then pull the VST3 in and they are in tune also.

So this is something about windows or your particular host.

**Comment by baconpaul** [comment]
On OSC Surge Ranoka reports he can reproduce it also; asked him for host combo

**Comment by baconpaul** [comment]
We think this happens windows / FL20

**Comment by VincyZed** [comment]
Ok, Yes I run FL 20.1.2 x64 with Windows 10 as well.

**Comment by baconpaul** [comment]
Thanks; it's a bit more work for me to boot up my VM to test that setup but I will look this week.

**Comment by baconpaul** [comment]
OK I just confirmed that VST3 FL20 Windows 10 is indeed off by one!!

So now I gotta debug and fix that somehow. Will ponder.

**Comment by baconpaul** [comment]
OK this is crazy
VST3 Win 10 bitwig is in tune; VST3 Win10 FL20 is off by a half step
Both are sending the same 'playNote'
I suspect pitchbend implementation problem but am not sure.

**Comment by baconpaul** [comment]
Yes; FL20 sends a pitchbend value of 0.5 at outset. bitwig does not.

**Comment by baconpaul** [comment]
Alright so if I disable pitch bend in FL20 with the VST3 everything is fine. Wonder if I'm doing pitchbend wrong in vst3?

**Comment by baconpaul** [comment]
Ahh yeah that's it.
Pitch bend in VST3 is between 0 and 1, not -1 and 1.
So the center wheel is 0.5

You can repro this in any host any OS as follows

1. Load the VST3
2. Play a note
3. Jog the pitch wheel up and down
4. Play the same note

The note will be a half step up

The reason for that is because it got pitch bend "0.5" which became 4192 or whatever which is a half step.
