### ISSUE TITLE
Scrolling mouse wheel unintendedly changes more than one parameter

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#856]
In the **VST3 version**, when scrolling using the mouse wheel to move a slider, if the GUI is set to 125%, more than one parameter will move.

**Steps to reproduce this behavior:**
1. Set GUI to 125%.
2. Move the mouse over certain parameters and scroll.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/50145178/57000181-68d0a180-6b80-11e9-9d51-dfbda38e0a9c.gif)

**Expected behavior:**
It should only move the slider under the mouse pointer.

**System:**
 - OS: Windows 10 64bit
 - Host: FL Studio 20.1.2 x64
 - Version: 1.6.0-beta-8 (VST3 x64)

**Additional info:**
Even if the VST2 version doesn't scale up properly, it seems that it does not have this problem.
Also, my screen resolution is too small to go above 125%, so I can't tell if this happens with 150% and above.

**Comment by baconpaul** [comment]
Couple of quick checks

1. Does this happen at 100%? 90%?
2. I see FL changing above; the parameter change you get is the one you re shifting right? It's not like FL is doing a bad roundtrip mapping?

Thanks!

**Comment by VincyZed** [comment]
- This does not happen at 100%. However, at 90%, it does it, and it's different than at 125%.

1. The parameter updates section on the top left show only one update at a time, and there's more than 1  in this case. 
2. Oddly, it seems to only show the one(s) that should not move.
3. Both parameters are still updating at the same time. Don't know if that answers your question, because I'm not a super technical guy and not sure to understand what you mean by "bad roundtrip mapping"

**Comment by baconpaul** [comment]
“The one it shows is the one that doesn’t move” that’s interesting. So you move shape and FL shows pitch (and pitch moves also)

By bad round trip I meant “Surge -> FL ‘parameter 3 changes’” and FL says “Oh cool -> parameter 1 has changed” type thing.

Very useful and clear bug report.

Last question: Once it has happened with the mouse wheel does it also happen with the mouse? That is get it wedged so you get a double slide - does a regular drag also do a double slide?

Thanks so much!

**Comment by VincyZed** [comment]
No. After doing it with the mouse wheel, if I click and drag, everything works fine.
Glad to hear that helps!

**Comment by baconpaul** [comment]
OK I can replicate this

Also it seems super weirdly state-y

* Go to 125x zoom in FL20
* Do all of this without ever clicking
* Move the portamento with the mouse wheel
* then move the mouse to the 1x2 ring modulator mixer without mousing over any other element
* then mouse wheel and both 1x2 and portamento move
* them move mouse to gain and mouse wheel and gain moves and portamento doesnt
* then move mouse back to 1x2 and mouse wheel and *portamento doesn't move*

Bitwig does not do this; only FL20 (all on windows 10 in my VM)

So clearly something about focus or mouse leave event or some such is getting suppressed in FL20 in a way which isn't in BitWig.

Will be annoying to debug. I'll see if I can see it tonight when I have a bit more time. @VincyZed if you can confirm you see above prescription doing same would be appreciated.

**Comment by baconpaul** [comment]
From OSC Slack user ontrackp

> @baconpaul I almost always am at 125% and frequently get a wrong parameter moved by the mouse.  I thought it was just me being careless.  I use Logic Pro X.   And the box that comes up with the parameter info seems to loiter for a few seconds even after the mouse is moved away.

**Comment by VincyZed** [comment]
Yes, I can confirm that certain value boxes stay on the screen for way too long for me as well, until I click somewhere else. I will do the steps described above later today and let you know.

**Comment by baconpaul** [comment]
OK in good news this is happening because vstgui is calling on wheel twice. So it's not some messed up parameter round trip.

In bad news, this is happening because vstgui is calling on wheel twice. Chuckle.

**Comment by baconpaul** [comment]
I would bet it is this code in cviewcontainer which is screwing up when transforms are set

```
bool CViewContainer::onWheel (const CPoint &where, const CMouseWheelAxis &axis, const float &distance, const CButtonState &buttons)
{
        for (auto it = pImpl->children.rbegin (), end = pImpl->children.rend (); it != end; ++it)
        {
                const auto& pV = *it;
                CPoint where2 (where);
                where2.offset (-getViewSize ().left, -getViewSize ().top);
                getTransform ().inverse ().transform (where2);
                if (pV && pV->isVisible () && pV->getMouseEnabled () && pV->getMouseableArea ().pointInside (where2))
                {
                        if (pV->onWheel (where2, axis, distance, buttons))
                                return true;
                        if (!pV->getTransparency ())
                                return false;
                }
        }
        return false;
}
```

but have to hop now so just putting that there as a note to myself.

**Comment by baconpaul** [comment]
That wasn't it. But I have a fix. Doing a final bit of testing.
