### ISSUE TITLE
Modulate modulation amounts?

### ISSUE THREAD

**Issue by hems** [surge-synthesizer/surge#857]
**Is your feature request related to a problem? Please describe.**
When setting up modulation amount, for instance `LFO -> Cutoff` the modulation amount is 'fixed' and can't be modulated by the browser.

![image](https://user-images.githubusercontent.com/27327/57000941-ea8af400-6bad-11e9-9d92-4325c77179a8.png)

**Describe the solution you'd like**

Quick solution: Expose `Mod Ammount for LFO -> Cutoff` ( and any other routing ) to the DAW

**Describe alternatives you've considered**
Have a `Matrix Modulation` view ( like [Serum's Mod Matrix](https://www.google.com/search?biw=960&bih=533&tbm=isch&sa=1&ei=WeTIXNjQFaWH1fAPp6WsqAg&q=xfer+serum+modulation+matrix&oq=xfer+serum+modulation+matrix&gs_l=img.3...7555.8180..8302...0.0..0.200.590.1j2j1......1....1..gws-wiz-img.JzW-h6VYN1c) )

**Additional context**
Could be also nice to modulate `Mod Amount` of for instance `Velocity -> Cutoff` using another LFO.

I heard on Slack that's what the SLFO is for, but i'm not aware of how to use SLFO, so i need to look into that to see if it solves this issue for me.

Thank You!

**Comment by baconpaul** [comment]
Your idea is basically right now the surge modulation architecture is "p = p0 + a * modsource1 + b * modsource2" etc but a and b aren't themselves modulatable

If the mod sources are LFOs they are modulatable by other LFOs (that's what the little arrow does) so you can get there. But if, say, you want velocity sensitivity to change as a function of an envelope there's no real way to do that now.

Interesting observation. Hard to fix.

**Comment by hems** [comment]
i wouldn't need A and B to be modulatable, just A ( amount of modsoure ) to be exposed to the DAW!

**Comment by baconpaul** [comment]
yeah clever idea. some reasons it is hard (including a fixed parameter space at initialization in vst) but I'll think about a way to do something like this.

Obvious approach is to bind a midi controller to the modulation amount for instance...

**Comment by hems** [comment]
> Obvious approach is to bind a midi controller to the modulation amount for instance...

exactly, but this isn't possible yet right?

**Comment by baconpaul** [comment]
No it isn't. Was just designing out loud on GitHub! Sorry.

**Comment by hems** [comment]
For inspiration purposes i'll post here this absolutely insane  "modulation kit" for ableton live: https://isotonikstudios.com/product/signal/ maybe when dealing with modulations / mod matrix and others some inspiration could be found on that kit.

**Comment by baconpaul** [comment]
Yeah right. Imagine a modulation source which was also a modulation target and exposed itself to the daw 

We actually have that now of course. Burn an lfo by setting it in envelope mode set the rate to zero modulate the phase and the daw modulate the amplitude. But it is clumsy

**Comment by mkruselj** [comment]
> So i think we are not talking about the same thing.

We are talking about the same thing. You're talking about limiting the mod matrix to a particular number of slots. I'm talking that would stifle everything that's possible with Surge BECAUSE it doesn't have such a fixed-size tabula rasa mod matrix. Intsead, it has any-modulator-can-modulate-pretty-much-anything-simultaneously sort of thing which is quite unique.

However, do see [this issue](2049) for some of my thoughts on how to improve workflow with modulation in Surge.

**Comment by mkruselj** [comment]
@baconpaul Is it just me, or wouldn't mod mixers (as in Zebra) basically sort this issue out, too? Yeh, I think they would. :)

**Comment by mkruselj** [comment]
And just to confirm after yet again rereading this issue - mod mixers are DEFINITELY the final solution for this request! So, linking this issue to #1384 - closing that one should close this one too.

**Comment by mkruselj** [comment]
In fact, I'm going to close this issue right now since modmixers are superceding this issue.
