### ISSUE TITLE
Use output of A as input of B ( improve audio routing )

### ISSUE THREAD

**Issue by hems** [surge-synthesizer/surge#858]
**Is your feature request related to a problem? Please describe.**
I would like to use B filters after A filters

**Describe the solution you'd like**
On "B" OSC input on the "Audio Input" we could have "A SCENE output" not only external outputs

**Describe alternatives you've considered**
Having a "Routing View" in order to patch the signal path dynamically instead of toggles, like [Energy-XT](https://www.energy-xt.com/), [Jeskola Buzz](http://jeskola.net/buzz/), [Mutools Mux](https://www.mutools.com/mux-product.html), [Hollyhock 3](https://www.sensomusic.org/downloads.php) or [Plogue Bidule](https://www.plogue.com/products/bidule.html)

**Comment by baconpaul** [comment]
Discussed this some on slack.

If you are willing to have a BLOCK_SIZE delay this is pretty easy. The prior BLOCK of samples from scene A can be cached and available for scene B easily. The "sum scenes" section of SurgeSynthesizer::process could set the audio input for the next cycle for the audio input configured specially. etc...

Then make scene B have a special audio input flag which is "from scene a"

**Comment by hems** [comment]
that would be sweet. do you think DAW would compensate for that when that option is selected?

I have no experience with latency compensation...

**Comment by baconpaul** [comment]
nah. basically surge works by processing things in an internal block size of 32 samples. So a single "sweep" generates the next 32 samples. At the end of the sweep it is queued up for the output and so on.

But that means if A feeds B the first sweep will generate the 32 of A and B simultaneously, then the 32 of A get fed as input to the next 32 of B.

So that latency (32/44100) between scenes will exist if you do it the obvious way

The non-obvious way is really hard because there is no "loop" - the entire synth is a set of vectorized SSE2 instructions.

**Comment by hems** [comment]
@baconpaul it seems that the first possible solution would be to add that `1 block` latency when doing that routing, in the feature I guess routing could be improved to be more dynamic and lose that latency... still that 32/44.1k latency seems negligible !

**Comment by baconpaul** [comment]
Yeah and if it really bugs you you can run at 96k and have it be even smaller. I think it’s the way to go, Clever idea.

**Comment by hems** [comment]
> Yeah and if it really bugs you you can run at 96k and have it be even smaller. I think it’s the way to go, Clever idea.

not sure if it's easy for Surge to report latency to the DAW so the DAW could do the latency compensation..

Another option would be the plugin to report the latency on the GUI somewhere so the user can compensate for such latency manually when needed.

**Comment by baconpaul** [comment]
OK so I have this working with zero latency as well by unwinding the inner block a touch, and it even manages to not copy if you don't need it. The only constraint is that I need to shuffle A->B before A gets FX and clips. So the signal path is A -> (b optionally) and A-> A FX.

I'm seeing if I can restructure to lift that constraint but it is more surgical to do so....

**Comment by baconpaul** [comment]
oh right yeah this has to happen before FX because the oscillators all run at oversample frequency and the fx run at regular sample rate. So I would have to downsample and re-upsample to share. 

So cool should have this in the synth by the weekend.

**Comment by baconpaul** [comment]
I just merged this feature. Should be in a nightly in next 30-45 minutes
