### ISSUE TITLE
32bit v2 crashing Reaper in wine in ubuntu 14.04

### ISSUE THREAD

**Issue by michaelsjackson** [surge-synthesizer/surge#862]
Bug is explanatory, show stopper, plugin can not be used as the DAW, Reaper 32 bit, is crashing. Tried this some time ago, stopped, because of same behaviour, thought, anything is improve maybe now, but no, still crashing. Maybe I should try v3 instead?

**Comment by baconpaul** [comment]
jeez, I'll be honest: that's so far from anything like we test or can test that I don't know what to recommend. The combination of wine, reaper, older ubuntu and 32 bit seems likes problems could be anywhere.

If 32 bit reaper can load vst3s maybe try that but not sure.

do you get a stack trace or anything?

I will note that the plugin works great in native hosts on linux also.

**Comment by michaelsjackson** [comment]
vst3, I tried, not visible inside Reaper, it seems this does not work. Well all other vsti's work well, in above scenario, only surge not. Not sure what is different in surge?

And too bad, shortcircuit 1.1.2 is not open-sourced as well, maybe in future?

**Comment by baconpaul** [comment]
Yeah I don’t know what’s different with rack; but perhaps a different rendering pipeline? Another user had reported some problems with wine and partly rendered graphics and the suggestion was to make sure your OpenGL and so on libraries were up to date? I don’t know. I’ve never used anything close to your configuration :(

Are you a developer? If you are I could give you some hints on how I would debug this. But you’d want to install the MSFT development stack to do that under wine I guess.

**Comment by michaelsjackson** [comment]
The later version is working in wine, thanks for caring and cleaning here. All is fine with surge now, only shortcircuit missing, with source so its problems can be solved as well for wine. Here after reloading of a song, e.g. in Reaper the samples are not found, thus not loaded, which is a huge showstopper. Actually the only reason I am not using shortcircuit.

**Comment by baconpaul** [comment]
Yeah I’ve never used short circuit and it isn’t open source, so can’t help you there, but glad the latest version works! Thanks!
