### ISSUE TITLE
Midi Channel 3 

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#866]
[midi_export.zip](https://github.com/surge-synthesizer/surge/files/3148680/midi_export.zip)

Take that midi file and drag it into logic and attach a surge
With MPE enabled you hear noise
With MPE disabled you don't
If you edit it so that the track is 2, with MPE enabled or disabled you do
So what's wrong with channel 3 in this case?

Ooof.

**Comment by tank-trax** [comment]
MIDI specs for the Artiphon Instrument 1

[MIDI Specs.rtf.zip](https://github.com/surge-synthesizer/surge/files/3153772/MIDI.Specs.rtf.zip)

**Comment by baconpaul** [comment]
OK so I've figured out what's going on and I am not 100% sure it is a bug. 

This has to do with channel routing in non MPE mode and the "channel mask". If you put your surge into "dual" scene mode this should work. Weirdly.

I'm still figuring out exactly what it is doing. But the code has this comment:

```
   // For split/dual
   // MIDI Channel 1 plays the split/dual
   // MIDI Channel 2 plays A
   // MIDI Channel 3 plays B
```

Now in single mode what is happening is you are coming in on channel 2 (which is 3 in zero offset). With MPE disabled you end up if you look at calculateChannelMask with channel == 0 (false) || channel > 2 (false) || mpeEnalbed (false) so you return channel mask == channel = 2.

So since channel mask & 2 then you play on scene b.

But scene b isn't active if you are in single mode.

and that's the bug. calculateChannelMask needs to understand single mode for channel 1 and 2. Gotcha. 

So I can fix this now. Excellent. Sorry for the running commentary in GitHub. Good place to keep my notes. Fix will come in next day or so.
