### ISSUE TITLE
OSX 13.10.1 VST GUI problem

### ISSUE THREAD

**Issue by developerhorse** [surge-synthesizer/surge#870]
Installed Surge-1.6.0-beta-9-Setup.dmg as VST, GUI appears corrupted with blue background (screenshot attached). 

    OS: OSX 10.13.1
    Host: Ableton Live
    Version: 9.7

Any fixes or comments?

![Screen Shot 2019-05-08 at 4 37 52 PM](https://user-images.githubusercontent.com/50425139/57407342-e879f400-71b0-11e9-946b-885c6fa5e739.png)

**Comment by baconpaul** [comment]
Are you also user `Leonid` from slack?

If so here's what I just put on slack:

OK I wiped surge from my mac and installed the image from the website. The AU works fine in Hosting AU as does the VST and VST3 in Bitwig. So that means your problem is one of two things

1. The install didn’t work for you and you don’t have SVG assets
2. Something about Live 9.4 is setting up surge so that it uses the wrong path for SVG assets at load time

I hope 1; I fear 2.

So to confirm #1 can you open a terminal and send me the output of
`ls /Library/Audio/Plug-Ins/VST/Surge.vst/Contents/Resources/svg/`
If that shows you a mess of SVG files, then it is problem 2. And that will be tricky to debug and fix. But not impossible. But I will have to get you a nightly build with debug info.

If you do see a mess of SVG with that ls command do you have any other hosts installed? can you grab a demo of - well - anything else and try?

**Comment by developerhorse** [comment]
Hello,

1. output:

-bash: /Library/Audio/Plug-Ins/VST/Surge.vst/Contents/Resources/svg/: is a directory

2. Never really have a problem with ableton host. Installed the AU as well and the folder AU folder appeared on ableton but not the source. 

I'm a non slack user, should i?

Thank you, I appreciate the help. Intrigued about trying this project.

**Comment by baconpaul** [comment]
How totally random. Another person reported this on our slack 2 hours before you did here! 

I don't normally do this but debugging this will be hard so I made you a test build with some fixes and debugs in it.

Can you try this installer: https://www.dropbox.com/s/bysvsp7evkwa8t9/Surge-DEVELOPMENT-BACONPAUL-LIVE-TEST-870beta-2019-05-08-1934-Setup.dmg?dl=0

I will delete it in about 24 hours. It is built from the branch mentioned above. But does that fix your problem? If it does I will sweep the fix to the nightlies.

Thank you.

**Comment by developerhorse** [comment]
Hey Paul,

amazing thanks gonna test. Also, should I just install that version on top of the previous one ? if not, any best way to fully wipe out the previous Surge installation?

Thanks man

**Comment by baconpaul** [comment]
The installer will overwrite properly but if you want, remove /Library/Audio/Plug-Ins/VST/Surge.vst before you start sure.

You will get a popup that looks like an error once. I would really appreciate a screenshot of it. And then if everything else works that would be great to know. (If it works I will take that popup out fo the nightlies).

**Comment by developerhorse** [comment]
Great thanks this worked,

I installed, got the error and this is the screenshot:

![Screen Shot 2019-05-08 at 8 53 37 PM](https://user-images.githubusercontent.com/50425139/57420101-e6755c80-71d3-11e9-8253-0d1e780d7eba.png)

It seem to be working just fine and stable using VST. Midi work and resize as well. Also sounds great. 

Thank you so much man, should I keep this version or wipe it out and wait for one that will work for this settings?

If so, is there any mailing list to sign for or just check this forum regulary for updates and all that?
Thanks, much appreciate the DIY work and will dig into it as much as I can.

**Comment by baconpaul** [comment]
Awesome. Thanks for testing and a clear screenshot.

I will sweep that into the nightlies tomorrow and update this issue when I do. Then you can scrap that weird version I sent and get an updated version from the official nightly builds.

Glad it worked. fwiw that screenshot shows that Live 9.7 is doing something deeply rude with the plugin load sequence but it's low cost for me to work around it!

And best way to stay in touch is - uhh - I actually don't know! We will do a 1.6 release soon. The GitHub and slack are good conversation points. There's some chat on kvr also. But we don't have anything like a tiny letter announcing stuff.

**Comment by baconpaul** [comment]
OK I just swept this change to master. It usually takes about 30 minute for that to result in a new nightly on the website. But sometime later than half an hour from now go to surge-https://synthesizer.github.io click on the link that says "wanna live on the edge - try the nightlies?" and then download the nightly as long as the update date says "may 9".  That should give you a version with a clean home/about screen.

When we freeze 1.6.0 sometime in the next few weeks this feature will be in there.

Thanks for the bug report and test.

**Comment by baconpaul** [comment]
The nightly with your fix is now on our website. 16beta9 will still be broken but the nightlies will work.

**Comment by developerhorse** [comment]
Downloaded the nightlies version and works great. Will dig more into it and if I have any question will come back. Thank you for all your help.

**Comment by baconpaul** [comment]
Great thanks for letting us know!
