### ISSUE TITLE
Converted Wavetables with more than ~122 Waves crash Surge

### ISSUE THREAD

**Issue by theofficialajyoung** [surge-synthesizer/surge#872]
**Bug Description**

Recently I have been using the [Python script here ](https://github.com/surge-synthesizer/surge/tree/master/scripts/wt-tool) to convert Wavetables I use in other Synthesizers (such as Serum) to Surge format.

I have discovered that Wavetables created with a large number of Waves will crash both Surge and the DAW when trying to load them. No error message, just hard-closes the host program.
Sometimes it will load and display an inaccurate Waveform view, but not crash immediately. However, moving the Morph parameter to try to scan through the Wavetable will crash it.

**To reproduce:**

In the zip file below, there are 3 .wt files. All of them are 1024 samples per Wave. I have narrowed down the issue to being greater than ~122 Waves in a Wavetable. 

- test-256.wt: This is the full converted wavetable, the ideal end product. This has 256 Waves in it, and crashes Surge when loaded.
- test-122.wt: This is the same wavetable, but only converting the first 122 Waves. This one loads correctly!
- test-123.wt: This one has only one more Wave converted than the above. This crashes Surge.

[Test.zip](https://github.com/surge-synthesizer/surge/files/3167960/Test.zip)

**Expected Behavior**
According to the [.wt file format](https://github.com/surge-synthesizer/surge/blob/master/resources/data/wavetables/wt%20fileformat.txt), Surge should be able to support Wavetables with up to 512 Waves. These files crash with much fewer than that, and 123 seems to be a rather odd number, so I imagine something's wrong here.

I have a lot of custom Wavetables to share, and I would love to add them to be distributed with Surge if possible, but currently can't if they don't load properly.

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Host: Reaper 5.977 64-bit, FL Studio 20.1.2 [build 887]
 - Surge 1.6.0 beta9 (May 1 2019 23:59:14) VST2 64-bit

**Additional context**
You may remember me talking about some of this in [this KVR post](https://www.kvraudio.com/forum/viewtopic.php?p=7388947#p7388947).

To clarify my conversion process, here are the steps I use to convert a Serum Wavetable to Surge format. All of them seem to work great as long as they have a smaller number of Waves.

1. Open Serum and load the desired Wavetable. Open the Wavetable Editor.
2. In the Wavetable Editor, Morph>Remove Morph Tables, if there are any.
3. Export>Export All as Single-Cycle Waves. Choose directory and save.
4. Use an Editor to convert the Waves into the correct format. Reaper is great for batch-processing many files at a time.
     - Load the Wav files to separate tracks, maintaining the correct order
     - Increase the Playrate of the Waves to 2, and turn off "Preserve pitch when changing rate". This reduces the Waves from Serum's 2048 samples to Surge's expected 1024.
     - Drag the end of the items to match the smaller size, so that it does not repeat.
     - Lower the volume of all tracks. I do -12db. I've discovered Surge clips the waveforms well before they reach 0db, so lowering the volume is required for the Wavetable to sound correct.
     - Select all tracks, and render as "Stems (selected tracks)". No tail. 44.1khz, 16-bit, mono, WAV to match [the described format here](https://github.com/surge-synthesizer/surge/blob/master/doc/wavetables.md).
5. Use the Python script to convert the Waves to .wt format.

**Comment by baconpaul** [comment]
Thank you for this excellent bug report. This should be straight forward to fix after the clear and very useful description you gave givens appreciated. I’ll make sure to debug this before we ship 1.6.0

**Comment by theofficialajyoung** [comment]
Wonderful, thank you :) I have a ton of custom wavetables I'd love to convert and share with people.

**Comment by baconpaul** [comment]
Am able to reproduce on my mac with your zip file.

1. Load 122 and drag all the way back and forth with morph; no problem
2. Load 123 and drag all the way over with morph or load 255 and drag half the way over with morph and get a segfault

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.vemberaudio.au.surge      	0x000000010f360b9c WavetableOscillator::convolute(int, bool, bool) + 1116 (WavetableOscillator.cpp:263)
1   com.vemberaudio.au.surge      	0x000000010f36130f WavetableOscillator::process_block(float, float, bool, bool, float) + 1199 (WavetableOscillator.cpp:459)
2   com.vemberaudio.au.surge      	0x000000010f37950a COscillatorDisplay::draw(VSTGUI::CDrawContext*) + 1082
3   com.vemberaudio.au.surge      	0x000000010f3bf0f9 VSTGUI::CViewContainer::drawRect(VSTGUI::CDrawContext*, VSTGUI::CRect const&) + 3081 (cviewcontainer.cpp:884)
4   com.vemberaudio.au.surge      	0x000000010f3be452 VSTGUI::CFrame::drawRect(VSTGUI::CDrawContext*, VSTGUI::CRect const&) + 306 (cframe.cpp:338)
5   com.vemberaudio.au.surge      	0x000000010f3c653d non-virtual thunk to VSTGUI::CFrame::platformDrawRect(VSTGUI::CDrawContext*, VSTGUI::CRect const&) + 13
6   com.vemberaudio.au.surge      	0x000000010f42209c VSTGUI::NSViewFrame::drawRect(CGRect*) + 252 (nsviewframe.mm:909)
7   com.vemberaudio.au.surge      	0x000000010f41f9ba VSTGUI_NSView_drawRect(objc_object*, objc_selector*, CGRect) + 74 (nsviewframe.mm:228)
```

is the stack. It's in the display draw path but probably would crash in the playback path also.

**Comment by baconpaul** [comment]
(Oh @theofficialajyoung when I'm working on an issue I often drop 'notes to myself' in the issue since today I'm traveling and just had 10 minutes to look; don't worry if they don't make much sense to you they are sort of research memory more than reporter feedback!)

**Comment by baconpaul** [comment]
One more note: if I turn off the oscillator display and play in latch mode I get a crash at the same point in the DSP engine. So this is not a 'draw' problem.

Looks like TableF32WeakPointers may not be set up properly.

**Comment by baconpaul** [comment]
More debugging:

CheckRequiredWTSize returns false at the 123 level which makes the wavetable oscillator silently (!!) not set up its internal state leading to a crash since you are still in your prior state. Need to figure out what that check is actually doing tho.

**Comment by baconpaul** [comment]
I have found the problem here and have a fix. I'll sweep it in tonight if the builds work, which means it should be in the nightly build soon. I will tag this issue again when the nightlies are ready, or if you want, just grab them from surge-synthesizer.github.io if the build date is on or after May 11.

Thanks again for the excellent report. I wonder if that serum workflow could be scripted in other python scripts. What exactly does the playrate / shortening thing do? Alternately we could just allow 2048 samples in surge. I think there's an issue for that too somewhere.

**Comment by baconpaul** [comment]
The nightly on the surge website fixes both this problem and the menu problem you found.

Also: Thank you. Excellent bug reports like this make it so much easier to fix problems. Very valuable. Appreciated!

**Comment by theofficialajyoung** [comment]
Haha if nothing else, I know how to write a bug report.  ;) Dad's been a SysAdmin all his life so he drilled the tech stuff into me well.

I would definitely prefer that Surge supported 2048-sample wavetables. That's becoming the defacto standard these days. Started with Serum, and now nearly every modern Wavetable Synth (Dune, Rapid, Avenger, Synthmaster, etc.) uses that or greater.

The entire "Reaper" part of that process is because when you export the individual Frames from a Serum Wavetable, they output as Mono, 32-bit WAV at 2048 samples. So I had to reduce that to 1024 to work with Surge, by speeding up the files to double speed (and half length) and then re-rendering them at Surge's expected bit-depth (16-bit WAV).

If Surge supported 2048-sample, 32-bit WAV wavetables, it would cut the time it takes to convert a wavetable down to nearly 1/4. And it would open up Surge to the literally thousands of user-created Wavetables that exist for other Synths.

**Comment by theofficialajyoung** [comment]
Also of note is that many of my custom wavetables are dubstep-oriented, and have a lot of essential high-frequency content I'm afraid might be partially lost when reducing the samplerate. 

A common dubstep sound design technique is to take a table with a lot of high harmonics, and then warp it using phase distortion. Such as NI Massive's bend modes, or Surge's Horizontal Skew (which is roughly equivalent to Serum's Asym+/- warp mode).

I'd hate to have a quality loss when converting them to use in Surge, simply so that they don't sound different.

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/issues/461 is the issue for >1024

2048 is easy. Evil's idea of 8192 is a problem since surge allocs max size on stack not actual size on stack so we would waste quite a bit of memory. Let me see if I can just recompile with 2048 and then close that issue. There's a few spots to check but not many. Since this issue is closed mind adding yourself as a listener (just subscribe or add a comment) on #461 and I'll close it over there.

**Comment by baconpaul** [comment]
Oh and thanks again for the input!

**Comment by baconpaul** [comment]
Hey let me ask one favor: Over on #461 can you do this

Take one of your Serum wavetables and just split it down to the 2048-sample 32-bit WAV wavetables. That is, just make the stems without the conversion or what not. Then put em in a directory and zip them up along with (say) what they sound like when you play them in serum in a fairly vanilla way as an MP3?

And if you want, include the Serum wavetable along with it.

Obviously only if you have redistribution rights for a wavetable.

But then attach that zip to the other issue and I can try and figure out what the gap is in the loader. Reading the code, the 1024 samples seems like a suggestion not a requirement....

Thanks!

**Comment by theofficialajyoung** [comment]
Can do! I'm off work in a couple hours, and I'll do that when I'm back at my computer.
