### ISSUE TITLE
Display issues for Subfolders in Wavetable Menu

### ISSUE THREAD

**Issue by theofficialajyoung** [surge-synthesizer/surge#873]
**Describe the bug**

I've noticed if you select any wavetable that is in a sub-folder, the list of sub-folders gets truncated to only show the folders up to and including the one selected. This makes it very difficult to browse through wavetables when sound-designing.

**To Reproduce**

Simply select a Wavetable that is located in a sub-folder.

**Expected Behavior**

To display all folders, regardless of selected wavetable. It makes browsing much easier.

**Screenshots**

Here are some examples of this happening:

1.
![Menu Issues 1](https://user-images.githubusercontent.com/33675880/57563197-9081ef80-7360-11e9-95e9-e4110a66f3cc.png)
![Menu Issues 2](https://user-images.githubusercontent.com/33675880/57563198-94157680-7360-11e9-8c42-b08fec698636.png)
2.
![Menu Issues 3](https://user-images.githubusercontent.com/33675880/57563203-ab546400-7360-11e9-9ec7-37677c2c0e39.png)
![Menu Issues 4](https://user-images.githubusercontent.com/33675880/57563205-ad1e2780-7360-11e9-82f3-d48928ddd0b3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Host: Reaper 5.977 64-bit, FL Studio 20.1.2 [build 887]
 - Surge 1.6.0 beta9 (May 1 2019 23:59:14) VST2 64-bit

**Comment by baconpaul** [comment]
See the same thing on my mac yup. Looking.

**Comment by baconpaul** [comment]
Ha well the world needs two prizes.

A prize for "wonderfully excellent and clear bug reports" which goes to you.

And a second prize for "far too clever code which causes dumb bugs" which goes to me.

Anyway this was just me being dumb. 3 line fix which I now have in place. Thank you very much for the excellent report. I'll sweep this at the same time as the wavetable one so an upcoming nightly should fix both.
