### ISSUE TITLE
Single-sideband modulation (AM/FM)

### ISSUE THREAD

**Issue by Kwurqx** [surge-synthesizer/surge#878]
**Single-sideband modulation (AM/FM)**
https://en.wikipedia.org/wiki/Single-sideband_modulation

Both AM and FM generate 2 sets of sidebands (to the "left" and to the "right"). Also "reflected" "negative" (phase inverted) sideband frequencies can interfere with the audible/resulting spectrum.

As the name implies: Single-sideband modulation generates just 1 of the 2 sidebands, as generated by AM/FM. Either the lower or the upper half.

I guess it could also be used as a frequency (band) shifter or exiter or suboscillator type effect.

**Comment by baconpaul** [comment]
Huh this is neat and I didn't know about it. But are you proposing we add this as a new effect class in effect routing? I'm not quite sure where you re imagining this would fit into the block diagram of the synth.

Thanks!

**Comment by Kwurqx** [comment]
Not an effect (though it could be there too). Pre-filter. As part of the oscillators/mixer/signal generation.

Lets first adress AM. In the mixer Ring (AM) section? Ideally an extra slider to control the upper/lower sideband mix/ratio. Or else a 3 state switch (lower/both/upper (but this would limit the potential).

Since FM is both in the FM2 and FM3, you could have similar sliders there (per interacting operator pair). Not sure where (in the GUI) to put these sliders for the 3 operator interaction in the FM matrix.

I don't know of ANY synth that has a similar feature. It's always just mirrored sidebands. In FM it would (also) impact the reflected sideband frequencies amplitudes.

**Comment by Kwurqx** [comment]
By the way: when talking FM, I generally mean "Yamaha-style" PM (Phase Modulation), which I guess is the Surge implementaion too. Not actual FM (Frequency Modulation). But as long as the carrier frequency is greater the 0 Hz, the difference is hardly relevant.

**Comment by mkruselj** [comment]
From what I read, you cannot really get single-sideband modulation without either filtering or phasing tricks. So essentially if you have a filter with cutoff matching the pitch of the note you're playing, and you use LP or HP, you get only one set of sidebands. Basically you can then already sorta do this in Surge... There doesn't seem a "natural" way of doing this without some sort of filtering or phase cancellation.
