### ISSUE TITLE
Reverb2 Presets 

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#881]
Only thing needed for R2 now is some presets and we are done!

-----------

Surge has a reverb2 effect (`fxt_reverb2`, value == 11) which is not in configuration.xml

Why? We should probably add it to configuration.xml and see what happens!

**Comment by baconpaul** [comment]
You can turn it on using this patch

```
diff --git a/resources/data/configuration.xml b/resources/data/configuration.xml
index c43c117..1a1895c 100644
--- a/resources/data/configuration.xml
+++ b/resources/data/configuration.xml
@@ -118,6 +118,10 @@
     <type i="10" name="Vocoder">
         <snapshot name="Init" />
     </type>
+    <type i="11" name="Reverb 2">
+        <snapshot name="Init" />
+    </type>
+
 </fx>
 <customctrl>
     <entry p="0" ctrl="41" />
```

It is not clear to me that the effect is fully working though.

**Comment by baconpaul** [comment]
Yeah if you apply that diff the effect works only the first time you select it. Doesn't survive swapping to a chorus then back. Sometimes dies a click/pop death; sometimes makes no reverb.

**Comment by esaruoho** [comment]
any chance @kurasu could let us know if this is some remnant of unfinished code, or...?

**Comment by baconpaul** [comment]
It actually looks like unfinished new code

1: it’s the last not first fx in the enum
2: itndoesnt uses as much sse2 hand crafting since we can trust compilers a bit more now
3: when it works it is way cooler than reverb 1

So my thesis is “unfinished new 16 feature”. 

Would love to hear tho yeah!

**Comment by baconpaul** [comment]
Got confirmation that my thesis is correct enough. So this is a new feature looking to be finished!

**Comment by baconpaul** [comment]
So @bytecrew is interested in helping here which is great! This is a nice isolated bit of DSP code to finish and improve the synth for everyone!

@bytecrew here's how I would do it

1.  Apply the patch above 
2. Build surge as an AU (`./build-osx.sh --build-validate-au`) and it will all install
3. Into ~/Documents/Surge/Test unzip this zip file which contains an FXP
[patch.zip](https://github.com/surge-synthesizer/surge/files/3221020/patch.zip)
4. Take a look at src/headless/main.cpp and see the main() which has commented out stuff. Make the routine run by main "playSomeBack"
5. Build and run headless (`./build-osx.sh --run-headless`)

At this point you should get a wav file of a DX sounding EP playing one of the goldberg variations dropped into /tmp/988-v05.wav

If that happens you are all good. If you edit the playSomeBach routine to use the patch name in the zip file rather than "DX EP" it will play into reverb2. You can debug with lldb or use the Xcode project which cmake ejected into the `build/Surge.xcodeproj` dir.

Good luck!

**Comment by baconpaul** [comment]
Re-upping this issue for 1.6.6 since now I have the unit test framework it should be pretty easy to address

**Comment by baconpaul** [comment]
Couple more notes:
Long pre-Decay and short reverb will have ringout bug
Aparent LF Damping does nothing
