### ISSUE TITLE
Moving certain sliders unintendedly changes assignable Ctrl modulation values

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#882]
Description:
In the VST3 version, changing certain parameters also unintendedly changes assignable Ctrl modulation values.

1. **Drag or scroll** on the Poly, Split Key, Master Volume, FX1 or FX2 return sliders. (There might be more, I don't know...)

Expected behavior:
The assignable MOD values should not change.

Setup:
 - OS: Win 10 x64
 - Host FL Studio 20.1.2 x64
 - Version: Surge 1.6.0 beta-9, but also happens on the latest nightly build.

Additional info:
- This only happens with the VST3 version.
- This occurs at any zoom level.
- The MOD values really change, it isn't just a GUI glitch.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/50145178/58384024-fdc19180-7faa-11e9-96af-f5f3d9df0ccd.gif)

**Comment by baconpaul** [comment]
Oh thank you. What an excellently written bug report. Appreciated!

Out of curiosity do you have access to another daw and does this also happen there?

**Comment by VincyZed** [comment]
I just tried in Savihost, a really lightweight (and kinda buggy) VST3 host, yet strangely it does not happen.

**Comment by baconpaul** [comment]
Cool

Problems like this have occurred when hosts get co fused about parameters sometimes so that is useful info. I’ll try bitwig mac and win also and take a look. But not now. The sun is shining and the sky is blue here :)

**Comment by baconpaul** [comment]
Well the sun went in but I got some time outside before it did.

Bitwig Mac VST3 shows the same behavior. Should be pretty easy to figure out why.

**Comment by baconpaul** [comment]
OK I found it. I had carried over a thing from VST2 which isn't needed with the way VST3 does midi. Simple fix once I saw it. 

Will do a pull request now. Would you be up to trying a nightly when the build to see if it fixes it?

**Comment by VincyZed** [comment]
Yup, I'm up for it!
