### ISSUE TITLE
Zoom fails VST2 and VST3 Windows Cakewalk

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#885]
Cakewalk by BandLab, VST3, as reported in #816. Basically doesn't send the right size to ::onSize after you call IPlugFrame->resizeWindow. For now I disabled zoom in Cakewalk.

**Comment by baconpaul** [comment]
Link to #938

**Comment by baconpaul** [comment]
As reported on KVR: Fyi, Surge 1.6.1.1 VST2 still has zoom enabled in Cakewalk, and that fails to zoom properly also.

**Comment by baconpaul** [comment]
Even though this problem is still here, the KVR user who reported it notes that the new “set default zoom” menu item allows him to work around the problem. So I’m going to bump this one to 1.6.3 along with the other outstanding zoom issues.

Only Tracktion has a non-workaround right now

**Comment by mkruselj** [comment]
@baconpaul I wonder if @Kingston1's zoom tweaks actually helped with this one too...

**Comment by baconpaul** [comment]
Probably! Along with cdb upgrades too. Have you tried it?  I am also happy to just close and see if new reports trickle in so I’ll do that

**Comment by mkruselj** [comment]
I didn't try it, but I guess I should if nothing just to verify if there are any Cakewalk issues left that are valid...
