### ISSUE TITLE
MPE Status stored in patch

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#890]
currently if MPE is enabled and saved in a project Surge will open with MPE disabled

would it be possible to have a setting in SurgeUserDefaults.xml

similar to

`<default key="mpeEnabled" value="1" or "0">` 

so that if MPE is set to enabled in a project it will open with the MPE feature enabled

**Comment by tank-trax** [comment]
not sure if this is feasible
 
for example if a project has multiple instances of Surge it could be that one track may use Surge with a preset having MPE enabled and another track with a preset having MPE disabled

**Comment by baconpaul** [comment]
Yeah totally feasible but requires us to store mpe status in a patch so I want to wait until after 1.6.0. Also can’t you use an rpn midi message to do this today out of curiosity?
