### ISSUE TITLE
In _fx mode the VST2 doesn't receive midi

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#893]
@williamfields reported In #859 that the VST2 when renamed _fx with 1.6.0 ignores midi events. With 1.5.* it doesn't

(these are some notes to myself)

The problem it seems is midi events are ignored. It looks like this may be because wantEvents() isn't called but the canDo seems it would do that even in fx mode if you look in audioeffectx.cpp. 

So to debug this here's what I would do

1. Try calling isSynth() in the _fx block and see if that just fixes it
2. If that doesn't make sure the canDo("receiveVstMidiEvent") is getting called properly
3. If still broken then debug the hard way

@williamfields to do that I need just a couple more bits of info

1. I know you are windows but are you 32 or 64?
2. How do you set up an fx in reaper to get midi input? Assume I know zero reaper. Do you have a surge-only reaper file you can attach?

Thanks!

**Comment by williamfields** [comment]
I am using the 32-bit version.

To reproduce, you only need to drag an instance of Surge VST onto a channel, draw some MIDI notes and hit play.

I created and attached a REAPER project with two tracks that are identical, except one is using surge.dll and one is using surge_fx.dll. 

[surge-example.zip](https://github.com/surge-synthesizer/surge/files/3248551/surge-example.zip)

As you can see only the VSTi version is making sound:

![image](https://user-images.githubusercontent.com/9380730/58817963-fe85a380-85fa-11e9-830f-af960d40ab97.png)

Thanks!

**Comment by baconpaul** [comment]
Linking this to #1005

**Comment by baconpaul** [comment]
We spent some time looking at this, and concluded it was an ambiguity in version of the VST2 library leading to these various problems, but at the same time, with the 1.6.5 release which we will ship this week and the current nightly, we made the VST3 work as a fully functioning audio processing synth in reaper, cubase, and other VST3 hosts, so I’m going to close this issue and encourage you to try the VST3 nightly or (mid next week) 1.6.5 release.

The VST2 _fx midi will not be something we are going to fix for a variety of reasons, alas.

**Comment by williamfields** [comment]
No problem. This will work for me. Thanks!
