### ISSUE TITLE
osc_sine modes

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#896]
The sine oscillator is pretty straight forward. Be a sine. No parameters other than pitch.

But I was reading the yamaha TX81Z manual (for a different reason) and it reminded me that a lot of synths got really far by truncating, frequency doubling, or quadrant shuffling sine waves. Take a look at this picture for instance.

<img width="538" alt="Screen Shot 2019-06-03 at 10 51 20 AM" src="https://user-images.githubusercontent.com/13387561/58811370-ad22e780-85ed-11e9-8b89-fe35f5bd4fc3.png">

So I propose to add a "mode" parameter to sine which does various truncations and transformations like that picture and like other obvious extensions (like truncate quadrants 2 and 4; or 1 and 3 and stuff).

**Comment by esaruoho** [comment]
awesome. can't wait to try this out!

**Comment by baconpaul** [comment]
They are in 1.6.1.1 on the website or in home brew now!
