### ISSUE TITLE
More zoom issues with Surge (VST3)

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#898]
**Bug description**
Since the 1.6.0 release, there is a weird behavior regarding zoom in the VST3 version again.

**Steps to reproduce the behavior:**
Pretty complicated to explain. Just look at the GIFs below.

**Setup:**
 - OS: Windows 10 64 bit
 - Host: FL Studio 20.1.2 x64
 - Happens from Surge 1.6.0 to the latest nightly.

So here's what happens **EVERY TIME** I load Surge on 100% zoom:
![Add_Surge_100%_Zoom](https://user-images.githubusercontent.com/50145178/58997819-4d366780-87cc-11e9-881d-98edffe34fbb.gif)
Here, on 100%, the zoom option is there in the menu. (Setting it to 125% after that works great).

So here's what happens **SOMETIMES** when I load Surge on 125% zoom (it took 6 times before this happened, it's very random):
![Add_Surge_125%_Zoom](https://user-images.githubusercontent.com/50145178/58997899-88d13180-87cc-11e9-8ee4-f2a00676eccb.gif)
As you can see, here on 125%, it looks like it loads it at 100% instead, and the zoom option IS NOT present in the menu (See image below).
![Bug_No_Zoom_Menu](https://user-images.githubusercontent.com/50145178/58998195-989d4580-87cd-11e9-95fa-35c77fa170e8.png)

I'm not quite sure, but this seems to be caused by the fix for the initial zoom dance thing. (Thanks for fixing that, btw 😁)

**Comment by baconpaul** [comment]
Oooh the zoom menu not being there is a real hint. I suppress zoom in hosts that don't support it and that kills the zoom menu. I wonder if my initialization path for that suppression is bad. Thank you for the accurate report. I'll look in the morning.

**Comment by baconpaul** [comment]
Aww darnit yeah. My "fix" for cakewalk broke this because my memory is uninitialized. I just never set disableZoom to anything if you aren't cakewalk so you get rando memory.

More soon....

**Comment by baconpaul** [comment]
Hmm ... so I can't reproduce it but my zoom enablement is clearly uninitialized. Let me look at the rest of the code too. I fear my VM may act different with uninitialized memory than your box of course.

**Comment by baconpaul** [comment]
Aww damnit. Spot the bug:

```
#if TARGET_VST2   
   CRect wsize(0, 0, WINDOW_SIZE_X * fzf, WINDOW_SIZE_Y * fzf);
#else
   CRect wsize( 0, 0, WINDOW_SIZE_Y, WINDOW_SIZE_Y );
#endif
  ``` 

new nightly coming in a second.

**Comment by VincyZed** [comment]
Fixed. Thanks a lot! 😃

**Comment by baconpaul** [comment]
Awesome
