### ISSUE TITLE
Standalone Surge

### ISSUE THREAD

**Issue by jsakkine** [surge-synthesizer/surge#90]
For easy debugging with GDB etc., a standalone Surge would be awesome.

**Comment by baconpaul** [comment]
I agree!

**Comment by jsakkine** [comment]
I guess you still can use VSTGUI to create the UI but I guess the biggest open in this is what to use for interfacing with audio. Should be a

- a cross platform library
- easy to compile in rather than use as  DLL.

I've heard that this is fairly popular choice but have not done any further analysis on it: http://www.portaudio.com/

**Comment by baconpaul** [comment]
Rack uses rtaudio and that works well too. https://www.music.mcgill.ca/~gary/rtaudio/

If I were writing a stand-alone I would write it as a “fourth host” - side by side with au vst and vst3. Probably some ui code to bootstrap the vst GUI into a container like I did with the cocoa port then wrap the render method into one of the portable audio libraries. 

I don’t plan to do this soon but would be happy to review or pitch in if you get it started

**Comment by baconpaul** [comment]
Yeah I've cobbled together a logger so that I can use printfs when I'm inside AULab and see them but it's not ideal. A standalone would be sweet.

src/standalone here we come! Look forward to seeing what you come up with.

**Comment by baconpaul** [comment]
Oh and if you are interested, when I was debugging my VCV Rack plugins I wrote a little standalone thing which uses rtaudio to load my underlying oscillator and play it without requiring the whole UI and rigamarole. 

https://github.com/baconpaul/BaconPlugs/tree/master/standalone

the standalone_helper.hpp shows you what you need to use rtaudio to pull and output sound.

Hope that helps!

**Comment by jsakkine** [comment]
Thanks! Yeah, rtaudio looks like a good fit and can be compiled as a static library. I'll look into your previous works. Thank you.

**Comment by esaruoho** [comment]
loox like progress on this started at PR #96

**Comment by jsakkine** [comment]
Actually, maybe I'll close my PR now and hold up until those are merged? Maybe get more stuff while at it. I'll do a new one once the mainline is updated.

**Comment by baconpaul** [comment]
OK great. Thanks!

Also, if you pull that branch (so you grab all those commits) quite a few small bugs here and there will get fixed. Don't know how many impact your project but may be a help.

**Comment by baconpaul** [comment]
Hi! #92 got merged so if you repull master you will have the latest greatest as a starting point!

**Comment by jsakkine** [comment]
Great. Today busy with work but probably tomorrow continue with this :)

**Comment by jsakkine** [comment]
Anyway, rebased my tree

**Comment by baconpaul** [comment]
I know we just have stubs for the standalone now, but I did notice that vstgui in vst3sdk has a standalone directory which includes examples.

If that helps.

**Comment by jsakkine** [comment]
@baconpaul, I think once the VST2 plug-in starts working, this should be easy. Same goes for VST2. My priority order is: VST2, VST3 and standalone.

**Comment by baconpaul** [comment]
Yeah agree. Just recorded it for posterity since I saw it. Tbh the hosting au program means I don’t really need it on Mac at all but a nice to have in the future perhaps

**Comment by jsakkine** [comment]
@baconpaul, in future could the AU plug-in code catch SurgeError and display the dialog that is now in SurgeStorage.cpp (low priority)?

**Comment by baconpaul** [comment]
Yeah let’s make an issue for that. It’s way cleaner

**Comment by jsakkine** [comment]
I would suggest removing the work that has been done as we now have the headless version and close this issue.

We can bring this back on the table when there is actual motivation to work on it.

To close this I'll remove the current app target.

**Comment by baconpaul** [comment]
Agree completely. Kill app pull and close thisissue
