### ISSUE TITLE
All instances of Surge load to init preset in Cakewalk 

### ISSUE THREAD

**Issue by fyrebreak** [surge-synthesizer/surge#910]
All custom patches of Surge I created in Cakewalk have been reset to all init presets unintentionally. More details below.

Steps to reproduce the behavior (Might happen unpredictably as well, not sure):
1. Create a project, with perhaps 5 instances of Surge. Customize them and alter their settings. Click 'Save a Copy' in Cakewalk to save multiple copies of projects in the same folder as such: 
![image](https://user-images.githubusercontent.com/33426270/59549086-09d9b700-8f8b-11e9-86b8-e91635ccf3e1.png)

2. _Sequence of events: I froze all tracks to save CPU power, switched audio drivers from MME to ASIO, created another audio track and recorded guitar. I then saved the copy and closed Cakewalk._

3. Open project again and unfreeze Surge instances. All should load init presets only, instead of the custom patches you made as expected.

Note: This init issue is not only experienced with Surge, in Cakewalk. Other plugins like Orilriver also fail to load user-created presets and instead reverts back to the init preset when loaded up again, but this time even when multiple projects are _not_ saved in the folder. I'm not sure if this is related but it could be a clue. Hopefully this information might help.

 - OS: Windows 10 
- Host: Cakewalk by Bandlab 
 - Version: 2019.05, build 31

Orilriver: https://www.kvraudio.com/product/orilriver-by-denis-tihanov

**Comment by baconpaul** [comment]
Thank you. It sounds like freeze/unfreeze isn't streaming onto the preset state when it unfreezes.

Could you show me how to freeze and unfreeze a track in this DAW? I don't know how.

I have a few weeks of travel so am going to have a bit of a pause on surge but will look at this this summer for sure. Thank you for the clean report.

**Comment by fyrebreak** [comment]
Sure! Just click on the snowflake beside the track as such:
![image](https://user-images.githubusercontent.com/33426270/59550752-15d07380-8fa1-11e9-856d-b12063cb9dc3.png)
The audio clips should be highlighted in light blue, and an audio waveform should be visible.

**Comment by baconpaul** [comment]
Great thanks. And: You are using the surge VST2 or 3? And are you using 1.6.1.1?

**Comment by fyrebreak** [comment]
Currently VST2 and 1.6.0 :p

**Comment by baconpaul** [comment]
OK! Well you should grab 1.6.1.1 - fixes a couple of bugs and reduces memory usage (and also adds cool new waveforms in the sin oscillator). But it won't fix this problem here.

**Comment by fyrebreak** [comment]
That’s neat! I’m all for new waveforms and increased stability. I’ll go ahead and give this a shot. 

~~Got scared at first for my computer detecting the download as malicious software... haha~~

**Comment by mkruselj** [comment]
@fyrebreak Is this issue still happening for you in CbB?

**Comment by fyrebreak** [comment]
Issue no longer happening with current versions of CbB and nightlies, will close.
