### ISSUE TITLE
Zoom state of Surge VST3 gets lost after reopen

### ISSUE THREAD

**Issue by mireiner** [surge-synthesizer/surge#912]
**Describe the bug**
GUI zoom states higher than 100% get lost after reopen Surge VST3.
Surge VST2 works fine (does remember zoom state after reopen)!

**To Reproduce**
1. In Surge VST3 go to Menu/Zoom/Zoom to 150%
2. Close Surge GUI
3. Reopen Surge GUI
4. Now Surge GUI is set back to zoom 100%

**Expected behavior**
After Surge VST3 is reopened it should remember its zoom state (for example 150%)

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional 64 Bit Version 1803
 - Host: Presonus Studio One 4 Professional v4.5.1 64 bit
 - Surge VST3 Version: 1.6.1.1 VST3 64 bit
-  Surge-NIGHTLY-2019-06-15-546f9ea VST3 64 bit

**Comment by baconpaul** [comment]
Thanks for the accurate report and sorry for the bug. This behavior must have reverted when we fixed the opening “zoom dance” in the betas.

I’m taking a few week break from surge starting mid week - if this is easy to fix I will try and get it in a nightly but if not I can definitely fix it this summer

**Comment by baconpaul** [comment]
Just FYI: This also occurs Bitwig / Mac so it is definitely a VST3 wide problem. Just adding this note in case I don't get it this evening!

**Comment by baconpaul** [comment]
Yup this feature got lost when I did the zoom-dance-fix 

Anyway I have just swept a correction. If you want, grab a nightly and you will have 1.6.1.1 plus this fix. We will do a 1.6.2 later this summer with this fix in place. Thank you for the bug report.

If you could confirm the nightly fixes it for you I would appreciate it. If it does please add a comment and close the issue.

Thank you!

**Comment by mireiner** [comment]
Hi Paul,
the new nightly build "Surge-NIGHTLY-2019-06-16-a0564ae-Setup.exe" for Windows 64bit fixed the problem (VST3 didn't lose the zoom state on reopen anymore).
But I found another problem. If the actual project inside the DAW is closed and reopened then Surge still loses its zoom state (open with zoom 100%). And this does happens with Surge VST2 and VST3 64 bit v1.6.1.1 and latest 2019-06-16 nightly version on Windows 10 with Presonus Studio One v4.5.1 64 bit.

**Comment by baconpaul** [comment]
Yeah that’s always been the case but I can fix it now we shipped 16. I didn’t change the patch format at all until this point which is required for inter session. I’ll open a separate issue and close this one to track. Thanks!!!
