### ISSUE TITLE
Tunings issue Linux - no file explorer

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#917]
using Linux Debian Stretch tested on a local build and Surge-linux-x64-NIGHTLY-2019-06-16-ba855b9

when clicking on `Menu >> Tunings (Experimental) >> Apply .scl file tuning`

the file explorer does not appear so there is no way to select the .scl file

note: I tested it in WINE and noticed `Apply .kbl file mapping` indicated not supported yet
in Linux there is no warning either

**Comment by baconpaul** [comment]
Yeah this is basically more of “user interactions isn’t written”

I think I will do the gross zenity fork thing for now and if there’s a user that really offends its an open code base :)

**Comment by baconpaul** [comment]
Linking this with #637 and and #562
