### ISSUE TITLE
Linux file explorer

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#923]
currently Zenity is capable of selecting files for alternate tunings, simple request if KDialog could be used in KDE as an alternative file selector

also wondering for other Linux users if there are not other default file managers, or if there is a way to call the default, for example XFCE, Gnome, KDE, Mate and Cinnamon have other choices

also wondering the relationship between file managers and file selectors

File selectors for KDE include Zenity and KDialog. File managers (that appear to drive the file selection process) in XFCE are Thunar and Nautilus. In Cinnamon the default is Nemo or Files.

desktop integration is not a feature of the Linux OS but each desktop does have an integrated default file browser, wondering if that would work across different DE's in Linux

**Comment by baconpaul** [comment]
The entire question here is "is there an API I can call to pop a file open dialog using the correct thing"

for url open, freedesktop.org provided xdg-open which I use with a URL to open a folder or a web page natively.

I do not believe there is such an API from the command line for these functions.

But if we have a clean answer to that question we can call anything we want. Code is simple as pie.

**Comment by tank-trax** [comment]
after consideration, not a real priority as Zenity is more than adequate

**Comment by baconpaul** [comment]
OK cool let me close this then!
