### ISSUE TITLE
sevish-tunings-pack does not load in Linux

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#924]
when trying to load any SCL files from the [sevish-tunings-pack-v1.1.zip](https://sevish.com/musicmakingstuff/sevish-tunings-pack-v1.1.zip)

will produce error

![scl only png](https://user-images.githubusercontent.com/41337033/59888974-21081280-9398-11e9-8a15-dcb037835f3d.jpg)

it works when loaded in the Windows VM so appears to be isolated to Linux

**Comment by baconpaul** [comment]
Oh the problem is file names with spaces in them with the way I fork and popen zenity. Basically the file name is truncated at the space.

**Comment by baconpaul** [comment]
Anyway fix inbound. Thanks for the great bug report as always!

**Comment by tank-trax** [comment]
taking away the space is not enough, it looks like some kind of white space or non-breaking space within the file

If I build them here https://sevish.com/scaleworkshop/ they can load

this file can load
[BagpipesBulgaria.scl.zip](https://github.com/surge-synthesizer/surge/files/3312619/BagpipesBulgaria.scl.zip)

this file can't

[BulgarianBagpipe.scl.bad.zip](https://github.com/surge-synthesizer/surge/files/3312624/BulgarianBagpipe.scl.bad.zip)

**Comment by tank-trax** [comment]
yep all good now, thanks!
