### ISSUE TITLE
incorrect icons for switching patch

### ISSUE THREAD

**Issue by joelsinnott** [surge-synthesizer/surge#926]
Minor detail, but I feel the - and + icons dont apply to switching between patches. Back and foreward arrows would make much more sense in this context since I'm not adding or removing anything.

Cheers!

**Comment by baconpaul** [comment]
Thanks; that's a really good point!

@itsmedavep is it hard to swap those around for a 1.6.2 (which will probably be August timescale looking at schedules right now).

**Comment by itsmedavep** [comment]
Super easy. Ill knock this out while your on vacation!

**Comment by baconpaul** [comment]
Thanks!!

**Comment by itsmedavep** [comment]
https://github.com/surge-synthesizer/surge/pull/933

**Comment by baconpaul** [comment]
@joelsinnott we just swept new icons in the above PR so the nightly should have it in an hour or so, and the next release this summer will have the fix. Thanks for the suggestion!
