### ISSUE TITLE
FR: Increase range of pitch modulation

### ISSUE THREAD

**Issue by RCJacH** [surge-synthesizer/surge#934]
Currently the maximum semitones that can be modulated for the Oscillator Pitch slider is +-14 semitones, then another +-14 for the Scene Pitch. However when doing sound design for percussive instruments, such as kick and snare, 28 semitones might not be enough to create the initial transient. It would be nice if the range of pitch modulation of each oscillator itself expand to +-48 semitones.

**Comment by baconpaul** [comment]
Right mouse on the slider and choose extend range
Does that do it? Should give you +-72 tones or so

**Comment by RCJacH** [comment]
Thanks. I feel stupid cause I was reading this update with excitement few months ago, and now forgetting this implementation.

That aside, I realized a new bug. I'll close this and open a bug report.

**Comment by baconpaul** [comment]
Thanks!
