### ISSUE TITLE
Bug Report: Leftward motion beyond min value in modulation jumps to max value

### ISSUE THREAD

**Issue by RCJacH** [surge-synthesizer/surge#935]
Windows 64, surge built jun 9 2019.

This occurs during modulation assignment of any modulator, when moving the modulating parameter on GUI with mouse holding left button, upon exceeding the minimum value of a modulation amount by moving mouse leftward, the modulating amount value jumps to the maximum, and further leftward movement will decrease the value from the maximum, and re-triggering this behavior when the current value falls below the minimum again.

This behavior does not occur when moving sliders outside of modulation assignment mode.

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/blob/d6de8aed3e47a01da676059c69f06beb24b0272e/src/common/gui/CSurgeSlider.cpp#L323

Looks like restmodval is computed differently than modval so I will look there first. 

Thanks for the clear report. I’m on a short break from development but will look at this in July for sure.

**Comment by baconpaul** [comment]
Reproducible on MacOS in the AU also. Looking now.

**Comment by baconpaul** [comment]
Yup it was that restval indeed. Fix forthcoming. Thank you for the report! The nightlies should have a fix in a couple of hours.
