### ISSUE TITLE
Zoom fails VST2 Linux Reaper

### ISSUE THREAD

**Issue by Fourstepper** [surge-synthesizer/surge#937]
**Describe the bug**
The GUI doesn't render completely after plugin scaling (zooming) capabilities are initiated  

**Please let us know your surge version**
This information is all in the menu/about screen

* Surge Version: 1.6.1
* Plugin type: VST2 under Linux 64bit, kernel version 5.1.15-1

**To Reproduce**
1. Open Surge as a VST2 in Reaper
2. Click on Menu > Zoom 150%

**Expected behavior**
A clearly and fully loaded scaled GUI

**Screenshots**
https://imgur.com/a/7fkbTco

**Desktop (please complete the following information):**
 - OS: Linux Manjaro
 - Host: Reaper
 - Version: Reaper 5.79 (latest)

**Additional context**

**Comment by baconpaul** [comment]
Link to #938. Thanks for the report!

**Comment by baconpaul** [comment]
@Fourstepper this is "really hard" to fix with the vst2 but in the upcoming 1.6.2 release, I have the VST3 working with Reaper on Linux. Presuming I get all the bugs sorted out in VST3 linux reaper (there's only one left) and the vst3 builds from source and ships in the deb, any reason that wouldn't work for you?

(The reason it is really hard to fix is that there is no VST2 zoom API and on X, the window size / parent API is way trickier than in other places; VST3 has a zoom API and zoom in reaper linux vst3 works fine).

**Comment by Fourstepper** [comment]
Hello @baconpaul, thank you for reviewing my issue and for the upcoming fix. The solution you have presented totally seems good to me, thank you.

Best regards and good luck!

**Comment by baconpaul** [comment]
OK great. I will update this issue when the VST3 is testable in the nightlies and working in reaper linux fully for me. (Right now it works and zooms fine for us, but has a crash on exit occasionally I need to resolve; also it is not in the deb distribution).

**Comment by Fourstepper** [comment]
Wicked. Thanks a lot!

**Comment by baconpaul** [comment]
OK cool the crash on exit fix was easy as was the .deb file change. If you build from source at current master or grab the nightly deb from the website and install, you should get a /usr/lib/vst3/Surge.vst3 which will load and zoom and generally work great in linux reaper.

Please feel free to reopen this issue or add a comment here if not; or confirm if it does if you want.

THanks
