### ISSUE TITLE
Master Issue for Hosts which don’t Zoom Properly

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#938]
There’s a smattering of hosts which don’t zoom properly. They have their own tickets but I want them all in one place so I will tag this issue with a link to them.

**Comment by herodotas** [comment]
Renoise do not support vst3, only vst 2.4

**Comment by baconpaul** [comment]
Thanks! Edited the title.

**Comment by gnips** [comment]
Helm is open source ( https://github.com/mtytel/helm ), and zoom works fine in Cakewalk.
Can that be any help?

**Comment by baconpaul** [comment]
Thank you! I will look at it and see what they do. Very useful

**Comment by gnips** [comment]
Just a note regarding Cakewalk:
Using a zooming host, I zoom surge to prefs. and set as default zoom.
When I open surge in cakewalk, it's zoomed correct to that zoom.

**Comment by baconpaul** [comment]
Ahh that’s good to know. I changed the initial zoom process right before 1.6.0 in a way that “doesn’t zoom” to the initial size. Wonder if I can use a similar trick to force the resize. Thank you!

**Comment by gnips** [comment]
Don't thank me, Thank You! I'm just testing all your work.
It also works with vst3 version. Not fixed but a good work-around.
