### ISSUE TITLE
Chan. AT rename

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#960]
![image](https://user-images.githubusercontent.com/2393720/61237913-d467eb00-a73b-11e9-89f8-8de1db70888d.png)

I think there's enough room to just write out fully "Channel AT", no need for shortening?

**Comment by baconpaul** [comment]
<img width="260" alt="Screen Shot 2019-07-17 at 8 00 01 AM" src="https://user-images.githubusercontent.com/13387561/61373850-e7c4a480-a868-11e9-8947-cebe36610c79.png">

Indeed there is. Pushing now.
