### ISSUE TITLE
LFO visualisation improvement

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#969]
There's been one thing with the LFO visualisation that has been bugging me for a while now.

![image](https://user-images.githubusercontent.com/2393720/61510058-9c89cd80-a9f1-11e9-858b-7d12b77eb3cb.png)

1. with long envelope times (particularly delay, attack, hold stages) you see practically nothing in the visualisation
2. there's no way to see the release stage, ever

Both of these things make no sense considering the amount of GUI that this visualisation is taking up, so my proposal here would be:

1. Always draw the envelope rescaled so that it fits into the alloted area for the LFO waveform - this means that increasing or decreasing one stage would shift other stages inversely, so that everything fits in one screen
2. Add a little visualisation at the bottom for note on (arrow down) and note off (arrow up), so that release stage can be drawn after arrow up marking - a good example of this is in Massive X:

![image](https://user-images.githubusercontent.com/2393720/61510092-c216d700-a9f1-11e9-9066-b5b75e033987.png)

The best example of this way of envelope scaling I found in old Massive, see GIF:

![massive env](https://user-images.githubusercontent.com/2393720/61510296-8af4f580-a9f2-11e9-8bb0-8abbc1f899ea.gif)

**Comment by baconpaul** [comment]
![FinalTicks](https://user-images.githubusercontent.com/13387561/61543761-1762e080-aa12-11e9-9562-a3b3e1905be5.gif)
