### ISSUE TITLE
A MSEG window for LFO modulations (sort of an extended step sequencer)

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#982]
Right now the step sequencer is a regular grid piecewise continuous output signal. That’s what step sequencers do so that is fine.

But chatting with @itsmedavep and @mkruselj about “custom LFOs” we realized that the step sequencer could also be repurposed to be much more expressive if you add the following features

1. Start time of a step is no longer 1/16 * i but is rather user selectable (and of course a UI gesture could re-regularize it
2. As well as piecewise continuous connectors, you could also use piecewise linear, parabolic with a control point and s-curve with a control point.

So tossing this in as an issue so we remember the conversation.

**Comment by mkruselj** [comment]
A good implementation of this would be a multi-segment envelope type of thing from Zebra 2. Here's a screenshot of how that looks and pages from the manual that list all the features they can do.

![image](https://user-images.githubusercontent.com/2393720/62303347-3c2c6e80-b47c-11e9-9267-e660dcd5ebec.png)

![image](https://user-images.githubusercontent.com/2393720/62303374-477f9a00-b47c-11e9-88fa-7e570a7aaa97.png)

![image](https://user-images.githubusercontent.com/2393720/62303378-4a7a8a80-b47c-11e9-866e-0318510c576f.png)

**Comment by baconpaul** [comment]
I'm gonna bounce this until after 1.6.2 if that's OK with you all. Just trying to prune the list a bit of things I don't think I'll get to in the next 4-6 weeks.

**Comment by mkruselj** [comment]
https://www.arthurcarabott.com/mui-envelope/

**Comment by baconpaul** [comment]
<img width="586" alt="Screen Shot 2020-08-06 at 8 21 55 PM" src="https://user-images.githubusercontent.com/13387561/89595780-6f3dd680-d823-11ea-98f4-5da446bf2404.png">
<img width="1051" alt="Screen Shot 2020-08-06 at 8 22 29 PM" src="https://user-images.githubusercontent.com/13387561/89595784-71a03080-d823-11ea-829d-fbb782a8c687.png">
![emsg](https://user-images.githubusercontent.com/13387561/89595793-77961180-d823-11ea-8c7c-9215fdf9875b.gif)

So you can see where I'm going

that's `baconpaul/mseg-part-one`
lots to do
but totally doable for 1.7.2

**Comment by baconpaul** [comment]
OK so this is headed, in a gross unacceptable alpha stage, into the nightlies now. I'm going to open up a separate issue for the book of work to get it production ready.

**Comment by mkruselj** [comment]
I think since we have MSEG Design and book of work issues, we can close this one?
