### ISSUE TITLE
Do we want to show modulation in the OSC

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#996]
We keep chatting about this. I think we probably don't but I prototyped it.

![ModBetter](https://user-images.githubusercontent.com/13387561/62622097-8df54e80-b8eb-11e9-9173-d2e56bcf3ea7.gif)

I'm gonna push my branch against this issue but not merge it while we think about if we want to do this.

**Comment by esaruoho** [comment]
I wants it :)

**Comment by baconpaul** [comment]
Ha yeah! It's not uncontroversial though - it's a bit busy. I was gonna as @itsmedavep to think about some colors or display options when he's back from his vaca and leave this parked here until then.

**Comment by baconpaul** [comment]
![EYECANDY](https://user-images.githubusercontent.com/13387561/62630042-3dd2b800-b8fc-11e9-94df-bed8e94cac1e.gif)

thoughts on this one?

**Comment by VincyZed** [comment]
> ![EYECANDY](https://user-images.githubusercontent.com/13387561/62630042-3dd2b800-b8fc-11e9-94df-bed8e94cac1e.gif)
> 
> thoughts on this one?

Love this one, really good!

**Comment by VincyZed** [comment]
Possible bug, maybe intended, but the blue oscillator preview doesn't seem to work when modulated from SLFOs, Modwheel, Pitchbend, or ChannelAT.

**Comment by baconpaul** [comment]
Oh duh yeah I just forgot those modulators. Reopening.
